Repository brain-tec/odoo, pull requests merged in 2019-07, with the labels that each got.

#4672 Syncing from upstream odoo/odoo (11.0)
  addons/purchase/models/stock.py
  addons/purchase/tests/test_stockvaluation.py
Labels: 11.0

#4673 Syncing from upstream odoo/odoo (12.0)
  .tx/config
  addons/account_voucher/models/account_voucher.py
  addons/mail/models/mail_template.py
  addons/website/models/__init__.py
  addons/website/models/res_config_settings.py
  addons/website/models/res_lang.py
  addons/website/tests/test_qweb.py
  addons/website/tools.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/tools/misc.py
Labels: 12.0

#4675 Syncing from upstream odoo/odoo (saas-12.2)
  addons/hr_contract/models/hr_contract.py
  addons/pos_cache/static/src/js/pos_cache.js
Labels: saas-12.2

#4676 Syncing from upstream odoo/odoo (saas-12.3)
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/pos_hr/static/src/js/screens.js
Labels: saas-12.3

#4677 Syncing from upstream odoo/odoo (saas-12.4)
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/lib/sha1.js
  addons/point_of_sale/views/point_of_sale.xml
  addons/pos_hr/models/__init__.py
  addons/pos_hr/models/hr_employee.py
  addons/pos_hr/static/src/js/gui.js
  addons/pos_hr/static/src/js/models.js
  addons/pos_hr/static/src/js/screens.js
  odoo/addons/base/models/res_users.py
  odoo/models.py
Labels: saas-12.4

#4678 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/hr_contract/models/hr_contract.py
  addons/pos_cache/static/src/js/pos_cache.js
Labels: staging.saas-12.2

#4681 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/hr_contract/models/hr_contract.py
  addons/pos_cache/static/src/js/pos_cache.js
Labels: tmp.saas-12.2

#4684 Syncing from upstream odoo/odoo (10.0)
  addons/account/models/partner.py
  odoo/addons/base/ir/ir_http.py
Labels: 10.0

#4685 Syncing from upstream odoo/odoo (11.0)
  odoo/addons/base/ir/ir_http.py
Labels: 11.0

#4686 Syncing from upstream odoo/odoo (12.0)
  addons/point_of_sale/wizard/pos_payment.py
  odoo/addons/base/models/ir_http.py
Labels: 12.0

#4688 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/addons/base/models/ir_http.py
Labels: saas-11.3

#4689 Syncing from upstream odoo/odoo (saas-12.2)
  odoo/addons/base/models/ir_http.py
Labels: saas-12.2

#4690 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/scss/fields.scss
  odoo/addons/base/models/ir_http.py
Labels: saas-12.3

#4691 Syncing from upstream odoo/odoo (saas-12.4)
  addons/uom/data/uom_data.xml
  addons/uom/models/uom_uom.py
  odoo/addons/base/models/ir_http.py
Labels: saas-12.4

#4692 Syncing from upstream odoo/odoo (saas-14)
  odoo/addons/base/ir/ir_http.py
Labels: saas-14

#4693 Syncing from upstream odoo/odoo (saas-15)
  odoo/addons/base/ir/ir_http.py
Labels: saas-15

#4700 Syncing from upstream odoo/odoo (10.0)
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
Labels: 10.0

#4701 Syncing from upstream odoo/odoo (12.0)
  addons/base_import/models/base_import.py
Labels: 12.0

#4703 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/addons/base/models/ir_mail_server.py
Labels: saas-11.3

#4704 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/js/views/basic/basic_renderer.js
  addons/web/static/tests/views/form_tests.js
Labels: saas-12.3

#4705 Syncing from upstream odoo/odoo (saas-12.4)
  addons/crm/models/res_partner.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
Labels: saas-12.4

#4706 Syncing from upstream odoo/odoo (saas-14)
  addons/account/models/partner.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: saas-14

#4711 Syncing from upstream odoo/odoo (staging.10.0)
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  odoo/addons/base/ir/ir_http.py
Labels: staging.10.0

#4718 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  odoo/addons/base/ir/ir_http.py
Labels: tmp.10.0

#4720 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/partner.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/editor/summernote.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: 11.0

#4721 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/models/partner.py
  addons/account/report/account_aged_partner_balance.py
  addons/account/wizard/account_invoice_send_views.xml
  addons/google_account/i18n/google_account.pot
  addons/google_account/models/google_service.py
  addons/hr_holidays/report/hr_holidays_reports.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/point_of_sale/static/src/js/models.js
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/tools.py
  addons/website_form/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/views/sale_order_views.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: 12.0

#4723 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/partner.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_discount/static/src/js/discount.js
  addons/purchase/models/stock.py
  addons/purchase/tests/test_stockvaluation.py
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/web_editor/static/src/xml/editor.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: saas-11.3

#4724 Syncing from upstream odoo/odoo (saas-12.2)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_geolocalize/models/res_partner.py
  addons/hr/views/hr_views.xml
  addons/web/static/src/js/core/ajax.js
  addons/website_crm_partner_assign/tests/test_partner_assign.py
Labels: saas-12.2

#4725 Syncing from upstream odoo/odoo (saas-12.3)
  addons/hr_holidays/models/hr_leave.py
Labels: saas-12.3

#4726 Syncing from upstream odoo/odoo (saas-12.4)
  addons/sale/models/sales_team.py
  addons/website_sale/models/product.py
  setup.py
Labels: saas-12.4

#4727 Syncing from upstream odoo/odoo (saas-15)
  addons/account/models/partner.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: saas-15

#4729 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_geolocalize/models/res_partner.py
  addons/hr/views/hr_views.xml
  addons/web/static/src/js/core/ajax.js
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  odoo/addons/base/models/ir_http.py
Labels: staging.saas-12.2

#4732 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
Labels: staging.10.0

#4736 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_geolocalize/models/res_partner.py
  addons/hr/views/hr_views.xml
  addons/web/static/src/js/core/ajax.js
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  odoo/addons/base/models/ir_http.py
Labels: tmp.saas-12.2

#4739 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
Labels: tmp.10.0

#4742 [bt#5455] Mails per Company und Signaturen
  addons/mail/models/mail_template.py
  addons/mail/wizard/mail_compose_message.py
  odoo/addons/base/res/ir_property.py
  odoo/addons/base/res/res_users.py
Labels: 10.0.project_go_232.test

#4743 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/base/ir/ir_http.py
Labels: 10.0

#4744 Syncing from upstream odoo/odoo (11.0)
  addons/account_voucher/models/account_voucher.py
Labels: 11.0

#4745 Syncing from upstream odoo/odoo (12.0)
  addons/account/views/account_view.xml
  addons/sale_expense/security/ir.model.access.csv
  addons/sale_expense/security/sale_expense_security.xml
  addons/sale_expense/views/hr_expense_views.xml
Labels: 12.0

#4747 Syncing from upstream odoo/odoo (saas-12.2)
  addons/account/models/account_invoice.py
  addons/account/models/partner.py
  addons/account/report/account_aged_partner_balance.py
  addons/account/wizard/account_invoice_send_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/google_account/models/google_service.py
  addons/hr_holidays/report/hr_holidays_reports.xml
  addons/hw_escpos/controllers/main.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_template.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/wizard/pos_payment.py
  addons/pos_mercury/__manifest__.py
  addons/pos_mercury/static/src/js/pos_mercury.js
  addons/pos_mercury/views/pos_config_views.xml
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/models/__init__.py
  addons/website/models/res_config_settings.py
  addons/website/models/res_lang.py
  addons/website/static/src/js/tours/rte.js
  addons/website/tests/test_qweb.py
  addons/website/tools.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_form/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/sale_order_views.xml
  addons/website_slides/data/mail_data.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
  odoo/tools/misc.py
Labels: saas-12.2

#4748 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/partner.py
  addons/account/report/account_aged_partner_balance.py
  addons/account/wizard/account_invoice_send_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_geolocalize/models/res_partner.py
  addons/gamification/data/gamification_karma_rank_data.xml
  addons/gamification/data/gamification_karma_rank_demo.xml
  addons/gamification/models/res_users.py
  addons/google_account/models/google_service.py
  addons/hr/models/res_users.py
  addons/hr/views/hr_views.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/report/hr_holidays_reports.xml
  addons/hw_escpos/controllers/main.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_template.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/wizard/pos_payment.py
  addons/pos_cache/static/src/js/pos_cache.js
  addons/pos_mercury/__manifest__.py
  addons/pos_mercury/static/src/js/pos_mercury.js
  addons/pos_mercury/views/pos_config_views.xml
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web/static/src/js/core/ajax.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/tests/test_qweb.py
  addons/website/tools.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  addons/website_form/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_profile/static/src/js/website_profile.js
  addons/website_profile/views/website_profile.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/sale_order_views.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/data/mail_data.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/views/website_slides_templates_homepage.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
  odoo/tools/misc.py
Labels: saas-12.3

#4750 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/account/models/account_invoice.py
  addons/account/models/partner.py
  addons/account/report/account_aged_partner_balance.py
  addons/account/wizard/account_invoice_send_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/google_account/models/google_service.py
  addons/hr_holidays/report/hr_holidays_reports.xml
  addons/hw_escpos/controllers/main.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_template.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/wizard/pos_payment.py
  addons/pos_mercury/__manifest__.py
  addons/pos_mercury/static/src/js/pos_mercury.js
  addons/pos_mercury/views/pos_config_views.xml
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/models/__init__.py
  addons/website/models/res_config_settings.py
  addons/website/models/res_lang.py
  addons/website/static/src/js/tours/rte.js
  addons/website/tests/test_qweb.py
  addons/website/tools.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_form/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/sale_order_views.xml
  addons/website_slides/data/mail_data.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
  odoo/tools/misc.py
Labels: staging.saas-12.2

#4753 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/base/ir/ir_http.py
Labels: staging.10.0

#4757 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/account/models/account_invoice.py
  addons/account/models/partner.py
  addons/account/report/account_aged_partner_balance.py
  addons/account/wizard/account_invoice_send_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/google_account/models/google_service.py
  addons/hr_holidays/report/hr_holidays_reports.xml
  addons/hw_escpos/controllers/main.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_template.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/wizard/pos_payment.py
  addons/pos_mercury/__manifest__.py
  addons/pos_mercury/static/src/js/pos_mercury.js
  addons/pos_mercury/views/pos_config_views.xml
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/models/__init__.py
  addons/website/models/res_config_settings.py
  addons/website/models/res_lang.py
  addons/website/static/src/js/tours/rte.js
  addons/website/tests/test_qweb.py
  addons/website/tools.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_form/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/sale_order_views.xml
  addons/website_slides/data/mail_data.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
  odoo/tools/misc.py
Labels: tmp.saas-12.2

#4759 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/base/ir/ir_http.py
Labels: tmp.10.0

#4765 Syncing from upstream odoo/odoo (10.0)
  addons/account/models/partner.py
  addons/website_payment/controllers/main.py
Labels: 10.0

#4766 Syncing from upstream odoo/odoo (11.0)
  addons/purchase/models/purchase.py
  odoo/models.py
Labels: 11.0

#4767 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/static/src/js/unsubscribe.js
  addons/mrp/models/mrp_production.py
  addons/payment_authorize/models/payment.py
  addons/portal/i18n/portal.pot
  addons/portal/static/src/xml/portal_signature.xml
Labels: 12.0

#4768 Syncing from upstream odoo/odoo (master)
  addons/account/models/__init__.py
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/account/views/account_move_views.xml
  addons/account/views/account_report.xml
  addons/account/views/report_invoice.xml
  addons/base_address_city/views/res_city_view.xml
  addons/hr/models/hr_employee.py
  addons/hr_work_entry/models/hr_work_entry.py
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/mrp/static/src/js/mrp.js
  addons/stock/models/res_config_settings.py
  addons/stock/models/stock_picking.py
  addons/web/doc/changelog-7.0.rst
  odoo/addons/base/models/ir_actions_report.py
Labels: master

#4769 Syncing from upstream odoo/odoo (saas-12.4)
  addons/mail/models/mail_thread.py
Labels: saas-12.4

#4770 Syncing from upstream odoo/odoo (saas-15)
  addons/web/static/lib/jSignature/jSignatureCustom.js
Labels: saas-15

#4774 Syncing from upstream odoo/odoo (staging.10.0)
  addons/account/models/partner.py
  addons/website_payment/controllers/main.py
Labels: staging.10.0

#4780 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/account/models/partner.py
  addons/website_payment/controllers/main.py
Labels: tmp.10.0

#4783 Syncing from upstream odoo/odoo (10.0)
  odoo/models.py
Labels: 10.0

#4784 Syncing from upstream odoo/odoo (11.0)
  addons/web/views/database_manager.html
Labels: 11.0

#4785 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/views/unsubscribe_templates.xml
  addons/payment_authorize/models/payment.py
  addons/purchase/models/purchase.py
  addons/sale_timesheet/models/project.py
  odoo/tests/common.py
Labels: 12.0

#4786 Syncing from upstream odoo/odoo (master)
  addons/account/views/account_payment_view.xml
  addons/crm/models/res_partner.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/static/lib/sha1.js
  addons/point_of_sale/views/point_of_sale.xml
  addons/pos_hr/models/__init__.py
  addons/pos_hr/models/hr_employee.py
  addons/pos_hr/static/src/js/gui.js
  addons/pos_hr/static/src/js/models.js
  addons/pos_hr/static/src/js/screens.js
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/models/sales_team.py
  addons/sale_mrp/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/__init__.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/models/stock_warehouse.py
  addons/stock/tests/test_move2.py
  addons/stock/views/stock_rule_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/uom/data/uom_data.xml
  addons/uom/models/uom_uom.py
  addons/web/static/lib/py.js/lib/py.js
  addons/web/static/src/js/chrome/action_manager.js
  addons/web/static/src/js/core/dialog.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/web/static/tests/core/py_utils_tests.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/website_sale/models/product.py
  odoo/addons/base/models/res_users.py
  odoo/models.py
  setup.py
Labels: master

#4787 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
Labels: saas-12.2

#4788 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/views/account_move_views.xml
  addons/website_hr/security/hr_employee_security.xml
  addons/website_hr/security/ir.model.access.csv
Labels: saas-12.4

#4790 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
Labels: staging.saas-12.2

#4792 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/models.py
Labels: staging.10.0

#4796 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
Labels: tmp.saas-12.2

#4798 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/models.py
Labels: tmp.10.0

#4801 Syncing from upstream odoo/odoo (10.0)
  addons/account/models/account_invoice.py
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: 10.0

#4802 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/partner.py
  addons/mass_mailing/controllers/main.py
  addons/stock/models/product.py
  addons/web/static/lib/jSignature/jSignatureCustom.js
Labels: 11.0

#4803 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/account_invoice.py
  addons/account/models/partner.py
  addons/account_voucher/models/account_voucher.py
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report_view.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/payment/models/__init__.py
  addons/payment/models/ir_http.py
  addons/point_of_sale/models/pos_session.py
  addons/portal/models/res_partner.py
  addons/portal/views/portal_templates.xml
  addons/purchase/models/purchase.py
  addons/sale/models/res_partner.py
  addons/web/static/lib/jSignature/jSignatureCustom.js
  addons/web/views/database_manager.html
  addons/website/models/res_config_settings.py
  addons/website/views/res_config_settings_views.xml
  addons/website_blog/static/src/js/s_latest_posts_frontend.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/dorcyv.md
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/tests/common.py
Labels: 12.0

#4804 Syncing from upstream odoo/odoo (master)
  addons/auth_signup/__manifest__.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/auth_signup/data/ir_cron_data.xml
  addons/auth_signup/models/res_users.py
  addons/portal/wizard/portal_wizard.py
  addons/purchase_stock/models/purchase.py
  addons/sales_team/views/crm_team_views.xml
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/website_crm/views/website_crm_templates.xml
Labels: master

#4805 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/partner.py
  addons/account_voucher/models/account_voucher.py
  addons/purchase/models/purchase.py
  addons/web/static/lib/jSignature/jSignatureCustom.js
  addons/web/views/database_manager.html
  odoo/models.py
Labels: saas-11.3

#4807 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/addons/base/models/res_partner.py
Labels: saas-12.3

#4808 Syncing from upstream odoo/odoo (saas-12.4)
  addons/crm_livechat/__manifest__.py
  addons/crm_livechat/data/utm_data.xml
  addons/crm_livechat/models/mail_channel.py
  addons/hr/models/hr_employee.py
  addons/website/models/website.py
  addons/website/views/res_config_settings_views.xml
  addons/website_sale_delivery/static/tests/tours/website_free_delivery.js
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: saas-12.4

#4809 Syncing from upstream odoo/odoo (saas-14)
  addons/account/models/partner.py
  addons/website_payment/controllers/main.py
  odoo/models.py
Labels: saas-14

#4810 Syncing from upstream odoo/odoo (saas-15)
  addons/account/models/partner.py
  odoo/models.py
Labels: saas-15

#4812 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/partner.py
  addons/account_voucher/models/account_voucher.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_discount/static/src/js/discount.js
  addons/purchase/models/purchase.py
  addons/purchase/models/stock.py
  addons/purchase/tests/test_stockvaluation.py
  addons/web/static/lib/jSignature/jSignatureCustom.js
  addons/web/views/database_manager.html
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/web_editor/static/src/xml/editor.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/models.py
  odoo/service/model.py
Labels: staging.saas-11.3

#4816 Syncing from upstream odoo/odoo (staging.10.0)
  addons/account/models/account_invoice.py
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: staging.10.0

#4820 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/models/partner.py
  addons/account_voucher/models/account_voucher.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_discount/static/src/js/discount.js
  addons/purchase/models/purchase.py
  addons/purchase/models/stock.py
  addons/purchase/tests/test_stockvaluation.py
  addons/web/static/lib/jSignature/jSignatureCustom.js
  addons/web/views/database_manager.html
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/web_editor/static/src/xml/editor.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_rpc/__init__.py
  odoo/addons/test_rpc/__manifest__.py
  odoo/addons/test_rpc/ir.model.access.csv
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/__init__.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/models.py
  odoo/service/model.py
Labels: tmp.saas-11.3

#4824 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/account/models/account_invoice.py
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: tmp.10.0

#4828 Syncing from upstream odoo/odoo (11.0)
  addons/account_voucher/models/account_voucher.py
Labels: 11.0

#4829 Syncing from upstream odoo/odoo (12.0)
  addons/portal/models/mail_thread.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/web/tests/test_menu.py
  addons/web/tests/test_serving_base.py
  addons/web_editor/tests/test_converter.py
  addons/website/tests/test_converter.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/addons/base/tests/test_func.py
  odoo/addons/base/tests/test_ir_sequence.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_mimetypes.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_osv.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/tests/test_uninstall.py
  odoo/addons/base/tests/test_view_validation.py
  odoo/addons/test_mimetypes/tests/test_guess_mimetypes.py
  odoo/tests/common.py
  odoo/tools/config.py
Labels: 12.0

#4831 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mail/static/src/js/composers/basic_composer.js
  addons/mail/static/src/js/models/messages/message.js
  addons/mail/static/src/js/services/mail_manager.js
  addons/website_slides/static/src/js/slides_course_quiz.js
Labels: saas-12.2

#4832 Syncing from upstream odoo/odoo (saas-12.3)
  addons/l10n_br/data/account_tax_template_data.xml
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/website_slides/static/src/js/slides_course_quiz.js
Labels: saas-12.3

#4833 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/account_payment/models/payment.py
  addons/account_payment/views/account_portal_templates.xml
  addons/payment/models/payment_acquirer.py
  addons/sale_timesheet/views/hr_timesheet_templates.xml
  addons/sale_timesheet_purchase/models/project_overview.py
Labels: saas-12.4

#4835 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mail/static/src/js/composers/basic_composer.js
  addons/website_slides/static/src/js/slides_course_quiz.js
Labels: staging.saas-12.2

#4841 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mail/static/src/js/composers/basic_composer.js
  addons/website_slides/static/src/js/slides_course_quiz.js
Labels: tmp.saas-12.2

#4846 Syncing from upstream odoo/odoo (12.0)
  addons/hw_drivers/controllers/driver.py
  addons/hw_posbox_homepage/views/homepage.html
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/product/models/res_partner.py
  addons/website_sale/models/sale_order.py
  doc/_extensions/odoo_ext/sub-menu_list.html
Labels: 12.0

#4848 Syncing from upstream odoo/odoo (saas-12.2)
  addons/web_editor/static/src/js/wysiwyg/plugin/helper.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
Labels: saas-12.2

#4849 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/partner.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_move_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/lunch/models/lunch_supplier.py
  addons/mail/static/src/js/composers/basic_composer.js
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/followers.js
  addons/mail/static/src/js/models/messages/message.js
  addons/mail/static/src/js/services/mail_manager.js
  addons/mail/static/tests/discuss_tests.js
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/static/src/js/unsubscribe.js
  addons/mass_mailing/views/unsubscribe_templates.xml
  addons/mrp/models/mrp_production.py
  addons/payment_authorize/models/payment.py
  addons/purchase/models/purchase.py
  addons/sale_expense/security/ir.model.access.csv
  addons/sale_expense/security/sale_expense_security.xml
  addons/sale_expense/views/hr_expense_views.xml
  addons/sale_timesheet/models/project.py
  addons/web/static/lib/jSignature/jSignatureCustom.js
  addons/web/views/database_manager.html
  addons/website/static/src/js/tours/rte.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/tests/common.py
Labels: saas-12.3

#4852 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/web_editor/static/src/js/wysiwyg/plugin/helper.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
Labels: staging.saas-12.2

#4858 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/web_editor/static/src/js/wysiwyg/plugin/helper.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
Labels: tmp.saas-12.2

#4865 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/i18n/sl.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_TW.po
  addons/account/models/account_invoice.py
  addons/account_voucher/models/account_voucher.py
  addons/barcodes/i18n/cs.po
  addons/hr_expense/i18n/cs.po
  addons/hr_holidays/i18n/cs.po
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/mail/i18n/uk.po
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/cs.po
  addons/mrp/i18n/hu.po
  addons/mrp_byproduct/i18n/ko.po
  addons/payment/controllers/portal.py
  addons/point_of_sale/i18n/hu.po
  addons/sale/i18n/sl.po
  addons/sale_stock/i18n/cs.po
  addons/stock/i18n/hu.po
  addons/stock/models/product.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/survey/i18n/ko.po
  addons/website/i18n/uk.po
  addons/website_quote/i18n/cs.po
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  odoo/addons/base/i18n/sl.po
Labels: saas-11.3

#4866 Syncing from upstream odoo/odoo (saas-12.2)
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_statistics.py
Labels: saas-12.2

#4868 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/views/account_move_views.xml
  addons/crm/models/res_config_settings.py
Labels: saas-12.4

#4869 Syncing from upstream odoo/odoo (saas-14)
  addons/account/models/account_invoice.py
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: saas-14

#4870 Syncing from upstream odoo/odoo (saas-15)
  addons/account/models/account_invoice.py
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/website_payment/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: saas-15

#4872 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/i18n/sl.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_TW.po
  addons/account/models/account_invoice.py
  addons/account_voucher/models/account_voucher.py
  addons/barcodes/i18n/cs.po
  addons/hr_expense/i18n/cs.po
  addons/hr_holidays/i18n/cs.po
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/mail/i18n/uk.po
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/cs.po
  addons/mrp/i18n/hu.po
  addons/mrp_byproduct/i18n/ko.po
  addons/payment/controllers/portal.py
  addons/point_of_sale/i18n/hu.po
  addons/sale/i18n/sl.po
  addons/sale_stock/i18n/cs.po
  addons/stock/i18n/hu.po
  addons/stock/models/product.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/survey/i18n/ko.po
  addons/website/i18n/uk.po
  addons/website_quote/i18n/cs.po
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  odoo/addons/base/i18n/sl.po
Labels: staging.saas-11.3

#4873 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_statistics.py
Labels: staging.saas-12.2

#4879 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/i18n/sl.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_TW.po
  addons/account/models/account_invoice.py
  addons/account_voucher/models/account_voucher.py
  addons/barcodes/i18n/cs.po
  addons/hr_expense/i18n/cs.po
  addons/hr_holidays/i18n/cs.po
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_be_intrastat_2019/models/account_intrastat_report.py
  addons/mail/i18n/uk.po
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/cs.po
  addons/mrp/i18n/hu.po
  addons/mrp_byproduct/i18n/ko.po
  addons/payment/controllers/portal.py
  addons/point_of_sale/i18n/hu.po
  addons/sale/i18n/sl.po
  addons/sale_stock/i18n/cs.po
  addons/stock/i18n/hu.po
  addons/stock/models/product.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/survey/i18n/ko.po
  addons/website/i18n/uk.po
  addons/website_quote/i18n/cs.po
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  odoo/addons/base/i18n/sl.po
Labels: tmp.saas-11.3

#4880 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_statistics.py
Labels: tmp.saas-12.2

#4885 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/zh_TW.po
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/tests/reconciliation_tests.js
  addons/account_voucher/models/account_voucher.py
  addons/l10n_ch/models/account_invoice.py
  addons/mass_mailing/controllers/main.py
  addons/payment/controllers/portal.py
  addons/point_of_sale/models/pos_order.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/product.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/web/static/src/js/views/kanban/kanban_column_progressbar.js
  addons/web/static/src/xml/kanban.xml
  addons/website_sale/models/website.py
Labels: 12.0

#4901 Syncing from upstream odoo/odoo (11.0)
  addons/account_payment/views/account_portal_templates.xml
Labels: 11.0

#4902 Syncing from upstream odoo/odoo (12.0)
  addons/mail/static/src/scss/discuss.scss
  addons/sale/models/sale.py
  addons/sale_purchase/models/sale_order.py
  addons/stock/views/product_strategy_views.xml
  doc/cla/individual/lutrome.md
Labels: 12.0

#4904 Syncing from upstream odoo/odoo (saas-11.3)
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
Labels: saas-11.3

#4905 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mail/static/src/js/models/threads/dm_chat.js
  addons/mail/static/src/js/models/threads/document_thread.js
  addons/mail/static/src/js/models/threads/mixins/thread_typing_mixin.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_status_manager.js
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/src/js/thread_windows/thread_window.js
  addons/mail/static/src/xml/thread_window.xml
  addons/mail/static/tests/document_thread_window_tests.js
  addons/mail/static/tests/thread_window/basic_thread_window_tests.js
Labels: saas-12.2

#4906 Syncing from upstream odoo/odoo (saas-12.3)
  addons/hr_expense/models/hr_expense.py
Labels: saas-12.3

#4907 Syncing from upstream odoo/odoo (saas-12.4)
  addons/payment_alipay/tests/test_alipay.py
  addons/web/static/tests/views/calendar_tests.js
Labels: saas-12.4

#4909 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
Labels: staging.saas-11.3

#4910 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mail/static/src/js/models/threads/dm_chat.js
  addons/mail/static/src/js/models/threads/document_thread.js
  addons/mail/static/src/js/models/threads/mixins/thread_typing_mixin.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_status_manager.js
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/src/js/thread_windows/thread_window.js
  addons/mail/static/src/xml/thread_window.xml
  addons/mail/static/tests/document_thread_window_tests.js
  addons/mail/static/tests/thread_window/basic_thread_window_tests.js
Labels: staging.saas-12.2

#4916 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
Labels: tmp.saas-11.3

#4917 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mail/static/src/js/models/threads/dm_chat.js
  addons/mail/static/src/js/models/threads/document_thread.js
  addons/mail/static/src/js/models/threads/mixins/thread_typing_mixin.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_status_manager.js
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/src/js/thread_windows/thread_window.js
  addons/mail/static/src/xml/thread_window.xml
  addons/mail/static/tests/document_thread_window_tests.js
  addons/mail/static/tests/thread_window/basic_thread_window_tests.js
Labels: tmp.saas-12.2

#4922 Syncing from upstream odoo/odoo (10.0)
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_views.xml
Labels: 10.0

#4923 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_payment.py
  addons/account_asset/models/account_asset.py
  addons/delivery/__manifest__.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/static/src/js/delivery_translations.js
  addons/delivery/views/assets.xml
  addons/payment/i18n/payment.pot
  addons/payment/static/src/js/payment_translations.js
  addons/payment/views/assets.xml
  addons/stock/models/product.py
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  doc/reference/qweb.rst
Labels: 11.0

#4924 Syncing from upstream odoo/odoo (12.0)
  addons/crm_reveal/models/crm_reveal_rule.py
  addons/mail/static/src/js/services/mail_notification_manager.js
  addons/payment_authorize/models/authorize_request.py
  addons/stock_zebra/report/picking_templates.xml
  addons/web/static/src/xml/menu.xml
  addons/web_editor/static/src/js/widgets/widgets.js
  odoo/addons/test_testing_utilities/ir.model.access.csv
  odoo/addons/test_testing_utilities/models.py
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
Labels: 12.0

#4926 Syncing from upstream odoo/odoo (saas-12.2)
  addons/base_vat/models/res_partner.py
  addons/l10n_in/data/res_partner_demo.xml
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/mail/static/src/scss/abstract_thread_window.scss
  addons/mail/static/src/xml/abstract_thread_window.xml
  addons/portal/controllers/mail.py
  addons/sale/tests/test_sale_signature.py
  addons/web_editor/static/src/js/wysiwyg/plugin/history.js
Labels: saas-12.2

#4927 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/wysiwyg/plugin/helper.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/src/js/wysiwyg_snippets/wysiwyg_snippets.js
Labels: saas-12.3

#4928 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/base_vat/models/res_partner.py
  addons/l10n_in/data/res_partner_demo.xml
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/mail/static/src/scss/abstract_thread_window.scss
  addons/mail/static/src/xml/abstract_thread_window.xml
  addons/portal/controllers/mail.py
  addons/sale/tests/test_sale_signature.py
  addons/web_editor/static/src/js/wysiwyg/plugin/history.js
Labels: staging.saas-12.2

#4931 Syncing from upstream odoo/odoo (staging.10.0)
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_views.xml
Labels: staging.10.0

#4934 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/base_vat/models/res_partner.py
  addons/l10n_in/data/res_partner_demo.xml
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/mail/static/src/scss/abstract_thread_window.scss
  addons/mail/static/src/xml/abstract_thread_window.xml
  addons/portal/controllers/mail.py
  addons/sale/tests/test_sale_signature.py
  addons/web_editor/static/src/js/wysiwyg/plugin/history.js
Labels: tmp.saas-12.2

#4936 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_views.xml
Labels: tmp.10.0

#4939 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_bank_statement.py
  addons/account/wizard/account_invoice_send.py
  addons/delivery/models/sale_order.py
  addons/l10n_ae/data/account_tax_template_data.xml
  addons/portal/static/src/scss/portal.scss
  addons/project/models/project.py
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
Labels: 12.0

#4941 Syncing from upstream odoo/odoo (saas-12.2)
  addons/lunch/models/lunch_cashmove.py
Labels: saas-12.2

#4942 Syncing from upstream odoo/odoo (saas-12.3)
  addons/l10n_at/data/account_tax_data.xml
  addons/l10n_at/data/account_tax_report_data.xml
Labels: saas-12.3

#4943 Syncing from upstream odoo/odoo (saas-12.4)
  addons/lunch/models/lunch_cashmove.py
Labels: saas-12.4

#4944 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/lunch/models/lunch_cashmove.py
  addons/web/static/src/js/chrome/action_manager_act_window.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: staging.saas-12.2

#4949 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/lunch/models/lunch_cashmove.py
  addons/web/static/src/js/chrome/action_manager_act_window.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: tmp.saas-12.2

#4957 Syncing from upstream odoo/odoo (saas-12.2)
  addons/website_profile/controllers/main.py
Labels: saas-12.2

#4958 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/hu.po
  addons/account/i18n/uk.po
  addons/event/i18n/ca.po
  addons/event_sale/i18n/ca.po
  addons/hr/i18n/nl.po
  addons/hr_holidays/i18n/nl.po
  addons/hr_recruitment_survey/i18n/uk.po
  addons/lunch/i18n/nl.po
  addons/mail/i18n/nl.po
  addons/maintenance/i18n/uk.po
  addons/mass_mailing/i18n/fr.po
  addons/membership/i18n/ca.po
  addons/mrp/i18n/hu.po
  addons/mrp/i18n/nl.po
  addons/purchase/i18n/uk.po
  addons/rating/i18n/de.po
  addons/repair/i18n/de.po
  addons/repair/i18n/hu.po
  addons/resource/i18n/nl.po
  addons/sale/i18n/es.po
  addons/sale/i18n/hu.po
  addons/sale/i18n/ro.po
  addons/sale_crm/i18n/de.po
  addons/sale_management/i18n/de.po
  addons/sale_management/i18n/hu.po
  addons/sale_product_configurator/i18n/de.po
  addons/sale_quotation_builder/i18n/de.po
  addons/stock/i18n/hu.po
  addons/survey/i18n/fr.po
  addons/survey/i18n/nl.po
  addons/web_editor/i18n/nl.po
  addons/web_editor/static/tests/wysiwyg_tests.js
  addons/website/i18n/fr.po
  addons/website/i18n/hu.po
  addons/website_crm_partner_assign/i18n/ca.po
  addons/website_customer/i18n/ca.po
  addons/website_event/i18n/ca.po
  addons/website_membership/i18n/ca.po
  addons/website_slides/i18n/ca.po
  addons/website_slides/i18n/nl.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/hu.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/uk.po
Labels: saas-12.3

#4959 Syncing from upstream odoo/odoo (saas-12.4)
  addons/hr_expense/models/hr_expense.py
  addons/hr_recruitment_survey/i18n/uk.po
  addons/l10n_at/data/account_tax_data.xml
  addons/l10n_at/data/account_tax_report_data.xml
  addons/l10n_za/__manifest__.py
  addons/maintenance/i18n/uk.po
  addons/membership/i18n/ca.po
  addons/mrp/i18n/hu.po
  addons/repair/i18n/de.po
  addons/repair/i18n/hu.po
  addons/resource/i18n/nl.po
  addons/sale/i18n/hu.po
  addons/sale/i18n/ro.po
  addons/sale_management/i18n/de.po
  addons/sale_management/i18n/hu.po
  addons/sale_quotation_builder/i18n/de.po
  addons/stock/i18n/hu.po
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/wysiwyg/plugin/helper.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/src/js/wysiwyg_snippets/wysiwyg_snippets.js
  addons/web_editor/static/tests/wysiwyg_tests.js
  addons/website/i18n/hu.po
  addons/website_customer/i18n/ca.po
  addons/website_event/i18n/ca.po
  addons/website_form/static/src/js/website_form.js
  addons/website_membership/i18n/ca.po
Labels: saas-12.4

#4960 Syncing from upstream odoo/odoo (saas-14)
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_views.xml
Labels: saas-14

#4962 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/website_profile/controllers/main.py
Labels: staging.saas-12.2

#4968 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/website_profile/controllers/main.py
Labels: tmp.saas-12.2

#4973 Syncing from upstream odoo/odoo (11.0)
  addons/website_quote/views/sale_quote_views.xml
Labels: 11.0

#4974 Syncing from upstream odoo/odoo (12.0)
  addons/point_of_sale/models/pos_config.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/stock/models/stock_move_line.py
Labels: 12.0

#4977 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/js/views/list/list_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
  doc/reference/views.rst
Labels: saas-12.3

#4978 Syncing from upstream odoo/odoo (saas-12.4)
  addons/snailmail_account/tests/test_pingen_send.py
Labels: saas-12.4

#4990 Syncing from upstream odoo/odoo (10.0)
  addons/web_editor/models/ir_ui_view.py
Labels: 10.0

#4991 Syncing from upstream odoo/odoo (11.0)
  addons/website/models/website.py
  addons/website_sale/controllers/main.py
Labels: 11.0

#4992 Syncing from upstream odoo/odoo (12.0)
  addons/account/wizard/account_invoice_send_views.xml
  addons/mail/static/src/js/activity.js
  addons/mail/static/tests/chatter_tests.js
  addons/mail/wizard/mail_compose_message.py
  addons/purchase/views/purchase_views.xml
  addons/website_sale/controllers/main.py
Labels: 12.0

#4993 Syncing from upstream odoo/odoo (master)
  addons/portal/controllers/mail.py
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/portal_chatter.js
  addons/portal/static/src/scss/portal.scss
  addons/portal/static/src/xml/portal_chatter.xml
  addons/portal/tests/__init__.py
  addons/portal/tests/test_attachment.py
  addons/product/models/product.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/web/static/src/scss/form_view.scss
  addons/web/static/src/scss/form_view_extra.scss
  addons/web/static/src/scss/primary_variables.scss
  odoo/tests/common.py
Labels: master

#4994 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/website.py
  addons/website/static/src/js/menu/edit.js
  addons/website_quote/models/sale_order.py
  addons/website_quote/views/sale_quote_views.xml
  addons/website_sale/controllers/main.py
  doc/howtos/profilecode.rst
Labels: saas-11.3

#4995 Syncing from upstream odoo/odoo (saas-12.2)
  addons/gamification/models/gamification_karma_rank.py
  addons/gamification/models/res_users.py
  addons/gamification/tests/__init__.py
  addons/gamification/tests/test_recompute_rank.py
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
Labels: saas-12.2

#4997 Syncing from upstream odoo/odoo (saas-12.4)
  addons/web_editor/models/ir_ui_view.py
  addons/website/models/ir_ui_view.py
Labels: saas-12.4

#4998 Syncing from upstream odoo/odoo (saas-14)
  addons/website_sale/controllers/main.py
Labels: saas-14

#4999 Syncing from upstream odoo/odoo (saas-15)
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_views.xml
  addons/website_sale/controllers/main.py
Labels: saas-15

#5000 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/gamification/models/gamification_karma_rank.py
  addons/gamification/models/res_users.py
  addons/gamification/tests/__init__.py
  addons/gamification/tests/test_recompute_rank.py
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
Labels: staging.saas-12.2

#5003 Syncing from upstream odoo/odoo (staging.10.0)
  addons/web_editor/models/ir_ui_view.py
Labels: staging.10.0

#5006 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/gamification/models/gamification_karma_rank.py
  addons/gamification/models/res_users.py
  addons/gamification/tests/__init__.py
  addons/gamification/tests/test_recompute_rank.py
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
Labels: tmp.saas-12.2

#5009 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/web_editor/models/ir_ui_view.py
Labels: tmp.10.0

#5012 Syncing from upstream odoo/odoo (10.0)
  doc/cla/individual/stfnndrsn.md
Labels: 10.0

#5013 Syncing from upstream odoo/odoo (11.0)
  addons/web_editor/models/ir_ui_view.py
Labels: 11.0

#5014 Syncing from upstream odoo/odoo (12.0)
  addons/account/wizard/account_invoice_send.py
  addons/sale_management/models/sale_order.py
  addons/sale_management/views/sale_order_template_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/res_config_settings.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move2.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/website.py
  addons/website/static/src/js/menu/edit.js
  addons/website/tests/test_views.py
  addons/website_sale/controllers/main.py
  doc/cla/individual/ddufresne.md
  doc/howtos/profilecode.rst
  odoo/addons/base/models/res_users.py
Labels: 12.0

#5015 Syncing from upstream odoo/odoo (master)
  addons/event/models/event.py
  addons/event/models/event_mail.py
  addons/event/tests/common.py
  addons/event/tests/test_event_flow.py
  addons/event/tests/test_mail_schedule.py
  addons/event/views/event_views.xml
  addons/event_sale/views/event_views.xml
  addons/event_sale/wizard/event_edit_registration.py
  addons/event_sale/wizard/event_edit_registration.xml
  addons/event_sms/__init__.py
  addons/event_sms/__manifest__.py
  addons/event_sms/data/sms_data.xml
  addons/event_sms/models/__init__.py
  addons/event_sms/models/event.py
  addons/event_sms/models/event_mail.py
  addons/event_sms/tests/__init__.py
  addons/event_sms/tests/test_sms_schedule.py
  addons/event_sms/views/event_mail_views.xml
  addons/event_sms/views/event_views.xml
  addons/hw_drivers/drivers/SerialBaseDriver.py
  addons/hw_drivers/drivers/SerialScaleDriver.py
  addons/l10n_si/__manifest__.py
  addons/stock/models/stock_scrap.py
  addons/web/controllers/main.py
  addons/web/i18n/web.pot
  addons/web/models/ir_http.py
  addons/web/static/src/js/core/utils.js
  addons/web/static/tests/services/notification_service_tests.js
  addons/web/tests/test_serving_base.py
  addons/website/models/res_config_settings.py
  addons/website/models/website.py
  addons/website/static/src/img/website_logo.png
  addons/website/static/src/js/content/menu.js
  addons/website/views/res_config_settings_views.xml
  addons/website/views/website_templates.xml
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_views.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  doc/cla/individual/tanghulu0608.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/modules/loading.py
  odoo/modules/module.py
  odoo/service/server.py
  odoo/tests/common.py
  odoo/tools/__init__.py
  odoo/tools/template_inheritance.py
Labels: master
