Repository brain-tec/odoo, pull requests merged in 2019-03, with the labels that each got.

#3190 Syncing from upstream odoo/odoo (saas-12.1)
  addons/crm/models/crm_team.py
  addons/l10n_in/data/l10n_in_chart_data.xml
  addons/web/static/src/js/views/control_panel/control_panel_controller.js
  addons/web/static/src/js/views/control_panel/search/search_bar.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/web/static/tests/views/search_view_tests.js
  odoo/tests/common.py
Labels: saas-12.1

#3191 Syncing from upstream odoo/odoo (saas-12.2)
  addons/account/i18n/fr.po
  addons/account/i18n/hr.po
  addons/account/i18n/hu.po
  addons/account/i18n/nl.po
  addons/account/i18n/ru.po
  addons/account/i18n/tr.po
  addons/account/i18n/uk.po
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_invoice_view.xml
  addons/account_analytic_default/i18n/nl.po
  addons/account_bank_statement_import/i18n/tr.po
  addons/account_check_printing/i18n/hr.po
  addons/account_payment/i18n/tr.po
  addons/account_voucher/i18n/tr.po
  addons/analytic/i18n/tr.po
  addons/board/static/src/js/board_view.js
  addons/board/static/tests/dashboard_tests.js
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/composers/basic_composer.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/abstract_view.js
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/helpers/test_utils_fields.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/tr.po
  odoo/tests/common.py
Labels: saas-12.2

#3192 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/crm/models/crm_team.py
  addons/l10n_in/data/l10n_in_chart_data.xml
  addons/web/static/src/js/views/control_panel/control_panel_controller.js
  addons/web/static/src/js/views/control_panel/search/search_bar.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/web/static/tests/views/search_view_tests.js
  odoo/tests/common.py
Labels: staging.saas-12.1

#3193 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/account/i18n/fr.po
  addons/account/i18n/hr.po
  addons/account/i18n/hu.po
  addons/account/i18n/nl.po
  addons/account/i18n/ru.po
  addons/account/i18n/tr.po
  addons/account/i18n/uk.po
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_invoice_view.xml
  addons/account_analytic_default/i18n/nl.po
  addons/account_bank_statement_import/i18n/tr.po
  addons/account_check_printing/i18n/hr.po
  addons/account_payment/i18n/tr.po
  addons/account_voucher/i18n/tr.po
  addons/analytic/i18n/tr.po
  addons/board/static/src/js/board_view.js
  addons/board/static/tests/dashboard_tests.js
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/composers/basic_composer.js
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/abstract_view.js
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/helpers/test_utils_fields.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/tr.po
  odoo/tests/common.py
Labels: staging.saas-12.2

#3196 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/crm/models/crm_team.py
  addons/l10n_in/data/l10n_in_chart_data.xml
  addons/web/static/src/js/views/control_panel/control_panel_controller.js
  addons/web/static/src/js/views/control_panel/search/search_bar.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/web/static/tests/views/search_view_tests.js
  odoo/tests/common.py
Labels: tmp.saas-12.1

#3197 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/account/i18n/fr.po
  addons/account/i18n/hr.po
  addons/account/i18n/hu.po
  addons/account/i18n/nl.po
  addons/account/i18n/ru.po
  addons/account/i18n/tr.po
  addons/account/i18n/uk.po
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_invoice_view.xml
  addons/account_analytic_default/i18n/nl.po
  addons/account_bank_statement_import/i18n/tr.po
  addons/account_check_printing/i18n/hr.po
  addons/account_payment/i18n/tr.po
  addons/account_voucher/i18n/tr.po
  addons/analytic/i18n/tr.po
  addons/board/static/src/js/board_view.js
  addons/board/static/tests/dashboard_tests.js
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/composers/basic_composer.js
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/abstract_view.js
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/helpers/test_utils_fields.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/tr.po
  odoo/tests/common.py
Labels: tmp.saas-12.2

#3199 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_access_rights.py
Labels: staging.saas-12.1

#3202 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_access_rights.py
Labels: tmp.saas-12.1

#3210 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/i18n/de.po
  addons/account/i18n/es.po
  addons/account/i18n/mn.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_CN.po
  addons/account_bank_statement_import/i18n/es.po
  addons/account_check_printing/i18n/mn.po
  addons/account_payment/i18n/mn.po
  addons/account_voucher/i18n/mn.po
  addons/analytic/i18n/mn.po
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_access_rights.py
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/uk.po
Labels: saas-12.1

#3211 Syncing from upstream odoo/odoo (saas-12.2)
  addons/lunch/static/src/scss/lunch_kanban.scss
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
  addons/payment_payulatam/models/payment.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/web/static/src/scss/list_view.scss
Labels: saas-12.2

#3212 Syncing from upstream odoo/odoo (saas-12.2)
  addons/website_forum/views/website_forum_profile.xml
  addons/website_profile/static/src/img/badge_bronze.svg
  addons/website_profile/static/src/img/badge_gold.svg
  addons/website_profile/static/src/img/badge_silver.svg
  addons/website_profile/static/src/img/rank_1.svg
  addons/website_profile/static/src/img/rank_2.svg
  addons/website_profile/static/src/img/rank_3.svg
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_sale_slides/data/website_sale_slides_demo.xml
  addons/website_sale_slides/static/img/5WMqwTnZ-qs.png
  addons/website_sale_slides/static/img/ptjeDDoURL8.png
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_channel_demo.xml
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/img/banner_heroes_default.svg
  addons/website_slides/static/src/img/channel_demo_diy.jpg
  addons/website_slides/static/src/img/channel_demo_furniture_3.jpg
  addons/website_slides/static/src/img/slide_demo_gardening_1.jpg
  addons/website_slides/static/src/img/slide_demo_owl.jpg
  addons/website_slides/static/src/img/slide_demo_thumb_ebBez6bcSEc.jpg
  addons/website_slides/static/src/js/slides_course_slides_list.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/scss/website_slides_profile.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_profile.xml
  addons/website_slides_forum/data/slide_channel_demo.xml
  addons/website_slides_survey/data/slide_slide_demo.xml
  addons/website_slides_survey/views/website_profile.xml
  addons/website_slides_survey/views/website_slides_templates_course.xml
Labels: saas-12.2

#3213 Syncing from upstream odoo/odoo (saas-14)
  addons/point_of_sale/static/src/css/pos.css
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  odoo/addons/base/ir/ir_qweb/qweb.py
Labels: saas-14

#3214 Syncing from upstream odoo/odoo (saas-15)
  addons/account/models/account_invoice.py
  addons/barcodes/static/src/js/field_float_scannable.js
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays/models/hr_holidays.py
  addons/hr_timesheet_sheet/models/hr_timesheet_sheet.py
  addons/point_of_sale/static/src/css/pos.css
  addons/sale/models/res_partner.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/web/static/src/js/framework/formats.js
  addons/web/static/src/js/views/form_relational_widgets.js
  addons/website_mail/views/website_mail_templates.xml
  doc/cla/corporate/savoirfairelinux.md
  odoo/addons/base/ir/ir_qweb/qweb.py
  odoo/addons/base/ir/ir_rule.py
  odoo/addons/base/tests/test_expression.py
  odoo/models.py
  odoo/osv/expression.py
Labels: saas-15

#3215 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/account_move.py
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/views/res_config_settings_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/auth_signup/models/res_partner.py
  addons/base_automation/views/base_automation_view.xml
  addons/base_import_module/views/base_import_module_view.xml
  addons/crm/views/crm_lead_views.xml
  addons/google_calendar/models/google_calendar.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_it/__manifest__.py
  addons/l10n_mx/data/account_data.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/gui.js
  addons/sale_crm/models/crm_lead.py
  addons/sale_timesheet/models/account.py
  addons/stock/models/product.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/js/chrome/search_filters.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  doc/cla/corporate/invitu.md
  doc/cla/individual/naglis.md
  doc/reference/reports.rst
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/api.py
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-11.3

#3216 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/website_forum/views/website_forum_profile.xml
  addons/website_profile/static/src/img/badge_bronze.svg
  addons/website_profile/static/src/img/badge_gold.svg
  addons/website_profile/static/src/img/badge_silver.svg
  addons/website_profile/static/src/img/rank_1.svg
  addons/website_profile/static/src/img/rank_2.svg
  addons/website_profile/static/src/img/rank_3.svg
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_sale_slides/data/website_sale_slides_demo.xml
  addons/website_sale_slides/static/img/5WMqwTnZ-qs.png
  addons/website_sale_slides/static/img/ptjeDDoURL8.png
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_channel_demo.xml
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/img/banner_heroes_default.svg
  addons/website_slides/static/src/img/channel_demo_diy.jpg
  addons/website_slides/static/src/img/channel_demo_furniture_3.jpg
  addons/website_slides/static/src/img/slide_demo_gardening_1.jpg
  addons/website_slides/static/src/img/slide_demo_owl.jpg
  addons/website_slides/static/src/img/slide_demo_thumb_ebBez6bcSEc.jpg
  addons/website_slides/static/src/js/slides_course_slides_list.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/scss/website_slides_profile.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_profile.xml
  addons/website_slides_forum/data/slide_channel_demo.xml
  addons/website_slides_survey/data/slide_slide_demo.xml
  addons/website_slides_survey/views/website_profile.xml
  addons/website_slides_survey/views/website_slides_templates_course.xml
Labels: staging.saas-12.2

#3220 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/website_forum/views/website_forum_profile.xml
  addons/website_profile/static/src/img/badge_bronze.svg
  addons/website_profile/static/src/img/badge_gold.svg
  addons/website_profile/static/src/img/badge_silver.svg
  addons/website_profile/static/src/img/rank_1.svg
  addons/website_profile/static/src/img/rank_2.svg
  addons/website_profile/static/src/img/rank_3.svg
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_sale_slides/data/website_sale_slides_demo.xml
  addons/website_sale_slides/static/img/5WMqwTnZ-qs.png
  addons/website_sale_slides/static/img/ptjeDDoURL8.png
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_channel_demo.xml
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/img/banner_heroes_default.svg
  addons/website_slides/static/src/img/channel_demo_diy.jpg
  addons/website_slides/static/src/img/channel_demo_furniture_3.jpg
  addons/website_slides/static/src/img/slide_demo_gardening_1.jpg
  addons/website_slides/static/src/img/slide_demo_owl.jpg
  addons/website_slides/static/src/img/slide_demo_thumb_ebBez6bcSEc.jpg
  addons/website_slides/static/src/js/slides_course_slides_list.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/scss/website_slides_profile.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_profile.xml
  addons/website_slides_forum/data/slide_channel_demo.xml
  addons/website_slides_survey/data/slide_slide_demo.xml
  addons/website_slides_survey/views/website_profile.xml
  addons/website_slides_survey/views/website_slides_templates_course.xml
Labels: tmp.saas-12.2

#3222 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_invoice.py
  addons/account/tests/test_account_invoice_rounding.py
  addons/auth_signup/models/res_partner.py
  addons/event_sale/models/sale_order.py
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_activity.py
  addons/point_of_sale/static/src/css/pos.css
  addons/portal/wizard/portal_wizard.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/product/views/product_views.xml
  addons/sale/models/res_partner.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_account/views/product_views.xml
  addons/stock_account/views/stock_account_views.xml
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/__init__.py
  addons/website/__manifest__.py
  addons/website/models/__init__.py
  addons/website/models/ir_model.py
  addons/website/static/src/js/tours/rte.js
  addons/website_event_sale/models/__init__.py
  addons/website_event_sale/models/product_pricelist.py
  addons/website_quote/models/sale_quote.py
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/projet-grup.md
  doc/cla/corporate/savoirfairelinux.md
  doc/cla/individual/cantecim.md
  doc/cla/individual/mjabuz.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/qweb.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_views.py
  odoo/fields.py
  odoo/models.py
  odoo/osv/expression.py
Labels: saas-11.3

#3223 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/models/account_reconcile_model.py
  addons/analytic/models/analytic_account.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/web/static/src/js/chrome/action_manager_act_window.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: saas-12.1

#3224 Syncing from upstream odoo/odoo (saas-12.2)
  addons/gamification/data/gamification_karma_rank_data.xml
  addons/gamification/models/res_users.py
  addons/gamification/static/img/rank_misc_world.png
  addons/hr/models/hr.py
  addons/hr_payroll/models/hr_benefit.py
  addons/hr_payroll/tests/test_benefit.py
  addons/mail/models/mail_activity.py
  addons/mail/models/mail_tracking_value.py
  addons/mrp/models/stock_rule.py
  addons/sale_management/views/sale_order_views.xml
  addons/survey/views/survey_survey_views.xml
  addons/survey/wizard/survey_invite_views.xml
  addons/test_mail/tests/test_message_track.py
  addons/web/static/src/js/fields/field_registry.js
  addons/web_editor/static/lib/summernote/summernote.js
  addons/web_editor/static/src/js/wysiwyg/plugin/media.js
  addons/web_editor/static/src/js/wysiwyg/root.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides_forum/views/website_slides_forum_templates.xml
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/src/js/res_config_settings.js
  odoo/addons/base/static/tests/base_settings_tests.js
Labels: saas-12.2

#3225 Syncing from upstream odoo/odoo (saas-14)
  addons/web_editor/models/ir_ui_view.py
  addons/website/static/src/js/website.tour.rte.js
Labels: saas-14

#3226 Syncing from upstream odoo/odoo (saas-15)
  addons/web_editor/models/ir_ui_view.py
  addons/website/static/src/js/website.tour.rte.js
Labels: saas-15

#3227 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/account/i18n/de.po
  addons/account/i18n/es.po
  addons/account/i18n/mn.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_CN.po
  addons/account/models/account_reconcile_model.py
  addons/account_bank_statement_import/i18n/es.po
  addons/account_check_printing/i18n/mn.po
  addons/account_payment/i18n/mn.po
  addons/account_voucher/i18n/mn.po
  addons/analytic/i18n/mn.po
  addons/analytic/models/analytic_account.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/web/static/src/js/chrome/action_manager_act_window.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/uk.po
Labels: staging.saas-12.1

#3229 Syncing from upstream odoo/odoo (staging.10.0)
  addons/gamification/models/badge.py
  addons/point_of_sale/static/src/js/screens.js
  odoo/addons/base/ir/ir_qweb/qweb.py
Labels: staging.10.0

#3231 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/account/i18n/de.po
  addons/account/i18n/es.po
  addons/account/i18n/mn.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_CN.po
  addons/account/models/account_reconcile_model.py
  addons/account_bank_statement_import/i18n/es.po
  addons/account_check_printing/i18n/mn.po
  addons/account_payment/i18n/mn.po
  addons/account_voucher/i18n/mn.po
  addons/analytic/i18n/mn.po
  addons/analytic/models/analytic_account.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/web/static/src/js/chrome/action_manager_act_window.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/uk.po
Labels: tmp.saas-12.1

#3234 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/website_links/static/src/js/website_links.js
Labels: staging.saas-12.1

#3235 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/gamification/data/gamification_karma_rank_data.xml
  addons/gamification/data/gamification_karma_rank_demo.xml
  addons/hr_skills/static/src/js/resume_widget.js
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/portal_chatter.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_profile/controllers/main.py
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_channel_demo.xml
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/js/slides_share.js
  addons/website_slides/static/src/scss/slide_slide.scss
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/scss/website_slides_quiz.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  addons/website_slides/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides/views/assets.xml
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_forum/__manifest__.py
  addons/website_slides_forum/controllers/main.py
  addons/website_slides_forum/data/slide_channel_demo.xml
  addons/website_slides_forum/static/src/xml/website_slides_forum_channel.xml
  addons/website_slides_survey/__manifest__.py
  addons/website_slides_survey/controllers/slides.py
  addons/website_slides_survey/data/slide_slide_demo.xml
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/views/website_slides_templates_lesson.xml
  addons/website_slides_survey/views/website_slides_templates_lesson_fullscreen.xml
Labels: staging.saas-12.2

#3236 Syncing from upstream odoo/odoo (staging.10.0)
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/views/unsubscribe_templates.xml
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
Labels: staging.10.0

#3238 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/website_links/static/src/js/website_links.js
Labels: tmp.saas-12.1

#3239 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/gamification/data/gamification_karma_rank_data.xml
  addons/gamification/data/gamification_karma_rank_demo.xml
  addons/hr_skills/static/src/js/resume_widget.js
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/portal_chatter.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_profile/controllers/main.py
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_channel_demo.xml
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/js/slides_share.js
  addons/website_slides/static/src/scss/slide_slide.scss
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/scss/website_slides_quiz.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  addons/website_slides/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides/views/assets.xml
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_forum/__manifest__.py
  addons/website_slides_forum/controllers/main.py
  addons/website_slides_forum/data/slide_channel_demo.xml
  addons/website_slides_forum/static/src/xml/website_slides_forum_channel.xml
  addons/website_slides_survey/__manifest__.py
  addons/website_slides_survey/controllers/slides.py
  addons/website_slides_survey/data/slide_slide_demo.xml
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/views/website_slides_templates_lesson.xml
  addons/website_slides_survey/views/website_slides_templates_lesson_fullscreen.xml
Labels: tmp.saas-12.2

#3241 Syncing from upstream odoo/odoo (10.0)
  addons/gamification/models/badge.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
  addons/point_of_sale/static/src/js/screens.js
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/views/unsubscribe_templates.xml
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/ir/ir_qweb/qweb.py
Labels: 10.0

#3242 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_invoice.py
  addons/account/views/account_payment_view.xml
  addons/account/views/account_view.xml
  addons/account_asset/views/account_asset_views.xml
  addons/account_budget/views/account_budget_views.xml
  addons/event_sale/models/sale_order.py
  addons/gamification/models/badge.py
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays/models/hr_holidays.py
  addons/hr_holidays/views/hr_holidays_views.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/lunch/views/lunch_views.xml
  addons/mrp/views/mrp_unbuild_views.xml
  addons/mrp_repair/views/mrp_repair_views.xml
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/screens.js
  addons/point_of_sale/views/pos_order_view.xml
  addons/point_of_sale/views/pos_session_view.xml
  addons/purchase_requisition/views/purchase_requisition_views.xml
  addons/sale/models/res_partner.py
  addons/stock/views/stock_inventory_views.xml
  addons/stock/views/stock_move_views.xml
  addons/stock_picking_batch/views/stock_picking_batch_views.xml
  addons/survey/views/survey_views.xml
  addons/web/static/src/js/fields/field_registry.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web_editor/models/ir_ui_view.py
  addons/website/static/src/js/tours/rte.js
  addons/website_event_sale/i18n/website_event_sale.pot
  addons/website_event_sale/models/__init__.py
  addons/website_event_sale/models/product_pricelist.py
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/views/unsubscribe_templates.xml
  addons/website_sale/models/website.py
  doc/cla/corporate/savoirfairelinux.md
  odoo/addons/base/ir/ir_qweb/qweb.py
  odoo/addons/base/ir/ir_rule.py
  odoo/addons/base/tests/test_expression.py
  odoo/models.py
  odoo/osv/expression.py
Labels: 11.0

#3245 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/tests/test_account_invoice_rounding.py
  addons/account/views/account_payment_view.xml
  addons/account/views/account_view.xml
  addons/account_asset/views/account_asset_views.xml
  addons/account_budget/views/account_budget_views.xml
  addons/event_sale/models/sale_order.py
  addons/gamification/models/badge.py
  addons/hr_holidays/report/hr_leave_reports.xml
  addons/lunch/views/lunch_views.xml
  addons/mrp/views/mrp_unbuild_views.xml
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
  addons/point_of_sale/static/src/js/screens.js
  addons/point_of_sale/views/pos_order_view.xml
  addons/point_of_sale/views/pos_session_view.xml
  addons/purchase_requisition/views/purchase_requisition_views.xml
  addons/repair/views/repair_views.xml
  addons/stock/views/stock_inventory_views.xml
  addons/stock/views/stock_move_views.xml
  addons/stock_picking_batch/views/stock_picking_batch_views.xml
  addons/survey/views/survey_views.xml
  addons/web/static/src/js/fields/field_registry.js
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/views/unsubscribe_templates.xml
  addons/website_sale/models/website.py
  odoo/addons/base/tests/test_views.py
  odoo/models.py
Labels: saas-11.3

#3247 Syncing from upstream odoo/odoo (saas-12.2)
  addons/gamification/data/gamification_karma_rank_data.xml
  addons/gamification/data/gamification_karma_rank_demo.xml
  addons/hr_skills/static/src/js/resume_widget.js
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/portal_chatter.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_profile/controllers/main.py
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/data/slide_channel_demo.xml
  addons/website_slides/data/slide_slide_demo.xml
  addons/website_slides/data/slide_user_demo.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/js/slides_share.js
  addons/website_slides/static/src/scss/slide_slide.scss
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/scss/website_slides_quiz.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  addons/website_slides/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides/views/assets.xml
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_forum/__manifest__.py
  addons/website_slides_forum/controllers/main.py
  addons/website_slides_forum/data/slide_channel_demo.xml
  addons/website_slides_forum/static/src/xml/website_slides_forum_channel.xml
  addons/website_slides_survey/__manifest__.py
  addons/website_slides_survey/controllers/slides.py
  addons/website_slides_survey/data/slide_slide_demo.xml
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/views/website_slides_templates_lesson.xml
  addons/website_slides_survey/views/website_slides_templates_lesson_fullscreen.xml
Labels: saas-12.2

#3248 Syncing from upstream odoo/odoo (saas-14)
  addons/gamification/models/badge.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
  addons/point_of_sale/static/src/js/screens.js
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/views/unsubscribe_templates.xml
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
Labels: saas-14

#3249 Syncing from upstream odoo/odoo (saas-15)
  addons/gamification/models/badge.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/tests/test_authorize.py
  addons/point_of_sale/static/src/js/screens.js
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/views/unsubscribe_templates.xml
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
Labels: saas-15

#3251 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/survey/data/mail_template_data.xml
  addons/survey/models/survey_survey.py
  addons/survey/models/survey_user.py
  addons/survey/static/src/js/tour_test_certification_failure.js
  addons/survey/static/src/js/tour_test_certification_success.js
  addons/survey/views/survey_survey_views.xml
  addons/survey/views/survey_templates.xml
  addons/survey/views/survey_user_views.xml
Labels: staging.saas-12.2

#3252 Syncing from upstream odoo/odoo (staging.10.0)
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/website_sale/models/sale_order.py
Labels: staging.10.0

#3255 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/survey/data/mail_template_data.xml
  addons/survey/models/survey_survey.py
  addons/survey/models/survey_user.py
  addons/survey/static/src/js/tour_test_certification_failure.js
  addons/survey/static/src/js/tour_test_certification_success.js
  addons/survey/views/survey_survey_views.xml
  addons/survey/views/survey_templates.xml
  addons/survey/views/survey_user_views.xml
Labels: tmp.saas-12.2

#3258 Syncing from upstream odoo/odoo (10.0)
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/portal/wizard/portal_wizard.py
  addons/website_sale/models/sale_order.py
  odoo/addons/base/res/res_partner.py
Labels: 10.0

#3260 Syncing from upstream odoo/odoo (12.0)
  MANIFEST.in
  addons/account/static/src/xml/account_reconciliation.xml
  addons/account/views/report_invoice.xml
  addons/l10n_es/data/account.account.template-common.csv
  addons/l10n_es/data/account.account.template-full.csv
  addons/l10n_es/data/account.account.template-pymes.csv
  addons/l10n_es/data/account_group.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/mail/models/ir_attachment.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/js/thread_widget.js
  addons/mrp/wizard/mrp_product_produce.py
  addons/payment/static/src/js/payment_processing.js
  addons/product/models/product_template.py
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase/report/purchase_quotation_templates.xml
  addons/repair/report/repair_templates_repair_order.xml
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_product_configurator_templates.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/controllers/main.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/field_manager_mixin.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/src/scss/form_view.scss
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web/static/tests/views/pivot_tests.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/models/website.py
  addons/website_sale_comparison/controllers/main.py
  doc/cla/corporate/decodio-applications.md
  doc/cla/individual/j-zaballa.md
  odoo/addons/base/models/ir_attachment.py
Labels: 12.0

#3262 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/static/src/xml/account_reconciliation.xml
  addons/account/views/report_invoice.xml
  addons/l10n_es/data/account_account_template_common_data.xml
  addons/l10n_es/data/account_account_template_full_data.xml
  addons/l10n_es/data/account_account_template_pymes_data.xml
  addons/l10n_es/data/account_group.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/mail/static/src/js/thread.js
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase/report/purchase_quotation_templates.xml
  addons/repair/report/repair_templates_repair_order.xml
  addons/sale/report/sale_report_templates.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/field_manager_mixin.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/less/form_view.less
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/models/website.py
  addons/website_sale_comparison/controllers/main.py
  doc/cla/individual/j-zaballa.md
Labels: saas-11.3

#3265 Syncing from upstream odoo/odoo (saas-14)
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/website_sale/models/sale_order.py
Labels: saas-14

#3266 Syncing from upstream odoo/odoo (saas-15)
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/website_sale/models/sale_order.py
Labels: saas-15

#3269 Syncing from upstream odoo/odoo (staging.saas-12.1)
  odoo/addons/base/models/res_partner.py
Labels: staging.saas-12.1

#3271 Syncing from upstream odoo/odoo (staging.10.0)
  addons/portal/wizard/portal_wizard.py
  odoo/addons/base/res/res_partner.py
Labels: staging.10.0

#3276 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  odoo/addons/base/models/res_partner.py
Labels: tmp.saas-12.1

#3278 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/portal/wizard/portal_wizard.py
  odoo/addons/base/res/res_partner.py
Labels: tmp.10.0

#3281 Syncing from upstream odoo/odoo (10.0)
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
Labels: 10.0

#3282 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_bank_statement.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/less/customer_facing_display.less
  addons/web/static/src/js/views/form/form_renderer.js
Labels: 11.0

#3283 Syncing from upstream odoo/odoo (12.0)
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/sale_timesheet/models/sale_order.py
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/controllers/main.py
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  odoo/fields.py
Labels: 12.0

#3284 Syncing from upstream odoo/odoo (master)
  addons/delivery/__manifest__.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/stock_picking.py
  addons/delivery/views/delivery_portal_template.xml
  addons/delivery/views/delivery_view.xml
  addons/pos_restaurant/static/lib/js/jquery.event.drag-2.2.js
  addons/pos_restaurant/static/lib/js/jquery.ui.touch-punch.js
  addons/pos_restaurant/static/src/js/floors.js
  addons/pos_restaurant/static/src/xml/floors.xml
  addons/pos_restaurant/views/pos_restaurant_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  odoo/addons/base/models/ir_qweb_fields.py
Labels: master

#3285 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: saas-11.3

#3286 Syncing from upstream odoo/odoo (saas-12.2)
  addons/gamification/models/res_users.py
  addons/website_forum/controllers/main.py
  addons/website_forum/data/forum_data.xml
  addons/website_forum/models/forum.py
  addons/website_forum/models/res_users.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/views/website_forum.xml
  addons/website_profile/__manifest__.py
  addons/website_profile/controllers/main.py
  addons/website_profile/data/profile_data.xml
  addons/website_profile/models/__init__.py
  addons/website_profile/models/res_users.py
  addons/website_profile/static/src/js/website_profile.js
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_rating/static/src/js/website_mail.js
  addons/website_rating/views/website_rating_templates.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/__init__.py
  addons/website_slides/tests/test_karma.py
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides_survey/controllers/slides.py
Labels: saas-12.2

#3288 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/static/src/xml/account_reconciliation.xml
  addons/account/views/report_invoice.xml
  addons/l10n_es/data/account_account_template_common_data.xml
  addons/l10n_es/data/account_account_template_full_data.xml
  addons/l10n_es/data/account_account_template_pymes_data.xml
  addons/l10n_es/data/account_group.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/data/account.account.template.csv
  addons/l10n_jp/data/account_chart_template_data.xml
  addons/mail/static/src/js/thread.js
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase/report/purchase_quotation_templates.xml
  addons/repair/report/repair_templates_repair_order.xml
  addons/sale/report/sale_report_templates.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/field_manager_mixin.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/less/form_view.less
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/models/website.py
  addons/website_sale_comparison/controllers/main.py
  doc/cla/individual/j-zaballa.md
Labels: staging.saas-11.3

#3290 Syncing from upstream odoo/odoo (staging.10.0)
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/web/static/lib/qweb/qweb2.js
Labels: staging.10.0

#3296 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/web/static/lib/qweb/qweb2.js
Labels: tmp.10.0

#3299 Syncing from upstream odoo/odoo (10.0)
  addons/web/static/lib/qweb/qweb2.js
Labels: 10.0

#3300 Syncing from upstream odoo/odoo (saas-12.2)
  addons/survey/controllers/main.py
  addons/survey/views/survey_templates.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_forum/views/website_slides_templates.xml
  addons/website_slides_survey/controllers/slides.py
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/static/src/js/slides_certification_download.js
  addons/website_slides_survey/static/src/js/slides_course_fullscreen_player.js
  addons/website_slides_survey/static/src/scss/website_slides.scss
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/views/assets.xml
  addons/website_slides_survey/views/website_profile.xml
  addons/website_slides_survey/views/website_slides_templates_course.xml
  addons/website_slides_survey/views/website_slides_templates_lesson.xml
  addons/website_slides_survey/views/website_slides_templates_lesson_fullscreen.xml
Labels: saas-12.2

#3306 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/i18n/es.po
  addons/account/i18n/mn.po
  addons/account/i18n/nl.po
  addons/account/i18n/ro.po
  addons/account/i18n/ru.po
  addons/account/i18n/tr.po
  addons/account/i18n/zh_CN.po
  addons/account_analytic_default/i18n/mn.po
  addons/account_bank_statement_import/i18n/es.po
  addons/account_bank_statement_import/i18n/mn.po
  addons/account_bank_statement_import/i18n/nl.po
  addons/account_check_printing/i18n/uk.po
  addons/account_payment/i18n/ro.po
  addons/account_voucher/i18n/mn.po
  addons/account_voucher/i18n/tr.po
  addons/analytic/i18n/mn.po
  addons/analytic/i18n/tr.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/mn.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/ro.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/uk.po
Labels: saas-12.1

#3307 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/base/res/res_currency.py
Labels: 10.0

#3308 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_invoice.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/point_of_sale/models/pos_order.py
  addons/portal/wizard/portal_wizard.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  odoo/addons/base/res/res_currency.py
  odoo/addons/base/res/res_partner.py
Labels: 11.0

#3309 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/static/src/js/worker.js
  addons/hw_screen/views/pos_display.html
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/models/ir_attachment.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_stock.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/payment/models/payment_acquirer.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/scss/customer_facing_display.scss
  addons/portal/wizard/portal_wizard.py
  addons/product/models/product_pricelist.py
  addons/project/views/project_portal_templates.xml
  addons/purchase/report/purchase_bill.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_http.py
  addons/website/models/ir_rule.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/data/data.xml
  addons/website_sale/data/demo.xml
  addons/website_sale/models/product.py
  addons/website_sale/models/res_partner.py
  addons/website_sale/models/website.py
  addons/website_sale/security/website_sale.xml
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/product_views.xml
  doc/reference/guidelines.rst
  odoo/addons/base/models/res_partner.py
Labels: 12.0

#3310 Syncing from upstream odoo/odoo (master)
  addons/im_livechat/static/src/js/models/website_livechat_message.js
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/res_company.py
  addons/web/controllers/main.py
  addons/web/static/src/img/user_placeholder.jpg
  addons/web/static/src/js/chrome/action_manager_act_window.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/js/widgets/ace.js
  addons/website/static/src/js/widgets/theme.js
  addons/website/static/src/scss/website.scss
  addons/website_event/views/event_templates.xml
  addons/website_slides/static/src/js/slides_category_add.js
  addons/website_slides/static/src/js/slides_slide_archive.js
  odoo/addons/base/models/ir_actions_report.py
Labels: master

#3311 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/account_asset/models/account.py
  addons/account_asset/models/account_asset.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_stock.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/less/customer_facing_display.less
  addons/portal/wizard/portal_wizard.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  odoo/addons/base/models/res_partner.py
Labels: saas-11.3

#3312 Syncing from upstream odoo/odoo (saas-12.2)
  addons/hr_recruitment/static/src/scss/hr_job.scss
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/tests/test_order.py
  addons/product/models/product_template.py
  addons/product/views/product_attribute_views.xml
  addons/stock/models/stock_move.py
  addons/website/static/src/js/editor/wysiwyg_multizone.js
  addons/website/static/src/js/tours/restricted_editor.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
Labels: saas-12.2

#3313 Syncing from upstream odoo/odoo (saas-14)
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/portal/wizard/portal_wizard.py
  addons/web/static/lib/qweb/qweb2.js
  odoo/addons/base/res/res_currency.py
  odoo/addons/base/res/res_partner.py
Labels: saas-14

#3314 Syncing from upstream odoo/odoo (saas-15)
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/portal/wizard/portal_wizard.py
  addons/web/static/lib/qweb/qweb2.js
  odoo/addons/base/res/res_currency.py
  odoo/addons/base/res/res_partner.py
Labels: saas-15

#3317 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/hr_recruitment/static/src/scss/hr_job.scss
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/tests/test_order.py
  addons/product/models/product_template.py
  addons/product/views/product_attribute_views.xml
  addons/stock/models/stock_move.py
  addons/website/static/src/js/editor/wysiwyg_multizone.js
  addons/website/static/src/js/tours/restricted_editor.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
Labels: staging.saas-12.2

#3318 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/base/res/res_currency.py
Labels: staging.10.0

#3323 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/hr_recruitment/static/src/scss/hr_job.scss
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/tests/test_order.py
  addons/product/models/product_template.py
  addons/product/views/product_attribute_views.xml
  addons/stock/models/stock_move.py
  addons/website/static/src/js/editor/wysiwyg_multizone.js
  addons/website/static/src/js/tours/restricted_editor.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
Labels: tmp.saas-12.2

#3324 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/base/res/res_currency.py
Labels: tmp.10.0

#3327 Syncing from upstream odoo/odoo (11.0)
  addons/mrp/models/mrp_workorder.py
  odoo/service/server.py
Labels: 11.0

#3328 Syncing from upstream odoo/odoo (12.0)
  addons/account/tests/test_account_supplier_invoice.py
  addons/analytic/models/analytic_account.py
  addons/mail/models/mail_activity.py
  addons/sale/report/sale_report_templates.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_sale/views/templates.xml
Labels: 12.0

#3330 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/tests/common.py
Labels: saas-11.3

#3331 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/static/src/js/worker.js
  addons/hw_screen/views/pos_display.html
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/link_tracker/models/link_tracker.py
  addons/mail/models/ir_attachment.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_stock.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/payment/models/payment_acquirer.py
  addons/payment/static/src/js/payment_processing.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/scss/customer_facing_display.scss
  addons/portal/wizard/portal_wizard.py
  addons/product/models/product_pricelist.py
  addons/project/views/project_portal_templates.xml
  addons/purchase/report/purchase_bill.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_http.py
  addons/website/models/ir_rule.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/controllers/main.py
  addons/website_links/static/src/js/test_ui_flow.js
  addons/website_links/static/src/js/website_links_charts.js
  addons/website_links/tests/test_ui.py
  addons/website_links/views/website_links_template.xml
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/data/data.xml
  addons/website_sale/data/demo.xml
  addons/website_sale/models/product.py
  addons/website_sale/models/res_partner.py
  addons/website_sale/models/website.py
  addons/website_sale/security/website_sale.xml
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/product_views.xml
  addons/website_sale/views/templates.xml
  doc/reference/guidelines.rst
  odoo/addons/base/models/res_partner.py
  odoo/fields.py
Labels: saas-12.1

#3332 Syncing from upstream odoo/odoo (saas-12.2)
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/delivery/wizard/choose_delivery_carrier.py
  addons/delivery/wizard/choose_delivery_carrier_views.xml
  addons/lunch/static/src/js/lunch_kanban_controller.js
  addons/lunch/static/src/js/lunch_kanban_mobile.js
  addons/lunch/static/src/js/lunch_kanban_record.js
  addons/lunch/static/src/js/lunch_kanban_view.js
  addons/lunch/static/src/js/lunch_kanban_widget.js
  addons/lunch/static/src/js/lunch_payment_dialog.js
  addons/lunch/static/src/scss/lunch_kanban.scss
  addons/lunch/static/src/xml/lunch_kanban.xml
  addons/lunch/static/tests/lunch_kanban_mobile_tests.js
  addons/lunch/static/tests/lunch_kanban_tests.js
  addons/lunch/static/tests/lunch_test_utils.js
  addons/lunch/static/tests/test_lunch_kanban.js
  addons/lunch/views/lunch_templates.xml
  addons/survey/data/mail_template_data.xml
  addons/web/static/src/scss/search_view_mobile.scss
  addons/website_event/views/event_templates.xml
  addons/website_forum/views/website_forum.xml
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_survey/__manifest__.py
  addons/website_slides_survey/controllers/survey.py
  addons/website_slides_survey/data/mail_template_data.xml
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/models/survey_user.py
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/tests/__init__.py
  addons/website_slides_survey/tests/test_course_certification_failure.py
  addons/website_slides_survey/views/survey_templates.xml
  addons/website_slides_survey/views/website_profile.xml
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: saas-12.2

#3334 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/account_asset/models/account.py
  addons/account_asset/models/account_asset.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/controllers/main.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_stock.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/less/customer_facing_display.less
  addons/portal/wizard/portal_wizard.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  odoo/addons/base/models/res_partner.py
  odoo/tests/common.py
Labels: staging.saas-11.3

#3335 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/static/src/js/worker.js
  addons/hw_screen/views/pos_display.html
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/models/ir_attachment.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_stock.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/payment/models/payment_acquirer.py
  addons/payment/static/src/js/payment_processing.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/scss/customer_facing_display.scss
  addons/portal/wizard/portal_wizard.py
  addons/product/models/product_pricelist.py
  addons/project/views/project_portal_templates.xml
  addons/purchase/report/purchase_bill.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_http.py
  addons/website/models/ir_rule.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_blog/static/src/js/website_blog.js
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/controllers/main.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/data/data.xml
  addons/website_sale/data/demo.xml
  addons/website_sale/models/product.py
  addons/website_sale/models/res_partner.py
  addons/website_sale/models/website.py
  addons/website_sale/security/website_sale.xml
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/product_views.xml
  addons/website_sale/views/templates.xml
  doc/reference/guidelines.rst
  odoo/addons/base/models/res_partner.py
  odoo/fields.py
Labels: staging.saas-12.1

#3336 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/delivery/wizard/choose_delivery_carrier.py
  addons/delivery/wizard/choose_delivery_carrier_views.xml
  addons/lunch/static/src/js/lunch_kanban_controller.js
  addons/lunch/static/src/js/lunch_kanban_mobile.js
  addons/lunch/static/src/js/lunch_kanban_record.js
  addons/lunch/static/src/js/lunch_kanban_view.js
  addons/lunch/static/src/js/lunch_kanban_widget.js
  addons/lunch/static/src/js/lunch_payment_dialog.js
  addons/lunch/static/src/scss/lunch_kanban.scss
  addons/lunch/static/src/xml/lunch_kanban.xml
  addons/lunch/static/tests/lunch_kanban_mobile_tests.js
  addons/lunch/static/tests/lunch_kanban_tests.js
  addons/lunch/static/tests/lunch_test_utils.js
  addons/lunch/static/tests/test_lunch_kanban.js
  addons/lunch/views/lunch_templates.xml
  addons/survey/data/mail_template_data.xml
  addons/web/static/src/scss/search_view_mobile.scss
  addons/website_event/views/event_templates.xml
  addons/website_forum/views/website_forum.xml
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_survey/__manifest__.py
  addons/website_slides_survey/controllers/survey.py
  addons/website_slides_survey/data/mail_template_data.xml
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/models/survey_user.py
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/tests/__init__.py
  addons/website_slides_survey/tests/test_course_certification_failure.py
  addons/website_slides_survey/views/survey_templates.xml
  addons/website_slides_survey/views/website_profile.xml
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: staging.saas-12.2

#3341 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_supplier_invoice.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/barcodes/static/tests/barcode_mobile_tests.js
  addons/barcodes/views/barcodes_templates.xml
  addons/hw_screen/static/src/js/worker.js
  addons/hw_screen/views/pos_display.html
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/models/ir_attachment.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_stock.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/payment/models/payment_acquirer.py
  addons/payment/static/src/js/payment_processing.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/scss/customer_facing_display.scss
  addons/portal/wizard/portal_wizard.py
  addons/product/models/product_pricelist.py
  addons/project/views/project_portal_templates.xml
  addons/purchase/report/purchase_bill.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_traceability.py
  addons/web/static/lib/qweb/qweb2.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_http.py
  addons/website/models/ir_rule.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_blog/static/src/js/website_blog.js
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/controllers/main.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/data/data.xml
  addons/website_sale/data/demo.xml
  addons/website_sale/models/product.py
  addons/website_sale/models/res_partner.py
  addons/website_sale/models/website.py
  addons/website_sale/security/website_sale.xml
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/product_views.xml
  addons/website_sale/views/templates.xml
  doc/reference/guidelines.rst
  odoo/addons/base/models/res_partner.py
  odoo/fields.py
Labels: tmp.saas-12.1

#3342 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/delivery/wizard/choose_delivery_carrier.py
  addons/delivery/wizard/choose_delivery_carrier_views.xml
  addons/lunch/static/src/js/lunch_kanban_controller.js
  addons/lunch/static/src/js/lunch_kanban_mobile.js
  addons/lunch/static/src/js/lunch_kanban_record.js
  addons/lunch/static/src/js/lunch_kanban_view.js
  addons/lunch/static/src/js/lunch_kanban_widget.js
  addons/lunch/static/src/js/lunch_payment_dialog.js
  addons/lunch/static/src/scss/lunch_kanban.scss
  addons/lunch/static/src/xml/lunch_kanban.xml
  addons/lunch/static/tests/lunch_kanban_mobile_tests.js
  addons/lunch/static/tests/lunch_kanban_tests.js
  addons/lunch/static/tests/lunch_test_utils.js
  addons/lunch/static/tests/test_lunch_kanban.js
  addons/lunch/views/lunch_templates.xml
  addons/survey/data/mail_template_data.xml
  addons/web/static/src/scss/search_view_mobile.scss
  addons/website_event/views/event_templates.xml
  addons/website_forum/views/website_forum.xml
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_slides/controllers/main.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  addons/website_slides_survey/__manifest__.py
  addons/website_slides_survey/controllers/survey.py
  addons/website_slides_survey/data/mail_template_data.xml
  addons/website_slides_survey/models/slide_slide.py
  addons/website_slides_survey/models/survey_user.py
  addons/website_slides_survey/static/src/xml/website_slides_fullscreen.xml
  addons/website_slides_survey/tests/__init__.py
  addons/website_slides_survey/tests/test_course_certification_failure.py
  addons/website_slides_survey/views/survey_templates.xml
  addons/website_slides_survey/views/website_profile.xml
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: tmp.saas-12.2

#3345 [ADD][t114050][bt#4762]
  addons/web/static/src/js/views/form_widgets.js
Labels: 10.0.project_he_222, enhancement

#3346 Syncing from upstream odoo/odoo (10.0)
  odoo/service/server.py
Labels: 10.0

#3347 Syncing from upstream odoo/odoo (11.0)
  addons/fleet/models/fleet_vehicle_cost.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mass_mailing.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_quote/models/sale_order.py
Labels: 11.0

#3348 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account.py
  addons/account/report/account_invoice_report.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/point_of_sale/views/pos_config_view.xml
  addons/purchase_requisition/models/purchase_requisition.py
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock_dropshipping/models/sale.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  doc/cla/individual/iledarn.md
  odoo/addons/base/models/res_partner.py
Labels: 12.0

#3349 Syncing from upstream odoo/odoo (master)
  addons/stock/report/report_stock_rule.py
  addons/stock/report/report_stock_rule.xml
  addons/website/models/__init__.py
  addons/website/models/res_config_settings.py
  addons/website/models/res_lang.py
Labels: master

#3350 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web_editor/static/src/less/web_editor.common.less
Labels: saas-11.3

#3351 Syncing from upstream odoo/odoo (saas-12.1)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_payroll/models/hr_benefit.py
  addons/hr_payroll/models/hr_employee.py
  addons/hr_payroll/tests/test_benefit.py
  addons/website_blog/static/src/js/website_blog.js
Labels: saas-12.1

#3354 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/web_editor/static/src/less/web_editor.common.less
Labels: staging.saas-11.3

#3357 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/service/server.py
Labels: staging.10.0

#3364 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/service/server.py
Labels: tmp.10.0

#3367 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/base/ir/ir_logging.py
Labels: 10.0

#3368 Syncing from upstream odoo/odoo (11.0)
  addons/crm/models/crm_team.py
  addons/payment_adyen/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/stock/views/stock_picking_views.xml
  addons/website_quote/views/website_quote_templates.xml
Labels: 11.0

#3369 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/base_iban/models/res_partner_bank.py
  addons/payment_adyen/models/payment.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/i18n/web.pot
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/editor/transcoder.js
Labels: 12.0

#3370 Syncing from upstream odoo/odoo (master)
  addons/account/models/account.py
  addons/account/security/account_security.xml
  addons/account/security/ir.model.access.csv
  addons/account/views/account_view.xml
  addons/account/wizard/account_invoice_refund.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/purchase_stock/tests/test_fifo_returns.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/tests/test_move2.py
  addons/stock/tests/test_warehouse.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock/wizard/stock_picking_return_views.xml
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/web/static/src/js/tools/debug_manager.js
  addons/web/static/src/js/tools/test_menus.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/views/ir_module_views.xml
Labels: master

#3374 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/base/ir/ir_logging.py
Labels: staging.10.0

#3379 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/base/ir/ir_logging.py
Labels: tmp.10.0

#3383 Syncing from upstream odoo/odoo (11.0)
  addons/http_routing/models/ir_http.py
  addons/website/models/ir_qweb.py
  addons/website/tests/test_qweb.py
  odoo/addons/base/ir/ir_logging.py
  odoo/service/server.py
Labels: 11.0

#3384 Syncing from upstream odoo/odoo (12.0)
  addons/auth_signup/data/auth_signup_data.xml
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_forum/views/website_forum.xml
  doc/webservices/upgrade.rst
  odoo/addons/base/tests/test_translate.py
  odoo/tools/translate.py
Labels: 12.0

#3385 Syncing from upstream odoo/odoo (master)
  addons/mail/wizard/mail_resend_message_views.xml
  addons/web/static/src/js/tools/test_menus.js
Labels: master

#3386 Syncing from upstream odoo/odoo (saas-12.2)
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_sale/static/src/js/website_sale.js
Labels: saas-12.2

#3387 Syncing from upstream odoo/odoo (saas-14)
  odoo/addons/base/ir/ir_logging.py
  odoo/service/server.py
Labels: saas-14

#3388 Syncing from upstream odoo/odoo (saas-15)
  odoo/addons/base/ir/ir_logging.py
  odoo/service/server.py
Labels: saas-15

#3390 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_sale/static/src/js/website_sale.js
Labels: staging.saas-12.2

#3395 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_sale/static/src/js/website_sale.js
Labels: tmp.saas-12.2

#3401 Syncing from upstream odoo/odoo (10.0)
  addons/mail/tests/test_mail_gateway.py
  addons/mail/tests/test_mail_message.py
Labels: 10.0

#3402 Syncing from upstream odoo/odoo (11.0)
  addons/http_routing/models/ir_http.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/tests/test_mail_gateway.py
  addons/mail/tests/test_mail_message.py
  addons/stock/models/stock_move.py
  addons/website/models/ir_qweb.py
  addons/website/tests/test_qweb.py
Labels: 11.0

#3403 Syncing from upstream odoo/odoo (12.0)
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mrp/models/mrp_workorder.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/product/views/product_template_views.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/models/stock_move.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  doc/cla/corporate/inspur.md
  odoo/addons/base/models/ir_logging.py
  odoo/service/server.py
Labels: 12.0

#3405 Syncing from upstream odoo/odoo (saas-11.3)
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mass_mailing/models/mass_mailing.py
  addons/mrp/models/mrp_workorder.py
  addons/payment_adyen/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/stock/models/stock_move.py
  addons/stock/views/stock_picking_views.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_quote/models/sale_order.py
  addons/website_quote/views/website_quote_templates.xml
  odoo/addons/base/models/ir_logging.py
  odoo/service/server.py
Labels: saas-11.3

#3406 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/base_iban/models/res_partner_bank.py
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/models/mail_activity.py
  addons/payment_adyen/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/product/views/product_template_views.xml
  addons/purchase_requisition/models/purchase.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock/views/stock_picking_views.xml
  addons/stock_dropshipping/models/sale.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/transcoder.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  addons/website_forum/static/src/scss/website_forum.scss
  doc/cla/corporate/inspur.md
  doc/cla/individual/iledarn.md
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
  odoo/tools/translate.py
Labels: saas-12.1

#3407 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mrp/views/mrp_production_views.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/common.py
  addons/website_slides/tests/test_karma.py
  addons/website_slides/tests/test_statistics.py
Labels: saas-12.2

#3408 Syncing from upstream odoo/odoo (saas-14)
  addons/mail/tests/test_mail_gateway.py
  addons/mail/tests/test_mail_message.py
Labels: saas-14

#3409 Syncing from upstream odoo/odoo (saas-15)
  addons/mail/tests/test_mail_gateway.py
  addons/mail/tests/test_mail_message.py
Labels: saas-15

#3411 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/payment_ogone/models/payment.py
Labels: staging.saas-12.1

#3413 Syncing from upstream odoo/odoo (staging.10.0)
  addons/mail/tests/test_mail_gateway.py
  addons/mail/tests/test_mail_message.py
Labels: staging.10.0

#3417 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/payment_ogone/models/payment.py
Labels: tmp.saas-12.1

#3419 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/mail/tests/test_mail_gateway.py
  addons/mail/tests/test_mail_message.py
Labels: tmp.10.0

#3422 Syncing from upstream odoo/odoo (10.0)
  addons/hw_escpos/escpos/constants.py
Labels: 10.0

#3423 Syncing from upstream odoo/odoo (11.0)
  addons/account_payment/views/account_portal_templates.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/website_sale_options/views/website_sale_options_templates.xml
Labels: 11.0

#3424 Syncing from upstream odoo/odoo (saas-12.2)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/base_iban/models/res_partner_bank.py
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/models/mail_activity.py
  addons/payment_adyen/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/product/views/product_template_views.xml
  addons/purchase_requisition/models/purchase.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock/views/stock_picking_views.xml
  addons/stock_dropshipping/models/sale.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  addons/website_forum/static/src/scss/website_forum.scss
  doc/cla/corporate/inspur.md
  doc/cla/individual/iledarn.md
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
  odoo/tools/translate.py
Labels: saas-12.2

#3426 Syncing from upstream odoo/odoo (staging.10.0)
  addons/hw_escpos/escpos/constants.py
Labels: staging.10.0

#3430 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/hw_escpos/escpos/constants.py
Labels: tmp.10.0

#3433 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/l10n_nl/data/account.account.template.csv
  addons/l10n_nl/data/account_fiscal_position_account_template.xml
  addons/l10n_nl/data/account_fiscal_position_tax_template.xml
  addons/l10n_nl/data/account_fiscal_position_template.xml
  addons/l10n_nl/i18n/l10n_nl.pot
  addons/payment/models/account_payment.py
  addons/product/i18n/product.pot
  addons/product/models/product_template.py
  addons/purchase/models/account_invoice.py
  addons/purchase/models/product.py
  addons/repair/models/repair.py
  addons/stock/wizard/stock_warn_insufficient_qty.py
  addons/stock/wizard/stock_warn_insufficient_qty_views.xml
  addons/website_sale/models/product.py
  odoo/addons/base/models/ir_actions_report.py
Labels: 12.0

#3434 Syncing from upstream odoo/odoo (master)
  addons/crm/wizard/crm_lead_to_opportunity_views.xml
  addons/crm/wizard/crm_partner_binding.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/sale_crm/__init__.py
  addons/sale_crm/__manifest__.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_crm/views/crm_lead_views.xml
  addons/sale_crm/wizard/__init__.py
  addons/sale_crm/wizard/crm_opportunity_to_quotation.py
  addons/sale_crm/wizard/crm_opportunity_to_quotation_views.xml
  addons/web/static/src/js/views/basic/basic_model.js
Labels: master

#3435 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web/static/src/js/core/dialog.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: saas-11.3

#3436 Syncing from upstream odoo/odoo (saas-12.1)
  addons/website_sale/models/product.py
Labels: saas-12.1

#3437 Syncing from upstream odoo/odoo (saas-12.2)
  addons/l10n_be_hr_payroll/views/l10n_be_hr_payroll_view.xml
Labels: saas-12.2

#3439 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mass_mailing/models/mass_mailing.py
  addons/mrp/models/mrp_workorder.py
  addons/payment_adyen/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/stock/models/stock_move.py
  addons/stock/views/stock_picking_views.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/core/dialog.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_quote/models/sale_order.py
  addons/website_quote/views/website_quote_templates.xml
  odoo/addons/base/models/ir_logging.py
  odoo/service/server.py
Labels: staging.saas-11.3

#3440 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/base_iban/models/res_partner_bank.py
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/models/mail_activity.py
  addons/payment_adyen/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/product/views/product_template_views.xml
  addons/purchase_requisition/models/purchase.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock/views/stock_picking_views.xml
  addons/stock_dropshipping/models/sale.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/transcoder.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_sale/models/product.py
  doc/cla/corporate/inspur.md
  doc/cla/individual/iledarn.md
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
  odoo/tools/translate.py
Labels: staging.saas-12.1

#3441 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/base_iban/models/res_partner_bank.py
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_be_hr_payroll/views/l10n_be_hr_payroll_view.xml
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/models/mail_activity.py
  addons/payment_adyen/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/product/views/product_template_views.xml
  addons/purchase_requisition/models/purchase.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock/views/stock_picking_views.xml
  addons/stock_dropshipping/models/sale.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  addons/website_forum/static/src/scss/website_forum.scss
  doc/cla/corporate/inspur.md
  doc/cla/individual/iledarn.md
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
  odoo/tools/translate.py
Labels: staging.saas-12.2

#3445 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/base_iban/models/res_partner_bank.py
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/models/mail_activity.py
  addons/payment_adyen/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/product/views/product_template_views.xml
  addons/purchase_requisition/models/purchase.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock/views/stock_picking_views.xml
  addons/stock_dropshipping/models/sale.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/transcoder.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_sale/models/product.py
  doc/cla/corporate/inspur.md
  doc/cla/individual/iledarn.md
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
  odoo/tools/translate.py
Labels: tmp.saas-12.1

#3446 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/report/account_invoice_report.py
  addons/auth_signup/data/auth_signup_data.xml
  addons/base_iban/models/res_partner_bank.py
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_team.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/hr_holidays/static/scss/hr_leave_mobile.scss
  addons/hr_holidays/views/hr_leave_template.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_be_hr_payroll/views/l10n_be_hr_payroll_view.xml
  addons/l10n_tr/__manifest__.py
  addons/l10n_tr/data/res.country.state.csv
  addons/mail/models/mail_activity.py
  addons/payment_adyen/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_stripe/static/src/js/stripe.js
  addons/payment_stripe/views/payment_stripe_templates.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/product/views/product_template_views.xml
  addons/purchase_requisition/models/purchase.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/static/src/js/stock_traceability_report_widgets.js
  addons/stock/views/stock_picking_views.xml
  addons/stock_dropshipping/models/sale.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_event/controllers/main.py
  addons/website_event_sale/controllers/main.py
  addons/website_forum/static/src/scss/website_forum.scss
  doc/cla/corporate/inspur.md
  doc/cla/individual/iledarn.md
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_translate.py
  odoo/service/server.py
  odoo/tools/translate.py
Labels: tmp.saas-12.2

#3448 Syncing from upstream odoo/odoo (11.0)
  addons/mass_mailing/models/mass_mailing.py
Labels: 11.0

#3449 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/account/views/report_invoice.xml
  addons/delivery/models/stock_picking.py
  addons/repair/models/repair.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
Labels: 12.0

#3451 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
Labels: saas-12.2

#3454 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
Labels: staging.saas-12.2

#3458 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
Labels: tmp.saas-12.2

#3461 Syncing from upstream odoo/odoo (10.0)
  addons/hw_escpos/escpos/constants.py
Labels: 10.0

#3462 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/hw_escpos/escpos/constants.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/product/views/product_template_views.xml
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: 11.0

#3463 Syncing from upstream odoo/odoo (12.0)
  addons/account_check_printing/models/account_payment.py
  addons/mrp/report/mrp_report_bom_structure.py
Labels: 12.0

#3464 Syncing from upstream odoo/odoo (master)
  addons/account/views/account_analytic_view.xml
  addons/account/views/account_cash_rounding_view.xml
  addons/account/views/account_invoice_view.xml
  addons/account/views/account_move_views.xml
  addons/account/views/account_payment_view.xml
  addons/account/views/account_view.xml
  addons/account/wizard/wizard_tax_adjustments_view.xml
  addons/account_voucher/views/account_voucher_views.xml
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/mail/models/__init__.py
  addons/mail/models/mail_cc_mixin.py
  addons/mail/static/src/js/composers/chatter_composer.js
  addons/mail/static/src/xml/chatter.xml
  addons/maintenance/models/maintenance.py
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_workorder_operation.py
  addons/mrp/views/mrp_bom_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/wizard/mrp_product_produce.py
  addons/payment_payulatam/views/payment_views.xml
  addons/project/models/project.py
  addons/sale/wizard/sale_make_invoice_advance_views.xml
  addons/stock/views/product_strategy_views.xml
  addons/stock/views/product_views.xml
  addons/stock_account/views/product_views.xml
  addons/stock_account/views/stock_account_views.xml
  addons/stock_account/wizard/stock_change_standard_price_views.xml
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_cc.py
  addons/web/static/tests/helpers/test_utils_create.js
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/views/res_partner_views.xml
  odoo/tools/mail.py
Labels: master

#3465 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account_payment/views/account_portal_templates.xml
  addons/hw_escpos/escpos/constants.py
  addons/l10n_fr/data/account_tax_data.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/product/views/product_template_views.xml
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
  addons/website_sale_options/views/website_sale_options_templates.xml
Labels: saas-11.3

#3466 Syncing from upstream odoo/odoo (saas-12.1)
  addons/mail/static/src/js/document_viewer.js
Labels: saas-12.1

#3467 Syncing from upstream odoo/odoo (saas-12.2)
  addons/web/static/src/js/chrome/abstract_action.js
  addons/web/static/src/scss/form_view.scss
Labels: saas-12.2

#3468 Syncing from upstream odoo/odoo (saas-14)
  addons/hw_escpos/escpos/constants.py
Labels: saas-14

#3469 Syncing from upstream odoo/odoo (saas-15)
  addons/hw_escpos/escpos/constants.py
Labels: saas-15

#3471 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/mail/static/src/js/document_viewer.js
Labels: staging.saas-12.1

#3472 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/web/static/src/js/chrome/abstract_action.js
  addons/web/static/src/scss/form_view.scss
Labels: staging.saas-12.2

#3477 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/mail/static/src/js/document_viewer.js
Labels: tmp.saas-12.1

#3478 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/web/static/src/js/chrome/abstract_action.js
  addons/web/static/src/scss/form_view.scss
Labels: tmp.saas-12.2
