Repository brain-tec/odoo, pull requests merged in 2019-11, with the labels that each got.

#6137 Syncing from upstream odoo/odoo (11.0)
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  addons/website_form/static/src/js/website_form.js
  odoo/osv/expression.py
Labels: 11.0

#6138 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/account/views/account_invoice_view.xml
  addons/google_calendar/models/google_calendar.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  addons/payment_adyen/models/payment.py
  addons/payment_authorize/models/payment.py
  addons/payment_buckaroo/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_paypal/models/payment.py
  addons/payment_payumoney/models/payment.py
  addons/payment_sips/models/payment.py
  addons/website_sale/models/sale_order.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: 12.0

#6139 Syncing from upstream odoo/odoo (13.0)
  addons/account/views/account_move_views.xml
  addons/account_bank_statement_import/account_bank_statement_import.py
  addons/event_sale/models/event.py
  addons/hr_fleet/models/employee.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/models/__init__.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/payment_adyen/models/payment.py
  addons/payment_authorize/models/payment.py
  addons/payment_buckaroo/models/payment.py
  addons/payment_ingenico/models/payment.py
  addons/payment_paypal/models/payment.py
  addons/payment_payumoney/models/payment.py
  addons/payment_sips/models/payment.py
  addons/web/static/src/js/views/control_panel/search/add_new_favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/filter_menu.js
  addons/web/static/src/js/views/control_panel/search/groupby_menu.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/src/js/widgets/dropdown_menu.js
  addons/web/static/src/scss/form_view.scss
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/views/form_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website_forum/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  odoo/http.py
  odoo/models.py
Labels: 13.0

#6140 Syncing from upstream odoo/odoo (master)
  addons/account/views/account_move_views.xml
  addons/http_routing/models/ir_http.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/models/__init__.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_do/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/payment_adyen/models/payment.py
  addons/payment_authorize/models/payment.py
  addons/payment_buckaroo/models/payment.py
  addons/payment_ingenico/models/payment.py
  addons/payment_paypal/models/payment.py
  addons/payment_payumoney/models/payment.py
  addons/payment_sips/models/payment.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/views/pos_config_view.xml
  addons/pos_mercury/__manifest__.py
  addons/pos_mercury/views/pos_config_views.xml
  addons/sale/report/sale_report.py
  addons/web/static/src/js/views/control_panel/search/add_new_favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/filter_menu.js
  addons/web/static/src/js/views/control_panel/search/groupby_menu.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/src/js/widgets/dropdown_menu.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  odoo/addons/base/models/ir_fields.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_model.py
  odoo/http.py
Labels: master

#6141 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: saas-11.3

#6142 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/payment_adyen/models/payment.py
  addons/payment_authorize/models/payment.py
  addons/payment_buckaroo/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_paypal/models/payment.py
  addons/payment_payumoney/models/payment.py
  addons/payment_sips/models/payment.py
  addons/point_of_sale/models/pos_order.py
  addons/stock/models/stock_move.py
  addons/web/static/src/js/views/control_panel/search/add_new_favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/filter_menu.js
  addons/web/static/src/js/views/control_panel/search/groupby_menu.js
  addons/web/static/src/js/widgets/dropdown_menu.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: saas-12.3

#6144 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: staging.saas-11.3

#6145 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/payment_adyen/models/payment.py
  addons/payment_authorize/models/payment.py
  addons/payment_buckaroo/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_paypal/models/payment.py
  addons/payment_payumoney/models/payment.py
  addons/payment_sips/models/payment.py
  addons/point_of_sale/models/pos_order.py
  addons/stock/models/stock_move.py
  addons/web/static/src/js/views/control_panel/search/add_new_favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/filter_menu.js
  addons/web/static/src/js/views/control_panel/search/groupby_menu.js
  addons/web/static/src/js/widgets/dropdown_menu.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: staging.saas-12.3

#6150 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: tmp.saas-11.3

#6151 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_reconciliation.py
  addons/payment_adyen/models/payment.py
  addons/payment_authorize/models/payment.py
  addons/payment_buckaroo/models/payment.py
  addons/payment_ogone/models/payment.py
  addons/payment_paypal/models/payment.py
  addons/payment_payumoney/models/payment.py
  addons/payment_sips/models/payment.py
  addons/point_of_sale/models/pos_order.py
  addons/stock/models/stock_move.py
  addons/web/static/src/js/views/control_panel/search/add_new_favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/filter_menu.js
  addons/web/static/src/js/views/control_panel/search/groupby_menu.js
  addons/web/static/src/js/widgets/dropdown_menu.js
  addons/web/static/src/xml/base.xml
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  odoo/osv/expression.py
  odoo/tests/common.py
Labels: tmp.saas-12.3

#6155 Syncing from upstream odoo/odoo (12.0)
  addons/website_form/static/src/js/website_form.js
Labels: 12.0

#6156 Syncing from upstream odoo/odoo (13.0)
  addons/website_form/static/src/js/website_form.js
Labels: 13.0

#6157 Syncing from upstream odoo/odoo (master)
  addons/website_form/static/src/js/website_form.js
  addons/website_forum/controllers/main.py
  odoo/models.py
Labels: master

#6158 Syncing from upstream odoo/odoo (saas-11.3)
  addons/website_form/static/src/js/website_form.js
Labels: saas-11.3

#6159 Syncing from upstream odoo/odoo (saas-12.3)
  addons/website_form/static/src/js/website_form.js
Labels: saas-12.3

#6161 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/website_form/static/src/js/website_form.js
Labels: staging.saas-11.3

#6162 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/website_form/static/src/js/website_form.js
Labels: staging.saas-12.3

#6166 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/website_form/static/src/js/website_form.js
Labels: tmp.saas-11.3

#6167 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/website_form/static/src/js/website_form.js
Labels: tmp.saas-12.3

#6170 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/tests/common.py
Labels: saas-12.3

#6171 Syncing from upstream odoo/odoo (staging.saas-12.3)
  odoo/tests/common.py
Labels: staging.saas-12.3

#6172 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  odoo/tests/common.py
Labels: tmp.saas-12.3

#6178 Syncing from upstream odoo/odoo (11.0)
  addons/account/views/account_view.xml
  addons/event/models/event_mail.py
  odoo/service/server.py
Labels: 11.0

#6179 Syncing from upstream odoo/odoo (12.0)
  addons/payment_stripe/tests/test_stripe.py
  addons/sale/i18n/sale.pot
  addons/sale/models/payment.py
  addons/sale/tests/test_sale_transaction.py
  addons/web/views/report_templates.xml
  odoo/service/server.py
Labels: 12.0

#6180 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/link_tracker/models/link_tracker.py
  addons/mass_mailing_sms/models/sms_sms.py
  addons/mrp/static/src/js/mrp_bom_report.js
  addons/payment_stripe/static/src/js/payment_form.js
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale/models/sale.py
  addons/sale_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_product_matrix/views/assets.xml
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/product.py
  addons/stock/models/stock_inventory.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/web/static/src/js/views/form/form_controller.js
  addons/web_editor/static/src/js/editor/editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_snippets.js
  addons/website/static/src/js/editor/wysiwyg_multizone_translate.js
  addons/website_sale/controllers/main.py
  doc/howtos/website.rst
  doc/reference/data.rst
  doc/reference/orm.rst
  doc/setup/install.rst
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/api.py
  odoo/exceptions.py
  odoo/fields.py
  odoo/models.py
  odoo/osv/expression.py
  odoo/service/server.py
  odoo/tests/common.py
Labels: 13.0

#6181 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/calendar/models/calendar.py
  addons/event_sale/models/event.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/google_calendar.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mrp/static/src/js/mrp_bom_report.js
  addons/payment_stripe/static/src/js/payment_form.js
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/product_expiry/models/product_product.py
  addons/product_expiry/views/stock_quant_views.xml
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_product_matrix/views/assets.xml
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/product.py
  addons/stock/models/stock_inventory.py
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/src/js/views/form/form_renderer.js
  addons/web/static/src/scss/form_view.scss
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/editor/editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_snippets.js
  addons/website/static/src/js/editor/wysiwyg_multizone_translate.js
  addons/website_sale/controllers/main.py
  addons/website_slides/tests/test_ui_wslides.py
  doc/howtos/website.rst
  doc/reference/data.rst
  doc/reference/orm.rst
  odoo/addons/base/models/ir_fields.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/addons/test_impex/tests/test_load.py
  odoo/api.py
  odoo/exceptions.py
  odoo/fields.py
  odoo/models.py
  odoo/osv/expression.py
  odoo/service/server.py
  odoo/tests/common.py
  odoo/tools/__init__.py
Labels: master

#6182 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/service/server.py
Labels: saas-11.3

#6183 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/views/account_invoice_view.xml
  addons/payment_stripe/tests/test_stripe.py
  addons/sale/i18n/sale.pot
  addons/sale/models/payment.py
  addons/sale/tests/test_sale_transaction.py
  odoo/addons/base/tests/test_view_validation.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/service/server.py
  odoo/tools/view_validation.py
Labels: saas-12.3

#6185 Syncing from upstream odoo/odoo (staging.saas-11.3)
  odoo/service/server.py
Labels: staging.saas-11.3

#6186 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/views/account_invoice_view.xml
  addons/payment_stripe/tests/test_stripe.py
  addons/sale/i18n/sale.pot
  addons/sale/models/payment.py
  addons/sale/tests/test_sale_transaction.py
  odoo/addons/base/tests/test_view_validation.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/service/server.py
  odoo/tools/view_validation.py
Labels: staging.saas-12.3

#6191 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  odoo/service/server.py
Labels: tmp.saas-11.3

#6192 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/views/account_invoice_view.xml
  addons/payment_stripe/tests/test_stripe.py
  addons/sale/i18n/sale.pot
  addons/sale/models/payment.py
  addons/sale/tests/test_sale_transaction.py
  odoo/addons/base/tests/test_view_validation.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/service/server.py
  odoo/tools/view_validation.py
Labels: tmp.saas-12.3

#6197 Syncing from upstream odoo/odoo (11.0)
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/views/list_tests.js
  odoo/addons/base/ir/ir_http.py
Labels: 11.0

#6198 Syncing from upstream odoo/odoo (12.0)
  addons/account/static/src/js/bank_statement.js
  addons/event/models/event_mail.py
  addons/hr/static/xls/hr_employee.xls
  addons/project/views/project_views.xml
  addons/purchase/static/xls/product_purchase.xls
  odoo/addons/base/models/ir_http.py
Labels: 12.0

#6199 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_reconcile_model.py
  addons/account/models/reconciliation_widget.py
  addons/account/static/src/js/bank_statement.js
  addons/account/static/tests/tours/reconciliation.js
  addons/event/models/event_mail.py
  addons/project/views/project_views.xml
  addons/website_sale/security/website_sale.xml
  doc/setup/install.rst
  odoo/addons/base/models/ir_model.py
  setup/package.py
  setup/win32/Makefile
  setup/win32/setup.nsi
Labels: 13.0

#6200 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_bank_statement.py
  addons/account/static/src/js/bank_statement.js
  addons/account/tests/__init__.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/account_view.xml
  addons/event/models/event_mail.py
  addons/gamification/__manifest__.py
  addons/gamification/data/cron.xml
  addons/gamification/data/gamification_karma_rank_demo.xml
  addons/gamification/data/gamification_karma_tracking_demo.xml
  addons/gamification/models/__init__.py
  addons/gamification/models/gamification_karma_tracking.py
  addons/gamification/models/res_users.py
  addons/gamification/security/ir.model.access.csv
  addons/gamification/tests/__init__.py
  addons/gamification/tests/test_karma_tracking.py
  addons/gamification/tests/test_recompute_rank.py
  addons/gamification/views/gamification_karma_tracking_views.xml
  addons/link_tracker/models/link_tracker.py
  addons/mass_mailing_sms/models/sms_sms.py
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/screens.js
  addons/point_of_sale/static/src/xml/pos.xml
  addons/point_of_sale/static/tests/tours/point_of_sale.js
  addons/pos_mercury/static/src/css/pos_mercury.css
  addons/pos_mercury/static/src/js/pos_mercury.js
  addons/pos_mercury/static/src/xml/pos_mercury.xml
  addons/project/views/project_views.xml
  addons/sale/models/account_move.py
  addons/sale/models/sale.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_sale/security/website_sale.xml
  doc/reference/javascript_reference.rst
  doc/reference/testing.rst
  doc/setup/install.rst
  odoo/addons/base/models/ir_model.py
  odoo/http.py
  odoo/tests/common.py
  odoo/tools/convert.py
  odoo/tools/pycompat.py
  odoo/tools/safe_eval.py
  setup/package.py
  setup/win32/Makefile
  setup/win32/setup.nsi
Labels: master

#6201 Syncing from upstream odoo/odoo (saas-11.3)
  addons/event/models/event_mail.py
  odoo/addons/base/models/ir_http.py
Labels: saas-11.3

#6202 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/static/src/js/bank_statement.js
  addons/event/models/event_mail.py
  addons/project/views/project_views.xml
  addons/stock/security/stock_security.xml
  odoo/addons/base/models/ir_http.py
Labels: saas-12.3

#6204 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/event/models/event_mail.py
  odoo/addons/base/models/ir_http.py
Labels: staging.saas-11.3

#6205 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/static/src/js/bank_statement.js
  addons/event/models/event_mail.py
  addons/project/views/project_views.xml
  addons/stock/security/stock_security.xml
  odoo/addons/base/models/ir_http.py
Labels: staging.saas-12.3

#6210 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/event/models/event_mail.py
  odoo/addons/base/models/ir_http.py
Labels: tmp.saas-11.3

#6211 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/static/src/js/bank_statement.js
  addons/event/models/event_mail.py
  addons/project/views/project_views.xml
  addons/stock/security/stock_security.xml
  odoo/addons/base/models/ir_http.py
Labels: tmp.saas-12.3

#6196 [bt#5741] [FIX] account: multi-currencies fixes
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_payment.py
  addons/account/tests/test_reconciliation.py
Labels: 11.0.project_qt_291.test

#6215 Syncing from upstream odoo/odoo (11.0)
  addons/hr/views/hr_views.xml
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
  doc/reference/module.rst
Labels: 11.0

#6216 Syncing from upstream odoo/odoo (12.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/calendar/models/calendar.py
  addons/calendar/static/src/js/base_calendar.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_in/views/report_invoice.xml
  doc/reference/module.rst
Labels: 12.0

#6217 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/wizard/account_invoice_send.py
  addons/crm/static/xls/crm_lead.xls
  addons/crm/views/res_config_settings_views.xml
  addons/hr/static/xls/hr_employee.xls
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mass_mailing_sms/models/mailing_mailing.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/common.py
  addons/product/static/xls/product_pricelist.xls
  addons/product/static/xls/product_template.xls
  addons/purchase/static/xls/product_purchase.xls
  addons/sale_management/models/digest.py
  addons/stock/security/stock_security.xml
  addons/survey/static/src/js/survey_result.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website/static/src/js/menu/content.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  doc/cla/individual/sebisnow.md
  doc/reference/module.rst
  doc/setup/deploy.rst
  odoo/addons/base/static/xls/res_partner.xls
Labels: 13.0

#6219 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/views/list_tests.js
  doc/reference/module.rst
Labels: saas-11.3

#6220 Syncing from upstream odoo/odoo (saas-12.3)
  addons/calendar/models/calendar.py
  addons/calendar/static/src/js/base_calendar.js
  addons/hr/static/xls/hr_employee.xls
  addons/hr/views/hr_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/purchase/static/xls/product_purchase.xls
  addons/sale/i18n/fr.po
  addons/survey/static/src/js/survey_result.js
  addons/web/views/report_templates.xml
  addons/website_slides/static/src/js/slides_course_quiz.js
  doc/reference/module.rst
Labels: saas-12.3

#6222 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/views/list_tests.js
  doc/reference/module.rst
Labels: staging.saas-11.3

#6223 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/calendar/models/calendar.py
  addons/calendar/static/src/js/base_calendar.js
  addons/hr/static/xls/hr_employee.xls
  addons/hr/views/hr_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/purchase/static/xls/product_purchase.xls
  addons/sale/i18n/fr.po
  addons/survey/static/src/js/survey_result.js
  addons/web/views/report_templates.xml
  addons/website_slides/static/src/js/slides_course_quiz.js
  doc/reference/module.rst
Labels: staging.saas-12.3

#6228 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/views/list_tests.js
  doc/reference/module.rst
Labels: tmp.saas-11.3

#6229 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/calendar/models/calendar.py
  addons/calendar/static/src/js/base_calendar.js
  addons/hr/static/xls/hr_employee.xls
  addons/hr/views/hr_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/purchase/static/xls/product_purchase.xls
  addons/sale/i18n/fr.po
  addons/survey/static/src/js/survey_result.js
  addons/web/views/report_templates.xml
  addons/website_slides/static/src/js/slides_course_quiz.js
  doc/reference/module.rst
Labels: tmp.saas-12.3

#6233 Syncing from upstream odoo/odoo (11.0)
  addons/hr_expense/models/hr_expense.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/stock/views/stock_inventory_views.xml
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: 11.0

#6234 Syncing from upstream odoo/odoo (12.0)
  addons/crm/models/calendar.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/lunch/models/lunch.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/purchase_requisition/models/purchase_requisition.py
  addons/sale/static/src/scss/sale_portal.scss
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: 12.0

#6235 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/calendar/models/calendar.py
  addons/calendar/static/src/js/base_calendar.js
  addons/crm/models/calendar.py
  addons/event/models/res_partner.py
  addons/hr/views/hr_views.xml
  addons/l10n_in/views/report_invoice.xml
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/sale/static/src/scss/sale_portal.scss
  addons/website/models/website_visitor.py
  addons/website_sale/views/res_config_settings_views.xml
Labels: 13.0

#6237 Syncing from upstream odoo/odoo (saas-11.3)
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: saas-11.3

#6238 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/crm/models/calendar.py
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale/static/src/scss/sale_portal.scss
  addons/stock/models/stock_move.py
  addons/web/static/tests/views/list_tests.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: saas-12.3

#6240 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: staging.saas-11.3

#6241 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/crm/models/calendar.py
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale/static/src/scss/sale_portal.scss
  addons/stock/models/stock_move.py
  addons/web/static/tests/views/list_tests.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: staging.saas-12.3

#6246 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: tmp.saas-11.3

#6247 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/crm/models/calendar.py
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale/static/src/scss/sale_portal.scss
  addons/stock/models/stock_move.py
  addons/web/static/tests/views/list_tests.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: tmp.saas-12.3

#6251 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/partner.py
Labels: 11.0

#6252 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/static/src/scss/section_and_note_backend.scss
  addons/crm/models/crm_lead.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: 12.0

#6253 Syncing from upstream odoo/odoo (13.0)
  README.md
  addons/account/models/account.py
  addons/crm/models/crm_lead.py
  addons/google_calendar/models/google_calendar.py
  addons/hw_drivers/drivers/KeyboardUSBDriver.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/sale_timesheet_purchase/models/project_overview.py
  addons/web/static/tests/views/list_tests.js
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_event/views/event_templates.xml
  doc/cla/individual/fr3aker.md
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: 13.0

#6254 Syncing from upstream odoo/odoo (master)
  addons/account/models/account.py
  addons/account/models/company.py
  addons/crm/models/crm_lead.py
  addons/crm/static/xls/crm_lead.xls
  addons/hw_drivers/drivers/KeyboardUSBDriver.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/product/static/xls/product_pricelist.xls
  addons/product/static/xls/product_template.xls
  addons/purchase_requisition/models/purchase_requisition.py
  addons/stock/models/res_company.py
  addons/web/static/tests/views/list_tests.js
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_event/views/event_templates.xml
  doc/cla/individual/fr3aker.md
  odoo/addons/base/models/res_users.py
  odoo/addons/base/static/xls/res_partner.xls
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
  odoo/fields.py
Labels: master

#6255 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/partner.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: saas-11.3

#6256 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/crm/models/crm_lead.py
  addons/google_calendar/models/google_calendar.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/sale_timesheet/models/sale_order.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: saas-12.3

#6258 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/partner.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: staging.saas-11.3

#6259 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/crm/models/crm_lead.py
  addons/google_calendar/models/google_calendar.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/sale_timesheet/models/sale_order.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: staging.saas-12.3

#6264 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/models/partner.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: tmp.saas-11.3

#6265 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/crm/models/crm_lead.py
  addons/google_calendar/models/google_calendar.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/sale_timesheet/models/sale_order.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: tmp.saas-12.3

#6274 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_move.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  odoo/addons/base/ir/ir_filters.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: 11.0

#6275 Syncing from upstream odoo/odoo (12.0)
  addons/calendar/controllers/main.py
  addons/hr/views/hr_views.xml
  addons/membership/models/membership.py
  addons/membership/models/partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: 12.0

#6276 Syncing from upstream odoo/odoo (13.0)
  addons/calendar/controllers/main.py
  addons/hw_drivers/drivers/KeyboardUSBDriver.py
  addons/l10n_lu/data/account.account.template-2011.csv
  addons/l10n_lu/data/account.tax.group.csv
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mrp/views/ir_attachment_view.xml
  addons/sale/models/sales_team.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_move.py
  addons/test_mail/tests/test_mail_mail.py
  addons/web/static/lib/unhandled-rejection-polyfill/unhandled-rejection-polyfill.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/static/src/js/backend/field_html.js
  doc/cla/individual/niyasraphy.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/test_markers.py
  odoo/fields.py
Labels: 13.0

#6279 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/reconciliation_widget.py
  addons/hr/views/hr_views.xml
  addons/stock/views/stock_inventory_views.xml
  odoo/addons/test_lint/tests/test_markers.py
Labels: saas-11.3

#6282 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/reconciliation_widget.py
  addons/hr/views/hr_views.xml
  addons/stock/views/stock_inventory_views.xml
  odoo/addons/test_lint/tests/test_markers.py
Labels: staging.saas-11.3

#6283 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/calendar/controllers/main.py
  addons/membership/models/membership.py
  addons/membership/models/partner.py
  addons/mrp/views/ir_attachment_view.xml
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: staging.saas-12.3

#6288 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/models/reconciliation_widget.py
  addons/hr/views/hr_views.xml
  addons/stock/views/stock_inventory_views.xml
  odoo/addons/test_lint/tests/test_markers.py
Labels: tmp.saas-11.3

#6289 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/calendar/controllers/main.py
  addons/membership/models/membership.py
  addons/membership/models/partner.py
  addons/mrp/views/ir_attachment_view.xml
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_lint/tests/test_markers.py
Labels: tmp.saas-12.3

#6293 [bt#5741] Fehlermeldung Verbuchung Kredi.-Zsahllauf
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_payment.py
  addons/account/tests/test_reconciliation.py
Labels: 11.0.project_qt_291

#6294 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/gui.js
  addons/stock/models/stock_move.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_filters.py
Labels: 12.0

#6295 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/account_move_views.xml
  addons/account/views/account_payment_view.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_workorder_operation.py
  addons/mrp/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/db.js
  addons/pos_restaurant/static/src/js/floors.js
  addons/pos_restaurant/static/src/js/tours/pos_restaurant.js
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_dropshipping/views/sale_order_views.xml
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/content.js
  addons/website_form/static/src/js/website_form_editor.js
  odoo/addons/base/models/ir_filters.py
  odoo/addons/base/models/ir_rule.py
Labels: 13.0

#6297 Syncing from upstream odoo/odoo (saas-11.3)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  odoo/addons/base/models/ir_filters.py
Labels: saas-11.3

#6298 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_move_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/tests/test_order.py
  addons/portal/static/src/scss/portal.scss
  addons/stock/models/stock_move.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  addons/web/static/lib/unhandled-rejection-polyfill/unhandled-rejection-polyfill.js
  addons/web/views/webclient_templates.xml
  odoo/addons/base/models/ir_filters.py
Labels: saas-12.3

#6300 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/views/account_view.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  odoo/addons/base/models/ir_filters.py
Labels: staging.saas-11.3

#6301 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_move_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/tests/test_order.py
  addons/portal/static/src/scss/portal.scss
  addons/stock/models/stock_move.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  addons/web/static/lib/unhandled-rejection-polyfill/unhandled-rejection-polyfill.js
  addons/web/views/webclient_templates.xml
  odoo/addons/base/models/ir_filters.py
Labels: staging.saas-12.3

#6305 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/views/account_view.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  odoo/addons/base/models/ir_filters.py
Labels: tmp.saas-11.3

#6306 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_move_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/tests/test_order.py
  addons/portal/static/src/scss/portal.scss
  addons/stock/models/stock_move.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_dropshipping/views/sale_order_views.xml
  addons/web/static/lib/unhandled-rejection-polyfill/unhandled-rejection-polyfill.js
  addons/web/views/webclient_templates.xml
  odoo/addons/base/models/ir_filters.py
Labels: tmp.saas-12.3

#6309 Syncing from upstream odoo/odoo (11.0)
  addons/mrp/models/stock_move.py
  addons/stock/models/stock_move.py
Labels: 11.0

#6310 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account_check_printing/i18n/account_check_printing.pot
  addons/account_voucher/i18n/account_voucher.pot
  addons/auth_oauth/i18n/auth_oauth.pot
  addons/base_automation/i18n/base_automation.pot
  addons/base_geolocalize/i18n/base_geolocalize.pot
  addons/calendar/data/mail_data.xml
  addons/calendar/models/calendar.py
  addons/crm/__init__.py
  addons/crm_reveal/i18n/crm_reveal.pot
  addons/delivery/i18n/delivery.pot
  addons/digest/i18n/digest.pot
  addons/hr_contract/i18n/hr_contract.pot
  addons/hr_payroll/i18n/hr_payroll.pot
  addons/im_support/i18n/im_support.pot
  addons/mail/i18n/mail.pot
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mrp/i18n/mrp.pot
  addons/payment/i18n/payment.pot
  addons/payment_authorize/i18n/payment_authorize.pot
  addons/payment_ogone/i18n/payment_ogone.pot
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/purchase/i18n/purchase.pot
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/sale/i18n/sale.pot
  addons/sale_timesheet/i18n/sale_timesheet.pot
  addons/stock/i18n/stock.pot
  addons/stock_account/i18n/stock_account.pot
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/website/i18n/website.pot
  addons/website_event/i18n/website_event.pot
  addons/website_livechat/i18n/website_livechat.pot
  addons/website_mail/i18n/website_mail.pot
  addons/website_mail_channel/i18n/website_mail_channel.pot
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_wishlist/i18n/website_sale_wishlist.pot
  odoo/addons/base/i18n/base.pot
Labels: 12.0

#6311 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/hw_drivers/drivers/DisplayDriver.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/tests/test_order.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/gui.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/odoo/http.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/META-INF/manifest.mf
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/META-INF/mozilla.rsa
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/META-INF/mozilla.sf
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/README
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/chrome.manifest
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/content/rkioskbrowser.js
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/content/rkioskbrowser.xul
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/content/rkioskunknownContentType.xul
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/content/rkioskxpinstallConfirm.xul
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/lib/firefox-esr/browser/extensions/{4D498D0A-05AD-4fdb-97B5-8A0AABC1FC5B}/install.rdf
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.7/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/share/firefox-esr/browser/defaults/preferences/all-posbox.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/point_of_sale/tools/posbox/posbox_download_images.sh
  addons/portal/static/src/scss/portal.scss
  addons/pos_restaurant/models/pos_order.py
  addons/sale/i18n/sale.pot
  addons/sale/models/payment.py
  addons/sale/tests/test_sale_transaction.py
  addons/stock/models/stock_move.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/website_sale/controllers/main.py
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/test_new_api/ir.model.access.csv
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
  odoo/modules/registry.py
  requirements.txt
Labels: 13.0

#6313 Syncing from upstream odoo/odoo (saas-11.3)
  addons/mrp/models/stock_move.py
  addons/stock/models/stock_move.py
Labels: saas-11.3

#6314 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/calendar/data/mail_data.xml
  addons/calendar/models/calendar.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/gui.js
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: saas-12.3

#6316 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/mrp/models/stock_move.py
  addons/stock/models/stock_move.py
Labels: staging.saas-11.3

#6317 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_invoice.py
  addons/calendar/data/mail_data.xml
  addons/calendar/models/calendar.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/gui.js
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: staging.saas-12.3

#6322 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/mrp/models/stock_move.py
  addons/stock/models/stock_move.py
Labels: tmp.saas-11.3

#6323 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_invoice.py
  addons/calendar/data/mail_data.xml
  addons/calendar/models/calendar.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/gui.js
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
Labels: tmp.saas-12.3

#6328 Syncing from upstream odoo/odoo (11.0)
  addons/web/static/src/less/kanban_dashboard.less
  odoo/modules/registry.py
Labels: 11.0

#6329 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account.py
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/stock_warehouse.py
  addons/product/models/product_pricelist.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/stock/models/stock_warehouse.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/modules/registry.py
Labels: 12.0

#6330 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account.py
  addons/calendar/data/mail_data.xml
  addons/calendar/models/calendar.py
  addons/l10n_ar/models/res_partner_bank.py
  addons/l10n_lu/data/account.account.template-2011.csv
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/stock/views/stock_inventory_views.xml
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
  addons/web_editor/static/src/js/editor/editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale_coupon/models/sale_order.py
  odoo/modules/registry.py
Labels: 13.0

#6331 Syncing from upstream odoo/odoo (master)
  addons/account/models/account.py
  addons/calendar/data/mail_data.xml
  addons/calendar/models/calendar.py
  addons/l10n_lu/data/account.account.template-2011.csv
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu_multilang.pot
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/models/pos_order.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project_overview.py
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock/views/stock_inventory_views.xml
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
  addons/web_editor/static/src/js/editor/editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale_coupon/models/sale_order.py
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: master

#6332 Syncing from upstream odoo/odoo (saas-11.3)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  odoo/modules/registry.py
Labels: saas-11.3

#6333 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
  addons/l10n_eu_service/wizard/wizard.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/stock_warehouse.py
  addons/product/models/product_pricelist.py
  addons/stock/models/stock_warehouse.py
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/website_sale_coupon/models/sale_order.py
  odoo/modules/registry.py
Labels: saas-12.3

#6335 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  odoo/modules/registry.py
Labels: staging.saas-11.3

#6336 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account.py
  addons/l10n_eu_service/wizard/wizard.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/stock_warehouse.py
  addons/product/models/product_pricelist.py
  addons/stock/models/stock_warehouse.py
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/website_sale_coupon/models/sale_order.py
  odoo/modules/registry.py
Labels: staging.saas-12.3

#6341 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  odoo/modules/registry.py
Labels: tmp.saas-11.3

#6342 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account.py
  addons/l10n_eu_service/wizard/wizard.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/stock_warehouse.py
  addons/product/models/product_pricelist.py
  addons/stock/models/stock_warehouse.py
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/website_sale_coupon/models/sale_order.py
  odoo/modules/registry.py
Labels: tmp.saas-12.3

#6346 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account.py
Labels: 13.0

#6347 Syncing from upstream odoo/odoo (master)
  addons/account/models/account.py
Labels: master

#6355 Syncing from upstream odoo/odoo (11.0)
  odoo/addons/base/ir/ir_qweb/qweb.py
Labels: 11.0

#6356 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/views/partner_view.xml
  addons/delivery/views/delivery_view.xml
  addons/http_routing/models/ir_http.py
  addons/sale/models/analytic.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_is_multilang.py
  addons/test_website/views/templates.xml
  addons/web/static/src/scss/kanban_dashboard.scss
  addons/web_editor/models/ir_qweb.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_validate.js
  odoo/addons/base/models/qweb.py
Labels: 12.0

#6357 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/views/partner_view.xml
  addons/crm/models/crm_lead.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/l10n_eu_service/wizard/wizard.py
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/stock_warehouse.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_warehouse.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/control_panel/control_panel_model.js
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/src/scss/kanban_dashboard.scss
  addons/web/static/tests/views/control_panel_tests.js
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/website_crm/models/crm_lead.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_validate.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/qweb.py
  odoo/addons/base/models/res_config.py
  odoo/addons/base/models/res_partner.py
Labels: 13.0

#6359 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/views/account_view.xml
  addons/web/static/src/less/kanban_dashboard.less
  odoo/addons/base/models/qweb.py
Labels: saas-11.3

#6360 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/account.pot
  addons/account/views/partner_view.xml
  addons/l10n_eu_service/wizard/wizard.py
  addons/l10n_eu_service/wizard/wizard.xml
  addons/web/static/src/scss/kanban_dashboard.scss
  addons/web_editor/models/ir_qweb.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_validate.js
  odoo/addons/base/models/qweb.py
Labels: saas-12.3

#6363 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/views/partner_view.xml
  addons/l10n_eu_service/wizard/wizard.py
  addons/l10n_eu_service/wizard/wizard.xml
  addons/web/static/src/scss/kanban_dashboard.scss
  addons/web_editor/models/ir_qweb.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_validate.js
  odoo/addons/base/models/qweb.py
Labels: staging.saas-12.3

#6369 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/views/partner_view.xml
  addons/l10n_eu_service/wizard/wizard.py
  addons/l10n_eu_service/wizard/wizard.xml
  addons/web/static/src/scss/kanban_dashboard.scss
  addons/web_editor/models/ir_qweb.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_validate.js
  odoo/addons/base/models/qweb.py
Labels: tmp.saas-12.3

#6373 Syncing from upstream odoo/odoo (11.0)
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_gateway.py
  addons/mass_mailing/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/project/models/project.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: 11.0

#6374 Syncing from upstream odoo/odoo (12.0)
  addons/account/static/src/js/bills_tree_upload.js
  addons/account_facturx/models/account_invoice.py
  addons/repair/models/repair.py
  addons/sale_timesheet/models/sale_order.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/views/pivot_tests.js
  addons/website/controllers/main.py
Labels: 12.0

#6375 Syncing from upstream odoo/odoo (13.0)
  addons/http_routing/models/ir_http.py
  addons/l10n_ar/views/res_country_view.xml
  addons/l10n_eu_service/wizard/wizard.py
  addons/l10n_eu_service/wizard/wizard.xml
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account.account.template.csv
  addons/l10n_no/data/account_chart_template_data.xml
  addons/l10n_no/data/l10n_no_chart_data.xml
  addons/payment_paypal/controllers/main.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_is_multilang.py
  addons/test_website/views/templates.xml
  addons/web/static/src/scss/dropdown_menu.scss
  addons/web/static/src/xml/base.xml
  addons/website/controllers/main.py
Labels: 13.0

#6377 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: saas-11.3

#6378 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_move.py
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/delivery/views/delivery_view.xml
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/website/controllers/main.py
Labels: saas-12.3

#6380 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: staging.saas-11.3

#6381 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_move.py
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/delivery/views/delivery_view.xml
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/website/controllers/main.py
Labels: staging.saas-12.3

#6386 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
Labels: tmp.saas-11.3

#6387 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_move.py
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/delivery/views/delivery_view.xml
  addons/web/static/src/js/views/pivot/pivot_model.js
  addons/web/static/tests/views/pivot_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/website/controllers/main.py
Labels: tmp.saas-12.3

#6391 Syncing from upstream odoo/odoo (11.0)
  addons/sale/security/sale_security.xml
Labels: 11.0

#6392 Syncing from upstream odoo/odoo (12.0)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/res_company.py
  addons/project_timesheet_holidays/models/res_config_settings.py
  addons/stock/models/stock_move_line.py
Labels: 12.0

#6393 Syncing from upstream odoo/odoo (13.0)
  addons/account/data/account_data.xml
  addons/account/models/account_move.py
  addons/account/static/src/js/section_and_note_fields_backend.js
  addons/account_analytic_default/models/account_analytic_default.py
  addons/delivery/models/delivery_carrier.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/product/views/product_views.xml
  addons/sale_timesheet/i18n/sale_timesheet.pot
  addons/sale_timesheet/views/hr_timesheet_templates.xml
  addons/stock/models/stock_move_line.py
  addons/stock/views/stock_move_views.xml
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/website_form/static/src/js/website_form_editor.js
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/static/src/js/website_sale_payment.js
Labels: 13.0

#6395 Syncing from upstream odoo/odoo (saas-11.3)
  addons/project/models/project.py
  addons/stock/models/stock_move_line.py
Labels: saas-11.3

#6396 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/static/src/js/section_and_note_fields_backend.js
  addons/account_facturx/models/account_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_holidays/views/hr_views.xml
  addons/project_timesheet_holidays/models/res_company.py
  addons/project_timesheet_holidays/models/res_config_settings.py
  addons/repair/models/repair.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
Labels: saas-12.3

#6398 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/project/models/project.py
  addons/stock/models/stock_move_line.py
Labels: staging.saas-11.3

#6399 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/static/src/js/section_and_note_fields_backend.js
  addons/account_facturx/models/account_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_holidays/views/hr_views.xml
  addons/project_timesheet_holidays/models/res_company.py
  addons/project_timesheet_holidays/models/res_config_settings.py
  addons/repair/models/repair.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
Labels: staging.saas-12.3

#6404 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/project/models/project.py
  addons/stock/models/stock_move_line.py
Labels: tmp.saas-11.3

#6405 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/static/src/js/section_and_note_fields_backend.js
  addons/account_facturx/models/account_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_holidays/views/hr_views.xml
  addons/project_timesheet_holidays/models/res_company.py
  addons/project_timesheet_holidays/models/res_config_settings.py
  addons/repair/models/repair.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
Labels: tmp.saas-12.3

#6409 Syncing from upstream odoo/odoo (11.0)
  addons/web_editor/models/ir_qweb.py
  odoo/service/server.py
Labels: 11.0

#6410 Syncing from upstream odoo/odoo (12.0)
  addons/calendar/data/mail_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar.py
  addons/google_calendar/models/google_calendar.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/pos_sale/report/sale_report.py
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale/report/sale_report.py
  addons/web/static/src/scss/dropdown_menu.scss
  addons/web/static/src/xml/base.xml
  addons/web_unsplash/models/ir_qweb.py
  odoo/service/server.py
Labels: 12.0

#6411 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/reconciliation_widget.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/google_calendar/models/google_calendar.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mail/models/mail_cc_mixin.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_compose_message.py
  addons/payment/views/payment_views.xml
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/test_mail/tests/common.py
  addons/test_mail/tests/test_discuss.py
  addons/test_mail/tests/test_mail_channel.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_message_track.py
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mail_channel.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/views/basic_model_tests.js
  addons/website/tests/__init__.py
  addons/website/tests/test_attachment.py
  addons/website_slides/wizard/slide_channel_invite.py
  doc/cla/individual/phuctranerp.md
  doc/reference/javascript_cheatsheet.rst
  doc/setup/deploy.rst
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_mail.py
  odoo/cli/templates/default/__manifest__.py.template
  odoo/cli/templates/default/controllers/controllers.py.template
  odoo/cli/templates/default/demo/demo.xml.template
  odoo/cli/templates/default/models/models.py.template
  odoo/cli/templates/default/security/ir.model.access.csv.template
  odoo/cli/templates/default/views/templates.xml.template
  odoo/cli/templates/default/views/views.xml.template
  odoo/service/server.py
  odoo/tools/mail.py
Labels: 13.0

#6412 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/google_calendar/models/google_calendar.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/http_routing/views/http_routing_template.xml
  addons/payment/views/payment_views.xml
  addons/portal/views/portal_templates.xml
  addons/theme_default/__manifest__.py
  addons/theme_default/data/theme_default_data.xml
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/scss/dropdown_menu.scss
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/views/basic_model_tests.js
  addons/website/static/src/js/theme_preview_form.js
  addons/website/static/src/xml/theme_preview.xml
  addons/website/views/website_templates.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/views/event_templates.xml
  addons/website_forum/views/website_forum.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/static/src/js/website_sale_payment.js
  addons/website_sale/views/templates.xml
  addons/website_slides/data/website_data.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/static/src/xml/website_slides_channel.xml
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  doc/cla/individual/phuctranerp.md
  doc/reference/javascript_cheatsheet.rst
  doc/setup/deploy.rst
  odoo/cli/templates/default/__manifest__.py.template
  odoo/cli/templates/default/controllers/controllers.py.template
  odoo/cli/templates/default/demo/demo.xml.template
  odoo/cli/templates/default/models/models.py.template
  odoo/cli/templates/default/security/ir.model.access.csv.template
  odoo/cli/templates/default/views/templates.xml.template
  odoo/cli/templates/default/views/views.xml.template
  odoo/service/server.py
Labels: master

#6413 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/service/server.py
Labels: saas-11.3

#6414 Syncing from upstream odoo/odoo (saas-12.3)
  addons/calendar/data/mail_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar.py
  addons/google_calendar/models/google_calendar.py
  addons/pos_sale/report/sale_report.py
  addons/sale/models/product_product.py
  addons/sale/report/sale_report.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/scss/dropdown_menu.scss
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/views/basic_model_tests.js
  odoo/addons/base/models/ir_http.py
  odoo/service/server.py
Labels: saas-12.3

#6416 Syncing from upstream odoo/odoo (staging.saas-11.3)
  odoo/service/server.py
Labels: staging.saas-11.3

#6417 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/calendar/data/mail_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar.py
  addons/google_calendar/models/google_calendar.py
  addons/pos_sale/report/sale_report.py
  addons/sale/models/product_product.py
  addons/sale/report/sale_report.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/scss/dropdown_menu.scss
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/views/basic_model_tests.js
  odoo/addons/base/models/ir_http.py
  odoo/service/server.py
Labels: staging.saas-12.3

#6422 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  odoo/service/server.py
Labels: tmp.saas-11.3

#6423 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/calendar/data/mail_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar.py
  addons/google_calendar/models/google_calendar.py
  addons/pos_sale/report/sale_report.py
  addons/sale/models/product_product.py
  addons/sale/report/sale_report.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/scss/dropdown_menu.scss
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/views/basic_model_tests.js
  odoo/addons/base/models/ir_http.py
  odoo/service/server.py
Labels: tmp.saas-12.3

#6427 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_fiscal_year.py
  addons/gamification/models/challenge.py
  addons/gamification/models/goal.py
  addons/website_blog/static/src/js/website_blog.editor.js
  addons/website_blog/views/website_blog_templates.xml
  odoo/fields.py
Labels: 11.0

#6428 Syncing from upstream odoo/odoo (12.0)
  addons/gamification/models/challenge.py
  addons/gamification/models/goal.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/mail/static/src/js/models/messages/message.js
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/views/stock_move_views.xml
Labels: 12.0

#6429 Syncing from upstream odoo/odoo (13.0)
  addons/base_gengo/i18n/base_gengo.pot
  addons/base_gengo/wizard/base_gengo_translations.py
  addons/calendar/data/mail_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar.py
  addons/l10n_be_edi/models/account_invoice.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/mail/models/mail_thread.py
  addons/payment_stripe/models/payment.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/tests/views/pivot_tests.js
  odoo/addons/base/models/res_partner.py
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/fields.py
  odoo/tools/translate.py
Labels: 13.0

#6431 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_fiscal_year.py
  addons/gamification/models/challenge.py
  addons/gamification/models/goal.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_blog/static/src/js/website_blog.editor.js
Labels: saas-11.3

#6432 Syncing from upstream odoo/odoo (saas-12.3)
  addons/gamification/models/challenge.py
  addons/http_routing/models/ir_http.py
  addons/l10n_be_edi/models/account_invoice.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_is_multilang.py
  addons/test_website/views/templates.xml
  addons/web_editor/static/src/js/wysiwyg/plugin/media.js
Labels: saas-12.3

#6434 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_fiscal_year.py
  addons/gamification/models/challenge.py
  addons/gamification/models/goal.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_blog/static/src/js/website_blog.editor.js
Labels: staging.saas-11.3
