Repository brain-tec/odoo, pull requests merged in 2019-08, with the labels that each got.

#5094 Syncing from upstream odoo/odoo (11.0)
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/web/static/src/js/views/basic/basic_model.js
Labels: 11.0

#5095 Syncing from upstream odoo/odoo (12.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/tests/reconciliation_tests.js
  addons/google_drive/models/res_config_settings.py
  addons/hr/security/hr_security.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/static/src/js/services/mail_notification_manager.js
  addons/mrp/models/mrp_production.py
  addons/partner_autocomplete/models/res_partner.py
  addons/website/models/website.py
  doc/cla/individual/Tatider.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: 12.0

#5097 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mail/static/src/js/emojis.js
Labels: saas-12.2

#5098 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/security/account_security.xml
  addons/l10n_mx/data/account_tax_data.xml
Labels: saas-12.3

#5099 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/data/account_data.xml
  addons/account/data/mail_template_data.xml
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_move_views.xml
  addons/l10n_ae/views/report_invoice_templates.xml
  addons/l10n_be_invoice_bba/models/account_invoice.py
  addons/l10n_in/__manifest__.py
  addons/l10n_in_pos/__manifest__.py
  addons/l10n_in_sale/__manifest__.py
  addons/l10n_in_stock/__manifest__.py
  addons/sale_stock/models/account_move.py
Labels: saas-12.4

#5100 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mail/static/src/js/emojis.js
Labels: staging.saas-12.2

#5104 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mail/static/src/js/emojis.js
Labels: tmp.saas-12.2

#5108 Syncing from upstream odoo/odoo (10.0)
  addons/stock/data/web_planner_data.xml
Labels: 10.0

#5109 Syncing from upstream odoo/odoo (11.0)
  addons/l10n_be_intrastat/models/l10n_be_intrastat.py
  addons/l10n_es/data/account_account_template_common_data.xml
  addons/payment_authorize/models/authorize_request.py
  addons/stock/views/product_views.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  doc/cla/individual/anhvu-sg.md
  doc/cla/individual/stfnndrsn.md
  odoo/addons/base/rng/gantt_view.rng
Labels: 11.0

#5110 Syncing from upstream odoo/odoo (12.0)
  addons/account_analytic_default/models/account_analytic_default.py
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/website_sale_wishlist/models/product_wishlist.py
Labels: 12.0

#5112 Syncing from upstream odoo/odoo (saas-11.3)
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/l10n_be_intrastat/models/l10n_be_intrastat.py
  addons/l10n_es/data/account_account_template_common_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mail/views/mail_templates.xml
  addons/payment_authorize/models/authorize_request.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/stock/security/stock_security.xml
  addons/test_mail/tests/test_performance.py
  addons/web/controllers/main.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/website/static/src/js/content/website_root.js
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  doc/cla/individual/anhvu-sg.md
  doc/cla/individual/stfnndrsn.md
Labels: saas-11.3

#5113 Syncing from upstream odoo/odoo (saas-12.2)
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/tests/views/calendar_tests.js
Labels: saas-12.2

#5114 Syncing from upstream odoo/odoo (saas-12.4)
  addons/website_slides/static/src/js/website_slides.editor.js
Labels: saas-12.4

#5115 Syncing from upstream odoo/odoo (saas-14)
  addons/l10n_be_intrastat/models/l10n_be_intrastat.py
  addons/payment_authorize/models/authorize_request.py
  doc/cla/individual/anhvu-sg.md
  doc/cla/individual/stfnndrsn.md
Labels: saas-14

#5116 Syncing from upstream odoo/odoo (saas-15)
  addons/l10n_be_intrastat/models/l10n_be_intrastat.py
  addons/payment_authorize/models/authorize_request.py
  doc/cla/individual/anhvu-sg.md
  doc/cla/individual/stfnndrsn.md
Labels: saas-15

#5117 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/tests/views/calendar_tests.js
Labels: staging.saas-12.2

#5122 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/tests/views/calendar_tests.js
Labels: tmp.saas-12.2

#5132 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/portal/views/portal_templates.xml
  addons/stock/views/product_views.xml
  odoo/addons/base/rng/gantt_view.rng
Labels: saas-11.3

#5133 Syncing from upstream odoo/odoo (saas-12.2)
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_forum/views/website_forum.xml
Labels: saas-12.2

#5135 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account_facturx/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_compose_message.py
Labels: saas-12.4

#5136 Syncing from upstream odoo/odoo (saas-14)
  addons/stock/data/web_planner_data.xml
Labels: saas-14

#5137 Syncing from upstream odoo/odoo (saas-15)
  addons/stock/data/web_planner_data.xml
Labels: saas-15

#5138 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_forum/views/website_forum.xml
Labels: staging.saas-12.2

#5143 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_forum/views/website_forum.xml
Labels: tmp.saas-12.2

#5147 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_payment.py
  addons/document/models/ir_attachment.py
  addons/point_of_sale/wizard/pos_details.xml
  addons/stock_dropshipping/__manifest__.py
  addons/stock_dropshipping/views/sale_order_views.xml
Labels: 11.0

#5148 Syncing from upstream odoo/odoo (12.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/views/res_config_settings_views.xml
  addons/base_vat/models/res_partner.py
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/l10n_es/data/account.account.template-common.csv
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mail/views/mail_templates.xml
  addons/portal/views/portal_templates.xml
  addons/pos_mercury/views/pos_config_setting_views.xml
  addons/pos_mercury/views/pos_config_views.xml
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_management/views/sale_order_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/res_config_settings.py
  addons/stock/security/stock_security.xml
  addons/stock/views/product_views.xml
  addons/test_mail/tests/test_performance.py
  addons/web/controllers/main.py
  addons/web/static/src/js/views/basic/basic_model.js
  doc/cla/individual/anhvu-sg.md
  doc/cla/individual/stfnndrsn.md
  odoo/addons/base/rng/gantt_view.rng
Labels: 12.0

#5152 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/crm/models/res_config_settings.py
  addons/crm/views/res_config_settings_views.xml
  addons/hr/models/hr_employee_base.py
  addons/phone_validation/models/res_company.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/public/public_root_instance.js
  addons/website/static/src/js/content/website_root_instance.js
  addons/website_sale/static/src/scss/website_sale.scss
Labels: saas-12.4

#5162 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/account_invoice.py
  addons/base_import/models/base_import.py
  addons/iap/i18n/iap.pot
  addons/iap/models/iap.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/models/res_company.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_resend_message.py
  addons/mass_mailing/models/mass_mailing.py
  addons/mrp/models/mrp_workorder.py
  addons/portal/controllers/portal.py
  addons/portal/i18n/portal.pot
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_create_picking.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale.py
  addons/sale_management/i18n/sale_management.pot
  addons/sale_management/models/sale_order_template.py
  addons/web/static/src/js/core/utils.js
  addons/web/static/src/js/views/kanban/kanban_renderer_mobile.js
  addons/web/static/tests/views/kanban_mobile_tests.js
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: 12.0

#5164 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_payment.py
  addons/document/models/ir_attachment.py
  addons/point_of_sale/wizard/pos_details.xml
  addons/stock_dropshipping/__manifest__.py
  addons/stock_dropshipping/views/sale_order_views.xml
Labels: saas-11.3

#5165 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mass_mailing/views/mass_mailing_views.xml
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/res_company.py
  addons/web/static/src/js/views/control_panel/control_panel_model.js
  addons/web/static/src/js/views/control_panel/search/add_new_favorite_menu.js
  addons/web/static/src/js/views/control_panel/search/favorite_menu.js
  addons/web/static/tests/views/search_view_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/plugin/keyboard.js
  addons/web_editor/static/src/js/wysiwyg/plugin/media.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  addons/web_editor/static/tests/test_utils.js
Labels: saas-12.3

#5170 Syncing from upstream odoo/odoo (11.0)
  addons/website_event/static/src/js/website_geolocation.js
Labels: 11.0

#5171 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/hw_escpos/escpos/escpos.py
  addons/mail/static/src/js/models/threads/document_thread.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/tests/document_thread_window_tests.js
  addons/point_of_sale/static/src/js/screens.js
  addons/point_of_sale/wizard/pos_details.xml
Labels: 12.0

#5173 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_payment.py
  addons/account/views/account_payment_view.xml
  addons/hr_recruitment/models/hr_job.py
  addons/point_of_sale/views/pos_session_view.xml
  addons/website_rating/static/src/scss/website_rating.scss
  addons/website_rating/static/src/xml/website_mail.xml
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
Labels: saas-12.3

#5183 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_invoice.py
Labels: 11.0

#5184 Syncing from upstream odoo/odoo (12.0)
  addons/base_iban/models/res_partner_bank.py
  addons/crm/views/crm_lead_views.xml
  addons/event/views/event_views.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/l10n_ae/data/account_tax_template_data.xml
  addons/mail/static/src/js/models/threads/document_thread.js
  addons/mail/static/tests/chatter_tests.js
  addons/maintenance/views/maintenance_views.xml
  addons/mass_mailing/views/mass_mailing_views.xml
  addons/note/views/note_views.xml
  addons/project/views/project_views.xml
  addons/survey/views/survey_views.xml
  addons/website_event/static/src/js/website_geolocation.js
  doc/cla/individual/igoris.md
  doc/cla/individual/reinaldoramosarxi.md
  odoo/addons/base/data/res.lang.csv
  odoo/addons/base/views/ir_module_views.xml
Labels: 12.0

#5186 Syncing from upstream odoo/odoo (saas-11.3)
  addons/website_event/static/src/js/website_geolocation.js
Labels: saas-11.3

#5187 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
  addons/l10n_ae/data/account_tax_template_data.xml
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/tests/thread_window/basic_thread_window_tests.js
  addons/point_of_sale/static/src/xml/pos.xml
  addons/web/static/src/js/widgets/domain_selector.js
  addons/web/static/src/js/widgets/model_field_selector.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/widgets/model_field_selector_tests.js
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_rating/static/src/scss/website_rating.scss
  addons/website_rating/static/src/xml/portal_chatter.xml
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides_forum/views/website_slides_forum_templates.xml
Labels: saas-12.3

#5188 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/point_of_sale/static/src/xml/pos.xml
Labels: staging.saas-12.2

#5191 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/point_of_sale/static/src/xml/pos.xml
Labels: tmp.saas-12.2

#5193 Syncing from upstream odoo/odoo (11.0)
  addons/website_sale_comparison/controllers/main.py
  addons/website_sale_comparison/models/website_sale_comparison.py
Labels: 11.0

#5194 Syncing from upstream odoo/odoo (12.0)
  addons/partner_autocomplete/models/res_partner.py
  addons/purchase/models/purchase.py
  addons/sale_timesheet/models/account_invoice.py
  addons/stock_account/models/stock.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/website/models/website.py
  addons/website/tests/test_ui.py
  addons/website_payment/models/payment_acquirer.py
  addons/website_sale/models/product.py
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_twitter/models/website_twitter_tweet.py
Labels: 12.0

#5196 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
  addons/hr/security/hr_security.xml
  addons/hr_holidays/models/hr.py
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
Labels: saas-12.3

#5199 Syncing from upstream odoo/odoo (staging.10.0)
  addons/mail/models/mail_thread.py
Labels: staging.10.0

#5202 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/mail/models/mail_thread.py
Labels: tmp.10.0

#5204 Syncing from upstream odoo/odoo (10.0)
  addons/mail/models/mail_thread.py
Labels: 10.0

#5205 Syncing from upstream odoo/odoo (11.0)
  addons/stock/models/stock_production_lot.py
  doc/reference/qweb.rst
Labels: 11.0

#5206 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/purchase_stock/models/stock.py
  addons/sale_stock/models/stock.py
  addons/website_mass_mailing/views/res_config_settings_views.xml
  odoo/__init__.py
Labels: 12.0

#5208 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mail/static/src/js/services/mail_manager.js
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/src/js/systray/systray_activity_menu.js
  addons/mail/static/src/scss/discuss.scss
  addons/mail/static/tests/discuss_tests.js
  addons/mail/static/tests/systray/systray_activity_menu_tests.js
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
Labels: saas-12.3

#5209 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/views/account_move_views.xml
Labels: saas-12.4

#5211 Syncing from upstream odoo/odoo (staging.10.0)
  addons/mail/models/mail_thread.py
Labels: staging.10.0

#5214 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/mail/models/mail_thread.py
Labels: tmp.10.0

#5216 Syncing from upstream odoo/odoo (12.0)
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_employee.py
  addons/hr_expense/models/hr_expense.py
  addons/maintenance/i18n/maintenance.pot
  addons/maintenance/models/maintenance.py
  addons/stock_picking_batch/report/report_picking_batch.xml
Labels: 12.0

#5218 Syncing from upstream odoo/odoo (saas-12.3)
  addons/survey/views/survey_report_templates.xml
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/scss/list_view.scss
  addons/web/static/tests/views/list_tests.js
Labels: saas-12.3

#5225 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/test_new_api/ir.model.access.csv
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: 10.0

#5226 Syncing from upstream odoo/odoo (11.0)
  addons/mail/models/mail_thread.py
  odoo/addons/base/ir/ir_rule.py
  odoo/addons/test_access_rights/ir.model.access.csv
  odoo/addons/test_access_rights/models.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
  odoo/addons/test_new_api/ir.model.access.csv
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: 11.0

#5227 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/calendar/views/calendar_views.xml
  addons/mail/models/mail_thread.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_production_lot.py
  addons/website_sale_comparison/controllers/main.py
  doc/reference/qweb.rst
  odoo/addons/base/models/ir_rule.py
  odoo/addons/test_access_rights/ir.model.access.csv
  odoo/addons/test_access_rights/models.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
  odoo/tests/common.py
Labels: 12.0

#5229 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/stock/models/stock_production_lot.py
  addons/website_sale_comparison/controllers/main.py
  addons/website_sale_comparison/models/website_sale_comparison.py
  doc/reference/qweb.rst
  odoo/addons/base/models/ir_rule.py
  odoo/addons/test_access_rights/ir.model.access.csv
  odoo/addons/test_access_rights/models.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: saas-11.3

#5231 Syncing from upstream odoo/odoo (saas-12.4)
  addons/hr/models/hr_employee_base.py
  addons/hr/models/hr_employee_public.py
  addons/mass_mailing_sale/models/mass_mailing.py
Labels: saas-12.4

#5232 Syncing from upstream odoo/odoo (saas-14)
  addons/mail/models/mail_thread.py
  odoo/addons/test_new_api/ir.model.access.csv
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: saas-14

#5233 Syncing from upstream odoo/odoo (saas-15)
  addons/mail/models/mail_thread.py
  odoo/addons/test_new_api/ir.model.access.csv
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: saas-15

#5240 Syncing from upstream odoo/odoo (10.0)
  addons/web_editor/static/src/js/summernote.js
  odoo/addons/base/ir/ir_model.py
Labels: 10.0

#5241 Syncing from upstream odoo/odoo (11.0)
  addons/im_livechat/controllers/main.py
  addons/mail/models/mail_template.py
  addons/purchase/models/purchase.py
  addons/web/static/src/js/core/utils.js
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/models/website_sale_comparison.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: 11.0

#5242 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_reconciliation_widget.py
  addons/account/views/report_invoice.xml
  addons/base_address_city/models/res_partner.py
  addons/hr_payroll_account/models/hr_payroll_account.py
  addons/payment/views/payment_portal_templates.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/ir_module_module.xml
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
Labels: 12.0

#5245 Syncing from upstream odoo/odoo (saas-12.3)
  addons/delivery/models/sale_order.py
  addons/delivery/wizard/choose_delivery_carrier.py
  addons/mail/static/tests/chatter_tests.js
  addons/website_sale_delivery/static/src/js/website_free_delivery_tour.js
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  odoo/addons/base/models/res_partner.py
Labels: saas-12.3

#5248 Syncing from upstream odoo/odoo (staging.10.0)
  addons/web_editor/static/src/js/summernote.js
  odoo/addons/base/ir/ir_model.py
Labels: staging.10.0

#5251 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/web_editor/static/src/js/summernote.js
  odoo/addons/base/ir/ir_model.py
Labels: tmp.10.0

#5253 [bt#7654] Update jSignature js lib
  addons/website_quote/static/lib/jSignature/jSignature.min.js
Labels: 8.0.valaiscom

#5254 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_move.py
  addons/l10n_uk/__manifest__.py
  addons/web_editor/static/src/js/editor/summernote.js
  odoo/addons/base/ir/ir_model.py
Labels: 11.0

#5257 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_move.py
  addons/im_livechat/controllers/main.py
  addons/l10n_uk/__manifest__.py
  addons/purchase/models/purchase.py
  addons/web/static/src/js/core/utils.js
  addons/web_editor/static/src/js/editor/summernote.js
  addons/website_sale_comparison/models/website_sale_comparison.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: saas-11.3

#5259 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account.py
  addons/account/models/account_move.py
Labels: saas-12.4

#5260 Syncing from upstream odoo/odoo (saas-14)
  addons/web_editor/static/src/js/summernote.js
  odoo/addons/base/ir/ir_model.py
Labels: saas-14

#5261 Syncing from upstream odoo/odoo (saas-15)
  addons/web_editor/static/src/js/summernote.js
  odoo/addons/base/ir/ir_model.py
Labels: saas-15

#5266 Syncing from upstream odoo/odoo (10.0)
  addons/account/models/account.py
  odoo/tools/mail.py
Labels: 10.0

#5267 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_move.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/views/account_payment_views.xml
  addons/gamification/views/goal.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/payment_stripe/static/src/js/stripe.js
  addons/website_event_track/models/event_track.py
Labels: 11.0

#5268 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/tvtmarine-automation.md
Labels: 12.0

#5270 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_move.py
Labels: saas-11.3

#5271 Syncing from upstream odoo/odoo (saas-12.3)
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/point_of_sale/static/src/js/models.js
Labels: saas-12.3

#5272 Syncing from upstream odoo/odoo (saas-14)
  addons/account/models/account.py
Labels: saas-14

#5273 Syncing from upstream odoo/odoo (saas-15)
  addons/account/models/account.py
Labels: saas-15

#5275 Syncing from upstream odoo/odoo (staging.10.0)
  addons/account/models/account.py
  odoo/tools/mail.py
Labels: staging.10.0

#5277 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/account/models/account.py
  odoo/tools/mail.py
Labels: tmp.10.0

#5280 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
Labels: saas-12.3

#5282 Syncing from upstream odoo/odoo (master)
  odoo/sql_db.py
Labels: master

#5287 Syncing from upstream odoo/odoo (11.0)
  addons/point_of_sale/static/src/js/screens.js
  addons/portal/views/portal_templates.xml
  addons/website/models/website.py
Labels: 11.0

#5288 Syncing from upstream odoo/odoo (12.0)
  addons/sale/models/sale.py
  addons/website/static/src/js/content/menu.js
Labels: 12.0

#5289 Syncing from upstream odoo/odoo (master)
  addons/mass_mailing/models/mailing.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/views/mrp_bom_views.xml
  addons/sale/models/sales_team.py
  addons/stock/models/product.py
  addons/stock/models/stock_production_lot.py
  addons/stock/static/src/xml/stock_traceability_report_line.xml
  addons/stock/views/report_stock_traceability.xml
  addons/stock/views/stock_production_lot_views.xml
  addons/website_event_questions/views/event_templates.xml
  odoo/sql_db.py
Labels: master

#5290 Syncing from upstream odoo/odoo (saas-12.3)
  addons/gamification/models/challenge.py
  addons/gamification/models/goal.py
  addons/gamification/views/challenge.xml
  addons/gamification/views/goal.xml
  addons/lunch/static/src/js/lunch_kanban_controller.js
  addons/lunch/static/src/js/lunch_kanban_model.js
  addons/lunch/static/src/js/lunch_kanban_view.js
  addons/lunch/static/tests/lunch_kanban_tests.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields_tests.js
Labels: saas-12.3

#5294 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/website_event_sale/models/sale_order.py
  odoo/tools/mail.py
Labels: 11.0

#5295 Syncing from upstream odoo/odoo (12.0)
  addons/account_tax_python/models/account_tax.py
  addons/l10n_lu/__init__.py
  addons/l10n_lu/__manifest__.py
  addons/l10n_multilang/models/l10n_multilang.py
  addons/mail/static/src/scss/composer.scss
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/point_of_sale/static/src/css/customer_facing_display.css
  addons/point_of_sale/static/src/scss/customer_facing_display.scss
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/js/views/form/form_view.js
  addons/web/static/src/scss/ui.scss
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/form_tests.js
  addons/web/static/tests/views/view_dialogs_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/views/website_templates.xml
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: 12.0

#5296 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/views/account_payment_views.xml
  addons/gamification/views/goal.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/point_of_sale/static/src/js/screens.js
  addons/website/models/website.py
  addons/website_event_sale/models/sale_order.py
  addons/website_event_track/models/event_track.py
  odoo/tools/mail.py
Labels: saas-11.3

#5297 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
  addons/account/tests/test_tax.py
Labels: saas-12.3

#5299 Syncing from upstream odoo/odoo (saas-14)
  odoo/tools/mail.py
Labels: saas-14

#5300 Syncing from upstream odoo/odoo (saas-15)
  odoo/tools/mail.py
Labels: saas-15

#5301 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account.py
  addons/account/tests/test_tax.py
Labels: staging.saas-12.3

#5305 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account.py
  addons/account/tests/test_tax.py
Labels: tmp.saas-12.3

#5309 Syncing from upstream odoo/odoo (10.0)
  addons/auth_oauth/controllers/main.py
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  doc/_extensions/odoo_ext/static/variables.less
  doc/cla/individual/hari4274.md
Labels: 10.0

#5310 Syncing from upstream odoo/odoo (11.0)
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/graph/graph_view.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/web/static/tests/views/graph_tests.js
  doc/reference/javascript_reference.rst
  odoo/addons/base/rng/calendar_view.rng
Labels: 11.0

#5311 Syncing from upstream odoo/odoo (12.0)
  addons/mail/static/src/js/thread_windows/thread_window.js
  addons/mail/static/tests/discuss_mobile_tests.js
  addons/stock/models/stock_move.py
  addons/stock/tests/test_packing.py
  addons/website/static/src/scss/website.scss
  addons/website_blog/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale_stock/models/product_template.py
  doc/reference/orm.rst
Labels: 12.0

#5312 Syncing from upstream odoo/odoo (saas-12.3)
  addons/point_of_sale/models/account_tax.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
Labels: saas-12.3

#5314 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/point_of_sale/models/account_tax.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
Labels: staging.saas-12.3

#5316 Syncing from upstream odoo/odoo (staging.10.0)
  addons/auth_oauth/controllers/main.py
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  doc/_extensions/odoo_ext/static/variables.less
  doc/cla/individual/hari4274.md
Labels: staging.10.0

#5319 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/point_of_sale/models/account_tax.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/wysiwyg/plugin/text.js
Labels: tmp.saas-12.3

#5321 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/auth_oauth/controllers/main.py
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  doc/_extensions/odoo_ext/static/variables.less
  doc/cla/individual/hari4274.md
Labels: tmp.10.0

#5324 Syncing from upstream odoo/odoo (10.0)
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: 10.0

#5325 Syncing from upstream odoo/odoo (11.0)
  addons/auth_oauth/controllers/main.py
  addons/mail/static/src/js/utils.js
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  doc/cla/individual/hari4274.md
Labels: 11.0

#5326 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_reconciliation.py
  addons/account/tests/test_reconciliation_widget.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/views/account_payment_views.xml
  addons/auth_oauth/controllers/main.py
  addons/gamification/views/goal.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/mail/static/src/js/utils.js
  addons/maintenance/views/maintenance_views.xml
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/graph/graph_view.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/web/static/tests/views/graph_tests.js
  addons/website/models/website.py
  addons/website_event_sale/models/sale_order.py
  addons/website_event_track/models/event_track.py
  doc/cla/individual/hari4274.md
  doc/reference/javascript_reference.rst
  odoo/addons/base/rng/calendar_view.rng
  odoo/tools/mail.py
Labels: 12.0

#5327 Syncing from upstream odoo/odoo (master)
  odoo/service/wsgi_server.py
Labels: master

#5328 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/tests/test_reconciliation.py
  addons/auth_oauth/controllers/main.py
  addons/mail/static/src/js/utils.js
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/graph/graph_view.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/web/static/tests/views/graph_tests.js
  doc/cla/individual/hari4274.md
  doc/reference/javascript_reference.rst
  odoo/addons/base/rng/calendar_view.rng
Labels: saas-11.3

#5329 Syncing from upstream odoo/odoo (saas-12.3)
  addons/purchase_stock/models/account_invoice.py
Labels: saas-12.3

#5330 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_out_invoice.py
Labels: saas-12.4

#5331 Syncing from upstream odoo/odoo (saas-12.5)
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/screens.js
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/models/purchase.py
  addons/sale_coupon/views/sale_order_views.xml
  addons/sale_product_matrix/i18n/sale_product_matrix.pot
  addons/sale_product_matrix/models/sale_order.py
  addons/stock/models/product.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/models/website_menu.py
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/xml/website.contentMenu.xml
  addons/website_mass_mailing/static/src/scss/website_mass_mailing.editor.scss
  addons/website_mass_mailing/views/website_mass_mailing_templates.xml
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides_survey/views/slide_channel_views.xml
Labels: saas-12.5

#5332 Syncing from upstream odoo/odoo (saas-14)
  addons/auth_oauth/controllers/main.py
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  doc/_extensions/odoo_ext/static/variables.less
  doc/cla/individual/hari4274.md
Labels: saas-14

#5333 Syncing from upstream odoo/odoo (saas-15)
  addons/auth_oauth/controllers/main.py
  addons/theme_bootswatch/static/src/less/amelia/bootswatch.less
  addons/theme_bootswatch/static/src/less/cosmo/bootswatch.less
  addons/theme_bootswatch/static/src/less/cyborg/bootswatch.less
  addons/theme_bootswatch/static/src/less/flatly/bootswatch.less
  addons/theme_bootswatch/static/src/less/journal/bootswatch.less
  addons/theme_bootswatch/static/src/less/readable/bootswatch.less
  addons/theme_bootswatch/static/src/less/simplex/bootswatch.less
  addons/theme_bootswatch/static/src/less/spacelab/bootswatch.less
  addons/theme_bootswatch/static/src/less/united/bootswatch.less
  doc/_extensions/odoo_ext/static/variables.less
  doc/cla/individual/hari4274.md
Labels: saas-15

#5336 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/purchase_stock/models/account_invoice.py
Labels: staging.saas-12.3

#5338 Syncing from upstream odoo/odoo (staging.saas-12.5)
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/screens.js
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/models/purchase.py
  addons/sale_coupon/views/sale_order_views.xml
  addons/sale_product_matrix/i18n/sale_product_matrix.pot
  addons/sale_product_matrix/models/sale_order.py
  addons/stock/models/product.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/models/website_menu.py
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/xml/website.contentMenu.xml
  addons/website_mass_mailing/static/src/scss/website_mass_mailing.editor.scss
  addons/website_mass_mailing/views/website_mass_mailing_templates.xml
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides_survey/views/slide_channel_views.xml
Labels: staging.saas-12.5

#5339 Syncing from upstream odoo/odoo (staging.10.0)
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: staging.10.0

#5344 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/purchase_stock/models/account_invoice.py
Labels: tmp.saas-12.3

#5346 Syncing from upstream odoo/odoo (tmp.saas-12.5)
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/screens.js
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/models/purchase.py
  addons/sale_coupon/views/sale_order_views.xml
  addons/sale_product_matrix/i18n/sale_product_matrix.pot
  addons/sale_product_matrix/models/sale_order.py
  addons/stock/models/product.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/models/website_menu.py
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/xml/website.contentMenu.xml
  addons/website_mass_mailing/static/src/scss/website_mass_mailing.editor.scss
  addons/website_mass_mailing/views/website_mass_mailing_templates.xml
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides_survey/views/slide_channel_views.xml
Labels: tmp.saas-12.5

#5347 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: tmp.10.0

#5350 Syncing from upstream odoo/odoo (11.0)
  addons/mail/static/src/less/thread.less
Labels: 11.0

#5351 Syncing from upstream odoo/odoo (12.0)
  addons/account/tests/test_reconciliation.py
  addons/website_sale_digital/controllers/main.py
Labels: 12.0

#5352 Syncing from upstream odoo/odoo (master)
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/form_tests.js
Labels: master

#5354 Syncing from upstream odoo/odoo (saas-12.4)
  addons/sale/models/sale.py
Labels: saas-12.4

#5357 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_move.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/web/static/src/js/views/kanban/kanban_record.js
  addons/web/static/tests/views/kanban_tests.js
Labels: staging.saas-12.3

#5363 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_move.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/web/static/src/js/views/kanban/kanban_record.js
  addons/web/static/tests/views/kanban_tests.js
Labels: tmp.saas-12.3
