Repository brain-tec/odoo, pull requests merged in 2019-04, with the labels that each got.

#3502 Syncing from upstream odoo/odoo (11.0)
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/website_quote/controllers/main.py
  odoo/addons/base/res/res_bank.py
  odoo/addons/base/res/res_bank_view.xml
Labels: 11.0

#3503 Syncing from upstream odoo/odoo (12.0)
  addons/l10n_generic_coa/data/account_invoice_demo.xml
  addons/l10n_in/views/report_invoice.xml
  addons/purchase_stock/models/purchase.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/views/account_invoice_views.xml
  addons/website/static/src/js/backend/dashboard.js
Labels: 12.0

#3505 Syncing from upstream odoo/odoo (saas-12.2)
  addons/web_editor/static/src/js/wysiwyg/plugin/keyboard.js
Labels: saas-12.2

#3507 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/account/models/account_invoice.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/report_invoice.xml
  addons/account_check_printing/models/account_payment.py
  addons/bus/models/bus.py
  addons/hr_holidays/models/hr.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hw_escpos/escpos/constants.py
  addons/im_livechat/models/mail_channel.py
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_nl/data/account.account.template.csv
  addons/l10n_nl/data/account_fiscal_position_account_template.xml
  addons/l10n_nl/data/account_fiscal_position_tax_template.xml
  addons/l10n_nl/data/account_fiscal_position_template.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/payment/models/account_payment.py
  addons/payment_buckaroo/tests/test_buckaroo.py
  addons/payment_paypal/tests/test_paypal.py
  addons/product/models/product_template.py
  addons/project/data/project_data.xml
  addons/purchase/models/account_invoice.py
  addons/purchase/models/product.py
  addons/purchase_stock/report/purchase_report_templates.xml
  addons/repair/models/repair.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/wizard/stock_warn_insufficient_qty.py
  addons/stock/wizard/stock_warn_insufficient_qty_views.xml
  addons/web/static/src/js/core/dialog.js
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/views/calendar_tests.js
  addons/website/static/src/scss/website.backend.scss
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale/data/data.xml
  addons/website_sale/models/sale_order.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_translation_import/tests/test_term_count.py
  odoo/tools/translate.py
Labels: staging.saas-12.1

#3513 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/account/models/account_invoice.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/report_invoice.xml
  addons/account_check_printing/models/account_payment.py
  addons/bus/models/bus.py
  addons/hr_holidays/models/hr.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hw_escpos/escpos/constants.py
  addons/im_livechat/models/mail_channel.py
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_nl/data/account.account.template.csv
  addons/l10n_nl/data/account_fiscal_position_account_template.xml
  addons/l10n_nl/data/account_fiscal_position_tax_template.xml
  addons/l10n_nl/data/account_fiscal_position_template.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/payment/models/account_payment.py
  addons/payment_buckaroo/tests/test_buckaroo.py
  addons/payment_paypal/tests/test_paypal.py
  addons/product/models/product_template.py
  addons/project/data/project_data.xml
  addons/purchase/models/account_invoice.py
  addons/purchase/models/product.py
  addons/purchase_stock/report/purchase_report_templates.xml
  addons/repair/models/repair.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/stock/wizard/stock_warn_insufficient_qty.py
  addons/stock/wizard/stock_warn_insufficient_qty_views.xml
  addons/web/static/src/js/core/dialog.js
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/views/calendar_tests.js
  addons/website/static/src/scss/website.backend.scss
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale/data/data.xml
  addons/website_sale/models/sale_order.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_translation_import/tests/test_term_count.py
  odoo/tools/translate.py
Labels: tmp.saas-12.1

#3518 Syncing from upstream odoo/odoo (11.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/tests/reconciliation_tests.js
  addons/base_geolocalize/models/res_partner.py
  addons/website_sale/models/sale_order.py
Labels: 11.0

#3519 Syncing from upstream odoo/odoo (12.0)
  addons/hw_drivers/controllers/__init__.py
  addons/hw_drivers/controllers/driver.py
  addons/hw_drivers/controllers/loading.py
  addons/hw_drivers/static/img/False.jpg
  addons/hw_drivers/static/img/True.jpg
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/homepage.html
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/cups/cupsd.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/xdg/openbox/autostart
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.5/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/point_of_sale/tools/posbox/posbox_download_images.sh
  addons/purchase/views/purchase_views.xml
  addons/web/static/src/js/core/domain.js
  odoo/addons/base/rng/gantt_view.rng
Labels: 12.0

#3521 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/tests/reconciliation_tests.js
  addons/base_geolocalize/models/res_partner.py
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/website_quote/controllers/main.py
  addons/website_sale/models/sale_order.py
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/views/res_bank_views.xml
Labels: saas-11.3

#3522 Syncing from upstream odoo/odoo (saas-14)
  addons/base_geolocalize/models/res_partner.py
Labels: saas-14

#3523 Syncing from upstream odoo/odoo (saas-15)
  addons/base_geolocalize/models/res_partner.py
Labels: saas-15

#3531 Syncing from upstream odoo/odoo (10.0)
  addons/l10n_pl/data/account_tax_data.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/purchase/models/purchase.py
Labels: 10.0

#3532 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_invoice.py
  addons/account/views/account_view.xml
  addons/point_of_sale/models/pos_order.py
  addons/product/views/product_views.xml
Labels: 11.0

#3533 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/reconciliation_widget.py
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/tests/reconciliation_tests.js
  addons/account/views/report_payment_receipt_templates.xml
  addons/account_check_printing/models/account_payment.py
  addons/base_geolocalize/models/res_partner.py
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_multilang/models/l10n_multilang.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/models/mail_mail.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/note/data/note_data.xml
  addons/point_of_sale/models/pos_session.py
  addons/purchase_stock/models/account_invoice.py
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web/static/src/scss/layout_background.scss
  addons/web/static/tests/views/calendar_tests.js
  addons/website_crm_partner_assign/models/crm_lead.py
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  addons/website_sale/models/sale_order.py
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/views/res_bank_views.xml
  odoo/addons/test_testing_utilities/ir.model.access.csv
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/models.py
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
  odoo/tools/date_utils.py
Labels: 12.0

#3534 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_payment.py
  addons/account/views/account_payment_view.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/views/stock_picking_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/res_config_settings.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/test_mail/tests/test_performance.py
  addons/website_forum/models/forum.py
Labels: master

#3535 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_payment.py
  addons/account/views/account_payment_view.xml
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/models/res_config_settings.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_bom_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/views/mrp_routing_views.xml
  addons/mrp/views/res_config_settings_views.xml
  addons/mrp_account/__init__.py
  addons/mrp_account/__manifest__.py
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/mrp_production.py
  addons/mrp_account/models/mrp_workcenter.py
  addons/mrp_account/tests/__init__.py
  addons/mrp_account/tests/test_mrp_account.py
  addons/mrp_byproduct/views/mrp_bom_views.xml
  addons/mrp_subcontracting/__init__.py
  addons/mrp_subcontracting/__manifest__.py
  addons/mrp_subcontracting/data/mrp_subcontracting_data.xml
  addons/mrp_subcontracting/models/__init__.py
  addons/mrp_subcontracting/models/mrp_bom.py
  addons/mrp_subcontracting/models/res_company.py
  addons/mrp_subcontracting/models/res_partner.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/mrp_subcontracting/tests/__init__.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/mrp_bom_views.xml
  addons/mrp_subcontracting/views/stock_picking_views.xml
  addons/mrp_subcontracting/views/stock_warehouse_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/product/views/product_views.xml
  addons/purchase_mrp_subcontracting/__init__.py
  addons/purchase_mrp_subcontracting/__manifest__.py
  addons/purchase_mrp_subcontracting/models/__init__.py
  addons/purchase_mrp_subcontracting/models/product.py
  addons/purchase_mrp_subcontracting/models/stock_picking.py
  addons/purchase_mrp_subcontracting/tests/__init__.py
  addons/purchase_mrp_subcontracting/tests/test_purchase_subcontracting.py
  addons/purchase_mrp_subcontracting/views/supplier_info_views.xml
  addons/stock/models/res_company.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_warehouse.py
  addons/stock/views/res_partner_views.xml
Labels: saas-12.3

#3539 Syncing from upstream odoo/odoo (staging.10.0)
  addons/l10n_pl/data/account_tax_data.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/purchase/models/purchase.py
Labels: staging.10.0

#3543 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/l10n_pl/data/account_tax_data.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/purchase/models/purchase.py
Labels: tmp.10.0

#3546 Syncing from upstream odoo/odoo (10.0)
  addons/account_asset/views/account_asset_views.xml
  addons/web_editor/static/src/js/widgets.js
Labels: 10.0

#3547 Syncing from upstream odoo/odoo (11.0)
  addons/account_asset/views/account_asset_views.xml
  addons/http_routing/models/ir_http.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/purchase/models/purchase.py
  addons/stock/wizard/stock_immediate_transfer.py
  addons/stock_account/models/stock.py
  addons/survey/static/src/js/survey.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/website/models/ir_qweb.py
  addons/website/tests/test_qweb.py
  odoo/fields.py
Labels: 11.0

#3548 Syncing from upstream odoo/odoo (12.0)
  addons/base_address_extended/models/base_address_extended.py
  addons/board/static/src/js/favorite_menu.js
  addons/board/static/tests/dashboard_tests.js
  addons/payment_authorize/models/authorize_request.py
  addons/purchase/models/purchase.py
  odoo/__init__.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/tests/common.py
Labels: 12.0

#3551 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mrp/views/mrp_workorder_views.xml
  addons/product/models/product_template.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.editor.ui.scss
Labels: saas-12.2

#3552 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
  addons/account/models/account_invoice.py
  addons/account/models/account_invoice_import_wizard.py
  addons/account/static/src/js/bills_tree_upload.js
  addons/account/views/account_invoice_view.xml
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_view.xml
  addons/account_facturx/__manifest__.py
  addons/account_facturx/models/account_invoice.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_picking.py
  addons/mrp/models/stock_production_lot.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/mrp/views/stock_picking_views.xml
  addons/mrp/wizard/mrp_product_produce_views.xml
  addons/sale/static/src/js/tour.js
  addons/sale_timesheet/models/project_overview.py
  addons/stock/models/stock_production_lot.py
  addons/stock/views/stock_picking_views.xml
  addons/website_sale/static/src/js/website_sale_tour_buy.js
  addons/website_sale/static/src/js/website_sale_tour_shop_custom_attribute_value.js
  addons/website_sale_product_configurator/static/src/js/website_sale_tour_buy.js
  addons/website_sale_product_configurator/static/src/js/website_sale_tour_shop_custom_attributes_value.js
  addons/website_sale_product_configurator/views/assets.xml
  odoo/addons/base/data/res.lang.csv
Labels: saas-12.3

#3553 Syncing from upstream odoo/odoo (saas-14)
  addons/account_asset/views/account_asset_views.xml
  addons/l10n_pl/data/account_tax_data.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/purchase/models/purchase.py
  addons/web_editor/static/src/js/widgets.js
Labels: saas-14

#3554 Syncing from upstream odoo/odoo (saas-15)
  addons/account_asset/views/account_asset_views.xml
  addons/l10n_pl/data/account_tax_data.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/purchase/models/purchase.py
  addons/web_editor/static/src/js/widgets.js
Labels: saas-15

#3557 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mrp/views/mrp_workorder_views.xml
  addons/product/models/product_template.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.editor.ui.scss
Labels: staging.saas-12.2

#3559 Syncing from upstream odoo/odoo (staging.10.0)
  addons/account_asset/views/account_asset_views.xml
  addons/web_editor/static/src/js/widgets.js
Labels: staging.10.0

#3564 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mrp/views/mrp_workorder_views.xml
  addons/product/models/product_template.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.editor.ui.scss
Labels: tmp.saas-12.2

#3566 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/account_asset/views/account_asset_views.xml
  addons/web_editor/static/src/js/widgets.js
Labels: tmp.10.0

#3570 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/base/module/module.py
  odoo/models.py
Labels: 10.0

#3571 Syncing from upstream odoo/odoo (11.0)
  addons/account_payment/views/account_portal_templates.xml
  addons/base_address_city/models/res_partner.py
  addons/stock/models/stock_inventory.py
  doc/cla/individual/matthewdwatkins.md
Labels: 11.0

#3572 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/__init__.py
  addons/account/models/res_users.py
  addons/delivery_hs_code/models/product_template.py
  addons/mail/models/mail_mail.py
  addons/sale/models/res_company.py
  addons/sale/models/sale.py
  addons/stock/models/stock_quant.py
  doc/cla/corporate/xoe-corp.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_translation.py
  odoo/models.py
Labels: 12.0

#3573 Syncing from upstream odoo/odoo (master)
  addons/calendar/models/calendar.py
  addons/crm_iap_lead/models/crm_iap_lead_helpers.py
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mail/models/mail_template.py
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/point_of_sale_dashboard.xml
  addons/point_of_sale/views/pos_category_view.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/sale/views/sale_views.xml
  addons/web_tour/static/src/js/tour_service.js
  addons/website_forum/models/forum.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/views/res_currency_views.xml
  odoo/tests/common.py
Labels: master

#3577 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/tests/reconciliation_tests.js
  addons/account_payment/views/account_portal_templates.xml
  addons/base_geolocalize/models/res_partner.py
  addons/hw_escpos/escpos/constants.py
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_jp/data/account.tax.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/product/views/product_template_views.xml
  addons/stock_account/models/stock.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
  addons/website_quote/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_options/views/website_sale_options_templates.xml
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/views/res_bank_views.xml
Labels: staging.saas-11.3

#3580 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/base/module/module.py
  odoo/models.py
Labels: staging.10.0

#3587 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/base/module/module.py
  odoo/models.py
Labels: tmp.10.0

#3593 Syncing from upstream odoo/odoo (12.0)
  addons/purchase_requisition/models/purchase_requisition.py
Labels: 12.0

#3601 [t10038] Odoo Security Advisory - ODOO-SA-2018-08-07
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/models/res_users.py
  addons/mail/models/mail_template.py
  addons/mail/views/mail_template_views.xml
  addons/report/models/report.py
  addons/web/controllers/main.py
  addons/website/models/ir_attachment.py
  addons/website_mail/controllers/main.py
  addons/website_mail/models/mail_message.py
  odoo/addons/base/ir/ir_actions.py
  odoo/addons/base/ir/ir_attachment.py
  odoo/addons/base/ir/ir_qweb/assetsbundle.py
  odoo/addons/base/module/module.py
  odoo/addons/base/res/res_users.py
  odoo/http.py
  odoo/models.py
  odoo/tools/misc.py
Labels: 10.0.project_lu_268

#3602 [t113281] Odoo Security Advisory - ODOO-SA-2018-11-28
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/wizard/invite.py
Labels: 10.0.project_lu_268

#3603 Syncing from upstream odoo/odoo (10.0)
  addons/website/models/ir_actions.py
Labels: 10.0

#3604 Syncing from upstream odoo/odoo (11.0)
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/web_editor/static/src/js/editor/rte.summernote.js
  doc/cla/individual/bletourmy.md
  odoo/addons/base/module/module.py
Labels: 11.0

#3605 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/views/account_view.xml
  addons/account_payment/views/account_portal_templates.xml
  addons/base_address_city/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/http_routing/models/ir_http.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mass_mailing_stats.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/product/views/product_views.xml
  addons/purchase_stock/models/stock_rule.py
  addons/stock/models/stock_inventory.py
  addons/stock/wizard/stock_immediate_transfer.py
  addons/stock_account/models/stock.py
  addons/survey/static/src/js/survey.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/website/models/ir_qweb.py
  addons/website/tests/test_qweb.py
  doc/cla/corporate/business-solutions-for-africa.md
  doc/cla/individual/andriisem.md
  doc/cla/individual/bletourmy.md
  doc/cla/individual/matthewdwatkins.md
  doc/cla/individual/mmahgoub.md
  doc/howtos/themes.rst
  odoo/addons/base/models/ir_module.py
  odoo/fields.py
Labels: 12.0

#3606 Syncing from upstream odoo/odoo (master)
  addons/hr/models/res_users.py
  addons/hr/views/res_users.xml
  addons/mail/views/mail_activity_views.xml
  addons/survey/models/survey_question.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/survey/views/survey_templates.xml
  doc/cla/corporate/thought-gang.md
  doc/cla/individual/xtanuiha.md
  odoo/addons/base/views/ir_rule_views.xml
Labels: master

#3607 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/account_invoice.py
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_view.xml
  addons/account_asset/views/account_asset_views.xml
  addons/account_payment/views/account_portal_templates.xml
  addons/base_address_city/models/res_partner.py
  addons/http_routing/models/ir_http.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/product/views/product_views.xml
  addons/purchase/models/purchase.py
  addons/stock/models/stock_inventory.py
  addons/stock/wizard/stock_immediate_transfer.py
  addons/stock_account/models/stock.py
  addons/survey/static/src/js/survey.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/website/models/ir_qweb.py
  addons/website/tests/test_qweb.py
  doc/cla/individual/bletourmy.md
  doc/cla/individual/matthewdwatkins.md
  odoo/addons/base/models/ir_module.py
  odoo/fields.py
Labels: saas-11.3

#3608 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mail/static/src/scss/chatter.scss
  addons/mail/static/src/scss/composer.scss
Labels: saas-12.2

#3609 Syncing from upstream odoo/odoo (saas-14)
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/website/models/ir_actions.py
  odoo/addons/base/module/module.py
  odoo/models.py
Labels: saas-14

#3610 Syncing from upstream odoo/odoo (saas-15)
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/website/models/ir_actions.py
  odoo/addons/base/module/module.py
Labels: saas-15

#3613 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mail/static/src/scss/chatter.scss
  addons/mail/static/src/scss/composer.scss
  addons/pos_hr/__manifest__.py
Labels: staging.saas-12.2

#3615 Syncing from upstream odoo/odoo (staging.10.0)
  addons/website/models/ir_actions.py
Labels: staging.10.0

#3619 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mail/static/src/scss/chatter.scss
  addons/mail/static/src/scss/composer.scss
  addons/pos_hr/__manifest__.py
Labels: tmp.saas-12.2

#3621 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/website/models/ir_actions.py
Labels: tmp.10.0

#3624 Syncing from upstream odoo/odoo (10.0)
  addons/point_of_sale/static/src/js/models.js
Labels: 10.0

#3625 Syncing from upstream odoo/odoo (11.0)
  addons/calendar/models/res_partner.py
  addons/survey/static/src/js/survey.js
Labels: 11.0

#3626 Syncing from upstream odoo/odoo (12.0)
  addons/account/security/account_security.xml
  addons/account/views/report_invoice.xml
  addons/board/static/src/scss/dashboard.scss
  addons/calendar/models/res_partner.py
  addons/digest/models/digest.py
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/js/chatter.js
  addons/mrp/wizard/mrp_product_produce.py
  addons/product/models/product_template.py
  addons/product/tests/test_product_attribute_value_config.py
  addons/purchase/models/account_invoice.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template.py
  addons/sale_management/views/sale_portal_templates.xml
  addons/stock/report/report_stockinventory.xml
  addons/stock_account/views/product_views.xml
  addons/survey/static/src/js/survey.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
  odoo/addons/base/models/res_currency.py
Labels: 12.0

#3628 Syncing from upstream odoo/odoo (saas-11.3)
  addons/calendar/models/res_partner.py
  addons/survey/static/src/js/survey.js
Labels: saas-11.3

#3634 Syncing from upstream odoo/odoo (staging.10.0)
  addons/point_of_sale/static/src/js/models.js
Labels: staging.10.0

#3640 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/point_of_sale/static/src/js/models.js
Labels: tmp.10.0

#3643 [t10038] Odoo Security Advisory - ODOO-SA-2018-08-07
  odoo/addons/base/res/res_users.py
  odoo/service/security.py
Labels: 10.0.project_lu_268

#3644 Syncing from upstream odoo/odoo (10.0)
  addons/l10n_ca/data/account_tax_data.xml
  addons/point_of_sale/models/pos_order.py
Labels: 10.0

#3645 Syncing from upstream odoo/odoo (11.0)
  addons/account/__init__.py
  addons/website_sale/models/res_config_settings.py
Labels: 11.0

#3646 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/mail/models/ir_attachment.py
  addons/stock_account/models/stock.py
Labels: 12.0

#3647 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_be/data/account_data.xml
  addons/l10n_be/data/account_tax_template_data.xml
  addons/stock/models/res_company.py
  addons/web/static/src/scss/kanban_view.scss
  addons/web/static/src/scss/model_field_selector.scss
  addons/web/static/src/xml/base.xml
  addons/website/static/src/js/menu/navbar.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/views/website_navbar_templates.xml
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/views/website_forum.xml
  addons/website_rating/static/src/js/website_mail.js
  addons/website_rating/static/src/scss/website_rating.scss
  addons/website_rating/static/src/xml/website_mail.xml
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  doc/cla/individual/heckad.md
  odoo/http.py
Labels: master

#3648 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/mail/models/ir_attachment.py
Labels: saas-12.1

#3649 Syncing from upstream odoo/odoo (saas-12.2)
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/mail/models/ir_attachment.py
  addons/snailmail/static/tests/chatter_snailmail_tests.js
Labels: saas-12.2

#3652 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/account/models/account_move.py
  addons/account/security/account_security.xml
  addons/account/tests/test_reconciliation.py
  addons/account/views/report_invoice.xml
  addons/board/static/src/scss/dashboard.scss
  addons/calendar/models/res_partner.py
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/js/chatter.js
  addons/product/models/product_template.py
  addons/product/tests/test_product_attribute_value_config.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template.py
  addons/sale_management/views/sale_portal_templates.xml
  addons/snailmail/static/tests/chatter_snailmail_tests.js
  addons/stock/report/report_stockinventory.xml
  addons/stock_account/views/product_views.xml
  addons/survey/static/src/js/survey.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
  addons/website_sale_slides/__manifest__.py
  odoo/addons/base/models/res_currency.py
Labels: staging.saas-12.2

#3653 Syncing from upstream odoo/odoo (staging.10.0)
  addons/l10n_ca/data/account_tax_data.xml
  addons/point_of_sale/models/pos_order.py
Labels: staging.10.0

#3657 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/account/models/account_move.py
  addons/account/security/account_security.xml
  addons/account/tests/test_reconciliation.py
  addons/account/views/report_invoice.xml
  addons/board/static/src/scss/dashboard.scss
  addons/calendar/models/res_partner.py
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/js/chatter.js
  addons/product/models/product_template.py
  addons/product/tests/test_product_attribute_value_config.py
  addons/sale/report/sale_report_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template.py
  addons/sale_management/views/sale_portal_templates.xml
  addons/snailmail/static/tests/chatter_snailmail_tests.js
  addons/stock/report/report_stockinventory.xml
  addons/stock_account/views/product_views.xml
  addons/survey/static/src/js/survey.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
  addons/website_sale_slides/__manifest__.py
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-12.2

#3658 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/l10n_ca/data/account_tax_data.xml
  addons/point_of_sale/models/pos_order.py
Labels: tmp.10.0

#3661 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/res_users.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/stock/models/stock_picking.py
  doc/cla/individual/hviniciusg.md
  odoo/tests/common.py
Labels: 12.0

#3662 Syncing from upstream odoo/odoo (master)
  addons/mail/static/src/scss/composer.scss
  addons/mail/static/src/xml/composer.xml
  addons/sale_management/views/sale_order_template_views.xml
  addons/stock/views/product_views.xml
  addons/website/views/snippets.xml
  odoo/addons/base/views/res_partner_views.xml
Labels: master

#3663 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/i18n/account.pot
  addons/account/models/res_users.py
  addons/l10n_be_hr_payroll/models/l10n_be_hr_payroll.py
  addons/l10n_be_hr_payroll/views/l10n_be_hr_payroll_view.xml
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/stock_account/models/stock.py
  doc/cla/individual/hviniciusg.md
  odoo/tests/common.py
Labels: saas-12.1

#3664 Syncing from upstream odoo/odoo (saas-12.2)
  addons/account/i18n/account.pot
  addons/account/models/res_users.py
  addons/l10n_be_hr_payroll/models/l10n_be_hr_payroll.py
  addons/l10n_be_hr_payroll/views/l10n_be_hr_payroll_view.xml
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/stock_account/models/stock.py
  addons/survey/controllers/main.py
  addons/survey/data/survey_demo_certification.xml
  addons/survey/models/survey_survey.py
  doc/cla/individual/hviniciusg.md
  odoo/tests/common.py
Labels: saas-12.2

#3665 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/res_users.py
  addons/account_check_printing/tests/test_print_check.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/snailmail/static/tests/chatter_snailmail_tests.js
  addons/stock_account/models/stock.py
  addons/survey/controllers/main.py
  addons/survey/data/survey_demo_certification.xml
  addons/survey/models/survey_survey.py
  doc/cla/individual/hviniciusg.md
  odoo/tests/common.py
Labels: saas-12.3

#3674 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/account_payment.py
  addons/purchase/models/account_invoice.py
Labels: 11.0

#3675 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/hr/i18n/hr.pot
  addons/hr/views/hr_views.xml
  addons/hw_screen/static/src/js/worker.js
  addons/purchase/models/account_invoice.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/views/list_tests.js
  addons/website_livechat/models/__init__.py
  addons/website_livechat/models/ir_http.py
  addons/website_sale/controllers/main.py
Labels: 12.0

#3677 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/models/account_invoice.py
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/web/static/src/js/fields/basic_fields.js
  addons/website_livechat/models/__init__.py
  addons/website_livechat/models/ir_http.py
  addons/website_sale/controllers/main.py
Labels: saas-12.1

#3678 Syncing from upstream odoo/odoo (saas-12.2)
  addons/hr_presence/views/hr_employee_views.xml
  addons/website_profile/views/website_profile.xml
  addons/website_sale_slides/__manifest__.py
  addons/website_slides/views/website_slides_templates_homepage.xml
Labels: saas-12.2

#3690 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/res_users.py
  addons/sale_management/tests/test_sale_ui.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: 12.0

#3696 Syncing from upstream odoo/odoo (10.0)
  requirements.txt
Labels: 10.0

#3697 Syncing from upstream odoo/odoo (11.0)
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/data/l10n_de_skr03_chart_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/l10n_de_skr04_chart_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/stock_account/models/product.py
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: 11.0

#3698 Syncing from upstream odoo/odoo (12.0)
  addons/account/__init__.py
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/account/security/account_security.xml
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_ua/__init__.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account.account.template.csv
  addons/l10n_ua/data/account_account_tag_data.xml
  addons/l10n_ua/data/account_chart_template.xml
  addons/l10n_ua/data/account_chart_template_config.xml
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_tag_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/l10n_ua/i18n/l10n_ua.pot
  addons/l10n_ua/static/description/icon.png
  addons/mail/models/ir_attachment.py
  addons/mail/models/ir_model.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/purchase/models/account_invoice.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
  addons/theme_bootswatch/static/lib/bootswatch/cyborg/_variables.scss
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/fonts.scss
  addons/web/static/src/scss/layout_clean.scss
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/scss/primary_variables.scss
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: 12.0

#3699 Syncing from upstream odoo/odoo (master)
  addons/link_tracker/views/link_tracker_views.xml
  addons/mail/static/src/js/followers.js
  addons/mail/static/src/js/models/messages/message.js
  addons/mail/static/src/js/systray/systray_messaging_menu.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/scss/discuss.scss
  addons/mail/static/src/xml/discuss.xml
  addons/mail/static/src/xml/thread.xml
  addons/mail/static/tests/chatter_tests.js
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/mass_mailing/models/mass_mailing.py
  addons/mass_mailing/views/link_tracker_views.xml
  addons/mass_mailing/views/mass_mailing_stats_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/views/mrp_unbuild_views.xml
  addons/portal/views/portal_templates.xml
  addons/project/views/project_views.xml
  addons/sale_management/models/sale_order.py
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  addons/stock/views/product_views.xml
  addons/stock/views/stock_quant_views.xml
  addons/stock/views/stock_scrap_views.xml
  addons/website/tests/test_qweb.py
Labels: master

#3700 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/__init__.py
  addons/account/models/account_payment.py
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/data/l10n_de_skr03_chart_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/l10n_de_skr04_chart_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/purchase/models/account_invoice.py
  addons/stock_account/models/product.py
  addons/website_sale/models/res_config_settings.py
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: saas-11.3

#3701 Syncing from upstream odoo/odoo (saas-12.1)
  addons/board/static/src/js/add_to_board_menu.js
  addons/board/static/src/js/board_view.js
  addons/board/static/tests/dashboard_tests.js
Labels: saas-12.1

#3702 Syncing from upstream odoo/odoo (saas-12.2)
  addons/l10n_be_hr_payroll_fleet/views/res_config_settings_views.xml
Labels: saas-12.2

#3703 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/stock/tests/__init__.py
  addons/stock/tests/common.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/stock/tests/test_shipment.py
  addons/stock/tests/test_warehouse.py
  addons/stock_account/tests/test_stockvaluation.py
Labels: saas-12.3

#3704 Syncing from upstream odoo/odoo (saas-14)
  addons/l10n_ca/data/account_tax_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  requirements.txt
Labels: saas-14

#3705 Syncing from upstream odoo/odoo (saas-15)
  addons/l10n_ca/data/account_tax_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  requirements.txt
Labels: saas-15

#3707 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/account/models/account_invoice.py
  addons/board/static/src/js/add_to_board_menu.js
  addons/board/static/src/js/board_view.js
  addons/board/static/tests/dashboard_tests.js
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/web/static/src/js/fields/basic_fields.js
  addons/website_livechat/models/__init__.py
  addons/website_livechat/models/ir_http.py
  addons/website_sale/controllers/main.py
Labels: staging.saas-12.1

#3710 Syncing from upstream odoo/odoo (staging.10.0)
  requirements.txt
Labels: staging.10.0

#3714 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/account/models/account_invoice.py
  addons/board/static/src/js/add_to_board_menu.js
  addons/board/static/src/js/board_view.js
  addons/board/static/tests/dashboard_tests.js
  addons/hw_screen/static/src/js/worker.js
  addons/l10n_be_hr_payroll/views/res_config_settings_views.xml
  addons/web/static/src/js/fields/basic_fields.js
  addons/website_livechat/models/__init__.py
  addons/website_livechat/models/ir_http.py
  addons/website_sale/controllers/main.py
Labels: tmp.saas-12.1

#3717 Syncing from upstream odoo/odoo (tmp.10.0)
  requirements.txt
Labels: tmp.10.0

#3720 Syncing from upstream odoo/odoo (11.0)
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/models/stock.py
  addons/purchase/tests/test_stockvaluation.py
  addons/sale_mrp/models/sale_mrp.py
Labels: 11.0

#3721 Syncing from upstream odoo/odoo (12.0)
  addons/account/views/account_portal_templates.xml
  addons/calendar/data/mail_data.xml
  addons/crm/data/crm_data.xml
  addons/crm/data/crm_demo.xml
  addons/crm/data/crm_lead_data.xml
  addons/delivery/models/sale_order.py
  addons/mrp/models/stock_rule.py
  addons/portal/views/portal_templates.xml
  addons/sale/data/sale_data.xml
  addons/sale/models/sale.py
  addons/sale/views/sale_portal_templates.xml
  addons/stock/models/stock_rule.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
Labels: 12.0

#3723 Syncing from upstream odoo/odoo (saas-11.3)
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/models/stock.py
  addons/purchase/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/purchase/tests/test_stockvaluation.py
Labels: saas-11.3

#3724 Syncing from upstream odoo/odoo (saas-12.1)
  addons/stock/models/stock_move_line.py
  addons/stock/security/stock_security.xml
  addons/website_livechat/views/website_livechat.xml
Labels: saas-12.1

#3725 Syncing from upstream odoo/odoo (saas-12.2)
  addons/mail/models/mail_channel.py
Labels: saas-12.2

#3726 Syncing from upstream odoo/odoo (saas-12.3)
  addons/stock/models/stock_warehouse.py
Labels: saas-12.3

#3727 Syncing from upstream odoo/odoo (saas-15)
  addons/l10n_ch/models/account_invoice.py
Labels: saas-15

#3729 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/__init__.py
  addons/account/models/account_invoice.py
  addons/account/models/account_payment.py
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_view.xml
  addons/account_asset/views/account_asset_views.xml
  addons/account_payment/views/account_portal_templates.xml
  addons/base_address_city/models/res_partner.py
  addons/calendar/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/http_routing/models/ir_http.py
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/data/l10n_de_skr03_chart_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/l10n_de_skr04_chart_data.xml
  addons/l10n_pl/data/account_tax_data.xml
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/chrome.js
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/product/views/product_views.xml
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/models/stock.py
  addons/purchase/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/purchase/tests/test_stockvaluation.py
  addons/stock/models/stock_inventory.py
  addons/stock/wizard/stock_immediate_transfer.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
  addons/survey/static/src/js/survey.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/widgets/widgets.js
  addons/website/models/ir_qweb.py
  addons/website/tests/test_qweb.py
  addons/website_sale/models/res_config_settings.py
  doc/cla/individual/bletourmy.md
  doc/cla/individual/matthewdwatkins.md
  odoo/addons/base/models/ir_module.py
  odoo/fields.py
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: staging.saas-11.3

#3730 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/stock/models/stock_move_line.py
  addons/stock/security/stock_security.xml
  addons/website_livechat/views/website_livechat.xml
Labels: staging.saas-12.1

#3731 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/mail/models/mail_channel.py
Labels: staging.saas-12.2

#3738 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/stock/models/stock_move_line.py
  addons/stock/security/stock_security.xml
  addons/website_livechat/views/website_livechat.xml
Labels: tmp.saas-12.1

#3739 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/mail/models/mail_channel.py
Labels: tmp.saas-12.2

#3743 Syncing from upstream odoo/odoo (10.0)
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/__init__.py
  addons/l10n_fr_pos_cert/models/account_fiscal_position.py
Labels: 10.0

#3744 Syncing from upstream odoo/odoo (11.0)
  addons/point_of_sale/views/account_journal_view.xml
  addons/website_sale/models/sale_order.py
Labels: 11.0

#3745 Syncing from upstream odoo/odoo (12.0)
  addons/calendar/models/mail_message.py
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/sale/models/sale.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/views/search/search_inputs.js
  addons/web/static/tests/views/search_view_tests.js
  addons/web_editor/static/src/js/editor/summernote.js
Labels: 12.0

#3746 Syncing from upstream odoo/odoo (master)
  addons/hr_contract/models/hr_contract.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/point_of_sale/static/src/xml/pos.xml
  addons/resource/models/resource.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/field_html_tests.js
Labels: master

#3747 Syncing from upstream odoo/odoo (saas-11.3)
  addons/sale_mrp/models/sale_mrp.py
Labels: saas-11.3

#3748 Syncing from upstream odoo/odoo (saas-12.1)
  addons/account/__init__.py
  addons/account/models/account_payment.py
  addons/account/models/res_users.py
  addons/account/security/account_security.xml
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/views/account_portal_templates.xml
  addons/calendar/data/mail_data.xml
  addons/calendar/models/mail_message.py
  addons/crm/data/crm_data.xml
  addons/crm/data/crm_demo.xml
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/hr/views/hr_views.xml
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_ua/__init__.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account.account.template.csv
  addons/l10n_ua/data/account_account_tag_data.xml
  addons/l10n_ua/data/account_chart_template.xml
  addons/l10n_ua/data/account_chart_template_config.xml
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_tag_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/l10n_ua/static/description/icon.png
  addons/mail/models/ir_attachment.py
  addons/mail/models/ir_model.py
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/portal/views/portal_templates.xml
  addons/purchase/models/account_invoice.py
  addons/sale/models/sale.py
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/tests/test_sale_ui.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_rule.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
  addons/theme_bootswatch/static/lib/bootswatch/cyborg/_variables.scss
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/fonts.scss
  addons/web/static/src/scss/layout_clean.scss
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/views/search_view_tests.js
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: saas-12.1

#3749 Syncing from upstream odoo/odoo (saas-12.2)
  addons/payment_payulatam/models/payment.py
Labels: saas-12.2

#3750 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/__manifest__.py
  addons/account/models/account.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/static/src/js/mail_activity.js
  addons/account/static/src/scss/account_activity.scss
  addons/account/static/src/xml/account_journal_activity.xml
  addons/account/tests/test_account_move_tax_lock_date.py
  addons/account/views/account.xml
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_view.xml
  addons/l10n_be/data/account_pcmn_belgium_data.xml
Labels: saas-12.3

#3752 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/sale_mrp/models/sale_mrp.py
Labels: staging.saas-11.3

#3753 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/payment_payulatam/models/payment.py
Labels: staging.saas-12.2

#3755 Syncing from upstream odoo/odoo (staging.10.0)
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/__init__.py
  addons/l10n_fr_pos_cert/models/account_fiscal_position.py
Labels: staging.10.0

#3760 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/payment_payulatam/models/payment.py
Labels: tmp.saas-12.2

#3762 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/__init__.py
  addons/l10n_fr_pos_cert/models/account_fiscal_position.py
Labels: tmp.10.0

#3765 Syncing from upstream odoo/odoo (11.0)
  addons/stock_dropshipping/models/purchase.py
  addons/stock_dropshipping/tests/test_dropship.py
Labels: 11.0

#3766 Syncing from upstream odoo/odoo (12.0)
  addons/base_setup/data/base_setup_data.xml
  addons/mail/models/mail_template.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_order.py
  addons/purchase_stock/models/stock.py
  addons/stock_dropshipping/tests/test_dropship.py
Labels: 12.0

#3767 Syncing from upstream odoo/odoo (master)
  addons/crm_iap_lead/models/crm_iap_lead_mining_request.py
  addons/crm_iap_lead/views/crm_iap_lead_views.xml
  addons/crm_iap_lead_website/views/crm_reveal_views.xml
  addons/fleet/__init__.py
  addons/fleet/data/fleet_demo.xml
  addons/fleet/models/__init__.py
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/models/fleet_vehicle_cost.py
  addons/fleet/models/fleet_vehicle_model.py
  addons/fleet/models/res_partner.py
  addons/fleet/security/ir.model.access.csv
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_model_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr/views/hr_views.xml
  addons/hr_presence/data/ir_actions_server.xml
  addons/l10n_in/data/res_partner_demo.xml
  addons/mail/models/__init__.py
  addons/mail/models/ir_model.py
  addons/mail/models/ir_model_fields.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_tracking_value.py
  addons/mail/models/res_partner.py
  addons/mail/static/src/js/models/messages/abstract_message.js
  addons/point_of_sale/views/account_journal_view.xml
  addons/project/__manifest__.py
  addons/project/static/src/js/project.js
  addons/project/static/src/scss/project_dashboard.scss
  addons/project/static/src/xml/project.xml
  addons/project/static/tests/project_tests.js
  addons/project/views/project_assets.xml
  addons/project/views/project_views.xml
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/stock/views/stock_quant_views.xml
  addons/test_mail/tests/test_message_track.py
  addons/web/static/src/js/views/kanban/kanban_record.js
  addons/web/static/src/scss/kanban_view.scss
  addons/web/static/src/xml/kanban.xml
  addons/web/static/tests/views/kanban_tests.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/scss/website.scss
  addons/website_forum/views/forum.xml
  odoo/modules/registry.py
Labels: master

#3768 Syncing from upstream odoo/odoo (saas-12.1)
  addons/sale/__manifest__.py
  addons/website_forum/views/website_forum.xml
Labels: saas-12.1

#3769 Syncing from upstream odoo/odoo (saas-12.2)
  addons/event/controllers/main.py
  addons/web_editor/static/src/js/wysiwyg/plugin/keyboard.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
Labels: saas-12.2

#3770 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/js/widgets/attach_document.js
Labels: saas-12.3

#3772 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/account/__init__.py
  addons/account/models/account_payment.py
  addons/account/models/res_users.py
  addons/account/security/account_security.xml
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/views/account_portal_templates.xml
  addons/calendar/data/mail_data.xml
  addons/calendar/models/mail_message.py
  addons/crm/data/crm_data.xml
  addons/crm/data/crm_demo.xml
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/hr/views/hr_views.xml
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_ua/__init__.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account.account.template.csv
  addons/l10n_ua/data/account_account_tag_data.xml
  addons/l10n_ua/data/account_chart_template.xml
  addons/l10n_ua/data/account_chart_template_config.xml
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_tag_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/l10n_ua/static/description/icon.png
  addons/mail/models/ir_attachment.py
  addons/mail/models/ir_model.py
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/portal/views/portal_templates.xml
  addons/purchase/models/account_invoice.py
  addons/sale/__manifest__.py
  addons/sale/models/sale.py
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/tests/test_sale_ui.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_rule.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
  addons/theme_bootswatch/static/lib/bootswatch/cyborg/_variables.scss
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/fonts.scss
  addons/web/static/src/scss/layout_clean.scss
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/views/search_view_tests.js
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website_forum/views/website_forum.xml
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: staging.saas-12.1

#3773 Syncing from upstream odoo/odoo (staging.saas-12.2)
  addons/event/controllers/main.py
  addons/web_editor/static/src/js/wysiwyg/plugin/keyboard.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
Labels: staging.saas-12.2

#3775 Syncing from upstream odoo/odoo (staging.10.0)
  addons/website_event_sale/models/sale_order.py
Labels: staging.10.0

#3779 Syncing from upstream odoo/odoo (tmp.saas-12.1)
  addons/account/__init__.py
  addons/account/models/account_payment.py
  addons/account/models/res_users.py
  addons/account/security/account_security.xml
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/views/account_portal_templates.xml
  addons/calendar/data/mail_data.xml
  addons/calendar/models/mail_message.py
  addons/crm/data/crm_data.xml
  addons/crm/data/crm_demo.xml
  addons/delivery/models/sale_order.py
  addons/delivery/views/delivery_view.xml
  addons/hr/views/hr_views.xml
  addons/l10n_ca/data/account_tax_data.xml
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_ua/__init__.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account.account.template.csv
  addons/l10n_ua/data/account_account_tag_data.xml
  addons/l10n_ua/data/account_chart_template.xml
  addons/l10n_ua/data/account_chart_template_config.xml
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_tag_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/l10n_ua/static/description/icon.png
  addons/mail/models/ir_attachment.py
  addons/mail/models/ir_model.py
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/portal/views/portal_templates.xml
  addons/purchase/models/account_invoice.py
  addons/sale/__manifest__.py
  addons/sale/models/sale.py
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/tests/test_sale_ui.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_rule.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock.py
  addons/theme_bootswatch/static/lib/bootswatch/cyborg/_variables.scss
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/fonts.scss
  addons/web/static/src/scss/layout_clean.scss
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/views/search_view_tests.js
  addons/web_editor/static/src/js/editor/summernote.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website_forum/views/website_forum.xml
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  requirements.txt
  setup/win32/winpy_requirements.txt
Labels: tmp.saas-12.1

#3780 Syncing from upstream odoo/odoo (tmp.saas-12.2)
  addons/event/controllers/main.py
  addons/web_editor/static/src/js/wysiwyg/plugin/keyboard.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
Labels: tmp.saas-12.2

#3782 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/website_event_sale/models/sale_order.py
Labels: tmp.10.0

#3785 Syncing from upstream odoo/odoo (10.0)
  addons/account/views/report_overdue.xml
  addons/auth_signup/controllers/main.py
  addons/website_event_sale/models/sale_order.py
  addons/website_quote/views/sale_order_views.xml
Labels: 10.0

#3786 Syncing from upstream odoo/odoo (12.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/models/res_config_settings.py
  addons/resource/security/resource_security.xml
Labels: 12.0

#3788 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web/static/src/js/core/dom.js
  addons/web/static/src/js/public/public_root.js
  addons/website/static/src/js/content/menu.js
  addons/website_sale/static/src/js/website_sale.js
Labels: saas-12.3

#3792 Syncing from upstream odoo/odoo (staging.10.0)
  addons/account/views/report_overdue.xml
  addons/auth_signup/controllers/main.py
  addons/website_quote/views/sale_order_views.xml
Labels: staging.10.0

#3796 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/account/views/report_overdue.xml
  addons/auth_signup/controllers/main.py
  addons/website_quote/views/sale_order_views.xml
Labels: tmp.10.0

#3800 Syncing from upstream odoo/odoo (master)
  addons/account/views/account_invoice_view.xml
  addons/calendar/views/calendar_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/membership/views/product_views.xml
  addons/product/views/product_views.xml
  addons/purchase/views/purchase_views.xml
  addons/resource/views/resource_views.xml
  addons/sale/views/sale_views.xml
  addons/stock/wizard/product_replenish_views.xml
  addons/web/static/src/scss/form_view.scss
  addons/website_forum/views/forum.xml
Labels: master

#3804 Syncing from upstream odoo/odoo (10.0)
  addons/base_import_module/models/ir_module.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/website_quote/controllers/main.py
  addons/website_quote/static/src/js/website_quotation.js
  addons/website_quote/views/website_quote_templates.xml
Labels: 10.0

#3805 Syncing from upstream odoo/odoo (11.0)
  addons/event_sale/models/sale_order.py
  addons/sale_timesheet/models/account.py
  addons/stock/models/stock_move.py
Labels: 11.0

#3806 Syncing from upstream odoo/odoo (12.0)
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/purchase/report/purchase_bill.py
  addons/purchase/views/purchase_views.xml
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/views/list_tests.js
  odoo/addons/base/data/res_currency_data.xml
Labels: 12.0

#3808 Syncing from upstream odoo/odoo (saas-12.1)
  addons/l10n_be_hr_payroll/data/l10n_be_hr_payroll_data.xml
Labels: saas-12.1

#3809 Syncing from upstream odoo/odoo (saas-12.2)
  addons/website/views/website_navbar_templates.xml
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_forum/views/website_forum.xml
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_profile/views/website_profile.xml
  addons/website_sale/controllers/main.py
  addons/website_sale_slides/views/website_slides_templates.xml
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides_forum/views/website_slides_forum_templates.xml
  addons/website_slides_survey/static/src/img/certification.svg
  addons/website_slides_survey/static/src/scss/website_profile.scss
  addons/website_slides_survey/static/src/scss/website_slides_survey.scss
  addons/website_slides_survey/views/assets.xml
  addons/website_slides_survey/views/survey_templates.xml
  addons/website_slides_survey/views/website_slides_templates_course.xml
  addons/website_slides_survey/views/website_slides_templates_homepage.xml
Labels: saas-12.2

#3810 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/__manifest__.py
  addons/account/models/account.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/chart_template.py
  addons/account/models/reconciliation_widget.py
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_view.xml
  addons/account/views/tax_adjustments.xml
  addons/account/wizard/account_invoice_refund.py
  addons/l10n_be/data/account_reconcile_model_template.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/mrp/__init__.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/test_workorder_operation.py
  addons/point_of_sale/views/account_statement_view.xml
  addons/pos_hr/static/src/js/gui.js
  addons/pos_mercury/views/pos_mercury_views.xml
  addons/stock/models/stock_warehouse.py
  addons/web/static/tests/helpers/qunit_config.js
  addons/web_editor/static/src/js/wysiwyg/plugin/link.js
  addons/web_editor/static/src/js/wysiwyg/plugin/media.js
  addons/web_editor/static/tests/wysiwyg_keyboard_tests.js
Labels: saas-12.3

#3811 Syncing from upstream odoo/odoo (saas-14)
  addons/account/views/report_overdue.xml
  addons/auth_signup/controllers/main.py
  addons/base_import_module/models/ir_module.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/__init__.py
  addons/l10n_fr_pos_cert/models/account_fiscal_position.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/website_event_sale/models/sale_order.py
  addons/website_quote/controllers/main.py
  addons/website_quote/static/src/js/website_quotation.js
  addons/website_quote/views/sale_order_views.xml
  addons/website_quote/views/website_quote_templates.xml
Labels: saas-14

#3815 Syncing from upstream odoo/odoo (staging.10.0)
  addons/base_import_module/models/ir_module.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/website_quote/controllers/main.py
  addons/website_quote/static/src/js/website_quotation.js
  addons/website_quote/views/website_quote_templates.xml
Labels: staging.10.0

#3821 Syncing from upstream odoo/odoo (tmp.10.0)
  addons/base_import_module/models/ir_module.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/website_quote/controllers/main.py
  addons/website_quote/static/src/js/website_quotation.js
  addons/website_quote/views/website_quote_templates.xml
Labels: tmp.10.0

#3824 Syncing from upstream odoo/odoo (10.0)
  addons/mrp_byproduct/models/mrp_subproduct.py
Labels: 10.0

#3825 Syncing from upstream odoo/odoo (11.0)
  addons/account/views/report_overdue.xml
  addons/auth_signup/controllers/main.py
  addons/base_import_module/models/ir_module.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_fr_pos_cert/models/__init__.py
  addons/l10n_fr_pos_cert/models/account_fiscal_position.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/web/static/src/js/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar_tests.js
  addons/website_event_sale/models/sale_order.py
  addons/website_quote/controllers/main.py
  addons/website_quote/static/src/js/website_quotation.js
  addons/website_quote/views/sale_order_views.xml
  addons/website_quote/views/website_quote_templates.xml
  odoo/addons/base/ir/ir_qweb/fields.py
Labels: 11.0

#3826 Syncing from upstream odoo/odoo (12.0)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/mrp/models/stock_warehouse.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_warehouse.py
  addons/stock/views/stock_move_views.xml
  addons/web/doc/module.rst
  addons/website/models/res_users.py
  addons/website_sale/controllers/main.py
  addons/website_sale_comparison/static/src/js/website_sale_tour_comparison.js
  addons/website_sale_comparison/tests/test_website_sale_comparison.py
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: 12.0

#3829 Syncing from upstream odoo/odoo (saas-12.2)
  addons/lunch/report/lunch_product_report.py
  addons/portal/views/portal_templates.xml
  addons/survey/views/survey_templates.xml
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/views/kanban_model_tests.js
  addons/website_survey/views/website_survey_templates.xml
Labels: saas-12.2

#3830 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/__manifest__.py
  addons/account/data/service_cron.xml
  addons/account/data/service_cron_reverse.xml
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/account/views/account_move_views.xml
Labels: saas-12.3

#3831 Syncing from upstream odoo/odoo (saas-15)
  addons/account/views/report_overdue.xml
  addons/auth_signup/controllers/main.py
  addons/base_import_module/models/ir_module.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/__init__.py
  addons/l10n_fr_pos_cert/models/account_fiscal_position.py
  addons/point_of_sale/data/point_of_sale_data.xml
  addons/website_event_sale/models/sale_order.py
  addons/website_quote/controllers/main.py
  addons/website_quote/static/src/js/website_quotation.js
  addons/website_quote/views/sale_order_views.xml
  addons/website_quote/views/website_quote_templates.xml
Labels: saas-15

#3833 Syncing from upstream odoo/odoo (staging.saas-12.1)
  addons/l10n_be_hr_payroll/data/l10n_be_hr_payroll_data.xml
Labels: staging.saas-12.1
