Repository brain-tec/odoo, pull requests merged in 2019-09, with the labels that each got.

#5377 Syncing from upstream odoo/odoo (11.0)
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: 11.0

#5378 Syncing from upstream odoo/odoo (12.0)
  addons/account_voucher/models/account_voucher.py
  addons/account_voucher/tests/test_account_voucher.py
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/main.py
  addons/mail/static/src/scss/thread.scss
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
  odoo/addons/base/models/ir_actions_report.py
Labels: 12.0

#5379 Syncing from upstream odoo/odoo (saas-11.3)
  addons/mail/static/src/less/thread.less
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: saas-11.3

#5380 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mail/static/tests/discuss_mobile_tests.js
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/web/models/ir_qweb.py
Labels: saas-12.3

#5381 Syncing from upstream odoo/odoo (saas-12.5)
  addons/mail/static/src/js/views/activity/activity_renderer.js
  addons/mail/static/tests/activity_tests.js
  addons/project/views/project_views.xml
  addons/web/static/src/js/views/kanban/kanban_column_progressbar.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/src/scss/kanban_column_progressbar.scss
  addons/web/static/src/scss/webclient.scss
  addons/web/static/tests/views/form_tests.js
  addons/web/static/tests/views/kanban_tests.js
  doc/reference/views.rst
  odoo/tools/translate.py
Labels: saas-12.5

#5382 Syncing from upstream odoo/odoo (saas-14)
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: saas-14

#5383 Syncing from upstream odoo/odoo (saas-15)
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  doc/reference/cmdline.rst
Labels: saas-15

#5392 Syncing from upstream odoo/odoo (11.0)
  addons/im_livechat/static/src/js/im_livechat.js
  addons/website_blog/static/src/js/website_blog.js
Labels: 11.0

#5393 Syncing from upstream odoo/odoo (12.0)
  addons/bus/static/src/js/crosstab_bus.js
  addons/mail/static/src/js/models/threads/document_thread.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_window_manager.js
  addons/mail/static/tests/document_thread_window_tests.js
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/payment_sips/models/payment.py
  addons/payment_sips/views/payment_views.xml
  addons/web/static/src/js/core/abstract_storage_service.js
  addons/web/static/src/js/core/local_storage.js
  addons/web/static/src/js/core/ram_storage.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/views/list_tests.js
Labels: 12.0

#5394 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account_cancel/views/account_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/account_voucher/tests/test_account_voucher.py
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/main.py
  addons/mail/static/src/js/models/threads/searchable_thread.js
  addons/mail/static/src/scss/thread.scss
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/mrp/models/mrp_production.py
  addons/payment_sips/models/payment.py
  addons/payment_sips/views/payment_views.xml
  addons/sale_purchase/models/sale_order.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale_digital/controllers/main.py
  addons/website_sale_slides/controllers/i18n/so.po
  doc/reference/cmdline.rst
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-12.3

#5395 Syncing from upstream odoo/odoo (saas-12.4)
  addons/mail/views/mail_activity_views.xml
Labels: saas-12.4

#5397 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account_cancel/views/account_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/account_voucher/tests/test_account_voucher.py
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/main.py
  addons/mail/static/src/js/models/threads/searchable_thread.js
  addons/mail/static/src/scss/thread.scss
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/mrp/models/mrp_production.py
  addons/payment_sips/models/payment.py
  addons/payment_sips/views/payment_views.xml
  addons/sale_purchase/models/sale_order.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale_digital/controllers/main.py
  addons/website_sale_slides/controllers/i18n/so.po
  doc/reference/cmdline.rst
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.saas-12.3

#5402 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account_cancel/views/account_views.xml
  addons/account_voucher/models/account_voucher.py
  addons/account_voucher/tests/test_account_voucher.py
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/main.py
  addons/mail/static/src/js/models/threads/searchable_thread.js
  addons/mail/static/src/scss/thread.scss
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/mrp/models/mrp_production.py
  addons/payment_sips/models/payment.py
  addons/payment_sips/views/payment_views.xml
  addons/sale_purchase/models/sale_order.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale_digital/controllers/main.py
  addons/website_sale_slides/controllers/i18n/so.po
  doc/reference/cmdline.rst
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-12.3

#5407 Syncing from upstream odoo/odoo (10.0)
  addons/account/models/account_bank_statement.py
  addons/mail/models/mail_thread.py
  addons/payment_payumoney/models/payment.py
  addons/web/static/src/js/views/search_view.js
  addons/web/static/src/js/widgets/auto_complete.js
  addons/website_google_map/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale_options/controllers/main.py
  doc/cla/corporate/international-business-hub.md
  doc/cla/corporate/quartile.md
Labels: 10.0

#5431 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/chart_template.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: 11.0

#5432 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/models/reconciliation_widget.py
  addons/account/views/account_invoice_view.xml
  addons/im_livechat/static/src/js/im_livechat.js
  addons/payment_paypal/controllers/main.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock_account/models/product.py
  addons/stock_account/views/stock_account_views.xml
  addons/stock_account/wizard/stock_quantity_history.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/scss/banner.scss
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web_editor/static/src/js/widgets/widgets.js
Labels: 12.0

#5433 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: saas-11.3

#5434 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_payment.py
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_payment.py
  addons/account/views/account_invoice_view.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/payment_paypal/controllers/main.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/sale/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
Labels: saas-12.3

#5436 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: staging.saas-11.3

#5437 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_payment.py
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_payment.py
  addons/account/views/account_invoice_view.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/payment_paypal/controllers/main.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/sale/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
Labels: staging.saas-12.3

#5441 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
Labels: tmp.saas-11.3

#5442 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_payment.py
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_payment.py
  addons/account/views/account_invoice_view.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/payment_paypal/controllers/main.py
  addons/payment_payumoney/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/sale/models/payment.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
Labels: tmp.saas-12.3

#5446 [bt#7976] Solve cache problem on users
  openerp/addons/base/res/res_users.py
Labels: 9.0.project_eb_212

#5447 Syncing from upstream odoo/odoo (11.0)
  addons/l10n_be_intrastat/wizard/xml_decl.py
Labels: 11.0

#5449 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
Labels: staging.saas-12.3

#5450 Syncing from upstream odoo/odoo (staging.saas-12.5)
  addons/account/models/account.py
  addons/l10n_ie/__manifest__.py
  addons/l10n_ie/data/account.chart.template.csv
  addons/sale_coupon/models/sale_order.py
  odoo/models.py
Labels: staging.saas-12.5

#5453 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
Labels: tmp.saas-12.3

#5457 Syncing from upstream odoo/odoo (11.0)
  addons/sale/models/sale.py
Labels: 11.0

#5458 Syncing from upstream odoo/odoo (12.0)
  addons/mrp/models/mrp_production.py
  addons/payment/models/payment_acquirer.py
  addons/payment_stripe_sca/models/payment.py
  addons/sale/models/sale.py
  addons/stock/models/stock_warehouse.py
  addons/web/controllers/main.py
  addons/website_event/controllers/main.py
  addons/website_sale/data/mail_template_data.xml
  doc/reference/cmdline.rst
  doc/setup/install.rst
  odoo/addons/base/wizard/base_language_install.py
Labels: 12.0

#5460 Syncing from upstream odoo/odoo (saas-11.3)
  addons/l10n_be_intrastat/wizard/xml_decl.py
  addons/sale/models/sale.py
Labels: saas-11.3

#5461 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_reconcile_model.py
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/auth_signup/models/res_partner.py
  addons/event/controllers/main.py
  addons/im_livechat/static/src/js/im_livechat.js
  addons/payment/models/payment_acquirer.py
  addons/payment_stripe_sca/models/payment.py
  addons/sale/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/src/scss/banner.scss
  addons/website_sale/data/mail_template_data.xml
  odoo/addons/base/wizard/base_language_install.py
Labels: saas-12.3

#5475 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/account/views/account_view.xml
  addons/auth_signup/models/res_partner.py
  addons/digest/data/res_config_settings_data.xml
  addons/mrp/models/mrp_production.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/web/static/tests/views/search_view_tests.js
  addons/web_editor/static/src/scss/web_editor.ui.scss
Labels: 12.0

#5476 Syncing from upstream odoo/odoo (saas-12.3)
  addons/digest/data/res_config_settings_data.xml
  addons/l10n_in/data/account_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_manager.js
  addons/mail/static/src/js/systray/systray_activity_menu.js
  addons/mail/static/src/js/systray/systray_messaging_menu.js
  addons/mail/static/src/js/thread_field.js
  addons/mail/static/src/scss/discuss.scss
  addons/mail/static/src/xml/discuss.xml
  addons/mail/static/src/xml/systray.xml
  addons/mail/static/tests/discuss_tests.js
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/snailmail/models/res_partner.py
  addons/web/static/src/js/fields/abstract_field.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/widgets/domain_selector_tests.js
  addons/website/static/src/scss/website.scss
  addons/website_event_questions/report/report_event_question_view.xml
Labels: saas-12.3

#5477 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/payment_stripe_sca/static/src/js/payment_processing.js
Labels: saas-12.4

#5480 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/digest/data/res_config_settings_data.xml
  addons/l10n_in/data/account_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_manager.js
  addons/mail/static/src/js/systray/systray_activity_menu.js
  addons/mail/static/src/js/systray/systray_messaging_menu.js
  addons/mail/static/src/js/thread_field.js
  addons/mail/static/src/scss/discuss.scss
  addons/mail/static/src/xml/discuss.xml
  addons/mail/static/src/xml/systray.xml
  addons/mail/static/tests/discuss_tests.js
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/snailmail/models/res_partner.py
  addons/web/static/src/js/fields/abstract_field.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/widgets/domain_selector_tests.js
  addons/website/static/src/scss/website.scss
  addons/website_event_questions/report/report_event_question_view.xml
Labels: staging.saas-12.3

#5485 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/digest/data/res_config_settings_data.xml
  addons/l10n_in/data/account_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/services/mail_document_thread_manager.js
  addons/mail/static/src/js/services/mail_manager.js
  addons/mail/static/src/js/systray/systray_activity_menu.js
  addons/mail/static/src/js/systray/systray_messaging_menu.js
  addons/mail/static/src/js/thread_field.js
  addons/mail/static/src/scss/discuss.scss
  addons/mail/static/src/xml/discuss.xml
  addons/mail/static/src/xml/systray.xml
  addons/mail/static/tests/discuss_tests.js
  addons/mail/static/tests/systray/systray_messaging_menu_tests.js
  addons/snailmail/models/res_partner.py
  addons/web/static/src/js/fields/abstract_field.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/widgets/domain_selector_tests.js
  addons/website/static/src/scss/website.scss
  addons/website_event_questions/report/report_event_question_view.xml
Labels: tmp.saas-12.3

#5489 Syncing from upstream odoo/odoo (11.0)
  addons/sale/models/sale.py
  addons/web/static/src/css/reset.min.css
  odoo/service/model.py
Labels: 11.0

#5490 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/sale/models/sale.py
  addons/stock/models/stock_move.py
  addons/web/static/src/css/reset.min.css
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web_editor/static/src/scss/web_editor.ui.scss
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_non_regression.py
  odoo/addons/base/tests/test_user_has_group.py
Labels: 12.0

#5491 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mail/models/mail_cc_mixin.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_thread.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/common.py
  addons/test_mail/tests/test_discuss.py
  addons/test_mail/tests/test_mail_channel.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_message_track.py
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mail_channel.py
  addons/website_slides/wizard/slide_channel_invite.py
  doc/_extensions/odoo_ext/pygments_override.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_partner.py
  odoo/tools/mail.py
Labels: master

#5492 Syncing from upstream odoo/odoo (saas-11.3)
  addons/sale/models/sale.py
  addons/web/static/src/css/reset.min.css
Labels: saas-11.3

#5493 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/views/account_view.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/sale/models/sale.py
  addons/stock/models/stock_move.py
  addons/web/static/src/css/reset.min.css
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/web/static/tests/views/search_view_tests.js
  doc/howtos/website/module-empty
  doc/reference/actions.rst
  doc/reference/cmdline.rst
  doc/reference/data.rst
  doc/reference/javascript_api.rst
  doc/reference/javascript_cheatsheet.rst
  doc/reference/javascript_reference.rst
  doc/reference/mixins.rst
  doc/reference/module.rst
  doc/reference/qweb.rst
  doc/reference/reports.rst
  doc/reference/test-report.txt
  doc/reference/testing.rst
  doc/reference/translations.rst
  doc/setup/deploy.rst
  doc/webservices/iap.rst
  doc/webservices/odoo.rst
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_non_regression.py
  odoo/addons/base/tests/test_user_has_group.py
Labels: saas-12.3

#5496 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/sale/models/sale.py
  addons/web/static/src/css/reset.min.css
Labels: staging.saas-11.3

#5497 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/views/account_view.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/sale/models/sale.py
  addons/stock/models/stock_move.py
  addons/web/static/src/css/reset.min.css
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/web/static/tests/views/search_view_tests.js
  doc/howtos/website/module-empty
  doc/reference/actions.rst
  doc/reference/cmdline.rst
  doc/reference/data.rst
  doc/reference/javascript_api.rst
  doc/reference/javascript_cheatsheet.rst
  doc/reference/javascript_reference.rst
  doc/reference/mixins.rst
  doc/reference/module.rst
  doc/reference/qweb.rst
  doc/reference/reports.rst
  doc/reference/test-report.txt
  doc/reference/testing.rst
  doc/reference/translations.rst
  doc/setup/deploy.rst
  doc/webservices/iap.rst
  doc/webservices/odoo.rst
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_non_regression.py
  odoo/addons/base/tests/test_user_has_group.py
Labels: staging.saas-12.3

#5503 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/sale/models/sale.py
  addons/web/static/src/css/reset.min.css
Labels: tmp.saas-11.3

#5504 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/views/account_view.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/product/models/product_template.py
  addons/sale/models/sale.py
  addons/stock/models/stock_move.py
  addons/web/static/src/css/reset.min.css
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/src/js/widgets/date_picker.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/web/static/tests/views/search_view_tests.js
  doc/howtos/website/module-empty
  doc/reference/actions.rst
  doc/reference/cmdline.rst
  doc/reference/data.rst
  doc/reference/javascript_api.rst
  doc/reference/javascript_cheatsheet.rst
  doc/reference/javascript_reference.rst
  doc/reference/mixins.rst
  doc/reference/module.rst
  doc/reference/qweb.rst
  doc/reference/reports.rst
  doc/reference/test-report.txt
  doc/reference/testing.rst
  doc/reference/translations.rst
  doc/setup/deploy.rst
  doc/webservices/iap.rst
  doc/webservices/odoo.rst
  doc/webservices/upgrade.rst
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_non_regression.py
  odoo/addons/base/tests/test_user_has_group.py
Labels: tmp.saas-12.3

#5508 Syncing from upstream odoo/odoo (11.0)
  addons/payment_stripe_sca/models/payment.py
  addons/payment_stripe_sca/static/src/js/payment_form.js
Labels: 11.0

#5509 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_reconciliation_widget.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/payment_stripe_sca/models/payment.py
  odoo/service/model.py
Labels: 12.0

#5512 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_reconciliation_widget.py
  addons/mrp/models/product.py
  addons/payment_stripe_sca/models/payment.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move2.py
  addons/survey/controllers/main.py
  addons/survey/static/src/js/survey.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/basic_fields_tests.js
  doc/reference/cmdline.rst
  doc/setup/install.rst
  odoo/service/model.py
Labels: saas-12.3

#5513 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
Labels: saas-12.4

#5516 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/payment_stripe_sca/models/payment.py
  odoo/service/model.py
Labels: staging.saas-11.3

#5517 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_reconciliation_widget.py
  addons/mrp/models/product.py
  addons/payment_stripe_sca/models/payment.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move2.py
  addons/survey/controllers/main.py
  addons/survey/static/src/js/survey.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/basic_fields_tests.js
  doc/reference/cmdline.rst
  doc/setup/install.rst
  odoo/service/model.py
Labels: staging.saas-12.3

#5520 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/base/ir/ir_cron.py
  odoo/service/server.py
Labels: staging.10.0

#5524 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/payment_stripe_sca/models/payment.py
  odoo/service/model.py
Labels: tmp.saas-11.3

#5525 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/account/tests/test_reconciliation_widget.py
  addons/mrp/models/product.py
  addons/payment_stripe_sca/models/payment.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move2.py
  addons/survey/controllers/main.py
  addons/survey/static/src/js/survey.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/basic_fields_tests.js
  doc/reference/cmdline.rst
  doc/setup/install.rst
  odoo/service/model.py
Labels: tmp.saas-12.3

#5528 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/base/ir/ir_cron.py
  odoo/service/server.py
Labels: tmp.10.0

#5531 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/base/ir/ir_cron.py
  odoo/service/server.py
Labels: 10.0

#5532 Syncing from upstream odoo/odoo (saas-12.5)
  addons/website/models/website_visitor.py
  addons/website/static/src/scss/website_visitor_views.scss
  addons/website/views/website_templates.xml
  addons/website/views/website_visitor_views.xml
  addons/website_crm/views/website_visitor_views.xml
  addons/website_livechat/static/src/scss/mail_thread_visitor_info.scss
  addons/website_livechat/views/website_visitor_views.xml
  addons/website_sms/views/website_visitor_views.xml
Labels: saas-12.5

#5533 Syncing from upstream odoo/odoo (staging.saas-12.5)
  addons/website/models/website_visitor.py
  addons/website/static/src/scss/website_visitor_views.scss
  addons/website/views/website_templates.xml
  addons/website/views/website_visitor_views.xml
  addons/website_crm/views/website_visitor_views.xml
  addons/website_livechat/static/src/scss/mail_thread_visitor_info.scss
  addons/website_livechat/views/website_visitor_views.xml
  addons/website_sms/views/website_visitor_views.xml
Labels: staging.saas-12.5

#5535 Syncing from upstream odoo/odoo (tmp.saas-12.5)
  addons/website/models/website_visitor.py
  addons/website/static/src/scss/website_visitor_views.scss
  addons/website/views/website_templates.xml
  addons/website/views/website_visitor_views.xml
  addons/website_crm/views/website_visitor_views.xml
  addons/website_livechat/static/src/scss/mail_thread_visitor_info.scss
  addons/website_livechat/views/website_visitor_views.xml
  addons/website_sms/views/website_visitor_views.xml
Labels: tmp.saas-12.5

#5538 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/addons/base/models/ir_cron.py
  odoo/service/server.py
Labels: saas-11.3

#5539 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/addons/base/models/ir_cron.py
  odoo/service/server.py
Labels: saas-12.3

#5542 Syncing from upstream odoo/odoo (staging.saas-11.3)
  odoo/addons/base/models/ir_cron.py
  odoo/service/server.py
Labels: staging.saas-11.3

#5543 Syncing from upstream odoo/odoo (staging.saas-12.3)
  odoo/addons/base/models/ir_cron.py
  odoo/service/server.py
Labels: staging.saas-12.3

#5546 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  odoo/addons/base/models/ir_cron.py
  odoo/service/server.py
Labels: tmp.saas-11.3

#5547 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  odoo/addons/base/models/ir_cron.py
  odoo/service/server.py
Labels: tmp.saas-12.3

#5550 Syncing from upstream odoo/odoo (10.0)
  odoo/addons/base/res/res_currency_data.xml
Labels: 10.0

#5551 Syncing from upstream odoo/odoo (11.0)
  addons/web_editor/static/src/js/editor/summernote.js
  addons/website_sale_wishlist/controllers/main.py
  odoo/addons/base/ir/ir_cron.py
  odoo/addons/base/res/res_currency_data.xml
Labels: 11.0

#5552 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_reconcile_model.py
  addons/account/models/res_users.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/product/models/product.py
  addons/purchase_stock/models/stock_rule.py
  addons/web/static/src/js/core/dom.js
  addons/web_editor/static/src/js/editor/summernote.js
  addons/website_sale_wishlist/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/res_config.py
  odoo/service/server.py
  odoo/tools/misc.py
Labels: 12.0

#5553 Syncing from upstream odoo/odoo (master)
  doc/cla/individual/r-sierra.md
  odoo/addons/base/data/res.country.state.csv
Labels: master

#5554 Syncing from upstream odoo/odoo (saas-11.3)
  addons/payment_stripe_sca/static/src/js/payment_form.js
  addons/web_editor/static/src/js/editor/summernote.js
  addons/website_sale_wishlist/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
Labels: saas-11.3

#5555 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/res_users.py
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/web/static/src/js/core/dom.js
  addons/website_sale_wishlist/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/res_config.py
  odoo/service/server.py
  odoo/tools/misc.py
Labels: saas-12.3

#5556 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/account/tests/account_test_no_chart.py
  addons/account/tests/test_account_move_entry.py
  addons/hr_org_chart/controllers/hr_org_chart.py
  addons/hr_org_chart/static/src/js/hr_org_chart.js
  addons/purchase/tests/test_purchase_order_report.py
  addons/sale/tests/test_reinvoice.py
  addons/sale/tests/test_sale_order.py
Labels: saas-12.4

#5557 Syncing from upstream odoo/odoo (saas-12.5)
  addons/account/data/data_account_type.xml
  addons/account/models/account_move.py
  addons/account/static/src/js/account_selection.js
  addons/account/views/account_move_views.xml
  addons/account/wizard/account_accrual_accounting_view.xml
  addons/auth_signup/controllers/main.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/tests/test_lead2opportunity.py
  addons/hr/models/hr_employee_base.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_attendance/data/hr_attendance_demo.xml
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_contract/data/hr_contract_demo.xml
  addons/hr_holidays/data/hr_holidays_demo.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_org_chart/static/src/scss/hr_org_chart.scss
  addons/hr_presence/models/hr_employee.py
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/views/project_views.xml
  addons/hw_drivers/controllers/driver.py
  addons/hw_drivers/drivers/KeyboardUSBDriver.py
  addons/l10n_cn_city/data/res_city_data.xml
  addons/mail/static/src/js/views/activity/activity_controller.js
  addons/mass_mailing_sms/static/description/icon.png
  addons/mass_mailing_sms/static/description/icon.svg
  addons/mrp/views/mrp_workcenter_views.xml
  addons/point_of_sale/static/src/css/pos_receipts.css
  addons/point_of_sale/static/src/js/printers.js
  addons/point_of_sale/static/src/xml/pos.xml
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.5/dist-packages/keysym_to_ucs.py
  addons/resource/data/resource_data.xml
  addons/sms/models/mail_message.py
  addons/sms/static/img/sms_failure.png
  addons/sms/static/img/sms_failure.svg
  addons/sms/static/src/js/fields_phone_widget.js
  addons/sms/static/src/xml/thread.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/website_visitor.py
  addons/website/static/tests/tours/reset_password.js
  addons/website_mass_mailing/views/snippets_templates.xml
  odoo/addons/base/models/ir_model.py
  odoo/models.py
Labels: saas-12.5

#5560 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/res_users.py
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/web/static/src/js/core/dom.js
  addons/website_sale_wishlist/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/res_config.py
  odoo/service/server.py
  odoo/tools/misc.py
Labels: staging.saas-12.3

#5563 Syncing from upstream odoo/odoo (staging.10.0)
  odoo/addons/base/res/res_currency_data.xml
Labels: staging.10.0

#5568 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/res_users.py
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/web/static/src/js/core/dom.js
  addons/website_sale_wishlist/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/res_config.py
  odoo/service/server.py
  odoo/tools/misc.py
Labels: tmp.saas-12.3

#5571 Syncing from upstream odoo/odoo (tmp.10.0)
  odoo/addons/base/res/res_currency_data.xml
Labels: tmp.10.0

#5574 Syncing from upstream odoo/odoo (11.0)
  addons/account/models/partner.py
  addons/l10n_ch/views/account_invoice_view.xml
Labels: 11.0

#5576 Syncing from upstream odoo/odoo (master)
  addons/web/static/src/js/core/dom.js
Labels: master

#5577 Syncing from upstream odoo/odoo (saas-11.3)
  addons/account/models/partner.py
  addons/l10n_ch/views/account_invoice_view.xml
  odoo/addons/base/models/ir_cron.py
Labels: saas-11.3

#5578 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/partner.py
  addons/base_import/models/base_import.py
  addons/google_calendar/models/google_calendar.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
  addons/product/models/product.py
  addons/stock/i18n/fr.po
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: saas-12.3

#5582 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/account/models/partner.py
  addons/l10n_ch/views/account_invoice_view.xml
Labels: staging.saas-11.3

#5583 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/partner.py
  addons/base_import/models/base_import.py
  addons/google_calendar/models/google_calendar.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
  addons/product/models/product.py
  addons/stock/i18n/fr.po
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: staging.saas-12.3

#5589 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/account/models/partner.py
  addons/l10n_ch/views/account_invoice_view.xml
Labels: tmp.saas-11.3

#5590 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/partner.py
  addons/base_import/models/base_import.py
  addons/google_calendar/models/google_calendar.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
  addons/product/models/product.py
  addons/stock/i18n/fr.po
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
Labels: tmp.saas-12.3

#5595 Syncing from upstream odoo/odoo (11.0)
  addons/web_editor/static/src/js/editor/summernote.js
Labels: 11.0

#5596 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_rounding.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/sale/models/sale.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/js/core/ajax.js
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
Labels: 12.0

#5597 Syncing from upstream odoo/odoo (master)
  addons/point_of_sale/models/pos_order.py
Labels: master

#5598 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/account_analytic_default/models/account_analytic_default.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_in/models/account_invoice.py
  addons/purchase_requisition/models/purchase.py
  addons/website/controllers/backend.py
  addons/website/models/ir_ui_view.py
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
Labels: saas-12.3

#5599 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/partner.py
  addons/account_analytic_default/models/account_analytic_default.py
  addons/base_import/models/base_import.py
  addons/google_calendar/models/google_calendar.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/tests/discuss_tests.js
  addons/product/models/product.py
  addons/purchase_requisition/models/purchase.py
  addons/stock/i18n/fr.po
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/tests/chrome/action_manager_tests.js
  addons/website/controllers/backend.py
  addons/website/models/ir_ui_view.py
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  odoo/addons/base/models/ir_cron.py
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
  odoo/tools/image.py
Labels: saas-12.4

#5602 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account_analytic_default/models/account_analytic_default.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_in/models/account_invoice.py
  addons/purchase_requisition/models/purchase.py
  addons/website/controllers/backend.py
  addons/website/models/ir_ui_view.py
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
Labels: staging.saas-12.3

#5607 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account_analytic_default/models/account_analytic_default.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_in/models/account_invoice.py
  addons/purchase_requisition/models/purchase.py
  addons/website/controllers/backend.py
  addons/website/models/ir_ui_view.py
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  odoo/addons/test_testing_utilities/menu.xml
  odoo/addons/test_testing_utilities/tests/test_form_impl.py
  odoo/tests/common.py
Labels: tmp.saas-12.3

#5611 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/mail/models/mail_thread.py
Labels: saas-12.4

#5612 Syncing from upstream odoo/odoo (saas-12.5)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/tests/views/control_panel_tests.js
Labels: saas-12.5

#5613 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/web/static/src/js/core/ajax.js
Labels: staging.saas-12.3

#5614 Syncing from upstream odoo/odoo (staging.saas-12.5)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/tests/views/control_panel_tests.js
Labels: staging.saas-12.5

#5616 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/web/static/src/js/core/ajax.js
Labels: tmp.saas-12.3

#5617 Syncing from upstream odoo/odoo (tmp.saas-12.5)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/web/static/src/js/views/control_panel/control_panel_view.js
  addons/web/static/tests/views/control_panel_tests.js
Labels: tmp.saas-12.5

#5618 Syncing from upstream odoo/odoo (11.0)
  addons/mrp/models/mrp_routing.py
  addons/payment_ogone/views/payment_views.xml
Labels: 11.0

#5619 Syncing from upstream odoo/odoo (12.0)
  addons/mail/static/src/js/attachment_box.js
  addons/mail/static/src/js/models/messages/abstract_message.js
  addons/mrp/models/mrp_routing.py
  addons/payment_ogone/views/payment_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/sale/controllers/portal.py
  addons/web_editor/static/src/js/editor/summernote.js
Labels: 12.0

#5620 Syncing from upstream odoo/odoo (saas-11.3)
  addons/mrp/models/mrp_routing.py
  addons/payment_ogone/views/payment_views.xml
  addons/web_editor/static/src/js/editor/summernote.js
Labels: saas-11.3

#5621 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_rounding.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/mail/static/src/js/attachment_box.js
  addons/mail/static/src/js/models/messages/abstract_message.js
  addons/payment_ogone/views/payment_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/screens.js
  addons/pos_hr/static/src/js/screens.js
  addons/sale/models/sale.py
  addons/web/static/src/js/core/ajax.js
Labels: saas-12.3

#5622 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/mail/static/src/js/attachment_box.js
  addons/mail/static/src/js/models/messages/abstract_message.js
  addons/payment_ogone/views/payment_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/screens.js
  addons/pos_hr/static/src/js/screens.js
  addons/sale/models/sale.py
  addons/web/static/src/js/core/ajax.js
Labels: saas-12.4

#5624 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/mrp/models/mrp_routing.py
  addons/payment_ogone/views/payment_views.xml
  addons/web_editor/static/src/js/editor/summernote.js
Labels: staging.saas-11.3

#5625 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_rounding.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/mail/static/src/js/attachment_box.js
  addons/mail/static/src/js/models/messages/abstract_message.js
  addons/payment_ogone/views/payment_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/screens.js
  addons/pos_hr/static/src/js/screens.js
  addons/sale/models/sale.py
Labels: staging.saas-12.3

#5629 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/mrp/models/mrp_routing.py
  addons/payment_ogone/views/payment_views.xml
  addons/web_editor/static/src/js/editor/summernote.js
Labels: tmp.saas-11.3

#5630 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_rounding.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/mail/static/src/js/attachment_box.js
  addons/mail/static/src/js/models/messages/abstract_message.js
  addons/payment_ogone/views/payment_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/screens.js
  addons/pos_hr/static/src/js/screens.js
  addons/sale/models/sale.py
Labels: tmp.saas-12.3

#5647 Syncing from upstream odoo/odoo (10.0)
  doc/cla/corporate/odooexperts.md
Labels: 10.0

#5648 Syncing from upstream odoo/odoo (11.0)
  addons/mail/static/src/less/thread.less
  doc/cla/corporate/odooexperts.md
  doc/cla/individual/ezchan.md
Labels: 11.0

#5649 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_invoice.py
  addons/account/tests/__init__.py
  addons/account/tests/test_settings.py
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/thread_widget.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/scss/thread.scss
  addons/mail/static/src/xml/thread.xml
  addons/payment/__init__.py
  addons/payment/__manifest__.py
  doc/reference/mixins.rst
  odoo/addons/base/models/res_config.py
  odoo/fields.py
Labels: 12.0

#5650 Syncing from upstream odoo/odoo (saas-11.3)
  addons/l10n_de/data/res.country.state.csv
  addons/mail/static/src/less/thread.less
Labels: saas-11.3

#5651 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/thread_widget.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/xml/thread.xml
  addons/mrp/models/mrp_routing.py
  addons/sale/controllers/portal.py
  odoo/fields.py
Labels: saas-12.3

#5652 Syncing from upstream odoo/odoo (saas-12.4)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_move_reversal_view.xml
  addons/account_facturx/models/account_move.py
  addons/mrp/models/mrp_routing.py
  addons/sale/controllers/portal.py
Labels: saas-12.4

#5655 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/hr_holidays/security/ir.model.access.csv
  addons/l10n_de/data/res.country.state.csv
  addons/mail/static/src/less/thread.less
Labels: staging.saas-11.3

#5656 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_invoice.py
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/thread_widget.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/xml/thread.xml
  addons/mrp/models/mrp_routing.py
  addons/sale/controllers/portal.py
  odoo/fields.py
Labels: staging.saas-12.3

#5658 Syncing from upstream odoo/odoo (staging.10.0)
  doc/cla/corporate/odooexperts.md
  doc/cla/individual/kos94ok-3d.md
Labels: staging.10.0

#5662 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/hr_holidays/security/ir.model.access.csv
  addons/l10n_de/data/res.country.state.csv
  addons/mail/static/src/less/thread.less
Labels: tmp.saas-11.3

#5663 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account_invoice.py
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/static/src/js/discuss.js
  addons/mail/static/src/js/thread_widget.js
  addons/mail/static/src/js/thread_windows/abstract_thread_window.js
  addons/mail/static/src/xml/thread.xml
  addons/mrp/models/mrp_routing.py
  addons/sale/controllers/portal.py
  odoo/fields.py
Labels: tmp.saas-12.3

#5665 Syncing from upstream odoo/odoo (tmp.10.0)
  doc/cla/corporate/odooexperts.md
  doc/cla/individual/kos94ok-3d.md
Labels: tmp.10.0
