Repository brain-tec/odoo, pull requests merged in 2020-11, with the labels that each got.

#11822 Syncing from upstream odoo/odoo (14.0)
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: 14.0

#11823 Syncing from upstream odoo/odoo (master)
  addons/website_form/static/src/snippets/s_website_form/000.js
  odoo/addons/test_populate/models.py
  odoo/addons/test_populate/tests/test_populate.py
  odoo/models.py
  odoo/tools/populate.py
Labels: master

#11824 Syncing from upstream odoo/odoo (saas-13.3)
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: saas-13.3

#11826 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: staging.saas-13.3

#11827 Syncing from upstream odoo/odoo (staging.14.0)
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: staging.14.0

#11829 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: tmp.saas-13.3

#11830 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: tmp.14.0

#11832 Syncing from upstream odoo/odoo (11.0)
  addons/account/i18n/ca.po
  addons/account/i18n/fa.po
  addons/account/i18n/ja.po
  addons/account_analytic_default/i18n/ja.po
  addons/account_asset/i18n/fa.po
  addons/account_bank_statement_import/i18n/fa.po
  addons/account_cash_basis_base_account/i18n/fa.po
  addons/account_cash_basis_base_account/i18n/ja.po
  addons/auth_oauth/i18n/ja.po
  addons/base_geolocalize/i18n/es.po
  addons/delivery/i18n/es.po
  addons/fleet/i18n/fa.po
  addons/gamification/i18n/fa.po
  addons/gamification_sale_crm/i18n/ja.po
  addons/google_calendar/i18n/ja.po
  addons/google_spreadsheet/i18n/ja.po
  addons/hr_expense/i18n/sk.po
  addons/hr_payroll/i18n/sv.po
  addons/mail/i18n/fa.po
  addons/mail/i18n/pt_BR.po
  addons/mass_mailing/i18n/fa.po
  addons/mrp/i18n/fa.po
  addons/note/i18n/fa.po
  addons/payment/i18n/fa.po
  addons/point_of_sale/i18n/fa.po
  addons/portal/i18n/fa.po
  odoo/addons/base/i18n/da.po
  odoo/addons/base/i18n/fa.po
  odoo/addons/base/i18n/pt_BR.po
  odoo/addons/base/i18n/sk.po
  odoo/addons/base/i18n/zh_CN.po
Labels: 11.0

#11835 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/src/js/models.js
Labels: 14.0

#11838 Syncing from upstream odoo/odoo (staging.14.0)
  addons/point_of_sale/static/src/js/models.js
Labels: staging.14.0

#11840 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/point_of_sale/static/src/js/models.js
Labels: tmp.14.0

#11841 Syncing from upstream odoo/odoo (11.0)
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: 11.0

#11842 Syncing from upstream odoo/odoo (12.0)
  addons/account_facturx/models/account_invoice.py
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/composers/mention_manager.js
  addons/product/models/product_pricelist.py
  addons/sale/models/sale.py
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: 12.0

#11843 Syncing from upstream odoo/odoo (13.0)
  addons/account/data/account_data.xml
  addons/account/views/res_config_settings_views.xml
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/lunch/views/res_config_settings.xml
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/views/res_config_settings_views.xml
  addons/pad/models/pad.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/product/models/product_pricelist.py
  addons/project/views/res_config_settings_views.xml
  addons/purchase/models/res_partner.py
  addons/purchase/views/res_config_settings_views.xml
  addons/repair/views/repair_views.xml
  addons/sale/models/sale.py
  addons/sale/views/res_config_settings_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_rule.py
  addons/stock/views/res_config_settings_views.xml
  addons/website/views/res_config_settings_views.xml
  addons/website_gengo/controllers/main.py
  addons/website_slides/views/res_config_settings_views.xml
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: 13.0

#11844 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account_edi/models/account_journal.py
  addons/crm/models/res_partner.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/l10n_it_edi/models/ddt.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/components/message_author_prefix/message_author_prefix.xml
  addons/mail/static/src/components/message_list/message_list.xml
  addons/mail/static/src/components/messaging_menu/messaging_menu_tests.js
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview.xml
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview_tests.js
  addons/mail/static/src/components/thread_preview/thread_preview.js
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/models/composer/composer.js
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/src/models/thread_view/thread_view.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mrp/models/stock_rule.py
  addons/portal_rating/static/src/js/portal_chatter.js
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/rating/models/rating_mixin.py
  addons/sale/models/sale.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/models/ir_actions.py
  addons/website/models/ir_module_module.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/js/tours/homepage.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.scss
  addons/website/views/website_views.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_event/static/src/js/tours/website_event.js
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/base/views/base_menus.xml
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: 14.0

#11845 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/common.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account_edi/models/account_journal.py
  addons/crm/models/res_partner.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/components/message_author_prefix/message_author_prefix.xml
  addons/mail/static/src/components/message_list/message_list.xml
  addons/mail/static/src/components/messaging_menu/messaging_menu_tests.js
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview.xml
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview_tests.js
  addons/mail/static/src/components/thread_preview/thread_preview.js
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/models/composer/composer.js
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/src/models/thread_view/thread_view.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/point_of_sale/static/src/js/models.js
  addons/portal_rating/static/src/js/portal_chatter.js
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/rating/models/rating_mixin.py
  addons/sale/models/sale.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_countdown/options.js
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: master

#11846 Syncing from upstream odoo/odoo (saas-11.3)
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: saas-11.3

#11847 Syncing from upstream odoo/odoo (saas-12.3)
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/sale/models/sale.py
  addons/stock/models/stock_rule.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: saas-12.3

#11848 Syncing from upstream odoo/odoo (saas-13.3)
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_rule.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_gengo/controllers/main.py
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  doc/cla/individual/mihranthalhath.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: saas-13.3

#11850 Syncing from upstream odoo/odoo (staging.saas-11.3)
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: staging.saas-11.3

#11851 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/sale/models/sale.py
  addons/stock/models/stock_rule.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: staging.saas-12.3

#11852 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_rule.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_gengo/controllers/main.py
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  doc/cla/individual/mihranthalhath.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: staging.saas-13.3

#11856 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account_edi/models/account_journal.py
  addons/crm/models/res_partner.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/l10n_it_edi/models/ddt.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/components/message_author_prefix/message_author_prefix.xml
  addons/mail/static/src/components/message_list/message_list.xml
  addons/mail/static/src/components/messaging_menu/messaging_menu_tests.js
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview.xml
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview_tests.js
  addons/mail/static/src/components/thread_preview/thread_preview.js
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/models/composer/composer.js
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/src/models/thread_view/thread_view.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mrp/models/stock_rule.py
  addons/portal_rating/static/src/js/portal_chatter.js
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/rating/models/rating_mixin.py
  addons/sale/models/sale.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/models/ir_actions.py
  addons/website/models/ir_module_module.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/js/tours/homepage.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.scss
  addons/website/views/website_views.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_event/static/src/js/tours/website_event.js
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/base/views/base_menus.xml
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: staging.14.0

#11858 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: tmp.saas-11.3

#11859 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product_pricelist.py
  addons/sale/models/sale.py
  addons/stock/models/stock_rule.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: tmp.saas-12.3

#11860 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/composers/mention_manager.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_rule.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_gengo/controllers/main.py
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  doc/cla/individual/mihranthalhath.md
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: tmp.saas-13.3

#11864 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account_edi/models/account_journal.py
  addons/crm/models/res_partner.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/l10n_hu/data/account.account.template.csv
  addons/l10n_it_edi/models/ddt.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/components/message_author_prefix/message_author_prefix.xml
  addons/mail/static/src/components/message_list/message_list.xml
  addons/mail/static/src/components/messaging_menu/messaging_menu_tests.js
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview.xml
  addons/mail/static/src/components/thread_needaction_preview/thread_needaction_preview_tests.js
  addons/mail/static/src/components/thread_preview/thread_preview.js
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/models/composer/composer.js
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/src/models/thread_view/thread_view.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mrp/models/stock_rule.py
  addons/portal_rating/static/src/js/portal_chatter.js
  addons/pos_epson_printer/models/pos_config.py
  addons/product/models/product_pricelist.py
  addons/purchase/models/res_partner.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/rating/models/rating_mixin.py
  addons/sale/models/sale.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/models/ir_actions.py
  addons/website/models/ir_module_module.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/js/tours/homepage.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.scss
  addons/website/views/website_views.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_event/static/src/js/tours/website_event.js
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_forum/controllers/main.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_mail_channel/models/mail_channel.py
  doc/cla/corporate/arxilead.md
  doc/cla/corporate/factorlibre.md
  odoo/addons/base/views/base_menus.xml
  odoo/addons/test_inherits/models.py
  odoo/addons/test_inherits/tests/test_inherits.py
  odoo/models.py
Labels: tmp.14.0

#11865 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/account_cash_rounding.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: 12.0

#11866 Syncing from upstream odoo/odoo (13.0)
  addons/account/report/account_aged_partner_balance.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/tools/debug_manager_backend.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: 13.0

#11867 Syncing from upstream odoo/odoo (14.0)
  addons/account/data/account_data.xml
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_journal_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_automation.py
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/fleet_board_view.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/lunch/views/res_config_settings.xml
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/views/res_config_settings_views.xml
  addons/pad/models/pad.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_restaurant/models/pos_order.py
  addons/pos_sale/models/crm_team.py
  addons/project/views/res_config_settings_views.xml
  addons/purchase/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_bill.py
  addons/purchase/views/res_config_settings_views.xml
  addons/sale/views/res_config_settings_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/views/res_config_settings_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/js/components/dropdown_menu.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/res_config_settings_views.xml
  addons/website_slides/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/security/base_security.xml
  odoo/addons/base/tests/test_ir_actions.py
Labels: 14.0

#11869 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mail/models/mail_message.py
  addons/sale/models/sale.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: saas-12.3

#11870 Syncing from upstream odoo/odoo (saas-13.3)
  addons/account/data/account_data.xml
  addons/account/views/res_config_settings_views.xml
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/lunch/views/res_config_settings.xml
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/views/res_config_settings_views.xml
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/project/views/res_config_settings_views.xml
  addons/purchase/views/res_config_settings_views.xml
  addons/sale/views/res_config_settings_views.xml
  addons/stock/views/res_config_settings_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/js/components/dropdown_menu.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_slides/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: saas-13.3

#11872 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mail/models/mail_message.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: staging.saas-12.3

#11873 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/account/data/account_data.xml
  addons/account/views/res_config_settings_views.xml
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/lunch/views/res_config_settings.xml
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/views/res_config_settings_views.xml
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/project/views/res_config_settings_views.xml
  addons/purchase/views/res_config_settings_views.xml
  addons/sale/views/res_config_settings_views.xml
  addons/stock/views/res_config_settings_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/js/components/dropdown_menu.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_slides/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: staging.saas-13.3

#11874 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/account_cash_rounding.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: staging.12.0

#11875 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/report/account_aged_partner_balance.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/tools/debug_manager_backend.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: staging.13.0

#11876 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/data/account_data.xml
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_journal_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_automation.py
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/fleet_board_view.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/lunch/views/res_config_settings.xml
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/views/res_config_settings_views.xml
  addons/pad/models/pad.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_restaurant/models/pos_order.py
  addons/pos_sale/models/crm_team.py
  addons/project/views/res_config_settings_views.xml
  addons/purchase/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_bill.py
  addons/purchase/views/res_config_settings_views.xml
  addons/sale/views/res_config_settings_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/views/res_config_settings_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/js/components/dropdown_menu.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/res_config_settings_views.xml
  addons/website_slides/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/security/base_security.xml
  odoo/addons/base/tests/test_ir_actions.py
Labels: staging.14.0

#11878 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mail/models/mail_message.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: tmp.saas-12.3

#11879 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/account/data/account_data.xml
  addons/account/views/res_config_settings_views.xml
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/lunch/views/res_config_settings.xml
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/views/res_config_settings_views.xml
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/project/views/res_config_settings_views.xml
  addons/purchase/views/res_config_settings_views.xml
  addons/sale/views/res_config_settings_views.xml
  addons/stock/views/res_config_settings_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/js/components/dropdown_menu.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_slides/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: tmp.saas-13.3

#11880 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/account_cash_rounding.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: tmp.12.0

#11881 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/report/account_aged_partner_balance.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale.py
  addons/sale/report/sale_report_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/tools/debug_manager_backend.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: tmp.13.0

#11882 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/data/account_data.xml
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_journal_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_automation.py
  addons/crm/views/res_config_settings_views.xml
  addons/event/views/res_config_settings_views.xml
  addons/fleet/views/fleet_board_view.xml
  addons/fleet/views/res_config_settings_views.xml
  addons/hr/views/res_config_settings_views.xml
  addons/hr_attendance/views/res_config_settings_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/res_config_settings_views.xml
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/lunch/views/res_config_settings.xml
  addons/mass_mailing/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/views/res_config_settings_views.xml
  addons/pad/models/pad.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_restaurant/models/pos_order.py
  addons/pos_sale/models/crm_team.py
  addons/project/views/res_config_settings_views.xml
  addons/purchase/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_bill.py
  addons/purchase/views/res_config_settings_views.xml
  addons/sale/views/res_config_settings_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/views/res_config_settings_views.xml
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/js/components/dropdown_menu.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/res_config_settings_views.xml
  addons/website_slides/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/security/base_security.xml
  odoo/addons/base/tests/test_ir_actions.py
Labels: tmp.14.0

#11883 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_reconcile_model.py
  addons/test_mail/tests/test_ui.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/vauxoo.md
Labels: 12.0

#11884 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_reconcile_model.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  addons/pos_cash_rounding/views/pos_config_view.xml
  addons/test_mail/tests/test_ui.py
Labels: 13.0

#11885 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_cl/__manifest__.py
  addons/l10n_cl/demo/demo_company.xml
  addons/mail/static/src/components/composer_suggestion/composer_suggestion_channel_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_moderation_tests.js
  addons/point_of_sale/models/account_move.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_event/static/src/js/website_geolocation.js
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_slides/static/src/components/activity/activity_tests.js
  odoo/addons/base/data/res_partner_data.xml
  odoo/addons/base/data/res_partner_demo.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/base/views/res_users_views.xml
Labels: 14.0

#11886 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/coupon/views/coupon_program_views.xml
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/crm/views/crm_lead_views.xml
  addons/event/views/event_views.xml
  addons/fleet/views/fleet_board_view.xml
  addons/l10n_cl/__manifest__.py
  addons/l10n_cl/demo/demo_company.xml
  addons/mail/static/src/components/composer_suggestion/composer_suggestion_channel_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_moderation_tests.js
  addons/mass_mailing/views/mailing_contact_views.xml
  addons/mass_mailing/views/mailing_list_views.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/point_of_sale/models/account_move.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/point_of_sale/views/res_partner_view.xml
  addons/product/views/product_views.xml
  addons/project/models/res_partner.py
  addons/project/static/src/scss/project_dashboard.scss
  addons/project/views/project_views.xml
  addons/sales_team/views/crm_team_views.xml
  addons/utm/views/utm_campaign_views.xml
  addons/web/static/src/js/core/utils.js
  addons/web/static/src/scss/kanban_view.scss
  addons/web_editor/static/lib/jabberwock/jabberwock.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/models/ir_actions.py
  addons/website/models/ir_module_module.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/js/tours/homepage.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_blockquote/options.js
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_masonry_block.xml
  addons/website/views/snippets/s_popup.xml
  addons/website/views/snippets/s_product_catalog.xml
  addons/website/views/snippets/s_quotes_carousel.xml
  addons/website/views/website_templates.xml
  addons/website/views/website_views.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_event/static/src/js/tours/website_event.js
  addons/website_event/static/src/js/website_geolocation.js
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_slides/static/src/components/activity/activity_tests.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/base/views/base_menus.xml
  odoo/addons/base/views/res_partner_views.xml
  odoo/addons/base/views/res_users_views.xml
Labels: master

#11887 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_reconcile_model.py
  addons/test_mail/tests/test_ui.py
Labels: saas-12.3

#11888 Syncing from upstream odoo/odoo (saas-13.3)
  addons/account/models/account_reconcile_model.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/test_mail/tests/test_ui.py
Labels: saas-13.3

#11890 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_reconcile_model.py
  addons/test_mail/tests/test_ui.py
Labels: staging.saas-12.3

#11891 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/account/models/account_reconcile_model.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/test_mail/tests/test_ui.py
Labels: staging.saas-13.3

#11892 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/models/account_reconcile_model.py
  addons/test_mail/tests/test_ui.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/vauxoo.md
Labels: staging.12.0

#11893 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_reconcile_model.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  addons/pos_cash_rounding/views/pos_config_view.xml
  addons/test_mail/tests/test_ui.py
Labels: staging.13.0

#11894 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_cl/__manifest__.py
  addons/l10n_cl/demo/demo_company.xml
  addons/mail/static/src/components/composer_suggestion/composer_suggestion_channel_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_moderation_tests.js
  addons/point_of_sale/models/account_move.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_event/static/src/js/website_geolocation.js
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_slides/static/src/components/activity/activity_tests.js
  odoo/addons/base/data/res_partner_data.xml
  odoo/addons/base/data/res_partner_demo.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/base/views/res_users_views.xml
Labels: staging.14.0

#11896 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_reconcile_model.py
  addons/test_mail/tests/test_ui.py
Labels: tmp.saas-12.3

#11897 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/account/models/account_reconcile_model.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/test_mail/tests/test_ui.py
Labels: tmp.saas-13.3

#11898 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/models/account_reconcile_model.py
  addons/test_mail/tests/test_ui.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/vauxoo.md
Labels: tmp.12.0

#11899 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_reconcile_model.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  addons/pos_cash_rounding/views/pos_config_view.xml
  addons/test_mail/tests/test_ui.py
Labels: tmp.13.0

#11900 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/crm/models/ir_config_parameter.py
  addons/crm/tests/test_crm_pls.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_cl/__manifest__.py
  addons/l10n_cl/demo/demo_company.xml
  addons/mail/static/src/components/composer_suggestion/composer_suggestion_channel_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_moderation_tests.js
  addons/point_of_sale/models/account_move.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_event/static/src/js/website_geolocation.js
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_slides/static/src/components/activity/activity_tests.js
  odoo/addons/base/data/res_partner_data.xml
  odoo/addons/base/data/res_partner_demo.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/base/views/res_users_views.xml
Labels: tmp.14.0

#11901 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/google_calendar/models/google_calendar.py
  addons/mail/static/src/js/followers.js
  addons/mrp/models/mrp_production.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/js/views/calendar/calendar_view.js
  odoo/fields.py
  odoo/models.py
Labels: 12.0

#11902 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/l10n_in/models/account_invoice.py
  addons/mail/static/src/js/followers.js
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
  odoo/models.py
Labels: 13.0

#11903 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/sequence_mixin.py
  addons/account/views/account_bank_statement_views.xml
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/fleet/views/fleet_board_view.xml
  addons/mail/models/mail_notification.py
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/models/partner/partner.js
  addons/mail/static/src/models/thread_cache/thread_cache.js
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/stock/models/stock_production_lot.py
  addons/web/static/src/js/control_panel/search_utils.js
  addons/web/static/src/scss/report.scss
  addons/web/static/tests/control_panel/search_utils_tests.js
  addons/web/views/report_templates.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/willdoo-it.md
Labels: 14.0

#11904 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/sequence_mixin.py
  addons/account/views/account_bank_statement_views.xml
  addons/crm/data/crm_lead_prediction_data.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/fleet/views/fleet_board_view.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/models/__init__.py
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/mail/models/mail_notification.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/models/partner/partner.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/src/models/thread_cache/thread_cache.js
  addons/mrp/models/mrp_production.py
  addons/purchase/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_bill.py
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_production_lot.py
  addons/stock/models/stock_quant.py
  addons/web/static/src/scss/form_view.scss
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/willdoo-it.md
  odoo/addons/base/data/res_partner_data.xml
  odoo/addons/base/data/res_partner_demo.xml
Labels: master

#11905 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/mail/static/src/js/followers.js
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  doc/cla/corporate/vauxoo.md
  odoo/fields.py
  odoo/models.py
Labels: saas-12.3

#11906 Syncing from upstream odoo/odoo (saas-13.3)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/calendar/models/mail_activity.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/mail/static/src/js/followers.js
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_authorize_templates.xml
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  doc/cla/corporate/vauxoo.md
Labels: saas-13.3

#11908 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/mail/static/src/js/followers.js
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  doc/cla/corporate/vauxoo.md
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-12.3

#11909 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/calendar/models/mail_activity.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/mail/static/src/js/followers.js
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_authorize_templates.xml
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  doc/cla/corporate/vauxoo.md
Labels: staging.saas-13.3

#11910 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/google_calendar/models/google_calendar.py
  addons/mail/static/src/js/followers.js
  addons/mrp/models/mrp_production.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/js/views/calendar/calendar_view.js
  odoo/fields.py
  odoo/models.py
Labels: staging.12.0

#11911 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/l10n_in/models/account_invoice.py
  addons/mail/static/src/js/followers.js
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
  odoo/models.py
Labels: staging.13.0

#11912 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/account_bank_statement_views.xml
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/fleet/views/fleet_board_view.xml
  addons/mail/models/mail_notification.py
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/models/partner/partner.js
  addons/mail/static/src/models/thread_cache/thread_cache.js
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/stock/models/stock_production_lot.py
  addons/web/static/src/js/control_panel/search_utils.js
  addons/web/static/src/scss/report.scss
  addons/web/static/tests/control_panel/search_utils_tests.js
  addons/web/views/report_templates.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/willdoo-it.md
Labels: staging.14.0

#11914 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/mail/static/src/js/followers.js
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web_editor/static/src/js/wysiwyg_snippets/snippets.editor.js
  doc/cla/corporate/vauxoo.md
  odoo/fields.py
  odoo/models.py
Labels: tmp.saas-12.3

#11915 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/calendar/models/mail_activity.py
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/mail/static/src/js/followers.js
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_authorize_templates.xml
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-13.3

#11916 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/google_calendar/models/google_calendar.py
  addons/mail/static/src/js/followers.js
  addons/mrp/models/mrp_production.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/js/views/calendar/calendar_view.js
  odoo/fields.py
  odoo/models.py
Labels: tmp.12.0

#11917 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/reconciliation_widget.py
  addons/calendar/models/mail_activity.py
  addons/l10n_in/models/account_invoice.py
  addons/mail/static/src/js/followers.js
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/web/static/src/js/views/calendar/calendar_view.js
  addons/web/static/src/scss/report.scss
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
  odoo/models.py
Labels: tmp.13.0

#11918 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/account_bank_statement_views.xml
  addons/event/data/email_template_data.xml
  addons/event/i18n/event.pot
  addons/fleet/views/fleet_board_view.xml
  addons/mail/models/mail_notification.py
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/models/partner/partner.js
  addons/mail/static/src/models/thread_cache/thread_cache.js
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/stock/models/stock_production_lot.py
  addons/web/static/src/js/control_panel/search_utils.js
  addons/web/static/src/scss/report.scss
  addons/web/static/tests/control_panel/search_utils_tests.js
  addons/web/views/report_templates.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/willdoo-it.md
Labels: tmp.14.0

#11919 Syncing from upstream odoo/odoo (12.0)
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
Labels: 12.0

#11920 Syncing from upstream odoo/odoo (13.0)
  addons/crm/models/res_partner.py
  addons/stock/models/stock_rule.py
Labels: 13.0

#11921 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/l10n_in/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/widgets/form_renderer/form_renderer.js
  addons/mass_mailing/models/utm.py
  addons/mass_mailing/report/mailing_trace_report_views.xml
  addons/mass_mailing_sms/report/mailing_trace_report_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/sms/i18n/sms.pot
  addons/sms/static/src/js/fields_sms_widget.js
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_rule.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/public/public_root.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/content.js
  addons/website/views/snippets/s_banner.xml
  addons/website/views/snippets/s_call_to_action.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_color_blocks_2.xml
  addons/website/views/snippets/s_comparisons.xml
  addons/website/views/snippets/s_cover.xml
  addons/website/views/snippets/s_image_text.xml
  addons/website/views/snippets/s_media_list.xml
  addons/website/views/snippets/s_popup.xml
  addons/website/views/snippets/s_showcase.xml
  addons/website/views/snippets/s_text_image.xml
  addons/website_crm_partner_assign/models/crm_lead.py
Labels: 14.0

#11922 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/crm/views/crm_lead_views.xml
  addons/l10n_in/models/account_invoice.py
  addons/mail/models/mail_activity.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/utm.py
  addons/mass_mailing/report/mailing_trace_report_views.xml
  addons/mass_mailing_sms/report/mailing_trace_report_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/note/static/src/scss/note.scss
  addons/note/views/note_views.xml
  addons/sms/i18n/sms.pot
  addons/sms/static/src/js/fields_sms_widget.js
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_rule.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web/static/src/js/control_panel/search_utils.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/public/public_root.js
  addons/web/static/tests/control_panel/search_utils_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/views/snippets/s_banner.xml
  addons/website/views/snippets/s_call_to_action.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_color_blocks_2.xml
  addons/website/views/snippets/s_comparisons.xml
  addons/website/views/snippets/s_cover.xml
  addons/website/views/snippets/s_image_text.xml
  addons/website/views/snippets/s_media_list.xml
  addons/website/views/snippets/s_popup.xml
  addons/website/views/snippets/s_showcase.xml
  addons/website/views/snippets/s_text_block.xml
  addons/website/views/snippets/s_text_image.xml
  addons/website/views/snippets/s_title.xml
  addons/website_crm_partner_assign/models/crm_lead.py
  odoo/addons/base/models/res_bank.py
Labels: master

#11923 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mrp/models/mrp_production.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_rule.py
Labels: saas-12.3

#11924 Syncing from upstream odoo/odoo (saas-13.3)
  addons/l10n_in/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/pad/models/pad.py
  addons/stock/models/stock_rule.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/tools/debug_manager_backend.js
Labels: saas-13.3

#11926 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mrp/models/mrp_production.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_rule.py
Labels: staging.saas-12.3

#11927 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/l10n_in/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/pad/models/pad.py
  addons/stock/models/stock_rule.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/tools/debug_manager_backend.js
Labels: staging.saas-13.3

#11928 Syncing from upstream odoo/odoo (staging.12.0)
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
Labels: staging.12.0

#11929 Syncing from upstream odoo/odoo (staging.13.0)
  addons/crm/models/res_partner.py
  addons/stock/models/stock_rule.py
Labels: staging.13.0

#11932 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mrp/models/mrp_production.py
  addons/stock/models/stock_inventory.py
  addons/stock/models/stock_rule.py
Labels: tmp.saas-12.3

#11933 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/l10n_in/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/pad/models/pad.py
  addons/stock/models/stock_rule.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/tools/debug_manager_backend.js
Labels: tmp.saas-13.3

#11934 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
Labels: tmp.12.0

#11935 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/crm/models/res_partner.py
  addons/stock/models/stock_rule.py
Labels: tmp.13.0

#11938 Syncing from upstream odoo/odoo (saas-12.3)
  addons/sale/report/sale_report_views.xml
Labels: saas-12.3

#11944 [FIX] web: improve the hit box of the kanban quick_create
  addons/web/static/src/js/views/kanban/kanban_record_quick_create.js
  addons/web/static/tests/views/kanban_tests.js
Labels: 12.0

#11945 Syncing from upstream odoo/odoo (12.0)
  addons/payment_stripe_sca/models/payment.py
  odoo/fields.py
Labels: 12.0

#11946 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/google_calendar/models/google_calendar.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mrp/models/mrp_production.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: 13.0

#11947 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/models/composer/composer.js
  addons/mrp/models/mrp_bom.py
  addons/payment_authorize/models/payment.py
  addons/payment_authorize/views/payment_authorize_templates.xml
  addons/sale_mrp/models/sale.py
  addons/web/static/src/js/tools/debug_manager_backend.js
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
  odoo/fields.py
  odoo/models.py
Labels: 14.0

#11949 Syncing from upstream odoo/odoo (saas-12.3)
  addons/google_calendar/models/google_calendar.py
  addons/payment_stripe_sca/models/payment.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  odoo/fields.py
Labels: saas-12.3

#11950 Syncing from upstream odoo/odoo (saas-13.3)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/google_calendar/models/google_calendar.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/fields.py
  odoo/models.py
Labels: saas-13.3

#11952 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/google_calendar/models/google_calendar.py
  addons/payment_stripe_sca/models/payment.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  odoo/fields.py
Labels: staging.saas-12.3

#11953 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/google_calendar/models/google_calendar.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-13.3

#11958 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/google_calendar/models/google_calendar.py
  addons/payment_stripe_sca/models/payment.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  odoo/fields.py
Labels: tmp.saas-12.3

#11959 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/google_calendar/models/google_calendar.py
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/fields.py
  odoo/models.py
Labels: tmp.saas-13.3

#11963 [bt#12320] Fehler validieren von Rechnungen (#12320
  openerp/addons/base/ir/ir_sequence.py
Labels: 7.0.project_li_101

#11964 Syncing from upstream odoo/odoo (12.0)
  addons/mrp/models/mrp_bom.py
  addons/website_slides/models/slides.py
  addons/website_slides/tests/test_from_url.py
Labels: 12.0

#11965 Syncing from upstream odoo/odoo (13.0)
  addons/calendar/models/calendar.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/wizard/mrp_product_produce.py
  addons/point_of_sale/static/src/js/models.js
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/core/dom.js
Labels: 13.0

#11966 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account_edi/views/account_payment_views.xml
  addons/account_fleet/models/fleet_vehicle.py
  addons/crm/models/res_partner.py
  addons/crm/models/utm.py
  addons/hr/models/res_users.py
  addons/hr_expense/models/account_journal_dashboard.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_dk/models/account_journal.py
  addons/l10n_mx/models/account.py
  addons/l10n_nl/models/account_journal.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_picking.py
  addons/stock_account/models/stock_inventory.py
  addons/stock_account/models/stock_move.py
  addons/survey/models/survey_survey.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/shapes/Airy/03.svg
  addons/web_editor/static/shapes/Origins/05.svg
  addons/web_editor/static/shapes/Origins/06.svg
  addons/web_editor/static/shapes/Origins/11.svg
  addons/web_editor/static/shapes/Origins/13.svg
  addons/web_editor/static/shapes/Origins/14.svg
  addons/web_editor/static/shapes/Wavy/01.svg
  addons/web_editor/static/shapes/Wavy/05.svg
  addons/web_editor/static/shapes/Zigs/03.svg
  addons/web_editor/static/src/js/editor/snippets.options.js
  odoo/tools/test_reports.py
Labels: 14.0

#11967 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account_edi/views/account_payment_views.xml
  addons/account_fleet/models/fleet_vehicle.py
  addons/crm/models/res_partner.py
  addons/crm/models/utm.py
  addons/hr/models/res_users.py
  addons/hr_expense/models/account_journal_dashboard.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/mrp/models/mrp_routing.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/stock_account/models/stock_inventory.py
  addons/stock_account/models/stock_move.py
  addons/survey/models/survey_survey.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/shapes/Airy/03.svg
  addons/web_editor/static/shapes/Origins/05.svg
  addons/web_editor/static/shapes/Origins/06.svg
  addons/web_editor/static/shapes/Origins/11.svg
  addons/web_editor/static/shapes/Origins/13.svg
  addons/web_editor/static/shapes/Origins/14.svg
  addons/web_editor/static/shapes/Wavy/01.svg
  addons/web_editor/static/shapes/Wavy/05.svg
  addons/web_editor/static/shapes/Zigs/03.svg
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_slides/controllers/main.py
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_profile.xml
  odoo/tools/test_reports.py
Labels: master

#11968 Syncing from upstream odoo/odoo (saas-13.3)
  addons/calendar/models/calendar.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/core/dom.js
Labels: saas-13.3

#11971 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/calendar/models/calendar.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/core/dom.js
Labels: staging.saas-13.3

#11972 Syncing from upstream odoo/odoo (staging.12.0)
  addons/mrp/models/mrp_bom.py
  addons/website_slides/models/slides.py
  addons/website_slides/tests/test_from_url.py
Labels: staging.12.0

#11973 Syncing from upstream odoo/odoo (staging.13.0)
  addons/calendar/models/calendar.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/wizard/mrp_product_produce.py
  addons/point_of_sale/static/src/js/models.js
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/core/dom.js
Labels: staging.13.0

#11974 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account_edi/views/account_payment_views.xml
  addons/account_fleet/models/fleet_vehicle.py
  addons/crm/models/res_partner.py
  addons/crm/models/utm.py
  addons/hr/models/res_users.py
  addons/hr_expense/models/account_journal_dashboard.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_dk/models/account_journal.py
  addons/l10n_mx/models/account.py
  addons/l10n_nl/models/account_journal.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_picking.py
  addons/stock_account/models/stock_inventory.py
  addons/stock_account/models/stock_move.py
  addons/survey/models/survey_survey.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/shapes/Airy/03.svg
  addons/web_editor/static/shapes/Origins/05.svg
  addons/web_editor/static/shapes/Origins/06.svg
  addons/web_editor/static/shapes/Origins/11.svg
  addons/web_editor/static/shapes/Origins/13.svg
  addons/web_editor/static/shapes/Origins/14.svg
  addons/web_editor/static/shapes/Wavy/01.svg
  addons/web_editor/static/shapes/Wavy/05.svg
  addons/web_editor/static/shapes/Zigs/03.svg
  addons/web_editor/static/src/js/editor/snippets.options.js
  odoo/tools/test_reports.py
Labels: staging.14.0

#11976 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/calendar/models/calendar.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/core/dom.js
Labels: tmp.saas-13.3

#11977 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/mrp/models/mrp_bom.py
  addons/website_slides/models/slides.py
  addons/website_slides/tests/test_from_url.py
Labels: tmp.12.0

#11978 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/calendar/models/calendar.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/wizard/mrp_product_produce.py
  addons/point_of_sale/static/src/js/models.js
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/js/core/dom.js
Labels: tmp.13.0

#11979 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account_edi/views/account_payment_views.xml
  addons/account_fleet/models/fleet_vehicle.py
  addons/crm/models/res_partner.py
  addons/crm/models/utm.py
  addons/hr/models/res_users.py
  addons/hr_expense/models/account_journal_dashboard.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_dk/models/account_journal.py
  addons/l10n_mx/models/account.py
  addons/l10n_nl/models/account_journal.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_picking.py
  addons/stock_account/models/stock_inventory.py
  addons/stock_account/models/stock_move.py
  addons/survey/models/survey_survey.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/shapes/Airy/03.svg
  addons/web_editor/static/shapes/Origins/05.svg
  addons/web_editor/static/shapes/Origins/06.svg
  addons/web_editor/static/shapes/Origins/11.svg
  addons/web_editor/static/shapes/Origins/13.svg
  addons/web_editor/static/shapes/Origins/14.svg
  addons/web_editor/static/shapes/Wavy/01.svg
  addons/web_editor/static/shapes/Wavy/05.svg
  addons/web_editor/static/shapes/Zigs/03.svg
  addons/web_editor/static/src/js/editor/snippets.options.js
  odoo/tools/test_reports.py
Labels: tmp.14.0

#11981 Syncing from upstream odoo/odoo (12.0)
  addons/point_of_sale/static/src/js/screens.js
  odoo/addons/base/data/res_country_data.xml
Labels: 12.0

#11982 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/product/i18n/product.pot
  addons/product/models/__init__.py
  addons/product/models/decimal_precision.py
  addons/product/models/uom_uom.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_package_level.py
  addons/stock/tests/test_move2.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/website_rating/static/src/xml/portal_tools.xml
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/decimal_precision.py
  odoo/modules/registry.py
Labels: 13.0

#11983 Syncing from upstream odoo/odoo (14.0)
  addons/account_payment/views/account_portal_templates.xml
  addons/crm/models/res_partner.py
  addons/l10n_bo/data/account_tax_report_data.xml
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/src/js/printers.js
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: 14.0

#11984 Syncing from upstream odoo/odoo (master)
  addons/account_payment/views/account_portal_templates.xml
  addons/calendar/models/calendar_attendee.py
  addons/calendar/models/calendar_event.py
  addons/event_sale/models/event_registration.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_bo/data/account_tax_report_data.xml
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/src/js/printers.js
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: master

#11985 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/static/src/js/screens.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_from_url.py
  odoo/addons/base/data/res_country_data.xml
Labels: saas-12.3

#11986 Syncing from upstream odoo/odoo (saas-13.3)
  addons/crm/models/res_partner.py
  addons/mrp/models/mrp_bom.py
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: saas-13.3

#11988 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/static/src/js/screens.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_from_url.py
  odoo/addons/base/data/res_country_data.xml
Labels: staging.saas-12.3

#11989 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/crm/models/res_partner.py
  addons/mrp/models/mrp_bom.py
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: staging.saas-13.3

#11990 Syncing from upstream odoo/odoo (staging.12.0)
  addons/point_of_sale/static/src/js/screens.js
  odoo/addons/base/data/res_country_data.xml
Labels: staging.12.0

#11991 Syncing from upstream odoo/odoo (staging.13.0)
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/product/i18n/product.pot
  addons/product/models/__init__.py
  addons/product/models/decimal_precision.py
  addons/product/models/uom_uom.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_package_level.py
  addons/stock/tests/test_move2.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/website_rating/static/src/xml/portal_tools.xml
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/decimal_precision.py
  odoo/modules/registry.py
Labels: staging.13.0

#11992 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_payment/views/account_portal_templates.xml
  addons/crm/models/res_partner.py
  addons/l10n_bo/data/account_tax_report_data.xml
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/src/js/printers.js
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: staging.14.0

#11994 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/static/src/js/screens.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_from_url.py
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.saas-12.3

#11995 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/crm/models/res_partner.py
  addons/mrp/models/mrp_bom.py
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: tmp.saas-13.3

#11996 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/point_of_sale/static/src/js/screens.js
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.12.0

#11997 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/product/i18n/product.pot
  addons/product/models/__init__.py
  addons/product/models/decimal_precision.py
  addons/product/models/uom_uom.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_package_level.py
  addons/stock/tests/test_move2.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/website_rating/static/src/xml/portal_tools.xml
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/decimal_precision.py
  odoo/modules/registry.py
Labels: tmp.13.0

#11998 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_payment/views/account_portal_templates.xml
  addons/crm/models/res_partner.py
  addons/l10n_bo/data/account_tax_report_data.xml
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/src/js/printers.js
  addons/portal_rating/static/src/xml/portal_tools.xml
  addons/stock/models/stock_package_level.py
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/snippets/s_countdown/options.js
  odoo/addons/base/data/res_country_data.xml
  odoo/modules/registry.py
Labels: tmp.14.0

#11999 Syncing from upstream odoo/odoo (12.0)
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/static/src/js/website_blog.js
Labels: 12.0

#12000 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_portal_templates.xml
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_package_level.py
Labels: 13.0

#12001 Syncing from upstream odoo/odoo (14.0)
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/scss/keyframes.scss
  addons/web_tour/static/src/scss/tip.scss
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: 14.0

#12002 Syncing from upstream odoo/odoo (master)
  addons/crm/models/res_partner.py
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/stock/static/img/replenishment.svg
  addons/stock/static/src/scss/stock_empty_screen.scss
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/scss/keyframes.scss
  addons/web_tour/static/src/scss/tip.scss
  addons/web_tour/views/tour_templates.xml
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: master

#12003 Syncing from upstream odoo/odoo (saas-12.3)
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/static/src/js/website_blog.js
Labels: saas-12.3

#12004 Syncing from upstream odoo/odoo (saas-13.3)
  addons/account/models/account_move.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/wizard/mrp_product_produce.py
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: saas-13.3

#12006 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/static/src/js/website_blog.js
Labels: staging.saas-12.3

#12007 Syncing from upstream odoo/odoo (staging.saas-13.3)
  addons/account/models/account_move.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/wizard/mrp_product_produce.py
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: staging.saas-13.3

#12008 Syncing from upstream odoo/odoo (staging.12.0)
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/static/src/js/website_blog.js
Labels: staging.12.0

#12009 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_portal_templates.xml
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_package_level.py
Labels: staging.13.0

#12010 Syncing from upstream odoo/odoo (staging.14.0)
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/scss/keyframes.scss
  addons/web_tour/static/src/scss/tip.scss
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: staging.14.0

#12012 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/static/src/js/website_blog.js
Labels: tmp.saas-12.3

#12013 Syncing from upstream odoo/odoo (tmp.saas-13.3)
  addons/account/models/account_move.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/wizard/mrp_product_produce.py
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: tmp.saas-13.3

#12014 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/static/src/js/website_blog.js
Labels: tmp.12.0

#12015 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_portal_templates.xml
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_package_level.py
Labels: tmp.13.0

#12016 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/payment/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment.py
  addons/stock/models/stock_package_level.py
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/scss/keyframes.scss
  addons/web_tour/static/src/scss/tip.scss
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
Labels: tmp.14.0

#12022 Syncing from upstream odoo/odoo (11.0)
  addons/decimal_precision/i18n/decimal_precision.pot
  addons/decimal_precision/models/decimal_precision.py
  addons/product/i18n/product.pot
  addons/product/models/decimal_precision.py
  addons/product/models/product_uom.py
Labels: 11.0

#12023 Syncing from upstream odoo/odoo (12.0)
  addons/google_calendar/models/google_calendar.py
Labels: 12.0

#12024 Syncing from upstream odoo/odoo (13.0)
  addons/account/report/account_aged_partner_balance.py
  addons/hw_drivers/controllers/driver.py
  addons/payment_paypal/models/payment.py
  addons/payment_paypal/tests/test_paypal.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sales_team/__manifest__.py
  addons/sales_team/views/res_partner_views.xml
  addons/stock/models/stock_package_level.py
  addons/stock/tests/test_packing.py
  addons/web/static/src/js/views/kanban/kanban_record_quick_create.js
  addons/web/static/src/js/views/pivot/pivot_controller.js
  addons/web/static/tests/views/kanban_tests.js
  addons/website/static/src/scss/website.scss
  doc/cla/corporate/niboo.md
  doc/cla/individual/jvandri.md
Labels: 13.0

#12026 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/base_setup/models/res_config_settings.py
  addons/base_setup/views/res_config_settings_views.xml
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/models/res_config_settings.py
  addons/google_recaptcha/views/res_config_settings_view.xml
  addons/hw_drivers/controllers/driver.py
  addons/hw_drivers/event_manager.py
  addons/l10n_dk/models/account_journal.py
  addons/l10n_mx/models/account.py
  addons/l10n_nl/models/account_journal.py
  addons/mail/static/src/component_hooks/use_update/use_update.js
  addons/mail/static/src/components/chat_window/chat_window.js
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/chatter/chatter.js
  addons/mail/static/src/components/chatter_container/chatter_container.js
  addons/mail/static/src/components/composer/composer.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mail/static/src/components/composer_suggestion/composer_suggestion.js
  addons/mail/static/src/components/composer_text_input/composer_text_input.js
  addons/mail/static/src/components/composer_text_input/composer_text_input.xml
  addons/mail/static/src/components/discuss/discuss.js
  addons/mail/static/src/components/discuss/tests/discuss_domain_tests.js
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/components/discuss_sidebar/discuss_sidebar.js
  addons/mail/static/src/components/emojis_popover/emojis_popover.js
  addons/mail/static/src/components/message/message.js
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_list/message_list.js
  addons/mail/static/src/components/thread_view/thread_view.js
  addons/mail/static/src/components/thread_view/thread_view_tests.js
  addons/mail/static/src/models/message/message.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/src/models/thread_cache/thread_cache.js
  addons/mail/static/src/widgets/form_renderer/form_renderer_tests.js
  addons/mail/static/tests/helpers/mock_models.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/views/assets.xml
  addons/mrp/models/mrp_production.py
  addons/payment_paypal/models/payment.py
  addons/payment_paypal/tests/test_paypal.py
  addons/point_of_sale/models/pos_session.py
  addons/survey/controllers/survey_session_manage.py
  addons/survey/static/src/js/survey_quick_access.js
  addons/survey/static/src/scss/survey_form.scss
  addons/survey/views/survey_survey_views.xml
  addons/survey/views/survey_templates_management.xml
  addons/web/static/src/js/views/kanban/kanban_record_quick_create.js
  addons/web/static/src/js/widgets/notification.js
  addons/web/static/src/scss/form_view.scss
  addons/web/static/src/scss/notification.scss
  addons/web/static/src/xml/notification.xml
  addons/web/static/tests/services/notification_service_tests.js
  addons/web/static/tests/views/kanban_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_form/views/snippets/s_website_form.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_slide_utils.py
  odoo/addons/base/models/ir_actions_report.py
Labels: master

#12027 Syncing from upstream odoo/odoo (saas-11.3)
  addons/decimal_precision/i18n/decimal_precision.pot
  addons/decimal_precision/models/decimal_precision.py
  addons/product/i18n/product.pot
  addons/product/models/__init__.py
  addons/product/models/decimal_precision.py
  addons/product/models/uom_uom.py
  addons/uom/models/uom_uom.py
Labels: saas-11.3
