Repository brain-tec/odoo, pull requests merged in 2021-01, with the labels that each got.

#12483 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_automatic_leave_dates.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_multilang/models/l10n_multilang.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/payment/models/account_invoice.py
  addons/pos_sale/models/pos_order.py
  addons/sale_stock/models/sale_order.py
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  odoo/addons/base/data/base_data.sql
Labels: 14.0

#12484 Syncing from upstream odoo/odoo (master)
  addons/account/__manifest__.py
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/static/src/js/bank_statement.js
  addons/account/static/src/js/bills_upload.js
  addons/account/static/src/xml/bills_upload_views.xml
  addons/account/views/account.xml
  addons/account/views/account_move_views.xml
  addons/base_import/static/src/scss/base_import.scss
  addons/coupon/models/coupon_program.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_automatic_leave_dates.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_multilang/models/l10n_multilang.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/payment/models/account_invoice.py
  addons/pos_sale/models/pos_order.py
  addons/sale/static/src/js/product_configurator_widget.js
  addons/sale_stock/models/sale_order.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  addons/test_website/static/tests/tours/custom_snippets.js
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_custom_snippet.py
  addons/test_website/views/templates.xml
  addons/web/static/src/js/views/calendar/calendar_controller.js
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/web_editor/views/snippets.xml
  addons/website/static/src/js/tours/homepage.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/tests/test_ui.py
  addons/website/views/snippets/s_banner.xml
  addons/website_jitsi/static/src/js/chat_room.js
  addons/website_mail_channel/controllers/main.py
  addons/website_mail_channel/static/src/snippets/s_channel/options.js
  addons/website_mail_channel/views/snippets/s_channel.xml
  addons/website_sale/models/website.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  doc/howtos/web.rst
  doc/reference/actions.rst
  odoo/addons/base/data/base_data.sql
  odoo/tools/mail.py
Labels: master

#12486 Syncing from upstream odoo/odoo (12.0)
  addons/l10n_multilang/models/l10n_multilang.py
  addons/mrp/models/mrp_bom.py
  addons/web/static/lib/pdfjs/src/core/fonts.js
  addons/website_theme_install/models/theme_models.py
  doc/howtos/web.rst
  doc/reference/actions.rst
  odoo/addons/base/data/base_data.sql
  odoo/tools/mail.py
Labels: 12.0

#12487 Syncing from upstream odoo/odoo (13.0)
  addons/im_livechat/static/src/scss/im_livechat.scss
  addons/mrp/models/mrp_bom.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  odoo/addons/base/data/base_data.sql
Labels: 13.0

#12489 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/addons/base/data/base_data.sql
Labels: saas-12.3

#12490 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/auth_signup/models/res_users.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_work_entry/models/hr_work_entry.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workcenter.py
  addons/mrp/populate/mrp.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/views/mrp_workcenter_views.xml
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_production_lot.py
  addons/stock/models/stock_rule.py
  addons/stock/populate/stock.py
  addons/stock/views/stock_move_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_certification_badge.py
  addons/survey/views/survey_survey_views.xml
  addons/web/i18n/web.pot
  addons/web/static/src/js/views/graph/graph_controller.js
  addons/web/static/tests/views/sample_server_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/models/theme_models.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/wysiwyg_multizone.js
  addons/website/static/src/scss/secondary_variables.scss
  addons/website_form/controllers/main.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/test_xmlrpc.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
  odoo/models.py
Labels: master

#12492 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/account/tests/test_account_journal.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_check_printing/models/account_payment.py
  addons/auth_signup/controllers/main.py
  addons/base_address_city/models/res_partner.py
  addons/calendar/models/calendar_attendee.py
  addons/mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.js
  addons/mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.xml
  addons/mail/static/src/models/activity/activity.js
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/repair/models/repair.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/stock_rule.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/views/graph/graph_controller.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/views/sample_server_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/models/theme_models.py
  addons/website_form/controllers/main.py
  debian/README.Debian
  debian/changelog
  debian/lintian-overrides
  doc/cla/individual/fedegobea.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/qweb.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/models.py
Labels: 14.0

#12495 Syncing from upstream odoo/odoo (12.0)
  addons/mail/static/src/js/systray/systray_activity_menu.js
  odoo/modules/loading.py
Labels: 12.0

#12497 Syncing from upstream odoo/odoo (13.0)
  addons/account_facturx/models/account_move.py
  addons/mrp/models/product.py
  addons/portal/i18n/portal.pot
  addons/portal/static/src/js/portal_sidebar.js
  addons/pos_hr/static/src/js/screens.js
  addons/sale/models/account_move.py
  addons/stock/models/stock_scrap.py
  addons/web/static/src/scss/mimetypes.scss
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  doc/cla/individual/davejames.md
  odoo/modules/loading.py
Labels: 13.0

#12498 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_journal.py
  addons/base_vat/models/res_partner.py
  addons/crm/models/crm_lead.py
  addons/crm/views/crm_lead_views.xml
  addons/crm_sms/__manifest__.py
  addons/crm_sms/views/crm_lead_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.js
  addons/mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.xml
  addons/mail/static/src/models/activity/activity.js
  addons/mail/tests/common.py
  addons/portal/i18n/portal.pot
  addons/portal/models/portal_mixin.py
  addons/portal/static/src/js/portal_sidebar.js
  addons/project/models/project.py
  addons/repair/models/repair.py
  addons/sale/models/sale.py
  addons/stock/models/stock_rule.py
  addons/test_mail/tests/test_message_post.py
  addons/website/models/ir_translation.py
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/000.scss
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/000.xml
  addons/website_blog/models/website_blog.py
  addons/website_forum/models/forum.py
  addons/website_slides/models/slide_slide.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
  odoo/models.py
Labels: master

#12501 [FIX] mail: call check_access_rule correctly
  addons/mail/models/mail_followers.py
Labels: 12.0.project_wi_445

#12502 [t119959][FIX] mail: call check_access_rule correctly
  addons/mail/models/mail_followers.py
Labels: 12.0.project_st_215

#12503 [t119948][FIX] mail: call check_access_rule correctly
  addons/mail/models/mail_followers.py
Labels: 12.0.project_ls_540

#12504 Syncing from upstream odoo/odoo (12.0)
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
Labels: 12.0

#12505 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_move.py
  addons/base_automation/models/base_automation.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
Labels: 12.0

#12507 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/wizard/account_automatic_entry_wizard_views.xml
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/discuss_sidebar_item/discuss_sidebar_item.js
  addons/mail/static/src/components/editable_text/editable_text.js
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_channel.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mrp/models/stock_warehouse.py
  addons/payment_authorize/controllers/main.py
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_warehouse.py
  addons/stock/report/report_stock_forecasted.py
  addons/stock/static/src/js/popover_widget.js
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/models.py
Labels: master

#12515 Syncing from upstream odoo/odoo (11.0)
  requirements.txt
Labels: 11.0

#12517 Syncing from upstream odoo/odoo (12.0)
  addons/website_event/models/event.py
  addons/website_rating/static/src/scss/website_rating.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  doc/cla/corporate/rapsodoo.md
  doc/howtos/theme_tutorial_assets/img/folder.jpg
  doc/howtos/theme_tutorial_assets/img/theme_folder.jpg
  doc/howtos/themes.rst
Labels: 12.0

#12520 Syncing from upstream odoo/odoo (12.0)
  addons/account/models/account_reconcile_model.py
  doc/cla/individual/luquedaniel.md
  requirements.txt
Labels: 12.0

#12523 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account_facturx/models/account_invoice.py
  addons/base_automation/models/base_automation.py
  addons/delivery/models/sale_order.py
  addons/google_drive/i18n/google_drive.pot
  addons/google_drive/models/google_drive.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_multilang/models/l10n_multilang.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/models/pos_order.py
  addons/portal/i18n/portal.pot
  addons/portal/static/src/js/portal_sidebar.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/models/stock_rule.py
  addons/web/controllers/main.py
  addons/web/static/lib/pdfjs/src/core/fonts.js
  addons/web/static/lib/pdfjs/src/display/canvas.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
  addons/website_event/models/event.py
  addons/website_event_questions/models/event.py
  addons/website_event_track/controllers/main.py
  addons/website_sale/models/product.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  addons/website_theme_install/models/theme_models.py
  doc/cla/corporate/rapsodoo.md
  doc/howtos/theme_tutorial_assets/img/folder.jpg
  doc/howtos/theme_tutorial_assets/img/theme_folder.jpg
  doc/howtos/themes.rst
  doc/howtos/web.rst
  doc/reference/actions.rst
  odoo/addons/base/data/base_data.sql
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/modules/loading.py
  odoo/tools/mail.py
  odoo/tools/misc.py
Labels: staging.saas-12.3

#12527 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_invoice.py
  addons/account/models/account_move.py
  addons/account_facturx/models/account_invoice.py
  addons/base_automation/models/base_automation.py
  addons/delivery/models/sale_order.py
  addons/google_drive/i18n/google_drive.pot
  addons/google_drive/models/google_drive.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/models/pos_order.py
  addons/portal/i18n/portal.pot
  addons/portal/static/src/js/portal_sidebar.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/models/stock_rule.py
  addons/web/static/lib/pdfjs/src/core/fonts.js
  addons/web/static/src/js/views/list/list_editable_renderer.js
  addons/web/static/tests/views/list_tests.js
  addons/website_event/models/event.py
  addons/website_event_questions/models/event.py
  addons/website_event_track/controllers/main.py
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/static/src/js/website_sale_delivery.js
  addons/website_theme_install/models/theme_models.py
  doc/cla/corporate/rapsodoo.md
  doc/howtos/theme_tutorial_assets/img/folder.jpg
  doc/howtos/theme_tutorial_assets/img/theme_folder.jpg
  doc/howtos/themes.rst
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/modules/loading.py
  odoo/tools/misc.py
Labels: saas-12.3

#12528 Syncing from upstream odoo/odoo (14.0)
  addons/calendar/views/calendar_views.xml
  addons/http_routing/models/ir_http.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/views/snippets_themes.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_management/views/sale_portal_templates.xml
  addons/sale_timesheet/views/project_task_views.xml
  addons/test_website/__init__.py
  addons/test_website/__manifest__.py
  addons/test_website/controllers/main.py
  addons/test_website/data/test_website_data.xml
  addons/test_website/models/__init__.py
  addons/test_website/models/model.py
  addons/test_website/security/ir.model.access.csv
  addons/test_website/tests/test_redirect.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/ir_http.py
Labels: 14.0

#12529 Syncing from upstream odoo/odoo (12.0)
  addons/point_of_sale/static/src/js/chrome.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/stock/views/stock_move_line_views.xml
Labels: 12.0

#12532 Syncing from upstream odoo/odoo (12.0)
  addons/hr_holidays/models/hr_leave.py
  addons/mail/models/mail_followers.py
  addons/mail/models/mail_message_subtype.py
  addons/mail/models/mail_thread.py
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/project/models/project.py
  addons/test_mail/tests/test_mail_followers.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/tests/test_views.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/static/src/scss/website_sale.scss
Labels: 12.0

#12534 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account_reconcile_model.py
  addons/point_of_sale/static/src/js/chrome.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/sale_coupon/models/sale_order.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/tests/test_views.py
  addons/website_rating/static/src/scss/website_rating.scss
  addons/website_sale/static/src/scss/website_sale.scss
Labels: saas-12.3

#12535 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/wizard/account_payment_register.py
  addons/crm/views/crm_lead_views.xml
  addons/mrp_account/models/product.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/stock_account/models/stock_quant.py
  addons/stock_account/report/report_stock_forecasted.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/000.js
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/options.js
  addons/website_sale/views/snippets/s_dynamic_snippet_products.xml
  debian/control
  doc/cla/corporate/simpit.md
  doc/cla/individual/msteinfeld.md
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
  setup/package.dfsrc
  setup/redhat/install.sh
  setup/redhat/postinstall.sh
Labels: 14.0
