Repository brain-tec/odoo, pull requests merged in 2021-03, with the labels that each got.

#12601 Syncing from upstream odoo/odoo (11.0)
  addons/account/i18n/bs.po
  addons/account/i18n/cs.po
  addons/account/i18n/nb.po
  addons/account_bank_statement_import/i18n/bs.po
  addons/account_bank_statement_import/i18n/cs.po
  addons/account_cash_basis_base_account/i18n/bs.po
  addons/account_payment/i18n/sl.po
  addons/barcodes/i18n/ro.po
  addons/base_setup/i18n/ro.po
  addons/delivery/i18n/bs.po
  addons/delivery/i18n/el.po
  addons/delivery/i18n/ro.po
  addons/event/i18n/bs.po
  addons/event/i18n/pt_BR.po
  addons/event_sale/i18n/pt_BR.po
  addons/fleet/i18n/cs.po
  addons/fleet/i18n/id.po
  addons/fleet/i18n/ro.po
  addons/google_drive/i18n/ro.po
  addons/google_spreadsheet/i18n/ro.po
  addons/hr_attendance/i18n/pt_BR.po
  addons/hr_attendance/i18n/sl.po
  addons/hr_contract/i18n/pt_BR.po
  addons/hr_contract/i18n/sl.po
  addons/hr_payroll/i18n/pt_BR.po
  addons/hr_timesheet/i18n/pt_BR.po
  addons/lunch/i18n/cs.po
  addons/mail/i18n/pt.po
  addons/mail/i18n/pt_BR.po
  addons/mass_mailing/i18n/hu.po
  addons/mass_mailing/i18n/pt_BR.po
  addons/mass_mailing/i18n/sk.po
  addons/mrp/i18n/cs.po
  addons/mrp/i18n/hu.po
  addons/mrp/i18n/pt_BR.po
  addons/mrp/i18n/ro.po
  addons/mrp_byproduct/i18n/pt_BR.po
  addons/mrp_repair/i18n/pt.po
  addons/payment/i18n/ro.po
  addons/payment_authorize/i18n/ja.po
  addons/point_of_sale/i18n/it.po
  addons/point_of_sale/i18n/nb.po
  addons/pos_cache/i18n/nb.po
  addons/pos_cache/i18n/pt_BR.po
  odoo/addons/base/i18n/bs.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/fi.po
  odoo/addons/base/i18n/id.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/sl.po
Labels: 11.0

#12602 Syncing from upstream odoo/odoo (12.0)
  MANIFEST.in
Labels: 12.0

#12604 Syncing from upstream odoo/odoo (14.0)
  MANIFEST.in
  addons/calendar/models/calendar_alarm_manager.py
  addons/calendar/tests/test_calendar.py
  addons/hr_contract/static/src/scss/calendar_mismatch.scss
  addons/payment/models/payment_acquirer.py
  addons/pos_cache/models/pos_cache.py
  addons/pos_cache/static/src/js/pos_cache.js
  addons/stock/models/product.py
  addons/survey/controllers/main.py
  addons/survey/wizard/survey_invite.py
  addons/website_slides/wizard/slide_channel_invite.py
Labels: 14.0

#12606 Syncing from upstream odoo/odoo (saas-12.3)
  MANIFEST.in
  addons/mrp/data/mrp_demo.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_stock.py
  addons/mrp_bom_cost/tests/test_bom_price.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web/static/src/js/tools/test_menus.js
  addons/website_form/controllers/main.py
  doc/cla/corporate/online-erp-hungary-kft.md
Labels: saas-12.3

#12610 Syncing from upstream odoo/odoo (staging.saas-12.3)
  MANIFEST.in
  addons/mrp/data/mrp_demo.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_stock.py
  addons/mrp_bom_cost/tests/test_bom_price.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web/static/src/js/tools/test_menus.js
  addons/website_form/controllers/main.py
  doc/cla/corporate/online-erp-hungary-kft.md
Labels: staging.saas-12.3

#12617 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  MANIFEST.in
  addons/mrp/data/mrp_demo.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_stock.py
  addons/mrp_bom_cost/tests/test_bom_price.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web/static/src/js/tools/test_menus.js
  addons/website_form/controllers/main.py
  doc/cla/corporate/online-erp-hungary-kft.md
Labels: tmp.saas-12.3

#12623 Syncing from upstream odoo/odoo (13.0)
  .github/CODEOWNERS
  .gitignore
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/models/res_partner.py
  addons/bus/models/bus_presence.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/i18n/l10n_mx.pot
  addons/l10n_mx/models/__init__.py
  addons/l10n_mx/models/account_move.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/stock_move_views.xml
  addons/payment/controllers/portal.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_templates.xml
  addons/payment/wizards/payment_link_wizard.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/helpers/mock_server.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/models/sale_order.py
  debian/control
  doc/cla/corporate/tecnativa.md
  doc/reference/javascript_reference.rst
  doc/reference/security.rst
  odoo/tools/test-config-values
  odoo/tools/test-config-values-00.conf
  odoo/tools/test_config.py
  setup/package.dfdebian
Labels: 13.0

#12628 Syncing from upstream odoo/odoo (12.0)
  odoo/addons/base/models/ir_actions.py
Labels: 12.0

#12629 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_stock_ddt/__init__.py
  addons/l10n_it_stock_ddt/__manifest__.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_it_stock_ddt/models/__init__.py
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_it_stock_ddt/tests/__init__.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/views/account_invoice_views.xml
  addons/l10n_it_stock_ddt/views/stock_picking_views.xml
  addons/mrp/models/mrp_workorder.py
  addons/stock/models/product.py
  odoo/addons/base/models/ir_actions.py
Labels: 13.0

#12630 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/base_vat/models/res_partner.py
  addons/bus/models/bus_presence.py
  addons/l10n_be/data/account_tax_template_data.xml
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/l10n_ro/__manifest__.py
  addons/l10n_ro/data/account.account.template.csv
  addons/l10n_ro/data/account_fiscal_position_data.xml
  addons/l10n_ro/data/account_tax_data.xml
  addons/l10n_ro/data/account_tax_report_data.xml
  addons/l10n_ro/data/l10n_ro_chart_post_data.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/message/message.xml
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale_stock_margin/models/sale_order_line.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/uom/models/uom_uom.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields/field_many2many_tests.js
  doc/reference/javascript_reference.rst
  odoo/addons/base/models/ir_actions.py
  odoo/netsvc.py
Labels: 14.0

#12631 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_bank_statement.py
  addons/base_vat/models/res_partner.py
  addons/bus/models/bus_presence.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale_stock_margin/models/sale_order_line.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/tests/fields/relational_fields/field_many2many_tests.js
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web/static/tests/helpers/mock_server.js
  doc/reference/javascript_reference.rst
  odoo/addons/base/models/ir_actions.py
  odoo/netsvc.py
Labels: master

#12632 Syncing from upstream odoo/odoo (saas-12.3)
  .github/CODEOWNERS
  .gitignore
  addons/account/i18n/hu.po
  addons/base_vat/models/res_partner.py
  addons/bus/models/bus_presence.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/ir_actions.py
  odoo/tools/test-config-values
  odoo/tools/test-config-values-00.conf
  odoo/tools/test_config.py
Labels: saas-12.3

#12636 Syncing from upstream odoo/odoo (staging.saas-12.3)
  .github/CODEOWNERS
  .gitignore
  addons/account/i18n/hu.po
  addons/base_vat/models/res_partner.py
  addons/bus/models/bus_presence.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/ir_actions.py
  odoo/tools/test-config-values
  odoo/tools/test-config-values-00.conf
  odoo/tools/test_config.py
Labels: staging.saas-12.3

#12643 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  .github/CODEOWNERS
  .gitignore
  addons/account/i18n/hu.po
  addons/base_vat/models/res_partner.py
  addons/bus/models/bus_presence.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mass_mailing/models/mass_mailing.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/ir_actions.py
  odoo/tools/test-config-values
  odoo/tools/test-config-values-00.conf
  odoo/tools/test_config.py
Labels: tmp.saas-12.3

#12650 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/sale_purchase/models/purchase_order.py
Labels: tmp.saas-12.3

#12651 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_latam_base/models/res_partner.py
  addons/mail/models/mail_alias.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/sale_purchase/models/purchase_order.py
  addons/stock_account/models/product.py
  addons/test_xlsx_export/models.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/js/widgets/data_export.js
  addons/web/static/tests/widgets/data_export_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/website_visitor.py
Labels: 13.0

#12652 Syncing from upstream odoo/odoo (14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/google_calendar/static/src/xml/google_calendar_popover.xml
  addons/hr_expense/models/product_template.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/microsoft_calendar/static/src/xml/microsoft_calendar_popover.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/purchase_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_purchase/models/purchase_order.py
  addons/test_mail/tests/test_performance.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/tools/translate.py
Labels: 14.0

#12654 Syncing from upstream odoo/odoo (saas-14.1)
  addons/account_fleet/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/google_calendar/__manifest__.py
  addons/google_calendar/static/src/js/google_calendar.js
  addons/google_calendar/static/src/js/google_calendar_popover.js
  addons/google_calendar/static/src/xml/google_calendar_popover.xml
  addons/google_calendar/views/google_calendar_templates.xml
  addons/google_calendar/views/google_calendar_views.xml
  addons/hr_expense/models/product_template.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_be/data/account_tax_template_data.xml
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/__manifest__.py
  addons/microsoft_calendar/static/src/js/microsoft_calendar.js
  addons/microsoft_calendar/static/src/js/microsoft_calendar_popover.js
  addons/microsoft_calendar/static/src/xml/microsoft_calendar_popover.xml
  addons/microsoft_calendar/views/microsoft_calendar_templates.xml
  addons/microsoft_calendar/views/microsoft_calendar_views.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/purchase_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_purchase/models/purchase_order.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_sale/controllers/main.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/tools/translate.py
Labels: saas-14.1

#12655 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mail/models/mail_alias.py
  addons/sale_purchase/models/purchase_order.py
Labels: staging.saas-12.3

#12656 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account_fleet/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hr_expense/models/product_template.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_be/data/account_tax_template_data.xml
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/message/message.xml
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/purchase_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_purchase/models/purchase_order.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website_sale/controllers/main.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/modules/registry.py
  odoo/tools/translate.py
Labels: staging.saas-14.2

#12657 Syncing from upstream odoo/odoo (staging.12.0)
  addons/sale_purchase/models/purchase_order.py
  addons/stock/models/stock_picking.py
  odoo/addons/base/models/res_partner.py
Labels: staging.12.0

#12658 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_latam_base/models/res_partner.py
  addons/mail/models/mail_alias.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/sale_purchase/models/purchase_order.py
  addons/stock_account/models/product.py
  addons/test_xlsx_export/models.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/js/widgets/data_export.js
  addons/web/static/tests/widgets/data_export_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/website_visitor.py
Labels: staging.13.0

#12661 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mail/models/mail_alias.py
Labels: tmp.saas-12.3

#12662 Syncing from upstream odoo/odoo (tmp.saas-14.1)
  addons/account_fleet/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/google_calendar/__manifest__.py
  addons/google_calendar/static/src/js/google_calendar.js
  addons/google_calendar/static/src/js/google_calendar_popover.js
  addons/google_calendar/static/src/xml/google_calendar_popover.xml
  addons/google_calendar/views/google_calendar_templates.xml
  addons/google_calendar/views/google_calendar_views.xml
  addons/hr_expense/models/product_template.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_be/data/account_tax_template_data.xml
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/__manifest__.py
  addons/microsoft_calendar/static/src/js/microsoft_calendar.js
  addons/microsoft_calendar/static/src/js/microsoft_calendar_popover.js
  addons/microsoft_calendar/static/src/xml/microsoft_calendar_popover.xml
  addons/microsoft_calendar/views/microsoft_calendar_templates.xml
  addons/microsoft_calendar/views/microsoft_calendar_views.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/purchase_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_purchase/models/purchase_order.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_sale/controllers/main.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/tools/translate.py
Labels: tmp.saas-14.1

#12663 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account_fleet/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hr_expense/models/product_template.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_be/data/account_tax_template_data.xml
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/message/message.xml
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/purchase_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale_purchase/models/purchase_order.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website_sale/controllers/main.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/modules/registry.py
  odoo/tools/translate.py
Labels: tmp.saas-14.2

#12664 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/sale_purchase/models/purchase_order.py
  addons/stock/models/stock_picking.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.12.0

#12665 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_latam_base/models/res_partner.py
  addons/mail/models/mail_alias.py
  addons/mrp/models/mrp_abstract_workorder.py
  addons/mrp/wizard/mrp_product_produce.py
  addons/sale_purchase/models/purchase_order.py
  addons/stock_account/models/product.py
  addons/test_xlsx_export/models.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/js/widgets/data_export.js
  addons/web/static/tests/widgets/data_export_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/website_visitor.py
Labels: tmp.13.0

#12667 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/mail/models/res_users.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/stock_account/models/product.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/test_mail/tests/test_mail_channel.py
  odoo/addons/base/models/res_partner.py
Labels: 13.0

#12668 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_co/data/l10n_latam.identification.type.csv
  addons/l10n_latam_base/models/res_partner.py
  addons/l10n_pe/i18n/es.po
  addons/l10n_pe/i18n/l10n_pe.pot
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/composer_text_input/composer_text_input.js
  addons/mail/static/src/components/thread_view/thread_view.js
  addons/mail/static/src/components/thread_view/thread_view.xml
  addons/mail/static/src/model/model_field.js
  addons/mail/static/src/models/thread_view/thread_view.js
  addons/sale/models/sale.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/basic_model_tests.js
  addons/website_sale/models/website_visitor.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_partner.py
Labels: 14.0

#12669 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/barcodes/models/__init__.py
  addons/barcodes/models/barcode_nomenclature.py
  addons/barcodes/models/barcode_rule.py
  addons/barcodes/models/barcodes.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/barcodes/static/tests/barcode_parser_tests.js
  addons/barcodes/tests/test_barcode_nomenclature.py
  addons/barcodes/views/barcodes_templates.xml
  addons/barcodes/views/barcodes_view.xml
  addons/barcodes_gs1_nomenclature/__init__.py
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/data/barcodes_gs1_rules.xml
  addons/barcodes_gs1_nomenclature/models/__init__.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/models/barcode_rule.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/barcodes_gs1_nomenclature/tests/__init__.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/barcodes_gs1_nomenclature/views/barcodes_gs1_templates.xml
  addons/barcodes_gs1_nomenclature/views/barcodes_view.xml
  addons/crm/tests/test_performances.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_co/data/l10n_latam.identification.type.csv
  addons/l10n_latam_base/models/res_partner.py
  addons/l10n_pe/i18n/es.po
  addons/l10n_pe/i18n/l10n_pe.pot
  addons/mail/static/src/model/model_field.js
  addons/point_of_sale/static/src/js/barcode_reader.js
  addons/sale/models/sale.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/src/scss/kanban_dashboard.scss
  addons/web_editor/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website_visitor.py
  doc/cla/individual/tmotyl.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/models.py
  odoo/modules/registry.py
  odoo/tools/config.py
Labels: master

#12670 Syncing from upstream odoo/odoo (staging.saas-14.1)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account_fleet/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/google_calendar/__manifest__.py
  addons/google_calendar/static/src/js/google_calendar.js
  addons/google_calendar/static/src/js/google_calendar_popover.js
  addons/google_calendar/static/src/xml/google_calendar_popover.xml
  addons/google_calendar/views/google_calendar_templates.xml
  addons/google_calendar/views/google_calendar_views.xml
  addons/hr_expense/models/product_template.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/res_partner.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_be/data/account_tax_template_data.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_co/data/l10n_latam.identification.type.csv
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale/report/account_invoice_report.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/l10n_latam_base/models/res_partner.py
  addons/l10n_pe/i18n/es.po
  addons/l10n_pe/i18n/l10n_pe.pot
  addons/l10n_ro/__manifest__.py
  addons/l10n_ro/data/account.account.template.csv
  addons/l10n_ro/data/account_fiscal_position_data.xml
  addons/l10n_ro/data/account_tax_data.xml
  addons/l10n_ro/data/account_tax_report_data.xml
  addons/l10n_ro/data/l10n_ro_chart_post_data.xml
  addons/mail/static/src/model/model_field.js
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/__manifest__.py
  addons/microsoft_calendar/static/src/js/microsoft_calendar.js
  addons/microsoft_calendar/static/src/js/microsoft_calendar_popover.js
  addons/microsoft_calendar/static/src/xml/microsoft_calendar_popover.xml
  addons/microsoft_calendar/views/microsoft_calendar_templates.xml
  addons/microsoft_calendar/views/microsoft_calendar_views.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/purchase_product_matrix/static/tests/section_and_note_widget_tests.js
  addons/sale/models/sale.py
  addons/sale_purchase/models/purchase_order.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website_visitor.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/tools/translate.py
Labels: staging.saas-14.1

#12671 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/crm/tests/test_performances.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/res_partner.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_co/data/l10n_latam.identification.type.csv
  addons/l10n_latam_base/models/res_partner.py
  addons/l10n_pe/i18n/es.po
  addons/l10n_pe/i18n/l10n_pe.pot
  addons/l10n_ro/__manifest__.py
  addons/l10n_ro/data/account.account.template.csv
  addons/l10n_ro/data/account_fiscal_position_data.xml
  addons/l10n_ro/data/account_tax_data.xml
  addons/l10n_ro/data/account_tax_report_data.xml
  addons/l10n_ro/data/l10n_ro_chart_post_data.xml
  addons/mail/static/src/model/model_field.js
  addons/sale/models/sale.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_sale/models/website_visitor.py
  odoo/addons/base/models/res_partner.py
Labels: staging.saas-14.2

#12672 Syncing from upstream odoo/odoo (staging.12.0)
  addons/crm/security/crm_security.xml
Labels: staging.12.0

#12673 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/mail/models/res_users.py
  addons/sale/models/account_invoice.py
  addons/sale/models/sale.py
  addons/stock_account/models/product.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/test_mail/tests/test_mail_channel.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.13.0

#12674 Syncing from upstream odoo/odoo (12.0)
  addons/crm/security/crm_security.xml
  addons/link_tracker/models/link_tracker.py
  addons/sale_purchase/models/purchase_order.py
  addons/stock/models/stock_picking.py
  odoo/addons/base/models/res_partner.py
Labels: 12.0

#12675 Syncing from upstream odoo/odoo (13.0)
  addons/crm/security/crm_security.xml
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/web/static/src/js/views/list/list_renderer.js
Labels: 13.0

#12676 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/crm/security/crm_security.xml
  addons/delivery/tests/test_delivery_cost.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_stock_ddt/__init__.py
  addons/l10n_it_stock_ddt/__manifest__.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_it_stock_ddt/models/__init__.py
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_it_stock_ddt/tests/__init__.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/views/account_invoice_views.xml
  addons/l10n_it_stock_ddt/views/stock_picking_views.xml
  addons/mail/models/res_users.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/views/mrp_production_views.xml
  addons/sale/models/account_invoice.py
  addons/stock_account/models/product.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/test_mail/tests/test_mail_channel.py
  addons/web/static/src/js/core/popover.js
  addons/web/static/src/js/views/list/list_renderer.js
  odoo/addons/test_lint/tests/test_ecmascript.py
Labels: 14.0

#12677 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/account_move_views.xml
  addons/crm/security/crm_security.xml
  addons/delivery/tests/test_delivery_cost.py
  addons/l10n_in_sale/models/sale_order.py
  addons/l10n_in_sale_stock/models/sale_order.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_stock_ddt/__init__.py
  addons/l10n_it_stock_ddt/__manifest__.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_it_stock_ddt/models/__init__.py
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_it_stock_ddt/tests/__init__.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/views/account_invoice_views.xml
  addons/l10n_it_stock_ddt/views/stock_picking_views.xml
  addons/l10n_ro/__manifest__.py
  addons/l10n_ro/data/account.account.template.csv
  addons/l10n_ro/data/account_fiscal_position_data.xml
  addons/l10n_ro/data/account_tax_data.xml
  addons/l10n_ro/data/account_tax_report_data.xml
  addons/l10n_ro/data/l10n_ro_chart_post_data.xml
  addons/mail/static/src/components/chat_window_manager/chat_window_manager_tests.js
  addons/mail/static/src/components/composer_text_input/composer_text_input.js
  addons/mail/static/src/components/thread_view/thread_view.js
  addons/mail/static/src/components/thread_view/thread_view.xml
  addons/mail/static/src/models/thread_view/thread_view.js
  addons/mrp/models/mrp_production.py
  addons/mrp/views/mrp_production_views.xml
  addons/sale/models/account_invoice.py
  addons/sale/views/sale_views.xml
  addons/stock/models/stock_rule.py
  addons/stock_account/models/product.py
  addons/stock_account/views/stock_valuation_layer_views.xml
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/web/static/src/js/core/popover.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/basic_model_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/snippets.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/snippets/snippets.xml
  addons/website_event/views/event_type_views.xml
  addons/website_event_exhibitor/views/event_type_views.xml
  addons/website_event_meet/views/event_type_views.xml
  addons/website_event_track/views/event_type_views.xml
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
Labels: master

#12697 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/auth_signup/controllers/main.py
  addons/hr_attendance/static/tests/hr_attendance_tests.js
  addons/link_tracker/models/link_tracker.py
  addons/website/models/res_users.py
  addons/website_blog/views/website_blog_templates.xml
  odoo/addons/base/models/res_users.py
Labels: staging.saas-12.3

#12698 Syncing from upstream odoo/odoo (staging.saas-14.1)
  addons/account/models/account_move.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_event.py
  addons/hr_attendance/static/tests/hr_attendance_tests.js
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users.py
  addons/mail/static/src/components/discuss/tests/discuss_sidebar_tests.js
  addons/mail/static/src/components/discuss_sidebar/discuss_sidebar.js
  addons/mail/tests/test_mail_channel.py
  addons/sale/static/src/js/sale_order_view.js
  addons/test_mail/tests/test_performance.py
  addons/web/static/tests/views/calendar_tests.js
  addons/web_tour/static/src/js/tip.js
  addons/website_blog/views/website_blog_templates.xml
  odoo/addons/base/tests/test_ir_model.py
  odoo/models.py
Labels: staging.saas-14.1

#12704 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/auth_signup/controllers/main.py
  addons/hr_attendance/static/tests/hr_attendance_tests.js
  addons/link_tracker/models/link_tracker.py
  addons/website/models/res_users.py
  addons/website_blog/views/website_blog_templates.xml
  odoo/addons/base/models/res_users.py
Labels: tmp.saas-12.3

#12705 Syncing from upstream odoo/odoo (tmp.saas-14.1)
  addons/account/models/account_move.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_event.py
  addons/hr_attendance/static/tests/hr_attendance_tests.js
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users.py
  addons/mail/static/src/components/discuss/tests/discuss_sidebar_tests.js
  addons/mail/static/src/components/discuss_sidebar/discuss_sidebar.js
  addons/mail/tests/test_mail_channel.py
  addons/sale/static/src/js/sale_order_view.js
  addons/test_mail/tests/test_performance.py
  addons/web/static/tests/views/calendar_tests.js
  addons/web_tour/static/src/js/tip.js
  addons/website_blog/views/website_blog_templates.xml
  odoo/addons/base/tests/test_ir_model.py
  odoo/models.py
Labels: tmp.saas-14.1

#12710 [bt#13741][FIX] sale: use correct currency for reverse pricelist price computation
  addons/sale/models/sale.py
Labels: 11.0.project_el_543

#12715 Syncing from upstream odoo/odoo (staging.12.0)
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: staging.12.0

#12716 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/test_base_automation.py
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/mail/models/mail_thread.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon_delivery/models/sale_order.py
  addons/sale_stock/models/account_move.py
  addons/snailmail/models/snailmail_letter.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  doc/cla/individual/veryberry.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: staging.13.0

#12718 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/snailmail/models/snailmail_letter.py
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: tmp.saas-12.3

#12719 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: tmp.12.0

#12720 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/test_base_automation.py
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/mail/models/mail_thread.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon_delivery/models/sale_order.py
  addons/sale_stock/models/account_move.py
  addons/snailmail/models/snailmail_letter.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  doc/cla/individual/veryberry.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: tmp.13.0

#12721 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/test_base_automation.py
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project.py
  addons/l10n_ua/__manifest__.py
  addons/l10n_ua/data/account_tax_group_data.xml
  addons/l10n_ua/data/account_tax_template.xml
  addons/mail/models/mail_thread.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/point_of_sale/models/pos_session.py
  addons/portal/wizard/portal_share.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon_delivery/models/sale_order.py
  addons/sale_stock/models/account_move.py
  addons/snailmail/models/snailmail_letter.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  doc/cla/individual/veryberry.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
  odoo/tools/sql.py
Labels: 13.0

#12722 Syncing from upstream odoo/odoo (14.0)
  addons/event/models/event_mail.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_mail_schedule.py
  addons/event_sms/models/event_mail.py
  addons/l10n_cz/__init__.py
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account.group.template.csv
  addons/l10n_cz/data/account_chart_template_data.xml
  addons/l10n_cz/data/account_data.xml
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/demo_company.xml
  addons/l10n_cz/data/l10n_cz_coa_data.xml
  addons/l10n_cz/data/l10n_cz_coa_post_data.xml
  addons/l10n_cz/static/description/icon.png
  addons/l10n_sk/__init__.py
  addons/l10n_sk/__manifest__.py
  addons/l10n_sk/data/account.account.template.csv
  addons/l10n_sk/data/account.group.template.csv
  addons/l10n_sk/data/account_chart_template_data.xml
  addons/l10n_sk/data/account_data.xml
  addons/l10n_sk/data/account_fiscal_position_data.xml
  addons/l10n_sk/data/account_tax_data.xml
  addons/l10n_sk/data/demo_company.xml
  addons/l10n_sk/data/l10n_sk_coa_data.xml
  addons/l10n_sk/data/l10n_sk_coa_post_data.xml
  addons/l10n_sk/static/description/icon.png
  addons/mail/tests/common.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/portal/wizard/portal_share.py
  doc/cla/corporate/26house.md
  odoo/addons/test_lint/tests/__init__.py
  odoo/addons/test_lint/tests/test_jstranslate.py
  odoo/tools/pdf.py
  odoo/tools/sql.py
  requirements.txt
Labels: 14.0

#12723 Syncing from upstream odoo/odoo (master)
  addons/mail/models/mail_thread.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/test_mail/tests/test_performance.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/basic_model_tests.js
  addons/web/tests/__init__.py
  addons/web/tests/test_session_info.py
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/static/src/js/tours/tour_utils.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_misc.py
  odoo/tools/convert.py
  odoo/tools/misc.py
  odoo/tools/pdf.py
  odoo/tools/sql.py
Labels: master

#12727 Syncing from upstream odoo/odoo (saas-12.3)
  addons/auth_signup/controllers/main.py
  addons/hr_attendance/static/tests/hr_attendance_tests.js
  addons/link_tracker/models/link_tracker.py
  addons/portal/wizard/portal_share.py
  addons/snailmail/models/snailmail_letter.py
  addons/website/controllers/main.py
  addons/website/models/res_users.py
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  doc/cla/corporate/itpp-labs.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: saas-12.3

#12728 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/portal/wizard/portal_share.py
  addons/snailmail/models/snailmail_letter.py
  addons/website/controllers/main.py
  addons/website_sale/models/product.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  doc/cla/corporate/itpp-labs.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/tools/float_utils.py
Labels: staging.saas-12.3

#12731 [bt#13838] Server down cherry-picked from https://github.com/odoo/odoo/pull/25064/commits/c3a8e3b680f5f45a78c41f6cfc03cab434417869
  odoo/addons/base/ir/ir_mail_server.py
Labels: 10.0.project_th
