Repository brain-tec/odoo, pull requests merged in 2021-04, with the labels that each got.

#12739 Syncing from upstream odoo/odoo (saas-12.3)
  .github/CODEOWNERS
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_co/__manifest__.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/utils.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/mrp/data/mrp_demo.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_stock.py
  addons/mrp_bom_cost/tests/test_bom_price.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_portal_templates.xml
  addons/payment_payulatam/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/point_of_sale/static/src/js/db.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/sale.py
  addons/sale_coupon/data/sale_coupon_email_data.xml
  addons/sale_coupon/i18n/sale_coupon.pot
  addons/sale_coupon/wizard/sale_coupon_generate.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web/static/src/js/views/control_panel/search/search_bar_autocomplete_sources.js
  addons/web/static/tests/views/search_view_tests.js
  addons/website_mail_channel/controllers/main.py
  doc/cla/individual/qaidjoharbarbhaya.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/wizard/base_update_translations.py
  odoo/osv/expression.py
Labels: saas-12.3

#12740 Syncing from upstream odoo/odoo (saas-14.1)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_move_entry.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/common.py
  addons/crm/tests/test_crm_lead.py
  addons/crm/tests/test_crm_lead_convert.py
  addons/digest/views/res_config_settings_views.xml
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_event.py
  addons/hr_attendance/static/tests/hr_attendance_tests.js
  addons/l10n_cn/i18n_extra/l10n_cn.pot
  addons/l10n_cn/i18n_extra/zh_CN.po
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/link_tracker/models/link_tracker.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users.py
  addons/mail/static/src/components/discuss/tests/discuss_sidebar_tests.js
  addons/mail/static/src/components/discuss_sidebar/discuss_sidebar.js
  addons/mail/tests/test_mail_channel.py
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/static/tests/tours/point_of_sale.js
  addons/purchase/models/purchase.py
  addons/purchase_product_matrix/models/purchase.py
  addons/sale/static/src/js/sale_order_view.js
  addons/stock/models/stock_orderpoint.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/js/control_panel/custom_filter_item.js
  addons/web/static/src/js/libs/jquery.js
  addons/web/static/src/js/libs/popper.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/custom_filter_item_tests.js
  addons/web/static/tests/views/calendar_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website/static/src/scss/website.scss
  addons/website_blog/views/website_blog_templates.xml
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/static/src/scss/website_forum.scss
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/snippets/snippets.xml
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/tests/test_float.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/models.py
  odoo/modules/loading.py
  odoo/tools/float_utils.py
Labels: saas-14.1

#12743 Syncing from upstream odoo/odoo (staging.saas-12.3)
  .github/CODEOWNERS
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_co/__manifest__.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/utils.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/mrp/data/mrp_demo.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_stock.py
  addons/mrp_bom_cost/tests/test_bom_price.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_portal_templates.xml
  addons/payment_payulatam/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/point_of_sale/static/src/js/db.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/sale.py
  addons/sale_coupon/data/sale_coupon_email_data.xml
  addons/sale_coupon/i18n/sale_coupon.pot
  addons/sale_coupon/wizard/sale_coupon_generate.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web/static/src/js/views/control_panel/search/search_bar_autocomplete_sources.js
  addons/web/static/tests/views/search_view_tests.js
  addons/website_mail_channel/controllers/main.py
  doc/cla/individual/qaidjoharbarbhaya.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/wizard/base_update_translations.py
  odoo/osv/expression.py
Labels: staging.saas-12.3

#12750 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  .github/CODEOWNERS
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_co/__manifest__.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_message.py
  addons/mail/static/src/js/utils.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/mrp/data/mrp_demo.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_stock.py
  addons/mrp_bom_cost/tests/test_bom_price.py
  addons/payment/static/src/js/payment_form.js
  addons/payment/views/payment_portal_templates.xml
  addons/payment_payulatam/models/payment.py
  addons/payment_stripe_sca/models/payment.py
  addons/point_of_sale/static/src/js/db.js
  addons/portal/wizard/portal_share.py
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/sale.py
  addons/sale_coupon/data/sale_coupon_email_data.xml
  addons/sale_coupon/i18n/sale_coupon.pot
  addons/sale_coupon/wizard/sale_coupon_generate.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web/static/src/js/views/control_panel/search/search_bar_autocomplete_sources.js
  addons/web/static/tests/views/search_view_tests.js
  addons/website/controllers/main.py
  addons/website_mail_channel/controllers/main.py
  doc/cla/corporate/itpp-labs.md
  doc/cla/individual/qaidjoharbarbhaya.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/wizard/base_update_translations.py
  odoo/osv/expression.py
Labels: tmp.saas-12.3

#12756 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/models/account_move.py
  addons/account_check_printing/models/account_payment.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/account.group.template.csv
  addons/l10n_ar/data/account_group_data.xml
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/payment_payulatam/models/payment_acquirer.py
  addons/web/static/src/js/owl_compatibility.js
  addons/web/static/src/js/widgets/colorpicker.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/scss/website.editor.ui.scss
  addons/website/static/src/snippets/s_share/000.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website/views/snippets/s_quotes_carousel.xml
  addons/website/views/snippets/s_share.xml
  addons/website/views/snippets/snippets.xml
  addons/website_blog/views/snippets/snippets.xml
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/trescloud.md
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/wizard/base_update_translations.py
Labels: saas-14.3

#12757 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/models/account_move.py
  addons/account_check_printing/models/account_payment.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/account.group.template.csv
  addons/l10n_ar/data/account_group_data.xml
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/web/static/src/js/owl_compatibility.js
  addons/web/static/src/js/widgets/colorpicker.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/scss/website.editor.ui.scss
  addons/website/static/src/snippets/s_share/000.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website/views/snippets/s_quotes_carousel.xml
  addons/website/views/snippets/s_share.xml
  addons/website/views/snippets/snippets.xml
  addons/website_blog/views/snippets/snippets.xml
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/trescloud.md
  odoo/addons/base/wizard/base_update_translations.py
Labels: staging.saas-14.3

#12758 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/website_slides/models/slide_slide.py
Labels: staging.13.0

#12759 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_resequence.py
  addons/account_check_printing/models/account_payment.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/calendar/models/calendar_event.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/account.group.template.csv
  addons/l10n_ar/data/account_group_data.xml
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/__manifest__.py
  addons/l10n_ar_website_sale/controllers/__init__.py
  addons/l10n_ar_website_sale/controllers/main.py
  addons/l10n_ar_website_sale/data/ir_model_fields.xml
  addons/l10n_ar_website_sale/demo/website_demo.xml
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/static/description/icon.png
  addons/l10n_ar_website_sale/views/templates.xml
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/payment_payulatam/models/payment_acquirer.py
  addons/web/static/src/js/owl_compatibility.js
  addons/web/static/src/js/widgets/colorpicker.js
  addons/web_editor/static/lib/jQuery.transfo.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/backend/view_hierarchy.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/scss/website.editor.ui.scss
  addons/website/static/src/snippets/s_share/000.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website/views/snippets/s_quotes_carousel.xml
  addons/website/views/snippets/s_share.xml
  addons/website/views/snippets/snippets.xml
  addons/website_blog/views/snippets/snippets.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_product_configurator/static/tests/tours/website_sale_buy.js
  doc/cla/corporate/trescloud.md
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/wizard/base_update_translations.py
Labels: master

#12760 Syncing from upstream odoo/odoo (staging.13.0)
  .github/CODEOWNERS
  addons/mail/wizard/mail_compose_message.py
  addons/test_mail/tests/test_message_composer.py
Labels: staging.13.0

#12761 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/account_tax.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_resequence.py
  addons/account_check_printing/models/account_payment.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/account.group.template.csv
  addons/l10n_ar/data/account_group_data.xml
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/__manifest__.py
  addons/l10n_ar_website_sale/controllers/__init__.py
  addons/l10n_ar_website_sale/controllers/main.py
  addons/l10n_ar_website_sale/data/ir_model_fields.xml
  addons/l10n_ar_website_sale/demo/website_demo.xml
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/static/description/icon.png
  addons/l10n_ar_website_sale/views/templates.xml
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/web/static/src/js/owl_compatibility.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/editor/rte.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/scss/website.editor.ui.scss
  addons/website/static/src/snippets/s_share/000.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website/views/snippets/s_quotes_carousel.xml
  addons/website/views/snippets/s_share.xml
  addons/website_blog/views/snippets/snippets.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/trescloud.md
  odoo/addons/base/tests/test_base.py
Labels: tmp.saas-14.2

#12762 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/account_tax.py
  addons/account/views/account_move_views.xml
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_resequence.py
  addons/account_check_printing/models/account_payment.py
  addons/auth_oauth/data/auth_oauth_data.xml
  addons/calendar/models/calendar_event.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/data/account.group.template.csv
  addons/l10n_ar/data/account_group_data.xml
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/__manifest__.py
  addons/l10n_ar_website_sale/controllers/__init__.py
  addons/l10n_ar_website_sale/controllers/main.py
  addons/l10n_ar_website_sale/data/ir_model_fields.xml
  addons/l10n_ar_website_sale/demo/website_demo.xml
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/static/description/icon.png
  addons/l10n_ar_website_sale/views/templates.xml
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/web/static/src/js/owl_compatibility.js
  addons/web/static/src/js/widgets/colorpicker.js
  addons/web_editor/static/lib/jQuery.transfo.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/backend/view_hierarchy.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/static/src/scss/website.editor.ui.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_share/000.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_carousel.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website/views/snippets/s_quotes_carousel.xml
  addons/website/views/snippets/s_share.xml
  addons/website/views/snippets/snippets.xml
  addons/website_blog/views/snippets/snippets.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_product_configurator/static/tests/tours/website_sale_buy.js
  doc/cla/corporate/trescloud.md
  odoo/addons/base/wizard/base_update_translations.py
Labels: tmp.saas-14.3

#12763 Syncing from upstream odoo/odoo (tmp.13.0)
  .github/CODEOWNERS
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/tests/test_reconciliation.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/mail/wizard/mail_compose_message.py
  addons/test_mail/tests/test_message_composer.py
  addons/website_slides/models/slide_slide.py
Labels: tmp.13.0

#12765 Syncing from upstream odoo/odoo (12.0)
  .github/CODEOWNERS
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/web/static/src/js/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph_tests.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: 12.0

#12766 Syncing from upstream odoo/odoo (saas-12.3)
  .github/CODEOWNERS
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/mail/wizard/mail_compose_message.py
  addons/test_mail/tests/test_message_compose.py
Labels: saas-12.3

#12767 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  .github/CODEOWNERS
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/mail/wizard/mail_compose_message.py
  addons/test_mail/tests/test_message_compose.py
Labels: tmp.saas-12.3

#12768 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  .github/CODEOWNERS
  addons/l10n_cl/__manifest__.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp/models/stock_move.py
  addons/project/static/src/js/project_kanban.js
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  doc/cla/corporate/mainframemonkey.md
  doc/cla/individual/leogavidia.md
Labels: tmp.saas-14.2

#12769 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_product_line_mixin.py
  addons/account/models/reconciliation_widget.py
  addons/account/static/src/js/reconciliation/reconciliation_action.js
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/src/xml/account_reconciliation.xml
  addons/l10n_ar/data/l10n_ar_afip_responsibility_type_data.xml
  addons/l10n_ar/data/res_partner_data.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp_subcontracting/models/stock_move.py
  doc/cla/corporate/mainframemonkey.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.13.0

#12771 Syncing from upstream odoo/odoo (12.0)
  addons/web_editor/static/src/js/editor/transcoder.js
  addons/website/views/res_config_settings_views.xml
Labels: 12.0

#12776 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  doc/cla/individual/emilkholod.md
Labels: master

#12777 Syncing from upstream odoo/odoo (saas-12.3)
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/payment/static/src/js/payment_form.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: saas-12.3

#12779 Syncing from upstream odoo/odoo (saas-14.3)
  .github/CODEOWNERS
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/account_tax.py
  addons/account/views/account_move_views.xml
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_resequence.py
  addons/auth_oauth/data/auth_oauth_data.xml
  addons/calendar/models/calendar_event.py
  addons/l10n_ar/data/l10n_ar_afip_responsibility_type_data.xml
  addons/l10n_ar/data/res_partner_data.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/__manifest__.py
  addons/l10n_ar_website_sale/controllers/__init__.py
  addons/l10n_ar_website_sale/controllers/main.py
  addons/l10n_ar_website_sale/data/ir_model_fields.xml
  addons/l10n_ar_website_sale/demo/website_demo.xml
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/static/description/icon.png
  addons/l10n_ar_website_sale/views/templates.xml
  addons/l10n_cl/__manifest__.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_pe/data/l10n_latam_document_type_data.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/mrp_routing.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/project/static/src/js/project_kanban.js
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_warehouse.py
  addons/stock/views/stock_quant_views.xml
  addons/web_editor/static/lib/jQuery.transfo.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/backend/view_hierarchy.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/views/res_config_settings_views.xml
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_product_configurator/static/tests/tours/website_sale_buy.js
  doc/cla/corporate/mainframemonkey.md
  doc/cla/individual/emilkholod.md
  doc/cla/individual/leogavidia.md
  odoo/tests/common.py
Labels: saas-14.3

#12781 Syncing from upstream odoo/odoo (staging.saas-12.3)
  .github/CODEOWNERS
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mail/wizard/mail_compose_message.py
  addons/payment/static/src/js/payment_form.js
  addons/test_mail/tests/test_message_compose.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/views/res_config_settings_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: staging.saas-12.3

#12784 Syncing from upstream odoo/odoo (staging.12.0)
  .github/CODEOWNERS
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/web/static/src/js/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph_tests.js
  addons/web_editor/static/src/js/editor/transcoder.js
  addons/website/views/res_config_settings_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: staging.12.0

#12785 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/account/models/account_product_line_mixin.py
  addons/account/models/reconciliation_widget.py
  addons/account/static/src/js/reconciliation/reconciliation_action.js
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/account/static/src/xml/account_reconciliation.xml
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_ar/data/l10n_ar_afip_responsibility_type_data.xml
  addons/l10n_ar/data/res_partner_data.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/product.py
  addons/mrp_account/models/product.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/payment/static/src/js/payment_form.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/views/res_config_settings_views.xml
  doc/cla/corporate/mainframemonkey.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: staging.13.0

#12788 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/payment/static/src/js/payment_form.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/views/res_config_settings_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: tmp.saas-12.3

#12790 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  .github/CODEOWNERS
  addons/account/models/account_move.py
  addons/l10n_ar/data/l10n_ar_afip_responsibility_type_data.xml
  addons/l10n_ar/data/res_partner_data.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_cl/__manifest__.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_pe/data/l10n_latam_document_type_data.xml
  addons/mrp/models/mrp_routing.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/project/static/src/js/project_kanban.js
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_warehouse.py
  addons/stock/views/stock_quant_views.xml
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/views/res_config_settings_views.xml
  addons/website_form/static/src/snippets/s_website_form/000.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  doc/cla/corporate/mainframemonkey.md
  doc/cla/individual/emilkholod.md
  doc/cla/individual/leogavidia.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: tmp.saas-14.3

#12791 Syncing from upstream odoo/odoo (tmp.12.0)
  .github/CODEOWNERS
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/web/static/src/js/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph_tests.js
  addons/web_editor/static/src/js/editor/transcoder.js
  addons/website/views/res_config_settings_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: tmp.12.0

#12792 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mrp_account/models/product.py
  addons/payment/static/src/js/payment_form.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/views/res_config_settings_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/tests/common.py
Labels: tmp.13.0

#12794 Syncing from upstream odoo/odoo (13.0)
  addons/calendar/models/calendar.py
  addons/calendar/tests/test_calendar_recurrent_event_case2.py
Labels: 13.0

#12795 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  doc/howtos/profilecode.rst
Labels: 14.0

#12797 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/models/account_journal_dashboard.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/stock/models/stock_location.py
  doc/howtos/profilecode.rst
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
Labels: saas-14.2

#12798 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/models/account_journal_dashboard.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/event/models/event_event.py
  addons/l10n_be_edi/models/account_edi_format.py
  addons/stock/models/stock_location.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_utils.js
  addons/website_event/static/src/scss/event_templates_common.scss
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page.xml
  addons/website_event/views/event_templates_widgets.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_list.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_page.xml
  addons/website_event_exhibitor/views/event_sponsor_views.xml
  addons/website_event_meet/controllers/community.py
  addons/website_event_meet/views/event_meet_templates_list.xml
  addons/website_event_meet/views/event_meet_templates_page.xml
  addons/website_event_track/__manifest__.py
  addons/website_event_track/controllers/event_track.py
  addons/website_event_track/models/event_track.py
  addons/website_event_track/models/event_track_visitor.py
  addons/website_event_track/static/src/js/event_track_reminder.js
  addons/website_event_track/static/src/js/event_track_timer.js
  addons/website_event_track/static/src/scss/event_track_templates.scss
  addons/website_event_track/views/event_event_views.xml
  addons/website_event_track/views/event_templates.xml
  addons/website_event_track/views/event_track_templates_agenda.xml
  addons/website_event_track/views/event_track_templates_list.xml
  addons/website_event_track/views/event_track_templates_page.xml
  addons/website_event_track/views/event_track_templates_proposal.xml
  addons/website_event_track/views/event_track_views.xml
  addons/website_event_track_live/__manifest__.py
  addons/website_event_track_live/static/src/js/website_event_track_live.js
  addons/website_event_track_live/static/src/js/website_event_track_replay_suggestion.js
  addons/website_event_track_live/static/src/xml/website_event_track_live_templates.xml
  addons/website_event_track_live/views/event_track_templates_page.xml
  addons/website_sale/controllers/main.py
  doc/howtos/profilecode.rst
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_country.py
Labels: saas-14.3

#12801 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/models/account_journal_dashboard.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/stock/models/stock_location.py
  doc/howtos/profilecode.rst
Labels: staging.saas-14.2

#12802 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/models/account_journal_dashboard.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/event/models/event_event.py
  addons/l10n_be_edi/models/account_edi_format.py
  addons/stock/models/stock_location.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_utils.js
  addons/website_event/static/src/scss/event_templates_common.scss
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page.xml
  addons/website_event/views/event_templates_widgets.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_list.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_page.xml
  addons/website_event_exhibitor/views/event_sponsor_views.xml
  addons/website_event_meet/controllers/community.py
  addons/website_event_meet/views/event_meet_templates_list.xml
  addons/website_event_meet/views/event_meet_templates_page.xml
  addons/website_event_track/__manifest__.py
  addons/website_event_track/controllers/event_track.py
  addons/website_event_track/models/event_track.py
  addons/website_event_track/models/event_track_visitor.py
  addons/website_event_track/static/src/js/event_track_reminder.js
  addons/website_event_track/static/src/js/event_track_timer.js
  addons/website_event_track/static/src/scss/event_track_templates.scss
  addons/website_event_track/views/event_event_views.xml
  addons/website_event_track/views/event_templates.xml
  addons/website_event_track/views/event_track_templates_agenda.xml
  addons/website_event_track/views/event_track_templates_list.xml
  addons/website_event_track/views/event_track_templates_page.xml
  addons/website_event_track/views/event_track_templates_proposal.xml
  addons/website_event_track/views/event_track_views.xml
  addons/website_event_track_live/__manifest__.py
  addons/website_event_track_live/static/src/js/website_event_track_live.js
  addons/website_event_track_live/static/src/js/website_event_track_replay_suggestion.js
  addons/website_event_track_live/static/src/xml/website_event_track_live_templates.xml
  addons/website_event_track_live/views/event_track_templates_page.xml
  addons/website_sale/controllers/main.py
  doc/howtos/profilecode.rst
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.saas-14.3

#12807 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/models/account_journal_dashboard.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/stock/models/stock_location.py
  doc/howtos/profilecode.rst
Labels: tmp.saas-14.2

#12808 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/models/account_journal_dashboard.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/event/models/event_event.py
  addons/l10n_be_edi/models/account_edi_format.py
  addons/stock/models/stock_location.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_utils.js
  addons/website_event/static/src/scss/event_templates_common.scss
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page.xml
  addons/website_event/views/event_templates_widgets.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_list.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_page.xml
  addons/website_event_exhibitor/views/event_sponsor_views.xml
  addons/website_event_meet/controllers/community.py
  addons/website_event_meet/views/event_meet_templates_list.xml
  addons/website_event_meet/views/event_meet_templates_page.xml
  addons/website_event_track/__manifest__.py
  addons/website_event_track/controllers/event_track.py
  addons/website_event_track/models/event_track.py
  addons/website_event_track/models/event_track_visitor.py
  addons/website_event_track/static/src/js/event_track_reminder.js
  addons/website_event_track/static/src/js/event_track_timer.js
  addons/website_event_track/static/src/scss/event_track_templates.scss
  addons/website_event_track/views/event_event_views.xml
  addons/website_event_track/views/event_templates.xml
  addons/website_event_track/views/event_track_templates_agenda.xml
  addons/website_event_track/views/event_track_templates_list.xml
  addons/website_event_track/views/event_track_templates_page.xml
  addons/website_event_track/views/event_track_templates_proposal.xml
  addons/website_event_track/views/event_track_views.xml
  addons/website_event_track_live/__manifest__.py
  addons/website_event_track_live/static/src/js/website_event_track_live.js
  addons/website_event_track_live/static/src/js/website_event_track_replay_suggestion.js
  addons/website_event_track_live/static/src/xml/website_event_track_live_templates.xml
  addons/website_event_track_live/views/event_track_templates_page.xml
  addons/website_sale/controllers/main.py
  doc/howtos/profilecode.rst
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-14.3

#12813 Syncing from upstream odoo/odoo (13.0)
  addons/account/views/account_view.xml
  addons/stock_account/models/stock_valuation_layer.py
Labels: 13.0

#12814 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/wizard/mail_compose_message.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/tests/test_reinvoice.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_performance.py
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: 14.0

#12815 Syncing from upstream odoo/odoo (master)
  addons/calendar_sms/__manifest__.py
  addons/l10n_pe/data/l10n_latam_document_type_data.xml
  addons/mail/wizard/mail_compose_message.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_performance.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_utils.js
  addons/web_editor/static/src/scss/wysiwyg.scss
Labels: master

#12816 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_performance.py
Labels: saas-14.2

#12817 Syncing from upstream odoo/odoo (saas-14.3)
  addons/calendar_sms/__manifest__.py
  addons/event/tests/test_event_mail_schedule.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/tests/__init__.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_channel.py
  addons/mail/tests/test_mail_render.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/sms/tests/test_sms_template.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_message_composer.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website_forum/static/src/xml/website_forum_templates.xml
Labels: saas-14.3

#12821 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_performance.py
Labels: staging.saas-14.2

#12822 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/calendar_sms/__manifest__.py
  addons/event/tests/test_event_mail_schedule.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/tests/__init__.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_channel.py
  addons/mail/tests/test_mail_render.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/sms/tests/test_sms_template.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_message_composer.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website_forum/static/src/xml/website_forum_templates.xml
Labels: staging.saas-14.3

#12825 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/views/account_view.xml
  addons/stock_account/models/stock_valuation_layer.py
Labels: staging.13.0

#12828 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_performance.py
Labels: tmp.saas-14.2

#12829 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/calendar_sms/__manifest__.py
  addons/event/tests/test_event_mail_schedule.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/tests/__init__.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_channel.py
  addons/mail/tests/test_mail_render.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/sms/tests/test_sms_template.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_message_composer.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website_forum/static/src/xml/website_forum_templates.xml
Labels: tmp.saas-14.3

#12830 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/views/account_view.xml
  addons/stock_account/models/stock_valuation_layer.py
Labels: tmp.13.0

#12812 [bt#13804] Fixes error in module `email.generator` if no content-transfer-encoding is given in the message
  addons/mail/models/__init__.py
  addons/mail/models/email_generator_fix.py
Labels: 13.0.project_ms_592

#12832 Syncing from upstream odoo/odoo (12.0)
  addons/fetchmail/models/fetchmail.py
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: 12.0

#12833 Syncing from upstream odoo/odoo (13.0)
  addons/fetchmail/models/fetchmail.py
  addons/portal/controllers/portal.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: 13.0

#12835 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/calendar/controllers/main.py
  addons/crm/views/crm_lead_views.xml
  addons/delivery/tests/test_delivery_stock_move.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_ar/views/uom_uom_view.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_in/views/uom_uom_views.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mrp_account/models/mrp_production.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase/views/purchase_views.xml
  addons/purchase_stock/tests/test_onchange_product.py
  addons/sale/views/sale_views.xml
  addons/stock/views/stock_menu_views.xml
  addons/survey/controllers/survey_session_manage.py
  addons/survey/models/survey_survey.py
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/uom/models/uom_uom.py
  addons/uom/views/uom_uom_views.xml
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/static/src/js/menu/content.js
  addons/website/static/tests/tours/edit_megamenu.js
  addons/website_forum/static/src/xml/website_forum_templates.xml
  odoo/addons/base/models/ir_ui_view.py
Labels: master

#12836 Syncing from upstream odoo/odoo (saas-12.3)
  addons/fetchmail/models/fetchmail.py
  addons/website/views/res_config_settings_views.xml
  addons/website_event/static/src/js/website_geolocation.js
Labels: saas-12.3

#12837 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/point_of_sale/static/src/js/models.js
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  doc/cla/corporate/acsone.md
Labels: saas-14.2

#12838 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/calendar/controllers/main.py
  addons/calendar/tests/test_calendar_controller.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/tests/tours/edit_megamenu.js
Labels: saas-14.3

#12840 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/fetchmail/models/fetchmail.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: staging.saas-12.3

#12841 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/point_of_sale/static/src/js/models.js
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  doc/cla/corporate/acsone.md
Labels: staging.saas-14.2

#12842 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/calendar/controllers/main.py
  addons/calendar/tests/test_calendar_controller.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/tests/tours/edit_megamenu.js
Labels: staging.saas-14.3

#12843 Syncing from upstream odoo/odoo (staging.12.0)
  addons/fetchmail/models/fetchmail.py
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: staging.12.0

#12844 Syncing from upstream odoo/odoo (staging.13.0)
  addons/fetchmail/models/fetchmail.py
  addons/portal/controllers/portal.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: staging.13.0

#12846 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/fetchmail/models/fetchmail.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: tmp.saas-12.3

#12847 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/point_of_sale/static/src/js/models.js
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  doc/cla/corporate/acsone.md
Labels: tmp.saas-14.2

#12848 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/calendar/controllers/main.py
  addons/calendar/tests/test_calendar_controller.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_onchange_product.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/src/js/views/form/form_controller.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/views/form_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/tests/tours/edit_megamenu.js
Labels: tmp.saas-14.3

#12849 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/fetchmail/models/fetchmail.py
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: tmp.12.0

#12850 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/fetchmail/models/fetchmail.py
  addons/portal/controllers/portal.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/website_event/static/src/js/website_geolocation.js
Labels: tmp.13.0

#12851 Syncing from upstream odoo/odoo (12.0)
  addons/web/static/lib/jquery/jquery.js
Labels: 12.0

#12852 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
  addons/web/static/src/js/core/session.js
Labels: 13.0

#12853 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/mail/models/mail_message.py
  addons/mrp/models/product.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
  odoo/addons/base/views/res_users_views.xml
Labels: 14.0

#12854 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/l10n_ch/data/account.account.template.csv
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/data/l10n_ch_chart_data.xml
  addons/l10n_ch/i18n_extra/de.po
  addons/l10n_ch/i18n_extra/fr.po
  addons/l10n_ch/i18n_extra/it.po
  addons/l10n_ch/i18n_extra/l10n_ch.pot
  addons/mail/models/mail_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/models/mrp_routing.py
  addons/mrp/models/res_config_settings.py
  addons/project/models/project.py
  addons/sale_project/models/sale_order.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  odoo/addons/base/models/ir_asset.py
  odoo/addons/test_assetsbundle/tests/test_js_transpiler.py
  odoo/tools/js_transpiler.py
Labels: master

#12855 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
Labels: saas-12.3

#12856 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_message.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
Labels: saas-14.2

#12857 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/project/models/project.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website/static/src/scss/website.edit_mode.scss
  odoo/addons/base/models/ir_asset.py
Labels: saas-14.3

#12859 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
Labels: staging.saas-12.3

#12860 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_message.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
Labels: staging.saas-14.2

#12861 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/project/models/project.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website/static/src/scss/website.edit_mode.scss
  odoo/addons/base/models/ir_asset.py
Labels: staging.saas-14.3

#12862 Syncing from upstream odoo/odoo (staging.11.0)
  addons/web/static/lib/jquery/jquery.js
Labels: staging.11.0

#12863 Syncing from upstream odoo/odoo (staging.12.0)
  addons/web/static/lib/jquery/jquery.js
Labels: staging.12.0

#12864 Syncing from upstream odoo/odoo (staging.13.0)
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
  addons/web/static/src/js/core/session.js
Labels: staging.13.0

#12866 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
Labels: tmp.saas-12.3

#12867 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_message.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
Labels: tmp.saas-14.2

#12868 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/project/models/project.py
  addons/sale_project/models/sale_order.py
  addons/web/static/src/js/core/session.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website/static/src/scss/website.edit_mode.scss
  odoo/addons/base/models/ir_asset.py
Labels: tmp.saas-14.3

#12869 Syncing from upstream odoo/odoo (tmp.11.0)
  addons/web/static/lib/jquery/jquery.js
Labels: tmp.11.0

#12870 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/web/static/lib/jquery/jquery.js
Labels: tmp.12.0

#12871 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mail/models/mail_message.py
  addons/sale_timesheet/models/sale_order.py
  addons/web/static/src/js/core/session.js
Labels: tmp.13.0

#12872 Syncing from upstream odoo/odoo (11.0)
  addons/web/static/lib/jquery/jquery.js
Labels: 11.0

#12873 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_ar/data/account_tax_group.xml
  addons/l10n_ar/data/account_tax_template_data.xml
  addons/l10n_ar/demo/account_tax_demo.xml
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
Labels: 13.0

#12874 Syncing from upstream odoo/odoo (14.0)
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/static/src/js/google_calendar.js
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/static/src/js/microsoft_calendar.js
  addons/stock/models/product.py
  addons/website_livechat/models/website_visitor.py
  odoo/tools/convert.py
Labels: 14.0

#12876 Syncing from upstream odoo/odoo (saas-14.2)
  addons/calendar/models/calendar_recurrence.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mrp/models/product.py
  addons/stock/models/product.py
  addons/website/static/src/scss/website.scss
Labels: saas-14.2

#12877 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/js/import_action.js
  addons/calendar/models/calendar_recurrence.py
  addons/hr_timesheet/static/src/js/task_with_hours.js
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mrp/models/product.py
  addons/note/static/src/scss/note.scss
  addons/note/views/note_views.xml
  addons/project/static/src/css/project.css
  addons/project/static/src/js/project_form.js
  addons/project/static/src/scss/project_form.scss
  addons/stock/models/product.py
  addons/web/static/src/js/views/basic/widget_wrapper.js
  addons/web/static/src/js/widgets/week_days.js
  addons/web/static/tests/owl_compatibility_tests.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/views/website_views.xml
Labels: saas-14.3

#12879 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/calendar/models/calendar_recurrence.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mrp/models/product.py
  addons/stock/models/product.py
  addons/website/static/src/scss/website.scss
Labels: staging.saas-14.2

#12880 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/js/import_action.js
  addons/calendar/models/calendar_recurrence.py
  addons/hr_timesheet/static/src/js/task_with_hours.js
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mrp/models/product.py
  addons/note/static/src/scss/note.scss
  addons/note/views/note_views.xml
  addons/project/static/src/css/project.css
  addons/project/static/src/js/project_form.js
  addons/project/static/src/scss/project_form.scss
  addons/stock/models/product.py
  addons/web/static/src/js/views/basic/widget_wrapper.js
  addons/web/static/src/js/widgets/week_days.js
  addons/web/static/tests/owl_compatibility_tests.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/views/website_views.xml
Labels: staging.saas-14.3

#12882 Syncing from upstream odoo/odoo (staging.13.0)
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_ar/data/account_tax_group.xml
  addons/l10n_ar/data/account_tax_template_data.xml
  addons/l10n_ar/demo/account_tax_demo.xml
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
Labels: staging.13.0

#12885 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/calendar/models/calendar_recurrence.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mrp/models/product.py
  addons/stock/models/product.py
  addons/website/static/src/scss/website.scss
Labels: tmp.saas-14.2

#12886 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/js/import_action.js
  addons/calendar/models/calendar_recurrence.py
  addons/hr_timesheet/static/src/js/task_with_hours.js
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_DT_001.xml
  addons/l10n_it_edi/tests/expected_xmls/IT01234567890_FPR01_RC_001.xml
  addons/l10n_it_edi/tests/test_ir_mail_server.py
  addons/l10n_latam_invoice_document/models/account_move_line.py
  addons/mrp/models/product.py
  addons/note/static/src/scss/note.scss
  addons/note/views/note_views.xml
  addons/project/static/src/css/project.css
  addons/project/static/src/js/project_form.js
  addons/project/static/src/scss/project_form.scss
  addons/stock/models/product.py
  addons/web/static/src/js/views/basic/widget_wrapper.js
  addons/web/static/src/js/widgets/week_days.js
  addons/web/static/tests/owl_compatibility_tests.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/views/website_views.xml
Labels: tmp.saas-14.3

#12887 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_ar/data/account_tax_group.xml
  addons/l10n_ar/data/account_tax_template_data.xml
  addons/l10n_ar/demo/account_tax_demo.xml
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
Labels: tmp.13.0

#12891 Syncing from upstream odoo/odoo (master)
  addons/web/static/src/js/views/basic/widget_wrapper.js
  addons/web/static/src/js/widgets/week_days.js
  addons/web/static/tests/owl_compatibility_tests.js
Labels: master

#12894 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/et.po
  addons/base_automation/i18n/ca.po
  addons/crm/i18n/ka.po
  addons/delivery/i18n/cs.po
  addons/event_sale/i18n/ca.po
  addons/hr_holidays/i18n/hu.po
  addons/hr_recruitment/i18n/ka.po
  addons/iap/i18n/hu.po
  addons/im_livechat/i18n/hu.po
  addons/im_livechat/i18n/sl.po
  addons/mail/i18n/hu.po
  addons/mrp/i18n/sl.po
  addons/point_of_sale/i18n/cs.po
  addons/point_of_sale/i18n/et.po
  addons/portal/i18n/fr.po
  addons/product/i18n/cs.po
  addons/product/i18n/it.po
  addons/product_expiry/i18n/cs.po
  addons/product_expiry/i18n/et.po
  addons/project/i18n/ka.po
  addons/project/i18n/sl.po
  addons/purchase/i18n/it.po
  addons/purchase_requisition/i18n/et.po
  addons/sale/i18n/ca.po
  addons/sale/i18n/cs.po
  addons/sale/i18n/it.po
  addons/sale_management/i18n/it.po
  addons/sale_purchase/i18n/et.po
  addons/sale_stock/i18n/cs.po
  addons/sale_timesheet/i18n/de.po
  addons/sale_timesheet/i18n/it.po
  addons/stock/i18n/cs.po
  addons/stock_zebra/i18n/et.po
  addons/web/i18n/et.po
  addons/web/i18n/it.po
  addons/website/i18n/sl.po
  addons/website_blog/i18n/cs.po
  addons/website_event_track/i18n/cs.po
  addons/website_rating/i18n/es.po
  addons/website_sale/i18n/cs.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/da.po
  odoo/addons/base/i18n/sl.po
  odoo/addons/base/i18n/tr.po
  odoo/addons/base/i18n/zh_CN.po
Labels: 12.0

#12895 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account.py
Labels: 13.0

#12901 Syncing from upstream odoo/odoo (12.0)
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/attachment_box.js
  addons/mass_mailing/static/src/js/unsubscribe.js
Labels: 12.0

#12902 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/point_of_sale/models/account_move.py
  odoo/addons/base/models/ir_attachment.py
Labels: 13.0

#12903 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_account.py
  addons/account/views/account_journal_views.xml
  addons/event_sms/tests/test_sms_schedule.py
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/sms/tests/common.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  odoo/addons/base/models/ir_attachment.py
Labels: 14.0

#12904 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/base_import/static/src/js/import_action.js
  addons/calendar/tests/test_calendar_controller.py
  addons/hr_timesheet/static/src/js/task_with_hours.js
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/note/static/src/scss/note.scss
  addons/note/views/note_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/static/src/css/project.css
  addons/project/static/src/js/project_form.js
  addons/project/static/src/scss/project_form.scss
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/sale_timesheet/tests/test_project_billing.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/js/core/translation.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.scss
  addons/website/views/website_views.xml
  addons/website_event_track/data/mail_data.xml
  addons/website_event_track/models/event_track.py
  addons/website_event_track/views/mail_templates.xml
  addons/website_livechat/models/website_visitor.py
  doc/cla/corporate/acsone.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/views/res_users_views.xml
  odoo/tools/convert.py
Labels: master

#12905 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/attachment_box.js
Labels: saas-12.3

#12906 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/models/account_account.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp_account/models/mrp_production.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/point_of_sale/models/pos_session.py
  addons/website_livechat/models/website_visitor.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/views/res_users_views.xml
  odoo/tools/convert.py
Labels: saas-14.2

#12907 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/mrp_account/models/mrp_production.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/core/translation.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website_livechat/models/website_visitor.py
  doc/cla/corporate/acsone.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/views/res_users_views.xml
  odoo/tools/convert.py
Labels: saas-14.3

#12909 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/attachment_box.js
Labels: staging.saas-12.3

#12911 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/mrp_account/models/mrp_production.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/core/translation.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website_livechat/models/website_visitor.py
  doc/cla/corporate/acsone.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/views/res_users_views.xml
  odoo/tools/convert.py
Labels: staging.saas-14.3

#12912 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/i18n/et.po
  addons/base_automation/i18n/ca.po
  addons/crm/i18n/ka.po
  addons/delivery/i18n/cs.po
  addons/event_sale/i18n/ca.po
  addons/hr_holidays/i18n/hu.po
  addons/hr_recruitment/i18n/ka.po
  addons/iap/i18n/hu.po
  addons/im_livechat/i18n/hu.po
  addons/im_livechat/i18n/sl.po
  addons/mail/i18n/hu.po
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/attachment_box.js
  addons/mass_mailing/static/src/js/unsubscribe.js
  addons/mrp/i18n/sl.po
  addons/point_of_sale/i18n/cs.po
  addons/point_of_sale/i18n/et.po
  addons/portal/i18n/fr.po
  addons/product/i18n/cs.po
  addons/product/i18n/it.po
  addons/product_expiry/i18n/cs.po
  addons/product_expiry/i18n/et.po
  addons/project/i18n/ka.po
  addons/project/i18n/sl.po
  addons/purchase/i18n/it.po
  addons/purchase_requisition/i18n/et.po
  addons/sale/i18n/ca.po
  addons/sale/i18n/cs.po
  addons/sale/i18n/it.po
  addons/sale_management/i18n/it.po
  addons/sale_purchase/i18n/et.po
  addons/sale_stock/i18n/cs.po
  addons/sale_timesheet/i18n/de.po
  addons/sale_timesheet/i18n/it.po
  addons/stock/i18n/cs.po
  addons/stock_zebra/i18n/et.po
  addons/web/i18n/et.po
  addons/web/i18n/it.po
  addons/website/i18n/sl.po
  addons/website_blog/i18n/cs.po
  addons/website_event_track/i18n/cs.po
  addons/website_rating/i18n/es.po
  addons/website_sale/i18n/cs.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/da.po
  odoo/addons/base/i18n/sl.po
  odoo/addons/base/i18n/tr.po
  odoo/addons/base/i18n/zh_CN.po
Labels: staging.12.0

#12913 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/point_of_sale/models/account_move.py
  odoo/addons/base/models/ir_attachment.py
Labels: staging.13.0

#12916 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/attachment_box.js
Labels: tmp.saas-12.3

#12918 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/mrp_account/models/mrp_production.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/src/js/core/translation.js
  addons/web_editor/static/lib/odoo-editor/odoo-editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website_livechat/models/website_visitor.py
  doc/cla/corporate/acsone.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/views/res_users_views.xml
  odoo/tools/convert.py
Labels: tmp.saas-14.3

#12919 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/i18n/et.po
  addons/base_automation/i18n/ca.po
  addons/crm/i18n/ka.po
  addons/delivery/i18n/cs.po
  addons/event_sale/i18n/ca.po
  addons/hr_holidays/i18n/hu.po
  addons/hr_recruitment/i18n/ka.po
  addons/iap/i18n/hu.po
  addons/im_livechat/i18n/hu.po
  addons/im_livechat/i18n/sl.po
  addons/mail/i18n/hu.po
  addons/mail/i18n/mail.pot
  addons/mail/static/src/js/attachment_box.js
  addons/mass_mailing/static/src/js/unsubscribe.js
  addons/mrp/i18n/sl.po
  addons/point_of_sale/i18n/cs.po
  addons/point_of_sale/i18n/et.po
  addons/portal/i18n/fr.po
  addons/product/i18n/cs.po
  addons/product/i18n/it.po
  addons/product_expiry/i18n/cs.po
  addons/product_expiry/i18n/et.po
  addons/project/i18n/ka.po
  addons/project/i18n/sl.po
  addons/purchase/i18n/it.po
  addons/purchase_requisition/i18n/et.po
  addons/sale/i18n/ca.po
  addons/sale/i18n/cs.po
  addons/sale/i18n/it.po
  addons/sale_management/i18n/it.po
  addons/sale_purchase/i18n/et.po
  addons/sale_stock/i18n/cs.po
  addons/sale_timesheet/i18n/de.po
  addons/sale_timesheet/i18n/it.po
  addons/stock/i18n/cs.po
  addons/stock_zebra/i18n/et.po
  addons/web/i18n/et.po
  addons/web/i18n/it.po
  addons/website/i18n/sl.po
  addons/website_blog/i18n/cs.po
  addons/website_event_track/i18n/cs.po
  addons/website_rating/i18n/es.po
  addons/website_sale/i18n/cs.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/da.po
  odoo/addons/base/i18n/sl.po
  odoo/addons/base/i18n/tr.po
  odoo/addons/base/i18n/zh_CN.po
Labels: tmp.12.0

#12920 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/point_of_sale/models/account_move.py
  odoo/addons/base/models/ir_attachment.py
Labels: tmp.13.0

#12922 Syncing from upstream odoo/odoo (12.0)
  odoo/addons/base/models/ir_sequence.py
Labels: 12.0

#12923 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/models/pos_order.py
  addons/pos_cash_rounding/models/pos_order.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  addons/pos_cash_rounding/static/src/xml/pos.xml
  odoo/addons/base/models/ir_sequence.py
Labels: 13.0

#12924 Syncing from upstream odoo/odoo (14.0)
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/stock/models/stock_orderpoint.py
  addons/stock/report/report_stock_quantity.py
  addons/stock/tests/test_report_stock_quantity.py
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
Labels: 14.0

#12926 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mass_mailing/static/src/js/unsubscribe.js
  odoo/addons/base/models/ir_sequence.py
Labels: saas-12.3

#12927 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/event_sms/tests/test_sms_schedule.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/res_users.py
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/tests/test_reinvoice.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/sms/tests/common.py
  addons/stock/report/report_stock_quantity.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: saas-14.2

#12928 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/models/account_payment.py
  addons/event_sms/tests/test_sms_schedule.py
  addons/l10n_be/data/account_tax_report_data.xml
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/sms/tests/common.py
  addons/stock/report/report_stock_quantity.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
Labels: saas-14.3

#12930 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mass_mailing/static/src/js/unsubscribe.js
  odoo/addons/base/models/ir_sequence.py
Labels: staging.saas-12.3

#12931 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/event_sms/tests/test_sms_schedule.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/res_users.py
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/tests/test_reinvoice.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/sms/tests/common.py
  addons/stock/report/report_stock_quantity.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: staging.saas-14.2

#12932 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/models/account_payment.py
  addons/event_sms/tests/test_sms_schedule.py
  addons/l10n_be/data/account_tax_report_data.xml
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/sms/tests/common.py
  addons/stock/report/report_stock_quantity.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
Labels: staging.saas-14.3

#12933 Syncing from upstream odoo/odoo (staging.12.0)
  odoo/addons/base/models/ir_sequence.py
Labels: staging.12.0

#12934 Syncing from upstream odoo/odoo (staging.13.0)
  addons/point_of_sale/models/pos_order.py
  addons/pos_cash_rounding/models/pos_order.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  addons/pos_cash_rounding/static/src/xml/pos.xml
  odoo/addons/base/models/ir_sequence.py
Labels: staging.13.0

#12937 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/mass_mailing/static/src/js/unsubscribe.js
  odoo/addons/base/models/ir_sequence.py
Labels: tmp.saas-12.3

#12938 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/event_sms/tests/test_sms_schedule.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/res_users.py
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/tests/test_reinvoice.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/sms/tests/common.py
  addons/stock/report/report_stock_quantity.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: tmp.saas-14.2

#12939 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/models/account_payment.py
  addons/event_sms/tests/test_sms_schedule.py
  addons/l10n_be/data/account_tax_report_data.xml
  addons/link_tracker/tests/common.py
  addons/mail/tests/common.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/mass_mailing_sms/tests/common.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/sms/tests/common.py
  addons/stock/report/report_stock_quantity.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_mail_full/tests/test_mass_sms.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mail_full/tests/test_sms_post.py
  addons/test_mail_full/tests/test_sms_server_actions.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/test_mass_mailing/tests/common.py
  addons/test_mass_mailing/tests/test_blacklist_behavior.py
  addons/test_mass_mailing/tests/test_mailing_internals.py
  addons/test_mass_mailing/tests/test_mass_mailing.py
  addons/web/static/tests/helpers/test_utils_mock.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  odoo/addons/base/models/ir_sequence.py
Labels: tmp.saas-14.3

#12940 Syncing from upstream odoo/odoo (tmp.12.0)
  odoo/addons/base/models/ir_sequence.py
Labels: tmp.12.0

#12941 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/point_of_sale/models/pos_order.py
  addons/pos_cash_rounding/models/pos_order.py
  addons/pos_cash_rounding/static/src/js/pos_cash_rounding.js
  addons/pos_cash_rounding/static/src/xml/pos.xml
  odoo/addons/base/models/ir_sequence.py
Labels: tmp.13.0

#12943 Syncing from upstream odoo/odoo (12.0)
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
Labels: 12.0

#12944 Syncing from upstream odoo/odoo (13.0)
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
Labels: 13.0

#12945 Syncing from upstream odoo/odoo (14.0)
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing_list.py
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mass_mailing/wizard/mailing_list_merge_views.xml
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
Labels: 14.0

#12946 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/coupon/__manifest__.py
  addons/coupon/static/src/js/coupon.js
  addons/coupon/wizard/coupon_generate_views.xml
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/portal/wizard/portal_wizard_views.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/web/__manifest__.py
  addons/web/static/lib/ace/mode-qweb.js
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/widgets/domain_selector.js
  addons/web/static/src/scss/ace.scss
  addons/web/static/tests/widgets/domain_selector_tests.js
  addons/web_editor/static/src/js/common/ace.js
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_templates.xml
Labels: master

#12947 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/views/account_journal_views.xml
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: saas-14.2

#12948 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/views/account_journal_views.xml
  addons/base_import_module/tests/test_module/__manifest__.py
  addons/base_import_module/tests/test_module/test.xml
  addons/im_livechat/__manifest__.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/views/im_livechat_channel_templates.xml
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/portal/wizard/portal_wizard_views.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: saas-14.3

#12950 Syncing from upstream odoo/odoo (staging.saas-14.2)
  addons/account/views/account_journal_views.xml
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: staging.saas-14.2

#12951 Syncing from upstream odoo/odoo (staging.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/views/account_journal_views.xml
  addons/base_import_module/tests/test_module/__manifest__.py
  addons/base_import_module/tests/test_module/test.xml
  addons/im_livechat/__manifest__.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/views/im_livechat_channel_templates.xml
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/portal/wizard/portal_wizard_views.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: staging.saas-14.3

#12952 Syncing from upstream odoo/odoo (staging.12.0)
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
Labels: staging.12.0

#12953 Syncing from upstream odoo/odoo (staging.13.0)
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
Labels: staging.13.0

#12956 Syncing from upstream odoo/odoo (tmp.saas-14.2)
  addons/account/views/account_journal_views.xml
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: tmp.saas-14.2

#12957 Syncing from upstream odoo/odoo (tmp.saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/views/account_journal_views.xml
  addons/base_import_module/tests/test_module/__manifest__.py
  addons/base_import_module/tests/test_module/test.xml
  addons/im_livechat/__manifest__.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/views/im_livechat_channel_templates.xml
  addons/mass_mailing/tests/test_mailing_list.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing/wizard/mailing_list_merge.py
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/OrderReceipt.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/portal/wizard/portal_wizard_views.xml
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: tmp.saas-14.3

#12958 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
Labels: tmp.12.0

#12959 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/sale/models/account_move.py
  addons/sale/tests/test_reinvoice.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/snailmail_account/wizard/account_invoice_send.py
  addons/snailmail_account/wizard/account_invoice_send_views.xml
Labels: tmp.13.0

#12961 Syncing from upstream odoo/odoo (12.0)
  addons/base_iban/models/res_partner_bank.py
  addons/mail/models/mail_thread.py
  addons/sale/views/sale_views.xml
  addons/test_mail/tests/test_mail_gateway.py
Labels: 12.0

#12962 Syncing from upstream odoo/odoo (13.0)
  addons/crm/models/crm_lead.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_latam_invoice_document/views/report_templates.xml
  addons/mail/data/mail_data.xml
  addons/mail/models/mail_thread.py
  addons/portal/models/portal_mixin.py
  addons/project/models/project.py
  addons/sale/data/mail_data.xml
  addons/sale/models/sale.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
Labels: 13.0

#12963 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_payment.py
  addons/account_edi/tests/common.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/purchase_product_matrix/static/src/js/product_matrix_configurator.js
  addons/sale/static/src/js/tours/sale.js
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock/static/src/xml/report_stock_forecasted.xml
  addons/web/static/src/js/libs/jquery.js
Labels: 14.0

#12964 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_payment.py
  addons/board/models/board.py
  addons/gift_card/models/gift_card.py
  addons/gift_card/models/sale_order.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/res_users.py
  addons/l10n_nl/__manifest__.py
  addons/lunch/report/lunch_product_report.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/sale/static/src/js/tours/sale.js
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock/static/src/xml/report_stock_forecasted.xml
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website/static/src/js/menu/edit.js
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: master

#12965 Syncing from upstream odoo/odoo (saas-12.3)
  addons/mail/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
Labels: saas-12.3

#12966 Syncing from upstream odoo/odoo (saas-14.2)
  addons/account/models/account_payment.py
  addons/account_edi/tests/common.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/sale/models/account_move.py
  addons/sale/static/src/js/tours/sale.js
  addons/sale/tests/test_reinvoice.py
  addons/stock/static/src/xml/report_stock_forecasted.xml
  addons/web/static/src/js/libs/jquery.js
Labels: saas-14.2

#12967 Syncing from upstream odoo/odoo (saas-14.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account_edi/tests/common.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/gift_card/models/gift_card.py
  addons/gift_card/models/sale_order.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/res_users.py
  addons/l10n_be_edi/test_xml_file/efff_test.xml
  addons/l10n_be_edi/tests/test_ubl.py
  addons/l10n_nl/__manifest__.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/static/src/js/tours/sale.js
  addons/sale/tests/test_reinvoice.py
  addons/sale/tests/test_sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/stock/static/src/xml/report_stock_forecasted.xml
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website/models/website.py
  addons/website/static/src/js/menu/edit.js
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: saas-14.3

#12969 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/mail/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
Labels: staging.saas-12.3
