Repository brain-tec/odoo, pull requests merged in 2021-09, with the labels that each got.

#14965 Syncing from upstream odoo/odoo (13.0)
  addons/web/static/src/js/views/control_panel/control_panel_renderer.js
  addons/web/static/tests/views/control_panel_tests.js
  addons/website/static/src/js/utils.js
  addons/website_slides/static/src/js/slides_upload.js
Labels: 13.0

#14966 Syncing from upstream odoo/odoo (14.0)
  addons/mail/models/mail_thread.py
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website_slides/static/src/js/slides_upload.js
Labels: 14.0

#14968 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/fields.py
Labels: saas-12.3

#14969 Syncing from upstream odoo/odoo (saas-14.4)
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/mail/models/mail_thread.py
  addons/transifex/data/ir_translation_view.xml
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/views/view_dialogs_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: saas-14.4

#14971 Syncing from upstream odoo/odoo (staging.saas-12.3)
  odoo/fields.py
Labels: staging.saas-12.3

#14972 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/mail/models/mail_thread.py
  addons/transifex/data/ir_translation_view.xml
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/views/view_dialogs_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: staging.saas-14.4

#14973 Syncing from upstream odoo/odoo (staging.13.0)
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/lib/html2canvas.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/point_of_sale/static/src/js/screens.js
  addons/web/static/src/js/views/control_panel/control_panel_renderer.js
  addons/web/static/tests/views/control_panel_tests.js
  addons/website/static/src/js/utils.js
  addons/website_slides/static/src/js/slides_upload.js
  odoo/fields.py
Labels: staging.13.0

#14976 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  odoo/fields.py
Labels: tmp.saas-12.3

#14977 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/mail/models/mail_thread.py
  addons/transifex/data/ir_translation_view.xml
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/views/view_dialogs_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.saas-14.4

#14978 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/mail/models/mail_thread.py
  addons/point_of_sale/static/lib/html2canvas.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/point_of_sale/static/src/js/screens.js
  addons/web/static/src/js/views/control_panel/control_panel_renderer.js
  addons/web/static/tests/views/control_panel_tests.js
  addons/website/static/src/js/utils.js
  addons/website_slides/static/src/js/slides_upload.js
  odoo/fields.py
Labels: tmp.13.0

#14981 Syncing from upstream odoo/odoo (13.0)
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/stock_dropshipping/tests/test_dropship.py
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
  odoo/models.py
Labels: 13.0

#14982 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/lib/html2canvas.js
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/web/static/src/js/core/custom_hooks.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/js/widgets/pie_chart.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/control_panel_tests.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/models.py
Labels: 14.0

#14985 Syncing from upstream odoo/odoo (saas-14.4)
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_vn/__manifest__.py
  addons/l10n_vn/data/account.account.template.csv
  addons/l10n_vn/migrations/14.0.2.0.1/post-migration.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/web/static/src/js/core/custom_hooks.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/control_panel_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_slides/static/src/js/slides_upload.js
  odoo/models.py
Labels: saas-14.4

#14987 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: staging.saas-12.3

#14988 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_vn/__manifest__.py
  addons/l10n_vn/data/account.account.template.csv
  addons/l10n_vn/migrations/14.0.2.0.1/post-migration.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/web/static/src/js/core/custom_hooks.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/control_panel_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_slides/static/src/js/slides_upload.js
  odoo/models.py
Labels: staging.saas-14.4

#14989 Syncing from upstream odoo/odoo (staging.12.0)
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: staging.12.0

#14990 Syncing from upstream odoo/odoo (staging.13.0)
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/stock_dropshipping/tests/test_dropship.py
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
  odoo/models.py
Labels: staging.13.0

#14993 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: tmp.saas-12.3

#14994 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_vn/__manifest__.py
  addons/l10n_vn/data/account.account.template.csv
  addons/l10n_vn/migrations/14.0.2.0.1/post-migration.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/web/static/src/js/core/custom_hooks.js
  addons/web/static/src/js/views/abstract_controller.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/control_panel_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_slides/static/src/js/slides_upload.js
  odoo/models.py
Labels: tmp.saas-14.4

#14995 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: tmp.12.0

#14996 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/stock_dropshipping/tests/test_dropship.py
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
  odoo/models.py
Labels: tmp.13.0

#14998 Syncing from upstream odoo/odoo (12.0)
  addons/point_of_sale/views/pos_order_view.xml
Labels: 12.0

#14999 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/models/account_move.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: 13.0

#15000 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
Labels: 14.0

#15002 Syncing from upstream odoo/odoo (saas-14.4)
  addons/delivery/models/stock_move.py
  addons/point_of_sale/static/lib/html2canvas.js
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/widgets/pie_chart.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
Labels: saas-14.4

#15004 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/delivery/models/stock_move.py
  addons/point_of_sale/static/lib/html2canvas.js
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/widgets/pie_chart.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
Labels: staging.saas-14.4

#15005 Syncing from upstream odoo/odoo (staging.12.0)
  addons/point_of_sale/views/pos_order_view.xml
Labels: staging.12.0

#15006 Syncing from upstream odoo/odoo (staging.13.0)
  addons/l10n_ar/models/account_move.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: staging.13.0

#15009 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/delivery/models/stock_move.py
  addons/point_of_sale/static/lib/html2canvas.js
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/js/widgets/pie_chart.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website_form/static/src/snippets/s_website_form/options.js
  addons/website_sale_slides/models/sale_order.py
  addons/website_sale_slides/tests/test_course_purchase_flow.py
Labels: tmp.saas-14.4

#15010 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/point_of_sale/views/pos_order_view.xml
Labels: tmp.12.0

#15011 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/l10n_ar/models/account_move.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
Labels: tmp.13.0

#15013 Syncing from upstream odoo/odoo (12.0)
  addons/web_editor/controllers/main.py
Labels: 12.0

#15014 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/lib/qunit/qunit-2.9.1.js
  addons/web/static/src/js/libs/fullcalendar.js
  addons/web/static/tests/helpers/qunit_config.js
  addons/web/static/tests/helpers/test_utils_dom.js
  addons/web/static/tests/views/list_tests.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/tours/slides_tour.js
  addons/website_slides/static/src/xml/slide_management.xml
  addons/website_slides/static/src/xml/website_slides_upload.xml
  odoo/addons/base/controllers/rpc.py
  odoo/addons/base/tests/test_xmlrpc.py
  odoo/service/server.py
  odoo/service/wsgi_server.py
Labels: 14.0

#15016 Syncing from upstream odoo/odoo (saas-14.4)
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/web/static/lib/owl/owl.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.ui.scss
Labels: saas-14.4

#15017 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/web/static/lib/owl/owl.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.ui.scss
Labels: staging.saas-14.4

#15018 Syncing from upstream odoo/odoo (staging.12.0)
  addons/web_editor/controllers/main.py
Labels: staging.12.0

#15021 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/web/static/lib/owl/owl.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.ui.scss
Labels: tmp.saas-14.4

#15022 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/web_editor/controllers/main.py
Labels: tmp.12.0

#15029 [bt#16095] fix massmailing constraint
  addons/mass_mailing/models/link_tracker.py
Labels: 13.0.project_zi_593

#15030 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/website_sale/models/sale_order.py
Labels: 12.0

#15031 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/link_tracker/models/link_tracker.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/report/report_stock_quantity.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/web_editor/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: 13.0

#15032 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/test_file/test_facturx.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/account_qr_code_sepa/models/res_bank.py
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/link_tracker/models/mail_render_mixin.py
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/report/report_stock_quantity.py
  addons/test_mail_full/tests/test_sms_sms.py
  addons/web/static/src/js/model.js
  addons/web_editor/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
Labels: 14.0

#15034 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/models/partner.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/web_editor/controllers/main.py
  addons/website_sale/models/sale_order.py
Labels: saas-12.3

#15035 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment.py
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/link_tracker/models/mail_render_mixin.py
  addons/stock/views/stock_orderpoint_views.xml
  addons/test_mail_full/tests/test_sms_sms.py
  addons/web/static/lib/qunit/qunit-2.9.1.js
  addons/web/static/src/js/libs/fullcalendar.js
  addons/web/static/src/js/model.js
  addons/web/static/tests/helpers/qunit_config.js
  addons/web/static/tests/helpers/test_utils_dom.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/controllers/main.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/tours/slides_tour.js
  addons/website_slides/static/src/xml/slide_management.xml
  addons/website_slides/static/src/xml/website_slides_upload.xml
  odoo/addons/base/controllers/rpc.py
  odoo/addons/base/tests/test_xmlrpc.py
  odoo/service/server.py
  odoo/service/wsgi_server.py
Labels: saas-14.4

#15047 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/views/account_move_views.xml
  addons/account_edi/views/account_payment_views.xml
  addons/hr_recruitment/data/hr_recruitment_data.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/product_expiry/models/stock_move_line.py
  addons/purchase_stock/models/purchase.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_stock_quantity.py
  addons/stock/tests/test_report_stock_quantity.py
  addons/web/static/src/js/fields/relational_fields.js
  doc/cla/individual/ettoreleandrotognoli.md
  doc/cla/individual/imbarbudiman.md
  doc/cla/individual/joseramongarcia.md
  doc/cla/individual/saran440.md
Labels: 14.0

#15049 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account_qr_code_sepa/models/res_bank.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/product.py
  addons/stock/report/report_stock_quantity.py
  doc/cla/individual/ettoreleandrotognoli.md
  doc/cla/individual/imbarbudiman.md
  doc/cla/individual/joseramongarcia.md
  doc/cla/individual/saran440.md
Labels: saas-14.4

#15051 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/account_qr_code_sepa/models/res_bank.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/product.py
  addons/stock/report/report_stock_quantity.py
  doc/cla/individual/ettoreleandrotognoli.md
  doc/cla/individual/imbarbudiman.md
  doc/cla/individual/joseramongarcia.md
  doc/cla/individual/saran440.md
Labels: staging.saas-14.4

#15055 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/account_qr_code_sepa/models/res_bank.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/product.py
  addons/stock/report/report_stock_quantity.py
  doc/cla/individual/ettoreleandrotognoli.md
  doc/cla/individual/imbarbudiman.md
  doc/cla/individual/joseramongarcia.md
  doc/cla/individual/saran440.md
Labels: tmp.saas-14.4

#15058 Syncing from upstream odoo/odoo (12.0)
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: 12.0

#15059 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/survey/models/survey_user.py
Labels: 14.0

#15061 Syncing from upstream odoo/odoo (saas-14.4)
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/product_expiry/models/stock_move_line.py
  addons/purchase_stock/models/purchase.py
  addons/sale/models/sale_order.py
  addons/sale_crm/models/crm_lead.py
  addons/stock/models/stock_move.py
Labels: saas-14.4

#15062 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/product_expiry/models/stock_move_line.py
  addons/purchase_stock/models/purchase.py
  addons/sale/models/sale_order.py
  addons/sale_crm/models/crm_lead.py
  addons/stock/models/stock_move.py
Labels: staging.saas-14.4

#15063 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: staging.12.0

#15065 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/product_expiry/models/stock_move_line.py
  addons/purchase_stock/models/purchase.py
  addons/sale/models/sale_order.py
  addons/sale_crm/models/crm_lead.py
  addons/stock/models/stock_move.py
Labels: tmp.saas-14.4

#15066 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: tmp.12.0

#15068 Syncing from upstream odoo/odoo (12.0)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 12.0

#15069 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_workorder_operation.py
  addons/payment/models/payment_acquirer.py
  addons/point_of_sale/static/src/js/models.js
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
Labels: 13.0

#15070 Syncing from upstream odoo/odoo (14.0)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/gamification/models/goal.py
  addons/l10n_ch/data/l10n_ch_chart_data.xml
  addons/l10n_ch/i18n_extra/en.po
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/payment/models/payment_acquirer.py
  addons/sale/models/payment.py
  addons/sale/tests/test_sale_transaction.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/js/owl_compatibility.js
  addons/website_event_track_live/controllers/session.py
Labels: 14.0

#15071 Syncing from upstream odoo/odoo (master)
  addons/account/wizard/accrued_orders.py
  addons/mail/models/mail_channel.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/sale_crm/models/crm_lead.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_stock_quantity.py
  addons/stock/tests/test_report_stock_quantity.py
  addons/survey/models/survey_user_input.py
  addons/web/static/src/legacy/js/owl_compatibility.js
  addons/web/static/src/legacy/scss/ribbon.scss
  odoo/addons/base/models/ir_actions.py
Labels: master

#15072 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/point_of_sale/static/src/js/models.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: saas-12.3

#15073 Syncing from upstream odoo/odoo (saas-14.4)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/delivery/models/sale_order.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_stock_quantity.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_report_stock_quantity.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/survey/models/survey_user.py
  addons/web/static/src/js/owl_compatibility.js
  addons/website_event_track_live/controllers/session.py
Labels: saas-14.4

#15074 Syncing from upstream odoo/odoo (saas-14.5)
  addons/http_routing/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/project/models/project.py
  addons/project/static/src/scss/project_rightpanel.scss
  addons/sale/models/sale_order.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/tests/__init__.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/stock_picking_batch/views/stock_picking_wave_views.xml
  addons/stock_picking_batch/wizard/stock_add_to_wave.py
  addons/survey/models/survey_user_input.py
  addons/web/static/src/legacy/js/core/session.js
  addons/web/static/src/legacy/js/owl_compatibility.js
  addons/web/static/src/legacy/js/public/public_root.js
  addons/web/static/src/legacy/scss/ribbon.scss
  addons/website/tests/test_lang_url.py
  addons/website/tests/test_qweb.py
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale_stock/static/src/xml/website_sale_stock_product_availability.xml
Labels: saas-14.5

#15075 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/point_of_sale/static/src/js/models.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: staging.saas-12.3

#15076 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/delivery/models/sale_order.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_stock_quantity.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_report_stock_quantity.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/survey/models/survey_user.py
  addons/web/static/src/js/owl_compatibility.js
  addons/website_event_track_live/controllers/session.py
Labels: staging.saas-14.4

#15077 Syncing from upstream odoo/odoo (staging.saas-14.5)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/http_routing/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/project/models/project.py
  addons/project/static/src/scss/project_rightpanel.scss
  addons/sale/models/sale_order.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/tests/__init__.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/stock_picking_batch/views/stock_picking_wave_views.xml
  addons/stock_picking_batch/wizard/stock_add_to_wave.py
  addons/survey/models/survey_user_input.py
  addons/web/static/src/legacy/js/core/session.js
  addons/web/static/src/legacy/js/owl_compatibility.js
  addons/web/static/src/legacy/js/public/public_root.js
  addons/web/static/src/legacy/scss/ribbon.scss
  addons/website/tests/test_lang_url.py
  addons/website/tests/test_qweb.py
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale_stock/static/src/xml/website_sale_stock_product_availability.xml
Labels: staging.saas-14.5

#15078 Syncing from upstream odoo/odoo (staging.12.0)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: staging.12.0

#15079 Syncing from upstream odoo/odoo (staging.13.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_workorder_operation.py
  addons/payment/models/payment_acquirer.py
  addons/point_of_sale/static/src/js/models.js
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
Labels: staging.13.0

#15081 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/point_of_sale/static/src/js/models.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/res_bank.py
Labels: tmp.saas-12.3

#15082 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/delivery/models/sale_order.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_stock_quantity.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_report_stock_quantity.py
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/survey/models/survey_user.py
  addons/web/static/src/js/owl_compatibility.js
  addons/website_event_track_live/controllers/session.py
Labels: tmp.saas-14.4

#15083 Syncing from upstream odoo/odoo (tmp.saas-14.5)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_pls.py
  addons/http_routing/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/product.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/project/models/project.py
  addons/project/static/src/scss/project_rightpanel.scss
  addons/sale/models/sale_order.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/tests/__init__.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/stock_picking_batch/views/stock_picking_wave_views.xml
  addons/stock_picking_batch/wizard/stock_add_to_wave.py
  addons/survey/models/survey_user_input.py
  addons/web/static/src/legacy/js/core/session.js
  addons/web/static/src/legacy/js/owl_compatibility.js
  addons/web/static/src/legacy/js/public/public_root.js
  addons/web/static/src/legacy/scss/ribbon.scss
  addons/website/tests/test_lang_url.py
  addons/website/tests/test_qweb.py
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale_stock/static/src/xml/website_sale_stock_product_availability.xml
Labels: tmp.saas-14.5

#15084 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: tmp.12.0

#15085 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_workorder_operation.py
  addons/payment/models/payment_acquirer.py
  addons/point_of_sale/static/src/js/models.js
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
Labels: tmp.13.0

#15087 Syncing from upstream odoo/odoo (12.0)
  addons/account_facturx/data/facturx_templates.xml
Labels: 12.0

#15088 Syncing from upstream odoo/odoo (13.0)
  addons/gamification/views/mail_templates.xml
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  odoo/tools/cloc.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 13.0

#15089 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/account_move.py
  addons/auth_totp/controllers/home.py
  addons/auth_totp/i18n/auth_totp.pot
  addons/auth_totp/models/res_users.py
  addons/auth_totp/static/tests/totp_flow.js
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp/views/templates.xml
  addons/auth_totp/views/user_preferences.xml
  addons/auth_totp_portal/i18n/auth_totp_portal.pot
  addons/auth_totp_portal/static/src/js/totp_frontend.js
  addons/auth_totp_portal/views/templates.xml
  addons/l10n_es_edi_sii/__init__.py
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/data/account_edi_data.xml
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/data/res_partner_data.xml
  addons/l10n_es_edi_sii/demo/certificates/sello_entidad_act.p12
  addons/l10n_es_edi_sii/demo/demo_company.xml
  addons/l10n_es_edi_sii/models/__init__.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_move.py
  addons/l10n_es_edi_sii/models/account_tax.py
  addons/l10n_es_edi_sii/models/l10n_es_edi_certificate.py
  addons/l10n_es_edi_sii/models/res_company.py
  addons/l10n_es_edi_sii/models/res_config_settings.py
  addons/l10n_es_edi_sii/security/ir.model.access.csv
  addons/l10n_es_edi_sii/tests/__init__.py
  addons/l10n_es_edi_sii/tests/common.py
  addons/l10n_es_edi_sii/tests/test_edi_web_services.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_es_edi_sii/views/account_tax_views.xml
  addons/l10n_es_edi_sii/views/l10n_es_edi_certificate_views.xml
  addons/l10n_es_edi_sii/views/res_config_settings_views.xml
  addons/mrp/models/mrp_bom.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/core/misc.js
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
  odoo/addons/base/models/res_users.py
  odoo/tools/cloc.py
Labels: 14.0

#15091 Syncing from upstream odoo/odoo (saas-12.3)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: saas-12.3

#15092 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi/views/account_payment_views.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/test_file/test_facturx.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/auth_totp/controllers/home.py
  addons/auth_totp/i18n/auth_totp.pot
  addons/auth_totp/models/res_users.py
  addons/auth_totp/static/tests/totp_flow.js
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp/views/templates.xml
  addons/auth_totp/views/user_preferences.xml
  addons/auth_totp_portal/i18n/auth_totp_portal.pot
  addons/auth_totp_portal/static/src/js/totp_frontend.js
  addons/auth_totp_portal/views/templates.xml
  addons/gamification/models/goal.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/core/misc.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
  odoo/addons/base/models/res_users.py
  odoo/modules/registry.py
  odoo/tools/cloc.py
Labels: saas-14.4

#15094 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: staging.saas-12.3

#15095 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi/views/account_payment_views.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/test_file/test_facturx.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/auth_totp/controllers/home.py
  addons/auth_totp/i18n/auth_totp.pot
  addons/auth_totp/models/res_users.py
  addons/auth_totp/static/tests/totp_flow.js
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp/views/templates.xml
  addons/auth_totp/views/user_preferences.xml
  addons/auth_totp_portal/i18n/auth_totp_portal.pot
  addons/auth_totp_portal/static/src/js/totp_frontend.js
  addons/auth_totp_portal/views/templates.xml
  addons/gamification/models/goal.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/core/misc.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
  odoo/addons/base/models/res_users.py
  odoo/modules/registry.py
  odoo/tools/cloc.py
Labels: staging.saas-14.4

#15097 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account_facturx/data/facturx_templates.xml
Labels: staging.12.0

#15098 Syncing from upstream odoo/odoo (staging.13.0)
  addons/gamification/views/mail_templates.xml
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  odoo/tools/cloc.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: staging.13.0

#15100 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: tmp.saas-12.3

#15101 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi/views/account_payment_views.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/test_file/test_facturx.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/auth_totp/controllers/home.py
  addons/auth_totp/i18n/auth_totp.pot
  addons/auth_totp/models/res_users.py
  addons/auth_totp/static/tests/totp_flow.js
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp/views/templates.xml
  addons/auth_totp/views/user_preferences.xml
  addons/auth_totp_portal/i18n/auth_totp_portal.pot
  addons/auth_totp_portal/static/src/js/totp_frontend.js
  addons/auth_totp_portal/views/templates.xml
  addons/gamification/models/goal.py
  addons/stock_account/models/product.py
  addons/web/static/src/js/core/misc.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/js/views/graph/graph_model.js
  addons/web/static/tests/views/graph_tests.js
  odoo/addons/base/models/res_users.py
  odoo/modules/registry.py
  odoo/tools/cloc.py
Labels: tmp.saas-14.4

#15103 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account_facturx/data/facturx_templates.xml
Labels: tmp.12.0

#15104 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/gamification/views/mail_templates.xml
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  odoo/tools/cloc.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: tmp.13.0

#15108 Syncing from upstream odoo/odoo (master)
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/js/website_slides.editor.js
Labels: master

#15110 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/hr.po
  addons/account/i18n/pt.po
  addons/account/i18n/sv.po
  addons/account_bank_statement_import/i18n/hr.po
  addons/analytic/i18n/sv.po
  addons/barcodes/i18n/sv.po
  addons/base_iban/i18n/pt_BR.po
  addons/base_setup/i18n/fi.po
  addons/crm/i18n/hr.po
  addons/crm_reveal/i18n/hr.po
  addons/delivery/i18n/hr.po
  addons/delivery/i18n/sv.po
  addons/google_calendar/i18n/hr.po
  addons/hr_holidays/i18n/sv.po
  addons/hr_timesheet/i18n/sv.po
  addons/mail/i18n/fi.po
  addons/mail/i18n/hu.po
  addons/membership/i18n/hu.po
  addons/mrp/i18n/hr.po
  addons/mrp/i18n/sv.po
  addons/mrp_bom_cost/i18n/ro.po
  addons/payment_stripe/i18n/fi.po
  addons/payment_stripe_checkout_webhook/i18n/fi.po
  addons/point_of_sale/i18n/hr.po
  addons/point_of_sale/i18n/sv.po
  addons/portal/i18n/hu.po
  addons/pos_restaurant/i18n/de.po
  addons/pos_restaurant/i18n/hr.po
  addons/product/i18n/sv.po
  addons/project/i18n/hr.po
  addons/purchase/i18n/sv.po
  addons/purchase_requisition/i18n/sv.po
  addons/rating/i18n/hu.po
  addons/sale/i18n/hr.po
  addons/sale/i18n/sv.po
  addons/sale_purchase/i18n/sv.po
  addons/sale_timesheet/i18n/sv.po
  addons/stock/i18n/hr.po
  addons/stock/i18n/sv.po
  addons/stock_account/i18n/hr.po
  addons/stock_account/i18n/sv.po
  addons/stock_picking_batch/i18n/sv.po
  addons/stock_zebra/i18n/sv.po
  addons/survey/i18n/fi.po
  addons/website_membership/i18n/hu.po
  addons/website_sale/i18n/hr.po
  odoo/addons/base/i18n/fi.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/pl.po
  odoo/addons/base/i18n/pt.po
  odoo/addons/base/i18n/sv.po
Labels: 12.0

#15118 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/payment/views/payment_portal_templates.xml
  addons/website_sale/views/templates.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/res_bank.py
Labels: 13.0

#15119 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/wizard/account_resequence.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_mail_composer.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_full_composer.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/controllers/main.py
  addons/snailmail/wizard/snailmail_letter_missing_required_fields_views.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/models/__init__.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/website/static/src/js/editor/editor_menu.js
  addons/website/static/src/js/editor/wysiwyg_multizone.js
  odoo/addons/base/wizard/base_partner_merge.py
Labels: 14.0

#15120 Syncing from upstream odoo/odoo (master)
  addons/account/wizard/account_resequence.py
  addons/mail/static/src/components/activity/activity.xml
  addons/mail/static/src/components/rtc_video/rtc_video.js
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/rtc_session/rtc_session.js
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock/models/product.py
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
Labels: master

#15121 Syncing from upstream odoo/odoo (saas-12.3)
  addons/sale_stock/models/sale_order.py
Labels: saas-12.3

#15122 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account/models/account_move.py
  addons/account/wizard/account_resequence.py
  addons/mail/models/mail_render_mixin.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_template.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/menu/edit.js
Labels: saas-14.4

#15125 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/sale_stock/models/sale_order.py
Labels: staging.saas-12.3

#15126 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/account/models/account_move.py
  addons/account/wizard/account_resequence.py
  addons/mail/models/mail_render_mixin.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_template.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/menu/edit.js
Labels: staging.saas-14.4

#15128 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/i18n/hr.po
  addons/account/i18n/pt.po
  addons/account/i18n/sv.po
  addons/account_bank_statement_import/i18n/hr.po
  addons/analytic/i18n/sv.po
  addons/barcodes/i18n/sv.po
  addons/base_iban/i18n/pt_BR.po
  addons/base_setup/i18n/fi.po
  addons/crm/i18n/hr.po
  addons/crm_reveal/i18n/hr.po
  addons/delivery/i18n/hr.po
  addons/delivery/i18n/sv.po
  addons/google_calendar/i18n/hr.po
  addons/hr_holidays/i18n/sv.po
  addons/hr_timesheet/i18n/sv.po
  addons/mail/i18n/fi.po
  addons/mail/i18n/hu.po
  addons/membership/i18n/hu.po
  addons/mrp/i18n/hr.po
  addons/mrp/i18n/sv.po
  addons/mrp_bom_cost/i18n/ro.po
  addons/payment_stripe/i18n/fi.po
  addons/payment_stripe_checkout_webhook/i18n/fi.po
  addons/point_of_sale/i18n/hr.po
  addons/point_of_sale/i18n/sv.po
  addons/portal/i18n/hu.po
  addons/pos_restaurant/i18n/de.po
  addons/pos_restaurant/i18n/hr.po
  addons/product/i18n/sv.po
  addons/project/i18n/hr.po
  addons/purchase/i18n/sv.po
  addons/purchase_requisition/i18n/sv.po
  addons/rating/i18n/hu.po
  addons/sale/i18n/hr.po
  addons/sale/i18n/sv.po
  addons/sale_purchase/i18n/sv.po
  addons/sale_timesheet/i18n/sv.po
  addons/stock/i18n/hr.po
  addons/stock/i18n/sv.po
  addons/stock_account/i18n/hr.po
  addons/stock_account/i18n/sv.po
  addons/stock_picking_batch/i18n/sv.po
  addons/stock_zebra/i18n/sv.po
  addons/survey/i18n/fi.po
  addons/website_membership/i18n/hu.po
  addons/website_sale/i18n/hr.po
  odoo/addons/base/i18n/fi.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/pl.po
  odoo/addons/base/i18n/pt.po
  odoo/addons/base/i18n/sv.po
Labels: staging.12.0

#15132 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/sale_stock/models/sale_order.py
Labels: tmp.saas-12.3

#15133 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/account/models/account_move.py
  addons/account/wizard/account_resequence.py
  addons/mail/models/mail_render_mixin.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_template.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/menu/edit.js
Labels: tmp.saas-14.4

#15135 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/i18n/hr.po
  addons/account/i18n/pt.po
  addons/account/i18n/sv.po
  addons/account_bank_statement_import/i18n/hr.po
  addons/analytic/i18n/sv.po
  addons/barcodes/i18n/sv.po
  addons/base_iban/i18n/pt_BR.po
  addons/base_setup/i18n/fi.po
  addons/crm/i18n/hr.po
  addons/crm_reveal/i18n/hr.po
  addons/delivery/i18n/hr.po
  addons/delivery/i18n/sv.po
  addons/google_calendar/i18n/hr.po
  addons/hr_holidays/i18n/sv.po
  addons/hr_timesheet/i18n/sv.po
  addons/mail/i18n/fi.po
  addons/mail/i18n/hu.po
  addons/membership/i18n/hu.po
  addons/mrp/i18n/hr.po
  addons/mrp/i18n/sv.po
  addons/mrp_bom_cost/i18n/ro.po
  addons/payment_stripe/i18n/fi.po
  addons/payment_stripe_checkout_webhook/i18n/fi.po
  addons/point_of_sale/i18n/hr.po
  addons/point_of_sale/i18n/sv.po
  addons/portal/i18n/hu.po
  addons/pos_restaurant/i18n/de.po
  addons/pos_restaurant/i18n/hr.po
  addons/product/i18n/sv.po
  addons/project/i18n/hr.po
  addons/purchase/i18n/sv.po
  addons/purchase_requisition/i18n/sv.po
  addons/rating/i18n/hu.po
  addons/sale/i18n/hr.po
  addons/sale/i18n/sv.po
  addons/sale_purchase/i18n/sv.po
  addons/sale_timesheet/i18n/sv.po
  addons/stock/i18n/hr.po
  addons/stock/i18n/sv.po
  addons/stock_account/i18n/hr.po
  addons/stock_account/i18n/sv.po
  addons/stock_picking_batch/i18n/sv.po
  addons/stock_zebra/i18n/sv.po
  addons/survey/i18n/fi.po
  addons/website_membership/i18n/hu.po
  addons/website_sale/i18n/hr.po
  odoo/addons/base/i18n/fi.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/pl.po
  odoo/addons/base/i18n/pt.po
  odoo/addons/base/i18n/sv.po
Labels: tmp.12.0

#15138 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/stock/static/src/scss/stock_traceability_report.scss
Labels: 13.0

#15139 Syncing from upstream odoo/odoo (14.0)
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock/models/stock_move.py
  addons/website/models/res_config_settings.py
  addons/website/tests/__init__.py
  addons/website/tests/test_auth_signup_uninvited.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
Labels: 14.0

#15141 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account_edi/models/account_move.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_mail_composer.py
  addons/l10n_es_edi_sii/__init__.py
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/data/account_edi_data.xml
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/data/res_partner_data.xml
  addons/l10n_es_edi_sii/demo/certificates/sello_entidad_act.p12
  addons/l10n_es_edi_sii/demo/demo_company.xml
  addons/l10n_es_edi_sii/models/__init__.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_move.py
  addons/l10n_es_edi_sii/models/account_tax.py
  addons/l10n_es_edi_sii/models/l10n_es_edi_certificate.py
  addons/l10n_es_edi_sii/models/res_company.py
  addons/l10n_es_edi_sii/models/res_config_settings.py
  addons/l10n_es_edi_sii/security/ir.model.access.csv
  addons/l10n_es_edi_sii/tests/__init__.py
  addons/l10n_es_edi_sii/tests/common.py
  addons/l10n_es_edi_sii/tests/test_edi_web_services.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_es_edi_sii/views/account_tax_views.xml
  addons/l10n_es_edi_sii/views/l10n_es_edi_certificate_views.xml
  addons/l10n_es_edi_sii/views/res_config_settings_views.xml
  addons/l10n_pe/data/account.account.template.csv
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_full_composer.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/controllers/main.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/snailmail/wizard/snailmail_letter_missing_required_fields_views.xml
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/models/__init__.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  odoo/addons/base/wizard/base_partner_merge.py
Labels: saas-14.4

#15144 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/account_edi/models/account_move.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_mail_composer.py
  addons/l10n_es_edi_sii/__init__.py
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/data/account_edi_data.xml
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/data/res_partner_data.xml
  addons/l10n_es_edi_sii/demo/certificates/sello_entidad_act.p12
  addons/l10n_es_edi_sii/demo/demo_company.xml
  addons/l10n_es_edi_sii/models/__init__.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_move.py
  addons/l10n_es_edi_sii/models/account_tax.py
  addons/l10n_es_edi_sii/models/l10n_es_edi_certificate.py
  addons/l10n_es_edi_sii/models/res_company.py
  addons/l10n_es_edi_sii/models/res_config_settings.py
  addons/l10n_es_edi_sii/security/ir.model.access.csv
  addons/l10n_es_edi_sii/tests/__init__.py
  addons/l10n_es_edi_sii/tests/common.py
  addons/l10n_es_edi_sii/tests/test_edi_web_services.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_es_edi_sii/views/account_tax_views.xml
  addons/l10n_es_edi_sii/views/l10n_es_edi_certificate_views.xml
  addons/l10n_es_edi_sii/views/res_config_settings_views.xml
  addons/l10n_pe/data/account.account.template.csv
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_full_composer.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/controllers/main.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/snailmail/wizard/snailmail_letter_missing_required_fields_views.xml
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/models/__init__.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  odoo/addons/base/wizard/base_partner_merge.py
Labels: staging.saas-14.4

#15146 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/stock/static/src/scss/stock_traceability_report.scss
Labels: staging.13.0

#15149 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/account_edi/models/account_move.py
  addons/base_automation/tests/__init__.py
  addons/base_automation/tests/test_mail_composer.py
  addons/l10n_es_edi_sii/__init__.py
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/data/account_edi_data.xml
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/data/res_partner_data.xml
  addons/l10n_es_edi_sii/demo/certificates/sello_entidad_act.p12
  addons/l10n_es_edi_sii/demo/demo_company.xml
  addons/l10n_es_edi_sii/models/__init__.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_move.py
  addons/l10n_es_edi_sii/models/account_tax.py
  addons/l10n_es_edi_sii/models/l10n_es_edi_certificate.py
  addons/l10n_es_edi_sii/models/res_company.py
  addons/l10n_es_edi_sii/models/res_config_settings.py
  addons/l10n_es_edi_sii/security/ir.model.access.csv
  addons/l10n_es_edi_sii/tests/__init__.py
  addons/l10n_es_edi_sii/tests/common.py
  addons/l10n_es_edi_sii/tests/test_edi_web_services.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_es_edi_sii/views/account_tax_views.xml
  addons/l10n_es_edi_sii/views/l10n_es_edi_certificate_views.xml
  addons/l10n_es_edi_sii/views/res_config_settings_views.xml
  addons/l10n_pe/data/account.account.template.csv
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mail/tests/test_mail_full_composer.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/controllers/main.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/snailmail/wizard/snailmail_letter_missing_required_fields_views.xml
  addons/snailmail_account/tests/test_pingen_send.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/models/__init__.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  odoo/addons/base/wizard/base_partner_merge.py
Labels: tmp.saas-14.4

#15151 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/stock/static/src/scss/stock_traceability_report.scss
Labels: tmp.13.0

#15153 Syncing from upstream odoo/odoo (12.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
Labels: 12.0

#15154 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/mrp/models/stock_picking.py
  addons/product/models/product.py
  addons/purchase_stock/models/stock_rule.py
  addons/stock/models/res_config_settings.py
Labels: 13.0

#15155 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/mass_mailing/models/utm.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/product_expiry/wizard/confirm_expiry.py
  addons/product_margin/models/product_product.py
  addons/survey/models/survey_question.py
  addons/survey/models/survey_user.py
  addons/survey/static/src/js/survey_result.js
  addons/survey/tests/common.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_statistics.xml
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 14.0

#15157 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
Labels: saas-12.3

#15158 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/google_recaptcha/models/ir_http.py
  addons/hr_contract/models/hr_contract.py
  addons/mass_mailing/models/utm.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/survey/models/survey_question.py
  addons/survey/models/survey_user.py
  addons/survey/static/src/js/survey_result.js
  addons/survey/tests/common.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_statistics.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/res_config_settings.py
  addons/website/tests/__init__.py
  addons/website/tests/test_auth_signup_uninvited.py
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: saas-14.4

#15161 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
Labels: staging.saas-12.3

#15162 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/google_recaptcha/models/ir_http.py
  addons/hr_contract/models/hr_contract.py
  addons/mass_mailing/models/utm.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/survey/models/survey_question.py
  addons/survey/models/survey_user.py
  addons/survey/static/src/js/survey_result.js
  addons/survey/tests/common.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_statistics.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/res_config_settings.py
  addons/website/tests/__init__.py
  addons/website/tests/test_auth_signup_uninvited.py
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: staging.saas-14.4

#15164 Syncing from upstream odoo/odoo (staging.12.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
Labels: staging.12.0

#15165 Syncing from upstream odoo/odoo (staging.13.0)
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/mrp/models/stock_picking.py
  addons/product/models/product.py
  addons/purchase_stock/models/stock_rule.py
  addons/stock/models/res_config_settings.py
Labels: staging.13.0

#15167 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
Labels: tmp.saas-12.3

#15168 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/google_recaptcha/models/ir_http.py
  addons/hr_contract/models/hr_contract.py
  addons/mass_mailing/models/utm.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/survey/models/survey_question.py
  addons/survey/models/survey_user.py
  addons/survey/static/src/js/survey_result.js
  addons/survey/tests/common.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_statistics.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/res_config_settings.py
  addons/website/tests/__init__.py
  addons/website/tests/test_auth_signup_uninvited.py
  addons/website_sale/static/tests/tours/website_sale_buy.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: tmp.saas-14.4

#15170 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
Labels: tmp.12.0

#15171 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/mrp/models/stock_picking.py
  addons/product/models/product.py
  addons/purchase_stock/models/stock_rule.py
  addons/stock/models/res_config_settings.py
Labels: tmp.13.0

#15176 Syncing from upstream odoo/odoo (saas-14.4)
  addons/l10n_ar/data/res.country.csv
  addons/product_expiry/wizard/confirm_expiry.py
  addons/product_margin/models/product_product.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
Labels: saas-14.4

#15177 Syncing from upstream odoo/odoo (saas-14.5)
  addons/l10n_ar/data/res.country.csv
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/mail/__manifest__.py
  addons/mail/models/mail_channel_partner.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/ControlButtons/InvoiceButton.js
  addons/point_of_sale/static/src/js/utils.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderFetcher.js
  addons/pos_sale/static/src/js/SetSaleOrderButton.js
  addons/product_expiry/wizard/confirm_expiry.py
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
Labels: saas-14.5

#15179 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/l10n_ar/data/res.country.csv
  addons/product_expiry/wizard/confirm_expiry.py
  addons/product_margin/models/product_product.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
Labels: staging.saas-14.4

#15181 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/ir_actions_report.py
  addons/l10n_ar/data/res.country.csv
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/stock/views/stock_scrap_views.xml
Labels: staging.13.0

#15183 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/l10n_ar/data/res.country.csv
  addons/product_expiry/wizard/confirm_expiry.py
  addons/product_margin/models/product_product.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
Labels: tmp.saas-14.4

#15185 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/ir_actions_report.py
  addons/l10n_ar/data/res.country.csv
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/stock/views/stock_scrap_views.xml
Labels: tmp.13.0

#15187 Syncing from upstream odoo/odoo (12.0)
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
Labels: 12.0

#15188 Syncing from upstream odoo/odoo (13.0)
  addons/payment_authorize/models/authorize_request.py
Labels: 13.0

#15189 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/account_payment_register.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/payment/models/account_payment.py
  addons/payment_fix_register_token/models/account_payment_register.py
  addons/payment_fix_register_token/tests/__init__.py
  addons/payment_fix_register_token/tests/test_account_payment_register.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/stock/views/stock_scrap_views.xml
  doc/cla/individual/AlfaFza.md
  doc/cla/individual/innovara.md
  odoo/addons/base/data/res.lang.csv
Labels: 14.0

#15190 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/crm/tests/test_crm_lead_assignment.py
  addons/mail/__manifest__.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_channel_partner.py
  addons/mail/static/tests/m2x_avatar_user_tests.js
  addons/mail/static/tests/webclient/commands/mail_providers_tests.js
  addons/mrp/models/stock_move.py
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/commands/command_service.js
  addons/web/static/src/webclient/user_menu/user_menu_items.xml
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/webclient/commands/command_service_tests.js
  addons/web/static/tests/webclient/commands/menu_provider_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
Labels: master

#15191 Syncing from upstream odoo/odoo (saas-14.4)
  addons/account/models/account_move.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/edit_translated_page.js
  addons/website/tests/test_ui.py
Labels: saas-14.4

#15192 Syncing from upstream odoo/odoo (saas-14.5)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/crm/tests/test_crm_lead_assignment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/mail/models/mail_alias.py
  addons/mail/static/tests/webclient/commands/mail_providers_tests.js
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/views/pos_assets_index.xml
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/project/__manifest__.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/stock/views/stock_scrap_views.xml
  addons/web/static/src/core/commands/command_category.js
  addons/web/static/src/core/commands/command_hook.js
  addons/web/static/src/core/commands/command_palette.js
  addons/web/static/src/core/commands/command_palette.scss
  addons/web/static/src/core/commands/command_palette.xml
  addons/web/static/src/core/commands/command_palette_dialog.js
  addons/web/static/src/core/commands/command_palette_dialog.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/commands/default_providers.js
  addons/web/static/src/core/debug/debug_menu.js
  addons/web/static/src/core/utils/concurrency.js
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/src/views/pivot/pivot_model.js
  addons/web/static/src/webclient/menus/menu_helpers.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/commands/command_service_tests.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/core/utils/concurrency_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/webclient/helpers.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web/static/tests/webclient/webclient_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/components/configurator/configurator.xml
  addons/website/static/src/js/menu/debug_menu.js
  addons/website/static/src/scss/configurator.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_form_project/static/src/js/website_form_project_editor.js
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/views/ir_model_views.xml
Labels: saas-14.5

#15194 Syncing from upstream odoo/odoo (staging.saas-14.4)
  addons/account/models/account_move.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/edit_translated_page.js
  addons/website/tests/test_ui.py
Labels: staging.saas-14.4

#15195 Syncing from upstream odoo/odoo (staging.saas-14.5)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/crm/tests/test_crm_lead_assignment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/mail/models/mail_alias.py
  addons/mail/static/tests/webclient/commands/mail_providers_tests.js
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/views/pos_assets_index.xml
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/project/__manifest__.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/stock/views/stock_scrap_views.xml
  addons/web/static/src/core/commands/command_category.js
  addons/web/static/src/core/commands/command_hook.js
  addons/web/static/src/core/commands/command_palette.js
  addons/web/static/src/core/commands/command_palette.scss
  addons/web/static/src/core/commands/command_palette.xml
  addons/web/static/src/core/commands/command_palette_dialog.js
  addons/web/static/src/core/commands/command_palette_dialog.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/commands/default_providers.js
  addons/web/static/src/core/debug/debug_menu.js
  addons/web/static/src/core/utils/concurrency.js
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/src/views/pivot/pivot_model.js
  addons/web/static/src/webclient/menus/menu_helpers.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/commands/command_service_tests.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/core/utils/concurrency_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/webclient/helpers.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web/static/tests/webclient/webclient_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/components/configurator/configurator.xml
  addons/website/static/src/js/menu/debug_menu.js
  addons/website/static/src/scss/configurator.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_form_project/static/src/js/website_form_project_editor.js
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/views/ir_model_views.xml
Labels: staging.saas-14.5

#15196 Syncing from upstream odoo/odoo (staging.12.0)
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
Labels: staging.12.0

#15197 Syncing from upstream odoo/odoo (staging.13.0)
  addons/payment_authorize/models/authorize_request.py
Labels: staging.13.0

#15199 Syncing from upstream odoo/odoo (tmp.saas-14.4)
  addons/account/models/account_move.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/edit_translated_page.js
  addons/website/tests/test_ui.py
Labels: tmp.saas-14.4

#15200 Syncing from upstream odoo/odoo (tmp.saas-14.5)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/crm/tests/test_crm_lead_assignment.py
  addons/l10n_cl/demo/demo_company.xml
  addons/l10n_cl/models/res_partner.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/mail/models/mail_alias.py
  addons/mail/static/tests/webclient/commands/mail_providers_tests.js
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/views/pos_assets_index.xml
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/project/__manifest__.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/stock/views/stock_scrap_views.xml
  addons/web/static/src/core/commands/command_category.js
  addons/web/static/src/core/commands/command_hook.js
  addons/web/static/src/core/commands/command_palette.js
  addons/web/static/src/core/commands/command_palette.scss
  addons/web/static/src/core/commands/command_palette.xml
  addons/web/static/src/core/commands/command_palette_dialog.js
  addons/web/static/src/core/commands/command_palette_dialog.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/commands/default_providers.js
  addons/web/static/src/core/debug/debug_menu.js
  addons/web/static/src/core/utils/concurrency.js
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/src/views/pivot/pivot_model.js
  addons/web/static/src/webclient/menus/menu_helpers.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/commands/command_service_tests.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/core/utils/concurrency_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/webclient/helpers.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web/static/tests/webclient/webclient_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/components/configurator/configurator.xml
  addons/website/static/src/js/menu/debug_menu.js
  addons/website/static/src/scss/configurator.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_form_project/static/src/js/website_form_project_editor.js
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/views/ir_model_views.xml
Labels: tmp.saas-14.5

#15201 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
Labels: tmp.12.0

#15202 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/payment_authorize/models/authorize_request.py
Labels: tmp.13.0

#15205 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/mail/static/tests/webclient/commands/mail_providers_tests.js
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/views/pos_assets_index.xml
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/project/__manifest__.py
  addons/sale/models/payment_transaction.py
  addons/sale/tests/test_payment_flow.py
  addons/web/static/src/core/commands/command_category.js
  addons/web/static/src/core/commands/command_hook.js
  addons/web/static/src/core/commands/command_palette.js
  addons/web/static/src/core/commands/command_palette.scss
  addons/web/static/src/core/commands/command_palette.xml
  addons/web/static/src/core/commands/command_palette_dialog.js
  addons/web/static/src/core/commands/command_palette_dialog.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/commands/default_providers.js
  addons/web/static/src/core/debug/debug_menu.js
  addons/web/static/src/core/utils/concurrency.js
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/src/views/pivot/pivot_model.js
  addons/web/static/src/webclient/menus/menu_helpers.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/commands/command_service_tests.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/core/utils/concurrency_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/webclient/helpers.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web/static/tests/webclient/webclient_tests.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/menu/debug_menu.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_forum/models/forum.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/views/ir_model_views.xml
Labels: master

#15215 Syncing from upstream odoo/odoo (12.0)
  doc/cla/corporate/layline-tech.md
  odoo/addons/base/models/res_currency.py
  odoo/tools/mimetypes.py
Labels: 12.0

#15216 Syncing from upstream odoo/odoo (13.0)
  addons/hr_org_chart/i18n/hr_org_chart.pot
  addons/hr_org_chart/static/src/js/hr_org_chart.js
  addons/hr_org_chart/static/src/xml/hr_org_chart.xml
  addons/mail/static/src/js/form_renderer.js
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  addons/web/static/src/js/views/form/form_view.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/layline-tech.md
  odoo/addons/base/models/res_currency.py
Labels: 13.0

#15217 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/ir_actions_report.py
  addons/l10n_in/models/account_invoice.py
  addons/mrp/models/stock_picking.py
  addons/payment_authorize/models/authorize_request.py
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  doc/cla/corporate/layline-tech.md
  odoo/modules/loading.py
Labels: 14.0

#15219 Syncing from upstream odoo/odoo (saas-12.3)
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  doc/cla/corporate/layline-tech.md
  odoo/addons/base/models/res_currency.py
Labels: saas-12.3

#15221 Syncing from upstream odoo/odoo (saas-14.5)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/crm/__manifest__.py
  addons/crm/static/src/js/forecast/forecast_model_extension.js
  addons/crm/static/src/js/forecast/forecast_search_model.js
  addons/crm/static/src/js/forecast/forecast_views.js
  addons/crm/static/tests/forecast_view_tests.js
  addons/hr_contract/models/hr_contract.py
  addons/mail/models/mail_channel_partner.py
  addons/mail/static/src/models/thread/thread.js
  addons/mrp/models/stock_picking.py
  addons/payment_authorize/models/authorize_request.py
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  addons/stock_picking_batch/views/stock_picking_batch_views.xml
  addons/web/static/src/core/debug/profiling/profiling_qweb_view.js
  addons/web/static/src/legacy/backend_utils.js
  addons/web/static/src/legacy/js/core/debug/profiling/profiling_qweb_view.js
  addons/web/static/src/legacy/js/core/debug/profiling/profiling_qweb_view.scss
  addons/web/static/src/search/search_model.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_tour/models/ir_http.py
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/tests/tours/edit_translated_page.js
  addons/website/tests/test_ui.py
  addons/website/views/snippets/snippets.xml
  doc/cla/corporate/layline-tech.md
  doc/cla/individual/AlfaFza.md
  doc/cla/individual/innovara.md
  odoo/addons/base/data/res.lang.csv
Labels: saas-14.5

#15223 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  doc/cla/corporate/layline-tech.md
  odoo/addons/base/models/res_currency.py
Labels: staging.saas-12.3

#15225 Syncing from upstream odoo/odoo (staging.saas-14.5)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/crm/__manifest__.py
  addons/crm/static/src/js/forecast/forecast_model_extension.js
  addons/crm/static/src/js/forecast/forecast_search_model.js
  addons/crm/static/src/js/forecast/forecast_views.js
  addons/crm/static/tests/forecast_view_tests.js
  addons/hr_contract/models/hr_contract.py
  addons/mail/models/mail_channel_partner.py
  addons/mail/static/src/models/thread/thread.js
  addons/mrp/models/stock_picking.py
  addons/payment_authorize/models/authorize_request.py
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  addons/stock_picking_batch/views/stock_picking_batch_views.xml
  addons/web/static/src/core/debug/profiling/profiling_qweb_view.js
  addons/web/static/src/legacy/backend_utils.js
  addons/web/static/src/legacy/js/core/debug/profiling/profiling_qweb_view.js
  addons/web/static/src/legacy/js/core/debug/profiling/profiling_qweb_view.scss
  addons/web/static/src/search/search_model.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_tour/models/ir_http.py
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/tests/tours/edit_translated_page.js
  addons/website/tests/test_ui.py
  addons/website/views/snippets/snippets.xml
  doc/cla/corporate/layline-tech.md
  doc/cla/individual/AlfaFza.md
  doc/cla/individual/innovara.md
  odoo/addons/base/data/res.lang.csv
Labels: staging.saas-14.5

#15229 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  doc/cla/corporate/layline-tech.md
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-12.3

#15231 Syncing from upstream odoo/odoo (tmp.saas-14.5)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/crm/__manifest__.py
  addons/crm/static/src/js/forecast/forecast_model_extension.js
  addons/crm/static/src/js/forecast/forecast_search_model.js
  addons/crm/static/src/js/forecast/forecast_views.js
  addons/crm/static/tests/forecast_view_tests.js
  addons/hr_contract/models/hr_contract.py
  addons/mail/models/mail_channel_partner.py
  addons/mail/static/src/models/thread/thread.js
  addons/mrp/models/stock_picking.py
  addons/payment_authorize/models/authorize_request.py
  addons/sale_quotation_builder/i18n/sale_quotation_builder.pot
  addons/sale_quotation_builder/views/sale_portal_templates.xml
  addons/stock_picking_batch/views/stock_picking_batch_views.xml
  addons/web/static/src/core/debug/profiling/profiling_qweb_view.js
  addons/web/static/src/legacy/backend_utils.js
  addons/web/static/src/legacy/js/core/debug/profiling/profiling_qweb_view.js
  addons/web/static/src/legacy/js/core/debug/profiling/profiling_qweb_view.scss
  addons/web/static/src/search/search_model.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_tour/models/ir_http.py
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/tests/tours/edit_translated_page.js
  addons/website/tests/test_ui.py
  addons/website/views/snippets/snippets.xml
  doc/cla/corporate/layline-tech.md
  doc/cla/individual/AlfaFza.md
  doc/cla/individual/innovara.md
  odoo/addons/base/data/res.lang.csv
Labels: tmp.saas-14.5

#15235 Syncing from upstream odoo/odoo (13.0)
  odoo/tools/mimetypes.py
Labels: 13.0

#15236 Syncing from upstream odoo/odoo (14.0)
  addons/hr_org_chart/i18n/hr_org_chart.pot
  addons/hr_org_chart/static/src/js/hr_org_chart.js
  addons/hr_org_chart/static/src/xml/hr_org_chart.xml
  addons/l10n_pe/data/l10n_latam_identification_type_data.xml
  addons/mrp/models/stock_orderpoint.py
  addons/mrp/models/stock_rule.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/website/static/src/js/content/snippets.animation.js
Labels: 14.0
