Repository brain-tec/odoo, pull requests merged in 2022-08, with the labels that each got.

#17201 Syncing from upstream odoo/odoo (master)
  addons/l10n_gcc_invoice_stock_account/__init__.py
  addons/l10n_gcc_invoice_stock_account/__manifest__.py
  addons/l10n_gcc_invoice_stock_account/views/report_invoice.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/__init__.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
Labels: master

#17202 Syncing from upstream odoo/odoo (13.0)
  addons/google_drive/models/google_drive.py
  addons/l10n_in/views/res_partner_views.xml
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock_dropshipping/models/res_company.py
  addons/website_sale_stock/models/sale_order.py
Labels: 13.0

#17203 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/google_drive/models/google_drive.py
  addons/l10n_de_sale/i18n/l10n_de_sale.pot
  addons/l10n_de_sale/models/sale.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/sale/report/sale_report_templates.xml
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_dropshipping/models/res_company.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_sale_stock/models/sale_order.py
Labels: 14.0

#17204 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/l10n_fi/data/l10n_fi_chart_post_data.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mass_mailing/static/src/js/mailing_mailing_view_form_full_width.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment/views/payment_portal_templates.xml
  addons/pos_coupon/models/pos_config.py
  addons/product/i18n/product.pot
  addons/product/wizard/product_label_layout.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/stock_dropshipping/models/res_company.py
  addons/web/static/src/legacy/js/fields/field_utils.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/urlRegex.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  addons/website_sale_stock/models/sale_order.py
Labels: 15.0

#17206 Syncing from upstream odoo/odoo (15.0)
  addons/mass_mailing/static/src/js/mass_mailing_snippets.js
  addons/web/static/src/core/utils/hooks.js
  addons/web/static/tests/core/utils/hooks_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
Labels: 15.0

#17208 Syncing from upstream odoo/odoo (13.0)
  addons/account_bank_statement_import/account_bank_statement_import.py
  addons/l10n_be/data/account_data.xml
  addons/sale_stock/models/account_move.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/field_utils_tests.js
Labels: 13.0

#17209 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_be/data/account_data.xml
  addons/web/static/src/js/components/datepicker.js
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/website/static/src/scss/website.scss
  odoo/addons/base/models/ir_ui_view.py
Labels: 14.0

#17210 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_bg/__init__.py
  addons/l10n_bg/__manifest__.py
  addons/l10n_bg/data/account.account.template.csv
  addons/l10n_bg/data/account.group.template.csv
  addons/l10n_bg/data/account_chart_template_configure_data.xml
  addons/l10n_bg/data/account_chart_template_data.xml
  addons/l10n_bg/data/account_fiscal_position_template.xml
  addons/l10n_bg/data/account_tax_group_data.xml
  addons/l10n_bg/data/account_tax_template_data.xml
  addons/l10n_bg/data/l10n_bg_chart_data.xml
  addons/l10n_bg/data/menuitem.xml
  addons/l10n_bg/data/tax_report.xml
  addons/l10n_bg/demo/demo_company.xml
  addons/l10n_bg/i18n/bg.po
  addons/l10n_bg/i18n/l10n_bg.pot
  addons/l10n_bg/static/description/icon.png
  addons/l10n_bg/static/description/icon.svg
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/Orderline.xml
  addons/product/models/product.py
  addons/product/tests/test_variants.py
  addons/project/models/project.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_move.py
  addons/web/static/src/legacy/js/fields/field_utils.js
  addons/web/static/tests/legacy/fields/field_utils_tests.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website_event_track/controllers/event_track.py
  addons/website_event_track/views/event_track_templates_agenda.xml
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_ui_view.py
Labels: 15.0

#17212 Syncing from upstream odoo/odoo (13.0)
  addons/google_gmail/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/website_twitter/views/res_config_settings_views.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/viindoo.md
Labels: 13.0

#17213 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account_qr_code_sepa/tests/test_sepa_qr.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/purchase_stock/models/purchase.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  doc/cla/corporate/viindoo.md
Labels: 14.0

#17214 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_document.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/point_of_sale/models/pos_session.py
  addons/purchase_stock/models/purchase.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock/models/stock_move.py
  addons/test_website/models/__init__.py
  addons/test_website/models/model.py
  addons/test_website/models/website.py
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_fuzzy.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/legacy/js/components/datepicker.js
  addons/website/i18n/website.pot
  addons/website/models/mixins.py
  addons/website/models/website.py
  addons/website/static/src/snippets/s_website_form/options.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
  doc/cla/corporate/viindoo.md
  doc/cla/individual/sang-sakarin.md
Labels: 15.0

#17215 Syncing from upstream odoo/odoo (master)
  addons/bus/static/tests/helpers/mock_server.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_timesheet/views/project_portal_templates.xml
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/static/tests/helpers/webclient_setup.js
  addons/mail/static/tests/qunit_suite_tests/chatter_tests.js
  addons/project/__manifest__.py
  addons/project/models/project.py
  addons/project/security/ir.model.access.csv
  addons/project/tests/test_project_base.py
  addons/project/views/project_portal_templates.xml
  addons/project/views/project_views.xml
  addons/project/views/res_config_settings_views.xml
  addons/project/wizard/__init__.py
  addons/project/wizard/project_delete_wizard.py
  addons/project/wizard/project_delete_wizard_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/static/src/xml/project_templates.xml
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_palette.js
  addons/web/static/src/core/commands/command_palette.scss
  addons/web/static/src/core/commands/command_palette.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/tooltip/tooltip.scss
  addons/web/static/src/core/utils/hooks.js
  addons/web/static/src/legacy/js/fields/field_utils.js
  addons/web/static/src/views/fields/field_tooltip.xml
  addons/web/static/src/views/form/form_label.js
  addons/web/static/src/webclient/menus/menu_command_item.xml
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/command_palette_tests.js
  addons/web/static/tests/core/commands/command_service_tests.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/core/utils/hooks_tests.js
  addons/web/static/tests/legacy/fields/field_utils_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/helpers.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/models/website.py
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/tests/common.py
  odoo/tests/runner.py
Labels: master

#17218 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/he.po
  addons/account/i18n/ja.po
  addons/account/i18n/pl.po
  addons/account_bank_statement_import/i18n/lt.po
  addons/auth_signup/i18n/he.po
  addons/fetchmail/i18n/he.po
  addons/fetchmail_outlook/i18n/he.po
  addons/fetchmail_outlook/i18n/ja.po
  addons/fetchmail_outlook/i18n/vi.po
  addons/hr_recruitment/i18n/ja.po
  addons/hr_skills/i18n/ja.po
  addons/hr_timesheet/i18n/fa.po
  addons/im_livechat/i18n/ja.po
  addons/mail/controllers/main.py
  addons/mail/i18n/he.po
  addons/mass_mailing/i18n/ja.po
  addons/mass_mailing/i18n/mn.po
  addons/microsoft_outlook/i18n/ja.po
  addons/microsoft_outlook/i18n/vi.po
  addons/mrp/i18n/ja.po
  addons/mrp/i18n/zh_CN.po
  addons/payment/i18n/es.po
  addons/point_of_sale/i18n/es.po
  addons/point_of_sale/i18n/pl.po
  addons/pos_epson_printer/i18n/ja.po
  addons/pos_epson_printer_restaurant/i18n/ja.po
  addons/pos_restaurant/i18n/ja.po
  addons/product/i18n/ar.po
  addons/product/i18n/ca.po
  addons/product/i18n/de.po
  addons/product/i18n/es.po
  addons/product/i18n/fa.po
  addons/product/i18n/he.po
  addons/product/i18n/it.po
  addons/product/i18n/nl.po
  addons/product/i18n/tr.po
  addons/product/i18n/uk.po
  addons/product/i18n/zh_CN.po
  addons/project/i18n/ja.po
  addons/purchase/i18n/es.po
  addons/rating/i18n/ja.po
  addons/sale/i18n/ar.po
  addons/sale/i18n/es.po
  addons/sale_coupon/i18n/es.po
  addons/sale_stock/i18n/ru.po
  addons/sms/i18n/he.po
  addons/stock/i18n/he.po
  addons/stock_account/i18n/ja.po
  addons/stock_account/i18n/ru.po
  addons/stock_picking_batch/i18n/ru.po
  addons/survey/i18n/zh_CN.po
  addons/web/i18n/fa.po
  addons/web_editor/i18n/es.po
  addons/web_editor/i18n/vi.po
  addons/website/i18n/ja.po
  addons/website_blog/controllers/main.py
  addons/website_sale/i18n/ja.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/ja.po
Labels: 13.0

#17219 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/data/cron.xml
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/google_gmail/views/res_config_settings_views.xml
  addons/hr_recruitment_survey/__init__.py
  addons/hr_recruitment_survey/controllers/__init__.py
  addons/hr_recruitment_survey/controllers/main.py
  addons/mail/controllers/main.py
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/mrp/__init__.py
  addons/sale_stock/models/account_move.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website_twitter/views/res_config_settings_views.xml
Labels: 14.0

#17220 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account_qr_code_sepa/tests/test_sepa_qr.py
  addons/calendar_sms/models/calendar_event.py
  addons/delivery_mondialrelay/models/delivery_carrier.py
  addons/google_gmail/views/res_config_settings_views.xml
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_contract/report/hr_contract_history_report_views.xml
  addons/l10n_be/data/account_tax_group_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/sale_stock/models/account_move.py
  addons/website_event_track/controllers/event_track.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_twitter/views/res_config_settings_views.xml
  doc/cla/corporate/nitrokey.md
  doc/cla/individual/angelmoya.md
Labels: 15.0

#17223 Syncing from upstream odoo/odoo (14.0)
  addons/sms/wizard/sms_composer.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/field_utils_tests.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: 14.0

#17226 [t130552] Extend account.move 'posted' status to include 'posted_sent'
  addons/account/models/account.py
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/models/company.py
  addons/account/models/digest.py
  addons/account/models/ir_actions_report.py
  addons/account/models/partner.py
  addons/account/models/reconciliation_widget.py
  addons/account/report/account_aged_partner_balance.py
  addons/account/report/account_journal.py
  addons/account/views/account_portal_templates.xml
  addons/account/views/account_report.xml
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_accrual_accounting.py
  addons/account/wizard/account_move_reversal.py
Labels: 13.0.project_sv_559

#17227 Syncing from upstream odoo/odoo (13.0)
  addons/website/models/website.py
  addons/website_event/static/src/scss/website_event.scss
Labels: 13.0

#17228 Syncing from upstream odoo/odoo (14.0)
  addons/website/models/website.py
  doc/cla/corporate/mainframemonkey.md
Labels: 14.0

#17229 Syncing from upstream odoo/odoo (15.0)
  addons/mail/models/mail_message.py
  addons/mail/models/res_users.py
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mail/tests/test_mail_channel.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/report/mrp_production_templates.xml
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_move_line.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail_full/tests/test_sms_composer.py
  doc/cla/corporate/mainframemonkey.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: 15.0

#17231 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_latam_invoice_document/views/account_move_view.xml
Labels: 13.0

#17232 Syncing from upstream odoo/odoo (14.0)
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_latam_invoice_document/views/account_move_view.xml
  addons/website_event/static/src/scss/website_event.scss
Labels: 14.0

#17233 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_full_reconcile.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_cl/models/account_move.py
  addons/mrp/__init__.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_coupon/static/src/js/tours/PosCoupon1.tour.js
  addons/pos_coupon/tests/test_frontend.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/test_website/tests/test_fuzzy.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_event/__manifest__.py
  addons/website_event/static/src/snippets/s_country_events_list/000.scss
Labels: 15.0

#17235 Syncing from upstream odoo/odoo (13.0)
  addons/account/views/product_view.xml
Labels: 13.0

#17236 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_ar_website_sale/controllers/main.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mrp/models/stock_move.py
  addons/mrp/views/stock_move_views.xml
  addons/website_blog/controllers/main.py
Labels: 14.0

#17237 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/project.py
  addons/l10n_latam_invoice_document/views/account_move_view.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/stock_move.py
  addons/mrp/views/stock_move_views.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website/static/src/components/configurator/configurator.js
  addons/website_blog/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
Labels: 15.0

#17239 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/fr.po
  addons/account/i18n/he.po
  addons/account/i18n/pl.po
  addons/delivery/i18n/ja.po
  addons/hr_timesheet/i18n/ja.po
  addons/mail/i18n/he.po
  addons/membership/i18n/he.po
  addons/payment/i18n/ca.po
  addons/purchase/i18n/pl.po
  addons/sale/i18n/pl.po
  addons/sale_coupon/i18n/ja.po
  addons/sale_timesheet/i18n/ca.po
  addons/stock/i18n/pl.po
  addons/web/i18n/pl.po
  addons/web_editor/i18n/ru.po
  addons/website_membership/i18n/he.po
  addons/website_slides/i18n/ja.po
  addons/website_slides/i18n/ru.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/fr.po
Labels: 13.0

#17240 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/fr.po
  addons/account/i18n/he.po
  addons/account/i18n/pl.po
  addons/delivery/i18n/ja.po
  addons/event/i18n/ca.po
  addons/hr/i18n/es_MX.po
  addons/hr/i18n/ko.po
  addons/hr_timesheet/i18n/ja.po
  addons/lunch/i18n/tr.po
  addons/mail/i18n/he.po
  addons/mail/i18n/pl.po
  addons/mail_client_extension/i18n/ca.po
  addons/membership/i18n/he.po
  addons/payment/i18n/ca.po
  addons/product/i18n/ja.po
  addons/product/i18n/zh_CN.po
  addons/project/i18n/fa.po
  addons/purchase/i18n/pl.po
  addons/purchase_stock/i18n/pl.po
  addons/sale/i18n/pl.po
  addons/sale_coupon/i18n/ja.po
  addons/sale_timesheet/i18n/ca.po
  addons/sale_timesheet/i18n/ja.po
  addons/stock/i18n/he.po
  addons/stock/i18n/pl.po
  addons/web/i18n/pl.po
  addons/web_editor/i18n/ru.po
  addons/website/i18n/ja.po
  addons/website/i18n/mn.po
  addons/website_event_meet/i18n/he.po
  addons/website_hr_recruitment/i18n/es_MX.po
  addons/website_hr_recruitment/i18n/ko.po
  addons/website_membership/i18n/he.po
  addons/website_slides/i18n/ja.po
  addons/website_slides/i18n/ru.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/fr.po
Labels: 14.0

#17242 Syncing from upstream odoo/odoo (master)
  addons/hr_timesheet/models/project.py
  addons/l10n_ar_website_sale/controllers/main.py
  addons/l10n_latam_invoice_document/views/account_move_view.xml
Labels: master

#17243 Syncing from upstream odoo/odoo (saas-15.1)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/im_livechat/static/src/components/composer/tests/composer_tests.js
  addons/im_livechat/static/src/models/composer_view/composer_view.js
  addons/l10n_ar/models/account_move.py
  addons/mail/static/src/components/composer/composer.xml
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_restaurant/static/src/js/Chrome.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_hr_recruitment/controllers/main.py
Labels: saas-15.1

#17249 Syncing from upstream odoo/odoo (staging.saas-15.1)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/im_livechat/static/src/components/composer/tests/composer_tests.js
  addons/im_livechat/static/src/models/composer_view/composer_view.js
  addons/l10n_ar/models/account_move.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/mail/static/src/components/composer/composer.xml
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_restaurant/static/src/js/Chrome.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_hr_recruitment/controllers/main.py
  doc/cla/individual/TeoGoddet.md
Labels: staging.saas-15.1

#17261 Syncing from upstream odoo/odoo (14.0)
  addons/website_slides/controllers/main.py
Labels: 14.0

#17262 Syncing from upstream odoo/odoo (master)
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_fleet/views/fleet_vehicle_views.xml
Labels: master

#17263 Syncing from upstream odoo/odoo (saas-15.3)
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
Labels: saas-15.3

#17264 Syncing from upstream odoo/odoo (saas-15.4)
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
Labels: saas-15.4

#17268 Syncing from upstream odoo/odoo (staging.saas-15.4)
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mrp/models/stock_move.py
  addons/mrp/views/stock_move_views.xml
Labels: staging.saas-15.4

#17269 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/i18n/fr.po
  addons/account/i18n/he.po
  addons/account/i18n/pl.po
  addons/delivery/i18n/ja.po
  addons/event/i18n/ca.po
  addons/hr/i18n/es_MX.po
  addons/hr/i18n/ko.po
  addons/hr_timesheet/i18n/ja.po
  addons/lunch/i18n/tr.po
  addons/mail/i18n/he.po
  addons/mail/i18n/pl.po
  addons/mail_client_extension/i18n/ca.po
  addons/membership/i18n/he.po
  addons/payment/i18n/ca.po
  addons/product/i18n/ja.po
  addons/product/i18n/zh_CN.po
  addons/project/i18n/fa.po
  addons/purchase/i18n/pl.po
  addons/purchase_stock/i18n/pl.po
  addons/sale/i18n/pl.po
  addons/sale_coupon/i18n/ja.po
  addons/sale_timesheet/i18n/ca.po
  addons/sale_timesheet/i18n/ja.po
  addons/stock/i18n/he.po
  addons/stock/i18n/pl.po
  addons/web/i18n/pl.po
  addons/web_editor/i18n/ru.po
  addons/website/i18n/ja.po
  addons/website/i18n/mn.po
  addons/website_event_meet/i18n/he.po
  addons/website_hr_recruitment/i18n/es_MX.po
  addons/website_hr_recruitment/i18n/ko.po
  addons/website_membership/i18n/he.po
  addons/website_slides/controllers/main.py
  addons/website_slides/i18n/ja.po
  addons/website_slides/i18n/ru.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/fr.po
Labels: staging.14.0

#17274 Syncing from upstream odoo/odoo (tmp.saas-15.4)
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mrp/models/stock_move.py
  addons/mrp/views/stock_move_views.xml
Labels: tmp.saas-15.4

#17278 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/test_mail/tests/test_message_composer.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
Labels: 13.0

#17279 Syncing from upstream odoo/odoo (14.0)
  addons/account/views/product_view.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/xml/Screens/ClientListScreen/ClientDetailsEdit.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
Labels: 14.0

#17280 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/views/product_view.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/tests/test_mail_composer.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/controllers/main.py
  odoo/tools/profiler.py
Labels: 15.0

#17283 Syncing from upstream odoo/odoo (staging.saas-15.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_payment_register.py
  addons/account/views/product_view.xml
  addons/account/wizard/account_payment_register.py
  addons/l10n_cl/models/account_move.py
  addons/mail/wizard/mail_compose_message.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_rating.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/tools/profiler.py
Labels: staging.saas-15.3

#17284 Syncing from upstream odoo/odoo (staging.saas-15.4)
  addons/account/tests/test_account_payment_register.py
  addons/account/views/product_view.xml
  addons/account/wizard/account_payment_register.py
  addons/l10n_cl/models/account_move.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/tools/profiler.py
Labels: staging.saas-15.4

#17285 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/i18n/fr.po
  addons/account/i18n/he.po
  addons/account/i18n/pl.po
  addons/account/models/account_move.py
  addons/delivery/i18n/ja.po
  addons/hr_timesheet/i18n/ja.po
  addons/mail/i18n/he.po
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/membership/i18n/he.po
  addons/payment/i18n/ca.po
  addons/purchase/i18n/pl.po
  addons/sale/i18n/pl.po
  addons/sale_coupon/i18n/ja.po
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_timesheet/i18n/ca.po
  addons/stock/i18n/pl.po
  addons/test_mail/tests/test_message_composer.py
  addons/web/i18n/pl.po
  addons/web_editor/i18n/ru.po
  addons/website_membership/i18n/he.po
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/i18n/ja.po
  addons/website_slides/i18n/ru.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/fr.po
Labels: staging.13.0

#17286 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/views/product_view.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/xml/Screens/ClientListScreen/ClientDetailsEdit.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
Labels: staging.14.0

#17290 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_payment_register.py
  addons/account/views/product_view.xml
  addons/account/wizard/account_payment_register.py
  addons/l10n_cl/models/account_move.py
  addons/mail/wizard/mail_compose_message.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_rating.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/tools/profiler.py
Labels: tmp.saas-15.3

#17291 Syncing from upstream odoo/odoo (tmp.saas-15.4)
  addons/account/tests/test_account_payment_register.py
  addons/account/views/product_view.xml
  addons/account/wizard/account_payment_register.py
  addons/l10n_cl/models/account_move.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/controllers/main.py
  odoo/addons/base/data/res_currency_data.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/tools/profiler.py
Labels: tmp.saas-15.4

#17292 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/i18n/fr.po
  addons/account/i18n/he.po
  addons/account/i18n/pl.po
  addons/account/models/account_move.py
  addons/delivery/i18n/ja.po
  addons/hr_timesheet/i18n/ja.po
  addons/mail/i18n/he.po
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/membership/i18n/he.po
  addons/payment/i18n/ca.po
  addons/purchase/i18n/pl.po
  addons/sale/i18n/pl.po
  addons/sale_coupon/i18n/ja.po
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_timesheet/i18n/ca.po
  addons/stock/i18n/pl.po
  addons/test_mail/tests/test_message_composer.py
  addons/web/i18n/pl.po
  addons/web_editor/i18n/ru.po
  addons/website_membership/i18n/he.po
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/i18n/ja.po
  addons/website_slides/i18n/ru.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/fr.po
Labels: tmp.13.0

#17293 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/views/product_view.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/xml/Screens/ClientListScreen/ClientDetailsEdit.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
Labels: tmp.14.0

#17294 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/account/views/product_view.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/tests/test_mail_composer.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_slides/controllers/main.py
  odoo/tools/profiler.py
Labels: tmp.15.0

#17295 Syncing from upstream odoo/odoo (13.0)
  addons/note/models/note.py
  addons/website/static/src/xml/website.facebook_page.xml
Labels: 13.0

#17296 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
Labels: 14.0

#17297 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_partial_reconcile.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/crm/tests/test_performances.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_event_track/views/event_track_views.xml
  doc/cla/individual/mossaabboudchicha.md
  odoo/addons/base/models/qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: 15.0

#17299 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/note/models/note.py
  addons/payment/models/account_payment.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: 14.0

#17300 Syncing from upstream odoo/odoo (15.0)
  addons/account/demo/account_demo.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_ar/models/account_journal.py
  addons/mrp/views/mrp_production_views.xml
  addons/note/models/note.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/purchase_requisition/tests/common.py
  addons/purchase_requisition_stock/tests/test_purchase_requisition_stock.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_stock_wishlist/views/templates.xml
  odoo/addons/base/models/res_lang.py
Labels: 15.0

#17304 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_partial_reconcile.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_ar/models/account_journal.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/tests/common.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mass_mailing_sms/models/mailing_mailing.py
  addons/mrp/views/mrp_production_views.xml
  addons/note/models/note.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/pos_config_view.xml
  addons/stock/models/stock_move_line.py
  addons/test_mass_mailing/models/__init__.py
  addons/test_mass_mailing/models/mailing_models_cornercase.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_event_track/views/event_track_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale_stock_wishlist/views/templates.xml
  doc/cla/individual/grzana12.md
  doc/cla/individual/mossaabboudchicha.md
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: tmp.saas-15.3

#17305 Syncing from upstream odoo/odoo (tmp.saas-15.4)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_move.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/call_action_list/call_action_list.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mrp/views/mrp_production_views.xml
  addons/note/models/note.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_rating.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_event_track/views/event_track_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  doc/cla/corporate/adhoc.md
  doc/cla/individual/mossaabboudchicha.md
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: tmp.saas-15.4

#17306 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/note/models/note.py
  addons/website/static/src/xml/website.facebook_page.xml
Labels: tmp.13.0

#17307 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/note/models/note.py
  addons/payment/models/account_payment.py
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: tmp.14.0

#17308 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/demo/account_demo.py
  addons/account/models/account_bank_statement.py
  addons/account/models/account_partial_reconcile.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/crm/tests/test_performances.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ar/models/account_journal.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/views/mrp_production_views.xml
  addons/note/models/note.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/views/pos_config_view.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/purchase_requisition/tests/common.py
  addons/purchase_requisition_stock/tests/test_purchase_requisition_stock.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_sms_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_event_track/views/event_track_views.xml
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_stock_wishlist/views/templates.xml
  doc/cla/individual/mossaabboudchicha.md
  odoo/addons/base/models/qweb.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/test_qweb.py
Labels: tmp.15.0

#17309 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/sale/models/account_invoice.py
  addons/sale/models/account_move.py
Labels: 14.0

#17310 Syncing from upstream odoo/odoo (15.0)
  addons/web/static/src/webclient/clickbot/clickbot.js
Labels: 15.0

#17315 Syncing from upstream odoo/odoo (staging.saas-15.4)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/call_action_list/call_action_list.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mrp/views/mrp_production_views.xml
  addons/note/models/note.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_rating.py
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_event_track/views/event_track_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_sale_process.py
  doc/cla/corporate/adhoc.md
  doc/cla/individual/mossaabboudchicha.md
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: staging.saas-15.4

#17316 Syncing from upstream odoo/odoo (staging.13.0)
  addons/note/models/note.py
  addons/website/static/src/xml/website.facebook_page.xml
Labels: staging.13.0

#17317 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/note/models/note.py
  addons/payment/models/account_payment.py
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale/models/account_invoice.py
  addons/sale/models/account_move.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: staging.14.0

#17321 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/web/static/src/webclient/clickbot/clickbot.js
Labels: tmp.saas-15.3

#17322 Syncing from upstream odoo/odoo (tmp.saas-15.4)
  addons/l10n_ar/models/account_journal.py
  addons/web/static/src/webclient/clickbot/clickbot.js
Labels: tmp.saas-15.4

#17323 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/sale/models/account_invoice.py
  addons/sale/models/account_move.py
Labels: tmp.14.0

#17324 Syncing from upstream odoo/odoo (13.0)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_event/static/src/scss/website_event.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
Labels: 13.0

#17325 Syncing from upstream odoo/odoo (14.0)
  addons/survey/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
Labels: 14.0

#17326 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_payment_register.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/xml/Screens/ClientListScreen/ClientDetailsEdit.xml
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/project/tests/__init__.py
  addons/project/tests/test_project_task_type.py
  addons/project/views/project_views.xml
  addons/sale/models/account_move.py
  addons/sale/models/account_move_line.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_move_line.py
  addons/website/views/website_views.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/models/sale_order.py
  addons/website_sale_delivery/static/tests/tours/website_sale_delivery_gift_card.js
  addons/website_sale_delivery/tests/__init__.py
  addons/website_sale_delivery/tests/test_website_sale_delivery.py
  addons/website_sale_gift_card/controllers/gift_card_controller.py
Labels: 15.0

#17327 Syncing from upstream odoo/odoo (master)
  addons/account/demo/account_demo.py
  addons/l10n_sg/__manifest__.py
  addons/l10n_sg/demo/demo_company.xml
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web/static/src/core/hotkeys/hotkey_service.js
  addons/web/static/src/views/fields/field.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.js
  addons/web/static/src/views/view_button/view_button_hook.js
  addons/web/static/tests/core/hotkeys/hotkey_service_tests.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/views/snippets/s_facebook_page.xml
  odoo/addons/base/models/res_lang.py
  odoo/tests/loader.py
Labels: master

#17328 Syncing from upstream odoo/odoo (13.0)
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/website_sale/models/product.py
Labels: 13.0

#17329 Syncing from upstream odoo/odoo (14.0)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  odoo/addons/base/models/ir_model.py
  odoo/tools/misc.py
Labels: 14.0

#17330 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_move.py
  addons/account_edi/views/account_move_views.xml
  addons/mail/models/mail_thread.py
  addons/payment/models/account_payment.py
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/tests/test_click_everywhere.py
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_event_track_quiz/views/event_track_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/qweb.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/tests/test_qweb.py
  odoo/tools/misc.py
Labels: 15.0

#17332 Syncing from upstream odoo/odoo (13.0)
  addons/stock_account/models/account_reconciliation_widget.py
  addons/stock_account/tests/__init__.py
  addons/stock_account/tests/test_reconciliation_widget.py
Labels: 13.0

#17334 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_account_move_reconcile.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_multicompany.py
  addons/hr_timesheet/report/project_report.py
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/payment/views/payment_portal_templates.xml
  addons/payment_transfer/views/payment_transfer_templates.xml
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_website/static/tests/tours/image_link.js
  addons/test_website/tests/test_media.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/snippet_popup_add_remove.js
  addons/website_sale/models/product_template.py
  odoo/addons/base/models/ir_cron.py
  odoo/tests/common.py
  odoo/tools/speedscope.py
Labels: 15.0

#17336 Syncing from upstream odoo/odoo (13.0)
  addons/account/views/account_move_views.xml
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web/static/src/js/public/lazyloader.js
  doc/cla/corporate/blancomartin.md
Labels: 13.0

#17337 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/account_resequence.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/payment_stripe/controllers/main.py
  addons/payment_stripe/static/src/js/payment_processing.js
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web/static/src/js/public/lazyloader.js
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website_event/static/src/scss/website_event.scss
  doc/cla/corporate/blancomartin.md
Labels: 14.0

#17338 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_account_move_reconcile.py
  addons/hr_attendance/models/hr_attendance.py
  addons/l10n_sg/data/account_tax_data.xml
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/project/models/project.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_mrp/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website_event/static/src/scss/event_templates_list.scss
  doc/cla/corporate/blancomartin.md
Labels: 15.0

#17340 Syncing from upstream odoo/odoo (13.0)
  addons/stock/views/stock_quant_views.xml
Labels: 13.0

#17348 Syncing from upstream odoo/odoo (staging.saas-15.4)
  addons/account/demo/account_demo.py
  addons/account/models/account_full_reconcile.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_payment_register.py
  addons/account_edi/models/account_move.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/hr/wizard/hr_departure_wizard.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_fleet/wizard/hr_departure_wizard.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/payment/models/account_payment.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerDetailsEdit.js
  addons/point_of_sale/static/src/xml/Screens/PartnerListScreen/PartnerDetailsEdit.xml
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale/models/account_move.py
  addons/sale/models/account_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web/controllers/binary.py
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/tests/test_click_everywhere.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/views/website_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/models/sale_order.py
  addons/website_sale_delivery/static/tests/tours/website_sale_delivery_gift_card.js
  addons/website_sale_delivery/tests/__init__.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_delivery/tests/test_website_sale_delivery.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/test_http/tests/test_static.py
  odoo/tools/misc.py
Labels: staging.saas-15.4

#17357 Syncing from upstream odoo/odoo (tmp.saas-15.4)
  addons/account/demo/account_demo.py
  addons/account/models/account_full_reconcile.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_payment_register.py
  addons/account_edi/models/account_move.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/hr/wizard/hr_departure_wizard.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_fleet/wizard/hr_departure_wizard.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/payment/models/account_payment.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerDetailsEdit.js
  addons/point_of_sale/static/src/xml/Screens/PartnerListScreen/PartnerDetailsEdit.xml
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale/models/account_move.py
  addons/sale/models/account_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web/controllers/binary.py
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/tests/test_click_everywhere.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/views/website_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/models/sale_order.py
  addons/website_sale_delivery/static/tests/tours/website_sale_delivery_gift_card.js
  addons/website_sale_delivery/tests/__init__.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_delivery/tests/test_website_sale_delivery.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/test_http/tests/test_static.py
  odoo/tools/misc.py
Labels: tmp.saas-15.4

#17364 Syncing from upstream odoo/odoo (master)
  addons/account/__manifest__.py
  addons/account/models/account_move.py
  addons/account/static/src/components/account_move_form/account_move_form.js
  addons/account/static/src/components/account_move_form/account_move_form_notebook.xml
  addons/account/static/src/components/account_payment_field/account_payment.xml
  addons/account/static/src/components/account_payment_field/account_payment_field.js
  addons/account/static/src/components/account_resequence/account_resequence.xml
  addons/account/static/src/components/account_resequence/account_resequence_field.js
  addons/account/static/src/components/account_type_selection/account_type_selection.js
  addons/account/static/src/components/account_type_selection/account_type_selection.xml
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account/static/src/components/bills_upload/bills_upload.scss
  addons/account/static/src/components/bills_upload/bills_upload.xml
  addons/account/static/src/components/grouped_view_widget/grouped_view_widget.js
  addons/account/static/src/components/grouped_view_widget/grouped_view_widget.xml
  addons/account/static/src/components/journal_dashboard_activity/journal_dashboard_activity.js
  addons/account/static/src/components/journal_dashboard_activity/journal_dashboard_activity.xml
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/account/static/src/components/open_move_widget/open_move_widget.xml
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_backend.scss
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.js
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.xml
  addons/account/static/src/components/tax_totals/tax_totals.css
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/static/src/js/account_dashboard_setup_bar.js
  addons/account/static/src/js/legacy_account_move_form.js
  addons/account/static/src/js/legacy_account_payment_field.js
  addons/account/static/src/js/legacy_account_selection.js
  addons/account/static/src/js/legacy_bills_upload.js
  addons/account/static/src/js/legacy_mail_activity.js
  addons/account/static/src/js/legacy_open_move_widget.js
  addons/account/static/src/js/legacy_section_and_note_fields_backend.js
  addons/account/static/src/js/tours/account.js
  addons/account/static/src/scss/account_resequence.scss
  addons/account/static/src/scss/group_view_widget.scss
  addons/account/static/src/scss/legacy_account_activity.scss
  addons/account/static/src/xml/legacy_account_journal_activity.xml
  addons/account/static/src/xml/legacy_account_payment.xml
  addons/account/static/src/xml/legacy_account_type_selection.xml
  addons/account/static/src/xml/legacy_bills_upload_views.xml
  addons/account/static/tests/tours/account_dashboard_setup_bar_tests.js
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/l10n_ar/static/src/js/tours/account.js
  addons/mail/static/src/models/thread.js
  addons/mail/static/src/models/web_client_view_attachment_view.js
  addons/web/static/src/views/fields/file_handler.js
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: master

#17368 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/iap/models/iap.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_sale/views/templates.xml
  doc/cla/corporate/mainframemonkey.md
  doc/cla/corporate/viindoo.md
Labels: 13.0

#17369 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hr_timesheet/views/project_views.xml
  addons/iap/models/iap_account.py
  addons/l10n_ar_website_sale/static/tests/tours/website_sale_buy.js
  addons/l10n_ar_website_sale/static/tests/tours/website_sale_complete_flow.js
  addons/l10n_in_pos/models/pos_order.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/stock/views/stock_quant_views.xml
  addons/web/tests/test_serving_base.py
  addons/website_sale/views/templates.xml
  doc/cla/corporate/mainframemonkey.md
  doc/cla/corporate/viindoo.md
Labels: 14.0

#17372 Syncing from upstream odoo/odoo (13.0)
  addons/sale_stock/models/account_move.py
Labels: 13.0

#17373 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/point_of_sale/static/src/js/models.js
Labels: 15.0

#17144 [bt#19472] migrate fetchmail_outlook and microsoft_outlook from v12
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/base_config_settings.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/views/base_config_settings_views.xml
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/templates.xml
Labels: 10.0.project_th
