Repository brain-tec/odoo, pull requests merged in 2022-01, with the labels that each got.

#15884 Syncing from upstream odoo/odoo (14.0)
  addons/mail/models/mail_template.py
  addons/mass_mailing/models/mailing.py
  addons/stock/models/stock_inventory.py
Labels: 14.0

#15885 Syncing from upstream odoo/odoo (15.0)
  addons/mail/models/mail_template.py
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/css/pos.css
  addons/pos_restaurant/static/src/css/restaurant.css
  addons/sale/wizard/__init__.py
  addons/sale/wizard/account_payment_register.py
  addons/web/static/src/img/openhand.cur
  addons/web/static/src/legacy/scss/data_export.scss
  addons/web/static/src/legacy/scss/fields.scss
  addons/web/static/src/legacy/scss/utils.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: 15.0

#15893 Syncing from upstream odoo/odoo (13.0)
  addons/calendar/models/calendar.py
  addons/hr_holidays/security/ir.model.access.csv
  addons/hr_holidays/tests/test_company_leave.py
  addons/point_of_sale/static/src/js/popups.js
Labels: 13.0

#15894 Syncing from upstream odoo/odoo (14.0)
  addons/hr_holidays/security/ir.model.access.csv
  addons/mrp/models/stock_picking.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
Labels: 14.0

#15895 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_reconcile.py
  addons/hr_holidays/tests/test_holidays_flow.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/components/file_uploader/file_uploader.js
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/tests/test_rtc.py
  addons/payment_authorize/models/authorize_request.py
  addons/project/views/project_views.xml
  addons/sale_management/models/sale_order.py
  addons/sale_project/models/project.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/stock_move_line.py
  addons/survey/static/src/js/survey_form.js
  addons/web/static/src/legacy/js/fields/abstract_field.js
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web/static/tests/legacy/views/kanban_tests.js
  addons/website/views/website_views.xml
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/static/tests/tours/website_sale_mock_tracking.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
Labels: 15.0

#15896 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_reconcile.py
  addons/fleet/report/fleet_report.py
  addons/hr_contract/report/hr_contract_history.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/models/res_company.py
  addons/hr_work_entry/models/resource.py
  addons/hr_work_entry/views/resource_calendar_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/discuss/discuss.js
  addons/mail/static/src/components/discuss/tests/discuss_message_edit_tests.js
  addons/mail/static/src/components/file_uploader/file_uploader.js
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/mail/static/src/models/file_uploader_view/file_uploader_view.js
  addons/mail/static/src/models/message/message.js
  addons/mail/static/src/models/message_in_reply_to_view/message_in_reply_to_view.js
  addons/mail/static/src/utils/test_utils.js
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/Popups/ProductInfoPopup.js
  addons/point_of_sale/static/src/xml/Popups/ProductInfoPopup.xml
  addons/point_of_sale/views/pos_config_view.xml
  addons/pos_restaurant/static/src/css/restaurant.css
  addons/project/views/project_views.xml
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale/wizard/__init__.py
  addons/sale/wizard/account_payment_register.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/stock_account/report/report_stock_forecasted.py
  addons/stock_account/report/report_stock_forecasted.xml
  addons/survey/models/survey_question.py
  addons/survey/views/survey_question_views.xml
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/img/openhand.cur
  addons/web/static/src/legacy/scss/data_export.scss
  addons/web/static/src/legacy/scss/fields.scss
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_sale/models/__init__.py
  addons/website_sale/models/payment_acquirer.py
  addons/website_sale/models/product_pricelist.py
  addons/website_sale/models/product_public_category.py
  addons/website_sale/models/product_ribbon.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/models/website_base_unit.py
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/static/tests/tours/website_sale_mock_tracking.js
  addons/website_sale/wizard/__init__.py
  addons/website_sale/wizard/mail_compose_message.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: master

#15902 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_reconcile.py
  addons/fleet/report/fleet_report.py
  addons/hr_contract/report/hr_contract_history.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_work_entry/models/resource.py
  addons/hr_work_entry/views/resource_calendar_views.xml
  addons/lunch/models/lunch_product.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/components/file_uploader/file_uploader.js
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/tests/test_rtc.py
  addons/point_of_sale/static/src/css/pos.css
  addons/pos_restaurant/static/src/css/restaurant.css
  addons/product/models/product_pricelist.py
  addons/project/models/project.py
  addons/project/tests/__init__.py
  addons/project/tests/test_task_tracking.py
  addons/project/views/project_views.xml
  addons/sale/wizard/__init__.py
  addons/sale/wizard/account_payment_register.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/stock_account/report/report_stock_forecasted.py
  addons/stock_account/report/report_stock_forecasted.xml
  addons/survey/views/survey_question_views.xml
  addons/web/static/src/img/openhand.cur
  addons/web/static/src/legacy/scss/data_export.scss
  addons/web/static/src/legacy/scss/fields.scss
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/static/tests/tours/website_sale_mock_tracking.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
Labels: tmp.saas-15.1

#15906 Syncing from upstream odoo/odoo (13.0)
  addons/stock/models/stock_quant.py
  addons/stock_picking_batch/models/stock_picking_batch.py
Labels: 13.0

#15907 Syncing from upstream odoo/odoo (14.0)
  addons/hr_holidays/tests/test_company_leave.py
  addons/l10n_sa_pos/static/src/js/OrderReceipt.js
  addons/l10n_sa_pos/static/src/xml/OrderReceipt.xml
Labels: 14.0

#15908 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/hr_holidays/static/src/js/time_off_calendar_employee.js
  addons/hr_holidays/tests/test_company_leave.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/tests/test_snippets.py
Labels: 15.0

#15909 Syncing from upstream odoo/odoo (master)
  addons/bus/static/src/js/services/assets_watchdog_service.js
  addons/bus/static/tests/assets_watchdog_tests.js
  addons/bus/tests/test_assetsbundle.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_holidays/tests/test_holidays_flow.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_timesheet/data/hr_timesheet_demo.xml
  addons/http_routing/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_channel_rtc_session.py
  addons/mail/static/src/components/rtc_call_participant_card/rtc_call_participant_card.xml
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/mail/static/src/models/partner/partner.js
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/rtc_call_participant_card/rtc_call_participant_card.js
  addons/mail/static/src/models/rtc_session/rtc_session.js
  addons/mail/tests/test_rtc.py
  addons/payment_authorize/models/authorize_request.py
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/project/__manifest__.py
  addons/project/data/mail_template_demo.xml
  addons/project/data/project_demo.xml
  addons/project/models/project.py
  addons/project/tests/__init__.py
  addons/project/tests/test_task_tracking.py
  addons/project_hr_expense/__manifest__.py
  addons/project_hr_expense/data/project_hr_expense_demo.xml
  addons/project_mrp/__manifest__.py
  addons/project_mrp/data/project_mrp_demo.xml
  addons/project_purchase/__manifest__.py
  addons/project_purchase/data/project_purchase_demo.xml
  addons/sale/models/sale_order_line.py
  addons/sale_management/models/sale_order.py
  addons/sale_stock/tests/test_create_perf.py
  addons/sale_timesheet/data/sale_service_demo.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/survey/static/src/js/survey_form.js
  addons/test_website/controllers/main.py
  addons/test_website/data/test_website_data.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/legacy/js/fields/abstract_field.js
  addons/web/static/tests/legacy/views/kanban_tests.js
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/tests/test_snippets.py
  addons/website/views/website_views.xml
  addons/website_event_sale/data/event_data.xml
  addons/website_event_track/data/event_data.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/tools/convert.py
Labels: master

#15910 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
Labels: 13.0

#15911 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_sa_invoice/models/account_move.py
  addons/product/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_quant.py
  addons/website_sale/static/src/js/website_sale_utils.js
Labels: 14.0

#15912 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_document.py
  addons/l10n_sa_invoice/models/account_move.py
  addons/mail/models/mail_activity.py
  addons/mail/static/src/models/rtc/rtc.js
  addons/mass_mailing_sale/data/mass_mailing_demo.xml
  addons/payment_adyen/models/payment_transaction.py
  addons/stock/models/stock_quant.py
  addons/website_sale/static/src/js/website_sale_utils.js
Labels: 15.0

#15914 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/purchase_mrp/models/__init__.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/__init__.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/stock.py
  debian/control
  doc/cla/corporate/moduon.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 13.0

#15915 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal_dashboard.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/data/mail_data.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/stock/models/stock_move.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/stock/tests/test_robustness.py
  addons/stock_account/report/report_stock_forecasted.py
  addons/stock_account/report/report_stock_forecasted.xml
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/scss/kanban_view.scss
  debian/control
  doc/cla/corporate/moduon.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 14.0

#15916 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/data/mail_templates.xml
  addons/payment/controllers/portal.py
  addons/payment/static/src/js/manage_form.js
  addons/payment/tests/test_multicompany_flows.py
  addons/stock/models/stock_production_lot.py
  addons/stock_account/report/report_stock_forecasted.xml
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/test_message_post.py
  doc/cla/corporate/moduon.md
Labels: 15.0

#15917 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/data/mail_templates_email_layouts.xml
  addons/mail/static/src/components/rtc_call_participant_card/rtc_call_participant_card.xml
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/rtc_call_participant_card/rtc_call_participant_card.js
  addons/mail/static/src/models/rtc_controller/rtc_controller.js
  addons/mail/static/src/models/rtc_session/rtc_session.js
  addons/mass_mailing_sale/data/mass_mailing_demo.xml
  addons/payment_adyen/models/payment_transaction.py
  addons/product/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_move_line.py
  addons/stock_account/report/report_stock_forecasted.xml
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/test_message_post.py
  addons/website_forum/static/src/js/tours/website_forum.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_sale/models/res_config_settings.py
  doc/cla/corporate/moduon.md
Labels: master

#15918 Syncing from upstream odoo/odoo (13.0)
  addons/google_spreadsheet/models/google_drive.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/project/models/project.py
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: 13.0

#15919 Syncing from upstream odoo/odoo (14.0)
  addons/calendar/models/calendar_event.py
  addons/google_spreadsheet/models/google_drive.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/__init__.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/stock.py
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
Labels: 14.0

#15920 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/models/stock_picking.py
  addons/mrp/wizard/stock_assign_serial_numbers.py
  addons/payment/static/src/js/manage_form.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/product/models/product.py
  addons/project/views/project_sharing_views.xml
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/web/static/src/legacy/scss/kanban_view.scss
  addons/web/static/src/search/search_arch_parser.js
  addons/web/static/tests/search/search_model_tests.js
Labels: 15.0

#15921 Syncing from upstream odoo/odoo (master)
  addons/delivery/models/stock_picking.py
  addons/hr/data/hr_demo.xml
  addons/hr_holidays/report/hr_leave_report_calendar.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/components/attachment_box/attachment_box.js
  addons/mail/static/src/components/composer/composer.js
  addons/mail/static/src/components/file_uploader/file_uploader.js
  addons/mail/static/src/components/file_uploader/file_uploader.xml
  addons/mail/static/src/models/activity_view/activity_view.js
  addons/mail/static/src/models/attachment_box_view/attachment_box_view.js
  addons/mail/static/src/models/emoji_list_view/emoji_list_view.js
  addons/mail/static/src/models/file_uploader_view/file_uploader_view.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/project/views/project_sharing_views.xml
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_deliveryslip.xml
  addons/web/static/src/legacy/scss/kanban_view.scss
  odoo/addons/base/tests/test_reports.py
Labels: master

#15924 Syncing from upstream odoo/odoo (11.0)
  addons/web_editor/controllers/main.py
Labels: 11.0

#15925 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_lu/data/account_tax_report_line.xml
Labels: 13.0

#15926 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/pos_box.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/calendar/models/calendar_event.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/wizard/account_payment_register.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_traceability.py
  addons/payment_ingenico/models/payment.py
  addons/project/models/project.py
  addons/repair/models/__init__.py
  addons/repair/models/product.py
  addons/stock/models/product.py
  addons/test_website/__manifest__.py
  addons/test_website/tests/test_views_during_module_operation.py
  addons/web/static/src/js/tools/debug_manager_backend.js
  addons/web/static/src/js/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph_tests.js
  addons/website/models/__init__.py
  addons/website/models/ir_model_data.py
  addons/website/models/theme_models.py
  addons/website/tests/test_theme.py
  odoo/addons/base/models/ir_model.py
Labels: 14.0

#15927 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/account_move_views.xml
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/pos_box.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/calendar/models/calendar_event.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/wizard/account_payment_register.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_coupon/static/src/js/coupon.js
  addons/product/wizard/product_label_layout.py
  addons/project/models/project.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/__init__.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/stock.py
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/image_link_tools.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/views/website_templates.xml
  debian/control
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 15.0

#15929 Syncing from upstream odoo/odoo (saas-12.3)
  addons/account/models/account.py
Labels: saas-12.3

#15934 Syncing from upstream odoo/odoo (staging.11.0)
  addons/web_editor/controllers/main.py
Labels: staging.11.0

#15935 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/google_spreadsheet/models/google_drive.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/project/models/project.py
  addons/purchase_mrp/models/__init__.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/__init__.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_quant.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
  debian/control
  doc/cla/corporate/moduon.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: staging.13.0

#15940 Syncing from upstream odoo/odoo (tmp.11.0)
  addons/web_editor/controllers/main.py
Labels: tmp.11.0

#15941 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/google_spreadsheet/models/google_drive.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/project/models/project.py
  addons/purchase_mrp/models/__init__.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/__init__.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_quant.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/website/i18n/website.pot
  addons/website/views/website_templates.xml
  debian/control
  doc/cla/corporate/moduon.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: tmp.13.0

#15944 Syncing from upstream odoo/odoo (12.0)
  addons/web_editor/controllers/main.py
Labels: 12.0

#15945 Syncing from upstream odoo/odoo (13.0)
  addons/fetchmail/models/fetchmail.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web_editor/controllers/main.py
Labels: 13.0

#15946 Syncing from upstream odoo/odoo (14.0)
  addons/base_automation/models/base_automation.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/report/project_report.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/account_invoice.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web_editor/controllers/main.py
Labels: 14.0

#15947 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/l10n_gcc_pos/static/src/xml/OrderReceipt.xml
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/lunch/data/lunch_demo.xml
  addons/lunch/models/lunch_alert.py
  addons/lunch/models/lunch_supplier.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp_repair/tests/test_tracability.py
  addons/project/models/project.py
  addons/project/report/project_report.py
  addons/project/views/project_views.xml
  addons/repair/models/__init__.py
  addons/repair/models/product.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/test_website/__manifest__.py
  addons/test_website/tests/test_views_during_module_operation.py
  addons/web/static/src/legacy/js/views/graph/graph_renderer.js
  addons/web/static/src/legacy/utils.js
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/legacy/views/graph_tests.js
  addons/web/static/tests/legacy/views/qweb_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/controllers/main.py
  addons/website/models/website_page.py
  addons/website/tests/test_fuzzy.py
  addons/website/tests/test_theme.py
  addons/website_blog/models/website_blog.py
  addons/website_event/models/event_event.py
  addons/website_forum/models/forum.py
  addons/website_sale/models/product_misc.py
  addons/website_sale/models/product_template.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
Labels: 15.0

#15949 Syncing from upstream odoo/odoo (saas-11.3)
  addons/web_editor/controllers/main.py
Labels: saas-11.3

#15950 Syncing from upstream odoo/odoo (saas-12.3)
  addons/web_editor/controllers/main.py
Labels: saas-12.3

#15953 Syncing from upstream odoo/odoo (staging.saas-11.3)
  addons/web_editor/controllers/main.py
Labels: staging.saas-11.3

#15954 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/account/models/account.py
  addons/web_editor/controllers/main.py
Labels: staging.saas-12.3

#15955 Syncing from upstream odoo/odoo (staging.saas-15.1)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/account_move_views.xml
  addons/calendar/models/calendar_event.py
  addons/fetchmail/models/fetchmail.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_gcc_pos/static/src/xml/OrderReceipt.xml
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/lunch/data/lunch_demo.xml
  addons/lunch/models/lunch_alert.py
  addons/lunch/models/lunch_supplier.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp_repair/tests/test_tracability.py
  addons/product/wizard/product_label_layout.py
  addons/project/models/project.py
  addons/project/report/project_report.py
  addons/project/views/project_views.xml
  addons/repair/models/__init__.py
  addons/repair/models/product.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/js/views/graph/graph_renderer.js
  addons/web/static/src/legacy/utils.js
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/legacy/views/graph_tests.js
  addons/web/static/tests/legacy/views/qweb_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/image_link_tools.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
Labels: staging.saas-15.1

#15957 Syncing from upstream odoo/odoo (staging.13.0)
  addons/fetchmail/models/fetchmail.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web_editor/controllers/main.py
Labels: staging.13.0

#15958 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/wizard/pos_box.py
  addons/base_automation/models/base_automation.py
  addons/fetchmail/models/fetchmail.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/report/project_report.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/account_invoice.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web_editor/controllers/main.py
Labels: staging.14.0

#15961 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  addons/web_editor/controllers/main.py
Labels: tmp.saas-11.3

#15962 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/account/models/account.py
  addons/web_editor/controllers/main.py
Labels: tmp.saas-12.3

#15963 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_bank_statement.py
  addons/base_automation/models/base_automation.py
  addons/calendar/models/calendar_event.py
  addons/fetchmail/models/fetchmail.py
  addons/google_spreadsheet/models/google_drive.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_gcc_pos/static/src/xml/OrderReceipt.xml
  addons/lunch/data/lunch_demo.xml
  addons/lunch/models/lunch_alert.py
  addons/lunch/models/lunch_supplier.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp_repair/tests/test_tracability.py
  addons/product/wizard/product_label_layout.py
  addons/project/models/project.py
  addons/project/report/project_report.py
  addons/project/views/project_views.xml
  addons/repair/models/__init__.py
  addons/repair/models/product.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/js/views/graph/graph_renderer.js
  addons/web/static/src/legacy/utils.js
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/legacy/views/graph_tests.js
  addons/web/static/tests/legacy/views/qweb_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/image_link_tools.xml
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
Labels: tmp.saas-15.1

#15965 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/fetchmail/models/fetchmail.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web_editor/controllers/main.py
Labels: tmp.13.0

#15966 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/wizard/pos_box.py
  addons/base_automation/models/base_automation.py
  addons/fetchmail/models/fetchmail.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/report/project_report.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/account_invoice.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web_editor/controllers/main.py
Labels: tmp.14.0

#15967 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/base_automation/models/base_automation.py
  addons/fetchmail/models/fetchmail.py
  addons/google_spreadsheet/models/google_drive.py
  addons/l10n_gcc_pos/static/src/xml/OrderReceipt.xml
  addons/lunch/data/lunch_demo.xml
  addons/lunch/models/lunch_alert.py
  addons/lunch/models/lunch_supplier.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp_repair/tests/test_tracability.py
  addons/project/models/project.py
  addons/project/report/project_report.py
  addons/project/views/project_views.xml
  addons/repair/models/__init__.py
  addons/repair/models/product.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/product.py
  addons/stock_account/wizard/stock_picking_return.py
  addons/test_website/__manifest__.py
  addons/test_website/tests/test_views_during_module_operation.py
  addons/web/static/src/legacy/js/views/graph/graph_renderer.js
  addons/web/static/src/legacy/utils.js
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/legacy/views/graph_tests.js
  addons/web/static/tests/legacy/views/qweb_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/controllers/main.py
  addons/website/models/website_page.py
  addons/website/tests/test_fuzzy.py
  addons/website/tests/test_theme.py
  addons/website_blog/models/website_blog.py
  addons/website_event/models/event_event.py
  addons/website_forum/models/forum.py
  addons/website_sale/models/product_misc.py
  addons/website_sale/models/product_template.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
Labels: tmp.15.0

#15968 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/sale/models/account_invoice.py
  addons/sale_mrp/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/product.py
Labels: 13.0

#15969 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/wizard/pos_box.py
  addons/fetchmail/models/fetchmail.py
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/stock/models/stock_rule.py
  addons/stock_picking_batch/models/stock_picking_batch.py
Labels: 14.0

#15970 Syncing from upstream odoo/odoo (15.0)
  addons/base_automation/models/base_automation.py
  addons/fetchmail/models/fetchmail.py
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle_model.py
  addons/google_calendar/models/calendar.py
  addons/google_spreadsheet/models/google_drive.py
  addons/mail/wizard/mail_compose_message.py
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/microsoft_calendar/models/calendar.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/views/project_views.xml
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_project/models/sale_order.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/core/hotkeys/hotkey_service.js
Labels: 15.0

#15972 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/test_xlsx_export/tests/test_export.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/qweb.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: 13.0

#15973 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/website/models/ir_module_module.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/qweb.py
Labels: 14.0

#15974 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ar/__manifest__.py
  addons/l10n_ar/demo/account_customer_invoice_demo.xml
  addons/l10n_ar/demo/account_customer_refund_demo.xml
  addons/l10n_ar/demo/account_supplier_invoice_demo.xml
  addons/l10n_ar/demo/account_supplier_refund_demo.xml
  addons/l10n_ar/demo/account_tax_demo.xml
  addons/l10n_ar/demo/res_users_demo.xml
  addons/l10n_ar/demo/respinsc_demo.xml
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_be/data/account_fiscal_position_tax_template_data.xml
  addons/l10n_be/data/account_tax_template_data.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/ir_module_module.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/assetsbundle.py
Labels: 15.0

#15976 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
Labels: 13.0

#15977 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_attendees.py
  addons/calendar/views/calendar_views.xml
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/l10n_be_edi/models/ir_actions_report.py
  addons/l10n_be_edi/tests/__init__.py
  addons/l10n_be_edi/tests/test_efff_export.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
  addons/sale/models/account_invoice.py
  addons/sale/views/res_partner_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/survey/controllers/main.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_slides/views/website_slides_templates_utils.xml
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: 14.0

#15978 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/wizard/account_invoice_send.py
  addons/calendar/tests/test_attendees.py
  addons/calendar/views/calendar_views.xml
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mrp/views/mrp_workorder_views.xml
  addons/payment_authorize/views/payment_authorize_templates.xml
  addons/purchase_stock/models/stock_rule.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  doc/cla/individual/BayarkhuuBataa.md
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/models/qweb.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: 15.0

#15980 Syncing from upstream odoo/odoo (15.0)
  addons/microsoft_calendar/tests/test_sync_odoo2microsoft.py
  addons/web/controllers/main.py
  odoo/addons/base/models/ir_qweb.py
Labels: 15.0

#15982 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
  addons/sale/models/account_invoice.py
  addons/sale_mrp/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/product.py
  addons/test_xlsx_export/tests/test_export.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/qweb.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: staging.13.0

#15983 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_payment.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_attendees.py
  addons/calendar/views/calendar_views.xml
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/l10n_be_edi/models/ir_actions_report.py
  addons/l10n_be_edi/tests/__init__.py
  addons/l10n_be_edi/tests/test_efff_export.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
  addons/sale/models/account_invoice.py
  addons/sale/views/res_partner_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_rule.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/survey/controllers/main.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_module_module.py
  addons/website_slides/views/website_slides_templates_utils.xml
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/qweb.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: staging.14.0

#15987 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
  addons/sale/models/account_invoice.py
  addons/sale_mrp/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/product.py
  addons/test_xlsx_export/tests/test_export.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/qweb.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: tmp.13.0

#15988 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_payment.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_attendees.py
  addons/calendar/views/calendar_views.xml
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/l10n_be_edi/models/ir_actions_report.py
  addons/l10n_be_edi/tests/__init__.py
  addons/l10n_be_edi/tests/test_efff_export.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/maintenance/data/maintenance_data.xml
  addons/maintenance/models/maintenance.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/views/mrp_workorder_views.xml
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
  addons/sale/models/account_invoice.py
  addons/sale/views/res_partner_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_rule.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/survey/controllers/main.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_module_module.py
  addons/website_slides/views/website_slides_templates_utils.xml
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/qweb.py
  odoo/addons/test_impex/tests/test_export.py
  odoo/models.py
Labels: tmp.14.0

#15990 Syncing from upstream odoo/odoo (15.0)
  addons/web_editor/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_qweb.py
Labels: 15.0

#15991 Syncing from upstream odoo/odoo (master)
  addons/microsoft_calendar/tests/test_sync_odoo2microsoft.py
  addons/web/controllers/main.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/views/snippets.xml
  addons/website/__manifest__.py
  addons/website/static/src/snippets/s_social_media/000.scss
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website/tests/test_snippets.py
  addons/website/views/res_config_settings_views.xml
  addons/website/views/snippets/s_share.xml
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/snippets/snippets.xml
  addons/website/views/website_templates.xml
  odoo/addons/base/models/ir_qweb.py
Labels: master

#15992 [t126952] Odoo Security Advisory - ODOO-SA-2021-12-28 (v13)
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 13.0.project_te_576

#15993 [t126941] Odoo Security Advisory - ODOO-SA-2021-12-28 (v13)
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 13.0.project_li_101

#15994 [t126949] Odoo Security Advisory - ODOO-SA-2021-12-28 (v13)
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 13.0.project_pr_449

#15995 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  git
  odoo/addons/base/models/ir_attachment.py
Labels: 13.0

#15996 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ch/models/res_bank.py
  addons/l10n_pe/demo/demo_company.xml
  addons/l10n_pe/demo/demo_partner.xml
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  addons/sale_purchase/models/purchase_order.py
  addons/web/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
Labels: 14.0

#15997 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/wizard/pos_box.py
  addons/l10n_be_edi/models/ir_actions_report.py
  addons/l10n_be_edi/tests/__init__.py
  addons/l10n_be_edi/tests/test_efff_export.py
  addons/l10n_pe/demo/demo_company.xml
  addons/l10n_pe/demo/demo_partner.xml
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/payment_buckaroo/controllers/main.py
  addons/payment_buckaroo/i18n/payment_buckaroo.pot
  addons/payment_buckaroo/models/payment_transaction.py
  addons/point_of_sale/models/pos_config.py
  addons/sale/models/account_move.py
  addons/sale/views/res_partner_views.xml
  addons/sale_project/views/project_task_views.xml
  addons/stock/models/product.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/style.css
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/views/website_slides_templates_utils.xml
Labels: 15.0

#15999 [t126945] Odoo Security Advisory - ODOO-SA-2021-12-28 (v13)
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 13.0.project_mi_582

#16000 Syncing from upstream odoo/odoo (11.0)
  odoo/tools/mimetypes.py
Labels: 11.0

#16001 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/views/account_move_views.xml
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_template.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/tests/test_workorder_operation.py
  addons/mrp/wizard/change_production_qty.py
  addons/sale_stock/models/account_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/test_mass_mailing/tests/test_performance.py
Labels: 13.0

#16002 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/views/account_move_views.xml
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_template.py
  addons/mass_mailing/models/mailing.py
  addons/mrp_account/models/product.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/CashBoxOpening.js
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/controllers/portal.py
  addons/sale_stock/models/account_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/test_mass_mailing/tests/test_performance.py
Labels: 14.0

#16003 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment_method.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_move_views.xml
  addons/account/wizard/accrued_orders.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_attendance/views/hr_attendance_overtime_view.xml
  addons/l10n_ar/demo/account_demo.py
  addons/l10n_cl/demo/account_demo.py
  addons/l10n_ec/demo/account_demo.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_pe/demo/account_demo.py
  addons/mrp_account/models/product.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/static/src/js/printers.js
  addons/pos_sale/i18n/pos_sale.pot
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  addons/product_expiry/models/stock_picking.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_purchase/models/purchase_order.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_account/tests/test_anglo_saxon_valuation_reconciliation_common.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/tests/test_assets.py
  addons/website_blog/controllers/main.py
  odoo/addons/base/models/ir_attachment.py
Labels: 15.0

#16005 [REM] packaging: remove obsolete dependency feedparser
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 13.0.project_te_576

#16006 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/models/account_journal.py
  addons/l10n_pt/data/account_data.xml
  addons/l10n_pt/data/account_tax_data.xml
  addons/mail/models/mail_thread.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
Labels: 13.0

#16007 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ar/models/account_journal.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/point_of_sale/static/src/js/printers.js
  addons/product_expiry/models/stock_picking.py
Labels: 14.0

#16008 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/l10n_ar/models/account_journal.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_pt/__manifest__.py
  addons/l10n_pt/data/account_tax_data.xml
  addons/l10n_pt/data/account_tax_report.xml
  addons/l10n_se/__manifest__.py
  addons/l10n_se/data/account.account.tag.csv
  addons/l10n_se/data/account.account.template-K2.csv
  addons/l10n_se/data/account.account.template-K3.csv
  addons/l10n_se/data/account.account.template.csv
  addons/l10n_se/data/account_chart_template_before_accounts.xml
  addons/l10n_se/data/menuitem_data.xml
  addons/l10n_se/i18n/l10n_se.pot
  addons/l10n_se/i18n/sv_SE.po
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail_group/models/mail_group.py
  addons/mail_group/tests/test_mail_group.py
  addons/mail_group/tests/test_mail_group_message.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/mrp_production.py
  addons/mrp/wizard/stock_assign_serial_numbers.py
  addons/payment/static/src/js/checkout_form.js
  addons/payment/static/src/js/manage_form.js
  addons/payment/static/src/js/payment_form_mixin.js
  addons/payment_adyen/static/src/js/payment_form.js
  addons/payment_authorize/static/src/js/payment_form.js
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/legacy/js/components/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale_payment.js
Labels: 15.0

#16010 Syncing from upstream odoo/odoo (12.0)
  odoo/tools/mimetypes.py
Labels: 12.0

#16011 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/base_import/static/src/js/import_action.js
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/sale/models/product_template.py
  addons/website_sale/models/product.py
  odoo/tools/mimetypes.py
Labels: 13.0

#16012 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_pt/data/account_data.xml
  addons/l10n_pt/data/account_tax_data.xml
  addons/repair/models/repair.py
  addons/sale/models/product_template.py
  addons/website_sale/models/product.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/tools/mimetypes.py
Labels: 14.0

#16013 Syncing from upstream odoo/odoo (15.0)
  addons/base_import/static/src/legacy/js/import_action.js
  addons/l10n_pt/data/account_tax_data.xml
  addons/l10n_pt/data/account_tax_group_data.xml
  addons/mail/models/ir_attachment.py
  addons/mail/models/mail_message.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/mass_mailing/tests/test_mailing_ui.py
  addons/mass_mailing/views/assets.xml
  addons/mass_mailing/views/snippets/s_text_block.xml
  addons/mass_mailing/views/snippets_themes.xml
  addons/payment_buckaroo/models/payment_acquirer.py
  addons/payment_buckaroo/tests/common.py
  addons/payment_buckaroo/tests/test_buckaroo.py
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/static/src/js/printers.js
  addons/sale/models/product_template.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/models/product_template.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/tools/mimetypes.py
Labels: 15.0

#16015 Syncing from upstream odoo/odoo (saas-11.3)
  odoo/tools/mimetypes.py
Labels: saas-11.3

#16016 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/tools/mimetypes.py
Labels: saas-12.3

#16018 Syncing from upstream odoo/odoo (master)
  addons/base_import/static/src/legacy/js/import_action.js
  addons/hr/models/hr_employee.py
  addons/im_livechat/controllers/main.py
  addons/payment/static/src/js/checkout_form.js
  addons/payment/static/src/js/manage_form.js
  addons/payment/static/src/js/payment_form_mixin.js
  addons/payment_adyen/static/src/js/payment_form.js
  addons/payment_authorize/static/src/js/payment_form.js
  addons/purchase/controllers/portal.py
  addons/web/controllers/main.py
  addons/web/models/ir_http.py
  addons/web_editor/controllers/main.py
  addons/web_editor/tools.py
  addons/web_unsplash/controllers/main.py
  addons/website/models/website.py
  addons/website_event_track/models/website.py
  addons/website_profile/controllers/main.py
  addons/website_sale/static/src/js/website_sale_payment.js
  addons/website_slides/controllers/main.py
  odoo/addons/base/models/avatar_mixin.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_company.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_avatar_mixin.py
  odoo/addons/base/tests/test_image.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/fields.py
  odoo/tools/image.py
Labels: master

#16019 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/models/pos_session.py
Labels: 14.0

#16020 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_edi/models/account_edi_format.py
Labels: master

#16022 Syncing from upstream odoo/odoo (staging.11.0)
  odoo/tools/mimetypes.py
Labels: staging.11.0

#16023 Syncing from upstream odoo/odoo (staging.12.0)
  odoo/tools/mimetypes.py
Labels: staging.12.0

#16024 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/views/account_move_views.xml
  addons/base_import/static/src/js/import_action.js
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_pt/data/account_data.xml
  addons/l10n_pt/data/account_tax_data.xml
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/tests/test_workorder_operation.py
  addons/mrp/wizard/change_production_qty.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  addons/sale/models/product_template.py
  addons/sale_stock/models/account_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website_sale/models/product.py
  git
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/tools/mimetypes.py
Labels: staging.13.0

#16025 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/views/account_move_views.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_pe/demo/demo_company.xml
  addons/l10n_pe/demo/demo_partner.xml
  addons/l10n_pt/data/account_data.xml
  addons/l10n_pt/data/account_tax_data.xml
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mailing.py
  addons/mrp_account/models/product.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/CashBoxOpening.js
  addons/point_of_sale/static/src/js/printers.js
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  addons/product_expiry/models/stock_picking.py
  addons/repair/models/repair.py
  addons/sale/models/product_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_purchase/models/purchase_order.py
  addons/sale_stock/controllers/portal.py
  addons/sale_stock/models/account_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/controllers/main.py
  addons/website_sale/models/product.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/tools/mimetypes.py
Labels: staging.14.0

#16028 Syncing from upstream odoo/odoo (tmp.saas-11.3)
  odoo/tools/mimetypes.py
Labels: tmp.saas-11.3

#16029 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  odoo/tools/mimetypes.py
Labels: tmp.saas-12.3

#16031 Syncing from upstream odoo/odoo (tmp.11.0)
  odoo/tools/mimetypes.py
Labels: tmp.11.0

#16032 Syncing from upstream odoo/odoo (tmp.12.0)
  odoo/tools/mimetypes.py
Labels: tmp.12.0

#16033 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/views/account_move_views.xml
  addons/base_import/static/src/js/import_action.js
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_pt/data/account_data.xml
  addons/l10n_pt/data/account_tax_data.xml
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/tests/test_workorder_operation.py
  addons/mrp/wizard/change_production_qty.py
  addons/point_of_sale/models/pos_order.py
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  addons/sale/models/product_template.py
  addons/sale_stock/models/account_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website_sale/models/product.py
  git
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/tools/mimetypes.py
Labels: tmp.13.0

#16034 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/views/account_move_views.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/i18n/l10n_fr_fec.pot
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_pe/demo/demo_company.xml
  addons/l10n_pe/demo/demo_partner.xml
  addons/l10n_pt/data/account_data.xml
  addons/l10n_pt/data/account_tax_data.xml
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mailing.py
  addons/mrp_account/models/product.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/CashBoxOpening.js
  addons/point_of_sale/static/src/js/printers.js
  addons/product/models/product.py
  addons/product/models/product_pricelist.py
  addons/product/tests/test_variants.py
  addons/product_expiry/models/stock_picking.py
  addons/repair/models/repair.py
  addons/sale/models/product_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_purchase/models/purchase_order.py
  addons/sale_stock/controllers/portal.py
  addons/sale_stock/models/account_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/controllers/main.py
  addons/website_sale/models/product.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/tools/mimetypes.py
Labels: tmp.14.0

#16036 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  doc/cla/corporate/adhoc.md
Labels: 13.0

#16037 Syncing from upstream odoo/odoo (14.0)
  addons/base_import/static/src/js/import_action.js
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/mail/models/mail_thread.py
  addons/sale_project/views/project_task_views.xml
  addons/test_mail/tests/test_message_post.py
  odoo/addons/base/models/ir_module.py
Labels: 14.0

#16038 Syncing from upstream odoo/odoo (15.0)
  .tx/config
  addons/account/i18n/account.pot
  addons/account_edi/i18n/account_edi.pot
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/base_vat/i18n/base_vat.pot
  addons/digest/i18n/digest.pot
  addons/hr_attendance/static/src/scss/hr_attendance.scss
  addons/hr_fleet/i18n/hr_fleet.pot
  addons/hr_presence/i18n/hr_presence.pot
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/im_livechat/i18n/im_livechat.pot
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_pt/data/l10n_pt_chart_data.xml
  addons/lunch/i18n/lunch.pot
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mrp/i18n/mrp.pot
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting_dropshipping/i18n/mrp_subcontracting_dropshipping.pot
  addons/payment/i18n/payment.pot
  addons/point_of_sale/models/pos_session.py
  addons/project/i18n/project.pot
  addons/sale/i18n/sale.pot
  addons/sale_timesheet/models/project.py
  addons/stock_landed_costs/i18n/stock_landed_costs.pot
  addons/test_mail/tests/test_message_post.py
  addons/web/controllers/main.py
  addons/web/i18n/web.pot
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_crm_partner_assign/i18n/website_crm_partner_assign.pot
  addons/website_event/i18n/website_event.pot
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
Labels: 15.0

#16039 Syncing from upstream odoo/odoo (master)
  addons/account/models/partner.py
  addons/hr_attendance/static/src/scss/hr_attendance.scss
  addons/hr_recruitment/__manifest__.py
  addons/hr_recruitment/models/__init__.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/models/ir_ui_menu.py
  addons/hr_recruitment/models/res_users.py
  addons/hr_recruitment/security/hr_recruitment_security.xml
  addons/hr_recruitment/security/ir.model.access.csv
  addons/hr_recruitment/static/src/scss/hr_applicant.scss
  addons/hr_recruitment/tests/__init__.py
  addons/hr_recruitment/tests/test_recruitment_interviewer.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/tests/test_mailing_ui.py
  addons/mass_mailing/views/assets.xml
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/product_template.py
  addons/sale_stock/tests/test_create_perf.py
  addons/sale_timesheet/models/project.py
  addons/web/controllers/main.py
  addons/web/tests/__init__.py
  addons/web/tests/test_db_manager.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/web_editor/static/src/xml/image_link_tools.xml
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/web_editor/views/snippets.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/models/product_template.py
  odoo/modules/module.py
  odoo/service/db.py
  odoo/tools/config.py
Labels: master

#16040 Syncing from upstream odoo/odoo (12.0)
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: 12.0

#16041 Syncing from upstream odoo/odoo (13.0)
  .tx/config
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mail/models/mail_followers.py
  addons/product/models/product.py
  addons/test_mail/tests/test_mail_followers.py
  odoo/addons/base/models/ir_mail_server.py
Labels: 13.0

#16042 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fr_pos_cert/views/account_views.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_unbuild.py
  addons/project/models/project.py
  addons/project/tests/test_project_flow.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/survey/static/src/css/survey_print.css
  addons/website/static/tests/tours/rte.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_form/static/tests/tours/website_form_editor.js
Labels: 14.0

#16043 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_payment.py
  addons/hr/wizard/hr_departure_wizard.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/mail/static/src/component_hooks/use_component_to_model/use_component_to_model.js
  addons/mail/static/src/component_hooks/use_ref_to_model/use_ref_to_model.js
  addons/mail/static/src/components/rtc_call_viewer/rtc_call_viewer.xml
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/account_journal.py
  addons/pos_gift_card/i18n/pos_gift_card.pot
  addons/pos_gift_card/models/gift_card.py
  addons/pos_gift_card/static/src/js/GiftCardPopup.js
  addons/pos_gift_card/static/src/js/PaymentScreen.js
  addons/pos_gift_card/static/src/js/models.js
  addons/stock/report/report_stock_reception.py
  addons/stock/static/src/js/report_stock_reception.js
  addons/stock/tests/test_report.py
  addons/web/models/ir_ui_menu.py
  addons/web/tests/test_load_menus.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/snippet_popup_add_remove.js
  addons/website/tests/test_snippets.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/tests/test_ir_mail_server.py
Labels: 15.0

#16045 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_import/static/src/js/import_action.js
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fr_pos_cert/views/account_views.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_unbuild.py
  addons/project/models/project.py
  addons/project/tests/test_project_flow.py
  addons/sale_project/views/project_task_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/survey/static/src/css/survey_print.css
  addons/test_mail/tests/test_message_post.py
  addons/website/static/tests/tours/rte.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_form/static/tests/tours/website_form_editor.js
  odoo/addons/base/models/ir_module.py
Labels: tmp.14.0

#16047 Syncing from upstream odoo/odoo (14.0)
  .tx/config
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/auth_totp/views/user_preferences.xml
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  odoo/addons/base/models/ir_mail_server.py
Labels: 14.0

#16048 Syncing from upstream odoo/odoo (15.0)
  .tx/config
  addons/auth_totp/data/ir_action_data.xml
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_fr_pos_cert/views/account_views.xml
  addons/mail/static/src/components/chat_window_manager/tests/chat_window_manager_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_unbuild.py
  addons/point_of_sale/models/account_journal.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_gift_card/static/src/js/GiftCardPopup.js
  addons/product/models/product.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/static/src/js/lazy_column_list.js
  addons/stock/static/src/xml/inventory_report.xml
  addons/stock/static/tests/lazy_column_list_tests.js
  addons/survey/static/src/css/survey_templates_print.css
  addons/web/controllers/main.py
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web/tests/test_serving_base.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/rte.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/ir_mail_server.py
Labels: 15.0

#16050 Syncing from upstream odoo/odoo (saas-12.3)
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: saas-12.3

#16053 Syncing from upstream odoo/odoo (staging.saas-11.3)
  odoo/tools/mimetypes.py
Labels: staging.saas-11.3

#16054 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/mimetypes.py
Labels: staging.saas-12.3

#16056 Syncing from upstream odoo/odoo (staging.12.0)
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: staging.12.0

#16057 Syncing from upstream odoo/odoo (staging.13.0)
  .tx/config
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mail/models/mail_followers.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/product/models/product.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/test_mail/tests/test_mail_followers.py
  doc/cla/corporate/adhoc.md
  odoo/addons/base/models/ir_mail_server.py
Labels: staging.13.0

#16058 Syncing from upstream odoo/odoo (staging.14.0)
  .tx/config
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/auth_totp/views/user_preferences.xml
  addons/base_import/static/src/js/import_action.js
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fr_pos_cert/views/account_views.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_unbuild.py
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  addons/project/models/project.py
  addons/project/tests/test_project_flow.py
  addons/sale_project/views/project_task_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/survey/static/src/css/survey_print.css
  addons/test_mail/tests/test_message_post.py
  addons/website/static/tests/tours/rte.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_form/static/tests/tours/website_form_editor.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
Labels: staging.14.0

#16061 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.saas-12.3

#16063 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.12.0

#16064 Syncing from upstream odoo/odoo (tmp.13.0)
  .tx/config
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_dk/__manifest__.py
  addons/l10n_dk/data/account_fiscal_position_tax_template.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mail/models/mail_followers.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/product/models/product.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/test_mail/tests/test_mail_followers.py
  doc/cla/corporate/adhoc.md
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.13.0

#16065 Syncing from upstream odoo/odoo (tmp.14.0)
  .tx/config
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/auth_totp/views/user_preferences.xml
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/product/models/product.py
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.14.0

#16066 Syncing from upstream odoo/odoo (tmp.15.0)
  .tx/config
  addons/auth_totp/data/ir_action_data.xml
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_fr_pos_cert/views/account_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_unbuild.py
  addons/point_of_sale/models/account_journal.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_gift_card/static/src/js/GiftCardPopup.js
  addons/product/models/product.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/static/src/js/lazy_column_list.js
  addons/stock/static/src/xml/inventory_report.xml
  addons/stock/static/tests/lazy_column_list_tests.js
  addons/survey/static/src/css/survey_templates_print.css
  addons/web/controllers/main.py
  addons/web/tests/test_serving_base.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/rte.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.15.0

#16067 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/product/models/res_partner.py
  addons/sale/models/sale.py
  addons/stock/models/stock_picking.py
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
Labels: 13.0

#16068 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/mail/models/mail_followers.py
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/product/models/product_pricelist.py
  addons/test_mail/tests/test_mail_followers.py
  addons/web/static/src/scss/web_calendar.scss
  doc/cla/corporate/adhoc.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
Labels: 14.0

#16069 Syncing from upstream odoo/odoo (15.0)
  addons/hr_attendance/static/src/js/kiosk_mode.js
  addons/hr_contract/models/hr_employee.py
  addons/hr_contract/tests/test_contract.py
  addons/mail/controllers/discuss.py
  addons/mail/models/res_users.py
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/mail/static/tests/chatter_tests.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/project/views/project_views.xml
  addons/resource/models/resource.py
  addons/stock/models/stock_quant.py
  addons/test_discuss_full/tests/test_performance.py
  addons/web/static/src/legacy/frontend/keyboard_navigation_mixin.js
  addons/web/static/src/legacy/scss/web_calendar.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/scss/website.ui.scss
Labels: 15.0

#16071 Syncing from upstream odoo/odoo (13.0)
  addons/account/tests/test_fiscal_position.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_attribute.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/xml/website.pageProperties.xml
  doc/cla/corporate/optesis.md
  odoo/models.py
Labels: 13.0

#16072 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/product/models/product_attribute.py
  addons/product/models/res_partner.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_popup/001.scss
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/static/tests/tours/rte.js
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_livechat/models/mail_channel.py
  addons/website_livechat/tests/common.py
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_sale/static/src/js/tours/website_sale_shop.js
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  addons/website_slides/static/src/js/tours/slides_tour.js
  doc/cla/individual/kwfx.md
  odoo/models.py
Labels: 14.0

#16073 Syncing from upstream odoo/odoo (15.0)
  addons/coupon/models/coupon.py
  addons/l10n_au/data/account_tax_report_data.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_followers.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/payment_paypal/controllers/main.py
  addons/payment_paypal/tests/test_paypal.py
  addons/product/models/product_attribute.py
  addons/product/models/product_pricelist.py
  addons/product/models/res_partner.py
  addons/sale_project/views/project_task_views.xml
  addons/stock/models/stock_move.py
  addons/test_mail/tests/test_mail_followers.py
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  doc/cla/individual/aitalinassim.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/models.py
Labels: 15.0

#16075 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ar/models/account_move.py
  doc/cla/corporate/optesis.md
Labels: 14.0

#16076 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ch/static/src/scss/report_swissqr.scss
  doc/cla/corporate/optesis.md
Labels: 15.0

#16077 Syncing from upstream odoo/odoo (master)
  doc/cla/corporate/optesis.md
  doc/cla/individual/aitalinassim.md
Labels: master
