Repository brain-tec/odoo, pull requests merged in 2022-07, with the labels that each got.

#17068 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/mrp/models/mrp_production.py
  addons/website_forum/controllers/main.py
  addons/website_forum/models/forum.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/tests/test_forum.py
  doc/cla/individual/petrus-v.md
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_user_has_group.py
Labels: 13.0

#17069 Syncing from upstream odoo/odoo (14.0)
  .tx/config
  addons/base_import_module/tests/test_cloc.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/payment/models/payment_acquirer.py
  addons/payment_adyen_paybylink/__init__.py
  addons/payment_adyen_paybylink/__manifest__.py
  addons/payment_adyen_paybylink/const.py
  addons/payment_adyen_paybylink/controllers/__init__.py
  addons/payment_adyen_paybylink/controllers/main.py
  addons/payment_adyen_paybylink/i18n/payment_adyen_paybylink.pot
  addons/payment_adyen_paybylink/models/__init__.py
  addons/payment_adyen_paybylink/models/payment_acquirer.py
  addons/payment_adyen_paybylink/models/payment_transaction.py
  addons/payment_adyen_paybylink/views/payment_views.xml
  addons/portal/static/src/scss/portal.scss
  addons/sale_mrp/models/sale.py
  addons/stock_account/models/stock_move.py
  addons/website_forum/controllers/main.py
  addons/website_forum/models/forum.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/tests/test_forum.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/addons/base/tests/test_user_has_group.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
  odoo/tests/test_module_operations.py
  odoo/tools/cloc.py
Labels: 14.0

#17072 Syncing from upstream odoo/odoo (12.0)
  odoo/tools/cloc.py
Labels: 12.0

#17073 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/hr_expense/models/product_template.py
  addons/l10n_ch/models/account_invoice.py
  addons/mail/views/mail_mail_views.xml
  addons/mail/views/mail_message_views.xml
  odoo/http.py
  odoo/modules/module.py
  odoo/osv/expression.py
  odoo/tools/misc.py
Labels: 13.0

#17074 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_expense/models/product_template.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mail/views/mail_mail_views.xml
  addons/mail/views/mail_message_views.xml
  addons/mail/views/mail_notification_views.xml
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/website_sale/tests/test_customize.py
  odoo/http.py
  odoo/tools/misc.py
Labels: 14.0

#17075 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/static/src/js/tax_totals.js
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_mail.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/payment/tests/test_flows.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/sale_expense/views/product_view.xml
  addons/sale_mrp/models/sale.py
  addons/stock/static/src/js/popover_widget.js
  doc/cla/individual/dieterreinert.md
  odoo/http.py
  odoo/sql_db.py
  odoo/tools/misc.py
  odoo/tools/profiler.py
Labels: 15.0

#17077 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/ca.po
  addons/account/i18n/de.po
  addons/account/i18n/id.po
  addons/account/i18n/lt.po
  addons/account/i18n/mn.po
  addons/account/i18n/pt.po
  addons/account/i18n/uk.po
  addons/account_debit_note/i18n/pt.po
  addons/account_edi/i18n/fi.po
  addons/adyen_platforms/i18n/pt.po
  addons/auth_totp/i18n/lt.po
  addons/calendar/i18n/de.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/fi.po
  addons/event/i18n/de.po
  addons/hr/i18n/ca.po
  addons/hr_expense/i18n/ca.po
  addons/hr_holidays/i18n/ca.po
  addons/hr_recruitment/i18n/lt.po
  addons/hr_recruitment/i18n/pl.po
  addons/hr_recruitment_survey/i18n/fr.po
  addons/mrp/i18n/ar.po
  addons/mrp/i18n/de.po
  addons/mrp/i18n/he.po
  addons/point_of_sale/i18n/de.po
  addons/purchase_requisition/i18n/he.po
  addons/purchase_stock/i18n/he.po
  addons/sale_quotation_builder/i18n/de.po
  addons/stock_landed_costs/i18n/ar.po
  addons/stock_picking_batch/i18n/ar.po
  addons/survey/i18n/ar.po
  addons/web_editor/i18n/ar.po
  addons/website/i18n/tr.po
  addons/website_event_track/i18n/ar.po
  addons/website_event_track_quiz/i18n/ar.po
  addons/website_form/i18n/fi.po
  addons/website_form/i18n/tr.po
  addons/website_forum/i18n/ar.po
  addons/website_forum/i18n/ca.po
  addons/website_hr_recruitment/i18n/fr.po
  addons/website_livechat/i18n/ar.po
  addons/website_mass_mailing/i18n/uk.po
  addons/website_profile/i18n/ar.po
  addons/website_sale/i18n/ar.po
  addons/website_sale_wishlist/i18n/ar.po
  addons/website_slides/i18n/ar.po
  addons/website_slides/i18n/ca.po
  addons/website_slides_forum/i18n/ar.po
  addons/website_slides_forum/i18n/ca.po
  addons/website_slides_survey/i18n/ar.po
  addons/website_sms/i18n/ar.po
  addons/website_twitter/i18n/ar.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/it.po
Labels: 14.0

#17079 Syncing from upstream odoo/odoo (master)
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website_sale/tests/test_customize.py
  odoo/http.py
  odoo/tools/misc.py
Labels: master

#17080 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/ca.po
  addons/account/i18n/lt.po
  addons/account/i18n/pt.po
  addons/account/i18n/uk.po
  addons/crm/i18n/pl.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/fi.po
  addons/hr/i18n/ca.po
  addons/hr_expense/i18n/ca.po
  addons/hr_holidays/i18n/ca.po
  addons/hr_recruitment/views/hr_job_views.xml
  addons/mrp/i18n/ar.po
  addons/mrp/i18n/de.po
  addons/point_of_sale/i18n/de.po
  addons/sale_quotation_builder/i18n/de.po
  addons/stock_landed_costs/i18n/ar.po
  addons/stock_picking_batch/i18n/ar.po
  addons/survey/i18n/ar.po
  addons/web/static/src/scss/kanban_view.scss
  addons/web_editor/i18n/ar.po
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_form/i18n/fi.po
  addons/website_form/views/snippets.xml
  addons/website_forum/i18n/ar.po
  addons/website_forum/i18n/ca.po
  addons/website_livechat/i18n/ar.po
  addons/website_profile/i18n/ar.po
  addons/website_sale/views/snippets.xml
  addons/website_sale_wishlist/i18n/ar.po
  addons/website_slides/i18n/ar.po
  addons/website_slides/i18n/ca.po
  addons/website_slides_forum/i18n/ar.po
  addons/website_slides_survey/i18n/ar.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/it.po
Labels: 13.0

#17081 Syncing from upstream odoo/odoo (14.0)
  addons/hr_recruitment/views/hr_job_views.xml
  addons/im_livechat/static/src/bugfix/bugfix.js
  addons/im_livechat/static/src/components/composer/composer_tests.js
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account.fiscal.position.template.csv
  addons/l10n_it/data/account_fiscal_position_tax_template_data.xml
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/l10n_it/data/report_invoice.xml
  addons/l10n_it_edi/__init__.py
  addons/l10n_it_edi/__manifest__.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/__init__.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_invoice.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/mail/static/src/components/composer/composer.xml
  addons/mail/static/src/models/composer/composer.js
  addons/mrp/models/stock_picking.py
  addons/payment/models/payment_acquirer.py
  addons/product_expiry/views/stock_quant_views.xml
  addons/purchase/models/purchase.py
  addons/web/static/src/scss/kanban_view.scss
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
Labels: 14.0

#17082 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/res_config_settings.py
  addons/account/views/account_portal_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_payment/views/account_portal_templates.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account.fiscal.position.template.csv
  addons/l10n_it/data/account_fiscal_position_tax_template_data.xml
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/l10n_it/data/report_invoice.xml
  addons/l10n_it_edi/__init__.py
  addons/l10n_it_edi/__manifest__.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/__init__.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_invoice.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/mail/static/src/component_hooks/use_component_to_model/use_component_to_model.js
  addons/mail/static/src/component_hooks/use_ref_to_model/use_ref_to_model.js
  addons/mail/views/mail_mail_views.xml
  addons/mail/views/mail_message_views.xml
  addons/mail/views/mail_notification_views.xml
  addons/payment/models/account_move.py
  addons/purchase/models/purchase.py
  addons/web/static/src/views/graph/graph_view.js
  addons/web/static/src/views/pivot/pivot_view.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/website_sale/views/templates.xml
Labels: 15.0

#17084 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/utils/google_calendar.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_au/data/account_tax_template_data.xml
  addons/l10n_it/data/report_invoice.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/mail/static/src/components/activity/activity.js
  addons/mail/static/src/models/activity/activity.js
  addons/website/static/src/snippets/s_popup/options.js
Labels: 14.0

#17085 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_sequence_mixin.py
  addons/calendar/static/src/models/activity/activity.js
  addons/im_livechat/static/src/components/composer/tests/composer_tests.js
  addons/im_livechat/static/src/models/composer_view/composer_view.js
  addons/l10n_au/data/account_tax_template_data.xml
  addons/mail/static/src/components/activity/activity.js
  addons/mail/static/src/components/composer/composer.xml
  addons/mail/static/src/models/activity/activity.js
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/mrp/models/stock_picking.py
  addons/pos_restaurant/static/src/js/Chrome.js
  addons/product_expiry/views/stock_quant_views.xml
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/src/js/backend/field_html.js
Labels: 15.0

#17097 Syncing from upstream odoo/odoo (staging.12.0)
  odoo/tools/cloc.py
Labels: staging.12.0

#17107 Syncing from upstream odoo/odoo (tmp.12.0)
  odoo/tools/cloc.py
Labels: tmp.12.0

#17113 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_unbuild.py
  addons/payment/models/payment_acquirer.py
  addons/purchase_stock/models/purchase.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_hr_recruitment/controllers/main.py
Labels: 14.0

#17114 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/l10n_ar/models/account_move.py
  addons/mail/controllers/discuss.py
  addons/payment/models/payment_transaction.py
  addons/project/models/project.py
  addons/project/tests/test_project_flow.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/test_website/static/tests/tours/replace_media.js
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_media.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_hr_recruitment/controllers/main.py
Labels: 15.0

#17116 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_unbuild.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_sale_wishlist/static/tests/tours/website_sale_wishlist_admin.js
  addons/website_sale_wishlist/tests/test_wishlist_process.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
Labels: 13.0

#17117 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.xml
  addons/repair/views/repair_views.xml
  addons/sale/models/sale.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move_line.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_sale_wishlist/static/tests/tours/website_sale_wishlist_admin.js
  addons/website_sale_wishlist/tests/test_wishlist_process.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  odoo/tests/common.py
Labels: 14.0

#17120 Syncing from upstream odoo/odoo (staging.13.0)
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_unbuild.py
  addons/purchase_stock/models/purchase.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website_hr_recruitment/controllers/main.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_sale_wishlist/static/tests/tours/website_sale_wishlist_admin.js
  addons/website_sale_wishlist/tests/test_wishlist_process.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
Labels: staging.13.0

#17121 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_unbuild.py
  addons/payment/models/payment_acquirer.py
  addons/purchase_stock/models/purchase.py
  addons/repair/views/repair_views.xml
  addons/sale/models/sale.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/models/stock.py
  addons/stock/models/stock_move_line.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_hr_recruitment/controllers/main.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_sale_wishlist/static/tests/tours/website_sale_wishlist_admin.js
  addons/website_sale_wishlist/tests/test_wishlist_process.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  odoo/tests/common.py
Labels: staging.14.0

#17124 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/im_livechat/static/src/components/composer/tests/composer_tests.js
  addons/im_livechat/static/src/models/composer_view/composer_view.js
  addons/l10n_ar/models/account_move.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/mail/static/src/components/composer/composer.xml
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_restaurant/static/src/js/Chrome.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_hr_recruitment/controllers/main.py
  doc/cla/individual/TeoGoddet.md
Labels: tmp.saas-15.1

#17126 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/calendar/static/src/models/activity.js
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/mail/controllers/discuss.py
  addons/mail/static/src/models/activity.js
  addons/mail/static/src/models/activity_view.js
  addons/mrp/static/src/js/mrp_field_one2many_with_copy.js
  addons/mrp/tests/test_traceability.py
  addons/payment/models/payment_transaction.py
  addons/pos_restaurant/static/src/js/Chrome.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/stock/models/stock_lot.py
  addons/stock/report/report_stock_forecasted.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/core/py_js/py_parser.js
  addons/web/static/src/core/py_js/py_utils.js
  addons/web/static/tests/core/domain_tests.js
  addons/web/static/tests/core/py_js/py_utils_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/tests/test_page.py
  addons/website_hr_recruitment/controllers/main.py
  doc/cla/individual/TeoGoddet.md
  odoo/addons/base/wizard/base_language_install.py
Labels: tmp.saas-15.3

#17130 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/l10n_ar/models/account_move.py
  addons/mail/controllers/discuss.py
  addons/mrp/static/src/js/mrp_field_one2many_with_copy.js
  addons/payment/models/payment_transaction.py
  addons/project/models/project.py
  addons/project/tests/test_project_flow.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_product_matrix/models/purchase.py
  addons/purchase_stock/models/purchase.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_stock_forecasted.xml
  addons/test_website/static/tests/tours/replace_media.js
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_media.py
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/core/py_js/py_parser.js
  addons/web/static/src/core/py_js/py_utils.js
  addons/web/static/tests/core/domain_tests.js
  addons/web/static/tests/core/py_js/py_utils_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_hr_recruitment/controllers/main.py
  doc/cla/corporate/vauxoo.md
  odoo/tests/common.py
Labels: tmp.15.0

#17131 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/website_twitter/static/src/img/api_key.png
  addons/website_twitter/views/res_config_settings_views.xml
Labels: 13.0

#17132 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/calendar/models/calendar_attendee.py
  addons/mail/static/src/models/messaging/messaging.js
  addons/web/static/src/js/core/dom.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/scss/website.scss
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/tests/test_ir_http.py
Labels: 14.0

#17133 Syncing from upstream odoo/odoo (15.0)
  addons/fleet/models/fleet_vehicle.py
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.xml
  addons/mail/static/src/models/attachment/attachment.js
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/repair/views/repair_views.xml
  addons/sale/models/sale_order.py
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website_twitter/static/src/img/api_key.png
  addons/website_twitter/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/tests/test_ir_http.py
Labels: 15.0

#17138 Syncing from upstream odoo/odoo (master)
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  odoo/addons/base/models/ir_binary.py
  odoo/addons/test_http/tests/test_static.py
Labels: master

#17111 [bt#19471] migrate fetchmail_outlook and microsoft_outlook from v12
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_company.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
Labels: 11.0.project_el_543

#17139 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/xml/account_reconciliation.xml
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_stage.py
  addons/crm/tests/test_crm_lead.py
  addons/crm_iap_lead/models/crm_iap_lead_mining_request.py
  addons/google_drive/i18n/google_drive.pot
  addons/google_drive/models/google_drive.py
  addons/google_drive/models/res_config_settings.py
  addons/google_drive/views/res_config_settings_views.xml
  addons/hr_attendance/models/hr_employee.py
  addons/hr_attendance/tests/test_hr_attendance_process.py
  addons/website/i18n/website.pot
  addons/website/static/src/xml/website.backend.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/static/src/js/website_sale_utils.js
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  doc/cla/corporate/metrum.md
  doc/cla/individual/KareemAbuzaid.md
Labels: 13.0

#17140 Syncing from upstream odoo/odoo (14.0)
  addons/account/views/report_invoice.xml
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_drive/i18n/google_drive.pot
  addons/google_drive/models/google_drive.py
  addons/google_drive/models/res_config_settings.py
  addons/google_drive/views/res_config_settings_views.xml
  addons/hr_attendance/models/hr_employee.py
  addons/hr_attendance/tests/test_hr_attendance_process.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_invoice.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_unbuild.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/website_twitter/static/src/img/api_key.png
  addons/website_twitter/views/res_config_settings_views.xml
  doc/cla/corporate/cloudition.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: 14.0

#17141 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/auth_totp/models/auth_totp.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/utils/google_calendar.py
  addons/google_drive/i18n/google_drive.pot
  addons/google_drive/models/google_drive.py
  addons/google_drive/models/res_config_settings.py
  addons/google_drive/views/res_config_settings_views.xml
  addons/hr/i18n/hr.pot
  addons/hr/models/hr_employee.py
  addons/hr_gamification/models/gamification.py
  addons/hr_recruitment/models/hr_job.py
  addons/mail/static/src/models/messaging/messaging.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_unbuild.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/project/report/project_report_views.xml
  addons/project/views/project_sharing_views.xml
  addons/project/views/project_views.xml
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
  addons/web/static/src/webclient/actions/action_service.js
  doc/cla/corporate/cloudition.md
  doc/cla/individual/afmipy.md
Labels: 15.0

#17145 [bt#19472] migrate fetchmail_outlook and microsoft_outlook from v12
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/base_config_settings.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/views/base_config_settings_views.xml
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/templates.xml
Labels: 10.0.project_th.test

#17146 [bt#19748][ADD] server: allow env variable to control HTTP socket timeout
  odoo/service/server.py
Labels: 10.0.project_th.test

#17143 [bt#19748][ADD] server: allow env variable to control HTTP socket timeout
  odoo/service/server.py
Labels: 10.0.project_th

#17147 Syncing from upstream odoo/odoo (13.0)
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
Labels: 13.0

#17148 Syncing from upstream odoo/odoo (14.0)
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_stage.py
  addons/crm/tests/common.py
  addons/crm/tests/test_crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/crm_iap_lead/models/crm_iap_lead_mining_request.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_move.py
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_form/views/snippets/snippets.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/static/src/js/website_sale_utils.js
  addons/website_sale/views/snippets/snippets.xml
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/metrum.md
  doc/cla/individual/KareemAbuzaid.md
Labels: 14.0

#17149 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_invoice.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_reverse_charge_xml.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_unbuild.py
  addons/web/static/src/core/utils/patch.js
  addons/web/static/src/legacy/js/public/public_root.js
  addons/web/static/tests/core/utils/patch_tests.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/website_page_options.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/static/src/js/website_sale_utils.js
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
Labels: 15.0

#17150 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/static/src/js/account_selection.js
  addons/account/static/src/scss/account_dashboard.scss
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/static/src/xml/account_type_selection.xml
  addons/account/views/account_account_views.xml
  addons/account/views/account_chart_template_views.xml
  addons/account/views/report_invoice.xml
  addons/account/wizard/setup_wizards_view.xml
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/mail/static/src/models/messaging.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/sale/tests/test_sale_pricelist.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/domain_selector/domain_selector_leaf_node.js
  addons/web/static/src/core/domain_selector/domain_selector_operators.js
  addons/web/static/src/core/domain_selector_dialog/domain_selector_dialog.js
  addons/web/static/src/core/domain_selector_dialog/domain_selector_dialog.xml
  addons/web/static/src/core/utils/patch.js
  addons/web/static/src/views/fields/domain/domain_field.js
  addons/web/static/src/views/fields/domain/domain_field.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/utils/patch_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web_editor/static/src/components/media_dialog/file_selector.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/tests/test_form_create.py
Labels: master

#17157 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/repair/models/repair.py
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/tests/test_converter.py
  doc/cla/individual/angelmoya.md
Labels: 13.0

#17158 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/repair/models/repair.py
  addons/website/static/src/js/editor/snippets.options.js
Labels: 14.0

#17159 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_format.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/coupon/views/coupon_program_views.xml
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/models/crm_stage.py
  addons/crm/tests/common.py
  addons/crm/tests/test_crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/crm/views/crm_lead_views.xml
  addons/crm_iap_mine/models/crm_iap_lead_mining_request.py
  addons/event/views/event_views.xml
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/views/mailing_contact_views.xml
  addons/mass_mailing/views/mailing_list_views.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/report/mrp_production_templates.xml
  addons/product/views/product_views.xml
  addons/project/views/project_views.xml
  addons/repair/models/repair.py
  addons/sale_stock/views/sale_order_views.xml
  addons/sales_team/views/crm_team_views.xml
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/utm/views/utm_campaign_views.xml
  addons/web/static/src/legacy/js/core/dom.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/scss/website.scss
  doc/cla/corporate/metrum.md
  doc/cla/individual/KareemAbuzaid.md
  odoo/addons/base/views/res_partner_views.xml
Labels: 15.0

#17161 Syncing from upstream odoo/odoo (13.0)
  addons/crm/views/crm_lead_views.xml
  addons/website/models/ir_ui_view.py
  addons/website/tests/test_views.py
Labels: 13.0

#17166 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_account_move_reconcile.py
  addons/base_import/static/src/js/import_action.js
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/utils/google_calendar.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/common.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/models/sale.py
  addons/sale_management/models/sale_order.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_controller.js
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_stock/models/sale_order.py
  addons/web/static/src/js/control_panel/custom_filter_item.js
  addons/web/static/tests/control_panel/custom_filter_item_tests.js
  addons/website_sale/models/sale_order.py
  doc/cla/individual/angelmoya.md
  doc/cla/individual/gordon.md
Labels: 14.0

#17167 Syncing from upstream odoo/odoo (15.0)
  addons/base_import/static/src/legacy/js/import_action.js
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_multicompany.py
  addons/crm/tests/test_performances.py
  addons/crm/views/res_partner_views.xml
  addons/google_drive/models/google_drive.py
  addons/hr_attendance/i18n/hr_attendance.pot
  addons/hr_attendance/models/hr_employee.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/payment_stripe/models/payment_acquirer.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_controller.js
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/web/static/src/legacy/js/control_panel/custom_filter_item.js
  addons/web/static/src/legacy/js/libs/fullcalendar.js
  addons/web/static/tests/legacy/control_panel/custom_filter_item_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/ir_ui_view.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/src/xml/website.backend.xml
  addons/website/tests/test_views.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_wishlist/static/src/js/website_sale_wishlist.js
  addons/website_sale_wishlist/static/tests/tours/website_sale_wishlist_admin.js
  addons/website_sale_wishlist/tests/test_wishlist_process.py
Labels: 15.0

#17169 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/static/src/js/models.js
Labels: 13.0

#17171 Syncing from upstream odoo/odoo (15.0)
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/product_matrix/models/product_template.py
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/scss/wysiwyg_iframe.scss
  addons/website_sale_stock_wishlist/views/templates.xml
  doc/cla/individual/gordon.md
  odoo/addons/base/models/ir_fields.py
Labels: 15.0

#17173 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account_bank_statement_import/account_bank_statement_import.py
  addons/purchase/models/purchase.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
Labels: 13.0

#17174 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/crm/views/crm_lead_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
Labels: 14.0

#17175 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/account_move_views.xml
  addons/crm/views/crm_lead_views.xml
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/utils/google_calendar.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/sale_order_line.py
  addons/sale_management/models/sale_order.py
  addons/sale_stock/models/sale_order.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/web/static/src/legacy/js/views/calendar/calendar_view.js
  addons/web/static/src/legacy/scss/fields.scss
  addons/website/static/src/xml/website_form_editor.xml
  addons/website_sale/models/product_product.py
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/tests/test_website_sale_cart.py
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/profiler.py
Labels: 15.0

#17177 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/board/static/src/js/board_view.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/__init__.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/point_of_sale/tests/test_pos_basic_config.py
Labels: 13.0

#17178 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_it_edi/data/invoice_it_template.xml
Labels: 14.0

#17179 Syncing from upstream odoo/odoo (15.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/project/models/project.py
  addons/purchase_stock/models/product.py
  addons/web/views/report_templates.xml
Labels: 15.0

#17184 [bt#19468][t129516] Allow payment of invoices with 'posted_sent' state
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
Labels: 13.0.project_sv_559

#17185 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_in/views/res_partner_views.xml
  addons/stock/models/stock_picking.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: 13.0

#17186 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/board/static/src/js/board_view.js
  addons/hr/models/res_users.py
  addons/l10n_in/views/res_partner_views.xml
  addons/mrp/views/stock_move_views.xml
  addons/purchase/models/purchase.py
  addons/stock/models/stock_package_level.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_sale/static/src/snippets/s_products_searchbar/000.js
  addons/website_sale/static/src/xml/website_sale_utils.xml
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_homepage.xml
  doc/cla/corporate/allegro-it.md
  odoo/tools/image.py
Labels: 14.0

#17187 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/barcodes/static/src/js/barcode_form_view.js
  addons/barcodes/static/tests/barcode_tests.js
  addons/board/static/src/legacy/js/board_view.js
  addons/hr/models/res_users.py
  addons/hr_contract/i18n/hr_contract.pot
  addons/hr_contract/models/hr_contract_type.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/wizard/account_payment_register.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_in/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/common.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_procurement.py
  addons/mrp/views/stock_move_views.xml
  addons/payment/models/payment_transaction.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_create_picking.py
  addons/stock/models/stock_package_level.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/tests/test_packing.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/tests/test_get_current_website.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  doc/cla/corporate/allegro-it.md
  odoo/addons/base/models/res_currency.py
  odoo/tools/image.py
Labels: 15.0

#17189 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_cl/models/account_move.py
  addons/payment_payulatam/models/payment.py
Labels: 13.0

#17190 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/tests/test_account_bank_statement.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/__init__.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/mrp/models/stock_orderpoint.py
  addons/payment_payulatam/models/payment.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/js/db.js
  addons/product/models/product.py
  addons/product/tests/test_variants.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_orderpoint.py
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/common.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_image.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
Labels: 14.0

#17191 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/account_payment_view.xml
  addons/barcodes/models/barcode_nomenclature.py
  addons/barcodes/tests/test_barcode_nomenclature.py
  addons/bus/static/src/js/crosstab_bus.js
  addons/bus/static/tests/bus_tests.js
  addons/l10n_gcc_invoice_stock_account/__init__.py
  addons/l10n_gcc_invoice_stock_account/__manifest__.py
  addons/l10n_gcc_invoice_stock_account/views/report_invoice.xml
  addons/mrp/models/stock_orderpoint.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientDetailsEdit.js
  addons/project/static/src/js/project_kanban.js
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/wizard/stock_request_count.py
  addons/web/static/src/legacy/scss/daterangepicker.scss
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_payment/views/snippets/snippets.xml
  doc/cla/individual/lin-ww.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/addons/base/tests/test_reports.py
Labels: 15.0

#17193 Syncing from upstream odoo/odoo (13.0)
  addons/stock/models/product.py
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  doc/cla/individual/AndrewChau.md
Labels: 13.0

#17194 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
Labels: 14.0

#17195 Syncing from upstream odoo/odoo (15.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/__init__.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/web/static/src/legacy/js/_deprecated/basic_fields.js
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/scss/web_calendar.scss
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_editor/views/snippets.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/src/snippets/s_searchbar/000.xml
  addons/website/views/snippets/snippets.xml
  addons/website_sale/static/src/xml/website_sale_utils.xml
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_homepage.xml
Labels: 15.0

#17199 Syncing from upstream odoo/odoo (master)
  addons/pos_restaurant/static/src/js/Screens/FloorScreen/FloorScreen.js
  addons/pos_restaurant/static/src/js/Screens/TicketScreen.js
  addons/pos_restaurant/static/src/xml/Screens/TicketScreen.xml
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  doc/cla/individual/AndrewChau.md
Labels: master
