Repository brain-tec/odoo, pull requests merged in 2022-10, with the labels that each got.

#17544 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/mrp_workorder.py
Labels: 13.0

#17545 Syncing from upstream odoo/odoo (14.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_byproduct.py
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_currency.py
Labels: 14.0

#17546 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/stock/views/stock_quant_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/tests/test_controller.py
  odoo/addons/base/models/res_currency.py
Labels: 15.0

#17549 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/i18n/account.pot
  addons/account/views/report_invoice.xml
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/mrp/models/mrp_workorder.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_currency.py
Labels: staging.13.0

#17550 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_payment_term.py
  addons/account/wizard/account_resequence.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_stock/models/product.py
  addons/purchase_stock/models/purchase.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/js/core/dom.js
  addons/web/static/src/js/libs/jquery.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/seo.js
  addons/website_sale/controllers/main.py
  doc/cla/corporate/manatec.md
  doc/cla/individual/miikanissi.md
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_currency.py
Labels: staging.14.0

#17554 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mrp/models/mrp_workorder.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_event_booth_sale/models/sale_order.py
  addons/website_event_sale/models/sale_order.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/views/templates.xml
  doc/cla/individual/vvanneri-ia.md
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-15.2

#17555 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/crm/tests/test_performances.py
  addons/mrp/models/mrp_workorder.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  doc/cla/individual/vvanneri-ia.md
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-15.3

#17556 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/mrp/models/mrp_workorder.py
Labels: tmp.13.0

#17557 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_byproduct.py
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_currency.py
Labels: tmp.14.0

#17558 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/stock/views/stock_quant_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/tests/test_controller.py
  odoo/addons/base/models/res_currency.py
Labels: tmp.15.0

#17565 [bt#20455] Addid missing changes from cherry pick.
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
Labels: enhancement, 13.0.project_pm_597

#17566 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  doc/cla/corporate/comunitea.md
Labels: 13.0

#17567 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/views/report_invoice.xml
  addons/hr/static/src/models/employee/employee.js
  addons/hr/static/src/models/messaging/messaging.js
  addons/mrp_account/models/mrp_production.py
  addons/mrp_account/tests/test_mrp_account.py
  addons/payment_alipay/models/payment.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
Labels: 14.0

#17568 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/i18n/fr_BE.po
  addons/account/views/report_invoice.xml
  addons/account_debit_note/i18n/fr_BE.po
  addons/gamification_sale_crm/i18n/fr_BE.po
  addons/l10n_it_edi/models/res_partner.py
  addons/payment/i18n/fr_BE.po
  addons/project/static/src/js/project_form.js
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  odoo/addons/base/i18n/fr_BE.po
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_ir_mail_server.py
Labels: 15.0

#17583 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/point_of_sale.xml
Labels: 13.0

#17584 Syncing from upstream odoo/odoo (14.0)
  addons/barcodes/models/barcodes.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mail/static/src/components/message/message.scss
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/customer_facing_display.xml
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/corporate/comunitea.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/test_reports.py
Labels: 14.0

#17585 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mail/static/src/components/message/message.scss
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment_alipay/models/payment_transaction.py
  addons/payment_alipay/tests/test_alipay.py
  addons/purchase_stock/models/purchase.py
  addons/web/static/src/legacy/scss/report.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/corporate/comunitea.md
  doc/cla/individual/atul-patel.md
  odoo/tools/mail.py
Labels: 15.0

#17588 [bt#20474] Re: Connection Test Failed - Outgoing PM Server
  .tx/config
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/i18n/fetchmail_gmail.pot
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: 13.0.project_pm_597

#17589 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_nz/data/account_tax_template_data.xml
Labels: 14.0

#17590 Syncing from upstream odoo/odoo (15.0)
  addons/hr/static/src/models/employee/employee.js
  addons/hr/static/src/models/messaging/messaging.js
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_rs/__init__.py
  addons/l10n_rs/__manifest__.py
  addons/l10n_rs/data/account.account.template.csv
  addons/l10n_rs/data/account.group.template.csv
  addons/l10n_rs/data/account_chart_template_configure_data.xml
  addons/l10n_rs/data/account_chart_template_data.xml
  addons/l10n_rs/data/account_tax_group_data.xml
  addons/l10n_rs/data/account_tax_report_data.xml
  addons/l10n_rs/data/account_tax_template_data.xml
  addons/l10n_rs/data/fiscal_position_data.xml
  addons/l10n_rs/data/l10n_rs_chart_data.xml
  addons/l10n_rs/data/menuitem_data.xml
  addons/l10n_rs/demo/demo_company.xml
  addons/l10n_rs/models/__init__.py
  addons/l10n_rs/models/account_move.py
  addons/l10n_rs/models/res_partner.py
  addons/l10n_rs/views/account_move.xml
  addons/l10n_rs/views/report_invoice.xml
  addons/l10n_rs/views/res_partner.xml
  addons/mail/views/mail_template_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/static/src/xml/CustomerFacingDisplay/CustomerFacingDisplayOrder.xml
  addons/project/static/src/scss/project_sharing/chatter.scss
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
Labels: 15.0

#17594 Syncing from upstream odoo/odoo (staging.saas-15.3)
  addons/account/i18n/account.pot
  addons/account/views/report_invoice.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_it_edi/models/res_partner.py
  addons/mail/static/src/components/message/message.scss
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment_alipay/models/payment_transaction.py
  addons/payment_alipay/tests/test_alipay.py
  addons/point_of_sale/static/src/xml/CustomerFacingDisplay/CustomerFacingDisplayOrder.xml
  addons/project/models/project.py
  addons/project/static/src/scss/project_sharing/chatter.scss
  addons/purchase_stock/models/purchase.py
  addons/resource/models/resource.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_resource/tests/test_resource.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/legacy/scss/report.scss
  addons/website/models/ir_module_module.py
  doc/cla/corporate/comunitea.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: staging.saas-15.3

#17595 Syncing from upstream odoo/odoo (staging.13.0)
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/point_of_sale.xml
Labels: staging.13.0

#17596 Syncing from upstream odoo/odoo (staging.14.0)
  addons/barcodes/models/barcodes.py
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_nz/data/account_tax_template_data.xml
  addons/mail/static/src/components/message/message.scss
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/customer_facing_display.xml
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/corporate/comunitea.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/test_reports.py
Labels: staging.14.0

#17599 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/delivery_stock_picking_batch/models/stock_picking.py
  addons/hr/static/src/models/employee/employee.js
  addons/hr/static/src/models/messaging/messaging.js
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_it_edi/models/res_partner.py
  addons/mail/static/src/components/message/message.scss
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment_alipay/models/payment_transaction.py
  addons/payment_alipay/tests/test_alipay.py
  addons/point_of_sale/static/src/xml/CustomerFacingDisplay/CustomerFacingDisplayOrder.xml
  addons/project/models/project.py
  addons/project/static/src/scss/project_sharing/chatter.scss
  addons/purchase_stock/models/purchase.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/stock/models/stock_picking.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/stock_picking_batch/wizard/__init__.py
  addons/stock_picking_batch/wizard/stock_backorder_confirmation.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/scss/report.scss
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/corporate/comunitea.md
  odoo/tools/mail.py
Labels: tmp.saas-15.2

#17600 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/i18n/account.pot
  addons/account/views/report_invoice.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_it_edi/models/res_partner.py
  addons/mail/static/src/components/message/message.scss
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment_alipay/models/payment_transaction.py
  addons/payment_alipay/tests/test_alipay.py
  addons/point_of_sale/static/src/xml/CustomerFacingDisplay/CustomerFacingDisplayOrder.xml
  addons/project/models/project.py
  addons/project/static/src/scss/project_sharing/chatter.scss
  addons/purchase_stock/models/purchase.py
  addons/resource/models/resource.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_resource/tests/test_resource.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/legacy/scss/report.scss
  addons/website/models/ir_module_module.py
  doc/cla/corporate/comunitea.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: tmp.saas-15.3

#17601 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/point_of_sale.xml
Labels: tmp.13.0

#17602 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/barcodes/models/barcodes.py
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_nz/data/account_tax_template_data.xml
  addons/mail/static/src/components/message/message.scss
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/views/customer_facing_display.xml
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/corporate/comunitea.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/test_reports.py
Labels: tmp.14.0

#17603 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_journal.py
  addons/hr/static/src/models/employee/employee.js
  addons/hr/static/src/models/messaging/messaging.js
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_rs/__init__.py
  addons/l10n_rs/__manifest__.py
  addons/l10n_rs/data/account.account.template.csv
  addons/l10n_rs/data/account.group.template.csv
  addons/l10n_rs/data/account_chart_template_configure_data.xml
  addons/l10n_rs/data/account_chart_template_data.xml
  addons/l10n_rs/data/account_tax_group_data.xml
  addons/l10n_rs/data/account_tax_report_data.xml
  addons/l10n_rs/data/account_tax_template_data.xml
  addons/l10n_rs/data/fiscal_position_data.xml
  addons/l10n_rs/data/l10n_rs_chart_data.xml
  addons/l10n_rs/data/menuitem_data.xml
  addons/l10n_rs/demo/demo_company.xml
  addons/l10n_rs/models/__init__.py
  addons/l10n_rs/models/account_move.py
  addons/l10n_rs/models/res_partner.py
  addons/l10n_rs/views/account_move.xml
  addons/l10n_rs/views/report_invoice.xml
  addons/l10n_rs/views/res_partner.xml
  addons/mail/static/src/components/message/message.scss
  addons/mail/views/mail_template_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment_alipay/models/payment_transaction.py
  addons/payment_alipay/tests/test_alipay.py
  addons/point_of_sale/static/src/xml/CustomerFacingDisplay/CustomerFacingDisplayOrder.xml
  addons/project/static/src/scss/project_sharing/chatter.scss
  addons/purchase_stock/models/purchase.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/scss/report.scss
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/corporate/comunitea.md
  doc/cla/individual/atul-patel.md
  odoo/tools/mail.py
Labels: tmp.15.0

#17605 Syncing from upstream odoo/odoo (13.0)
  addons/sale/models/sale.py
Labels: 13.0

#17606 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_data.xml
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/mail/models/mail_message.py
Labels: 14.0

#17607 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account_edi/models/account_journal.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  doc/cla/sign-cla.md
Labels: 15.0

#17610 Syncing from upstream odoo/odoo (13.0)
  addons/account/views/report_invoice.xml
Labels: 13.0

#17611 Syncing from upstream odoo/odoo (14.0)
  addons/account/views/report_invoice.xml
  addons/l10n_eu_service/tests/test_oss.py
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/stock_picking_batch/tests/test_batch_picking.py
Labels: 14.0

#17612 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/report_invoice.xml
  addons/account/views/res_config_settings_views.xml
  addons/l10n_eu_oss/tests/test_oss.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/l10n_sa_pos/static/src/js/models.js
  addons/l10n_sa_pos/static/src/xml/OrderReceipt.xml
  addons/project/views/project_views.xml
  addons/sale_coupon/models/sale_order.py
  addons/stock/models/product.py
  addons/web/static/src/legacy/utils.js
Labels: 15.0

#17615 Syncing from upstream odoo/odoo (staging.saas-15.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_journal.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mail/views/mail_template_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/sale_project/models/project.py
  addons/stock/models/product.py
  addons/web/static/src/legacy/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/tools.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/views/website_slides_templates_course.xml
  doc/cla/individual/atul-patel.md
Labels: staging.saas-15.3

#17616 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/views/report_invoice.xml
  addons/sale/models/sale.py
Labels: staging.13.0

#17617 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/views/report_invoice.xml
  addons/l10n_eu_service/tests/test_oss.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_data.xml
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mail/models/mail_message.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/stock_picking_batch/tests/test_batch_picking.py
Labels: staging.14.0

#17620 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_journal.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_eu_oss/tests/test_oss.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mail/views/mail_template_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/sale_coupon/models/sale_order.py
  addons/stock/models/product.py
  addons/web/static/src/legacy/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/individual/atul-patel.md
Labels: tmp.saas-15.2

#17621 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_journal.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mail/views/mail_template_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/sale_project/models/project.py
  addons/stock/models/product.py
  addons/web/static/src/legacy/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/tools.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/views/website_slides_templates_course.xml
  doc/cla/individual/atul-patel.md
Labels: tmp.saas-15.3

#17622 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/views/report_invoice.xml
  addons/sale/models/sale.py
Labels: tmp.13.0

#17623 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/views/report_invoice.xml
  addons/l10n_eu_service/tests/test_oss.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account_data.xml
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/ir_mail_server.py
  addons/mail/models/mail_message.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/stock_picking_batch/tests/test_batch_picking.py
Labels: tmp.14.0

#17631 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_nz/data/account_tax_template_data.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/tours/tour_utils.js
Labels: 15.0

#17634 Syncing from upstream odoo/odoo (13.0)
  addons/account_facturx/models/uom.py
  addons/payment_adyen_paybylink/models/payment_transaction.py
  doc/cla/individual/joanna350.md
Labels: 13.0

#17635 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/product.py
  addons/account/tests/common.py
  addons/account/views/product_view.xml
  addons/account_edi_facturx/models/uom.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/payment_adyen_paybylink/models/payment_transaction.py
  addons/sale/models/sale.py
  addons/website/models/theme_models.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  doc/cla/individual/joanna350.md
Labels: 14.0

#17647 Syncing from upstream odoo/odoo (12.0)
  addons/calendar/models/calendar.py
Labels: 12.0

#17648 Syncing from upstream odoo/odoo (15.0)
  addons/mail/models/ir_translation.py
  doc/cla/individual/benoit-bertholon.md
Labels: 15.0

#17649 Syncing from upstream odoo/odoo (16.0)
  addons/mail/static/src/models/emoji_grid_view.js
  addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
  addons/web/static/src/views/fields/progress_bar/progress_bar_field.xml
  doc/cla/individual/benoit-bertholon.md
  odoo/addons/base/views/ir_actions_views.xml
Labels: 16.0

#17650 Syncing from upstream odoo/odoo (master)
  addons/hr_holidays/static/src/views/view_dialog/form_view_dialog.js
  addons/hr_holidays/static/src/views/view_dialog/form_view_dialog.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/mail/static/src/components/emoji_grid_view/emoji_grid_view.js
  addons/mail/static/src/models/emoji_grid_view.js
  addons/project_timesheet_holidays/views/hr_holidays_views.xml
  addons/web/static/src/views/fields/progress_bar/progress_bar_field.scss
  addons/web/static/src/views/fields/progress_bar/progress_bar_field.xml
  doc/cla/individual/benoit-bertholon.md
Labels: master

#17652 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/es.po
  addons/account/i18n/es_MX.po
  addons/account/i18n/fr.po
  addons/account/i18n/hr.po
  addons/account/i18n/lt.po
  addons/account/i18n/sl.po
  addons/auth_totp/i18n/sl.po
  addons/auth_totp_portal/i18n/sl.po
  addons/event/i18n/es_MX.po
  addons/fleet/i18n/ru.po
  addons/hr/i18n/es_MX.po
  addons/hr_attendance/i18n/es_MX.po
  addons/hr_expense/i18n/es_MX.po
  addons/hr_holidays/i18n/es_MX.po
  addons/hr_presence/i18n/es_MX.po
  addons/hr_recruitment/i18n/es_MX.po
  addons/hr_skills/i18n/hu.po
  addons/hr_skills_slides/i18n/hu.po
  addons/hr_skills_survey/i18n/hu.po
  addons/hr_timesheet/i18n/hr.po
  addons/iap/i18n/id.po
  addons/im_livechat/i18n/es_MX.po
  addons/im_livechat/i18n/sl.po
  addons/lunch/i18n/es_MX.po
  addons/mail/i18n/nb.po
  addons/mass_mailing/i18n/zh_CN.po
  addons/mrp/i18n/nb.po
  addons/point_of_sale/i18n/es_MX.po
  addons/portal/i18n/hr.po
  addons/project/i18n/es_MX.po
  addons/project/i18n/hr.po
  addons/purchase_stock/i18n/hr.po
  addons/purchase_stock/i18n/lt.po
  addons/sale_stock/i18n/nb.po
  addons/sale_timesheet/i18n/hr.po
  addons/stock/i18n/ru.po
  addons/stock_account/i18n/es_MX.po
  addons/stock_landed_costs/i18n/es_MX.po
  addons/stock_picking_batch/i18n/lt.po
  addons/uom/i18n/ru.po
  addons/utm/i18n/fr.po
  addons/web/i18n/sl.po
  addons/web_editor/i18n/nb.po
  addons/website_event_track/i18n/fr.po
  addons/website_event_track_live/i18n/id.po
  addons/website_sale/i18n/es.po
  addons/website_sale/i18n/fr.po
  addons/website_sale/i18n/id.po
  addons/website_sale/i18n/ja.po
  addons/website_sale/i18n/sl.po
  addons/website_slides/i18n/es_MX.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/id.po
  odoo/addons/base/i18n/sl.po
Labels: 14.0

#17655 Syncing from upstream odoo/odoo (master)
  addons/hr_timesheet/models/project.py
  addons/project/views/project_views.xml
Labels: master

#17656 Syncing from upstream odoo/odoo (saas-12.3)
  addons/calendar/models/calendar.py
Labels: saas-12.3

#17658 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/product.py
  addons/mail/controllers/main.py
  addons/portal/controllers/mail.py
  addons/project/models/project.py
  addons/project/tests/test_project_base.py
  addons/survey/views/survey_question_views.xml
  addons/test_mail_full/tests/test_portal.py
  addons/web/static/src/js/core/dialog.js
  addons/web/static/tests/core/dialog_tests.js
  addons/web/static/tests/views/form_tests.js
Labels: 14.0

#17659 Syncing from upstream odoo/odoo (15.0)
  addons/crm/tests/test_crm_lead.py
  addons/hr/views/hr_job_views.xml
  addons/l10n_ar/data/account.account.template.csv
  addons/mail/controllers/mail.py
  addons/phone_validation/i18n/phone_validation.pot
  addons/phone_validation/models/mail_thread_phone.py
  addons/point_of_sale/models/product.py
  addons/portal/controllers/mail.py
  addons/project/models/project.py
  addons/project/tests/test_project_sharing.py
  addons/survey/views/survey_question_views.xml
  addons/test_mail_full/models/test_mail_models.py
  addons/test_mail_full/tests/__init__.py
  addons/test_mail_full/tests/test_mail_thread_phone.py
  addons/test_mail_full/tests/test_portal.py
  addons/website/static/src/js/editor/widget_link.js
  addons/website_sale_stock_wishlist/static/src/js/website_sale.js
Labels: 15.0

#17662 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_de/models/datev.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/web/static/src/js/apps.js
Labels: 14.0

#17663 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ae/__manifest__.py
  addons/l10n_ae_pos/__manifest__.py
  addons/l10n_de/models/datev.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/payment/utils.py
  addons/payment_stripe/models/payment_acquirer.py
  addons/payment_stripe/models/payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/project/models/project.py
  addons/project/tests/test_project_base.py
Labels: 15.0

#17664 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/views/account_move_views.xml
  addons/account/views/account_tax_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_test/views/accounting_assert_test_views.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/l10n_account_edi_ubl_cii_tests/tests/__init__.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_ar/data/account.account.template.csv
  addons/mail/controllers/mail.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/backend_components/activity_list_view/activity_list_view.xml
  addons/mail/static/src/models/message_action_view.js
  addons/mail/static/src/models/user_notification_manager.js
  addons/mail/static/src/views/form/form_renderer.js
  addons/payment/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_ogone/tests/test_ogone.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/point_of_sale/models/product.py
  addons/portal/controllers/mail.py
  addons/project/models/project.py
  addons/project/tests/test_project_sharing.py
  addons/sale_project/models/product.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/test_mail_full/tests/test_portal.py
  addons/web/static/src/core/checkbox/checkbox.js
  addons/web/static/src/core/ui/ui_service.js
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_renderer.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/settings_form_view/settings/settings_page.js
  addons/web/static/src/webclient/settings_form_view/settings/settings_page.xml
  addons/web/static/src/webclient/settings_form_view/settings_form_renderer.js
  addons/web/static/tests/core/checkbox_tests.js
  addons/web/static/tests/views/form/form_compiler_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  addons/website/static/src/js/editor/widget_link.js
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_format_address_mixin.py
  odoo/addons/base/tests/test_views.py
Labels: 16.0

#17666 Syncing from upstream odoo/odoo (13.0)
  addons/snailmail/models/snailmail_letter.py
Labels: 13.0

#17667 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_in/demo/product_demo.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/payment_stripe/models/payment.py
  addons/point_of_sale/static/src/css/pos.css
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/product/data/product_demo.xml
  addons/sale/data/product_product_demo.xml
  addons/stock/data/stock_demo.xml
  addons/web/static/lib/py.js/lib/py_extras.js
  addons/web/static/tests/core/py_utils_tests.js
Labels: 14.0

#17668 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/product_view.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/point_of_sale/static/src/css/pos.css
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/legacy/js/core/dialog.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web/static/tests/legacy/core/dialog_tests.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
Labels: 15.0

#17669 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/l10n_de/models/datev.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mail/static/src/models/suggested_recipient_info.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/payment/utils.py
  addons/payment_stripe/models/payment_provider.py
  addons/payment_stripe/models/payment_transaction.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/ProductsWidgetControlPanel.xml
  addons/pos_restaurant/static/src/js/ChromeWidgets/TicketButton.js
  addons/sale_timesheet/report/timesheets_analysis_report.py
  addons/test_website/static/tests/tours/image_link.js
  addons/web/static/lib/py.js/lib/py_extras.js
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/settings_form_view/settings_confirmation_dialog.xml
  addons/web/static/tests/core/confirmation_dialog_tests.js
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web/static/tests/helpers/utils.js
  addons/web/static/tests/legacy/core/py_utils_tests.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/systray_items/edit_website.xml
  addons/website/static/src/systray_items/translate_website.xml
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/edit_megamenu.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_flow.js
  addons/website_livechat/static/tests/tours/website_livechat_common.js
  odoo/addons/base/views/ir_model_views.xml
  odoo/addons/base/wizard/base_import_language_views.xml
  odoo/cli/templates/default/__manifest__.py.template
Labels: 16.0

#17670 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/bus/static/tests/helpers/mock_python_environment.js
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/l10n_de/models/datev.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mail/static/src/models/suggested_recipient_info.js
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/ProductsWidgetControlPanel.xml
  addons/web/static/lib/py.js/lib/py_extras.js
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/graph/graph_controller.js
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/src/views/graph/graph_view.js
  addons/web/static/src/views/kanban/kanban_renderer.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/pivot/pivot_controller.js
  addons/web/static/src/views/pivot/pivot_model.js
  addons/web/static/src/views/pivot/pivot_view.js
  addons/web/static/src/views/utils.js
  addons/web/static/src/views/widgets/pie_chart/pie_chart.js
  addons/web/static/src/views/widgets/pie_chart/pie_chart.xml
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web/static/tests/helpers/utils.js
  addons/web/static/tests/legacy/core/py_utils_tests.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/form/form_compiler_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_flow.js
  addons/website_livechat/static/tests/tours/website_livechat_common.js
  odoo/__main__.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_format_address_mixin.py
  odoo/addons/base/tests/test_views.py
  odoo/netsvc.py
Labels: master

#17671 Syncing from upstream odoo/odoo (13.0)
  addons/web/static/src/js/views/kanban/kanban_model.js
  addons/web/static/tests/helpers/mock_server.js
  odoo/http.py
Labels: 13.0

#17672 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_reconcile.py
  addons/delivery/models/sale_order.py
  addons/mrp/models/mrp_production.py
  addons/snailmail/models/snailmail_letter.py
  addons/web/static/src/js/fields/abstract_field.js
  addons/web/static/src/js/views/kanban/kanban_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/menu.js
  odoo/http.py
Labels: 14.0

#17673 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_syscohada/__manifest__.py
  addons/l10n_syscohada/data/account.account.template.csv
  addons/l10n_syscohada/data/menuitem_data.xml
  addons/l10n_syscohada/demo/demo_company.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/snailmail/models/snailmail_letter.py
  addons/website_livechat/models/mail_channel.py
Labels: 15.0

#17674 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/views/account_reconcile_model_views.xml
  addons/account/views/product_view.xml
  addons/calendar/static/src/scss/calendar.scss
  addons/calendar/static/src/views/attendee_calendar/year/attendee_calendar_year_popover.js
  addons/hr/static/src/scss/hr.scss
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/src/views/calendar/calendar_renderer.scss
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_recruitment/views/hr_department_views.xml
  addons/l10n_nz/data/account_tax_report_data.xml
  addons/mail/static/src/models/attachment_delete_confirm_view.js
  addons/mail/static/src/models/chatter.js
  addons/mail/static/src/models/emoji_search_bar_view.js
  addons/mail/static/src/models/file_uploader.js
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/payment/models/payment_token.py
  addons/payment/views/payment_token_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/project/views/res_config_settings_views.xml
  addons/sale_loyalty/i18n/sale_loyalty.pot
  addons/sale_loyalty/models/sale_order.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/snailmail/models/snailmail_letter.py
  addons/web/static/src/search/search_panel/search_panel.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/calendar/calendar_renderer.scss
  addons/web/static/src/views/calendar/calendar_year/calendar_year_popover.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_popover.scss
  addons/web/static/src/views/calendar/calendar_year/calendar_year_popover.xml
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_popover_tests.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
  addons/website_livechat/models/mail_channel.py
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/models/slide_channel.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/views/ir_attachment_views.xml
Labels: 16.0

#17677 Syncing from upstream odoo/odoo (15.0)
  addons/mrp/models/mrp_production.py
  addons/pos_gift_card/static/src/js/GiftCardPopup.js
  addons/stock/models/stock_move.py
  addons/web/static/src/legacy/action_adapters.js
  addons/web/static/src/legacy/js/fields/abstract_field.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/menu.js
  doc/cla/corporate/trescloud.md
Labels: 15.0

#17680 Syncing from upstream odoo/odoo (staging.12.0)
  addons/calendar/models/calendar.py
Labels: staging.12.0

#17685 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/calendar/models/calendar.py
Labels: tmp.saas-12.3

#17688 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/calendar/models/calendar.py
Labels: tmp.12.0

#17696 Syncing from upstream odoo/odoo (master)
  doc/cla/corporate/trescloud.md
Labels: master

#17698 Syncing from upstream odoo/odoo (14.0)
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_cost.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/pos_restaurant/models/pos_order.py
  addons/snailmail/models/snailmail_letter.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  odoo/addons/base/tests/test_image.py
  odoo/fields.py
  odoo/tools/image.py
Labels: 14.0

#17699 Syncing from upstream odoo/odoo (15.0)
  addons/account/tests/common.py
  addons/base_import/tests/test_base_import.py
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_cost.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_report.py
  addons/snailmail/models/snailmail_letter.py
  addons/snailmail/static/src/js/snailmail_external_layout.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/web/static/src/legacy/js/views/kanban/kanban_model.js
  addons/web/static/src/legacy/js/views/sample_server.js
  addons/web/static/src/views/helpers/sample_server.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_tour/models/tour.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
  addons/website/views/snippets/snippets.xml
  addons/website_sale/models/product_template.py
  addons/website_sale/views/templates.xml
Labels: 15.0

#17700 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/account/models/account_report.py
  addons/account/models/company.py
  addons/account/models/res_config_settings.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/hr/views/hr_employee_views.xml
  addons/hr_attendance/static/src/xml/attendance.xml
  addons/hr_holidays_attendance/views/hr_employee_views.xml
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ae/__manifest__.py
  addons/l10n_ae_pos/__manifest__.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mail/static/src/components/emoji_grid_loading_screen/emoji_grid_loading_screen.js
  addons/mail/static/src/components/emoji_grid_loading_screen/emoji_grid_loading_screen.xml
  addons/mail/static/src/components/emoji_grid_search_no_content_view/emoji_grid_search_no_content_view.xml
  addons/mail/static/src/components/emoji_grid_view/emoji_grid_view.xml
  addons/mail/static/src/models/emoji_grid_loading_screen.js
  addons/mail/static/src/models/emoji_grid_view.js
  addons/mrp/models/mrp_workorder.py
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/pos_restaurant/models/pos_order.py
  addons/pos_restaurant/static/src/js/Screens/TicketScreen.js
  addons/project/i18n/project.pot
  addons/project/static/src/views/burndown_chart/burndown_chart_model.js
  addons/project/views/project_sharing_views.xml
  addons/sale_loyalty/i18n/sale_loyalty.pot
  addons/sale_loyalty/models/sale_order.py
  addons/sale_timesheet/controllers/portal.py
  addons/sale_timesheet/views/sale_timesheet_portal_templates.xml
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_package_type_view.xml
  addons/web/static/src/legacy/js/views/view_registry.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/widgets/attach_document/attach_document.js
  addons/web/static/tests/helpers/legacy.js
  addons/web/static/tests/views/widgets/attach_document_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_tour/models/tour.py
  addons/website_forum/views/forum.xml
  addons/website_sale_stock_wishlist/static/src/js/variant.js
  odoo/addons/base/tests/test_res_config.py
Labels: 16.0

#17702 Syncing from upstream odoo/odoo (13.0)
  odoo/models.py
Labels: 13.0

#17703 Syncing from upstream odoo/odoo (14.0)
  addons/website/models/assets.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website/static/src/scss/secondary_variables.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/website_templates.xml
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_slides/models/slide_channel.py
Labels: 14.0

#17704 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_reconcile.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_uninstall.py
  addons/l10n_in/demo/product_demo.xml
  addons/l10n_sa_invoice/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/l10n_uk/__manifest__.py
  addons/mail/models/ir_model.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_uninstall.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/product/data/product_demo.xml
  addons/sale/data/product_product_demo.xml
  addons/stock/data/stock_demo.xml
  addons/stock/report/report_deliveryslip.xml
  addons/web/static/lib/py.js/lib/py_extras.js
  addons/web/static/src/legacy/js/components/action_menus.js
  addons/web/static/tests/legacy/core/py_utils_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/models/slide_channel.py
  odoo/http.py
  odoo/modules/registry.py
Labels: 15.0

#17707 Syncing from upstream odoo/odoo (13.0)
  addons/snailmail/models/snailmail_letter.py
  addons/website_blog/controllers/main.py
Labels: 13.0

#17708 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/web_editor/static/src/js/editor/rte.js
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/rte.summernote.js
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/snippets/s_company_team.xml
  addons/website_blog/views/website_blog_components.xml
  addons/website_form/controllers/main.py
  odoo/models.py
Labels: 14.0

#17709 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_bank_statement.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/models/mail_channel.py
  addons/mail/tests/test_mail_channel.py
  addons/web/static/src/legacy/js/apps.js
  addons/website/i18n/website.pot
  addons/website/models/assets.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/primary_variables.scss
  addons/website/static/src/scss/secondary_variables.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/xml/website.editor.xml
  addons/website/views/website_templates.xml
  addons/website_blog/views/website_blog_components.xml
  odoo/models.py
Labels: 15.0

#17710 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_uninstall.py
  addons/l10n_in/demo/product_demo.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_channel.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_channel.py
  addons/mail/tests/test_uninstall.py
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/product/data/product_demo.xml
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/common.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_requisition_stock/tests/test_purchase_requisition_stock.py
  addons/purchase_stock/models/purchase.py
  addons/sale/data/product_demo.xml
  addons/stock/data/stock_demo.xml
  addons/survey/i18n/survey.pot
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/legacy/js/widgets/translation_dialog.js
  addons/web/static/src/legacy/scss/daterangepicker.scss
  addons/web/static/src/search/control_panel/control_panel.scss
  addons/web/static/src/views/fields/daterange/daterange_field.js
  addons/web/static/src/views/fields/formatters.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/fields/translation_dialog.js
  addons/web/static/src/views/form/control_panel/form_control_panel.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/search/search_bar_tests.js
  addons/web/static/tests/views/fields/char_field_tests.js
  addons/web/static/tests/views/fields/date_field_tests.js
  addons/web/static/tests/views/fields/daterange_field_tests.js
  addons/web/static/tests/views/fields/formatters_tests.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  odoo/http.py
  odoo/models.py
Labels: 16.0

#17713 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/calendar/models/calendar.py
Labels: staging.saas-12.3

#17725 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/purchase_stock/models/purchase.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_stock/models/sale_order.py
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/website/static/src/js/menu/content.js
  addons/website_blog/controllers/main.py
Labels: 14.0

#17726 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/stock/views/stock_quant_views.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/website/controllers/form.py
  addons/website/static/src/js/menu/edit.js
  addons/website/views/snippets/s_company_team.xml
  addons/website_sale/static/src/js/website_sale.editor.js
Labels: 15.0

#17729 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/mrp_bom.py
  addons/purchase/views/purchase_views.xml
Labels: 13.0

#17730 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/account_move.py
  addons/sale_mrp/models/sale.py
  addons/snailmail/models/snailmail_letter.py
  addons/website/static/src/snippets/s_table_of_content/000.scss
Labels: 14.0

#17731 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fr_pos_cert/static/src/js/NumpadWidget.js
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/point_of_sale/static/src/js/models.js
  addons/project/controllers/portal.py
  addons/purchase_stock/models/purchase.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_stock/models/sale_order.py
  addons/snailmail/models/snailmail_letter.py
  addons/web/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/static/src/js/menu/content.js
  addons/website_blog/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  odoo/addons/base/tests/test_image.py
  odoo/fields.py
  odoo/tools/image.py
Labels: 15.0

#17737 Syncing from upstream odoo/odoo (master)
  addons/fleet/models/fleet_vehicle.py
  addons/mail/static/src/components/activity/activity.xml
  addons/product_margin/models/product_product.py
  addons/resource/models/resource.py
  addons/website/models/ir_http.py
  addons/website/models/website.py
  addons/website/static/src/snippets/s_table_of_content/000.scss
  odoo/addons/base/controllers/rpc.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/models.py
  odoo/addons/test_http/tests/test_misc.py
  odoo/http.py
Labels: master

#17739 Syncing from upstream odoo/odoo (15.0)
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/tests/test_stockvaluation.py
Labels: 15.0
