Repository brain-tec/odoo, pull requests merged in 2022-02, with the labels that each got.

#16079 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_cl/models/res_partner.py
  addons/web_tour/static/src/js/tip.js
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
Labels: 13.0

#16080 Syncing from upstream odoo/odoo (14.0)
  addons/account/tests/test_fiscal_position.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/sale/models/sale.py
  addons/sale/views/res_partner_views.xml
  addons/sale/views/sale_views.xml
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
Labels: 14.0

#16081 Syncing from upstream odoo/odoo (15.0)
  addons/account/tests/test_fiscal_position.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/mail/models/mail_channel.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale/models/sale_order_line.py
  addons/sale/views/res_partner_views.xml
  addons/sale/views/sale_views.xml
  addons/web/controllers/main.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/src/legacy/js/public/public_root.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_popup/001.scss
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website/static/tests/tours/rte.js
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/static/src/js/tours/website_sale_shop.js
  addons/website_slides/static/src/js/tours/slides_tour.js
  doc/cla/corporate/adhoc.md
Labels: 15.0

#16083 [t126948] Odoo Security Advisory - ODOO-SA-2021-12-28 (v13)
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 13.0.project_pm_597

#16084 Syncing from upstream odoo/odoo (13.0)
  addons/account_facturx/data/facturx_templates.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mail/models/mail_thread.py
  addons/sale/models/sale.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
  addons/test_mail/tests/test_message_post.py
  doc/cla/individual/insiyashakir02.md
Labels: 13.0

#16085 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/account_payment_register.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_order.py
  addons/test_mail/tests/test_message_post.py
  doc/cla/individual/insiyashakir02.md
Labels: 14.0

#16089 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/static/src/js/bank_statement.js
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/tests/test_fiscal_position.py
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/l10n_cl/models/res_partner.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_thread.py
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_attribute.py
  addons/product/models/res_partner.py
  addons/sale/models/sale.py
  addons/stock/models/stock_picking.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  doc/cla/corporate/optesis.md
  doc/cla/individual/insiyashakir02.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/models.py
Labels: staging.13.0

#16090 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_fiscal_position.py
  addons/account/wizard/account_payment_register.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mail/models/mail_followers.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/product/models/product_attribute.py
  addons/product/models/product_pricelist.py
  addons/product/models/res_partner.py
  addons/sale/models/sale.py
  addons/sale/views/res_partner_views.xml
  addons/sale/views/sale_views.xml
  addons/test_mail/tests/test_mail_followers.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/scss/web_calendar.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_popup/001.scss
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website/static/tests/tours/rte.js
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
  addons/website_livechat/models/mail_channel.py
  addons/website_livechat/tests/common.py
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_sale/static/src/js/tours/website_sale_shop.js
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  addons/website_slides/static/src/js/tours/slides_tour.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/optesis.md
  doc/cla/individual/insiyashakir02.md
  doc/cla/individual/kwfx.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/models.py
Labels: staging.14.0

#16094 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/static/src/js/bank_statement.js
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/account/tests/test_fiscal_position.py
  addons/account_facturx/data/facturx_templates.xml
  addons/account_facturx/tests/test_facturx.py
  addons/l10n_cl/models/res_partner.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_thread.py
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_attribute.py
  addons/product/models/res_partner.py
  addons/sale/models/sale.py
  addons/stock/models/stock_picking.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
  addons/test_mail/tests/test_message_post.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  doc/cla/corporate/optesis.md
  doc/cla/individual/insiyashakir02.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/models.py
Labels: tmp.13.0

#16095 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_fiscal_position.py
  addons/account/wizard/account_payment_register.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mail/models/mail_followers.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/product/models/product_attribute.py
  addons/product/models/product_pricelist.py
  addons/product/models/res_partner.py
  addons/sale/models/sale.py
  addons/sale/views/res_partner_views.xml
  addons/sale/views/sale_views.xml
  addons/test_mail/tests/test_mail_followers.py
  addons/test_mail/tests/test_message_post.py
  addons/web/static/src/scss/web_calendar.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/scss/web_editor.variables.scss
  addons/web_tour/static/src/js/tip.js
  addons/website/static/src/js/menu/content.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_popup/001.scss
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website/static/tests/tours/rte.js
  addons/website_blog/static/src/js/tours/website_blog.js
  addons/website_blog/tests/test_ui.py
  addons/website_livechat/models/mail_channel.py
  addons/website_livechat/tests/common.py
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_sale/static/src/js/tours/website_sale_shop.js
  addons/website_sale_digital/i18n/website_sale_digital.pot
  addons/website_sale_digital/models/product.py
  addons/website_slides/static/src/js/tours/slides_tour.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/optesis.md
  doc/cla/individual/insiyashakir02.md
  doc/cla/individual/kwfx.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/models.py
Labels: tmp.14.0

#16078 [REM] packaging: remove obsolete dependency feedparser
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  debian/control
  requirements.txt
  setup.cfg
  setup.py
  setup/package.dfdebian
  setup/package.dffedora
Labels: 13.0.project_ms_592

#16098 [t126930] Odoo Security Advisory - ODOO-SA-2021-12-28 (v14)
  addons/auth_signup/controllers/main.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 14.0.project_ca_594

#16099 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/bank_statement.js
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
Labels: 13.0

#16100 Syncing from upstream odoo/odoo (14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/auth_totp/models/res_users.py
  addons/l10n_es/data/account_tax_data.xml
  addons/sale_crm/views/crm_lead_views.xml
  addons/test_xlsx_export/ir.model.access.csv
  addons/test_xlsx_export/models.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  odoo/addons/base/models/res_users.py
Labels: 14.0

#16101 Syncing from upstream odoo/odoo (15.0)
  addons/account_check_printing/models/account_payment.py
  addons/delivery/views/report_deliveryslip.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project_pricing_type.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_location.py
Labels: 15.0

#16103 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/auth_totp/models/res_users.py
  addons/l10n_es/data/account_tax_data.xml
  addons/sale_crm/views/crm_lead_views.xml
  addons/test_xlsx_export/ir.model.access.csv
  addons/test_xlsx_export/models.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/res_users.py
Labels: staging.14.0

#16106 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account_check_printing/models/account_payment.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order_line.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project_pricing_type.py
Labels: tmp.saas-15.1

#16107 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
Labels: tmp.13.0

#16108 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/auth_totp/models/res_users.py
  addons/l10n_es/data/account_tax_data.xml
  addons/sale_crm/views/crm_lead_views.xml
  addons/test_xlsx_export/ir.model.access.csv
  addons/test_xlsx_export/models.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/res_users.py
Labels: tmp.14.0

#16109 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_check_printing/models/account_payment.py
  addons/delivery/views/report_deliveryslip.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project_pricing_type.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_location.py
Labels: tmp.15.0

#16110 [bt#18315][FIX] Add SMTP-Timeout to prevent locks due to not responding server
  openerp/addons/base/ir/ir_mail_server.py
Labels: 8.0.valaiscom

#16111 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_coupon/models/sale_coupon.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_rules.py
Labels: 13.0

#16112 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
Labels: 14.0

#16113 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_render_mixin.py
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/pos_epson_printer_restaurant/static/src/js/multiprint.js
  addons/project/models/project.py
  addons/project/models/project_collaborator.py
  addons/project/models/res_partner.py
  addons/sale/models/sale_order_line.py
  addons/web_editor/controllers/main.py
Labels: 15.0

#16115 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/sale/models/sale_order_line.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_location.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/website/static/tests/tours/rte.js
  addons/website_slides/models/slide_channel.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/tests/test_views.py
  odoo/fields.py
  odoo/tools/translate.py
Labels: tmp.saas-15.1

#16116 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_coupon/models/sale_coupon.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_rules.py
Labels: tmp.13.0

#16117 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/sale/models/sale.py
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
Labels: tmp.14.0

#16118 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_payment_view.xml
  addons/mail/models/mail_render_mixin.py
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/pos_epson_printer_restaurant/static/src/js/multiprint.js
  addons/project/models/project.py
  addons/project/models/project_collaborator.py
  addons/project/models/res_partner.py
  addons/sale/models/sale_order_line.py
  addons/web_editor/controllers/main.py
Labels: tmp.15.0

#16119 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/partner.py
Labels: 13.0

#16120 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/partner.py
  addons/l10n_ar/models/account_move.py
  addons/sale/tests/test_sale_order.py
Labels: 14.0

#16121 Syncing from upstream odoo/odoo (15.0)
  addons/account/__manifest__.py
  addons/account/models/partner.py
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/message/message.js
  addons/mail/static/src/models/message_view/message_view.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/project/views/project_sharing_views.xml
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/legacy/js/views/list/list_renderer.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/controllers/form.py
Labels: 15.0

#16124 Syncing from upstream odoo/odoo (staging.saas-15.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_payment_view.xml
  addons/account_check_printing/models/account_payment.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/static/src/models/message_view/message_view.js
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_epson_printer_restaurant/static/src/js/multiprint.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/product/views/product_views.xml
  addons/project/models/project.py
  addons/project/models/project_collaborator.py
  addons/project/models/res_partner.py
  addons/project/views/project_sharing_views.xml
  addons/sale/models/sale_order_line.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project_pricing_type.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/web/controllers/main.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/static/tests/tours/rte.js
  addons/website_slides/models/slide_channel.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/tests/test_views.py
  odoo/fields.py
  odoo/tools/translate.py
Labels: staging.saas-15.1

#16125 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_coupon/models/sale_coupon.py
  addons/sale_coupon/models/sale_coupon_program.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/sale_coupon/tests/test_program_rules.py
Labels: staging.13.0

#16126 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/views/stock_landed_cost_views.xml
Labels: staging.14.0

#16129 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_payment_view.xml
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/static/src/models/message_view/message_view.js
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_epson_printer_restaurant/static/src/js/multiprint.js
  addons/project/models/project.py
  addons/project/models/project_collaborator.py
  addons/project/models/res_partner.py
  addons/project/views/project_sharing_views.xml
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/web/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-15.1

#16130 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/partner.py
Labels: tmp.13.0

#16131 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/partner.py
  addons/l10n_ar/models/account_move.py
  addons/sale/tests/test_sale_order.py
Labels: tmp.14.0

#16132 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/__manifest__.py
  addons/account/models/partner.py
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/message/message.js
  addons/mail/static/src/models/message_view/message_view.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/project/views/project_sharing_views.xml
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/legacy/js/views/list/list_renderer.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/controllers/form.py
Labels: tmp.15.0

#16133 Syncing from upstream odoo/odoo (14.0)
  doc/cla/individual/ramiadavid.md
Labels: 14.0

#16134 Syncing from upstream odoo/odoo (15.0)
  doc/cla/individual/ramiadavid.md
Labels: 15.0

#16135 Syncing from upstream odoo/odoo (master)
  doc/cla/individual/ramiadavid.md
Labels: master

#16136 Syncing from upstream odoo/odoo (13.0)
  addons/delivery/models/delivery_carrier.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/payment_payulatam/views/payment_payulatam_templates.xml
  addons/sale_stock/models/stock.py
  addons/stock_account/models/account_move.py
Labels: 13.0

#16137 Syncing from upstream odoo/odoo (14.0)
  addons/coupon/models/coupon_program.py
  addons/delivery/models/delivery_carrier.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/payment_payulatam/views/payment_payulatam_templates.xml
  addons/sale_coupon/models/coupon.py
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_rules.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_popup/000.js
Labels: 14.0

#16138 Syncing from upstream odoo/odoo (15.0)
  addons/account/wizard/account_move_reversal.py
  addons/account_debit_note/wizard/account_debit_note.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_transaction.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/payment_payulatam/views/payment_payulatam_templates.xml
  addons/pos_sale/models/sale_order.py
  addons/purchase_stock/report/report_stock_forecasted.py
  addons/sale/tests/test_sale_order.py
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_deliveryslip.xml
  addons/web/static/src/legacy/js/core/dialog.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/__manifest__.py
  addons/website/static/src/js/tours/configurator_tour.js
  addons/website/static/src/js/widgets/dialog.js
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_event/security/ir.model.access.csv
  addons/website_event/static/tests/tours/website_event.js
  odoo/tools/translate.py
Labels: 15.0

#16140 Syncing from upstream odoo/odoo (13.0)
  addons/snailmail/models/snailmail_letter.py
Labels: 13.0

#16141 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/account_move_reversal.py
  addons/account_debit_note/wizard/account_debit_note.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_traceability.py
  addons/sale_coupon/models/coupon_program.py
  addons/website_sale/models/sale_order.py
Labels: 14.0

#16142 Syncing from upstream odoo/odoo (15.0)
  addons/coupon/models/coupon_program.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/project/models/project.py
  addons/project/tests/test_project_sharing.py
  addons/project/views/project_sharing_views.xml
  addons/project/views/project_views.xml
  addons/sale_coupon/models/coupon_program.py
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/static/src/fonts/AlexBrush-Regular-ofl.txt
  addons/survey/static/src/fonts/Cochin-LT-Std-Bold.ttf
  addons/survey/static/src/fonts/Cochin-LT-Std-Roman.ttf
  addons/survey/static/src/fonts/HomepageBaukasten-Bold.otf
  addons/survey/static/src/fonts/HomepageBaukasten-Book.otf
  addons/survey/static/src/fonts/IbarraRealNova-Bold.ttf
  addons/survey/static/src/fonts/IbarraRealNova-Regular.ttf
  addons/survey/static/src/fonts/IbarraRealNova-ofl.txt
  addons/survey/static/src/fonts/Trueno-ofl.txt
  addons/survey/static/src/fonts/Trueno-wml2.otf
  addons/survey/static/src/fonts/TruenoBd.otf
  addons/survey/static/src/scss/survey_reports.scss
  addons/survey/views/survey_report_templates.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: 15.0

#16144 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_reconciliation.py
  addons/l10n_pt/data/account_tax_data.xml
  addons/product/models/product_template.py
Labels: 13.0

#16145 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_pt/data/account_tax_data.xml
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/utils/microsoft_calendar.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_production_backorder.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/snailmail/models/snailmail_letter.py
  addons/stock/models/stock_move_line.py
  addons/website_form/static/src/snippets/s_website_form/options.js
Labels: 14.0

#16146 Syncing from upstream odoo/odoo (15.0)
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_pt/data/account_tax_data.xml
  addons/mass_mailing/data/mailing_data_templates.xml
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_production_backorder.py
  addons/pos_sale/views/stock_template.xml
  addons/product/security/ir.model.access.csv
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_rules.py
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: 15.0

#16148 Syncing from upstream odoo/odoo (13.0)
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/scss/form_view.scss
  doc/cla/individual/ppreeper.md
Labels: 13.0

#16149 Syncing from upstream odoo/odoo (14.0)
  addons/survey/controllers/main.py
  addons/website/static/src/xml/website.pageProperties.xml
  doc/cla/individual/ppreeper.md
Labels: 14.0

#16150 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/mass_mailing/__manifest__.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/utils/microsoft_calendar.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_traceability.py
  addons/pad/py_etherpad/__init__.py
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/product/i18n/product.pot
  addons/product/models/product.py
  addons/product/models/product_template.py
  addons/sale_coupon/models/coupon_program.py
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/frontend/loader.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/data/website_data.xml
  addons/website/static/src/snippets/s_website_form/options.js
  doc/cla/individual/ppreeper.md
Labels: 15.0

#16152 Syncing from upstream odoo/odoo (13.0)
  addons/google_spreadsheet/models/google_drive.py
  addons/http_routing/models/ir_http.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/web/static/lib/Chart/Chart.js
  doc/cla/corporate/adhoc.md
  doc/cla/individual/SplashS.md
  odoo/tests/common.py
Labels: 13.0

#16153 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_account_move_reconcile.py
  addons/crm/static/src/js/crm_form.js
  addons/crm/static/tests/tours/crm_email_and_phone_propagation.js
  addons/crm/tests/test_crm_ui.py
  addons/crm/views/assets.xml
  addons/google_spreadsheet/models/google_drive.py
  addons/http_routing/models/ir_http.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/js/core/domain.js
  addons/web/static/src/scss/form_view.scss
  addons/web/static/tests/core/domain_tests.js
  doc/cla/individual/SplashS.md
  odoo/addons/base/models/res_partner.py
  odoo/tests/common.py
Labels: 14.0

#16154 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_account_move_reconcile.py
  addons/http_routing/models/ir_http.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/tests/test_mailing_ui.py
  addons/mass_mailing/views/assets.xml
  addons/payment/data/payment_acquirer_data.xml
  addons/payment/data/payment_icon_data.xml
  addons/payment/i18n/payment.pot
  addons/payment/models/res_company.py
  addons/payment/tests/common.py
  addons/payment/tests/http_common.py
  addons/payment/tests/test_flows.py
  addons/payment/tests/test_payments.py
  addons/payment/wizards/payment_acquirer_onboarding_templates.xml
  addons/payment/wizards/payment_acquirer_onboarding_wizard.py
  addons/payment_stripe/const.py
  addons/payment_stripe/controllers/__init__.py
  addons/payment_stripe/controllers/main.py
  addons/payment_stripe/controllers/onboarding.py
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_acquirer.py
  addons/payment_stripe/models/payment_transaction.py
  addons/payment_stripe/static/src/js/payment_form.js
  addons/payment_stripe/tests/test_stripe.py
  addons/payment_stripe/views/payment_views.xml
  addons/sale/i18n/sale.pot
  addons/sale/models/res_company.py
  addons/sale/wizard/payment_acquirer_onboarding_wizard.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/stock/views/stock_picking_views.xml
  addons/survey/controllers/main.py
  addons/web/static/src/legacy/scss/form_view.scss
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/web_editor/views/editor.xml
  addons/website/static/src/snippets/s_chart/options.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_sale/models/res_company.py
  addons/website_sale/views/onboarding_views.xml
  addons/website_sale/wizard/payment_acquirer_onboarding_wizard.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/test_lint/tests/test_ecmascript.py
  odoo/tests/common.py
Labels: 15.0

#16156 Syncing from upstream odoo/odoo (14.0)
  addons/stock_landed_costs/models/stock_landed_cost.py
Labels: 14.0

#16158 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
  addons/product/i18n/product.pot
  addons/product/models/product_attribute.py
  addons/product/models/product_template.py
  addons/product/tests/test_product_attribute_value_config.py
  addons/product/tests/test_variants.py
  addons/purchase_stock/models/account_invoice.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website/static/src/scss/website.edit_mode.scss
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
Labels: 13.0

#16159 Syncing from upstream odoo/odoo (14.0)
  addons/mail/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/product/i18n/product.pot
  addons/product/models/product_attribute.py
  addons/product/models/product_template.py
  addons/product/tests/test_product_attribute_value_config.py
  addons/product/tests/test_variants.py
  addons/purchase_stock/models/account_invoice.py
  addons/sale/controllers/portal.py
  addons/stock_account/models/account_move.py
  addons/web/static/lib/Chart/Chart.js
  addons/website/data/website_data.xml
  addons/website/models/website.py
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/tests/tours/automatic_editor.js
  addons/website/tests/__init__.py
  addons/website/tests/test_automatic_editor.py
  addons/website/views/assets.xml
Labels: 14.0

#16160 Syncing from upstream odoo/odoo (15.0)
  addons/google_spreadsheet/models/google_drive.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/models/mrp_production.py
  addons/pos_coupon/models/pos_order.py
  addons/pos_gift_card/models/gift_card.py
  addons/pos_hr/models/hr_employee.py
  addons/purchase_stock/models/account_invoice.py
  addons/sale_coupon/models/coupon_program.py
  addons/stock_account/models/account_move.py
  addons/test_website_modules/tests/test_configurator.py
  addons/web/static/lib/Chart/Chart.js
  addons/web/static/src/legacy/js/core/domain.js
  addons/web/static/src/start.js
  addons/web/static/tests/core/domain_tests.js
  addons/web/static/tests/legacy/core/domain_tests.js
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/components/configurator/configurator.js
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/__init__.py
  addons/website/tests/test_configurator.py
  addons/website/tests/test_fuzzy.py
  addons/website_sale/models/sale_order.py
  doc/cla/individual/AdrianTeng.md
  odoo/models.py
Labels: 15.0

#16166 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_new_api/models.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/http.py
  odoo/models.py
Labels: 13.0

#16168 Syncing from upstream odoo/odoo (15.0)
  addons/base_geolocalize/models/res_partner.py
  addons/l10n_ar/models/res_company.py
  addons/l10n_ec/models/res_company.py
  addons/l10n_pe/data/res_country_data.xml
  addons/l10n_pe/models/res_company.py
  addons/l10n_pe/models/res_partner.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/payment/views/payment_templates.xml
  addons/payment_adyen/static/src/js/payment_form.js
  addons/stock/models/stock_package_level.py
  addons/stock/tests/test_packing.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/website/static/src/scss/website.edit_mode.scss
Labels: 15.0

#16170 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_fr_fec/i18n/fr.po
  addons/link_tracker/models/link_tracker.py
  addons/stock/data/stock_data.xml
Labels: 13.0

#16171 Syncing from upstream odoo/odoo (14.0)
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account/wizard/wizard_tax_adjustments_view.xml
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.js
  addons/sale/models/sale.py
  addons/sale/views/sale_views.xml
  addons/stock/data/stock_data.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/http.py
  odoo/models.py
Labels: 14.0

#16172 Syncing from upstream odoo/odoo (15.0)
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account/wizard/wizard_tax_adjustments_view.xml
  addons/base_geolocalize/models/res_partner.py
  addons/hr_attendance/security/hr_attendance_security.xml
  addons/l10n_fr_fec/i18n/fr.po
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it/data/account_account_tag.xml
  addons/l10n_it/migrations/15.0.0.3/post-migrate.py
  addons/mail/controllers/discuss.py
  addons/mail/static/src/components/activity_mark_done_popover/activity_mark_done_popover.js
  addons/mrp/models/mrp_production.py
  addons/stock/wizard/stock_replenishment_info.py
  addons/stock_picking_batch/models/__init__.py
  addons/stock_picking_batch/models/stock_move.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web/static/src/legacy/xml/base.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteForward.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/editor-test.html
  addons/web_editor/static/lib/odoo-editor/test/editor-test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/align.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/autostep.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/fontAwesome.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/mixins.py
  addons/website/security/ir.model.access.csv
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  addons/website_livechat/models/mail_channel.py
  addons/website_livechat/tests/common.py
  addons/website_livechat/tests/test_livechat_basic_flow.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
Labels: 15.0

#16174 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/models/pos_session.py
Labels: 13.0

#16175 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/l10n_ar/models/res_partner.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/mrp/models/stock_rule.py
  addons/website_sale/controllers/main.py
  doc/cla/corporate/forgeflow.md
Labels: 14.0

#16176 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/base_geolocalize/models/res_partner.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_it/models/account_tax_report.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/mail/static/src/components/discuss/discuss.js
  addons/mail/static/src/models/discuss/discuss.js
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/mail/static/src/widgets/discuss/discuss.js
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/project/controllers/portal.py
  addons/sale/controllers/portal.py
  addons/web/static/src/fields/formatters.js
  addons/web/static/tests/fields/formatters_tests.js
  addons/website/models/website.py
  addons/website/tests/test_fuzzy.py
  addons/website_crm_partner_assign/models/crm_lead.py
Labels: 15.0

#16178 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/ca.po
  addons/account/i18n/es.po
  addons/account/i18n/et.po
  addons/account/i18n/it.po
  addons/account/i18n/nb.po
  addons/account/i18n/pl.po
  addons/account/i18n/sv.po
  addons/account/i18n/th.po
  addons/analytic/i18n/nb.po
  addons/auth_totp/i18n/es.po
  addons/auth_totp/i18n/sv.po
  addons/auth_totp_portal/i18n/es.po
  addons/base_setup/i18n/sv.po
  addons/calendar/i18n/it.po
  addons/contacts/i18n/nb.po
  addons/coupon/i18n/th.po
  addons/crm/i18n/it.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/es.po
  addons/delivery/i18n/it.po
  addons/delivery/i18n/th.po
  addons/digest/i18n/ar.po
  addons/event/i18n/sv.po
  addons/event/i18n/th.po
  addons/event_crm/i18n/es.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nb.po
  odoo/addons/base/i18n/sv.po
Labels: 14.0

#16180 Syncing from upstream odoo/odoo (master)
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/core/l10n/translation_tests.js
Labels: master

#16181 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ar/models/res_partner.py
Labels: 15.0

#16182 Syncing from upstream odoo/odoo (master)
  addons/l10n_ar/models/res_partner.py
Labels: master

#16184 Syncing from upstream odoo/odoo (13.0)
  odoo/addons/base/tests/test_expression.py
  odoo/fields.py
  odoo/osv/expression.py
Labels: 13.0

#16185 Syncing from upstream odoo/odoo (14.0)
  addons/account_check_printing/models/account_move.py
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/tests/__init__.py
  addons/fleet/tests/test_overdue.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_move.py
  addons/l10n_es_edi_sii/tests/common.py
  addons/link_tracker/models/link_tracker.py
  odoo/fields.py
  odoo/osv/expression.py
Labels: 14.0

#16186 Syncing from upstream odoo/odoo (15.0)
  addons/account/demo/account_demo.py
  addons/account/i18n/account.pot
  addons/account/views/report_journal.xml
  addons/account/wizard/account_report_common.py
  addons/account/wizard/account_report_common_view.xml
  addons/account_check_printing/models/account_move.py
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/account_edi_ubl_bis3/data/bis3_templates.xml
  addons/board/static/src/legacy/js/board_view.js
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/tests/__init__.py
  addons/fleet/tests/test_overdue.py
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/l10n_be_edi/tests/test_efff_export.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_move.py
  addons/link_tracker/models/link_tracker.py
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/models/stock_rule.py
  addons/payment/controllers/portal.py
  addons/payment/views/payment_templates.xml
  addons/project/i18n/project.pot
  addons/project/static/src/js/right_panel/project_right_panel.js
  addons/project/static/src/xml/project_templates.xml
  addons/project/views/project_sharing_views.xml
  addons/survey/views/survey_question_views.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/lib/bootstrap/js/dropdown.js
  addons/web/static/src/core/commands/command_palette.js
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/hotkeys/hotkey_hook.js
  addons/web/static/src/core/hotkeys/hotkey_service.js
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/hotkeys/hotkey_service_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website.py
  addons/website/static/tests/tours/automatic_editor.js
  addons/website/tests/__init__.py
  addons/website/tests/test_automatic_editor.py
  doc/cla/corporate/forgeflow.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/fields.py
  odoo/osv/expression.py
Labels: 15.0

#16188 Merge branch '12.0.project_PR_606' of github.com:brain-tec/odoo into 12.0.project_PR_606
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 12.0.project_pr_606

#16183 [bt#18476][FIX] web: chrome 89 event delegation
  addons/web/static/lib/jquery/jquery.js
Labels: 12.0.project_pr_606

#16189 Revert "Merge branch '12.0.project_PR_606' of github.com:brain-tec/odoo into 12.0.project_PR_606"
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mail/controllers/main.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 12.0.project_pr_606

#16190 Syncing from upstream odoo/odoo (13.0)
  addons/web_editor/models/assets.py
Labels: 13.0

#16191 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/account/models/account_tax_report.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/web_editor/models/assets.py
Labels: 14.0

#16192 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_tax_report.py
  addons/account/models/partner.py
  addons/calendar/static/src/js/calendar_controller.js
  addons/calendar/static/src/js/services/calendar_notification_service.js
  addons/calendar/static/tests/calendar_notification_tests.js
  addons/calendar/views/calendar_views.xml
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/views/mrp_production_views.xml
  addons/payment/tests/common.py
  addons/payment/tests/http_common.py
  addons/payment/tests/test_flows.py
  addons/payment/tests/test_payments.py
  addons/portal_rating/static/src/xml/portal_chatter.xml
  addons/pos_gift_card/static/src/css/giftCard.css
  addons/pos_sale/i18n/pos_sale.pot
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/project/models/project.py
  addons/project/static/src/js/project_form.js
  addons/project/views/project_views.xml
  addons/sale/models/sale_order.py
  addons/sale/views/sale_views.xml
  addons/sale_crm/views/crm_lead_views.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/web_editor/models/assets.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/cli/server.py
Labels: 15.0

#16194 Syncing from upstream odoo/odoo (12.0)
  addons/payment_stripe_sca/controllers/main.py
  doc/cla/individual/petrus-v.md
Labels: 12.0

#16195 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/account_facturx/i18n/account_facturx.pot
  addons/account_facturx/models/account_move.py
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/models/ir_cron.py
Labels: 13.0

#16196 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_account.py
  addons/account/models/account_journal.py
  addons/hr_expense/data/hr_expense_demo.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_slides/models/slide_slide.py
Labels: 14.0

#16197 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_payment.py
  addons/hr_expense/data/hr_expense_demo.xml
  addons/test_website/tests/test_performance.py
  addons/uom/models/uom_uom.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/legacy/fields/relational_fields/field_many2one_tests.js
  addons/website/tests/test_performance.py
  addons/website_blog/tests/test_performance.py
  addons/website_slides/models/slide_slide.py
Labels: 15.0

#16198 Syncing from upstream odoo/odoo (master)
  addons/account/demo/account_demo.py
  addons/account/i18n/account.pot
  addons/account/views/report_journal.xml
  addons/account/wizard/account_report_common.py
  addons/account/wizard/account_report_common_view.xml
  addons/account/wizard/wizard_tax_adjustments.py
  addons/account/wizard/wizard_tax_adjustments_view.xml
  addons/hr/wizard/hr_departure_wizard_views.xml
  addons/l10n_hu/__manifest__.py
  addons/l10n_hu/data/account.account.template.csv
  addons/l10n_hu/data/account.financial.report.csv
  addons/l10n_hu/data/account.fiscal.position.tax.template.csv
  addons/l10n_hu/data/account.group.template.csv
  addons/l10n_hu/data/account.tax.group.csv
  addons/l10n_hu/data/account_chart_template_data.xml
  addons/l10n_hu/data/account_tax_report_data.xml
  addons/l10n_hu/data/account_tax_template_data.xml
  addons/l10n_hu/data/l10n_hu_chart_data.xml
  addons/l10n_hu/data/menuitem_data.xml
  addons/l10n_pe/models/res_partner.py
  addons/mail/static/src/components/discuss_sidebar_category_item/tests/discuss_sidebar_category_item_tests.js
  addons/mail/static/tests/activity_tests.js
  addons/mail/static/tests/document_viewer_tests.js
  addons/mail/static/tests/m2x_avatar_user_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/static/tests/mrp_tests.js
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/payment/tests/common.py
  addons/payment/tests/http_common.py
  addons/payment/tests/test_flows.py
  addons/payment/tests/test_payments.py
  addons/rating/models/rating_parent_mixin.py
  addons/uom/models/uom_uom.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/src/legacy/js/promise_extension.js
  addons/web/static/src/legacy/root_widget.js
  addons/web/static/src/legacy/utils.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/legacy/helpers/test_utils_mock.js
  addons/web/static/tests/legacy/owl_compatibility_tests.js
  addons/web/static/tests/legacy/views/kanban_tests.js
  addons/web/static/tests/qunit.js
  addons/web/static/tests/setup.js
  addons/web/static/tests/webclient/user_menu_tests.js
  addons/web_editor/models/assets.py
  addons/website_crm_partner_assign/__manifest__.py
  addons/website_crm_partner_assign/data/res_partner_activation_data.xml
  addons/website_crm_partner_assign/data/res_partner_grade_data.xml
  addons/website_crm_partner_assign/models/res_partner_activation.py
  addons/website_crm_partner_assign/models/res_partner_grade.py
  addons/website_crm_partner_assign/views/res_partner_activation_views.xml
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/models/ir_actions.py
Labels: master

#16199 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/partner.py
  addons/l10n_ar/models/account_move.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/qweb.py
  odoo/addons/test_converter/tests/test_html.py
  odoo/api.py
  odoo/models.py
  odoo/modules/registry.py
  odoo/tools/misc.py
Labels: 13.0

#16200 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/partner.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  odoo/addons/base/models/ir_cron.py
Labels: 14.0

#16201 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_account.py
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/product/models/product.py
  addons/project/models/project.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move2.py
  addons/test_website/tests/test_controller_args.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/legacy/js/core/domain.js
  addons/web/static/src/legacy/js/views/basic/basic_renderer.js
  addons/web/static/src/legacy/js/widgets/colorpicker.js
  addons/web/static/src/search/utils/dates.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/helpers/cleanup.js
  addons/web/static/tests/legacy/core/domain_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.backend.scss
  addons/website/models/website.py
  addons/website/tests/test_disable_unused_snippets_assets.py
  addons/website/tests/test_page.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/ir_cron.py
Labels: 15.0

#16203 Syncing from upstream odoo/odoo (saas-12.3)
  addons/payment_stripe_sca/controllers/main.py
  doc/cla/individual/petrus-v.md
Labels: saas-12.3

#16204 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/portal/static/src/scss/portal.scss
  odoo/fields.py
Labels: 13.0

#16205 Syncing from upstream odoo/odoo (14.0)
  addons/account_fleet/models/account_move.py
  addons/account_fleet/models/fleet_vehicle.py
  addons/google_spreadsheet/models/google_drive.py
  addons/hr_timesheet/views/project_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  odoo/fields.py
Labels: 14.0

#16208 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/ca.po
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/account/i18n/nb.po
  addons/account/i18n/sv.po
  addons/account_debit_note/i18n/ca.po
  addons/account_edi/i18n/de.po
  addons/account_fleet/i18n/ca.po
  addons/account_lock/i18n/ca.po
  addons/account_tax_python/i18n/ca.po
  addons/account_tax_python/i18n/ja.po
  addons/adyen_platforms/i18n/de.po
  addons/analytic/i18n/ca.po
  addons/auth_oauth/i18n/ca.po
  addons/auth_signup/i18n/it.po
  addons/auth_totp_portal/i18n/de.po
  addons/barcodes/i18n/ca.po
  addons/barcodes/i18n/it.po
  addons/base_setup/i18n/ca.po
  addons/base_setup/i18n/vi.po
  addons/calendar/i18n/ca.po
  addons/calendar_sms/i18n/ca.po
  addons/contacts/i18n/es.po
  addons/coupon/i18n/de.po
  addons/coupon/i18n/et.po
  addons/coupon/i18n/it.po
  addons/crm/i18n/ca.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/es.po
  addons/delivery/i18n/th.po
  addons/digest/i18n/ca.po
  addons/digest/i18n/it.po
  addons/event/i18n/th.po
  addons/portal/static/src/scss/portal.scss
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/th.po
Labels: 14.0

#16210 Syncing from upstream odoo/odoo (master)
  addons/auth_totp/controllers/home.py
  addons/auth_totp/tests/test_totp.py
  addons/board/static/src/legacy/js/board_view.js
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_acquirer.py
  addons/payment_stripe/views/payment_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/point_of_sale/tests/test_pos_multiple_receivable_accounts.py
  addons/point_of_sale/tests/test_pos_other_currency_config.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/point_of_sale/tests/test_pos_simple_invoiced_orders.py
  addons/point_of_sale/tests/test_pos_simple_orders.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/point_of_sale/tests/test_pos_with_fiscal_position.py
  addons/portal/static/src/scss/portal.scss
  addons/web/controllers/main.py
Labels: master

#16217 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/payment_stripe_sca/controllers/main.py
  doc/cla/individual/petrus-v.md
Labels: tmp.saas-12.3

#16220 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/payment_stripe_sca/controllers/main.py
  doc/cla/individual/petrus-v.md
Labels: tmp.12.0

#16225 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/i18n/ca.po
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/account/i18n/nb.po
  addons/account/i18n/sv.po
  addons/account_debit_note/i18n/ca.po
  addons/account_edi/i18n/de.po
  addons/account_fleet/i18n/ca.po
  addons/account_lock/i18n/ca.po
  addons/account_tax_python/i18n/ca.po
  addons/account_tax_python/i18n/ja.po
  addons/adyen_platforms/i18n/de.po
  addons/analytic/i18n/ca.po
  addons/auth_oauth/i18n/ca.po
  addons/auth_signup/i18n/it.po
  addons/auth_totp_portal/i18n/de.po
  addons/barcodes/i18n/ca.po
  addons/barcodes/i18n/it.po
  addons/base_setup/i18n/ca.po
  addons/base_setup/i18n/vi.po
  addons/calendar/i18n/ca.po
  addons/calendar_sms/i18n/ca.po
  addons/contacts/i18n/es.po
  addons/coupon/i18n/de.po
  addons/coupon/i18n/et.po
  addons/coupon/i18n/it.po
  addons/crm/i18n/ca.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/es.po
  addons/delivery/i18n/th.po
  addons/digest/i18n/ca.po
  addons/digest/i18n/it.po
  addons/event/i18n/th.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/th.po
Labels: tmp.14.0
