Repository brain-tec/odoo, pull requests merged in 2022-09, with the labels that each got.

#17375 Syncing from upstream odoo/odoo (14.0)
  addons/sale_stock/models/account_move.py
Labels: 14.0

#17376 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/crm/models/crm_lead.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_refund.xml
  addons/l10n_ar/views/account_move_view.xml
  addons/l10n_in_pos/models/pos_order.py
  addons/project/models/project.py
  addons/project/static/src/scss/project_sharing/chatter.scss
  addons/web/static/src/legacy/scss/bootstrap_review.scss
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
Labels: 15.0

#17378 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account.py
  addons/account/models/account_payment.py
  addons/account/tests/test_payment.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
Labels: 13.0

#17379 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_taxes.py
  addons/mail/static/src/models/partner/partner.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/sale_stock_margin/models/sale_order_line.py
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
Labels: 14.0

#17380 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_ec/__manifest__.py
  addons/mail/static/src/models/partner/partner.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale_stock_margin/models/sale_order_line.py
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/search/search_bar/search_bar.xml
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: 15.0

#17396 Syncing from upstream odoo/odoo (13.0)
  addons/event/i18n/de.po
  addons/hr_expense/i18n/ar.po
  addons/hr_holidays/i18n/ar.po
  addons/hr_recruitment/i18n/ja.po
  addons/mass_mailing/i18n/de.po
  addons/mrp_subcontracting/i18n/ar.po
  addons/sale_timesheet/i18n/de.po
  addons/stock/i18n/ar.po
  addons/stock/i18n/cs.po
  addons/utm/i18n/ar.po
  addons/web/i18n/ja.po
  addons/web_tour/i18n/ar.po
  addons/website_mail_channel/i18n/ar.po
  odoo/addons/base/i18n/ar.po
Labels: 13.0

#17397 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/es_MX.po
  addons/account/i18n/lt.po
  addons/event/i18n/ar.po
  addons/event/i18n/de.po
  addons/event/i18n/sv.po
  addons/event_crm/i18n/sv.po
  addons/hr_expense/i18n/ar.po
  addons/hr_holidays/i18n/ar.po
  addons/hr_recruitment/i18n/ja.po
  addons/hr_timesheet/i18n/ca.po
  addons/hr_timesheet/i18n/de.po
  addons/hr_timesheet/i18n/es.po
  addons/hr_timesheet/i18n/es_MX.po
  addons/hr_timesheet/i18n/fr.po
  addons/hr_timesheet/i18n/he.po
  addons/hr_timesheet/i18n/lt.po
  addons/hr_timesheet/i18n/nl.po
  addons/hr_timesheet/i18n/uk.po
  addons/hr_timesheet/i18n/zh_CN.po
  addons/lunch/i18n/mn.po
  addons/mass_mailing/i18n/de.po
  addons/mrp/i18n/ar.po
  addons/mrp_subcontracting/i18n/ar.po
  addons/project/i18n/es_MX.po
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale_stock/i18n/pt.po
  addons/sale_timesheet/i18n/de.po
  addons/sale_timesheet/i18n/es_MX.po
  addons/stock/i18n/ar.po
  addons/utm/i18n/ar.po
  addons/web/i18n/ja.po
  addons/web_tour/i18n/ar.po
  addons/website/i18n/fr.po
  addons/website_event_track/i18n/de.po
  addons/website_forum/i18n/de.po
  addons/website_mail_channel/i18n/ar.po
  addons/website_sale/i18n/de.po
  addons/website_slides_forum/i18n/fr.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/de.po
Labels: 14.0

#17400 Syncing from upstream odoo/odoo (13.0)
  doc/cla/corporate/quartile.md
Labels: 13.0

#17402 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_coupon/static/src/js/tours/PosCoupon3tour.js
  addons/pos_coupon/tests/test_frontend.py
  addons/web/static/src/legacy/debug_manager.js
  addons/web/static/src/legacy/scss/form_view.scss
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/src/search/search_model.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  doc/cla/corporate/quartile.md
  odoo/addons/base/models/res_users.py
Labels: 15.0

#17405 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/event/i18n/de.po
  addons/hr_expense/i18n/ar.po
  addons/hr_holidays/i18n/ar.po
  addons/hr_recruitment/i18n/ja.po
  addons/mass_mailing/i18n/de.po
  addons/mrp_subcontracting/i18n/ar.po
  addons/sale_timesheet/i18n/de.po
  addons/stock/i18n/ar.po
  addons/stock/i18n/cs.po
  addons/utm/i18n/ar.po
  addons/web/i18n/ja.po
  addons/web_tour/i18n/ar.po
  addons/website_mail_channel/i18n/ar.po
  doc/cla/corporate/quartile.md
  odoo/addons/base/i18n/ar.po
Labels: tmp.13.0

#17406 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/i18n/es_MX.po
  addons/account/i18n/lt.po
  addons/account/models/account_bank_statement.py
  addons/calendar_sms/models/calendar.py
  addons/calendar_sms/tests/__init__.py
  addons/calendar_sms/tests/test_calendar_sms.py
  addons/event/i18n/ar.po
  addons/event/i18n/de.po
  addons/event/i18n/sv.po
  addons/event_crm/i18n/sv.po
  addons/hr_expense/i18n/ar.po
  addons/hr_holidays/i18n/ar.po
  addons/hr_recruitment/i18n/ja.po
  addons/hr_timesheet/i18n/ca.po
  addons/hr_timesheet/i18n/de.po
  addons/hr_timesheet/i18n/es.po
  addons/hr_timesheet/i18n/es_MX.po
  addons/hr_timesheet/i18n/fr.po
  addons/hr_timesheet/i18n/he.po
  addons/hr_timesheet/i18n/lt.po
  addons/hr_timesheet/i18n/nl.po
  addons/hr_timesheet/i18n/uk.po
  addons/hr_timesheet/i18n/zh_CN.po
  addons/l10n_ch/i18n_extra/de.po
  addons/l10n_ch/i18n_extra/fr.po
  addons/l10n_ch/i18n_extra/it.po
  addons/l10n_ch/i18n_extra/l10n_ch.pot
  addons/lunch/i18n/mn.po
  addons/mail/models/mail_thread.py
  addons/mass_mailing/i18n/de.po
  addons/mrp/i18n/ar.po
  addons/mrp_subcontracting/i18n/ar.po
  addons/project/i18n/es_MX.po
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_stock/i18n/pt.po
  addons/sale_timesheet/i18n/de.po
  addons/sale_timesheet/i18n/es_MX.po
  addons/stock/i18n/ar.po
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/utm/i18n/ar.po
  addons/web/i18n/ja.po
  addons/web/static/src/js/libs/moment.js
  addons/web/views/webclient_templates.xml
  addons/web_tour/i18n/ar.po
  addons/website/i18n/fr.po
  addons/website_event_track/i18n/de.po
  addons/website_forum/i18n/de.po
  addons/website_mail_channel/i18n/ar.po
  addons/website_sale/i18n/de.po
  addons/website_slides_forum/i18n/fr.po
  doc/cla/corporate/quartile.md
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/de.po
Labels: tmp.14.0

#17410 Syncing from upstream odoo/odoo (13.0)
  addons/iap/models/iap.py
  addons/purchase/models/product.py
Labels: 13.0

#17411 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_tax.py
  addons/account/wizard/account_resequence.py
  addons/iap/models/iap_account.py
  addons/mail/static/src/components/dialog/dialog.scss
  addons/mail/static/src/components/dialog/dialog.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/survey/static/src/xml/survey_breadcrumb_templates.xml
  addons/survey/views/survey_templates.xml
  addons/survey/views/survey_templates_print.xml
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
Labels: 14.0

#17412 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_tax.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/calendar_sms/models/calendar_event.py
  addons/calendar_sms/tests/__init__.py
  addons/calendar_sms/tests/test_calendar_sms.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/dialog/dialog.scss
  addons/mail/static/src/components/dialog/dialog.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/product/report/product_product_templates.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/survey/static/src/xml/survey_breadcrumb_templates.xml
  addons/survey/views/survey_templates.xml
  addons/survey/views/survey_templates_print.xml
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/web/__manifest__.py
  addons/web/static/src/legacy/js/libs/moment.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/editor-test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/fontSize.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/controllers/main.py
  addons/website/static/src/js/menu/translate.js
  addons/website_sale_delivery_giftcard/static/tests/tours/website_sale_delivery_gift_card.js
  addons/website_sale_delivery_giftcard/tests/test_website_sale_delivery_giftcard.py
Labels: 15.0

#17414 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/website/models/website.py
Labels: 13.0

#17415 Syncing from upstream odoo/odoo (14.0)
  addons/calendar/models/calendar_event.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/src/js/ChromeWidgets/TicketButton.js
  addons/pos_restaurant/static/src/js/floors.js
  addons/pos_restaurant/static/tests/tours/TipScreen.tour.js
Labels: 14.0

#17416 Syncing from upstream odoo/odoo (15.0)
  addons/calendar/static/src/js/calendar_model.js
  addons/iap/models/iap_account.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/menu/edit.js
  addons/website_sale_delivery_giftcard/static/tests/tours/website_sale_delivery_gift_card.js
Labels: 15.0

#17418 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/ar.po
  addons/account/i18n/fr.po
  addons/account_analytic_default/i18n/ar.po
  addons/account_analytic_default/i18n/de.po
  addons/account_lock/i18n/ja.po
  addons/base_address_extended/i18n/pl.po
  addons/board/i18n/ja.po
  addons/delivery/i18n/ja.po
  addons/gamification/i18n/zh_CN.po
  addons/google_drive/i18n/fr.po
  addons/hr_holidays/i18n/pt.po
  addons/hr_work_entry/i18n/pt.po
  addons/im_livechat/i18n/ja.po
  addons/link_tracker/i18n/ja.po
  addons/lunch/i18n/ja.po
  addons/mail/i18n/fa.po
  addons/mass_mailing/i18n/de.po
  addons/mass_mailing/i18n/ja.po
  addons/mass_mailing/i18n/pl.po
  addons/mass_mailing_sms/i18n/pl.po
  addons/mrp/i18n/fr.po
  addons/pos_restaurant/i18n/ja.po
  addons/product/i18n/ja.po
  addons/product/i18n/pt.po
  addons/project/i18n/ja.po
  addons/rating/i18n/ja.po
  addons/sale/i18n/ar.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/pt.po
  addons/snailmail/i18n/hu.po
  addons/stock/i18n/ar.po
  addons/stock/i18n/he.po
  addons/stock/i18n/ja.po
  addons/stock/i18n/pt.po
  addons/web/i18n/hu.po
  addons/web_editor/i18n/fr.po
  addons/web_editor/i18n/hu.po
  addons/web_unsplash/i18n/hu.po
  addons/website/i18n/fr.po
  addons/website/i18n/hu.po
  addons/website/i18n/ja.po
  addons/website/i18n/zh_CN.po
  addons/website_form/i18n/hu.po
  addons/website_form/i18n/ja.po
  addons/website_livechat/i18n/ja.po
  addons/website_mass_mailing/i18n/pl.po
  addons/website_sale/i18n/hu.po
  addons/website_sale/i18n/ja.po
  addons/website_sale/i18n/pt.po
  addons/website_slides/i18n/hu.po
  addons/website_slides/i18n/ja.po
  addons/website_theme_install/i18n/hu.po
  odoo/addons/base/i18n/fa.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/he.po
  odoo/addons/base/i18n/hu.po
  odoo/addons/base/i18n/pt.po
Labels: 13.0

#17421 Syncing from upstream odoo/odoo (master)
  addons/point_of_sale/models/pos_session.py
Labels: master

#17422 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/website/models/website.py
Labels: 14.0

#17423 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/bus/models/bus.py
  addons/hr_holidays/views/hr_views.xml
  addons/l10n_fr_pos_cert/static/src/js/Chrome.js
  addons/l10n_it_edi/models/account_edi_format.py
  addons/point_of_sale/static/src/js/ChromeWidgets/HeaderButton.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/Popups/ProductInfoPopup.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ControlButtons/ProductInfoButton.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductItem.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_sale_product_configurator/static/src/js/models.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/models/website.py
Labels: 15.0

#17425 Syncing from upstream odoo/odoo (13.0)
  addons/google_spreadsheet/models/google_drive.py
  addons/google_spreadsheet/static/src/js/add_to_google_spreadsheet_menu.js
  addons/google_spreadsheet/static/src/xml/addtospreadsheet.xml
  addons/google_spreadsheet/views/res_config_settings_views.xml
  addons/web/controllers/main.py
Labels: 13.0

#17426 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/google_spreadsheet/models/google_drive.py
  addons/google_spreadsheet/static/src/js/add_to_google_spreadsheet_menu.js
  addons/google_spreadsheet/static/src/xml/addtospreadsheet.xml
  addons/google_spreadsheet/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/views/stock_move_views.xml
  addons/web/controllers/main.py
Labels: 14.0

#17427 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
  addons/google_spreadsheet/models/google_drive.py
  addons/google_spreadsheet/static/src/add_to_google_spreadsheet/add_to_google_spreadsheet.js
  addons/google_spreadsheet/static/src/add_to_google_spreadsheet/add_to_google_spreadsheet.xml
  addons/google_spreadsheet/static/src/legacy/js/add_to_google_spreadsheet_menu.js
  addons/google_spreadsheet/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_coupon/static/src/js/tours/PosCoupon3tour.js
  addons/pos_restaurant/static/src/js/ChromeWidgets/TicketButton.js
  addons/pos_restaurant/static/src/js/floors.js
  addons/pos_restaurant/static/tests/tours/TipScreen.tour.js
  addons/pos_sale/models/pos_order.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/static/src/js/report_stock_forecasted.js
  addons/stock/views/stock_move_views.xml
  addons/web/controllers/main.py
Labels: 15.0

#17429 Syncing from upstream odoo/odoo (13.0)
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
  addons/stock/views/stock_move_line_views.xml
Labels: 13.0

#17430 Syncing from upstream odoo/odoo (14.0)
  addons/hr/static/src/models/employee/employee.js
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/models/user/user.js
  addons/product_expiry/models/stock_move_line.py
  addons/product_expiry/tests/test_stock_production_lot.py
  addons/stock/models/stock_move_line.py
  odoo/modules/registry.py
Labels: 14.0

#17431 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/account_move_views.xml
  addons/account_edi/models/account_edi_document.py
  addons/gift_card/models/gift_card.py
  addons/hr/static/src/models/employee/employee.js
  addons/hr_expense/models/hr_expense.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mail/static/src/models/user/user.js
  addons/pos_gift_card/models/gift_card.py
  addons/sale/models/sale_order.py
  addons/web/static/src/views/graph/graph_arch_parser.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
Labels: 15.0

#17433 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/data/account.account.template.csv
  addons/payment/static/src/js/payment_processing.js
  addons/website/static/src/js/editor/snippets.options.js
Labels: 13.0

#17434 Syncing from upstream odoo/odoo (14.0)
  addons/attachment_indexation/models/ir_attachment.py
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/models/__init__.py
  addons/l10n_ar_website_sale/models/ir_ui_view.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
  addons/stock/views/stock_move_line_views.xml
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/fields/relational_fields_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/addons/base/models/ir_attachment.py
  odoo/tests/test_module_operations.py
Labels: 14.0

#17435 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/attachment_indexation/models/ir_attachment.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_ar_website_sale/__init__.py
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_website_sale/models/__init__.py
  addons/l10n_ar_website_sale/models/ir_ui_view.py
  addons/l10n_bg/data/tax_report.xml
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/static/src/js/ChromeWidgets/ClientScreenButton.js
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
  addons/stock/views/stock_move_line_views.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/models/ir_attachment.py
  odoo/modules/registry.py
  odoo/tests/test_module_operations.py
  requirements.txt
Labels: 15.0

#17437 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/ar.po
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/tr.po
  addons/crm/i18n/hr.po
  addons/crm_iap_lead/i18n/hr.po
  addons/digest/i18n/hu.po
  addons/hr_attendance/i18n/ja.po
  addons/hr_expense/i18n/ja.po
  addons/hr_recruitment/i18n/ja.po
  addons/hr_skills/i18n/mn.po
  addons/hr_timesheet/i18n/lt.po
  addons/mail/i18n/he.po
  addons/mail/i18n/mn.po
  addons/payment/i18n/mn.po
  addons/payment_alipay/i18n/mn.po
  addons/payment_paypal/i18n/mn.po
  addons/point_of_sale/i18n/fi.po
  addons/portal/i18n/mn.po
  addons/pos_cash_rounding/i18n/fi.po
  addons/product/i18n/hr.po
  addons/product/i18n/mn.po
  addons/project/i18n/ar.po
  addons/repair/i18n/ja.po
  addons/sale/i18n/ar.po
  addons/sale/i18n/hr.po
  addons/sale/i18n/mn.po
  addons/sale_product_configurator/i18n/hr.po
  addons/stock/i18n/hr.po
  addons/stock/i18n/mn.po
  addons/website/i18n/fr.po
  addons/website_blog/i18n/he.po
  addons/website_forum/i18n/mn.po
  addons/website_sale/i18n/mn.po
  addons/website_slides/i18n/ar.po
  addons/website_slides/i18n/it.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/hr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/mn.po
  odoo/addons/base/i18n/pl.po
Labels: 13.0

#17438 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/ar.po
  addons/account/i18n/de.po
  addons/account/i18n/hu.po
  addons/account/i18n/mn.po
  addons/analytic/i18n/mn.po
  addons/calendar/i18n/fr.po
  addons/crm/i18n/fr.po
  addons/crm/i18n/hr.po
  addons/crm_iap_lead/i18n/hr.po
  addons/delivery/i18n/it.po
  addons/digest/i18n/hu.po
  addons/fleet/i18n/de.po
  addons/hr_attendance/i18n/ja.po
  addons/hr_expense/i18n/ja.po
  addons/hr_recruitment/i18n/ja.po
  addons/hr_skills/i18n/mn.po
  addons/hr_timesheet/i18n/lt.po
  addons/mail/i18n/ar.po
  addons/mail/i18n/hu.po
  addons/mail/i18n/mn.po
  addons/mrp/i18n/mn.po
  addons/payment/i18n/mn.po
  addons/payment_alipay/i18n/mn.po
  addons/payment_odoo_by_adyen/i18n/mn.po
  addons/payment_paypal/i18n/mn.po
  addons/point_of_sale/i18n/fi.po
  addons/portal/i18n/mn.po
  addons/product/i18n/hr.po
  addons/product/i18n/mn.po
  addons/project/i18n/ar.po
  addons/repair/i18n/ja.po
  addons/sale/i18n/ar.po
  addons/sale/i18n/hr.po
  addons/sale/i18n/mn.po
  addons/sale_product_configurator/i18n/hr.po
  addons/stock/i18n/hr.po
  addons/stock/i18n/mn.po
  addons/web/i18n/es_MX.po
  addons/web/i18n/he.po
  addons/web_tour/i18n/fr.po
  addons/website/i18n/fr.po
  addons/website/i18n/hr.po
  addons/website_blog/i18n/he.po
  addons/website_blog/i18n/it.po
  addons/website_event_track_exhibitor/i18n/hu.po
  addons/website_event_track_quiz/i18n/it.po
  addons/website_form/i18n/hr.po
  addons/website_form/i18n/mn.po
  addons/website_forum/i18n/fr.po
  addons/website_forum/i18n/mn.po
  addons/website_sale/i18n/mn.po
  addons/website_slides/i18n/ar.po
  addons/website_slides/i18n/it.po
  addons/website_slides_forum/i18n/fr.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/hr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/mn.po
  odoo/addons/base/i18n/pl.po
Labels: 14.0

#17440 Syncing from upstream odoo/odoo (master)
  addons/auth_password_policy/__manifest__.py
  addons/bus/__manifest__.py
  addons/calendar/views/calendar_templates.xml
  addons/event/__manifest__.py
  addons/hr/static/src/models/employee.js
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/mail/static/src/models/user.js
  addons/mass_mailing/__manifest__.py
  addons/mass_mailing/views/assets.xml
  addons/stock/__manifest__.py
  addons/survey/__manifest__.py
  addons/web/__manifest__.py
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/__manifest__.py
  addons/web_tour/__manifest__.py
  addons/website/__manifest__.py
  addons/website/controllers/main.py
  addons/website/models/ir_qweb.py
  addons/website/tests/test_performance.py
  addons/website/views/website_templates.xml
  addons/website_event/__manifest__.py
  addons/website_forum/__manifest__.py
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/__manifest__.py
Labels: master

#17441 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_workorder_operation.py
  addons/website_event/static/src/js/website_event.js
  addons/website_event/views/event_templates.xml
Labels: 13.0

#17442 Syncing from upstream odoo/odoo (14.0)
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/l10n_in/__manifest__.py
  addons/l10n_in/views/account_journal_views.xml
  addons/l10n_in/views/res_company_view.xml
  addons/l10n_in/views/res_country_state_view.xml
  addons/payment/static/src/js/payment_processing.js
  addons/sale/models/res_partner.py
  addons/website_sale/views/templates.xml
Labels: 14.0

#17443 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/res_config_settings_views.xml
  addons/account/wizard/account_resequence.py
  addons/l10n_in/__manifest__.py
  addons/l10n_in/views/account_journal_views.xml
  addons/l10n_in/views/res_company_view.xml
  addons/l10n_in/views/res_country_state_view.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/post_processing.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/product_expiry/models/stock_move_line.py
  addons/product_expiry/tests/test_stock_production_lot.py
  addons/purchase_stock/models/purchase.py
  addons/sale_stock/models/sale_order.py
  addons/sale_timesheet/models/project.py
  addons/stock/models/stock_move_line.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/website_sale/views/templates.xml
Labels: 15.0

#17445 Syncing from upstream odoo/odoo (13.0)
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_margin/models/sale_order.py
Labels: 13.0

#17446 Syncing from upstream odoo/odoo (14.0)
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/sale/models/sale.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web_editor/controllers/main.py
  addons/web_editor/models/ir_ui_view.py
  addons/website_forum/views/website_forum.xml
Labels: 14.0

#17447 Syncing from upstream odoo/odoo (15.0)
  addons/sale/models/res_partner.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/web_editor/controllers/main.py
  addons/web_editor/models/ir_ui_view.py
  odoo/addons/base/models/res_currency.py
Labels: 15.0

#17458 Syncing from upstream odoo/odoo (13.0)
  addons/sale_stock/models/account_move.py
Labels: 13.0

#17459 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
Labels: 14.0

#17460 Syncing from upstream odoo/odoo (15.0)
  addons/point_of_sale/static/src/js/models.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  odoo/addons/base/data/res_country_data.xml
Labels: 15.0

#17461 Syncing from upstream odoo/odoo (master)
  addons/bus/models/ir_websocket.py
  addons/bus/static/tests/helpers/mock_server.js
  addons/bus/static/tests/helpers/mock_server/models/ir_websocket.js
  addons/hr_timesheet/static/tests/timesheet_uom_widgets_tests.js
  addons/mail/models/ir_websocket.py
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/static/tests/helpers/mock_server/models/ir_websocket.js
  addons/mail/static/tests/helpers/model_definitions_setup.js
  addons/mail/static/tests/qunit_suite_tests/components/persona_im_status_icon_tests.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/tests/test_sync_microsoft2odoo.py
  addons/project/wizard/project_task_type_delete.py
  addons/sale_product_matrix/models/__init__.py
  addons/sale_product_matrix/models/sale_order_line.py
  addons/web/static/src/views/fields/float_toggle/float_toggle_field.js
  addons/web_editor/controllers/main.py
  addons/web_editor/models/ir_ui_view.py
  addons/website_forum/views/website_forum.xml
  odoo/release.py
Labels: master

#17462 Syncing from upstream odoo/odoo (staging.13.0)
  addons/sale_stock/models/account_move.py
Labels: staging.13.0

#17463 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
Labels: staging.14.0

#17466 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi/models/account_edi_document.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_quant_views.xml
  addons/website_forum/views/website_forum.xml
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-15.2

#17467 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/static/src/leave_stats/leave_stats.js
  addons/point_of_sale/static/src/js/models.js
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/stock/views/stock_quant_views.xml
  addons/website_forum/views/website_forum.xml
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-15.3

#17468 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/sale_stock/models/account_move.py
Labels: tmp.13.0

#17469 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
Labels: tmp.14.0

#17471 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/l10n_in/views/report_invoice.xml
  addons/stock_account/models/stock_inventory.py
Labels: 13.0

#17473 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_notifications.py
  addons/hr/data/hr_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_gift_card/i18n/pos_gift_card.pot
  addons/pos_gift_card/static/src/js/models.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale_margin/__init__.py
  addons/pos_sale_margin/__manifest__.py
  addons/pos_sale_margin/report/__init__.py
  addons/pos_sale_margin/report/sale_report.py
  addons/pos_sale_margin/tests/__init__.py
  addons/pos_sale_margin/tests/test_pos_sale_margin_report.py
  addons/sale/models/payment_transaction.py
  addons/sale/models/sale_order_line.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
  addons/sale_purchase/models/sale_order.py
  addons/sale_stock/models/account_move.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web/tests/test_base_document_layout.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_actions_report.py
  setup/win32/Makefile
Labels: 15.0

#17476 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/gift_card/models/gift_card.py
  addons/hr/data/hr_data.xml
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_gift_card/models/gift_card.py
  addons/pos_sale/report/sale_report.py
  addons/pos_sale_margin/__init__.py
  addons/pos_sale_margin/__manifest__.py
  addons/pos_sale_margin/report/__init__.py
  addons/pos_sale_margin/report/sale_report.py
  addons/pos_sale_margin/tests/__init__.py
  addons/pos_sale_margin/tests/test_pos_sale_margin_report.py
  addons/sale/models/payment_transaction.py
  addons/sale_product_matrix/static/tests/tours/sale_product_matrix_tour.js
  addons/sale_purchase/models/sale_order.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/legacy/fields/relational_fields_tests.js
  addons/web/tests/test_base_document_layout.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/individual/angelmoya.md
  odoo/addons/base/models/ir_actions_report.py
  setup/win32/Makefile
Labels: tmp.saas-15.2

#17477 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/models/account_move.py
  addons/hr/data/hr_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/sale/models/payment_transaction.py
  addons/sale_purchase/models/sale_order_line.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/models/base_document_layout.py
  addons/web/tests/test_base_document_layout.py
  doc/cla/individual/angelmoya.md
  odoo/addons/base/models/ir_actions_report.py
  setup/win32/Makefile
Labels: tmp.saas-15.3

#17478 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/l10n_in/views/report_invoice.xml
  addons/stock_account/models/stock_inventory.py
Labels: tmp.13.0

#17479 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_notifications.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/test_oss.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/sale_stock/models/account_move.py
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
Labels: tmp.14.0

#17482 Syncing from upstream odoo/odoo (14.0)
  addons/mrp_account/models/product.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website_event/static/src/js/website_event.js
  addons/website_event/views/event_templates_page_registration.xml
Labels: 14.0

#17483 Syncing from upstream odoo/odoo (15.0)
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_eu_oss/models/eu_tag_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/l10n_it_stock_ddt/models/account_invoice.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp_account/models/product.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/views/website_templates.xml
  addons/website_event/static/src/js/website_event.js
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/data/res.country.state.csv
Labels: 15.0

#17490 Syncing from upstream odoo/odoo (master)
  .tx/config
  addons/account/i18n/account.pot
  addons/account_edi/i18n/account_edi.pot
  addons/account_fleet/i18n/account_fleet.pot
  addons/analytic/i18n/analytic.pot
  addons/auth_totp_mail_enforce/i18n/auth_totp_mail_enforce.pot
  addons/calendar/i18n/calendar.pot
  addons/crm_iap_mine/i18n/crm_iap_mine.pot
  addons/event_crm/i18n/event_crm.pot
  addons/google_account/i18n/google_account.pot
  addons/hr/i18n/hr.pot
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_gamification/i18n/hr_gamification.pot
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_skills/i18n/hr_skills.pot
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/l10n_multilang/i18n/l10n_multilang.pot
  addons/loyalty/i18n/loyalty.pot
  addons/mail/i18n/mail.pot
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/portal_rating/i18n/portal_rating.pot
  addons/pos_adyen/i18n/pos_adyen.pot
  addons/pos_hr/i18n/pos_hr.pot
  addons/pos_mercury/i18n/pos_mercury.pot
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/product/i18n/product.pot
  addons/project/i18n/project.pot
  addons/project_hr_expense/i18n/project_hr_expense.pot
  addons/project_mrp/i18n/project_mrp.pot
  addons/project_purchase/i18n/project_purchase.pot
  addons/project_sms/i18n/project_sms.pot
  addons/purchase/i18n/purchase.pot
  addons/purchase_requisition/i18n/purchase_requisition.pot
  addons/resource/i18n/resource.pot
  addons/sale/i18n/sale.pot
  addons/sale_expense/i18n/sale_expense.pot
  addons/sale_product_configurator/i18n/sale_product_configurator.pot
  addons/sale_project/i18n/sale_project.pot
  addons/sale_timesheet/i18n/sale_timesheet.pot
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/stock/i18n/stock.pot
  addons/test_event_full/static/src/js/tours/wevent_register_tour.js
  addons/test_event_full/tests/test_wevent_register.py
  addons/uom/i18n/uom.pot
  addons/web/i18n/web.pot
  addons/web_unsplash/i18n/web_unsplash.pot
  addons/website/i18n/website.pot
  addons/website_event_booth_exhibitor/i18n/website_event_booth_exhibitor.pot
  addons/website_slides/i18n/website_slides.pot
  odoo/addons/base/i18n/base.pot
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/models.py
  odoo/modules/registry.py
  odoo/tools/translate.py
Labels: master

#17491 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/static/src/js/reconciliation/reconciliation_model.js
  addons/l10n_in/views/report_invoice.xml
  addons/stock_account/models/stock_inventory.py
Labels: staging.13.0

#17492 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_notifications.py
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/test_oss.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/mrp_account/models/product.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_event/static/src/js/website_event.js
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
Labels: staging.14.0

#17493 [t132061] v15 mig: Accounting group in settings shown as checkboxes
  odoo/addons/base/models/res_users.py
Labels: feature, 15.0.project_sv_559

#17494 Syncing from upstream odoo/odoo (13.0)
  .github/PULL_REQUEST_TEMPLATE.md
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/website_event_sale/models/sale_order.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: 13.0

#17495 Syncing from upstream odoo/odoo (14.0)
  .github/PULL_REQUEST_TEMPLATE.md
  addons/account/tests/common.py
  addons/website_event_sale/models/sale_order.py
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: 14.0

#17496 Syncing from upstream odoo/odoo (15.0)
  .github/PULL_REQUEST_TEMPLATE.md
  addons/account/tests/common.py
  addons/hr/views/hr_employee_views.xml
  addons/payment/models/payment_transaction.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/db.js
  addons/pos_restaurant/static/src/js/multiprint.js
  addons/website_event_booth_sale/models/sale_order.py
  addons/website_event_sale/models/sale_order.py
  addons/website_forum/views/website_forum.xml
  addons/website_sale/models/sale_order.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  doc/cla/individual/jpcweb.md
  doc/cla/individual/malaycmkhamar.md
  doc/cla/individual/mouafiq.md
Labels: 15.0

#17515 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/account.pot
  addons/account/views/report_invoice.xml
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
Labels: 13.0

#17516 Syncing from upstream odoo/odoo (14.0)
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/l10n_in/views/report_invoice.xml
  addons/purchase_stock/models/product.py
  addons/website/static/src/js/menu/seo.js
  doc/cla/individual/miikanissi.md
Labels: 14.0

#17517 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/pos_sale_product_configurator/static/src/js/models.js
  addons/project/models/project.py
  addons/project/tests/test_project_subtasks.py
  addons/purchase_stock/models/product.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/static/src/js/menu/seo.js
  doc/cla/individual/miikanissi.md
Labels: 15.0

#17521 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/l10n_in/views/report_invoice.xml
  addons/purchase_stock/models/product.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/website/static/src/js/menu/seo.js
  doc/cla/individual/miikanissi.md
Labels: tmp.14.0

#17522 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_journal.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/pos_sale_product_configurator/static/src/js/models.js
  addons/project/models/project.py
  addons/project/tests/test_project_subtasks.py
  addons/purchase_stock/models/product.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/static/src/js/menu/seo.js
  doc/cla/individual/miikanissi.md
Labels: tmp.15.0

#17525 [bt#20333] migration modules for deprecated basic auth
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_company.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  addons/web/static/lib/jquery/jquery.js
Labels: 11.0.project_qt_291.test

#17526 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_payment_term.py
  addons/account/wizard/account_resequence.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/js/core/dom.js
  addons/web/static/src/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
Labels: 14.0

#17527 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_payment.py
  addons/account/models/account_payment_term.py
  addons/event_booth_sale/models/__init__.py
  addons/event_booth_sale/models/sale_order_template_line.py
  addons/event_sale/models/__init__.py
  addons/event_sale/models/sale_order_template_line.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/payment/static/src/js/post_processing.js
  addons/payment_authorize/models/authorize_request.py
  addons/sale/static/src/js/variant_mixin.js
  addons/sale_product_configurator/views/templates.xml
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  addons/website_sale_product_configurator/static/tests/tours/website_sale_preconfigured_variant_price.js
  addons/website_sale_product_configurator/tests/__init__.py
  addons/website_sale_product_configurator/tests/test_website_sale_configurator.py
Labels: 15.0

#17530 [bt#20455] Add 2 new modules
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
Labels: enhancement, 13.0.project_pm_597

#17531 Syncing from upstream odoo/odoo (13.0)
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_currency.py
Labels: 13.0

#17532 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/purchase_stock/models/purchase.py
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_translation.py
Labels: 14.0

#17533 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/widget_link.js
  doc/cla/individual/vvanneri-ia.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_mail.py
Labels: 15.0

#17536 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_payment_term.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_account_move_out_refund.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/barcodes/models/ir_http.py
  addons/barcodes/static/src/js/barcode_events.js
  addons/crm/tests/test_performances.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_ar/demo/account_supplier_invoice_demo.xml
  addons/l10n_ar/demo/account_supplier_refund_demo.xml
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/payment/models/payment_transaction.py
  addons/payment/static/src/js/post_processing.js
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/src/js/Screens/SplitBillScreen/SplitBillScreen.js
  addons/pos_sale_product_configurator/static/src/js/models.js
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/src/js/menu/seo.js
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  doc/cla/individual/miikanissi.md
  odoo/addons/base/models/ir_translation.py
Labels: tmp.saas-15.2

#17538 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_currency.py
Labels: tmp.13.0

#17539 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_payment_term.py
  addons/account/wizard/account_resequence.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_stock/models/purchase.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/js/core/dom.js
  addons/web/static/src/js/libs/jquery.js
  addons/web/static/src/js/views/basic/basic_model.js
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  doc/cla/corporate/manatec.md
  odoo/addons/base/models/ir_translation.py
Labels: tmp.14.0

#17540 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_payment.py
  addons/account/models/account_payment_term.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/event_booth_sale/models/__init__.py
  addons/event_booth_sale/models/sale_order_template_line.py
  addons/event_sale/models/__init__.py
  addons/event_sale/models/sale_order_template_line.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/payment/static/src/js/post_processing.js
  addons/payment_authorize/models/authorize_request.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/static/src/js/variant_mixin.js
  addons/sale_coupon/models/sale_order.py
  addons/sale_product_configurator/views/templates.xml
  addons/sale_stock/views/sale_stock_portal_template.xml
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  addons/website_sale_product_configurator/static/tests/tours/website_sale_preconfigured_variant_price.js
  addons/website_sale_product_configurator/tests/__init__.py
  addons/website_sale_product_configurator/tests/test_website_sale_configurator.py
  doc/cla/individual/vvanneri-ia.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_mail.py
Labels: tmp.15.0

#17542 [t130552][t127490] Migration to v15: Extend account.move 'posted' status to include 'posted_sent' (missing change)
  addons/account/wizard/account_payment_register.py
Labels: bug, 15.0.project_sv_559

#17543 [t132097] Adaptions of debtor name in QR for SV
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
Labels: enhancement, 15.0.project_sv_559
