Repository brain-tec/odoo, pull requests merged in 2022-03, with the labels that each got.

#16228 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_proxy_client/models/account_edi_proxy_auth.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/ir.model.access.csv
  addons/event_sale/models/sale_order.py
  addons/sale/views/sale_views.xml
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
Labels: 14.0

#16231 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/i18n/ca.po
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/account/i18n/nb.po
  addons/account/i18n/sv.po
  addons/account_debit_note/i18n/ca.po
  addons/account_edi/i18n/de.po
  addons/account_edi_proxy_client/models/account_edi_proxy_auth.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/ir.model.access.csv
  addons/account_fleet/i18n/ca.po
  addons/account_lock/i18n/ca.po
  addons/account_tax_python/i18n/ca.po
  addons/account_tax_python/i18n/ja.po
  addons/adyen_platforms/i18n/de.po
  addons/analytic/i18n/ca.po
  addons/auth_oauth/i18n/ca.po
  addons/auth_signup/i18n/it.po
  addons/auth_totp_portal/i18n/de.po
  addons/barcodes/i18n/ca.po
  addons/barcodes/i18n/it.po
  addons/base_setup/i18n/ca.po
  addons/base_setup/i18n/vi.po
  addons/calendar/i18n/ca.po
  addons/calendar_sms/i18n/ca.po
  addons/contacts/i18n/es.po
  addons/coupon/i18n/de.po
  addons/coupon/i18n/et.po
  addons/coupon/i18n/it.po
  addons/crm/i18n/ca.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/delivery/i18n/es.po
  addons/delivery/i18n/th.po
  addons/digest/i18n/ca.po
  addons/digest/i18n/it.po
  addons/event/i18n/th.po
  addons/event_sale/models/sale_order.py
  addons/sale/views/sale_views.xml
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/th.po
Labels: staging.14.0

#16234 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account_edi/models/account_move.py
  addons/account_edi_proxy_client/models/account_edi_proxy_auth.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/ir.model.access.csv
  addons/event_sale/models/sale_order.py
  addons/hr/models/hr_employee_base.py
  addons/hr_holidays/static/src/js/time_off_calendar/time_off_calendar_controller.js
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_eg/__init__.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/data/account.account.template.csv
  addons/l10n_eg/data/account_chart_template_data.xml
  addons/l10n_eg/data/account_tax_group_data.xml
  addons/l10n_eg/data/account_tax_report_data.xml
  addons/l10n_eg/data/account_tax_template_data.xml
  addons/l10n_eg/data/fiscal_templates_data.xml
  addons/l10n_eg/data/l10n_eg_chart_data.xml
  addons/l10n_eg/data/l10n_eg_chart_post_data.xml
  addons/l10n_eg/demo/demo_company.xml
  addons/l10n_eg/demo/demo_partner.xml
  addons/l10n_eg/i18n_extra/ar_001.po
  addons/l10n_eg/i18n_extra/l10n_eg.pot
  addons/l10n_eg/models/__init__.py
  addons/l10n_eg/models/account_chart_template.py
  addons/l10n_eg/models/account_tax.py
  addons/l10n_eg/views/account_tax.xml
  addons/l10n_in_purchase/models/account_move.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/microsoft_calendar/models/calendar.py
  addons/payment/models/payment_transaction.py
  addons/payment_stripe/models/payment_acquirer.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_coupon/models/pos_order.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/sale/views/sale_views.xml
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/tests/legacy/fields/relational_fields/field_many2one_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
Labels: tmp.saas-15.1

#16236 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/wizard/account_move_reversal.py
  addons/account_debit_note/wizard/account_debit_note.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_quant.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
Labels: tmp.13.0

#16237 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_proxy_client/models/account_edi_proxy_auth.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/ir.model.access.csv
  addons/event_sale/models/sale_order.py
  addons/sale/views/sale_views.xml
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
Labels: tmp.14.0

#16238 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account_edi_proxy_client/models/account_edi_proxy_auth.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/ir.model.access.csv
  addons/account_sale_timesheet/models/project.py
  addons/event_sale/models/sale_order.py
  addons/hr/models/hr_employee_base.py
  addons/hr_attendance/models/hr_employee.py
  addons/hr_attendance/tests/test_hr_attendance_process.py
  addons/hr_expense/models/account_move_line.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_in_purchase/models/account_move.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/microsoft_calendar/models/calendar.py
  addons/payment/models/payment_transaction.py
  addons/payment_stripe/models/payment_acquirer.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/project/models/project.py
  addons/project_hr_expense/models/project.py
  addons/project_mrp/models/project.py
  addons/project_purchase/models/project.py
  addons/sale/views/sale_views.xml
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_project_account/models/project.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/stock/tests/test_quant.py
  addons/web/static/src/legacy/js/_deprecated/basic_fields.js
  addons/web/static/src/legacy/js/views/basic/basic_view.js
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/js/tour_manager.js
Labels: tmp.15.0

#16240 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/stock_landed_costs/models/stock_landed_cost.py
  doc/cla/corporate/systemworks.md
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
Labels: 14.0

#16243 Syncing from upstream odoo/odoo (13.0)
  addons/account/views/account_move_views.xml
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/sale/views/sale_views.xml
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/addons/test_converter/tests/test_html.py
  odoo/tools/cloc.py
Labels: 13.0

#16244 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/repair/models/repair.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/models/website.py
  addons/website_slides/controllers/main.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/tools/cloc.py
Labels: 14.0

#16245 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/account_edi_ubl_bis3/models/account_edi_format.py
  addons/auth_totp_mail_enforce/models/res_users.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/website_slides/controllers/main.py
  doc/cla/corporate/systemworks.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/qweb.py
  odoo/addons/base/models/res_users.py
Labels: 15.0

#16250 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/payment_stripe_sca/controllers/main.py
  doc/cla/individual/petrus-v.md
Labels: staging.saas-12.3

#16254 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/repair/models/repair.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/models/website.py
  addons/website_slides/controllers/main.py
  doc/cla/corporate/systemworks.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/tools/cloc.py
Labels: staging.14.0

#16257 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/models/account_move_line_tax_details.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_sale_timesheet/models/project.py
  addons/auth_totp_mail_enforce/models/res_users.py
  addons/board/static/src/legacy/js/board_view.js
  addons/hr_attendance/models/hr_employee.py
  addons/hr_attendance/tests/test_hr_attendance_process.py
  addons/hr_expense/models/account_move_line.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/project.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/payment_stripe/models/payment_acquirer.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/project/models/project.py
  addons/project_hr_expense/models/project.py
  addons/project_mrp/models/project.py
  addons/project_purchase/models/project.py
  addons/purchase_stock/models/stock.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_project_account/models/project.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move2.py
  addons/stock/tests/test_quant.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/web/static/src/legacy/js/_deprecated/basic_fields.js
  addons/web/static/src/legacy/js/views/basic/basic_view.js
  addons/web/static/tests/legacy/fields/relational_fields/field_many2one_tests.js
  addons/web_editor/static/lib/odoo-editor/demo/index.html
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/checklist.css
  addons/web_editor/static/lib/odoo-editor/test/editor-test.html
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_tour/static/src/js/tip.js
  addons/web_tour/static/src/js/tour_manager.js
  addons/website/models/mixins.py
  addons/website/static/src/js/menu/edit.js
  addons/website_slides/controllers/main.py
  doc/cla/corporate/systemworks.md
  odoo/addons/base/models/qweb.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
Labels: tmp.saas-15.1

#16260 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/repair/models/repair.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/website_sale/__init__.py
  addons/website_sale/__manifest__.py
  addons/website_sale/models/website.py
  addons/website_slides/controllers/main.py
  doc/cla/corporate/systemworks.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
  odoo/tools/cloc.py
Labels: tmp.14.0

#16261 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_facturx/tests/test_facturx.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/account_edi_ubl_bis3/models/account_edi_format.py
  addons/auth_totp_mail_enforce/models/res_users.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/purchase_stock/models/stock.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/web_editor/static/lib/odoo-editor/demo/index.html
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/checklist.css
  addons/web_editor/static/lib/odoo-editor/test/editor-test.html
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/js/menu/edit.js
  addons/website_slides/controllers/main.py
  doc/cla/corporate/systemworks.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/qweb.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/models.py
Labels: tmp.15.0

#16262 Syncing from upstream odoo/odoo (14.0)
  addons/account/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/hr/views/res_users.xml
  addons/l10n_ar/demo/account_customer_refund_demo.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_six/static/src/js/payment_six.js
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/views/sale_views.xml
  odoo/addons/base/models/ir_translation.py
Labels: 14.0

#16265 Syncing from upstream odoo/odoo (13.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/views/account_move_views.xml
  addons/lunch/controllers/main.py
  odoo/models.py
  odoo/tests/common.py
Labels: 13.0

#16266 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_pe/data/res_country_data.xml
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_packing.py
Labels: 14.0

#16267 Syncing from upstream odoo/odoo (15.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/mail/models/mail_mail.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_six/static/src/js/payment_six.js
  addons/sale_expense/models/hr_expense.py
  addons/sale_expense/views/hr_expense_views.xml
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/web/static/src/legacy/js/views/search_panel_model_extension.js
  addons/web/static/tests/search/search_panel_tests.js
Labels: 15.0

#16268 Syncing from upstream odoo/odoo (master)
  addons/account_edi/models/account_edi_document.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr_expense/data/hr_expense_demo.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/static/src/leave_stats/leave_stats.xml
  addons/hr_holidays/static/src/scss/time_off.scss
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_holidays/views/resource_views.xml
  addons/mail/models/ir_attachment.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/tests/helpers/mock_models.js
  addons/mail/views/mail_activity_views.xml
  addons/mail/views/mail_followers_views.xml
  addons/mail/views/mail_message_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/models/mrp_production.py
  addons/pos_six/static/src/js/payment_six.js
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/resource/models/resource.py
  addons/sale_expense/models/hr_expense.py
  addons/sale_expense/views/hr_expense_views.xml
  addons/stock/models/stock_move_line.py
  addons/test_mail/__manifest__.py
  addons/test_mail/static/tests/helpers/mock_models.js
  addons/test_mail/static/tests/tracking_value_tests.js
  addons/web/__manifest__.py
  addons/web/static/lib/es6-promise/es6-promise-polyfill.js
  addons/web/static/src/core/pager/pager.scss
  addons/web/static/src/core/pager/pager.xml
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/src/libs/bs5_utility_classes.scss
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_cloc.py
  odoo/tools/cloc.py
Labels: master

#16269 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_move_views.xml
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/account_edi_ubl_bis3/models/account_edi_format.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr_expense/data/hr_expense_data.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/models/product_template.py
  addons/hr_expense/static/src/js/expense_views.js
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/src/xml/documents_upload_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/mail/models/mail_mail.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_six/static/src/js/payment_six.js
  addons/sale/views/sale_views.xml
  addons/sale_expense/views/product_view.xml
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/web/static/src/legacy/js/views/search_panel_model_extension.js
  addons/web/static/tests/search/search_panel_tests.js
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/tools/cloc.py
Labels: tmp.saas-15.1

#16271 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/views/account_move_views.xml
  addons/lunch/controllers/main.py
  odoo/models.py
  odoo/tests/common.py
Labels: tmp.13.0

#16272 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/hr/views/res_users.xml
  addons/l10n_ar/demo/account_customer_refund_demo.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/l10n_pe/data/res_country_data.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_six/static/src/js/payment_six.js
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/views/sale_views.xml
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_packing.py
  odoo/addons/base/models/ir_translation.py
Labels: tmp.14.0

#16276 Syncing from upstream odoo/odoo (master)
  addons/account/views/account_move_views.xml
Labels: master

#16277 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/views/account_move_views.xml
  addons/l10n_pe/data/res_country_data.xml
Labels: tmp.saas-15.1

#16279 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/views/account_move_views.xml
  addons/l10n_ar/models/account_move.py
Labels: tmp.14.0

#16280 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/views/account_move_views.xml
  addons/l10n_pe/data/res_country_data.xml
Labels: tmp.15.0

#16281 Syncing from upstream odoo/odoo (master)
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
Labels: master

#16282 Syncing from upstream odoo/odoo (staging.saas-15.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_move_views.xml
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_facturx/i18n/account_edi_facturx.pot
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_ubl/models/account_edi_format.py
  addons/account_edi_ubl_bis3/models/account_edi_format.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr_expense/data/hr_expense_data.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/models/product_template.py
  addons/hr_expense/static/src/js/expense_views.js
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/src/xml/documents_upload_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_fr_pos_cert/models/account_bank_statement.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/l10n_pe/data/res_country_data.xml
  addons/mail/models/mail_mail.py
  addons/mail/wizard/mail_compose_message.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_six/static/src/js/payment_six.js
  addons/sale/views/sale_views.xml
  addons/sale_expense/views/product_view.xml
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/web/static/src/legacy/js/views/search_panel_model_extension.js
  addons/web/static/tests/search/search_panel_tests.js
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_cloc.py
  odoo/tools/cloc.py
Labels: staging.saas-15.1

#16284 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/i18n/account.pot
  addons/account/models/account.py
  addons/account/views/account_move_views.xml
  addons/lunch/controllers/main.py
  odoo/models.py
  odoo/tests/common.py
Labels: staging.13.0

#16285 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/hr/views/res_users.xml
  addons/l10n_ar/demo/account_customer_refund_demo.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/l10n_pe/data/res_country_data.xml
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_six/static/src/js/payment_six.js
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/views/sale_views.xml
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_packing.py
  odoo/addons/base/models/ir_translation.py
Labels: staging.14.0

#16289 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/delivery/models/delivery_grid.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mrp/models/product.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/sale/models/sale.py
  addons/sale/tests/test_onchange.py
  addons/sale/tests/test_sale_order.py
  addons/sale/views/sale_views.xml
Labels: 13.0

#16290 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_bank_statement.py
  addons/account_edi/i18n/account_edi.pot
  addons/account_edi/models/account_edi_document.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mail/models/mail_channel.py
  addons/membership/views/partner_views.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/sale/views/sale_views.xml
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/test_converter/tests/test_html.py
  odoo/models.py
  odoo/tests/common.py
Labels: 14.0

#16291 Syncing from upstream odoo/odoo (15.0)
  addons/crm/tests/test_performances.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_tour.js
  addons/membership/views/partner_views.xml
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/stock_rule.py
  addons/purchase/models/account_invoice.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/views/sale_views.xml
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/test_discuss_full/tests/test_performance.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/static/src/js/website_forum.editor.js
  addons/website_forum/static/src/js/website_forum.js
  odoo/models.py
  odoo/tests/common.py
Labels: 15.0

#16292 Syncing from upstream odoo/odoo (master)
  addons/account/controllers/portal.py
  addons/calendar/models/calendar_event.py
  addons/calendar/static/src/js/calendar_controller.js
  addons/calendar/static/src/js/services/calendar_notification_service.js
  addons/calendar/static/tests/calendar_notification_tests.js
  addons/calendar/views/calendar_views.xml
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_holidays/tests/test_company_leave.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/views/project_views.xml
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/mail/static/src/components/chat_window/chat_window.js
  addons/mail/static/src/components/chat_window/chat_window.xml
  addons/mail/static/src/components/popover_view/popover_view.js
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mail/static/src/models/chat_window/chat_window.js
  addons/mail/static/src/models/chatter/chatter.js
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_tour.js
  addons/membership/views/partner_views.xml
  addons/microsoft_calendar/static/src/js/microsoft_calendar.js
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/stock_rule.py
  addons/project/models/project.py
  addons/project/report/project_report.py
  addons/project/report/project_report_views.xml
  addons/project/report/project_task_burndown_chart_report.py
  addons/project/report/project_task_burndown_chart_report_views.xml
  addons/project/views/project_views.xml
  addons/sale/models/res_config_settings.py
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/views/sale_order_views.xml
  addons/sale_timesheet/models/project.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant_inventory_mode.py
  addons/test_discuss_full/tests/test_performance.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  odoo/addons/test_lint/tests/test_eslint.py
Labels: master

#16293 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/discuss.js
Labels: 13.0

#16294 Syncing from upstream odoo/odoo (14.0)
  addons/delivery/models/delivery_grid.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
  addons/mail/static/src/components/thread_icon/thread_icon.xml
  addons/mail/static/src/models/discuss/discuss.js
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/sale/models/res_partner.py
  addons/sale/views/res_partner_views.xml
  addons/website/static/src/js/content/menu.js
Labels: 14.0

#16295 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_bank_statement.py
  addons/account/tests/test_account_bank_statement.py
  addons/account_fleet/models/account_move.py
  addons/account_fleet/models/fleet_vehicle.py
  addons/account_fleet/views/account_move_views.xml
  addons/calendar/data/mail_template_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/delivery/models/delivery_grid.py
  addons/l10n_de_stock/models/stock.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
  addons/mail/static/src/models/discuss/discuss.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/tests/test_mail_channel.py
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_workorder.py
  addons/payment_stripe/models/payment_acquirer.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_discuss_full/tests/test_performance.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
Labels: 15.0

#16288 [t126954] Odoo Security Advisory - ODOO-SA-2021-12-28 (v14)
  addons/auth_signup/controllers/main.py
  addons/http_routing/models/ir_http.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/static/src/models/messaging_notification_handler/messaging_notification_handler.js
  addons/payment/models/account_invoice.py
  addons/sale/models/sale.py
  addons/web/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_demo.py
  odoo/addons/base/models/ir_module.py
  odoo/http.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tools/misc.py
Labels: 14.0.project_va_da_170

#16297 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_ar/models/res_partner.py
  setup/package.py
Labels: 13.0

#16298 Syncing from upstream odoo/odoo (14.0)
  addons/hr/models/res_users.py
  addons/hr/tests/test_self_user_access.py
  addons/hr/views/res_users.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/purchase_stock/models/account_invoice.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
Labels: 14.0

#16299 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/ir_actions_report.py
  addons/account/models/product.py
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_hu/data/account_tax_template_data.xml
  addons/l10n_il/data/account_tax_template_data.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/discuss/tests/discuss_tests.js
  addons/mail/static/src/components/thread_icon/thread_icon.xml
  addons/mail/static/src/models/discuss_sidebar_category_item/discuss_sidebar_category_item.js
  addons/sale/models/res_partner.py
  addons/sale/views/res_partner_views.xml
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/web/controllers/profiling.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/assetsbundle.py
  odoo/tools/pdf.py
Labels: 15.0

#16300 Syncing from upstream odoo/odoo (master)
  addons/account/models/ir_actions_report.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/hr/models/res_users.py
  addons/hr/tests/test_self_user_access.py
  addons/hr/views/res_users.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_hu/data/account_tax_template_data.xml
  addons/l10n_il/data/account_tax_template_data.xml
  addons/l10n_it_edi_sdicoop/models/res_config_settings.py
  addons/l10n_it_edi_sdicoop/views/res_config_settings_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
  addons/mail/static/src/components/chatter_topbar/tests/chatter_topbar_tests.js
  addons/mail/static/src/components/follower_list_menu/tests/follower_list_menu_tests.js
  addons/mail/static/src/components/rtc_controller/rtc_controller.xml
  addons/mail/static/src/models/attachment/attachment.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/tests/helpers/mock_models.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/payment/data/payment_acquirer_data.xml
  addons/payment/tests/utils.py
  addons/payment_buckaroo/tests/test_buckaroo.py
  addons/payment_sips/tests/test_sips.py
  addons/payment_stripe/const.py
  addons/payment_stripe/data/payment_acquirer_data.xml
  addons/payment_stripe/models/payment_acquirer.py
  addons/payment_stripe/models/payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/project/models/project.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_discuss_full/tests/test_performance.py
  addons/web/controllers/profiling.py
  addons/web/static/src/core/hotkeys/hotkey_service.js
  addons/web/static/src/legacy/js/widgets/name_and_signature.js
  addons/web/static/src/views/graph/graph_view.xml
  addons/web/static/src/views/helpers/standard_view_props.js
  addons/web/static/src/views/pivot/pivot_view.xml
  addons/web/static/src/views/view.js
  addons/web/static/src/views/view.xml
  addons/web/static/src/webclient/actions/action_container.js
  addons/web/static/tests/core/hotkeys/hotkey_service_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web/static/tests/views/view_tests.js
  addons/web/static/tests/webclient/actions/legacy_tests.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/static/src/js/website_forum.share.js
  addons/website_forum/static/src/xml/public_templates.xml
  addons/website_forum/static/src/xml/website_forum_templates.xml
  odoo/tests/common.py
  odoo/tools/pdf.py
Labels: master

#16301 Syncing from upstream odoo/odoo (13.0)
  addons/account/models/account_move.py
  addons/payment_sips/models/payment.py
Labels: 13.0

#16302 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/base_vat/models/res_partner.py
  addons/payment_sips/models/payment.py
  addons/sale/models/sale.py
  addons/sale/tests/test_onchange.py
  addons/sale/tests/test_sale_order.py
  addons/survey/controllers/main.py
Labels: 14.0

#16303 Syncing from upstream odoo/odoo (15.0)
  addons/account/__manifest__.py
  addons/account/i18n/account.pot
  addons/account/models/__init__.py
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/ir_module_module.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr/models/res_users.py
  addons/hr/tests/test_self_user_access.py
  addons/hr/views/res_users.xml
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/payment/controllers/portal.py
  addons/purchase_stock/models/account_invoice.py
  addons/sale/tests/test_sale_order.py
  addons/survey/controllers/main.py
  addons/web/tooling/_husky/pre-commit
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  doc/cla/individual/nattajs.md
  odoo/addons/base/data/res.lang.csv
Labels: 15.0

#16310 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/delivery/models/delivery_grid.py
  addons/l10n_ar/models/res_partner.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/discuss.js
  addons/mrp/models/product.py
  addons/payment_sips/models/payment.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/sale/models/sale.py
  addons/sale/tests/test_onchange.py
  addons/sale/tests/test_sale_order.py
  addons/sale/views/sale_views.xml
  setup/package.py
Labels: staging.13.0

#16316 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/models/account.py
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/delivery/models/delivery_grid.py
  addons/l10n_ar/models/res_partner.py
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_dk/data/account_tax_template_data.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mail/static/src/js/discuss.js
  addons/mrp/models/product.py
  addons/payment_sips/models/payment.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/sale/models/sale.py
  addons/sale/tests/test_onchange.py
  addons/sale/tests/test_sale_order.py
  addons/sale/views/sale_views.xml
  setup/package.py
Labels: tmp.13.0

#16319 Syncing from upstream odoo/odoo (13.0)
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_service/models/__init__.py
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/__init__.py
  addons/l10n_eu_service/tests/test_oss.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: 13.0

#16320 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_service/models/__init__.py
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/__init__.py
  addons/l10n_eu_service/tests/test_oss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_blacklist.py
  addons/mail/models/mail_thread_blacklist.py
  addons/payment/static/lib/jquery.payment/jquery.payment.js
  addons/sale_margin/views/sale_margin_view.xml
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: 14.0

#16321 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account_check_printing/models/account_payment.py
  addons/account_edi/i18n/account_edi.pot
  addons/account_edi/models/account_edi_document.py
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_oss/models/__init__.py
  addons/l10n_eu_oss/models/eu_tag_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/__init__.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/mail/controllers/discuss.py
  addons/mail/static/src/components/message/tests/message_tests.js
  addons/mail/static/src/models/attachment/attachment.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/models/product.py
  addons/payment_sips/models/payment_acquirer.py
  addons/project/models/project.py
  addons/project/static/src/js/project_list.js
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_onchange.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/cli/templates/default/__manifest__.py.template
  odoo/fields.py
Labels: 15.0

#16322 Syncing from upstream odoo/odoo (master)
  addons/account/__manifest__.py
  addons/account/models/account_tax.py
  addons/account/views/account_tax_views.xml
  addons/account_check_printing/models/account_payment.py
  addons/hr_attendance/views/hr_employee_view.xml
  addons/mail/static/src/models/rtc_session/rtc_session.js
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/mrp/models/product.py
  addons/payment_sips/models/payment_acquirer.py
  addons/project/models/project.py
  addons/project/static/src/js/project_list.js
  addons/sale_margin/views/sale_order_views.xml
  addons/web/static/src/core/hotkeys/hotkey.scss
  addons/web/static/src/core/hotkeys/hotkey_service.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/server_action_tests.js
  addons/web/tooling/_husky/pre-commit
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  doc/cla/individual/nattajs.md
  odoo/addons/base/data/res.lang.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: master

#16325 Syncing from upstream odoo/odoo (master)
  addons/account_edi/i18n/account_edi.pot
  addons/account_edi/models/account_edi_document.py
  addons/l10n_eu_oss/models/__init__.py
  addons/l10n_eu_oss/models/eu_tag_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/__init__.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/project_sms/__init__.py
  addons/project_sms/__manifest__.py
  addons/project_sms/models/__init__.py
  addons/project_sms/models/project.py
  addons/project_sms/models/project_stage.py
  addons/project_sms/models/project_task.py
  addons/project_sms/models/project_task_type.py
  addons/project_sms/security/ir.model.access.csv
  addons/project_sms/security/project_sms_security.xml
  addons/project_sms/views/project_stage_views.xml
  addons/project_sms/views/project_task_type_views.xml
Labels: master

#16327 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_service/models/__init__.py
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/__init__.py
  addons/l10n_eu_service/tests/test_oss.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: tmp.13.0

#16328 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_service/models/__init__.py
  addons/l10n_eu_service/models/eu_tag_map.py
  addons/l10n_eu_service/models/res_company.py
  addons/l10n_eu_service/tests/__init__.py
  addons/l10n_eu_service/tests/test_oss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_blacklist.py
  addons/mail/models/mail_thread_blacklist.py
  addons/payment/static/lib/jquery.payment/jquery.payment.js
  addons/sale_margin/views/sale_margin_view.xml
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/fields.py
Labels: tmp.14.0

#16329 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account_check_printing/models/account_payment.py
  addons/account_edi/i18n/account_edi.pot
  addons/account_edi/models/account_edi_document.py
  addons/hr_attendance/views/hr_employee_view.xml
  addons/l10n_eu_oss/models/__init__.py
  addons/l10n_eu_oss/models/eu_tag_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/__init__.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/mail/controllers/discuss.py
  addons/mail/static/src/components/message/tests/message_tests.js
  addons/mail/static/src/models/attachment/attachment.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/models/product.py
  addons/payment_sips/models/payment_acquirer.py
  addons/project/models/project.py
  addons/project/static/src/js/project_list.js
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_onchange.py
  addons/sale_margin/views/sale_margin_view.xml
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/cli/templates/default/__manifest__.py.template
  odoo/fields.py
Labels: tmp.15.0

#16330 Syncing from upstream odoo/odoo (15.0)
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
Labels: 15.0

#16331 Syncing from upstream odoo/odoo (master)
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
Labels: master

#16332 Syncing from upstream odoo/odoo (13.0)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js
  addons/web/static/lib/jquery/jquery.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/res_users.py
Labels: 13.0

#16333 Syncing from upstream odoo/odoo (14.0)
  addons/digest/models/digest.py
  addons/lunch/controllers/main.py
  addons/purchase_stock/report/report_stock_forecasted.py
  addons/purchase_stock/tests/test_purchase_stock_report.py
  addons/sale_management/models/sale_order.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  doc/cla/individual/shurshilov.md
  odoo/addons/base/models/ir_actions_report.py
Labels: 14.0

#16334 Syncing from upstream odoo/odoo (15.0)
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/common.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/tests/test_expenses_mail_import.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/lunch/controllers/main.py
  addons/lunch/models/lunch_order.py
  addons/mail/i18n/mail.pot
  addons/mail/views/res_config_settings_views.xml
  addons/mail_plugin/models/res_partner.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/payment/models/payment_acquirer.py
  addons/web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js
  addons/web/static/lib/jquery/jquery.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/editor-test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/fontSize.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/website/static/tests/tours/rte.js
  doc/cla/corporate/sprint-it.md
  doc/cla/individual/shurshilov.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/test_converter/tests/test_html.py
Labels: 15.0

#16336 Syncing from upstream odoo/odoo (14.0)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js
  addons/web/static/lib/jquery/jquery.js
Labels: 14.0

#16337 Syncing from upstream odoo/odoo (15.0)
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/purchase_stock/report/report_stock_forecasted.py
  addons/purchase_stock/tests/test_purchase_stock_report.py
Labels: 15.0

#16338 Syncing from upstream odoo/odoo (master)
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa/models/__init__.py
  addons/l10n_sa/models/account_move.py
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa/views/view_move_form.xml
  addons/l10n_sa_invoice/__init__.py
  addons/l10n_sa_invoice/__manifest__.py
  addons/l10n_sa_invoice/models/__init__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/mail/static/src/components/chat_window_header/chat_window_header.js
  addons/mail/static/src/components/chat_window_header/chat_window_header.xml
  addons/mail/static/src/models/chat_window/chat_window.js
  addons/web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js
  addons/web/static/lib/jquery/jquery.js
  odoo/addons/base/i18n/base.pot
Labels: master

#16341 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/purchase_requisition_stock/models/purchase_requisition.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/lib/jquery.ba-bbq/jquery.ba-bbq.js
  addons/web/static/lib/jquery/jquery.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/res_users.py
Labels: tmp.13.0

#16344 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/bills_tree_upload.js
  addons/mrp/models/stock_move.py
  addons/payment_stripe_checkout_webhook/controllers/main.py
  addons/product/models/product.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/security/stock_picking_batch_security.xml
Labels: 13.0

#16345 Syncing from upstream odoo/odoo (14.0)
  addons/account/static/src/js/bills_tree_upload.js
  addons/point_of_sale/static/src/js/models.js
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/security/stock_picking_batch_security.xml
Labels: 14.0

#16346 Syncing from upstream odoo/odoo (15.0)
  addons/digest/models/digest.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_blacklist.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/point_of_sale/static/src/js/models.js
  addons/repair/models/repair.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_robustness.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/security/stock_picking_batch_security.xml
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/website/static/src/scss/website.backend.scss
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/common.py
  addons/website_slides/tests/test_slide_utils.py
Labels: 15.0

#16348 Syncing from upstream odoo/odoo (saas-12.3)
  addons/payment_stripe_checkout_webhook/controllers/main.py
Labels: saas-12.3

#16352 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_proxy_client/__init__.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/delivery/models/sale_order.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/sale/models/sale.py
Labels: 14.0

#16353 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_proxy_client/__init__.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
Labels: 15.0

#16355 Syncing from upstream odoo/odoo (13.0)
  addons/payment_ingenico/data/payment_acquirer_data.xml
  addons/payment_ingenico/models/payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
Labels: 13.0

#16356 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/payment_ingenico/data/payment_acquirer_data.xml
  addons/payment_ingenico/models/payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale/models/sale.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/web_editor/controllers/main.py
Labels: 14.0

#16357 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ar/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_se/data/account_tax_template.xml
  addons/mrp/models/mrp_workorder.py
  addons/sale/models/sale_order_line.py
  addons/sale_management/models/sale_order.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/tests/__init__.py
  addons/web_editor/tests/test_controller.py
Labels: 15.0

#16359 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/static/src/js/bills_upload.js
  addons/account_edi_proxy_client/__init__.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/calendar/data/mail_template_data.xml
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/delivery/views/report_deliveryslip.xml
  addons/digest/models/digest.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/common.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/tests/test_expenses_mail_import.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_se/data/account_tax_template.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_blacklist.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/purchase_stock/report/report_stock_forecasted.py
  addons/purchase_stock/tests/test_purchase_stock_report.py
  addons/repair/models/repair.py
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_onchange.py
  addons/sale_management/models/sale_order.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/security/stock_picking_batch_security.xml
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/website/static/src/scss/website.backend.scss
  odoo/addons/base/models/ir_qweb_fields.py
Labels: tmp.saas-15.1

#16362 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/static/src/js/bills_tree_upload.js
  addons/account_edi_proxy_client/__init__.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/delivery/models/sale_order.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/payment_ingenico/data/payment_acquirer_data.xml
  addons/payment_ingenico/models/payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale/models/sale.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/security/stock_picking_batch_security.xml
  addons/web_editor/controllers/main.py
Labels: tmp.14.0

#16363 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_proxy_client/__init__.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/data/config_demo.xml
  addons/digest/models/digest.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_se/data/account_tax_template.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_blacklist.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/repair/models/repair.py
  addons/sale/models/sale_order_line.py
  addons/sale_management/models/sale_order.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_robustness.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_picking_batch/__manifest__.py
  addons/stock_picking_batch/security/stock_picking_batch_security.xml
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/tests/__init__.py
  addons/web_editor/tests/test_controller.py
  addons/website/static/src/scss/website.backend.scss
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/common.py
  addons/website_slides/tests/test_slide_utils.py
Labels: tmp.15.0

#16364 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/it.po
  addons/account/i18n/sv.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_CN.po
  addons/account_edi/i18n/de.po
  addons/account_edi/i18n/es.po
  addons/account_edi/i18n/uk.po
  addons/account_payment/i18n/sk.po
  addons/adyen_platforms/i18n/it.po
  addons/board/i18n/sv.po
  addons/calendar_sms/i18n/he.po
  addons/coupon/i18n/it.po
  addons/crm/i18n/hr.po
  addons/crm_iap_lead/i18n/he.po
  addons/crm_iap_lead_enrich/i18n/it.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/event/i18n/fr.po
  addons/event/i18n/th.po
  addons/event_crm/i18n/th.po
  addons/event_sale/i18n/th.po
  addons/event_sms/i18n/th.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/he.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/sv.po
  odoo/addons/base/i18n/th.po
Labels: 14.0

#16366 Syncing from upstream odoo/odoo (14.0)
  addons/mrp/models/stock_move.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
Labels: 14.0

#16367 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
Labels: 15.0

#16368 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: master

#16375 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/payment_stripe_checkout_webhook/controllers/main.py
Labels: tmp.saas-12.3

#16378 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/i18n/de.po
  addons/account/i18n/he.po
  addons/account/i18n/it.po
  addons/account/i18n/sv.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_CN.po
  addons/account_edi/i18n/de.po
  addons/account_edi/i18n/es.po
  addons/account_edi/i18n/uk.po
  addons/account_payment/i18n/sk.po
  addons/adyen_platforms/i18n/it.po
  addons/board/i18n/sv.po
  addons/calendar_sms/i18n/he.po
  addons/coupon/i18n/it.po
  addons/crm/i18n/hr.po
  addons/crm_iap_lead/i18n/he.po
  addons/crm_iap_lead_enrich/i18n/it.po
  addons/crm_iap_lead_website/i18n/de.po
  addons/event/i18n/fr.po
  addons/event/i18n/th.po
  addons/event_crm/i18n/th.po
  addons/event_sale/i18n/th.po
  addons/event_sms/i18n/th.po
  addons/mrp/models/stock_move.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/he.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/ru.po
  odoo/addons/base/i18n/sv.po
  odoo/addons/base/i18n/th.po
Labels: tmp.14.0

#16380 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/purchase_mrp/i18n/purchase_mrp.pot
  addons/purchase_mrp/models/stock_move.py
  addons/stock/report/picking_templates.xml
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/tests/test_translate.py
Labels: 13.0

#16384 Syncing from upstream odoo/odoo (13.0)
  addons/auth_ldap/models/res_company_ldap.py
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/models/mrp_production.py
  addons/purchase/report/purchase_quotation_templates.xml
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/tests/test_warehouse.py
  addons/website_sale/models/crm_team.py
  addons/website_sale/views/sale_report_views.xml
Labels: 13.0

#16385 Syncing from upstream odoo/odoo (14.0)
  addons/auth_ldap/models/res_company_ldap.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_order.py
  addons/sale/tests/test_sale_pricelist.py
  addons/sale_management/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/view_dialogs.js
  addons/web/static/tests/views/view_dialogs_tests.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_sale/models/crm_team.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/res_users.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_qweb_fields.py
Labels: 14.0

#16386 Syncing from upstream odoo/odoo (15.0)
  .gitignore
  addons/auth_ldap/models/res_company_ldap.py
  addons/auth_totp_portal/static/src/js/totp_frontend.js
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/hr_recruitment_survey/models/hr_applicant.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_channel.py
  addons/mail/models/res_partner.py
  addons/mail/static/src/components/attachment_viewer/attachment_viewer.js
  addons/mail/static/src/models/attachment/attachment.js
  addons/mail/static/tests/helpers/mock_models.js
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mail/tests/test_res_partner.py
  addons/mrp/models/stock_move.py
  addons/payment_ogone/data/payment_acquirer_data.xml
  addons/payment_ogone/models/payment_acquirer.py
  addons/sale/models/sale_order.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/tests/test_move.py
  addons/web/static/src/core/hotkeys/hotkey_service.js
  addons/web/static/tests/core/hotkeys/hotkey_service_tests.js
  addons/web/tooling/_husky/.gitignore
  addons/web/tooling/_package.json
  addons/web/tooling/disable.sh
  addons/web/tooling/enable.sh
  addons/web/tooling/hooks/pre-commit
  addons/web/tooling/reload.sh
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_event_track/controllers/event_track.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/product_template.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/res_users.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/views/res_users_views.xml
Labels: 15.0

#16388 Syncing from upstream odoo/odoo (13.0)
  addons/account_facturx/models/account_move.py
  addons/mrp/models/mrp_document.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/stock/models/stock_quant.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/widgets/data_export_tests.js
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
Labels: 13.0

#16389 Syncing from upstream odoo/odoo (14.0)
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_de_sale/i18n/l10n_de_sale.pot
  addons/l10n_de_sale/models/sale.py
  addons/purchase/report/purchase_quotation_templates.xml
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/tests/test_warehouse.py
  addons/website_sale/views/sale_report_views.xml
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_res_users.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_many2many.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/osv/expression.py
Labels: 14.0

#16390 Syncing from upstream odoo/odoo (15.0)
  addons/crm/models/crm_team.py
  addons/crm/tests/common.py
  addons/crm/tests/test_crm_lead_assignment.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ar/demo/account_supplier_invoice_demo.xml
  addons/l10n_ar/demo/account_supplier_refund_demo.xml
  addons/mail/static/src/components/message_list/message_list.js
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/mail/static/src/models/thread_cache/thread_cache.js
  addons/project/models/project.py
  addons/purchase/report/purchase_quotation_templates.xml
  addons/resource/models/res_users.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_warehouse.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/customize.js
  addons/website/static/src/js/menu/new_content.js
  addons/website_sale/views/sale_report_views.xml
Labels: 15.0

#16392 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_jp/data/account_tax_template_data.xml
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/sale_mrp/models/sale_mrp.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  doc/cla/corporate/vauxoo.md
Labels: 13.0

#16393 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/hr/security/hr_security.xml
  addons/l10n_jp/data/account_tax_template_data.xml
  addons/mrp/models/mrp_document.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/survey/controllers/main.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/tests/fields/basic_fields_tests.js
  doc/cla/corporate/vauxoo.md
Labels: 14.0

#16394 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/hr_timesheet/models/project.py
  addons/l10n_ar/demo/account_customer_refund_demo.xml
  addons/l10n_ar/models/account_move.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_de_purchase/models/purchase.py
  addons/l10n_jp/data/account_tax_template_data.xml
  addons/mail/tests/test_mail_channel_partner.py
  addons/mrp/models/mrp_document.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/portal/__manifest__.py
  addons/portal/controllers/portal.py
  addons/portal/i18n/portal.pot
  addons/portal/models/__init__.py
  addons/portal/models/res_config_settings.py
  addons/portal/models/res_users_apikeys_description.py
  addons/portal/static/src/js/portal.js
  addons/portal/static/src/xml/portal_security.xml
  addons/portal/views/portal_templates.xml
  addons/portal/views/res_config_settings_views.xml
  addons/sale_timesheet/models/project.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/webclient/actions/concurrency_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_res_users.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_many2many.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/osv/expression.py
Labels: 15.0

#16396 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account_facturx/models/account_move.py
  addons/auth_ldap/models/res_company_ldap.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_jp/data/account_tax_template_data.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_document.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/purchase/report/purchase_quotation_templates.xml
  addons/purchase_mrp/i18n/purchase_mrp.pot
  addons/purchase_mrp/models/stock_move.py
  addons/sale_mrp/models/sale_mrp.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/stock/models/stock_rule.py
  addons/stock/report/picking_templates.xml
  addons/stock/tests/test_stock_flow.py
  addons/stock/tests/test_warehouse.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/widgets/data_export_tests.js
  addons/website_sale/models/crm_team.py
  addons/website_sale/views/sale_report_views.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/addons/base/tests/test_translate.py
Labels: staging.13.0

#16402 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account_facturx/models/account_move.py
  addons/auth_ldap/models/res_company_ldap.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_jp/data/account_tax_template_data.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_document.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/purchase/report/purchase_quotation_templates.xml
  addons/purchase_mrp/i18n/purchase_mrp.pot
  addons/purchase_mrp/models/stock_move.py
  addons/sale_mrp/models/sale_mrp.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/stock/models/stock_rule.py
  addons/stock/report/picking_templates.xml
  addons/stock/tests/test_stock_flow.py
  addons/stock/tests/test_warehouse.py
  addons/web/static/src/js/fields/basic_fields.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/views/list/list_renderer.js
  addons/web/static/tests/fields/basic_fields_tests.js
  addons/web/static/tests/views/list_tests.js
  addons/web/static/tests/widgets/data_export_tests.js
  addons/website_sale/models/crm_team.py
  addons/website_sale/views/sale_report_views.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/models/ir_translation.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/addons/base/tests/test_translate.py
Labels: tmp.13.0

#16405 Syncing from upstream odoo/odoo (12.0)
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: 12.0

#16406 Syncing from upstream odoo/odoo (13.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/point_of_sale/static/src/js/models.js
Labels: 13.0

#16407 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/coupon/models/coupon.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
Labels: 14.0

#16408 Syncing from upstream odoo/odoo (15.0)
  addons/coupon/models/coupon.py
  addons/hr/security/hr_security.xml
  addons/mrp/models/mrp_production.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/survey/controllers/main.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/views/view_dialogs.js
  addons/web/static/src/legacy/scss/form_view.scss
  addons/web/static/tests/legacy/views/view_dialogs_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/models/product_misc.py
  addons/website_sale/static/tests/tours/website_sale_shop_editor_tour.js
  addons/website_sale/tests/test_customize.py
Labels: 15.0

#16410 Syncing from upstream odoo/odoo (saas-12.3)
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: saas-12.3

#16414 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  addons/payment_stripe_checkout_webhook/controllers/main.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: staging.saas-12.3

#16417 Syncing from upstream odoo/odoo (staging.12.0)
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: staging.12.0

#16418 Syncing from upstream odoo/odoo (staging.13.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/point_of_sale/static/src/js/models.js
Labels: staging.13.0

#16419 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/coupon/models/coupon.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
Labels: staging.14.0

#16422 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: tmp.saas-12.3

#16423 Syncing from upstream odoo/odoo (tmp.saas-15.1)
  addons/coupon/models/coupon.py
  addons/hr/security/hr_security.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_din5008_purchase/models/purchase.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/static/src/components/rtc_video/rtc_video.js
  addons/mail/tests/test_mail_channel_partner.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/payment_ogone/data/payment_acquirer_data.xml
  addons/payment_ogone/models/payment_acquirer.py
  addons/point_of_sale/models/stock_picking.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/survey/controllers/main.py
  addons/web/static/src/legacy/scss/form_view.scss
  odoo/addons/base/tests/test_expression.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_many2many.py
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/osv/expression.py
Labels: tmp.saas-15.1

#16425 Syncing from upstream odoo/odoo (tmp.12.0)
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: tmp.12.0

#16426 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/account/static/src/js/reconciliation/reconciliation_renderer.js
  addons/point_of_sale/static/src/js/models.js
Labels: tmp.13.0

#16427 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/coupon/models/coupon.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
Labels: tmp.14.0

#16428 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/coupon/models/coupon.py
  addons/hr/security/hr_security.xml
  addons/mrp/models/mrp_production.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/survey/controllers/main.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/views/view_dialogs.js
  addons/web/static/src/legacy/scss/form_view.scss
  addons/web/static/tests/legacy/views/view_dialogs_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/models/product_misc.py
  addons/website_sale/static/tests/tours/website_sale_shop_editor_tour.js
  addons/website_sale/tests/test_customize.py
Labels: tmp.15.0

#16429 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/ca.po
  addons/account/i18n/et.po
  addons/account/i18n/hr.po
  addons/account/i18n/it.po
  addons/account/i18n/nb.po
  addons/account/i18n/sv.po
  addons/account_edi/i18n/it.po
  addons/account_edi/i18n/th.po
  addons/account_edi_facturx/i18n/es_MX.po
  addons/account_payment/i18n/lv.po
  addons/auth_oauth/i18n/th.po
  addons/auth_password_policy/i18n/th.po
  addons/auth_signup/i18n/th.po
  addons/auth_signup/i18n/vi.po
  addons/auth_totp/i18n/th.po
  addons/calendar/i18n/ca.po
  addons/calendar/i18n/fr.po
  addons/calendar/i18n/it.po
  addons/crm/i18n/ca.po
  addons/crm/i18n/hr.po
  addons/crm/i18n/sv.po
  addons/crm_iap_lead_enrich/i18n/ar.po
  addons/digest/i18n/et.po
  addons/digest/i18n/hr.po
  addons/event/i18n/ca.po
  addons/event_crm/i18n/es.po
  addons/fetchmail/i18n/et.po
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/hr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nb.po
  odoo/addons/base/i18n/th.po
Labels: 14.0

#16431 Syncing from upstream odoo/odoo (master)
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_sale_project.py
Labels: master

#16432 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_de_sale/i18n/l10n_de_sale.pot
  addons/l10n_de_sale/models/sale.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
Labels: 15.0

#16433 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
Labels: master

#16434 Syncing from upstream odoo/odoo (13.0)
  odoo/addons/base/data/res.country.state.csv
Labels: 13.0

#16435 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/wizard/account_resequence.py
  addons/account_edi_facturx/models/account_edi_format.py
  addons/hr_timesheet/controllers/portal.py
  addons/im_livechat/static/src/legacy/public_livechat.js
  addons/mail/static/src/components/file_uploader/file_uploader.js
  addons/web/controllers/main.py
  addons/web/i18n/web.pot
  addons/web/static/src/js/control_panel/search_bar.js
  addons/web/static/tests/control_panel/search_bar_tests.js
  addons/website_livechat/static/src/legacy/public_livechat.js
  addons/website_slides/controllers/main.py
Labels: 14.0

#16436 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_timesheet/controllers/portal.py
  addons/im_livechat/static/src/legacy/public_livechat.js
  addons/mail/controllers/discuss.py
  addons/mail/models/ir_attachment.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/components/attachment_box/tests/attachment_box_tests.js
  addons/mail/static/src/components/chatter_topbar/tests/chatter_topbar_tests.js
  addons/mail/static/src/models/attachment/attachment.js
  addons/mail/static/src/models/thread/thread.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/tests/test_sync_odoo2microsoft.py
  addons/mrp/models/stock_rule.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_management/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_livechat/static/src/legacy/public_livechat.js
  addons/website_sale/static/src/js/tours/website_sale_shop.js
  addons/website_sale/views/templates.xml
  addons/website_slides/controllers/main.py
  doc/cla/individual/warp10.md
  odoo/tools/cloc.py
  requirements.txt
Labels: 15.0

#16438 Syncing from upstream odoo/odoo (12.0)
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/main.py
Labels: 12.0

#16439 Syncing from upstream odoo/odoo (13.0)
  .tx/config
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/i18n/fetchmail_outlook.pot
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  addons/mrp_account/views/product_views.xml
  addons/stock_account/views/product_views.xml
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: 13.0

#16440 Syncing from upstream odoo/odoo (14.0)
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/sale/models/sale.py
  addons/sale_management/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/sale_mrp/models/sale.py
  odoo/addons/base/data/res.country.state.csv
Labels: 14.0

#16441 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_facturx/models/account_edi_format.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/l10n_de_stock/models/stock.py
  addons/mrp_account/views/analytic_account_views.xml
  addons/mrp_account/views/product_views.xml
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/sale_mrp/models/sale.py
  addons/web/static/src/legacy/js/control_panel/search_bar.js
  addons/web/static/tests/legacy/control_panel/search_bar_tests.js
  doc/cla/individual/wm-cortex.md
  odoo/addons/base/data/res.country.state.csv
  odoo/service/server.py
  requirements.txt
Labels: 15.0

#16443 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mail/models/mail_thread.py
  addons/test_mail/tests/test_discuss.py
  odoo/addons/base/static/src/js/res_config_settings.js
  odoo/addons/base/static/tests/base_settings_tests.js
Labels: 13.0

#16444 Syncing from upstream odoo/odoo (14.0)
  .tx/config
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/i18n/fetchmail_outlook.pot
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_calendar/models/calendar.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_cancel_mo.py
  addons/mrp/views/mrp_workorder_views.xml
  addons/mrp_account/views/product_views.xml
  addons/mrp_landed_costs/models/stock_landed_cost.py
  addons/mrp_landed_costs/tests/test_stock_landed_costs_mrp.py
  addons/mrp_landed_costs/views/stock_landed_cost_views.xml
  addons/sale_timesheet/models/project_overview.py
  addons/website_crm/models/crm_lead.py
  odoo/addons/base/static/src/js/res_config_settings.js
  odoo/addons/base/static/tests/base_settings_tests.js
  odoo/fields.py
Labels: 14.0

#16445 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_payment.py
  addons/google_calendar/models/calendar.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/lunch/static/src/js/lunch_kanban_record.js
  addons/mail/static/src/components/composer_suggestion/composer_suggestion.scss
  addons/mail/static/src/components/composer_suggestion/composer_suggestion.xml
  addons/mrp_landed_costs/models/stock_landed_cost.py
  addons/mrp_landed_costs/tests/test_stock_landed_costs_mrp.py
  addons/mrp_landed_costs/views/stock_landed_cost_views.xml
  addons/pos_restaurant/models/pos_order.py
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/static/src/xml/website.pageProperties.xml
  addons/website_crm/models/crm_lead.py
  odoo/addons/base/static/src/js/res_config_settings.js
  odoo/addons/base/static/tests/base_settings_tests.js
  odoo/fields.py
Labels: 15.0
