Repository brain-tec/odoo, pull requests merged in 2023-02, with the labels that each got.

#18426 Syncing from upstream odoo/odoo (14.0)
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_adyen/i18n/pos_adyen.pot
  addons/pos_adyen/models/pos_payment_method.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/controllers/main.py
  addons/web/controllers/main.py
  addons/web/static/lib/owl/owl.js
  addons/website_forum/views/website_forum.xml
Labels: 14.0

#18427 Syncing from upstream odoo/odoo (15.0)
  addons/event/models/event_mail.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_org_chart/controllers/hr_org_chart.py
  addons/l10n_ke_edi_tremol/i18n/l10n_ke_edi_tremol.pot
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/models/product.py
  addons/l10n_ke_edi_tremol/views/product_view.xml
  addons/l10n_mx/data/account.account.template.csv
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_acquirer.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/models/pos_order.py
  addons/stock/controllers/main.py
  addons/web/controllers/main.py
  addons/web/static/lib/owl/owl.js
  addons/website/models/ir_http.py
  addons/website/tests/test_page.py
  addons/website_forum/views/website_forum.xml
Labels: 15.0

#18428 Syncing from upstream odoo/odoo (16.0)
  .tx/config
  addons/account/wizard/accrued_orders.py
  addons/account_edi/models/account_move.py
  addons/account_edi/models/mail_template.py
  addons/account_payment_invoice_online_payment_patch/i18n/account_payment_invoice_online_payment_patch.pot
  addons/event/models/event_mail.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_org_chart/controllers/hr_org_chart.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_in/__manifest__.py
  addons/l10n_in/demo/account_invoice_demo.xml
  addons/l10n_in/demo/account_payment_demo.xml
  addons/l10n_in/demo/res_partner_demo.xml
  addons/l10n_in/models/account_invoice.py
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_ke_edi_tremol/i18n/l10n_ke_edi_tremol.pot
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/models/product.py
  addons/l10n_ke_edi_tremol/views/product_view.xml
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_provider.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/db.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/pos_hr/static/src/js/LoginScreen.js
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/calendar/helpers.js
  addons/web/static/tests/views/fields/html_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_forum/views/website_forum.xml
  addons/website_mass_mailing/controllers/website_form.py
  addons/website_slides/views/website_slides_templates_homepage.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/res_users.py
Labels: 16.0

#18430 Syncing from upstream odoo/odoo (saas-15.2)
  addons/event/models/event_mail.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_org_chart/controllers/hr_org_chart.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_ke_edi_tremol/i18n/l10n_ke_edi_tremol.pot
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/models/product.py
  addons/l10n_ke_edi_tremol/views/product_view.xml
  addons/l10n_mx/data/account.account.template.csv
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_acquirer.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/static/src/css/restaurant.css
  addons/stock/controllers/main.py
  addons/web/controllers/main.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_forum/views/website_forum.xml
Labels: saas-15.2

#18433 Syncing from upstream odoo/odoo (staging.14.0)
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_adyen/i18n/pos_adyen.pot
  addons/pos_adyen/models/pos_payment_method.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/controllers/main.py
  addons/web/controllers/main.py
  addons/web/static/lib/owl/owl.js
  addons/website_forum/views/website_forum.xml
Labels: staging.14.0

#18437 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_adyen/i18n/pos_adyen.pot
  addons/pos_adyen/models/pos_payment_method.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/controllers/main.py
  addons/web/controllers/main.py
  addons/web/static/lib/owl/owl.js
  addons/website_forum/views/website_forum.xml
Labels: tmp.14.0

#18438 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/event/models/event_mail.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_org_chart/controllers/hr_org_chart.py
  addons/l10n_ke_edi_tremol/i18n/l10n_ke_edi_tremol.pot
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/models/product.py
  addons/l10n_ke_edi_tremol/views/product_view.xml
  addons/l10n_mx/data/account.account.template.csv
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_acquirer.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/models/pos_order.py
  addons/stock/controllers/main.py
  addons/web/controllers/main.py
  addons/web/static/lib/owl/owl.js
  addons/website/models/ir_http.py
  addons/website/tests/test_page.py
  addons/website_forum/views/website_forum.xml
Labels: tmp.15.0

#18440 Syncing from upstream odoo/odoo (14.0)
  addons/bus/models/bus.py
  addons/website/models/website_menu.py
Labels: 14.0

#18441 Syncing from upstream odoo/odoo (15.0)
  addons/purchase_requisition/models/purchase.py
  addons/stock/models/stock_move.py
Labels: 15.0

#18442 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/account_payment_register.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/microsoft_calendar/models/res_users.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_loyalty/models/pos_order.py
  addons/pos_restaurant/models/pos_order.py
  addons/project/models/company.py
  addons/project/tests/__init__.py
  addons/project/tests/test_res_config_settings.py
  addons/spreadsheet/static/src/list/plugins/list_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/pivot/plugins/pivot_core_plugin.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/account_move.py
  addons/survey/static/src/scss/survey_templates_results.scss
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/date_field_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_masonry_block/001.scss
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/http.py
Labels: 16.0

#18444 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase_requisition/models/purchase.py
  addons/stock/models/stock_move.py
  addons/survey/static/src/scss/survey_templates_results.scss
  addons/web/static/lib/owl/owl.js
Labels: saas-15.2

#18447 Syncing from upstream odoo/odoo (staging.14.0)
  addons/bus/models/bus.py
  addons/website/models/website_menu.py
Labels: staging.14.0

#18450 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase_requisition/models/purchase.py
  addons/stock/models/stock_move.py
  addons/survey/static/src/scss/survey_templates_results.scss
  addons/web/static/lib/owl/owl.js
Labels: tmp.saas-15.2

#18451 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/bus/models/bus.py
  addons/website/models/website_menu.py
Labels: tmp.14.0

#18452 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/purchase_requisition/models/purchase.py
  addons/stock/models/stock_move.py
Labels: tmp.15.0

#18454 Syncing from upstream odoo/odoo (13.0)
  addons/website_slides/static/src/js/slides_upload.js
Labels: 13.0

#18455 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ar/views/report_invoice.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/tests/views/calendar_tests.js
  doc/cla/corporate/acsone.md
  doc/cla/individual/paimonchan.md
Labels: 14.0

#18456 Syncing from upstream odoo/odoo (15.0)
  addons/mass_mailing/security/ir.model.access.csv
  addons/mrp/models/stock_move.py
  addons/mrp/models/stock_orderpoint.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_product.py
  addons/web/static/lib/py.js/lib/py.js
  addons/web/static/src/core/py_js/py_tokenizer.js
  addons/web/static/src/search/utils/dates.js
  addons/web/static/tests/core/py_js/py_tokenizer_tests.js
  addons/web/static/tests/search/search_utils_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website_menu.py
  doc/cla/individual/kristjantehu.md
  doc/cla/individual/paimonchan.md
  odoo/addons/base/data/res.country.state.csv
Labels: 15.0

#18458 Syncing from upstream odoo/odoo (master)
  addons/bus/static/src/services/bus_service.js
  addons/bus/static/src/workers/websocket_worker.js
  addons/bus/static/tests/bus_tests.js
  addons/bus/static/tests/helpers/mock_websocket.js
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.xml
  addons/microsoft_calendar/models/res_users.py
  addons/mrp/models/mrp_bom.py
  addons/pos_loyalty/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/calendar/calendar_renderer.scss
  addons/web/static/src/views/fields/boolean_icon/boolean_icon_field.js
  addons/web/static/src/views/fields/boolean_icon/boolean_icon_field.xml
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/fields/boolean_icon_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  doc/cla/individual/mostafabarmshory.md
  odoo/addons/base/models/ir_model.py
  odoo/tools/config.py
Labels: master

#18459 Syncing from upstream odoo/odoo (saas-15.2)
  addons/mass_mailing/security/ir.model.access.csv
  addons/mrp/models/stock_orderpoint.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_product.py
  addons/web/static/lib/py.js/lib/py.js
  addons/web/static/src/core/py_js/py_tokenizer.js
  addons/web/static/tests/core/py_js/py_tokenizer_tests.js
  addons/website/models/ir_http.py
  addons/website/models/website_menu.py
  addons/website/tests/test_page.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
  doc/cla/individual/paimonchan.md
Labels: saas-15.2

#18462 Syncing from upstream odoo/odoo (staging.13.0)
  addons/website_slides/static/src/js/slides_upload.js
Labels: staging.13.0

#18463 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_ar/views/report_invoice.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/tests/views/calendar_tests.js
  doc/cla/corporate/acsone.md
  doc/cla/individual/paimonchan.md
Labels: staging.14.0

#18466 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/mass_mailing/security/ir.model.access.csv
  addons/mrp/models/stock_orderpoint.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_product.py
  addons/web/static/lib/py.js/lib/py.js
  addons/web/static/src/core/py_js/py_tokenizer.js
  addons/web/static/tests/core/py_js/py_tokenizer_tests.js
  addons/website/models/ir_http.py
  addons/website/models/website_menu.py
  addons/website/tests/test_page.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
  doc/cla/individual/paimonchan.md
Labels: tmp.saas-15.2

#18467 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/website_slides/static/src/js/slides_upload.js
Labels: tmp.13.0

#18468 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_ar/views/report_invoice.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/web/static/src/js/views/calendar/calendar_renderer.js
  addons/web/static/tests/views/calendar_tests.js
  doc/cla/corporate/acsone.md
  doc/cla/individual/paimonchan.md
Labels: tmp.14.0

#18469 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/mass_mailing/security/ir.model.access.csv
  addons/mrp/models/stock_move.py
  addons/mrp/models/stock_orderpoint.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_product.py
  addons/web/static/lib/py.js/lib/py.js
  addons/web/static/src/core/py_js/py_tokenizer.js
  addons/web/static/src/search/utils/dates.js
  addons/web/static/tests/core/py_js/py_tokenizer_tests.js
  addons/web/static/tests/search/search_utils_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website_menu.py
  doc/cla/individual/kristjantehu.md
  doc/cla/individual/paimonchan.md
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.15.0

#18471 Syncing from upstream odoo/odoo (14.0)
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  debian/postinst
Labels: 14.0

#18472 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/l10n_in/data/account_tax_group_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_in_edi/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/payment_paypal/controllers/main.py
  addons/payment_paypal/i18n/payment_paypal.pot
  addons/payment_paypal/views/payment_views.xml
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/legacy/js/views/calendar/calendar_renderer.js
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/models/__init__.py
  addons/website/models/ir_ui_view.py
  addons/website/models/mail_thread.py
  addons/website_forum/tests/test_forum.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  debian/postinst
  doc/cla/corporate/acsone.md
Labels: 15.0

#18475 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/models/stock_move.py
  addons/payment_paypal/controllers/main.py
  addons/payment_paypal/i18n/payment_paypal.pot
  addons/payment_paypal/views/payment_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/legacy/js/views/calendar/calendar_renderer.js
  addons/web/static/src/search/utils/dates.js
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web/static/tests/search/search_utils_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/models/__init__.py
  addons/website/models/ir_ui_view.py
  addons/website/models/mail_thread.py
  addons/website_forum/tests/test_forum.py
  debian/postinst
  doc/cla/corporate/acsone.md
  doc/cla/individual/kristjantehu.md
  doc/cla/individual/mehjabin.md
  odoo/addons/base/data/res.country.state.csv
Labels: saas-15.2

#18478 Syncing from upstream odoo/odoo (staging.14.0)
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  debian/postinst
Labels: staging.14.0

#18481 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/mrp/models/stock_move.py
  addons/payment_paypal/controllers/main.py
  addons/payment_paypal/i18n/payment_paypal.pot
  addons/payment_paypal/views/payment_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/legacy/js/views/calendar/calendar_renderer.js
  addons/web/static/src/search/utils/dates.js
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web/static/tests/search/search_utils_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/models/__init__.py
  addons/website/models/ir_ui_view.py
  addons/website/models/mail_thread.py
  addons/website_forum/tests/test_forum.py
  debian/postinst
  doc/cla/corporate/acsone.md
  doc/cla/individual/kristjantehu.md
  doc/cla/individual/mehjabin.md
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.saas-15.2

#18482 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  debian/postinst
Labels: tmp.14.0

#18483 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/l10n_in/data/account_tax_group_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_in_edi/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/payment_paypal/controllers/main.py
  addons/payment_paypal/i18n/payment_paypal.pot
  addons/payment_paypal/views/payment_views.xml
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/legacy/js/views/calendar/calendar_renderer.js
  addons/web/static/tests/legacy/views/calendar_tests.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/models/__init__.py
  addons/website/models/ir_ui_view.py
  addons/website/models/mail_thread.py
  addons/website_forum/tests/test_forum.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  debian/postinst
  doc/cla/corporate/acsone.md
Labels: tmp.15.0

#18489 Syncing from upstream odoo/odoo (saas-15.2)
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: saas-15.2

#18494 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: tmp.saas-15.2

#18495 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/auth_signup/controllers/main.py
  addons/auth_signup/tests/__init__.py
  addons/auth_signup/tests/test_auth_signup.py
Labels: tmp.15.0

#18497 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/es.po
  addons/account/i18n/it.po
  addons/account/i18n/nl.po
  addons/coupon/i18n/es.po
  addons/crm/i18n/nl.po
  addons/delivery_stock_picking_batch/i18n/es.po
  addons/event_sale/i18n/nl.po
  addons/google_recaptcha/i18n/it.po
  addons/hr/i18n/nl.po
  addons/hr_holidays/i18n/nl.po
  addons/hr_presence/i18n/it.po
  addons/hr_recruitment/i18n/nl.po
  addons/hr_timesheet/i18n/it.po
  addons/l10n_multilang/i18n/it.po
  addons/lunch/i18n/it.po
  addons/mail/i18n/es.po
  addons/mail/i18n/it.po
  addons/mail/i18n/nl.po
  addons/mail/i18n/uk.po
  addons/mrp/i18n/nl.po
  addons/payment_stripe/i18n/fr.po
  addons/point_of_sale/i18n/it.po
  addons/point_of_sale/i18n/nl.po
  addons/point_of_sale/i18n/zh_CN.po
  addons/portal/i18n/es.po
  addons/portal_rating/i18n/nl.po
  addons/pos_restaurant/i18n/it.po
  addons/pos_restaurant/i18n/nl.po
  addons/pos_sale/i18n/it.po
  addons/project/i18n/nl.po
  addons/purchase_stock/i18n/it.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/nl.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/survey/i18n/nl.po
  addons/utm/i18n/nl.po
  addons/web/i18n/nl.po
  addons/web_editor/i18n/it.po
  addons/web_editor/i18n/nl.po
  addons/website/i18n/es.po
  addons/website/i18n/nl.po
  addons/website/i18n/uk.po
  addons/website_blog/i18n/nl.po
  addons/website_event/i18n/fr.po
  addons/website_event/i18n/it.po
  addons/website_event/i18n/nl.po
  addons/website_forum/i18n/nl.po
  addons/website_profile/i18n/nl.po
  addons/website_sale/i18n/nl.po
  addons/website_sale_product_configurator/i18n/nl.po
  addons/website_slides/i18n/nl.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/it.po
Labels: saas-15.2

#18499 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/company.py
  addons/repair/models/repair.py
  addons/sale/models/sale.py
Labels: 14.0

#18500 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/company.py
  addons/account/wizard/accrued_orders.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/pos_adyen/i18n/pos_adyen.pot
  addons/pos_adyen/models/pos_payment_method.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
Labels: 15.0

#18501 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/company.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_invoice_taxes.py
  addons/account/wizard/accrued_orders.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/models/composer_view.js
  addons/payment_paypal/controllers/main.py
  addons/payment_paypal/i18n/payment_paypal.pot
  addons/payment_paypal/views/payment_provider_views.xml
  addons/pos_restaurant/static/src/scss/restaurant.scss
  addons/pos_stripe/models/pos_payment_method.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/view_dialogs/export_data_dialog.scss
  addons/web/static/src/views/view_dialogs/export_data_dialog.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/services/website_service.js
Labels: 16.0

#18503 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/company.py
  addons/account/wizard/accrued_orders.py
  addons/auth_signup/controllers/main.py
  addons/auth_signup/tests/__init__.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/pos_adyen/i18n/pos_adyen.pot
  addons/pos_adyen/models/pos_payment_method.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
Labels: saas-15.2

#18514 [t133771] Allow deletion of pos.categories with open sessions
  addons/point_of_sale/models/pos_category.py
Labels: feature, 15.0.project_sv_559

#18515 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/account_edi_document.py
  addons/calendar_sms/views/calendar_views.xml
  addons/l10n_pe/data/l10n_pe_chart_post_data.xml
  addons/website/static/src/scss/bootstrap_overridden.scss
Labels: 14.0

#18516 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/bus/models/bus.py
  addons/delivery/models/stock_picking.py
  addons/mass_mailing/static/src/js/mass_mailing_snippets.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/ir_asset_views.xml
Labels: 15.0

#18519 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/mass_mailing/static/src/js/mass_mailing_snippets.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: saas-15.2

#18522 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi/models/account_edi_document.py
  addons/calendar_sms/views/calendar_views.xml
  addons/l10n_pe/data/l10n_pe_chart_post_data.xml
  addons/website/static/src/scss/bootstrap_overridden.scss
Labels: staging.14.0

#18525 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/mass_mailing/static/src/js/mass_mailing_snippets.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.saas-15.2

#18526 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi/models/account_edi_document.py
  addons/calendar_sms/views/calendar_views.xml
  addons/l10n_pe/data/l10n_pe_chart_post_data.xml
  addons/website/static/src/scss/bootstrap_overridden.scss
Labels: tmp.14.0

#18527 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/bus/models/bus.py
  addons/delivery/models/stock_picking.py
  addons/mass_mailing/static/src/js/mass_mailing_snippets.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/ir_asset_views.xml
Labels: tmp.15.0

#18513 [IMP] microsoft_outlook: update refresh token when getting a new access token
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
Labels: 13.0.project_pm_597

#18529 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/tests/test_tax_report.py
Labels: 14.0

#18530 Syncing from upstream odoo/odoo (15.0)
  addons/delivery/tests/test_packing_delivery.py
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_stock_flow.py
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/scss/bootstrap_overridden.scss
Labels: 15.0

#18531 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/data/hr_holidays_data.xml
  addons/hr_holidays/data/hr_holidays_demo.xml
  addons/hr_holidays/tests/test_access_rights.py
  addons/hr_holidays_attendance/data/hr_holidays_attendance_data.xml
  addons/hr_work_entry_contract/data/hr_work_entry_data.xml
  addons/hr_work_entry_holidays/__manifest__.py
  addons/hr_work_entry_holidays/data/hr_payroll_holidays_demo.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_restaurant/models/pos_order.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/resource/data/resource_data.xml
  addons/resource/models/resource.py
  addons/spreadsheet/static/src/global_filters/components/year_picker.js
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/kanban/kanban_renderer.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/settings_form_view/widgets/res_config_invite_users.xml
  addons/web/static/tests/core/datepicker_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/tests/test_login.py
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/static/src/scss/website.scss
  addons/website/views/ir_asset_views.xml
  addons/website_slides/static/src/scss/website_slides.scss
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/http.py
  odoo/models.py
  odoo/modules/loading.py
  odoo/modules/registry.py
  setup/win32/setup.nsi
Labels: 16.0

#18536 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/tests/test_tax_report.py
Labels: staging.14.0

#18539 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/delivery/models/stock_picking.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/point_of_sale/models/pos_session.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/views/ir_asset_views.xml
Labels: tmp.saas-15.2

#18540 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/tests/test_tax_report.py
Labels: tmp.14.0

#18541 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/delivery/tests/test_packing_delivery.py
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_stock_flow.py
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/scss/bootstrap_overridden.scss
Labels: tmp.15.0

#18543 Syncing from upstream odoo/odoo (14.0)
  .tx/config
  addons/google_calendar/models/google_sync.py
  addons/google_gmail/controllers/main.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/l10n_it_edi/models/res_company.py
  addons/purchase/views/portal_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/transifex/models/ir_translation.py
  addons/web/static/src/scss/form_view.scss
Labels: 14.0

#18544 Syncing from upstream odoo/odoo (15.0)
  .tx/config
  addons/account/i18n/account.pot
  addons/account/models/ir_actions_report.py
  addons/google_gmail/controllers/main.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_stock_forecasted.py
  addons/stock_account/models/product.py
  addons/transifex/models/ir_translation.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: 15.0

#18547 Syncing from upstream odoo/odoo (saas-15.2)
  .tx/config
  addons/delivery/tests/test_packing_delivery.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_account/models/product.py
  addons/transifex/models/ir_translation.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: saas-15.2

#18550 Syncing from upstream odoo/odoo (staging.14.0)
  .tx/config
  addons/google_calendar/models/google_sync.py
  addons/google_gmail/controllers/main.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/l10n_it_edi/models/res_company.py
  addons/purchase/views/portal_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/transifex/models/ir_translation.py
  addons/web/static/src/scss/form_view.scss
Labels: staging.14.0

#18553 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  .tx/config
  addons/delivery/tests/test_packing_delivery.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_account/models/product.py
  addons/transifex/models/ir_translation.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-15.2

#18554 Syncing from upstream odoo/odoo (tmp.14.0)
  .tx/config
  addons/google_calendar/models/google_sync.py
  addons/google_gmail/controllers/main.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/l10n_it_edi/models/res_company.py
  addons/purchase/views/portal_templates.xml
  addons/sale/views/sale_portal_templates.xml
  addons/transifex/models/ir_translation.py
  addons/web/static/src/scss/form_view.scss
Labels: tmp.14.0

#18555 Syncing from upstream odoo/odoo (tmp.15.0)
  .tx/config
  addons/account/i18n/account.pot
  addons/account/models/ir_actions_report.py
  addons/google_gmail/controllers/main.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_stock_forecasted.py
  addons/stock_account/models/product.py
  addons/transifex/models/ir_translation.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: tmp.15.0

#18557 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/mrp/models/stock_rule.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/survey/static/src/js/fields_section_one2many.js
  addons/survey/static/src/js/survey_form.js
  addons/survey/static/tests/tours/survey_chained_conditional_questions.js
  addons/survey/tests/test_survey_ui_feedback.py
  addons/survey/views/assets.xml
Labels: 14.0

#18558 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/tests/test_tax_report.py
  addons/l10n_it_edi/models/res_company.py
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/mrp/models/stock_move.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/survey/static/src/js/fields_section_one2many.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: 15.0

#18561 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/models/ir_actions_report.py
  addons/account/tests/test_tax_report.py
  addons/bus/models/bus.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_it_edi/models/res_company.py
  addons/mrp/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_stock_forecasted.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
Labels: saas-15.2

#18564 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/mrp/models/stock_rule.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/survey/static/src/js/fields_section_one2many.js
  addons/survey/static/src/js/survey_form.js
  addons/survey/static/tests/tours/survey_chained_conditional_questions.js
  addons/survey/tests/test_survey_ui_feedback.py
  addons/survey/views/assets.xml
Labels: staging.14.0

#18567 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/models/ir_actions_report.py
  addons/account/tests/test_tax_report.py
  addons/bus/models/bus.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_it_edi/models/res_company.py
  addons/mrp/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/stock/models/stock_move.py
  addons/stock/report/report_stock_forecasted.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
Labels: tmp.saas-15.2

#18568 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/mrp/models/stock_rule.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/survey/static/src/js/fields_section_one2many.js
  addons/survey/static/src/js/survey_form.js
  addons/survey/static/tests/tours/survey_chained_conditional_questions.js
  addons/survey/tests/test_survey_ui_feedback.py
  addons/survey/views/assets.xml
Labels: tmp.14.0

#18569 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_tax_report.py
  addons/account/tests/test_tax_report.py
  addons/l10n_it_edi/models/res_company.py
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/mrp/models/stock_move.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/survey/static/src/js/fields_section_one2many.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: tmp.15.0

#18571 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/ir_actions_report.py
  addons/account/tests/test_account_move_entry.py
  addons/website/views/website_pages_views.xml
Labels: master

#18573 Syncing from upstream odoo/odoo (master)
  addons/stock/controllers/main.py
  addons/web/controllers/report.py
  odoo/netsvc.py
Labels: master

#18576 [bt#21829] Eingehender Mailserver, Refresh Token
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
Labels: 11.0.project_qt_291

#18591 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/l10n_de/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/project/models/project.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/controllers/main.py
  addons/website/models/website.py
Labels: 14.0

#18592 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_de/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: 15.0

#18593 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_reconcile.py
  addons/hr/models/hr_employee.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/mass_mailing/views/snippets_themes.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/purchase/views/portal_templates.xml
  addons/sale/models/sale_order_line.py
  addons/sale/static/src/js/product_discount_field.js
  addons/sale/views/sale_order_views.xml
  addons/sale/views/sale_portal_templates.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_anglo_saxon_valuation.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/survey/static/src/js/survey_form.js
  addons/survey/static/tests/tours/survey_chained_conditional_questions.js
  addons/survey/tests/test_survey_ui_feedback.py
  addons/web/static/src/views/kanban/kanban_controller.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website.py
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_livechat/views/website_livechat.xml
  addons/website_profile/views/website_profile.xml
  addons/website_sale/static/tests/tours/website_sale_shop_editor_tour.js
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
  addons/website_sale_picking/models/delivery_carrier.py
  doc/cla/individual/danibaumann.md
  odoo/addons/base/data/res.country.state.csv
  odoo/addons/base/views/res_partner_views.xml
  setup/win32/setup.nsi
Labels: 16.0

#18595 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/purchase/views/portal_templates.xml
  addons/sale/models/sale_order_line.py
  addons/sale/views/sale_portal_templates.xml
  addons/survey/static/src/js/survey_form.js
  addons/survey/static/tests/tours/survey_chained_conditional_questions.js
  addons/survey/tests/test_survey_ui_feedback.py
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: saas-15.2

#18598 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/l10n_de/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/project/models/project.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/controllers/main.py
  addons/website/models/website.py
Labels: staging.14.0

#18601 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/purchase/views/portal_templates.xml
  addons/sale/models/sale_order_line.py
  addons/sale/views/sale_portal_templates.xml
  addons/survey/static/src/js/survey_form.js
  addons/survey/static/tests/tours/survey_chained_conditional_questions.js
  addons/survey/tests/test_survey_ui_feedback.py
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: tmp.saas-15.2

#18602 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/l10n_de/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/project/models/project.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/controllers/main.py
  addons/website/models/website.py
Labels: tmp.14.0

#18603 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_de/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers.py
  addons/phone_validation/tools/phone_validation.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/website/controllers/main.py
  addons/website/models/website.py
  addons/website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: tmp.15.0

#18605 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
Labels: 14.0

#18606 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/chart_template.py
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/models/stock_rule.py
  addons/payment_authorize/models/authorize_request.py
  addons/pos_restaurant/data/pos_restaurant_demo.xml
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
Labels: 15.0

#18607 Syncing from upstream odoo/odoo (16.0)
  addons/http_routing/models/ir_http.py
  addons/l10n_din5008/models/account_move.py
  addons/mass_mailing/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/utm/models/ir_http.py
  addons/web/controllers/binary.py
  addons/web/controllers/database.py
  addons/web/controllers/report.py
  addons/web/static/src/views/fields/copy_clipboard/copy_button.js
  addons/web/static/src/views/kanban/kanban_renderer.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/models/sale_order.py
  addons/website_slides/controllers/main.py
  odoo/addons/base/controllers/rpc.py
  odoo/http.py
  odoo/netsvc.py
  odoo/sql_db.py
Labels: 16.0

#18609 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_tax.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/data/pos_restaurant_demo.xml
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
Labels: saas-15.2

#18612 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
Labels: staging.14.0

#18615 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_tax.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/data/pos_restaurant_demo.xml
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
Labels: tmp.saas-15.2

#18616 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
Labels: tmp.14.0

#18617 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/chart_template.py
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/models/stock_rule.py
  addons/payment_authorize/models/authorize_request.py
  addons/pos_restaurant/data/pos_restaurant_demo.xml
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
Labels: tmp.15.0

#18620 Syncing from upstream odoo/odoo (13.0)
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
Labels: 13.0

#18621 Syncing from upstream odoo/odoo (14.0)
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: 14.0

#18622 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/company.py
  addons/hr_attendance/report/hr_attendance_report_views.xml
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: 15.0

#18625 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/hr_attendance/report/hr_attendance_report_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: saas-15.2

#18628 Syncing from upstream odoo/odoo (staging.13.0)
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
Labels: staging.13.0

#18629 Syncing from upstream odoo/odoo (staging.14.0)
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: staging.14.0

#18632 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/hr_attendance/report/hr_attendance_report_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: tmp.saas-15.2

#18633 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
Labels: tmp.13.0

#18634 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: tmp.14.0

#18635 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/models/company.py
  addons/hr_attendance/report/hr_attendance_report_views.xml
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/resource/i18n/resource.pot
  addons/resource/models/resource.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: tmp.15.0

#18644 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_address_city/models/res_partner.py
  addons/delivery/models/stock_picking.py
  addons/google_account/models/google_service.py
  addons/google_calendar/controllers/main.py
  addons/mail/static/src/components/chatter/chatter_suggested_recipient_tests.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mrp_subcontracting/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/website/static/src/snippets/s_table_of_content/options.js
Labels: staging.14.0

#18647 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/delivery/models/stock_picking.py
  addons/google_account/models/google_service.py
  addons/google_calendar/controllers/main.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/mrp/models/stock_rule.py
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_table_of_content/options.js
Labels: tmp.saas-15.2

#18648 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_address_city/models/res_partner.py
  addons/delivery/models/stock_picking.py
  addons/google_account/models/google_service.py
  addons/google_calendar/controllers/main.py
  addons/mail/static/src/components/chatter/chatter_suggested_recipient_tests.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mrp_subcontracting/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/website/static/src/snippets/s_table_of_content/options.js
Labels: tmp.14.0

#18649 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/delivery/models/stock_picking.py
  addons/google_account/models/google_service.py
  addons/google_calendar/controllers/main.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/payment/models/res_company.py
  addons/payment/wizards/payment_acquirer_onboarding_templates.xml
  addons/payment/wizards/payment_acquirer_onboarding_wizard.py
  addons/payment_paypal/data/payment_paypal_email_data.xml
  addons/payment_paypal/models/payment_acquirer.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/views/payment_views.xml
  addons/payment_payulatam/models/payment_acquirer.py
  addons/stock/models/stock_rule.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: tmp.15.0

#18651 Syncing from upstream odoo/odoo (15.0)
  addons/project/models/project.py
Labels: 15.0

#18652 Syncing from upstream odoo/odoo (master)
  addons/website/static/src/snippets/s_table_of_content/options.js
Labels: master

#18148 [bt#19569][ADD] fetchmail_outlook, microsoft_outlook: add OAuth authentication
  addons/fetchmail/models/fetchmail.py
  addons/fetchmail_gmail/__init__.py
  addons/fetchmail_gmail/__manifest__.py
  addons/fetchmail_gmail/models/__init__.py
  addons/fetchmail_gmail/models/fetchmail_server.py
  addons/fetchmail_gmail/views/fetchmail_server_views.xml
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/google_account/models/google_service.py
  addons/google_gmail/__init__.py
  addons/google_gmail/__manifest__.py
  addons/google_gmail/models/__init__.py
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/google_gmail/models/res_config_settings.py
  addons/google_gmail/views/ir_mail_server_views.xml
  addons/google_gmail/views/res_config_settings_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
  odoo/addons/base/models/ir_mail_server.py
Labels: 12.0.project_st_215

#18619 [bt#21511][CR] Reactivate Attachment Delete-Button
  addons/mail/static/src/xml/thread.xml
Labels: 12.0.project_st_215

#18658 Syncing from upstream odoo/odoo (14.0)
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/pos_restaurant_adyen/__manifest__.py
  addons/web/static/src/js/fields/basic_fields.js
Labels: 14.0

#18659 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/pos_restaurant_adyen/__manifest__.py
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web_editor/static/src/scss/web_editor.backend.scss
  addons/website/i18n/website.pot
  addons/website/models/website.py
Labels: 15.0

#18662 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/payment/models/res_company.py
  addons/payment/wizards/payment_acquirer_onboarding_templates.xml
  addons/payment/wizards/payment_acquirer_onboarding_wizard.py
  addons/payment_paypal/data/payment_paypal_email_data.xml
  addons/payment_paypal/models/payment_acquirer.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/views/payment_views.xml
  addons/payment_payulatam/models/payment_acquirer.py
  addons/project/models/project.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/controllers/main.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.backend.scss
  addons/website/i18n/website.pot
  addons/website/models/website.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: saas-15.2

#18670 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/account/tests/__init__.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/pos_restaurant_adyen/__manifest__.py
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web_editor/static/src/scss/web_editor.backend.scss
  addons/website/i18n/website.pot
  addons/website/models/website.py
Labels: tmp.15.0

#18672 Syncing from upstream odoo/odoo (14.0)
  addons/base_automation/models/base_automation.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tools/remove_signature.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/product/models/product_template.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
Labels: 14.0

#18673 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_reconcile_model.py
  addons/base_address_city/models/res_partner.py
  addons/base_vat/models/res_partner.py
  addons/hr/models/hr_employee.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_dropshipping/models/purchase.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/product/models/product_template.py
  addons/sale/static/src/js/variant_mixin.js
  addons/sale_management/static/src/js/sale_management.js
  addons/sale_mrp/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/website/static/src/snippets/s_table_of_content/options.js
Labels: 15.0

#18675 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale_order.py
  addons/sale/static/src/js/variant_mixin.js
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/core/dropdown/dropdown.scss
Labels: saas-15.2

#18680 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_automation/models/base_automation.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tools/remove_signature.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/product/models/product_template.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
Labels: staging.14.0

#18684 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/sale/models/sale_order.py
  addons/sale/static/src/js/variant_mixin.js
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/core/dropdown/dropdown.scss
Labels: tmp.saas-15.2

#18686 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_automation/models/base_automation.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tools/remove_signature.py
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/product/models/product_template.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
Labels: tmp.14.0

#18687 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_reconcile_model.py
  addons/base_address_city/models/res_partner.py
  addons/base_vat/models/res_partner.py
  addons/hr/models/hr_employee.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_dropshipping/models/purchase.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/product/models/product_template.py
  addons/sale/static/src/js/variant_mixin.js
  addons/sale_management/static/src/js/sale_management.js
  addons/sale_mrp/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/website/static/src/snippets/s_table_of_content/options.js
Labels: tmp.15.0

#18689 Syncing from upstream odoo/odoo (14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/website/models/assets.py
  odoo/sql_db.py
Labels: 14.0

#18690 Syncing from upstream odoo/odoo (15.0)
  addons/base_automation/models/base_automation.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_tw/data/account.account.template.csv
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
Labels: 15.0

#18692 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_automation/models/base_automation.py
  addons/hr/models/hr_employee.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale_mrp/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
Labels: saas-15.2

#18693 Syncing from upstream odoo/odoo (saas-16.1)
  addons/base_automation/models/base_automation.py
  addons/delivery/views/report_deliveryslip.xml
  addons/hr/models/hr_employee.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_kz/data/account_tax_template_data.xml
  addons/l10n_kz/data/tax_report.xml
  addons/l10n_kz/i18n/l10n_kz.pot
  addons/l10n_kz/i18n/ru.po
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_rs/static/description/icon.png
  addons/l10n_rs/static/description/icon.svg
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/models/messaging_notification_handler.js
  addons/mail/static/src/models/thread.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/static/tests/helpers/mock_server/models/mail_thread.js
  addons/mail/static/tests/helpers/test_utils.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mail/static/tests/qunit_suite_tests/m2x_avatar_user_tests.js
  addons/mrp/static/src/scss/mrp_workorder_kanban.scss
  addons/project/views/project_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/static/src/accounting_datasource.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/stock_rule.py
  addons/web/controllers/binary.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/legacy/legacy_load_views.js
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/properties/property_value.xml
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web/static/tests/core/tooltip/tooltip_service_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/views/snippets/s_image_gallery.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/minimal.pdf
  odoo/addons/base/tests/test_misc.py
  odoo/netsvc.py
  odoo/tools/pdf.py
Labels: saas-16.1

#18696 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/base_automation/models/base_automation.py
  addons/delivery/views/report_deliveryslip.xml
  addons/hr/models/hr_employee.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_kz/data/account_tax_template_data.xml
  addons/l10n_kz/data/tax_report.xml
  addons/l10n_kz/i18n/l10n_kz.pot
  addons/l10n_kz/i18n/ru.po
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_rs/static/description/icon.png
  addons/l10n_rs/static/description/icon.svg
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/models/messaging_notification_handler.js
  addons/mail/static/src/models/thread.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/static/tests/helpers/mock_server/models/mail_thread.js
  addons/mail/static/tests/helpers/test_utils.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mail/static/tests/qunit_suite_tests/m2x_avatar_user_tests.js
  addons/mrp/static/src/scss/mrp_workorder_kanban.scss
  addons/project/views/project_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/static/src/accounting_datasource.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/stock_rule.py
  addons/web/controllers/binary.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/legacy/legacy_load_views.js
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/properties/property_value.xml
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web/static/tests/core/tooltip/tooltip_service_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/views/snippets/s_image_gallery.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/minimal.pdf
  odoo/addons/base/tests/test_misc.py
  odoo/netsvc.py
  odoo/tools/pdf.py
Labels: staging.saas-16.1

#18697 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/website/models/assets.py
  odoo/sql_db.py
Labels: staging.14.0

#18701 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_automation/models/base_automation.py
  addons/hr/models/hr_employee.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale_mrp/models/sale.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
Labels: tmp.saas-15.2

#18702 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/base_automation/models/base_automation.py
  addons/delivery/views/report_deliveryslip.xml
  addons/hr/models/hr_employee.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_kz/data/account_tax_template_data.xml
  addons/l10n_kz/data/tax_report.xml
  addons/l10n_kz/i18n/l10n_kz.pot
  addons/l10n_kz/i18n/ru.po
  addons/l10n_no/__manifest__.py
  addons/l10n_no/data/account_tax_data.xml
  addons/l10n_no/data/account_tax_report_data.xml
  addons/l10n_no/i18n/l10n_no.pot
  addons/l10n_no/i18n/nb_NO.po
  addons/l10n_no/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_rs/static/description/icon.png
  addons/l10n_rs/static/description/icon.svg
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/models/messaging_notification_handler.js
  addons/mail/static/src/models/thread.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/static/tests/helpers/mock_server/models/mail_thread.js
  addons/mail/static/tests/helpers/test_utils.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mail/static/tests/qunit_suite_tests/m2x_avatar_user_tests.js
  addons/mrp/static/src/scss/mrp_workorder_kanban.scss
  addons/project/views/project_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/static/src/accounting_datasource.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/stock_rule.py
  addons/web/controllers/binary.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/legacy/legacy_load_views.js
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/properties/property_value.xml
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web/static/tests/core/tooltip/tooltip_service_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/views/snippets/s_image_gallery.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/minimal.pdf
  odoo/addons/base/tests/test_misc.py
  odoo/netsvc.py
  odoo/tools/pdf.py
Labels: tmp.saas-16.1

#18703 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/website/models/assets.py
  odoo/sql_db.py
Labels: tmp.14.0

#18704 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_automation/models/base_automation.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_tw/data/account.account.template.csv
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
Labels: tmp.15.0

#18706 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_it_edi/i18n/it.po
  addons/snailmail/wizard/snailmail_letter_format_error.py
Labels: 14.0

#18707 Syncing from upstream odoo/odoo (15.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/event_booth_sale/models/__init__.py
  addons/event_booth_sale/models/sale_order_template_option.py
  addons/event_sale/models/__init__.py
  addons/event_sale/models/sale_order_template_option.py
  addons/hr_holidays/models/hr_leave.py
  addons/mail/static/src/components/chatter/tests/chatter_suggested_recipient_tests.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mrp_account/models/mrp_production.py
  addons/product/models/product_template.py
  addons/website/static/src/js/menu/edit.js
  odoo/sql_db.py
Labels: 15.0

#18709 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_reconcile_model.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_tw/data/account.account.template.csv
  addons/product/models/product_template.py
  addons/sale_management/static/src/js/sale_management.js
Labels: saas-15.2

#18710 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/tests/common.py
  addons/account/views/account_payment_term_views.xml
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/i18n/hr.pot
  addons/hr/models/res_users.py
  addons/hr/static/src/components/department_chart/department_chart.xml
  addons/hr_skills/__init__.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tools/remove_signature.py
  addons/l10n_tw/data/account.account.template.csv
  addons/mrp/__manifest__.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/static/src/scss/mrp_fields.scss
  addons/mrp/static/src/widgets/mrp_consumed.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.scss
  addons/mrp/static/tests/tours/mrp_manual_consumption.js
  addons/mrp/tests/__init__.py
  addons/mrp/tests/common_consume_tracked_component.py
  addons/mrp/tests/test_manual_consumption.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_traceability.py
  addons/mrp/views/mrp_bom_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_consumption_warning_views.xml
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_template.py
  addons/project_hr_expense/__init__.py
  addons/project_sale_expense/__init__.py
  addons/sale/models/sale_order.py
  addons/sale/report/sale_report.py
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_report.py
  addons/sale_expense_margin/__init__.py
  addons/sale_margin/report/sale_report.py
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/survey/static/src/question_page/question_page_list_renderer.js
  addons/survey/static/tests/components/question_page_list_renderer_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/data/res_country_data.xml
  odoo/models.py
Labels: saas-16.1

#18713 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/tests/common.py
  addons/account/views/account_payment_term_views.xml
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/i18n/hr.pot
  addons/hr/models/res_users.py
  addons/hr/static/src/components/department_chart/department_chart.xml
  addons/hr_skills/__init__.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tools/remove_signature.py
  addons/l10n_tw/data/account.account.template.csv
  addons/mrp/__manifest__.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/static/src/scss/mrp_fields.scss
  addons/mrp/static/src/widgets/mrp_consumed.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.scss
  addons/mrp/static/tests/tours/mrp_manual_consumption.js
  addons/mrp/tests/__init__.py
  addons/mrp/tests/common_consume_tracked_component.py
  addons/mrp/tests/test_manual_consumption.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_traceability.py
  addons/mrp/views/mrp_bom_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_consumption_warning_views.xml
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_template.py
  addons/project_hr_expense/__init__.py
  addons/project_sale_expense/__init__.py
  addons/sale/models/sale_order.py
  addons/sale/report/sale_report.py
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_report.py
  addons/sale_expense_margin/__init__.py
  addons/sale_margin/report/sale_report.py
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/survey/static/src/question_page/question_page_list_renderer.js
  addons/survey/static/tests/components/question_page_list_renderer_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/data/res_country_data.xml
  odoo/models.py
Labels: staging.saas-16.1

#18714 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_it_edi/i18n/it.po
  addons/snailmail/wizard/snailmail_letter_format_error.py
Labels: staging.14.0

#18718 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_reconcile_model.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_tw/data/account.account.template.csv
  addons/product/models/product_template.py
  addons/sale_management/static/src/js/sale_management.js
Labels: tmp.saas-15.2

#18719 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/tests/common.py
  addons/account/views/account_payment_term_views.xml
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/i18n/hr.pot
  addons/hr/models/res_users.py
  addons/hr/static/src/components/department_chart/department_chart.xml
  addons/hr_skills/__init__.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tools/remove_signature.py
  addons/l10n_tw/data/account.account.template.csv
  addons/mrp/__manifest__.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/static/src/scss/mrp_fields.scss
  addons/mrp/static/src/widgets/mrp_consumed.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.scss
  addons/mrp/static/tests/tours/mrp_manual_consumption.js
  addons/mrp/tests/__init__.py
  addons/mrp/tests/common_consume_tracked_component.py
  addons/mrp/tests/test_manual_consumption.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_traceability.py
  addons/mrp/views/mrp_bom_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp/wizard/mrp_consumption_warning_views.xml
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_sale/report/sale_report.py
  addons/product/models/product_template.py
  addons/project_hr_expense/__init__.py
  addons/project_sale_expense/__init__.py
  addons/sale/models/sale_order.py
  addons/sale/report/sale_report.py
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_report.py
  addons/sale_expense_margin/__init__.py
  addons/sale_margin/report/sale_report.py
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/survey/static/src/question_page/question_page_list_renderer.js
  addons/survey/static/tests/components/question_page_list_renderer_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/data/res_country_data.xml
  odoo/models.py
Labels: tmp.saas-16.1

#18720 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_it_edi/i18n/it.po
  addons/snailmail/wizard/snailmail_letter_format_error.py
Labels: tmp.14.0

#18721 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/event_booth_sale/models/__init__.py
  addons/event_booth_sale/models/sale_order_template_option.py
  addons/event_sale/models/__init__.py
  addons/event_sale/models/sale_order_template_option.py
  addons/hr_holidays/models/hr_leave.py
  addons/mail/static/src/components/chatter/tests/chatter_suggested_recipient_tests.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/mrp_account/models/mrp_production.py
  addons/product/models/product_template.py
  addons/website/static/src/js/menu/edit.js
  odoo/sql_db.py
Labels: tmp.15.0

#18723 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mrp/models/mrp_unbuild.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/stock/models/stock_picking.py
  addons/transifex/models/ir_translation.py
  odoo/addons/base/models/res_partner.py
Labels: 14.0

#18724 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/transifex/models/ir_translation.py
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: 15.0

#18726 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/static/src/components/chatter/tests/chatter_suggested_recipient_tests.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/transifex/models/ir_translation.py
  addons/website/static/src/js/menu/edit.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: saas-15.2

#18727 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_in/data/account_tax_group_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_in_edi/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/l10n_it_edi/i18n/it.po
  addons/mrp/models/mrp_workorder.py
  addons/pos_loyalty/static/src/js/ControlButtons/PromoCodeButton.js
  addons/project_purchase/models/project.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/stock/models/product.py
  addons/transifex/models/transifex_translation.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/snippet_table_of_content.js
  addons/website_sale/static/src/js/components/wysiwyg_adapter/wysiwyg_adapter.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: saas-16.1

#18730 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_in/data/account_tax_group_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_in_edi/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/l10n_it_edi/i18n/it.po
  addons/mrp/models/mrp_workorder.py
  addons/pos_loyalty/static/src/js/ControlButtons/PromoCodeButton.js
  addons/project_purchase/models/project.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/stock/models/product.py
  addons/transifex/models/transifex_translation.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/snippet_table_of_content.js
  addons/website_sale/static/src/js/components/wysiwyg_adapter/wysiwyg_adapter.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: staging.saas-16.1

#18731 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mrp/models/mrp_unbuild.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/stock/models/stock_picking.py
  addons/transifex/models/ir_translation.py
  odoo/addons/base/models/res_partner.py
Labels: staging.14.0

#18735 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/static/src/components/chatter/tests/chatter_suggested_recipient_tests.js
  addons/mail/static/src/components/composer_suggested_recipient/composer_suggested_recipient.js
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/transifex/models/ir_translation.py
  addons/website/static/src/js/menu/edit.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: tmp.saas-15.2

#18736 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_in/data/account_tax_group_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_in_edi/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/l10n_it_edi/i18n/it.po
  addons/mrp/models/mrp_workorder.py
  addons/pos_loyalty/static/src/js/ControlButtons/PromoCodeButton.js
  addons/project_purchase/models/project.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/stock/models/product.py
  addons/transifex/models/transifex_translation.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/snippet_table_of_content.js
  addons/website_sale/static/src/js/components/wysiwyg_adapter/wysiwyg_adapter.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: tmp.saas-16.1

#18737 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mrp/models/mrp_unbuild.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/stock/models/stock_picking.py
  addons/transifex/models/ir_translation.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.14.0

#18738 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/snailmail/wizard/snailmail_letter_format_error.py
  addons/transifex/models/ir_translation.py
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/corporate/brain-tec.md
  doc/cla/corporate/braintec-group.md
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/res_partner.py
Labels: tmp.15.0

#18742 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_edi/models/account_invoice.py
  addons/sale/views/sale_order_views.xml
Labels: master
