Repository brain-tec/odoo, pull requests merged in 2023-03, with the labels that each got.

#18784 Syncing from upstream odoo/odoo (14.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/common.py
  addons/account/tests/test_account_payment_register.py
  addons/google_account/controllers/main.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mrp/models/mrp_unbuild.py
  addons/sms/wizard/sms_composer_views.xml
  addons/web/static/src/js/core/smooth_scroll_on_drag.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: 14.0

#18785 Syncing from upstream odoo/odoo (15.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_account_journal.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_holidays/static/src/js/float_without_trailing_zeros.js
  addons/hr_holidays/views/hr_leave_accrual_views.xml
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mass_mailing/models/mailing.py
  addons/payment/tests/common.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_acquirer.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/models/assets.py
  addons/website/static/src/js/menu/edit.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: 15.0

#18787 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_din5008/i18n/l10n_din5008.pot
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_pe/data/l10n_pe_chart_post_data.xml
  addons/mass_mailing/models/mailing.py
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/website/static/src/js/menu/edit.js
Labels: saas-15.2

#18788 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_bank_statement.py
  addons/hr/report/hr_employee_badge.xml
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_din5008/i18n/fr.po
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/models/ir_binary.py
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/tests/test_controllers.py
  addons/website/tests/test_performance.py
  addons/website_payment/views/res_config_settings_views.xml
  addons/website_payment_authorize/views/res_config_settings_views.xml
  addons/website_payment_paypal/__manifest__.py
  addons/website_payment_paypal/views/res_config_settings_views.xml
  debian/copyright
  odoo/addons/base/models/ir_binary.py
  odoo/addons/base/tests/test_mimetypes.py
  odoo/addons/base/tests/test_test_suite.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/modules/loading.py
  odoo/modules/registry.py
  odoo/service/server.py
  odoo/tests/__init__.py
  odoo/tests/case.py
  odoo/tests/common.py
  odoo/tests/loader.py
  odoo/tests/result.py
  odoo/tests/suite.py
  odoo/tests/tag_selector.py
Labels: saas-16.1

#18791 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_bank_statement.py
  addons/hr/report/hr_employee_badge.xml
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_din5008/i18n/fr.po
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/models/ir_binary.py
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/tests/test_controllers.py
  addons/website/tests/test_performance.py
  addons/website_payment/views/res_config_settings_views.xml
  addons/website_payment_authorize/views/res_config_settings_views.xml
  addons/website_payment_paypal/__manifest__.py
  addons/website_payment_paypal/views/res_config_settings_views.xml
  debian/copyright
  odoo/addons/base/models/ir_binary.py
  odoo/addons/base/tests/test_mimetypes.py
  odoo/addons/base/tests/test_test_suite.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/modules/loading.py
  odoo/modules/registry.py
  odoo/service/server.py
  odoo/tests/__init__.py
  odoo/tests/case.py
  odoo/tests/common.py
  odoo/tests/loader.py
  odoo/tests/result.py
  odoo/tests/suite.py
  odoo/tests/tag_selector.py
Labels: staging.saas-16.1

#18792 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/common.py
  addons/account/tests/test_account_payment_register.py
  addons/google_account/controllers/main.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mrp/models/mrp_unbuild.py
  addons/sms/wizard/sms_composer_views.xml
  addons/web/static/src/js/core/smooth_scroll_on_drag.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: staging.14.0

#18796 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_din5008/i18n/l10n_din5008.pot
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_pe/data/l10n_pe_chart_post_data.xml
  addons/mass_mailing/models/mailing.py
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/website/static/src/js/menu/edit.js
Labels: tmp.saas-15.2

#18797 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_bank_statement.py
  addons/hr/report/hr_employee_badge.xml
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/1.1/post-migrate_update_amls.py
  addons/l10n_de_skr03/__manifest__.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr03/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_de_skr04/__manifest__.py
  addons/l10n_de_skr04/data/account_tax_fiscal_position_data.xml
  addons/l10n_de_skr04/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_din5008/i18n/fr.po
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mass_mailing/static/src/scss/mass_mailing.ui.scss
  addons/point_of_sale/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/models/ir_binary.py
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/tests/test_controllers.py
  addons/website/tests/test_performance.py
  addons/website_payment/views/res_config_settings_views.xml
  addons/website_payment_authorize/views/res_config_settings_views.xml
  addons/website_payment_paypal/__manifest__.py
  addons/website_payment_paypal/views/res_config_settings_views.xml
  debian/copyright
  odoo/addons/base/models/ir_binary.py
  odoo/addons/base/tests/test_mimetypes.py
  odoo/addons/base/tests/test_test_suite.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/modules/loading.py
  odoo/modules/registry.py
  odoo/service/server.py
  odoo/tests/__init__.py
  odoo/tests/case.py
  odoo/tests/common.py
  odoo/tests/loader.py
  odoo/tests/result.py
  odoo/tests/suite.py
  odoo/tests/tag_selector.py
Labels: tmp.saas-16.1

#18798 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/common.py
  addons/account/tests/test_account_payment_register.py
  addons/google_account/controllers/main.py
  addons/google_account/models/google_service.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mrp/models/mrp_unbuild.py
  addons/sms/wizard/sms_composer_views.xml
  addons/web/static/src/js/core/smooth_scroll_on_drag.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: tmp.14.0

#18799 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_account_journal.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_holidays/static/src/js/float_without_trailing_zeros.js
  addons/hr_holidays/views/hr_leave_accrual_views.xml
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/mass_mailing/models/mailing.py
  addons/payment/tests/common.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_acquirer.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/legacy/js/core/smooth_scroll_on_drag.js
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/models/assets.py
  addons/website/static/src/js/menu/edit.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: tmp.15.0

#18801 Syncing from upstream odoo/odoo (14.0)
  addons/account/views/res_partner_bank_views.xml
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_id_efaktur/models/account_move.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment.py
  addons/web/static/src/js/public/public_widget.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_chart/options.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: 14.0

#18802 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/res_partner_bank_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/static/src/models/rtc/rtc.js
  addons/stock/tests/test_inventory.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_chart/options.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: 15.0

#18804 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_account_journal.py
  addons/account/views/res_partner_bank_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_din5008/i18n/l10n_din5008.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/static/src/models/rtc/rtc.js
  addons/payment/tests/common.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_acquirer.py
  addons/payment_payulatam/tests/common.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/point_of_sale/models/pos_order.py
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_chart/options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: saas-15.2

#18805 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/views/res_partner_bank_views.xml
  addons/google_gmail/models/ir_mail_server.py
  addons/hr/models/hr_employee.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_hourly_cost/models/hr_employee.py
  addons/l10n_din5008/i18n/l10n_din5008.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/static/src/models/chatter.js
  addons/mail/static/src/models/drop_zone_view.js
  addons/mail/static/tests/qunit_suite_tests/widgets/form_renderer_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/error_handlers/error_handlers.js
  addons/pos_restaurant/static/src/app/error_handlers.js
  addons/pos_restaurant/static/src/js/Screens/FloorScreen/FloorScreen.js
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/static/lib/moment/locale/mn.js
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/src/legacy/scss/dropdown.scss
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/src/webclient/actions/reports/report.scss
  addons/web/static/tests/core/errors/error_service_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_chart/options.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.lang.csv
Labels: saas-16.1

#18809 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/views/res_partner_bank_views.xml
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_id_efaktur/models/account_move.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment.py
  addons/web/static/src/js/public/public_widget.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_chart/options.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: staging.14.0

#18815 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/views/res_partner_bank_views.xml
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_id_efaktur/models/account_move.py
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment.py
  addons/web/static/src/js/public/public_widget.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_chart/options.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: tmp.14.0

#18816 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/views/res_partner_bank_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_it_edi_sdicoop/models/account_edi_format.py
  addons/mail/static/src/models/rtc/rtc.js
  addons/stock/tests/test_inventory.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_chart/options.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: tmp.15.0

#18818 Syncing from upstream odoo/odoo (13.0)
  addons/snailmail/models/snailmail_letter.py
Labels: 13.0

#18819 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_timesheet/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
Labels: 14.0

#18822 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/gamification/data/mail_template_data.xml
  addons/gamification/i18n/gamification.pot
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/l10n_ar/views/report_invoice.xml
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/tests/test_inventory.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: saas-15.2

#18823 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi/models/account_edi_format.py
  addons/gamification/data/mail_template_data.xml
  addons/gamification/i18n/gamification.pot
  addons/hr/views/hr_employee_public_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_skills/static/src/fields/resume_one2many.xml
  addons/hr_skills/static/src/fields/skills_one2many.xml
  addons/hr_skills/views/hr_views.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_latam_account_sequence/models/account_move.py
  addons/mail/static/src/models/rtc.js
  addons/note/static/src/components/activity_menu_view/activity_menu_view.xml
  addons/note/static/src/scss/note.scss
  addons/product/report/product_product_templates.xml
  addons/sale/wizard/sale_order_cancel.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/tests/test_inventory.py
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_blog/controllers/main.py
  odoo/addons/base/data/res.country.state.csv
  odoo/addons/base/data/res_currency_data.xml
Labels: saas-16.1

#18826 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi/models/account_edi_format.py
  addons/gamification/data/mail_template_data.xml
  addons/gamification/i18n/gamification.pot
  addons/hr/views/hr_employee_public_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_skills/static/src/fields/resume_one2many.xml
  addons/hr_skills/static/src/fields/skills_one2many.xml
  addons/hr_skills/views/hr_views.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_latam_account_sequence/models/account_move.py
  addons/mail/static/src/models/rtc.js
  addons/note/static/src/components/activity_menu_view/activity_menu_view.xml
  addons/note/static/src/scss/note.scss
  addons/product/report/product_product_templates.xml
  addons/sale/wizard/sale_order_cancel.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/tests/test_inventory.py
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_blog/controllers/main.py
  odoo/addons/base/data/res.country.state.csv
  odoo/addons/base/data/res_currency_data.xml
Labels: staging.saas-16.1

#18827 Syncing from upstream odoo/odoo (staging.13.0)
  addons/snailmail/models/snailmail_letter.py
Labels: staging.13.0

#18828 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_timesheet/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
Labels: staging.14.0

#18832 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/gamification/data/mail_template_data.xml
  addons/gamification/i18n/gamification.pot
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/l10n_ar/views/report_invoice.xml
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/tests/test_inventory.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
Labels: tmp.saas-15.2

#18833 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi/models/account_edi_format.py
  addons/gamification/data/mail_template_data.xml
  addons/gamification/i18n/gamification.pot
  addons/hr/views/hr_employee_public_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_skills/static/src/fields/resume_one2many.xml
  addons/hr_skills/static/src/fields/skills_one2many.xml
  addons/hr_skills/views/hr_views.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_latam_account_sequence/models/account_move.py
  addons/mail/static/src/models/rtc.js
  addons/note/static/src/components/activity_menu_view/activity_menu_view.xml
  addons/note/static/src/scss/note.scss
  addons/product/report/product_product_templates.xml
  addons/sale/wizard/sale_order_cancel.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/tests/test_inventory.py
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_blog/controllers/main.py
  odoo/addons/base/data/res.country.state.csv
  odoo/addons/base/data/res_currency_data.xml
Labels: tmp.saas-16.1

#18834 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/snailmail/models/snailmail_letter.py
Labels: tmp.13.0

#18835 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_timesheet/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
Labels: tmp.14.0

#18836 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_edi_format.py
  addons/base_iban/models/res_partner_bank.py
  addons/gamification/data/mail_template_data.xml
  addons/gamification/i18n/gamification.pot
  addons/google_account/controllers/main.py
  addons/google_account/models/google_service.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/sale_timesheet/models/account_move.py
  addons/web/static/src/legacy/js/public/public_widget.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.15.0

#18838 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_21.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_xrechnung.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice_tax_incl.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_de.py
  addons/purchase/views/purchase_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web/static/src/js/core/dom.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
  addons/website_form/static/src/scss/wysiwyg_snippets.scss
Labels: 14.0

#18839 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_payment.py
  addons/account/wizard/account_payment_register.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock/models/stock_picking.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
Labels: 15.0

#18842 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_tax.py
  addons/account/models/res_partner_bank.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/views/account_journal_views.xml
  addons/base_iban/models/res_partner_bank.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_ec/data/l10n_latam_identification_type_data.xml
  addons/mrp/static/src/scss/mrp_workorder_kanban.scss
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_project/models/account_move.py
  addons/sms/wizard/sms_composer_views.xml
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/stock_move.py
  addons/stock/static/src/widgets/json_widget.xml
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_controller_args.py
  addons/web/static/src/legacy/js/public/public_widget.js
  addons/web_editor/static/src/components/media_dialog/icon_selector.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/models/website.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/001.scss
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/media_dialog.js
  addons/website/static/tests/tours/website_click_tests.js
  addons/website/tests/test_ui.py
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_sale/tests/test_sitemap.py
  addons/website_sale/views/templates.xml
Labels: saas-16.1

#18845 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_tax.py
  addons/account/models/res_partner_bank.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/views/account_journal_views.xml
  addons/base_iban/models/res_partner_bank.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_ec/data/l10n_latam_identification_type_data.xml
  addons/mrp/static/src/scss/mrp_workorder_kanban.scss
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_project/models/account_move.py
  addons/sms/wizard/sms_composer_views.xml
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/stock_move.py
  addons/stock/static/src/widgets/json_widget.xml
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_controller_args.py
  addons/web/static/src/legacy/js/public/public_widget.js
  addons/web_editor/static/src/components/media_dialog/icon_selector.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/models/website.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/001.scss
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/media_dialog.js
  addons/website/static/tests/tours/website_click_tests.js
  addons/website/tests/test_ui.py
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_sale/tests/test_sitemap.py
  addons/website_sale/views/templates.xml
Labels: staging.saas-16.1

#18846 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_21.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_xrechnung.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice_tax_incl.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_de.py
  addons/purchase/views/purchase_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web/static/src/js/core/dom.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
  addons/website_form/static/src/scss/wysiwyg_snippets.scss
Labels: staging.14.0

#18850 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/mrp_subcontracting/models/stock_move.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_account_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/static/src/legacy/js/public/public_widget.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_process_steps/options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
Labels: tmp.saas-15.2

#18851 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_tax.py
  addons/account/models/res_partner_bank.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/views/account_journal_views.xml
  addons/base_iban/models/res_partner_bank.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_ec/data/l10n_latam_identification_type_data.xml
  addons/mrp/static/src/scss/mrp_workorder_kanban.scss
  addons/point_of_sale/static/src/js/models.js
  addons/project/models/project.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_project/models/account_move.py
  addons/sms/wizard/sms_composer_views.xml
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/stock_move.py
  addons/stock/static/src/widgets/json_widget.xml
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_controller_args.py
  addons/web/static/src/legacy/js/public/public_widget.js
  addons/web_editor/static/src/components/media_dialog/icon_selector.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/models/website.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/001.scss
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/media_dialog.js
  addons/website/static/tests/tours/website_click_tests.js
  addons/website/tests/test_ui.py
  addons/website_blog/controllers/main.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_event_track_quiz/controllers/community.py
  addons/website_profile/controllers/main.py
  addons/website_profile/views/website_profile.xml
  addons/website_sale/tests/test_sitemap.py
  addons/website_sale/views/templates.xml
Labels: tmp.saas-16.1

#18852 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_21.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_xrechnung.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice_tax_incl.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_de.py
  addons/purchase/views/purchase_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web/static/src/js/core/dom.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
  addons/website_form/static/src/scss/wysiwyg_snippets.scss
Labels: tmp.14.0

#18853 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_payment.py
  addons/account/wizard/account_payment_register.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock/models/stock_picking.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
Labels: tmp.15.0

#18859 Syncing from upstream odoo/odoo (staging.saas-16.1)
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.saas-16.1

#18862 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-16.1

#18863 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_21.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_xrechnung.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_invoice_tax_incl.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_de.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_nl.py
Labels: 15.0

#18877 Syncing from upstream odoo/odoo (14.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/base_vat/models/res_partner.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/wizard/mail_template_preview.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/addons/test_new_api/tests/test_one2many.py
Labels: 14.0

#18878 Syncing from upstream odoo/odoo (15.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/addons/test_new_api/tests/test_one2many.py
Labels: 15.0

#18881 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_payment.py
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/mail/models/mail_channel.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website_forum/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/addons/test_new_api/tests/test_one2many.py
Labels: saas-15.2

#18890 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_payment.py
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/mail/models/mail_channel.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/utils.js
  addons/website_forum/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/addons/test_new_api/tests/test_one2many.py
Labels: tmp.saas-15.2

#18893 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_check_printing/models/account_payment.py
  addons/account_check_printing/tests/test_print_check.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/mail/models/mail_channel.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/addons/test_new_api/tests/test_one2many.py
Labels: tmp.15.0

#18895 Syncing from upstream odoo/odoo (14.0)
  addons/google_spreadsheet/views/google_spreadsheet_views.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/snailmail/models/snailmail_letter.py
  addons/web/static/src/scss/import_bootstrap.scss
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
Labels: 14.0

#18896 Syncing from upstream odoo/odoo (15.0)
  addons/base_vat/models/res_partner.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/snailmail/models/snailmail_letter.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/base/models/ir_actions_report.py
Labels: 15.0

#18897 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/base_vat/models/res_partner.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_channel_member.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/product/views/product_views.xml
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/snailmail/models/snailmail_letter.py
  addons/stock/static/src/scss/stock_traceability_report.scss
  addons/web/controllers/webclient.py
  addons/web/static/src/legacy/js/core/cookie_utils.js
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/static/src/views/fields/boolean/boolean_field.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/form/form_group/form_group.xml
  addons/web/static/src/webclient/settings_form_view/settings_form_view.scss
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/models/ir_actions_report.py
Labels: 16.0

#18899 Syncing from upstream odoo/odoo (saas-15.2)
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/base_vat/models/res_partner.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/snailmail/models/snailmail_letter.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-15.2

#18900 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/base_vat/models/res_partner.py
  addons/google_account/controllers/main.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_channel_member.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_snippets_menu_tabs.js
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mass_mailing/tests/test_mailing_ui.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/views/mrp_production_views.xml
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_provider.py
  addons/payment_payulatam/tests/common.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/pos_loyalty/models/pos_session.py
  addons/project/__init__.py
  addons/project/models/__init__.py
  addons/project/models/mail_message.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/snailmail/models/snailmail_letter.py
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/view_button/view_button.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website_slides_survey/__init__.py
  addons/website_slides_survey/__manifest__.py
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-16.1

#18903 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/base_vat/models/res_partner.py
  addons/google_account/controllers/main.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_channel_member.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_snippets_menu_tabs.js
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mass_mailing/tests/test_mailing_ui.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/views/mrp_production_views.xml
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_provider.py
  addons/payment_payulatam/tests/common.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/pos_loyalty/models/pos_session.py
  addons/project/__init__.py
  addons/project/models/__init__.py
  addons/project/models/mail_message.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/snailmail/models/snailmail_letter.py
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/view_button/view_button.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website_slides_survey/__init__.py
  addons/website_slides_survey/__manifest__.py
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.saas-16.1

#18904 Syncing from upstream odoo/odoo (staging.14.0)
  addons/google_spreadsheet/views/google_spreadsheet_views.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/snailmail/models/snailmail_letter.py
  addons/web/static/src/scss/import_bootstrap.scss
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.14.0

#18908 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/base_vat/models/res_partner.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/snailmail/models/snailmail_letter.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-15.2

#18909 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_inalterable_hash.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail_enforce/data/mail_template_data.xml
  addons/base_vat/models/res_partner.py
  addons/google_account/controllers/main.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_channel_member.py
  addons/mail/models/res_partner.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_snippets_menu_tabs.js
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mass_mailing/tests/test_mailing_ui.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/views/mrp_production_views.xml
  addons/payment_payulatam/controllers/main.py
  addons/payment_payulatam/models/payment_provider.py
  addons/payment_payulatam/tests/common.py
  addons/payment_payulatam/tests/test_payulatam.py
  addons/pos_loyalty/models/pos_session.py
  addons/project/__init__.py
  addons/project/models/__init__.py
  addons/project/models/mail_message.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/snailmail/models/snailmail_letter.py
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_picking_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/view_button/view_button.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/000.scss
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website_slides_survey/__init__.py
  addons/website_slides_survey/__manifest__.py
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-16.1

#18910 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/google_spreadsheet/views/google_spreadsheet_views.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/snailmail/models/snailmail_letter.py
  addons/web/static/src/scss/import_bootstrap.scss
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.14.0

#18911 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_vat/models/res_partner.py
  addons/hr_contract/data/hr_contract_data.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/snailmail/models/snailmail_letter.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.15.0

#18914 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/models/models.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/stock/models/stock_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: 14.0

#18915 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/models/models.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/legacy/scss/import_bootstrap.scss
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: 15.0

#18916 Syncing from upstream odoo/odoo (16.0)
  addons/hr/views/hr_employee_views.xml
  addons/hr_fleet/views/employee_views.xml
  addons/hr_holidays/models/hr_employee.py
  addons/hr_hourly_cost/views/hr_employee_views.xml
  addons/hr_org_chart/static/src/fields/hr_org_chart.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/controllers/discuss.py
  addons/mail/models/ir_websocket.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mrp/models/mrp_production.py
  addons/purchase/views/purchase_views.xml
  addons/repair/report/repair_templates_repair_order.xml
  addons/sale/models/sale_order.py
  addons/sale/views/sale_order_views.xml
  addons/stock/views/stock_picking_type_views.xml
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_account_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/scss/import_bootstrap.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
Labels: 16.0

#18918 Syncing from upstream odoo/odoo (saas-15.2)
  addons/google_account/controllers/main.py
  addons/google_account/models/google_service.py
  addons/mail/models/models.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/legacy/scss/import_bootstrap.scss
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: saas-15.2

#18919 Syncing from upstream odoo/odoo (saas-16.1)
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/controllers/discuss.py
  addons/mail/models/ir_websocket.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mrp/models/mrp_production.py
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/product/views/product_views.xml
  addons/purchase/views/purchase_views.xml
  addons/repair/report/repair_templates_repair_order.xml
  addons/sale/models/sale_order.py
  addons/sale/views/sale_order_views.xml
  addons/stock/views/stock_picking_type_views.xml
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_account_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/static/src/scss/import_bootstrap.scss
  addons/web/static/src/views/fields/boolean/boolean_field.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/form/form_group/form_group.xml
  addons/web/static/src/webclient/settings_form_view/settings_form_view.scss
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: saas-16.1

#18922 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/controllers/discuss.py
  addons/mail/models/ir_websocket.py
  addons/mail/tests/test_mail_channel_as_guest.py
  addons/mrp/models/mrp_production.py
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/product/views/product_views.xml
  addons/purchase/views/purchase_views.xml
  addons/repair/report/repair_templates_repair_order.xml
  addons/sale/models/sale_order.py
  addons/sale/views/sale_order_views.xml
  addons/stock/views/stock_picking_type_views.xml
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_account_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/static/src/scss/import_bootstrap.scss
  addons/web/static/src/views/fields/boolean/boolean_field.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/form/form_group/form_group.xml
  addons/web/static/src/webclient/settings_form_view/settings_form_view.scss
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: staging.saas-16.1

#18923 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/models/models.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/stock/models/stock_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: staging.14.0

#18927 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/google_account/controllers/main.py
  addons/google_account/models/google_service.py
  addons/mail/models/models.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/legacy/scss/import_bootstrap.scss
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: tmp.saas-15.2

#18929 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/models/models.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/stock/models/stock_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: tmp.14.0

#18930 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/mail/models/models.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/legacy/scss/import_bootstrap.scss
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
Labels: tmp.15.0

#18932 Syncing from upstream odoo/odoo (14.0)
  addons/account/controllers/portal.py
  addons/account/models/account_account.py
  addons/account/security/account_security.xml
  addons/mrp/models/mrp_production.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale.py
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  doc/cla/corporate/acsone.md
Labels: 14.0

#18933 Syncing from upstream odoo/odoo (15.0)
  addons/account/controllers/portal.py
  addons/account/security/account_security.xml
  addons/hr_holidays/models/hr_leave.py
  addons/purchase/views/analytic_account_views.xml
  addons/purchase/views/purchase_views.xml
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  doc/cla/corporate/acsone.md
Labels: 15.0

#18936 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/controllers/portal.py
  addons/account/security/account_security.xml
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/purchase/views/purchase_views.xml
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_move.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  doc/cla/corporate/acsone.md
Labels: saas-15.2

#18937 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/security/account_security.xml
  addons/account/views/account_move_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi/models/account_journal.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/account_edi_proxy_client_security.xml
  addons/calendar/__manifest__.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.xml
  addons/calendar/static/tests/tours/calendar_tour.js
  addons/calendar/tests/test_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_renderer.scss
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/common.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/mail/models/mail_render_mixin.py
  addons/mrp/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_six/static/src/js/payment_six.js
  addons/sale/views/sale_order_views.xml
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/stock_account/models/account_move.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
  odoo/models.py
Labels: saas-16.1

#18940 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/security/account_security.xml
  addons/account/views/account_move_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi/models/account_journal.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/account_edi_proxy_client_security.xml
  addons/calendar/__manifest__.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.xml
  addons/calendar/static/tests/tours/calendar_tour.js
  addons/calendar/tests/test_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_renderer.scss
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/common.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/mail/models/mail_render_mixin.py
  addons/mrp/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_six/static/src/js/payment_six.js
  addons/sale/views/sale_order_views.xml
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/stock_account/models/account_move.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-16.1

#18941 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/controllers/portal.py
  addons/account/models/account_account.py
  addons/account/security/account_security.xml
  addons/mrp/models/mrp_production.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale.py
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  doc/cla/corporate/acsone.md
Labels: staging.14.0

#18945 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/controllers/portal.py
  addons/account/security/account_security.xml
  addons/l10n_it_edi_sdicoop/models/account_invoice.py
  addons/purchase/views/purchase_views.xml
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_move.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  doc/cla/corporate/acsone.md
Labels: tmp.saas-15.2

#18946 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/security/account_security.xml
  addons/account/views/account_move_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi/models/account_journal.py
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/security/account_edi_proxy_client_security.xml
  addons/calendar/__manifest__.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.xml
  addons/calendar/static/tests/tours/calendar_tour.js
  addons/calendar/tests/test_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_renderer.scss
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/common.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/mail/models/mail_render_mixin.py
  addons/mrp/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_six/static/src/js/payment_six.js
  addons/sale/views/sale_order_views.xml
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/sale_product_configurator/views/templates.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/stock_account/models/account_move.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/static/tests/tours/website_sale_variants_modal_window.js
  addons/website_sale/tests/test_customize.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
  odoo/models.py
Labels: tmp.saas-16.1

#18947 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/controllers/portal.py
  addons/account/models/account_account.py
  addons/account/security/account_security.xml
  addons/mrp/models/mrp_production.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale.py
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  doc/cla/corporate/acsone.md
Labels: tmp.14.0

#18948 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/controllers/portal.py
  addons/account/security/account_security.xml
  addons/hr_holidays/models/hr_leave.py
  addons/purchase/views/analytic_account_views.xml
  addons/purchase/views/purchase_views.xml
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order.py
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock_account/models/product.py
  addons/test_mail_full/tests/test_sms_composer.py
  doc/cla/corporate/acsone.md
Labels: tmp.15.0

#18950 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/mrp/models/mrp_unbuild.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_scrap_views.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: 14.0

#18951 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_account.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/product/report/product_product_templates.xml
  addons/product_expiry/report/report_deliveryslip.xml
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock_account/models/stock_move_line.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: 15.0

#18952 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_early_payment_discount.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/analytic/models/analytic_account.py
  addons/hr/views/hr_department_views.xml
  addons/hr/views/hr_job_views.xml
  addons/hr/views/hr_plan_views.xml
  addons/hr/views/hr_work_location_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/mail/controllers/discuss.py
  addons/mail/static/src/views/form/form_compiler.js
  addons/mail/static/src/views/form/form_controller.js
  addons/mass_mailing/static/image_shapes/basic/circle.svg
  addons/mass_mailing/static/image_shapes/basic/slanted.svg
  addons/mass_mailing/static/image_shapes/basic/triangle.svg
  addons/mass_mailing/static/src/img/theme_default/s_default_image_team_member_1-circle.png
  addons/mass_mailing/static/src/img/theme_default/s_default_image_team_member_2-circle.png
  addons/mass_mailing/static/src/img/theme_default/s_default_image_team_member_3-circle.png
  addons/mass_mailing/static/src/img/theme_default/s_default_image_team_member_4-circle.png
  addons/mass_mailing/views/snippets/s_blockquote.xml
  addons/mass_mailing/views/snippets/s_company_team.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/report/mrp_report_bom_structure.xml
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase_stock/models/stock_move.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/sale_stock/models/sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/migration.js
  addons/stock/models/stock_move_line.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/views/widgets/signature/signature.js
  addons/web/static/tests/views/widgets/signature_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/secondary_variables.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: 16.0

#18954 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_account.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock/models/stock_move_line.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: saas-15.2

#18959 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/mrp/models/mrp_unbuild.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_scrap_views.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: staging.14.0

#18963 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_account.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock/models/stock_move_line.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: tmp.saas-15.2

#18965 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/mrp/models/mrp_unbuild.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_scrap_views.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: tmp.14.0

#18966 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_account.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_lu_peppol_id/__init__.py
  addons/l10n_lu_peppol_id/__manifest__.py
  addons/l10n_lu_peppol_id/models/__init__.py
  addons/l10n_lu_peppol_id/models/res_partner.py
  addons/l10n_lu_peppol_id/views/partner_view.xml
  addons/product/report/product_product_templates.xml
  addons/product_expiry/report/report_deliveryslip.xml
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock_account/models/stock_move_line.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: tmp.15.0

#18969 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/cs.po
  addons/account/i18n/de.po
  addons/account/i18n/fr.po
  addons/account/i18n/id.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/account/i18n/ko.po
  addons/account/i18n/lt.po
  addons/account/i18n/nb.po
  addons/account/i18n/pl.po
  addons/account/i18n/tr.po
  addons/account/i18n/uk.po
  addons/account/i18n/zh_TW.po
  addons/account_debit_note/i18n/ko.po
  addons/account_edi/i18n/it.po
  addons/auth_oauth/i18n/fi.po
  addons/auth_totp/i18n/fi.po
  addons/auth_totp_mail/i18n/fi.po
  addons/auth_totp_mail/i18n/ko.po
  addons/auth_totp_mail_enforce/i18n/fi.po
  addons/auth_totp_mail_enforce/i18n/ko.po
  addons/barcodes/i18n/pl.po
  addons/base_import/i18n/pl.po
  addons/base_setup/i18n/fi.po
  addons/calendar/i18n/ja.po
  addons/calendar/i18n/pl.po
  addons/contacts/i18n/ja.po
  addons/crm/i18n/ja.po
  addons/crm/i18n/pl.po
  addons/crm_iap_enrich/i18n/pl.po
  addons/crm_iap_mine/i18n/de.po
  addons/crm_iap_mine/i18n/pl.po
  addons/crm_mail_plugin/i18n/pl.po
  addons/delivery/i18n/fr.po
  addons/delivery/i18n/id.po
  addons/delivery/i18n/pl.po
  addons/digest/i18n/pl.po
  addons/event/i18n/ja.po
  addons/event/i18n/sk.po
  addons/event_booth/i18n/ja.po
  addons/event_booth_sale/i18n/cs.po
  addons/event_crm/i18n/pl.po
  addons/fetchmail/i18n/pl.po
  addons/fleet/i18n/ja.po
  addons/gamification/i18n/es.po
  addons/gamification/i18n/es_MX.po
  addons/gamification/i18n/et.po
  addons/gamification/i18n/uk.po
  addons/gamification_sale_crm/i18n/pl.po
  addons/hr_timesheet/views/res_config_settings_views.xml
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/et.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/ja.po
  odoo/addons/base/i18n/ko.po
  odoo/addons/base/i18n/nb.po
  odoo/addons/base/i18n/pl.po
  odoo/addons/base/i18n/pt.po
Labels: 15.0

#18971 Syncing from upstream odoo/odoo (master)
  addons/website/static/src/js/content/snippets.animation.js
Labels: master

#18972 Syncing from upstream odoo/odoo (saas-16.1)
  addons/stock/static/src/scss/stock_traceability_report.scss
Labels: saas-16.1

#18975 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/stock/static/src/scss/stock_traceability_report.scss
Labels: staging.saas-16.1

#18979 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/stock/static/src/scss/stock_traceability_report.scss
Labels: tmp.saas-16.1

#18980 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_timesheet/views/res_config_settings_views.xml
Labels: tmp.15.0

#18982 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_edi/models/account_invoice.py
Labels: master

#18989 Syncing from upstream odoo/odoo (13.0)
  odoo/tests/common.py
Labels: 13.0

#18990 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/models/ir_qweb.py
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/options.js
  odoo/addons/base/tests/test_db_cursor.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: 14.0

#18991 Syncing from upstream odoo/odoo (15.0)
  addons/event/models/event_mail.py
  addons/event/views/event_views.xml
  addons/event_sms/models/event_mail.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/mail/wizard/mail_template_preview.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/i18n/pos_sale.pot
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderFetcher.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderRow.js
  addons/pos_sale/static/src/xml/OrderManagementScreen/SaleOrderRow.xml
  addons/product/report/product_pricelist_report.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web/static/src/boot.js
  addons/web_editor/models/ir_qweb.py
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
  addons/website_blog/static/src/snippets/s_blog_posts/options.js
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/options.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/views/res_country_views.xml
  odoo/sql_db.py
  odoo/tests/common.py
Labels: 15.0

#18992 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/account_bank_statement_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/account_bank_statement_views.xml
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/models.py
  addons/mail/tests/test_mail_template.py
  addons/product_expiry/report/report_deliveryslip.xml
  addons/purchase/views/analytic_account_views.xml
  addons/sale_project/models/project.py
  addons/stock/models/stock_location.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/views/form/form_group/form_group.xml
  addons/web/static/tests/mobile/views/widgets/signature_tests.js
  addons/web/static/tests/views/widgets/signature_tests.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_sale/models/product_product.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/sql_db.py
Labels: 16.0

#18994 Syncing from upstream odoo/odoo (saas-15.2)
  addons/event/models/event_mail.py
  addons/event/views/event_views.xml
  addons/event_sms/models/event_mail.py
  addons/l10n_ch/models/mail_template.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_in/data/account_tax_group_data.xml
  addons/l10n_in/data/account_tax_template_data.xml
  addons/l10n_in_edi/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/product_expiry/report/report_deliveryslip.xml
  addons/purchase/views/analytic_account_views.xml
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order.py
  addons/sale_stock/tests/test_create_perf.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: saas-15.2

#18995 Syncing from upstream odoo/odoo (saas-16.1)
  addons/base_import/models/base_import.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/mail/models/models.py
  addons/product_expiry/report/report_deliveryslip.xml
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_requisition/wizard/purchase_requisition_create_alternative.py
  addons/purchase_stock/models/stock_move.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/sale_project/models/project.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/controllers/webclient.py
  addons/web/static/src/core/popover/popover_container.js
  addons/web/static/src/legacy/js/core/cookie_utils.js
  addons/web/static/tests/core/popover/popover_service_tests.js
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/tests/test_db_cursor.py
  odoo/sql_db.py
Labels: saas-16.1

#18998 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/base_import/models/base_import.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/mail/models/models.py
  addons/product_expiry/report/report_deliveryslip.xml
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_requisition/wizard/purchase_requisition_create_alternative.py
  addons/purchase_stock/models/stock_move.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/sale_project/models/project.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/controllers/webclient.py
  addons/web/static/src/core/popover/popover_container.js
  addons/web/static/src/legacy/js/core/cookie_utils.js
  addons/web/static/tests/core/popover/popover_service_tests.js
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/tests/test_db_cursor.py
  odoo/sql_db.py
Labels: staging.saas-16.1

#18999 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/tests/common.py
Labels: staging.13.0

#19005 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/base_import/models/base_import.py
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/mail/models/models.py
  addons/product_expiry/report/report_deliveryslip.xml
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_requisition/wizard/purchase_requisition_create_alternative.py
  addons/purchase_stock/models/stock_move.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/sale_project/models/project.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/controllers/webclient.py
  addons/web/static/src/core/popover/popover_container.js
  addons/web/static/src/legacy/js/core/cookie_utils.js
  addons/web/static/tests/core/popover/popover_service_tests.js
  addons/web_tour/static/src/js/running_tour_action_helper.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_blog/static/tests/tours/blog_search_with_date.js
  addons/website_blog/tests/test_ui.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/tests/test_db_cursor.py
  odoo/sql_db.py
Labels: tmp.saas-16.1

#19006 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/tests/common.py
Labels: tmp.13.0

#19010 Syncing from upstream odoo/odoo (14.0)
  addons/account/security/account_security.xml
  addons/mail/data/mail_data.xml
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
Labels: 14.0

#19011 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/account_reconcile_model_views.xml
  addons/google_spreadsheet/views/google_spreadsheet_views.xml
  addons/hr/models/mail_channel.py
  addons/mail/data/mail_templates.xml
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website_slides/static/src/scss/website_slides.scss
  odoo/addons/base/__manifest__.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: 15.0

#19014 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr/models/mail_channel.py
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/mail/wizard/mail_template_preview.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/product/report/product_pricelist_report.py
  addons/product/report/product_product_templates.xml
  addons/stock_account/models/stock_move_line.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web/static/src/boot.js
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
  addons/website_blog/static/src/snippets/s_blog_posts/options.js
  addons/website_event/static/src/snippets/s_events/options.js
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/options.js
Labels: saas-15.2

#19019 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/security/account_security.xml
  addons/mail/data/mail_data.xml
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
Labels: staging.14.0

#19023 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr/models/mail_channel.py
  addons/hr_timesheet/views/res_config_settings_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/mail/wizard/mail_template_preview.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/product/report/product_pricelist_report.py
  addons/product/report/product_product_templates.xml
  addons/stock_account/models/stock_move_line.py
  addons/test_mail/tests/test_mail_template_preview.py
  addons/web/static/src/boot.js
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
  addons/website_blog/static/src/snippets/s_blog_posts/options.js
  addons/website_event/static/src/snippets/s_events/options.js
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/options.js
Labels: tmp.saas-15.2

#19025 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/security/account_security.xml
  addons/mail/data/mail_data.xml
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
Labels: tmp.14.0

#19026 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/views/account_reconcile_model_views.xml
  addons/google_spreadsheet/views/google_spreadsheet_views.xml
  addons/hr/models/mail_channel.py
  addons/mail/data/mail_templates.xml
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website_slides/static/src/scss/website_slides.scss
  odoo/addons/base/__manifest__.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: tmp.15.0

#19028 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/stock/views/product_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_landed_costs/models/account_move.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: 14.0

#19029 Syncing from upstream odoo/odoo (15.0)
  addons/mrp/models/mrp_production.py
  addons/payment/utils.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/pos_session.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale_stock/tests/test_report.py
  addons/sale_stock/tests/test_sale_stock_report.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_landed_costs/models/account_move.py
  addons/survey/views/survey_report_templates.xml
Labels: 15.0

#19030 Syncing from upstream odoo/odoo (16.0)
  addons/account/views/res_config_settings_views.xml
  addons/analytic/views/analytic_plan_views.xml
  addons/base_automation/models/base_automation.py
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/mail/wizard/mail_template_preview.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/static/src/mrp_forecasted/forecasted_buttons.js
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/portal_rating/static/src/scss/portal_rating.scss
  addons/portal_rating/static/src/xml/portal_chatter.xml
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/survey/views/survey_question_views.xml
  addons/test_mail/tests/test_mail_template_preview.py
  addons/test_sale_product_configurators/tests/test_sale_product_matrix.py
  addons/web/static/src/webclient/webclient.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_dynamic_snippet/options.js
  addons/website/static/src/snippets/s_dynamic_snippet_carousel/options.js
  addons/website/views/snippets/s_dynamic_snippet.xml
  addons/website_blog/static/src/snippets/s_blog_posts/options.js
  addons/website_event/static/src/scss/event_templates_page.scss
  addons/website_event/static/src/snippets/s_events/options.js
  addons/website_event_track_live/static/src/js/website_event_track_live.js
  addons/website_event_track_live/views/event_track_templates_page.xml
  addons/website_profile/views/website_profile.xml
  addons/website_sale/static/src/snippets/s_dynamic_snippet_products/options.js
  addons/website_slides/models/slide_slide_resource.py
  addons/website_slides/tests/test_slide_resource.py
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  odoo/addons/base/__manifest__.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: 16.0

#19032 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_din5008_repair/models/repair.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mrp/models/mrp_production.py
  addons/stock_landed_costs/models/account_move.py
  odoo/addons/base/__manifest__.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: saas-15.2

#19033 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/ir_actions_report.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/l10n_au/__init__.py
  addons/l10n_au/__manifest__.py
  addons/l10n_au/data/l10n_au_chart_data.xml
  addons/l10n_au/models/__init__.py
  addons/l10n_au/models/chart_template.py
  addons/l10n_au/views/res_company_views.xml
  addons/l10n_co/data/l10n_co_chart_data.xml
  addons/l10n_co/i18n/es.po
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/static/src/stock_forecasted/forecasted_warehouse_filter.js
  addons/stock/static/src/stock_forecasted/stock_forecasted.js
  addons/stock/static/src/stock_forecasted/stock_forecasted.xml
  addons/stock/views/stock_scrap_views.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website_livechat/controllers/main.py
  addons/website_slides/models/slide_slide_resource.py
  addons/website_slides/tests/test_slide_resource.py
  addons/website_slides/views/website_slides_templates_lesson.xml
  addons/website_slides/views/website_slides_templates_lesson_fullscreen.xml
  doc/cla/corporate/ito-invest.md
  odoo/addons/test_http/tests/test_web_server.py
Labels: saas-16.1

#19037 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/stock/views/product_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_landed_costs/models/account_move.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: staging.14.0

#19041 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_din5008_repair/models/repair.py
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/mrp/models/mrp_production.py
  addons/stock_landed_costs/models/account_move.py
  odoo/addons/base/__manifest__.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_currency.py
Labels: tmp.saas-15.2

#19043 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/stock/views/product_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_landed_costs/models/account_move.py
  addons/website_sale/controllers/main.py
  addons/website_sale/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/test_website_sale_cart_payment.py
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: tmp.14.0

#19044 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/mrp/models/mrp_production.py
  addons/payment/utils.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/pos_session.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale_stock/tests/test_report.py
  addons/sale_stock/tests/test_sale_stock_report.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_landed_costs/models/account_move.py
  addons/survey/views/survey_report_templates.xml
Labels: tmp.15.0

#19046 [bt#22075] fetchmail_outlook and microsoft_outlook
  addons/fetchmail_outlook/__init__.py
  addons/fetchmail_outlook/__manifest__.py
  addons/fetchmail_outlook/models/__init__.py
  addons/fetchmail_outlook/models/fetchmail_server.py
  addons/fetchmail_outlook/tests/__init__.py
  addons/fetchmail_outlook/tests/test_fetchmail_outlook.py
  addons/fetchmail_outlook/views/fetchmail_server_views.xml
  addons/microsoft_outlook/__init__.py
  addons/microsoft_outlook/__manifest__.py
  addons/microsoft_outlook/controllers/__init__.py
  addons/microsoft_outlook/controllers/main.py
  addons/microsoft_outlook/models/__init__.py
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/microsoft_outlook/models/res_company.py
  addons/microsoft_outlook/models/res_config_settings.py
  addons/microsoft_outlook/views/ir_mail_server_views.xml
  addons/microsoft_outlook/views/res_config_settings_views.xml
  addons/microsoft_outlook/views/templates.xml
Labels: 11.0.project_co_286

#18657 [bt#21511][CR] Reactivate Attachment Delete-Button
  addons/mail/static/src/xml/thread.xml
Labels: 12.0.project_st_215

#19047 Syncing from upstream odoo/odoo (14.0)
  addons/event/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: 14.0

#19048 Syncing from upstream odoo/odoo (15.0)
  addons/account/security/account_security.xml
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/mrp/models/mrp_unbuild.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/sale_project/models/sale_order.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/product_views.xml
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/core/dropdown/dropdown.scss
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: 15.0

#19051 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/security/account_security.xml
  addons/account/views/res_config_settings_views.xml
  addons/delivery/views/stock_picking_type_views.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses_mail_import.py
  addons/payment/utils.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_sale/i18n/pos_sale.pot
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderFetcher.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderRow.js
  addons/pos_sale/static/src/xml/OrderManagementScreen/SaleOrderRow.xml
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/sale_project/models/sale_order.py
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/survey/views/survey_report_templates.xml
  addons/web/static/src/core/dropdown/dropdown.scss
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: saas-15.2

#19058 Syncing from upstream odoo/odoo (staging.14.0)
  addons/event/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: staging.14.0

#19062 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/security/account_security.xml
  addons/account/views/res_config_settings_views.xml
  addons/delivery/views/stock_picking_type_views.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses_mail_import.py
  addons/payment/utils.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_sale/i18n/pos_sale.pot
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderFetcher.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderRow.js
  addons/pos_sale/static/src/xml/OrderManagementScreen/SaleOrderRow.xml
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/sale_project/models/sale_order.py
  addons/stock/models/product.py
  addons/stock/views/product_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/survey/views/survey_report_templates.xml
  addons/web/static/src/core/dropdown/dropdown.scss
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: tmp.saas-15.2

#19065 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/event/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: tmp.14.0

#19066 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/security/account_security.xml
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/mrp/models/mrp_unbuild.py
  addons/payment_ogone/models/payment_transaction.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/sale_project/models/sale_order.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/product_views.xml
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web/static/src/core/dropdown/dropdown.scss
  doc/cla/corporate/versada.md
  doc/cla/individual/oerp-odoo.md
Labels: tmp.15.0

#19069 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_reconcile_model.py
  addons/account_edi/tests/common.py
  addons/event/controllers/main.py
  addons/mail/controllers/discuss.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/mail_plugin/views/mail_plugin_login.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_ir_cron.py
Labels: 15.0

#19070 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/security/account_security.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/views/account_edi_proxy_user_views.xml
  addons/analytic/models/analytic_account.py
  addons/event/controllers/main.py
  addons/l10n_din5008/i18n/de.po
  addons/l10n_din5008_repair/models/repair.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/mail/static/src/components/thread_view/thread_view.xml
  addons/mail/static/tests/qunit_suite_tests/components/call_settings_menu_tests.js
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/static/src/mrp_forecasted/forecasted_buttons.js
  addons/onboarding/views/onboarding_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/fields/daterange/daterange_field.js
  addons/web/static/src/views/fields/image/image_field.xml
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.scss
  addons/web/static/src/views/fields/many2many_tags_avatar/many2many_tags_avatar_field.scss
  addons/web/static/src/views/fields/many2one_avatar/many2one_avatar_field.xml
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/form/form_controller.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/kanban/kanban_record_quick_create.xml
  addons/web/static/src/views/utils.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/fields/daterange_field_tests.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web/static/tests/views/fields/many2one_avatar_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/ir_module_module.py
  doc/cla/corporate/acsone.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/views/res_country_views.xml
  odoo/models.py
Labels: 16.0

#19072 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_reconcile_model.py
  addons/event/controllers/main.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/mrp/models/mrp_unbuild.py
  addons/product/static/src/scss/report_label_sheet.scss
  addons/product_expiry/i18n/product_expiry.pot
  addons/product_expiry/report/report_lot_barcode.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/report/report_lot_barcode.xml
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/views/res_country_views.xml
Labels: saas-15.2

#19073 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/views/account_edi_proxy_user_views.xml
  addons/analytic/models/analytic_account.py
  addons/base_import/static/src/import_model.js
  addons/event/controllers/main.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_din5008/i18n/de.po
  addons/l10n_din5008_repair/models/repair.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/mail/static/src/components/thread_view/thread_view.xml
  addons/mail/static/tests/qunit_suite_tests/components/call_settings_menu_tests.js
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/mrp/models/mrp_unbuild.py
  addons/onboarding/views/onboarding_views.xml
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/lib/pdfjs/build/pdf.sandbox.js
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web/static/src/boot.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.scss
  addons/web/static/src/views/fields/many2many_tags_avatar/many2many_tags_avatar_field.scss
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/form/form_controller.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/kanban/kanban_record_quick_create.xml
  addons/web/static/src/views/utils.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/wysiwyg.js
  doc/cla/individual/cunivca.md
  doc/cla/individual/k700mx.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/views/res_country_views.xml
Labels: saas-16.1

#19077 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/views/account_edi_proxy_user_views.xml
  addons/analytic/models/analytic_account.py
  addons/base_import/static/src/import_model.js
  addons/event/controllers/main.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_din5008/i18n/de.po
  addons/l10n_din5008_repair/models/repair.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/mail/static/src/components/thread_view/thread_view.xml
  addons/mail/static/tests/qunit_suite_tests/components/call_settings_menu_tests.js
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/mrp/models/mrp_unbuild.py
  addons/onboarding/views/onboarding_views.xml
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/lib/pdfjs/build/pdf.sandbox.js
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web/static/src/boot.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.scss
  addons/web/static/src/views/fields/many2many_tags_avatar/many2many_tags_avatar_field.scss
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/form/form_controller.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/kanban/kanban_record_quick_create.xml
  addons/web/static/src/views/utils.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/wysiwyg.js
  doc/cla/individual/cunivca.md
  doc/cla/individual/k700mx.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/views/res_country_views.xml
Labels: staging.saas-16.1

#19079 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_reconcile_model.py
  addons/mail_client_extension/views/mail_client_extension_login.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_picking_return.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_snippets.py
  addons/website/views/assets.xml
Labels: staging.14.0

#19083 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_reconcile_model.py
  addons/event/controllers/main.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/mrp/models/mrp_unbuild.py
  addons/product/static/src/scss/report_label_sheet.scss
  addons/product_expiry/i18n/product_expiry.pot
  addons/product_expiry/report/report_lot_barcode.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/report/report_lot_barcode.xml
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_scrap_views.xml
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/views/res_country_views.xml
Labels: tmp.saas-15.2

#19084 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_proxy_client/__manifest__.py
  addons/account_edi_proxy_client/models/account_edi_proxy_user.py
  addons/account_edi_proxy_client/views/account_edi_proxy_user_views.xml
  addons/analytic/models/analytic_account.py
  addons/base_import/static/src/import_model.js
  addons/event/controllers/main.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_din5008/i18n/de.po
  addons/l10n_din5008_repair/models/repair.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/mail/static/src/components/thread_view/thread_view.xml
  addons/mail/static/tests/qunit_suite_tests/components/call_settings_menu_tests.js
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_mailing_schedule_date.py
  addons/mrp/models/mrp_unbuild.py
  addons/onboarding/views/onboarding_views.xml
  addons/point_of_sale/static/src/js/Misc/AbstractReceiptScreen.js
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/printers.js
  addons/pos_epson_printer/i18n/pos_epson_printer.pot
  addons/pos_epson_printer/static/src/js/printers.js
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/sale/i18n/sale.pot
  addons/sale/models/sale_order.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/lib/pdfjs/build/pdf.sandbox.js
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web/static/src/boot.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.scss
  addons/web/static/src/views/fields/many2many_tags_avatar/many2many_tags_avatar_field.scss
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/form/form_controller.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/kanban/kanban_record_quick_create.xml
  addons/web/static/src/views/utils.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/wysiwyg.js
  doc/cla/individual/cunivca.md
  doc/cla/individual/k700mx.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_form_create.py
  odoo/addons/base/views/res_country_views.xml
Labels: tmp.saas-16.1

#19086 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_reconcile_model.py
  addons/mail_client_extension/views/mail_client_extension_login.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_picking_return.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_snippets.py
  addons/website/views/assets.xml
Labels: tmp.14.0

#19087 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_journal.py
  addons/account/models/account_reconcile_model.py
  addons/account_edi/tests/common.py
  addons/event/controllers/main.py
  addons/mail/controllers/discuss.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/mail_plugin/views/mail_plugin_login.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/data/website_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_ir_cron.py
Labels: tmp.15.0

#19092 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
Labels: master

#19093 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/views/account_reconcile_model_views.xml
Labels: saas-15.2

#19094 Syncing from upstream odoo/odoo (saas-16.1)
  addons/project/models/project.py
Labels: saas-16.1

#19095 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_journal.py
Labels: saas-16.2

#19098 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/project/models/project.py
Labels: staging.saas-16.1

#19102 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/views/account_reconcile_model_views.xml
Labels: tmp.saas-15.2

#19103 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/project/models/project.py
Labels: tmp.saas-16.1

#19104 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_journal.py
Labels: tmp.saas-16.2

#19106 Syncing from upstream odoo/odoo (master)
  addons/web_editor/controllers/main.py
Labels: master

#19118 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account_fleet/models/fleet_vehicle.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media_dialog.js
Labels: 14.0

#19119 Syncing from upstream odoo/odoo (15.0)
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_coupon/static/src/js/tours/PosCoupon5.tour.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/web/static/src/webclient/webclient.scss
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_snippets.py
Labels: 15.0

#19122 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_holidays/static/src/js/float_without_trailing_zeros.js
  addons/hr_holidays/views/hr_leave_accrual_views.xml
  addons/mail_plugin/views/mail_plugin_login.xml
  addons/point_of_sale/models/stock_picking.py
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_picking_return.py
  addons/website/static/src/snippets/s_social_media/options.js
Labels: saas-15.2

#19133 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_accrual_plan_level.py
  addons/hr_holidays/static/src/js/float_without_trailing_zeros.js
  addons/hr_holidays/views/hr_leave_accrual_views.xml
  addons/mail_plugin/views/mail_plugin_login.xml
  addons/point_of_sale/models/stock_picking.py
  addons/pos_mercury/models/pos_mercury_transaction.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_picking_return.py
  addons/website/static/src/snippets/s_social_media/options.js
Labels: tmp.saas-15.2
