Repository brain-tec/odoo, pull requests merged in 2023-10, with the labels that each got.

#23303 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/l10n_in_edi/models/account_edi_format.py
Labels: staging.saas-16.1

#23304 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/l10n_in_edi/models/account_edi_format.py
Labels: staging.saas-16.2

#23310 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/partner.py
Labels: tmp.saas-15.2

#23311 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/l10n_in_edi/models/account_edi_format.py
Labels: tmp.saas-16.1

#23312 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/l10n_in_edi/models/account_edi_format.py
Labels: tmp.saas-16.2

#23313 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/l10n_in_edi/models/account_edi_format.py
Labels: tmp.saas-16.4

#23314 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.15.0

#23316 Syncing from upstream odoo/odoo (saas-16.1)
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
Labels: saas-16.1

#23317 Syncing from upstream odoo/odoo (saas-16.2)
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
Labels: saas-16.2

#23318 Syncing from upstream odoo/odoo (saas-16.3)
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
Labels: saas-16.3

#23334 Syncing from upstream odoo/odoo (14.0)
  addons/auth_password_policy/data/defaults.xml
  addons/base_vat/models/res_partner.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: 14.0

#23335 Syncing from upstream odoo/odoo (15.0)
  addons/digest/models/digest.py
  addons/iap/models/iap_account.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: 15.0

#23336 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/partner.py
  addons/auth_password_policy/data/defaults.xml
  addons/mail/models/res_partner.py
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sale_project/models/project.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_partner.py
Labels: 16.0

#23338 Syncing from upstream odoo/odoo (saas-15.2)
  addons/auth_password_policy/data/defaults.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: saas-15.2

#23339 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/hr_attendance/static/src/js/kiosk_confirm.js
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/web/static/tests/views/fields/image_url_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: saas-16.1

#23340 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/bg.po
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/base_automation/i18n/bg.po
  addons/bus/websocket.py
  addons/crm/i18n/bg.po
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/lunch/i18n/bg.po
  addons/mrp/i18n/bg.po
  addons/note/i18n/bg.po
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/stock/i18n/bg.po
  addons/stock/models/stock_lot.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: saas-16.2

#23341 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_es_edi_facturae/data/signature_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_in_invoice_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_signed_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_edi_facturae/xml_utils.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/views/fields/state_selection/state_selection_field.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: saas-16.3

#23342 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account_payment/controllers/portal.py
  addons/account_peppol/i18n/account_peppol.pot
  addons/account_peppol/views/res_config_settings_views.xml
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_es_edi_facturae/data/signature_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_in_invoice_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_signed_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_edi_facturae/xml_utils.py
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/product_expiry/models/stock_move.py
  addons/product_expiry/tests/test_stock_lot.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/web/__manifest__.py
  addons/web/static/src/legacy/js/libs/bootstrap.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.xml
  addons/web/static/tests/core/domain_selector_dialog_tests.js
  addons/web/static/tests/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/snippets.xml
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: saas-16.4

#23345 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/web/static/tests/views/fields/image_url_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: staging.saas-16.1

#23346 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/i18n/bg.po
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/base_automation/i18n/bg.po
  addons/bus/websocket.py
  addons/crm/i18n/bg.po
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/lunch/i18n/bg.po
  addons/mrp/i18n/bg.po
  addons/note/i18n/bg.po
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/stock/i18n/bg.po
  addons/stock/models/stock_lot.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: staging.saas-16.2

#23349 Syncing from upstream odoo/odoo (staging.14.0)
  addons/auth_password_policy/data/defaults.xml
  addons/base_vat/models/res_partner.py
  odoo/addons/base/models/res_partner.py
Labels: staging.14.0

#23353 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/auth_password_policy/data/defaults.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: tmp.saas-15.2

#23354 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/hr_attendance/static/src/js/kiosk_confirm.js
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/web/static/tests/views/fields/image_url_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: tmp.saas-16.1

#23355 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/bg.po
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/base_automation/i18n/bg.po
  addons/bus/websocket.py
  addons/crm/i18n/bg.po
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/lunch/i18n/bg.po
  addons/mrp/i18n/bg.po
  addons/note/i18n/bg.po
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/stock/i18n/bg.po
  addons/stock/models/stock_lot.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: tmp.saas-16.2

#23356 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account_payment/controllers/portal.py
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_es_edi_facturae/data/signature_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_in_invoice_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_signed_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_edi_facturae/xml_utils.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/views/fields/state_selection/state_selection_field.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: tmp.saas-16.3

#23357 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account_payment/controllers/portal.py
  addons/account_peppol/i18n/account_peppol.pot
  addons/account_peppol/views/res_config_settings_views.xml
  addons/auth_password_policy/data/defaults.xml
  addons/bus/websocket.py
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_es_edi_facturae/data/signature_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_in_invoice_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_signed_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_edi_facturae/xml_utils.py
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/product_expiry/models/stock_move.py
  addons/product_expiry/tests/test_stock_lot.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/web/__manifest__.py
  addons/web/static/src/legacy/js/libs/bootstrap.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.xml
  addons/web/static/tests/core/domain_selector_dialog_tests.js
  addons/web/static/tests/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/snippets.xml
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/http.py
Labels: tmp.saas-16.4

#23359 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/digest/models/digest.py
  addons/iap/models/iap_account.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: tmp.15.0

#23360 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/partner.py
  addons/auth_password_policy/data/defaults.xml
  addons/mail/models/res_partner.py
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sale_project/models/project.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event_track/static/src/js/website_event_pwa_widget.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.16.0

#23361 Syncing from upstream odoo/odoo (14.0)
  addons/crm/report/crm_activity_report_views.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
Labels: 14.0

#23362 Syncing from upstream odoo/odoo (15.0)
  addons/auth_password_policy/data/defaults.xml
  addons/base_vat/models/res_partner.py
  addons/calendar/models/calendar_event.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/mail/models/mail_thread.py
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon_delivery/models/sale_coupon_program.py
  addons/sms/models/sms_sms.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: 15.0

#23363 Syncing from upstream odoo/odoo (16.0)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/base_vat/models/res_partner.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/digest/models/digest.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/l10n_br/models/res_partner.py
  addons/lunch/tests/common.py
  addons/mail/static/tests/qunit_suite_tests/webclient/commands/mail_providers_tests.js
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/sale/report/sale_report_views.xml
  addons/sms/models/sms_sms.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website_sale/controllers/main.py
  odoo/api.py
Labels: 16.0

#23365 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/sms/models/sms_sms.py
Labels: saas-15.2

#23366 Syncing from upstream odoo/odoo (saas-16.1)
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/tests/common.py
  addons/mail/models/res_partner.py
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: saas-16.1

#23367 Syncing from upstream odoo/odoo (saas-16.2)
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/tests/common.py
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: saas-16.2

#23368 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/bg.po
  addons/base_automation/i18n/bg.po
  addons/calendar/models/calendar_event.py
  addons/crm/i18n/bg.po
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/i18n/bg.po
  addons/lunch/tests/common.py
  addons/mail/static/src/web/activity/activity.js
  addons/mail/static/src/web/activity/activity.xml
  addons/mrp/i18n/bg.po
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/project_purchase/models/project_project.py
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/sms/models/sms_sms.py
  addons/stock/i18n/bg.po
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.xml
  addons/web/static/src/core/popover/popover.js
  addons/web/static/src/core/popover/popover.scss
  addons/web/static/src/core/popover/popover_service.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/search/search_bar_menu/search_bar_menu.xml
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/helpers/utils.js
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: saas-16.3

#23369 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/partner.py
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_it_edi/models/res_config_settings.py
  addons/lunch/tests/common.py
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/point_of_sale/models/pos_session.py
  addons/repair/tests/test_repair.py
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.xml
  addons/web/static/src/core/popover/popover.js
  addons/web/static/src/core/popover/popover.scss
  addons/web/static/src/core/popover/popover_service.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/search/search_bar_menu/search_bar_menu.xml
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/utils/objects_tests.js
  addons/web/static/tests/helpers/utils.js
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website_forum/i18n/website_forum.pot
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
  odoo/tools/mail.py
Labels: saas-16.4

#23372 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/tests/common.py
  addons/mail/models/res_partner.py
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: staging.saas-16.1

#23373 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/tests/common.py
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: staging.saas-16.2

#23376 Syncing from upstream odoo/odoo (staging.14.0)
  addons/crm/report/crm_activity_report_views.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
Labels: staging.14.0

#23380 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/sms/models/sms_sms.py
Labels: tmp.saas-15.2

#23381 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/tests/common.py
  addons/mail/models/res_partner.py
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: tmp.saas-16.1

#23382 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/tests/common.py
  addons/mail/static/src/components/message/message.xml
  addons/mail/static/src/components/message_in_reply_to_view/message_in_reply_to_view.xml
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/popover/popover.scss
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: tmp.saas-16.2

#23383 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/bg.po
  addons/base_automation/i18n/bg.po
  addons/calendar/models/calendar_event.py
  addons/crm/i18n/bg.po
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/lunch/i18n/bg.po
  addons/lunch/tests/common.py
  addons/mail/static/src/web/activity/activity.js
  addons/mail/static/src/web/activity/activity.xml
  addons/mrp/i18n/bg.po
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/project_purchase/models/project_project.py
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/sms/models/sms_sms.py
  addons/stock/i18n/bg.po
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.xml
  addons/web/static/src/core/popover/popover.js
  addons/web/static/src/core/popover/popover.scss
  addons/web/static/src/core/popover/popover_service.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/search/search_bar_menu/search_bar_menu.xml
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/helpers/utils.js
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
Labels: tmp.saas-16.3

#23384 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/partner.py
  addons/calendar/models/calendar_event.py
  addons/digest/models/digest.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_it_edi/models/res_config_settings.py
  addons/lunch/tests/common.py
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/point_of_sale/models/pos_session.py
  addons/repair/tests/test_repair.py
  addons/sms/models/sms_sms.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.xml
  addons/web/static/src/core/popover/popover.js
  addons/web/static/src/core/popover/popover.scss
  addons/web/static/src/core/popover/popover_service.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/search/search_bar_menu/search_bar_menu.xml
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/utils/objects_tests.js
  addons/web/static/tests/helpers/utils.js
  addons/web/tests/test_session_info.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website_forum/i18n/website_forum.pot
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/res_partner.py
  odoo/api.py
  odoo/tools/mail.py
Labels: tmp.saas-16.4

#23385 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/crm/report/crm_activity_report_views.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
Labels: tmp.14.0

#23386 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/auth_password_policy/data/defaults.xml
  addons/base_vat/models/res_partner.py
  addons/calendar/models/calendar_event.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_attendee.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/mail/models/mail_thread.py
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon_delivery/models/sale_coupon_program.py
  addons/sms/models/sms_sms.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.15.0

#23387 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/base_vat/models/res_partner.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/digest/models/digest.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/l10n_br/models/res_partner.py
  addons/lunch/tests/common.py
  addons/mail/static/tests/qunit_suite_tests/webclient/commands/mail_providers_tests.js
  addons/mrp/models/mrp_unbuild.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/sale/report/sale_report_views.xml
  addons/sms/models/sms_sms.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website_sale/controllers/main.py
  odoo/api.py
Labels: tmp.16.0

#23389 Syncing from upstream odoo/odoo (15.0)
  addons/base_import/models/base_import.py
  addons/crm/report/crm_activity_report_views.xml
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/pos_sale/models/pos_order.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order.py
  addons/stock/models/stock_package_type.py
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/website/views/website_templates.xml
  addons/website_slides/static/src/js/slides_embed.js
Labels: 15.0

#23392 Syncing from upstream odoo/odoo (saas-15.2)
  addons/crm/report/crm_activity_report_views.xml
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon_delivery/models/sale_coupon_program.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_package_type.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/website_templates.xml
  addons/website_slides/static/src/js/slides_embed.js
Labels: saas-15.2

#23394 Syncing from upstream odoo/odoo (saas-16.2)
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hr_attendance/static/src/client_action/kiosk_confirm/kiosk_confirm.xml
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/point_of_sale/models/pos_order.py
  addons/stock/models/stock_lot.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_dropshipping/models/stock.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website_sale/controllers/main.py
  addons/website_slides/static/src/js/slides_embed.js
Labels: saas-16.2

#23395 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/messaging_service.js
  addons/mail/static/src/web/thread_service_patch.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/orm_service.js
  addons/web/static/tests/core/orm_service_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website_sale/controllers/main.py
Labels: saas-16.3

#23396 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_send.py
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mail/static/src/core/common/partner_compare.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/orm_service.js
  addons/web/static/tests/core/orm_service_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
Labels: saas-16.4

#23400 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hr_attendance/static/src/client_action/kiosk_confirm/kiosk_confirm.xml
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/point_of_sale/models/pos_order.py
  addons/stock/models/stock_lot.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_dropshipping/models/stock.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website_sale/controllers/main.py
  addons/website_slides/static/src/js/slides_embed.js
Labels: staging.saas-16.2

#23407 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/crm/report/crm_activity_report_views.xml
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/sale_coupon/models/coupon_program.py
  addons/sale_coupon_delivery/models/sale_coupon_program.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_package_type.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/website_templates.xml
  addons/website_slides/static/src/js/slides_embed.js
Labels: tmp.saas-15.2

#23409 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hr_attendance/static/src/client_action/kiosk_confirm/kiosk_confirm.xml
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/static/tests/qunit_suite_tests/components/chatter_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/composer_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/discuss_tests.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/point_of_sale/models/pos_order.py
  addons/stock/models/stock_lot.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_dropshipping/models/stock.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website_sale/controllers/main.py
  addons/website_slides/static/src/js/slides_embed.js
Labels: tmp.saas-16.2

#23410 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/messaging_service.js
  addons/mail/static/src/web/thread_service_patch.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/orm_service.js
  addons/web/static/tests/core/orm_service_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website_sale/controllers/main.py
Labels: tmp.saas-16.3

#23411 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_send.py
  addons/base_vat/models/res_partner.py
  addons/crm/report/crm_activity_report_views.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/six_payment_terminal.html
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mail/static/src/core/common/partner_compare.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mrp/static/src/components/mo_overview_components_block/mrp_mo_overview_components_block.js
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/orm_service.js
  addons/web/static/tests/core/orm_service_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
Labels: tmp.saas-16.4

#23412 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/website_slides/static/src/js/slides_embed.js
Labels: tmp.14.0

#23413 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_import/models/base_import.py
  addons/crm/report/crm_activity_report_views.xml
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_mx/data/account_tax_data.xml
  addons/pos_sale/models/pos_order.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order.py
  addons/stock/models/stock_package_type.py
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/website/views/website_templates.xml
  addons/website_slides/static/src/js/slides_embed.js
Labels: tmp.15.0

#23415 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ch/models/res_bank.py
Labels: 14.0

#23416 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_ar/tests/common.py
  addons/project/static/tests/tours/project_update_tour_tests.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/stock/report/product_templates.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/toggleList.js
  addons/web_editor/static/lib/odoo-editor/src/style.css
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/fontAwesome.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/fields.py
Labels: 15.0

#23417 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_report.py
  addons/base_import/models/base_import.py
  addons/http_routing/models/ir_http.py
  addons/point_of_sale/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale_project/models/sale_order.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/core/network/download.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: 16.0

#23419 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_import/models/base_import.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
Labels: saas-15.2

#23420 Syncing from upstream odoo/odoo (saas-16.1)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/models/fleet_vehicle_tag.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/http_routing/models/ir_http.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: saas-16.1

#23421 Syncing from upstream odoo/odoo (saas-16.2)
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/http_routing/models/ir_http.py
  addons/mail/static/tests/qunit_suite_tests/webclient/commands/mail_providers_tests.js
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: saas-16.2

#23422 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/core_ui/message_in_reply.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_traceability.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_tour/static/src/tour_pointer/tour_pointer.js
  addons/web_tour/static/src/tour_pointer/tour_pointer.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: saas-16.3

#23423 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_dk_oioubl/models/account_move.py
  addons/l10n_dk_oioubl/tests/test_files/external/ADVORD_01_01_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_files/external/ADVORD_02_02_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_files/external/ADVORD_03_03_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_files/external/BASPRO_01_01_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_xml_oioubl_dk.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/src/core/web/chatter.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_traceability.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_tour/static/src/tour_pointer/tour_pointer.js
  addons/web_tour/static/src/tour_pointer/tour_pointer.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: saas-16.4

#23426 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/models/fleet_vehicle_tag.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/http_routing/models/ir_http.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: staging.saas-16.1

#23427 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/http_routing/models/ir_http.py
  addons/mail/static/tests/qunit_suite_tests/webclient/commands/mail_providers_tests.js
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: staging.saas-16.2

#23430 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_ch/models/res_bank.py
Labels: staging.14.0

#23434 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_import/models/base_import.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/web_editor/models/ir_qweb.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
Labels: tmp.saas-15.2

#23435 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/models/fleet_vehicle_tag.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/http_routing/models/ir_http.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: tmp.saas-16.1

#23436 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/http_routing/models/ir_http.py
  addons/mail/static/tests/qunit_suite_tests/webclient/commands/mail_providers_tests.js
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: tmp.saas-16.2

#23437 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/core_ui/message_in_reply.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_traceability.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_tour/static/src/tour_pointer/tour_pointer.js
  addons/web_tour/static/src/tour_pointer/tour_pointer.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: tmp.saas-16.3

#23438 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/google_calendar/utils/google_calendar.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_dk_oioubl/models/account_move.py
  addons/l10n_dk_oioubl/tests/test_files/external/ADVORD_01_01_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_files/external/ADVORD_02_02_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_files/external/ADVORD_03_03_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_files/external/BASPRO_01_01_00_Invoice_v2p1.xml
  addons/l10n_dk_oioubl/tests/test_xml_oioubl_dk.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/src/core/web/chatter.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_traceability.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/report/sale_report_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_tour/static/src/tour_pointer/tour_pointer.js
  addons/web_tour/static/src/tour_pointer/tour_pointer.xml
  addons/web_tour/static/src/tour_service/tour_pointer_state.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website/views/website_templates.xml
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: tmp.saas-16.4

#23439 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_ch/models/res_bank.py
Labels: tmp.14.0

#23440 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_ar/tests/common.py
  addons/project/static/tests/tours/project_update_tour_tests.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/stock/report/product_templates.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/toggleList.js
  addons/web_editor/static/lib/odoo-editor/src/style.css
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/fontAwesome.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/fields.py
Labels: tmp.15.0

#23441 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_report.py
  addons/base_import/models/base_import.py
  addons/http_routing/models/ir_http.py
  addons/point_of_sale/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale_project/models/sale_order.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/core/network/download.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/website_sale_comparison/i18n/website_sale_comparison.pot
  addons/website_sale_comparison/views/snippets.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
Labels: tmp.16.0

#23442 Syncing from upstream odoo/odoo (14.0)
  addons/maintenance/models/maintenance.py
  doc/cla/corporate/camptocamp.md
Labels: 14.0

#23443 Syncing from upstream odoo/odoo (15.0)
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  doc/cla/corporate/camptocamp.md
Labels: 15.0

#23444 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_invoice_send.py
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/tests/test_print_check.py
  addons/hr/views/hr_employee_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/fields.py
Labels: 16.0

#23446 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_ar/tests/common.py
  addons/l10n_ch/models/res_bank.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/stock/report/product_templates.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  odoo/fields.py
Labels: saas-15.2

#23447 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/tests/test_print_check.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/snailmail/static/tests/qunit_suite_tests/components/message_tests.js
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/website_slides/static/src/js/slides_embed.js
  odoo/fields.py
Labels: saas-16.1

#23448 Syncing from upstream odoo/odoo (saas-16.2)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  odoo/fields.py
Labels: saas-16.2

#23449 Syncing from upstream odoo/odoo (saas-16.3)
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_skills/static/src/fields/resume_one2many.scss
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mail/static/tests/web/command_palette_tests.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_project/models/sale_order.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/stock/report/product_templates.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
Labels: saas-16.3

#23450 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_tax.py
  addons/account/tests/test_multivat.py
  addons/hr_attendance/static/src/client_action/kiosk_confirm/kiosk_confirm.xml
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/src/discuss/core/common/discuss_core_common_service.js
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/stock/report/product_templates.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/i18n/website_forum.pot
  addons/website_forum/static/src/js/website_forum.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/controllers/main.py
Labels: saas-16.4

#23454 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  odoo/fields.py
Labels: staging.saas-16.2

#23457 Syncing from upstream odoo/odoo (staging.14.0)
  addons/maintenance/models/maintenance.py
  doc/cla/corporate/camptocamp.md
Labels: staging.14.0

#23461 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_ar/tests/common.py
  addons/l10n_ch/models/res_bank.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/stock/report/product_templates.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  odoo/fields.py
Labels: tmp.saas-15.2

#23462 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/tests/test_print_check.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/snailmail/static/tests/qunit_suite_tests/components/message_tests.js
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/website_slides/static/src/js/slides_embed.js
  odoo/fields.py
Labels: tmp.saas-16.1

#23463 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_service.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  odoo/fields.py
Labels: tmp.saas-16.2

#23464 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_skills/static/src/fields/resume_one2many.scss
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mail/static/tests/web/command_palette_tests.js
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_project/models/sale_order.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/stock/report/product_templates.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
Labels: tmp.saas-16.3

#23465 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_tax.py
  addons/account/tests/test_multivat.py
  addons/hr_attendance/static/src/client_action/kiosk_confirm/kiosk_confirm.xml
  addons/l10n_mx/data/template/account.tax-mx.csv
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/src/discuss/core/common/discuss_core_common_service.js
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/sale_stock/models/sale_order_line.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/stock/report/product_templates.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/i18n/website_forum.pot
  addons/website_forum/static/src/js/website_forum.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/controllers/main.py
Labels: tmp.saas-16.4

#23466 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/maintenance/models/maintenance.py
  doc/cla/corporate/camptocamp.md
Labels: tmp.14.0

#23467 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  doc/cla/corporate/camptocamp.md
Labels: tmp.15.0

#23468 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/wizard/account_invoice_send.py
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/tests/test_print_check.py
  addons/hr/views/hr_employee_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/change_production_qty.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/models/stock_move_line.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/change_production_qty.py
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/stock/models/stock_move.py
  addons/stock/report/product_templates.xml
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/py_js/py_date.js
  addons/web/static/src/webclient/loading_indicator/loading_indicator.js
  addons/web/static/tests/core/py_js/py_date_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  odoo/fields.py
Labels: tmp.16.0

#23476 Syncing from upstream odoo/odoo (saas-16.3)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: saas-16.3

#23480 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: staging.saas-16.1

#23481 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: staging.saas-16.2

#23486 Syncing from upstream odoo/odoo (tmp.master)
  addons/hr_holidays/tests/test_access_rights.py
Labels: tmp.master

#23487 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/maintenance/models/maintenance.py
Labels: tmp.saas-15.2

#23488 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: tmp.saas-16.1

#23489 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: tmp.saas-16.2

#23490 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: tmp.saas-16.3

#23491 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/l10n_br/models/res_partner.py
  addons/maintenance/models/maintenance.py
Labels: tmp.saas-16.4

#23492 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/maintenance/models/maintenance.py
Labels: tmp.15.0

#23493 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/maintenance/models/maintenance.py
Labels: tmp.16.0

#23499 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/uom.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/hr_holidays/models/hr_leave.py
  addons/iap/static/src/js/iap_buy_more_credits.js
  addons/web/static/tests/components/pager_tests.js
  addons/web/static/tests/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/helpers/test_utils_dom.js
  addons/web/static/tests/views/form_tests.js
  addons/web/static/tests/views/list_tests.js
Labels: 14.0

#23500 Syncing from upstream odoo/odoo (15.0)
  addons/event_sale/wizard/event_edit_registration.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/iap/static/src/js/iap_buy_more_credits.js
  addons/mail/models/mail_ice_server.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/sale_product_configurator/static/tests/tours/product_configurator_ui.js
  addons/web/static/tests/legacy/components/pager_tests.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/web/static/tests/legacy/fields/relational_fields/field_many2one_tests.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/legacy/helpers/test_utils_dom.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
Labels: 15.0

#23501 Syncing from upstream odoo/odoo (16.0)
  addons/auth_oauth/controllers/main.py
  addons/bus/websocket.py
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web/controllers/utils.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  doc/cla/individual/pallavisrivastavaa.md
  doc/cla/individual/trungtuan88.md
  odoo/addons/test_lint/tests/eslintrc
  odoo/http.py
Labels: 16.0

#23503 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/iap/static/src/js/iap_buy_more_credits.js
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/project/static/tests/tours/project_update_tour_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/toggleList.js
  addons/web_editor/static/lib/odoo-editor/src/style.css
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/fontAwesome.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/insertHTML.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
Labels: saas-15.2

#23504 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/wizard/account_invoice_send.py
  addons/auth_oauth/controllers/main.py
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/web/controllers/utils.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  doc/cla/individual/pallavisrivastavaa.md
  doc/cla/individual/trungtuan88.md
  odoo/addons/test_lint/tests/eslintrc
  odoo/http.py
Labels: saas-16.1

#23506 Syncing from upstream odoo/odoo (saas-16.3)
  addons/auth_oauth/controllers/main.py
  addons/calendar/data/mail_template_data.xml
  addons/hr_attendance/static/src/client_action/kiosk_confirm/kiosk_confirm.xml
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/web/chatter_tests.js
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_order.py
  addons/project/models/project_task.py
  addons/project/views/project_task_views.xml
  addons/snailmail/static/tests/message/message_patch_tests.js
  addons/web/controllers/utils.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/individual/pallavisrivastavaa.md
  doc/cla/individual/trungtuan88.md
  odoo/http.py
Labels: saas-16.3

#23507 Syncing from upstream odoo/odoo (saas-16.4)
  addons/auth_oauth/controllers/main.py
  addons/calendar/data/mail_template_data.xml
  addons/fleet/i18n/fleet.pot
  addons/fleet/models/fleet_vehicle.py
  addons/hr_skills/static/src/fields/resume_one2many.scss
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/l10n_fr/demo/demo_company.xml
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mail/static/tests/discuss/core/web/command_palette_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/project/models/project_task.py
  addons/project/views/project_task_views.xml
  addons/project_timesheet_holidays/models/hr_employee.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale/data/mail_template_data.xml
  addons/sale_project/i18n/sale_project.pot
  addons/sale_project/models/sale_order.py
  addons/test_mail/tests/test_mail_message.py
  addons/web/controllers/utils.py
  addons/web/static/src/search/search_panel/search_panel.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/tests/search/search_panel_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/website_forum/views/forum_forum_templates_tools.xml
  doc/cla/individual/pallavisrivastavaa.md
  doc/cla/individual/trungtuan88.md
  odoo/addons/base/tests/test_ir_model.py
  odoo/http.py
  odoo/models.py
Labels: saas-16.4

#23498 [bt#24091][FIX] account: enable correct onchange
  addons/account/models/account_move.py
Labels: 15.0.project_sv_559

#23526 Syncing from upstream odoo/odoo (14.0)
  doc/cla/individual/mikolodz.md
Labels: 14.0

#23527 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/models/__init__.py
  addons/hr_holidays_attendance/models/hr_attendance.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
Labels: 15.0

#23530 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/mail/models/mail_ice_server.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/camptocamp.md
Labels: saas-15.2

#23531 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_report.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_ar/report/invoice_report.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
Labels: saas-16.1

#23532 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_report.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/report/invoice_report.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/point_of_sale/models/report_sale_details.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/wizard/base_partner_merge.py
Labels: saas-16.2

#23534 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/views/account_analytic_line_views.xml
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/tests/test_print_check.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/im_livechat/views/rating_rating_views.xml
  addons/l10n_ar/report/invoice_report.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/models/mail_ice_server.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/models/report_sale_details.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/spreadsheet/static/src/data_sources/data_source.js
  addons/spreadsheet/static/src/pivot/pivot_data_source.js
  addons/spreadsheet/static/src/pivot/pivot_functions.js
  addons/spreadsheet/static/src/pivot/pivot_model.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/static/src/js/slides_embed.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
Labels: saas-16.4

#23537 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_report.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_ar/report/invoice_report.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
Labels: staging.saas-16.1

#23538 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_report.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/report/invoice_report.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/point_of_sale/models/report_sale_details.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/wizard/base_partner_merge.py
Labels: staging.saas-16.2

#23541 Syncing from upstream odoo/odoo (staging.14.0)
  doc/cla/individual/mikolodz.md
Labels: staging.14.0

#23545 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/mail/models/mail_ice_server.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/camptocamp.md
Labels: tmp.saas-15.2

#23546 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_report.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_ar/report/invoice_report.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
Labels: tmp.saas-16.1

#23547 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_report.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/report/invoice_report.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/point_of_sale/models/report_sale_details.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/wizard/base_partner_merge.py
Labels: tmp.saas-16.2

#23549 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account/tests/test_account_payment_register.py
  addons/account/views/account_analytic_line_views.xml
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_payment_register.py
  addons/account_check_printing/tests/test_print_check.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/bus/websocket.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/im_livechat/views/rating_rating_views.xml
  addons/l10n_ar/report/invoice_report.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/mail/models/mail_ice_server.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_routing.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/models/report_sale_details.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/spreadsheet/static/src/data_sources/data_source.js
  addons/spreadsheet/static/src/pivot/pivot_data_source.js
  addons/spreadsheet/static/src/pivot/pivot_functions.js
  addons/spreadsheet/static/src/pivot/pivot_model.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/static/src/js/slides_embed.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
Labels: tmp.saas-16.4

#23550 Syncing from upstream odoo/odoo (tmp.14.0)
  doc/cla/individual/mikolodz.md
Labels: tmp.14.0

#23551 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/models/__init__.py
  addons/hr_holidays_attendance/models/hr_attendance.py
  addons/sale_purchase/models/sale_order.py
  addons/sale_purchase/tests/test_sale_purchase.py
Labels: tmp.15.0

#23552 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/partner.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/event_sale/wizard/event_edit_registration.py
  addons/l10n_ar/report/invoice_report.py
  addons/l10n_ch/models/res_bank.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tools/__init__.py
  addons/mail/tools/credentials.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_ab_testing.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_restaurant/models/pos_config.py
  addons/project/models/project.py
  addons/sale/models/res_partner.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/tests/utils/pivot.js
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/webclient/actions/action_hook.js
  addons/web/static/tests/search/search_panel_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  doc/cla/corporate/acsone.md
  doc/cla/corporate/camptocamp.md
  doc/cla/individual/kevin11andrew.md
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.16.0

#23553 Syncing from upstream odoo/odoo (14.0)
  addons/base_vat/models/res_partner.py
Labels: 14.0

#23554 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_format.py
Labels: 15.0

#23555 Syncing from upstream odoo/odoo (16.0)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/account_payment_term_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/iap/data/neutralize.sql
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/spreadsheet/static/src/chart/odoo_chart/odoo_line_chart.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
Labels: 16.0

#23557 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/models/__init__.py
  addons/hr_holidays_attendance/models/hr_attendance.py
Labels: saas-15.2

#23558 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/account_payment_term_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ch/models/res_bank.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/base/models/ir_qweb.py
Labels: saas-16.1

#23559 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ch/models/res_bank.py
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp/tests/test_order.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/utils/pivot.js
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/fields/image_url_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/base/models/ir_qweb.py
Labels: saas-16.2

#23560 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_account_move_send.py
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/models/res_bank.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale/views/product_product_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/src/search/search_bar_menu/search_bar_menu.scss
  addons/web/static/src/search/search_bar_menu/search_bar_menu.xml
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event/__manifest__.py
  odoo/addons/base/models/ir_qweb.py
Labels: saas-16.3

#23561 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_report.py
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/mail_thread.py
  addons/mrp/tests/test_order.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale/views/product_product_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  odoo/addons/base/models/ir_qweb.py
Labels: saas-16.4

#23564 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/account_payment_term_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ch/models/res_bank.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/base/models/ir_qweb.py
Labels: staging.saas-16.1

#23565 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ch/models/res_bank.py
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp/tests/test_order.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/utils/pivot.js
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/fields/image_url_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/base/models/ir_qweb.py
Labels: staging.saas-16.2

#23567 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_vat/models/res_partner.py
Labels: staging.14.0

#23571 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/models/__init__.py
  addons/hr_holidays_attendance/models/hr_attendance.py
Labels: tmp.saas-15.2

#23572 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/account_payment_term_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ch/models/res_bank.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/backend/field_html.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.saas-16.1

#23573 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ch/models/res_bank.py
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp/tests/test_order.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/utils/pivot.js
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/fields/image_url_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.saas-16.2

#23574 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/account.pot
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_account_move_send.py
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/barcodes_gs1_nomenclature/__manifest__.py
  addons/barcodes_gs1_nomenclature/models/ir_http.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/barcodes_gs1_nomenclature/static/src/js/tests/barcode_parser_tests.js
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/models/res_bank.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale/views/product_product_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/src/search/search_bar_menu/search_bar_menu.scss
  addons/web/static/src/search/search_bar_menu/search_bar_menu.xml
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_event/__manifest__.py
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.saas-16.3

#23575 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_report.py
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/tests/__init__.py
  addons/account_edi_ubl_cii/tests/test_partner_peppol_fields.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/mail_thread.py
  addons/mrp/tests/test_order.py
  addons/pos_restaurant/static/src/js/Screens/BillScreen.js
  addons/sale/views/product_product_views.xml
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.saas-16.4

#23576 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_vat/models/res_partner.py
Labels: tmp.14.0

#23577 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_edi_format.py
Labels: tmp.15.0

#23578 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/account_payment_term_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/iap/data/neutralize.sql
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/spreadsheet/static/src/chart/odoo_chart/odoo_line_chart.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/views/form/form_label.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
Labels: tmp.16.0
