Repository brain-tec/odoo, pull requests merged in 2023-01, with the labels that each got.

#18140 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/l10n_ar/report/invoice_report_view.xml
  addons/mrp/models/product.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale/report/sale_report_views.xml
Labels: 14.0

#18141 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/static/src/js/time_off_calendar.js
  addons/l10n_ar/report/invoice_report_view.xml
  addons/mrp/models/product.py
  addons/mrp/views/mrp_production_views.xml
  addons/note/static/src/js/systray_activity_menu.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/pos_gift_card/static/src/js/PaymentScreen.js
  addons/pos_restaurant/static/src/js/Screens/ProductScreen/ControlButtons/PrintBillButton.js
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale/models/sale_order_line.py
  addons/sale/report/sale_report_views.xml
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_project/models/sale_order.py
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  odoo/addons/base/tests/test_mimetypes.py
  odoo/tools/mimetypes.py
Labels: 15.0

#18142 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_ar/report/invoice_report_view.xml
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_sg/__manifest__.py
  addons/l10n_sg/data/account_tax_data.xml
  addons/l10n_sg/data/account_tax_group_data.xml
  addons/l10n_sg/data/l10n_sg_chart_data.xml
  addons/l10n_sg/migrations/2.1/post-migrate_update_tax.py
  addons/mrp/models/product.py
  addons/mrp/views/mrp_production_views.xml
  addons/payment_razorpay/i18n/payment_razorpay.pot
  addons/payment_razorpay/models/payment_transaction.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/wizard/pos_session_check_product_wizard.xml
  addons/sale/models/product_product.py
  addons/sale/models/product_template.py
  addons/sale/report/sale_report_views.xml
  addons/spreadsheet/static/tests/global_filters/global_filters_chart_test.js
  addons/spreadsheet_dashboard_event_sale/data/files/events_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_controller_args.py
  addons/web/static/src/views/fields/translation_dialog.xml
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/src/views/widgets/attach_document/attach_document.js
  addons/web/static/src/views/widgets/attach_document/attach_document.xml
  addons/web/static/tests/helpers/mock_server.js
  addons/web/static/tests/mobile/views/form_view_tests.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/view_dialogs/select_create_dialog_tests.js
  addons/web/static/tests/views/widgets/attach_document_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website.py
  addons/website_sale/views/snippets/snippets.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/tests/test_mimetypes.py
  odoo/tools/mimetypes.py
Labels: 16.0

#18144 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/base_setup/static/src/xml/res_config_invite_users.xml
  addons/hr_holidays/models/hr_leave.py
  odoo/addons/base/tests/test_translate.py
  odoo/models.py
Labels: 14.0

#18145 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/delivery/models/__init__.py
  addons/delivery/models/stock_move.py
  addons/delivery/models/stock_picking.py
  addons/point_of_sale/models/pos_session.py
  addons/product_margin/models/product_product.py
Labels: 15.0

#18146 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_reconcile.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/views/hr_employee_public_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/analytic.py
  addons/hr_expense/tests/test_expenses.py
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models_data/emoji_data.js
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/sale/views/res_partner_views.xml
  addons/spreadsheet/static/src/helpers/constants.js
  addons/spreadsheet/static/src/pivot/pivot_model.js
  addons/spreadsheet/static/tests/pivots/model/pivot_positional_formula_test.js
  addons/spreadsheet_dashboard/tests/test_dashboard_data.py
  addons/spreadsheet_dashboard_hr_expense/data/files/expense_dashboard.json
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/spreadsheet_dashboard_sale/data/files/product_dashboard.json
  addons/spreadsheet_dashboard_sale/data/files/sales_dashboard.json
  addons/spreadsheet_dashboard_sale_expense/data/files/expense_dashboard.json
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/views/sample_server.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/webclient/actions/load_state_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  odoo/addons/base/data/res.lang.csv
Labels: 16.0

#18149 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal.py
  addons/l10n_be/data/account.account.template.csv
  addons/l10n_be/i18n_extra/de.po
  addons/l10n_be/i18n_extra/fr.po
  addons/l10n_be/i18n_extra/l10n_be.pot
  addons/l10n_be/i18n_extra/nl.po
  addons/l10n_cl/views/report_invoice.xml
  addons/payment_adyen_paybylink/models/payment_acquirer.py
  addons/payment_adyen_paybylink/utils.py
  addons/portal/views/portal_templates.xml
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale_timesheet/models/project.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_test_suite.py
Labels: 14.0

#18150 Syncing from upstream odoo/odoo (15.0)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/tests/tours/helpers/PaymentScreenTourMethods.js
  addons/pos_coupon/static/src/js/PaymentScreen.js
  addons/pos_coupon/static/src/js/tours/PosCoupon4.tour.js
  addons/pos_coupon/tests/test_frontend.py
  addons/project/views/project_views.xml
  addons/website/models/website_form.py
  addons/website/static/src/snippets/s_website_form/options.js
Labels: 15.0

#18152 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/views/hr_employee_public_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_org_chart/models/hr_employee.py
  addons/hr_org_chart/models/hr_org_chart_mixin.py
  addons/hr_org_chart/tests/__init__.py
  addons/hr_org_chart/tests/test_employee.py
  addons/l10n_fr/__init__.py
  addons/l10n_fr/__manifest__.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_fr/data/account.group.template.csv
  addons/l10n_fr/data/account_chart_template_data.xml
  addons/l10n_fr/data/account_fiscal_position_template_data.xml
  addons/l10n_fr/data/account_reconcile_model_template.xml
  addons/l10n_fr/data/account_tax_data.xml
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_fr/data/l10n_fr_chart_data.xml
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_fr/i18n/fr.po
  addons/l10n_fr/i18n/fr_CA.po
  addons/l10n_fr/i18n/l10n_fr.pot
  addons/l10n_fr/migrations/9.0.1.1/pre-set_tags_and_taxes_updatable.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models_data/emoji_data.js
  addons/product_margin/models/product_product.py
  addons/spreadsheet/static/src/helpers/constants.js
  addons/spreadsheet/static/src/helpers/odoo_functions_helpers.js
  addons/spreadsheet/static/src/list/list_helpers.js
  addons/spreadsheet/static/src/pivot/pivot_helpers.js
  addons/spreadsheet/static/src/pivot/pivot_model.js
  addons/spreadsheet/static/tests/pivots/model/pivot_positional_formula_test.js
  addons/spreadsheet_account/static/src/utils.js
  addons/spreadsheet_dashboard/tests/test_dashboard_data.py
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/views/sample_server.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/webclient/actions/load_state_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web_editor/tools.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/views/website_templates.xml
Labels: master

#18161 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_bank_statement.py
  addons/hr_presence/i18n/hr_presence.pot
  addons/hr_presence/models/hr_employee.py
  addons/l10n_fr/__manifest__.py
  addons/l10n_fr/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_gcc_pos/static/src/js/OrderReceipt.js
  addons/l10n_sa_pos/models/__init__.py
  addons/l10n_sa_pos/models/pos_config.py
  addons/l10n_sa_pos/static/src/js/OrderReceipt.js
  addons/repair/views/repair_views.xml
  addons/web/static/src/js/core/session.js
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/web/views/database_manager.html
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_partner.py
Labels: 14.0

#18162 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/chart_template.py
  addons/account/models/product.py
  addons/base_setup/static/src/xml/res_config_invite_users.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_fr/__manifest__.py
  addons/l10n_fr/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_gcc_pos/static/src/js/OrderReceipt.js
  addons/l10n_in_upi/__init__.py
  addons/l10n_in_upi/__manifest__.py
  addons/l10n_in_upi/models/__init__.py
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_in_upi/models/res_company.py
  addons/l10n_in_upi/views/res_company_views.xml
  addons/l10n_sa_pos/models/__init__.py
  addons/l10n_sa_pos/models/pos_config.py
  addons/l10n_sa_pos/static/src/js/models.js
  addons/mrp/models/stock_move.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/tests/common.py
  addons/portal/views/portal_templates.xml
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale_timesheet/models/account.py
  addons/stock/report/report_stock_forecasted.py
  addons/web/static/src/public/database_manager.qweb.html
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_share/000.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_mail.py
Labels: 15.0

#18172 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_journal.py
  addons/account/models/chart_template.py
  addons/base_setup/static/src/xml/res_config_invite_users.xml
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_fr/__manifest__.py
  addons/l10n_fr/migrations/2.1/post-migrate_update_taxes.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/OrderWidget.js
  addons/point_of_sale/tests/common.py
  addons/portal/views/portal_templates.xml
  addons/project/views/project_views.xml
  addons/web/static/src/public/database_manager.qweb.html
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/website_form.py
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_mail.py
Labels: tmp.saas-15.2

#18174 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_bank_statement.py
  addons/hr_presence/i18n/hr_presence.pot
  addons/hr_presence/models/hr_employee.py
  addons/l10n_fr/__manifest__.py
  addons/l10n_fr/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_gcc_pos/static/src/js/OrderReceipt.js
  addons/l10n_sa_pos/models/__init__.py
  addons/l10n_sa_pos/models/pos_config.py
  addons/l10n_sa_pos/static/src/js/OrderReceipt.js
  addons/repair/views/repair_views.xml
  addons/web/static/src/js/core/session.js
  addons/web/static/src/js/fields/field_utils.js
  addons/web/static/tests/fields/field_utils_tests.js
  addons/web/views/database_manager.html
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_partner.py
Labels: tmp.14.0

#18175 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/chart_template.py
  addons/account/models/product.py
  addons/base_setup/static/src/xml/res_config_invite_users.xml
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_fr/__manifest__.py
  addons/l10n_fr/migrations/2.1/post-migrate_update_taxes.py
  addons/l10n_gcc_pos/static/src/js/OrderReceipt.js
  addons/l10n_in_upi/__init__.py
  addons/l10n_in_upi/__manifest__.py
  addons/l10n_in_upi/models/__init__.py
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_in_upi/models/res_company.py
  addons/l10n_in_upi/views/res_company_views.xml
  addons/l10n_sa_pos/models/__init__.py
  addons/l10n_sa_pos/models/pos_config.py
  addons/l10n_sa_pos/static/src/js/models.js
  addons/mrp/models/stock_move.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/tests/common.py
  addons/portal/views/portal_templates.xml
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale_timesheet/models/account.py
  addons/stock/report/report_stock_forecasted.py
  addons/web/static/src/public/database_manager.qweb.html
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_share/000.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/test_mail.py
Labels: tmp.15.0

#18177 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_cn/models/account_move.py
  addons/mail/static/src/js/utils.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/payment/data/account_data.xml
  addons/purchase_stock/report/vendor_delay_report.py
  addons/purchase_stock/tests/test_purchase_stock_report.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/web/static/src/js/core/ajax.js
  addons/web/static/src/js/core/dialog.js
  addons/web/static/src/js/fields/relational_fields.js
  addons/web/static/src/scss/ui.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  doc/cla/individual/zyzcss.md
Labels: 14.0

#18180 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/views/report_invoice.xml
  addons/delivery/tests/test_carrier_propagation.py
  addons/hr_expense/models/account_move.py
  addons/hr_presence/i18n/hr_presence.pot
  addons/hr_presence/models/hr_employee.py
  addons/l10n_cn/models/account_move.py
  addons/l10n_fr_fec/tests/test_wizard.py
  addons/l10n_in_upi/__init__.py
  addons/l10n_in_upi/__manifest__.py
  addons/l10n_in_upi/models/__init__.py
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_in_upi/models/res_company.py
  addons/l10n_in_upi/views/res_company_views.xml
  addons/mail/models/ir_ui_view.py
  addons/mrp/models/stock_move.py
  addons/onboarding/models/onboarding_onboarding.py
  addons/onboarding/models/onboarding_step.py
  addons/onboarding/tests/test_onboarding.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/product_expiry/models/production_lot.py
  addons/product_expiry/tests/test_stock_lot.py
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase/views/res_config_settings_views.xml
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/repair/views/repair_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_warehouse.py
  addons/stock/report/report_stock_forecasted.py
  addons/stock/static/src/views/list/inventory_report_list_controller.js
  addons/stock/views/stock_quant_views.xml
  addons/website/data/ir_asset.xml
  addons/website/models/website.py
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/scss/compatibility/bs3_for_12_0.scss
  addons/website/static/tests/tours/page_manager.js
  addons/website/tests/__init__.py
  addons/website/tests/test_page_manager.py
  doc/cla/individual/zyzcss.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_test_suite.py
  odoo/addons/base/tests/test_views.py
Labels: master

#18185 Syncing from upstream odoo/odoo (master)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/sale_timesheet/models/account.py
Labels: master

#18186 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/models/res_company.py
  addons/l10n_ke_edi_tremol/static/src/js/send_invoice.js
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/l10n_ke_edi_tremol/views/report_invoice.xml
Labels: 15.0

#18188 Syncing from upstream odoo/odoo (master)
  addons/website/models/website_form.py
  addons/website/static/src/snippets/s_website_form/options.js
Labels: master

#18189 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/chart_template.py
  addons/account/tests/__init__.py
  addons/account/tests/test_chart_template.py
  addons/delivery/models/stock_picking.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/snailmail/models/snailmail_letter.py
Labels: 14.0

#18190 Syncing from upstream odoo/odoo (15.0)
  addons/crm_mail_plugin/controllers/crm_client.py
  addons/l10n_ke_edi_tremol/i18n/l10n_ke_edi_tremol.pot
  addons/mail/tests/test_mail_composer.py
  addons/mail/wizard/mail_compose_message.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/payment_adyen/static/src/scss/dropin.scss
  addons/purchase_stock/report/vendor_delay_report.py
  addons/purchase_stock/tests/test_purchase_stock_report.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/snailmail/models/snailmail_letter.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/legacy/js/core/dialog.js
  addons/web/static/src/legacy/js/core/profiling_qweb_view.js
  addons/web/static/src/legacy/scss/ace.scss
  addons/web/static/src/legacy/scss/ui.scss
  addons/web/static/tests/setup.js
  addons/website/models/website.py
Labels: 15.0

#18196 Syncing from upstream odoo/odoo (14.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/product/models/product_pricelist.py
  addons/product/tests/test_product_pricelist.py
  addons/website_forum/models/forum.py
Labels: 14.0

#18197 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/product.py
  addons/account/tests/__init__.py
  addons/account/tests/test_chart_template.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_eg_edi_eta/data/res_country_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/OrderWidget.js
  addons/pos_coupon/static/src/js/coupon.js
  addons/product/models/product_pricelist.py
  addons/product/tests/test_product_pricelist.py
  addons/web/static/src/legacy/js/core/ajax.js
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: 15.0

#18198 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/account_move_views.xml
  addons/bus/controllers/websocket.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/static/src/js/send_invoice.js
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/mail/tests/test_mail_composer.py
  addons/mail/wizard/mail_compose_message.py
  addons/payment_adyen/__manifest__.py
  addons/payment_adyen/static/src/scss/dropin.scss
  addons/point_of_sale/models/pos_order.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/debug/profiling/profiling_qweb.js
  addons/web/static/src/core/dialog/dialog.js
  addons/web/static/src/core/dialog/dialog.xml
  addons/web/static/src/core/notebook/notebook.js
  addons/web/static/src/core/notebook/notebook.xml
  addons/web/static/src/legacy/js/core/ajax.js
  addons/web/static/src/legacy/js/core/dialog.js
  addons/web/static/src/legacy/js/fields/field_utils.js
  addons/web/static/src/legacy/js/fields/relational_fields.js
  addons/web/static/src/legacy/scss/ace.scss
  addons/web/static/src/legacy/scss/ui.scss
  addons/web/static/src/views/fields/formatters.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/src/views/view_dialogs/select_create_dialog.xml
  addons/web/static/src/webclient/actions/action_dialog.xml
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/fields/formatters_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/models/website.py
Labels: 16.0

#18212 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/tests/test_frontend.py
  addons/survey/controllers/main.py
  addons/survey/views/survey_templates.xml
Labels: 14.0

#18213 Syncing from upstream odoo/odoo (15.0)
  addons/account_payment/controllers/payment.py
  addons/delivery/models/stock_picking.py
  addons/hr_attendance/models/hr_attendance.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/controllers/portal.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/tests/tours/edit_megamenu.js
  addons/website_forum/models/forum.py
  addons/website_payment/controllers/portal.py
  addons/website_sale/controllers/main.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
Labels: 15.0

#18219 Syncing from upstream odoo/odoo (staging.14.0)
  addons/point_of_sale/tests/test_frontend.py
  addons/survey/controllers/main.py
  addons/survey/views/survey_templates.xml
Labels: staging.14.0

#18222 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account_payment/controllers/payment.py
  addons/delivery/models/stock_picking.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/sale/controllers/portal.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/web/i18n/web.pot
  addons/web/static/src/legacy/js/core/ajax.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_forum/models/forum.py
  addons/website_payment/controllers/portal.py
  addons/website_sale/controllers/main.py
  addons/website_slides_survey/views/survey_survey_views.xml
Labels: tmp.saas-15.2

#18223 Syncing from upstream odoo/odoo (tmp.saas-15.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/delivery/models/stock_picking.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_restaurant/static/src/js/Screens/ProductScreen/ControlButtons/PrintBillButton.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_forum/models/forum.py
Labels: tmp.saas-15.3

#18224 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/point_of_sale/tests/test_frontend.py
  addons/survey/controllers/main.py
  addons/survey/views/survey_templates.xml
Labels: tmp.14.0

#18225 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_payment/controllers/payment.py
  addons/delivery/models/stock_picking.py
  addons/hr_attendance/models/hr_attendance.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/controllers/portal.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/tests/tours/edit_megamenu.js
  addons/website_forum/models/forum.py
  addons/website_payment/controllers/portal.py
  addons/website_sale/controllers/main.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
Labels: tmp.15.0

#18227 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/account_invoice.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/pos_sale/report/sale_report.py
  addons/sale/report/sale_report.py
  addons/sale_margin/report/sale_report.py
  addons/sale_stock/report/sale_report.py
  addons/website_sale/report/sale_report.py
Labels: 14.0

#18229 Syncing from upstream odoo/odoo (16.0)
  addons/calendar/static/src/views/attendee_calendar/attendee_calendar_model.js
  addons/event/data/mail_template_data.xml
  addons/event/i18n/event.pot
  addons/fleet/static/src/js/fleet_form.js
  addons/hr_attendance/models/hr_attendance.py
  addons/l10n_eg_edi_eta/data/res_country_data.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_nz/demo/demo_company.xml
  addons/purchase_price_diff/__init__.py
  addons/purchase_price_diff/__manifest__.py
  addons/purchase_price_diff/models/__init__.py
  addons/purchase_price_diff/models/account_move_line.py
  addons/purchase_price_diff/models/product.py
  addons/purchase_price_diff/views/product_views.xml
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/sale_product_configurator/controllers/main.py
  addons/spreadsheet_dashboard_pos_hr/data/files/pos_dashboard.json
  addons/survey/controllers/main.py
  addons/survey/views/survey_templates.xml
  addons/web/static/src/core/dialog/dialog.xml
  addons/web/static/src/legacy/scss/fields.scss
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/settings_form_view/settings_form_view.js
  addons/web/static/src/webclient/settings_form_view/settings_form_view.scss
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/models/res_users.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/edit_megamenu.js
  addons/website_payment/controllers/portal.py
  addons/website_slides/static/src/js/components/editor.js
  addons/website_slides_survey/views/survey_survey_views.xml
  doc/cla/individual/dvlazariev.md
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
  odoo/tools/translate.py
Labels: 16.0

#18231 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/google_calendar/models/res_users.py
  addons/l10n_cl/views/account_move_view.xml
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/project/static/src/css/project.css
  addons/purchase_stock/models/stock.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/fonts/mnmliconsv21-webfont.eot
  addons/web/static/src/fonts/mnmliconsv21-webfont.svg
  addons/web/static/src/fonts/mnmliconsv21-webfont.ttf
  addons/web/static/src/fonts/mnmliconsv21-webfont.woff
  addons/web/static/src/fonts/sign/OoohBaby-Regular-ofl.txt
  addons/web/static/src/fonts/sign/OoohBaby-Regular.ttf
  addons/web/static/src/fonts/sign/Rhesmanisa.ttf
  addons/website/__init__.py
  addons/website/models/assets.py
  addons/website/models/website.py
  debian/copyright
Labels: 14.0

#18232 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/account_invoice.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/error_codes.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/survey/static/src/fonts/AlexBrush-Regular-ofl.txt
  addons/survey/static/src/fonts/AlexBrush-Regular.ttf
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/common.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_image.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: 15.0

#18238 Syncing from upstream odoo/odoo (master)
  addons/l10n_in_edi/__manifest__.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/__init__.py
  addons/l10n_in_edi_ewaybill/__manifest__.py
  addons/l10n_in_edi_ewaybill/data/account_edi_data.xml
  addons/l10n_in_edi_ewaybill/data/ewaybill_type_data.xml
  addons/l10n_in_edi_ewaybill/demo/account_invoice_demo.xml
  addons/l10n_in_edi_ewaybill/demo/demo_company.xml
  addons/l10n_in_edi_ewaybill/demo/res_partner_demo.xml
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/__init__.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/l10n_in_edi_ewaybill/models/ewaybill_type.py
  addons/l10n_in_edi_ewaybill/models/res_company.py
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/security/ir.model.access.csv
  addons/l10n_in_edi_ewaybill/tests/__init__.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_json.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_in_edi_ewaybill/views/edi_pdf_report.xml
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
Labels: master

#18244 Syncing from upstream odoo/odoo (staging.13.0)
  addons/sale_stock/views/report_invoice.xml
Labels: staging.13.0

#18245 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/google_calendar/models/res_users.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/account_invoice.xml
  addons/l10n_cl/views/account_move_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/pos_sale/report/sale_report.py
  addons/project/static/src/css/project.css
  addons/purchase_stock/models/stock.py
  addons/sale/report/sale_report.py
  addons/sale_margin/report/sale_report.py
  addons/sale_stock/report/sale_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/fonts/mnmliconsv21-webfont.eot
  addons/web/static/src/fonts/mnmliconsv21-webfont.svg
  addons/web/static/src/fonts/mnmliconsv21-webfont.ttf
  addons/web/static/src/fonts/mnmliconsv21-webfont.woff
  addons/web/static/src/fonts/sign/OoohBaby-Regular-ofl.txt
  addons/web/static/src/fonts/sign/OoohBaby-Regular.ttf
  addons/web/static/src/fonts/sign/Rhesmanisa.ttf
  addons/website/__init__.py
  addons/website/models/assets.py
  addons/website/models/website.py
  addons/website_sale/report/sale_report.py
  debian/copyright
Labels: staging.14.0

#18248 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_holidays/report/hr_leave_reports.xml
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_eg_edi_eta/data/res_country_data.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_gcc_pos/static/src/js/OrderReceipt.js
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/l10n_sa_pos/models/__init__.py
  addons/l10n_sa_pos/models/pos_config.py
  addons/l10n_sa_pos/static/src/js/models.js
  addons/payment_stripe/models/payment_transaction.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_project_account/models/project.py
  addons/stock/models/stock_move.py
  addons/survey/controllers/main.py
  addons/survey/views/survey_templates.xml
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website/static/src/js/menu/edit.js
  addons/website/static/tests/tours/edit_megamenu.js
  addons/website_payment/controllers/portal.py
  odoo/addons/base/i18n/base.pot
Labels: tmp.saas-15.2

#18249 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/sale_stock/views/report_invoice.xml
Labels: tmp.13.0

#18250 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/google_calendar/models/res_users.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/account_invoice.xml
  addons/l10n_cl/views/account_move_view.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/pos_sale/report/sale_report.py
  addons/project/static/src/css/project.css
  addons/purchase_stock/models/stock.py
  addons/sale/report/sale_report.py
  addons/sale_margin/report/sale_report.py
  addons/sale_stock/report/sale_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/fonts/mnmliconsv21-webfont.eot
  addons/web/static/src/fonts/mnmliconsv21-webfont.svg
  addons/web/static/src/fonts/mnmliconsv21-webfont.ttf
  addons/web/static/src/fonts/mnmliconsv21-webfont.woff
  addons/web/static/src/fonts/sign/OoohBaby-Regular-ofl.txt
  addons/web/static/src/fonts/sign/OoohBaby-Regular.ttf
  addons/web/static/src/fonts/sign/Rhesmanisa.ttf
  addons/website/__init__.py
  addons/website/models/assets.py
  addons/website/models/website.py
  addons/website_sale/report/sale_report.py
  debian/copyright
Labels: tmp.14.0

#18251 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/account_invoice.xml
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/error_codes.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/IT00470550013_basis.xml
  addons/l10n_it_edi_sdicoop/tests/expected_xmls/reverse_charge_bill.xml
  addons/l10n_it_edi_sdicoop/tests/test_edi_xml.py
  addons/payment_stripe/models/payment_transaction.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_project_account/models/project.py
  addons/stock/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/survey/controllers/main.py
  addons/survey/static/src/fonts/AlexBrush-Regular-ofl.txt
  addons/survey/static/src/fonts/AlexBrush-Regular.ttf
  addons/survey/views/survey_templates.xml
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/xml/editor.xml
  addons/website_payment/controllers/portal.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/common.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_image.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: tmp.15.0

#18253 Syncing from upstream odoo/odoo (13.0)
  addons/sale_stock/views/report_invoice.xml
Labels: 13.0

#18254 Syncing from upstream odoo/odoo (14.0)
  addons/web/controllers/main.py
Labels: 14.0

#18255 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_cl/views/account_move_view.xml
  addons/pos_coupon/static/src/js/coupon.js
Labels: 15.0

#18256 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/product.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_early_payment_discount.py
  addons/auth_oauth/controllers/main.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/views/account_invoice.xml
  addons/l10n_cl/views/account_move_view.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/error_codes.py
  addons/mail/wizard/mail_template_preview_views.xml
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/product/views/product_pricelist_item_views.xml
  addons/project_timesheet_holidays/models/project_task.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/sms/wizard/sms_composer.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web/static/src/search/control_panel/control_panel.scss
  addons/web/static/src/views/form/control_panel/form_control_panel.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/settings_form_view/settings_form_view.scss
  addons/web/static/src/webclient/settings_form_view/settings_form_view.xml
  addons/web/static/src/webclient/user_menu/user_menu_items.js
  addons/web/static/src/webclient/user_menu/user_menu_items.xml
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/models/product_template.py
  addons/website_sale/models/website.py
  doc/cla/corporate/dynamic-business-group.md
  doc/cla/individual/Heshmatkhah.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/addons/base/views/ir_attachment_views.xml
  odoo/addons/base/views/ir_ui_view_views.xml
  odoo/addons/base/wizard/base_import_language.py
Labels: 16.0

#18267 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/hr/models/hr_job.py
  addons/hr_holidays/static/src/js/time_off_calendar_employee.js
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/note/models/note.py
  addons/project/models/project.py
  addons/purchase_stock/models/stock.py
  addons/stock_account/models/stock_move.py
  addons/web/controllers/main.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/__init__.py
  addons/website/models/assets.py
  addons/website/models/website.py
  odoo/tools/mail.py
Labels: 15.0

#18268 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/board/static/src/board_controller.scss
  addons/board/static/src/board_controller.xml
  addons/calendar/static/src/views/attendee_calendar/attendee_calendar_model.js
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.js
  addons/hr_recruitment/models/hr_recruitment.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/models/res_company.py
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/l10n_ke_edi_tremol/views/report_invoice.xml
  addons/mail/static/src/models/chatter.js
  addons/mail/static/tests/qunit_suite_tests/components/follower_tests.js
  addons/mrp_subcontracting/models/res_partner.py
  addons/mrp_subcontracting/models/stock_location.py
  addons/mrp_subcontracting/views/res_partner_views.xml
  addons/mrp_subcontracting/views/stock_location_views.xml
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/spreadsheet/static/src/o_spreadsheet/migration.js
  addons/spreadsheet/static/tests/migrations/migrations.js
  addons/stock/models/stock_move.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/survey/static/src/fonts/AlexBrush-Regular-ofl.txt
  addons/survey/static/src/fonts/AlexBrush-Regular.ttf
  addons/web/controllers/export.py
  addons/web/static/src/search/search_model.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/properties/properties_field.scss
  addons/web/static/src/views/fields/properties/property_definition.scss
  addons/web/static/src/views/fields/properties/property_definition.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/list/list_arch_parser.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/search/search_model_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/__init__.py
  addons/website/models/assets.py
  addons/website/models/website.py
Labels: 16.0

#18270 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/survey/static/src/fonts/AlexBrush-Regular-ofl.txt
  addons/survey/static/src/fonts/AlexBrush-Regular.ttf
  addons/web/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/__init__.py
  addons/website/models/assets.py
  addons/website/models/website.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/common.py
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_sale_image.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_slides/static/src/js/slides_course_fullscreen_player.js
Labels: tmp.saas-15.2

#18274 Syncing from upstream odoo/odoo (14.0)
  addons/im_livechat/models/mail_channel.py
  addons/pos_restaurant/views/pos_restaurant_views.xml
  addons/project/models/project.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/sale_stock/views/report_invoice.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
Labels: 14.0

#18275 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_gift_card/__manifest__.py
  addons/pos_gift_card/static/src/js/tours/PosGiftCardsTourMethods.js
  addons/pos_gift_card/static/src/js/tours/PosGiftCardstour.js
  addons/pos_gift_card/tests/__init__.py
  addons/pos_gift_card/tests/test_gift_card_promotion.py
  addons/pos_restaurant/models/pos_order.py
  addons/pos_restaurant/static/src/js/floors.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_sale_margin/report/sale_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/stock/views/stock_storage_category_views.xml
  addons/stock_account/views/report_invoice.xml
Labels: 15.0

#18276 Syncing from upstream odoo/odoo (16.0)
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_backend.scss
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.js
  addons/account/static/tests/section_and_note_tests.js
  addons/account/wizard/accrued_orders.py
  addons/board/static/src/board_controller.scss
  addons/board/static/tests/board_test.js
  addons/calendar/models/calendar_alarm_manager.py
  addons/l10n_gcc_pos/static/src/js/OrderReceipt.js
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_sa_pos/models/__init__.py
  addons/l10n_sa_pos/models/pos_config.py
  addons/l10n_sa_pos/static/src/js/models.js
  addons/mail/views/mail_activity_views.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_hr/static/src/js/PaymentScreen.js
  addons/purchase_requisition/i18n/purchase_requisition.pot
  addons/purchase_requisition/models/purchase_requisition.py
  addons/spreadsheet/static/src/data_sources/data_sources.js
  addons/spreadsheet/static/src/data_sources/metadata_repository.js
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/spreadsheet/static/tests/data_fetching/metadata_repository_test.js
  addons/spreadsheet/static/tests/utils/model.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/commands/default_providers.js
  addons/web/static/src/core/pager/pager.js
  addons/web/static/src/core/pager/pager.xml
  addons/web/static/src/search/control_panel/control_panel.scss
  addons/web/static/src/search/search_model.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/src/views/form/control_panel/form_control_panel.xml
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/settings_form_view/settings_form_view.scss
  addons/web/static/tests/core/commands/command_service_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/statusbar_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: 16.0

#18280 Syncing from upstream odoo/odoo (staging.14.0)
  addons/im_livechat/models/mail_channel.py
  addons/pos_restaurant/views/pos_restaurant_views.xml
  addons/project/models/project.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/sale_stock/views/report_invoice.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
Labels: staging.14.0

#18283 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/hr/models/hr_job.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/mrp_subcontracting_dropshipping/tests/__init__.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/note/models/note.py
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/project/models/project.py
  addons/purchase_stock/models/stock.py
  addons/stock_account/models/stock_move.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/tools/mail.py
Labels: tmp.saas-15.2

#18285 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/im_livechat/models/mail_channel.py
  addons/pos_restaurant/views/pos_restaurant_views.xml
  addons/project/models/project.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/sale_stock/views/report_invoice.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
Labels: tmp.14.0

#18286 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_gift_card/__manifest__.py
  addons/pos_gift_card/static/src/js/tours/PosGiftCardsTourMethods.js
  addons/pos_gift_card/static/src/js/tours/PosGiftCardstour.js
  addons/pos_gift_card/tests/__init__.py
  addons/pos_gift_card/tests/test_gift_card_promotion.py
  addons/pos_restaurant/models/pos_order.py
  addons/pos_restaurant/static/src/js/floors.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_sale_margin/report/sale_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/stock/views/stock_storage_category_views.xml
  addons/stock_account/views/report_invoice.xml
Labels: tmp.15.0

#18289 Syncing from upstream odoo/odoo (14.0)
  addons/calendar/models/calendar_event.py
  addons/mail/wizard/mail_compose_message.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/project/static/src/js/tours/project.js
  addons/sale_coupon/models/sale_order.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/test_mail/tests/test_mail_message.py
  addons/website_forum/controllers/main.py
  addons/website_forum/views/website_forum_profile.xml
  addons/website_profile/views/website_profile.xml
  odoo/addons/base/models/ir_attachment.py
Labels: 14.0

#18290 Syncing from upstream odoo/odoo (15.0)
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_holidays_calendar.py
  addons/pos_sale/__manifest__.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/sale_order_line.py
  addons/sale_mrp/models/sale.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  doc/cla/corporate/vauxoo.md
Labels: 15.0

#18293 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/chart_template.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account_data.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/migrations/5.1/post-migrate_update_taxes.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_workorder.py
  addons/pos_cache/static/src/js/pos_cache.js
  addons/sale/models/account_move.py
  addons/sale/models/sale.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/sale_purchase/models/sale_order.py
  addons/stock/models/stock_orderpoint.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: 14.0

#18294 Syncing from upstream odoo/odoo (15.0)
  addons/pos_coupon/static/src/js/coupon.js
  addons/pos_restaurant/views/pos_restaurant_views.xml
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/project/static/src/js/tours/project.js
  addons/sale/models/sale_order_line.py
  addons/sale_coupon/models/sale_order.py
  addons/sale_coupon/tests/test_program_numbers.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/fonts/mnmliconsv21-webfont.eot
  addons/web/static/fonts/mnmliconsv21-webfont.svg
  addons/web/static/fonts/mnmliconsv21-webfont.ttf
  addons/web/static/fonts/mnmliconsv21-webfont.woff
  addons/web/static/fonts/sign/OoohBaby-Regular-ofl.txt
  addons/web/static/fonts/sign/OoohBaby-Regular.ttf
  addons/web/static/fonts/sign/Rhesmanisa.ttf
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  debian/copyright
Labels: 15.0

#18302 Syncing from upstream odoo/odoo (15.0)
  addons/mail/models/ir_config_parameter.py
  addons/mail/tests/test_mail_render.py
Labels: 15.0

#18303 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_bo/__manifest__.py
  addons/l10n_bo/data/account.group.template.csv
  addons/l10n_eg_edi_eta/views/product_template_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/web/static/tests/webclient/helpers.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/static/src/scss/res_partner.scss
  odoo/addons/base/wizard/base_partner_merge_views.xml
Labels: 16.0

#18193 [bt#21068] fix outlook token 90 days
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
Labels: 10.0.project_th

#18316 Syncing from upstream odoo/odoo (15.0)
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_cost.py
  addons/purchase/models/purchase.py
  addons/sale/models/sale_order.py
  addons/sale_gift_card/models/sale_order.py
Labels: 15.0

#18317 Syncing from upstream odoo/odoo (16.0)
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/account_invoice.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/views/page_list.xml
  addons/website/static/src/components/views/page_views_mixin.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/wizard/website_robots.xml
Labels: 16.0

#18329 Syncing from upstream odoo/odoo (13.0)
  odoo/modules/migration.py
Labels: 13.0

#18330 Syncing from upstream odoo/odoo (14.0)
  addons/base_vat/models/res_partner.py
  addons/l10n_cl/data/res.country.csv
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.editor.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/res_country_data.xml
Labels: 14.0

#18331 Syncing from upstream odoo/odoo (15.0)
  addons/base_vat/models/res_partner.py
  addons/hr_recruitment_survey/models/survey_invite.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/static/src/css/restaurant.css
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  odoo/addons/base/data/res_country_data.xml
Labels: 15.0

#18332 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/res_users.py
  addons/hr_recruitment_survey/models/survey_invite.py
  addons/hr_work_entry/models/hr_work_entry.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/mail/static/src/models/chatter.js
  addons/mail/static/tests/qunit_suite_tests/widgets/form_renderer_tests.js
  addons/pos_restaurant/models/pos_order.py
  addons/project/static/src/components/project_control_panel/project_control_panel.js
  addons/purchase/models/purchase.py
  addons/sale_stock/models/sale_order.py
  addons/web/static/src/views/form/form_arch_parser.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/__init__.py
  addons/website/models/base_partner_merge.py
  addons/website/tests/test_website_visitor.py
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
Labels: 16.0

#18334 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_cost.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_holidays_calendar.py
  addons/hr_recruitment_survey/models/survey_invite.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/sale/models/sale_order.py
  addons/sale_gift_card/models/sale_order.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/data/res_country_data.xml
Labels: saas-15.2

#18339 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/modules/migration.py
Labels: staging.13.0

#18340 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_vat/models/res_partner.py
  addons/l10n_cl/data/res.country.csv
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.editor.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/res_country_data.xml
Labels: staging.14.0

#18343 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/models/sale_order.py
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_cost.py
  addons/hr_holidays/__manifest__.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_holidays_calendar.py
  addons/hr_recruitment_survey/models/survey_invite.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/sale/models/sale_order.py
  addons/sale_gift_card/models/sale_order.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.saas-15.2

#18345 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/modules/migration.py
Labels: tmp.13.0

#18346 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_vat/models/res_partner.py
  addons/l10n_cl/data/res.country.csv
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.editor.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.14.0

#18347 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_vat/models/res_partner.py
  addons/hr_recruitment_survey/models/survey_invite.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_restaurant/static/src/css/restaurant.css
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.15.0

#18349 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/stock_account/models/product.py
  odoo/modules/migration.py
Labels: 14.0

#18350 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/mass_mailing/data/mass_mailing_demo.xml
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mass_mailing_sale/data/mass_mailing_demo.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  odoo/modules/migration.py
Labels: 15.0

#18351 Syncing from upstream odoo/odoo (16.0)
  addons/account_payment_invoice_online_payment_patch/i18n/account_payment_extension.pot
  addons/account_payment_invoice_online_payment_patch/views/account_portal_templates.xml
  addons/bus/models/__init__.py
  addons/bus/models/ir_http.py
  addons/bus/static/src/services/bus_service.js
  addons/bus/static/tests/bus_tests.js
  addons/calendar/models/calendar_event.py
  addons/calendar/static/src/views/attendee_calendar/attendee_calendar_model.js
  addons/hr_recruitment/views/hr_job_views.xml
  addons/mail/models/ir_config_parameter.py
  addons/mail/tests/test_mail_render.py
  addons/mass_mailing/data/mass_mailing_demo.xml
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mass_mailing_sale/data/mass_mailing_demo.xml
  addons/mrp/models/mrp_workorder.py
  addons/mrp/static/src/widgets/timer.js
  addons/point_of_sale/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/sale/views/sale_order_views.xml
  addons/spreadsheet_dashboard_pos_hr/data/files/pos_dashboard.json
  addons/spreadsheet_dashboard_sale/data/files/product_dashboard.json
  addons/spreadsheet_dashboard_sale/data/files/sales_dashboard.json
  addons/spreadsheet_dashboard_sale/i18n/spreadsheet_dashboard_sale.pot
  addons/spreadsheet_dashboard_website_sale_slides/data/files/elearning_dashboard.json
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/modules/migration.py
Labels: 16.0

#18358 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/stock_account/models/product.py
  odoo/modules/migration.py
Labels: staging.14.0

#18361 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/mail/models/ir_config_parameter.py
  addons/mail/tests/test_mail_render.py
  addons/mass_mailing/data/mass_mailing_demo.xml
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mass_mailing_sale/data/mass_mailing_demo.xml
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/models/pos_order.py
  addons/purchase/models/purchase.py
  addons/sale_purchase/models/product_template.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/modules/migration.py
Labels: tmp.saas-15.2

#18363 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_rule.py
  addons/stock_account/models/product.py
  odoo/modules/migration.py
Labels: tmp.14.0

#18364 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/mass_mailing/data/mass_mailing_demo.xml
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/mass_mailing_sale/data/mass_mailing_demo.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  odoo/modules/migration.py
Labels: tmp.15.0

#18366 Syncing from upstream odoo/odoo (14.0)
  addons/base_setup/models/res_config_settings.py
  addons/l10n_eu_service/models/eu_tax_map.py
  addons/purchase_requisition/models/purchase.py
  addons/sale_management/models/digest.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
  odoo/addons/base/models/res_users.py
Labels: 14.0

#18367 Syncing from upstream odoo/odoo (15.0)
  addons/base_setup/models/res_config_settings.py
  addons/pos_sale/models/pos_order.py
  addons/stock_account/models/product.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
Labels: 15.0

#18370 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_setup/models/res_config_settings.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/stock_account/models/product.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: saas-15.2

#18375 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_setup/models/res_config_settings.py
  addons/l10n_eu_service/models/eu_tax_map.py
  addons/purchase_requisition/models/purchase.py
  addons/sale_management/models/digest.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
  odoo/addons/base/models/res_users.py
Labels: staging.14.0

#18378 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_setup/models/res_config_settings.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/stock_account/models/product.py
  addons/web/static/src/core/network/rpc_service.js
  addons/web/static/tests/core/network/rpc_service_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: tmp.saas-15.2

#18380 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_setup/models/res_config_settings.py
  addons/l10n_eu_service/models/eu_tax_map.py
  addons/purchase_requisition/models/purchase.py
  addons/sale_management/models/digest.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
  odoo/addons/base/models/res_users.py
Labels: tmp.14.0

#18381 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_setup/models/res_config_settings.py
  addons/pos_sale/models/pos_order.py
  addons/stock_account/models/product.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event_questions/tests/test_event_internals.py
Labels: tmp.15.0

#18386 Syncing from upstream odoo/odoo (master)
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/pager/pager.js
  addons/web/static/src/views/kanban/kanban_arch_parser.js
  addons/web/static/src/views/kanban/kanban_controller.js
  addons/web/static/src/views/list/list_arch_parser.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/core/pager_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  odoo/addons/base/rng/tree_view.rng
Labels: master

#18395 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_cl/data/res.country.csv
Labels: 15.0

#18396 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_cl/data/res.country.csv
  addons/website/models/ir_module_module.py
  addons/website/tests/test_views.py
Labels: 16.0

#18397 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/l10n_latam_invoice_document/views/account_move_view.xml
Labels: master

#18398 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/zh_TW.po
  addons/hr_expense/i18n/es_MX.po
  addons/hr_expense/i18n/it.po
  addons/hr_recruitment/i18n/nl.po
  addons/l10n_cl/data/res.country.csv
  addons/lunch/i18n/uk.po
  addons/mail/i18n/uk.po
  addons/mass_mailing/i18n/zh_TW.po
  addons/mrp_account/i18n/de.po
  addons/mrp_account/i18n/es.po
  addons/mrp_account/i18n/es_MX.po
  addons/mrp_account/i18n/fr.po
  addons/mrp_account/i18n/it.po
  addons/mrp_account/i18n/nl.po
  addons/mrp_account/i18n/uk.po
  addons/mrp_account/i18n/vi.po
  addons/mrp_account/i18n/zh_CN.po
  addons/mrp_account/i18n/zh_TW.po
  addons/portal/i18n/fr.po
  addons/product/i18n/es_MX.po
  addons/product/i18n/zh_TW.po
  addons/purchase/i18n/zh_TW.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/zh_TW.po
  addons/sale_timesheet/i18n/es_MX.po
  addons/sms/i18n/uk.po
  addons/stock/i18n/es.po
  addons/stock/i18n/es_MX.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/stock/i18n/zh_TW.po
  addons/stock_picking_batch/i18n/es.po
  addons/stock_picking_batch/i18n/zh_TW.po
  addons/web_editor/i18n/nl.po
  addons/website/i18n/de.po
  addons/website/i18n/es.po
  addons/website/i18n/es_MX.po
  addons/website/i18n/fr.po
  addons/website/i18n/it.po
  addons/website/i18n/nl.po
  addons/website/i18n/uk.po
  addons/website/i18n/vi.po
  addons/website/i18n/zh_CN.po
  addons/website/i18n/zh_TW.po
  addons/website_blog/i18n/it.po
  addons/website_event_track/i18n/fr.po
  addons/website_forum/i18n/nl.po
  addons/website_sale/i18n/zh_TW.po
  addons/website_sale_product_configurator/i18n/nl.po
  addons/website_slides/i18n/nl.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/uk.po
Labels: saas-15.2

#18405 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/zh_TW.po
  addons/hr_expense/i18n/es_MX.po
  addons/hr_expense/i18n/it.po
  addons/hr_recruitment/i18n/nl.po
  addons/l10n_cl/data/res.country.csv
  addons/lunch/i18n/uk.po
  addons/mail/i18n/uk.po
  addons/mass_mailing/i18n/zh_TW.po
  addons/mrp_account/i18n/de.po
  addons/mrp_account/i18n/es.po
  addons/mrp_account/i18n/es_MX.po
  addons/mrp_account/i18n/fr.po
  addons/mrp_account/i18n/it.po
  addons/mrp_account/i18n/nl.po
  addons/mrp_account/i18n/uk.po
  addons/mrp_account/i18n/vi.po
  addons/mrp_account/i18n/zh_CN.po
  addons/mrp_account/i18n/zh_TW.po
  addons/portal/i18n/fr.po
  addons/product/i18n/es_MX.po
  addons/product/i18n/zh_TW.po
  addons/purchase/i18n/zh_TW.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/zh_TW.po
  addons/sale_timesheet/i18n/es_MX.po
  addons/sms/i18n/uk.po
  addons/stock/i18n/es.po
  addons/stock/i18n/es_MX.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/stock/i18n/zh_TW.po
  addons/stock_picking_batch/i18n/es.po
  addons/stock_picking_batch/i18n/zh_TW.po
  addons/web_editor/i18n/nl.po
  addons/website/i18n/de.po
  addons/website/i18n/es.po
  addons/website/i18n/es_MX.po
  addons/website/i18n/fr.po
  addons/website/i18n/it.po
  addons/website/i18n/nl.po
  addons/website/i18n/uk.po
  addons/website/i18n/vi.po
  addons/website/i18n/zh_CN.po
  addons/website/i18n/zh_TW.po
  addons/website_blog/i18n/it.po
  addons/website_event_track/i18n/fr.po
  addons/website_forum/i18n/nl.po
  addons/website_sale/i18n/zh_TW.po
  addons/website_sale_product_configurator/i18n/nl.po
  addons/website_slides/i18n/nl.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/uk.po
Labels: tmp.saas-15.2

#18409 Syncing from upstream odoo/odoo (14.0)
  addons/auth_signup/controllers/main.py
  addons/auth_signup/tests/__init__.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/hr_org_chart/controllers/hr_org_chart.py
  addons/l10n_mx/data/account.account.template.csv
  addons/stock_account/models/product.py
  addons/survey/static/src/css/survey_print.css
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/website/models/ir_http.py
  addons/website/tests/test_page.py
Labels: 14.0

#18410 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/wizard/accrued_orders.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/pos_gift_card/static/src/js/models.js
  addons/sale/tests/test_accrued_sale_orders.py
  addons/survey/static/src/css/survey_templates_print.css
Labels: 15.0

#18413 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/wizard/accrued_orders.py
  addons/pos_sale/models/pos_order.py
  addons/sale/tests/test_accrued_sale_orders.py
Labels: saas-15.2

#18421 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/wizard/accrued_orders.py
  addons/pos_sale/models/pos_order.py
  addons/sale/tests/test_accrued_sale_orders.py
Labels: tmp.saas-15.2

#18424 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/wizard/accrued_orders.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/pos_gift_card/static/src/js/models.js
  addons/sale/tests/test_accrued_sale_orders.py
  addons/survey/static/src/css/survey_templates_print.css
Labels: tmp.15.0
