Repository brain-tec/odoo, pull requests merged in 2023-07, with the labels that each got.

#21150 Syncing from upstream odoo/odoo (14.0)
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
Labels: 14.0

#21151 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
Labels: 15.0

#21152 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tools/__init__.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/google_account/controllers/main.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_group_template_data.xml
  addons/l10n_ec/data/account_tax_group_data.xml
  addons/l10n_ec/i18n/es_EC.po
  addons/l10n_ec/models/account_chart_template.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/product/models/product_product.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/tests/views/fields/many2many_field_tests.js
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/sql_db.py
Labels: 16.0

#21154 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/google_account/controllers/main.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
Labels: saas-15.2

#21155 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/static/tests/tours/tax_group_tests.js
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_tour.py
  addons/account/tools/__init__.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/im_livechat/controllers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/product/models/product_product.py
  addons/repair/models/__init__.py
  addons/repair/models/mail_compose_message.py
  addons/repair/tests/test_repair.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: saas-16.1

#21156 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/chart_template.py
  addons/account/tools/__init__.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/im_livechat/controllers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/product/models/product_product.py
  addons/project/models/project.py
  addons/project/tests/test_project_base.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: saas-16.2

#21157 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tools/__init__.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/composer/navigable_list.js
  addons/mail/static/src/composer/suggestion_hook.js
  addons/mail/static/src/core_ui/message.scss
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/discuss_app/channel_selector.js
  addons/mail/static/tests/call/call_tests.js
  addons/mail/static/tests/chat_window/chat_window_new_message_tests.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/crosstab/crosstab_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/mail/static/tests/discuss_app/sidebar_tests.js
  addons/mail/static/tests/message/message_tests.js
  addons/mail/static/tests/messaging_menu/messaging_menu_tests.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/product/models/product_product.py
  addons/repair/models/__init__.py
  addons/repair/models/mail_compose_message.py
  addons/repair/tests/test_repair.py
  addons/sale_project/models/project.py
  addons/spreadsheet/static/src/global_filters/components/records_selector/records_selector.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.scss
  addons/stock/models/stock_quant.py
  addons/web/static/tests/core/position_hook_tests.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: saas-16.3

#21160 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/static/tests/tours/tax_group_tests.js
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_tour.py
  addons/account/tools/__init__.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/im_livechat/controllers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/product/models/product_product.py
  addons/repair/models/__init__.py
  addons/repair/models/mail_compose_message.py
  addons/repair/tests/test_repair.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: staging.saas-16.1

#21164 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
Labels: staging.14.0

#21168 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/google_account/controllers/main.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
Labels: tmp.saas-15.2

#21169 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/static/tests/tours/tax_group_tests.js
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_tour.py
  addons/account/tools/__init__.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/im_livechat/controllers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/product/models/product_product.py
  addons/repair/models/__init__.py
  addons/repair/models/mail_compose_message.py
  addons/repair/tests/test_repair.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: tmp.saas-16.1

#21170 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/chart_template.py
  addons/account/tools/__init__.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/im_livechat/controllers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/product/models/product_product.py
  addons/project/models/project.py
  addons/project/tests/test_project_base.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: tmp.saas-16.2

#21171 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tools/__init__.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_recruitment/models/hr_job.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/composer/navigable_list.js
  addons/mail/static/src/composer/suggestion_hook.js
  addons/mail/static/src/core_ui/message.scss
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/discuss_app/channel_selector.js
  addons/mail/static/tests/call/call_tests.js
  addons/mail/static/tests/chat_window/chat_window_new_message_tests.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/crosstab/crosstab_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/mail/static/tests/discuss_app/sidebar_tests.js
  addons/mail/static/tests/message/message_tests.js
  addons/mail/static/tests/messaging_menu/messaging_menu_tests.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/product/models/product_product.py
  addons/repair/models/__init__.py
  addons/repair/models/mail_compose_message.py
  addons/repair/tests/test_repair.py
  addons/sale_project/models/project.py
  addons/spreadsheet/static/src/global_filters/components/records_selector/records_selector.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.scss
  addons/stock/models/stock_quant.py
  addons/web/static/tests/core/position_hook_tests.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/tests/test_ir_default.py
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/models.py
  odoo/sql_db.py
Labels: tmp.saas-16.3

#21172 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
Labels: tmp.14.0

#21173 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
Labels: tmp.15.0

#21174 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tools/__init__.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/google_account/controllers/main.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_group_template_data.xml
  addons/l10n_ec/data/account_tax_group_data.xml
  addons/l10n_ec/i18n/es_EC.po
  addons/l10n_ec/models/account_chart_template.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mail/static/src/components/discuss_sidebar_category/discuss_sidebar_category.scss
  addons/product/models/product_product.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/tests/views/fields/many2many_field_tests.js
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/sql_db.py
Labels: tmp.16.0

#21178 Syncing from upstream odoo/odoo (master)
  addons/spreadsheet/static/src/global_filters/components/records_selector/records_selector.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.scss
Labels: master

#21183 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/l10n_sa_edi/views/account_journal_views.xml
Labels: staging.saas-16.1

#21189 Syncing from upstream odoo/odoo (tmp.master)
  addons/l10n_sa_edi/views/account_journal_views.xml
  addons/spreadsheet/static/src/global_filters/components/records_selector/records_selector.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.scss
Labels: tmp.master

#21190 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_sa_edi/views/account_journal_views.xml
Labels: tmp.saas-15.2

#21191 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/l10n_sa_edi/views/account_journal_views.xml
Labels: tmp.saas-16.1

#21192 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/l10n_sa_edi/views/account_journal_views.xml
Labels: tmp.saas-16.2

#21193 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/l10n_sa_edi/views/account_journal_views.xml
Labels: tmp.saas-16.3

#21195 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/l10n_sa_edi/views/account_journal_views.xml
Labels: 16.0

#21203 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/chart_template.py
Labels: tmp.master

#21208 Syncing from upstream odoo/odoo (14.0)
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/sale/views/sale_views.xml
Labels: 14.0

#21209 Syncing from upstream odoo/odoo (15.0)
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/attachment/attachment.js
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/mail/static/src/models/message/message.js
  addons/mail/static/src/models/message_action_list/message_action_list.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_order.py
  addons/portal/controllers/mail.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/sale/views/sale_views.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  debian/odoo.links
Labels: 15.0

#21210 Syncing from upstream odoo/odoo (16.0)
  addons/account/controllers/portal.py
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web/static/lib/zxing-library/zxing-library.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/_monkeypatches.py
Labels: 16.0

#21212 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/attachment/attachment.js
  addons/mail/static/src/models/composer_view/composer_view.js
  addons/mail/static/src/models/delete_message_confirm_view/delete_message_confirm_view.js
  addons/mail/static/src/models/message/message.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_order.py
  addons/portal/controllers/mail.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/sale/views/sale_order_views.xml
  debian/odoo.links
  odoo/tools/_monkeypatches.py
Labels: saas-15.2

#21213 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/res_config_settings.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/phone_validation/wizard/phone_blacklist_remove.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web/static/lib/zxing-library/zxing-library.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website_sale/views/res_config_settings_views.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/tools/_monkeypatches.py
Labels: saas-16.1

#21214 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/point_of_sale/wizard/pos_session_check_product_wizard.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_discount/static/src/js/models.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/tools/_monkeypatches.py
Labels: saas-16.2

#21215 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/google_account/controllers/main.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/static/tests/composer_patch_tests.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/message/message_tests.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/project/models/project_task.py
  addons/sale/__manifest__.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
  addons/spreadsheet/static/src/helpers/constants.js
  addons/stock/views/stock_move_views.xml
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/view_button/view_button.js
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/addons/base/static/src/scss/onboarding.scss
  odoo/addons/base/static/src/scss/onboarding.variables.dark.scss
  odoo/addons/base/static/src/scss/onboarding.variables.scss
  odoo/addons/base/views/onboarding_views.xml
  odoo/tools/_monkeypatches.py
Labels: saas-16.3

#21218 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/res_config_settings.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/phone_validation/wizard/phone_blacklist_remove.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web/static/lib/zxing-library/zxing-library.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website_sale/views/res_config_settings_views.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/tools/_monkeypatches.py
Labels: staging.saas-16.1

#21226 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/res_config_settings.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/phone_validation/wizard/phone_blacklist_remove.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web/static/lib/zxing-library/zxing-library.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website_sale/views/res_config_settings_views.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-16.1

#21227 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/point_of_sale/wizard/pos_session_check_product_wizard.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_discount/static/src/js/models.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-16.2

#21228 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/controllers/portal.py
  addons/account/models/account_move.py
  addons/account/models/account_partial_reconcile.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_date_algorithm.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/google_account/controllers/main.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/static/tests/composer_patch_tests.js
  addons/l10n_au/data/template/account.tax-au.csv
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/message/message_tests.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/project/models/project_task.py
  addons/sale/__manifest__.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
  addons/spreadsheet/static/src/helpers/constants.js
  addons/stock/views/stock_move_views.xml
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/view_button/view_button.js
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/addons/base/static/src/scss/onboarding.scss
  odoo/addons/base/static/src/scss/onboarding.variables.dark.scss
  odoo/addons/base/static/src/scss/onboarding.variables.scss
  odoo/addons/base/views/onboarding_views.xml
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-16.3

#21231 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/controllers/portal.py
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/auth_signup/models/res_partner.py
  addons/auth_signup/tests/test_auth_signup.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web/static/lib/zxing-library/zxing-library.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/static/tests/tours/test_promo_main_tour.js
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  debian/odoo.links
  doc/cla/individual/jadir-bs.md
  doc/cla/individual/rinngell-rezs.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/_monkeypatches.py
Labels: tmp.16.0

#21232 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/src/css/pos.css
  addons/project/views/project_views.xml
  addons/stock/models/stock_move_line.py
  addons/website/static/src/js/editor/widget_link.js
  odoo/tools/misc.py
Labels: 14.0

#21233 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ch/data/account.account.template.csv
  addons/l10n_ch/data/l10n_ch_chart_post_data.xml
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/sale/views/sale_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/website_event_track/models/website.py
  addons/website_event_track/tests/test_website.py
Labels: 15.0

#21234 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models/delete_message_confirm_view.js
  addons/mail/static/src/models/message.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/portal/controllers/mail.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sale/views/sale_order_views.xml
Labels: 16.0

#21236 Syncing from upstream odoo/odoo (saas-15.2)
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/sale/views/sale_order_views.xml
Labels: saas-15.2

#21237 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: saas-16.1

#21238 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/models/res_config_settings.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/mrp/models/mrp_production.py
  addons/payment_authorize/static/src/js/payment_form.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_sale/views/res_config_settings_views.xml
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: saas-16.2

#21239 Syncing from upstream odoo/odoo (saas-16.3)
  addons/bus/websocket.py
  addons/calendar/views/calendar_views.xml
  addons/hr_recruitment_survey/models/hr_job.py
  addons/im_livechat/models/discuss_channel.py
  addons/l10n_au/data/template/account.tax-au.csv
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/mail/controllers/thread.py
  addons/mail/static/src/composer/navigable_list.xml
  addons/mail/static/src/core/message_model.js
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/core_ui/message_reaction_menu.xml
  addons/mail/static/src/core_ui/primary_variables.scss
  addons/mail/static/src/scss/variables/primary_variables.scss
  addons/mail/static/src/web/activity/activity.js
  addons/mail/static/src/web/activity/activity.xml
  addons/mail/static/src/web/activity/activity_list_popover_item.xml
  addons/mail/static/src/web/chat_window/chat_window.js
  addons/mail/static/src/web/chat_window/chat_window.xml
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_discount/static/src/js/models.js
  addons/product/models/product_template.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_base.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/scss/primary_variables.scss
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/calendar/calendar_renderer.scss
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/web/static/src/views/form/form.variables.scss
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/form/form_compiler_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_tour/static/src/tour_service/tour_compilers.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: saas-16.3

#21242 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: staging.saas-16.1

#21245 Syncing from upstream odoo/odoo (staging.14.0)
  addons/point_of_sale/static/src/css/pos.css
  addons/project/views/project_views.xml
  addons/stock/models/stock_move_line.py
  addons/website/static/src/js/editor/widget_link.js
  odoo/tools/misc.py
Labels: staging.14.0

#21249 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/sale/views/sale_order_views.xml
Labels: tmp.saas-15.2

#21250 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.saas-16.1

#21251 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/models/res_config_settings.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/mrp/models/mrp_production.py
  addons/payment_authorize/static/src/js/payment_form.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_sale/views/res_config_settings_views.xml
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.saas-16.2

#21252 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/bus/websocket.py
  addons/calendar/views/calendar_views.xml
  addons/hr_recruitment_survey/models/hr_job.py
  addons/im_livechat/models/discuss_channel.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/mail/controllers/thread.py
  addons/mail/static/src/composer/navigable_list.xml
  addons/mail/static/src/core/message_model.js
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/core_ui/message_reaction_menu.xml
  addons/mail/static/src/core_ui/primary_variables.scss
  addons/mail/static/src/scss/variables/primary_variables.scss
  addons/mail/static/src/web/activity/activity.js
  addons/mail/static/src/web/activity/activity.xml
  addons/mail/static/src/web/activity/activity_list_popover_item.xml
  addons/mail/static/src/web/chat_window/chat_window.js
  addons/mail/static/src/web/chat_window/chat_window.xml
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_discount/static/src/js/models.js
  addons/product/models/product_template.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_base.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/survey/models/survey_survey.py
  addons/survey/views/survey_templates_management.xml
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/scss/primary_variables.scss
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/calendar/calendar_renderer.scss
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/web/static/src/views/form/form.variables.scss
  addons/web/static/src/views/form/form_compiler.js
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/form/form_compiler_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_tour/static/src/tour_service/tour_compilers.js
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.js
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_mail_server.py
Labels: tmp.saas-16.3

#21253 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/point_of_sale/static/src/css/pos.css
  addons/project/views/project_views.xml
  addons/stock/models/stock_move_line.py
  addons/website/static/src/js/editor/widget_link.js
  odoo/tools/misc.py
Labels: tmp.14.0

#21254 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_ch/data/account.account.template.csv
  addons/l10n_ch/data/l10n_ch_chart_post_data.xml
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/sale/views/sale_views.xml
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/website_event_track/models/website.py
  addons/website_event_track/tests/test_website.py
Labels: tmp.15.0

#21255 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_journal.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models/delete_message_confirm_view.js
  addons/mail/static/src/models/message.js
  addons/mail/static/tests/helpers/mock_server.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/views/pos_order_report_view.xml
  addons/portal/controllers/mail.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sale/views/sale_order_views.xml
Labels: tmp.16.0

#21256 Syncing from upstream odoo/odoo (11.0)
  odoo/addons/test_main_flows/tests/test_flow.py
Labels: 11.0

#21257 Syncing from upstream odoo/odoo (14.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/mrp/views/mrp_production_views.xml
  addons/sms/wizard/sms_composer.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
Labels: 14.0

#21258 Syncing from upstream odoo/odoo (15.0)
  addons/barcodes/static/src/js/barcode_parser.js
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_guest.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/sms/wizard/sms_composer.py
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/src/js/menu/navbar.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
Labels: 15.0

#21259 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_report.py
  addons/account/models/ir_actions_report.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/js/PaymentScreen.js
  addons/l10n_sa_edi_pos/static/src/js/pos_models.js
  addons/mail/security/ir.model.access.csv
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/models/pos_session.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web_editor/models/ir_qweb_fields.py
  addons/website/models/__init__.py
  addons/website/models/ir_model.py
  addons/website/models/ir_ui_menu.py
  addons/website/models/ir_ui_view.py
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_configurator.py
  addons/website/tests/test_ui.py
  addons/website/tests/test_views.py
  addons/website/views/website_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_page.js
  addons/website_slides/tests/test_statistics.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: 16.0

#21261 Syncing from upstream odoo/odoo (saas-15.2)
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/project/models/project.py
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/src/js/menu/navbar.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
Labels: saas-15.2

#21262 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_report.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: saas-16.1

#21263 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/website/static/src/components/views/page_list.js
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: saas-16.2

#21264 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/bus/__manifest__.py
  addons/im_livechat/static/src/composer/suggestion_service_patch.js
  addons/im_livechat/static/tests/composer_patch_tests.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/composer/navigable_list.js
  addons/mail/static/src/composer/suggestion_hook.js
  addons/mail/static/src/discuss_app/channel_selector.js
  addons/mail/static/src/rtc/call.xml
  addons/mail/static/src/rtc/call_action_list.xml
  addons/mail/static/tests/call/call_tests.js
  addons/mail/static/tests/chat_window/chat_window_new_message_tests.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/crosstab/crosstab_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/mail/static/tests/discuss_app/sidebar_tests.js
  addons/mail/static/tests/message/message_tests.js
  addons/mail/static/tests/messaging_menu/messaging_menu_tests.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/payment_authorize/static/src/js/payment_form.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/web/static/src/search/search_model.js
  addons/web/static/tests/search/search_bar_menu_tests.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: saas-16.3

#21267 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_report.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: staging.saas-16.1

#21270 Syncing from upstream odoo/odoo (staging.11.0)
  odoo/addons/test_main_flows/tests/test_flow.py
Labels: staging.11.0

#21271 Syncing from upstream odoo/odoo (staging.14.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/mrp/views/mrp_production_views.xml
  addons/sms/wizard/sms_composer.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
Labels: staging.14.0

#21275 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/project/models/project.py
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/src/js/menu/navbar.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
Labels: tmp.saas-15.2

#21276 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_report.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: tmp.saas-16.1

#21277 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/website/static/src/components/views/page_list.js
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: tmp.saas-16.2

#21278 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/account/static/src/js/account_portal.js
  addons/auth_password_policy/static/src/password_policy.js
  addons/bus/__manifest__.py
  addons/im_livechat/static/src/composer/suggestion_service_patch.js
  addons/im_livechat/static/tests/composer_patch_tests.js
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/models/account_journal.py
  addons/l10n_ch/tests/test_swissqr.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/composer/navigable_list.js
  addons/mail/static/src/composer/suggestion_hook.js
  addons/mail/static/src/discuss_app/channel_selector.js
  addons/mail/static/src/rtc/call.xml
  addons/mail/static/src/rtc/call_action_list.xml
  addons/mail/static/tests/call/call_tests.js
  addons/mail/static/tests/chat_window/chat_window_new_message_tests.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/crosstab/crosstab_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/mail/static/tests/discuss_app/sidebar_tests.js
  addons/mail/static/tests/message/message_tests.js
  addons/mail/static/tests/messaging_menu/messaging_menu_tests.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_byproduct.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/payment_authorize/static/src/js/payment_form.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/pos_mrp/__init__.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/models/__init__.py
  addons/pos_mrp/models/pos_order.py
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/sale/models/payment_transaction.py
  addons/sale/static/src/js/sale_portal.js
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/web/static/src/search/search_model.js
  addons/web/static/tests/search/search_bar_menu_tests.js
  addons/website/static/src/components/views/page_list.js
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/tests/test_configurator.py
Labels: tmp.saas-16.3

#21279 Syncing from upstream odoo/odoo (tmp.11.0)
  odoo/addons/test_main_flows/tests/test_flow.py
Labels: tmp.11.0

#21280 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/mrp/views/mrp_production_views.xml
  addons/sms/wizard/sms_composer.py
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/tests/views/list_tests.js
Labels: tmp.14.0

#21281 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/barcodes/static/src/js/barcode_parser.js
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_guest.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/css/pos.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/sms/wizard/sms_composer.py
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/src/js/menu/navbar.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
Labels: tmp.15.0

#21282 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_report.py
  addons/account/models/ir_actions_report.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/js/PaymentScreen.js
  addons/l10n_sa_edi_pos/static/src/js/pos_models.js
  addons/mail/security/ir.model.access.csv
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/models/pos_session.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/sms/wizard/sms_composer.py
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web_editor/models/ir_qweb_fields.py
  addons/website/models/__init__.py
  addons/website/models/ir_model.py
  addons/website/models/ir_ui_menu.py
  addons/website/models/ir_ui_view.py
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/configurator_translation.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_configurator.py
  addons/website/tests/test_ui.py
  addons/website/tests/test_views.py
  addons/website/views/website_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_page.js
  addons/website_slides/tests/test_statistics.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: tmp.16.0

#21283 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: 14.0

#21284 Syncing from upstream odoo/odoo (15.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/pos_coupon/models/coupon_program.py
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/views/view_utils.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
Labels: 15.0

#21285 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/pos_discount/static/src/js/models.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase/models/account_invoice.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/text_animations.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/omnidapps.md
Labels: 16.0

#21287 Syncing from upstream odoo/odoo (saas-15.2)
  addons/barcodes/static/src/js/barcode_parser.js
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/data/account.account.template.csv
  addons/l10n_ch/data/l10n_ch_chart_post_data.xml
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_guest.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_coupon/models/coupon_program.py
  addons/project/views/project_views.xml
  addons/sale/models/sale_order.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/tests/legacy/views/list_tests.js
Labels: saas-15.2

#21288 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models/delete_message_confirm_view.js
  addons/mail/static/src/models/message.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_session.py
  addons/portal/controllers/mail.py
  addons/sale/views/sale_order_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/editor-test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: saas-16.1

#21289 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/tests/test_chart_template.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/views/sale_order_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/editor-test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/static/tests/tours/page_manager.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: saas-16.2

#21290 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/tests/test_chart_template.py
  addons/im_livechat/static/src/web/message_patch.js
  addons/im_livechat/static/tests/message_patch_tests.js
  addons/mail/security/ir.model.access.csv
  addons/mail/static/src/composer/suggestion_service.js
  addons/mail/static/src/core/store_service.js
  addons/mail/static/src/core_ui/message.js
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/web/activity/activity_service.js
  addons/mail/static/src/web/chat_window/chat_window.js
  addons/mail/static/src/web/chat_window/chat_window.scss
  addons/mail/static/src/web/chat_window/chat_window.xml
  addons/mail/static/src/web/fields/many2one_avatar_user_field/many2one_avatar_user_field.js
  addons/mail/static/src/web/messaging_menu/messaging_menu.xml
  addons/mail/static/src/web/messaging_service_patch.js
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/views/mailing_list_views.xml
  addons/mrp/views/mrp_workcenter_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project/views/project_task_views.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_stock/static/src/widgets/qty_at_date_widget.xml
  addons/sale_timesheet/views/account_invoice_views.xml
  addons/stock/views/product_views.xml
  addons/stock/views/stock_lot_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web/static/src/core/notifications/notification_service.js
  addons/web/static/src/search/search_model.js
  addons/web/static/src/search/search_panel/search_panel.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/kanban/kanban_controller.xml
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/src/webclient/settings_form_view/settings_form_view.xml
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides/views/slide_slide_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/wizard/base_module_update_views.xml
Labels: saas-16.3

#21293 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models/delete_message_confirm_view.js
  addons/mail/static/src/models/message.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_session.py
  addons/portal/controllers/mail.py
  addons/sale/views/sale_order_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/editor-test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: staging.saas-16.1

#21296 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: staging.14.0

#21300 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/barcodes/static/src/js/barcode_parser.js
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/data/account.account.template.csv
  addons/l10n_ch/data/l10n_ch_chart_post_data.xml
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_guest.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_coupon/models/coupon_program.py
  addons/project/views/project_views.xml
  addons/sale/models/sale_order.py
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/tests/legacy/views/list_tests.js
Labels: tmp.saas-15.2

#21301 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_expense/models/hr_expense.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_attachment.py
  addons/mail/static/src/models/composer_view.js
  addons/mail/static/src/models/delete_message_confirm_view.js
  addons/mail/static/src/models/message.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_discuss_controller.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_session.py
  addons/portal/controllers/mail.py
  addons/sale/views/sale_order_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/editor-test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: tmp.saas-16.1

#21302 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/tests/test_chart_template.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_session.py
  addons/sale/views/sale_order_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/editor-test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/static/tests/tours/page_manager.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: tmp.saas-16.2

#21303 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/account.pot
  addons/account/i18n/km.po
  addons/account/models/account_move.py
  addons/account/tests/test_chart_template.py
  addons/im_livechat/static/src/web/message_patch.js
  addons/im_livechat/static/tests/message_patch_tests.js
  addons/mail/security/ir.model.access.csv
  addons/mail/static/src/composer/suggestion_service.js
  addons/mail/static/src/core/store_service.js
  addons/mail/static/src/core_ui/message.js
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/web/activity/activity_service.js
  addons/mail/static/src/web/chat_window/chat_window.js
  addons/mail/static/src/web/chat_window/chat_window.scss
  addons/mail/static/src/web/chat_window/chat_window.xml
  addons/mail/static/src/web/fields/many2one_avatar_user_field/many2one_avatar_user_field.js
  addons/mail/static/src/web/messaging_menu/messaging_menu.xml
  addons/mail/static/src/web/messaging_service_patch.js
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/views/mailing_list_views.xml
  addons/mrp/views/mrp_workcenter_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project/views/project_task_views.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_stock/static/src/widgets/qty_at_date_widget.xml
  addons/sale_timesheet/views/account_invoice_views.xml
  addons/stock/views/product_views.xml
  addons/stock/views/stock_lot_views.xml
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_survey_views.xml
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web/static/src/core/notifications/notification_service.js
  addons/web/static/src/search/search_model.js
  addons/web/static/src/search/search_panel/search_panel.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/kanban/kanban_controller.xml
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/src/webclient/settings_form_view/settings_form_view.xml
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_slides/views/slide_channel_views.xml
  addons/website_slides/views/slide_slide_views.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/wizard/base_module_update_views.xml
Labels: tmp.saas-16.3

#21304 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/account.account.template.csv
  addons/l10n_de_skr04/data/account.account.template.csv
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: tmp.14.0

#21305 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/pos_coupon/models/coupon_program.py
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/views/view_utils.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
Labels: tmp.15.0

#21306 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/pos_discount/static/src/js/models.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/purchase/models/account_invoice.py
  addons/survey/models/survey_survey.py
  addons/survey/tests/test_survey.py
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/views/view_dialogs/select_create_dialog.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/text_animations.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/omnidapps.md
Labels: tmp.16.0

#21307 Syncing from upstream odoo/odoo (14.0)
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
Labels: 14.0

#21308 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_document.py
  addons/hr_expense/models/hr_expense.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: 15.0

#21309 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_payment.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/point_of_sale/static/src/css/pos_receipts.css
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/pos_daily_sales_reports/views/point_of_sale_view.xml
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/sale/models/sale_order.py
  addons/sale_project/models/__init__.py
  addons/sale_project/models/sale_order_template_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: 16.0

#21311 Syncing from upstream odoo/odoo (saas-15.2)
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/view_utils.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: saas-15.2

#21312 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_group_template_data.xml
  addons/l10n_ec/data/account_tax_group_data.xml
  addons/l10n_ec/i18n/es_EC.po
  addons/l10n_ec/models/account_chart_template.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/models.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/sale/models/sale_order.py
  addons/sale_project/models/__init__.py
  addons/sale_project/models/sale_order_template_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/text_animations.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_ui.py
  addons/website/tests/test_unsplash_beacon.py
  doc/cla/corporate/omnidapps.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/tools/misc.py
Labels: saas-16.1

#21317 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_group_template_data.xml
  addons/l10n_ec/data/account_tax_group_data.xml
  addons/l10n_ec/i18n/es_EC.po
  addons/l10n_ec/models/account_chart_template.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/models.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/sale/models/sale_order.py
  addons/sale_project/models/__init__.py
  addons/sale_project/models/sale_order_template_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/text_animations.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_ui.py
  addons/website/tests/test_unsplash_beacon.py
  doc/cla/corporate/omnidapps.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/tools/misc.py
Labels: staging.saas-16.1

#21324 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/view_utils.js
  addons/web/static/tests/legacy/helpers/mock_server.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: tmp.saas-15.2

#21325 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_group_template_data.xml
  addons/l10n_ec/data/account_tax_group_data.xml
  addons/l10n_ec/i18n/es_EC.po
  addons/l10n_ec/models/account_chart_template.py
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/l10n_fr_pos_cert/report/pos_hash_integrity.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/ir_http.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/point_of_sale/static/src/css/popups/common.css
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/point_of_sale/static/src/js/Popups/CashOpeningPopup.js
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Popups/CashMovePopup.xml
  addons/point_of_sale/static/src/xml/Popups/CashOpeningPopup.xml
  addons/point_of_sale/static/src/xml/Popups/ClosePosPopup.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/models.js
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/sale/models/sale_order.py
  addons/sale_project/models/__init__.py
  addons/sale_project/models/sale_order_template_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website/static/tests/tours/text_animations.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_ui.py
  addons/website/tests/test_unsplash_beacon.py
  doc/cla/corporate/omnidapps.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/tools/misc.py
Labels: tmp.saas-16.1

#21329 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_edi_document.py
  addons/hr_expense/models/hr_expense.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: tmp.15.0

#21330 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_payment.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/point_of_sale/static/src/css/pos_receipts.css
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/pos_daily_sales_reports/views/point_of_sale_view.xml
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/sale/models/sale_order.py
  addons/sale_project/models/__init__.py
  addons/sale_project/models/sale_order_template_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/unsplash_beacon.js
  addons/website/tests/test_unsplash_beacon.py
Labels: tmp.16.0

#21334 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_payment.py
  addons/mail/static/src/core/web/chatter.xml
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  doc/cla/individual/rinngell-rezs.md
Labels: master

#21335 Syncing from upstream odoo/odoo (saas-16.3)
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/tests/views/fields/properties_field_tests.js
Labels: saas-16.3

#21340 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_payment.py
  addons/mail/static/src/core/web/chatter.xml
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  doc/cla/individual/rinngell-rezs.md
Labels: tmp.master

#21341 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/tests/views/fields/properties_field_tests.js
Labels: tmp.saas-16.3

#21342 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_document.py
Labels: 15.0

#21356 Syncing from upstream odoo/odoo (14.0)
  addons/mail/models/mail_channel.py
  addons/mass_mailing_event_sms/__manifest__.py
  addons/website_form/static/src/snippets/s_website_form/000.js
  odoo/tools/_monkeypatches.py
Labels: 14.0

#21357 Syncing from upstream odoo/odoo (15.0)
  addons/hr_attendance/report/hr_attendance_report.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/website_event_track/tests/test_website.py
  addons/website_event_track/tests/test_website_event.py
  odoo/tools/_monkeypatches.py
Labels: 15.0

#21358 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/calendar/models/calendar_event.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/tests/tours/edit_link_popover.js
  odoo/tools/_monkeypatches.py
Labels: 16.0

#21360 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi/models/account_edi_document.py
  addons/hr_attendance/report/hr_attendance_report.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_event_track/models/website.py
  addons/website_event_track/tests/test_website_event.py
  odoo/tools/_monkeypatches.py
Labels: saas-15.2

#21361 Syncing from upstream odoo/odoo (saas-16.1)
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/security/ir.model.access.csv
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/src/snippets/s_image_gallery/000.xml
  odoo/tools/_monkeypatches.py
Labels: saas-16.1

#21362 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_fi/data/template/account.account-fi.csv
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/models/mail_activity.py
  addons/mail/security/ir.model.access.csv
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_slide.py
  odoo/tools/_monkeypatches.py
Labels: saas-16.2

#21363 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment_term.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_early_payment_discount.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.xml
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/im_livechat/static/src/core/thread_model_patch.js
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/models/account_move_send.py
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_fi/data/template/account.account-fi.csv
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/composer/suggestion_hook.js
  addons/mail/static/src/core/thread_service.js
  addons/mail/static/src/core_ui/thread.js
  addons/mail/static/src/utils/hooks.js
  addons/mail/static/src/web/chatter.xml
  addons/mail/static/tests/discuss/suggestion_tests.js
  addons/mail/static/tests/helpers/mock_server/models/discuss_channel.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/project/i18n/project.pot
  addons/project/models/project_task.py
  addons/project/models/project_task_type.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale_timesheet/models/project.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/text_animations.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale_payment.js
  addons/website_slides/models/slide_channel.py
  odoo/tools/_monkeypatches.py
Labels: saas-16.3

#21366 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/security/ir.model.access.csv
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/src/snippets/s_image_gallery/000.xml
  odoo/tools/_monkeypatches.py
Labels: staging.saas-16.1

#21373 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi/models/account_edi_document.py
  addons/hr_attendance/report/hr_attendance_report.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_event_track/models/website.py
  addons/website_event_track/tests/test_website_event.py
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-15.2

#21374 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/tests/test_edi_import.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/security/ir.model.access.csv
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_security.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/src/snippets/s_image_gallery/000.xml
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-16.1

#21376 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment_term.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_early_payment_discount.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.xml
  addons/hr_attendance/report/hr_attendance_report.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/im_livechat/static/src/core/thread_model_patch.js
  addons/l10n_eg_edi_eta/views/report_invoice.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/models/account_move_send.py
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_fi/data/template/account.account-fi.csv
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/composer/suggestion_hook.js
  addons/mail/static/src/core/thread_service.js
  addons/mail/static/src/core_ui/thread.js
  addons/mail/static/src/utils/hooks.js
  addons/mail/static/src/web/chatter.xml
  addons/mail/static/tests/discuss/suggestion_tests.js
  addons/mail/static/tests/helpers/mock_server/models/discuss_channel.js
  addons/mail/static/tests/thread/thread_tests.js
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/project/i18n/project.pot
  addons/project/models/project_task.py
  addons/project/models/project_task_type.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale_timesheet/models/project.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/text_animations.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale_payment.js
  addons/website_slides/models/slide_channel.py
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-16.3

#21378 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_attendance/report/hr_attendance_report.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/website_event_track/tests/test_website.py
  addons/website_event_track/tests/test_website_event.py
  odoo/tools/_monkeypatches.py
Labels: tmp.15.0

#21380 Syncing from upstream odoo/odoo (14.0)
  addons/base_address_city/models/res_partner.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/models/project.py
  addons/l10n_fr/data/tax_report_data.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_workorder.py
  addons/project/controllers/portal.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/__init__.py
  addons/website_sale_delivery/tests/test_delivery.py
  addons/website_slides/controllers/main.py
  doc/cla/individual/SlaveWilson.md
Labels: 14.0

#21381 Syncing from upstream odoo/odoo (15.0)
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/models/project.py
  addons/mail/models/mail_channel.py
  addons/payment/models/account_journal.py
  addons/payment/models/account_payment_method.py
  addons/payment/tests/__init__.py
  addons/payment/tests/test_account_payment_method.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/project/controllers/portal.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/SlaveWilson.md
Labels: 15.0

#21382 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/static/src/components/account_move_form/account_move_form.js
  addons/account/static/src/components/account_move_service/account_move_service.js
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/views/project_views.xml
  addons/mail/controllers/discuss.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/pos_daily_sales_reports/wizard/pos_daily_sales_reports_wizard.py
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/SlaveWilson.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/tools/misc.py
Labels: 16.0

#21384 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_timesheet/models/project.py
  addons/payment/models/account_journal.py
  addons/payment/models/account_payment_method.py
  addons/payment/tests/__init__.py
  addons/payment/tests/test_account_payment_method.py
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/SlaveWilson.md
Labels: saas-15.2

#21385 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/pos_daily_sales_reports/wizard/pos_daily_sales_reports_wizard.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  doc/cla/individual/SlaveWilson.md
Labels: saas-16.1

#21386 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mrp/report/mrp_report_mo_overview.xml
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_provider.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/wizard/pos_daily_sales_reports.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/project/static/src/components/subtask_kanban_list/subtask_kanban_list.js
  addons/project/static/tests/project_subtask_kanban_list_tests.js
  addons/project/views/project_sharing_views.xml
  addons/sale/models/res_partner.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  doc/cla/individual/SlaveWilson.md
Labels: saas-16.2

#21387 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/im_livechat/static/tests/channel_invite_tests.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/static/src/core/channel_member_service.js
  addons/mail/static/src/discuss/channel_invitation.js
  addons/mail/static/src/discuss_app/discuss.xml
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/helpers/mock_server/models/discuss_channel.js
  addons/mrp/report/mrp_report_mo_overview.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/wizard/pos_daily_sales_reports.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/project/i18n/project.pot
  addons/project/models/project_task_type.py
  addons/project/static/src/project_sharing/components/chatter/chatter.scss
  addons/sale/models/res_partner.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_quiz_finish.js
  addons/website_slides/tests/test_slide_slide.py
  doc/cla/individual/SlaveWilson.md
Labels: saas-16.3

#21390 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/pos_daily_sales_reports/wizard/pos_daily_sales_reports_wizard.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  doc/cla/individual/SlaveWilson.md
Labels: staging.saas-16.1

#21393 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_address_city/models/res_partner.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/models/project.py
  addons/l10n_fr/data/tax_report_data.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_workorder.py
  addons/project/controllers/portal.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/__init__.py
  addons/website_sale_delivery/tests/test_delivery.py
  addons/website_slides/controllers/main.py
  doc/cla/individual/SlaveWilson.md
Labels: staging.14.0

#21397 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_contract/models/hr_contract.py
  addons/hr_holidays/report/hr_leave_report.py
  addons/hr_timesheet/models/project.py
  addons/payment/models/account_journal.py
  addons/payment/models/account_payment_method.py
  addons/payment/tests/__init__.py
  addons/payment/tests/test_account_payment_method.py
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/SlaveWilson.md
Labels: tmp.saas-15.2

#21398 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/pos_daily_sales_reports/wizard/pos_daily_sales_reports_wizard.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/page_manager.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  doc/cla/individual/SlaveWilson.md
Labels: tmp.saas-16.1

#21399 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mrp/report/mrp_report_mo_overview.xml
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/payment_stripe/models/payment_provider.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/static/src/js/Popups/ClosePosPopup.js
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/point_of_sale/wizard/pos_daily_sales_reports.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/project/static/src/components/subtask_kanban_list/subtask_kanban_list.js
  addons/project/static/tests/project_subtask_kanban_list_tests.js
  addons/project/views/project_sharing_views.xml
  addons/sale/models/res_partner.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/__init__.py
  addons/website/models/ir_ui_menu.py
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/website_backend_menus_redirect.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  doc/cla/individual/SlaveWilson.md
Labels: tmp.saas-16.2

#21400 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/models/partner.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_tax_python/i18n/account_tax_python.pot
  addons/account_tax_python/models/account_tax.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/im_livechat/static/tests/channel_invite_tests.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/static/src/core/channel_member_service.js
  addons/mail/static/src/discuss/channel_invitation.js
  addons/mail/static/src/discuss_app/discuss.xml
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/helpers/mock_server/models/discuss_channel.js
  addons/mrp/report/mrp_report_mo_overview.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/wizard/pos_daily_sales_reports.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/project/controllers/portal.py
  addons/project/i18n/project.pot
  addons/project/models/project_task_type.py
  addons/project/static/src/project_sharing/components/chatter/chatter.scss
  addons/sale/models/res_partner.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/static/src/js/slides_course_quiz_finish.js
  addons/website_slides/tests/test_slide_slide.py
  doc/cla/individual/SlaveWilson.md
Labels: tmp.saas-16.3

#21401 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_address_city/models/res_partner.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/models/project.py
  addons/l10n_fr/data/tax_report_data.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_workorder.py
  addons/project/controllers/portal.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/__init__.py
  addons/website_sale_delivery/tests/test_delivery.py
  addons/website_slides/controllers/main.py
  doc/cla/individual/SlaveWilson.md
Labels: tmp.14.0

#21402 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/models/project.py
  addons/mail/models/mail_channel.py
  addons/payment/models/account_journal.py
  addons/payment/models/account_payment_method.py
  addons/payment/tests/__init__.py
  addons/payment/tests/test_account_payment_method.py
  addons/pos_coupon/static/src/js/coupon.js
  addons/project/controllers/portal.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/SlaveWilson.md
Labels: tmp.15.0

#21403 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_report.py
  addons/account/static/src/components/account_move_form/account_move_form.js
  addons/account/static/src/components/account_move_service/account_move_service.js
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account_payment/models/account_journal.py
  addons/account_payment/models/account_payment_method_line.py
  addons/account_payment/tests/test_account_payment.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/event_crm/models/event_registration.py
  addons/event_sale/tests/test_event_sale.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_timesheet/views/project_views.xml
  addons/mail/controllers/discuss.py
  addons/phone_validation/models/res_partner.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/js/Popups/CashMovePopup.js
  addons/pos_daily_sales_reports/wizard/pos_daily_sales_reports_wizard.py
  addons/project/controllers/portal.py
  addons/sales_team/data/crm_team_data.xml
  addons/stock/models/stock_move_line.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_sale_delivery/models/res_country.py
  addons/website_sale_delivery/tests/test_controller.py
  doc/cla/individual/SlaveWilson.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/tools/misc.py
Labels: tmp.16.0

#21404 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/chart_template.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/link_tracker/tests/test_mail_render_mixin.py
  odoo/tests/common.py
Labels: 14.0

#21405 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_address_city/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  odoo/tools/misc.py
Labels: 15.0

#21406 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_timesheet/models/project.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/project/tests/test_project_milestone.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/sms/static/src/components/sms_button/sms_button.js
  addons/sms/static/src/components/sms_button/sms_button.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/fields/phone/phone_field.js
  addons/web/static/src/views/fields/phone/phone_field.xml
  addons/web/static/tests/views/fields/phone_field_tests.js
  addons/website/static/src/js/editor/widget_link.js
  odoo/addons/base/models/ir_binary.py
Labels: 16.0

#21408 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website/static/src/js/editor/widget_link.js
  odoo/tools/misc.py
Labels: saas-15.2

#21409 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_journal_dashboard.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_timesheet/models/project.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
Labels: saas-16.1

#21410 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/data/template/account.tax-generic_coa.csv
  addons/account/models/account_journal_dashboard.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_timesheet/models/project.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/controllers/main.py
  addons/project/tests/test_project_recurrence.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_sale/models/res_country.py
  addons/website_sale/tests/test_delivery_controller.py
Labels: saas-16.2

#21414 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_journal_dashboard.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_timesheet/models/project.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
Labels: staging.saas-16.1

#21417 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/chart_template.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/link_tracker/tests/test_mail_render_mixin.py
  odoo/tests/common.py
Labels: staging.14.0

#21421 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website/static/src/js/editor/widget_link.js
  odoo/tools/misc.py
Labels: tmp.saas-15.2

#21422 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_journal_dashboard.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_timesheet/models/project.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
Labels: tmp.saas-16.1

#21423 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/data/template/account.tax-generic_coa.csv
  addons/account/models/account_journal_dashboard.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr_timesheet/models/project.py
  addons/mail/controllers/discuss.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/controllers/main.py
  addons/project/tests/test_project_recurrence.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/services/website_custom_menus.js
  addons/website/static/src/services/website_service.js
  addons/website/tests/test_ui.py
  addons/website/views/website_templates.xml
  addons/website_sale/models/res_country.py
  addons/website_sale/tests/test_delivery_controller.py
Labels: tmp.saas-16.2

#21425 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/chart_template.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/link_tracker/tests/test_mail_render_mixin.py
  odoo/tests/common.py
Labels: tmp.14.0

#21426 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_address_city/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_fr/data/tax_report_data.xml
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_thread.py
  addons/purchase_stock/models/res_partner.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/legacy/js/fields/basic_fields.js
  odoo/tools/misc.py
Labels: tmp.15.0

#21427 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_timesheet/models/project.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_no_prices.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/i18n/mail.pot
  addons/mail/models/ir_config_parameter.py
  addons/mail/models/mail_alias.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_thread.py
  addons/project/tests/test_project_milestone.py
  addons/purchase/models/purchase.py
  addons/purchase/report/purchase_report.py
  addons/purchase/tests/test_purchase_order_report.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/purchase_stock/models/res_partner.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/sms/static/src/components/sms_button/sms_button.js
  addons/sms/static/src/components/sms_button/sms_button.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/fields/phone/phone_field.js
  addons/web/static/src/views/fields/phone/phone_field.xml
  addons/web/static/tests/views/fields/phone_field_tests.js
  addons/website/static/src/js/editor/widget_link.js
  odoo/addons/base/models/ir_binary.py
Labels: tmp.16.0

#21428 Revert "[bt#21829] Eingehender Mailserver, Refresh Token"
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
Labels: 11.0.project_qt_291

#21429 Syncing from upstream odoo/odoo (14.0)
  addons/mrp/models/mrp_workorder.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
Labels: 14.0

#21430 Syncing from upstream odoo/odoo (15.0)
  addons/link_tracker/tests/test_mail_render_mixin.py
  addons/mass_mailing_event_sms/__manifest__.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/stock_account/models/stock_move.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/tests/common.py
Labels: 15.0

#21431 Syncing from upstream odoo/odoo (16.0)
  .tx/config
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/remote_connect.html
  addons/im_livechat/static/src/legacy/models/public_livechat.js
  addons/im_livechat/static/src/legacy/widgets/public_livechat_window/public_livechat_window.js
  addons/im_livechat/static/src/public_models/livechat_button_view.js
  addons/im_livechat/static/src/public_models/public_livechat_global.js
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/mass_mailing_event_sms/__manifest__.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/mrp_consumption_warning.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.9/dist-packages/v4l2.py.iotpatch
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/website_livechat/static/src/public_models/public_livechat_global.js
  addons/website_livechat/static/tests/tours/website_livechat_session_user_changes.js
  addons/website_livechat/tests/__init__.py
  addons/website_livechat/tests/test_livechat_session_user_changes.py
Labels: 16.0

#21433 Syncing from upstream odoo/odoo (saas-15.2)
  .tx/config
  addons/l10n_fr/data/tax_report_data.xml
  addons/link_tracker/tests/test_mail_render_mixin.py
  addons/mass_mailing_event_sms/__manifest__.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/stock_account/models/stock_move.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/corporate/twio_tech.md
  odoo/tests/common.py
Labels: saas-15.2
