Repository brain-tec/odoo, pull requests merged in 2023-05, with the labels that each got.

#19945 Syncing from upstream odoo/odoo (master)
  requirements.txt
Labels: master

#19958 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/ar.po
  addons/account/i18n/ca.po
  addons/account/i18n/de.po
  addons/account/i18n/es_MX.po
  addons/account/i18n/fr.po
  addons/account/i18n/lv.po
  addons/account/i18n/ml.po
  addons/account/i18n/pl.po
  addons/account_edi/i18n/pl.po
  addons/account_edi_proxy_client/i18n/pl.po
  addons/account_edi_ubl_cii/i18n/pl.po
  addons/account_payment/i18n/ar.po
  addons/analytic/i18n/ar.po
  addons/analytic/i18n/es_MX.po
  addons/auth_password_policy/i18n/it.po
  addons/auth_signup/i18n/de.po
  addons/auth_signup/i18n/it.po
  addons/auth_totp/i18n/it.po
  addons/auth_totp_mail/i18n/ar.po
  addons/auth_totp_mail/i18n/it.po
  addons/auth_totp_mail_enforce/i18n/ar.po
  addons/auth_totp_mail_enforce/i18n/it.po
  addons/barcodes_gs1_nomenclature/i18n/es_MX.po
  addons/base_iban/i18n/ar.po
  addons/base_import_module/i18n/de.po
  addons/base_install_request/i18n/ar.po
  addons/crm/i18n/ar.po
  addons/delivery/i18n/es.po
  addons/event/i18n/ar.po
  addons/event_sale/i18n/ar.po
  addons/fleet/i18n/es.po
  addons/fleet/i18n/fi.po
  addons/fleet/i18n/pl.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/id.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/pl.po
  odoo/addons/base/i18n/pt_BR.po
  odoo/addons/base/i18n/sv.po
  requirements.txt
Labels: tmp.16.0

#19959 [bt#22547][Terresta][IMP] microsoft_outlook: update refresh token when getting a new access token
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
Labels: 13.0.project_te_576

#19965 Syncing from upstream odoo/odoo (13.0)
  odoo/tools/cloc.py
Labels: 13.0

#19966 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/mail/static/src/models/attachment/attachment.js
  doc/cla/corporate/le-filament.md
  odoo/tools/cloc.py
Labels: 14.0

#19967 Syncing from upstream odoo/odoo (15.0)
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/hr_attendance/models/hr_employee.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  doc/cla/corporate/le-filament.md
  odoo/tools/cloc.py
  odoo/tools/translate.py
Labels: 15.0

#19969 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/tools/cloc.py
Labels: saas-12.3

#19970 Syncing from upstream odoo/odoo (saas-15.2)
  addons/crm/data/ir_action_data.xml
  addons/hr_attendance/models/hr_employee.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_eu_oss/models/res_company.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/i18n/website.pot
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  doc/cla/corporate/le-filament.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/common.py
  odoo/tools/translate.py
Labels: saas-15.2

#19971 Syncing from upstream odoo/odoo (saas-16.1)
  addons/base_setup/views/res_config_settings_views.xml
  addons/calendar/wizard/calendar_provider_config.xml
  addons/crm/data/ir_action_data.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/views/templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template_line.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/res_config_settings_views.xml
  addons/survey/static/src/views/fields/boolean_toggle/survey_toggle_field_no_saving.js
  addons/survey/wizard/survey_invite_views.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website_sale_stock/models/product_product.py
  addons/website_sale_stock/models/product_template.py
  doc/cla/corporate/le-filament.md
  doc/cla/individual/fatmasayed22.md
  doc/cla/individual/qlasta.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/case.py
  odoo/tests/common.py
Labels: saas-16.1

#19972 Syncing from upstream odoo/odoo (saas-16.2)
  .tx/config
  addons/account/models/account_payment_term.py
  addons/account/models/account_tax.py
  addons/account/models/ir_attachment.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/base_setup/views/res_config_settings_views.xml
  addons/calendar/wizard/calendar_provider_config.xml
  addons/crm/data/ir_action_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_2.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_san_marino.xml
  addons/l10n_it_edi/tests/export_xmls/credit_note_reverse_charge.xml
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/purchase/models/purchase.py
  addons/sale/models/sale_order.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/views/templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template_line.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sales_team/models/crm_team.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/res_config_settings_views.xml
  addons/stock_account/models/stock_location.py
  addons/survey/wizard/survey_invite_views.xml
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/xml/website.backend.xml
  addons/website/views/res_config_settings_views.xml
  addons/website_sale_stock/models/product_product.py
  addons/website_sale_stock/models/product_template.py
  doc/cla/corporate/le-filament.md
  doc/cla/individual/fatmasayed22.md
  doc/cla/individual/qlasta.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/case.py
  odoo/tests/common.py
Labels: saas-16.2

#19973 Syncing from upstream odoo/odoo (staging.saas-12.3)
  odoo/tools/cloc.py
Labels: staging.saas-12.3

#19975 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/base_setup/views/res_config_settings_views.xml
  addons/calendar/wizard/calendar_provider_config.xml
  addons/crm/data/ir_action_data.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/views/templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template_line.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/res_config_settings_views.xml
  addons/survey/static/src/views/fields/boolean_toggle/survey_toggle_field_no_saving.js
  addons/survey/wizard/survey_invite_views.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website_sale_stock/models/product_product.py
  addons/website_sale_stock/models/product_template.py
  doc/cla/corporate/le-filament.md
  doc/cla/individual/fatmasayed22.md
  doc/cla/individual/qlasta.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/case.py
  odoo/tests/common.py
Labels: staging.saas-16.1

#19977 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/tools/cloc.py
Labels: staging.13.0

#19978 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/mail/static/src/models/attachment/attachment.js
  doc/cla/corporate/le-filament.md
  odoo/tools/cloc.py
Labels: staging.14.0

#19981 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  odoo/tools/cloc.py
Labels: tmp.saas-12.3

#19982 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/crm/data/ir_action_data.xml
  addons/hr_attendance/models/hr_employee.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_eu_oss/models/res_company.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/i18n/website.pot
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  doc/cla/corporate/le-filament.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/common.py
  odoo/tools/translate.py
Labels: tmp.saas-15.2

#19983 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/base_setup/views/res_config_settings_views.xml
  addons/calendar/wizard/calendar_provider_config.xml
  addons/crm/data/ir_action_data.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/views/templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template_line.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/res_config_settings_views.xml
  addons/survey/static/src/views/fields/boolean_toggle/survey_toggle_field_no_saving.js
  addons/survey/wizard/survey_invite_views.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website_sale_stock/models/product_product.py
  addons/website_sale_stock/models/product_template.py
  doc/cla/corporate/le-filament.md
  doc/cla/individual/fatmasayed22.md
  doc/cla/individual/qlasta.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/case.py
  odoo/tests/common.py
Labels: tmp.saas-16.1

#19984 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  .tx/config
  addons/account/models/account_payment_term.py
  addons/account/models/account_tax.py
  addons/account/models/ir_attachment.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/base_setup/views/res_config_settings_views.xml
  addons/calendar/wizard/calendar_provider_config.xml
  addons/crm/data/ir_action_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_2.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_san_marino.xml
  addons/l10n_it_edi/tests/export_xmls/credit_note_reverse_charge.xml
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/purchase/models/purchase.py
  addons/sale/models/sale_order.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/views/templates.xml
  addons/sale_management/models/sale_order.py
  addons/sale_management/models/sale_order_template_line.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sales_team/models/crm_team.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/res_config_settings_views.xml
  addons/stock_account/models/stock_location.py
  addons/survey/wizard/survey_invite_views.xml
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_countdown/000.js
  addons/website/static/src/xml/website.backend.xml
  addons/website/views/res_config_settings_views.xml
  addons/website_sale_stock/models/product_product.py
  addons/website_sale_stock/models/product_template.py
  doc/cla/corporate/le-filament.md
  doc/cla/individual/fatmasayed22.md
  doc/cla/individual/qlasta.md
  odoo/addons/base/tests/test_test_suite.py
  odoo/tests/case.py
  odoo/tests/common.py
Labels: tmp.saas-16.2

#19985 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/tools/cloc.py
Labels: tmp.13.0

#19986 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/mail/static/src/models/attachment/attachment.js
  doc/cla/corporate/le-filament.md
  odoo/tools/cloc.py
Labels: tmp.14.0

#19987 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/google_calendar/models/calendar.py
  addons/google_calendar/models/calendar_recurrence_rule.py
  addons/google_calendar/models/google_sync.py
  addons/hr_attendance/models/hr_employee.py
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/it.po
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/sale_mrp/i18n/sale_mrp.pot
  addons/sale_mrp/models/__init__.py
  addons/sale_mrp/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/website/i18n/website.pot
  addons/website/static/src/js/menu/translate.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  doc/cla/corporate/le-filament.md
  odoo/tools/cloc.py
  odoo/tools/translate.py
Labels: tmp.15.0

#19989 Syncing from upstream odoo/odoo (11.0)
  odoo/addons/base/ir/ir_model.py
Labels: 11.0

#19990 Syncing from upstream odoo/odoo (14.0)
  addons/crm/data/crm_lead_demo.xml
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
Labels: 14.0

#19991 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/crm/data/crm_lead_demo.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment/attachment.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/project/controllers/portal.py
  addons/web/static/src/legacy/js/core/menu.js
  addons/website_blog/static/src/scss/website_blog.scss
Labels: 15.0

#19993 Syncing from upstream odoo/odoo (saas-15.2)
  addons/crm/data/crm_lead_demo.xml
  addons/mail/static/src/models/attachment/attachment.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/project/controllers/portal.py
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/tools/cloc.py
Labels: saas-15.2

#19999 Syncing from upstream odoo/odoo (staging.11.0)
  odoo/addons/base/ir/ir_model.py
Labels: staging.11.0

#20000 Syncing from upstream odoo/odoo (staging.14.0)
  addons/crm/data/crm_lead_demo.xml
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
Labels: staging.14.0

#20003 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/crm/data/crm_lead_demo.xml
  addons/mail/static/src/models/attachment/attachment.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/project/controllers/portal.py
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/tools/cloc.py
Labels: tmp.saas-15.2

#20006 Syncing from upstream odoo/odoo (tmp.11.0)
  odoo/addons/base/ir/ir_model.py
Labels: tmp.11.0

#20007 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/crm/data/crm_lead_demo.xml
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
Labels: tmp.14.0

#20008 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/crm/data/crm_lead_demo.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment/attachment.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_acquirer.py
  addons/project/controllers/portal.py
  addons/web/static/src/legacy/js/core/menu.js
  addons/website_blog/static/src/scss/website_blog.scss
Labels: tmp.15.0

#20009 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_sequence/models/sequence_mixin.py
  addons/crm/data/crm_lead_demo.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_eu_oss/models/res_company.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/chat_window_manager.js
  addons/mass_mailing/static/src/js/mass_mailing_mobile_preview.js
  addons/product/i18n/product.pot
  addons/product/models/product_attribute.py
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/spreadsheet/static/tests/lists/list_plugin_test.js
  addons/spreadsheet/static/tests/utils/data.js
  addons/website/models/website_rewrite.py
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/__manifest__.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/tests/test_ir_model_fields_translation.js
  odoo/addons/base/tests/test_ir_model.py
  odoo/tools/cloc.py
Labels: tmp.16.0

#20010 Syncing from upstream odoo/odoo (14.0)
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
  addons/website_slides/views/assets.xml
  doc/cla/corporate/viindoo.md
Labels: 14.0

#20011 Syncing from upstream odoo/odoo (15.0)
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/project/views/project_views.xml
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: 15.0

#20013 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/project/views/project_views.xml
  addons/web/static/src/legacy/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: saas-15.2

#20014 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/chat_window_manager.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_provider.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/controllers/portal.py
  addons/purchase_stock/views/res_config_settings_views.xml
  addons/spreadsheet_dashboard/i18n/spreadsheet_dashboard.pot
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard_group.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/spreadsheet_dashboard_stock_account/data/files/inventory_on_hand_dashboard.json
  addons/web/static/src/legacy/scss/modal.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/website_rewrite.py
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website_sale_digital/controllers/main.py
  odoo/addons/base/__manifest__.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/tests/test_ir_model_fields_translation.js
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/addons/base/tests/test_ir_model.py
Labels: saas-16.1

#20015 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_bank_statement_line.py
  addons/account/static/src/components/auto_save_res_partner_bank/auto_save_res_partner_bank.js
  addons/account/views/partner_view.xml
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/chat_window_manager.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_provider.py
  addons/project/controllers/portal.py
  addons/project/views/project_views.xml
  addons/purchase_stock/views/res_config_settings_views.xml
  addons/sale/models/account_move.py
  addons/spreadsheet_dashboard_stock_account/data/files/inventory_on_hand_dashboard.json
  addons/web/static/src/legacy/scss/modal.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/website_rewrite.py
  addons/website/static/lib/multirange/multirange_custom.js
  odoo/addons/base/__manifest__.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/tests/test_ir_model_fields_translation.js
  odoo/addons/base/tests/test_ir_model.py
Labels: saas-16.2

#20017 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/chat_window_manager.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_provider.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/controllers/portal.py
  addons/purchase_stock/views/res_config_settings_views.xml
  addons/spreadsheet_dashboard/i18n/spreadsheet_dashboard.pot
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard_group.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/spreadsheet_dashboard_stock_account/data/files/inventory_on_hand_dashboard.json
  addons/web/static/src/legacy/scss/modal.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/website_rewrite.py
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website_sale_digital/controllers/main.py
  odoo/addons/base/__manifest__.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/tests/test_ir_model_fields_translation.js
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/addons/base/tests/test_ir_model.py
Labels: staging.saas-16.1

#20019 Syncing from upstream odoo/odoo (staging.14.0)
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
  addons/website_slides/views/assets.xml
  doc/cla/corporate/viindoo.md
Labels: staging.14.0

#20022 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/project/views/project_views.xml
  addons/web/static/src/legacy/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: tmp.saas-15.2

#20023 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/chat_window_manager.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_provider.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/controllers/portal.py
  addons/purchase_stock/views/res_config_settings_views.xml
  addons/spreadsheet_dashboard/i18n/spreadsheet_dashboard.pot
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard_group.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/spreadsheet_dashboard_stock_account/data/files/inventory_on_hand_dashboard.json
  addons/web/static/src/legacy/scss/modal.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/website_rewrite.py
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website_sale_digital/controllers/main.py
  odoo/addons/base/__manifest__.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/tests/test_ir_model_fields_translation.js
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/addons/base/tests/test_ir_model.py
Labels: tmp.saas-16.1

#20024 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_bank_statement_line.py
  addons/account/static/src/components/auto_save_res_partner_bank/auto_save_res_partner_bank.js
  addons/account/views/partner_view.xml
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_us.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/static/src/models/attachment.js
  addons/mail/static/src/models/chat_window_manager.js
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_provider.py
  addons/project/controllers/portal.py
  addons/project/views/project_views.xml
  addons/purchase_stock/views/res_config_settings_views.xml
  addons/sale/models/account_move.py
  addons/spreadsheet_dashboard_stock_account/data/files/inventory_on_hand_dashboard.json
  addons/web/static/src/legacy/scss/modal.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/models/website_rewrite.py
  addons/website/static/lib/multirange/multirange_custom.js
  odoo/addons/base/__manifest__.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/static/tests/test_ir_model_fields_translation.js
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/addons/base/tests/test_ir_model.py
Labels: tmp.saas-16.2

#20025 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
  addons/website_slides/views/assets.xml
  doc/cla/corporate/viindoo.md
Labels: tmp.14.0

#20026 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/project/views/project_views.xml
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/scss/modal.scss
  addons/website_sale_digital/controllers/main.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: tmp.15.0

#20027 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/hr_attendance/i18n/hr_attendance.pot
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_in/models/account.py
  addons/payment/i18n/payment.pot
  addons/payment/models/payment_provider.py
  addons/project/controllers/portal.py
  addons/purchase_stock/views/res_config_settings_views.xml
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/legacy/scss/modal.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website_sale_digital/controllers/main.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/service/model.py
Labels: tmp.16.0

#20029 [bt#22492] login layout changed
  addons/web/views/webclient_templates.xml
Labels: 10.0.project_th.test

#20030 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  odoo/addons/base/models/res_partner.py
Labels: 14.0

#20031 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/stock/report/report_stock_quantity.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
Labels: 15.0

#20033 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/stock/report/report_stock_quantity.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
Labels: saas-15.2

#20034 Syncing from upstream odoo/odoo (saas-16.1)
  addons/hr_attendance/i18n/hr_attendance.pot
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi/tests/test_edi_json.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/static/src/models/chatter.js
  addons/mail/static/src/views/activity/activity_model.js
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase_mrp/models/mrp_production.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/stock/report/report_stock_quantity.py
  addons/survey/views/survey_survey_views.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
  odoo/tests/test_module_operations.py
Labels: saas-16.1

#20035 Syncing from upstream odoo/odoo (saas-16.2)
  addons/hr_attendance/i18n/hr_attendance.pot
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi/tests/test_edi_json.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/static/src/views/activity/activity_model.js
  addons/pos_restaurant/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/stock/report/report_stock_quantity.py
  addons/survey/views/survey_survey_views.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale_digital/controllers/main.py
  doc/cla/corporate/viindoo.md
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_http.py
  odoo/tests/test_module_operations.py
Labels: saas-16.2

#20037 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/hr_attendance/i18n/hr_attendance.pot
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi/tests/test_edi_json.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/static/src/models/chatter.js
  addons/mail/static/src/views/activity/activity_model.js
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase_mrp/models/mrp_production.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/stock/report/report_stock_quantity.py
  addons/survey/views/survey_survey_views.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
  odoo/tests/test_module_operations.py
Labels: staging.saas-16.1

#20039 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  odoo/addons/base/models/res_partner.py
Labels: staging.14.0

#20042 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/stock/report/report_stock_quantity.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
Labels: tmp.saas-15.2

#20043 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/hr_attendance/i18n/hr_attendance.pot
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi/tests/test_edi_json.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/static/src/models/chatter.js
  addons/mail/static/src/views/activity/activity_model.js
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_restaurant/models/pos_order.py
  addons/purchase_mrp/models/mrp_production.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/stock/report/report_stock_quantity.py
  addons/survey/views/survey_survey_views.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/website/views/res_config_settings_views.xml
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
  odoo/tests/test_module_operations.py
Labels: tmp.saas-16.1

#20045 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.14.0

#20046 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/stock/report/report_stock_quantity.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
Labels: tmp.15.0

#20047 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/auth_password_policy/static/src/password_policy.js
  addons/hr_expense/models/hr_expense.py
  addons/l10n_in_edi_ewaybill/i18n/l10n_in_edi_ewaybill.pot
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/static/src/models/chatter.js
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/product.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/views/product_views.xml
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase_mrp/report/mrp_report_bom_structure.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/legacy/js/core/menu.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web_editor/static/src/js/common/ace.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/views/res_config_settings_views.xml
  addons/website_livechat/models/mail_channel.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/viindoo.md
Labels: tmp.16.0

#20050 Syncing from upstream odoo/odoo (saas-16.2)
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/test_mail/static/tests/activity_tests.js
Labels: saas-16.2

#20053 Syncing from upstream odoo/odoo (staging.14.0)
  addons/website/controllers/main.py
Labels: staging.14.0

#20055 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/test_mail/static/tests/activity_tests.js
Labels: tmp.saas-16.2

#20056 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/website/controllers/main.py
Labels: tmp.14.0

#20057 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/spreadsheet_dashboard_sale/data/files/sales_dashboard.json
Labels: tmp.16.0

#20058 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/fr.po
  addons/account_edi_ubl_cii/i18n/es_MX.po
  addons/account_edi_ubl_cii/i18n/fr.po
  addons/account_edi_ubl_cii/i18n/nl.po
  addons/event/i18n/de.po
  addons/hr/i18n/fr.po
  addons/im_livechat/i18n/fr.po
  addons/mail/i18n/fr.po
  addons/maintenance/i18n/fr.po
  addons/mrp/i18n/es.po
  addons/mrp/i18n/fr.po
  addons/mrp_subcontracting_dropshipping/i18n/vi.po
  addons/mrp_subcontracting_purchase/i18n/vi.po
  addons/payment/i18n/de.po
  addons/payment/i18n/fr.po
  addons/payment/i18n/nl.po
  addons/phone_validation/i18n/es_MX.po
  addons/point_of_sale/i18n/fr.po
  addons/portal_rating/i18n/fr.po
  addons/pos_restaurant/i18n/es_MX.po
  addons/pos_restaurant/i18n/uk.po
  addons/pos_sale/i18n/es_MX.po
  addons/product/i18n/es_MX.po
  addons/project/i18n/es_MX.po
  addons/project/i18n/fr.po
  addons/purchase/i18n/es.po
  addons/purchase/i18n/fr.po
  addons/rating/i18n/fr.po
  addons/repair/i18n/es_MX.po
  addons/sale/i18n/es.po
  addons/sale_mrp/i18n/de.po
  addons/sale_mrp/i18n/fr.po
  addons/sale_mrp/i18n/nl.po
  addons/sale_timesheet/i18n/fr.po
  addons/stock/i18n/es.po
  addons/stock/i18n/fr.po
  addons/utm/i18n/fr.po
  addons/website/i18n/de.po
  addons/website/i18n/es.po
  addons/website/i18n/fr.po
  addons/website/i18n/it.po
  addons/website/i18n/nl.po
  addons/website/i18n/zh_TW.po
  addons/website_forum/i18n/fr.po
  addons/website_livechat/i18n/fr.po
  addons/website_sale/i18n/it.po
  odoo/addons/base/i18n/fr.po
Labels: saas-15.2

#20028 [bt#22492] login layout changed
  addons/web/views/webclient_templates.xml
Labels: 10.0.project_th

#20067 Syncing from upstream odoo/odoo (14.0)
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/web/controllers/main.py
  doc/cla/individual/eLBati.md
  odoo/addons/base/wizard/base_import_language.py
  odoo/http.py
Labels: 14.0

#20068 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_res_partner.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/sale/controllers/portal.py
  addons/sale/tests/test_payment_flow.py
  addons/test_discuss_full/tests/test_performance.py
  addons/web/controllers/main.py
  doc/cla/individual/eLBati.md
  odoo/addons/base/wizard/base_import_language.py
  odoo/http.py
Labels: 15.0

#20069 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/account/wizard/accrued_orders.py
  addons/fleet/models/fleet_vehicle_log_contract.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/project/views/project_views.xml
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/controllers/portal.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/sale/tests/test_payment_flow.py
  addons/sale_loyalty_delivery/models/sale_order.py
  addons/sale_loyalty_delivery/tests/test_free_shipping_reward.py
  addons/web/static/src/views/fields/float_time/float_time_field.xml
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/fields/priority/priority_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/float_time_field_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/fields/priority_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website_blog/models/website_blog.py
  doc/cla/individual/eLBati.md
Labels: 16.0

#20071 Syncing from upstream odoo/odoo (saas-15.2)
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/sale/controllers/portal.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_payment_flow.py
  addons/web/controllers/main.py
  doc/cla/individual/eLBati.md
  odoo/addons/base/wizard/base_import_language.py
  odoo/http.py
Labels: saas-15.2

#20072 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move_line.py
  addons/auth_password_policy/static/src/password_policy.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/views/project_views.xml
  addons/sale/controllers/portal.py
  addons/sale/tests/test_payment_flow.py
  addons/sale_loyalty_delivery/models/sale_order.py
  addons/sale_loyalty_delivery/tests/test_free_shipping_reward.py
  addons/spreadsheet_dashboard_sale/data/files/sales_dashboard.json
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/core/network/download.js
  addons/web/static/src/legacy/js/core/menu.js
  addons/web/static/src/views/fields/float_time/float_time_field.xml
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/fields/priority/priority_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.xml
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/float_time_field_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/fields/priority_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website_livechat/models/mail_channel.py
  doc/cla/individual/eLBati.md
Labels: saas-16.1

#20073 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move_line.py
  addons/account/models/chart_template.py
  addons/auth_password_policy/static/src/password_policy.js
  addons/hr/models/res_users.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/mail/static/src/models/chatter.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/ProductScreen.xml
  addons/point_of_sale/static/src/xml/Screens/TicketScreen/TicketScreen.xml
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_restaurant/static/src/js/Screens/ProductScreen/ActionpadWidget.js
  addons/pos_restaurant/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/purchase_mrp/models/mrp_production.py
  addons/sale/controllers/portal.py
  addons/sale/tests/test_payment_flow.py
  addons/sale_loyalty_delivery/models/sale_order.py
  addons/sale_loyalty_delivery/tests/test_free_shipping_reward.py
  addons/spreadsheet_dashboard/i18n/spreadsheet_dashboard.pot
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard.py
  addons/spreadsheet_dashboard/models/spreadsheet_dashboard_group.py
  addons/spreadsheet_dashboard/tests/test_spreadsheet_dashboard.py
  addons/spreadsheet_dashboard_sale/data/files/sales_dashboard.json
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/core/network/download.js
  addons/web/static/src/legacy/js/core/menu.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/views/fields/float_time/float_time_field.xml
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/views/view_button/view_button_hook.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/float_time_field_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/actions/error_handling_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/website_livechat/models/mail_channel.py
  addons/website_sale/static/src/js/website_sale_delivery.js
  addons/website_sale_loyalty/controllers/delivery.py
  doc/cla/individual/eLBati.md
Labels: saas-16.2

#20080 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/fr.po
  addons/account_edi_ubl_cii/i18n/es_MX.po
  addons/account_edi_ubl_cii/i18n/fr.po
  addons/account_edi_ubl_cii/i18n/nl.po
  addons/event/i18n/de.po
  addons/hr/i18n/fr.po
  addons/im_livechat/i18n/fr.po
  addons/mail/i18n/fr.po
  addons/maintenance/i18n/fr.po
  addons/mrp/i18n/es.po
  addons/mrp/i18n/fr.po
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_byproduct.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/mrp_subcontracting_dropshipping/i18n/vi.po
  addons/mrp_subcontracting_purchase/i18n/vi.po
  addons/payment/i18n/de.po
  addons/payment/i18n/fr.po
  addons/payment/i18n/nl.po
  addons/phone_validation/i18n/es_MX.po
  addons/point_of_sale/i18n/fr.po
  addons/portal_rating/i18n/fr.po
  addons/pos_restaurant/i18n/es_MX.po
  addons/pos_restaurant/i18n/uk.po
  addons/pos_sale/i18n/es_MX.po
  addons/product/i18n/es_MX.po
  addons/project/i18n/es_MX.po
  addons/project/i18n/fr.po
  addons/purchase/i18n/es.po
  addons/purchase/i18n/fr.po
  addons/rating/i18n/fr.po
  addons/repair/i18n/es_MX.po
  addons/sale/controllers/portal.py
  addons/sale/i18n/es.po
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_payment_flow.py
  addons/sale_mrp/i18n/de.po
  addons/sale_mrp/i18n/fr.po
  addons/sale_mrp/i18n/nl.po
  addons/sale_timesheet/i18n/fr.po
  addons/stock/i18n/es.po
  addons/stock/i18n/fr.po
  addons/utm/i18n/fr.po
  addons/web/controllers/main.py
  addons/website/i18n/de.po
  addons/website/i18n/es.po
  addons/website/i18n/fr.po
  addons/website/i18n/it.po
  addons/website/i18n/nl.po
  addons/website/i18n/zh_TW.po
  addons/website_forum/i18n/fr.po
  addons/website_livechat/i18n/fr.po
  addons/website_sale/i18n/it.po
  doc/cla/individual/eLBati.md
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/wizard/base_import_language.py
  odoo/http.py
Labels: tmp.saas-15.2

#20086 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/addons/base/tests/test_image.py
  odoo/tools/image.py
Labels: 14.0

#20087 Syncing from upstream odoo/odoo (15.0)
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/website/models/website_page.py
  odoo/addons/base/models/res_partner.py
Labels: 15.0

#20088 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/delivery/models/delivery_carrier.py
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_lv/Readme.txt
  addons/l10n_lv/__init__.py
  addons/l10n_lv/__manifest__.py
  addons/l10n_lv/data/account.account.template.csv
  addons/l10n_lv/data/account.group.template.csv
  addons/l10n_lv/data/account_chart_template_data.xml
  addons/l10n_lv/data/account_chart_template_load.xml
  addons/l10n_lv/data/account_chart_template_setup_data.xml
  addons/l10n_lv/data/account_fiscal_position_template_data.xml
  addons/l10n_lv/data/account_tax_group_data.xml
  addons/l10n_lv/data/account_tax_template_data.xml
  addons/l10n_lv/data/vat_tax_report.xml
  addons/l10n_lv/demo/demo_company.xml
  addons/l10n_lv/i18n/lv.po
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/product/models/product_product.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/src/views/fields/email/email_field.xml
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website/models/website_page.py
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  addons/website_sale_slides/views/website_slides_templates.xml
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
Labels: 16.0

#20090 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/web/static/src/legacy/js/core/menu.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/models/website_page.py
  odoo/addons/base/models/res_partner.py
Labels: saas-15.2

#20091 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/accrued_orders.py
  addons/fleet/models/fleet_vehicle_log_contract.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/models/hr_job.py
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/web_editor/static/src/js/common/ace.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_blog/models/website_blog.py
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  addons/website_sale_slides/views/website_slides_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/http.py
  odoo/service/model.py
Labels: saas-16.1

#20092 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/demo/account_demo.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_entry.py
  addons/account/wizard/accrued_orders.py
  addons/account/wizard/setup_wizards.py
  addons/fleet/models/fleet_vehicle_log_contract.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in/models/account.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/web/static/src/views/fields/priority/priority_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/priority_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web_editor/static/src/js/common/ace.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_blog/models/website_blog.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: saas-16.2

#20095 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/accrued_orders.py
  addons/fleet/models/fleet_vehicle_log_contract.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/models/hr_job.py
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/web_editor/static/src/js/common/ace.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_blog/models/website_blog.py
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  addons/website_sale_slides/views/website_slides_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/http.py
  odoo/service/model.py
Labels: staging.saas-16.1

#20097 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/addons/base/tests/test_image.py
  odoo/tools/image.py
Labels: staging.14.0

#20101 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/sale/models/account_move_line.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_reinvoice.py
  addons/web/static/src/legacy/js/core/menu.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/models/website_page.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.saas-15.2

#20102 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/accrued_orders.py
  addons/fleet/models/fleet_vehicle_log_contract.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/models/hr_job.py
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/web_editor/static/src/js/common/ace.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_blog/models/website_blog.py
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  addons/website_sale_slides/views/website_slides_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/http.py
  odoo/service/model.py
Labels: tmp.saas-16.1

#20103 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/demo/account_demo.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_entry.py
  addons/account/wizard/accrued_orders.py
  addons/account/wizard/setup_wizards.py
  addons/fleet/models/fleet_vehicle_log_contract.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment_survey/models/hr_job.py
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_in/models/account.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/i18n/project.pot
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale/tests/test_accrued_sale_orders.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/web/static/src/views/fields/priority/priority_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/priority_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web_editor/static/src/js/common/ace.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_blog/models/website_blog.py
  addons/website_sale_slides/views/website_slides_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_rpc/models.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/service/model.py
Labels: tmp.saas-16.2

#20104 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/addons/base/tests/test_image.py
  odoo/tools/image.py
Labels: tmp.14.0

#20105 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/website/models/website_page.py
  odoo/addons/base/models/res_partner.py
Labels: tmp.15.0

#20106 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/delivery/models/delivery_carrier.py
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_lv/Readme.txt
  addons/l10n_lv/__init__.py
  addons/l10n_lv/__manifest__.py
  addons/l10n_lv/data/account.account.template.csv
  addons/l10n_lv/data/account.group.template.csv
  addons/l10n_lv/data/account_chart_template_data.xml
  addons/l10n_lv/data/account_chart_template_load.xml
  addons/l10n_lv/data/account_chart_template_setup_data.xml
  addons/l10n_lv/data/account_fiscal_position_template_data.xml
  addons/l10n_lv/data/account_tax_group_data.xml
  addons/l10n_lv/data/account_tax_template_data.xml
  addons/l10n_lv/data/vat_tax_report.xml
  addons/l10n_lv/demo/demo_company.xml
  addons/l10n_lv/i18n/lv.po
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/product/models/product_product.py
  addons/stock/static/src/components/reception_report_main/stock_reception_report_main.js
  addons/stock/static/src/components/reception_report_table/stock_reception_report_table.js
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/src/views/fields/email/email_field.xml
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website/models/website_page.py
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale_slides/views/website_slides_templates.xml
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/wizard/base_import_language.py
Labels: tmp.16.0

#20107 Syncing from upstream odoo/odoo (14.0)
  addons/hr_contract/models/hr_contract.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_backorder_confirmation.py
Labels: 14.0

#20108 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_payment.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/mail/models/ir_model.py
  addons/mail/static/src/models/chat_window_manager/chat_window_manager.js
  addons/mail/static/src/models/discuss_public_view/discuss_public_view.js
  addons/mail/static/src/models/messaging/messaging.js
  addons/pos_restaurant/static/src/js/Screens/TicketScreen.js
  addons/pos_restaurant/static/tests/tours/refund.tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
Labels: 15.0

#20109 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_a_nz.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/ir_model.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_product.py
  addons/web/controllers/binary.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
Labels: 16.0

#20111 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_res_partner.py
  addons/mail/models/ir_model.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_uninstall.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_product.py
  addons/test_discuss_full/tests/test_performance.py
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
Labels: saas-15.2

#20112 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/views/res_config_settings_views.xml
  addons/delivery/models/delivery_carrier.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_in/models/account.py
  addons/l10n_lv/Readme.txt
  addons/l10n_lv/__init__.py
  addons/l10n_lv/__manifest__.py
  addons/l10n_lv/data/account.account.template.csv
  addons/l10n_lv/data/account.group.template.csv
  addons/l10n_lv/data/account_chart_template_data.xml
  addons/l10n_lv/data/account_chart_template_load.xml
  addons/l10n_lv/data/account_chart_template_setup_data.xml
  addons/l10n_lv/data/account_fiscal_position_template_data.xml
  addons/l10n_lv/data/account_tax_group_data.xml
  addons/l10n_lv/data/account_tax_template_data.xml
  addons/l10n_lv/data/vat_tax_report.xml
  addons/l10n_lv/demo/demo_company.xml
  addons/l10n_lv/i18n/lv.po
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/product/models/product_product.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock_account/models/account_move.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/controllers/binary.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/src/views/fields/email/email_field.xml
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website/models/website_page.py
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: saas-16.1

#20113 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/ir_attachment.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_a_nz.py
  addons/delivery/models/delivery_carrier.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_lv/Readme.txt
  addons/l10n_lv/__init__.py
  addons/l10n_lv/__manifest__.py
  addons/l10n_lv/data/template/account.account-lv.csv
  addons/l10n_lv/data/template/account.fiscal.position-lv.csv
  addons/l10n_lv/data/template/account.group-lv.csv
  addons/l10n_lv/data/template/account.tax-lv.csv
  addons/l10n_lv/data/template/account.tax.group-lv.csv
  addons/l10n_lv/data/vat_tax_report.xml
  addons/l10n_lv/demo/demo_company.xml
  addons/l10n_lv/i18n/lv.po
  addons/l10n_lv/models/__init__.py
  addons/l10n_lv/models/template_lv.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/payment/static/src/js/manage_form.js
  addons/payment/static/src/js/payment_form_mixin.js
  addons/payment_adyen/static/src/js/payment_form.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/product/models/product_product.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/sale/models/payment_transaction.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock_account/models/account_move.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/controllers/binary.py
  addons/web/static/src/views/fields/email/email_field.xml
  addons/website/models/website_page.py
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale_slides/views/website_slides_templates.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: saas-16.2

#20116 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/views/res_config_settings_views.xml
  addons/delivery/models/delivery_carrier.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_in/models/account.py
  addons/l10n_lv/Readme.txt
  addons/l10n_lv/__init__.py
  addons/l10n_lv/__manifest__.py
  addons/l10n_lv/data/account.account.template.csv
  addons/l10n_lv/data/account.group.template.csv
  addons/l10n_lv/data/account_chart_template_data.xml
  addons/l10n_lv/data/account_chart_template_load.xml
  addons/l10n_lv/data/account_chart_template_setup_data.xml
  addons/l10n_lv/data/account_fiscal_position_template_data.xml
  addons/l10n_lv/data/account_tax_group_data.xml
  addons/l10n_lv/data/account_tax_template_data.xml
  addons/l10n_lv/data/vat_tax_report.xml
  addons/l10n_lv/demo/demo_company.xml
  addons/l10n_lv/i18n/lv.po
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/product/models/product_product.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock_account/models/account_move.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/controllers/binary.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/src/views/fields/email/email_field.xml
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website/models/website_page.py
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: staging.saas-16.1

#20118 Syncing from upstream odoo/odoo (staging.14.0)
  addons/hr_contract/models/hr_contract.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_backorder_confirmation.py
Labels: staging.14.0

#20122 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_res_partner.py
  addons/mail/models/ir_model.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_uninstall.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_product.py
  addons/test_discuss_full/tests/test_performance.py
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
Labels: tmp.saas-15.2

#20123 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_entry.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/views/res_config_settings_views.xml
  addons/delivery/models/delivery_carrier.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_in/models/account.py
  addons/l10n_lv/Readme.txt
  addons/l10n_lv/__init__.py
  addons/l10n_lv/__manifest__.py
  addons/l10n_lv/data/account.account.template.csv
  addons/l10n_lv/data/account.group.template.csv
  addons/l10n_lv/data/account_chart_template_data.xml
  addons/l10n_lv/data/account_chart_template_load.xml
  addons/l10n_lv/data/account_chart_template_setup_data.xml
  addons/l10n_lv/data/account_fiscal_position_template_data.xml
  addons/l10n_lv/data/account_tax_group_data.xml
  addons/l10n_lv/data/account_tax_template_data.xml
  addons/l10n_lv/data/vat_tax_report.xml
  addons/l10n_lv/demo/demo_company.xml
  addons/l10n_lv/i18n/lv.po
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/product/models/product_product.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock_account/models/account_move.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/controllers/binary.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/src/views/fields/email/email_field.xml
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website/models/website_page.py
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: tmp.saas-16.1

#20125 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hr_contract/models/hr_contract.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_backorder_confirmation.py
Labels: tmp.14.0

#20126 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_payment.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/mail/models/ir_model.py
  addons/mail/static/src/models/chat_window_manager/chat_window_manager.js
  addons/mail/static/src/models/discuss_public_view/discuss_public_view.js
  addons/mail/static/src/models/messaging/messaging.js
  addons/pos_restaurant/static/src/js/Screens/TicketScreen.js
  addons/pos_restaurant/static/tests/tours/refund.tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
Labels: tmp.15.0

#20127 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_a_nz.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/ir_model.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/stock/i18n/stock.pot
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_product.py
  addons/web/controllers/binary.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/website_crm_partner_assign/report/crm_partner_report_view.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_ui_wslides.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
Labels: tmp.16.0

#20128 Syncing from upstream odoo/odoo (13.0)
  odoo/modules/module.py
Labels: 13.0

#20129 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/chart_template.py
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_profile/views/website_profile.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/tests/loader.py
Labels: 14.0

#20130 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/l10n_lu/migrations/2.1/end-migrate_update_taxes.py
  addons/mail/models/mail_thread.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/legacy/scss/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/main.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_profile/views/website_profile.xml
  odoo/modules/module.py
Labels: 15.0

#20131 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/__init__.py
  addons/loyalty/models/product_product.py
  addons/loyalty/models/product_template.py
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/project_purchase/models/project.py
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/website/controllers/main.py
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_mass_mailing/tests/test_snippets.py
  odoo/addons/base/models/res_partner.py
  odoo/modules/module.py
Labels: 16.0

#20133 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_payment.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/crm/models/ir_config_parameter.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/l10n_lu/migrations/2.1/end-migrate_update_taxes.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/chat_window_manager/chat_window_manager.js
  addons/mail/static/src/models/discuss_public_view/discuss_public_view.js
  addons/mail/static/src/models/messaging/messaging.js
  addons/mrp/models/mrp_production.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/legacy/scss/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/controllers/main.py
  odoo/addons/base/models/ir_model.py
  odoo/fields.py
  odoo/modules/loading.py
  odoo/modules/module.py
Labels: saas-15.2

#20134 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_a_nz.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_chart_template_setup_accounts.xml
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/models/account_move.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/project_purchase/models/project.py
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/stock/models/stock_orderpoint.py
  addons/website/controllers/main.py
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
  odoo/modules/module.py
Labels: saas-16.1

#20135 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/res_config_settings_views.xml
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/views/res_config_settings_views.xml
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/l10n_ec/models/account_move.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
  odoo/modules/module.py
Labels: saas-16.2

#20138 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_a_nz.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_chart_template_setup_accounts.xml
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/models/account_move.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/project_purchase/models/project.py
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/stock/models/stock_orderpoint.py
  addons/website/controllers/main.py
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
  odoo/modules/module.py
Labels: staging.saas-16.1

#20140 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/modules/module.py
Labels: staging.13.0

#20141 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/chart_template.py
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_profile/views/website_profile.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/modules/module.py
  odoo/tests/loader.py
Labels: staging.14.0

#20145 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_payment.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/crm/models/ir_config_parameter.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/l10n_lu/migrations/2.1/end-migrate_update_taxes.py
  addons/mail/models/ir_model.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/chat_window_manager/chat_window_manager.js
  addons/mail/static/src/models/discuss_public_view/discuss_public_view.js
  addons/mail/static/src/models/messaging/messaging.js
  addons/mrp/models/mrp_production.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/legacy/scss/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/controllers/main.py
  odoo/addons/base/models/ir_model.py
  odoo/fields.py
  odoo/modules/loading.py
  odoo/modules/module.py
Labels: tmp.saas-15.2

#20146 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_a_nz.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_chart_template_setup_accounts.xml
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/models/account_move.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/project_purchase/models/project.py
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/stock/models/stock_orderpoint.py
  addons/website/controllers/main.py
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
  odoo/modules/module.py
Labels: tmp.saas-16.1

#20147 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/res_config_settings_views.xml
  addons/analytic/i18n/analytic.pot
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/views/res_config_settings_views.xml
  addons/hr/views/hr_job_views.xml
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/calendar.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_recruitment/views/hr_job_views.xml
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_recruitment/wizard/applicant_refuse_reason_views.xml
  addons/hr_recruitment_skills/views/hr_applicant_views.xml
  addons/hr_recruitment_survey/views/hr_job_views.xml
  addons/l10n_ec/models/account_move.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/loyalty/data/mail_template_data.xml
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp_account/models/product.py
  addons/mrp_account/tests/test_bom_price.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/search/filter_menu/custom_filter_item.js
  addons/web/static/tests/search/custom_filter_item_tests.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_hr_recruitment/models/hr_job.py
  addons/website_hr_recruitment/views/hr_recruitment_views.xml
  doc/cla/individual/nabilragab.md
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
  odoo/cli/cloc.py
  odoo/cli/command.py
  odoo/cli/db.py
  odoo/cli/deploy.py
  odoo/cli/genproxytoken.py
  odoo/cli/neutralize.py
  odoo/cli/populate.py
  odoo/cli/scaffold.py
  odoo/cli/server.py
  odoo/cli/shell.py
  odoo/cli/start.py
  odoo/cli/tsconfig.py
  odoo/modules/module.py
Labels: tmp.saas-16.2

#20148 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/modules/module.py
Labels: tmp.13.0

#20149 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/chart_template.py
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_profile/views/website_profile.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/modules/module.py
  odoo/tests/loader.py
Labels: tmp.14.0

#20150 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/l10n_lu/migrations/2.1/end-migrate_update_taxes.py
  addons/mail/models/mail_thread.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/legacy/scss/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/main.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_profile/views/website_profile.xml
  odoo/modules/module.py
Labels: tmp.15.0

#20151 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/__init__.py
  addons/loyalty/models/product_product.py
  addons/loyalty/models/product_template.py
  addons/mail/models/template_reset_mixin.py
  addons/mail/tests/test_mail_template.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/views/snippets_themes.xml
  addons/project_purchase/models/project.py
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_so_line_milestones.py
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/website/controllers/main.py
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_mass_mailing/tests/test_snippets.py
  odoo/addons/base/models/res_partner.py
  odoo/modules/module.py
Labels: tmp.16.0

#20152 Syncing from upstream odoo/odoo (14.0)
  addons/gamification/models/challenge.py
  addons/gamification/tests/test_challenge.py
  addons/point_of_sale/models/pos_config.py
  addons/stock/models/stock_orderpoint.py
  addons/website_form/static/src/snippets/s_website_form/000.js
  odoo/modules/module.py
Labels: 14.0

#20153 Syncing from upstream odoo/odoo (15.0)
  addons/mrp_subcontracting_account/models/product_product.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_backorder_confirmation.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/tests/loader.py
Labels: 15.0

#20154 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_early_payment_discount.py
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/static/src/components/bom_overview_components_block/mrp_bom_overview_components_block.xml
  addons/mrp_subcontracting/static/src/components/bom_overview_special_line/mrp_bom_overview_special_line.xml
  addons/point_of_sale/static/src/js/ChromeWidgets/CashMoveButton.js
  addons/point_of_sale/static/src/xml/Popups/CashMoveReceipt.xml
  addons/pos_daily_sales_reports/static/src/xml/SaleDetailsReport.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_actions_report.py
Labels: 16.0

#20156 Syncing from upstream odoo/odoo (saas-15.2)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/mrp_subcontracting_account/models/product_product.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/tests/loader.py
Labels: saas-15.2

#20157 Syncing from upstream odoo/odoo (saas-16.1)
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/sale/models/sale_order_line.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-16.1

#20158 Syncing from upstream odoo/odoo (saas-16.2)
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/l10n_ec/data/template/account.tax-ec.csv
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/project_purchase/models/project.py
  addons/sale/models/sale_order_line.py
  addons/sale_project/models/project.py
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/utils.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-16.2

#20161 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/sale/models/sale_order_line.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.saas-16.1

#20167 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/mrp_subcontracting_account/models/product_product.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/tests/loader.py
Labels: tmp.saas-15.2

#20168 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/sale/models/sale_order_line.py
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-16.1

#20169 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/event/models/event_mail.py
  addons/event/tests/test_event_flow.py
  addons/l10n_ec/data/template/account.tax-ec.csv
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/project_purchase/models/project.py
  addons/sale/models/sale_order_line.py
  addons/sale_project/models/project.py
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/utils.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/website/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-16.2

#20171 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/mrp_subcontracting_account/models/product_product.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/wizard/stock_backorder_confirmation.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/tests/loader.py
Labels: tmp.15.0

#20172 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_early_payment_discount.py
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/static/src/components/bom_overview_components_block/mrp_bom_overview_components_block.xml
  addons/mrp_subcontracting/static/src/components/bom_overview_special_line/mrp_bom_overview_special_line.xml
  addons/point_of_sale/static/src/js/ChromeWidgets/CashMoveButton.js
  addons/point_of_sale/static/src/xml/Popups/CashMoveReceipt.xml
  addons/pos_daily_sales_reports/static/src/xml/SaleDetailsReport.xml
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/views/graph_view_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.16.0

#20177 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/it.po
  addons/account_edi_ubl_cii/i18n/uk.po
  addons/crm/i18n/it.po
  addons/mass_mailing/i18n/it.po
  addons/mrp/i18n/es.po
  addons/payment/i18n/it.po
  addons/point_of_sale/i18n/it.po
  addons/pos_adyen/i18n/es_MX.po
  addons/pos_restaurant/i18n/es_MX.po
  addons/pos_six/i18n/it.po
  addons/product_expiry/i18n/es_MX.po
  addons/purchase_stock/i18n/es_MX.po
  addons/resource/i18n/es_MX.po
  addons/resource/i18n/it.po
  addons/sale/i18n/es_MX.po
  addons/sale/i18n/it.po
  addons/sale/i18n/zh_CN.po
  addons/sale_mrp/i18n/it.po
  addons/stock/i18n/es.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/utm/i18n/it.po
  addons/web/i18n/es.po
  addons/website/i18n/it.po
  addons/website_forum/i18n/it.po
  addons/website_sale/i18n/it.po
  addons/website_sale_stock/i18n/it.po
  addons/website_slides/i18n/it.po
  odoo/addons/base/i18n/it.po
Labels: saas-15.2

#20180 Syncing from upstream odoo/odoo (16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: 16.0

#20188 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/it.po
  addons/account_edi_ubl_cii/i18n/uk.po
  addons/crm/i18n/it.po
  addons/mass_mailing/i18n/it.po
  addons/mrp/i18n/es.po
  addons/payment/i18n/it.po
  addons/point_of_sale/i18n/it.po
  addons/pos_adyen/i18n/es_MX.po
  addons/pos_restaurant/i18n/es_MX.po
  addons/pos_six/i18n/it.po
  addons/product_expiry/i18n/es_MX.po
  addons/purchase_stock/i18n/es_MX.po
  addons/resource/i18n/es_MX.po
  addons/resource/i18n/it.po
  addons/sale/i18n/es_MX.po
  addons/sale/i18n/it.po
  addons/sale/i18n/zh_CN.po
  addons/sale_mrp/i18n/it.po
  addons/stock/i18n/es.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/utm/i18n/it.po
  addons/web/i18n/es.po
  addons/website/i18n/it.po
  addons/website_forum/i18n/it.po
  addons/website_sale/i18n/it.po
  addons/website_sale_stock/i18n/it.po
  addons/website_slides/i18n/it.po
  odoo/addons/base/i18n/it.po
Labels: tmp.saas-15.2

#20193 Syncing from upstream odoo/odoo (14.0)
  addons/website/static/src/js/editor/wysiwyg_multizone_translate.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/tests/tours/rte.js
Labels: 14.0

#20194 Syncing from upstream odoo/odoo (15.0)
  addons/crm/__manifest__.py
  addons/crm/static/src/js/forecast_graph_legacy.js
  addons/gamification/models/challenge.py
  addons/gamification/tests/test_challenge.py
  addons/point_of_sale/models/pos_config.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_website_form/000.js
Labels: 15.0

#20195 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.js
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/hr_timesheet/static/src/js/task_with_hours.js
  addons/hr_timesheet/static/src/js/timesheet_field_many2one.js
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/l10n_lu/migrations/2.1/end-migrate_update_taxes.py
  addons/mail/static/src/models/chat_window_manager.js
  addons/mail/static/src/models/discuss_public_view.js
  addons/mail/static/src/models/messaging.js
  addons/mrp/static/src/views/fields/google_slides_viewer.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.js
  addons/payment_alipay/controllers/main.py
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/models/pos_config.py
  addons/project/models/project.py
  addons/resource/static/src/section_one2many_field.js
  addons/stock/static/src/views/picking_form/stock_move_one2many.js
  addons/survey/static/src/question_page/question_page_one2many_field.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/website/models/ir_http.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_forum/models/forum.py
  addons/website_slides/__manifest__.py
  addons/website_slides/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: 16.0

#20197 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/point_of_sale/models/pos_config.py
  addons/pos_restaurant/static/src/js/Screens/TicketScreen.js
  addons/pos_restaurant/static/tests/tours/refund.tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/000.js
  odoo/addons/base/tests/test_image.py
  odoo/tools/image.py
Labels: saas-15.2

#20198 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account/tests/test_early_payment_discount.py
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/product.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/views/product_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/purchase_mrp/report/mrp_report_bom_structure.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_mass_mailing/tests/test_snippets.py
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: saas-16.1

#20199 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/wizard/account_move_send.py
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/point_of_sale/models/pos_config.py
  addons/project/static/src/components/project_task_state_selection/project_task_state_selection.js
  addons/project/static/src/components/project_task_state_selection/project_task_state_selection.scss
  addons/project/static/src/components/project_task_state_selection/project_task_state_selection.xml
  addons/sale/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_mass_mailing/tests/test_snippets.py
  addons/website_sale/tests/test_sale_process.py
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: saas-16.2

#20202 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account/tests/test_early_payment_discount.py
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/product.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/views/product_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/purchase_mrp/report/mrp_report_bom_structure.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_mass_mailing/tests/test_snippets.py
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: staging.saas-16.1

#20208 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_vat/models/res_partner.py
  addons/point_of_sale/models/pos_config.py
  addons/pos_restaurant/static/src/js/Screens/TicketScreen.js
  addons/pos_restaurant/static/tests/tours/refund.tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/000.js
  odoo/addons/base/tests/test_image.py
  odoo/tools/image.py
Labels: tmp.saas-15.2

#20209 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account/tests/test_early_payment_discount.py
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/l10n_ec/data/account_tax_template_vat_data.xml
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/product.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/views/product_views.xml
  addons/point_of_sale/models/pos_config.py
  addons/purchase_mrp/report/mrp_report_bom_structure.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale/models/sale_order.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_mass_mailing/tests/test_snippets.py
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: tmp.saas-16.1

#20210 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_line_tax_details.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/wizard/account_move_send.py
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/l10n_jp/__manifest__.py
  addons/l10n_jp/migrations/2.3/pre-migrate.py
  addons/point_of_sale/models/pos_config.py
  addons/project/static/src/components/project_task_state_selection/project_task_state_selection.js
  addons/project/static/src/components/project_task_state_selection/project_task_state_selection.scss
  addons/project/static/src/components/project_task_state_selection/project_task_state_selection.xml
  addons/sale/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/wizard/stock_backorder_confirmation.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/navbar/navbar.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/src/webclient/navbar/navbar.xml
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web/static/tests/webclient/navbar_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_mass_mailing/tests/test_snippets.py
  addons/website_sale/tests/test_sale_process.py
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: tmp.saas-16.2

#20213 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.js
  addons/base_vat/models/res_partner.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/hr_timesheet/static/src/js/task_with_hours.js
  addons/hr_timesheet/static/src/js/timesheet_field_many2one.js
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
  addons/l10n_lu/migrations/2.1/end-migrate_update_taxes.py
  addons/mail/static/src/models/chat_window_manager.js
  addons/mail/static/src/models/discuss_public_view.js
  addons/mail/static/src/models/messaging.js
  addons/mrp/static/src/views/fields/google_slides_viewer.js
  addons/mrp/static/src/widgets/mrp_production_components_x2many.js
  addons/payment_alipay/controllers/main.py
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/models/pos_config.py
  addons/project/models/project.py
  addons/resource/static/src/section_one2many_field.js
  addons/stock/static/src/views/picking_form/stock_move_one2many.js
  addons/survey/static/src/question_page/question_page_one2many_field.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/webclient/actions/target_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/website/models/ir_http.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_forum/models/forum.py
  addons/website_slides/__manifest__.py
  addons/website_slides/static/src/client_actions/website_preview/website_preview.js
  odoo/addons/base/tests/test_image.py
  odoo/tests/loader.py
  odoo/tools/image.py
Labels: tmp.16.0

#20214 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/google_gmail_mixin.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/website/models/res_users.py
  addons/website/tests/test_res_users.py
  odoo/tools/_monkeypatches.py
Labels: 14.0

#20215 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/controllers/portal.py
  addons/sale/models/payment_transaction.py
  addons/sale/models/sale_order.py
  addons/web_editor/controllers/main.py
Labels: 15.0

#20216 Syncing from upstream odoo/odoo (16.0)
  addons/crm/models/ir_config_parameter.py
  addons/gamification/models/gamification_challenge.py
  addons/gamification/tests/test_challenge.py
  addons/hr_contract/data/hr_contract_demo.xml
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/mail/models/ir_model.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_uninstall.py
  addons/sale/controllers/portal.py
  addons/sale/models/sale_order.py
  addons/web_editor/controllers/main.py
  addons/website/controllers/main.py
  addons/website/static/src/scss/website.scss
  odoo/addons/base/models/ir_model.py
  odoo/fields.py
  odoo/modules/loading.py
Labels: 16.0

#20218 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/gamification/models/gamification_challenge.py
  addons/gamification/tests/test_challenge.py
  addons/sale/controllers/portal.py
  addons/sale/models/payment_transaction.py
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web_editor/controllers/main.py
  addons/website/static/src/scss/website.scss
Labels: saas-15.2

#20225 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/google_gmail_mixin.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/website/models/res_users.py
  addons/website/tests/test_res_users.py
  odoo/tools/_monkeypatches.py
Labels: staging.14.0

#20229 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/gamification/models/gamification_challenge.py
  addons/gamification/tests/test_challenge.py
  addons/sale/controllers/portal.py
  addons/sale/models/payment_transaction.py
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web_editor/controllers/main.py
  addons/website/static/src/scss/website.scss
Labels: tmp.saas-15.2

#20232 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/google_gmail_mixin.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/controllers/portal.py
  addons/sale/models/sale.py
  addons/website/models/res_users.py
  addons/website/tests/test_res_users.py
  odoo/tools/_monkeypatches.py
Labels: tmp.14.0

#20233 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_rounding.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/controllers/portal.py
  addons/sale/models/payment_transaction.py
  addons/sale/models/sale_order.py
  addons/web_editor/controllers/main.py
Labels: tmp.15.0
