Repository brain-tec/odoo, pull requests merged in 2023-09, with the labels that each got.

#22563 Syncing from upstream odoo/odoo (13.0)
  odoo/addons/base/models/ir_module.py
Labels: 13.0

#22564 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hw_drivers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale_timesheet/models/account_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
Labels: 15.0

#22565 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_din5008/i18n/nl.po
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/controllers/portal.py
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/i18n/website.pot
  addons/website/static/src/js/form_editor_registry.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_event_sale/controllers/main.py
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
  doc/cla/individual/mostafamahmoud.md
  odoo/modules/module.py
Labels: 16.0

#22567 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/website_templates.xml
Labels: saas-15.2

#22568 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/l10n_din5008/i18n/nl.po
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale_crm/views/sale_order_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: saas-16.1

#22569 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/l10n_din5008/i18n/nl.po
  addons/l10n_din5008_purchase/i18n/nl.po
  addons/l10n_din5008_repair/i18n/nl.po
  addons/l10n_din5008_sale/i18n/nl.po
  addons/l10n_din5008_stock/i18n/nl.po
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/js/website_sale_delivery.js
  doc/cla/corporate/aardug.md
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: saas-16.2

#22570 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/l10n_din5008/i18n/nl.po
  addons/l10n_din5008_purchase/i18n/nl.po
  addons/l10n_din5008_repair/i18n/nl.po
  addons/l10n_din5008_sale/i18n/nl.po
  addons/l10n_din5008_stock/i18n/nl.po
  addons/l10n_ph/models/template_ph.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/barcode_reader_service.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_restaurant_stripe/static/src/js/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/product/models/product_template.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_product_configurator/tests/test_product_configurator_data.py
  addons/sale_stock/models/stock.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  doc/cla/corporate/aardug.md
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: saas-16.3

#22571 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/im_livechat/__manifest__.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/static/src/embed/boot_helpers.js
  addons/im_livechat/static/src/embed/core/message_model_patch.js
  addons/l10n_din5008/i18n/nl.po
  addons/mrp/data/mrp_data.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/static/src/app/store/product_configurator_popup/product_configurator_popup.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_online_payment/static/src/app/screens/payment_screen/payment_screen.js
  addons/pos_restaurant_stripe/static/src/js/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/product/models/product_template.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_product_configurator/tests/test_product_configurator_data.py
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
  odoo/tests/common.py
Labels: saas-16.4

#22574 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/l10n_din5008/i18n/nl.po
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale_crm/views/sale_order_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: staging.saas-16.1

#22578 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/addons/base/models/ir_module.py
Labels: staging.13.0

#22583 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/website_templates.xml
Labels: tmp.saas-15.2

#22584 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/l10n_din5008/i18n/nl.po
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale_crm/views/sale_order_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: tmp.saas-16.1

#22585 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/l10n_din5008/i18n/nl.po
  addons/l10n_din5008_purchase/i18n/nl.po
  addons/l10n_din5008_repair/i18n/nl.po
  addons/l10n_din5008_sale/i18n/nl.po
  addons/l10n_din5008_stock/i18n/nl.po
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/js/website_sale_delivery.js
  doc/cla/corporate/aardug.md
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: tmp.saas-16.2

#22586 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/l10n_din5008/i18n/nl.po
  addons/l10n_din5008_purchase/i18n/nl.po
  addons/l10n_din5008_repair/i18n/nl.po
  addons/l10n_din5008_sale/i18n/nl.po
  addons/l10n_din5008_stock/i18n/nl.po
  addons/l10n_ph/models/template_ph.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/barcode_reader_service.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_restaurant_stripe/static/src/js/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/product/models/product_template.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_product_configurator/tests/test_product_configurator_data.py
  addons/sale_stock/models/stock.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  doc/cla/corporate/aardug.md
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
Labels: tmp.saas-16.3

#22587 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/im_livechat/__manifest__.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/static/src/embed/boot_helpers.js
  addons/im_livechat/static/src/embed/core/message_model_patch.js
  addons/l10n_din5008/i18n/nl.po
  addons/mrp/data/mrp_data.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/static/src/app/store/product_configurator_popup/product_configurator_popup.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/nginx_ap.conf
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/nginx/sites-enabled/default
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/rc.local
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_online_payment/static/src/app/screens/payment_screen/payment_screen.js
  addons/pos_restaurant_stripe/static/src/js/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/product/models/product_template.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_product_configurator/tests/test_product_configurator_data.py
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  doc/cla/individual/mostafamahmoud.md
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_ir_actions.py
  odoo/addons/test_new_api/tests/__init__.py
  odoo/addons/test_new_api/tests/test_views.py
  odoo/tests/common.py
Labels: tmp.saas-16.4

#22588 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/addons/base/models/ir_module.py
Labels: tmp.13.0

#22589 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hw_drivers/main.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale_timesheet/models/account_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
Labels: tmp.15.0

#22590 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_din5008/i18n/nl.po
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/controllers/portal.py
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website/i18n/website.pot
  addons/website/static/src/js/form_editor_registry.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_event_sale/controllers/main.py
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
  doc/cla/individual/mostafamahmoud.md
  odoo/modules/module.py
Labels: tmp.16.0

#22591 Syncing from upstream odoo/odoo (13.0)
  odoo/addons/base/models/ir_module.py
Labels: 13.0

#22592 Syncing from upstream odoo/odoo (14.0)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/crm/tests/test_crm_pls.py
  addons/event/models/event_registration.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_res_partner.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/survey/wizard/survey_invite.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_mail_tools.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/website_crm/views/website_visitor_views.xml
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: 14.0

#22593 Syncing from upstream odoo/odoo (15.0)
  addons/sale_product_configurator/static/src/js/product_configurator_widget.js
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/website_crm/views/website_visitor_views.xml
  odoo/addons/base/models/ir_module.py
Labels: 15.0

#22596 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale_timesheet/models/account_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/models/ir_module.py
Labels: saas-15.2

#22597 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale_timesheet/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/ir_http.py
  addons/website/static/src/js/form_editor_registry.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_event_sale/controllers/main.py
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: saas-16.1

#22598 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/chart_template.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/mrp/models/stock_rule.py
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/project/report/project_report.py
  addons/project/tests/test_project_report.py
  addons/sale_crm/views/sale_order_views.xml
  addons/sale_timesheet/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/ir_http.py
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_event_sale/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: saas-16.2

#22600 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/static/src/components/account_payment_field/account_payment.xml
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/account_move_views.xml
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/fleet/models/fleet_vehicle_model.py
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/mrp/data/mrp_data.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/views/project_project_views.xml
  addons/sale_crm/views/sale_order_views.xml
  addons/sale_timesheet/models/sale_order.py
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/views/fields/binary/binary_field.xml
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/core/datetime/datetime_picker_tests.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_event_sale/controllers/main.py
  addons/website_payment/controllers/portal.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_sale/static/src/js/website_sale_delivery.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
  odoo/tools/mail.py
Labels: saas-16.4

#22603 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale_timesheet/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/ir_http.py
  addons/website/static/src/js/form_editor_registry.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_event_sale/controllers/main.py
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: staging.saas-16.1

#22607 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/addons/base/models/ir_module.py
Labels: staging.13.0

#22608 Syncing from upstream odoo/odoo (staging.14.0)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/crm/tests/test_crm_pls.py
  addons/event/models/event_registration.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_res_partner.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/survey/wizard/survey_invite.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_mail_tools.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/website_crm/views/website_visitor_views.xml
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: staging.14.0

#22612 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/sale_timesheet/models/account_move.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  odoo/addons/base/models/ir_module.py
Labels: tmp.saas-15.2

#22613 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale_timesheet/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/models/ir_http.py
  addons/website/static/src/js/form_editor_registry.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_event_sale/controllers/main.py
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.saas-16.1

#22614 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/chart_template.py
  addons/account/views/res_config_settings_views.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/mrp/models/stock_rule.py
  addons/payment_stripe/i18n/payment_stripe.pot
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/src/xml/Screens/ReceiptScreen/OrderReceipt.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/project/report/project_report.py
  addons/project/tests/test_project_report.py
  addons/sale_crm/views/sale_order_views.xml
  addons/sale_timesheet/models/account_move.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/models/ir_http.py
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_event_sale/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.saas-16.2

#22616 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/static/src/components/account_payment_field/account_payment.xml
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/account_move_views.xml
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/static/src/import_model.js
  addons/fleet/models/fleet_vehicle_model.py
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr/models/hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/mass_mailing/wizard/mailing_mailing_test.py
  addons/mrp/data/mrp_data.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/views/project_project_views.xml
  addons/sale_crm/views/sale_order_views.xml
  addons/sale_timesheet/models/sale_order.py
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/views/fields/binary/binary_field.xml
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/core/datetime/datetime_picker_tests.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/gray_color_palette.js
  addons/website_event_sale/controllers/main.py
  addons/website_payment/controllers/portal.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_sale/static/src/js/website_sale_delivery.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
  odoo/tools/mail.py
Labels: tmp.saas-16.4

#22617 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/addons/base/models/ir_module.py
Labels: tmp.13.0

#22618 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/crm/tests/test_crm_pls.py
  addons/event/models/event_registration.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_channel.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_res_partner.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/survey/wizard/survey_invite.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_mail_tools.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/website_crm/views/website_visitor_views.xml
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: tmp.14.0

#22619 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/sale_product_configurator/static/src/js/product_configurator_widget.js
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/website_crm/views/website_visitor_views.xml
  odoo/addons/base/models/ir_module.py
Labels: tmp.15.0

#22624 Syncing from upstream odoo/odoo (master)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
Labels: master

#22626 Syncing from upstream odoo/odoo (saas-16.1)
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it/data/account.fiscal.position.template.csv
  addons/l10n_it/data/account.tax.group.csv
  addons/l10n_it/data/account_fiscal_position_tax_template_data.xml
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/l10n_it/migrations/16.0.0.4/end-migrate_update_taxes.py
  addons/l10n_it/models/account_chart_template.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/expected_xmls/split_payment.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_pa/__init__.py
  addons/l10n_it_edi_pa/__manifest__.py
  addons/l10n_it_edi_pa/i18n/it.po
  addons/l10n_it_edi_pa/i18n/l10n_it_edi_pa.pot
  addons/l10n_it_edi_pa/models/__init__.py
  addons/l10n_it_edi_pa/models/account_edi_format.py
  addons/l10n_it_edi_pa/models/account_move.py
  addons/l10n_it_edi_pa/tests/__init__.py
  addons/l10n_it_edi_pa/tests/test_edi_pa.py
  addons/l10n_it_edi_pa/views/account_move_view.xml
  addons/l10n_it_edi_pa/views/report_invoice.xml
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_it_stock_ddt/tests/test_ddt.py
Labels: saas-16.1

#22627 Syncing from upstream odoo/odoo (saas-16.2)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: saas-16.2

#22628 Syncing from upstream odoo/odoo (saas-16.3)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: saas-16.3

#22632 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it/data/account.fiscal.position.template.csv
  addons/l10n_it/data/account.tax.group.csv
  addons/l10n_it/data/account_fiscal_position_tax_template_data.xml
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/l10n_it/migrations/16.0.0.4/end-migrate_update_taxes.py
  addons/l10n_it/models/account_chart_template.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/expected_xmls/split_payment.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_pa/__init__.py
  addons/l10n_it_edi_pa/__manifest__.py
  addons/l10n_it_edi_pa/i18n/it.po
  addons/l10n_it_edi_pa/i18n/l10n_it_edi_pa.pot
  addons/l10n_it_edi_pa/models/__init__.py
  addons/l10n_it_edi_pa/models/account_edi_format.py
  addons/l10n_it_edi_pa/models/account_move.py
  addons/l10n_it_edi_pa/tests/__init__.py
  addons/l10n_it_edi_pa/tests/test_edi_pa.py
  addons/l10n_it_edi_pa/views/account_move_view.xml
  addons/l10n_it_edi_pa/views/report_invoice.xml
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_it_stock_ddt/tests/test_ddt.py
Labels: staging.saas-16.1

#22638 Syncing from upstream odoo/odoo (tmp.master)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
Labels: tmp.master

#22639 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: tmp.saas-15.2

#22640 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it/data/account.fiscal.position.template.csv
  addons/l10n_it/data/account.tax.group.csv
  addons/l10n_it/data/account_fiscal_position_tax_template_data.xml
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/account_tax_template.xml
  addons/l10n_it/migrations/16.0.0.4/end-migrate_update_taxes.py
  addons/l10n_it/models/account_chart_template.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/expected_xmls/split_payment.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_pa/__init__.py
  addons/l10n_it_edi_pa/__manifest__.py
  addons/l10n_it_edi_pa/i18n/it.po
  addons/l10n_it_edi_pa/i18n/l10n_it_edi_pa.pot
  addons/l10n_it_edi_pa/models/__init__.py
  addons/l10n_it_edi_pa/models/account_edi_format.py
  addons/l10n_it_edi_pa/models/account_move.py
  addons/l10n_it_edi_pa/tests/__init__.py
  addons/l10n_it_edi_pa/tests/test_edi_pa.py
  addons/l10n_it_edi_pa/views/account_move_view.xml
  addons/l10n_it_edi_pa/views/report_invoice.xml
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/l10n_it_stock_ddt/tests/test_ddt.py
Labels: tmp.saas-16.1

#22641 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: tmp.saas-16.2

#22642 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: tmp.saas-16.3

#22643 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/barcode/barcode_reader_service.js
  addons/point_of_sale/static/tests/tours/BarcodeScanning.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
Labels: tmp.saas-16.4

#22644 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: tmp.15.0

#22645 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
Labels: tmp.16.0

#22646 Syncing from upstream odoo/odoo (14.0)
  doc/cla/corporate/dec.md
  odoo/addons/base/data/rtlcss.json
  odoo/addons/base/models/assetsbundle.py
Labels: 14.0

#22647 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/web_editor/static/src/scss/wysiwyg.scss
  odoo/addons/base/data/rtlcss.json
  odoo/addons/base/models/assetsbundle.py
Labels: 15.0

#22648 Syncing from upstream odoo/odoo (16.0)
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/web_editor/controllers/main.py
  addons/website_sale/models/product_template.py
  addons/website_sale/static/tests/tours/website_sale_shop_compare_list_price_pricelist.js
  addons/website_sale/tests/test_website_sale_show_compare_list_price.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/rtlcss.json
  odoo/addons/base/models/assetsbundle.py
Labels: 16.0

#22650 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/de.po
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_product_configurator/static/src/js/product_configurator_widget.js
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/web_editor/controllers/main.py
  odoo/addons/base/data/rtlcss.json
  odoo/addons/base/models/assetsbundle.py
Labels: saas-15.2

#22654 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/views/res_config_settings_views.xml
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/controllers/main.py
  odoo/addons/base/data/rtlcss.json
  odoo/addons/base/models/assetsbundle.py
Labels: saas-16.4

#22673 Syncing from upstream odoo/odoo (15.0)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/event/models/event_registration.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_mail_tools.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/project/models/project.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/options.js
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: 15.0

#22674 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_payment/controllers/payment.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale/controllers/portal.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/tests/views/fields/html_field_tests.js
  addons/website_payment/controllers/portal.py
Labels: 16.0

#22676 Syncing from upstream odoo/odoo (saas-15.2)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/event/models/event_registration.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_mail_tools.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/sale_timesheet/models/account.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/options.js
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: saas-15.2

#22677 Syncing from upstream odoo/odoo (saas-16.1)
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/microsoft_calendar/models/calendar.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/models/payment_transaction.py
  addons/website/models/website_visitor.py
Labels: saas-16.1

#22678 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/views/account_journal_dashboard_view.xml
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/template/account.account-it.csv
  addons/l10n_it/data/template/account.fiscal.position-it.csv
  addons/l10n_it/data/template/account.tax-it.csv
  addons/l10n_it/data/template/account.tax.group-it.csv
  addons/l10n_it/models/account_chart_template.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/export_xmls/split_payment.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_pa/__init__.py
  addons/l10n_it_edi_pa/__manifest__.py
  addons/l10n_it_edi_pa/i18n/it.po
  addons/l10n_it_edi_pa/i18n/l10n_it_edi_pa.pot
  addons/l10n_it_edi_pa/models/__init__.py
  addons/l10n_it_edi_pa/models/account_edi_format.py
  addons/l10n_it_edi_pa/models/account_move.py
  addons/l10n_it_edi_pa/tests/__init__.py
  addons/l10n_it_edi_pa/tests/test_edi_pa.py
  addons/l10n_it_edi_pa/views/account_move_view.xml
  addons/l10n_it_edi_pa/views/report_invoice.xml
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_mn/__manifest__.py
  addons/l10n_mn/data/account.account.tag.csv
  addons/l10n_mn/data/template/account.account-mn.csv
  addons/l10n_mn/data/template/account.fiscal.position-mn.csv
  addons/l10n_mn/data/template/account.tax-mn.csv
  addons/l10n_mn/i18n/l10n_mn.pot
  addons/l10n_mn/i18n/mn.po
  addons/l10n_mn/models/template_mn.py
  addons/microsoft_calendar/models/calendar.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/static/src/js/sale_product_field.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/src/views/pivot/pivot_renderer.xml
  addons/web/static/src/views/pivot/pivot_view.scss
  addons/website/i18n/website.pot
  addons/website/static/src/js/form_editor_registry.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
Labels: saas-16.2

#22680 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/im_livechat/static/src/embed/chatbot/chatbot_service.js
  addons/im_livechat/static/src/embed/core/livechat_service.js
  addons/im_livechat/tests/test_im_livechat_support_page.py
  addons/im_livechat/views/im_livechat_chatbot_templates.xml
  addons/l10n_ar/security/ir.model.access.csv
  addons/l10n_latam_base/security/ir.model.access.csv
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users.py
  addons/mail/static/src/core/common/chat_window.scss
  addons/mail/static/src/core/common/chat_window.xml
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/common/messaging_service.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/web/chatter.js
  addons/mail/static/src/core/web/follower_subtype_dialog.js
  addons/mail/static/src/core/web/recipient_list.js
  addons/mail/static/src/core/web/recipient_list.xml
  addons/mail/static/src/core/web/thread_model_patch.js
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/static/tests/helpers/mock_server/models/mail_thread.js
  addons/mail/static/tests/web/follower_list_menu_tests.js
  addons/mail/tests/discuss/test_load_messages.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/account_move.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/models/payment_transaction.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/i18n/website.pot
  addons/website/models/ir_http.py
  addons/website/models/website_visitor.py
  addons/website/static/src/js/send_mail_form.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_livechat/controllers/chatbot.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
Labels: saas-16.4

#22683 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/microsoft_calendar/models/calendar.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/models/payment_transaction.py
Labels: staging.saas-16.1

#22691 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/event/models/event_registration.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_mail_tools.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/project/models/project.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_purchase_lead_time.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/sale_timesheet/models/account.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/options.js
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: tmp.saas-15.2

#22692 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/microsoft_calendar/models/calendar.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/models/payment_transaction.py
  addons/website/models/website_visitor.py
Labels: tmp.saas-16.1

#22693 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/views/account_journal_dashboard_view.xml
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/template/account.account-it.csv
  addons/l10n_it/data/template/account.fiscal.position-it.csv
  addons/l10n_it/data/template/account.tax-it.csv
  addons/l10n_it/data/template/account.tax.group-it.csv
  addons/l10n_it/models/account_chart_template.py
  addons/l10n_it_edi/data/account_invoice_demo.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_edi_format.py
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/export_xmls/split_payment.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_it_edi_pa/__init__.py
  addons/l10n_it_edi_pa/__manifest__.py
  addons/l10n_it_edi_pa/i18n/it.po
  addons/l10n_it_edi_pa/i18n/l10n_it_edi_pa.pot
  addons/l10n_it_edi_pa/models/__init__.py
  addons/l10n_it_edi_pa/models/account_edi_format.py
  addons/l10n_it_edi_pa/models/account_move.py
  addons/l10n_it_edi_pa/tests/__init__.py
  addons/l10n_it_edi_pa/tests/test_edi_pa.py
  addons/l10n_it_edi_pa/views/account_move_view.xml
  addons/l10n_it_edi_pa/views/report_invoice.xml
  addons/l10n_it_edi_withholding/models/account_edi_format.py
  addons/l10n_it_stock_ddt/tests/test_ddt.py
  addons/l10n_mn/__manifest__.py
  addons/l10n_mn/data/account.account.tag.csv
  addons/l10n_mn/data/template/account.account-mn.csv
  addons/l10n_mn/data/template/account.fiscal.position-mn.csv
  addons/l10n_mn/data/template/account.tax-mn.csv
  addons/l10n_mn/i18n/l10n_mn.pot
  addons/l10n_mn/i18n/mn.po
  addons/l10n_mn/models/template_mn.py
  addons/microsoft_calendar/models/calendar.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/static/src/js/sale_product_field.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/src/views/pivot/pivot_renderer.xml
  addons/web/static/src/views/pivot/pivot_view.scss
  addons/website/i18n/website.pot
  addons/website/static/src/js/form_editor_registry.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_mass_mailing/static/src/js/mass_mailing_form_editor.js
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
Labels: tmp.saas-16.2

#22695 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/im_livechat/static/src/embed/chatbot/chatbot_service.js
  addons/im_livechat/static/src/embed/core/livechat_service.js
  addons/im_livechat/tests/test_im_livechat_support_page.py
  addons/im_livechat/views/im_livechat_chatbot_templates.xml
  addons/l10n_ar/security/ir.model.access.csv
  addons/l10n_latam_base/security/ir.model.access.csv
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users.py
  addons/mail/static/src/core/common/chat_window.scss
  addons/mail/static/src/core/common/chat_window.xml
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/common/messaging_service.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/web/chatter.js
  addons/mail/static/src/core/web/follower_subtype_dialog.js
  addons/mail/static/src/core/web/recipient_list.js
  addons/mail/static/src/core/web/recipient_list.xml
  addons/mail/static/src/core/web/thread_model_patch.js
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/helpers/mock_server/controllers/discuss.js
  addons/mail/static/tests/helpers/mock_server/models/mail_thread.js
  addons/mail/static/tests/web/follower_list_menu_tests.js
  addons/mail/tests/discuss/test_load_messages.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/models/account_move.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/models/payment_transaction.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_redirect.py
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/i18n/website.pot
  addons/website/models/ir_http.py
  addons/website/models/website_visitor.py
  addons/website/static/src/js/send_mail_form.js
  addons/website_crm/i18n/website_crm.pot
  addons/website_crm/static/src/js/website_crm_editor.js
  addons/website_form_project/i18n/website_form_project.pot
  addons/website_form_project/static/src/js/website_form_project_editor.js
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/static/src/js/website_hr_recruitment_editor.js
  addons/website_livechat/controllers/chatbot.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/static/src/js/website_sale_form_editor.js
Labels: tmp.saas-16.4

#22696 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_notification.py
  addons/event/models/event_registration.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/models/mail_thread.py
  addons/mail/models/mail_thread_blacklist.py
  addons/mail/models/models.py
  addons/mail/static/src/js/utils.js
  addons/mail/tests/test_mail_tools.py
  addons/mail/tests/test_res_partner.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mailing_contact.py
  addons/mass_mailing/tests/common.py
  addons/project/models/project.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/__init__.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_mail.py
  addons/test_mail/tests/test_mail_thread_mixins.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website/static/src/snippets/s_table_of_content/options.js
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_expression.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: tmp.15.0

#22697 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_payment/controllers/payment.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale/controllers/portal.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/tests/views/fields/html_field_tests.js
  addons/website_payment/controllers/portal.py
Labels: tmp.16.0

#22698 Syncing from upstream odoo/odoo (14.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/portal/static/src/scss/portal.scss
  addons/sale_timesheet/models/project.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: 14.0

#22699 Syncing from upstream odoo/odoo (15.0)
  addons/calendar/models/calendar_event.py
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: 15.0

#22702 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/hw_drivers/main.py
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: saas-15.2

#22704 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account_payment/controllers/payment.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/models/google_sync.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/hw_drivers/main.py
  addons/l10n_es_edi_tbai/tests/common.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale/controllers/portal.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/html_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website/views/snippets/s_mega_menu_odoo_menu.xml
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/website_templates.xml
  addons/website_payment/controllers/portal.py
Labels: saas-16.2

#22713 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/portal/static/src/scss/portal.scss
  addons/sale_timesheet/models/project.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: staging.14.0

#22717 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/hw_drivers/main.py
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/point_of_sale/static/src/js/models.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.saas-15.2

#22719 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account_payment/controllers/payment.py
  addons/calendar/models/calendar_recurrence.py
  addons/google_calendar/models/google_sync.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/hw_drivers/main.py
  addons/l10n_es_edi_tbai/tests/common.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/calendar_recurrence_rule.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_rule.py
  addons/sale/controllers/portal.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_purchase.py
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/html_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/tests/tours/snippet_social_media.js
  addons/website/views/snippets/s_mega_menu_odoo_menu.xml
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/website_templates.xml
  addons/website_payment/controllers/portal.py
Labels: tmp.saas-16.2

#22722 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/portal/static/src/scss/portal.scss
  addons/sale_timesheet/models/project.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.14.0

#22723 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/calendar/models/calendar_event.py
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.15.0

#22726 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_reconcile_model.py
  addons/delivery/models/stock_picking.py
  addons/hr_skills/data/hr.resume.line.csv
  addons/hr_skills/models/hr_resume.py
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_data.xml
  addons/l10n_mx/data/account_tax_data.xml
Labels: 14.0

#22727 Syncing from upstream odoo/odoo (15.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
Labels: 15.0

#22728 Syncing from upstream odoo/odoo (16.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/models/hr_employee.py
  addons/im_livechat/models/chatbot_script.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/stock/__init__.py
  addons/stock/__manifest__.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: 16.0

#22730 Syncing from upstream odoo/odoo (saas-15.2)
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: saas-15.2

#22731 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/views/resource_views.xml
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: saas-16.1

#22732 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/template_generic_coa.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/views/resource_views.xml
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_bo/models/template_bo.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_cz/models/template_cz.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/template/account.account-de_skr03.csv
  addons/l10n_de_skr04/data/template/account.account-de_skr04.csv
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_dk/models/template_dk.py
  addons/l10n_ec/models/template_ec.py
  addons/l10n_eg/models/template_eg.py
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/l10n_fi/models/template_fi.py
  addons/l10n_jp/models/template_jp.py
  addons/l10n_no/models/template_no.py
  addons/l10n_pe/models/template_pe.py
  addons/l10n_pt/models/template_pt.py
  addons/l10n_sk/models/template_sk.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/views/delivery_view.xml
  addons/web/static/src/core/utils/binary.js
  addons/web/static/src/views/fields/binary/binary_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: saas-16.2

#22733 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/static/src/emoji_picker/emoji_picker.js
  addons/mail/static/tests/emoji/emoji_tests.js
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/tests/test_project.py
  addons/web/static/src/core/utils/binary.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/binary/binary_field.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/views/snippets/s_mega_menu_odoo_menu.xml
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/website_templates.xml
  addons/website_event_track/static/src/js/service_worker.js
Labels: saas-16.3

#22734 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_recruitment/static/applicant_cvs/Cecile_Donth_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/David_Armstrong_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/David_Billy_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Enrique_Jones_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Hubert_Blank_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Johan_Duck_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/John_Bruno_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Joren_Jacob_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Jose_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Kelly_Wallant_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Marie_Justine_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Sandra_Elvis_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Shane_Williams_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Tina_Augustie_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Yin_Lee_CV.pdf
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/static/src/core/common/message_service.js
  addons/mail/static/src/core/web/sidebar.js
  addons/mail/static/src/utils/common/hooks.js
  addons/mail/static/tests/discuss_app/sidebar_tests.js
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/repair/models/stock_picking.py
  addons/sale_project/models/product.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/tests/test_project.py
  addons/web/static/src/core/utils/binary.js
  addons/web/static/src/views/fields/binary/binary_field.js
  addons/web/static/src/views/fields/field.js
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: saas-16.4

#22737 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/views/resource_views.xml
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: staging.saas-16.1

#22741 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_reconcile_model.py
  addons/delivery/models/stock_picking.py
  addons/hr_skills/data/hr.resume.line.csv
  addons/hr_skills/models/hr_resume.py
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_data.xml
  addons/l10n_mx/data/account_tax_data.xml
Labels: staging.14.0

#22745 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.saas-15.2

#22746 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/calendar/models/calendar_event.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/views/resource_views.xml
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/pos_daily_sales_reports/models/pos_daily_sales_reports.py
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: tmp.saas-16.1

#22747 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/template_generic_coa.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/views/resource_views.xml
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_bo/models/template_bo.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_cz/models/template_cz.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/template/account.account-de_skr03.csv
  addons/l10n_de_skr04/data/template/account.account-de_skr04.csv
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_dk/models/template_dk.py
  addons/l10n_ec/models/template_ec.py
  addons/l10n_eg/models/template_eg.py
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/l10n_fi/models/template_fi.py
  addons/l10n_jp/models/template_jp.py
  addons/l10n_no/models/template_no.py
  addons/l10n_pe/models/template_pe.py
  addons/l10n_pt/models/template_pt.py
  addons/l10n_sk/models/template_sk.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/views/delivery_view.xml
  addons/web/static/src/core/utils/binary.js
  addons/web/static/src/views/fields/binary/binary_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: tmp.saas-16.2

#22748 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/de.po
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/static/src/emoji_picker/emoji_picker.js
  addons/mail/static/tests/emoji/emoji_tests.js
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/purchase/i18n/de.po
  addons/sale/i18n/de.po
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/tests/test_project.py
  addons/web/static/src/core/utils/binary.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/binary/binary_field.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/views/snippets/s_mega_menu_odoo_menu.xml
  addons/website/views/snippets/s_social_media.xml
  addons/website/views/website_templates.xml
  addons/website_event_track/static/src/js/service_worker.js
Labels: tmp.saas-16.3

#22749 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_recruitment/static/applicant_cvs/Cecile_Donth_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/David_Armstrong_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/David_Billy_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Enrique_Jones_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Hubert_Blank_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Johan_Duck_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/John_Bruno_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Joren_Jacob_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Jose_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Kelly_Wallant_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Marie_Justine_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Sandra_Elvis_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Shane_Williams_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Tina_Augustie_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Yin_Lee_CV.pdf
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/models/hr_employee.py
  addons/hr_work_entry_contract/tests/test_global_time_off.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_holidays/tests/test_leave.py
  addons/hr_work_entry_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_payslip_holidays_computation.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/im_livechat/models/chatbot_script.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_es_edi_sii/__manifest__.py
  addons/l10n_es_edi_sii/views/account_move_views.xml
  addons/mail/static/src/core/common/message_service.js
  addons/mail/static/src/core/web/sidebar.js
  addons/mail/static/src/utils/common/hooks.js
  addons/mail/static/tests/discuss_app/sidebar_tests.js
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/repair/models/stock_picking.py
  addons/sale_project/models/product.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/tests/test_project.py
  addons/web/static/src/core/utils/binary.js
  addons/web/static/src/views/fields/binary/binary_field.js
  addons/web/static/src/views/fields/field.js
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/fields/binary_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
Labels: tmp.saas-16.4

#22750 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_reconcile_model.py
  addons/delivery/models/stock_picking.py
  addons/hr_skills/data/hr.resume.line.csv
  addons/hr_skills/models/hr_resume.py
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_data.xml
  addons/l10n_mx/data/account_tax_data.xml
Labels: tmp.14.0

#22751 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
Labels: tmp.15.0

#22752 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/base_geolocalize/models/base_geocoder.py
  addons/calendar/models/calendar_event.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/models/hr_employee.py
  addons/im_livechat/models/chatbot_script.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/models/user_setting.js
  addons/mail/tests/test_mail_tools.py
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/sale_project/models/product.py
  addons/sale_timesheet/models/account.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet_margin/models/sale_order_line.py
  addons/sale_timesheet_margin/tests/__init__.py
  addons/sale_timesheet_margin/tests/test_sale_timesheet_margin.py
  addons/stock/__init__.py
  addons/stock/__manifest__.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/scss/wysiwyg.scss
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.16.0

#22725 [bt#23810] VAT Switz. 2024
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/l10n_ch/__manifest__.py
  addons/l10n_ch/data/account_fiscal_position_data.xml
  addons/l10n_ch/data/account_fiscal_position_data_2024.xml
  addons/l10n_ch/data/account_tax_group_data.xml
  addons/l10n_ch/data/account_tax_report_data.xml
  addons/l10n_ch/data/account_tax_template_data_2024.xml
  addons/l10n_ch/data/account_vat2011_data.xml
  addons/l10n_ch/i18n/de.po
  addons/l10n_ch/i18n/fr.po
  addons/l10n_ch/i18n/it.po
  addons/l10n_ch/i18n/l10n_ch.pot
  addons/l10n_ch/migrations/11.1/end-migrate_update_taxes.py
Labels: 16.0.project_me_665

#22753 Syncing from upstream odoo/odoo (14.0)
  addons/base_geolocalize/models/base_geocoder.py
Labels: 14.0

#22754 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_reconcile_model.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/coupon/views/coupon_program_views.xml
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: 15.0

#22755 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/l10n_pl/data/account_tax_report_data.xml
  addons/l10n_pl_jpk/__init__.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/l10n_pl_jpk/data/l10n_pl_tax_office.csv
  addons/l10n_pl_jpk/i18n/l10n_pl_jpk.pot
  addons/l10n_pl_jpk/i18n/pl.po
  addons/l10n_pl_jpk/models/__init__.py
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_pl_jpk/models/product.py
  addons/l10n_pl_jpk/models/res_company.py
  addons/l10n_pl_jpk/models/res_config_settings.py
  addons/l10n_pl_jpk/models/res_partner.py
  addons/l10n_pl_jpk/security/ir.model.access.csv
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/l10n_pl_jpk/views/product_views.xml
  addons/l10n_pl_jpk/views/report_invoice.xml
  addons/l10n_pl_jpk/views/res_config_settings_views.xml
  addons/l10n_pl_jpk/views/res_partner_views.xml
  addons/l10n_pl_sale_stock/__init__.py
  addons/l10n_pl_sale_stock/__manifest__.py
  addons/l10n_pl_sale_stock/models/__init__.py
  addons/l10n_pl_sale_stock/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/mrp_immediate_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/factorlibre.md
Labels: 16.0

#22757 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/bg.po
  addons/account/models/account_reconcile_model.py
  addons/base_automation/i18n/bg.po
  addons/base_geolocalize/models/base_geocoder.py
  addons/crm/i18n/bg.po
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/lunch/i18n/bg.po
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/mrp/i18n/bg.po
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/note/i18n/bg.po
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/stock/i18n/bg.po
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: saas-15.2

#22758 Syncing from upstream odoo/odoo (saas-16.1)
  addons/base_geolocalize/models/base_geocoder.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/l10n_pl/data/account_tax_report_data.xml
  addons/l10n_pl_jpk/__init__.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/l10n_pl_jpk/data/l10n_pl_tax_office.csv
  addons/l10n_pl_jpk/i18n/l10n_pl_jpk.pot
  addons/l10n_pl_jpk/i18n/pl.po
  addons/l10n_pl_jpk/models/__init__.py
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_pl_jpk/models/product.py
  addons/l10n_pl_jpk/models/res_company.py
  addons/l10n_pl_jpk/models/res_config_settings.py
  addons/l10n_pl_jpk/models/res_partner.py
  addons/l10n_pl_jpk/security/ir.model.access.csv
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/l10n_pl_jpk/views/product_views.xml
  addons/l10n_pl_jpk/views/report_invoice.xml
  addons/l10n_pl_jpk/views/res_config_settings_views.xml
  addons/l10n_pl_jpk/views/res_partner_views.xml
  addons/l10n_pl_sale_stock/__init__.py
  addons/l10n_pl_sale_stock/__manifest__.py
  addons/l10n_pl_sale_stock/models/__init__.py
  addons/l10n_pl_sale_stock/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: saas-16.1

#22760 Syncing from upstream odoo/odoo (saas-16.3)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/template/account.account-de_skr03.csv
  addons/l10n_de_skr04/data/template/account.account-de_skr04.csv
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core_ui/link_preview/link_preview_confirm_delete.js
  addons/mail/static/src/core_ui/link_preview/link_preview_confirm_delete.xml
  addons/mail/static/tests/message/link_preview_test.js
  addons/mail/tests/test_mail_tools.py
  addons/point_of_sale/static/tests/unit/pos_app_tests.js
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/views/delivery_view.xml
  addons/test_sale_product_configurators/static/tests/tours/product_configurator_edition_ui.js
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: saas-16.3

#22761 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account_peppol/__manifest__.py
  addons/account_peppol/demo/account_peppol_demo.xml
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/event/i18n/event.pot
  addons/event/models/event_registration.py
  addons/event/static/src/scss/event.scss
  addons/event/views/event_registration_views.xml
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_cl/models/account_move.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/link_preview_confirm_delete.js
  addons/mail/static/src/core/common/link_preview_confirm_delete.xml
  addons/mail/static/tests/emoji/emoji_tests.js
  addons/mail/static/tests/message/link_preview_test.js
  addons/mail/tests/test_mail_tools.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/views/delivery_view.xml
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/core/emoji_picker/emoji_picker.js
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website_event/models/event_registration.py
  addons/website_event/views/event_registration_views.xml
  addons/website_event_track/static/src/js/service_worker.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: saas-16.4

#22764 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/base_geolocalize/models/base_geocoder.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/l10n_pl/data/account_tax_report_data.xml
  addons/l10n_pl_jpk/__init__.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/l10n_pl_jpk/data/l10n_pl_tax_office.csv
  addons/l10n_pl_jpk/i18n/l10n_pl_jpk.pot
  addons/l10n_pl_jpk/i18n/pl.po
  addons/l10n_pl_jpk/models/__init__.py
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_pl_jpk/models/product.py
  addons/l10n_pl_jpk/models/res_company.py
  addons/l10n_pl_jpk/models/res_config_settings.py
  addons/l10n_pl_jpk/models/res_partner.py
  addons/l10n_pl_jpk/security/ir.model.access.csv
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/l10n_pl_jpk/views/product_views.xml
  addons/l10n_pl_jpk/views/report_invoice.xml
  addons/l10n_pl_jpk/views/res_config_settings_views.xml
  addons/l10n_pl_jpk/views/res_partner_views.xml
  addons/l10n_pl_sale_stock/__init__.py
  addons/l10n_pl_sale_stock/__manifest__.py
  addons/l10n_pl_sale_stock/models/__init__.py
  addons/l10n_pl_sale_stock/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: staging.saas-16.1

#22768 Syncing from upstream odoo/odoo (staging.14.0)
  addons/base_geolocalize/models/base_geocoder.py
Labels: staging.14.0

#22772 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/bg.po
  addons/account/models/account_reconcile_model.py
  addons/base_automation/i18n/bg.po
  addons/base_geolocalize/models/base_geocoder.py
  addons/crm/i18n/bg.po
  addons/hr_contract/i18n/bg.po
  addons/hr_holidays/i18n/bg.po
  addons/hr_recruitment/i18n/bg.po
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/lunch/i18n/bg.po
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/mrp/i18n/bg.po
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/note/i18n/bg.po
  addons/point_of_sale/i18n/bg.po
  addons/project/i18n/bg.po
  addons/purchase_requisition/i18n/bg.po
  addons/sale/i18n/bg.po
  addons/stock/i18n/bg.po
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/survey/i18n/bg.po
  addons/web/i18n/bg.po
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: tmp.saas-15.2

#22773 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/base_geolocalize/models/base_geocoder.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/l10n_pl/data/account_tax_report_data.xml
  addons/l10n_pl_jpk/__init__.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/l10n_pl_jpk/data/l10n_pl_tax_office.csv
  addons/l10n_pl_jpk/i18n/l10n_pl_jpk.pot
  addons/l10n_pl_jpk/i18n/pl.po
  addons/l10n_pl_jpk/models/__init__.py
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_pl_jpk/models/product.py
  addons/l10n_pl_jpk/models/res_company.py
  addons/l10n_pl_jpk/models/res_config_settings.py
  addons/l10n_pl_jpk/models/res_partner.py
  addons/l10n_pl_jpk/security/ir.model.access.csv
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/l10n_pl_jpk/views/product_views.xml
  addons/l10n_pl_jpk/views/report_invoice.xml
  addons/l10n_pl_jpk/views/res_config_settings_views.xml
  addons/l10n_pl_jpk/views/res_partner_views.xml
  addons/l10n_pl_sale_stock/__init__.py
  addons/l10n_pl_sale_stock/__manifest__.py
  addons/l10n_pl_sale_stock/models/__init__.py
  addons/l10n_pl_sale_stock/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.saas-16.1

#22775 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/data/account_account_tags_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_de_skr03/data/template/account.account-de_skr03.csv
  addons/l10n_de_skr04/data/template/account.account-de_skr04.csv
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core_ui/link_preview/link_preview_confirm_delete.js
  addons/mail/static/src/core_ui/link_preview/link_preview_confirm_delete.xml
  addons/mail/static/tests/message/link_preview_test.js
  addons/mail/tests/test_mail_tools.py
  addons/point_of_sale/static/tests/unit/pos_app_tests.js
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/views/delivery_view.xml
  addons/test_sale_product_configurators/static/tests/tours/product_configurator_edition_ui.js
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.saas-16.3

#22776 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account_peppol/__manifest__.py
  addons/account_peppol/demo/account_peppol_demo.xml
  addons/base_geolocalize/models/base_geocoder.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/board/static/src/add_to_board/add_to_board.js
  addons/board/static/tests/add_to_dashboard_tests.js
  addons/event/i18n/event.pot
  addons/event/models/event_registration.py
  addons/event/static/src/scss/event.scss
  addons/event/views/event_registration_views.xml
  addons/hr/models/hr_plan_activity_type.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_cl/models/account_move.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/link_preview_confirm_delete.js
  addons/mail/static/src/core/common/link_preview_confirm_delete.xml
  addons/mail/static/tests/emoji/emoji_tests.js
  addons/mail/static/tests/message/link_preview_test.js
  addons/mail/tests/test_mail_tools.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/views/delivery_view.xml
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/core/emoji_picker/emoji_picker.js
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website_event/models/event_registration.py
  addons/website_event/views/event_registration_views.xml
  addons/website_event_track/static/src/js/service_worker.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.saas-16.4

#22777 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/base_geolocalize/models/base_geocoder.py
Labels: tmp.14.0

#22778 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_reconcile_model.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/coupon/views/coupon_program_views.xml
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/mail/static/src/models/rtc/rtc.js
  addons/mail/static/src/models/user_setting/user_setting.js
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_order.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: tmp.15.0

#22779 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/base_geolocalize/models/base_geocoder.py
  addons/l10n_pl/data/account_tax_data.xml
  addons/l10n_pl/data/account_tax_report_data.xml
  addons/l10n_pl_jpk/__init__.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/l10n_pl_jpk/data/l10n_pl_tax_office.csv
  addons/l10n_pl_jpk/i18n/l10n_pl_jpk.pot
  addons/l10n_pl_jpk/i18n/pl.po
  addons/l10n_pl_jpk/models/__init__.py
  addons/l10n_pl_jpk/models/account_move.py
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_pl_jpk/models/product.py
  addons/l10n_pl_jpk/models/res_company.py
  addons/l10n_pl_jpk/models/res_config_settings.py
  addons/l10n_pl_jpk/models/res_partner.py
  addons/l10n_pl_jpk/security/ir.model.access.csv
  addons/l10n_pl_jpk/views/account_move_views.xml
  addons/l10n_pl_jpk/views/product_views.xml
  addons/l10n_pl_jpk/views/report_invoice.xml
  addons/l10n_pl_jpk/views/res_config_settings_views.xml
  addons/l10n_pl_jpk/views/res_partner_views.xml
  addons/l10n_pl_sale_stock/__init__.py
  addons/l10n_pl_sale_stock/__manifest__.py
  addons/l10n_pl_sale_stock/models/__init__.py
  addons/l10n_pl_sale_stock/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/wizard/mrp_immediate_production.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/factorlibre.md
Labels: tmp.16.0

#22780 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_de/report/din5008_report.xml
  addons/l10n_de/static/src/scss/report_din5008.scss
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/stock/models/product.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
Labels: 14.0

#22781 Syncing from upstream odoo/odoo (15.0)
  addons/delivery/models/stock_picking.py
  addons/l10n_de/report/din5008_report.xml
  addons/l10n_de/static/src/scss/report_din5008.scss
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
Labels: 15.0

#22782 Syncing from upstream odoo/odoo (16.0)
  addons/account/__init__.py
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_payment_method.py
  addons/account/populate/account_payment.py
  addons/account/tests/test_account_journal.py
  addons/delivery/models/stock_picking.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/models/rtc.js
  addons/mail/static/src/models/user_setting.js
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mrp/models/stock_move.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp/tests/test_order.py
  addons/pos_loyalty/models/pos_session.py
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  addons/website_sale/models/product_template.py
  addons/website_sale/static/tests/tours/website_sale_shop_compare_list_price_pricelist.js
  addons/website_sale/views/templates.xml
Labels: 16.0

#22784 Syncing from upstream odoo/odoo (saas-15.2)
  addons/delivery/models/stock_picking.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
Labels: saas-15.2

#22785 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/delivery/models/stock_picking.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/mail/static/src/models/rtc.js
  addons/mail/static/src/models/user_setting.js
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  doc/cla/corporate/factorlibre.md
Labels: saas-16.1

#22786 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es/data/template/account.tax.group-es_common.csv
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_delivery/models/stock_picking.py
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  doc/cla/corporate/factorlibre.md
Labels: saas-16.2

#22791 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/delivery/models/stock_picking.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/mail/static/src/models/rtc.js
  addons/mail/static/src/models/user_setting.js
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  doc/cla/corporate/factorlibre.md
Labels: staging.saas-16.1

#22795 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_de/report/din5008_report.xml
  addons/l10n_de/static/src/scss/report_din5008.scss
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/stock/models/product.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
Labels: staging.14.0

#22799 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/delivery/models/stock_picking.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/static/src/scss/wysiwyg.scss
Labels: tmp.saas-15.2

#22800 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/delivery/models/stock_picking.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/data/account_tax_group_data.xml
  addons/mail/static/src/models/rtc.js
  addons/mail/static/src/models/user_setting.js
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  doc/cla/corporate/factorlibre.md
Labels: tmp.saas-16.1

#22801 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_invoice_taxes.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es/data/template/account.tax.group-es_common.csv
  addons/l10n_es_edi_sii/data/template/account.tax-es_common.csv
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/timesyncd
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_delivery/models/stock_picking.py
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  doc/cla/corporate/factorlibre.md
Labels: tmp.saas-16.2

#22804 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_de/report/din5008_report.xml
  addons/l10n_de/static/src/scss/report_din5008.scss
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/stock/models/product.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
Labels: tmp.14.0

#22805 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/delivery/models/stock_picking.py
  addons/l10n_de/report/din5008_report.xml
  addons/l10n_de/static/src/scss/report_din5008.scss
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
Labels: tmp.15.0

#22806 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/__init__.py
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_payment_method.py
  addons/account/populate/account_payment.py
  addons/account/tests/test_account_journal.py
  addons/delivery/models/stock_picking.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/models/rtc.js
  addons/mail/static/src/models/user_setting.js
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mrp/models/stock_move.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/tests/test_bom.py
  addons/mrp/tests/test_order.py
  addons/pos_loyalty/models/pos_session.py
  addons/purchase_mrp/models/mrp_bom.py
  addons/purchase_mrp/models/stock_move.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/spreadsheet_account/models/account.py
  addons/spreadsheet_account/tests/test_debit_credit.py
  addons/stock/models/product.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_product.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/actions/client_actions.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/actions/client_action_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/website/views/website_templates.xml
  addons/website_sale/models/product_template.py
  addons/website_sale/static/tests/tours/website_sale_shop_compare_list_price_pricelist.js
  addons/website_sale/views/templates.xml
Labels: tmp.16.0

#22811 Syncing from upstream odoo/odoo (saas-16.3)
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
Labels: saas-16.3

#22818 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_din5008/static/src/scss/report_din5008.scss
Labels: tmp.saas-16.3

#22819 Syncing from upstream odoo/odoo (14.0)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
Labels: 14.0

#22820 Syncing from upstream odoo/odoo (15.0)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
Labels: 15.0

#22821 Syncing from upstream odoo/odoo (16.0)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
Labels: 16.0

#22822 Syncing from upstream odoo/odoo (master)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
Labels: master

#22823 Syncing from upstream odoo/odoo (saas-15.2)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/main.py
Labels: saas-15.2

#22827 Syncing from upstream odoo/odoo (saas-16.4)
  addons/pos_paytm/__init__.py
  addons/pos_paytm/__manifest__.py
  addons/pos_paytm/models/__init__.py
  addons/pos_paytm/models/pos_payment.py
  addons/pos_paytm/models/pos_payment_method.py
  addons/pos_paytm/static/src/js/PaymentScreen.js
  addons/pos_paytm/static/src/js/model.js
  addons/pos_paytm/static/src/js/payment_paytm.js
  addons/pos_paytm/static/src/js/pos_paytm.js
  addons/pos_paytm/views/pos_payment_method_views.xml
  addons/pos_paytm/views/pos_payment_views.xml
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
Labels: saas-16.4

#22837 Syncing from upstream odoo/odoo (tmp.master)
  addons/test_xlsx_export/tests/test_export.py
  addons/web/controllers/export.py
Labels: tmp.master

#22846 Syncing from upstream odoo/odoo (14.0)
  addons/auth_oauth/controllers/main.py
  addons/mail/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: 14.0

#22847 Syncing from upstream odoo/odoo (15.0)
  addons/auth_oauth/controllers/main.py
  addons/bus/models/bus.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  odoo/addons/base/models/ir_cron.py
Labels: 15.0

#22848 Syncing from upstream odoo/odoo (16.0)
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_invoice_send.py
  addons/account/wizard/setup_wizards.py
  addons/auth_oauth/controllers/main.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/note/views/note_views.xml
  addons/project/static/src/components/project_right_side_panel/components/project_milestone.xml
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/controllers/utils.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/date/date_field.js
  addons/web/static/src/views/fields/date/date_field.xml
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/datetime/datetime_field.xml
  addons/web/static/src/webclient/user_menu/user_menu.scss
  addons/web/static/src/webclient/user_menu/user_menu.xml
  addons/web/static/tests/views/form/form_view_tests.js
  addons/website/tests/test_menu.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_related_translation.py
  odoo/models.py
  odoo/tools/translate.py
Labels: 16.0

#22850 Syncing from upstream odoo/odoo (saas-15.2)
  addons/auth_oauth/controllers/main.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/coupon/views/coupon_program_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: saas-15.2

#22851 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/__init__.py
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_payment_method.py
  addons/account/populate/account_payment.py
  addons/account/tests/test_account_journal.py
  addons/auth_oauth/controllers/main.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account.group.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/l10n_mx/i18n/es.po
  addons/l10n_mx/i18n/l10n_mx.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/note/views/note_views.xml
  addons/pos_loyalty/models/pos_session.py
  addons/project/static/src/components/project_right_side_panel/components/project_milestone.xml
  addons/sale_loyalty/models/sale_order.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/date/date_field.js
  addons/web/static/src/views/fields/date/date_field.xml
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/datetime/datetime_field.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/webclient/user_menu/user_menu.scss
  addons/web/static/src/webclient/user_menu/user_menu.xml
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/views/ir_module_views.xml
  odoo/models.py
Labels: saas-16.1

#22854 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/tests/test_account_journal.py
  addons/auth_oauth/controllers/main.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/loyalty/models/loyalty_card.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/user_settings_service.js
  addons/mail/static/src/core/web/chatter.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/tests/unit/pos_app_tests.js
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/sale/views/sale_portal_templates.xml
  addons/sale_loyalty/models/sale_order.py
  addons/stock/__init__.py
  addons/stock/__manifest__.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/company_service.js
  addons/web/static/src/webclient/switch_company_menu/switch_company_menu.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/mobile/mobile_switch_company_menu_tests.js
  addons/web/static/tests/webclient/switch_company_menu_tests.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/models.py
Labels: saas-16.4

#22857 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/__init__.py
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_payment_method.py
  addons/account/populate/account_payment.py
  addons/account/tests/test_account_journal.py
  addons/auth_oauth/controllers/main.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account.group.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/l10n_mx/i18n/es.po
  addons/l10n_mx/i18n/l10n_mx.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/note/views/note_views.xml
  addons/pos_loyalty/models/pos_session.py
  addons/project/static/src/components/project_right_side_panel/components/project_milestone.xml
  addons/sale_loyalty/models/sale_order.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/date/date_field.js
  addons/web/static/src/views/fields/date/date_field.xml
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/datetime/datetime_field.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/webclient/user_menu/user_menu.scss
  addons/web/static/src/webclient/user_menu/user_menu.xml
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/views/ir_module_views.xml
  odoo/models.py
Labels: staging.saas-16.1

#22860 Syncing from upstream odoo/odoo (staging.14.0)
  addons/auth_oauth/controllers/main.py
  addons/mail/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: staging.14.0

#22864 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/auth_oauth/controllers/main.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/coupon/views/coupon_program_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
Labels: tmp.saas-15.2

#22865 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/__init__.py
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/models/account_payment_method.py
  addons/account/populate/account_payment.py
  addons/account/tests/test_account_journal.py
  addons/auth_oauth/controllers/main.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_mx/data/account.account.template.csv
  addons/l10n_mx/data/account.group.template.csv
  addons/l10n_mx/data/account_tax_data.xml
  addons/l10n_mx/data/account_tax_group_data.xml
  addons/l10n_mx/i18n/es.po
  addons/l10n_mx/i18n/l10n_mx.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/note/views/note_views.xml
  addons/pos_loyalty/models/pos_session.py
  addons/project/static/src/components/project_right_side_panel/components/project_milestone.xml
  addons/sale_loyalty/models/sale_order.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/date/date_field.js
  addons/web/static/src/views/fields/date/date_field.xml
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/datetime/datetime_field.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/webclient/user_menu/user_menu.scss
  addons/web/static/src/webclient/user_menu/user_menu.xml
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/views/ir_module_views.xml
  odoo/models.py
Labels: tmp.saas-16.1

#22868 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_journal.py
  addons/account/tests/test_account_journal.py
  addons/auth_oauth/controllers/main.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_din5008/static/src/scss/report_din5008.scss
  addons/loyalty/models/loyalty_card.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/user_settings_service.js
  addons/mail/static/src/core/web/chatter.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail_plugin/controllers/authenticate.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/tests/unit/pos_app_tests.js
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/sale/views/sale_portal_templates.xml
  addons/sale_loyalty/models/sale_order.py
  addons/stock/__init__.py
  addons/stock/__manifest__.py
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/webclient/company_service.js
  addons/web/static/src/webclient/switch_company_menu/switch_company_menu.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/webclient/mobile/mobile_switch_company_menu_tests.js
  addons/web/static/tests/webclient/switch_company_menu_tests.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/models.py
Labels: tmp.saas-16.4

#22869 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/auth_oauth/controllers/main.py
  addons/mail/models/mail_thread.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: tmp.14.0

#22870 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/auth_oauth/controllers/main.py
  addons/bus/models/bus.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  odoo/addons/base/models/ir_cron.py
Labels: tmp.15.0

#22871 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_invoice_send.py
  addons/account/wizard/setup_wizards.py
  addons/auth_oauth/controllers/main.py
  addons/base_import/i18n/base_import.pot
  addons/base_import/models/base_import.py
  addons/mass_mailing/models/mailing.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_bom.py
  addons/mrp/wizard/mrp_immediate_production_views.xml
  addons/note/views/note_views.xml
  addons/project/static/src/components/project_right_side_panel/components/project_milestone.xml
  addons/test_mass_mailing/models/mailing_models.py
  addons/test_mass_mailing/security/ir.model.access.csv
  addons/test_mass_mailing/tests/test_mailing.py
  addons/web/controllers/utils.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/date/date_field.js
  addons/web/static/src/views/fields/date/date_field.xml
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/datetime/datetime_field.xml
  addons/web/static/src/webclient/user_menu/user_menu.scss
  addons/web/static/src/webclient/user_menu/user_menu.xml
  addons/web/static/tests/views/form/form_view_tests.js
  addons/website/tests/test_menu.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_qweb.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_related_translation.py
  odoo/models.py
  odoo/tools/translate.py
Labels: tmp.16.0

#22872 Syncing from upstream odoo/odoo (14.0)
  odoo/addons/base/models/ir_rule.py
  odoo/addons/test_access_rights/tests/test_feedback.py
  odoo/models.py
Labels: 14.0

#22873 Syncing from upstream odoo/odoo (15.0)
  addons/event/controllers/main.py
  addons/mail/models/mail_thread.py
  addons/portal/static/src/scss/portal.scss
  addons/test_mail/tests/test_mail_gateway.py
Labels: 15.0

#22874 Syncing from upstream odoo/odoo (16.0)
  addons/hr_expense/views/hr_expense_views.xml
  addons/mail/models/mail_composer_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_users_settings.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/portal/static/src/scss/portal.scss
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_order_cancel.py
  addons/sale/wizard/sale_order_cancel.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website_sale/models/product_template.py
  odoo/tools/translate.py
Labels: 16.0
