Repository brain-tec/odoo, pull requests merged in 2023-06, with the labels that each got.

#20488 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi/models/__init__.py
  addons/account_edi/models/uom.py
  addons/account_edi_facturx/models/__init__.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/stock/models/stock_rule.py
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/wizard/base_import_language.py
Labels: 14.0

#20489 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/crm/tests/test_performances.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mail/models/mail_thread.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  addons/website_payment/static/src/snippets/s_donation/000.js
  addons/website_sale_stock_wishlist/views/templates.xml
Labels: 15.0

#20490 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_nlcius.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr/wizard/hr_plan_wizard_views.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_th/__init__.py
  addons/l10n_th/__manifest__.py
  addons/l10n_th/models/__init__.py
  addons/l10n_th/models/account_move.py
  addons/l10n_th/models/res_partner.py
  addons/l10n_th/views/report_invoice.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/pos_daily_sales_reports/views/point_of_sale_view.xml
  addons/pos_loyalty/static/src/js/PaymentScreen.js
  addons/purchase_requisition/wizard/purchase_requisition_create_alternative.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/controllers/form.py
  addons/website/models/ir_module_module.py
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_payment/static/src/snippets/s_donation/000.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/service/model.py
Labels: 16.0

#20492 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/src/js/models.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_payment/static/src/snippets/s_donation/000.js
  addons/website_profile/views/website_profile.xml
  addons/website_sale_stock_wishlist/views/templates.xml
Labels: saas-15.2

#20493 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi/models/account_payment.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_th/__init__.py
  addons/l10n_th/__manifest__.py
  addons/l10n_th/models/__init__.py
  addons/l10n_th/models/account_move.py
  addons/l10n_th/models/res_partner.py
  addons/l10n_th/views/report_invoice.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mail/models/res_users.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_bill.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/barcode_reader.js
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_http.py
  odoo/http.py
Labels: saas-16.1

#20494 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mail/models/res_users.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_bill.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/barcode_reader.js
  addons/point_of_sale/static/src/js/models.js
  addons/stock/models/stock_move.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_http.py
  odoo/http.py
Labels: saas-16.2

#20497 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi/models/account_payment.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_th/__init__.py
  addons/l10n_th/__manifest__.py
  addons/l10n_th/models/__init__.py
  addons/l10n_th/models/account_move.py
  addons/l10n_th/models/res_partner.py
  addons/l10n_th/views/report_invoice.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mail/models/res_users.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_bill.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/barcode_reader.js
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_http.py
  odoo/http.py
Labels: staging.saas-16.1

#20500 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi/models/__init__.py
  addons/account_edi/models/uom.py
  addons/account_edi_facturx/models/__init__.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/stock/models/stock_rule.py
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/wizard/base_import_language.py
Labels: staging.14.0

#20503 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/static/src/js/models.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  addons/website_event_track_quiz/i18n/website_event_track_quiz.pot
  addons/website_event_track_quiz/views/event_leaderboard_templates.xml
  addons/website_payment/static/src/snippets/s_donation/000.js
  addons/website_profile/views/website_profile.xml
  addons/website_sale_stock_wishlist/views/templates.xml
Labels: tmp.saas-15.2

#20504 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi/models/account_payment.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_th/__init__.py
  addons/l10n_th/__manifest__.py
  addons/l10n_th/models/__init__.py
  addons/l10n_th/models/account_move.py
  addons/l10n_th/models/res_partner.py
  addons/l10n_th/views/report_invoice.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mail/models/res_users.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_bill.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/barcode_reader.js
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_http.py
  odoo/http.py
Labels: tmp.saas-16.1

#20505 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/barcodes_gs1_nomenclature/static/src/js/barcode_parser.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mail/models/res_users.py
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_bill.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/barcode_reader.js
  addons/point_of_sale/static/src/js/models.js
  addons/stock/models/stock_move.py
  addons/test_mail/models/test_mail_corner_case_models.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web/views/report_templates.xml
  odoo/addons/base/models/ir_http.py
  odoo/http.py
Labels: tmp.saas-16.2

#20507 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi/models/__init__.py
  addons/account_edi/models/uom.py
  addons/account_edi_facturx/models/__init__.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/stock/models/stock_rule.py
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/wizard/base_import_language.py
Labels: tmp.14.0

#20508 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/crm/tests/test_performances.py
  addons/google_gmail/i18n/google_gmail.pot
  addons/google_gmail/models/google_gmail_mixin.py
  addons/google_gmail/models/ir_mail_server.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/mail/models/mail_thread.py
  addons/microsoft_outlook/i18n/microsoft_outlook.pot
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/microsoft_outlook/models/microsoft_outlook_mixin.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/models/website.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/new_content.js
  addons/website/tests/test_page.py
  addons/website_payment/static/src/snippets/s_donation/000.js
  addons/website_sale_stock_wishlist/views/templates.xml
Labels: tmp.15.0

#20509 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_sequence_mixin.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_nlcius.py
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr/wizard/hr_plan_wizard_views.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/models/resource.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_sg/data/account_tax_report_data.xml
  addons/l10n_za/data/account_tax_report_data.xml
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
  addons/pos_daily_sales_reports/views/point_of_sale_view.xml
  addons/pos_loyalty/static/src/js/PaymentScreen.js
  addons/purchase_requisition/wizard/purchase_requisition_create_alternative.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/controllers/form.py
  addons/website/models/ir_module_module.py
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_payment/static/src/snippets/s_donation/000.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/service/model.py
Labels: tmp.16.0

#20510 Syncing from upstream odoo/odoo (14.0)
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/widgets/translation_dialog.js
  addons/web/static/tests/views/list_tests.js
  addons/website/models/website_rewrite.py
Labels: 14.0

#20511 Syncing from upstream odoo/odoo (15.0)
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/widgets/translation_dialog.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/website/tests/__init__.py
  addons/website/tests/test_ir_asset.py
  odoo/addons/base/wizard/base_import_language.py
Labels: 15.0

#20512 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_analytic_account.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/tests/mass_mailing_html_tests.js
  addons/payment_adyen/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_sale/models/__init__.py
  addons/pos_sale/models/stock_picking.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stock_quantity.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/stock/static/src/widgets/forecast_widget.js
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/domain_selector/domain_selector_leaf_node.js
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_slide_channel.py
  doc/cla/individual/joray.md
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
Labels: 16.0

#20514 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_analytic_line.py
  addons/crm/tests/test_performances.py
  addons/mail/models/mail_thread.py
  addons/mrp_account/models/mrp_production.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/payment_adyen/controllers/main.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stock_quantity.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/widgets/translation_dialog.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/static/src/scss/website.scss
  odoo/addons/base/wizard/base_import_language.py
Labels: saas-15.2

#20515 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
Labels: saas-16.1

#20516 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/res_partner_bank_views.xml
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr/wizard/hr_plan_wizard_views.xml
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/payment_adyen/controllers/main.py
  addons/point_of_sale/models/pos_category.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/views/fields/signature/signature_field.js
  addons/web/static/src/views/fields/signature/signature_field.xml
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/views/fields/signature_field_tests.js
  addons/web_editor/controllers/main.py
  addons/website/controllers/form.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/osv/expression.py
  odoo/service/model.py
Labels: saas-16.2

#20517 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/res_partner_bank_views.xml
  addons/gamification/views/gamification_goal_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr/wizard/hr_plan_wizard_views.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_org_chart/static/src/fields/hr_org_chart.xml
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_es_edi_facturae/models/account_move_send.py
  addons/lunch/static/src/components/lunch_dashboard.xml
  addons/mail/static/src/attachments/attachment_model.js
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/core_ui/primary_variables.scss
  addons/mail/static/src/scss/variables/primary_variables.scss
  addons/mail/static/src/web/chat_window/chat_window_service.js
  addons/mail/static/src/web/chatter.xml
  addons/payment_adyen/controllers/main.py
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/models/pos_category.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/search/search_model.js
  addons/web/static/src/webclient/burger_menu/burger_menu.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/search/search_bar_menu_tests.js
  addons/web/static/tests/search/search_bar_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/controllers/main.py
  addons/website/controllers/form.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/osv/expression.py
  odoo/service/model.py
Labels: saas-16.3

#20519 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/static/src/scss/website.scss
Labels: staging.saas-16.1

#20522 Syncing from upstream odoo/odoo (staging.14.0)
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/widgets/translation_dialog.js
  addons/web/static/tests/views/list_tests.js
  addons/website/models/website_rewrite.py
Labels: staging.14.0

#20525 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_analytic_line.py
  addons/crm/tests/test_performances.py
  addons/mail/models/mail_thread.py
  addons/mrp_account/models/mrp_production.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/payment_adyen/controllers/main.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stock_quantity.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/widgets/translation_dialog.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/static/src/scss/website.scss
  odoo/addons/base/wizard/base_import_language.py
Labels: tmp.saas-15.2

#20526 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/static/src/scss/website.scss
Labels: tmp.saas-16.1

#20527 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/res_partner_bank_views.xml
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr/wizard/hr_plan_wizard_views.xml
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/payment_adyen/controllers/main.py
  addons/point_of_sale/models/pos_category.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/views/fields/signature/signature_field.js
  addons/web/static/src/views/fields/signature/signature_field.xml
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/views/fields/signature_field_tests.js
  addons/web_editor/controllers/main.py
  addons/website/controllers/form.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/osv/expression.py
  odoo/service/model.py
Labels: tmp.saas-16.2

#20528 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/res_partner_bank_views.xml
  addons/gamification/views/gamification_goal_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr/wizard/hr_plan_wizard.py
  addons/hr/wizard/hr_plan_wizard_views.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_org_chart/static/src/fields/hr_org_chart.xml
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_es_edi_facturae/models/account_move_send.py
  addons/lunch/static/src/components/lunch_dashboard.xml
  addons/mail/static/src/attachments/attachment_model.js
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/core_ui/primary_variables.scss
  addons/mail/static/src/scss/variables/primary_variables.scss
  addons/mail/static/src/web/chat_window/chat_window_service.js
  addons/mail/static/src/web/chatter.xml
  addons/payment_adyen/controllers/main.py
  addons/payment_paypal/controllers/main.py
  addons/point_of_sale/models/pos_category.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move_line.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/search/search_model.js
  addons/web/static/src/webclient/burger_menu/burger_menu.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/search/search_bar_menu_tests.js
  addons/web/static/tests/search/search_bar_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/controllers/main.py
  addons/website/controllers/form.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/osv/expression.py
  odoo/service/model.py
Labels: tmp.saas-16.3

#20529 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/js/views/basic/basic_controller.js
  addons/web/static/src/js/views/list/list_controller.js
  addons/web/static/src/js/widgets/translation_dialog.js
  addons/web/static/tests/views/list_tests.js
  addons/website/models/website_rewrite.py
Labels: tmp.14.0

#20530 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/legacy/js/views/basic/basic_controller.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/legacy/js/views/list/list_controller.js
  addons/web/static/src/legacy/js/widgets/translation_dialog.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/website/tests/__init__.py
  addons/website/tests/test_ir_asset.py
  odoo/addons/base/wizard/base_import_language.py
Labels: tmp.15.0

#20531 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_analytic_account.py
  addons/hr_work_entry_contract/models/hr_contract.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/tests/mass_mailing_html_tests.js
  addons/payment_adyen/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_sale/models/__init__.py
  addons/pos_sale/models/stock_picking.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stock_quantity.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/stock/static/src/widgets/forecast_widget.js
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/domain_selector/domain_selector_leaf_node.js
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/l10n/dates_tests.js
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_slide_channel.py
  doc/cla/individual/joray.md
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
Labels: tmp.16.0

#20532 Syncing from upstream odoo/odoo (13.0)
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
Labels: 13.0

#20533 Syncing from upstream odoo/odoo (14.0)
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  odoo/modules/registry.py
Labels: 14.0

#20534 Syncing from upstream odoo/odoo (15.0)
  addons/account/report/account_invoice_report.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_import/models/base_import.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/mrp_workorder.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/website/models/website_rewrite.py
  addons/website_sale/models/sale_order.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
Labels: 15.0

#20535 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/board/__manifest__.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.scss
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_test.js
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/hr/static/src/views/fields/many2many_avatar_employee_field/many2many_avatar_employee_field.js
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr_expense/models/hr_expense.py
  addons/im_livechat/views/im_livechat_channel_views.xml
  addons/l10n_th/models/__init__.py
  addons/l10n_th/models/ir_actions_report.py
  addons/mrp/static/src/components/bom_overview_control_panel/mrp_bom_overview_control_panel.js
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/fields/properties/properties_field.scss
  addons/web/static/src/views/fields/signature/signature_field.js
  addons/web/static/src/views/fields/signature/signature_field.xml
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban/kanban_compiler_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/views/view_dialogs/export_data_dialog_tests.js
  addons/web/static/tests/views/widgets/signature_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website_rewrite.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_reports.py
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
Labels: 16.0

#20537 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/website/models/website_rewrite.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
Labels: saas-15.2

#20540 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/views/res_config_settings_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/board/__manifest__.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.scss
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_test.js
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/im_livechat/views/im_livechat_channel_views.xml
  addons/mail/static/src/core_ui/core.scss
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/discuss_app/im_status.scss
  addons/mail/static/src/discuss_app/thread_icon.xml
  addons/mail/static/src/web/chatter.scss
  addons/mail/static/src/web/chatter.xml
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/tests/mass_mailing_html_tests.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp_subcontracting/static/src/components/bom_overview_components_block/mrp_bom_overview_components_block.xml
  addons/mrp_subcontracting/static/src/components/bom_overview_special_line/mrp_bom_overview_special_line.xml
  addons/purchase/models/purchase.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/fields/properties/properties_field.scss
  addons/web/static/src/views/fields/signature/signature_field.js
  addons/web/static/src/views/fields/signature/signature_field.xml
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/fields/signature_field_tests.js
  addons/web/static/tests/views/kanban/kanban_compiler_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/data/website_data.xml
  addons/website/models/ir_module_module.py
  addons/website/models/website_rewrite.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_slide_channel.py
  doc/cla/individual/joray.md
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
Labels: saas-16.3

#20545 Syncing from upstream odoo/odoo (staging.13.0)
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
Labels: staging.13.0

#20546 Syncing from upstream odoo/odoo (staging.14.0)
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  odoo/modules/registry.py
Labels: staging.14.0

#20549 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist.py
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/website/models/website_rewrite.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
Labels: tmp.saas-15.2

#20552 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/views/res_config_settings_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/board/__manifest__.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.scss
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_test.js
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_event_recurrence.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_recruitment/views/hr_applicant_refuse_reason_views.xml
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/im_livechat/views/im_livechat_channel_views.xml
  addons/mail/static/src/core_ui/core.scss
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/discuss_app/im_status.scss
  addons/mail/static/src/discuss_app/thread_icon.xml
  addons/mail/static/src/web/chatter.scss
  addons/mail/static/src/web/chatter.xml
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/tests/mass_mailing_html_tests.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp_subcontracting/static/src/components/bom_overview_components_block/mrp_bom_overview_components_block.xml
  addons/mrp_subcontracting/static/src/components/bom_overview_special_line/mrp_bom_overview_special_line.xml
  addons/purchase/models/purchase.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/models/project.py
  addons/survey/views/survey_survey_views.xml
  addons/web/static/src/views/fields/parsers.js
  addons/web/static/src/views/fields/properties/properties_field.scss
  addons/web/static/src/views/fields/signature/signature_field.js
  addons/web/static/src/views/fields/signature/signature_field.xml
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/src/webclient/navbar/navbar.scss
  addons/web/static/tests/views/fields/parsers_tests.js
  addons/web/static/tests/views/fields/signature_field_tests.js
  addons/web/static/tests/views/kanban/kanban_compiler_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/data/website_data.xml
  addons/website/models/ir_module_module.py
  addons/website/models/website_rewrite.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_slide_channel.py
  doc/cla/individual/joray.md
  odoo/addons/base/tests/test_translate.py
  odoo/addons/base/wizard/base_import_language.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_one2many.py
  odoo/fields.py
Labels: tmp.saas-16.3

#20553 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/mrp/models/product.py
  addons/mrp/tests/common.py
  addons/mrp/tests/test_bom.py
Labels: tmp.13.0

#20554 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  odoo/modules/registry.py
Labels: tmp.14.0

#20555 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/report/account_invoice_report.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_import/models/base_import.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mass_mailing/static/src/js/mass_mailing_widget.js
  addons/mrp/models/mrp_workorder.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/website/models/website_rewrite.py
  addons/website_sale/models/sale_order.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
Labels: tmp.15.0

#20556 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/board/__manifest__.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.scss
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_test.js
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/utils/google_event.py
  addons/hr/static/src/views/fields/many2many_avatar_employee_field/many2many_avatar_employee_field.js
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr_expense/models/hr_expense.py
  addons/im_livechat/views/im_livechat_channel_views.xml
  addons/l10n_th/models/__init__.py
  addons/l10n_th/models/ir_actions_report.py
  addons/mrp/static/src/components/bom_overview_control_panel/mrp_bom_overview_control_panel.js
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/report/report_deliveryslip.xml
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/fields/properties/properties_field.scss
  addons/web/static/src/views/fields/signature/signature_field.js
  addons/web/static/src/views/fields/signature/signature_field.xml
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/legacy/fields/relational_fields/field_one2many_tests.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web/static/tests/views/kanban/kanban_compiler_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/views/view_dialogs/export_data_dialog_tests.js
  addons/web/static/tests/views/widgets/signature_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/website_rewrite.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_reports.py
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
Labels: tmp.16.0

#20560 Syncing from upstream odoo/odoo (master)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: master

#20564 Syncing from upstream odoo/odoo (saas-16.3)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: saas-16.3

#20566 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: staging.saas-16.1

#20569 Syncing from upstream odoo/odoo (staging.14.0)
  doc/cla/corporate/vauxoo.md
Labels: staging.14.0

#20572 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.saas-16.1

#20573 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.saas-16.2

#20574 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.saas-16.3

#20575 Syncing from upstream odoo/odoo (tmp.14.0)
  doc/cla/corporate/vauxoo.md
Labels: tmp.14.0

#20576 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.16.0

#20582 Syncing from upstream odoo/odoo (14.0)
  addons/purchase/models/purchase.py
  addons/website_form/static/src/snippets/s_website_form/options.js
  odoo/addons/base/views/res_users_views.xml
Labels: 14.0

#20583 Syncing from upstream odoo/odoo (15.0)
  addons/point_of_sale/models/stock_picking.py
  addons/stock/models/stock_move.py
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_statistics.py
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: 15.0

#20584 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/report/account_invoice_report.py
  addons/base_import/models/base_import.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_ae/data/l10n_ae_chart_post_data.xml
  addons/l10n_ar/data/account.account.template.csv
  addons/l10n_ar/data/account_chart_template_data2.xml
  addons/l10n_at/data/account_chart_template.xml
  addons/l10n_au/data/account.account.template.csv
  addons/l10n_au/data/account_chart_template_data.xml
  addons/l10n_bg/data/l10n_bg_chart_data.xml
  addons/l10n_br/data/account_chart_template_data.xml
  addons/l10n_ch/data/l10n_ch_chart_post_data.xml
  addons/l10n_cl/data/l10n_cl_chart_data.xml
  addons/l10n_dk/data/l10n_dk_chart_template_post_data.xml
  addons/l10n_es/data/account_chart_template_account_account_link.xml
  addons/l10n_hu/data/l10n_hu_chart_data.xml
  addons/l10n_in/data/account.account.template.csv
  addons/l10n_in/data/l10n_in_chart_post_data.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_mn/data/account.account.template.csv
  addons/l10n_mn/data/l10n_mn_chart_template_data.xml
  addons/l10n_nl/data/account_chart_template_post_data.xml
  addons/l10n_no/data/account_chart_template_data.xml
  addons/l10n_pt/data/account_chart_template_data.xml
  addons/l10n_sa/data/l10n_sa_chart_data.xml
  addons/l10n_se/data/account_chart_template_after_accounts.xml
  addons/l10n_sg/data/l10n_sg_chart_data.xml
  addons/l10n_si/data/account.account.template.csv
  addons/l10n_si/data/account_chart_template_configure_data.xml
  addons/l10n_uk/data/account.chart.template.csv
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/project/static/src/components/project_state_selection/project_state_selection.scss
  addons/project/static/src/components/project_status_with_color_selection/project_status_with_color_selection_field.xml
  addons/project/views/project_views.xml
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_timesheet/i18n/sale_timesheet.pot
  addons/sale_timesheet/models/project.py
  addons/sms/wizard/sms_composer.py
  addons/stock_sms/models/stock_picking.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/website/models/website.py
  addons/website/static/src/components/dialog/dialog.js
  addons/website/tests/__init__.py
  addons/website/tests/test_ir_asset.py
  addons/website/tests/test_page.py
  addons/website_forum/static/src/js/website_forum.js
Labels: 16.0

#20586 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/report/account_invoice_report.py
  addons/base_import/models/base_import.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/website/tests/__init__.py
  addons/website/tests/test_ir_asset.py
  addons/website_sale/models/sale_order.py
Labels: saas-15.2

#20587 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/chart_template.py
  addons/base_import/models/base_import.py
  addons/hr_recruitment/models/hr_job.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/static/src/components/bom_overview_control_panel/mrp_bom_overview_control_panel.js
  addons/point_of_sale/static/src/js/ChromeWidgets/CashMoveButton.js
  addons/point_of_sale/static/src/xml/Popups/CashMoveReceipt.xml
  addons/product/i18n/product.pot
  addons/product/models/product_pricelist_item.py
  addons/project/static/src/components/project_state_selection/project_state_selection.scss
  addons/project/static/src/components/project_status_with_color_selection/project_status_with_color_selection_field.xml
  addons/project/views/project_views.xml
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/web/static/src/views/view_dialogs/export_data_dialog.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.xml
  addons/web/static/tests/views/view_dialogs/export_data_dialog_tests.js
  addons/website/models/website.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/dialog/dialog.js
  addons/website/tests/__init__.py
  addons/website/tests/test_ir_asset.py
  addons/website/tests/test_page.py
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  odoo/service/model.py
Labels: saas-16.1

#20602 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/point_of_sale/models/stock_picking.py
  addons/stock/models/stock_move.py
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_statistics.py
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
Labels: tmp.15.0

#20604 [t136708] Skip account constraints based on context flag
  addons/account/models/account_move.py
Labels: feature, 15.0.project_sv_559

#20605 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/board/static/src/js/board_view.js
  addons/board/static/src/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/board/views/board_templates.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/res_company.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/src/tests/tours/slides_course_member.js
Labels: 14.0

#20606 Syncing from upstream odoo/odoo (15.0)
  addons/board/__manifest__.py
  addons/board/static/src/legacy/js/board_view.js
  addons/board/static/src/legacy/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mail/models/res_company.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_rule.py
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  addons/website_slides/static/src/tests/tours/slides_course_member.js
  odoo/addons/base/views/res_users_views.xml
Labels: 15.0

#20607 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_report.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/public_models/chatbot.js
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_th/models/res_partner.py
  addons/mail/models/res_company.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/project/models/project.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/src/views/utils.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_member.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/axl-lvy.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/views/res_users_views.xml
  odoo/modules/loading.py
Labels: 16.0

#20609 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi/models/account_move.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_nlcius.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/res_company.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_rule.py
  addons/web/models/base_document_layout.py
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web/views/report_templates.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  addons/website_sale_delivery/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_member.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/data/res.country.state.csv
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_company.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/views/res_users_views.xml
Labels: saas-15.2

#20618 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/board/static/src/js/board_view.js
  addons/board/static/src/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/board/views/board_templates.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/res_company.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/src/tests/tours/slides_course_member.js
Labels: staging.14.0

#20622 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi/models/account_move.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_nlcius.py
  addons/l10n_account_edi_ubl_cii_tests/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case2.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_ecotaxes_case3.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/res_company.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_rule.py
  addons/web/models/base_document_layout.py
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web/views/report_templates.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  addons/website_sale_delivery/controllers/main.py
  addons/website_slides/static/src/tests/tours/slides_course_member.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/data/res.country.state.csv
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_company.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/views/res_users_views.xml
Labels: tmp.saas-15.2

#20626 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/board/static/src/js/board_view.js
  addons/board/static/src/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/board/views/board_templates.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/mail/models/res_company.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/src/tests/tours/slides_course_member.js
Labels: tmp.14.0

#20627 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/board/__manifest__.py
  addons/board/static/src/legacy/js/board_view.js
  addons/board/static/src/legacy/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mail/models/res_company.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_rule.py
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_event/views/event_templates_list.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
  addons/website_slides/static/src/tests/tours/slides_course_member.js
  odoo/addons/base/views/res_users_views.xml
Labels: tmp.15.0

#20628 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_report.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/public_models/chatbot.js
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_th/models/res_partner.py
  addons/mail/models/res_company.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/project/models/project.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_timesheet/models/sale_order.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/src/views/utils.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/views/templates.xml
  addons/website_sale_delivery/controllers/main.py
  addons/website_slides/static/tests/tours/slides_course_member.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/axl-lvy.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/views/res_users_views.xml
  odoo/modules/loading.py
Labels: tmp.16.0

#20629 Syncing from upstream odoo/odoo (13.0)
  addons/point_of_sale/models/account_tax.py
Labels: 13.0

#20630 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/models/account_tax.py
  addons/survey/views/survey_templates.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/osv/expression.py
Labels: 14.0

#20631 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/survey/views/survey_templates.xml
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/modules/registry.py
Labels: 15.0

#20632 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr/static/src/scss/hr.scss
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_au/models/chart_template.py
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.js
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.xml
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_quant.py
  addons/stock_dropshipping/models/stock.py
  addons/stock_dropshipping/tests/test_dropship.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/views/report_templates.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/static/src/js/website_sale.editor.js
  odoo/addons/base/models/res_company.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: 16.0

#20634 Syncing from upstream odoo/odoo (saas-12.3)
  addons/point_of_sale/models/account_tax.py
Labels: saas-12.3

#20635 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/board/__manifest__.py
  addons/board/static/src/legacy/js/board_view.js
  addons/board/static/src/legacy/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/survey/views/survey_templates.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale/static/src/js/website_sale.editor.js
Labels: saas-15.2

#20636 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/mail/models/res_company.py
  addons/mail/static/src/views/activity/activity_model.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_quant.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/models/base_document_layout.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/tests/tours/slides_course_member.js
  odoo/addons/base/models/res_company.py
  odoo/modules/loading.py
Labels: saas-16.1

#20637 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/static/src/components/mail_attachments/mail_attachments.js
  addons/account/tests/test_account_move_send.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/models/account_move_send.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/mail/models/res_company.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/snailmail_account/wizard/account_move_send.py
  addons/stock/models/stock_quant.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/tests/tours/slides_course_member.js
  odoo/addons/base/data/res.country.state.csv
  odoo/modules/loading.py
Labels: saas-16.2

#20640 Syncing from upstream odoo/odoo (staging.saas-12.3)
  addons/point_of_sale/models/account_tax.py
Labels: staging.saas-12.3

#20642 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/mail/models/res_company.py
  addons/mail/static/src/views/activity/activity_model.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_quant.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/models/base_document_layout.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/tests/tours/slides_course_member.js
  odoo/addons/base/models/res_company.py
  odoo/modules/loading.py
Labels: staging.saas-16.1

#20645 Syncing from upstream odoo/odoo (staging.13.0)
  addons/point_of_sale/models/account_tax.py
Labels: staging.13.0

#20646 Syncing from upstream odoo/odoo (staging.14.0)
  addons/point_of_sale/models/account_tax.py
  addons/survey/views/survey_templates.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/osv/expression.py
Labels: staging.14.0

#20650 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  addons/point_of_sale/models/account_tax.py
Labels: tmp.saas-12.3

#20651 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/board/__manifest__.py
  addons/board/static/src/legacy/js/board_view.js
  addons/board/static/src/legacy/xml/board.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/survey/views/survey_templates.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale/static/src/js/website_sale.editor.js
Labels: tmp.saas-15.2

#20652 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/mail/models/res_company.py
  addons/mail/static/src/views/activity/activity_model.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/stock/models/stock_quant.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/models/base_document_layout.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/tests/tours/slides_course_member.js
  odoo/addons/base/models/res_company.py
  odoo/modules/loading.py
Labels: tmp.saas-16.1

#20653 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/static/src/components/mail_attachments/mail_attachments.js
  addons/account/tests/test_account_move_send.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_move_send.py
  addons/account_edi_ubl_cii/models/account_move_send.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/mail/models/res_company.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/purchase/models/purchase.py
  addons/snailmail_account/wizard/account_move_send.py
  addons/stock/models/stock_quant.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/datepicker/datepicker.xml
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.scss
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/window_action_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/parallax.js
  addons/website/tests/test_snippets.py
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_slides/static/tests/tours/slides_course_member.js
  odoo/addons/base/data/res.country.state.csv
  odoo/modules/loading.py
Labels: tmp.saas-16.2

#20655 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/point_of_sale/models/account_tax.py
Labels: tmp.13.0

#20656 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/point_of_sale/models/account_tax.py
  addons/survey/views/survey_templates.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/osv/expression.py
Labels: tmp.14.0

#20657 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/survey/views/survey_templates.xml
  addons/website/models/website.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/modules/registry.py
Labels: tmp.15.0

#20658 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr/static/src/scss/hr.scss
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_au/models/chart_template.py
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.js
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.xml
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_quant.py
  addons/stock_dropshipping/models/stock.py
  addons/stock_dropshipping/tests/test_dropship.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/core/assets.js
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/views/report_templates.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/static/src/js/website_sale.editor.js
  odoo/addons/base/models/res_company.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: tmp.16.0

#20659 Syncing from upstream odoo/odoo (13.0)
  addons/base_address_extended/__init__.py
Labels: 13.0

#20660 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_cl/models/account_move.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  doc/cla/corporate/vauxoo.md
Labels: 14.0

#20661 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/chart_template.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/point_of_sale/models/account_tax.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/position/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_result.html
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/osv/expression.py
Labels: 15.0

#20664 Syncing from upstream odoo/odoo (saas-15.2)
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/website/models/website.py
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/modules/registry.py
  odoo/osv/expression.py
Labels: saas-15.2

#20665 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/im_livechat/static/src/public_models/livechat_button_view.js
  addons/l10n_ie/data/account_tax_data.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.xml
  addons/mail/static/src/models/follower_list_menu_view.js
  addons/mail/tests/test_mail_render.py
  addons/mass_mailing/data/mailing_data_templates.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing_themes/views/mass_mailing_themes_templates.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/product/views/product_tag_views.xml
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/web_editor/static/tests/test_utils.js
  addons/website/models/website.py
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
  odoo/osv/expression.py
Labels: saas-16.1

#20667 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/ir_attachment.py
  addons/account/static/src/components/account_payment_field/account_payment_field.js
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account/static/src/components/journal_dashboard_activity/journal_dashboard_activity.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.js
  addons/base_import/static/src/import_action/import_action.xml
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/mail/static/src/views/activity/activity_model.js
  addons/mrp/models/mrp_production.py
  addons/pos_self_order/__manifest__.py
  addons/pos_self_order/models/pos_self_order_custom_link.py
  addons/pos_self_order/static/src/NavBar/NavBar.xml
  addons/pos_stripe/models/pos_payment_method.py
  addons/product/views/product_tag_views.xml
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_sale_project.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_unsplash/static/src/js/unsplash_beacon.js
  addons/website/models/website.py
  addons/website/static/src/js/utils.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_forum/static/src/js/website_forum.js
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
  odoo/modules/loading.py
  odoo/osv/expression.py
Labels: saas-16.3

#20670 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/im_livechat/static/src/public_models/livechat_button_view.js
  addons/l10n_ie/data/account_tax_data.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.xml
  addons/mail/static/src/models/follower_list_menu_view.js
  addons/mail/tests/test_mail_render.py
  addons/mass_mailing/data/mailing_data_templates.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing_themes/views/mass_mailing_themes_templates.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/product/views/product_tag_views.xml
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/web_editor/static/tests/test_utils.js
  addons/website/models/website.py
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
  odoo/osv/expression.py
Labels: staging.saas-16.1

#20673 Syncing from upstream odoo/odoo (staging.13.0)
  addons/base_address_extended/__init__.py
Labels: staging.13.0

#20674 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_cl/models/account_move.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  doc/cla/corporate/vauxoo.md
Labels: staging.14.0

#20678 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/web/static/src/core/position/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/website/models/website.py
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/modules/registry.py
  odoo/osv/expression.py
Labels: tmp.saas-15.2

#20679 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/im_livechat/static/src/public_models/livechat_button_view.js
  addons/l10n_ie/data/account_tax_data.xml
  addons/mail/models/mail_render_mixin.py
  addons/mail/static/src/components/follower_list_menu/follower_list_menu.xml
  addons/mail/static/src/models/follower_list_menu_view.js
  addons/mail/tests/test_mail_render.py
  addons/mass_mailing/data/mailing_data_templates.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing_themes/views/mass_mailing_themes_templates.xml
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/product/views/product_tag_views.xml
  addons/web/static/src/core/dropdown/dropdown.js
  addons/web/static/src/core/dropdown/dropdown.scss
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/views/calendar/calendar_controller.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.js
  addons/web/static/src/views/calendar/quick_create/calendar_quick_create.xml
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/core/dropdown_tests.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/calendar/calendar_quick_create_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/web_editor/static/tests/test_utils.js
  addons/website/models/website.py
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
  odoo/osv/expression.py
Labels: tmp.saas-16.1

#20681 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/ir_attachment.py
  addons/account/static/src/components/account_payment_field/account_payment_field.js
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account/static/src/components/journal_dashboard_activity/journal_dashboard_activity.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/account/static/src/components/section_and_note_fields_backend/section_and_note_fields_backend.js
  addons/base_import/static/src/import_action/import_action.xml
  addons/board/static/src/board_controller.js
  addons/board/static/src/board_controller.xml
  addons/board/static/tests/mobile/board_tests.js
  addons/mail/static/src/views/activity/activity_model.js
  addons/mrp/models/mrp_production.py
  addons/pos_self_order/__manifest__.py
  addons/pos_self_order/models/pos_self_order_custom_link.py
  addons/pos_self_order/static/src/NavBar/NavBar.xml
  addons/pos_stripe/models/pos_payment_method.py
  addons/product/views/product_tag_views.xml
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_sale_project.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_unsplash/static/src/js/unsplash_beacon.js
  addons/website/models/website.py
  addons/website/static/src/js/utils.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_forum/static/src/js/website_forum.js
  doc/cla/individual/mohamedlaminelalmi.md
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
  odoo/modules/loading.py
  odoo/osv/expression.py
Labels: tmp.saas-16.3

#20682 Syncing from upstream odoo/odoo (tmp.13.0)
  addons/base_address_extended/__init__.py
Labels: tmp.13.0

#20683 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_cl/models/account_move.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  doc/cla/corporate/vauxoo.md
Labels: tmp.14.0

#20684 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/chart_template.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/point_of_sale/models/account_tax.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/position/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_result.html
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_model.py
  odoo/osv/expression.py
Labels: tmp.15.0

#20686 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/ir_actions_report.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_fr/data/account_data.xml
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/web/views/report_templates.xml
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: 14.0

#20687 Syncing from upstream odoo/odoo (15.0)
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/xml/Screens/PaymentScreen/PaymentScreen.xml
  addons/point_of_sale/tests/test_anglo_saxon.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: 15.0

#20688 Syncing from upstream odoo/odoo (16.0)
  addons/account/data/mail_template_data.xml
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/views/account_move_views.xml
  addons/account/views/report_invoice.xml
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail/data/mail_template_data.xml
  addons/gamification/views/gamification_goal_definition_views.xml
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_cn/i18n_extra/zh_CN.po
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/account_tax_template.xml
  addons/l10n_nl/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_nl/views/res_config_settings_view.xml
  addons/point_of_sale/models/account_tax.py
  addons/product/models/product_template.py
  addons/product/static/src/scss/report_label_sheet.scss
  addons/purchase_requisition/views/purchase_views.xml
  addons/sale/data/mail_template_data.xml
  addons/sale/static/src/js/variant_mixin.js
  addons/stock/models/stock_move.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/core/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website_sale/data/mail_template_data.xml
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/website_views.xml
  doc/cla/individual/flalexg.md
  odoo/addons/base/views/ir_default_views.xml
  odoo/addons/base/views/ir_model_views.xml
  odoo/modules/registry.py
Labels: 16.0

#20690 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/chart_template.py
  addons/l10n_ie/data/account_tax_data.xml
  addons/point_of_sale/models/account_tax.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/position/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_clipboard.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/libre_result.html
  addons/web_editor/static/lib/odoo-editor/test/utils.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_statistics.py
Labels: saas-15.2

#20691 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/data/mail_template_data.xml
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_edi_document.py
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail/data/mail_template_data.xml
  addons/gamification/views/gamification_goal_definition_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_bom_structure.py
  addons/point_of_sale/models/account_tax.py
  addons/pos_loyalty/static/src/js/PaymentScreen.js
  addons/pos_restaurant/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/sale/data/mail_template_data.xml
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/stock/models/stock_move.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/web_editor.backend.scss
  addons/web_editor/static/tests/field_html_tests.js
  addons/web_editor/static/tests/test_utils.js
  addons/website/static/tests/tours/website_text_edition.js
  addons/website/tests/test_ui.py
  addons/website_sale/data/mail_template_data.xml
  addons/website_sale/models/product_template.py
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/tests/test_website_sale_product.py
  addons/website_sale/views/templates.xml
  addons/website_sale/views/website_views.xml
  doc/cla/individual/flalexg.md
  odoo/addons/base/views/ir_default_views.xml
  odoo/addons/base/views/ir_model_views.xml
  odoo/modules/registry.py
Labels: saas-16.1

#20699 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/ir_actions_report.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_fr/data/account_data.xml
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/web/views/report_templates.xml
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: staging.14.0

#20707 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/ir_actions_report.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_fr/data/account_data.xml
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/web/views/report_templates.xml
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website_form/static/src/snippets/s_website_form/000.js
Labels: tmp.14.0

#20708 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/xml/Screens/PaymentScreen/PaymentScreen.xml
  addons/point_of_sale/tests/test_anglo_saxon.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.15.0

#20709 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/data/mail_template_data.xml
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/views/account_move_views.xml
  addons/account/views/report_invoice.xml
  addons/auth_signup/data/mail_template_data.xml
  addons/auth_totp_mail/data/mail_template_data.xml
  addons/gamification/views/gamification_goal_definition_views.xml
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/common.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_cn/i18n_extra/zh_CN.po
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/account_tax_template.xml
  addons/l10n_nl/migrations/3.1/post-migrate_update_taxes.py
  addons/l10n_nl/views/res_config_settings_view.xml
  addons/point_of_sale/models/account_tax.py
  addons/product/models/product_template.py
  addons/product/static/src/scss/report_label_sheet.scss
  addons/purchase_requisition/views/purchase_views.xml
  addons/sale/data/mail_template_data.xml
  addons/sale/static/src/js/variant_mixin.js
  addons/stock/models/stock_move.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/core/position_hook.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website_sale/data/mail_template_data.xml
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/views/website_views.xml
  doc/cla/individual/flalexg.md
  odoo/addons/base/views/ir_default_views.xml
  odoo/addons/base/views/ir_model_views.xml
  odoo/modules/registry.py
Labels: tmp.16.0

#20713 Syncing from upstream odoo/odoo (master)
  addons/bus/controllers/websocket.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/im_livechat/controllers/main.py
  addons/project/models/project_task.py
  addons/project/tests/test_project_base.py
  addons/project/tests/test_project_subtasks.py
  addons/project/views/project_task_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_child_tasks.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_timesheet/models/project.py
  addons/test_website/tests/test_qweb.py
  addons/web/static/src/core/confirmation_dialog/confirmation_dialog.xml
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/tests/test_assets.py
  addons/web/tests/test_assets_xml.py
  addons/web/tests/test_js.py
  addons/web_editor/controllers/main.py
  addons/website/models/ir_asset.py
  addons/website/models/ir_qweb.py
  addons/website/models/website.py
  addons/website/tests/test_ir_asset.py
  addons/website/tests/test_performance.py
  addons/website/tests/test_ui.py
  doc/cla/individual/jasonribble.md
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/ir_asset.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
  odoo/tests/common.py
Labels: master

#20715 Syncing from upstream odoo/odoo (saas-16.3)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/project/models/project_task.py
  addons/project/tests/test_project_base.py
  addons/project/tests/test_project_subtasks.py
  addons/project/views/project_task_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_child_tasks.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_timesheet/models/project.py
  doc/cla/individual/jasonribble.md
Labels: saas-16.3

#20718 Syncing from upstream odoo/odoo (staging.saas-16.1)
  doc/cla/individual/jasonribble.md
Labels: staging.saas-16.1

#20724 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  doc/cla/individual/jasonribble.md
Labels: tmp.saas-16.1

#20725 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  doc/cla/individual/jasonribble.md
Labels: tmp.saas-16.2

#20726 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/project/models/project_task.py
  addons/project/tests/test_project_base.py
  addons/project/tests/test_project_subtasks.py
  addons/project/views/project_task_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale_project/models/project.py
  addons/sale_project/tests/test_child_tasks.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_project/views/project_task_views.xml
  addons/sale_timesheet/models/project.py
  doc/cla/individual/jasonribble.md
Labels: tmp.saas-16.3

#20727 Syncing from upstream odoo/odoo (tmp.16.0)
  doc/cla/individual/jasonribble.md
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
Labels: tmp.16.0

#20742 Syncing from upstream odoo/odoo (14.0)
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/website_forum/static/src/js/website_forum.js
Labels: 14.0

#20743 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_in_upi/models/account_invoice.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_forum/static/src/js/website_forum.js
Labels: 15.0

#20744 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr_holidays/data/hr_holidays_demo.xml
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/static/src/views/calendar/calendar_controller.js
  addons/hr_holidays/static/src/views/calendar/calendar_renderer.scss
  addons/hr_holidays/static/src/views/calendar/filter_panel/calendar_filter_panel.js
  addons/hr_holidays/static/src/views/calendar/filter_panel/calendar_filter_panel.scss
  addons/hr_holidays/static/src/views/calendar/filter_panel/calendar_filter_panel.xml
  addons/hr_holidays/static/src/views/calendar/year/calendar_year_popover.js
  addons/hr_holidays/static/src/views/calendar/year/calendar_year_popover.xml
  addons/hr_holidays/static/src/views/calendar/year/calendar_year_renderer.js
  addons/hr_holidays/static/src/views/hooks.js
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/views/report_invoice.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/point_of_sale/controllers/main.py
  addons/spreadsheet/static/tests/utils/commands.js
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_popover.js
  addons/web/static/src/views/calendar/utils.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/tests/views/calendar/calendar_common_popover_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/views/templates.xml
  addons/website_sale_stock/__manifest__.py
  addons/website_sale_stock/static/tests/tours/website_sale_stock_multilang.js
  addons/website_sale_stock/tests/__init__.py
  addons/website_sale_stock/tests/test_website_sale_stock_multilang.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: 16.0

#20746 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/ir_actions_report.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: saas-15.2

#20747 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/views/account_move_views.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr/static/src/scss/hr.scss
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr/views/hr_employee_public_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr/views/res_users.xml
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_recruitment/static/src/scss/hr_applicant.scss
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/account_tax_template.xml
  addons/l10n_nl/migrations/3.1/post-migrate_update_taxes.py
  addons/product/models/product_template.py
  addons/purchase_requisition/views/purchase_views.xml
  addons/sale/static/src/js/variant_mixin.js
  addons/sms/static/src/components/sms_button/sms_button.js
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_sms/models/stock_picking.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/phone/phone_field.scss
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/backend/html_field.xml
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/tests/tours/snippet_editor_panel_options.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: saas-16.1

#20752 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/views/account_move_views.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr/static/src/scss/hr.scss
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr/views/hr_employee_public_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr/views/res_users.xml
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_recruitment/static/src/scss/hr_applicant.scss
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/account_tax_template.xml
  addons/l10n_nl/migrations/3.1/post-migrate_update_taxes.py
  addons/product/models/product_template.py
  addons/purchase_requisition/views/purchase_views.xml
  addons/sale/static/src/js/variant_mixin.js
  addons/sms/static/src/components/sms_button/sms_button.js
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_sms/models/stock_picking.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/phone/phone_field.scss
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/backend/html_field.xml
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/tests/tours/snippet_editor_panel_options.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: staging.saas-16.1

#20759 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/ir_actions_report.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/stock_account/models/stock_move.py
  addons/stock_dropshipping/tests/test_stockvaluation.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/tests/legacy/views/form_tests.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/excel_result.html
  addons/web_editor/static/lib/odoo-editor/test/spec/html_tables/google_result.html
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.saas-15.2

#20760 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/views/account_move_views.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr/static/src/scss/hr.scss
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr/views/hr_employee_public_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr/views/res_users.xml
  addons/hr_expense/models/account_move.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_recruitment/static/src/scss/hr_applicant.scss
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/account_tax_template.xml
  addons/l10n_nl/migrations/3.1/post-migrate_update_taxes.py
  addons/product/models/product_template.py
  addons/purchase_requisition/views/purchase_views.xml
  addons/sale/static/src/js/variant_mixin.js
  addons/sms/static/src/components/sms_button/sms_button.js
  addons/sms/wizard/sms_composer.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_sms/models/stock_picking.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/phone/phone_field.scss
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/backend/html_field.xml
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/tests/tours/snippet_editor_panel_options.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.saas-16.1

#20761 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/models/company.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/src/components/tax_totals/tax_totals.xml
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_edi_document.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr/static/src/scss/hr.scss
  addons/hr/views/hr_employee_public_views.xml
  addons/hr/views/hr_employee_views.xml
  addons/hr/views/res_users.xml
  addons/hr_recruitment/static/src/scss/hr_applicant.scss
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/public_models/chatbot.js
  addons/l10n_cl/models/account_move.py
  addons/product/models/product_template.py
  addons/purchase_requisition/views/purchase_views.xml
  addons/sale/static/src/js/variant_mixin.js
  addons/sms/wizard/sms_composer.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/stock_sms/models/stock_picking.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/web/static/src/views/fields/phone/phone_field.scss
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/tests/tours/snippet_editor_panel_options.js
  addons/website_sale/models/product_template.py
  addons/website_sale/static/src/js/website_sale.js
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.saas-16.2

#20765 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr_holidays/data/hr_holidays_demo.xml
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/static/src/views/calendar/calendar_controller.js
  addons/hr_holidays/static/src/views/calendar/calendar_renderer.scss
  addons/hr_holidays/static/src/views/calendar/filter_panel/calendar_filter_panel.js
  addons/hr_holidays/static/src/views/calendar/filter_panel/calendar_filter_panel.scss
  addons/hr_holidays/static/src/views/calendar/filter_panel/calendar_filter_panel.xml
  addons/hr_holidays/static/src/views/calendar/year/calendar_year_popover.js
  addons/hr_holidays/static/src/views/calendar/year/calendar_year_popover.xml
  addons/hr_holidays/static/src/views/calendar/year/calendar_year_renderer.js
  addons/hr_holidays/static/src/views/hooks.js
  addons/hr_timesheet/views/project_views.xml
  addons/l10n_cl/models/account_move.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/views/report_invoice.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/point_of_sale/controllers/main.py
  addons/spreadsheet/static/tests/utils/commands.js
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_stock_flow.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_popover.js
  addons/web/static/src/views/calendar/utils.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/tests/views/calendar/calendar_common_popover_tests.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/i18n/website.pot
  addons/website/models/website_rewrite.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/views/templates.xml
  addons/website_sale_stock/__manifest__.py
  addons/website_sale_stock/static/tests/tours/website_sale_stock_multilang.js
  addons/website_sale_stock/tests/__init__.py
  addons/website_sale_stock/tests/test_website_sale_stock_multilang.py
  odoo/addons/base/models/ir_module.py
  odoo/modules/module.py
Labels: tmp.16.0

#20766 Syncing from upstream odoo/odoo (14.0)
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_es/data/account_tax_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: 14.0

#20767 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_sa/data/account_tax_group.xml
  addons/l10n_sa/demo/demo_company.xml
  addons/l10n_sa_edi/__init__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/data/account_edi_format.xml
  addons/l10n_sa_edi/data/pre-hash_invoice.xsl
  addons/l10n_sa_edi/data/res_country_data.xml
  addons/l10n_sa_edi/data/ubl_21_zatca.xml
  addons/l10n_sa_edi/demo/demo_company.xml
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_document.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_tax.py
  addons/l10n_sa_edi/models/res_company.py
  addons/l10n_sa_edi/models/res_config_settings.py
  addons/l10n_sa_edi/models/res_partner.py
  addons/l10n_sa_edi/security/ir.model.access.csv
  addons/l10n_sa_edi/static/src/scss/form_view.scss
  addons/l10n_sa_edi/tests/__init__.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/views/account_journal_views.xml
  addons/l10n_sa_edi/views/account_tax_views.xml
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_edi/views/res_company_views.xml
  addons/l10n_sa_edi/views/res_config_settings_view.xml
  addons/l10n_sa_edi/views/res_partner_views.xml
  addons/l10n_sa_edi/wizard/__init__.py
  addons/l10n_sa_edi/wizard/account_debit_note.py
  addons/l10n_sa_edi/wizard/account_move_reversal.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_discount/static/src/js/models.js
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
Labels: 15.0

#20768 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/crm/static/tests/tours/crm_rainbowman.js
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_sg/demo/demo_company.xml
  addons/loyalty/models/loyalty_program.py
  addons/mail/static/src/models/messaging_menu.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_account/models/account_move.py
  addons/survey/static/src/scss/survey_survey_views.scss
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_website/tests/test_performance.py
  addons/web/static/tests/qunit.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/tests/test_performance.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/pixora.md
  odoo/http.py
  odoo/sql_db.py
  odoo/tools/xml_utils.py
Labels: 16.0

#20770 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_journal.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_sa/data/account_tax_group.xml
  addons/l10n_sa/demo/demo_company.xml
  addons/l10n_sa_edi/__init__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/data/account_edi_format.xml
  addons/l10n_sa_edi/data/pre-hash_invoice.xsl
  addons/l10n_sa_edi/data/res_country_data.xml
  addons/l10n_sa_edi/data/ubl_21_zatca.xml
  addons/l10n_sa_edi/demo/demo_company.xml
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_document.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_tax.py
  addons/l10n_sa_edi/models/res_company.py
  addons/l10n_sa_edi/models/res_config_settings.py
  addons/l10n_sa_edi/models/res_partner.py
  addons/l10n_sa_edi/security/ir.model.access.csv
  addons/l10n_sa_edi/static/src/scss/form_view.scss
  addons/l10n_sa_edi/tests/__init__.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/views/account_journal_views.xml
  addons/l10n_sa_edi/views/account_tax_views.xml
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_edi/views/res_company_views.xml
  addons/l10n_sa_edi/views/res_config_settings_view.xml
  addons/l10n_sa_edi/views/res_partner_views.xml
  addons/l10n_sa_edi/wizard/__init__.py
  addons/l10n_sa_edi/wizard/account_debit_note.py
  addons/l10n_sa_edi/wizard/account_move_reversal.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_forum/static/src/js/website_forum.js
Labels: saas-15.2

#20779 Syncing from upstream odoo/odoo (staging.14.0)
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_es/data/account_tax_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: staging.14.0

#20783 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_journal.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_holidays/models/hr_employee.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_sa/data/account_tax_group.xml
  addons/l10n_sa/demo/demo_company.xml
  addons/l10n_sa_edi/__init__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/data/account_edi_format.xml
  addons/l10n_sa_edi/data/pre-hash_invoice.xsl
  addons/l10n_sa_edi/data/res_country_data.xml
  addons/l10n_sa_edi/data/ubl_21_zatca.xml
  addons/l10n_sa_edi/demo/demo_company.xml
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_document.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_tax.py
  addons/l10n_sa_edi/models/res_company.py
  addons/l10n_sa_edi/models/res_config_settings.py
  addons/l10n_sa_edi/models/res_partner.py
  addons/l10n_sa_edi/security/ir.model.access.csv
  addons/l10n_sa_edi/static/src/scss/form_view.scss
  addons/l10n_sa_edi/tests/__init__.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/views/account_journal_views.xml
  addons/l10n_sa_edi/views/account_tax_views.xml
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_edi/views/res_company_views.xml
  addons/l10n_sa_edi/views/res_config_settings_view.xml
  addons/l10n_sa_edi/views/res_partner_views.xml
  addons/l10n_sa_edi/wizard/__init__.py
  addons/l10n_sa_edi/wizard/account_debit_note.py
  addons/l10n_sa_edi/wizard/account_move_reversal.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website_forum/static/src/js/website_forum.js
Labels: tmp.saas-15.2

#20787 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hr_timesheet/models/project.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_es/data/account_tax_data.xml
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: tmp.14.0

#20788 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_sa/data/account_tax_group.xml
  addons/l10n_sa/demo/demo_company.xml
  addons/l10n_sa_edi/__init__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/data/account_edi_format.xml
  addons/l10n_sa_edi/data/pre-hash_invoice.xsl
  addons/l10n_sa_edi/data/res_country_data.xml
  addons/l10n_sa_edi/data/ubl_21_zatca.xml
  addons/l10n_sa_edi/demo/demo_company.xml
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_document.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_tax.py
  addons/l10n_sa_edi/models/res_company.py
  addons/l10n_sa_edi/models/res_config_settings.py
  addons/l10n_sa_edi/models/res_partner.py
  addons/l10n_sa_edi/security/ir.model.access.csv
  addons/l10n_sa_edi/static/src/scss/form_view.scss
  addons/l10n_sa_edi/tests/__init__.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/views/account_journal_views.xml
  addons/l10n_sa_edi/views/account_tax_views.xml
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_edi/views/res_company_views.xml
  addons/l10n_sa_edi/views/res_config_settings_view.xml
  addons/l10n_sa_edi/views/res_partner_views.xml
  addons/l10n_sa_edi/wizard/__init__.py
  addons/l10n_sa_edi/wizard/account_debit_note.py
  addons/l10n_sa_edi/wizard/account_move_reversal.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.py
  addons/l10n_sa_edi/wizard/l10n_sa_edi_otp_wizard.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_discount/static/src/js/models.js
  addons/test_mail/tests/test_mail_multicompany.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/options.js
Labels: tmp.15.0

#20789 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_journal.py
  addons/account/models/ir_actions_report.py
  addons/crm/static/tests/tours/crm_rainbowman.js
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_fr/data/account_tax_group_data.xml
  addons/l10n_in_upi/models/account_invoice.py
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_sg/demo/demo_company.xml
  addons/loyalty/models/loyalty_program.py
  addons/mail/static/src/models/messaging_menu.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_account/models/account_move.py
  addons/survey/static/src/scss/survey_survey_views.scss
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_website/tests/test_performance.py
  addons/web/static/tests/qunit.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/tests/test_performance.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/models/sale_order.py
  doc/cla/corporate/pixora.md
  odoo/http.py
  odoo/sql_db.py
  odoo/tools/xml_utils.py
Labels: tmp.16.0

#20790 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_ch/models/mail_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/models/hr_recruitment.py
Labels: 14.0

#20791 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/mrp_account/models/mrp_bom.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
Labels: 15.0

#20792 Syncing from upstream odoo/odoo (16.0)
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/static/tests/tours/tax_group_tests.js
  addons/account/tests/test_tour.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/analytic/models/analytic_plan.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_recruitment/views/hr_job_views.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_picking.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  addons/website_slides/controllers/main.py
  odoo/models.py
Labels: 16.0

#20794 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_ch/models/mail_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: saas-15.2

#20795 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/analytic/models/analytic_plan.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/views/report_invoice.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_sg/demo/demo_company.xml
  addons/loyalty/models/loyalty_program.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/i18n/ar.po
  addons/sale/i18n/de.po
  addons/sale/i18n/es.po
  addons/sale/i18n/es_MX.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/id.po
  addons/sale/i18n/it.po
  addons/sale/i18n/ja.po
  addons/sale/i18n/ko.po
  addons/sale/i18n/nl.po
  addons/sale/i18n/pl.po
  addons/sale/i18n/pt.po
  addons/sale/i18n/pt_BR.po
  addons/sale/i18n/th.po
  addons/sale/i18n/vi.po
  addons/sale/i18n/zh_CN.po
  addons/sale/i18n/zh_TW.po
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/stock_account/models/account_move.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
  odoo/tools/xml_utils.py
Labels: saas-16.1

#20797 Syncing from upstream odoo/odoo (saas-16.3)
  addons/hr/models/hr_employee.py
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/l10n_sg/demo/demo_company.xml
  addons/loyalty/models/loyalty_program.py
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/discuss/channel_invitation.js
  addons/mail/static/src/discuss/web/chat_window_patch.xml
  addons/mail/static/src/js/utils.js
  addons/mail/static/src/utils/format.js
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/mail/static/tests/discuss/channel_invitation_tests.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/point_of_sale/models/account_tax.py
  addons/pos_restaurant/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/spreadsheet/static/tests/utils/commands.js
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/kanban/kanban_header.xml
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
  odoo/tools/xml_utils.py
Labels: saas-16.3

#20800 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/analytic/models/analytic_plan.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/views/report_invoice.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/loyalty/models/loyalty_program.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/i18n/ar.po
  addons/sale/i18n/de.po
  addons/sale/i18n/es.po
  addons/sale/i18n/es_MX.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/id.po
  addons/sale/i18n/it.po
  addons/sale/i18n/ja.po
  addons/sale/i18n/ko.po
  addons/sale/i18n/nl.po
  addons/sale/i18n/pl.po
  addons/sale/i18n/pt.po
  addons/sale/i18n/pt_BR.po
  addons/sale/i18n/th.po
  addons/sale/i18n/vi.po
  addons/sale/i18n/zh_CN.po
  addons/sale/i18n/zh_TW.po
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/stock_account/models/account_move.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
  odoo/tools/xml_utils.py
Labels: staging.saas-16.1

#20803 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_ch/models/mail_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/models/hr_recruitment.py
Labels: staging.14.0

#20807 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_ch/models/mail_template.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/account_move.py
  addons/website/static/src/snippets/s_table_of_content/000.js
Labels: tmp.saas-15.2

#20808 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/views/report_invoice.xml
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/analytic/models/analytic_plan.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/views/report_invoice.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/loyalty/models/loyalty_program.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale/i18n/ar.po
  addons/sale/i18n/de.po
  addons/sale/i18n/es.po
  addons/sale/i18n/es_MX.po
  addons/sale/i18n/fr.po
  addons/sale/i18n/id.po
  addons/sale/i18n/it.po
  addons/sale/i18n/ja.po
  addons/sale/i18n/ko.po
  addons/sale/i18n/nl.po
  addons/sale/i18n/pl.po
  addons/sale/i18n/pt.po
  addons/sale/i18n/pt_BR.po
  addons/sale/i18n/th.po
  addons/sale/i18n/vi.po
  addons/sale/i18n/zh_CN.po
  addons/sale/i18n/zh_TW.po
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/stock_account/models/account_move.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
  odoo/tools/xml_utils.py
Labels: tmp.saas-16.1

#20810 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/hr/models/hr_employee.py
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_it_stock_ddt/data/l10n_it_ddt_template.xml
  addons/loyalty/models/loyalty_program.py
  addons/mail/static/src/core_ui/message.xml
  addons/mail/static/src/discuss/channel_invitation.js
  addons/mail/static/src/discuss/web/chat_window_patch.xml
  addons/mail/static/src/js/utils.js
  addons/mail/static/src/utils/format.js
  addons/mail/static/src/views/activity/activity_renderer.js
  addons/mail/static/tests/discuss/channel_invitation_tests.js
  addons/mail/static/tests/mail_utils_tests.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/point_of_sale/models/account_tax.py
  addons/pos_restaurant/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/spreadsheet/static/tests/utils/commands.js
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/kanban/kanban_header.xml
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/http.py
  odoo/tools/xml_utils.py
Labels: tmp.saas-16.3
