Repository brain-tec/odoo, pull requests merged in 2023-04, with the labels that each got.

#19336 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/point_of_sale/static/src/js/db.js
  addons/purchase_stock/models/purchase.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  doc/cla/individual/tranngocson1996.md
Labels: 14.0

#19337 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/data/account_edi_data.xml
  addons/account_edi_ubl_cii/models/__init__.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_sg.py
  addons/google_recaptcha/static/src/js/recaptcha.js
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/mrp/views/mrp_production_views.xml
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/project/controllers/portal.py
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/shapes/convert.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_blog/static/src/js/website_blog.js
  addons/website_event_exhibitor/static/src/js/event_exhibitor_connect.js
  addons/website_event_track/static/src/js/website_event_track_proposal_form.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  addons/website_sale_stock_wishlist/static/src/js/wishlist.js
  addons/website_slides/static/src/js/slides_course_join.js
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_twitter/static/src/js/website.twitter.animation.js
  doc/cla/individual/tranngocson1996.md
Labels: 15.0

#19338 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_reconcile_model.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/mail/static/src/components/activity_box/activity_box.scss
  addons/mail/static/src/components/activity_box/activity_box.xml
  addons/mail/static/src/components/chatter_container/chatter_container.scss
  addons/mail/static/src/components/chatter_container/chatter_container.xml
  addons/mail/static/src/components/chatter_topbar/chatter_topbar.scss
  addons/mail/static/src/components/chatter_topbar/chatter_topbar.xml
  addons/mail/static/src/widgets/form_renderer/form_renderer.scss
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/static/src/xml/mailing_filter_widget.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_storage_category.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_storage_category_views.xml
  addons/stock_account/tests/test_account_move.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.js
  addons/web/static/src/views/view_dialogs/export_data_dialog.xml
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web/static/tests/views/view_dialogs/export_data_dialog_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_blog/static/src/snippets/s_blog_posts/000.scss
  addons/website_sale/models/product_template.py
  addons/website_sale_stock/models/product_product.py
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/tranngocson1996.md
Labels: 16.0

#19340 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/stock/models/stock_storage_category.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  addons/stock/views/stock_storage_category_views.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_sale/models/product_template.py
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/tranngocson1996.md
Labels: saas-15.2

#19347 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/point_of_sale/static/src/js/db.js
  addons/purchase_stock/models/purchase.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  doc/cla/individual/tranngocson1996.md
Labels: staging.14.0

#19351 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/stock/models/stock_storage_category.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  addons/stock/views/stock_storage_category_views.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_sale/models/product_template.py
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/tranngocson1996.md
Labels: tmp.saas-15.2

#19354 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/point_of_sale/static/src/js/db.js
  addons/purchase_stock/models/purchase.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  doc/cla/individual/tranngocson1996.md
Labels: tmp.14.0

#19355 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/data/account_edi_data.xml
  addons/account_edi_ubl_cii/models/__init__.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_sg.py
  addons/google_recaptcha/static/src/js/recaptcha.js
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/mrp/views/mrp_production_views.xml
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/project/controllers/portal.py
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/stock/static/src/js/stock_orderpoint_list_controller.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/shapes/convert.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_blog/static/src/js/website_blog.js
  addons/website_event_exhibitor/static/src/js/event_exhibitor_connect.js
  addons/website_event_track/static/src/js/website_event_track_proposal_form.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  addons/website_sale_stock_wishlist/static/src/js/wishlist.js
  addons/website_slides/static/src/js/slides_course_join.js
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_twitter/static/src/js/website.twitter.animation.js
  doc/cla/individual/tranngocson1996.md
Labels: tmp.15.0

#19357 Syncing from upstream odoo/odoo (14.0)
  doc/cla/corporate/vauxoo.md
Labels: 14.0

#19360 Syncing from upstream odoo/odoo (master)
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
Labels: master

#19361 Syncing from upstream odoo/odoo (saas-16.1)
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
Labels: saas-16.1

#19362 Syncing from upstream odoo/odoo (saas-16.2)
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
Labels: saas-16.2

#19365 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
Labels: staging.saas-16.1

#19367 Syncing from upstream odoo/odoo (staging.14.0)
  doc/cla/corporate/vauxoo.md
Labels: staging.14.0

#19371 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/project/controllers/portal.py
  addons/project/models/project.py
Labels: tmp.saas-15.2

#19372 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
Labels: tmp.saas-16.1

#19373 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/spreadsheet_account/tests/test_company_fiscal_year.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
Labels: tmp.saas-16.2

#19374 Syncing from upstream odoo/odoo (tmp.14.0)
  doc/cla/corporate/vauxoo.md
Labels: tmp.14.0

#19375 Syncing from upstream odoo/odoo (16.0)
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/snippets/s_popup/000.js
Labels: 16.0

#19376 Syncing from upstream odoo/odoo (master)
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_blog/static/src/snippets/s_blog_posts/000.scss
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  addons/website_mass_mailing/static/src/snippets/s_popup/000.js
  addons/website_mass_mailing/views/snippets_templates.xml
Labels: master

#19377 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/fr.po
  addons/account/i18n/vi.po
  addons/account/i18n/zh_CN.po
  addons/account_edi/i18n/de.po
  addons/account_edi_ubl_cii/i18n/de.po
  addons/account_edi_ubl_cii/i18n/es.po
  addons/account_edi_ubl_cii/i18n/es_MX.po
  addons/account_edi_ubl_cii/i18n/fr.po
  addons/account_edi_ubl_cii/i18n/it.po
  addons/account_edi_ubl_cii/i18n/nl.po
  addons/account_edi_ubl_cii/i18n/uk.po
  addons/account_edi_ubl_cii/i18n/vi.po
  addons/account_edi_ubl_cii/i18n/zh_CN.po
  addons/account_edi_ubl_cii/i18n/zh_TW.po
  addons/base_automation/i18n/nl.po
  addons/crm/i18n/vi.po
  addons/hr/i18n/es.po
  addons/hr/i18n/vi.po
  addons/hr_attendance/i18n/de.po
  addons/hr_expense/i18n/vi.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/vi.po
Labels: saas-15.2

#19379 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/es.po
  addons/account/i18n/fr.po
  addons/account_payment/i18n/zh_CN.po
  addons/base_import/i18n/vi.po
  addons/bus/i18n/de.po
  addons/crm/i18n/vi.po
  addons/hr/i18n/vi.po
  addons/hr_contract/i18n/vi.po
  addons/hr_expense/i18n/vi.po
  addons/hr_presence/i18n/de.po
  addons/hr_work_entry/i18n/vi.po
  addons/im_livechat/i18n/de.po
  addons/mail/i18n/de.po
  addons/mail/i18n/vi.po
  addons/payment/i18n/de.po
  addons/payment/i18n/vi.po
  addons/phone_validation/i18n/de.po
  addons/point_of_sale/i18n/fr.po
  addons/point_of_sale/i18n/vi.po
  addons/pos_epson_printer/i18n/vi.po
  addons/project/i18n/de.po
  addons/project/i18n/vi.po
  addons/purchase/i18n/ar.po
  addons/purchase_requisition/i18n/ar.po
  addons/purchase_requisition/i18n/es.po
  addons/sale_timesheet/i18n/de.po
  addons/stock_account/i18n/vi.po
  addons/stock_landed_costs/i18n/ar.po
  addons/survey/i18n/de.po
  addons/web/i18n/de.po
  addons/web/i18n/vi.po
  addons/web_editor/i18n/de.po
  addons/web_editor/i18n/vi.po
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/fr.po
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_blog/static/src/snippets/s_blog_posts/000.scss
  addons/website_event_track/i18n/ar.po
Labels: saas-16.2

#19387 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/fr.po
  addons/account/i18n/vi.po
  addons/account/i18n/zh_CN.po
  addons/account_edi/i18n/de.po
  addons/account_edi_ubl_cii/i18n/de.po
  addons/account_edi_ubl_cii/i18n/es.po
  addons/account_edi_ubl_cii/i18n/es_MX.po
  addons/account_edi_ubl_cii/i18n/fr.po
  addons/account_edi_ubl_cii/i18n/it.po
  addons/account_edi_ubl_cii/i18n/nl.po
  addons/account_edi_ubl_cii/i18n/uk.po
  addons/account_edi_ubl_cii/i18n/vi.po
  addons/account_edi_ubl_cii/i18n/zh_CN.po
  addons/account_edi_ubl_cii/i18n/zh_TW.po
  addons/base_automation/i18n/nl.po
  addons/crm/i18n/vi.po
  addons/hr/i18n/es.po
  addons/hr/i18n/vi.po
  addons/hr_attendance/i18n/de.po
  addons/hr_expense/i18n/vi.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/nl.po
  odoo/addons/base/i18n/vi.po
Labels: tmp.saas-15.2

#19389 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/i18n/es.po
  addons/account/i18n/fr.po
  addons/account_payment/i18n/zh_CN.po
  addons/base_import/i18n/vi.po
  addons/bus/i18n/de.po
  addons/crm/i18n/vi.po
  addons/hr/i18n/vi.po
  addons/hr_contract/i18n/vi.po
  addons/hr_expense/i18n/vi.po
  addons/hr_presence/i18n/de.po
  addons/hr_work_entry/i18n/vi.po
  addons/im_livechat/i18n/de.po
  addons/mail/i18n/de.po
  addons/mail/i18n/vi.po
  addons/payment/i18n/de.po
  addons/payment/i18n/vi.po
  addons/phone_validation/i18n/de.po
  addons/point_of_sale/i18n/fr.po
  addons/point_of_sale/i18n/vi.po
  addons/pos_epson_printer/i18n/vi.po
  addons/project/i18n/de.po
  addons/project/i18n/vi.po
  addons/purchase/i18n/ar.po
  addons/purchase_requisition/i18n/ar.po
  addons/purchase_requisition/i18n/es.po
  addons/sale_timesheet/i18n/de.po
  addons/stock_account/i18n/vi.po
  addons/stock_landed_costs/i18n/ar.po
  addons/survey/i18n/de.po
  addons/web/i18n/de.po
  addons/web/i18n/vi.po
  addons/web_editor/i18n/de.po
  addons/web_editor/i18n/vi.po
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/fr.po
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_blog/static/src/snippets/s_blog_posts/000.scss
  addons/website_event_track/i18n/ar.po
Labels: tmp.saas-16.2

#19392 [bt#22075] set user to none
  addons/microsoft_outlook/models/ir_mail_server.py
Labels: 11.0.project_co_286

#19393 Syncing from upstream odoo/odoo (14.0)
  addons/account/models/account_move.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: 14.0

#19394 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/point_of_sale/static/src/js/db.js
  addons/web_editor/controllers/main.py
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: 15.0

#19395 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/wizard/account_payment_register.py
  addons/hr_timesheet/models/project.py
  addons/l10n_be/data/account_tax_report_data.xml
  addons/l10n_be/i18n/de.po
  addons/l10n_be/i18n/fr.po
  addons/l10n_be/i18n/l10n_be.pot
  addons/l10n_be/i18n/nl.po
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/mail/static/src/models/attachment_viewer.js
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/static/src/js/db.js
  addons/project/controllers/portal.py
  addons/project/models/project.py
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase_stock/models/purchase.py
  addons/sale/report/ir_actions_report_templates.xml
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/spreadsheet/static/tests/utils/model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/controllers/main.py
  addons/website_profile/views/website_profile.xml
  doc/cla/corporate/stesiconsultingsrl.md
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: 16.0

#19397 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/point_of_sale/static/src/js/db.js
  addons/project/controllers/portal.py
  addons/project/models/project.py
  addons/purchase_stock/models/purchase.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web_editor/controllers/main.py
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: saas-15.2

#19398 Syncing from upstream odoo/odoo (saas-16.1)
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_column_quick_create.js
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_renderer.js
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_renderer.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/hr_timesheet/models/project.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/mail/static/src/components/message_list/message_list.js
  addons/project/models/project.py
  addons/project/static/src/js/project_task_kanban_examples.js
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase_stock/models/purchase.py
  addons/sale/report/ir_actions_report_templates.xml
  addons/sale_timesheet/views/project_task_views.xml
  addons/utm/static/src/js/utm_campaign_kanban_examples.js
  addons/web/i18n/web.pot
  addons/web/static/src/boot.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.xml
  addons/web/static/src/views/kanban/kanban_renderer.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/controllers/main.py
  addons/website/__manifest__.py
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/adapt_content.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/tests/test_qweb.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/fields.py
  odoo/models.py
Labels: saas-16.1

#19402 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_column_quick_create.js
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_renderer.js
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_renderer.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/hr_timesheet/models/project.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/mail/static/src/components/message_list/message_list.js
  addons/project/models/project.py
  addons/project/static/src/js/project_task_kanban_examples.js
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase_stock/models/purchase.py
  addons/sale/report/ir_actions_report_templates.xml
  addons/sale_timesheet/views/project_task_views.xml
  addons/utm/static/src/js/utm_campaign_kanban_examples.js
  addons/web/i18n/web.pot
  addons/web/static/src/boot.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.xml
  addons/web/static/src/views/kanban/kanban_renderer.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/controllers/main.py
  addons/website/__manifest__.py
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/adapt_content.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/tests/test_qweb.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-16.1

#19404 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account/models/account_move.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: staging.14.0

#19409 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_column_quick_create.js
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_renderer.js
  addons/crm/static/src/views/forecast_kanban/forecast_kanban_renderer.xml
  addons/delivery/models/delivery_carrier.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/hr_timesheet/models/project.py
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/mail/static/src/components/message_list/message_list.js
  addons/project/models/project.py
  addons/project/static/src/js/project_task_kanban_examples.js
  addons/purchase/report/purchase_order_templates.xml
  addons/purchase_stock/models/purchase.py
  addons/sale/report/ir_actions_report_templates.xml
  addons/sale_timesheet/views/project_task_views.xml
  addons/utm/static/src/js/utm_campaign_kanban_examples.js
  addons/web/i18n/web.pot
  addons/web/static/src/boot.js
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.js
  addons/web/static/src/views/kanban/kanban_column_quick_create.xml
  addons/web/static/src/views/kanban/kanban_renderer.js
  addons/web/static/src/views/kanban/kanban_renderer.xml
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/tests/views/kanban_view_tests.js
  addons/web_editor/controllers/main.py
  addons/website/__manifest__.py
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/adapt_content.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/tests/test_qweb.py
  addons/website_slides/controllers/main.py
  addons/website_slides/static/src/js/slides_course_quiz.js
  addons/website_slides/static/src/scss/slides_slide_fullscreen.scss
  addons/website_slides/static/src/xml/slide_quiz.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/models/res_users.py
  odoo/addons/test_assetsbundle/tests/test_assetsbundle.py
  odoo/fields.py
  odoo/models.py
Labels: tmp.saas-16.1

#19411 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account/models/account_move.py
  addons/web_editor/controllers/main.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: tmp.14.0

#19412 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/l10n_fr_pos_cert/models/res_company.py
  addons/point_of_sale/static/src/js/db.js
  addons/web_editor/controllers/main.py
  odoo/addons/base/models/res_users.py
  odoo/fields.py
  odoo/models.py
Labels: tmp.15.0

#19419 [bt#22075] change to apply the right connection type
  addons/microsoft_outlook/models/ir_mail_server.py
Labels: 11.0.project_co_286

#19420 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_ma/__manifest__.py
  addons/mass_mailing_event/models/event.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/models/product.py
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: 14.0

#19421 Syncing from upstream odoo/odoo (15.0)
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_timesheet/views/project_portal_templates.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/models/product.py
  addons/project/controllers/portal.py
  addons/stock/models/stock_move.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: 15.0

#19422 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/mail/models/mail_channel.py
  addons/mail/static/src/models/message_list_view_item.js
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/project/report/project_report_views.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_slides/views/website_slides_templates_lesson.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/brcha.md
  doc/cla/individual/francescoballerini.md
Labels: 16.0

#19424 Syncing from upstream odoo/odoo (saas-15.2)
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/google_recaptcha/static/src/js/recaptcha.js
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/hr_timesheet/views/project_portal_templates.xml
  addons/mail/static/src/components/activity/tests/activity_tests.js
  addons/mail/static/src/models/time/time.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_requisition/views/purchase_requisition_views.xml
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/shapes/convert.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_blog/static/src/js/website_blog.js
  addons/website_event_booth/static/src/js/booth_register.js
  addons/website_event_exhibitor/static/src/js/event_exhibitor_connect.js
  addons/website_event_track/static/src/js/website_event_track_proposal_form.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_jitsi/static/src/js/chat_room.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  addons/website_sale_stock_wishlist/static/src/js/wishlist.js
  addons/website_slides/static/src/js/slides_course_join.js
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_twitter/static/src/js/website.twitter.animation.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: saas-15.2

#19431 Syncing from upstream odoo/odoo (staging.11.0)
  odoo/modules/migration.py
Labels: staging.11.0

#19432 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_ma/__manifest__.py
  addons/mass_mailing_event/models/event.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/models/product.py
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: staging.14.0

#19436 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/google_recaptcha/static/src/js/recaptcha.js
  addons/hr_holidays/static/tests/tours/time_off_request_calendar_view.js
  addons/hr_timesheet/views/project_portal_templates.xml
  addons/mail/static/src/components/activity/tests/activity_tests.js
  addons/mail/static/src/models/time/time.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_requisition/views/purchase_requisition_views.xml
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/shapes/convert.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/backend/dashboard.js
  addons/website/static/src/js/content/website_root.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.wysiwyg.scss
  addons/website/static/src/snippets/s_social_media/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_blog/static/src/js/website_blog.js
  addons/website_event_booth/static/src/js/booth_register.js
  addons/website_event_exhibitor/static/src/js/event_exhibitor_connect.js
  addons/website_event_track/static/src/js/website_event_track_proposal_form.js
  addons/website_forum/static/src/js/website_forum.js
  addons/website_jitsi/static/src/js/chat_room.js
  addons/website_sale_comparison/static/src/js/website_sale_comparison.js
  addons/website_sale_stock_wishlist/static/src/js/wishlist.js
  addons/website_slides/static/src/js/slides_course_join.js
  addons/website_slides/static/src/js/slides_slide_like.js
  addons/website_twitter/static/src/js/website.twitter.animation.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: tmp.saas-15.2

#19439 Syncing from upstream odoo/odoo (tmp.11.0)
  odoo/modules/migration.py
Labels: tmp.11.0

#19440 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_ma/__manifest__.py
  addons/mass_mailing_event/models/event.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/models/product.py
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: tmp.14.0

#19441 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/calendar/i18n/calendar.pot
  addons/calendar/models/calendar_event.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_timesheet/views/project_portal_templates.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/product/models/product.py
  addons/project/controllers/portal.py
  addons/stock/models/stock_move.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/scss/website.wysiwyg.scss
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
Labels: tmp.15.0

#19443 Syncing from upstream odoo/odoo (11.0)
  odoo/modules/migration.py
Labels: 11.0

#19444 Syncing from upstream odoo/odoo (14.0)
  doc/cla/corporate/vauxoo.md
Labels: 14.0

#19445 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/models/hr_leave_type.py
  addons/mrp/models/mrp_workorder.py
  doc/cla/corporate/vauxoo.md
Labels: 15.0

#19446 Syncing from upstream odoo/odoo (16.0)
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  doc/cla/corporate/vauxoo.md
Labels: 16.0

#19447 Syncing from upstream odoo/odoo (master)
  addons/event/models/event_event.py
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/models/fleet_vehicle_model.py
  addons/hr_contract/models/hr_contract.py
  addons/hr_contract/report/hr_contract_history_report_views.xml
  addons/hr_contract/views/hr_contract_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_pe/models/template_pe.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/res_company.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductsWidget.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductsWidgetControlPanel.js
  addons/point_of_sale/static/src/scss/pos.scss
  addons/point_of_sale/static/src/xml/Screens/PartnerListScreen/PartnerListScreen.xml
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/ProductsWidget.xml
  addons/point_of_sale/static/src/xml/Screens/ProductScreen/ProductsWidgetControlPanel.xml
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web/i18n/web.pot
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_event/models/event_event.py
  addons/website_event/static/src/snippets/s_searchbar/000.js
  addons/website_event/static/src/snippets/s_searchbar/000.xml
  addons/website_event/tests/test_website_event.py
  addons/website_event/views/snippets/snippets.xml
  doc/cla/corporate/vauxoo.md
  odoo/addons/test_lint/tests/_odoo_checker_sql_injection.py
  odoo/addons/test_lint/tests/test_checkers.py
Labels: master

#19448 Syncing from upstream odoo/odoo (saas-15.2)
  addons/mrp/models/mrp_workorder.py
  addons/website/static/src/scss/website.scss
  doc/cla/corporate/vauxoo.md
Labels: saas-15.2

#19449 Syncing from upstream odoo/odoo (saas-16.1)
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  doc/cla/corporate/vauxoo.md
Labels: saas-16.1

#19450 Syncing from upstream odoo/odoo (saas-16.2)
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
Labels: saas-16.2

#19453 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/wizard/account_payment_register.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/report/project_report_views.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  doc/cla/corporate/vauxoo.md
Labels: staging.saas-16.1

#19456 Syncing from upstream odoo/odoo (staging.14.0)
  doc/cla/corporate/vauxoo.md
Labels: staging.14.0

#19460 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/mrp/models/mrp_workorder.py
  addons/website/static/src/scss/website.scss
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-15.2

#19461 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/wizard/account_payment_register.py
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/report/project_report_views.xml
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-16.1

#19462 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/fleet/views/fleet_vehicle_cost_views.xml
  addons/fleet/views/fleet_vehicle_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/mrp_account/models/mrp_workorder.py
  addons/mrp_account/tests/test_analytic_account.py
  addons/project/report/project_report_views.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-16.2

#19464 Syncing from upstream odoo/odoo (tmp.14.0)
  doc/cla/corporate/vauxoo.md
Labels: tmp.14.0

#19465 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_holidays/models/hr_leave_type.py
  addons/mrp/models/mrp_workorder.py
  doc/cla/corporate/vauxoo.md
Labels: tmp.15.0

#19467 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/stock_landed_costs/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
Labels: 14.0

#19468 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/l10n_it/data/account.account.template.csv
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_event/models/event_event.py
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
Labels: 15.0

#19469 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_it/data/account.account.template.csv
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/project/controllers/portal.py
  addons/repair/i18n/repair.pot
  addons/repair/models/repair.py
  addons/repair/views/repair_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/__manifest__.py
  addons/website/static/src/scss/website.scss
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_event/views/event_templates_list.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  odoo/addons/base/views/res_users_views.xml
Labels: 16.0

#19471 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_it/data/account.account.template.csv
  addons/mass_mailing_event/models/event_event.py
  addons/stock/models/stock_move.py
Labels: saas-15.2

#19472 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/wizard/account_payment_register.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/calendar/static/src/views/attendee_calendar/year/attendee_calendar_year_renderer.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/project/report/project_report_views.xml
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/website/__manifest__.py
  addons/website/static/src/scss/website.scss
  odoo/addons/base/views/res_users_views.xml
Labels: saas-16.1

#19473 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/chart_template.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/calendar/static/src/views/attendee_calendar/year/attendee_calendar_year_renderer.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_be/data/account_tax_report_data.xml
  addons/l10n_be/i18n/de.po
  addons/l10n_be/i18n/fr.po
  addons/l10n_be/i18n/fr_BE.po
  addons/l10n_be/i18n/l10n_be.pot
  addons/l10n_be/i18n/nl.po
  addons/l10n_bg/i18n/bg.po
  addons/l10n_bg/i18n/l10n_bg.pot
  addons/l10n_ch/i18n/fr_BE.po
  addons/l10n_eg/i18n_extra/ar_001.po
  addons/l10n_eg/i18n_extra/l10n_eg.pot
  addons/l10n_hu/i18n/hu.po
  addons/l10n_hu/i18n/l10n_hu.pot
  addons/l10n_il/i18n/he_IL.po
  addons/l10n_il/i18n/l10n_il.pot
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/l10n_ro/i18n/l10n_ro.pot
  addons/l10n_ro/i18n/ro.po
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_si/i18n/l10n_si.pot
  addons/l10n_si/i18n/sl.po
  addons/l10n_vn/i18n_extra/l10n_vn.pot
  addons/l10n_vn/i18n_extra/vi_VN.po
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/project/report/project_report_views.xml
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/website/__manifest__.py
  addons/website/static/src/components/fields/publish_button.xml
  addons/website/static/src/scss/website.scss
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/francescoballerini.md
  odoo/addons/base/views/res_users_views.xml
Labels: saas-16.2

#19476 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_journal.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/calendar/static/src/views/attendee_calendar/year/attendee_calendar_year_renderer.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/website/__manifest__.py
  addons/website/static/src/scss/website.scss
  odoo/addons/base/views/res_users_views.xml
Labels: staging.saas-16.1

#19478 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/stock_landed_costs/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
Labels: staging.14.0

#19482 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_it/data/account.account.template.csv
  addons/mass_mailing_event/models/event_event.py
  addons/stock/models/stock_move.py
Labels: tmp.saas-15.2

#19483 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_journal.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/calendar/static/src/views/attendee_calendar/year/attendee_calendar_year_renderer.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/website/__manifest__.py
  addons/website/static/src/scss/website.scss
  odoo/addons/base/views/res_users_views.xml
Labels: tmp.saas-16.1

#19484 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/chart_template.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/calendar/static/src/views/attendee_calendar/year/attendee_calendar_year_renderer.js
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_be/data/account_tax_report_data.xml
  addons/l10n_be/i18n/de.po
  addons/l10n_be/i18n/fr.po
  addons/l10n_be/i18n/fr_BE.po
  addons/l10n_be/i18n/l10n_be.pot
  addons/l10n_be/i18n/nl.po
  addons/l10n_bg/i18n/bg.po
  addons/l10n_bg/i18n/l10n_bg.pot
  addons/l10n_ch/i18n/fr_BE.po
  addons/l10n_eg/i18n_extra/ar_001.po
  addons/l10n_eg/i18n_extra/l10n_eg.pot
  addons/l10n_hu/i18n/hu.po
  addons/l10n_hu/i18n/l10n_hu.pot
  addons/l10n_il/i18n/he_IL.po
  addons/l10n_il/i18n/l10n_il.pot
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/l10n_ro/i18n/l10n_ro.pot
  addons/l10n_ro/i18n/ro.po
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_si/i18n/l10n_si.pot
  addons/l10n_si/i18n/sl.po
  addons/l10n_vn/i18n_extra/l10n_vn.pot
  addons/l10n_vn/i18n_extra/vi_VN.po
  addons/point_of_sale/report/pos_order_report.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_pos_order.py
  addons/purchase/models/purchase.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_move.py
  addons/web/static/src/core/datepicker/datepicker.js
  addons/web/static/tests/core/datepicker_tests.js
  addons/website/__manifest__.py
  addons/website/static/src/components/fields/publish_button.xml
  addons/website/static/src/scss/website.scss
  doc/cla/individual/francescoballerini.md
  odoo/addons/base/views/res_users_views.xml
Labels: tmp.saas-16.2

#19485 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/stock_landed_costs/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/menu/edit.js
Labels: tmp.14.0

#19486 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/l10n_it/data/account.account.template.csv
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing_event/models/event_event.py
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
Labels: tmp.15.0

#19488 Syncing from upstream odoo/odoo (12.0)
  odoo/modules/migration.py
Labels: 12.0

#19489 Syncing from upstream odoo/odoo (13.0)
  odoo/modules/migration.py
Labels: 13.0

#19490 Syncing from upstream odoo/odoo (14.0)
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/controllers/main.py
  odoo/modules/migration.py
Labels: 14.0

#19491 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  odoo/modules/migration.py
Labels: 15.0

#19492 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_journal.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/bosaeed.md
  odoo/addons/base/models/res_currency.py
  odoo/modules/migration.py
  odoo/sql_db.py
Labels: 16.0

#19494 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  odoo/modules/migration.py
Labels: saas-15.2

#19495 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_journal.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/components/chatter/chatter.scss
  addons/mail/static/src/components/chatter/chatter.xml
  addons/mail/static/src/components/chatter_container/chatter_container.scss
  addons/mail/static/src/components/chatter_container/chatter_container.xml
  addons/mail/static/src/widgets/form_renderer/form_renderer.scss
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/static/src/xml/mailing_filter_widget.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/project/controllers/portal.py
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website_event/views/event_templates_list.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/res_currency.py
  odoo/modules/migration.py
Labels: saas-16.1

#19496 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/chart_template.py
  addons/account/models/ir_module.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_journal.py
  addons/l10n_be/demo/account_demo.py
  addons/l10n_de/models/chart_template.py
  addons/l10n_de_skr03/data/template/account.account-de_skr03.csv
  addons/l10n_de_skr04/data/template/account.account-de_skr04.csv
  addons/l10n_it/data/template/account.account-it.csv
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/components/chatter/chatter.scss
  addons/mail/static/src/components/chatter/chatter.xml
  addons/mail/static/src/components/chatter_container/chatter_container.scss
  addons/mail/static/src/components/chatter_container/chatter_container.xml
  addons/mail/static/src/views/form/form_renderer.scss
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/static/src/xml/mailing_filter_widget.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/project/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/web/static/tests/search/control_panel.js
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website_event/views/event_templates_list.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  odoo/addons/base/models/res_currency.py
  odoo/modules/migration.py
Labels: saas-16.2

#19498 Syncing from upstream odoo/odoo (staging.saas-12.3)
  odoo/modules/migration.py
Labels: staging.saas-12.3

#19500 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_journal.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/components/chatter/chatter.scss
  addons/mail/static/src/components/chatter/chatter.xml
  addons/mail/static/src/components/chatter_container/chatter_container.scss
  addons/mail/static/src/components/chatter_container/chatter_container.xml
  addons/mail/static/src/widgets/form_renderer/form_renderer.scss
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/static/src/xml/mailing_filter_widget.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/project/controllers/portal.py
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website_event/views/event_templates_list.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/res_currency.py
  odoo/modules/migration.py
Labels: staging.saas-16.1

#19502 Syncing from upstream odoo/odoo (staging.12.0)
  odoo/modules/migration.py
Labels: staging.12.0

#19503 Syncing from upstream odoo/odoo (staging.13.0)
  odoo/modules/migration.py
Labels: staging.13.0

#19504 Syncing from upstream odoo/odoo (staging.14.0)
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/controllers/main.py
  odoo/modules/migration.py
Labels: staging.14.0

#19508 Syncing from upstream odoo/odoo (tmp.saas-12.3)
  odoo/modules/migration.py
Labels: tmp.saas-12.3

#19509 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  odoo/modules/migration.py
Labels: tmp.saas-15.2

#19510 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_journal.py
  addons/l10n_it/data/account.account.template.csv
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/components/chatter/chatter.scss
  addons/mail/static/src/components/chatter/chatter.xml
  addons/mail/static/src/components/chatter_container/chatter_container.scss
  addons/mail/static/src/components/chatter_container/chatter_container.xml
  addons/mail/static/src/widgets/form_renderer/form_renderer.scss
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/static/src/xml/mailing_filter_widget.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/project/controllers/portal.py
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website_event/views/event_templates_list.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/res_currency.py
  odoo/modules/migration.py
Labels: tmp.saas-16.1

#19511 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/chart_template.py
  addons/account/models/ir_module.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_check_printing/models/account_journal.py
  addons/l10n_be/demo/account_demo.py
  addons/l10n_de/models/chart_template.py
  addons/l10n_de_skr03/data/template/account.account-de_skr03.csv
  addons/l10n_de_skr04/data/template/account.account-de_skr04.csv
  addons/l10n_it/data/template/account.account-it.csv
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/components/chatter/chatter.scss
  addons/mail/static/src/components/chatter/chatter.xml
  addons/mail/static/src/components/chatter_container/chatter_container.scss
  addons/mail/static/src/components/chatter_container/chatter_container.xml
  addons/mail/static/src/views/form/form_renderer.scss
  addons/mass_mailing/static/src/scss/mass_mailing.scss
  addons/mass_mailing/static/src/xml/mailing_filter_widget.xml
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/pos_mercury/static/src/js/PaymentScreen.js
  addons/project/controllers/portal.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/web/static/tests/search/control_panel.js
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website_event/views/event_templates_list.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  odoo/addons/base/models/res_currency.py
  odoo/modules/migration.py
Labels: tmp.saas-16.2

#19512 Syncing from upstream odoo/odoo (tmp.12.0)
  odoo/modules/migration.py
Labels: tmp.12.0

#19513 Syncing from upstream odoo/odoo (tmp.13.0)
  odoo/modules/migration.py
Labels: tmp.13.0

#19514 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/controllers/main.py
  odoo/modules/migration.py
Labels: tmp.14.0

#19515 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/purchase/models/account_invoice.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  odoo/modules/migration.py
Labels: tmp.15.0

#19517 Syncing from upstream odoo/odoo (14.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/custom_filter_item_tests.js
  addons/website_profile/__init__.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/tests/test_db_cursor.py
  odoo/models.py
  odoo/tests/common.py
Labels: 14.0

#19518 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_recurrence.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/tests/test_db_cursor.py
  odoo/tests/common.py
Labels: 15.0

#19521 Syncing from upstream odoo/odoo (saas-12.3)
  odoo/modules/migration.py
Labels: saas-12.3

#19522 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  doc/cla/corporate/vauxoo.md
  odoo/models.py
Labels: saas-15.2

#19523 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/static/src/components/open_move_line_move_widget/open_move_line_move_widget.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/bus/tests/test_websocket_caryall.py
  addons/hr_work_entry/i18n/hr_work_entry.pot
  addons/hr_work_entry/models/hr_work_entry.py
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/views/mrp_production_views.xml
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/data/data.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/bosaeed.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: saas-16.1

#19524 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/static/src/components/open_move_line_move_widget/open_move_line_move_widget.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/bus/tests/test_websocket_caryall.py
  addons/l10n_ec/data/l10n_latam_identification_type_data.xml
  addons/l10n_ec/data/template/account.tax-ec.csv
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/static/src/components/mo_overview/mrp_mo_overview.js
  addons/mrp/static/src/components/mo_overview/mrp_mo_overview.xml
  addons/mrp/static/src/components/mo_overview_display_filter/mrp_mo_overview_display_filter.js
  addons/mrp/static/src/components/mo_overview_line/mo_overview_colors.js
  addons/mrp/static/src/components/mo_overview_line/mrp_mo_overview_line.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_mrp/report/mrp_report_mo_overview.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/data/data.xml
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/bosaeed.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: saas-16.2

#19528 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/static/src/components/open_move_line_move_widget/open_move_line_move_widget.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/bus/tests/test_websocket_caryall.py
  addons/hr_work_entry/i18n/hr_work_entry.pot
  addons/hr_work_entry/models/hr_work_entry.py
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/views/mrp_production_views.xml
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/data/data.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/bosaeed.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: staging.saas-16.1

#19530 Syncing from upstream odoo/odoo (staging.14.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/custom_filter_item_tests.js
  addons/website_profile/__init__.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/tests/test_db_cursor.py
  odoo/models.py
  odoo/tests/common.py
Labels: staging.14.0

#19535 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  doc/cla/corporate/vauxoo.md
  odoo/models.py
Labels: tmp.saas-15.2

#19536 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/static/src/components/open_move_line_move_widget/open_move_line_move_widget.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/bus/tests/test_websocket_caryall.py
  addons/hr_work_entry/i18n/hr_work_entry.pot
  addons/hr_work_entry/models/hr_work_entry.py
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/hr_work_entry_contract/wizard/hr_work_entry_regeneration_wizard_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/views/mrp_production_views.xml
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/data/data.xml
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/bosaeed.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: tmp.saas-16.1

#19537 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/static/src/components/open_move_line_move_widget/open_move_line_move_widget.js
  addons/account/static/src/components/open_move_widget/open_move_widget.js
  addons/bus/tests/test_websocket_caryall.py
  addons/l10n_ec/data/l10n_latam_identification_type_data.xml
  addons/l10n_ec/data/template/account.tax-ec.csv
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/static/src/components/mo_overview/mrp_mo_overview.js
  addons/mrp/static/src/components/mo_overview/mrp_mo_overview.xml
  addons/mrp/static/src/components/mo_overview_display_filter/mrp_mo_overview_display_filter.js
  addons/mrp/static/src/components/mo_overview_line/mo_overview_colors.js
  addons/mrp/static/src/components/mo_overview_line/mrp_mo_overview_line.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_mrp/report/mrp_report_mo_overview.py
  addons/spreadsheet_dashboard_account/data/files/invoicing_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/webclient/actions/url_action_tests.js
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_sale/data/data.xml
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/vauxoo.md
  doc/cla/individual/bosaeed.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: tmp.saas-16.2

#19538 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/web/static/src/xml/base.xml
  addons/web/static/tests/control_panel/custom_filter_item_tests.js
  addons/website_profile/__init__.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/tests/test_db_cursor.py
  odoo/models.py
  odoo/tests/common.py
Labels: tmp.14.0

#19539 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_recurrence.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/menu/edit.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/tests/test_db_cursor.py
  odoo/tests/common.py
Labels: tmp.15.0

#19545 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
Labels: saas-15.2

#19546 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  odoo/models.py
Labels: saas-16.1

#19547 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  odoo/models.py
Labels: saas-16.2

#19550 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  odoo/models.py
Labels: staging.saas-16.1

#19556 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
Labels: tmp.saas-15.2

#19557 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  odoo/models.py
Labels: tmp.saas-16.1

#19558 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/a_nz_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  odoo/models.py
Labels: tmp.saas-16.2

#19559 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/nlcius_out_refund.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/ubl_test_import_partner.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_invoice.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/xrechnung_ubl_out_refund.xml
  odoo/models.py
Labels: tmp.15.0

#19561 Syncing from upstream odoo/odoo (master)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
  addons/barcodes/static/src/barcode_handlers.js
  addons/web/controllers/home.py
  addons/web/tests/__init__.py
  addons/web/tests/test_web_redirect.py
  doc/cla/corporate/rapsodoo.md
Labels: master

#19579 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
Labels: saas-16.2

#19587 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/ir_actions_report.py
  addons/account/tests/__init__.py
  addons/account/tests/test_ir_actions_report.py
Labels: tmp.saas-16.2

#19588 Syncing from upstream odoo/odoo (14.0)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/gamification/models/res_users.py
  addons/hr_org_chart/tests/test_employee_deletion.py
  addons/mail/views/ir_model_views.xml
  addons/sms/tests/test_sms_template.py
  addons/stock/views/stock_picking_views.xml
  addons/survey/tests/test_survey_security.py
  addons/web_unsplash/controllers/main.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/tests/common.py
Labels: 14.0

#19589 Syncing from upstream odoo/odoo (15.0)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/mail/views/ir_model_views.xml
  addons/mail/views/mail_activity_views.xml
  addons/resource/models/res_users.py
  addons/stock/views/stock_picking_views.xml
  addons/website/views/snippets/s_image_gallery.xml
  addons/website_profile/__init__.py
Labels: 15.0

#19591 Syncing from upstream odoo/odoo (saas-15.2)
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_recurrence.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/views/ir_model_views.xml
  addons/mail/views/mail_activity_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/stock/views/stock_picking_views.xml
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website_profile/__init__.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/tests/common.py
Labels: saas-15.2

#19592 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_account.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_recurrence.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/static/tests/qunit_suite_tests/components/activity_tests.js
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/controllers/main.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/project/views/project_views.xml
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/stock_picking_views.xml
  addons/stock/wizard/product_replenish.py
  addons/web/i18n/web.pot
  addons/web/static/src/views/fields/phone/phone_field.scss
  addons/web/static/src/webclient/user_menu/user_menu_items.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_forum/data/forum_default_faq.xml
  addons/website_forum/i18n/website_forum.pot
  addons/website_profile/__init__.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/test_http/tests/test_session.py
  odoo/http.py
  odoo/sql_db.py
  odoo/tools/_vendor/sessions.py
  odoo/tools/misc.py
Labels: saas-16.1

#19598 Syncing from upstream odoo/odoo (staging.14.0)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/gamification/models/res_users.py
  addons/hr_org_chart/tests/test_employee_deletion.py
  addons/mail/views/ir_model_views.xml
  addons/sms/tests/test_sms_template.py
  addons/stock/views/stock_picking_views.xml
  addons/survey/tests/test_survey_security.py
  addons/web_unsplash/controllers/main.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/tests/common.py
Labels: staging.14.0

#19602 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_recurrence.py
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/views/ir_model_views.xml
  addons/mail/views/mail_activity_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/stock/views/stock_picking_views.xml
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website_profile/__init__.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/tests/common.py
Labels: tmp.saas-15.2

#19603 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_account.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_event_recurrence.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/static/tests/qunit_suite_tests/components/activity_tests.js
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/controllers/main.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/project/views/project_views.xml
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_stock_flow.py
  addons/stock/views/stock_picking_views.xml
  addons/stock/wizard/product_replenish.py
  addons/web/i18n/web.pot
  addons/web/static/src/views/fields/phone/phone_field.scss
  addons/web/static/src/webclient/user_menu/user_menu_items.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_forum/data/forum_default_faq.xml
  addons/website_forum/i18n/website_forum.pot
  addons/website_profile/__init__.py
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/test_http/tests/test_session.py
  odoo/http.py
  odoo/sql_db.py
  odoo/tools/_vendor/sessions.py
  odoo/tools/misc.py
Labels: tmp.saas-16.1

#19605 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/gamification/models/res_users.py
  addons/hr_org_chart/tests/test_employee_deletion.py
  addons/mail/views/ir_model_views.xml
  addons/sms/tests/test_sms_template.py
  addons/stock/views/stock_picking_views.xml
  addons/survey/tests/test_survey_security.py
  addons/web_unsplash/controllers/main.py
  odoo/addons/base/tests/test_tests_tags.py
  odoo/tests/common.py
Labels: tmp.14.0

#19606 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/mail/views/ir_model_views.xml
  addons/mail/views/mail_activity_views.xml
  addons/resource/models/res_users.py
  addons/stock/views/stock_picking_views.xml
  addons/website/views/snippets/s_image_gallery.xml
  addons/website_profile/__init__.py
Labels: tmp.15.0

#19608 Syncing from upstream odoo/odoo (14.0)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/mail/models/mail_thread.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: 14.0

#19609 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mrp/tests/test_traceability.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_gift_card/static/src/js/GiftCardPopup.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/stock/models/stock_production_lot.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
Labels: 15.0

#19611 Syncing from upstream odoo/odoo (saas-15.2)
  addons/mail/models/mail_thread.py
  addons/mrp/views/mrp_production_views.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/website/views/snippets/s_image_gallery.xml
Labels: saas-15.2

#19612 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/models/account_move.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/scss/im_livechat_bootstrap.scss
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail/models/res_partner.py
  addons/mail/views/ir_model_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/project/views/project_views.xml
  addons/project_sms/models/project.py
  addons/project_sms/models/project_task.py
  addons/project_sms/tests/test_project_sharing.py
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_sale/views/templates.xml
Labels: saas-16.1

#19613 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/models/account_move.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/scss/im_livechat_bootstrap.scss
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/export_xmls/credit_note_reverse_charge.xml
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail/models/res_partner.py
  addons/mail/views/ir_model_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/test_mail_full/tests/test_rating.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_sale/views/templates.xml
  addons/website_slides_survey/__init__.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/tests/common.py
Labels: saas-16.2

#19616 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/models/account_move.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/scss/im_livechat_bootstrap.scss
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail/models/res_partner.py
  addons/mail/views/ir_model_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/project/views/project_views.xml
  addons/project_sms/models/project.py
  addons/project_sms/models/project_task.py
  addons/project_sms/tests/test_project_sharing.py
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_sale/views/templates.xml
Labels: staging.saas-16.1

#19618 Syncing from upstream odoo/odoo (staging.14.0)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/mail/models/mail_thread.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: staging.14.0

#19622 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/mail/models/mail_thread.py
  addons/mrp/views/mrp_production_views.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
  addons/website/views/snippets/s_image_gallery.xml
Labels: tmp.saas-15.2

#19623 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/models/account_move.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/scss/im_livechat_bootstrap.scss
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail/models/res_partner.py
  addons/mail/views/ir_model_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/project/views/project_views.xml
  addons/project_sms/models/project.py
  addons/project_sms/models/project_task.py
  addons/project_sms/tests/test_project_sharing.py
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_sale/views/templates.xml
Labels: tmp.saas-16.1

#19624 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/views/account_payment_view.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/delivery/models/sale_order.py
  addons/delivery/tests/test_delivery_cost.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/models/account_move.py
  addons/im_livechat/static/src/legacy/public_livechat_chatbot.xml
  addons/im_livechat/static/src/scss/im_livechat_bootstrap.scss
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/export_xmls/credit_note_reverse_charge.xml
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail/models/res_partner.py
  addons/mail/views/ir_model_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/test_mail_full/tests/test_rating.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/widgets/link_popover_widget.js
  addons/website_sale/views/templates.xml
  addons/website_slides_survey/__init__.py
  odoo/addons/base/tests/test_db_cursor.py
  odoo/tests/common.py
Labels: tmp.saas-16.2

#19625 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/mail/models/mail_thread.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
Labels: tmp.14.0

#19626 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_fr_pos_cert/static/src/xml/OrderReceipt.xml
  addons/l10n_fr_pos_cert/static/src/xml/Orderline.xml
  addons/l10n_id_efaktur/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mrp/tests/test_traceability.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/pos_gift_card/static/src/js/GiftCardPopup.js
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/stock/models/stock_production_lot.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/lib/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/lib/odoo-editor/test/spec/list.test.js
Labels: tmp.15.0

#19628 Syncing from upstream odoo/odoo (14.0)
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web/static/src/fonts/tiktok_only.woff
  addons/web/static/src/scss/fontawesome_overridden.scss
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: 14.0

#19629 Syncing from upstream odoo/odoo (15.0)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase_stock/models/purchase.py
  addons/stock/models/stock_location.py
  addons/stock/report/report_stock_forecasted.py
  addons/stock/tests/test_packing.py
  addons/web/static/fonts/tiktok_only.woff
  addons/web/static/src/legacy/scss/fontawesome_overridden.scss
  addons/web/static/src/legacy/scss/report.scss
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/website/static/src/snippets/s_website_form/000.js
Labels: 15.0

#19631 Syncing from upstream odoo/odoo (saas-15.2)
  addons/mrp/tests/test_traceability.py
  addons/purchase_stock/models/purchase.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/legacy/scss/report.scss
Labels: saas-15.2

#19633 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_attendance/static/src/client_action/my_attendances/my_attendances.js
  addons/hr_attendance/static/tests/client_action_tests.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/iap/models/iap_account.py
  addons/mail/data/mail_templates_email_layouts.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/tests/test_traceability.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/project_sms/models/project.py
  addons/project_sms/models/project_task.py
  addons/project_sms/tests/test_project_sharing.py
  addons/purchase_stock/models/purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock/models/stock_lot.py
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/views/graph/graph_view.scss
  addons/web/static/src/views/pivot/pivot_view.scss
  addons/web/static/src/webclient/actions/reports/report.scss
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/views/snippets.xml
  addons/website/i18n/website.pot
  addons/website/views/snippets/s_image_gallery.xml
  addons/website/views/snippets/snippets.xml
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/views/snippets/snippets.xml
  addons/website_event/i18n/website_event.pot
  addons/website_event/views/event_snippets.xml
  addons/website_event/views/snippets/snippets.xml
  addons/website_mail_group/i18n/website_mail_group.pot
  addons/website_mail_group/views/snippets/snippets.xml
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/static/tests/tours/newsletter_block.js
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_payment/i18n/website_payment.pot
  addons/website_payment/views/snippets/snippets.xml
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/snippets/snippets.xml
  addons/website_twitter/i18n/website_twitter.pot
  addons/website_twitter/views/website_twitter_snippet_templates.xml
  doc/cla/corporate/trescloud.md
  doc/cla/corporate/twio_tech.md
Labels: saas-16.2

#19638 Syncing from upstream odoo/odoo (staging.14.0)
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web/static/src/fonts/tiktok_only.woff
  addons/web/static/src/scss/fontawesome_overridden.scss
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: staging.14.0

#19642 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/mrp/tests/test_traceability.py
  addons/purchase_stock/models/purchase.py
  addons/stock/models/stock_lot.py
  addons/web/static/src/legacy/scss/report.scss
Labels: tmp.saas-15.2

#19644 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_attendance/static/src/client_action/my_attendances/my_attendances.js
  addons/hr_attendance/static/tests/client_action_tests.js
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/iap/models/iap_account.py
  addons/mail/data/mail_templates_email_layouts.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/views/snippets_themes.xml
  addons/mrp/tests/test_traceability.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/project_sms/models/project.py
  addons/project_sms/models/project_task.py
  addons/project_sms/tests/test_project_sharing.py
  addons/purchase_stock/models/purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock/models/stock_lot.py
  addons/test_mail/tests/test_performance.py
  addons/test_mass_mailing/tests/test_mailing.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/views/graph/graph_view.scss
  addons/web/static/src/views/pivot/pivot_view.scss
  addons/web/static/src/webclient/actions/reports/report.scss
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/xml/editor.xml
  addons/web_editor/views/snippets.xml
  addons/website/i18n/website.pot
  addons/website/views/snippets/s_image_gallery.xml
  addons/website/views/snippets/snippets.xml
  addons/website_blog/i18n/website_blog.pot
  addons/website_blog/views/snippets/snippets.xml
  addons/website_event/i18n/website_event.pot
  addons/website_event/views/event_snippets.xml
  addons/website_event/views/snippets/snippets.xml
  addons/website_mail_group/i18n/website_mail_group.pot
  addons/website_mail_group/views/snippets/snippets.xml
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_mass_mailing/static/tests/tours/newsletter_block.js
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_payment/i18n/website_payment.pot
  addons/website_payment/views/snippets/snippets.xml
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/snippets/snippets.xml
  addons/website_twitter/i18n/website_twitter.pot
  addons/website_twitter/views/website_twitter_snippet_templates.xml
  doc/cla/corporate/trescloud.md
  doc/cla/corporate/twio_tech.md
Labels: tmp.saas-16.2

#19645 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/web/static/src/fonts/tiktok_only.woff
  addons/web/static/src/scss/fontawesome_overridden.scss
  addons/web_editor/static/src/js/editor/rte.summernote.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: tmp.14.0

#19646 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/pos_discount/static/src/js/DiscountButton.js
  addons/purchase_stock/models/purchase.py
  addons/stock/models/stock_location.py
  addons/stock/report/report_stock_forecasted.py
  addons/stock/tests/test_packing.py
  addons/web/static/fonts/tiktok_only.woff
  addons/web/static/src/legacy/scss/fontawesome_overridden.scss
  addons/web/static/src/legacy/scss/report.scss
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/website/static/src/snippets/s_website_form/000.js
Labels: tmp.15.0

#18913 [bt#20751] added thread and cursors for more than 5 inv to be confirmed
  addons/account/__openerp__.py
  addons/account/data/cronjob.xml
  addons/account/models/account_invoice.py
  addons/account/wizard/account_invoice_state.py
Labels: 9.0.project_mu_214
