Repository brain-tec/odoo, pull requests merged in 2024-11, with the labels that each got.

#29995 Syncing from upstream odoo/odoo (16.0)
  addons/mail/static/src/components/attachment_viewer/attachment_viewer.xml
  addons/mrp/models/stock_warehouse.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/lib/owl/owl.js
  addons/website_sale_loyalty/views/website_sale_templates.xml
Labels: 16.0

#29996 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_audit_trail/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/models/base_import.py
  addons/event_sale/models/event_ticket.py
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.js
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/static/src/widgets/stock_pick_from.js
  addons/stock/tests/test_stock_lot.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/file_viewer/file_viewer.xml
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website_sale_product_configurator/i18n/website_sale_product_configurator.pot
  addons/website_sale_product_configurator/views/templates.xml
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
Labels: 17.0

#29999 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_fr/i18n/fr.po
  addons/l10n_fr/i18n/l10n_fr.pot
  addons/l10n_fr_account/i18n/fr.po
  addons/l10n_fr_account/i18n/l10n_fr_account.pot
  addons/l10n_fr_facturx_chorus_pro/i18n/fr.po
  addons/l10n_fr_facturx_chorus_pro/i18n/l10n_fr_facturx_chorus_pro.pot
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/mail/static/src/core/common/chat_window.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/tours/discuss_go_back_to_thread_from_breadcrumbs_tour.js
  addons/mail/tests/discuss/__init__.py
  addons/mail/tests/discuss/test_discuss_action.py
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/models/sale_order.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_process_steps/001.scss
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
Labels: staging.saas-17.4

#30001 Syncing from upstream odoo/odoo (staging.16.0)
  addons/mail/static/src/components/attachment_viewer/attachment_viewer.xml
  addons/mrp/models/stock_warehouse.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/lib/owl/owl.js
  addons/website_sale_loyalty/views/website_sale_templates.xml
Labels: staging.16.0

#30002 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_audit_trail/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/models/base_import.py
  addons/event_sale/models/event_ticket.py
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.js
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/static/src/widgets/stock_pick_from.js
  addons/stock/tests/test_stock_lot.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/file_viewer/file_viewer.xml
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website_sale_product_configurator/i18n/website_sale_product_configurator.pot
  addons/website_sale_product_configurator/views/templates.xml
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
Labels: staging.17.0

#30004 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/ir_module.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_fr/i18n/fr.po
  addons/l10n_fr/i18n/l10n_fr.pot
  addons/l10n_fr_account/i18n/fr.po
  addons/l10n_fr_account/i18n/l10n_fr_account.pot
  addons/l10n_fr_account/models/__init__.py
  addons/l10n_fr_account/models/template_mc.py
  addons/l10n_fr_facturx_chorus_pro/i18n/fr.po
  addons/l10n_fr_facturx_chorus_pro/i18n/l10n_fr_facturx_chorus_pro.pot
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/l10n_fr_invoice_addr/i18n/l10n_fr_invoice_addr.pot
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_mc/__init__.py
  addons/l10n_mc/__manifest__.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/sms/tests/test_sms_composer.py
  addons/sms/tools/sms_tools.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/user.js
  addons/website_sale_product_configurator/i18n/website_sale_product_configurator.pot
  addons/website_sale_product_configurator/views/templates.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/mail.py
Labels: tmp.saas-17.2

#30005 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_ar/models/account_journal.py
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_fr/i18n/fr.po
  addons/l10n_fr/i18n/l10n_fr.pot
  addons/l10n_fr_account/i18n/fr.po
  addons/l10n_fr_account/i18n/l10n_fr_account.pot
  addons/l10n_fr_facturx_chorus_pro/i18n/fr.po
  addons/l10n_fr_facturx_chorus_pro/i18n/l10n_fr_facturx_chorus_pro.pot
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/mail/static/src/core/common/chat_window.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/tours/discuss_go_back_to_thread_from_breadcrumbs_tour.js
  addons/mail/tests/discuss/__init__.py
  addons/mail/tests/discuss/test_discuss_action.py
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/models/sale_order.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_process_steps/001.scss
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
Labels: tmp.saas-17.4

#30006 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/mail/static/src/components/attachment_viewer/attachment_viewer.xml
  addons/mrp/models/stock_warehouse.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/lib/owl/owl.js
  addons/website_sale_loyalty/views/website_sale_templates.xml
Labels: tmp.16.0

#30007 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_audit_trail/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/models/base_import.py
  addons/event_sale/models/event_ticket.py
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.js
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/static/src/widgets/stock_pick_from.js
  addons/stock/tests/test_stock_lot.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/file_viewer/file_viewer.xml
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website_sale_product_configurator/i18n/website_sale_product_configurator.pot
  addons/website_sale_product_configurator/views/templates.xml
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
Labels: tmp.17.0

#30009 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
Labels: 15.0

#30010 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
Labels: 16.0

#30011 Syncing from upstream odoo/odoo (18.0)
  addons/base_import/models/base_import.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/mail/static/src/chatter/web/chatter.xml
  addons/payment_worldline/models/payment_transaction.py
  addons/payment_worldline/tests/common.py
  addons/payment_worldline/tests/test_worldline.py
  addons/stock/static/src/widgets/stock_pick_from.js
Labels: 18.0

#30012 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_payment.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/mail/static/src/chatter/web/chatter.xml
  addons/mrp_account/models/product.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/stock/static/src/widgets/stock_pick_from.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
Labels: master

#30016 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/chart_template.py
  addons/account/models/ir_module.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_import/models/base_import.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_pay_term_ecotax.xml
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ar/models/account_move.py
  addons/l10n_ar/models/account_tax_group.py
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_fr/i18n/fr.po
  addons/l10n_fr/i18n/l10n_fr.pot
  addons/l10n_fr_account/i18n/fr.po
  addons/l10n_fr_account/i18n/l10n_fr_account.pot
  addons/l10n_fr_account/models/__init__.py
  addons/l10n_fr_account/models/template_mc.py
  addons/l10n_fr_facturx_chorus_pro/i18n/fr.po
  addons/l10n_fr_facturx_chorus_pro/i18n/l10n_fr_facturx_chorus_pro.pot
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/l10n_fr_invoice_addr/i18n/l10n_fr_invoice_addr.pot
  addons/l10n_fr_pos_cert/i18n/fr.po
  addons/l10n_fr_pos_cert/i18n/l10n_fr_pos_cert.pot
  addons/l10n_mc/__init__.py
  addons/l10n_mc/__manifest__.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/sms/tests/test_sms_composer.py
  addons/sms/tools/sms_tools.py
  addons/stock/static/src/widgets/stock_pick_from.js
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_website/tests/test_page_manager.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/user.js
  addons/website_sale_product_configurator/i18n/website_sale_product_configurator.pot
  addons/website_sale_product_configurator/views/templates.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/mail.py
Labels: staging.saas-17.2

#30017 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/base_import/models/base_import.py
  addons/sale_project/models/sale_order_line.py
  addons/stock/static/src/widgets/stock_pick_from.js
Labels: staging.saas-17.4

#30019 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
Labels: staging.16.0

#30020 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_payment.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/mail/static/src/chatter/web/chatter.xml
  addons/mrp_account/models/product.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/stock/static/src/widgets/stock_pick_from.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_res_users.py
Labels: tmp.master

#30021 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/chart_template.py
  addons/base_import/models/base_import.py
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_move.py
  addons/l10n_ar/models/account_tax_group.py
  addons/stock/static/src/widgets/stock_pick_from.js
Labels: tmp.saas-17.2

#30022 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/base_import/models/base_import.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/sale_project/models/sale_order_line.py
  addons/stock/static/src/widgets/stock_pick_from.js
Labels: tmp.saas-17.4

#30023 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/l10n_sa_invoice/views/report_invoice.xml
Labels: tmp.15.0

#30024 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
Labels: tmp.16.0

#30025 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/base_import/models/base_import.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_config_settings_view.xml
  addons/payment_worldline/models/payment_transaction.py
  addons/payment_worldline/tests/common.py
  addons/payment_worldline/tests/test_worldline.py
  addons/stock/static/src/widgets/stock_pick_from.js
Labels: tmp.18.0

#30026 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/ar.po
  addons/account/i18n/az.po
  addons/account/i18n/bg.po
  addons/account/i18n/ca.po
  addons/account/i18n/cs.po
  addons/account/i18n/da.po
  addons/account/i18n/de.po
  addons/account/i18n/el.po
  addons/account/i18n/es.po
  addons/account/i18n/es_419.po
  addons/account/i18n/et.po
  addons/account/i18n/fa.po
  addons/account/i18n/fi.po
  addons/account/i18n/fr.po
  addons/account/i18n/he.po
  addons/account/i18n/hr.po
  addons/account/i18n/hu.po
  addons/account/i18n/hy.po
  addons/account/i18n/id.po
  addons/account/i18n/is.po
  addons/account/i18n/it.po
  addons/account/i18n/ja.po
  addons/account/i18n/ko.po
  addons/account/i18n/lt.po
  addons/account/i18n/lv.po
  addons/account/i18n/nb.po
  addons/account/i18n/nl.po
  addons/account/i18n/pl.po
  addons/account/i18n/pt.po
  addons/account/i18n/pt_BR.po
  addons/account/i18n/ro.po
  addons/account/i18n/ru.po
  addons/account/i18n/sk.po
  addons/account/i18n/sl.po
  addons/account/i18n/sr.po
  addons/account/i18n/sv.po
  addons/account/i18n/th.po
  addons/account/i18n/tr.po
  addons/account/i18n/uk.po
  addons/account/i18n/vi.po
  addons/account/i18n/zh_CN.po
  addons/account/i18n/zh_TW.po
  addons/account_edi/i18n/nb.po
  addons/account_edi/i18n/uk.po
  addons/account_edi_ubl_cii/i18n/et.po
  addons/account_edi_ubl_cii/i18n/ko.po
  addons/account_edi_ubl_cii/i18n/nb.po
  addons/account_edi_ubl_cii/i18n/nl.po
  addons/account_edi_ubl_cii/i18n/uk.po
  addons/account_edi_ubl_cii_tax_extension/i18n/et.po
  addons/account_edi_ubl_cii_tax_extension/i18n/pl.po
  addons/account_edi_ubl_cii_tax_extension/i18n/uk.po
  addons/account_payment/i18n/hr.po
  addons/account_payment/i18n/nb.po
  addons/account_peppol/i18n/uk.po
  addons/account_qr_code_emv/i18n/et.po
  addons/analytic/i18n/he.po
  addons/analytic/i18n/hr.po
  addons/auth_signup/i18n/hr.po
Labels: 17.0

#30027 Syncing from upstream odoo/odoo (18.0)
  addons/web/static/src/core/user.js
  odoo/netsvc.py
Labels: 18.0

#30028 Syncing from upstream odoo/odoo (master)
  addons/web/static/src/core/user.js
  addons/website/views/snippets/s_numbers.xml
  addons/website/views/snippets/s_numbers_list.xml
  odoo/netsvc.py
Labels: master

#30029 Syncing from upstream odoo/odoo (saas-17.2)
  odoo/netsvc.py
Labels: saas-17.2

#30030 Syncing from upstream odoo/odoo (saas-17.4)
  addons/web/static/src/core/user.js
  odoo/netsvc.py
Labels: saas-17.4

#30031 Syncing from upstream odoo/odoo (staging.master)
  addons/web/static/src/core/user.js
  addons/website/views/snippets/s_numbers.xml
  addons/website/views/snippets/s_numbers_list.xml
  odoo/netsvc.py
Labels: staging.master

#30032 Syncing from upstream odoo/odoo (staging.saas-17.2)
  odoo/netsvc.py
Labels: staging.saas-17.2

#30033 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/web/static/src/core/user.js
  odoo/netsvc.py
Labels: staging.saas-17.4

#30035 Syncing from upstream odoo/odoo (tmp.master)
  addons/web/static/src/core/user.js
  addons/website/views/snippets/s_numbers.xml
  addons/website/views/snippets/s_numbers_list.xml
  odoo/netsvc.py
Labels: tmp.master

#30036 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  odoo/netsvc.py
Labels: tmp.saas-17.2

#30037 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/web/static/src/core/user.js
  odoo/netsvc.py
Labels: tmp.saas-17.4

#30038 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/web/static/src/core/user.js
  odoo/netsvc.py
Labels: tmp.18.0

#30039 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/point_of_sale/models/pos_order.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/translate.py
Labels: 16.0

#30040 Syncing from upstream odoo/odoo (17.0)
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.xml
  addons/hr/report/hr_employee_badge.xml
  addons/hr_holidays/static/src/scss/accrual_plan_level.scss
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/generic_components/orderline/orderline.xml
  addons/point_of_sale/static/tests/tours/ReceiptScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/generic_components/OrderWidgetMethods.js
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/models/res_config_settings.py
  addons/pos_self_order/tests/test_self_order_common.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/repair/tests/test_repair.py
  addons/repair/views/repair_views.xml
  addons/sale_project/models/project.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/components/media_dialog/file_selector.js
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/components/media_dialog/image_selector.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_sale_loyalty/views/website_sale_templates.xml
  odoo/tools/translate.py
Labels: 17.0

#30043 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/ir_module.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.js
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.xml
  addons/l10n_fr_account/models/template_mc.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_online_payment_self_order/controllers/payment_portal.py
  addons/stock/models/stock_lot.py
  addons/stock/tests/test_stock_lot.py
  addons/web/static/src/core/file_viewer/file_viewer.xml
  addons/web_editor/static/src/components/media_dialog/file_selector.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  odoo/addons/base/models/ir_module.py
  odoo/tools/translate.py
Labels: saas-17.2

#30046 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/ir_module.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.js
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.xml
  addons/l10n_fr_account/models/template_mc.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_online_payment_self_order/controllers/payment_portal.py
  addons/stock/models/stock_lot.py
  addons/stock/tests/test_stock_lot.py
  addons/web/static/src/core/file_viewer/file_viewer.xml
  addons/web_editor/static/src/components/media_dialog/file_selector.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  odoo/addons/base/models/ir_module.py
  odoo/tools/translate.py
Labels: staging.saas-17.2

#30048 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/point_of_sale/models/pos_order.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/translate.py
Labels: staging.16.0

#30051 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/ir_module.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.js
  addons/hr_fleet/static/src/views/hr_fleet_kanban/hr_fleet_kanban_controller.xml
  addons/l10n_fr_account/models/template_mc.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_online_payment_self_order/controllers/payment_portal.py
  addons/stock/models/stock_lot.py
  addons/stock/tests/test_stock_lot.py
  addons/web/static/src/core/file_viewer/file_viewer.xml
  addons/web_editor/static/src/components/media_dialog/file_selector.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  odoo/addons/base/models/ir_module.py
  odoo/tools/translate.py
Labels: tmp.saas-17.2

#30053 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/point_of_sale/models/pos_order.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/translate.py
Labels: tmp.16.0

#30056 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move_line.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/iap/tools/iap_tools.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/stock_account/models/product.py
  addons/web/controllers/export.py
  addons/web/static/src/core/browser/browser.js
  addons/web/static/src/legacy/js/core/local_storage.js
  addons/web/static/src/legacy/js/core/session_storage.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
  addons/website/static/tests/tours/media_iframe_video.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/stesiconsultingsrl.md
Labels: 16.0

#30060 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/chart_template.py
  addons/bus/models/res_users.py
  addons/hr/models/hr_employee_base.py
  addons/hr_holidays/models/res_partner.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/static/src/scss/accrual_plan_level.scss
  addons/hr_homeworking/models/res_users.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_move.py
  addons/l10n_ar/models/account_tax_group.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/mail/static/src/chatter/web/chatter_patch.js
  addons/mail/static/src/core/common/attachment_view.js
  addons/mail/static/src/core/common/attachment_view.xml
  addons/mail/static/src/core/common/mail_popout_service.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_tour.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_loyalty_program_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/static/src/js/tours/project.js
  addons/sale_project/models/project_project.py
  addons/sale_project/models/project_task.py
  addons/sale_timesheet/models/project_project.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/sale_timesheet/report/project_report.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet/tests/test_task_analysis.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/components/media_dialog/image_selector.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/corporate/braintec.md
  odoo/addons/base/tests/test_tz.py
  odoo/addons/base/tests/test_xmlrpc.py
  odoo/addons/test_read_group/tests/test_groupby_week.py
  odoo/models.py
Labels: staging.saas-17.4

#30061 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move_line.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/iap/tools/iap_tools.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_project.py
  addons/stock_account/models/product.py
  addons/web/controllers/export.py
  addons/web/static/src/core/browser/browser.js
  addons/web/static/src/legacy/js/core/local_storage.js
  addons/web/static/src/legacy/js/core/session_storage.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
  addons/website/static/tests/tours/media_iframe_video.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/stesiconsultingsrl.md
Labels: staging.16.0

#30062 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move_line.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_attendance/static/src/hr_attendance.scss
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_si/__manifest__.py
  addons/l10n_si/data/account_account_tag.xml
  addons/l10n_si/data/account_tax_report_data.xml
  addons/l10n_si/data/account_tax_report_ir_data.xml
  addons/l10n_si/data/account_tax_report_pd_data.xml
  addons/l10n_si/data/account_tax_report_pr_data.xml
  addons/l10n_si/data/template/account.account-si.csv
  addons/l10n_si/data/template/account.fiscal.position-si.csv
  addons/l10n_si/data/template/account.tax-si.csv
  addons/l10n_si/data/template/account.tax.group-si.csv
  addons/l10n_si/i18n/l10n_si.pot
  addons/l10n_si/i18n/sl.po
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_attachment.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/discuss_app/im_status_tests.js
  addons/mail/static/tests/messaging_menu/messaging_menu_tests.js
  addons/mail/tests/__init__.py
  addons/mail/tests/discuss/test_discuss_channel.py
  addons/mail/tests/test_mail_message.py
  addons/maintenance/static/tests/tours/tour_calendar_with_recurrence.js
  addons/mrp/models/stock_warehouse.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/point_of_sale/static/src/app/store/combo_configurator_popup/combo_configurator_popup.js
  addons/point_of_sale/static/tests/tours/PosComboTour.js
  addons/point_of_sale/static/tests/tours/helpers/ComboPopupMethods.js
  addons/point_of_sale/tests/common_setup_methods.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/repair/models/stock_warehouse.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/report/project_report.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/sale_timesheet/tests/test_task_analysis.py
  addons/stock/models/product.py
  addons/stock/models/stock_warehouse.py
  doc/cla/corporate/oerp.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_tz.py
Labels: staging.17.0

#30064 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move_line.py
  addons/hr/report/hr_employee_badge.xml
  addons/hr_attendance/static/src/hr_attendance.scss
  addons/hr_holidays/static/src/scss/accrual_plan_level.scss
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/report/report_timesheet_templates.xml
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/__init__.py
  addons/l10n_it_edi/tests/test_res_partner.py
  addons/mail/static/src/core/common/attachment_list.xml
  addons/mass_mailing/static/src/js/tours/mass_mailing_tour.js
  addons/point_of_sale/static/src/app/generic_components/orderline/orderline.xml
  addons/point_of_sale/static/tests/tours/ReceiptScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/generic_components/OrderWidgetMethods.js
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/sale_project/models/project.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/report/project_report.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet/tests/test_task_analysis.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/legacy/views/list_view_tests.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/components/media_dialog/image_selector.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website_sale/static/src/js/website_sale.editor.js
  addons/website_sale_loyalty/views/website_sale_templates.xml
  doc/cla/corporate/braintec.md
  doc/cla/corporate/oerp.md
  odoo/addons/base/tests/test_tz.py
  odoo/addons/base/tests/test_xmlrpc.py
Labels: tmp.saas-17.2

#30065 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/chart_template.py
  addons/bus/models/res_users.py
  addons/hr/models/hr_employee_base.py
  addons/hr_holidays/models/res_partner.py
  addons/hr_holidays/models/res_users.py
  addons/hr_holidays/static/src/scss/accrual_plan_level.scss
  addons/hr_homeworking/models/res_users.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/account_move.py
  addons/l10n_ar/models/account_tax_group.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/mail/static/src/chatter/web/chatter_patch.js
  addons/mail/static/src/core/common/attachment_view.js
  addons/mail/static/src/core/common/attachment_view.xml
  addons/mail/static/src/core/common/mail_popout_service.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_tour.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/static/src/js/tours/project.js
  addons/sale_project/models/project_project.py
  addons/sale_project/models/project_task.py
  addons/sale_timesheet/models/project_project.py
  addons/sale_timesheet/models/project_sale_line_employee_map.py
  addons/sale_timesheet/report/project_report.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet/tests/test_task_analysis.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_picking.py
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/components/media_dialog/image_selector.xml
  addons/web_editor/static/src/js/common/utils.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/static/src/js/website_sale.editor.js
  doc/cla/corporate/braintec.md
  odoo/addons/base/tests/test_tz.py
  odoo/addons/base/tests/test_xmlrpc.py
  odoo/addons/test_read_group/tests/test_groupby_week.py
  odoo/models.py
Labels: tmp.saas-17.4

#30067 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move_line.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_attendance/static/src/hr_attendance.scss
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_si/__manifest__.py
  addons/l10n_si/data/account_account_tag.xml
  addons/l10n_si/data/account_tax_report_data.xml
  addons/l10n_si/data/account_tax_report_ir_data.xml
  addons/l10n_si/data/account_tax_report_pd_data.xml
  addons/l10n_si/data/account_tax_report_pr_data.xml
  addons/l10n_si/data/template/account.account-si.csv
  addons/l10n_si/data/template/account.fiscal.position-si.csv
  addons/l10n_si/data/template/account.tax-si.csv
  addons/l10n_si/data/template/account.tax.group-si.csv
  addons/l10n_si/i18n/l10n_si.pot
  addons/l10n_si/i18n/sl.po
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_attachment.py
  addons/mail/models/mail_message.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/discuss_app/im_status_tests.js
  addons/mail/static/tests/messaging_menu/messaging_menu_tests.js
  addons/mail/tests/__init__.py
  addons/mail/tests/discuss/test_discuss_channel.py
  addons/mail/tests/test_mail_message.py
  addons/maintenance/static/tests/tours/tour_calendar_with_recurrence.js
  addons/mrp/models/stock_warehouse.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/point_of_sale/static/src/app/store/combo_configurator_popup/combo_configurator_popup.js
  addons/point_of_sale/static/tests/tours/PosComboTour.js
  addons/point_of_sale/static/tests/tours/helpers/ComboPopupMethods.js
  addons/point_of_sale/tests/common_setup_methods.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/repair/models/stock_warehouse.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/report/project_report.py
  addons/sale_timesheet/tests/__init__.py
  addons/sale_timesheet/tests/test_project.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/sale_timesheet/tests/test_task_analysis.py
  addons/stock/models/product.py
  addons/stock/models/stock_warehouse.py
  doc/cla/corporate/oerp.md
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/tests/test_tz.py
Labels: tmp.17.0

#30069 Syncing from upstream odoo/odoo (16.0)
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/account_move.py
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web_kanban_gauge/static/src/gauge_field.js
  addons/web_kanban_gauge/static/tests/gauge_value_tests.js
Labels: 16.0

#30070 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/chart_template.py
  addons/event/report/event_event_templates.xml
  addons/iap/tools/iap_tools.py
  addons/l10n_in/views/res_config_settings_views.xml
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_uy/data/template/account.tax-uy.csv
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/project/views/project_project_views.xml
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/report/stock_forecasted.py
  addons/stock_account/models/product.py
  addons/test_mail_sms/tests/test_mail_thread_phone.py
  addons/web/controllers/export.py
  addons/web/static/src/core/browser/browser.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
  doc/cla/corporate/stesiconsultingsrl.md
Labels: 17.0

#30077 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/ir_module.py
  addons/event_product/models/event_event_ticket.py
  addons/hr/report/hr_employee_badge.xml
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/report/report_timesheet_templates.xml
  addons/iap/tools/iap_tools.py
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_fr_account/models/__init__.py
  addons/l10n_fr_account/models/template_mc.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_mc/__init__.py
  addons/l10n_mc/__manifest__.py
  addons/l10n_uy/data/template/account.tax-uy.csv
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_attachment.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/attachment_list.xml
  addons/mail/tests/discuss/test_discuss_channel.py
  addons/maintenance/static/tests/tours/tour_calendar_with_recurrence.js
  addons/mrp/models/product.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/test_bom.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/store/combo_configurator_popup/combo_configurator_popup.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/static/tests/tours/utils/combo_popup_util.js
  addons/point_of_sale/tests/common_setup_methods.py
  addons/portal/static/src/js/portal.js
  addons/pos_loyalty/static/tests/tours/gift_card_program_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/purchase/models/purchase_order.py
  addons/repair/models/stock_warehouse.py
  addons/sale/static/src/js/product/product.xml
  addons/sale_project/models/project_project.py
  addons/sale_timesheet/models/project_project.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/stock/models/product.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_warehouse.py
  addons/stock/tests/test_stock_lot.py
  addons/web/controllers/export.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website_sale/static/src/js/product/product.xml
  doc/cla/corporate/oerp.md
  doc/cla/corporate/stesiconsultingsrl.md
  odoo/addons/base/models/ir_attachment.py
Labels: staging.saas-17.4

#30078 Syncing from upstream odoo/odoo (staging.16.0)
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/account_move.py
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_kanban_gauge/static/src/gauge_field.js
  addons/web_kanban_gauge/static/tests/gauge_value_tests.js
  addons/website/static/src/scss/bootstrap_overridden.scss
Labels: staging.16.0

#30079 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/chart_template.py
  addons/event/report/event_event_templates.xml
  addons/iap/tools/iap_tools.py
  addons/l10n_in/views/res_config_settings_views.xml
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_uy/data/template/account.tax-uy.csv
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/project/views/project_project_views.xml
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/report/stock_forecasted.py
  addons/stock_account/models/product.py
  addons/test_mail_sms/tests/test_mail_thread_phone.py
  addons/web/controllers/export.py
  addons/web/static/src/core/browser/browser.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
  doc/cla/corporate/stesiconsultingsrl.md
Labels: staging.17.0

#30081 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/chart_template.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.xml
  addons/event_sale/models/event_ticket.py
  addons/iap/tools/iap_tools.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_uy/data/template/account.tax-uy.csv
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_attachment.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/discuss/test_discuss_channel.py
  addons/maintenance/static/tests/tours/tour_calendar_with_recurrence.js
  addons/mrp/models/product.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/test_bom.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/point_of_sale/static/src/app/store/combo_configurator_popup/combo_configurator_popup.js
  addons/point_of_sale/static/tests/tours/PosComboTour.js
  addons/point_of_sale/static/tests/tours/helpers/ComboPopupMethods.js
  addons/point_of_sale/tests/common_setup_methods.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/project/views/project_project_views.xml
  addons/repair/models/stock_warehouse.py
  addons/sale_timesheet/models/project.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/stock/models/product.py
  addons/stock/models/stock_warehouse.py
  addons/web/controllers/export.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  doc/cla/corporate/stesiconsultingsrl.md
  odoo/addons/base/models/ir_attachment.py
Labels: tmp.saas-17.2

#30082 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/ir_module.py
  addons/event_product/models/event_event_ticket.py
  addons/hr/report/hr_employee_badge.xml
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/report/report_timesheet_templates.xml
  addons/iap/tools/iap_tools.py
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_cl/views/report_invoice.xml
  addons/l10n_fr_account/models/__init__.py
  addons/l10n_fr_account/models/template_mc.py
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_mc/__init__.py
  addons/l10n_mc/__manifest__.py
  addons/l10n_uy/data/template/account.tax-uy.csv
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_attachment.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/attachment_list.xml
  addons/mail/tests/discuss/test_discuss_channel.py
  addons/maintenance/static/tests/tours/tour_calendar_with_recurrence.js
  addons/mrp/models/product.py
  addons/mrp/models/stock_warehouse.py
  addons/mrp/tests/test_bom.py
  addons/mrp_subcontracting/models/stock_warehouse.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/store/combo_configurator_popup/combo_configurator_popup.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/static/tests/tours/utils/combo_popup_util.js
  addons/point_of_sale/tests/common_setup_methods.py
  addons/portal/static/src/js/portal.js
  addons/pos_loyalty/static/tests/tours/gift_card_program_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project_sale_expense/models/project_project.py
  addons/project_sale_expense/tests/test_project_profitability.py
  addons/purchase/models/purchase_order.py
  addons/repair/models/stock_warehouse.py
  addons/sale/static/src/js/product/product.xml
  addons/sale_project/models/project_project.py
  addons/sale_timesheet/models/project_project.py
  addons/sale_timesheet/tests/test_reinvoice.py
  addons/stock/models/product.py
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_warehouse.py
  addons/stock/tests/test_stock_lot.py
  addons/web/controllers/export.py
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website_sale/static/src/js/product/product.xml
  doc/cla/corporate/oerp.md
  doc/cla/corporate/stesiconsultingsrl.md
  odoo/addons/base/models/ir_attachment.py
Labels: tmp.saas-17.4

#30083 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/sale_stock/models/account_move.py
  addons/stock_account/models/account_move.py
  addons/web/static/lib/tempusdominus/tempusdominus.js
  addons/web_kanban_gauge/static/src/gauge_field.js
  addons/web_kanban_gauge/static/tests/gauge_value_tests.js
Labels: tmp.16.0

#30084 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/chart_template.py
  addons/event/report/event_event_templates.xml
  addons/iap/tools/iap_tools.py
  addons/l10n_in/views/res_config_settings_views.xml
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_uy/data/template/account.tax-uy.csv
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/project/views/project_project_views.xml
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/report/stock_forecasted.py
  addons/stock_account/models/product.py
  addons/test_mail_sms/tests/test_mail_thread_phone.py
  addons/web/controllers/export.py
  addons/web/static/src/core/browser/browser.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
  doc/cla/corporate/stesiconsultingsrl.md
Labels: tmp.17.0

#30086 Syncing from upstream odoo/odoo (16.0)
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/static/src/js/views/activity/activity_controller.js
  addons/mrp/tests/test_order.py
  addons/purchase_stock/models/stock_move.py
  addons/sale_stock/models/account_move.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/scss/bootstrap_overridden.scss
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
Labels: 16.0

#30087 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/chart_template.py
  addons/auth_password_policy_signup/views/signup_templates.xml
  addons/base_automation/models/base_automation.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/mail/static/src/core/common/autoresize_input.js
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/pos_adyen/static/src/app/pos_bus.js
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock_account/models/account_move.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/static/tests/tours/colorpicker.js
  addons/website/static/tests/tours/media_iframe_video.js
  addons/website/tests/test_ui.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/cli/obfuscate.py
Labels: 17.0

#30090 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/auth_password_policy_signup/views/signup_templates.xml
  addons/base_automation/models/base_automation.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_in/views/res_config_settings_views.xml
  addons/l10n_si/__manifest__.py
  addons/l10n_si/data/account_account_tag.xml
  addons/l10n_si/data/account_tax_report_data.xml
  addons/l10n_si/data/account_tax_report_ir_data.xml
  addons/l10n_si/data/account_tax_report_pd_data.xml
  addons/l10n_si/data/account_tax_report_pr_data.xml
  addons/l10n_si/data/template/account.account-si.csv
  addons/l10n_si/data/template/account.fiscal.position-si.csv
  addons/l10n_si/data/template/account.tax-si.csv
  addons/l10n_si/data/template/account.tax.group-si.csv
  addons/l10n_si/i18n/l10n_si.pot
  addons/l10n_si/i18n/sl.po
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/autoresize_input.js
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_message.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/repair/tests/test_repair.py
  addons/repair/views/repair_views.xml
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/report/stock_forecasted.py
  addons/stock_account/models/product.py
  addons/test_mail_sms/tests/test_mail_thread_phone.py
  addons/web/static/src/core/browser/browser.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
Labels: staging.saas-17.2

#30093 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/chart_template.py
  addons/auth_password_policy_signup/views/signup_templates.xml
  addons/base_automation/models/base_automation.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/mail/static/src/core/common/autoresize_input.js
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/pos_adyen/static/src/app/pos_bus.js
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock_account/models/account_move.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/static/tests/tours/colorpicker.js
  addons/website/static/tests/tours/media_iframe_video.js
  addons/website/tests/test_ui.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/cli/obfuscate.py
Labels: staging.17.0

#30095 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/auth_password_policy_signup/views/signup_templates.xml
  addons/base_automation/models/base_automation.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_in/views/res_config_settings_views.xml
  addons/l10n_si/__manifest__.py
  addons/l10n_si/data/account_account_tag.xml
  addons/l10n_si/data/account_tax_report_data.xml
  addons/l10n_si/data/account_tax_report_ir_data.xml
  addons/l10n_si/data/account_tax_report_pd_data.xml
  addons/l10n_si/data/account_tax_report_pr_data.xml
  addons/l10n_si/data/template/account.account-si.csv
  addons/l10n_si/data/template/account.fiscal.position-si.csv
  addons/l10n_si/data/template/account.tax-si.csv
  addons/l10n_si/data/template/account.tax.group-si.csv
  addons/l10n_si/i18n/l10n_si.pot
  addons/l10n_si/i18n/sl.po
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/autoresize_input.js
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_message.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/repair/tests/test_repair.py
  addons/repair/views/repair_views.xml
  addons/sale_mrp/models/sale_order_line.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock/report/stock_forecasted.py
  addons/stock_account/models/product.py
  addons/test_mail_sms/tests/test_mail_thread_phone.py
  addons/web/static/src/core/browser/browser.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/client_actions/configurator/configurator.js
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/static/tests/tour_utils/widget_lifecycle_dep_widget.js
Labels: tmp.saas-17.2

#30097 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/static/src/js/views/activity/activity_controller.js
  addons/mrp/tests/test_order.py
  addons/purchase_stock/models/stock_move.py
  addons/sale_stock/models/account_move.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/scss/bootstrap_overridden.scss
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
Labels: tmp.16.0

#30098 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/chart_template.py
  addons/auth_password_policy_signup/views/signup_templates.xml
  addons/base_automation/models/base_automation.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/mail/static/src/core/common/autoresize_input.js
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mail/static/tests/chat_window/chat_window_tests.js
  addons/pos_adyen/static/src/app/pos_bus.js
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock_account/models/account_move.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/scss/bootstrap_overridden.scss
  addons/website/static/tests/tours/colorpicker.js
  addons/website/static/tests/tours/media_iframe_video.js
  addons/website/tests/test_ui.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/cli/obfuscate.py
Labels: tmp.17.0

#30100 Syncing from upstream odoo/odoo (16.0)
  addons/mail/models/mail_mail.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/stock/models/stock_warehouse.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_sale_product_configurators/static/tests/tours/product_configurator_optional_products_ui.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: 16.0

#30101 Syncing from upstream odoo/odoo (17.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_pe/data/template/account.tax-pe.csv
  addons/l10n_pe/data/template/account.tax.group-pe.csv
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_self_order/views/pos_self_order.index.xml
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/tests/views/fields/gauge_field_tests.js
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
  odoo/addons/base/views/res_partner_views.xml
Labels: 17.0

#30107 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/chart_template.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/mrp/tests/test_order.py
  addons/pos_adyen/static/src/app/pos_store.js
  addons/pos_self_order/views/pos_self_order.index.xml
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock_account/models/account_move.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/colorpicker.js
  addons/website/tests/test_ui.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/cli/obfuscate.py
Labels: staging.saas-17.2

#30109 Syncing from upstream odoo/odoo (staging.16.0)
  addons/mail/models/mail_mail.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_warehouse.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_sale_product_configurators/static/tests/tours/product_configurator_optional_products_ui.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: staging.16.0

#30110 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_pe/data/template/account.tax-pe.csv
  addons/l10n_pe/data/template/account.tax.group-pe.csv
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_self_order/views/pos_self_order.index.xml
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/tests/views/fields/gauge_field_tests.js
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
  odoo/addons/base/views/res_partner_views.xml
Labels: staging.17.0

#30112 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/chart_template.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/mrp/tests/test_order.py
  addons/pos_adyen/static/src/app/pos_store.js
  addons/pos_self_order/views/pos_self_order.index.xml
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin_test.js
  addons/stock_account/models/account_move.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website/static/tests/tours/colorpicker.js
  addons/website/tests/test_ui.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/cli/obfuscate.py
Labels: tmp.saas-17.2

#30113 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/chart_template.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_sa/i18n_extra/ar.po
  addons/l10n_sa/i18n_extra/l10n_sa.pot
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/i18n/ar.po
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/loyalty/models/loyalty_reward.py
  addons/loyalty/tests/test_loyalty.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/maintenance/static/tests/tours/tour_calendar_with_recurrence.js
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_warehouse_multistep_manufacturing.py
  addons/pos_self_order/views/pos_self_order.index.xml
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/repair/tests/test_repair.py
  addons/repair/views/repair_views.xml
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/account_move.py
  addons/sale_stock/models/sale_order.py
  addons/stock_account/models/account_move.py
  addons/stock_account/models/product.py
  addons/test_mail/static/tests/attachment_view.test.js
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_model.py
  odoo/cli/obfuscate.py
Labels: tmp.saas-17.4

#30114 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/mail/models/mail_mail.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/sale_product_configurator/controllers/main.py
  addons/sale_product_configurator/static/src/js/product_configurator_modal.js
  addons/stock/models/stock_warehouse.py
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/test_sale_product_configurators/static/tests/tours/product_configurator_optional_products_ui.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: tmp.16.0

#30115 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_pe/data/template/account.tax-pe.csv
  addons/l10n_pe/data/template/account.tax.group-pe.csv
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_self_order/views/pos_self_order.index.xml
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/tests/views/fields/gauge_field_tests.js
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
  odoo/addons/base/views/res_partner_views.xml
Labels: tmp.17.0

#30125 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.16.0

#30126 Syncing from upstream odoo/odoo (staging.master)
  addons/pos_self_order/views/pos_self_order.index.xml
Labels: staging.master

#30127 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
Labels: staging.saas-17.2

#30128 Syncing from upstream odoo/odoo (16.0)
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
Labels: 16.0

#30129 Syncing from upstream odoo/odoo (17.0)
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
Labels: 17.0

#30130 Syncing from upstream odoo/odoo (18.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
  addons/website/static/src/components/dialog/edit_menu.js
  addons/website/static/tests/tours/edit_menus.js
Labels: 18.0

#30131 Syncing from upstream odoo/odoo (master)
  addons/account/views/report_payment_receipt_templates.xml
  addons/point_of_sale/models/product_template.py
  addons/point_of_sale/static/src/app/components/popups/combo_configurator_popup/combo_configurator_popup.xml
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.js
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.scss
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.xml
  addons/point_of_sale/static/src/app/models/product_template.js
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
Labels: master

#30132 Syncing from upstream odoo/odoo (saas-17.2)
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
Labels: saas-17.2

#30133 Syncing from upstream odoo/odoo (saas-17.4)
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
Labels: saas-17.4

#30134 Syncing from upstream odoo/odoo (staging.master)
  addons/account/views/report_payment_receipt_templates.xml
  addons/point_of_sale/models/product_template.py
  addons/point_of_sale/static/src/app/components/popups/combo_configurator_popup/combo_configurator_popup.xml
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.js
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.scss
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.xml
  addons/point_of_sale/static/src/app/models/product_template.js
Labels: staging.master

#30142 Syncing from upstream odoo/odoo (16.0)
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp_mail/tests/test_totp.py
  addons/auth_totp_portal/tests/test_tour.py
  addons/lunch/static/tests/tours/order_lunch.js
  addons/lunch/tests/test_ui.py
  addons/mrp/models/product.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/tests/test_bom.py
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_js.py
  addons/repair/tests/test_repair.py
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
  addons/sale_timesheet/tests/test_sale_timesheet_ui.py
  addons/test_sale_product_configurators/tests/test_sale_product_matrix.py
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/systray_items/website_switcher.xml
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/snippet_cache_across_websites.js
  addons/website/tests/test_page_manager.py
  addons/website/tests/test_ui.py
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_payment/tests/test_snippets.py
  addons/website_profile/static/tests/tours/tour_website_profile_description.js
  addons/website_profile/tests/test_website_profile.py
  addons/website_sale/controllers/main.py
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale/static/tests/tours/website_sale_add_to_cart_snippet_tour.js
  addons/website_sale/static/tests/tours/website_sale_category_page_and_products_snippet.js
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_editor.py
  addons/website_sale/tests/test_website_sale_add_to_cart_snippet.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_snippets.py
  addons/website_sale_comparison/static/tests/tours/website_sale_comparison.js
  addons/website_sale_comparison/tests/test_website_sale_comparison.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  doc/cla/corporate/forgeflow.md
  doc/cla/corporate/odootech.md
  odoo/addons/base/tests/common.py
  odoo/addons/test_apikeys/tests/test_flow.py
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
  odoo/addons/test_main_flows/tests/test_flow.py
Labels: 16.0

#30143 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/l10n_it_edi/models/account_move.py
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/controllers/discuss/public_page.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_mail.py
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mrp/models/stock_orderpoint.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase_stock/models/stock.py
  addons/purchase_stock/models/stock_move.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/stock/models/product.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/stock_dropshipping/models/stock.py
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/tests/core/errors/error_service_tests.js
  addons/website_sale/models/product_public_category.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: 17.0

#30146 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account_audit_trail/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/mail/models/mail_mail.py
  addons/mrp/views/mrp_production_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/models/account_move.py
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/tests/legacy/views/fields/gauge_field_tests.js
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: saas-17.2

#30147 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/pos_adyen/static/src/app/pos_store.js
  addons/pos_discount/__manifest__.py
  addons/pos_discount/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_discount/static/tests/tours/global_discount_tour.js
  addons/pos_discount/tests/__init__.py
  addons/pos_discount/tests/test_frontend.py
  addons/purchase_stock/models/stock_move.py
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_delivery/models/delivery_carrier.py
  addons/web/static/src/core/l10n/dates.js
  addons/website/static/src/snippets/s_searchbar/000.js
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
Labels: saas-17.4

#30149 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_move.py
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account_audit_trail/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/mail/models/mail_mail.py
  addons/mrp/views/mrp_production_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/models/account_move.py
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/tests/legacy/views/fields/gauge_field_tests.js
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: staging.saas-17.2

#30150 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_move.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/pos_adyen/static/src/app/pos_store.js
  addons/pos_discount/__manifest__.py
  addons/pos_discount/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_discount/static/tests/tours/global_discount_tour.js
  addons/pos_discount/tests/__init__.py
  addons/pos_discount/tests/test_frontend.py
  addons/purchase_stock/models/stock_move.py
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_delivery/models/delivery_carrier.py
  addons/web/static/src/core/l10n/dates.js
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
  addons/website/static/src/snippets/s_searchbar/000.js
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
Labels: staging.saas-17.4

#30151 Syncing from upstream odoo/odoo (staging.16.0)
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp_mail/tests/test_totp.py
  addons/auth_totp_portal/tests/test_tour.py
  addons/lunch/static/tests/tours/order_lunch.js
  addons/lunch/tests/test_ui.py
  addons/mrp/models/product.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/tests/test_bom.py
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_js.py
  addons/repair/tests/test_repair.py
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
  addons/sale_timesheet/tests/test_sale_timesheet_ui.py
  addons/test_sale_product_configurators/tests/test_sale_product_matrix.py
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/systray_items/website_switcher.xml
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/snippet_cache_across_websites.js
  addons/website/tests/test_page_manager.py
  addons/website/tests/test_ui.py
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_payment/tests/test_snippets.py
  addons/website_profile/static/tests/tours/tour_website_profile_description.js
  addons/website_profile/tests/test_website_profile.py
  addons/website_sale/controllers/main.py
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale/static/tests/tours/website_sale_add_to_cart_snippet_tour.js
  addons/website_sale/static/tests/tours/website_sale_category_page_and_products_snippet.js
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_editor.py
  addons/website_sale/tests/test_website_sale_add_to_cart_snippet.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_snippets.py
  addons/website_sale_comparison/static/tests/tours/website_sale_comparison.js
  addons/website_sale_comparison/tests/test_website_sale_comparison.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  doc/cla/corporate/forgeflow.md
  doc/cla/corporate/odootech.md
  odoo/addons/base/tests/common.py
  odoo/addons/test_apikeys/tests/test_flow.py
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
  odoo/addons/test_main_flows/tests/test_flow.py
Labels: staging.16.0

#30155 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account_audit_trail/models/account_move.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/mail/models/mail_mail.py
  addons/mrp/views/mrp_production_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/models/account_move.py
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/tests/legacy/views/fields/gauge_field_tests.js
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
  doc/cla/individual/bhanq.md
  doc/cla/sign-cla.md
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/tools/mail.py
Labels: tmp.saas-17.2

#30157 [bt#29836][bt#28984] fixes from core regarding balances in PoS
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/stock/models/stock_orderpoint.py
Labels: 17.0.project_mg_732

#30158 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web_editor/tests/test_tools.py
  addons/web_editor/tools.py
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_slide.py
Labels: 16.0

#30159 Syncing from upstream odoo/odoo (17.0)
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_payment/models/account_payment.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ec/models/template_ec.py
  addons/l10n_ec_stock/__init__.py
  addons/l10n_ec_stock/__manifest__.py
  addons/l10n_ec_stock/models/__init__.py
  addons/l10n_ec_stock/models/account_chart_template.py
  addons/l10n_eu_oss/models/res_company.py
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/tests/discuss/typing/typing_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/tests/test_bom.py
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/controllers/main.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website_event/static/tests/tours/website_event.js
  addons/website_event/views/event_templates_list.xml
  addons/website_sale_product_configurator/controllers/main.py
  addons/website_sale_product_configurator/static/src/js/sale_product_configurator_modal.js
  doc/cla/corporate/forgeflow.md
  odoo/tools/misc.py
Labels: 17.0

#30162 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/event/report/event_event_templates.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/controllers/discuss/public_page.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/static/tests/discuss/typing/typing.test.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/test_mail/static/tests/activity.test.js
  addons/web/i18n/web.pot
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/src/search/control_panel/control_panel.js
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/core/errors/error_service.test.js
  addons/web/static/tests/legacy/views/fields/many2many_field_tests.js
  odoo/tools/misc.py
Labels: saas-17.2

#30163 Syncing from upstream odoo/odoo (saas-17.4)
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/crm/models/crm_team.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_message.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/spreadsheet/static/tests/helpers/model.js
  addons/test_mail/static/tests/activity.test.js
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/core/errors/error_service.test.js
  addons/web/static/tests/views/fields/gauge_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/website/static/src/snippets/s_searchbar/000.xml
  addons/website/views/website_templates.xml
  addons/website_sale/static/src/js/product/product.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/addons/test_lint/tests/_odoo_checker_sql_injection.py
  odoo/tools/mail.py
Labels: saas-17.4

#30166 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/crm/models/crm_team.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_message.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/spreadsheet/static/tests/helpers/model.js
  addons/test_mail/static/tests/activity.test.js
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/core/errors/error_service.test.js
  addons/web/static/tests/views/fields/gauge_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/website/static/src/snippets/s_searchbar/000.xml
  addons/website/views/website_templates.xml
  addons/website_sale/static/src/js/product/product.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/addons/test_lint/tests/_odoo_checker_sql_injection.py
  odoo/tools/mail.py
Labels: staging.saas-17.4

#30167 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web_editor/tests/test_tools.py
  addons/web_editor/tools.py
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_slide.py
Labels: staging.16.0

#30168 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_payment/models/account_payment.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_ec/models/template_ec.py
  addons/l10n_ec_stock/__init__.py
  addons/l10n_ec_stock/__manifest__.py
  addons/l10n_ec_stock/models/__init__.py
  addons/l10n_ec_stock/models/account_chart_template.py
  addons/l10n_eu_oss/models/res_company.py
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/tests/discuss/typing/typing_tests.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/tests/test_bom.py
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/controllers/main.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/website_event/static/tests/tours/website_event.js
  addons/website_event/views/event_templates_list.xml
  addons/website_sale_product_configurator/controllers/main.py
  addons/website_sale_product_configurator/static/src/js/sale_product_configurator_modal.js
  doc/cla/corporate/forgeflow.md
  odoo/tools/misc.py
Labels: staging.17.0

#30171 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/event/report/event_event_templates.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/controllers/discuss/public_page.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/static/tests/discuss/typing/typing.test.js
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_bom.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/test_mail/static/tests/activity.test.js
  addons/web/i18n/web.pot
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/src/search/control_panel/control_panel.js
  addons/web/static/src/search/control_panel/control_panel.xml
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/core/errors/error_service.test.js
  addons/web/static/tests/legacy/views/fields/many2many_field_tests.js
  odoo/tools/misc.py
Labels: tmp.saas-17.2

#30172 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/crm/models/crm_team.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/dropzone_hook.js
  addons/mail/static/src/core/common/notification_model.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_message.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/spreadsheet/static/tests/helpers/model.js
  addons/test_mail/static/tests/activity.test.js
  addons/test_mail/tests/test_mail_composer.py
  addons/web/static/src/core/errors/error_service.js
  addons/web/static/src/views/fields/gauge/gauge_field.js
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/core/errors/error_service.test.js
  addons/web/static/tests/views/fields/gauge_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/website/static/src/snippets/s_searchbar/000.xml
  addons/website/views/website_templates.xml
  addons/website_sale/static/src/js/product/product.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/addons/test_lint/tests/_odoo_checker_sql_injection.py
  odoo/tools/mail.py
Labels: tmp.saas-17.4

#30173 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/auth_totp/tests/test_totp.py
  addons/auth_totp_mail/tests/test_totp.py
  addons/auth_totp_portal/tests/test_tour.py
  addons/lunch/static/tests/tours/order_lunch.js
  addons/lunch/tests/test_ui.py
  addons/mrp/models/product.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/tests/test_bom.py
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_js.py
  addons/repair/tests/test_repair.py
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
  addons/sale_timesheet/tests/test_sale_timesheet_ui.py
  addons/test_sale_product_configurators/tests/test_sale_product_matrix.py
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/views/fields/x2many/x2many_field.xml
  addons/web/static/tests/views/fields/many2many_field_tests.js
  addons/web_editor/tests/test_tools.py
  addons/web_editor/tools.py
  addons/website/controllers/main.py
  addons/website/models/website_snippet_filter.py
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/systray_items/website_switcher.xml
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/snippet_cache_across_websites.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/tests/test_page_manager.py
  addons/website/tests/test_ui.py
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_payment/tests/test_snippets.py
  addons/website_profile/static/tests/tours/tour_website_profile_description.js
  addons/website_profile/tests/test_website_profile.py
  addons/website_sale/controllers/main.py
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale/static/tests/tours/website_sale_add_to_cart_snippet_tour.js
  addons/website_sale/static/tests/tours/website_sale_category_page_and_products_snippet.js
  addons/website_sale/static/tests/tours/website_sale_google_analytics.js
  addons/website_sale/static/tests/tours/website_sale_shop_pricelist_tour.js
  addons/website_sale/tests/test_sale_process.py
  addons/website_sale/tests/test_website_editor.py
  addons/website_sale/tests/test_website_sale_add_to_cart_snippet.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_snippets.py
  addons/website_sale_comparison/static/tests/tours/website_sale_comparison.js
  addons/website_sale_comparison/tests/test_website_sale_comparison.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_slide.py
  doc/cla/corporate/forgeflow.md
  doc/cla/corporate/odootech.md
  odoo/addons/base/tests/common.py
  odoo/addons/test_apikeys/tests/test_flow.py
  odoo/addons/test_main_flows/static/tests/tours/main_flow.js
  odoo/addons/test_main_flows/tests/test_flow.py
Labels: tmp.16.0

#30176 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/webclient/actions/reports/report.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  doc/cla/individual/mostafaala2.md
Labels: 16.0

#30177 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/mail/static/tests/discuss/typing/typing_tests.js
  addons/product/views/product_views.xml
  addons/sale/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: 17.0

#30180 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/l10n_ec/models/template_ec.py
  addons/l10n_ec_stock/__init__.py
  addons/l10n_ec_stock/__manifest__.py
  addons/l10n_ec_stock/models/__init__.py
  addons/l10n_ec_stock/models/account_chart_template.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_loyalty/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/list_controller.xml
  addons/website_sale_product_configurator/controllers/main.py
  addons/website_sale_product_configurator/static/src/js/sale_product_configurator_modal.js
  doc/cla/corporate/forgeflow.md
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: saas-17.2

#30181 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_report.py
  addons/account/report/account_invoice_report.py
  addons/account/static/src/js/tours/account.js
  addons/account/tests/test_account_invoice_report.py
  addons/account/wizard/account_move_send.py
  addons/calendar/models/res_users.py
  addons/calendar/tests/test_access_rights.py
  addons/hr_holidays/report/hr_leave_report_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/tests/discuss/core/composer.test.js
  addons/mail/static/tests/discuss/typing/typing.test.js
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/point_of_sale/static/src/customer_display/customer_display_data_service.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_loyalty/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin.test.js
  addons/stock/models/stock_quant.py
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/list_controller.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: saas-17.4

#30184 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_report.py
  addons/account/report/account_invoice_report.py
  addons/account/static/src/js/tours/account.js
  addons/account/tests/test_account_invoice_report.py
  addons/account/wizard/account_move_send.py
  addons/calendar/models/res_users.py
  addons/calendar/tests/test_access_rights.py
  addons/hr_holidays/report/hr_leave_report_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/tests/discuss/core/composer.test.js
  addons/mail/static/tests/discuss/typing/typing.test.js
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/point_of_sale/static/src/customer_display/customer_display_data_service.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_loyalty/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin.test.js
  addons/stock/models/stock_quant.py
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/list_controller.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: staging.saas-17.4

#30185 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/webclient/actions/reports/report.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/base_style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  doc/cla/individual/mostafaala2.md
Labels: staging.16.0

#30186 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/mail/static/tests/discuss/typing/typing_tests.js
  addons/product/views/product_views.xml
  addons/sale/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: staging.17.0

#30189 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/l10n_ec/models/template_ec.py
  addons/l10n_ec_stock/__init__.py
  addons/l10n_ec_stock/__manifest__.py
  addons/l10n_ec_stock/models/__init__.py
  addons/l10n_ec_stock/models/account_chart_template.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_loyalty/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/list_controller.xml
  addons/website_sale_product_configurator/controllers/main.py
  addons/website_sale_product_configurator/static/src/js/sale_product_configurator_modal.js
  doc/cla/corporate/forgeflow.md
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: tmp.saas-17.2

#30190 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/i18n/account.pot
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_report.py
  addons/account/report/account_invoice_report.py
  addons/account/static/src/js/tours/account.js
  addons/account/tests/test_account_invoice_report.py
  addons/account/wizard/account_move_send.py
  addons/calendar/models/res_users.py
  addons/calendar/tests/test_access_rights.py
  addons/hr_holidays/report/hr_leave_report_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/mail/static/src/discuss/typing/common/composer_patch.js
  addons/mail/static/tests/discuss/core/composer.test.js
  addons/mail/static/tests/discuss/typing/typing.test.js
  addons/mrp/wizard/product_replenish.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/point_of_sale/static/src/customer_display/customer_display_data_service.js
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_loyalty/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/purchase_stock/wizard/product_replenish.py
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin.test.js
  addons/stock/models/stock_quant.py
  addons/web/static/src/core/tooltip/tooltip_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/list_controller.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: tmp.saas-17.4

#30192 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_send.py
  addons/account/wizard/account_move_send.py
  addons/mail/static/tests/discuss/typing/typing_tests.js
  addons/product/views/product_views.xml
  addons/sale/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/security/base_security.xml
Labels: tmp.17.0

#30194 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/company.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/models/res_partner.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/fr_BE.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerDetailsEdit.js
  addons/stock/report/picking_templates.xml
  addons/stock_account/models/account_move.py
  addons/website_forum/static/src/js/website_forum.share.js
  doc/cla/corporate/codeforward.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: 16.0

#30195 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/hr/models/res_partner.py
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/mrp/wizard/mrp_workcenter_block_view.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/static/src/fields/stock_move_line_x2_many_field.js
  addons/stock/static/tests/tours/stock_picking_tour.js
  addons/stock/tests/test_picking_tours.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: 17.0

#30196 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_send.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/report/hr_leave_report_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/pos_restaurant/static/src/overrides/components/navbar/navbar.js
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.scss
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/column_width_hook.js
  addons/web/static/src/views/list/list_arch_parser.js
  addons/web/static/src/views/utils.js
  addons/web/static/tests/core/components/datetime/datetime_input.test.js
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web/static/tests/core/datetime/datetime_test_helpers.js
  addons/web/static/tests/core/domain_selector/domain_selector.test.js
  addons/web/static/tests/views/calendar/calendar_date_picker.test.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/one2many_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/fields/remaining_days_field.test.js
  addons/web/static/tests/views/list/column_widths.test.js
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/rng/common.rng
  odoo/addons/base/security/base_security.xml
Labels: 18.0

#30198 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_ch/report/swissqr_report.xml
  addons/mrp/models/mrp_production.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/views/product_views.xml
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-17.2

#30199 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/mail_message.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_audit_trail.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_it_edi/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/models/product_tag.py
  addons/point_of_sale/static/src/app/models/pos_order_line.js
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/chrome_tour.js
  addons/point_of_sale/static/tests/unit/related_models_test.js
  addons/pos_event/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/components/partner_line/partner_line.js
  addons/pos_loyalty/static/src/overrides/components/partner_line/partner_line.xml
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/src/app/product_screen/order_summary/order_summary.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_self_order/static/src/overrides/models/pos_store.js
  addons/product/models/product_pricelist_item.py
  addons/product/views/product_views.xml
  addons/sale/controllers/product_configurator.py
  addons/sale/models/sale_order_line.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website_sale/controllers/product_configurator.py
  addons/website_sale/models/__init__.py
  addons/website_sale/models/product_pricelist_item.py
  addons/website_sale/models/product_template.py
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/tests/test_website_sale_configurator.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/tests/test_website_sale_show_compare_list_price.py
  addons/website_sale/views/templates.xml
  doc/cla/corporate/forgeflow.md
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
Labels: saas-17.4

#30202 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/mail_message.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_audit_trail.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_it_edi/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/models/product_tag.py
  addons/point_of_sale/static/src/app/models/pos_order_line.js
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/chrome_tour.js
  addons/point_of_sale/static/tests/unit/related_models_test.js
  addons/pos_event/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/components/partner_line/partner_line.js
  addons/pos_loyalty/static/src/overrides/components/partner_line/partner_line.xml
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/src/app/product_screen/order_summary/order_summary.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_self_order/static/src/overrides/models/pos_store.js
  addons/product/models/product_pricelist_item.py
  addons/product/views/product_views.xml
  addons/sale/controllers/product_configurator.py
  addons/sale/models/sale_order_line.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website_sale/controllers/product_configurator.py
  addons/website_sale/models/__init__.py
  addons/website_sale/models/product_pricelist_item.py
  addons/website_sale/models/product_template.py
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/tests/test_website_sale_configurator.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/tests/test_website_sale_show_compare_list_price.py
  addons/website_sale/views/templates.xml
  doc/cla/corporate/forgeflow.md
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.saas-17.4

#30203 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/company.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/models/res_partner.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/fr_BE.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerDetailsEdit.js
  addons/stock/report/picking_templates.xml
  addons/stock_account/models/account_move.py
  addons/website_forum/static/src/js/website_forum.share.js
  doc/cla/corporate/codeforward.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: staging.16.0

#30204 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/hr/models/res_partner.py
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/mrp/wizard/mrp_workcenter_block_view.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/static/src/fields/stock_move_line_x2_many_field.js
  addons/stock/static/tests/tours/stock_picking_tour.js
  addons/stock/tests/test_picking_tours.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: staging.17.0

#30205 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_send.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/report/hr_leave_report_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/pos_restaurant/static/src/overrides/components/navbar/navbar.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.scss
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/column_width_hook.js
  addons/web/static/src/views/list/list_arch_parser.js
  addons/web/static/src/views/utils.js
  addons/web/static/tests/core/components/datetime/datetime_input.test.js
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web/static/tests/core/datetime/datetime_test_helpers.js
  addons/web/static/tests/core/domain_selector/domain_selector.test.js
  addons/web/static/tests/views/calendar/calendar_date_picker.test.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/one2many_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/fields/remaining_days_field.test.js
  addons/web/static/tests/views/list/column_widths.test.js
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/rng/common.rng
Labels: staging.18.0

#30207 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/security/hr_holidays_security.xml
  addons/l10n_ch/report/swissqr_report.xml
  addons/mrp/models/mrp_production.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/views/product_views.xml
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-17.2

#30208 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/mail_message.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_audit_trail.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_it_edi/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mrp/static/src/components/bom_overview/mrp_bom_overview.js
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/models/product_tag.py
  addons/point_of_sale/static/src/app/models/pos_order_line.js
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/chrome_tour.js
  addons/point_of_sale/static/tests/unit/related_models_test.js
  addons/pos_event/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/components/partner_line/partner_line.js
  addons/pos_loyalty/static/src/overrides/components/partner_line/partner_line.xml
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/src/app/product_screen/order_summary/order_summary.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_self_order/static/src/overrides/models/pos_store.js
  addons/product/models/product_pricelist_item.py
  addons/product/views/product_views.xml
  addons/sale/controllers/product_configurator.py
  addons/sale/models/sale_order_line.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website_sale/controllers/product_configurator.py
  addons/website_sale/models/__init__.py
  addons/website_sale/models/product_pricelist_item.py
  addons/website_sale/models/product_template.py
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/tests/test_website_sale_configurator.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
  addons/website_sale/tests/test_website_sale_show_compare_list_price.py
  addons/website_sale/views/templates.xml
  doc/cla/corporate/forgeflow.md
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.saas-17.4

#30209 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/company.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr/models/res_partner.py
  addons/l10n_ar/i18n/es.po
  addons/l10n_ar/i18n/fr_BE.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar_website_sale/i18n/es.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerDetailsEdit.js
  addons/stock/report/picking_templates.xml
  addons/stock_account/models/account_move.py
  addons/website_forum/static/src/js/website_forum.share.js
  doc/cla/corporate/codeforward.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: tmp.16.0

#30210 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/hr/models/res_partner.py
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/mrp/wizard/mrp_workcenter_block_view.xml
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move_line.py
  addons/stock/static/src/fields/stock_move_line_x2_many_field.js
  addons/stock/static/tests/tours/stock_picking_tour.js
  addons/stock/tests/test_picking_tours.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tests/test_ui.py
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: tmp.17.0

#30211 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_send.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/report/hr_leave_report_calendar.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/pos_restaurant/static/src/overrides/components/navbar/navbar.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.scss
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/list/column_width_hook.js
  addons/web/static/src/views/list/list_arch_parser.js
  addons/web/static/src/views/utils.js
  addons/web/static/tests/core/components/datetime/datetime_input.test.js
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web/static/tests/core/datetime/datetime_test_helpers.js
  addons/web/static/tests/core/domain_selector/domain_selector.test.js
  addons/web/static/tests/views/calendar/calendar_date_picker.test.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/one2many_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/fields/remaining_days_field.test.js
  addons/web/static/tests/views/list/column_widths.test.js
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_sale/static/src/js/website_sale_recently_viewed.js
  doc/cla/individual/mostafaala2.md
  odoo/addons/base/rng/common.rng
Labels: tmp.18.0

#30213 Syncing from upstream odoo/odoo (17.0)
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar_pos/i18n/es_419.po
  addons/l10n_ar_pos/i18n/l10n_ar_pos.pot
  addons/l10n_ar_website_sale/i18n/es_419.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_withholding/i18n/es_419.po
  addons/l10n_ar_withholding/i18n/l10n_ar_withholding.pot
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: 17.0

#30215 Syncing from upstream odoo/odoo (master)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  doc/cla/corporate/odootech.md
Labels: master

#30216 Syncing from upstream odoo/odoo (saas-17.2)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: saas-17.2

#30217 Syncing from upstream odoo/odoo (saas-17.4)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: saas-17.4

#30218 Syncing from upstream odoo/odoo (staging.master)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  doc/cla/corporate/odootech.md
Labels: staging.master

#30219 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: staging.saas-17.2

#30220 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: staging.saas-17.4

#30221 Syncing from upstream odoo/odoo (staging.17.0)
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar_pos/i18n/es_419.po
  addons/l10n_ar_pos/i18n/l10n_ar_pos.pot
  addons/l10n_ar_website_sale/i18n/es_419.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_withholding/i18n/es_419.po
  addons/l10n_ar_withholding/i18n/l10n_ar_withholding.pot
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: staging.17.0

#30222 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/tests/test_account_merge_wizard.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/account_payment.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/models/res_company.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/tests/test_expenses_states.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/html_editor/static/src/core/overlay.js
  addons/html_editor/static/src/core/overlay_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/l10n_ch/report/swissqr_report.xml
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/mail/i18n/mail.pot
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_binary.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/discuss/core/public/welcome_page.js
  addons/mail/views/mail_activity_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/mrp_repair/models/repair.py
  addons/mrp_repair/tests/__init__.py
  addons/mrp_repair/tests/test_mrp_repair_flow.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/views/pos_payment_method_views.xml
  addons/pos_discount/__manifest__.py
  addons/pos_discount/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_discount/static/tests/tours/global_discount_tour.js
  addons/pos_discount/tests/__init__.py
  addons/pos_discount/tests/test_frontend.py
  addons/purchase_repair/models/repair_order.py
  addons/purchase_repair/tests/__init__.py
  addons/purchase_repair/tests/test_repair_purchase_flow.py
  addons/repair/models/repair.py
  addons/repair/models/stock_move.py
  addons/repair/tests/test_rules_installation.py
  addons/stock/models/stock_move.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/tests/config/16.0.conf
  odoo/addons/base/tests/config/cli
  odoo/addons/base/tests/config/non_default.conf
  odoo/addons/base/tests/test_configmanager.py
  odoo/addons/base/wizard/base_partner_merge.py
Labels: staging.18.0

#30223 Syncing from upstream odoo/odoo (tmp.master)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  doc/cla/corporate/odootech.md
Labels: tmp.master

#30224 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: tmp.saas-17.2

#30225 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/tests/test_file_generation.py
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: tmp.saas-17.4

#30226 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar_pos/i18n/es_419.po
  addons/l10n_ar_pos/i18n/l10n_ar_pos.pot
  addons/l10n_ar_website_sale/i18n/es_419.po
  addons/l10n_ar_website_sale/i18n/l10n_ar_website_sale.pot
  addons/l10n_ar_withholding/i18n/es_419.po
  addons/l10n_ar_withholding/i18n/l10n_ar_withholding.pot
  doc/cla/corporate/codeforward.md
  doc/cla/corporate/odootech.md
Labels: tmp.17.0

#30228 Syncing from upstream odoo/odoo (17.0)
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/thread_model.js
  addons/test_discuss_full/tests/test_performance.py
Labels: 17.0

#30229 Syncing from upstream odoo/odoo (18.0)
  addons/calendar/models/res_users.py
  addons/calendar/tests/test_access_rights.py
  addons/sale_pdf_quote_builder/__manifest__.py
  addons/sale_pdf_quote_builder/models/quotation_document.py
  addons/sale_pdf_quote_builder/models/sale_order.py
  addons/sale_pdf_quote_builder/models/sale_order_template.py
  addons/sale_pdf_quote_builder/security/ir_rules.xml
  addons/sale_pdf_quote_builder/views/quotation_document_views.xml
Labels: 18.0

#30230 Syncing from upstream odoo/odoo (master)
  addons/bus/controllers/websocket.py
  addons/bus/models/ir_websocket.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/tests/legacy/helpers/mock_server.js
  addons/bus/static/tests/legacy/helpers/mock_server/models/ir_websocket.js
  addons/bus/static/tests/mock_server/mock_models/bus_bus.js
  addons/bus/static/tests/mock_server/mock_models/ir_websocket.js
  addons/calendar/models/res_users.py
  addons/calendar/tests/test_access_rights.py
  addons/hr_presence/models/ir_websocket.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/models/mail_thread.py
  addons/mail/static/tests/mock_server/mock_models/ir_websocket.js
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.scss
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/tests/core/components/datetime/datetime_input.test.js
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web/static/tests/core/datetime/datetime_test_helpers.js
  addons/web/static/tests/core/domain_selector/domain_selector.test.js
  addons/web/static/tests/views/calendar/calendar_date_picker.test.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/one2many_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/fields/remaining_days_field.test.js
  addons/web/static/tests/views/list/list_view.test.js
Labels: master

#30231 Syncing from upstream odoo/odoo (saas-17.2)
  addons/l10n_es_edi_tbai/data/template_invoice.xml
Labels: saas-17.2

#30233 Syncing from upstream odoo/odoo (staging.master)
  addons/bus/controllers/websocket.py
  addons/bus/models/ir_websocket.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/tests/legacy/helpers/mock_server.js
  addons/bus/static/tests/legacy/helpers/mock_server/models/ir_websocket.js
  addons/bus/static/tests/mock_server/mock_models/bus_bus.js
  addons/bus/static/tests/mock_server/mock_models/ir_websocket.js
  addons/hr_presence/models/ir_websocket.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/models/mail_thread.py
  addons/mail/static/tests/mock_server/mock_models/ir_websocket.js
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.scss
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/tests/core/components/datetime/datetime_input.test.js
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web/static/tests/core/datetime/datetime_test_helpers.js
  addons/web/static/tests/core/domain_selector/domain_selector.test.js
  addons/web/static/tests/views/calendar/calendar_date_picker.test.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/one2many_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/fields/remaining_days_field.test.js
  addons/web/static/tests/views/list/list_view.test.js
Labels: staging.master

#30234 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/l10n_es_edi_tbai/data/template_invoice.xml
Labels: staging.saas-17.2

#30238 Syncing from upstream odoo/odoo (tmp.master)
  addons/bus/controllers/websocket.py
  addons/bus/models/ir_websocket.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/tests/legacy/helpers/mock_server.js
  addons/bus/static/tests/legacy/helpers/mock_server/models/ir_websocket.js
  addons/bus/static/tests/mock_server/mock_models/bus_bus.js
  addons/bus/static/tests/mock_server/mock_models/ir_websocket.js
  addons/hr_presence/models/ir_websocket.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/models/mail_thread.py
  addons/mail/static/tests/mock_server/mock_models/ir_websocket.js
  addons/web/static/src/core/datetime/datetime_picker.js
  addons/web/static/src/core/datetime/datetime_picker.scss
  addons/web/static/src/core/datetime/datetime_picker.xml
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/tests/core/components/datetime/datetime_input.test.js
  addons/web/static/tests/core/components/datetime/datetime_picker.test.js
  addons/web/static/tests/core/datetime/datetime_test_helpers.js
  addons/web/static/tests/core/domain_selector/domain_selector.test.js
  addons/web/static/tests/views/calendar/calendar_date_picker.test.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/one2many_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/fields/remaining_days_field.test.js
  addons/web/static/tests/views/list/list_view.test.js
Labels: tmp.master

#30239 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/l10n_es_edi_tbai/data/template_invoice.xml
Labels: tmp.saas-17.2

#30241 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/thread_model.js
  addons/test_discuss_full/tests/test_performance.py
Labels: tmp.17.0

#30243 [FIX] auth_oauth: make token non-prefetch
  addons/auth_oauth/models/res_users.py
Labels: 16.0.project_ls_465

#30246 Syncing from upstream odoo/odoo (18.0)
  addons/mail/static/src/discuss/gif_picker/common/gif_picker.xml
  addons/mail/static/tests/gif_picker/gif_picker.test.js
  addons/payment_worldline/__manifest__.py
  addons/payment_worldline/models/payment_transaction.py
  addons/payment_worldline/static/src/js/payment_form.js
  addons/pos_restaurant/static/src/app/control_buttons/control_buttons.js
  addons/product/views/product_views.xml
  addons/spreadsheet/static/src/chart/plugins/odoo_chart_ui_plugin.js
  addons/spreadsheet/static/tests/charts/model/odoo_chart_plugin.test.js
  addons/stock/models/stock_quant.py
  addons/website_sale/views/templates.xml
Labels: 18.0
