Repository brain-tec/odoo, pull requests merged in 2024-01, with the labels that each got.

#25493 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi_ubl_cii/i18n/zh_TW.po
  addons/base_address_extended/i18n/es.po
  addons/digest/i18n/zh_TW.po
  addons/fleet/i18n/es_MX.po
  addons/gamification/i18n/es_MX.po
  addons/hr_contract/i18n/fr.po
  addons/mail_group/i18n/es_MX.po
  addons/mass_mailing_sms/i18n/fr.po
  addons/payment_payumoney/i18n/es.po
  addons/point_of_sale/i18n/es.po
  addons/sale_stock/i18n/es.po
  addons/uom/i18n/es.po
  addons/website_event_booth/i18n/es_MX.po
  addons/website_slides/i18n/es_MX.po
  addons/website_slides_survey/i18n/es_MX.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
Labels: saas-15.2

#25499 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/web/static/tests/legacy/views/pivot_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
Labels: 15.0

#25500 Syncing from upstream odoo/odoo (16.0)
  addons/hr/views/res_config_settings_views.xml
  addons/hr_holidays/models/hr_leave.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_loyalty/i18n/pos_loyalty.pot
  addons/pos_loyalty/static/src/js/ControlButtons/eWalletButton.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/EWalletProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web/static/tests/views/pivot_view_tests.js
  addons/web_editor/__manifest__.py
Labels: 16.0

#25502 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/__init__.py
  addons/account/tests/common.py
  addons/account/tests/test_account_all_l10n.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_unexpected_invoice.py
  addons/account/views/account_move_views.xml
  addons/account/views/partner_view.xml
  addons/account/wizard/account_validate_account_move.py
  addons/account/wizard/account_validate_move_view.xml
  addons/bus/static/src/workers/websocket_worker.js
  addons/bus/static/tests/bus_tests.js
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/im_livechat/static/src/views/discuss_channel_list/discuss_channel_list_view_controller.js
  addons/mail/controllers/discuss/channel.py
  addons/mail/controllers/discuss/rtc.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/static/src/core/common/chat_window_model.js
  addons/mail/static/src/core/common/chat_window_service.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/common/thread_service.js
  addons/mail/static/src/core/web/chat_window_service_patch.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/src/discuss/core/common/channel_member_list.js
  addons/mrp/models/stock_move.py
  addons/mrp/static/src/widgets/mrp_consumed.js
  addons/mrp/static/tests/tours/mrp_manual_consumption.js
  addons/mrp/tests/test_manual_consumption.py
  addons/mrp/views/mrp_production_views.xml
  addons/pos_adyen/models/pos_payment_method.py
  addons/project/static/src/views/project_rating_graph/project_rating_graph_view.js
  addons/project/static/src/views/project_rating_pivot/project_rating_pivot_view.js
  addons/rating/views/rating_rating_views.xml
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
  addons/web/static/tests/views/pivot_view_tests.js
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/tests/common.py
Labels: master

#25503 Syncing from upstream odoo/odoo (saas-15.2)
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/web/static/tests/legacy/views/pivot_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
Labels: saas-15.2

#25504 Syncing from upstream odoo/odoo (saas-16.1)
  addons/web/static/tests/views/pivot_view_tests.js
Labels: saas-16.1

#25505 Syncing from upstream odoo/odoo (saas-16.2)
  addons/hr_holidays/models/hr_leave.py
  addons/web/static/tests/views/pivot_view_tests.js
Labels: saas-16.2

#25506 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/tests/test_account_all_l10n.py
  addons/hr_holidays/models/hr_leave.py
  addons/web/static/tests/views/pivot_view_tests.js
Labels: saas-16.3

#25507 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/tests/test_account_all_l10n.py
  addons/web/static/tests/views/pivot_view_tests.js
Labels: saas-16.4

#25509 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/account_edi_ubl_cii/i18n/zh_TW.po
  addons/base_address_extended/i18n/es.po
  addons/digest/i18n/zh_TW.po
  addons/fleet/i18n/es_MX.po
  addons/gamification/i18n/es_MX.po
  addons/hr_contract/i18n/fr.po
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail_group/i18n/es_MX.po
  addons/mass_mailing_sms/i18n/fr.po
  addons/payment_payumoney/i18n/es.po
  addons/point_of_sale/i18n/es.po
  addons/sale_stock/i18n/es.po
  addons/uom/i18n/es.po
  addons/web/static/tests/legacy/views/pivot_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/website_event_booth/i18n/es_MX.po
  addons/website_slides/i18n/es_MX.po
  addons/website_slides_survey/i18n/es_MX.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
Labels: staging.saas-15.2

#25510 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/web/static/tests/views/pivot_view_tests.js
Labels: staging.saas-16.1

#25511 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/hr_holidays/models/hr_leave.py
  addons/web/static/tests/views/pivot_view_tests.js
Labels: staging.saas-16.2

#25517 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/account/tests/__init__.py
  addons/account/tests/common.py
  addons/account/tests/test_account_all_l10n.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/tests/test_unexpected_invoice.py
  addons/account/views/account_move_views.xml
  addons/account/views/partner_view.xml
  addons/account/wizard/account_validate_account_move.py
  addons/account/wizard/account_validate_move_view.xml
  addons/bus/static/src/workers/websocket_worker.js
  addons/bus/static/tests/bus_tests.js
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/im_livechat/static/src/views/discuss_channel_list/discuss_channel_list_view_controller.js
  addons/mail/controllers/discuss/channel.py
  addons/mail/controllers/discuss/rtc.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/static/src/core/common/chat_window_model.js
  addons/mail/static/src/core/common/chat_window_service.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/common/thread_service.js
  addons/mail/static/src/core/web/chat_window_service_patch.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/src/discuss/core/common/channel_member_list.js
  addons/mrp/models/stock_move.py
  addons/mrp/static/src/widgets/mrp_consumed.js
  addons/mrp/static/tests/tours/mrp_manual_consumption.js
  addons/mrp/tests/test_manual_consumption.py
  addons/mrp/views/mrp_production_views.xml
  addons/pos_adyen/models/pos_payment_method.py
  addons/project/static/src/views/project_rating_graph/project_rating_graph_view.js
  addons/project/static/src/views/project_rating_pivot/project_rating_pivot_view.js
  addons/rating/views/rating_rating_views.xml
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
  addons/web/static/tests/views/pivot_view_tests.js
  odoo/addons/test_testing_utilities/tests/test_methods.py
  odoo/tests/common.py
Labels: tmp.master

#25518 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi_ubl_cii/i18n/zh_TW.po
  addons/base_address_extended/i18n/es.po
  addons/digest/i18n/zh_TW.po
  addons/fleet/i18n/es_MX.po
  addons/gamification/i18n/es_MX.po
  addons/hr_contract/i18n/fr.po
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail_group/i18n/es_MX.po
  addons/mass_mailing_sms/i18n/fr.po
  addons/payment_payumoney/i18n/es.po
  addons/point_of_sale/i18n/es.po
  addons/sale_stock/i18n/es.po
  addons/uom/i18n/es.po
  addons/web/static/tests/legacy/views/pivot_tests.js
  addons/web/static/tests/views/pivot_view_tests.js
  addons/website_event_booth/i18n/es_MX.po
  addons/website_slides/i18n/es_MX.po
  addons/website_slides_survey/i18n/es_MX.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
Labels: tmp.saas-15.2

#25526 Syncing from upstream odoo/odoo (14.0)
  addons/web/static/tests/views/pivot_tests.js
Labels: 14.0

#25527 Syncing from upstream odoo/odoo (15.0)
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: 15.0

#25528 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: 16.0

#25531 Syncing from upstream odoo/odoo (saas-15.2)
  addons/web_editor/__manifest__.py
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: saas-15.2

#25532 Syncing from upstream odoo/odoo (saas-16.1)
  addons/hr/views/res_config_settings_views.xml
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/static/tests/qunit_suite_tests/components/thread_view_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_sale/models/pos_order.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: saas-16.1

#25533 Syncing from upstream odoo/odoo (saas-16.2)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/static/tests/qunit_suite_tests/components/persona_im_status_icon_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/thread_view_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_restaurant/models/pos_config.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: saas-16.2

#25534 Syncing from upstream odoo/odoo (saas-16.3)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale_stock/report/stock_forecasted.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_report.py
  addons/stock_account/models/account_chart_template.py
  addons/stock_account/models/product.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum_post.py
  addons/website_forum/tests/test_forum_internals.py
Labels: saas-16.3

#25535 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_tax.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/static/tests/tours/website_form_editor_frontend.js
  addons/website/tests/test_website_form_editor.py
  addons/website/tools.py
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
Labels: saas-16.4

#25537 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/web_editor/__manifest__.py
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: staging.saas-15.2

#25538 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/hr/views/res_config_settings_views.xml
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/static/tests/qunit_suite_tests/components/thread_view_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_sale/models/pos_order.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: staging.saas-16.1

#25539 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/static/tests/qunit_suite_tests/components/persona_im_status_icon_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/thread_view_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_restaurant/models/pos_config.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: staging.saas-16.2

#25544 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: staging.16.0

#25547 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/web_editor/__manifest__.py
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: tmp.saas-15.2

#25548 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/hr/views/res_config_settings_views.xml
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/static/tests/qunit_suite_tests/components/thread_view_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_sale/models/pos_order.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: tmp.saas-16.1

#25549 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/static/tests/qunit_suite_tests/components/persona_im_status_icon_tests.js
  addons/mail/static/tests/qunit_suite_tests/components/thread_view_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_restaurant/models/pos_config.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: tmp.saas-16.2

#25550 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/sale_stock/report/stock_forecasted.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_report.py
  addons/stock_account/models/account_chart_template.py
  addons/stock_account/models/product.py
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_forum/models/forum_post.py
  addons/website_forum/tests/test_forum_internals.py
Labels: tmp.saas-16.3

#25551 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_tax.py
  addons/barcodes/static/src/js/barcode_parser.js
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr/views/hr_employee_views.xml
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/form/button_box/button_box.scss
  addons/web_editor/__manifest__.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/utils.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/static/tests/tours/website_form_editor_frontend.js
  addons/website/tests/test_website_form_editor.py
  addons/website/tools.py
  addons/website_cf_turnstile/__manifest__.py
  addons/website_cf_turnstile/static/src/js/error_handler.js
  addons/website_cf_turnstile/static/src/js/turnstile.js
Labels: tmp.saas-16.4

#25553 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
Labels: tmp.15.0

#25554 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_forum/models/forum.py
  addons/website_forum/tests/test_forum.py
Labels: tmp.16.0

#25557 Syncing from upstream odoo/odoo (14.0)
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
Labels: 14.0

#25558 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.js
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/data/res.country.state.csv
Labels: 15.0

#25559 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/account_tax_group_data.xml
  addons/l10n_cz/migrations/1.1/end-migrate_update_taxes.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  odoo/addons/base/data/res.country.state.csv
Labels: 16.0

#25562 Syncing from upstream odoo/odoo (saas-15.2)
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/tests/test_sale_margin.py
  odoo/addons/base/data/res.country.state.csv
Labels: saas-15.2

#25563 Syncing from upstream odoo/odoo (saas-16.1)
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: saas-16.1

#25564 Syncing from upstream odoo/odoo (saas-16.2)
  addons/hr/views/res_config_settings_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: saas-16.2

#25565 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/views/report_invoice.xml
  addons/hr/views/res_config_settings_views.xml
  addons/mail/static/src/web/suggested_recipient.js
  addons/mail/static/src/web/thread_service_patch.js
  addons/mail/static/tests/composer/suggested_recipients_test.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale/views/sale_portal_templates.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/domain_selector_dialog/domain_selector_dialog.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: saas-16.3

#25566 Syncing from upstream odoo/odoo (saas-16.4)
  addons/hr/views/res_config_settings_views.xml
  addons/mail/static/tests/discuss_app/im_status_tests.js
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/purchase_stock/wizard/product_replenish.py
  addons/sale/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/survey/views/survey_templates_statistics.xml
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_forum/models/forum_post.py
  addons/website_forum/tests/test_forum_internals.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: saas-16.4

#25568 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/tests/test_sale_margin.py
  odoo/addons/base/data/res.country.state.csv
Labels: staging.saas-15.2

#25569 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: staging.saas-16.1

#25570 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/hr/views/res_config_settings_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: staging.saas-16.2

#25573 Syncing from upstream odoo/odoo (staging.14.0)
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
Labels: staging.14.0

#25578 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_margin/models/sale_order.py
  addons/sale_margin/tests/test_sale_margin.py
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.saas-15.2

#25579 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.saas-16.1

#25580 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/hr/views/res_config_settings_views.xml
  addons/mrp/views/mrp_production_views.xml
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/views/fields/domain_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.saas-16.2

#25581 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/views/report_invoice.xml
  addons/hr/views/res_config_settings_views.xml
  addons/mail/static/src/web/suggested_recipient.js
  addons/mail/static/src/web/thread_service_patch.js
  addons/mail/static/tests/composer/suggested_recipients_test.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale/views/sale_portal_templates.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/domain_selector_dialog/domain_selector_dialog.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.saas-16.3

#25582 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/hr/views/res_config_settings_views.xml
  addons/mail/static/tests/discuss_app/im_status_tests.js
  addons/payment_mercado_pago/models/payment_transaction.py
  addons/payment_mercado_pago/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/purchase_stock/i18n/purchase_stock.pot
  addons/purchase_stock/wizard/product_replenish.py
  addons/sale/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/survey/views/survey_templates_statistics.xml
  addons/web/static/src/core/dialog/dialog_service.js
  addons/web/static/src/webclient/menus/menu_providers.js
  addons/web/static/tests/core/commands/menu_provider_tests.js
  addons/web/views/webclient_templates.xml
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/common/grid_layout_utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_dialog.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_editor/static/tests/html_field_tests.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_forum/models/forum_post.py
  addons/website_forum/tests/test_forum_internals.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.saas-16.4

#25583 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
Labels: tmp.14.0

#25584 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.js
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  doc/cla/corporate/vauxoo.md
  odoo/addons/base/data/res.country.state.csv
Labels: tmp.15.0

#25587 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move_line_tax_details.py
  addons/base_vat/models/res_partner.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/website_event/views/event_templates_page_registration.xml
Labels: 15.0

#25588 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ar/models/account_fiscal_position.py
  addons/mrp/models/mrp_production.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page_registration.xml
  doc/cla/corporate/vauxoo.md
Labels: 16.0

#25591 Syncing from upstream odoo/odoo (saas-15.2)
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.js
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  doc/cla/corporate/vauxoo.md
Labels: saas-15.2

#25592 Syncing from upstream odoo/odoo (saas-16.1)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/purchase/models/product.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: saas-16.1

#25593 Syncing from upstream odoo/odoo (saas-16.2)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/purchase/models/product.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: saas-16.2

#25594 Syncing from upstream odoo/odoo (saas-16.3)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/resource/models/resource_calendar.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/float/float_field.js
  addons/web/static/src/views/fields/float_toggle/float_toggle_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: saas-16.3

#25595 Syncing from upstream odoo/odoo (saas-16.4)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: saas-16.4

#25597 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.js
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  doc/cla/corporate/vauxoo.md
Labels: staging.saas-15.2

#25603 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ar/models/account_fiscal_position.py
  addons/mrp/models/mrp_production.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page_registration.xml
  doc/cla/corporate/vauxoo.md
Labels: staging.16.0

#25606 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.js
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-15.2

#25607 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/purchase/models/product.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-16.1

#25608 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/purchase/models/product.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-16.2

#25609 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/resource/models/resource_calendar.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/float/float_field.js
  addons/web/static/src/views/fields/float_toggle/float_toggle_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-16.3

#25610 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_margin/tests/test_sale_margin.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/web/static/src/core/utils/ui.js
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/core/ui_service_tests.js
  addons/web/static/tests/mock_server_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/static/tests/tours/snippet_images_wall.js
  doc/cla/corporate/adhoc.md
  doc/cla/corporate/vauxoo.md
Labels: tmp.saas-16.4

#25611 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move_line_tax_details.py
  addons/base_vat/models/res_partner.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/website_event/views/event_templates_page_registration.xml
Labels: tmp.15.0

#25612 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/partner.py
  addons/base_vat/models/res_partner.py
  addons/hr_holidays_attendance/static/src/xml/time_off_calendar.xml
  addons/l10n_ar/models/account_fiscal_position.py
  addons/mrp/models/mrp_production.py
  addons/pos_adyen/controllers/main.py
  addons/pos_adyen/models/pos_payment_method.py
  addons/pos_adyen/static/src/js/payment_adyen.js
  addons/pos_adyen/views/pos_payment_method_views.xml
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web/static/src/legacy/scss/name_and_signature.scss
  addons/web/static/src/legacy/xml/name_and_signature.xml
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_event/views/event_templates_list.xml
  addons/website_event/views/event_templates_page_registration.xml
  doc/cla/corporate/vauxoo.md
Labels: tmp.16.0

#25619 Syncing from upstream odoo/odoo (saas-16.2)
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/account_tax_group_data.xml
  addons/l10n_cz/migrations/1.1/end-migrate_update_taxes.py
Labels: saas-16.2

#25620 Syncing from upstream odoo/odoo (saas-16.3)
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
Labels: saas-16.3

#25624 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/account_tax_group_data.xml
  addons/l10n_cz/migrations/1.1/end-migrate_update_taxes.py
Labels: staging.saas-16.2

#25628 Syncing from upstream odoo/odoo (tmp.master)
  addons/base_vat/models/res_partner.py
Labels: tmp.master

#25629 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/account_tax_group_data.xml
  addons/l10n_cz/migrations/1.1/end-migrate_update_taxes.py
Labels: tmp.saas-16.2

#25630 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
Labels: tmp.saas-16.3

#25631 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
Labels: tmp.saas-16.4

#25633 Syncing from upstream odoo/odoo (17.0)
  addons/base_vat/models/res_partner.py
Labels: 17.0

#25634 Syncing from upstream odoo/odoo (master)
  addons/base_vat/models/res_partner.py
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
Labels: master

#25638 Syncing from upstream odoo/odoo (saas-16.4)
  addons/website_event/views/event_templates_list.xml
Labels: saas-16.4

#25645 Syncing from upstream odoo/odoo (tmp.master)
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
Labels: tmp.master

#25652 Syncing from upstream odoo/odoo (15.0)
  addons/mass_mailing/models/mailing.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
Labels: 15.0

#25656 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mass_mailing/models/mailing.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website_event/views/event_templates_page_registration.xml
Labels: saas-15.2

#25657 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/point_of_sale/static/src/js/Chrome.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: saas-16.1

#25658 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: saas-16.2

#25659 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/views/mrp_production_views.xml
  addons/pos_restaurant/models/pos_config.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase/models/product.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/sale_timesheet/models/account.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: saas-16.3

#25660 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/account_tax_group_data.xml
  addons/l10n_cz/migrations/1.1/end-migrate_update_taxes.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/web/chatter.js
  addons/mail/static/src/core/web/chatter.xml
  addons/mail/static/src/core/web/suggested_recipient.js
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/composer/suggested_recipients_test.js
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/views/mrp_production_views.xml
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/views/project_task_views.xml
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/resource/models/resource_calendar.py
  addons/sale_timesheet/models/account.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/domain_selector/domain_selector_fields.js
  addons/web/static/src/core/domain_selector/domain_selector_fields.xml
  addons/web/static/src/core/domain_selector_dialog/domain_selector_dialog.js
  addons/web/static/src/views/fields/float/float_field.js
  addons/web/static/src/views/fields/float_toggle/float_toggle_field.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/file_selector.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: saas-16.4

#25662 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/base_setup/i18n/zh_TW.po
  addons/hr/i18n/zh_TW.po
  addons/hr_work_entry_holidays/i18n/zh_TW.po
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/l10n_multilang/i18n/zh_TW.po
  addons/mail/i18n/de.po
  addons/mail/i18n/es.po
  addons/mail/i18n/es_MX.po
  addons/mail/i18n/fr.po
  addons/mail/i18n/it.po
  addons/mail/i18n/nl.po
  addons/mail/i18n/uk.po
  addons/mail/i18n/vi.po
  addons/mail/i18n/zh_CN.po
  addons/mail/i18n/zh_TW.po
  addons/mass_mailing/models/mailing.py
  addons/mrp/i18n/es_MX.po
  addons/mrp/i18n/zh_TW.po
  addons/portal/i18n/es_MX.po
  addons/stock/i18n/es_MX.po
  addons/survey/i18n/es_MX.po
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/i18n/es_MX.po
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/i18n/es_MX.po
  addons/website/i18n/zh_TW.po
  addons/website_crm/i18n/zh_TW.po
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_event_track_quiz/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
Labels: staging.saas-15.2

#25663 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/point_of_sale/static/src/js/Chrome.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: staging.saas-16.1

#25664 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: staging.saas-16.2

#25671 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_setup/i18n/zh_TW.po
  addons/hr/i18n/zh_TW.po
  addons/hr_work_entry_holidays/i18n/zh_TW.po
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/l10n_multilang/i18n/zh_TW.po
  addons/mail/i18n/de.po
  addons/mail/i18n/es.po
  addons/mail/i18n/es_MX.po
  addons/mail/i18n/fr.po
  addons/mail/i18n/it.po
  addons/mail/i18n/nl.po
  addons/mail/i18n/uk.po
  addons/mail/i18n/vi.po
  addons/mail/i18n/zh_CN.po
  addons/mail/i18n/zh_TW.po
  addons/mass_mailing/models/mailing.py
  addons/mrp/i18n/es_MX.po
  addons/mrp/i18n/zh_TW.po
  addons/portal/i18n/es_MX.po
  addons/stock/i18n/es_MX.po
  addons/survey/i18n/es_MX.po
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/i18n/es_MX.po
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/image_processing.js
  addons/web_editor/static/src/js/wysiwyg/widgets/media.js
  addons/website/i18n/es_MX.po
  addons/website/i18n/zh_TW.po
  addons/website_crm/i18n/zh_TW.po
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_event_track_quiz/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
Labels: tmp.saas-15.2

#25672 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/auth_signup/models/res_partner.py
  addons/auth_totp/models/res_users.py
  addons/auth_totp/views/res_users_views.xml
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/point_of_sale/static/src/js/Chrome.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/project/views/project_views.xml
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: tmp.saas-16.1

#25673 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/tours/mass_mailing_editor_tour.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project.py
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: tmp.saas-16.2

#25674 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/views/mrp_production_views.xml
  addons/pos_restaurant/models/pos_config.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase/models/product.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/sale_timesheet/models/account.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: tmp.saas-16.3

#25675 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/account.account.template.csv
  addons/l10n_cz/data/account_fiscal_position_data.xml
  addons/l10n_cz/data/account_tax_data.xml
  addons/l10n_cz/data/account_tax_group_data.xml
  addons/l10n_cz/migrations/1.1/end-migrate_update_taxes.py
  addons/l10n_in_edi/models/res_config_settings.py
  addons/l10n_in_edi/views/res_config_settings_views.xml
  addons/l10n_in_edi_ewaybill/models/res_config_settings.py
  addons/l10n_in_edi_ewaybill/views/res_config_settings_views.xml
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/web/chatter.js
  addons/mail/static/src/core/web/chatter.xml
  addons/mail/static/src/core/web/suggested_recipient.js
  addons/mail/static/src/core/web/thread_service_patch.js
  addons/mail/static/tests/composer/composer_tests.js
  addons/mail/static/tests/composer/suggested_recipients_test.js
  addons/mass_mailing/models/mailing.py
  addons/microsoft_calendar/models/calendar.py
  addons/mrp/views/mrp_production_views.xml
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/views/project_task_views.xml
  addons/purchase_stock/tests/test_purchase_order_process.py
  addons/resource/models/resource_calendar.py
  addons/sale_timesheet/models/account.py
  addons/stock_account/models/stock_move.py
  addons/test_mass_mailing/tests/test_mailing_statistics.py
  addons/web/static/src/core/domain_selector/domain_selector.js
  addons/web/static/src/core/domain_selector/domain_selector.xml
  addons/web/static/src/core/domain_selector/domain_selector_fields.js
  addons/web/static/src/core/domain_selector/domain_selector_fields.xml
  addons/web/static/src/core/domain_selector_dialog/domain_selector_dialog.js
  addons/web/static/src/views/fields/float/float_field.js
  addons/web/static/src/views/fields/float_toggle/float_toggle_field.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/file_selector.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_event/views/event_templates_page_registration.xml
  odoo/addons/base/models/res_users.py
  odoo/tools/translate.py
Labels: tmp.saas-16.4

#25678 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/base_import_module/views/ir_module_views.xml
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/calendar/views/calendar_views.xml
  addons/mail/models/mail_message.py
  addons/mail/static/tests/tours/discuss_channel_public_tour.js
  addons/mass_mailing/static/src/js/mailing_m2o_filter.js
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_stock.py
  addons/payment_razorpay/models/payment_transaction.py
  addons/resource/models/resource_calendar.py
  addons/web/static/src/views/fields/char/char_field.js
  addons/web/static/src/views/fields/state_selection/state_selection_field.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/tests/views/fields/state_selection_field_tests.js
  addons/web/static/tests/views/fields/statusbar_field_tests.js
  odoo/models.py
Labels: tmp.17.0

#25651 [FIX] web: format set_profiling output nicely
  addons/web/controllers/profiling.py
Labels: 15.0.project_gd_615

#25679 Syncing from upstream odoo/odoo (15.0)
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/point_of_sale/static/src/js/models.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/web/static/tests/legacy/views/list_tests.js
  odoo/addons/base/models/ir_rule.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: 15.0

#25680 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line_tax_details.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/res_config_settings.py
  addons/spreadsheet/static/src/global_filters/components/filter_date_value/filter_date_value.js
  addons/spreadsheet/static/src/global_filters/components/year_picker.js
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/js/backend/convert_inline.js
  odoo/tools/translate.py
Labels: 16.0

#25683 Syncing from upstream odoo/odoo (saas-15.2)
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
Labels: saas-15.2

#25686 Syncing from upstream odoo/odoo (saas-16.3)
  addons/calendar/static/src/scss/calendar.scss
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/mail/controllers/thread.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/web/message_patch.xml
  addons/mail_group/models/mail_group.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/mass_mailing/static/tests/tours/mass_mailing_editor_tour.js
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_session.py
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/components/chatter/chatter.scss
  addons/project/static/src/project_sharing/views/form/project_sharing_form_compiler.js
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/survey/static/src/scss/survey_templates_form.scss
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_renderer.js
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_sale/tests/test_delivery_controller.py
  addons/website_sale_stock/tests/__init__.py
  addons/website_sale_stock/tests/test_website_sale_stock_delivery.py
Labels: saas-16.3

#25687 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/calendar/static/src/scss/calendar.scss
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/mail/static/src/core/web/message_patch.xml
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_restaurant/models/pos_config.py
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/project/models/project_task.py
  addons/purchase/models/product.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/survey/static/src/scss/survey_templates_form.scss
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/domain_selector/utils.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_renderer.js
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_sale/tests/test_delivery_controller.py
  addons/website_sale_stock/tests/__init__.py
  addons/website_sale_stock/tests/test_website_sale_stock_delivery.py
Labels: saas-16.4

#25689 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
Labels: staging.saas-15.2

#25695 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move_line_tax_details.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/res_config_settings.py
  addons/spreadsheet/static/src/global_filters/components/filter_date_value/filter_date_value.js
  addons/spreadsheet/static/src/global_filters/components/year_picker.js
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/js/backend/convert_inline.js
  odoo/tools/translate.py
Labels: staging.16.0

#25698 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/point_of_sale/static/src/js/models.js
  addons/web/static/tests/legacy/views/list_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
Labels: tmp.saas-15.2

#25701 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/calendar/static/src/scss/calendar.scss
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/mail/controllers/thread.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/web/message_patch.xml
  addons/mail_group/models/mail_group.py
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/mass_mailing/static/tests/tours/mass_mailing_editor_tour.js
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_session.py
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/components/chatter/chatter.scss
  addons/project/static/src/project_sharing/views/form/project_sharing_form_compiler.js
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/survey/static/src/scss/survey_templates_form.scss
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_renderer.js
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_sale/tests/test_delivery_controller.py
  addons/website_sale_stock/tests/__init__.py
  addons/website_sale_stock/tests/test_website_sale_stock_delivery.py
Labels: tmp.saas-16.3

#25702 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/i18n/account.pot
  addons/calendar/static/src/scss/calendar.scss
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_pl_jpk/__manifest__.py
  addons/mail/static/src/core/web/message_patch.xml
  addons/mail_plugin/controllers/mail_plugin.py
  addons/mail_plugin/i18n/mail_plugin.pot
  addons/mail_plugin/tests/test_controller.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_restaurant/models/pos_config.py
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/project/models/project_task.py
  addons/purchase/models/product.py
  addons/purchase_stock/tests/__init__.py
  addons/purchase_stock/tests/test_purchase_method.py
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/survey/static/src/scss/survey_templates_form.scss
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/domain_selector/utils.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_renderer.js
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/core/domain_selector_tests.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/components/media_dialog/image_selector.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_popover_widget.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/lib/multirange/multirange_custom.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/homepage_edit_discard.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/static/tests/tours/website_no_dirty_page.js
  addons/website/tests/test_ui.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_sale/tests/test_delivery_controller.py
  addons/website_sale_stock/tests/__init__.py
  addons/website_sale_stock/tests/test_website_sale_stock_delivery.py
Labels: tmp.saas-16.4

#25703 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/point_of_sale/static/src/js/models.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/web/static/tests/legacy/views/list_tests.js
  odoo/addons/base/models/ir_rule.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: tmp.15.0

#25704 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line_tax_details.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/res_config_settings.py
  addons/spreadsheet/static/src/global_filters/components/filter_date_value/filter_date_value.js
  addons/spreadsheet/static/src/global_filters/components/year_picker.js
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/web/tooling/enable.sh
  addons/web_editor/static/src/js/backend/convert_inline.js
  odoo/tools/translate.py
Labels: tmp.16.0

#25705 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/tests/test_product.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/barcodes/static/src/js/barcode_parser.js
  addons/crm/tests/test_performances.py
  addons/l10n_ch/models/template_ch.py
  addons/l10n_ee/models/template_ee.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_basic_config.py
  addons/pos_discount/models/__init__.py
  addons/pos_discount/models/pos_config.py
  addons/pos_discount/models/pos_session.py
  addons/pos_online_payment/tests/test_frontend.py
  addons/pos_restaurant/static/src/overrides/components/receipt_screen/order_receipt/order_receipt.xml
  addons/pos_restaurant/static/src/overrides/models/models.js
  addons/pos_sale/models/pos_config.py
  addons/pos_sale/models/pos_session.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_move.py
  addons/survey/static/src/js/survey_result.js
  addons/web/controllers/webclient.py
  addons/web/static/src/legacy/js/public/public_root.js
  addons/web/static/src/model/relational_model/static_list.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/views/website_controller_pages_views.xml
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.17.0

#25706 Syncing from upstream odoo/odoo (15.0)
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_res_lang.py
Labels: 15.0

#25707 Syncing from upstream odoo/odoo (16.0)
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/crm/static/src/views/forecast_search_model.js
  addons/crm/static/tests/crm_rainbowman_tests.js
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/pos_loyalty/models/pos_order.py
  addons/pos_sale_loyalty/__manifest__.py
  addons/pos_sale_loyalty/static/src/tours/PosSaleLoyaltyTour.js
  addons/pos_sale_loyalty/tests/__init__.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/website_slides/static/src/js/slides_course_page.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
Labels: 16.0

#25710 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_move_line_tax_details.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
Labels: saas-15.2

#25713 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move_line_tax_details.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/public/welcome_page.js
  addons/mail/static/src/public/welcome_page.xml
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/res_config_settings.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/web/static/src/views/kanban/kanban_controller.scss
Labels: saas-16.3

#25714 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_move_line_tax_details.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/event_sale/models/event_registration.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/thread.py
  addons/mail/models/mail_thread.py
  addons/mail_group/models/mail_group.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/models/res_config_settings.py
  addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.js
  addons/point_of_sale/static/src/app/store/cash_opening_popup/cash_opening_popup.js
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_session.py
  addons/project/static/src/project_sharing/components/chatter/chatter.scss
  addons/project/static/src/project_sharing/views/form/project_sharing_form_compiler.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/repair/models/sale_order.py
  addons/repair/tests/test_repair.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/web/static/src/core/utils/hooks.js
  addons/web/static/src/views/form/form_renderer.js
  addons/web/static/tests/core/utils/hooks_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_crm_partner_assign/tests/test_partner_assign.py
Labels: saas-16.4

#25716 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/account/models/account_move_line_tax_details.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
Labels: staging.saas-15.2

#25717 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move_line_tax_details.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/mail/static/src/models/welcome_view.js
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/point_of_sale/models/res_config_settings.py
  addons/point_of_sale/static/src/js/Chrome.js
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
Labels: staging.saas-16.1

#25722 Syncing from upstream odoo/odoo (staging.16.0)
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/crm/static/src/views/forecast_search_model.js
  addons/crm/static/tests/crm_rainbowman_tests.js
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/pos_loyalty/models/pos_order.py
  addons/pos_sale_loyalty/__manifest__.py
  addons/pos_sale_loyalty/static/src/tours/PosSaleLoyaltyTour.js
  addons/pos_sale_loyalty/tests/__init__.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/website_slides/static/src/js/slides_course_page.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
Labels: staging.16.0

#25725 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_move_line_tax_details.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
Labels: tmp.saas-15.2

#25726 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move_line_tax_details.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/components/welcome_view/welcome_view.xml
  addons/mail/static/src/models/welcome_view.js
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_unbuild.py
  addons/point_of_sale/models/res_config_settings.py
  addons/point_of_sale/static/src/js/Chrome.js
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
Labels: tmp.saas-16.1

#25728 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_move_line_tax_details.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/public/welcome_page.js
  addons/mail/static/src/public/welcome_page.xml
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/res_config_settings.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/web/static/src/views/kanban/kanban_controller.scss
Labels: tmp.saas-16.3

#25729 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/account_move_line_tax_details.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/event_sale/models/event_registration.py
  addons/l10n_ca/views/report_invoice.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/thread.py
  addons/mail/models/mail_thread.py
  addons/mail_group/models/mail_group.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/payment/tests/test_payment_token.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/models/res_config_settings.py
  addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.js
  addons/point_of_sale/static/src/app/store/cash_opening_popup/cash_opening_popup.js
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_report_session.py
  addons/project/static/src/project_sharing/components/chatter/chatter.scss
  addons/project/static/src/project_sharing/views/form/project_sharing_form_compiler.js
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/repair/models/sale_order.py
  addons/repair/tests/test_repair.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/web/static/src/core/utils/hooks.js
  addons/web/static/src/views/form/form_renderer.js
  addons/web/static/tests/core/utils/hooks_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_crm_partner_assign/tests/test_partner_assign.py
Labels: tmp.saas-16.4

#25730 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_res_lang.py
Labels: tmp.15.0

#25731 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/crm/static/src/views/forecast_search_model.js
  addons/crm/static/tests/crm_rainbowman_tests.js
  addons/event_sale/models/event_registration.py
  addons/hr/models/hr_employee.py
  addons/l10n_in_edi_ewaybill/views/account_move_views.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/pos_loyalty/models/pos_order.py
  addons/pos_sale_loyalty/__manifest__.py
  addons/pos_sale_loyalty/static/src/tours/PosSaleLoyaltyTour.js
  addons/pos_sale_loyalty/tests/__init__.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase_tax_totals.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/website_slides/static/src/js/slides_course_page.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson.xml
Labels: tmp.16.0

#25738 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/nl.po
  addons/account_lock/i18n/it.po
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/base_setup/i18n/de.po
  addons/hr/i18n/zh_CN.po
  addons/hr_contract/i18n/zh_CN.po
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/controllers/mail.py
  addons/mail/i18n/es.po
  addons/mail/i18n/fr.po
  addons/mail/i18n/it.po
  addons/mail/i18n/nl.po
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale/i18n/es.po
  addons/sale/i18n/fr.po
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/stock/i18n/fr.po
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/test_mail_full/tests/test_mass_mailing_statistics.py
  addons/web/i18n/de.po
  addons/web/i18n/zh_TW.po
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_blog/i18n/es.po
  addons/website_event_questions/i18n/es.po
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: saas-15.2

#25744 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/controllers/mail.py
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/test_mail_full/tests/test_mass_mailing_statistics.py
  addons/web_editor/static/src/xml/wysiwyg.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: staging.saas-15.2

#25745 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/crm/static/tests/crm_rainbowman_tests.js
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/mail.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_loyalty/models/pos_order.py
  addons/pos_sale_loyalty/__manifest__.py
  addons/pos_sale_loyalty/static/src/tours/PosSaleLoyaltyTour.js
  addons/pos_sale_loyalty/tests/__init__.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/product/views/product_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_mass_mailing/tests/test_mailing_statistics_sms.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website_slides/views/website_slides_templates_homepage.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
Labels: staging.saas-16.1

#25746 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/crm/static/tests/crm_rainbowman_tests.js
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_be_pos_sale/__init__.py
  addons/l10n_be_pos_sale/__manifest__.py
  addons/l10n_be_pos_sale/i18n/l10n_be_pos_sale.pot
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_be_pos_sale/static/src/js/models.js
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/__init__.py
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/mail.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/static/tests/tours/helpers/PaymentScreenTourMethods.js
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_loyalty/i18n/pos_loyalty.pot
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/js/ControlButtons/eWalletButton.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/EWalletProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale_loyalty/__manifest__.py
  addons/pos_sale_loyalty/static/src/tours/PosSaleLoyaltyTour.js
  addons/pos_sale_loyalty/tests/__init__.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/product/views/product_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_mass_mailing/tests/test_mailing_statistics_sms.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website_sale/static/src/js/website_sale_delivery.js
  addons/website_slides/views/website_slides_templates_homepage.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
Labels: staging.saas-16.2

#25751 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account_edi/models/ir_actions_report.py
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_holidays/models/hr_leave.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/mail.py
  addons/mail/models/mail_channel_member.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/snailmail/models/snailmail_letter.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_mass_mailing/tests/test_mailing_statistics_sms.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_sale_coupon_multiwebsite.py
  addons/website_slides/views/website_slides_templates_homepage.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: staging.16.0

#25754 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/controllers/mail.py
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale/models/account_move.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/test_mail_full/tests/test_mass_mailing_statistics.py
  addons/web_editor/static/src/xml/wysiwyg.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: tmp.saas-15.2

#25755 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/crm/static/src/views/crm_form/crm_form.js
  addons/crm/static/tests/crm_rainbowman_tests.js
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/mail.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_loyalty/models/pos_order.py
  addons/pos_sale_loyalty/__manifest__.py
  addons/pos_sale_loyalty/static/src/tours/PosSaleLoyaltyTour.js
  addons/pos_sale_loyalty/tests/__init__.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/product/views/product_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_timesheet/models/sale_order.py
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_mass_mailing/tests/test_mailing_statistics_sms.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website_slides/views/website_slides_templates_homepage.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
Labels: tmp.saas-16.1

#25760 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/__init__.py
  addons/account/tests/test_product.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/mail/controllers/mail.py
  addons/mrp/models/product.py
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/sale/static/src/js/variant_mixin.js
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/test_mail/tests/test_mail_thread_internals.py
  addons/test_mail_full/tests/test_mass_mailing_statistics.py
  addons/web_editor/static/src/xml/wysiwyg.xml
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_module_category.py
Labels: tmp.15.0

#25761 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/ir_actions_report.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account_edi/models/ir_actions_report.py
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_holidays/models/hr_leave.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mail/controllers/mail.py
  addons/mail/models/mail_channel_member.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/models/microsoft_sync.py
  addons/microsoft_calendar/tests/test_delete_events.py
  addons/payment_adyen/i18n/payment_adyen.pot
  addons/payment_adyen/tests/test_adyen.py
  addons/payment_adyen/utils.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_sale/models/pos_order.py
  addons/product/views/product_views.xml
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/snailmail/models/snailmail_letter.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_mass_mailing/tests/test_mailing_statistics_sms.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_sale_coupon_multiwebsite.py
  addons/website_slides/views/website_slides_templates_homepage.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_ir_mail_server.py
  odoo/addons/base/tests/test_ir_module_category.py
  odoo/addons/base/tests/test_res_lang.py
  odoo/addons/test_access_rights/tests/test_ir_rules.py
Labels: tmp.16.0

#25763 Syncing from upstream odoo/odoo (17.0)
  addons/web/static/src/views/kanban/kanban_controller.xml
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/view_dialogs/select_create_dialog_tests.js
Labels: 17.0

#25765 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
Labels: saas-15.2

#25768 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/account/i18n/nl.po
  addons/account_lock/i18n/it.po
  addons/base_setup/i18n/de.po
  addons/hr/i18n/zh_CN.po
  addons/hr_contract/i18n/zh_CN.po
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/i18n/es.po
  addons/mail/i18n/fr.po
  addons/mail/i18n/it.po
  addons/mail/i18n/nl.po
  addons/sale/i18n/es.po
  addons/sale/i18n/fr.po
  addons/stock/i18n/fr.po
  addons/web/i18n/de.po
  addons/web/i18n/zh_TW.po
  addons/website_blog/i18n/es.po
  addons/website_event_questions/i18n/es.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/zh_TW.po
Labels: staging.saas-15.2

#25772 Syncing from upstream odoo/odoo (tmp.master)
  addons/l10n_pe_website_sale/__init__.py
  addons/l10n_pe_website_sale/__manifest__.py
  addons/l10n_pe_website_sale/controllers/__init__.py
  addons/l10n_pe_website_sale/controllers/main.py
  addons/l10n_pe_website_sale/data/ir_model_fields.xml
  addons/l10n_pe_website_sale/i18n/es.po
  addons/l10n_pe_website_sale/models/__init__.py
  addons/l10n_pe_website_sale/models/website.py
  addons/l10n_pe_website_sale/security/ir.model.access.csv
  addons/l10n_pe_website_sale/static/src/js/website_sale.js
  addons/l10n_pe_website_sale/views/templates.xml
Labels: tmp.master

#25773 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/i18n/nl.po
  addons/account_lock/i18n/it.po
  addons/base_setup/i18n/de.po
  addons/hr/i18n/zh_CN.po
  addons/hr_contract/i18n/zh_CN.po
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/mail/i18n/es.po
  addons/mail/i18n/fr.po
  addons/mail/i18n/it.po
  addons/mail/i18n/nl.po
  addons/sale/i18n/es.po
  addons/sale/i18n/fr.po
  addons/stock/i18n/fr.po
  addons/web/i18n/de.po
  addons/web/i18n/zh_TW.po
  addons/website_blog/i18n/es.po
  addons/website_event_questions/i18n/es.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/it.po
  odoo/addons/base/i18n/zh_TW.po
Labels: tmp.saas-15.2

#25775 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/web/static/src/views/kanban/kanban_controller.xml
  addons/web/static/src/views/list/list_controller.xml
  addons/web/static/tests/mobile/views/view_dialog/select_create_dialog_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/view_dialogs/select_create_dialog_tests.js
Labels: tmp.17.0

#25776 [bt#25256][FIX] account_sequence: flush fields depending on sequence
  addons/account/tests/test_sequence_mixin.py
  addons/account_sequence/models/sequence_mixin.py
Labels: 16.0.project_me_665

#25806 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/es_CL.po
  addons/l10n_ph/wizard/generate_2307_wizard.py
  addons/point_of_sale/tools/posbox/configuration/connect_to_server_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/connect_to_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/i18n/es_CL.po
  addons/repair/i18n/es_CL.po
  addons/sale/i18n/es_CL.po
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/tests/tours/parallax.js
Labels: 15.0

#25807 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_export_with_changed_taxes.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_bg/data/account.account.template.csv
  addons/l10n_bg/data/account_fiscal_position_template.xml
  addons/l10n_bg/data/account_tax_template_data.xml
  addons/l10n_bg/data/l10n_bg_chart_data.xml
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/link_tracker/i18n/link_tracker.pot
  addons/link_tracker/models/link_tracker.py
  addons/link_tracker/models/mail_render_mixin.py
  addons/link_tracker/tests/test_link_tracker.py
  addons/link_tracker/tests/test_mail_render_mixin.py
  addons/point_of_sale/tests/test_pos_capture.py
  addons/point_of_sale/tools/posbox/configuration/connect_to_server_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/connect_to_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/web/i18n/web.pot
  addons/web/static/src/legacy/js/views/basic/basic_model.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/helpers/utils.js
  addons/web/static/tests/mobile/views/calendar_view_tests.js
  addons/web/static/tests/setup.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/web_unsplash/static/src/components/media_dialog/image_selector.js
  addons/website/static/src/services/website_service.js
  addons/website/static/tests/tours/conditional_visibility.js
  addons/website/tests/__init__.py
  addons/website/tests/test_custom_snippets.py
  addons/website/tests/test_ui.py
  addons/website_sale/controllers/main.py
  addons/website_sale_delivery/controllers/main.py
  odoo/addons/base/tests/test_misc.py
Labels: 16.0

#25810 Syncing from upstream odoo/odoo (saas-15.2)
  addons/point_of_sale/tools/posbox/configuration/connect_to_server_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/connect_to_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
Labels: saas-15.2

#25811 Syncing from upstream odoo/odoo (saas-16.1)
  addons/test_mail/tests/test_mail_gateway.py
  odoo/__init__.py
Labels: saas-16.1

#25812 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_payment/i18n/account_payment.pot
  addons/account_payment/models/payment_provider.py
  addons/point_of_sale/static/src/js/models.js
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/__init__.py
Labels: saas-16.2

#25813 Syncing from upstream odoo/odoo (saas-16.3)
  addons/point_of_sale/models/pos_printer.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/__init__.py
Labels: saas-16.3

#25814 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move_line.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_expense/models/__init__.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/models/ir_attachment.py
  addons/hr_expense/tests/test_expenses.py
  addons/mrp/models/stock_scrap.py
  addons/mrp/tests/test_replenish.py
  addons/project/wizard/project_share_wizard_views.xml
  addons/stock/models/stock_scrap.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_website/__manifest__.py
  addons/test_website/data/test_website_data.xml
  addons/test_website/data/test_website_demo.xml
  addons/test_website/models/model.py
  addons/test_website/static/tests/tours/page_manager.js
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_page_manager.py
  addons/test_website/views/test_model_views.xml
  addons/web/static/src/views/utils.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/website/models/website.py
  addons/website/static/src/components/views/page_kanban.js
  addons/website/static/src/components/views/page_kanban.xml
  addons/website/static/src/components/views/page_list.js
  addons/website/static/src/components/views/page_list.xml
  addons/website/static/src/components/views/page_search_model.js
  addons/website/static/src/components/views/page_views_mixin.js
  addons/website/views/website_pages_views.xml
  addons/website_forum/models/forum_forum.py
  addons/website_forum/tests/test_forum_internals.py
  addons/website_forum/views/forum_post_views.xml
  odoo/__init__.py
Labels: saas-16.4

#25816 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/point_of_sale/tools/posbox/configuration/connect_to_server_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/connect_to_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
Labels: staging.saas-15.2

#25817 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/test_mail/tests/test_mail_gateway.py
  odoo/__init__.py
Labels: staging.saas-16.1

#25818 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/sale_mrp/models/account_move.py
  addons/sale_mrp/tests/test_sale_mrp_flow.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/__init__.py
Labels: staging.saas-16.2

#25824 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/point_of_sale/tools/posbox/configuration/connect_to_server_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/connect_to_wifi.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
Labels: tmp.saas-15.2

#25825 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/test_mail/tests/test_mail_gateway.py
  odoo/__init__.py
Labels: tmp.saas-16.1
