Repository brain-tec/odoo, pull requests merged in 2024-04, with the labels that each got.

#27064 Syncing from upstream odoo/odoo (16.0)
  addons/account_check_printing/models/account_payment.py
Labels: 16.0

#27065 Syncing from upstream odoo/odoo (17.0)
  addons/account_check_printing/models/account_payment.py
  addons/website_sale/static/src/js/payment_button.js
Labels: 17.0

#27067 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account_check_printing/models/account_payment.py
Labels: saas-16.3

#27068 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account_check_printing/models/account_payment.py
  addons/website_sale/static/src/js/payment_button.js
Labels: saas-16.4

#27074 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_check_printing/models/account_payment.py
  addons/website_sale/static/src/js/payment_button.js
Labels: tmp.17.0

#27075 Syncing from upstream odoo/odoo (16.0)
  addons/stock/models/stock_move.py
Labels: 16.0

#27076 Syncing from upstream odoo/odoo (17.0)
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
Labels: 17.0

#27077 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/wizard/account_move_send.py
  addons/account_edi_ubl_cii/wizard/account_move_send_views.xml
  addons/account_peppol/models/account_move.py
  addons/account_peppol/wizard/account_move_send.py
  addons/account_peppol/wizard/account_move_send_views.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_lu/data/tax_report/section_2.xml
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_tools.py
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/sale_timesheet/views/project_update_templates.xml
  addons/stock/i18n/stock.pot
  addons/stock/static/src/widgets/generate_serial.js
  addons/stock/static/src/widgets/lots_dialog.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.scss
Labels: master

#27078 Syncing from upstream odoo/odoo (saas-16.3)
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
Labels: saas-16.3

#27079 Syncing from upstream odoo/odoo (saas-16.4)
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
Labels: saas-16.4

#27080 Syncing from upstream odoo/odoo (staging.16.0)
  addons/stock/models/stock_move.py
Labels: staging.16.0

#27081 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/wizard/account_move_send.py
  addons/account_edi_ubl_cii/wizard/account_move_send_views.xml
  addons/account_peppol/models/account_move.py
  addons/account_peppol/wizard/account_move_send.py
  addons/account_peppol/wizard/account_move_send_views.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_lu/data/tax_report/section_2.xml
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_tools.py
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/sale_timesheet/views/project_update_templates.xml
  addons/stock/i18n/stock.pot
  addons/stock/static/src/widgets/generate_serial.js
  addons/stock/static/src/widgets/lots_dialog.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.scss
Labels: tmp.master

#27082 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
Labels: tmp.saas-16.3

#27083 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
Labels: tmp.saas-16.4

#27084 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/stock/models/stock_move.py
Labels: tmp.16.0

#27085 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/product/tests/test_name.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
Labels: tmp.17.0

#27086 Syncing from upstream odoo/odoo (15.0)
  addons/hr_work_entry_contract/data/hr_work_entry_data.xml
  addons/hr_work_entry_contract/i18n/hr_work_entry_contract.pot
  addons/l10n_id_efaktur/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
Labels: 15.0

#27090 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/product.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/static/src/views/list.js
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/loyalty/views/loyalty_program_views.xml
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/static/src/discuss_app/channel_selector.xml
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/src/js/models.js
  addons/portal/models/mail_message.py
  addons/sale/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/src/legacy/js/core/minimal_dom.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web/static/tests/helpers/mock_services.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/webclient/clickbot_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_blog/static/tests/tours/blog_tags_tour.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/models/product_product.py
  addons/website_sale/models/product_template.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: saas-16.3

#27091 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/loyalty/views/loyalty_program_views.xml
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/static/src/discuss/core/web/channel_selector.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/src/app/utils/number_buffer_service.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/src/legacy/js/core/minimal_dom.js
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web/static/tests/helpers/mock_services.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/webclient/clickbot_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/models/product_product.py
  addons/website_sale/models/product_template.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: saas-16.4

#27092 Syncing from upstream odoo/odoo (staging.16.0)
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_es/data/account.account.template-assoc.csv
  addons/l10n_es/data/account.account.template-common.csv
  addons/l10n_es/data/account.account.template-full.csv
  addons/l10n_es/data/account.account.template-pymes.csv
  addons/l10n_id_efaktur/models/account_move.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_hr/models/hr_employee_public.py
  addons/web/static/src/legacy/js/core/minimal_dom.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_event_exhibitor/models/event_sponsor.py
  addons/website_event_meet/models/event_meeting_room.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  addons/website_sale_loyalty_delivery/controllers/main.py
  addons/website_sale_loyalty_delivery/static/src/js/website_sale_loyalty_delivery.js
  addons/website_sale_loyalty_delivery/static/tests/tours/website_sale_delivery_gift_card.js
  addons/website_sale_loyalty_delivery/tests/test_website_sale_loyalty_delivery.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_res_country.py
  odoo/tools/translate.py
Labels: staging.16.0

#27094 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/product.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/static/src/views/list.js
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/loyalty/views/loyalty_program_views.xml
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/static/src/discuss_app/channel_selector.xml
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/src/js/models.js
  addons/portal/models/mail_message.py
  addons/sale/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/src/legacy/js/core/minimal_dom.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web/static/tests/helpers/mock_services.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/webclient/clickbot_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_blog/static/tests/tours/blog_tags_tour.js
  addons/website_blog/tests/test_ui.py
  addons/website_sale/models/product_product.py
  addons/website_sale/models/product_template.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: tmp.saas-16.3

#27095 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_work_entry_contract/models/hr_work_entry.py
  addons/hr_work_entry_contract/tests/test_work_entry.py
  addons/l10n_it_edi/models/account_edi_format.py
  addons/loyalty/views/loyalty_program_views.xml
  addons/loyalty/views/loyalty_reward_views.xml
  addons/mail/static/src/discuss/core/web/channel_selector.xml
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mass_mailing/views/mailing_mailing_views.xml
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/src/app/utils/number_buffer_service.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale/models/sale_order_line.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/src/legacy/js/core/minimal_dom.js
  addons/web/static/src/views/kanban/kanban_model.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web/static/tests/helpers/mock_services.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/webclient/clickbot_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_sale/models/product_product.py
  addons/website_sale/models/product_template.py
  addons/website_sale/tests/test_website_sale_product_attribute_value_config.py
Labels: tmp.saas-16.4

#27097 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_delivery_stock_move.py
  addons/l10n_es/data/account.account.template-assoc.csv
  addons/l10n_es/data/account.account.template-common.csv
  addons/l10n_es/data/account.account.template-full.csv
  addons/l10n_es/data/account.account.template-pymes.csv
  addons/l10n_id_efaktur/models/account_move.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_hr/models/hr_employee_public.py
  addons/web/static/src/legacy/js/core/minimal_dom.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_event_exhibitor/models/event_sponsor.py
  addons/website_event_meet/models/event_meeting_room.py
  addons/website_sale_loyalty/views/website_sale_templates.xml
  addons/website_sale_loyalty_delivery/controllers/main.py
  addons/website_sale_loyalty_delivery/static/src/js/website_sale_loyalty_delivery.js
  addons/website_sale_loyalty_delivery/static/tests/tours/website_sale_delivery_gift_card.js
  addons/website_sale_loyalty_delivery/tests/test_website_sale_loyalty_delivery.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  odoo/addons/base/models/res_country.py
  odoo/addons/base/tests/test_res_country.py
  odoo/tools/translate.py
Labels: tmp.16.0

#27099 Syncing from upstream odoo/odoo (15.0)
  addons/calendar/models/calendar_alarm_manager.py
  addons/calendar/tests/test_event_notifications.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/stock_quant.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/stock_account/models/stock_move.py
  addons/website/static/src/snippets/s_searchbar/000.js
Labels: 15.0

#27100 Syncing from upstream odoo/odoo (16.0)
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/express_checkout_form.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
Labels: 16.0

#27104 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/calendar/models/calendar_event.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.js
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.js
  addons/calendar/tests/test_access_rights.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_es/data/template/account.account-es_assec.csv
  addons/l10n_es/data/template/account.account-es_common.csv
  addons/l10n_es/data/template/account.account-es_full.csv
  addons/l10n_es/data/template/account.account-es_pymes.csv
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/website/tests/test_crawl.py
  addons/website_sale/views/product_views.xml
  odoo/tools/translate.py
Labels: tmp.saas-16.3

#27105 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/calendar/models/calendar_event.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.js
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.js
  addons/calendar/tests/test_access_rights.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/static/src/views/list.js
  addons/im_livechat/controllers/main.py
  addons/l10n_es/data/template/account.account-es_assec.csv
  addons/l10n_es/data/template/account.account-es_common.csv
  addons/l10n_es/data/template/account.account-es_full.csv
  addons/l10n_es/data/template/account.account-es_pymes.csv
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/models/mail_message.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/sale/models/account_move.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/emoji_picker/emoji_picker.js
  addons/web/static/src/views/fields/many2many_binary/many2many_binary_field.js
  addons/web/static/src/views/fields/many2many_binary/many2many_binary_field.xml
  addons/website_blog/static/tests/tours/blog_tags_tour.js
  addons/website_blog/tests/test_ui.py
  addons/website_livechat/controllers/main.py
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_redirect.js
  odoo/tools/translate.py
Labels: tmp.saas-16.4

#27106 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/calendar/models/calendar_alarm_manager.py
  addons/calendar/tests/test_event_notifications.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/stock_quant.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/stock_account/models/stock_move.py
  addons/website/static/src/snippets/s_searchbar/000.js
Labels: tmp.15.0

#27107 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/express_checkout_form.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
Labels: tmp.16.0

#27108 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_journal.py
  addons/account/static/src/components/tax_totals/tax_totals.js
  addons/account/views/report_payment_receipt_templates.xml
  addons/base_vat/views/res_partner_views.xml
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_access_rights.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/im_livechat/controllers/main.py
  addons/im_livechat/models/discuss_channel.py
  addons/l10n_es/data/template/account.account-es_assec.csv
  addons/l10n_es/data/template/account.account-es_common.csv
  addons/l10n_es/data/template/account.account-es_full.csv
  addons/l10n_es/data/template/account.account-es_pymes.csv
  addons/loyalty/views/loyalty_program_views.xml
  addons/loyalty/views/loyalty_reward_views.xml
  addons/payment/views/payment_form_templates.xml
  addons/payment/views/portal_templates.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal_rating/models/rating_rating.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/purchase/models/purchase_order_line.py
  addons/sale/models/sale_order.py
  addons/sale/views/sale_portal_templates.xml
  addons/spreadsheet/static/src/pivot/pivot_model.js
  addons/spreadsheet/static/tests/pivots/model/pivot_plugin_test.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/core/colorpicker/colorpicker.xml
  addons/web/static/src/views/fields/many2many_binary/many2many_binary_field.js
  addons/web/static/src/views/fields/many2many_binary/many2many_binary_field.xml
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web/static/tests/helpers/mock_services.js
  addons/web/static/tests/webclient/clickbot_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/snippets.xml
  addons/website_blog/models/website_blog.py
  addons/website_livechat/controllers/main.py
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_redirect.js
  addons/website_payment/views/payment_form_templates.xml
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale/views/website_sale_delivery_templates.xml
  odoo/tools/translate.py
Labels: tmp.17.0

#27110 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/l10n_in/models/account_invoice.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/network/download.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  odoo/__init__.py
Labels: 15.0

#27111 Syncing from upstream odoo/odoo (16.0)
  addons/account/views/account_move_views.xml
  addons/calendar/models/calendar_alarm_manager.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_calendar.py
  addons/calendar/tests/test_event_notifications.py
  addons/calendar/tests/test_event_recurrence.py
  addons/event/data/event_demo.xml
  addons/event/data/event_demo_misc.xml
  addons/event/tests/test_event_internals.py
  addons/hr/tests/test_self_user_access.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/project/views/project_sharing_views.xml
  addons/spreadsheet/tests/test_currency_rate.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_resource/tests/common.py
  addons/test_resource/tests/test_resource.py
  addons/web/tests/test_image.py
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/static/src/snippets/options.js
  addons/website_slides/tests/test_slide_resource.py
  odoo/__init__.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/__init__.py
  odoo/tools/_monkeypatches_pytz.py
  odoo/tools/_monkeypatches_urls.py
  odoo/tools/safe_eval.py
  odoo/tools/template_inheritance.py
Labels: 16.0

#27114 Syncing from upstream odoo/odoo (saas-16.3)
  addons/board/static/src/board_controller.scss
  addons/calendar/models/calendar_event.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.js
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.js
  addons/calendar/tests/test_access_rights.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_es/data/template/account.account-es_assec.csv
  addons/l10n_es/data/template/account.account-es_common.csv
  addons/l10n_es/data/template/account.account-es_full.csv
  addons/l10n_es/data/template/account.account-es_pymes.csv
  addons/l10n_es_edi_facturae/i18n/l10n_es_edi_facturae.pot
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/mrp/tests/test_order.py
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/payment/static/src/js/express_checkout_form.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project/views/project_task_type_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_avatar_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/website/models/website.py
  addons/website/tests/test_crawl.py
  addons/website/tests/test_menu.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_sale/views/product_views.xml
  odoo/tools/translate.py
Labels: saas-16.3

#27115 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/calendar/models/calendar_event.py
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_popover.js
  addons/calendar/static/src/views/attendee_calendar/common/attendee_calendar_common_renderer.js
  addons/calendar/tests/test_access_rights.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_expense/static/src/views/list.js
  addons/hw_drivers/controllers/driver.py
  addons/im_livechat/controllers/main.py
  addons/l10n_es/data/template/account.account-es_assec.csv
  addons/l10n_es/data/template/account.account-es_common.csv
  addons/l10n_es/data/template/account.account-es_full.csv
  addons/l10n_es/data/template/account.account-es_pymes.csv
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/express_checkout_form.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/models/mail_message.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale/models/account_move.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/emoji_picker/emoji_picker.js
  addons/web/static/src/views/fields/many2many_binary/many2many_binary_field.js
  addons/web/static/src/views/fields/many2many_binary/many2many_binary_field.xml
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_blog/static/tests/tours/blog_tags_tour.js
  addons/website_blog/tests/test_ui.py
  addons/website_livechat/controllers/main.py
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_redirect.js
  addons/website_sale/views/product_views.xml
  odoo/addons/base/static/src/scss/res_partner.scss
  odoo/addons/base/views/res_users_identitycheck_views.xml
  odoo/tools/translate.py
Labels: saas-16.4

#27116 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/views/account_move_views.xml
  addons/calendar/models/calendar_alarm_manager.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_calendar.py
  addons/calendar/tests/test_event_notifications.py
  addons/calendar/tests/test_event_recurrence.py
  addons/event/data/event_demo.xml
  addons/event/data/event_demo_misc.xml
  addons/event/tests/test_event_internals.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr/tests/test_self_user_access.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/express_checkout_form.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/product_margin/i18n/product_margin.pot
  addons/product_margin/models/product_product.py
  addons/project/views/project_sharing_views.xml
  addons/spreadsheet/tests/test_currency_rate.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_resource/tests/common.py
  addons/test_resource/tests/test_resource.py
  addons/web/tests/test_image.py
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/static/src/snippets/options.js
  addons/website_slides/tests/test_slide_resource.py
  odoo/__init__.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/__init__.py
  odoo/tools/_monkeypatches_pytz.py
  odoo/tools/_monkeypatches_urls.py
  odoo/tools/safe_eval.py
  odoo/tools/template_inheritance.py
Labels: staging.16.0

#27118 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/board/static/src/board_controller.scss
  addons/l10n_es_edi_facturae/i18n/l10n_es_edi_facturae.pot
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/payment/static/src/js/express_checkout_form.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/project/views/project_task_type_views.xml
  addons/stock/models/stock_move.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_avatar_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
Labels: tmp.saas-16.3

#27119 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/controllers/driver.py
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/express_checkout_form.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_sale/views/product_views.xml
  odoo/addons/base/static/src/scss/res_partner.scss
  odoo/addons/base/views/res_users_identitycheck_views.xml
Labels: tmp.saas-16.4

#27120 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_journal.py
  addons/l10n_in/models/account_invoice.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/network/download.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  odoo/__init__.py
Labels: tmp.15.0

#27121 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/views/account_move_views.xml
  addons/calendar/models/calendar_alarm_manager.py
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_calendar.py
  addons/calendar/tests/test_event_notifications.py
  addons/calendar/tests/test_event_recurrence.py
  addons/event/data/event_demo.xml
  addons/event/data/event_demo_misc.xml
  addons/event/tests/test_event_internals.py
  addons/hr/tests/test_self_user_access.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/project/views/project_sharing_views.xml
  addons/spreadsheet/tests/test_currency_rate.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_resource/tests/common.py
  addons/test_resource/tests/test_resource.py
  addons/web/tests/test_image.py
  addons/web_editor/controllers/main.py
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/static/src/snippets/options.js
  addons/website_slides/tests/test_slide_resource.py
  odoo/__init__.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/__init__.py
  odoo/tools/_monkeypatches_pytz.py
  odoo/tools/_monkeypatches_urls.py
  odoo/tools/safe_eval.py
  odoo/tools/template_inheritance.py
Labels: tmp.16.0

#27122 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_peppol/models/account_move.py
  addons/account_peppol/models/res_partner.py
  addons/account_peppol/tests/test_peppol_messages.py
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/res_partner.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/models/res_users.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/im_livechat/views/im_livechat_channel_templates.xml
  addons/l10n_pe_pos/static/src/overrides/components/partner_list/partner_list.js
  addons/mrp/tests/test_order.py
  addons/payment/static/src/js/express_checkout_form.js
  addons/sale/models/sale_order.py
  addons/sale/models/sale_order_line.py
  addons/survey/i18n/survey.pot
  addons/survey/static/src/scss/survey_templates_results.scss
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/core/emoji_picker/emoji_picker.js
  addons/web/static/src/model/relational_model/relational_model.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/website_sale/views/product_views.xml
  odoo/addons/base/static/src/scss/res_partner.scss
  odoo/addons/base/views/res_users_identitycheck_views.xml
Labels: tmp.17.0

#27123 [bt#26686] Cash management - skip previous_statement_id computations
  addons/account/models/account_bank_statement.py
Labels: enhancement, 15.0.project_sv_559

#27124 [FIX] account: backport of computation of tax tag invert fix
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_out_invoice.py
Labels: 15.0.project_gd_615

#27125 Syncing from upstream odoo/odoo (15.0)
  addons/crm/models/res_partner.py
  addons/iap/tools/iap_tools.py
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_move2.py
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web_editor/models/ir_ui_view.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
Labels: 15.0

#27126 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/account/models/account_partial_reconcile.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/note/static/src/scss/note.scss
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/website_views.xml
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/models/website.py
Labels: 16.0

#27129 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_journal.py
  addons/account/views/account_move_views.xml
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_orderpoint.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/web/static/src/core/network/download.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/website_views.xml
  addons/website_event/static/src/snippets/options.js
  addons/website_event_exhibitor/models/event_sponsor.py
  addons/website_event_meet/models/event_meeting_room.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
Labels: saas-16.3

#27130 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_journal.py
  addons/account/views/account_move_views.xml
  addons/board/static/src/board_controller.scss
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_es_edi_facturae/i18n/l10n_es_edi_facturae.pot
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/views/project_task_type_views.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/network/download.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_avatar_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/js/common/utils.js
  addons/website/tests/test_crawl.py
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/static/src/snippets/options.js
Labels: saas-16.4

#27131 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_journal.py
  addons/account/models/account_partial_reconcile.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/note/static/src/scss/note.scss
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/website_views.xml
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/models/website.py
Labels: staging.16.0

#27133 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_journal.py
  addons/account/models/account_partial_reconcile.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/l10n_fr_fec/wizard/account_fr_fec.py
  addons/note/static/src/scss/note.scss
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/core/network/download.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/views/website_views.xml
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/models/website.py
Labels: tmp.16.0

#27134 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_journal.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_move_views.xml
  addons/account_tax_python/tests/test_tax.py
  addons/board/static/src/board_controller.scss
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_es_edi_facturae/i18n/l10n_es_edi_facturae.pot
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/store/db.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/portal/models/mail_message.py
  addons/pos_loyalty/i18n/pos_loyalty.pot
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_viva_wallet/views/pos_payment_method_views.xml
  addons/project/views/project_sharing_project_task_views.xml
  addons/project/views/project_task_type_views.xml
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_orderpoint.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/static/src/core/network/download.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/tests/test_crawl.py
  addons/website/views/website_views.xml
  addons/website_blog/static/tests/tours/blog_tags_tour.js
  addons/website_blog/tests/test_ui.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/static/src/snippets/options.js
  odoo/addons/base/views/res_partner_views.xml
Labels: tmp.17.0

#27138 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/company.py
  addons/account/report/account_hash_integrity_templates.xml
  addons/account/tests/test_account_inalterable_hash.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_journal_views.xml
  addons/account/views/account_move_views.xml
  addons/l10n_fr_account/__init__.py
Labels: master

#27139 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/es.po
  addons/account/i18n/es_MX.po
  addons/base_import/i18n/de.po
  addons/fleet/i18n/es_MX.po
  addons/hr/i18n/es_MX.po
  addons/hr_attendance/i18n/es_MX.po
  addons/hr_contract/i18n/es_MX.po
  addons/hr_holidays/i18n/de.po
  addons/mass_mailing/i18n/es_MX.po
  addons/sale/i18n/es_MX.po
  addons/web/i18n/zh_TW.po
  addons/website_crm_partner_assign/i18n/vi.po
  addons/website_event/i18n/vi.po
  addons/website_event_exhibitor/i18n/vi.po
  addons/website_event_meet/i18n/vi.po
  addons/website_event_questions/i18n/vi.po
  addons/website_event_track/i18n/vi.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/vi.po
  odoo/addons/base/i18n/zh_TW.po
Labels: saas-15.2

#27140 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/i18n/es_MX.po
  addons/account/i18n/id.po
  addons/account/i18n/pl.po
  addons/account/i18n/pt.po
  addons/analytic/i18n/zh_TW.po
  addons/auth_totp/i18n/pt.po
  addons/base_import/i18n/de.po
  addons/event/i18n/pt.po
  addons/fleet/i18n/es_MX.po
  addons/google_gmail/i18n/pt.po
  addons/hr/i18n/es_MX.po
  addons/hr/i18n/id.po
  addons/hr/i18n/pt_BR.po
  addons/hr_attendance/i18n/es_MX.po
  addons/hr_contract/i18n/es_MX.po
  addons/hr_holidays/i18n/de.po
  addons/hr_holidays/i18n/pt.po
  addons/hr_work_entry_contract/i18n/es_MX.po
  addons/mass_mailing/i18n/es_MX.po
  addons/mass_mailing_themes/i18n/es_MX.po
  addons/microsoft_outlook/i18n/pt.po
  addons/sale/i18n/es_MX.po
  addons/web/i18n/zh_TW.po
  addons/web_editor/i18n/id.po
  addons/web_editor/i18n/pt_BR.po
  addons/website_crm_partner_assign/i18n/vi.po
  addons/website_event/i18n/vi.po
  addons/website_event_exhibitor/i18n/vi.po
  addons/website_event_meet/i18n/vi.po
  addons/website_event_questions/i18n/vi.po
  addons/website_event_track/i18n/vi.po
  addons/website_event_track_live/i18n/pt.po
  addons/website_slides/i18n/pt.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/id.po
  odoo/addons/base/i18n/ja.po
  odoo/addons/base/i18n/zh_TW.po
Labels: saas-16.1

#27141 Syncing from upstream odoo/odoo (saas-16.3)
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_calendar.py
  addons/calendar/tests/test_event_recurrence.py
  addons/event/data/event_demo.xml
  addons/event/data/event_demo_misc.xml
  addons/event/tests/test_event_internals.py
  addons/hr/tests/test_self_user_access.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/spreadsheet/tests/test_currency_rate.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_resource/tests/common.py
  addons/test_resource/tests/test_resource.py
  addons/web/tests/test_image.py
  addons/web_editor/controllers/main.py
  addons/website_slides/tests/test_slide_resource.py
  odoo/__init__.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/__init__.py
  odoo/tools/_monkeypatches_pytz.py
  odoo/tools/_monkeypatches_urls.py
  odoo/tools/safe_eval.py
  odoo/tools/template_inheritance.py
Labels: saas-16.3

#27144 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_journal.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/company.py
  addons/account/report/account_hash_integrity_templates.xml
  addons/account/tests/test_account_inalterable_hash.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_journal_dashboard_view.xml
  addons/account/views/account_journal_views.xml
  addons/account/views/account_move_views.xml
  addons/l10n_fr_account/__init__.py
Labels: tmp.master

#27146 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_journal.py
  addons/account/views/account_move_views.xml
  addons/board/static/src/board_controller.scss
  addons/hr_expense/models/res_config_settings.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_es_edi_facturae/i18n/l10n_es_edi_facturae.pot
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_id_efaktur/models/account_move.py
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/views/project_task_type_views.xml
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/network/download.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_avatar_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/js/common/utils.js
  addons/website/tests/test_crawl.py
  addons/website/views/website_views.xml
  addons/website_blog/views/website_blog_components.xml
  addons/website_blog/views/website_blog_templates.xml
  addons/website_event/static/src/snippets/options.js
Labels: tmp.saas-16.4

#27147 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/crm/models/res_partner.py
  addons/iap/tools/iap_tools.py
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mass_mailing/views/mass_mailing_templates_portal.xml
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_move2.py
  addons/web/static/src/legacy/scss/layout_boxed.scss
  addons/web_editor/models/ir_ui_view.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
Labels: tmp.15.0

#27148 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_avatar_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
Labels: tmp.17.0

#27149 Syncing from upstream odoo/odoo (17.0)
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_calendar.py
  addons/calendar/tests/test_event_recurrence.py
  addons/event/data/event_demo.xml
  addons/event/data/event_demo_misc.xml
  addons/event/tests/test_event_internals.py
  addons/hr/tests/test_self_user_access.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/spreadsheet/tests/test_currency_rate.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_resource/tests/common.py
  addons/test_resource/tests/test_resource.py
  addons/web/tests/test_image.py
  addons/website_sale/views/product_views.xml
  addons/website_slides/tests/test_slide_resource.py
  odoo/__init__.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/__init__.py
  odoo/tools/_monkeypatches_pytz.py
  odoo/tools/_monkeypatches_urls.py
  odoo/tools/safe_eval.py
  odoo/tools/template_inheritance.py
Labels: 17.0

#27150 Syncing from upstream odoo/odoo (master)
  addons/web/static/lib/pdfjs/build/pdf.js
  addons/web/static/lib/pdfjs/build/pdf.worker.js
  addons/web/static/lib/pdfjs/web/debugger.js
  addons/web/static/lib/pdfjs/web/viewer.html
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web/static/src/core/assets.js
  addons/web/static/src/libs/pdfjs.js
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
Labels: master

#27151 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/i18n/es_MX.po
  addons/account/i18n/id.po
  addons/account/i18n/pl.po
  addons/account/i18n/pt.po
  addons/analytic/i18n/zh_TW.po
  addons/auth_totp/i18n/pt.po
  addons/base_import/i18n/de.po
  addons/event/i18n/pt.po
  addons/fleet/i18n/es_MX.po
  addons/google_gmail/i18n/pt.po
  addons/hr/i18n/es_MX.po
  addons/hr/i18n/id.po
  addons/hr/i18n/pt_BR.po
  addons/hr_attendance/i18n/es_MX.po
  addons/hr_contract/i18n/es_MX.po
  addons/hr_holidays/i18n/de.po
  addons/hr_holidays/i18n/es_MX.po
  addons/hr_holidays/i18n/pt.po
  addons/hr_work_entry_contract/i18n/es_MX.po
  addons/loyalty/i18n/fr.po
  addons/mass_mailing/i18n/es_MX.po
  addons/mass_mailing_themes/i18n/es_MX.po
  addons/microsoft_outlook/i18n/pt.po
  addons/sale/i18n/es_MX.po
  addons/stock/i18n/pt.po
  addons/web/i18n/zh_TW.po
  addons/website_crm_partner_assign/i18n/vi.po
  addons/website_event/i18n/vi.po
  addons/website_event_exhibitor/i18n/pt.po
  addons/website_event_exhibitor/i18n/vi.po
  addons/website_event_meet/i18n/vi.po
  addons/website_event_questions/i18n/vi.po
  addons/website_event_track/i18n/vi.po
  addons/website_event_track_live/i18n/pt.po
  addons/website_slides/i18n/pt.po
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/id.po
  odoo/addons/base/i18n/ja.po
  odoo/addons/base/i18n/pt.po
  odoo/addons/base/i18n/pt_BR.po
  odoo/addons/base/i18n/vi.po
  odoo/addons/base/i18n/zh_TW.po
Labels: saas-16.2

#27153 Syncing from upstream odoo/odoo (saas-16.4)
  addons/calendar/models/calendar_recurrence.py
  addons/calendar/tests/test_calendar.py
  addons/calendar/tests/test_event_recurrence.py
  addons/event/data/event_demo.xml
  addons/event/data/event_demo_misc.xml
  addons/event/tests/test_event_internals.py
  addons/hr/tests/test_self_user_access.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/spreadsheet/tests/test_currency_rate.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_resource/tests/common.py
  addons/test_resource/tests/test_resource.py
  addons/web/tests/test_image.py
  addons/web_editor/controllers/main.py
  addons/website_sale/views/product_views.xml
  addons/website_slides/tests/test_slide_resource.py
  odoo/__init__.py
  odoo/addons/base/tests/__init__.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/__init__.py
  odoo/tools/_monkeypatches_pytz.py
  odoo/tools/_monkeypatches_urls.py
  odoo/tools/safe_eval.py
  odoo/tools/template_inheritance.py
Labels: saas-16.4

#27154 Syncing from upstream odoo/odoo (tmp.master)
  addons/web/static/lib/pdfjs/build/pdf.js
  addons/web/static/lib/pdfjs/build/pdf.worker.js
  addons/web/static/lib/pdfjs/web/debugger.js
  addons/web/static/lib/pdfjs/web/viewer.html
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web/static/src/core/assets.js
  addons/web/static/src/libs/pdfjs.js
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
Labels: tmp.master

#27158 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_reconcile_model.py
  addons/event_sale/report/event_event_templates.xml
  addons/fetchmail/models/fetchmail.py
  addons/hw_escpos/controllers/main.py
  addons/mail/models/models.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/point_of_sale/models/pos_session.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_proc_rule.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/core/utils/timing.js
  addons/web/static/src/legacy/js/fields/basic_fields.js
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/core/utils/timing_tests.js
  addons/web/static/tests/legacy/fields/basic_fields_tests.js
  addons/website_blog/views/website_blog_posts_loop.xml
  odoo/addons/base/tests/test_qweb.py
  odoo/tests/common.py
Labels: 15.0

#27159 Syncing from upstream odoo/odoo (16.0)
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_recruitment/models/hr_recruitment.py
  addons/hr_recruitment/tests/test_utm.py
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mass_mailing/views/mailing_templates_portal_layouts.xml
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/core/utils/timing.js
  addons/web/static/src/webclient/actions/reports/layout_assets/layout_boxed.scss
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/core/utils/timing_tests.js
Labels: 16.0

#27162 Syncing from upstream odoo/odoo (saas-16.3)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_portal_timesheet.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hw_drivers/tools/helpers.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/project_todo/static/src/scss/todo.scss
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/models/website.py
  odoo/http.py
Labels: saas-16.3

#27163 Syncing from upstream odoo/odoo (saas-16.4)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_portal_timesheet.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hw_drivers/tools/helpers.py
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/website_event_exhibitor/models/event_sponsor.py
  addons/website_event_meet/models/event_meeting_room.py
  addons/website_sale/models/website.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  odoo/http.py
Labels: saas-16.4

#27166 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_portal_timesheet.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hw_drivers/tools/helpers.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/project_todo/static/src/scss/todo.scss
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/tests/html_field_tests.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/models/website.py
  odoo/http.py
Labels: tmp.saas-16.3

#27167 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_portal_timesheet.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hw_drivers/tools/helpers.py
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting/models/stock_picking.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/website_event_exhibitor/models/event_sponsor.py
  addons/website_event_meet/models/event_meeting_room.py
  addons/website_sale/models/website.py
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  odoo/http.py
Labels: tmp.saas-16.4

#27170 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/l10n_in_sale/views/report_sale_order.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/__init__.py
  addons/mrp/models/stock_quant.py
  addons/payment_stripe/models/payment_transaction.py
  addons/payment_stripe/utils.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_PA.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/sale_project/tests/test_project_profitability.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/py_js/py_interpreter.js
  addons/web/static/src/views/fields/url/url_field.js
  addons/web/static/tests/core/py_js/py_interpreter_tests.js
  addons/web/static/tests/views/fields/url_field_tests.js
  addons/web_editor/static/src/js/common/utils.js
  addons/website/models/website.py
  addons/website/tests/test_menu.py
  addons/website_event_exhibitor/models/event_sponsor.py
  addons/website_event_meet/models/event_meeting_room.py
  addons/website_sale/models/website.py
  addons/website_sale/views/templates.xml
  addons/website_slides/models/slide_channel.py
  addons/website_slides/models/slide_slide.py
  odoo/http.py
Labels: tmp.17.0

#27171 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/mixins.py
  addons/website/static/tests/tours/edit_menus.js
  addons/website/static/tests/tours/link_tools.js
  odoo/addons/base/models/ir_cron.py
Labels: 15.0

#27172 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_reconcile_model.py
  addons/account/views/account_move_views.xml
  addons/analytic/models/analytic_mixin.py
  addons/crm/models/res_partner.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/mail/models/fetchmail.py
  addons/mail/models/models.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_crm/models/crm_lead.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/mixins.py
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_qweb.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: 16.0

#27175 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_partial_reconcile.py
  addons/account/models/chart_template.py
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/mail/models/models.py
  addons/mass_mailing/static/src/snippets/s_rating/options.js
  addons/mass_mailing/views/mailing_templates_portal_layouts.xml
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/webclient/actions/reports/layout_assets/layout_boxed.scss
  addons/website/models/mixins.py
  addons/website/static/src/snippets/s_rating/options.js
Labels: saas-16.3

#27176 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_partial_reconcile.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/security/hr_recruitment_security.xml
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/mail/models/models.py
  addons/mass_mailing/static/src/snippets/s_rating/options.js
  addons/mass_mailing/views/mailing_templates_portal_layouts.xml
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/pos_sale/report/sale_report.py
  addons/project_todo/static/src/scss/todo.scss
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/webclient/actions/reports/layout_assets/layout_boxed.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/mixins.py
  addons/website/static/src/snippets/s_rating/options.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
Labels: saas-16.4

#27177 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_reconcile_model.py
  addons/account/views/account_move_views.xml
  addons/analytic/models/analytic_mixin.py
  addons/crm/models/res_partner.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/mail/models/fetchmail.py
  addons/mail/models/models.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_crm/models/crm_lead.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/mixins.py
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_qweb.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: staging.16.0

#27179 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_partial_reconcile.py
  addons/account/models/chart_template.py
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/mail/models/models.py
  addons/mass_mailing/static/src/snippets/s_rating/options.js
  addons/mass_mailing/views/mailing_templates_portal_layouts.xml
  addons/point_of_sale/static/src/js/custom_hooks.js
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/webclient/actions/reports/layout_assets/layout_boxed.scss
  addons/website/models/mixins.py
  addons/website/static/src/snippets/s_rating/options.js
Labels: tmp.saas-16.3

#27180 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_partial_reconcile.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/security/hr_recruitment_security.xml
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/l10n_fr_pos_cert/__manifest__.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/l10n_fr_pos_cert/views/res_config_settings_views.xml
  addons/mail/models/models.py
  addons/mass_mailing/static/src/snippets/s_rating/options.js
  addons/mass_mailing/views/mailing_templates_portal_layouts.xml
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_MU.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/static/src/scss/pos.scss
  addons/pos_sale/report/sale_report.py
  addons/project_todo/static/src/scss/todo.scss
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web/static/src/webclient/actions/reports/layout_assets/layout_boxed.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/mixins.py
  addons/website/static/src/snippets/s_rating/options.js
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
Labels: tmp.saas-16.4

#27181 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/models/mixins.py
  addons/website/static/tests/tours/edit_menus.js
  addons/website/static/tests/tours/link_tools.js
  odoo/addons/base/models/ir_cron.py
Labels: tmp.15.0

#27182 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_reconcile_model.py
  addons/account/views/account_move_views.xml
  addons/analytic/models/analytic_mixin.py
  addons/crm/models/res_partner.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/hw_escpos/controllers/main.py
  addons/iap/tools/iap_tools.py
  addons/mail/models/fetchmail.py
  addons/mail/models/models.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_crm/models/crm_lead.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/models/mixins.py
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_qweb.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: tmp.16.0

#27184 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_cl/data/account_fiscal_template.xml
  addons/l10n_cl/data/l10n_cl_chart_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  odoo/addons/base/tests/test_tz.py
  odoo/tools/safe_eval.py
Labels: 15.0

#27185 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/js/PaymentScreen.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/views/ir_sequence_views.xml
  odoo/tools/safe_eval.py
Labels: 16.0

#27188 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/account_move_views.xml
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/models/analytic_mixin.py
  addons/crm/models/res_partner.py
  addons/hr_recruitment/models/hr_recruitment_source.py
  addons/hr_recruitment/tests/test_utm.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/l10n_in/models/account_invoice.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale_crm/models/crm_lead.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_sale/views/templates.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/tools/safe_eval.py
Labels: saas-16.3

#27189 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/chart_template.py
  addons/account/static/src/scss/account_searchpanel.scss
  addons/account/views/account_account_views.xml
  addons/account/views/account_move_views.xml
  addons/crm/models/res_partner.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_project_task_quick_create.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_project/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_sale/views/templates.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/tools/safe_eval.py
Labels: saas-16.4

#27190 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move_line.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/js/PaymentScreen.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/views/ir_sequence_views.xml
Labels: staging.16.0

#27192 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/account_move_views.xml
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/models/analytic_mixin.py
  addons/crm/models/res_partner.py
  addons/hr_recruitment/models/hr_recruitment_source.py
  addons/hr_recruitment/tests/test_utm.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/l10n_in/models/account_invoice.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale_crm/models/crm_lead.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_sale/views/templates.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/tools/safe_eval.py
Labels: tmp.saas-16.3

#27193 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/chart_template.py
  addons/account/static/src/scss/account_searchpanel.scss
  addons/account/views/account_account_views.xml
  addons/account/views/account_move_views.xml
  addons/crm/models/res_partner.py
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/tests/test_project_task_quick_create.py
  addons/sale_crm/models/crm_lead.py
  addons/sale_project/views/project_task_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/grid_layout.js
  addons/website/tests/test_grid_layout.py
  addons/website_blog/views/website_blog_posts_loop.xml
  addons/website_sale/views/templates.xml
  odoo/__init__.py
  odoo/addons/base/models/ir_cron.py
  odoo/tools/safe_eval.py
Labels: tmp.saas-16.4

#27194 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_cl/data/account_fiscal_template.xml
  addons/l10n_cl/data/l10n_cl_chart_data.xml
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/mail/static/src/models/messaging_initializer/messaging_initializer.js
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  odoo/addons/base/tests/test_tz.py
Labels: tmp.15.0

#27195 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/account_edi/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/js/PaymentScreen.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/views/ir_sequence_views.xml
Labels: tmp.16.0

#27198 Syncing from upstream odoo/odoo (14.0)
  odoo/addons/base/models/ir_module.py
Labels: 14.0

#27199 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ar/tests/common.py
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
Labels: 15.0

#27200 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_in/models/account_invoice.py
  addons/stock_account/models/stock_move.py
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/tests/test_tz.py
Labels: 16.0

#27203 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_payment.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_move_reversal_view.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/sale/models/account_move.py
  addons/stock/models/stock_picking.py
  addons/stock/static/src/stock_forecasted/stock_forecasted.js
  addons/stock/tests/test_packing.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/tests/test_tz.py
Labels: saas-16.3

#27204 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_payment.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_move_reversal_view.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/hr_recruitment/models/hr_recruitment_source.py
  addons/hr_recruitment/tests/test_utm.py
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/sale/views/sale_portal_templates.xml
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_account/models/stock_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/tests/test_tz.py
Labels: saas-16.4

#27205 Syncing from upstream odoo/odoo (staging.14.0)
  addons/auth_signup/i18n/zh_TW.po
  addons/base_setup/i18n/es_MX.po
  addons/crm/i18n/pt.po
  addons/crm_iap_lead/i18n/sv.po
  addons/crm_sms/i18n/pt.po
  addons/delivery/i18n/es_MX.po
  addons/event/i18n/ca.po
  addons/event_crm/i18n/sv.po
  addons/event_sale/i18n/pt.po
  addons/event_sms/i18n/pt.po
  addons/hr_presence/i18n/pt.po
  addons/hr_timesheet/i18n/lv.po
  addons/im_livechat/i18n/pt.po
  addons/mail/i18n/ca.po
  addons/mail/i18n/pt.po
  addons/mass_mailing_sms/i18n/pt.po
  addons/mrp/i18n/es_MX.po
  addons/payment/i18n/es_MX.po
  addons/point_of_sale/i18n/es_MX.po
  addons/point_of_sale/i18n/pt.po
  addons/pos_restaurant/i18n/pt.po
  addons/product/i18n/es_MX.po
  addons/product/i18n/pt.po
  addons/purchase/i18n/es_MX.po
  addons/purchase_stock/i18n/es_MX.po
  addons/sale/i18n/pt.po
  addons/sale_management/i18n/pt.po
  addons/sale_quotation_builder/i18n/pt.po
  addons/sms/i18n/pt.po
  addons/sms/i18n/vi.po
  addons/stock/i18n/es_MX.po
  addons/stock/i18n/ja.po
  addons/stock/i18n/sk.po
  addons/stock_sms/i18n/pt.po
  addons/web_editor/i18n/lv.po
  addons/website/i18n/pt.po
  addons/website_blog/i18n/vi.po
  addons/website_crm/i18n/pt.po
  addons/website_event/i18n/es_MX.po
  addons/website_event_questions/i18n/pt.po
  addons/website_event_sale/i18n/pt.po
  addons/website_event_track/i18n/pt.po
  addons/website_form/i18n/pt.po
  addons/website_forum/i18n/fi.po
  addons/website_hr_recruitment/i18n/pt.po
  addons/website_livechat/i18n/pt.po
  addons/website_sale/i18n/zh_TW.po
  addons/website_sale_delivery/i18n/de.po
  addons/website_sale_slides/i18n/pt.po
  addons/website_slides/i18n/cs.po
  addons/website_slides/i18n/da.po
  addons/website_slides/i18n/lt.po
  addons/website_slides/i18n/pt.po
  addons/website_slides_forum/i18n/lt.po
  addons/website_sms/i18n/pt.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/addons/base/models/ir_module.py
Labels: staging.14.0

#27206 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_in/models/account_invoice.py
  addons/stock_account/models/stock_move.py
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/tests/test_tz.py
  odoo/tools/safe_eval.py
Labels: staging.16.0

#27208 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_payment.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_move_reversal_view.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/sale/models/account_move.py
  addons/stock/models/stock_picking.py
  addons/stock/static/src/stock_forecasted/stock_forecasted.js
  addons/stock/tests/test_packing.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/tests/test_tz.py
Labels: tmp.saas-16.3

#27209 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move_line.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_payment.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_move_reversal_view.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/delivery/data/neutralize.sql
  addons/delivery_mondialrelay/data/neutralize.sql
  addons/hr_recruitment/models/hr_recruitment_source.py
  addons/hr_recruitment/tests/test_utm.py
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_dropshipping/models/stock_picking.py
  addons/sale/views/sale_portal_templates.xml
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_account/models/stock_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/addons/base/tests/test_tz.py
Labels: tmp.saas-16.4

#27210 Syncing from upstream odoo/odoo (tmp.14.0)
  addons/auth_signup/i18n/zh_TW.po
  addons/base_setup/i18n/es_MX.po
  addons/crm/i18n/pt.po
  addons/crm_iap_lead/i18n/sv.po
  addons/crm_sms/i18n/pt.po
  addons/delivery/i18n/es_MX.po
  addons/event/i18n/ca.po
  addons/event_crm/i18n/sv.po
  addons/event_sale/i18n/pt.po
  addons/event_sms/i18n/pt.po
  addons/hr_presence/i18n/pt.po
  addons/hr_timesheet/i18n/lv.po
  addons/im_livechat/i18n/pt.po
  addons/mail/i18n/ca.po
  addons/mail/i18n/pt.po
  addons/mass_mailing_sms/i18n/pt.po
  addons/mrp/i18n/es_MX.po
  addons/payment/i18n/es_MX.po
  addons/point_of_sale/i18n/es_MX.po
  addons/point_of_sale/i18n/pt.po
  addons/pos_restaurant/i18n/pt.po
  addons/product/i18n/es_MX.po
  addons/product/i18n/pt.po
  addons/purchase/i18n/es_MX.po
  addons/purchase_stock/i18n/es_MX.po
  addons/sale/i18n/pt.po
  addons/sale_management/i18n/pt.po
  addons/sale_quotation_builder/i18n/pt.po
  addons/sms/i18n/pt.po
  addons/sms/i18n/vi.po
  addons/stock/i18n/es_MX.po
  addons/stock/i18n/ja.po
  addons/stock/i18n/sk.po
  addons/stock_sms/i18n/pt.po
  addons/web_editor/i18n/lv.po
  addons/website/i18n/pt.po
  addons/website_blog/i18n/vi.po
  addons/website_crm/i18n/pt.po
  addons/website_event/i18n/es_MX.po
  addons/website_event_questions/i18n/pt.po
  addons/website_event_sale/i18n/pt.po
  addons/website_event_track/i18n/pt.po
  addons/website_form/i18n/pt.po
  addons/website_forum/i18n/fi.po
  addons/website_hr_recruitment/i18n/pt.po
  addons/website_livechat/i18n/pt.po
  addons/website_sale/i18n/zh_TW.po
  addons/website_sale_delivery/i18n/de.po
  addons/website_sale_slides/i18n/pt.po
  addons/website_slides/i18n/cs.po
  addons/website_slides/i18n/da.po
  addons/website_slides/i18n/lt.po
  addons/website_slides/i18n/pt.po
  addons/website_slides_forum/i18n/lt.po
  addons/website_sms/i18n/pt.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/addons/base/models/ir_module.py
Labels: tmp.14.0

#27211 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ar/tests/common.py
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  odoo/tools/safe_eval.py
Labels: tmp.15.0

#27214 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/ir_module.py
Labels: 15.0

#27215 Syncing from upstream odoo/odoo (16.0)
  addons/account/views/account_reconcile_model_views.xml
  addons/event_sale/report/event_event_templates.xml
  addons/l10n_bg/data/tax_report.xml
  addons/l10n_bg/i18n/bg.po
  addons/l10n_bg/i18n/l10n_bg.pot
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_link_preview.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/chat_window_header/chat_window_header.xml
  addons/mail/tests/test_link_preview.py
  addons/mrp/models/stock_rule.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_stock/models/purchase.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  doc/cla/corporate/adhoc.md
  odoo/addons/base/models/ir_module.py
Labels: 16.0

#27217 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_account.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_all_l10n.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/models/utils/order_change.js
  addons/point_of_sale/static/tests/tours/barcode_scanning_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/static/src/scss/project_form.scss
  addons/project/views/project_task_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale/models/analytic.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/@types/pivot.d.ts
  addons/spreadsheet/static/src/helpers/constants.js
  addons/spreadsheet/static/src/pivot/pivot_table.js
  addons/spreadsheet/static/src/pivot/plugins/pivot_core_plugin.js
  addons/spreadsheet/static/tests/pivots/model/pivot_plugin_test.js
  addons/spreadsheet/static/tests/utils/pivot.js
  addons/web/static/src/search/search_arch_parser.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/tests/core/template_inheritance.test.js
  addons/web/static/tests/legacy/views/fields/statusbar_field_tests.js
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/website/models/mixins.py
  addons/website_customer/models/res_partner.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  odoo/addons/base/models/ir_actions.py
Labels: master

#27218 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/purchase_mrp/report/mrp_report_mo_overview.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/web/static/lib/bootstrap/scss/_carousel.scss
  addons/web/static/src/legacy/scss/fontawesome_overridden.scss
  addons/web/static/src/views/kanban/kanban_arch_parser.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/tests/views/kanban/kanban_arch_parser_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/web_tour/static/src/tour_pointer/tour_pointer.js
  addons/web_tour/static/tests/tour_service_tests.js
  addons/website_sale_slides/views/website_sale_templates.xml
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/tours/slides_tour.js
  odoo/addons/base/models/ir_module.py
Labels: saas-16.3

#27219 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/static/src/stock_forecasted/stock_forecasted.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/views/kanban/kanban_arch_parser.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/kanban/kanban_arch_parser_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/website_sale_slides/views/website_sale_templates.xml
  odoo/addons/base/models/ir_module.py
Labels: saas-16.4

#27220 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/views/account_reconcile_model_views.xml
  addons/event_sale/report/event_event_templates.xml
  addons/l10n_bg/data/tax_report.xml
  addons/l10n_bg/i18n/bg.po
  addons/l10n_bg/i18n/l10n_bg.pot
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_link_preview.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/chat_window_header/chat_window_header.xml
  addons/mail/tests/test_link_preview.py
  addons/mrp/models/stock_rule.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_stock/models/purchase.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  doc/cla/corporate/adhoc.md
  odoo/addons/base/models/ir_module.py
Labels: staging.16.0

#27221 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_account.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_all_l10n.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/hr_expense/static/src/components/qrcode_action.js
  addons/hr_expense/static/src/components/qrcode_action.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mrp/models/stock_move.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/models/utils/order_change.js
  addons/point_of_sale/static/tests/tours/barcode_scanning_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/project/static/src/scss/project_form.scss
  addons/project/views/project_task_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/sale/models/analytic.py
  addons/sale_timesheet/views/project_task_views.xml
  addons/spreadsheet/static/src/@types/pivot.d.ts
  addons/spreadsheet/static/src/helpers/constants.js
  addons/spreadsheet/static/src/pivot/pivot_table.js
  addons/spreadsheet/static/src/pivot/plugins/pivot_core_plugin.js
  addons/spreadsheet/static/tests/pivots/model/pivot_plugin_test.js
  addons/spreadsheet/static/tests/utils/pivot.js
  addons/web/static/src/search/search_arch_parser.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/tests/core/template_inheritance.test.js
  addons/web/static/tests/legacy/views/fields/statusbar_field_tests.js
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/website/models/mixins.py
  addons/website_customer/models/res_partner.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  odoo/addons/base/models/ir_actions.py
Labels: tmp.master

#27223 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/res_company.py
  addons/l10n_de/views/res_company_views.xml
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/static/src/stock_forecasted/stock_forecasted.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/views/kanban/kanban_arch_parser.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/web/static/tests/views/kanban/kanban_arch_parser_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/website_sale_slides/views/website_sale_templates.xml
  odoo/addons/base/models/ir_module.py
Labels: tmp.saas-16.4

#27224 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
  addons/mail/models/mail_thread.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/ir_module.py
Labels: tmp.15.0

#27225 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/views/account_reconcile_model_views.xml
  addons/event_sale/report/event_event_templates.xml
  addons/l10n_bg/data/tax_report.xml
  addons/l10n_bg/i18n/bg.po
  addons/l10n_bg/i18n/l10n_bg.pot
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_link_preview.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/components/chat_window_header/chat_window_header.xml
  addons/mail/tests/test_link_preview.py
  addons/mrp/models/stock_rule.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_stock/models/purchase.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  doc/cla/corporate/adhoc.md
  odoo/addons/base/models/ir_module.py
Labels: tmp.16.0

#27226 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_payment_term.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_move_reversal_view.xml
  addons/hr_attendance/controllers/main.py
  addons/hr_attendance/models/res_company.py
  addons/hr_org_chart/__init__.py
  addons/hr_org_chart/__manifest__.py
  addons/mail/models/models.py
  addons/mrp/tests/test_byproduct.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/product/models/product_catalog_mixin.py
  addons/purchase/models/purchase_order.py
  addons/sale/models/sale_order.py
  addons/spreadsheet/static/src/pivot/pivot_actions.js
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/static/src/stock_forecasted/stock_forecasted.js
  addons/stock_account/models/stock_move.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message.py
  addons/test_mail/tests/test_performance.py
  addons/web/__manifest__.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/core/position_hook.js
  addons/web/static/src/core/utils/draggable_hook_builder.js
  addons/web/static/src/polyfills/array.js
  addons/web/static/src/polyfills/object.js
  addons/web/static/tests/core/position_hook_tests.js
  addons/website/static/src/components/autocomplete_with_pages/url_autocomplete.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_links/static/src/js/website_links.js
  addons/website_links/static/src/js/website_links_charts.js
  addons/website_sale_loyalty/static/src/js/website_sale_gift_card.js
  addons/website_sale_slides/views/website_sale_templates.xml
  odoo/addons/base/models/ir_module.py
Labels: tmp.17.0

#27231 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/es_MX.po
  addons/account/i18n/vi.po
  addons/account_edi_ubl_cii/i18n/vi.po
  addons/base_import/i18n/vi.po
  addons/calendar/i18n/es.po
  addons/crm/i18n/es.po
  addons/digest/i18n/vi.po
  addons/event_booth/i18n/vi.po
  addons/event_sale/i18n/zh_TW.po
  addons/fetchmail_outlook/i18n/vi.po
  addons/google_calendar/i18n/vi.po
  addons/google_recaptcha/i18n/vi.po
  addons/hr/i18n/vi.po
  addons/hr_contract/i18n/es_MX.po
  addons/hr_contract/i18n/vi.po
  addons/hr_expense/i18n/vi.po
  addons/hr_holidays_attendance/i18n/vi.po
  addons/hr_recruitment/i18n/es_MX.po
  addons/hr_work_entry_contract/i18n/es_MX.po
  addons/hr_work_entry_contract/i18n/vi.po
  addons/http_routing/i18n/vi.po
  addons/link_tracker/i18n/vi.po
  addons/lunch/i18n/vi.po
  addons/mail/i18n/vi.po
  addons/mail_plugin/i18n/vi.po
  addons/maintenance/i18n/vi.po
  addons/mass_mailing_sms/i18n/es_MX.po
  addons/membership/i18n/vi.po
  addons/microsoft_outlook/i18n/vi.po
  addons/phone_validation/i18n/vi.po
  addons/point_of_sale/i18n/vi.po
  addons/portal_rating/i18n/vi.po
  addons/project_mail_plugin/i18n/vi.po
  addons/purchase/i18n/es_MX.po
  addons/purchase_requisition/i18n/es_MX.po
  addons/rating/i18n/vi.po
  addons/resource/i18n/vi.po
  addons/sale_timesheet/i18n/vi.po
  addons/snailmail/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/survey/i18n/es_MX.po
  addons/survey/i18n/vi.po
  addons/transifex/i18n/vi.po
  addons/uom/i18n/vi.po
  addons/utm/i18n/vi.po
  addons/web/i18n/es_MX.po
  addons/web_unsplash/i18n/vi.po
  addons/website/i18n/vi.po
  addons/website_event_booth/i18n/vi.po
  addons/website_event_track/i18n/vi.po
  addons/website_event_track_live/i18n/vi.po
  addons/website_forum/i18n/vi.po
  addons/website_hr_recruitment/i18n/vi.po
  addons/website_mass_mailing/i18n/vi.po
  addons/website_profile/i18n/vi.po
  addons/website_sale/i18n/vi.po
  addons/website_sale_slides/i18n/vi.po
  addons/website_slides_forum/i18n/vi.po
  addons/website_slides_survey/i18n/vi.po
  odoo/addons/base/i18n/es_MX.po
Labels: saas-15.2

#27233 Syncing from upstream odoo/odoo (saas-16.3)
  addons/event_sale/report/event_event_templates.xml
  doc/cla/corporate/adhoc.md
Labels: saas-16.3

#27235 Syncing from upstream odoo/odoo (tmp.17.0)
  doc/cla/corporate/adhoc.md
Labels: tmp.17.0

#27236 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account_tax_report_data.xml
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/migrations/3.8/post-migrate_update_taxes.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
Labels: 16.0

#27237 Syncing from upstream odoo/odoo (17.0)
  addons/l10n_in/models/account_invoice.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/tests/test_move_export.py
Labels: 17.0

#27248 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_vat/models/res_partner.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: 15.0

#27249 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/res_config_settings.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/mrp/tests/test_multicompany.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/stock/models/stock_warehouse.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/primary_variables.scss
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/src/views/widgets/ribbon/ribbon.scss
  addons/web/static/src/webclient/icons.scss
  addons/web/static/src/webclient/webclient.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res_country_data.xml
Labels: 16.0

#27252 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/chart_template.py
  addons/account/models/res_config_settings.py
  addons/account/views/account_reconcile_model_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_vat/views/res_partner_views.xml
  addons/delivery/models/sale_order.py
  addons/hr_expense/static/src/views/list.xml
  addons/l10n_es_edi_facturae/__init__.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/stock_rule.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/utils/timing.js
  addons/web/static/tests/core/utils/timing_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_website_sale_cart.py
  odoo/addons/base/data/res_country_data.xml
Labels: saas-16.3

#27253 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/res_config_settings.py
  addons/account/views/account_move_views.xml
  addons/account/views/account_reconcile_model_views.xml
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/views/res_partner_views.xml
  addons/l10n_es_edi_facturae/__init__.py
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_order.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/website/static/src/js/editor/snippets.editor.js
  odoo/addons/base/data/res_country_data.xml
Labels: saas-16.4

#27255 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/res_config_settings.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/mrp/tests/test_multicompany.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/stock/models/stock_warehouse.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/primary_variables.scss
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/src/views/widgets/ribbon/ribbon.scss
  addons/web/static/src/webclient/icons.scss
  addons/web/static/src/webclient/webclient.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.16.0

#27256 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/res_config_settings.py
  addons/account/views/account_reconcile_model_views.xml
  addons/base_vat/views/res_partner_views.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_skills/static/src/fields/skills_one2many/skills_one2many.js
  addons/hr_skills/views/hr_views.xml
  addons/l10n_it/data/template/account.tax-it.csv
  addons/mail/models/mail_thread.py
  addons/mrp/models/stock_rule.py
  addons/sale_async_emails/__init__.py
  addons/sale_async_emails/__manifest__.py
  addons/sale_async_emails/data/ir_config_parameter.xml
  addons/sale_async_emails/data/ir_cron.xml
  addons/sale_async_emails/models/__init__.py
  addons/sale_async_emails/models/sale_order.py
  addons/sale_async_emails/tests/__init__.py
  addons/sale_async_emails/tests/test_sale_order.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web_editor/controllers/main.py
  addons/web_editor/i18n/web_editor.pot
  addons/website/models/website.py
  doc/cla/individual/gugizm.md
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.17.0

#27257 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
Labels: 15.0

#27258 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/base_vat/models/res_partner.py
  addons/hr_attendance/security/hr_attendance_security.xml
  addons/hr_attendance/security/ir.model.access.csv
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/purchase_requisition_stock/tests/test_purchase_requisition_stock.py
  addons/purchase_requisition_stock/wizard/purchase_requisition_create_alternative.py
  addons/sale_expense/models/hr_expense_sheet.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/stock/wizard/stock_lot_label_layout.py
Labels: 16.0

#27261 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/base_vat/models/res_partner.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_examples_dialog.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
Labels: saas-16.3

#27262 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/partner.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_vat/models/res_partner.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/delivery/models/sale_order.py
  addons/hr_expense/static/src/views/list.xml
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_mrp/report/mrp_report_mo_overview.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/stock/models/stock_move.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_website_sale_cart.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: saas-16.4

#27263 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/res_config_settings.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/base_vat/models/res_partner.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/hr_attendance/security/hr_attendance_security.xml
  addons/hr_attendance/security/ir.model.access.csv
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/mrp/tests/test_multicompany.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_requisition_stock/tests/test_purchase_requisition_stock.py
  addons/purchase_requisition_stock/wizard/purchase_requisition_create_alternative.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/sale_expense/models/hr_expense_sheet.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/stock/models/stock_warehouse.py
  addons/stock/wizard/stock_lot_label_layout.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/scss/bootstrap_overridden.scss
  addons/web/static/src/scss/primary_variables.scss
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/src/views/widgets/ribbon/ribbon.scss
  addons/web/static/src/webclient/icons.scss
  addons/web/static/src/webclient/webclient.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website/static/src/snippets/s_searchbar/000.js
  addons/website_crm_partner_assign/static/src/js/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/addons/base/data/res_country_data.xml
Labels: staging.16.0

#27265 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/chart_template.py
  addons/account/models/res_config_settings.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/views/account_reconcile_model_views.xml
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/views/res_partner_views.xml
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/delivery/models/sale_order.py
  addons/hr_expense/static/src/views/list.xml
  addons/l10n_es_edi_facturae/__init__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/stock_rule.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web/static/src/core/utils/timing.js
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_examples_dialog.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/core/utils/timing_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_website_sale_cart.py
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.saas-16.3

#27266 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/models/res_config_settings.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/views/account_move_views.xml
  addons/account/views/account_reconcile_model_views.xml
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/models/analytic_mixin.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/views/res_partner_views.xml
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/delivery/models/sale_order.py
  addons/hr_expense/static/src/views/list.xml
  addons/l10n_es_edi_facturae/__init__.py
  addons/l10n_pl_jpk/models/l10n_pl_tax_office.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/mail/models/mail_thread.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase_mrp/report/mrp_report_mo_overview.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/stock/models/stock_move.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/i18n/web.pot
  addons/web/static/src/core/commands/command_items.xml
  addons/web/static/src/core/commands/command_service.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/website/__manifest__.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.js
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.js
  addons/website/static/src/components/fullscreen_indication/fullscreen_indication.xml
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/tests/test_website_sale_cart.py
  odoo/addons/base/data/res_country_data.xml
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: tmp.saas-16.4

#27267 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
Labels: tmp.15.0

#27268 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/base_vat/models/res_partner.py
  addons/hr_attendance/security/hr_attendance_security.xml
  addons/hr_attendance/security/ir.model.access.csv
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi/wizard/account_move_reversal_views.xml
  addons/purchase_requisition_stock/tests/test_purchase_requisition_stock.py
  addons/purchase_requisition_stock/wizard/purchase_requisition_create_alternative.py
  addons/sale_expense/models/hr_expense_sheet.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/stock/wizard/stock_lot_label_layout.py
Labels: tmp.16.0

#27269 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/tests/test_transfer_wizard.py
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_automation/models/base_automation.py
  addons/base_automation/tests/test_automation.py
  addons/base_vat/models/res_partner.py
  addons/crm/data/crm_lead_demo.xml
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead.py
  addons/hr_expense/static/src/views/list.xml
  addons/hr_homeworking/static/src/calendar/common/calender_common_renderer.xml
  addons/http_routing/views/res_lang_views.xml
  addons/l10n_es_edi_facturae/__init__.py
  addons/payment/data/payment_method_data.xml
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/models/project_project.py
  addons/purchase_mrp/report/mrp_report_mo_overview.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_rules.py
  addons/sale_project/tests/test_child_tasks.py
  addons/stock/models/stock_move.py
  addons/web/static/src/core/record_selectors/multi_record_selector.xml
  addons/web/static/src/core/record_selectors/record_selector.xml
  addons/web/static/src/polyfills/array.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/website_blog/tests/test_performance.py
  addons/website_payment/static/src/snippets/s_donation/options.js
  addons/website_sale_mondialrelay/controllers/controllers.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/tests/test_ir_actions.py
Labels: tmp.17.0

#27270 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/account.pot
  addons/account/wizard/account_payment_register.py
  addons/calendar/models/calendar_attendee.py
  addons/calendar/tests/test_calendar.py
  addons/stock/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/http.py
  odoo/tools/translate.py
Labels: 15.0

#27271 Syncing from upstream odoo/odoo (16.0)
  addons/account/tests/test_ir_actions_report.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/http.py
Labels: 16.0

#27274 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/tests/test_chart_template.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/l10n_be/demo/account_demo.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_san_marino.xml
  addons/mrp/tests/test_multicompany.py
  addons/sale_expense/models/hr_expense_sheet.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/stock/models/stock_warehouse.py
  odoo/addons/base/views/ir_sequence_views.xml
Labels: saas-16.3

#27275 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_peppol/models/res_config_settings.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_san_marino.xml
  addons/mrp/tests/test_multicompany.py
  addons/mrp_account/models/mrp_bom.py
  addons/mrp_account/tests/test_mrp_account.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/sale_expense/models/hr_expense_sheet.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/lib/bootstrap/scss/_carousel.scss
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/utils/timing.js
  addons/web/static/src/legacy/scss/fontawesome_overridden.scss
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_examples_dialog.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/core/utils/timing_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/content/snippets.animation.js
  odoo/addons/base/views/ir_sequence_views.xml
Labels: saas-16.4

#27278 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_peppol/models/res_config_settings.py
  addons/hr_holidays/static/src/views/calendar/calendar_model.js
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_san_marino.xml
  addons/mrp/tests/test_multicompany.py
  addons/mrp_account/models/mrp_bom.py
  addons/mrp_account/tests/test_mrp_account.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/sale/static/src/js/sale_product_field.js
  addons/sale/static/tests/sale_product_field_tests.js
  addons/sale_expense/models/hr_expense_sheet.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/stock/models/stock_warehouse.py
  addons/web/static/lib/bootstrap/scss/_carousel.scss
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/utils/timing.js
  addons/web/static/src/legacy/scss/fontawesome_overridden.scss
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/properties/property_value.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/relational_utils.xml
  addons/web/static/src/views/kanban/kanban_examples_dialog.scss
  addons/web/static/tests/core/autocomplete_tests.js
  addons/web/static/tests/core/utils/timing_tests.js
  addons/web/static/tests/views/fields/many2many_tags_field_tests.js
  addons/web/static/tests/views/fields/many2one_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/scss/web_editor.frontend.scss
  addons/website/static/src/js/content/snippets.animation.js
  odoo/addons/base/views/ir_sequence_views.xml
Labels: tmp.saas-16.4

#27279 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/wizard/account_payment_register.py
  addons/calendar/models/calendar_attendee.py
  addons/calendar/tests/test_calendar.py
  addons/stock/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website/static/src/snippets/s_table_of_content/000.js
  odoo/addons/base/models/ir_mail_server.py
  odoo/http.py
  odoo/tools/translate.py
Labels: tmp.15.0

#27280 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/tests/test_ir_actions_report.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/http.py
Labels: tmp.16.0

#27282 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/tests/test_ubl_cii.py
  addons/digest/models/res_users.py
  addons/l10n_es/data/account_tax_data.xml
  addons/resource/models/res_users.py
  addons/stock/views/stock_move_line_views.xml
  addons/survey/data/survey_demo_quiz_user_input_line.xml
  addons/uom/models/uom_uom.py
  addons/website/__init__.py
  addons/website/__manifest__.py
  addons/website/controllers/main.py
  addons/website/data/update_theme_images.xml
  addons/website/models/ir_module_module.py
Labels: 15.0

#27283 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/wizard/account_payment_register.py
  addons/calendar/models/calendar_attendee.py
  addons/calendar/tests/test_calendar.py
  addons/digest/models/res_users.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_holidays/i18n/es_CR.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_picking.py
  addons/website_sale/tests/test_website_sale_snippets.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/translate.py
Labels: 16.0

#27286 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mail/models/mail_link_preview.py
  addons/mail/tests/test_link_preview.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/http.py
  odoo/tools/translate.py
Labels: saas-16.3

#27287 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/tests/test_chart_template.py
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/crm/i18n/ro.po
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_be/demo/account_demo.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/tests/test_report_session.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/graph/graph_renderer.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_hr_recruitment/static/tests/tours/website_hr_recruitment.js
  addons/website_hr_recruitment/tests/test_website_hr_recruitment.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/http.py
  odoo/tools/translate.py
Labels: saas-16.4

#27290 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_de/migrations/2.0/pre-migrate.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/mail/models/mail_link_preview.py
  addons/mail/tests/test_link_preview.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/http.py
  odoo/tools/translate.py
Labels: tmp.saas-16.3

#27291 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/tests/test_chart_template.py
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/crm/i18n/ro.po
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/l10n_be/demo/account_demo.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/tests/test_report_session.py
  addons/point_of_sale/wizard/pos_payment.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/graph/graph_renderer.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_hr_recruitment/static/tests/tours/website_hr_recruitment.js
  addons/website_hr_recruitment/tests/test_website_hr_recruitment.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/http.py
  odoo/tools/translate.py
Labels: tmp.saas-16.4

#27292 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/tests/test_ubl_cii.py
  addons/digest/models/res_users.py
  addons/l10n_es/data/account_tax_data.xml
  addons/resource/models/res_users.py
  addons/stock/views/stock_move_line_views.xml
  addons/survey/data/survey_demo_quiz_user_input_line.xml
  addons/uom/models/uom_uom.py
  addons/website/__init__.py
  addons/website/__manifest__.py
  addons/website/controllers/main.py
  addons/website/data/update_theme_images.xml
  addons/website/models/ir_module_module.py
Labels: tmp.15.0

#27293 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/wizard/account_payment_register.py
  addons/calendar/models/calendar_attendee.py
  addons/calendar/tests/test_calendar.py
  addons/digest/models/res_users.py
  addons/google_calendar/models/calendar.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_holidays/i18n/es_CR.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_picking.py
  addons/website_sale/tests/test_website_sale_snippets.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/translate.py
Labels: tmp.16.0

#27295 Syncing from upstream odoo/odoo (15.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account_fleet/__init__.py
  addons/account_fleet/tests/__init__.py
  addons/account_fleet/tests/test_account_fleet.py
  addons/account_fleet/wizard/__init__.py
  addons/account_fleet/wizard/account_automatic_entry_wizard.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_access_rights.py
  addons/l10n_de/i18n/de.po
  addons/phone_validation/models/phone_blacklist.py
  addons/phone_validation/tests/__init__.py
  addons/phone_validation/tests/test_phonenumbers_blacklist.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/wysiwyg/PeerToPeer.js
Labels: 15.0

#27296 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_din5008/i18n/de.po
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_restaurant/static/src/js/Screens/FloorScreen/FloorScreen.js
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_move2.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/uom/models/uom_uom.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteForward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website/controllers/main.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_event/static/tests/tours/website_event.js
  addons/website_sale/static/src/js/tours/website_sale_shop.js
Labels: 16.0

#27299 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/wizard/account_payment_register.py
  addons/calendar/models/calendar_attendee.py
  addons/calendar/tests/test_calendar.py
  addons/digest/models/res_users.py
  addons/l10n_din5008/i18n/de.po
  addons/mail/static/src/web/activity/activity_cell.scss
  addons/mail/static/src/web/activity/activity_cell.xml
  addons/stock/wizard/stock_lot_label_layout.py
  addons/survey/tests/test_survey.py
  addons/uom/models/uom_uom.py
  addons/website_sale/models/product_template.py
Labels: saas-16.3

#27300 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/i18n/account.pot
  addons/account/static/src/scss/account_journal_dashboard.scss
  addons/account/wizard/account_payment_register.py
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_peppol/__init__.py
  addons/account_peppol/__manifest__.py
  addons/digest/models/res_users.py
  addons/l10n_din5008/i18n/de.po
  addons/point_of_sale/models/pos_config.py
  addons/stock/wizard/stock_lot_label_layout.py
  addons/survey/tests/test_survey_invite.py
  addons/survey/wizard/survey_invite.py
  addons/uom/models/uom_uom.py
  addons/website_sale/models/product_template.py
Labels: saas-16.4

#27301 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_din5008/i18n/de.po
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_restaurant/static/src/js/Screens/FloorScreen/FloorScreen.js
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_move2.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/uom/models/uom_uom.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteForward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/enter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/powerbox/Powerbox.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/utils.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website/controllers/main.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_event/static/tests/tours/website_event.js
  addons/website_sale/static/src/js/tours/website_sale_shop.js
Labels: staging.16.0
