Repository brain-tec/odoo, pull requests merged in 2024-08, with the labels that each got.

#28429 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/website_links/static/src/js/website_links.js
Labels: 15.0

#28433 Syncing from upstream odoo/odoo (saas-17.1)
  addons/account/models/account_move.py
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/template/account.fiscal.position-fi.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_fi/data/template/account.tax.group-fi.csv
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/l10n_fi/migrations/13.0.2/end-migrate_update_taxes.py
  addons/l10n_it_edi/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_discount/models/__init__.py
  addons/pos_discount/models/pos_session.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/src/overrides/models/models.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/debug/profiling/profiling_qweb.scss
  addons/web/static/tests/mobile/core/action_swiper_tests.js
Labels: saas-17.1

#28435 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/mail_message.py
  addons/account/tests/test_audit_trail.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/res_partner.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_pe_pos/models/res_partner.py
  addons/l10n_pe_pos/static/src/overrides/models/pos_store.js
  addons/mail/static/src/core/common/chat_bubble.dark.scss
  addons/mail/static/src/core/common/chat_bubble.scss
  addons/mail/static/src/core/common/chat_bubble.xml
  addons/mail/static/src/core/common/chat_hub.dark.scss
  addons/mail/static/src/core/common/chat_hub.scss
  addons/mail/static/src/core/common/chat_hub.xml
  addons/mail/static/src/core/common/core.scss
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/activity/activity.test.js
  addons/point_of_sale/models/res_company.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/portal/static/tests/tours/skip_to_content.js
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/unit/utils.js
  addons/pos_restaurant/static/src/app/floor_screen/floor_screen.js
  addons/repair/models/stock_lot.py
  addons/repair/tests/test_repair.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/stock_fleet/views/stock_picking_type.xml
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/stock_picking_batch/views/stock_picking_wave_views.xml
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/tests/legacy/mobile/core/action_swiper_tests.js
Labels: saas-17.4

#28437 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/account/models/account_move.py
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/template/account.fiscal.position-fi.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_fi/data/template/account.tax.group-fi.csv
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/l10n_fi/migrations/13.0.2/end-migrate_update_taxes.py
  addons/l10n_it_edi/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_discount/models/__init__.py
  addons/pos_discount/models/pos_session.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/src/overrides/models/models.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/debug/profiling/profiling_qweb.scss
  addons/web/static/tests/mobile/core/action_swiper_tests.js
Labels: staging.saas-17.1

#28439 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/mail_message.py
  addons/account/tests/test_audit_trail.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/res_partner.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_pe_pos/models/res_partner.py
  addons/l10n_pe_pos/static/src/overrides/models/pos_store.js
  addons/mail/static/src/core/common/chat_bubble.dark.scss
  addons/mail/static/src/core/common/chat_bubble.scss
  addons/mail/static/src/core/common/chat_bubble.xml
  addons/mail/static/src/core/common/chat_hub.dark.scss
  addons/mail/static/src/core/common/chat_hub.scss
  addons/mail/static/src/core/common/chat_hub.xml
  addons/mail/static/src/core/common/core.scss
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/activity/activity.test.js
  addons/point_of_sale/models/res_company.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/portal/static/tests/tours/skip_to_content.js
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/unit/utils.js
  addons/pos_restaurant/static/src/app/floor_screen/floor_screen.js
  addons/repair/models/stock_lot.py
  addons/repair/tests/test_repair.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/stock_fleet/views/stock_picking_type.xml
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/stock_picking_batch/views/stock_picking_wave_views.xml
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/tests/legacy/mobile/core/action_swiper_tests.js
Labels: staging.saas-17.4

#28440 Syncing from upstream odoo/odoo (staging.15.0)
  addons/account/models/account_move.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/website_links/static/src/js/website_links.js
Labels: staging.15.0

#28441 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_vat/models/res_partner.py
  addons/event/controllers/main.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hw_drivers/main.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_it_edi/models/account_move.py
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_list/product_list.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/point_of_sale/static/src/app/store/db.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_loyalty/static/src/app/control_buttons/reward_button/reward_button.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_location.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web/static/tests/views/fields/datetime_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/models.py
  requirements.txt
Labels: staging.17.0

#28443 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/account/models/account_move.py
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/template/account.fiscal.position-fi.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_fi/data/template/account.tax.group-fi.csv
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/l10n_fi/migrations/13.0.2/end-migrate_update_taxes.py
  addons/l10n_it_edi/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_discount/models/__init__.py
  addons/pos_discount/models/pos_session.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/src/overrides/models/models.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/debug/profiling/profiling_qweb.scss
  addons/web/static/tests/mobile/core/action_swiper_tests.js
Labels: tmp.saas-17.1

#28445 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/mail_message.py
  addons/account/tests/test_audit_trail.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/res_partner.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_pe_pos/models/res_partner.py
  addons/l10n_pe_pos/static/src/overrides/models/pos_store.js
  addons/mail/static/src/core/common/chat_bubble.dark.scss
  addons/mail/static/src/core/common/chat_bubble.scss
  addons/mail/static/src/core/common/chat_bubble.xml
  addons/mail/static/src/core/common/chat_hub.dark.scss
  addons/mail/static/src/core/common/chat_hub.scss
  addons/mail/static/src/core/common/chat_hub.xml
  addons/mail/static/src/core/common/core.scss
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/activity/activity.test.js
  addons/point_of_sale/models/res_company.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/portal/static/tests/tours/skip_to_content.js
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/unit/utils.js
  addons/pos_restaurant/static/src/app/floor_screen/floor_screen.js
  addons/repair/models/stock_lot.py
  addons/repair/tests/test_repair.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/stock_fleet/views/stock_picking_type.xml
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/stock_picking_batch/views/stock_picking_wave_views.xml
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/tests/legacy/mobile/core/action_swiper_tests.js
Labels: tmp.saas-17.4

#28446 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/website_links/static/src/js/website_links.js
Labels: tmp.15.0

#28447 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/im_livechat/models/mail_message.py
  addons/im_livechat/tests/chatbot_common.py
  addons/im_livechat/tests/test_message.py
  addons/l10n_lu/i18n_extra/de.po
  odoo/models.py
Labels: tmp.16.0

#28448 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/base_vat/models/res_partner.py
  addons/event/controllers/main.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hw_drivers/main.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_it_edi/models/account_move.py
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_list/product_list.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/point_of_sale/static/src/app/store/db.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_loyalty/static/src/app/control_buttons/reward_button/reward_button.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/stock/models/stock_location.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web/static/tests/views/fields/datetime_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/models.py
  requirements.txt
Labels: tmp.17.0

#28450 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
Labels: 15.0

#28451 Syncing from upstream odoo/odoo (16.0)
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/stock/views/res_config_settings_views.xml
  addons/test_website/tests/test_redirect.py
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/menu.js
  addons/website_links/static/src/js/website_links.js
Labels: 16.0

#28454 Syncing from upstream odoo/odoo (saas-17.1)
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/event/controllers/main.py
  addons/hw_drivers/main.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/mail/static/src/core/common/message.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/stock/models/stock_location.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/datetime_field_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/models.py
Labels: saas-17.1

#28455 Syncing from upstream odoo/odoo (saas-17.2)
  addons/bus/controllers/websocket.py
  addons/bus/models/bus_presence.py
  addons/bus/models/ir_websocket.py
  addons/bus/models/res_partner.py
  addons/bus/models/res_users.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/src/services/presence_service.js
  addons/bus/static/tests/legacy/im_status_tests.js
  addons/bus/tests/__init__.py
  addons/bus/tests/common.py
  addons/bus/tests/test_bus_presence.py
  addons/bus/tests/test_ir_websocket.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/tests/test_websocket_controller.py
  addons/bus/websocket.py
  addons/event/controllers/main.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/main.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/template/account.fiscal.position-fi.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_fi/data/template/account.tax.group-fi.csv
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/l10n_fi/migrations/13.0.2/end-migrate_update_taxes.py
  addons/mail/models/bus_presence.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/models/discuss/mail_guest.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/static/tests/legacy/helpers/unpatch_im_status_service.js
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/pos_discount/models/__init__.py
  addons/pos_discount/models/pos_session.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_discuss_full/tests/test_performance.py
  addons/web/models/ir_http.py
  addons/web/static/src/webclient/debug/profiling/profiling_qweb.scss
  addons/website/i18n/website.pot
  addons/website/static/src/components/edit_head_body_dialog/edit_head_body_dialog.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_links/static/src/js/website_links.js
  odoo/models.py
  odoo/tools/translate.py
Labels: saas-17.2

#28456 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/event/controllers/main.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/tests/test_expenses_access_rights.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hw_drivers/main.py
  addons/l10n_fr_account/tests/test_fec_export.py
  addons/l10n_fr_account/wizard/account_fr_fec_export_wizard.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_in/models/account_invoice.py
  addons/l10n_in/models/account_tax.py
  addons/l10n_in/static/src/helpers/hsn_summary.js
  addons/l10n_in/tests/test_hsn_summary.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_point_of_sale.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/sale/static/tests/tours/product_attribute_value_tour.js
  addons/sale/tests/test_product_attribute_value.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_picking.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/webclient/debug/profiling/profiling_qweb.scss
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_tour/static/src/tour_service/tour_compilers.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_links/static/src/js/website_links.js
  addons/website_sale/static/src/js/website_sale.editor.js
  odoo/addons/base/models/ir_filters.py
  odoo/addons/base/tests/test_ir_filters.py
  odoo/models.py
Labels: saas-17.4

#28458 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi/models/account_move.py
  addons/account_edi/views/account_move_views.xml
  addons/event/controllers/main.py
  addons/hw_drivers/main.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/mail/static/src/core/common/message.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/stock/models/stock_location.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/datetime_field_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/models.py
Labels: staging.saas-17.1

#28460 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/event/controllers/main.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/tests/test_expenses_access_rights.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hw_drivers/main.py
  addons/l10n_fr_account/tests/test_fec_export.py
  addons/l10n_fr_account/wizard/account_fr_fec_export_wizard.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_in/models/account_invoice.py
  addons/l10n_in/models/account_tax.py
  addons/l10n_in/static/src/helpers/hsn_summary.js
  addons/l10n_in/tests/test_hsn_summary.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_point_of_sale.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/sale/static/tests/tours/product_attribute_value_tour.js
  addons/sale/tests/test_product_attribute_value.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_picking.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/webclient/debug/profiling/profiling_qweb.scss
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_tour/static/src/tour_service/tour_compilers.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_links/static/src/js/website_links.js
  addons/website_sale/static/src/js/website_sale.editor.js
  odoo/addons/base/models/ir_filters.py
  odoo/addons/base/tests/test_ir_filters.py
  odoo/models.py
Labels: staging.saas-17.4

#28461 Syncing from upstream odoo/odoo (staging.15.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
Labels: staging.15.0

#28464 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/event/controllers/main.py
  addons/hw_drivers/main.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/mail/static/src/core/common/message.xml
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/stock/models/stock_location.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/datetime_field_tests.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/models.py
Labels: tmp.saas-17.1

#28465 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/bus/controllers/websocket.py
  addons/bus/models/bus_presence.py
  addons/bus/models/ir_websocket.py
  addons/bus/models/res_partner.py
  addons/bus/models/res_users.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/src/services/presence_service.js
  addons/bus/static/tests/legacy/im_status_tests.js
  addons/bus/tests/__init__.py
  addons/bus/tests/common.py
  addons/bus/tests/test_bus_presence.py
  addons/bus/tests/test_ir_websocket.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/tests/test_websocket_controller.py
  addons/bus/websocket.py
  addons/event/controllers/main.py
  addons/hr_holidays/tests/test_out_of_office.py
  addons/hw_drivers/main.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/template/account.fiscal.position-fi.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_fi/data/template/account.tax.group-fi.csv
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/l10n_fi/migrations/13.0.2/end-migrate_update_taxes.py
  addons/mail/models/bus_presence.py
  addons/mail/models/discuss/ir_websocket.py
  addons/mail/models/discuss/mail_guest.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/static/tests/legacy/helpers/unpatch_im_status_service.js
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/pos_discount/models/__init__.py
  addons/pos_discount/models/pos_session.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_discuss_full/tests/test_performance.py
  addons/web/models/ir_http.py
  addons/web/static/src/webclient/debug/profiling/profiling_qweb.scss
  addons/website/i18n/website.pot
  addons/website/static/src/components/edit_head_body_dialog/edit_head_body_dialog.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_links/static/src/js/website_links.js
  odoo/models.py
  odoo/tools/translate.py
Labels: tmp.saas-17.2

#28466 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/event/controllers/main.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/tests/test_expenses_access_rights.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hw_drivers/main.py
  addons/l10n_fr_account/tests/test_fec_export.py
  addons/l10n_fr_account/wizard/account_fr_fec_export_wizard.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_in/models/account_invoice.py
  addons/l10n_in/models/account_tax.py
  addons/l10n_in/static/src/helpers/hsn_summary.js
  addons/l10n_in/tests/test_hsn_summary.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.scss
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_point_of_sale.py
  addons/point_of_sale/tests/test_pos_products_with_tax.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/sale/static/tests/tours/product_attribute_value_tour.js
  addons/sale/tests/test_product_attribute_value.py
  addons/sale_project/models/sale_order_line.py
  addons/sale_project/tests/test_sale_project.py
  addons/sale_stock/i18n/sale_stock.pot
  addons/sale_stock/models/sale_order.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/sale_stock/views/sale_order_views.xml
  addons/stock/models/stock_picking.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/web/static/src/views/list/list_renderer.xml
  addons/web/static/src/webclient/debug/profiling/profiling_qweb.scss
  addons/web/static/tests/views/list/list_view.test.js
  addons/web_tour/static/src/tour_service/tour_compilers.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_links/static/src/js/website_links.js
  addons/website_sale/static/src/js/website_sale.editor.js
  odoo/addons/base/models/ir_filters.py
  odoo/addons/base/tests/test_ir_filters.py
  odoo/models.py
Labels: tmp.saas-17.4

#28468 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/stock/views/res_config_settings_views.xml
  addons/test_website/tests/test_redirect.py
  addons/website/models/ir_http.py
  addons/website/static/src/js/content/menu.js
  addons/website_links/static/src/js/website_links.js
Labels: tmp.16.0

#28470 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_company.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: 15.0

#28471 Syncing from upstream odoo/odoo (16.0)
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_holidays/tests/test_hr_leave_type.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
Labels: 16.0

#28475 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi/models/account_move.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/bus/controllers/websocket.py
  addons/bus/i18n/bus.pot
  addons/bus/models/__init__.py
  addons/bus/models/ir_http.py
  addons/bus/static/src/multi_tab_service.js
  addons/bus/static/src/services/bus_service.js
  addons/bus/static/src/workers/websocket_worker.js
  addons/bus/static/tests/legacy/bus_tests.js
  addons/bus/tests/common.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/tests/test_recruitment.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/im_livechat/static/src/embed/common/livechat_service.js
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_cy/data/template/account.tax.group-cy.csv
  addons/l10n_cy/models/template_cy.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/l10n_it_edi/models/account_move.py
  addons/mail/static/src/core/common/message.xml
  addons/maintenance/models/maintenance.py
  addons/maintenance/tests/test_maintenance.py
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_stock_report.py
  addons/sale/wizard/res_config_settings_views.xml
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/legacy/views/fields/datetime_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/views/res_config_settings_views.xml
  odoo/addons/base/tests/config/non_default.conf
  odoo/addons/base/tests/config/save_posix.conf
  odoo/addons/base/tests/test_configmanager.py
  odoo/service/server.py
  odoo/tools/config.py
Labels: saas-17.2

#28481 Syncing from upstream odoo/odoo (staging.15.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_company.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: staging.15.0

#28482 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/base_automation/controllers/main.py
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hw_drivers/websocket_client.py
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/mrp_account/models/product.py
  addons/mrp_repair/tests/test_tracability.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase/views/purchase_views.xml
  addons/repair/models/product.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_base_automation/__manifest__.py
  addons/test_base_automation/data/mail_template_data.xml
  addons/test_base_automation/models/test_base_automation.py
  addons/test_base_automation/tests/test_flow.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/js/content/menu.js
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_mondialrelay/views/templates.xml
Labels: staging.17.0

#28485 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/common.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_edi/models/account_move.py
  addons/account_edi/views/account_move_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/bus/controllers/websocket.py
  addons/bus/i18n/bus.pot
  addons/bus/models/__init__.py
  addons/bus/models/ir_http.py
  addons/bus/static/src/multi_tab_service.js
  addons/bus/static/src/services/bus_service.js
  addons/bus/static/src/workers/websocket_worker.js
  addons/bus/static/tests/legacy/bus_tests.js
  addons/bus/tests/common.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/tests/__init__.py
  addons/hr_holidays/tests/test_dashboard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/tests/test_recruitment.py
  addons/im_livechat/models/im_livechat_channel.py
  addons/im_livechat/static/src/embed/common/livechat_service.js
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_cy/data/template/account.tax.group-cy.csv
  addons/l10n_cy/models/template_cy.py
  addons/l10n_fr_hr_holidays/models/hr_leave.py
  addons/l10n_fr_hr_holidays/tests/test_french_leaves.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_edi_ewaybill/models/account_move.py
  addons/l10n_it_edi/models/account_move.py
  addons/mail/static/src/core/common/message.xml
  addons/maintenance/models/maintenance.py
  addons/maintenance/tests/test_maintenance.py
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/mrp/models/mrp_production.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_stock_report.py
  addons/sale/wizard/res_config_settings_views.xml
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/legacy/views/fields/datetime_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/views/res_config_settings_views.xml
  odoo/addons/base/tests/config/non_default.conf
  odoo/addons/base/tests/config/save_posix.conf
  odoo/addons/base/tests/test_configmanager.py
  odoo/service/server.py
  odoo/tools/config.py
Labels: tmp.saas-17.2

#28487 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_company.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: tmp.15.0

#28488 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hr_holidays/tests/test_hr_leave_type.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
Labels: tmp.16.0

#28489 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/base_automation/controllers/main.py
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hw_drivers/websocket_client.py
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/mrp_account/models/product.py
  addons/mrp_repair/tests/test_tracability.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/purchase/views/purchase_views.xml
  addons/repair/models/product.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_base_automation/__manifest__.py
  addons/test_base_automation/data/mail_template_data.xml
  addons/test_base_automation/models/test_base_automation.py
  addons/test_base_automation/tests/test_flow.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/js/content/menu.js
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_mondialrelay/views/templates.xml
Labels: tmp.17.0

#28490 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_company.py
Labels: 16.0

#28491 Syncing from upstream odoo/odoo (17.0)
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: 17.0

#28497 Syncing from upstream odoo/odoo (staging.17.0)
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: staging.17.0

#28498 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/models/res_company.py
Labels: tmp.16.0

#28499 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: tmp.17.0

#28500 Syncing from upstream odoo/odoo (master)
  addons/hr_holidays/static/src/views/view_dialog/form_view_dialog.js
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: master

#28501 Syncing from upstream odoo/odoo (staging.master)
  addons/hr_holidays/static/src/views/view_dialog/form_view_dialog.js
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: staging.master

#28502 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: staging.saas-17.1

#28504 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: staging.saas-17.4

#28505 Syncing from upstream odoo/odoo (tmp.master)
  addons/hr_holidays/static/src/views/view_dialog/form_view_dialog.js
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: tmp.master

#28506 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: tmp.saas-17.1

#28508 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: tmp.saas-17.4

#28513 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/i18n/account.pot
  addons/hw_drivers/main.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/mail/models/ir_http.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ReceiptScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_move_line.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/website/models/ir_http.py
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_mondialrelay/views/templates.xml
Labels: saas-17.2

#28514 Syncing from upstream odoo/odoo (saas-17.4)
  addons/event/data/mail_template_data.xml
  addons/event/report/event_event_templates.xml
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hw_drivers/main.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/views/report_invoice.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/tests/test_stock_report.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_discount/models/product_product.py
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_reward_button_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/static/src/js/tours/project.js
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/web/static/src/core/debug/debug_providers.js
  addons/web/static/src/core/overlay/overlay_container.scss
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/datetime_field.test.js
  addons/website/static/src/js/content/adapt_content.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_event_sale/controllers/sale.py
  addons/website_event_sale/views/website_sale_templates.xml
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/res_config_settings_views.xml
Labels: saas-17.4

#28516 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/hw_drivers/main.py
  addons/hw_drivers/websocket_client.py
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/pos_hr/models/pos_session.py
  addons/pos_hr/static/src/overrides/components/navbar/closing_popup/close_pos_popup.js
  addons/pos_hr/static/src/overrides/models/pos_store.js
  addons/pos_hr/static/tests/tours/PosHrTour.js
  addons/pos_hr/static/tests/tours/PosHrTourMethods.js
  addons/pos_hr/tests/test_frontend.py
  addons/project/static/src/views/project_task_form/project_task_form_controller.js
  addons/project/static/tests/tours/project_task_history.js
  addons/project/tests/test_project_ui.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/website/models/ir_http.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_mondialrelay/views/templates.xml
Labels: staging.saas-17.1

#28518 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/event/data/mail_template_data.xml
  addons/event/report/event_event_templates.xml
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hw_drivers/main.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/tests/test_stock_report.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_discount/models/product_product.py
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_reward_button_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/static/src/js/tours/project.js
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/web/static/src/core/debug/debug_providers.js
  addons/web/static/src/core/overlay/overlay_container.scss
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/datetime_field.test.js
  addons/website/static/src/js/content/adapt_content.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_event_sale/controllers/sale.py
  addons/website_event_sale/views/website_sale_templates.xml
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/res_config_settings_views.xml
Labels: staging.saas-17.4

#28520 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/wizard/account_move_send.py
  addons/hr_contract/models/__init__.py
  addons/hr_contract/models/resource_calendar_leaves.py
  addons/hr_contract/tests/test_contract.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_hr_leave_type.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/data/template/account.tax-in.csv
  addons/l10n_in_withholding/__init__.py
  addons/l10n_in_withholding/__manifest__.py
  addons/l10n_in_withholding/data/template/account.account-in.csv
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_in_withholding/i18n/l10n_in_withholding.pot
  addons/l10n_in_withholding/models/__init__.py
  addons/l10n_in_withholding/models/account_chart_template.py
  addons/l10n_in_withholding/models/account_move.py
  addons/l10n_in_withholding/models/account_move_line.py
  addons/l10n_in_withholding/models/account_payment.py
  addons/l10n_in_withholding/models/account_tax.py
  addons/l10n_in_withholding/models/res_company.py
  addons/l10n_in_withholding/models/res_config_settings.py
  addons/l10n_in_withholding/security/ir.model.access.csv
  addons/l10n_in_withholding/views/account_move_views.xml
  addons/l10n_in_withholding/views/account_payment_views.xml
  addons/l10n_in_withholding/views/account_tax_views.xml
  addons/l10n_in_withholding/views/res_config_settings_views.xml
  addons/l10n_in_withholding/wizard/__init__.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/lunch/models/lunch_alert.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/pos_printer_service.js
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/project/models/project_project.py
  addons/project/static/src/project_sharing/views/list/list_renderer.js
  addons/project/static/tests/tours/project_sharing_tour.js
  addons/project/tests/test_project_sharing_ui.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/resource/models/resource_calendar_leaves.py
  addons/resource/models/resource_resource.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/report/stock_forecasted.py
  addons/survey/static/src/scss/survey_survey_views.scss
  addons/survey/views/survey_survey_views.xml
  addons/test_resource/tests/test_resource.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/webclient/switch_company_menu/switch_company_menu.js
  addons/web_editor/controllers/main.py
  addons/website/models/ir_http.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website_sale/static/src/js/website_sale.js
Labels: staging.17.0

#28522 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/hw_drivers/main.py
  addons/hw_drivers/websocket_client.py
  addons/l10n_es_edi_facturae/tests/data/import_multiple_invoices.xml
  addons/l10n_es_edi_facturae/tests/data/import_withholding_invoice.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/pos_hr/models/pos_session.py
  addons/pos_hr/static/src/overrides/components/navbar/closing_popup/close_pos_popup.js
  addons/pos_hr/static/src/overrides/models/pos_store.js
  addons/pos_hr/static/tests/tours/PosHrTour.js
  addons/pos_hr/static/tests/tours/PosHrTourMethods.js
  addons/pos_hr/tests/test_frontend.py
  addons/project/static/src/views/project_task_form/project_task_form_controller.js
  addons/project/static/tests/tours/project_task_history.js
  addons/project/tests/test_project_ui.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/website/models/ir_http.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_mondialrelay/views/templates.xml
Labels: tmp.saas-17.1

#28523 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/i18n/account.pot
  addons/hw_drivers/main.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/mail/models/ir_http.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ReceiptScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyRewardButtonTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_move_line.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/legacy/js/core/dom.js
  addons/website/models/ir_http.py
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale/views/templates.xml
  addons/website_sale_mondialrelay/views/templates.xml
Labels: tmp.saas-17.2

#28524 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/event/data/mail_template_data.xml
  addons/event/report/event_event_templates.xml
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hw_drivers/main.py
  addons/l10n_es_modelo130/__init__.py
  addons/l10n_es_modelo130/__manifest__.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_es_modelo130/i18n/es.po
  addons/l10n_es_modelo130/i18n/l10n_es_modelo130.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/res_company.py
  addons/mrp/report/mrp_report_mo_overview.py
  addons/mrp/tests/test_stock_report.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_discount/models/product_product.py
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/pos_loyalty_reward_button_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/project/static/src/js/tours/project.js
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/web/static/src/core/debug/debug_providers.js
  addons/web/static/src/core/overlay/overlay_container.scss
  addons/web/static/src/legacy/js/core/dom.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/datetime_field.test.js
  addons/website/static/src/js/content/adapt_content.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/snippets/s_dynamic_snippet/000.scss
  addons/website_event_sale/controllers/sale.py
  addons/website_event_sale/views/website_sale_templates.xml
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/views/res_config_settings_views.xml
Labels: tmp.saas-17.4

#28527 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/wizard/account_move_send.py
  addons/hr_contract/models/__init__.py
  addons/hr_contract/models/resource_calendar_leaves.py
  addons/hr_contract/tests/test_contract.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_hr_leave_type.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in/data/template/account.tax-in.csv
  addons/l10n_in_withholding/__init__.py
  addons/l10n_in_withholding/__manifest__.py
  addons/l10n_in_withholding/data/template/account.account-in.csv
  addons/l10n_in_withholding/data/template/account.tax-in.csv
  addons/l10n_in_withholding/i18n/l10n_in_withholding.pot
  addons/l10n_in_withholding/models/__init__.py
  addons/l10n_in_withholding/models/account_chart_template.py
  addons/l10n_in_withholding/models/account_move.py
  addons/l10n_in_withholding/models/account_move_line.py
  addons/l10n_in_withholding/models/account_payment.py
  addons/l10n_in_withholding/models/account_tax.py
  addons/l10n_in_withholding/models/res_company.py
  addons/l10n_in_withholding/models/res_config_settings.py
  addons/l10n_in_withholding/security/ir.model.access.csv
  addons/l10n_in_withholding/views/account_move_views.xml
  addons/l10n_in_withholding/views/account_payment_views.xml
  addons/l10n_in_withholding/views/account_tax_views.xml
  addons/l10n_in_withholding/views/res_config_settings_views.xml
  addons/l10n_in_withholding/wizard/__init__.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/lunch/models/lunch_alert.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/pos_printer_service.js
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/project/models/project_project.py
  addons/project/static/src/project_sharing/views/list/list_renderer.js
  addons/project/static/tests/tours/project_sharing_tour.js
  addons/project/tests/test_project_sharing_ui.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/__init__.py
  addons/project_timesheet_holidays/tests/test_cancel_time_off.py
  addons/resource/models/resource_calendar_leaves.py
  addons/resource/models/resource_resource.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/stock/report/stock_forecasted.py
  addons/survey/static/src/scss/survey_survey_views.scss
  addons/survey/views/survey_survey_views.xml
  addons/test_resource/tests/test_resource.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/webclient/switch_company_menu/switch_company_menu.js
  addons/web_editor/controllers/main.py
  addons/website/models/ir_http.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website_sale/static/src/js/website_sale.js
Labels: tmp.17.0

#28528 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/es_MX.po
  addons/account/i18n/id.po
  addons/bus/i18n/ro.po
  addons/hr_holidays/wizard/hr_departure_wizard.py
  addons/http_routing/i18n/ro.po
  addons/iap/i18n/ro.po
  addons/mrp/i18n/es_MX.po
  addons/product/i18n/da.po
  addons/project_timesheet_holidays/tests/test_timesheet_holidays.py
  addons/resource/i18n/ro.po
  addons/sale/i18n/da.po
  addons/sale/i18n/es_MX.po
  addons/sale_quotation_builder/i18n/pt_BR.po
  addons/sale_timesheet/i18n/da.po
  addons/website/i18n/ro.po
  addons/website_blog/i18n/ro.po
  addons/website_event_booth/i18n/es_MX.po
  odoo/addons/base/i18n/cs.po
Labels: 15.0

#28529 Syncing from upstream odoo/odoo (16.0)
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/resource/models/resource.py
  addons/test_resource/tests/test_resource.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website_sale/models/res_config_settings.py
Labels: 16.0

#28540 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/resource/models/resource.py
  addons/test_resource/tests/test_resource.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website_sale/models/res_config_settings.py
Labels: staging.16.0

#28541 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/views/account_move_views.xml
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_in/views/res_partner_views.xml
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/product_expiry/models/stock_move.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
Labels: staging.17.0

#28547 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/resource/models/resource.py
  addons/test_resource/tests/test_resource.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website_sale/models/res_config_settings.py
Labels: tmp.16.0

#28548 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/views/account_move_views.xml
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_in/views/res_partner_views.xml
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/product_expiry/models/stock_move.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_location.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_quant.py
Labels: tmp.17.0

#28549 Syncing from upstream odoo/odoo (15.0)
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/website/static/src/js/content/snippets.animation.js
Labels: 15.0

#28550 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_it_edi_withholding/models/account_move.py
  odoo/addons/base/data/res_country_data.xml
Labels: 16.0

#28553 Syncing from upstream odoo/odoo (saas-17.1)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/mrp_repair/tests/test_tracability.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/models/stock.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_delivery/models/stock_picking.py
Labels: saas-17.1

#28554 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/views/account_move_views.xml
  addons/hr_expense/wizard/account_payment_register.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_loyalty/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/banner_tests.js
Labels: saas-17.2

#28555 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/hr_attendance/controllers/main.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/autoresize_input.scss
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/src/app/utils/time_hook.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_hr/static/img/barcode.png
  addons/pos_hr/static/img/enterPin.png
  addons/pos_hr/static/img/login-bg-overlay.svg
  addons/pos_hr/static/img/profile.png
  addons/pos_hr/static/src/app/login_screen/login_screen.js
  addons/pos_hr/static/src/app/login_screen/login_screen.xml
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_location.py
  addons/stock_account/models/product.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/core/overlay/overlay_container.scss
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph/graph_view.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/models/ir_http.py
Labels: saas-17.4

#28557 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/mrp_repair/tests/test_tracability.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/models/stock.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_delivery/models/stock_picking.py
Labels: staging.saas-17.1

#28559 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/hr_attendance/controllers/main.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/autoresize_input.scss
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/src/app/utils/time_hook.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_hr/static/img/barcode.png
  addons/pos_hr/static/img/enterPin.png
  addons/pos_hr/static/img/login-bg-overlay.svg
  addons/pos_hr/static/img/profile.png
  addons/pos_hr/static/src/app/login_screen/login_screen.js
  addons/pos_hr/static/src/app/login_screen/login_screen.xml
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_location.py
  addons/stock_account/models/product.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/core/overlay/overlay_container.scss
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph/graph_view.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/models/ir_http.py
Labels: staging.saas-17.4

#28560 Syncing from upstream odoo/odoo (staging.15.0)
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/mrp/i18n/es_MX.po
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_event_booth/i18n/es_MX.po
Labels: staging.15.0

#28561 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_it_edi_withholding/models/account_move.py
  odoo/addons/base/data/res_country_data.xml
Labels: staging.16.0

#28564 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/mrp_repair/tests/test_tracability.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/models/stock.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_delivery/models/stock_picking.py
Labels: tmp.saas-17.1

#28565 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_expense/models/account_move.py
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/views/account_move_views.xml
  addons/hr_expense/wizard/account_payment_register.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__init__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/models/__init__.py
  addons/l10n_sa_edi_pos/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/models/account_move.py
  addons/l10n_sa_edi_pos/models/pos_config.py
  addons/l10n_sa_edi_pos/static/src/overrides/models/models.js
  addons/l10n_sa_edi_pos/static/src/overrides/models/pos_store.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_loyalty/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyLoyaltyProgramTour.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/banner_tests.js
Labels: tmp.saas-17.2

#28566 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/hr_attendance/controllers/main.py
  addons/hw_drivers/iot_handlers/drivers/SerialBaseDriver.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi/models/account_move.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/autoresize_input.scss
  addons/mail/static/src/core/common/autoresize_input.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/src/app/utils/time_hook.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_hr/static/img/barcode.png
  addons/pos_hr/static/img/enterPin.png
  addons/pos_hr/static/img/login-bg-overlay.svg
  addons/pos_hr/static/img/profile.png
  addons/pos_hr/static/src/app/login_screen/login_screen.js
  addons/pos_hr/static/src/app/login_screen/login_screen.xml
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/stock/models/stock_location.py
  addons/stock_account/models/product.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/test_website/tests/test_redirect.py
  addons/web/static/src/core/overlay/overlay_container.scss
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph/graph_view.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/models/ir_http.py
Labels: tmp.saas-17.4

#28567 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface.py
  addons/mrp/i18n/es_MX.po
  addons/purchase_stock/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_event_booth/i18n/es_MX.po
Labels: tmp.15.0

#28568 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_it_edi_withholding/models/account_move.py
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.16.0

#28570 Syncing from upstream odoo/odoo (15.0)
  addons/mrp_account/models/mrp_workorder.py
Labels: 15.0

#28571 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/mrp_account/models/mrp_workorder.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_event/models/event_event.py
Labels: 16.0

#28574 Syncing from upstream odoo/odoo (saas-17.1)
  addons/account/wizard/account_move_send.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_holidays/static/src/thread_model_patch.js
  addons/hr_holidays/static/tests/channel_member_list_tests.js
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/discuss/core/channel_member_list_tests.js
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/helpers/ReceiptScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/project_account/models/project_project.py
  addons/project_account/tests/test_project_profitability.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_timesheet/tests/test_project_profitability.py
  addons/stock/report/stock_forecasted.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/snippets/s_text_cover/000.scss
  addons/website_event/models/event_event.py
  odoo/addons/base/data/res_country_data.xml
Labels: saas-17.1

#28575 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/account/wizard/account_move_send.py
  addons/account/wizard/accrued_orders.py
  addons/base_import_module/tests/test_import_module.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/hr_holidays/static/src/thread_model_patch.js
  addons/hr_holidays/static/tests/channel_member_list.test.js
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/discuss/core/channel_member_list.test.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_consume_component.py
  addons/mrp_repair/tests/test_tracability.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/report/stock_forecasted.py
  addons/stock/tests/test_proc_rule.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website/static/src/snippets/s_text_cover/000.scss
  addons/website_event/models/event_event.py
  odoo/addons/base/data/res_country_data.xml
Labels: saas-17.2

#28578 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/account/wizard/account_move_send.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_holidays/static/src/thread_model_patch.js
  addons/hr_holidays/static/tests/channel_member_list_tests.js
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/discuss/core/channel_member_list_tests.js
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/helpers/ReceiptScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/project_account/models/project_project.py
  addons/project_account/tests/test_project_profitability.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_timesheet/tests/test_project_profitability.py
  addons/stock/report/stock_forecasted.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/snippets/s_text_cover/000.scss
  addons/website_event/models/event_event.py
  odoo/addons/base/data/res_country_data.xml
Labels: staging.saas-17.1

#28581 Syncing from upstream odoo/odoo (staging.15.0)
  addons/mrp_account/models/mrp_workorder.py
Labels: staging.15.0

#28582 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/mrp_account/models/mrp_workorder.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_event/models/event_event.py
Labels: staging.16.0

#28583 Syncing from upstream odoo/odoo (staging.17.0)
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/product/models/product_product.py
  addons/purchase/views/purchase_views.xml
  addons/web_editor/models/ir_attachment.py
  addons/website/static/src/js/content/menu.js
  odoo/addons/base/data/res_country_data.xml
Labels: staging.17.0

#28585 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/account/wizard/account_move_send.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_holidays/static/src/thread_model_patch.js
  addons/hr_holidays/static/tests/channel_member_list_tests.js
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/discuss/core/channel_member_list_tests.js
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/helpers/ReceiptScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/project_account/models/project_project.py
  addons/project_account/tests/test_project_profitability.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_timesheet/tests/test_project_profitability.py
  addons/stock/report/stock_forecasted.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website/static/src/snippets/s_text_cover/000.scss
  addons/website_event/models/event_event.py
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.saas-17.1

#28586 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/account/wizard/account_move_send.py
  addons/account/wizard/accrued_orders.py
  addons/base_import_module/tests/test_import_module.py
  addons/bus/tests/test_websocket_caryall.py
  addons/bus/websocket.py
  addons/hr_holidays/static/src/thread_model_patch.js
  addons/hr_holidays/static/tests/channel_member_list.test.js
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/discuss/core/channel_member_list.test.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_consume_component.py
  addons/mrp_repair/tests/test_tracability.py
  addons/mrp_subcontracting_account/models/stock_move.py
  addons/mrp_subcontracting_account/tests/test_subcontracting_account.py
  addons/payment/controllers/post_processing.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/tests/__init__.py
  addons/pos_sale/tests/test_pos_sale_lot.py
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/report/stock_forecasted.py
  addons/stock/tests/test_proc_rule.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/components/media_dialog/video_selector.js
  addons/web_editor/tools.py
  addons/website/static/src/snippets/s_text_cover/000.scss
  addons/website_event/models/event_event.py
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.saas-17.2

#28588 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/mrp_account/models/mrp_workorder.py
Labels: tmp.15.0

#28589 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/mrp_account/models/mrp_workorder.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/fields/file_handler.js
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_event/models/event_event.py
Labels: tmp.16.0

#28590 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message_tests.js
  addons/mail/static/tests/discuss_app/inbox_tests.js
  addons/product/models/product_product.py
  addons/purchase/views/purchase_views.xml
  addons/web_editor/models/ir_attachment.py
  addons/website/static/src/js/content/menu.js
  odoo/addons/base/data/res_country_data.xml
Labels: tmp.17.0

#28591 [bt#25033] [FIX] account: backport of computation of tax tag invert fix
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_out_invoice.py
Labels: 15.0.project_gd_615

#28592 [bt#25033] backmerge
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_out_invoice.py
Labels: 15.0.project_gd_615.test

#28593 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/partner.py
  addons/account/tests/test_fiscal_position.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: 15.0

#28594 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hr_holidays/wizard/hr_departure_wizard.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/project_timesheet_holidays/tests/test_timesheet_holidays.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: 16.0

#28598 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/tests/test_tax.py
  addons/hr_timesheet/controllers/project.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/template/account.tax-dk.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_hr/static/src/app/select_cashier_mixin.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_control_panel/sale_order_management_control_panel.js
  addons/project/controllers/portal.py
  addons/project/static/src/project_sharing/project_sharing.js
  addons/project/static/src/project_sharing/views/list/list_renderer.js
  addons/project/static/tests/tours/project_sharing_tour.js
  addons/project/tests/test_project_sharing_ui.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project_account/models/project_project.py
  addons/project_account/tests/test_project_profitability.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_timesheet/tests/test_project_profitability.py
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/legacy/views/calendar/calendar_view_tests.js
  addons/web/static/tests/legacy/views/list_view_tests.js
  addons/web/static/tests/legacy/webclient/actions/load_state_tests.js
  addons/web_editor/models/ir_attachment.py
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/content/snippets.animation.js
  requirements.txt
Labels: saas-17.2

#28603 Syncing from upstream odoo/odoo (staging.15.0)
  addons/account/models/partner.py
  addons/account/tests/test_fiscal_position.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: staging.15.0

#28604 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hr_holidays/wizard/hr_departure_wizard.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/project_timesheet_holidays/tests/test_timesheet_holidays.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: staging.16.0

#28605 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_tax.py
  addons/account/models/res_currency.py
  addons/account/tests/test_tax.py
  addons/hr_holidays/static/src/dashboard/time_off_dashboard.js
  addons/hr_holidays/static/tests/time_off_dashboard_tests.js
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/template/account.tax-dk.csv
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/mail/static/src/core/common/message.js
  addons/mail/static/tests/message/message_tests.js
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_control_panel/sale_order_management_control_panel.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/fields/percent_pie_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/res_config_settings.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
Labels: staging.17.0

#28608 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/tests/test_tax.py
  addons/hr_timesheet/controllers/project.py
  addons/hr_timesheet/views/project_task_views.xml
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/template/account.tax-dk.csv
  addons/l10n_fi/data/template/account.tax-fi.csv
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_hr/static/src/app/select_cashier_mixin.js
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_control_panel/sale_order_management_control_panel.js
  addons/project/controllers/portal.py
  addons/project/static/src/project_sharing/project_sharing.js
  addons/project/static/src/project_sharing/views/list/list_renderer.js
  addons/project/static/tests/tours/project_sharing_tour.js
  addons/project/tests/test_project_sharing_ui.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/project_account/models/project_project.py
  addons/project_account/tests/test_project_profitability.py
  addons/project_purchase/tests/test_project_profitability.py
  addons/sale_project/tests/test_project_profitability.py
  addons/sale_timesheet/tests/test_project_profitability.py
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/legacy/views/calendar/calendar_view_tests.js
  addons/web/static/tests/legacy/views/list_view_tests.js
  addons/web/static/tests/legacy/webclient/actions/load_state_tests.js
  addons/web_editor/models/ir_attachment.py
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/content/snippets.animation.js
  requirements.txt
Labels: tmp.saas-17.2

#28610 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/partner.py
  addons/account/tests/test_fiscal_position.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
Labels: tmp.15.0

#28611 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hr_holidays/wizard/hr_departure_wizard.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/point_of_sale/static/src/js/Screens/ProductScreen/ProductScreen.js
  addons/project_timesheet_holidays/tests/test_timesheet_holidays.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: tmp.16.0

#28612 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_tax.py
  addons/account/models/res_currency.py
  addons/account/tests/test_tax.py
  addons/hr_holidays/static/src/dashboard/time_off_dashboard.js
  addons/hr_holidays/static/tests/time_off_dashboard_tests.js
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/l10n_dk/data/account_tax_report_data.xml
  addons/l10n_dk/data/template/account.tax-dk.csv
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/tests/compliance/simplified/credit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/debit.xml
  addons/l10n_sa_edi/tests/compliance/simplified/invoice.xml
  addons/l10n_sa_edi/tests/compliance/standard/credit.xml
  addons/l10n_sa_edi/tests/compliance/standard/debit.xml
  addons/l10n_sa_edi/tests/compliance/standard/invoice.xml
  addons/mail/static/src/core/common/message.js
  addons/mail/static/tests/message/message_tests.js
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_sale/models/pos_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_control_panel/sale_order_management_control_panel.js
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/src/webclient/webclient_layout.scss
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/fields/percent_pie_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/res_config_settings.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
Labels: tmp.17.0

#28613 Syncing from upstream odoo/odoo (15.0)
  addons/account/i18n/lt.po
  addons/account/i18n/pt.po
  addons/account/i18n/zh_TW.po
  addons/base_vat/i18n/zh_TW.po
  addons/event_booth/i18n/es_MX.po
  addons/google_recaptcha/i18n/et.po
  addons/hr/i18n/pt.po
  addons/hr_attendance/i18n/pt.po
  addons/hr_contract/i18n/lt.po
  addons/hr_contract/i18n/pt.po
  addons/hr_expense/i18n/pt.po
  addons/hr_fleet/i18n/pt.po
  addons/hr_holidays/i18n/pt.po
  addons/hr_holidays_attendance/i18n/pt.po
  addons/hr_org_chart/i18n/pt.po
  addons/hr_skills/i18n/pt.po
  addons/hr_timesheet/i18n/pt.po
  addons/hr_work_entry_contract/i18n/pt.po
  addons/l10n_eg_edi_eta/i18n/ar.po
  addons/l10n_eg_edi_eta/i18n/fr.po
  addons/l10n_eg_edi_eta/i18n/it.po
  addons/mail/i18n/et.po
  addons/mail_plugin/i18n/et.po
  addons/mass_mailing_sms/i18n/da.po
  addons/mrp/i18n/lt.po
  addons/mrp_account/i18n/da.po
  addons/payment/i18n/da.po
  addons/pos_hr/i18n/pt.po
  addons/pos_mercury/i18n/et.po
  addons/pos_restaurant/i18n/tr.po
  addons/sale_timesheet/i18n/es.po
  addons/sale_timesheet/i18n/et.po
  addons/stock/i18n/da.po
  addons/web/i18n/da.po
  addons/web_editor/i18n/et.po
  addons/website/i18n/ro.po
  addons/website_event_booth_exhibitor/i18n/es_MX.po
  addons/website_event_track/i18n/es_MX.po
  addons/website_event_track/i18n/et.po
  addons/website_event_track_live/i18n/es_MX.po
  addons/website_event_track_quiz/i18n/es_MX.po
  addons/website_sale/i18n/et.po
  odoo/addons/base/i18n/cs.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
Labels: 15.0

#28618 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/res_currency.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
Labels: saas-17.2

#28619 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/res_currency.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: saas-17.4

#28620 Syncing from upstream odoo/odoo (staging.master)
  addons/account/models/res_currency.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: staging.master

#28623 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/res_currency.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: staging.saas-17.4

#28624 Syncing from upstream odoo/odoo (staging.16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: staging.16.0

#28625 Syncing from upstream odoo/odoo (staging.17.0)
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: staging.17.0

#28626 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/res_currency.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: tmp.master

#28627 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/account/models/res_currency.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
Labels: tmp.saas-17.1

#28628 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/res_currency.py
  addons/analytic/models/analytic_mixin.py
  addons/analytic/tests/__init__.py
  addons/analytic/tests/test_analytic_mixin.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze_test.js
Labels: tmp.saas-17.2

#28629 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/res_currency.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_bd/data/account.account.tag.csv
  addons/l10n_bd/data/account_tax_report_data.xml
  addons/l10n_bd/data/template/account.account-bd.csv
  addons/l10n_bd/views/menu_items.xml
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/content/snippets.animation.js
Labels: tmp.saas-17.4

#28630 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.16.0

#28631 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.17.0

#28632 Syncing from upstream odoo/odoo (15.0)
  addons/portal/controllers/mail.py
  odoo/tools/safe_eval.py
Labels: 15.0

#28633 Syncing from upstream odoo/odoo (16.0)
  addons/portal/controllers/mail.py
  odoo/tools/safe_eval.py
Labels: 16.0

#28635 Syncing from upstream odoo/odoo (master)
  addons/portal/controllers/mail.py
  addons/portal/static/src/js/portal_chatter.js
  addons/project/static/src/project_sharing/components/chatter/chatter_container.js
  odoo/tools/safe_eval.py
Labels: master

#28636 Syncing from upstream odoo/odoo (saas-17.1)
  addons/portal/controllers/mail.py
  odoo/tools/safe_eval.py
Labels: saas-17.1

#28644 Syncing from upstream odoo/odoo (tmp.master)
  addons/portal/controllers/mail.py
  addons/portal/static/src/js/portal_chatter.js
  addons/project/static/src/project_sharing/components/chatter/chatter_container.js
  odoo/tools/safe_eval.py
Labels: tmp.master

#28648 Syncing from upstream odoo/odoo (15.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/l10n_eg_edi_eta/models/res_currency_rate.py
  addons/l10n_nl/data/account.account.template.csv
Labels: 15.0

#28649 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/partner.py
  addons/account/tests/test_fiscal_position.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/website/static/src/js/content/menu.js
Labels: 16.0

#28652 Syncing from upstream odoo/odoo (saas-17.1)
  addons/hw_drivers/connection_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/server_config.html
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message_tests.js
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/X11/xorg.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/NetworkManager/conf.d/90-dns-none.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/website_sale/models/res_config_settings.py
Labels: saas-17.1

#28653 Syncing from upstream odoo/odoo (saas-17.2)
  addons/hw_drivers/connection_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/server_config.html
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/X11/xorg.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/NetworkManager/conf.d/90-dns-none.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project_project.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/tests/views/fields/percent_pie_field.test.js
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website_sale/models/res_config_settings.py
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: saas-17.2

#28654 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/auth_passkey/models/auth_passkey_key.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/common/chat_bubble.js
  addons/mail/static/src/core/common/chat_bubble.xml
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/payment_xendit/static/src/js/payment_form.js
  addons/payment_xendit/views/payment_xendit_templates.xml
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/models/sale_order_line.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: saas-17.4

#28656 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/hw_drivers/connection_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/server_config.html
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message_tests.js
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/X11/xorg.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/NetworkManager/conf.d/90-dns-none.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/portal/controllers/mail.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  odoo/tools/safe_eval.py
Labels: staging.saas-17.1

#28658 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/auth_passkey/models/auth_passkey_key.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/common/chat_bubble.js
  addons/mail/static/src/core/common/chat_bubble.xml
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/payment_xendit/static/src/js/payment_form.js
  addons/payment_xendit/views/payment_xendit_templates.xml
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/models/sale_order_line.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: staging.saas-17.4

#28659 Syncing from upstream odoo/odoo (staging.15.0)
  addons/account/i18n/lt.po
  addons/account/i18n/pt.po
  addons/account/i18n/zh_TW.po
  addons/account/views/report_payment_receipt_templates.xml
  addons/base_vat/i18n/zh_TW.po
  addons/event_booth/i18n/es_MX.po
  addons/google_recaptcha/i18n/et.po
  addons/hr/i18n/pt.po
  addons/hr_attendance/i18n/pt.po
  addons/hr_contract/i18n/lt.po
  addons/hr_contract/i18n/pt.po
  addons/hr_expense/i18n/pt.po
  addons/hr_fleet/i18n/pt.po
  addons/hr_holidays/i18n/pt.po
  addons/hr_holidays_attendance/i18n/pt.po
  addons/hr_org_chart/i18n/pt.po
  addons/hr_skills/i18n/pt.po
  addons/hr_timesheet/i18n/pt.po
  addons/hr_work_entry_contract/i18n/pt.po
  addons/l10n_eg_edi_eta/i18n/ar.po
  addons/l10n_eg_edi_eta/i18n/fr.po
  addons/l10n_eg_edi_eta/i18n/it.po
  addons/l10n_eg_edi_eta/models/res_currency_rate.py
  addons/l10n_nl/data/account.account.template.csv
  addons/mail/i18n/et.po
  addons/mail_plugin/i18n/et.po
  addons/mass_mailing_sms/i18n/da.po
  addons/mrp/i18n/lt.po
  addons/mrp_account/i18n/da.po
  addons/payment/i18n/da.po
  addons/portal/controllers/mail.py
  addons/pos_hr/i18n/pt.po
  addons/pos_mercury/i18n/et.po
  addons/pos_restaurant/i18n/tr.po
  addons/sale_timesheet/i18n/es.po
  addons/sale_timesheet/i18n/et.po
  addons/stock/i18n/da.po
  addons/web/i18n/da.po
  addons/web_editor/i18n/et.po
  addons/website/i18n/ro.po
  addons/website_event_booth_exhibitor/i18n/es_MX.po
  addons/website_event_track/i18n/es_MX.po
  addons/website_event_track/i18n/et.po
  addons/website_event_track_live/i18n/es_MX.po
  addons/website_event_track_quiz/i18n/es_MX.po
  addons/website_sale/i18n/et.po
  odoo/addons/base/i18n/cs.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/tools/safe_eval.py
Labels: staging.15.0

#28661 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/account.pot
  addons/account/models/account_tax.py
  addons/account/tests/test_tax.py
  addons/hr_holidays/wizard/hr_departure_wizard.py
  addons/hw_drivers/connection_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/server_config.html
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/X11/xorg.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/NetworkManager/conf.d/90-dns-none.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/portal/controllers/mail.py
  addons/project_timesheet_holidays/tests/test_timesheet_holidays.py
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/kanban/progress_bar_hook.js
  addons/web/static/src/views/view_components/column_progress.xml
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/website_sale/controllers/main.py
  odoo/tools/safe_eval.py
Labels: staging.17.0

#28663 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/hw_drivers/connection_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/server_config.html
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message_tests.js
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/X11/xorg.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/NetworkManager/conf.d/90-dns-none.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/portal/controllers/mail.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/website_sale/models/res_config_settings.py
  odoo/tools/safe_eval.py
Labels: tmp.saas-17.1

#28664 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/hw_drivers/connection_manager.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/server_config.html
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/tools/posbox/configuration/odoo.conf
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/configuration/rename_iot.sh
  addons/point_of_sale/tools/posbox/configuration/wireless_ap.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/X11/xorg.conf
  addons/point_of_sale/tools/posbox/overwrite_after_init/etc/ld.so.preload
  addons/point_of_sale/tools/posbox/overwrite_after_init/home/pi/odoo/addons/point_of_sale/__manifest__.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/NetworkManager/conf.d/90-dns-none.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init.d/odoo
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/resolv.conf
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project_project.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/tests/views/fields/percent_pie_field.test.js
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  addons/website_sale/models/res_config_settings.py
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: tmp.saas-17.2

#28665 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/auth_passkey/models/auth_passkey_key.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_1.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_out_invoice_public_admin_2.xml
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/mail/i18n/mail.pot
  addons/mail/static/src/core/common/chat_bubble.js
  addons/mail/static/src/core/common/chat_bubble.xml
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/payment_xendit/static/src/js/payment_form.js
  addons/payment_xendit/views/payment_xendit_templates.xml
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/models/sale_order_line.py
  addons/snailmail/static/src/scss/snailmail_external_layout_asset.scss
  addons/spreadsheet/static/src/global_filters/plugins/global_filters_core_plugin.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_wave_picking.py
  addons/survey/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/page_properties.xml
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/fields.py
Labels: tmp.saas-17.4

#28666 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/lt.po
  addons/account/i18n/pt.po
  addons/account/i18n/zh_TW.po
  addons/account/views/report_payment_receipt_templates.xml
  addons/base_vat/i18n/zh_TW.po
  addons/event_booth/i18n/es_MX.po
  addons/google_recaptcha/i18n/et.po
  addons/hr/i18n/pt.po
  addons/hr_attendance/i18n/pt.po
  addons/hr_contract/i18n/lt.po
  addons/hr_contract/i18n/pt.po
  addons/hr_expense/i18n/pt.po
  addons/hr_fleet/i18n/pt.po
  addons/hr_holidays/i18n/pt.po
  addons/hr_holidays_attendance/i18n/pt.po
  addons/hr_org_chart/i18n/pt.po
  addons/hr_skills/i18n/pt.po
  addons/hr_timesheet/i18n/pt.po
  addons/hr_work_entry_contract/i18n/pt.po
  addons/l10n_eg_edi_eta/i18n/ar.po
  addons/l10n_eg_edi_eta/i18n/fr.po
  addons/l10n_eg_edi_eta/i18n/it.po
  addons/l10n_eg_edi_eta/models/res_currency_rate.py
  addons/l10n_nl/data/account.account.template.csv
  addons/mail/i18n/et.po
  addons/mail_plugin/i18n/et.po
  addons/mass_mailing_sms/i18n/da.po
  addons/mrp/i18n/lt.po
  addons/mrp_account/i18n/da.po
  addons/payment/i18n/da.po
  addons/portal/controllers/mail.py
  addons/pos_hr/i18n/pt.po
  addons/pos_mercury/i18n/et.po
  addons/pos_restaurant/i18n/tr.po
  addons/sale_timesheet/i18n/es.po
  addons/sale_timesheet/i18n/et.po
  addons/stock/i18n/da.po
  addons/web/i18n/da.po
  addons/web_editor/i18n/et.po
  addons/website/i18n/ro.po
  addons/website_event_booth_exhibitor/i18n/es_MX.po
  addons/website_event_track/i18n/es_MX.po
  addons/website_event_track/i18n/et.po
  addons/website_event_track_live/i18n/es_MX.po
  addons/website_event_track_quiz/i18n/es_MX.po
  addons/website_sale/i18n/et.po
  odoo/addons/base/i18n/cs.po
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_MX.po
  odoo/tools/safe_eval.py
Labels: tmp.15.0

#28669 Syncing from upstream odoo/odoo (15.0)
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/exception_logger.py
  addons/partner_autocomplete/models/res_partner.py
Labels: 15.0

#28670 Syncing from upstream odoo/odoo (16.0)
  addons/delivery/views/delivery_portal_template.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_nl/data/account.account.template.csv
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/purchase.py
Labels: 16.0

#28673 Syncing from upstream odoo/odoo (saas-17.1)
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/account_payment_register_views.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/mass_mailing/static/tests/tours/mailing_portal_unsubscribe_from_my.js
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/mass_mailing/views/mailing_templates_portal_unsubscribe.xml
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/product.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/kanban/progress_bar_hook.js
  addons/web/static/src/views/view_components/column_progress.xml
  addons/web/static/tests/setup.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  odoo/tests/common.py
Labels: saas-17.1

#28674 Syncing from upstream odoo/odoo (saas-17.2)
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message.test.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/point_of_sale/models/report_sale_details.py
  addons/project/static/src/views/project_task_form/project_task_form_controller.js
  addons/project/static/tests/tours/project_task_history.js
  addons/project/tests/test_project_ui.py
  addons/stock/models/product.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/kanban/progress_bar_hook.js
  addons/web/static/src/views/view_components/column_progress.xml
  addons/web/static/tests/legacy/views/fields/one2many_field_tests.js
  addons/web/static/tests/legacy/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  addons/website_sale/controllers/main.py
Labels: saas-17.2

#28677 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/account_payment_register_views.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/mass_mailing/static/tests/tours/mailing_portal_unsubscribe_from_my.js
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/mass_mailing/views/mailing_templates_portal_unsubscribe.xml
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/product.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/kanban/progress_bar_hook.js
  addons/web/static/src/views/view_components/column_progress.xml
  addons/web/static/tests/setup.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  odoo/tests/common.py
Labels: staging.saas-17.1

#28680 Syncing from upstream odoo/odoo (staging.15.0)
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/exception_logger.py
  addons/partner_autocomplete/models/res_partner.py
Labels: staging.15.0

#28681 Syncing from upstream odoo/odoo (staging.16.0)
  addons/delivery/views/delivery_portal_template.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_nl/data/account.account.template.csv
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/purchase.py
Labels: staging.16.0

#28682 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/account_payment_register_views.xml
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/exception_logger.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/mail/static/src/discuss/call/common/call_invitations.xml
  addons/mass_mailing/static/tests/tours/mailing_portal_unsubscribe_from_my.js
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/mass_mailing/views/mailing_templates_portal_unsubscribe.xml
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ErrorPopupTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/purchase_stock/models/stock_move.py
  addons/stock_delivery/views/delivery_portal_template.xml
  addons/web/models/models.py
  addons/web/static/tests/setup.js
  addons/web/tests/__init__.py
  addons/web/tests/test_web_read_group.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  odoo/models.py
  odoo/tests/common.py
Labels: staging.17.0

#28684 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/account_payment_register_views.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/mass_mailing/static/tests/tours/mailing_portal_unsubscribe_from_my.js
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/mass_mailing/views/mailing_templates_portal_unsubscribe.xml
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/spreadsheet_account/static/src/index.js
  addons/spreadsheet_account/static/tests/model/accounting_tests.js
  addons/spreadsheet_account/static/tests/ui/accounting_drilldown_tests.js
  addons/stock/models/product.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_picking_views.xml
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/kanban/progress_bar_hook.js
  addons/web/static/src/views/view_components/column_progress.xml
  addons/web/static/tests/setup.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  addons/website_sale/controllers/main.py
  addons/website_sale/static/src/scss/website_sale.scss
  addons/website_sale_picking/models/__init__.py
  addons/website_sale_picking/models/sale_order.py
  addons/website_sale_picking/static/tests/tours/onsite_payment_tour.js
  addons/website_sale_picking/tests/test_ui.py
  odoo/tests/common.py
Labels: tmp.saas-17.1

#28685 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/mail/static/tests/core/common/message.test.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/point_of_sale/models/report_sale_details.py
  addons/project/static/src/views/project_task_form/project_task_form_controller.js
  addons/project/static/tests/tours/project_task_history.js
  addons/project/tests/test_project_ui.py
  addons/stock/models/product.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/core/colorpicker/colorpicker.js
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/src/views/fields/many2many_tags/many2many_tags_field.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/src/views/fields/x2many/x2many_field.js
  addons/web/static/src/views/kanban/progress_bar_hook.js
  addons/web/static/src/views/view_components/column_progress.xml
  addons/web/static/tests/legacy/views/fields/one2many_field_tests.js
  addons/web/static/tests/legacy/views/kanban/kanban_view_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  addons/website_sale/controllers/main.py
Labels: tmp.saas-17.2

#28687 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/exception_logger.py
  addons/partner_autocomplete/models/res_partner.py
Labels: tmp.15.0

#28688 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/delivery/views/delivery_portal_template.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_nl/data/account.account.template.csv
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/purchase.py
Labels: tmp.16.0

#28689 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/account_payment_register_views.xml
  addons/hw_drivers/exception_logger.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/mail/static/src/discuss/call/common/call_invitations.xml
  addons/mass_mailing/static/tests/tours/mailing_portal_unsubscribe_from_my.js
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/mass_mailing/views/mailing_templates_portal_unsubscribe.xml
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/tests/tours/PaymentScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ErrorPopupTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/purchase_stock/models/stock_move.py
  addons/stock_delivery/views/delivery_portal_template.xml
  addons/web/models/models.py
  addons/web/static/tests/setup.js
  addons/web/tests/__init__.py
  addons/web/tests/test_web_read_group.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/menu.js
  odoo/models.py
  odoo/tests/common.py
Labels: tmp.17.0

#28690 Syncing from upstream odoo/odoo (15.0)
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/account_move_reversal.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/website_forum/models/forum.py
  addons/website_sale_slides/views/website_slides_templates.xml
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/models/ir_filters.py
Labels: 15.0

#28691 Syncing from upstream odoo/odoo (16.0)
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/account_move_reversal.py
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_latam_invoice_document/models/account_move.py
  addons/partner_autocomplete/models/res_partner.py
  addons/web/static/lib/owl/owl.js
Labels: 16.0

#28694 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/product.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_move_reversal.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/base_vat/models/res_partner.py
  addons/bus/tests/test_ir_websocket.py
  addons/hr_holidays/static/src/dashboard/time_off_dashboard.js
  addons/hr_holidays/static/tests/legacy/time_off_dashboard_tests.js
  addons/hw_drivers/exception_logger.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_withholding/__manifest__.py
  addons/l10n_in_withholding/models/account_chart_template.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.py
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/mail/static/src/discuss/call/common/call_invitations.xml
  addons/mass_mailing/static/tests/tours/mailing_portal_unsubscribe_from_my.js
  addons/mass_mailing/tests/test_mailing_controllers.py
  addons/mass_mailing/views/mailing_templates_portal_unsubscribe.xml
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/purchase/views/purchase_views.xml
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_delivery/views/delivery_portal_template.xml
  addons/web/static/src/core/browser/router.js
  addons/web/static/src/core/signature/name_and_signature.js
  addons/web/static/src/core/utils/urls.js
  addons/web/static/tests/core/router.test.js
  addons/web/static/tests/legacy/setup.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/views/product_views.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  odoo/addons/base/data/res_lang_data.xml
  odoo/tests/common.py
Labels: saas-17.2

#28695 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_move_reversal.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/base_vat/models/res_partner.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_withholding/__manifest__.py
  addons/l10n_in_withholding/models/account_chart_template.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.py
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/mail/static/src/core/common/chat_window_model.js
  addons/mail/static/src/core/common/composer.dark.scss
  addons/mail/static/src/core/common/composer.scss
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/discuss/voice_message/common/voice_recorder.xml
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/discuss/voice_message/voice_message.test.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_consume_component.py
  addons/product/models/product_product.py
  addons/project/static/src/views/project_task_form/project_task_form_controller.js
  addons/project/static/tests/tours/project_task_history.js
  addons/project/tests/test_project_ui.py
  addons/purchase/views/purchase_views.xml
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze.test.js
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_delivery/views/delivery_portal_template.xml
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/core/browser/router.js
  addons/web/static/src/core/signature/name_and_signature.js
  addons/web/static/src/core/utils/urls.js
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/tests/core/router.test.js
  addons/web/static/tests/views/fields/percent_pie_field.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/views/ir_actions_views.xml
  odoo/addons/base/views/res_partner_views.xml
Labels: saas-17.4

#28697 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/account/i18n/account.pot
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_tax.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_move_reversal.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/base_vat/models/res_partner.py
  addons/hr_holidays/static/src/dashboard/time_off_dashboard.js
  addons/hr_holidays/static/tests/time_off_dashboard_tests.js
  addons/l10n_bd/__manifest__.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_in_withholding/__manifest__.py
  addons/l10n_in_withholding/models/account_chart_template.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.py
  addons/mail/static/src/discuss/call/common/call_invitations.xml
  addons/mrp_account/models/product.py
  addons/product/models/product_product.py
  addons/purchase/views/purchase_views.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_delivery/views/delivery_portal_template.xml
  addons/web/models/models.py
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/tests/views/fields/percent_pie_field_tests.js
  addons/web/tests/__init__.py
  addons/web/tests/test_web_read_group.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/models.py
Labels: staging.saas-17.1

#28699 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/report_payment_receipt_templates.xml
  addons/account/wizard/account_move_reversal.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/base_vat/models/res_partner.py
  addons/l10n_bd/__manifest__.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_in_withholding/__manifest__.py
  addons/l10n_in_withholding/models/account_chart_template.py
  addons/l10n_in_withholding/wizard/l10n_in_withhold_wizard.py
  addons/l10n_pl/i18n/l10n_pl.pot
  addons/l10n_pl/i18n/pl.po
  addons/l10n_pl/models/account_move.py
  addons/mail/static/src/core/common/chat_window_model.js
  addons/mail/static/src/core/common/composer.dark.scss
  addons/mail/static/src/core/common/composer.scss
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/discuss/voice_message/common/voice_recorder.xml
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/discuss/voice_message/voice_message.test.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_consume_component.py
  addons/product/models/product_product.py
  addons/project/static/src/views/project_task_form/project_task_form_controller.js
  addons/project/static/tests/tours/project_task_history.js
  addons/project/tests/test_project_ui.py
  addons/purchase/views/purchase_views.xml
  addons/spreadsheet/static/src/helpers/model.js
  addons/spreadsheet/static/tests/public_spreadsheet/freeze.test.js
  addons/stock/models/product.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_scrap.py
  addons/stock/tests/test_move.py
  addons/stock_delivery/views/delivery_portal_template.xml
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/core/browser/router.js
  addons/web/static/src/core/signature/name_and_signature.js
  addons/web/static/src/core/utils/urls.js
  addons/web/static/src/views/fields/percent_pie/percent_pie_field.scss
  addons/web/static/tests/core/router.test.js
  addons/web/static/tests/views/fields/percent_pie_field.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/views/ir_actions_views.xml
  odoo/addons/base/views/res_partner_views.xml
Labels: staging.saas-17.4

#28700 Syncing from upstream odoo/odoo (staging.15.0)
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/wizard/account_move_reversal.py
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/website_forum/models/forum.py
  addons/website_sale_slides/views/website_slides_templates.xml
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/models/ir_filters.py
Labels: staging.15.0
