Repository brain-tec/odoo, pull requests merged in 2024-03, with the labels that each got.

#26618 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_report.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/snippets/s_tabs/options.js
Labels: 15.0

#26619 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_tax.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hr_holidays/models/hr_leave.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/stock/tests/test_inventory.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: 16.0

#26622 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_skills/views/hr_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/tablepicker/TablePicker.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: saas-15.2

#26623 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_tax.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_skills/views/hr_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
Labels: saas-16.1

#26624 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_skills/views/hr_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
Labels: saas-16.2

#26625 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_tax.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_skills/views/hr_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
Labels: saas-16.3

#26627 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_skills/views/hr_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/legacy/js/core/translation.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/tablepicker/TablePicker.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: staging.saas-15.2

#26628 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_tax.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_skills/views/hr_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
  addons/web/static/src/legacy/js/core/translation.js
Labels: staging.saas-16.1

#26629 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/models/account_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_skills/views/hr_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
Labels: staging.saas-16.2

#26630 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_tax.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hr_holidays/models/hr_leave.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/stock/tests/test_inventory.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: staging.16.0

#26632 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_skills/views/hr_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/tablepicker/TablePicker.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
Labels: tmp.saas-15.2

#26633 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_tax.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hr_skills/views/hr_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
Labels: tmp.saas-16.1

#26634 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_skills/views/hr_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
Labels: tmp.saas-16.2

#26635 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_tax.py
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/hr_skills/views/hr_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/project/static/src/js/tours/project.js
  addons/stock/tests/test_inventory.py
  addons/website_hr_recruitment/i18n/website_hr_recruitment.pot
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
Labels: tmp.saas-16.3

#26637 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_inventory.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_report.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/snippets/s_tabs/options.js
Labels: tmp.15.0

#26638 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_tax.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hr_holidays/models/hr_leave.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_in_edi/models/account_edi_format.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/stock/tests/test_inventory.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: tmp.16.0

#26640 Syncing from upstream odoo/odoo (15.0)
  .gitignore
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/stock_landed_costs/views/product_views.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/tests/test_security.py
Labels: 15.0

#26641 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/account_tax_python/tests/test_tax.py
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/loyalty/models/loyalty_program.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/tests/test_security.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tests/common.py
Labels: 16.0

#26644 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/project/views/project_sharing_views.xml
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/tests/common.py
Labels: saas-15.2

#26645 Syncing from upstream odoo/odoo (saas-16.1)
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: saas-16.1

#26646 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/chart_template.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_mx/models/account_account.py
  addons/project/models/project.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/integer_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: saas-16.2

#26647 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_mx/models/account_account.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/point_of_sale/models/report_sale_details.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: saas-16.3

#26648 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_mx/models/account_account.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/point_of_sale/models/report_sale_details.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  odoo/addons/base/models/ir_qweb.py
Labels: saas-16.4

#26649 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/project/views/project_sharing_views.xml
  addons/stock_landed_costs/views/product_views.xml
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/tests/common.py
Labels: staging.saas-15.2

#26650 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/stock_landed_costs/views/product_views.xml
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: staging.saas-16.1

#26651 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account/models/chart_template.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/project/models/project.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/integer_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: staging.saas-16.2

#26652 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/account_tax_python/tests/test_tax.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/loyalty/models/loyalty_program.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/tests/test_security.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tests/common.py
Labels: staging.16.0

#26654 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/project/views/project_sharing_views.xml
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/tests/common.py
Labels: tmp.saas-15.2

#26655 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: tmp.saas-16.1

#26656 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/chart_template.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_mx/models/account_account.py
  addons/project/models/project.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/integer_field_tests.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: tmp.saas-16.2

#26657 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/l10n_mx/models/account_account.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/point_of_sale/models/report_sale_details.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  odoo/addons/base/models/ir_qweb.py
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: tmp.saas-16.3

#26658 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/expense_mobile_tests.js
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_mx/models/account_account.py
  addons/payment_adyen/README.md
  addons/payment_adyen/__manifest__.py
  addons/payment_alipay/README.md
  addons/payment_alipay/__manifest__.py
  addons/payment_aps/README.md
  addons/payment_aps/__manifest__.py
  addons/payment_asiapay/README.md
  addons/payment_asiapay/__manifest__.py
  addons/payment_authorize/README.md
  addons/payment_authorize/__manifest__.py
  addons/payment_buckaroo/README.md
  addons/payment_buckaroo/__manifest__.py
  addons/payment_custom/README.md
  addons/payment_custom/__manifest__.py
  addons/payment_demo/README.md
  addons/payment_demo/__manifest__.py
  addons/payment_flutterwave/README.md
  addons/payment_flutterwave/__manifest__.py
  addons/payment_mercado_pago/README.md
  addons/payment_mercado_pago/__manifest__.py
  addons/payment_mollie/README.md
  addons/payment_mollie/__manifest__.py
  addons/payment_ogone/README.md
  addons/payment_ogone/__manifest__.py
  addons/payment_paypal/README.md
  addons/payment_paypal/__manifest__.py
  addons/payment_payulatam/README.md
  addons/payment_payulatam/__manifest__.py
  addons/payment_payumoney/README.md
  addons/payment_payumoney/__manifest__.py
  addons/payment_razorpay/README.md
  addons/payment_razorpay/__manifest__.py
  addons/payment_sips/README.md
  addons/payment_sips/__manifest__.py
  addons/payment_stripe/README.md
  addons/payment_stripe/__manifest__.py
  addons/point_of_sale/models/report_sale_details.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_sale_process.py
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.saas-16.4

#26659 Syncing from upstream odoo/odoo (tmp.15.0)
  .gitignore
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/stock_landed_costs/views/product_views.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/tests/test_security.py
Labels: tmp.15.0

#26660 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
  addons/account_tax_python/tests/test_tax.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_mx/models/account_account.py
  addons/loyalty/models/loyalty_program.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/stock_landed_costs/views/product_views.xml
  addons/web/static/src/legacy/js/core/translation.js
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/models/ir_qweb.py
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/tests/test_security.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tests/common.py
Labels: tmp.16.0

#26661 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/account.pot
  addons/account/models/account_tax.py
  addons/account/tests/test_account_tax.py
  addons/account/views/account_tax_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/hr/static/src/views/fields/many2one_avatar_employee_field/many2one_avatar_employee_field.js
  addons/hr/static/tests/m2x_avatar_employee_tests.js
  addons/hr_expense/__manifest__.py
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/tests/mobile/expense_mobile_tests.js
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/hw_drivers/iot_handlers/interfaces/DisplayInterface_L.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/bis3_ecotaxes_case4.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_be/data/template/account.account-be.csv
  addons/l10n_mx/models/account_account.py
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/tests/tours/mail_activity_schedule_from_chatter.js
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/printer_service.js
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/src/app/screens/partner_list/partner_editor/partner_editor.js
  addons/point_of_sale/static/src/app/store/product_configurator_popup/product_configurator_popup.xml
  addons/point_of_sale/static/src/utils.js
  addons/point_of_sale/static/tests/tours/ProductScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductConfiguratorTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/pos_razorpay/__init__.py
  addons/pos_razorpay/__manifest__.py
  addons/pos_razorpay/data/neutralize.sql
  addons/pos_razorpay/models/__init__.py
  addons/pos_razorpay/models/pos_payment.py
  addons/pos_razorpay/models/pos_payment_method.py
  addons/pos_razorpay/models/razorpay_pos_request.py
  addons/pos_razorpay/static/src/app/payment_razorpay.js
  addons/pos_razorpay/static/src/app/pos_razorpay.js
  addons/pos_razorpay/static/src/components/payment_screen/payment_screen.js
  addons/pos_razorpay/static/src/overrides/models.js
  addons/pos_razorpay/views/pos_payment_method_views.xml
  addons/pos_razorpay/views/pos_payment_views.xml
  addons/pos_self_order/static/src/app/components/order_widget/order_widget.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/web/static/src/core/user_service.js
  addons/web/static/tests/core/user_service_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/i18n/website.pot
  addons/website/models/ir_qweb.py
  addons/website/static/src/client_actions/configurator/configurator.scss
  addons/website/static/src/client_actions/configurator/configurator.xml
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/static/tests/tours/dropdowns_and_header_hide_on_scroll.js
  addons/website/tests/test_snippets.py
  addons/website_event_booth/controllers/event_booth.py
  addons/website_sale/models/product_ribbon.py
  odoo/addons/base/models/ir_qweb.py
Labels: tmp.17.0

#26666 Syncing from upstream odoo/odoo (master)
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/configurator/configurator.scss
  addons/website/static/src/client_actions/configurator/configurator.xml
Labels: master

#26667 Syncing from upstream odoo/odoo (saas-15.2)
  addons/account/i18n/de.po
  addons/account/i18n/es.po
  addons/account/i18n/es_MX.po
  addons/crm/i18n/es_MX.po
  addons/gamification/i18n/es_MX.po
  addons/hr_expense/i18n/es_MX.po
  addons/hr_gamification/i18n/es_MX.po
  addons/hr_holidays/i18n/es_MX.po
  addons/hr_org_chart/i18n/es_MX.po
  addons/hr_recruitment/i18n/es_MX.po
  addons/hr_skills_survey/i18n/zh_TW.po
  addons/hr_work_entry_contract/i18n/es_MX.po
  addons/http_routing/i18n/es_MX.po
  addons/http_routing/i18n/vi.po
  addons/im_livechat/i18n/es_MX.po
  addons/im_livechat/i18n/vi.po
  addons/mass_mailing/i18n/zh_TW.po
  addons/mass_mailing_sms/i18n/zh_TW.po
  addons/mrp/i18n/es_MX.po
  addons/point_of_sale/i18n/de.po
  addons/point_of_sale/i18n/es.po
  addons/point_of_sale/i18n/es_MX.po
  addons/point_of_sale/i18n/fr.po
  addons/point_of_sale/i18n/it.po
  addons/point_of_sale/i18n/nl.po
  addons/point_of_sale/i18n/uk.po
  addons/point_of_sale/i18n/vi.po
  addons/point_of_sale/i18n/zh_CN.po
  addons/point_of_sale/i18n/zh_TW.po
  addons/portal/i18n/vi.po
  addons/repair/i18n/es_MX.po
  addons/stock/i18n/de.po
  addons/stock/i18n/es.po
  addons/stock/i18n/es_MX.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/it.po
  addons/stock/i18n/nl.po
  addons/stock/i18n/uk.po
  addons/stock/i18n/vi.po
  addons/stock/i18n/zh_CN.po
  addons/stock/i18n/zh_TW.po
  addons/survey/i18n/zh_TW.po
  addons/uom/i18n/zh_TW.po
  addons/utm/i18n/zh_TW.po
  addons/web/i18n/zh_TW.po
  addons/web_editor/i18n/zh_TW.po
  addons/website_event_track_quiz/i18n/es_MX.po
  addons/website_sale/i18n/es_MX.po
  addons/website_slides/i18n/es_MX.po
  addons/website_slides_survey/i18n/es_MX.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/vi.po
Labels: saas-15.2

#26669 Syncing from upstream odoo/odoo (saas-16.3)
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
Labels: saas-16.3

#26671 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
Labels: staging.saas-16.1

#26672 Syncing from upstream odoo/odoo (tmp.master)
  addons/website/i18n/website.pot
  addons/website/static/src/client_actions/configurator/configurator.scss
  addons/website/static/src/client_actions/configurator/configurator.xml
Labels: tmp.master

#26673 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account_edi/models/account_edi_document.py
  addons/account_edi/models/account_move.py
Labels: tmp.saas-16.1

#26674 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
Labels: tmp.saas-16.3

#26676 Syncing from upstream odoo/odoo (saas-16.4)
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
Labels: saas-16.4

#26680 Syncing from upstream odoo/odoo (tmp.master)
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot-dom/helpers/events.js
  addons/web/static/lib/hoot-dom/hoot-dom.js
  addons/web/static/lib/hoot/core/fixture.js
  addons/web/static/lib/hoot/hoot.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/runner.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/events.test.js
  addons/web/static/lib/hoot/tests/hoot-owl-module.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/local_helpers.js
  addons/web/static/tests/_framework/component_test_helpers.js
  addons/web/static/tests/_framework/dom_test_helpers.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_templates.hoot.js
  addons/web/static/tests/_framework/view_test_helpers.js
  addons/web/static/tests/core/code_editor.test.js
  addons/web/static/tests/core/dialog.test.js
  addons/web/static/tests/core/utils/assets.test.js
  addons/web/static/tests/core/utils/timing.test.js
  addons/web/static/tests/views/fields/ace_field.test.js
  addons/web/static/tests/web_test_helpers.js
  addons/web/static/tests/webclient/barcode/barcode_scanner.test.js
  addons/web/tests/test_js.py
Labels: tmp.master

#26682 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
Labels: tmp.saas-16.4

#26684 Syncing from upstream odoo/odoo (15.0)
  addons/account_payment/views/account_portal_templates.xml
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/modules/module.py
Labels: 15.0

#26685 Syncing from upstream odoo/odoo (16.0)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/individual/kerbrose.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: 16.0

#26688 Syncing from upstream odoo/odoo (saas-15.2)
  .gitignore
  addons/account_edi_ubl_bis3/models/account_edi_format.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/tests/test_security.py
Labels: saas-15.2

#26689 Syncing from upstream odoo/odoo (saas-16.1)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/tests/common.py
Labels: saas-16.1

#26692 Syncing from upstream odoo/odoo (saas-16.4)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/mail/tests/test_mail_template.py
  addons/product/models/product_template_attribute_exclusion.py
  addons/product/tests/test_variants.py
  addons/project/models/project_task.py
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/integer_field_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/tests/common.py
Labels: saas-16.4

#26694 Syncing from upstream odoo/odoo (staging.saas-16.1)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/tests/common.py
Labels: staging.saas-16.1

#26697 Syncing from upstream odoo/odoo (staging.16.0)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/individual/kerbrose.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: staging.16.0

#26700 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_tax.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/mail/models/mail_mail.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/product/models/product_attribute.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_sale_delivery/tests/test_ui.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/tests/common.py
Labels: tmp.saas-16.1

#26703 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/mail/models/mail_mail.py
  addons/mail/models/mail_template.py
  addons/mail/tests/__init__.py
  addons/mail/tests/test_mail_mail_stable_selection.py
  addons/mail/tests/test_mail_template.py
  addons/product/models/product_template_attribute_exclusion.py
  addons/product/tests/test_variants.py
  addons/project/models/project_task.py
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/src/views/relational_model.js
  addons/web/static/tests/views/fields/integer_field_tests.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/snippets/s_website_form/options.js
  odoo/tests/common.py
Labels: tmp.saas-16.4

#26705 Syncing from upstream odoo/odoo (tmp.16.0)
  .gitignore
  addons/account/i18n/account.pot
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/tests/common.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/individual/kerbrose.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.16.0

#26707 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website_forum/controllers/main.py
Labels: 15.0

#26708 Syncing from upstream odoo/odoo (16.0)
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/project/views/project_sharing_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/views/website_slides_templates_course.xml
Labels: 16.0

#26711 Syncing from upstream odoo/odoo (saas-15.2)
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/tests/test_module.py
  odoo/modules/module.py
Labels: saas-15.2

#26712 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: saas-16.1

#26713 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: saas-16.2

#26714 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_chart_template.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/scss/bootstrap_review_frontend.scss
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: saas-16.3

#26715 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_account/models/stock_rule.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/tests/test_report_session.py
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/repair/models/stock_move.py
  addons/repair/tests/test_repair.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale_mrp/models/stock_move.py
  addons/sale_mrp/tests/__init__.py
  addons/sale_mrp/tests/test_sale_mrp_account.py
  addons/stock/models/stock_orderpoint.py
  addons/website_forum/views/website_profile_templates.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: saas-16.4

#26716 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/tests/test_module.py
  odoo/modules/module.py
Labels: staging.saas-15.2

#26717 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: staging.saas-16.1

#26718 Syncing from upstream odoo/odoo (staging.saas-16.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: staging.saas-16.2

#26720 Syncing from upstream odoo/odoo (staging.16.0)
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/project/views/project_sharing_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/views/website_slides_templates_course.xml
Labels: staging.16.0

#26722 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/point_of_sale/static/src/js/Screens/ClientListScreen/ClientListScreen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_forum/views/website_forum_profile.xml
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/tests/test_module.py
  odoo/modules/module.py
Labels: tmp.saas-15.2

#26723 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/views/website_slides_templates_course.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.saas-16.1

#26724 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/stock/data/stock_data.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/tests/test_robustness.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.saas-16.2

#26725 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_chart_template.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_id_efaktur/views/res_partner_views.xml
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/static/src/js/models.js
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/scss/bootstrap_review_frontend.scss
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.saas-16.3

#26726 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_in_refund.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/account/tests/test_tax.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_tax_python/tests/test_tax.py
  addons/hr_contract/wizard/hr_departure_wizard.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_recruitment/views/ir_attachment_views.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_be.py
  addons/l10n_it_edi_website_sale/controllers/main.py
  addons/l10n_it_edi_website_sale/i18n/it.po
  addons/l10n_it_edi_website_sale/i18n/l10n_it_edi_website_sale.pot
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/loyalty/models/loyalty_program.py
  addons/mrp_account/models/stock_rule.py
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/tests/test_report_session.py
  addons/pos_restaurant/static/tests/tours/helpers/BillScreenTourMethods.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/repair/models/stock_move.py
  addons/repair/tests/test_repair.py
  addons/sale/tests/test_sale_order_down_payment.py
  addons/sale_mrp/models/stock_move.py
  addons/sale_mrp/tests/__init__.py
  addons/sale_mrp/tests/test_sale_mrp_account.py
  addons/stock/models/stock_orderpoint.py
  addons/website_forum/views/website_profile_templates.xml
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_slides/controllers/mail.py
  addons/website_slides/i18n/website_slides.pot
  addons/website_slides/static/src/js/slides_embed.js
  addons/website_slides/static/src/js/slides_slide_toggle_is_preview.js
  addons/website_slides/static/src/scss/website_slides.scss
  addons/website_slides/tests/test_security.py
  addons/website_slides/views/website_slides_templates_course.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.saas-16.4

#26728 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website_forum/controllers/main.py
Labels: tmp.15.0

#26729 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/mrp_subcontracting/views/stock_move_views.xml
  addons/project/views/project_sharing_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_slides/views/website_slides_templates_course.xml
Labels: tmp.16.0

#26731 Syncing from upstream odoo/odoo (15.0)
  addons/event/models/event_mail.py
  addons/event_sms/models/event_mail.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/test_event_full/tests/test_event_mail.py
Labels: 15.0

#26732 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_payment/models/payment_provider.py
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/point_of_sale/models/stock_picking.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_forum/controllers/main.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  doc/cla/corporate/adhoc.md
  odoo/tools/safe_eval.py
Labels: 16.0

#26735 Syncing from upstream odoo/odoo (saas-15.2)
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website_forum/controllers/main.py
Labels: saas-15.2

#26736 Syncing from upstream odoo/odoo (saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_early_payment_discount.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/point_of_sale/static/src/js/models.js
  addons/project/views/project_sharing_views.xml
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
  odoo/tools/safe_eval.py
Labels: saas-16.1

#26737 Syncing from upstream odoo/odoo (saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_early_payment_discount.py
  addons/delivery/i18n/delivery.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/project/views/project_sharing_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/stock_delivery/wizard/choose_delivery_package.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
Labels: saas-16.2

#26738 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_report.py
  addons/account/views/account_move_views.xml
  addons/account/views/partner_view.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_edi/views/account_payment_views.xml
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/crm_iap_mine/views/crm_iap_lead_mining_request_views.xml
  addons/event_sale/wizard/event_edit_registration.xml
  addons/hr_work_entry_contract/views/hr_work_entry_views.xml
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_hk/tests/test_l10n_hk_emv_qr.py
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/mail_bot_hr/views/res_users_views.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/sale/views/sale_order_views.xml
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_report.py
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/form/form_controller.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/website_forum.py
  addons/website_slides/wizard/slide_channel_invite_views.xml
Labels: saas-16.3

#26739 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/l10n_hk/tests/test_l10n_hk_emv_qr.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_report.py
  addons/web/static/src/scss/bootstrap_review_frontend.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: saas-16.4

#26740 Syncing from upstream odoo/odoo (staging.saas-15.2)
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website_forum/controllers/main.py
Labels: staging.saas-15.2

#26741 Syncing from upstream odoo/odoo (staging.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_early_payment_discount.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/point_of_sale/static/src/js/models.js
  addons/project/views/project_sharing_views.xml
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
  odoo/tools/safe_eval.py
Labels: staging.saas-16.1

#26744 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_payment/models/payment_provider.py
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/point_of_sale/models/stock_picking.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_forum/controllers/main.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  doc/cla/corporate/adhoc.md
  odoo/tools/safe_eval.py
Labels: staging.16.0

#26746 Syncing from upstream odoo/odoo (tmp.saas-15.2)
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/web_editor/static/lib/odoo-editor/src/commands/commands.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/website_forum/controllers/main.py
Labels: tmp.saas-15.2

#26747 Syncing from upstream odoo/odoo (tmp.saas-16.1)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_early_payment_discount.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/stock_picking.py
  addons/delivery/tests/test_packing_delivery.py
  addons/delivery/wizard/choose_delivery_package.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/point_of_sale/static/src/js/models.js
  addons/project/views/project_sharing_views.xml
  addons/purchase_product_matrix/i18n/purchase_product_matrix.pot
  addons/purchase_product_matrix/static/src/js/purchase_product_field.js
  addons/purchase_product_matrix/views/purchase_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/views/fields/reference/reference_field.js
  addons/web/static/tests/views/fields/reference_field_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
  odoo/tools/safe_eval.py
Labels: tmp.saas-16.1

#26748 Syncing from upstream odoo/odoo (tmp.saas-16.2)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/account/tests/test_early_payment_discount.py
  addons/delivery/i18n/delivery.pot
  addons/hr_holidays/models/hr_leave.py
  addons/hr_recruitment/models/hr_applicant.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/project/views/project_sharing_views.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_packing.py
  addons/stock/tests/test_report.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/stock_delivery/wizard/choose_delivery_package.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/main.py
Labels: tmp.saas-16.2

#26749 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_report.py
  addons/account/views/account_move_views.xml
  addons/account/views/partner_view.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_edi/views/account_payment_views.xml
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/crm_iap_mine/views/crm_iap_lead_mining_request_views.xml
  addons/event_sale/wizard/event_edit_registration.xml
  addons/hr_work_entry_contract/views/hr_work_entry_views.xml
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/views/account_invoice_view.xml
  addons/l10n_hk/tests/test_l10n_hk_emv_qr.py
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/mail_bot_hr/views/res_users_views.xml
  addons/point_of_sale/static/src/js/Screens/PartnerListScreen/PartnerListScreen.js
  addons/sale/views/sale_order_views.xml
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_report.py
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/views/form/form_controller.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_forum/controllers/website_forum.py
  addons/website_slides/wizard/slide_channel_invite_views.xml
Labels: tmp.saas-16.3

#26750 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/l10n_hk/tests/test_l10n_hk_emv_qr.py
  addons/stock/report/product_label_report.py
  addons/stock/report/product_templates.xml
  addons/stock/tests/test_report.py
  addons/web/static/src/scss/bootstrap_review_frontend.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/xml/wysiwyg.xml
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: tmp.saas-16.4

#26751 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/event/models/event_mail.py
  addons/event_sms/models/event_mail.py
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/point_of_sale/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  addons/point_of_sale/static/src/js/models.js
  addons/test_event_full/tests/test_event_mail.py
Labels: tmp.15.0

#26752 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/account_reconcile_model.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/account_payment/models/payment_provider.py
  addons/l10n_lu/data/account_tax_template_2015.xml
  addons/point_of_sale/models/stock_picking.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website_forum/controllers/main.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  doc/cla/corporate/adhoc.md
  odoo/tools/safe_eval.py
Labels: tmp.16.0

#26755 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_blog/controllers/main.py
  addons/website_blog/views/snippets/s_blog_posts.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: 15.0

#26756 Syncing from upstream odoo/odoo (16.0)
  addons/account/views/account_journal_views.xml
  addons/crm/views/crm_team_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/mail/views/mail_alias_views.xml
  addons/mail/views/res_config_settings_views.xml
  addons/mail_group/views/mail_group_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/models/mrp_unbuild.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/project/views/project_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/i18n/website.pot
  addons/website/models/res_company.py
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_res_users.py
  addons/website_sale/controllers/main.py
Labels: 16.0

#26759 Syncing from upstream odoo/odoo (saas-16.1)
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: saas-16.1

#26760 Syncing from upstream odoo/odoo (saas-16.2)
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
Labels: saas-16.2

#26761 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/tests/test_early_payment_discount.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock/tests/test_report.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website_sale/controllers/main.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  doc/cla/corporate/adhoc.md
Labels: saas-16.3

#26762 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/views/account_move_views.xml
  addons/account/views/partner_view.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_peppol/models/res_partner.py
  addons/crm_iap_mine/views/crm_iap_lead_mining_request_views.xml
  addons/event_sale/wizard/event_edit_registration.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_work_entry_contract/views/hr_work_entry_views.xml
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/views/account_payment_view.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail_bot_hr/views/res_users_views.xml
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/views/sale_order_views.xml
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_report.py
  addons/survey/views/survey_question_views.xml
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web/i18n/web.pot
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/search/custom_favorite_item/custom_favorite_item.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/website_forum/controllers/website_forum.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  addons/website_slides/wizard/slide_channel_invite_views.xml
  doc/cla/corporate/adhoc.md
Labels: saas-16.4

#26763 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/account/tests/test_early_payment_discount.py
  addons/account/views/account_move_views.xml
  addons/account/views/partner_view.xml
  addons/account_edi/views/account_move_views.xml
  addons/account_peppol/models/res_partner.py
  addons/crm_iap_mine/views/crm_iap_lead_mining_request_views.xml
  addons/event_sale/wizard/event_edit_registration.xml
  addons/hr_holidays/models/hr_leave.py
  addons/hr_work_entry_contract/views/hr_work_entry_views.xml
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_ch/views/account_payment_view.xml
  addons/l10n_it_edi/data/invoice_it_simplified_template.xml
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_latam_check/views/account_payment_view.xml
  addons/mail_bot_hr/views/res_users_views.xml
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project_task_recurrence.py
  addons/project/tests/test_project_recurrence.py
  addons/sale/views/sale_order_views.xml
  addons/sms/wizard/sms_composer_views.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_report.py
  addons/survey/views/survey_question_views.xml
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web/i18n/web.pot
  addons/web/static/src/scss/bootstrap_review_backend.scss
  addons/web/static/src/search/custom_favorite_item/custom_favorite_item.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/website_forum/controllers/website_forum.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  addons/website_slides/wizard/slide_channel_invite_views.xml
  doc/cla/corporate/adhoc.md
Labels: tmp.saas-16.4

#26764 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/tests/field_html_tests.js
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_blog/controllers/main.py
  addons/website_blog/views/snippets/s_blog_posts.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: tmp.15.0

#26765 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/views/account_journal_views.xml
  addons/crm/views/crm_team_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/mail/views/mail_alias_views.xml
  addons/mail/views/res_config_settings_views.xml
  addons/mail_group/views/mail_group_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/models/mrp_unbuild.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/project/views/project_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/i18n/website.pot
  addons/website/models/res_company.py
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_res_users.py
  addons/website_sale/controllers/main.py
Labels: tmp.16.0

#26766 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_qr_code_emv/i18n/account_qr_code_emv.pot
  addons/account_qr_code_emv/models/res_bank.py
  addons/calendar/views/calendar_views.xml
  addons/hr/models/hr_employee.py
  addons/hr_contract/models/hr_employee.py
  addons/l10n_ar/data/l10n_latam.document.type.csv
  addons/l10n_ar/models/account_journal.py
  addons/l10n_br_pix/__init__.py
  addons/l10n_br_pix/__manifest__.py
  addons/l10n_br_pix/i18n/l10n_br_pix.pot
  addons/l10n_br_pix/i18n/pt_BR.po
  addons/l10n_br_pix/models/__init__.py
  addons/l10n_br_pix/models/res_partner_bank.py
  addons/l10n_br_pix/tests/__init__.py
  addons/l10n_br_pix/tests/test_l10n_br_pix.py
  addons/l10n_br_pix/views/res_bank_views.xml
  addons/l10n_es_pos/static/src/overrides/components/payment_screen/payment_screen.js
  addons/l10n_es_pos/static/tests/tours/spanish_pos_tour.js
  addons/l10n_es_pos/tests/test_frontend.py
  addons/l10n_hk/tests/test_l10n_hk_emv_qr.py
  addons/l10n_in/models/__init__.py
  addons/l10n_in/models/account_invoice.py
  addons/l10n_in/models/account_tax.py
  addons/l10n_in/tests/__init__.py
  addons/l10n_in/tests/test_invoice_hsn_summary.py
  addons/l10n_in/tests/test_partner_details_on_invoice.py
  addons/l10n_it_edi/models/account_move.py
  addons/mail/__init__.py
  addons/mail/__manifest__.py
  addons/mail/models/mail_alias_domain.py
  addons/mail/tests/test_mail_tools.py
  addons/mrp/models/mrp_workcenter.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_list/product_list.xml
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_razorpay/static/src/app/payment_razorpay.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/stock/tests/test_report.py
  addons/test_website/controllers/main.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/website/static/src/js/editor/snippets.options.js
  addons/website_forum/controllers/website_forum.py
  addons/website_slides/static/tests/tours/slide_course_publisher_standard.js
  addons/website_slides/static/tests/tours/slides_tour_tools.js
  addons/website_slides/tests/test_ui_wslides.py
  doc/cla/corporate/adhoc.md
  doc/cla/individual/gauravpandey068.md
  odoo/addons/base/tests/test_http_case.py
  odoo/tests/common.py
Labels: tmp.17.0

#26754 [bt#26065][FIX] web: Allow users to select maxDate and edit it
  addons/web/static/src/legacy/js/widgets/date_picker.js
Labels: 15.0.project_sv_559

#26767 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_journal.py
  addons/web_editor/models/ir_ui_view.py
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/tests/__init__.py
  addons/website/tests/test_custom_snippets.py
  doc/cla/corporate/braintec.md
Labels: 15.0

#26768 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_account.py
  addons/account/models/account_bank_statement_line.py
  addons/account/models/company.py
  addons/account/tests/test_account_account.py
  addons/account/wizard/setup_wizards_view.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/migrations/3.6/post-migrate_update_taxes.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/payment_alipay/README.md
  addons/payment_authorize/README.md
  addons/payment_buckaroo/README.md
  addons/payment_payumoney/README.md
  addons/product_expiry/report/report_lot_barcode.xml
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_blog/views/snippets/s_blog_posts.xml
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: 16.0

#26771 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/views/account_journal_views.xml
  addons/crm/views/crm_team_views.xml
  addons/delivery/i18n/delivery.pot
  addons/hr_contract/models/hr_contract.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/l10n_de_skr03/data/template/account.fiscal.position-de_skr03.csv
  addons/l10n_lu/data/template/account.tax-lu.csv
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/mail/views/mail_alias_views.xml
  addons/mail/views/res_config_settings_views.xml
  addons/mail_group/views/mail_group_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/models/mrp_unbuild.py
  addons/point_of_sale/models/stock_picking.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_account/models/account_move.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/stock_delivery/wizard/choose_delivery_package.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/i18n/website.pot
  addons/website/models/res_company.py
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_res_users.py
  addons/website_blog/controllers/main.py
  addons/website_blog/views/snippets/s_blog_posts.xml
  addons/website_hr_recruitment/controllers/main.py
  doc/cla/individual/kerbrose.md
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: saas-16.3

#26772 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/views/account_journal_views.xml
  addons/crm/views/crm_team_views.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/l10n_de/data/template/account.fiscal.position-de_skr03.csv
  addons/l10n_lu/data/template/account.tax-lu.csv
  addons/mail/views/mail_alias_views.xml
  addons/mail/views/res_config_settings_views.xml
  addons/mail_group/views/mail_group_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/models/mrp_unbuild.py
  addons/onboarding/models/__init__.py
  addons/onboarding/models/onboarding_progress.py
  addons/onboarding/models/res_company.py
  addons/onboarding/tests/test_onboarding.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_capture.py
  addons/point_of_sale/tools/__init__.py
  addons/point_of_sale/tools/pos_order_data.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_project/models/project.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/account_move.py
  addons/website/i18n/website.pot
  addons/website/models/res_company.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/tests/test_res_users.py
  addons/website_blog/controllers/main.py
  addons/website_blog/views/snippets/s_blog_posts.xml
  addons/website_hr_recruitment/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  doc/cla/individual/kerbrose.md
Labels: saas-16.4

#26774 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_account.py
  addons/account/models/account_bank_statement_line.py
  addons/account/models/company.py
  addons/account/tests/test_account_account.py
  addons/account/views/account_journal_views.xml
  addons/account/wizard/setup_wizards_view.xml
  addons/crm/views/crm_team_views.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_recruitment/views/hr_recruitment_views.xml
  addons/l10n_de_skr03/data/account_tax_fiscal_position_data.xml
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/migrations/3.6/post-migrate_update_taxes.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/mail/views/mail_alias_views.xml
  addons/mail/views/res_config_settings_views.xml
  addons/mail_group/views/mail_group_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/models/mrp_unbuild.py
  addons/payment_alipay/README.md
  addons/payment_authorize/README.md
  addons/payment_buckaroo/README.md
  addons/payment_payumoney/README.md
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/product_expiry/report/report_lot_barcode.xml
  addons/project/views/project_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/i18n/website.pot
  addons/website/models/res_company.py
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/test_res_users.py
  addons/website_blog/views/snippets/s_blog_posts.xml
  addons/website_sale/controllers/main.py
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: staging.16.0

#26777 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/tests/test_chart_template.py
  addons/account/views/account_journal_views.xml
  addons/crm/views/crm_team_views.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_expense/views/res_config_settings_views.xml
  addons/l10n_de/data/template/account.fiscal.position-de_skr03.csv
  addons/l10n_lu/data/template/account.tax-lu.csv
  addons/mail/views/mail_alias_views.xml
  addons/mail/views/res_config_settings_views.xml
  addons/mail_group/views/mail_group_views.xml
  addons/maintenance/views/maintenance_views.xml
  addons/mrp/models/mrp_unbuild.py
  addons/onboarding/models/__init__.py
  addons/onboarding/models/onboarding_progress.py
  addons/onboarding/models/res_company.py
  addons/onboarding/tests/test_onboarding.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_pos_capture.py
  addons/point_of_sale/tools/__init__.py
  addons/point_of_sale/tools/pos_order_data.py
  addons/pos_stripe/static/src/js/payment_stripe.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_project/models/project.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/models/account_move.py
  addons/website/i18n/website.pot
  addons/website/models/res_company.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website/tests/test_res_users.py
  addons/website_blog/controllers/main.py
  addons/website_blog/views/snippets/s_blog_posts.xml
  addons/website_hr_recruitment/controllers/main.py
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  doc/cla/individual/kerbrose.md
Labels: tmp.saas-16.4

#26778 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_journal.py
  addons/web_editor/models/ir_ui_view.py
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/tests/__init__.py
  addons/website/tests/test_custom_snippets.py
  doc/cla/corporate/braintec.md
Labels: tmp.15.0

#26779 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_account.py
  addons/account/models/account_bank_statement_line.py
  addons/account/models/company.py
  addons/account/tests/test_account_account.py
  addons/account/wizard/setup_wizards_view.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/account.account.template.csv
  addons/l10n_ec/data/account_tax_template_withhold_profit_data.xml
  addons/l10n_ec/migrations/3.6/post-migrate_update_taxes.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/payment_alipay/README.md
  addons/payment_authorize/README.md
  addons/payment_buckaroo/README.md
  addons/payment_payumoney/README.md
  addons/product_expiry/report/report_lot_barcode.xml
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_image_gallery/000.xml
  addons/website_blog/views/snippets/s_blog_posts.xml
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: tmp.16.0

#26785 Syncing from upstream odoo/odoo (master)
  addons/product_expiry/report/report_lot_barcode.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_project/models/project.py
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
Labels: master

#26788 Syncing from upstream odoo/odoo (saas-16.3)
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/product_expiry/report/report_lot_barcode.xml
Labels: saas-16.3

#26790 Syncing from upstream odoo/odoo (tmp.master)
  addons/product_expiry/report/report_lot_barcode.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_project/models/project.py
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
Labels: tmp.master

#26791 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/product_expiry/report/report_lot_barcode.xml
Labels: tmp.saas-16.3

#26792 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/__init__.py
  addons/hw_drivers/server_logger.py
  addons/hw_posbox_homepage/controllers/main.py
  addons/hw_posbox_homepage/views/handler_list.html
  addons/product_expiry/report/report_lot_barcode.xml
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/web/static/src/views/fields/input_field_hook.js
  addons/web/static/tests/views/list_view_tests.js
Labels: tmp.saas-16.4

#26793 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/pos_online_payment_self_order/static/src/components/order_widget/order_widget.js
  addons/pos_online_payment_self_order/static/src/pages/payment_page/payment_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/product_expiry/report/report_lot_barcode.xml
  addons/sale_project/models/project.py
Labels: tmp.17.0

#26794 Syncing from upstream odoo/odoo (16.0)
  addons/web_editor/models/ir_ui_view.py
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/tests/__init__.py
  addons/website/tests/test_custom_snippets.py
Labels: 16.0

#26800 Syncing from upstream odoo/odoo (14.0)
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/api.py
Labels: 14.0

#26801 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_nl.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/api.py
Labels: 15.0

#26802 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/event/models/event_mail.py
  addons/event_sms/models/event_mail.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_event_full/tests/test_event_mail.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/tests/test_tools.py
  addons/web_editor/tools.py
  addons/website/models/website.py
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/tests/test_get_current_website.py
  addons/website_blog/controllers/main.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_module.py
  odoo/api.py
  odoo/modules/module.py
Labels: 16.0

#26805 Syncing from upstream odoo/odoo (saas-15.2)
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/api.py
Labels: saas-15.2

#26806 Syncing from upstream odoo/odoo (saas-16.1)
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/api.py
Labels: saas-16.1

#26807 Syncing from upstream odoo/odoo (saas-16.2)
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/api.py
Labels: saas-16.2

#26808 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_account.py
  addons/account/models/company.py
  addons/account/tests/test_account_account.py
  addons/account/wizard/setup_wizards_view.xml
  addons/account_payment/models/account_move.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/template/account.account-ec.csv
  addons/l10n_ec/data/template/account.tax-ec.csv
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/models/website.py
  addons/website/tests/test_get_current_website.py
  addons/website_event_sale/views/website_event_templates.xml
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_module.py
  odoo/api.py
  odoo/modules/module.py
Labels: saas-16.3

#26809 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_account.py
  addons/account/models/company.py
  addons/account/tests/test_account_account.py
  addons/account/wizard/setup_wizards_view.xml
  addons/delivery/i18n/delivery.pot
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/stock_delivery/wizard/choose_delivery_package.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/models/ir_ui_view.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/snippet_image_gallery.js
  addons/website/tests/__init__.py
  addons/website/tests/test_custom_snippets.py
  addons/website_event_sale/views/website_event_templates.xml
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_module.py
  odoo/api.py
  odoo/modules/module.py
Labels: saas-16.4

#26810 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_journal.py
  addons/event/models/event_mail.py
  addons/event_sms/models/event_mail.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_event_full/tests/test_event_mail.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/tests/test_tools.py
  addons/web_editor/tools.py
  addons/website/models/website.py
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/tests/test_get_current_website.py
  addons/website_blog/controllers/main.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_module.py
  odoo/api.py
  odoo/modules/module.py
Labels: staging.16.0

#26812 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_account.py
  addons/account/models/company.py
  addons/account/tests/test_account_account.py
  addons/account/wizard/setup_wizards_view.xml
  addons/account_payment/models/account_move.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/l10n_ec/__manifest__.py
  addons/l10n_ec/data/template/account.account-ec.csv
  addons/l10n_ec/data/template/account.tax-ec.csv
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/test_mail/static/tests/activity_tests.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website/models/website.py
  addons/website/tests/test_get_current_website.py
  addons/website_event_sale/views/website_event_templates.xml
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_module.py
  odoo/api.py
  odoo/modules/module.py
Labels: tmp.saas-16.3

#26815 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_journal.py
  addons/event/models/event_mail.py
  addons/event_sms/models/event_mail.py
  addons/l10n_it_stock_ddt/i18n/it.po
  addons/l10n_it_stock_ddt/i18n/l10n_it_stock_ddt.pot
  addons/l10n_it_stock_ddt/models/stock_picking.py
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_event_full/tests/test_event_mail.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/tests/test_tools.py
  addons/web_editor/tools.py
  addons/website/models/website.py
  addons/website/static/src/js/tours/tour_utils.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/tests/test_get_current_website.py
  addons/website_blog/controllers/main.py
  addons/website_slides/models/slide_slide.py
  addons/website_slides/models/website.py
  addons/website_twitter/controllers/main.py
  addons/website_twitter/models/website_twitter.py
  doc/cla/corporate/braintec.md
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_module.py
  odoo/api.py
  odoo/modules/module.py
Labels: tmp.16.0

#26817 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/account_move.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de_purchase/i18n/de.po
  addons/l10n_de_purchase/i18n/l10n_de_purchase.pot
  addons/l10n_de_repair/i18n/de.po
  addons/l10n_de_repair/i18n/l10n_de_repair.pot
  addons/l10n_de_sale/i18n/de.po
  addons/l10n_de_sale/i18n/l10n_de_sale.pot
  addons/l10n_de_stock/i18n/de.po
  addons/l10n_de_stock/i18n/l10n_de_stock.pot
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/website_blog/views/website_blog_components.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_ir_cron.py
Labels: 15.0

#26818 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/bus/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_nl.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/mail/models/mail_thread.py
  addons/purchase/models/account_invoice.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/website/static/src/js/content/inject_dom.js
  addons/website/static/src/snippets/s_popup/000.js
Labels: 16.0

#26821 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_journal.py
  addons/account/models/account_payment.py
  addons/account/models/partner.py
  addons/account/tests/test_account_payment.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_orderpoint.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_cost.py
  doc/cla/corporate/braintec.md
Labels: saas-16.3

#26822 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_journal.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/account_payment/models/account_move.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/mrp/models/mrp_workorder.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website/models/website.py
  addons/website/tests/test_get_current_website.py
  doc/cla/corporate/braintec.md
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: saas-16.4

#26823 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/bus/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_nl.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/mail/models/mail_thread.py
  addons/purchase/models/account_invoice.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/website/static/src/js/content/inject_dom.js
  addons/website/static/src/snippets/s_popup/000.js
Labels: staging.16.0

#26825 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_journal.py
  addons/account/models/account_payment.py
  addons/account/models/partner.py
  addons/account/tests/test_account_payment.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_orderpoint.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_cost.py
  doc/cla/corporate/braintec.md
Labels: tmp.saas-16.3

#26826 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_journal.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/account_payment/models/account_move.py
  addons/account_payment/views/account_portal_templates.xml
  addons/hr_recruitment/models/hr_applicant.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/mrp/models/mrp_workorder.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website/models/website.py
  addons/website/tests/test_get_current_website.py
  doc/cla/corporate/braintec.md
  odoo/addons/base/tests/test_api.py
  odoo/models.py
Labels: tmp.saas-16.4

#26827 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/account_move.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de_purchase/i18n/de.po
  addons/l10n_de_purchase/i18n/l10n_de_purchase.pot
  addons/l10n_de_repair/i18n/de.po
  addons/l10n_de_repair/i18n/l10n_de_repair.pot
  addons/l10n_de_sale/i18n/de.po
  addons/l10n_de_sale/i18n/l10n_de_sale.pot
  addons/l10n_de_stock/i18n/de.po
  addons/l10n_de_stock/i18n/l10n_de_stock.pot
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/website_blog/views/website_blog_components.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/tests/test_ir_cron.py
Labels: tmp.15.0

#26828 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/bus/tests/common.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_nl.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/mail/models/mail_thread.py
  addons/purchase/models/account_invoice.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/src/views/list/list_renderer.xml
  addons/website/static/src/js/content/inject_dom.js
  addons/website/static/src/snippets/s_popup/000.js
Labels: tmp.16.0

#26830 Syncing from upstream odoo/odoo (15.0)
  addons/account/models/ir_actions_report.py
  addons/account_edi/models/account_edi_format.py
  addons/mail_group/data/mail_template_data.xml
  addons/mail_group/i18n/mail_group.pot
  addons/sale/views/sale_portal_templates.xml
  addons/web/static/src/legacy/scss/bootstrap_review.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.scss
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/minimal.pdf
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_pdf.py
  odoo/netsvc.py
  odoo/tools/pdf.py
Labels: 15.0

#26831 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/l10n_latam_check/tests/test_third_party_checks.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/models/stock_quant.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
  odoo/addons/base/models/ir_actions_report.py
Labels: 16.0

#26834 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/models/account_payment_term.py
  addons/hr/models/res_partner.py
  addons/hr/tests/test_hr_employee.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/purchase/models/account_invoice.py
  addons/stock/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/stock_dropshipping/views/purchase_order_views.xml
  addons/website/static/src/js/content/inject_dom.js
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
Labels: saas-16.3

#26835 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/account_payment_term.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/hr/models/hr_employee_base.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/l10n_mx/models/res_config_settings.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_cost.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
Labels: saas-16.4

#26836 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/l10n_latam_check/tests/test_third_party_checks.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/models/stock_quant.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.16.0

#26838 Syncing from upstream odoo/odoo (tmp.saas-16.3)
  addons/account/models/account_payment_term.py
  addons/hr/models/res_partner.py
  addons/hr/tests/test_hr_employee.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/purchase/models/account_invoice.py
  addons/stock/models/stock_move.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/stock_dropshipping/views/purchase_order_views.xml
  addons/website/static/src/js/content/inject_dom.js
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
Labels: tmp.saas-16.3

#26839 Syncing from upstream odoo/odoo (tmp.saas-16.4)
  addons/account/models/account_payment_term.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/hr/models/hr_employee_base.py
  addons/l10n_din5008_sale/i18n/de.po
  addons/l10n_mx/models/res_config_settings.py
  addons/mrp/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_picking.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_cost.py
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
Labels: tmp.saas-16.4

#26840 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/models/ir_actions_report.py
  addons/account_edi/models/account_edi_format.py
  addons/mail_group/data/mail_template_data.xml
  addons/mail_group/i18n/mail_group.pot
  addons/sale/views/sale_portal_templates.xml
  addons/web/static/src/legacy/scss/bootstrap_review.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.scss
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/tests/minimal.pdf
  odoo/addons/base/tests/test_misc.py
  odoo/addons/base/tests/test_pdf.py
  odoo/netsvc.py
  odoo/tools/pdf.py
Labels: tmp.15.0

#26841 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/l10n_latam_check/tests/test_third_party_checks.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/models/stock_quant.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/web/static/src/core/l10n/localization_service.js
  addons/web/static/tests/core/l10n/translation_tests.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.16.0

#26842 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/__manifest__.py
  addons/account/models/account_payment_term.py
  addons/account/static/src/scss/account_payment_term.scss
  addons/account/views/account_payment_term_views.xml
  addons/base_import_module/i18n/base_import_module.pot
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/__init__.py
  addons/base_import_module/tests/test_import_module.py
  addons/delivery/models/delivery_carrier.py
  addons/delivery/tests/test_delivery_cost.py
  addons/event/models/event_mail.py
  addons/event_sms/models/event_mail.py
  addons/hr_holidays/static/src/scss/time_off.scss
  addons/hr_holidays/views/hr_leave_accrual_views.xml
  addons/l10n_din5008_sale/i18n/de.po
  addons/l10n_ke/data/template/account.account-ke.csv
  addons/l10n_ke/data/template/account.tax.group-ke.csv
  addons/l10n_uk/data/template/account.account-uk.csv
  addons/mrp/report/mrp_report_bom_structure.py
  addons/mrp/static/src/components/bom_overview_table/mrp_bom_overview_table.xml
  addons/mrp_subcontracting/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_purchase/report/mrp_report_bom_structure.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/stock/models/stock_orderpoint.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/stock_account/wizard/stock_valuation_layer_revaluation.py
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_delivery_cost.py
  addons/test_event_full/tests/test_event_mail.py
  addons/web/static/src/views/form/button_box/button_box.js
  addons/web/static/src/views/form/button_box/button_box.xml
  addons/web/static/tests/mobile/views/form_view_tests.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/website_blog/views/website_blog_components.xml
  addons/website_event/static/src/snippets/options.js
Labels: tmp.17.0

#26843 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi_facturx/data/facturx_templates.xml
  addons/account_edi_ubl/data/ubl_templates.xml
  addons/account_edi_ubl/models/account_edi_format.py
  addons/account_edi_ubl_bis3/data/bis3_templates.xml
  addons/account_edi_ubl_bis3/models/account_edi_format.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/microsoft_account/controllers/main.py
  addons/note/__manifest__.py
  addons/website/models/assets.py
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/views/snippets/s_picture.xml
Labels: 15.0

#26844 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_payment_register.py
  addons/hr_expense/report/hr_expense_report.xml
  addons/mail_group/data/mail_template_data.xml
  addons/mail_group/i18n/mail_group.pot
  addons/mass_mailing/static/src/scss/themes/theme_basic.scss
  addons/microsoft_account/controllers/main.py
  addons/point_of_sale/views/res_config_settings_views.xml
  addons/purchase/report/purchase_order_templates.xml
  addons/sale/report/ir_actions_report_templates.xml
  addons/sale_management/models/sale_order_option.py
  addons/web/static/src/scss/bootstrap_review.scss
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop_widget.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/scss/website.scss
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_blog/views/website_blog_components.xml
  addons/website_mass_mailing/static/src/js/website_mass_mailing.editor.js
Labels: 16.0

#26847 Syncing from upstream odoo/odoo (saas-16.3)
  addons/account/i18n/account.pot
  addons/account/models/account_payment.py
  addons/account/wizard/account_payment_register.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/gamification/models/res_users.py
  addons/gamification/tests/test_karma_tracking.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_nl.py
  addons/l10n_in/models/res_partner.py
  addons/l10n_in/views/res_partner_views.xml
  addons/l10n_latam_check/tests/test_third_party_checks.py
  addons/l10n_pt/data/template/account.account-pt.csv
  addons/l10n_pt/models/template_pt.py
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/mail_group/data/mail_template_data.xml
  addons/mail_group/i18n/mail_group.pot
  addons/microsoft_account/controllers/main.py
  addons/point_of_sale/models/report_sale_details.py
  addons/stock_account/data/product_data.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/models/stock_quant.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/__manifest__.py
  addons/website/static/src/libs/bootstrap/bootstrap.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_slides/static/src/scss/website_slides.scss
Labels: saas-16.3

#26848 Syncing from upstream odoo/odoo (saas-16.4)
  addons/account/models/partner.py
  addons/account/wizard/account_payment_register.py
  addons/account_payment/models/payment_provider.py
  addons/gamification/models/res_users.py
  addons/gamification/tests/test_karma_tracking.py
  addons/l10n_in/models/res_partner.py
  addons/l10n_in/views/res_partner_views.xml
  addons/lunch/i18n/lunch.pot
  addons/lunch/models/lunch_supplier.py
  addons/mail_group/data/mail_template_data.xml
  addons/mail_group/i18n/mail_group.pot
  addons/microsoft_account/controllers/main.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/tests/common.py
  addons/point_of_sale/tests/test_report_session.py
  addons/point_of_sale/views/report_saledetails.xml
  addons/purchase/models/account_invoice.py
  addons/stock/models/stock_move.py
  addons/stock_account/data/product_data.xml
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/models/stock_move_line.py
  addons/stock_account/models/stock_quant.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/collab.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/content/inject_dom.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_popup/000.js
  addons/website_profile/static/src/scss/website_profile.scss
  addons/website_slides/static/src/scss/website_slides.scss
Labels: saas-16.4
