Repository brain-tec/odoo, pull requests merged in 2024-07, with the labels that each got.

#28121 Syncing from upstream odoo/odoo (15.0)
  addons/account_test/report/report_account_test.py
  odoo/addons/base/models/res_users.py
Labels: 15.0

#28122 Syncing from upstream odoo/odoo (16.0)
  addons/account_test/report/report_account_test.py
  odoo/addons/base/models/res_users.py
Labels: 16.0

#28124 Syncing from upstream odoo/odoo (master)
  addons/account_test/report/report_account_test.py
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_ir_sequence.py
Labels: master

#28126 Syncing from upstream odoo/odoo (tmp.master)
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/tests/test_ir_sequence.py
Labels: tmp.master

#28127 Syncing from upstream odoo/odoo (15.0)
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/payment_adyen/static/src/js/payment_form.js
  addons/web/static/src/core/l10n/utils.js
  addons/web/static/tests/l10n/utils_tests.js
Labels: 15.0

#28128 Syncing from upstream odoo/odoo (16.0)
  addons/hr_expense/models/hr_expense.py
  addons/point_of_sale/models/pos_payment.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: 16.0

#28136 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/web/static/src/legacy/scss/utils.scss
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/carousel_content_removal.js
  addons/website/tests/test_ui.py
  odoo/tools/translate.py
  setup/package.dfwine
Labels: 15.0

#28137 Syncing from upstream odoo/odoo (16.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/iap/tools/iap_tools.py
  addons/point_of_sale/static/tests/tours/helpers/PartnerListScreenTourMethods.js
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/website_event/controllers/main.py
  addons/website_event/tests/test_event_menus.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/tests/test_ir_sequence.py
  odoo/tools/translate.py
  setup/win32/setup.nsi
Labels: 16.0

#28138 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_tax.py
  addons/account/wizard/account_move_send.py
  addons/calendar/models/calendar_event.py
  addons/google_calendar/models/google_sync.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/iap/tools/iap_tools.py
  addons/im_livechat/static/src/embed/external/boot.js
  addons/im_livechat/tests/test_im_livechat_support_page.py
  addons/l10n_din5008_stock/i18n/l10n_din5008_stock.pot
  addons/l10n_din5008_stock/models/stock.py
  addons/l10n_es_pos/static/src/overrides/models/pos_store.js
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/tests/export_xmls/credit_note_negative_price.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_negative_price.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/template/account.tax-nl.csv
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/mail/static/tests/discuss/core/web/crosstab_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/payment/const.py
  addons/payment/utils.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_self_order/static/src/app/components/product_card/product_card.js
  addons/pos_self_order/static/src/app/pages/combo_page/combo_page.xml
  addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
  addons/pos_self_order/static/tests/helpers/product_page.js
  addons/pos_self_order/static/tests/tours/test_self_order_common.js
  addons/pos_self_order/tests/test_self_order_common.py
  addons/product/static/src/scss/report_label_sheet.scss
  addons/project/controllers/portal.py
  addons/project/i18n/project.pot
  addons/project/static/src/project_sharing/editor/odoo_editor.js
  addons/project/static/src/project_sharing/editor/wysiwyg.js
  addons/project/static/src/project_sharing/views/form/project_sharing_form_controller.js
  addons/project/static/tests/project_task_kanban_renderer_tests.js
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/scss/utils.scss
  addons/website/static/src/scss/primary_variables.scss
  addons/website/static/src/snippets/s_masonry_block/001.scss
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/views/res_currency_views.xml
  odoo/tools/mail.py
  setup/win32/setup.nsi
Labels: 17.0

#28142 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/web/static/src/legacy/scss/utils.scss
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/lib/odoo-editor/src/utils/utils.js
  addons/web_editor/static/lib/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/lib/odoo-editor/test/spec/utils.test.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/carousel_content_removal.js
  addons/website/tests/test_ui.py
  odoo/tools/translate.py
  setup/package.dfwine
Labels: tmp.15.0

#28143 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/iap/tools/iap_tools.py
  addons/point_of_sale/static/tests/tours/helpers/PartnerListScreenTourMethods.js
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale_purchase_stock/tests/test_sale_purchase_stock_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/website_event/controllers/main.py
  addons/website_event/tests/test_event_menus.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/tests/test_ir_sequence.py
  odoo/tools/translate.py
  setup/win32/setup.nsi
Labels: tmp.16.0

#28144 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_tax.py
  addons/account/wizard/account_move_send.py
  addons/calendar/models/calendar_event.py
  addons/google_calendar/models/google_sync.py
  addons/hr_expense/views/hr_expense_views.xml
  addons/iap/tools/iap_tools.py
  addons/im_livechat/static/src/embed/external/boot.js
  addons/im_livechat/tests/test_im_livechat_support_page.py
  addons/l10n_din5008_stock/i18n/l10n_din5008_stock.pot
  addons/l10n_din5008_stock/models/stock.py
  addons/l10n_es_pos/static/src/overrides/models/pos_store.js
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/tests/export_xmls/credit_note_negative_price.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_negative_price.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_nl/__manifest__.py
  addons/l10n_nl/data/account_tax_report_data.xml
  addons/l10n_nl/data/template/account.tax-nl.csv
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/mail/static/tests/discuss/core/web/crosstab_tests.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/payment/const.py
  addons/payment/utils.py
  addons/point_of_sale/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_self_order/static/src/app/components/product_card/product_card.js
  addons/pos_self_order/static/src/app/pages/combo_page/combo_page.xml
  addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
  addons/pos_self_order/static/tests/helpers/product_page.js
  addons/pos_self_order/static/tests/tours/test_self_order_common.js
  addons/pos_self_order/tests/test_self_order_common.py
  addons/product/static/src/scss/report_label_sheet.scss
  addons/project/controllers/portal.py
  addons/project/i18n/project.pot
  addons/project/static/src/project_sharing/editor/odoo_editor.js
  addons/project/static/src/project_sharing/editor/wysiwyg.js
  addons/project/static/src/project_sharing/views/form/project_sharing_form_controller.js
  addons/project/static/tests/project_task_kanban_renderer_tests.js
  addons/sale_timesheet/tests/test_sale_timesheet.py
  addons/sale_timesheet/wizard/sale_make_invoice_advance.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/static/src/scss/utils.scss
  addons/website/static/src/scss/primary_variables.scss
  addons/website/static/src/snippets/s_masonry_block/001.scss
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_mail.py
  odoo/addons/base/views/res_currency_views.xml
  odoo/tools/mail.py
  setup/win32/setup.nsi
Labels: tmp.17.0

#28145 Syncing from upstream odoo/odoo (15.0)
  addons/hw_drivers/server_logger.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/website_blog/data/blog_snippet_template_data.xml
  addons/website_sale/data/data.xml
Labels: 15.0

#28146 Syncing from upstream odoo/odoo (16.0)
  addons/account/security/ir.model.access.csv
  addons/payment_adyen/static/src/js/payment_form.js
  addons/web/static/src/core/l10n/utils.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/tests/l10n/utils_tests.js
  addons/web/static/tests/webclient/actions/misc_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  odoo/addons/base/views/ir_default_views.xml
  setup/package.dfwine
Labels: 16.0

#28151 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hw_drivers/server_logger.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/website_blog/data/blog_snippet_template_data.xml
  addons/website_sale/data/data.xml
Labels: tmp.15.0

#28152 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/security/ir.model.access.csv
  addons/payment_adyen/static/src/js/payment_form.js
  addons/web/static/src/core/l10n/utils.js
  addons/web/static/src/views/list/list_controller.js
  addons/web/static/src/views/list/list_renderer.scss
  addons/web/static/tests/l10n/utils_tests.js
  addons/web/static/tests/webclient/actions/misc_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  odoo/addons/base/views/ir_default_views.xml
  setup/package.dfwine
Labels: tmp.16.0

#28153 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/hr_holidays/report/hr_leave_report.py
  addons/l10n_it_edi_doi/models/sale_order.py
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/maintenance/models/maintenance.py
  addons/point_of_sale/static/src/app/navbar/navbar.js
  addons/product_expiry/tests/test_generate_serial_numbers.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/tests/test_timesheet_holidays.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_generate_serial_numbers.py
  addons/stock/tests/test_move.py
  addons/stock_landed_costs/models/account_move.py
  addons/stock_landed_costs/tests/test_stockvaluationlayer.py
  addons/test_website/__manifest__.py
  addons/test_website/controllers/main.py
  addons/test_website/models/model.py
  addons/test_website/security/ir.model.access.csv
  addons/test_website/security/test_website_security.xml
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/test_website/tests/__init__.py
  addons/test_website/tests/test_restricted_editor.py
  addons/test_website/tests/test_session.py
  addons/test_website/views/templates.xml
  addons/web/static/src/core/utils/timing.js
  addons/web/static/src/model/relational_model/dynamic_group_list.js
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/src/model/relational_model/dynamic_record_list.js
  addons/web/static/src/model/relational_model/group.js
  addons/web/static/tests/core/utils/timing_tests.js
  addons/web/static/tests/views/kanban/kanban_view_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/website/controllers/main.py
  addons/website/models/ir_qweb.py
  addons/website/models/website.py
  addons/website/static/src/systray_items/translate_website.js
  addons/website/static/src/systray_items/translate_website.xml
  addons/website_event/controllers/main.py
  addons/website_event/tests/test_event_menus.py
  doc/cla/corporate/VillaGroup.md
  odoo/addons/base/views/ir_default_views.xml
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/models.py
  odoo/tools/misc.py
  odoo/tools/translate.py
  setup/package.dfwine
Labels: tmp.17.0

#28154 [t150044] [ODOO-2257] display full Access Error msg when debug mode is off
  odoo/addons/base/models/ir_rule.py
Labels: 15.0.project_sv_559

#28155 Syncing from upstream odoo/odoo (15.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/web/static/src/legacy/js/widgets/colorpicker.js
  addons/web/tests/__init__.py
  addons/web/tests/test_reports.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/models/ir_actions_report.py
Labels: 15.0

#28156 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_report.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/payment_stripe/const.py
  addons/point_of_sale/models/pos_session.py
  addons/spreadsheet/static/src/pivot/plugins/pivot_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/stock_account/models/product.py
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/tests/__init__.py
  addons/web/tests/test_reports.py
  addons/website_blog/data/blog_snippet_template_data.xml
  addons/website_event/data/website_snippet_data.xml
  addons/website_sale/data/data.xml
  odoo/addons/base/models/ir_actions_report.py
  setup/package.dfwine
Labels: 16.0

#28161 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/web/static/src/legacy/js/widgets/colorpicker.js
  addons/web/tests/__init__.py
  addons/web/tests/test_reports.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.15.0

#28162 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_report.py
  addons/hr/models/hr_employee.py
  addons/hr/tests/test_hr_employee.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/payment_stripe/const.py
  addons/point_of_sale/models/pos_session.py
  addons/spreadsheet/static/src/pivot/plugins/pivot_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/stock_account/models/product.py
  addons/web/static/src/legacy/scss/utils.scss
  addons/web/tests/__init__.py
  addons/web/tests/test_reports.py
  addons/website_blog/data/blog_snippet_template_data.xml
  addons/website_event/data/website_snippet_data.xml
  addons/website_sale/data/data.xml
  odoo/addons/base/models/ir_actions_report.py
  setup/package.dfwine
Labels: tmp.16.0

#28163 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_report.py
  addons/account/security/ir.model.access.csv
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/hr/static/src/components/employee_chat/employee_chat.xml
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/static/src/dashboard/time_off_dashboard.js
  addons/hr_holidays/static/src/dashboard/time_off_dashboard.xml
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hw_drivers/websocket_client.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/mail/static/src/core/common/message_service.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/web/chatter.js
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/binary.py
  addons/point_of_sale/tests/test_frontend.py
  addons/purchase_requisition/report/report_purchaserequisition.xml
  addons/repair/models/repair.py
  addons/repair/tests/test_repair.py
  addons/sale/i18n/sale.pot
  addons/sale/report/sale_report_views.xml
  addons/sale_loyalty/views/sale_order_views.xml
  addons/spreadsheet/static/src/pivot/plugins/pivot_ui_plugin.js
  addons/spreadsheet/static/tests/global_filters/global_filters_model_test.js
  addons/spreadsheet/views/public_readonly_spreadsheet_templates.xml
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/web/static/src/core/l10n/utils.js
  addons/web/static/src/legacy/js/libs/jquery.js
  addons/web/static/src/scss/utils.scss
  addons/web/static/src/webclient/settings_form_view/widgets/res_config_invite_users.js
  addons/web/static/tests/l10n/utils_tests.js
  addons/web/tests/__init__.py
  addons/web/tests/test_reports.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_blog/data/blog_snippet_template_data.xml
  addons/website_event/data/website_snippet_data.xml
  addons/website_sale/data/data.xml
  addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
  addons/website_slides/static/src/js/slides_course_quiz.js
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.17.0

#28164 Syncing from upstream odoo/odoo (15.0)
  addons/partner_autocomplete/models/res_partner.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/views/website_forum.xml
  odoo/tools/_monkeypatches.py
Labels: 15.0

#28165 Syncing from upstream odoo/odoo (16.0)
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hw_drivers/server_logger.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mrp/models/stock_orderpoint.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_orderpoint.py
  addons/website_payment/models/payment_provider.py
Labels: 16.0

#28170 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/partner_autocomplete/models/res_partner.py
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/views/website_forum.xml
  odoo/tools/_monkeypatches.py
Labels: tmp.15.0

#28171 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hw_drivers/server_logger.py
  addons/l10n_sa_edi/models/account_move.py
  addons/mrp/models/stock_orderpoint.py
  addons/point_of_sale/static/src/js/models.js
  addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_orderpoint.py
  addons/website_payment/models/payment_provider.py
Labels: tmp.16.0

#28173 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move_line.py
  addons/account/wizard/account_move_send.py
  addons/account_audit_trail/__init__.py
  addons/account_audit_trail/__manifest__.py
  addons/account_audit_trail/i18n/account_audit_trail.pot
  addons/account_audit_trail/models/__init__.py
  addons/account_audit_trail/models/account_bank_statement_line.py
  addons/account_audit_trail/models/account_move.py
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/models/mail_tracking_value.py
  addons/account_audit_trail/report/audit_trail_report_views.xml
  addons/account_audit_trail/tests/__init__.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_lock/__init__.py
  addons/account_lock/__manifest__.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_de.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/__init__.py
  addons/l10n_de/models/account_account.py
  addons/l10n_de/models/datev.py
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_de/models/res_company.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/tests/core/autocomplete_tests.js
Labels: 17.0

#28176 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move_line.py
  addons/account/wizard/account_move_send.py
  addons/account_audit_trail/__init__.py
  addons/account_audit_trail/__manifest__.py
  addons/account_audit_trail/i18n/account_audit_trail.pot
  addons/account_audit_trail/models/__init__.py
  addons/account_audit_trail/models/account_bank_statement_line.py
  addons/account_audit_trail/models/account_move.py
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/models/mail_tracking_value.py
  addons/account_audit_trail/report/audit_trail_report_views.xml
  addons/account_audit_trail/tests/__init__.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/account_lock/__init__.py
  addons/account_lock/__manifest__.py
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_ubl_de.py
  addons/l10n_de/__manifest__.py
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/__init__.py
  addons/l10n_de/models/account_account.py
  addons/l10n_de/models/datev.py
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_de/models/res_company.py
  addons/mail/models/mail_thread.py
  addons/mail/models/res_partner.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/web/static/src/core/autocomplete/autocomplete.js
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/tests/core/autocomplete_tests.js
Labels: tmp.17.0

#28177 Syncing from upstream odoo/odoo (15.0)
  odoo/http.py
  odoo/tools/profiler.py
Labels: 15.0

#28178 Syncing from upstream odoo/odoo (16.0)
  odoo/http.py
  odoo/tools/profiler.py
Labels: 16.0

#28180 Syncing from upstream odoo/odoo (master)
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_ac_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_in_invoice_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_invoice_payment_means.xml
  addons/l10n_es_edi_facturae/tests/data/expected_invoice_period_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_signed_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
  odoo/http.py
  odoo/tools/profiler.py
Labels: master

#28181 Syncing from upstream odoo/odoo (tmp.master)
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_ac_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_in_invoice_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_invoice_payment_means.xml
  addons/l10n_es_edi_facturae/tests/data/expected_invoice_period_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_signed_document.xml
  addons/l10n_es_edi_facturae/tests/data/expected_tax_withholding.xml
  addons/l10n_es_edi_facturae/tests/test_edi_xml.py
Labels: tmp.master

#28183 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account_check_printing/i18n/id.po
  addons/account_edi_proxy_client/i18n/et.po
  addons/event_booth_sale/i18n/hr.po
  addons/fleet/i18n/ro.po
  addons/hr/i18n/hr.po
  addons/hr_contract/i18n/hr.po
  addons/hr_contract/i18n/zh_CN.po
  addons/hr_contract/models/__init__.py
  addons/hr_contract/models/resource_calendar_leaves.py
  addons/hr_contract/tests/test_contract.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/tests/test_expenses.py
  addons/hr_holidays/i18n/hr.po
  addons/hr_recruitment/i18n/ro.po
  addons/hr_recruitment_skills/i18n/ro.po
  addons/hr_recruitment_survey/i18n/ro.po
  addons/hr_skills/i18n/ro.po
  addons/mail/i18n/cs.po
  addons/maintenance/i18n/de.po
  addons/mrp/i18n/zh_TW.po
  addons/mrp_subcontracting/i18n/et.po
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/payment_stripe/i18n/et.po
  addons/pos_restaurant/i18n/mn.po
  addons/pos_sale/i18n/vi.po
  addons/resource/models/resource.py
  addons/sale/i18n/tr.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/i18n/et.po
  addons/stock_account/i18n/vi.po
  addons/survey/i18n/et.po
  addons/test_resource/tests/test_resource.py
  addons/transifex/i18n/et.po
  addons/uom/i18n/et.po
  addons/utm/i18n/et.po
  addons/web/i18n/et.po
  addons/web/i18n/uk.po
  addons/web/static/src/views/basic_relational_model.js
  addons/web/static/src/views/fields/relational_utils.js
  addons/web/static/tests/views/fields/one2many_field_tests.js
  addons/web_editor/i18n/et.po
  addons/website/i18n/zh_TW.po
  addons/website_blog/i18n/es_MX.po
  addons/website_event_track/i18n/es_MX.po
  addons/website_event_track/i18n/hr.po
  addons/website_forum/static/src/js/website_forum.js
  addons/website_forum/views/website_forum.xml
  addons/website_hr_recruitment/i18n/ro.po
  addons/website_mass_mailing/i18n/es_MX.po
  addons/website_sale/i18n/et.po
  addons/website_sale_slides/i18n/lt.po
  doc/cla/corporate/smart-obc.md
  odoo/addons/base/i18n/cs.po
  odoo/addons/base/i18n/es_MX.po
  odoo/addons/base/i18n/et.po
  odoo/addons/base/i18n/hr.po
  odoo/addons/base/i18n/zh_TW.po
Labels: 16.0

#28188 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_contract/models/__init__.py
  addons/hr_contract/models/resource_calendar_leaves.py
  addons/hr_contract/tests/test_contract.py
  addons/im_livechat/data/mail_data.xml
  addons/im_livechat/i18n/im_livechat.pot
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/resource/models/resource.py
  addons/resource/tests/test_resource.py
  addons/web/static/src/core/errors/error_utils.js
  addons/web/static/tests/core/errors/error_service_tests.js
  odoo/http.py
  odoo/tools/profiler.py
Labels: tmp.15.0

#28191 Syncing from upstream odoo/odoo (15.0)
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/report/holidays_summary_report.py
Labels: 15.0

#28192 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_reconcile_model.py
  addons/hr_expense/static/src/mixins/document_upload.js
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/src/views/kanban.xml
  addons/hr_expense/static/src/views/list.js
  addons/hr_expense/static/src/views/list.xml
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hr_expense/tests/__init__.py
  addons/hr_expense/tests/test_expenses_tour.py
  addons/im_livechat/data/mail_templates.xml
  addons/im_livechat/i18n/im_livechat.pot
  addons/l10n_nl/migrations/3.2/post-migrate_update_taxes.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/partner_autocomplete/models/res_partner.py
  addons/pos_loyalty/models/loyalty_program.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/core/errors/error_utils.js
  addons/web/static/tests/core/errors/error_service_tests.js
  doc/cla/corporate/grap.md
  odoo/tools/_monkeypatches.py
Labels: 16.0

#28197 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_reconcile_model.py
  addons/hr_expense/static/src/mixins/document_upload.js
  addons/hr_expense/static/src/scss/hr_expense.scss
  addons/hr_expense/static/src/views/kanban.xml
  addons/hr_expense/static/src/views/list.js
  addons/hr_expense/static/src/views/list.xml
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hr_expense/tests/__init__.py
  addons/hr_expense/tests/test_expenses_tour.py
  addons/im_livechat/data/mail_templates.xml
  addons/im_livechat/i18n/im_livechat.pot
  addons/l10n_nl/migrations/3.2/post-migrate_update_taxes.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/partner_autocomplete/models/res_partner.py
  addons/pos_loyalty/models/loyalty_program.py
  addons/purchase/models/purchase.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/report/report_stock_quantity.py
  addons/web/static/src/core/errors/error_utils.js
  addons/web/static/tests/core/errors/error_service_tests.js
  doc/cla/corporate/grap.md
  odoo/tools/_monkeypatches.py
Labels: tmp.16.0

#28198 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/tests/test_expenses.py
  addons/im_livechat/data/mail_templates.xml
  addons/im_livechat/i18n/im_livechat.pot
  addons/l10n_ar_withholding/__init__.py
  addons/l10n_cl/data/template/account.account-cl.csv
  addons/l10n_cl/data/template/account.fiscal.position-cl.csv
  addons/l10n_cl/models/template_cl.py
  addons/l10n_cz/__manifest__.py
  addons/l10n_cz/data/tax_report.xml
  addons/l10n_cz/data/template/account.account-cz.csv
  addons/l10n_cz/data/template/account.fiscal.position-cz.csv
  addons/l10n_cz/data/template/account.tax-cz.csv
  addons/l10n_cz/data/template/account.tax.group-cz.csv
  addons/l10n_cz/i18n/cs.po
  addons/l10n_cz/i18n/l10n_cz.pot
  addons/l10n_cz/models/template_cz.py
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_tr/migrations/1.2/end-migrate_update_package.py
  addons/mail/static/src/discuss/core/web/channel_selector.js
  addons/mail/static/tests/discuss/core/web/discuss_tests.js
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/TicketScreen.tour.js
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_loyalty/models/loyalty_program.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/pos_viva_wallet/models/pos_payment_method.py
  addons/purchase/models/purchase_order.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_requisition/models/purchase_requisition.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock/views/stock_move_views.xml
  addons/stock/wizard/stock_package_destination.py
  addons/stock_account/models/product.py
  addons/web/static/src/core/errors/error_utils.js
  addons/web/static/tests/core/errors/error_service_tests.js
  addons/website_event/views/event_templates_page_registration.xml
  addons/website_sale/i18n/website_sale.pot
  addons/website_sale/models/product_ribbon.py
  addons/website_sale/models/website.py
  addons/website_sale/static/src/js/website_sale.editor.js
  odoo/addons/test_read_group/tests/__init__.py
  odoo/addons/test_read_group/tests/test_exceptions.py
  odoo/models.py
Labels: tmp.17.0

#28200 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement_line.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/report/holidays_summary_report.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/pos_loyalty/models/loyalty_program.py
  addons/web/__manifest__.py
  addons/web/static/src/core/l10n/utils.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/wysiwyg.js
Labels: 16.0

#28206 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_bank_statement_line.py
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/report/holidays_summary_report.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/pos_loyalty/models/loyalty_program.py
  addons/web/__manifest__.py
  addons/web/static/src/core/l10n/utils.js
  addons/website/static/src/js/content/menu.js
  addons/website/static/src/js/editor/wysiwyg.js
Labels: tmp.16.0

#28207 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/hr_expense/tests/test_expenses_standard_price_update_warning.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/report/holidays_summary_report.py
  addons/l10n_cz/data/tax_report.xml
  addons/l10n_cz/i18n/cs.po
  addons/l10n_cz/i18n/l10n_cz.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_ke/data/template/account.tax-ke.csv
  addons/l10n_ke/models/__init__.py
  addons/l10n_ke/models/res_company.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/l10n_ke_edi_tremol/views/report_invoice.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_workorder.py
  addons/partner_autocomplete/models/res_partner.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/purchase/models/account_invoice.py
  addons/purchase/views/account_move_views.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_performance.py
  addons/website_sale/static/src/scss/website_sale.scss
  odoo/tools/_monkeypatches.py
Labels: tmp.17.0

#28208 Revert "[FIX] account: backport of computation of tax tag invert fix"
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_entry.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/tests/test_account_move_out_invoice.py
Labels: 15.0.project_gd_615

#28209 [FIX] website_sale_slides: avoid access error in portal slides
  addons/website_sale_slides/controllers/slides.py
Labels: 15.0.project_gd_615

#28210 Syncing from upstream odoo/odoo (15.0)
  addons/account_edi/models/account_move.py
  addons/l10n_sg/models/__init__.py
  addons/l10n_sg/models/chart_template.py
  addons/mail/models/res_users.py
  addons/test_mail/tests/test_mail_multicompany.py
Labels: 15.0

#28211 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/models/payment_provider.py
  addons/account_payment/tests/test_account_payment.py
  addons/delivery/views/report_deliveryslip.xml
  addons/sale_stock/report/stock_report_deliveryslip.xml
  addons/stock/report/report_deliveryslip.xml
Labels: 16.0

#28216 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_edi/models/account_move.py
  addons/l10n_sg/models/__init__.py
  addons/l10n_sg/models/chart_template.py
  addons/mail/models/res_users.py
  addons/test_mail/tests/test_mail_multicompany.py
Labels: tmp.15.0

#28217 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_payment/models/payment_provider.py
  addons/account_payment/tests/test_account_payment.py
  addons/delivery/views/report_deliveryslip.xml
  addons/sale_stock/report/stock_report_deliveryslip.xml
  addons/stock/report/report_deliveryslip.xml
Labels: tmp.16.0

#28218 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/hw_drivers/websocket_client.py
  addons/l10n_gcc_invoice/models/product.py
  addons/l10n_nl/migrations/3.1/end-migrate_update_taxes.py
  addons/l10n_nl/migrations/3.2/post-migrate_update_taxes.py
  addons/l10n_nl/migrations/3.3/post-migrate_update_taxes.py
  addons/l10n_tr/i18n/l10n_tr.pot
  addons/l10n_tr/i18n/tr.po
  addons/point_of_sale/static/tests/tours/helpers/PartnerListScreenTourMethods.js
  addons/pos_loyalty/models/loyalty_program.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/report_stock_quantity.py
  addons/stock_account/models/analytic_account.py
  addons/web/__manifest__.py
  addons/web/static/src/core/l10n/utils.js
  addons/website/controllers/main.py
  addons/website/models/ir_qweb.py
  addons/website_event/controllers/main.py
  addons/website_event/i18n/website_event.pot
  addons/website_event/views/event_templates_page_registration.xml
  doc/cla/corporate/grap.md
Labels: tmp.17.0

#28225 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_leave_accrual_plan.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  odoo/tools/_monkeypatches.py
Labels: tmp.15.0

#28226 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move_line.py
  addons/base_import_module/models/ir_module.py
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/website/data/website_data.xml
  addons/website/views/website_templates.xml
  odoo/addons/base/data/res_users_demo.xml
  odoo/tools/_monkeypatches.py
  odoo/tools/translate.py
Labels: tmp.16.0

#28227 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/base_automation/models/base_automation.py
  addons/crm/models/crm_lead.py
  addons/hr_expense/models/hr_expense_sheet.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_timesheet/report/report_timesheet_templates.xml
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_de/models/account_account.py
  addons/l10n_in_pos/models/__init__.py
  addons/l10n_in_pos/models/account_move.py
  addons/link_tracker/models/link_tracker.py
  addons/mrp_subcontracting/i18n/mrp_subcontracting.pot
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting/wizard/product_replenish.py
  addons/phone_validation/models/mail_thread_phone.py
  addons/product_expiry/report/report_lot_barcode.xml
  addons/project/models/project_project.py
  addons/project/models/res_config_settings.py
  addons/project/static/src/components/subtask_one2many_field/subtask_one2many_field.js
  addons/stock/models/stock_move.py
  addons/stock/report/report_lot_barcode.xml
  addons/stock/static/tests/tours/stock_picking_tour.js
  addons/stock/tests/test_picking_tours.py
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/stock_delivery/wizard/choose_delivery_package.py
  addons/utm/models/utm_mixin.py
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/form/form_controller.scss
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_hierarchy/static/src/hierarchy_model.js
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/content/menu.js
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
  odoo/tests/form.py
Labels: tmp.17.0

#28228 Syncing from upstream odoo/odoo (master)
  addons/html_editor/static/src/core/split_plugin.js
  addons/html_editor/static/tests/collaboration.test.js
  addons/link_tracker/models/link_tracker.py
  addons/utm/models/utm_mixin.py
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph/graph_view.test.js
Labels: master

#28230 Syncing from upstream odoo/odoo (tmp.master)
  addons/html_editor/static/src/core/split_plugin.js
  addons/html_editor/static/tests/collaboration.test.js
  addons/link_tracker/models/link_tracker.py
  addons/utm/models/utm_mixin.py
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph/graph_view.test.js
Labels: tmp.master

#28233 Syncing from upstream odoo/odoo (master)
  addons/base_automation/models/base_automation.py
  addons/stock/static/tests/tours/stock_picking_tour.js
  addons/stock/tests/test_picking_tours.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
  odoo/tests/form.py
Labels: master

#28235 Syncing from upstream odoo/odoo (tmp.master)
  addons/base_automation/models/base_automation.py
  addons/stock/static/tests/tours/stock_picking_tour.js
  addons/stock/tests/test_picking_tours.py
  odoo/addons/test_new_api/tests/test_onchange.py
  odoo/fields.py
  odoo/tests/form.py
Labels: tmp.master

#28236 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_pe/data/res_country_data.xml
  addons/l10n_pe/models/res_partner.py
  addons/partner_autocomplete/models/res_partner.py
  addons/web/models/models.py
  addons/website/static/src/js/editor/wysiwyg.js
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
  odoo/tools/_monkeypatches.py
Labels: 15.0

#28237 Syncing from upstream odoo/odoo (16.0)
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/mail/i18n/mail.pot
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/views/mrp_bom_views.xml
  addons/partner_autocomplete/models/res_partner.py
  addons/web/models/models.py
  addons/web/static/src/core/dialog/dialog.scss
  addons/web/static/src/core/dialog/dialog.xml
  addons/web/static/src/core/popover/popover.js
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/src/legacy/xml/dialog.xml
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/calendar/filter_panel/calendar_filter_panel.js
  addons/web/static/src/views/calendar/filter_panel/calendar_filter_panel.xml
  addons/web/static/tests/core/popover/popover_tests.js
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
  odoo/models.py
  odoo/tools/_monkeypatches.py
Labels: 16.0

#28243 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/mail/i18n/mail.pot
  addons/mail/wizard/mail_compose_message.py
  addons/mrp/views/mrp_bom_views.xml
  addons/partner_autocomplete/models/res_partner.py
  addons/web/models/models.py
  addons/web/static/src/core/dialog/dialog.scss
  addons/web/static/src/core/dialog/dialog.xml
  addons/web/static/src/core/popover/popover.js
  addons/web/static/src/legacy/xml/base.xml
  addons/web/static/src/legacy/xml/dialog.xml
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web/static/src/views/calendar/filter_panel/calendar_filter_panel.js
  addons/web/static/src/views/calendar/filter_panel/calendar_filter_panel.xml
  addons/web/static/tests/core/popover/popover_tests.js
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
  odoo/models.py
  odoo/tools/_monkeypatches.py
Labels: tmp.16.0

#28244 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move_line.py
  addons/account_payment_term/models/account_payment_term.py
  addons/account_payment_term/tests/test_payment_term.py
  addons/base_import_module/models/ir_module.py
  addons/calendar/views/calendar_views.xml
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/delivery_carrier.py
  addons/event/static/src/client_action/event_barcode.js
  addons/google_calendar/models/google_sync.py
  addons/google_calendar/tests/test_sync_google2odoo.py
  addons/hr_skills/views/hr_employee_cv_templates.xml
  addons/l10n_sg/models/template_sg.py
  addons/partner_autocomplete/models/res_partner.py
  addons/phone_validation/models/mail_thread_phone.py
  addons/pos_self_order/models/pos_config.py
  addons/pos_self_order/tests/self_order_common_test.py
  addons/product/views/product_views.xml
  addons/sale/report/ir_actions_report_templates.xml
  addons/spreadsheet/static/src/list/list_data_source.js
  addons/spreadsheet/static/tests/lists/list_plugin_test.js
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/web/models/models.py
  addons/web_editor/controllers/main.py
  addons/website/data/website_data.xml
  addons/website/views/website_templates.xml
  addons/website_sale/static/src/scss/website_sale.scss
  doc/cla/individual/mjrk.md
  odoo/addons/base/data/res_users_demo.xml
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
  odoo/tools/_monkeypatches.py
Labels: tmp.17.0

#28245 Syncing from upstream odoo/odoo (15.0)
  addons/hr_contract/models/hr_contract.py
  addons/hr_contract/tests/test_contract.py
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/mrp_repair/tests/test_tracability.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/repair/models/product.py
Labels: 15.0

#28246 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi/models/account_move.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_sg/models/__init__.py
  addons/l10n_sg/models/chart_template.py
  addons/link_tracker/models/link_tracker.py
  addons/mass_mailing_sms/__manifest__.py
  addons/mass_mailing_sms/i18n/mass_mailing_sms.pot
  addons/mass_mailing_sms/models/mailing_mailing.py
  addons/mass_mailing_sms/static/src/components/sms_widget/fields_sms_widget.js
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/mass_mailing_sms/wizard/sms_composer.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sms/__init__.py
  addons/sms/models/mail_thread.py
  addons/sms/static/src/components/sms_widget/fields_sms_widget.js
  addons/sms/static/src/components/sms_widget/fields_sms_widget.xml
  addons/sms/tests/__init__.py
  addons/sms/tests/common.py
  addons/sms/tests/test_sms_composer.py
  addons/sms/tools/__init__.py
  addons/sms/tools/sms_tools.py
  addons/sms/wizard/sms_composer.py
  addons/test_mail_sms/tests/test_sms_post.py
  addons/website/static/src/js/editor/wysiwyg.js
Labels: 16.0

#28251 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_contract/models/hr_contract.py
  addons/hr_contract/tests/test_contract.py
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/mrp_repair/tests/test_tracability.py
  addons/partner_autocomplete/models/res_partner.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/repair/models/product.py
  odoo/tools/_monkeypatches.py
Labels: tmp.15.0

#28252 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi/models/account_move.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_sg/models/__init__.py
  addons/l10n_sg/models/chart_template.py
  addons/link_tracker/models/link_tracker.py
  addons/mass_mailing_sms/__manifest__.py
  addons/mass_mailing_sms/i18n/mass_mailing_sms.pot
  addons/mass_mailing_sms/models/mailing_mailing.py
  addons/mass_mailing_sms/static/src/components/sms_widget/fields_sms_widget.js
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/mass_mailing_sms/wizard/sms_composer.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sms/__init__.py
  addons/sms/models/mail_thread.py
  addons/sms/static/src/components/sms_widget/fields_sms_widget.js
  addons/sms/static/src/components/sms_widget/fields_sms_widget.xml
  addons/sms/tests/__init__.py
  addons/sms/tests/common.py
  addons/sms/tests/test_sms_composer.py
  addons/sms/tools/__init__.py
  addons/sms/tools/sms_tools.py
  addons/sms/wizard/sms_composer.py
  addons/test_mail_sms/tests/test_sms_post.py
  addons/website/static/src/js/editor/wysiwyg.js
Labels: tmp.16.0

#28253 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/wizard/account_move_send.py
  addons/account_edi/models/account_move.py
  addons/base_automation/static/src/base_automation_error_dialog.xml
  addons/base_automation/static/tests/base_automation_error_dialog.js
  addons/calendar/models/calendar_event.py
  addons/event/models/event_registration.py
  addons/event/tests/test_event_internals.py
  addons/l10n_fr/models/template_fr.py
  addons/l10n_in_pos/models/account_move.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/views/mrp_bom_views.xml
  addons/payment_demo/static/src/js/express_checkout_form.js
  addons/pos_self_order/controllers/orders.py
  addons/pos_self_order/controllers/self_entry.py
  addons/product/populate/product.py
  addons/purchase/models/purchase_order.py
  addons/purchase/tests/test_purchase.py
  addons/web/static/src/core/dialog/dialog.scss
  addons/web/static/src/core/dialog/dialog.xml
  addons/web/static/src/legacy/xml/dialog.xml
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web/static/tests/webclient/clickbot_tests.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/views/templates.xml
Labels: tmp.17.0

#28254 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_es_edi_sii/models/account_edi_format.py
Labels: 15.0

#28255 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/mass_mailing/views/mailing_list_views.xml
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/mrp_repair/tests/test_tracability.py
  addons/repair/models/product.py
Labels: 16.0

#28258 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_es_edi_sii/models/account_edi_format.py
Labels: tmp.15.0

#28259 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/mass_mailing/views/mailing_list_views.xml
  addons/microsoft_outlook/models/ir_mail_server.py
  addons/mrp_repair/tests/test_tracability.py
  addons/repair/models/product.py
Labels: tmp.16.0

#28260 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/analytic/models/analytic_account.py
  addons/analytic/views/analytic_line_views.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_import_module.py
  addons/hr_attendance/views/hr_attendance_view.xml
  addons/hr_expense/models/hr_expense.py
  addons/hr_expense/static/src/mixins/document_upload.js
  addons/hr_expense/static/src/views/kanban.xml
  addons/hr_expense/static/src/views/list.js
  addons/hr_expense/static/src/views/list.xml
  addons/hr_expense/static/tests/tours/expense_upload_tours.js
  addons/hr_expense/tests/__init__.py
  addons/hr_expense/tests/test_expenses_tour.py
  addons/hr_holidays/views/hr_leave_views.xml
  addons/hr_timesheet/report/project_report_view.xml
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_fr_invoice_addr/i18n/fr.po
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/report/project_report_views.xml
  addons/project/static/src/project_sharing/views/form/project_sharing_form_controller.js
  addons/project/views/project_task_views.xml
  addons/web/static/src/views/graph/graph_arch_parser.js
  addons/web/static/src/views/graph/graph_renderer.js
  addons/web/static/tests/views/graph_view_tests.js
  odoo/addons/base/models/ir_module.py
  odoo/tools/translate.py
Labels: tmp.17.0

#28261 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_report.py
  addons/account/views/account_account_views.xml
  addons/account/views/account_move_views.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_contract/tests/test_contract.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/pos_loyalty/static/src/tours/PosLoyaltyTourMethods.js
  addons/web/controllers/binary.py
  addons/web/static/src/views/form/form_renderer.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/carousel_content_removal.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/samadeva.md
  odoo/addons/test_http/tests/test_static.py
Labels: 16.0

#28262 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/account/views/account_account_views.xml
  addons/account/views/account_move_views.xml
  addons/account_edi/views/account_journal_views.xml
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_performance.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/res_partner.py
  addons/l10n_be_pos_sale/models/pos_session.py
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/mail/models/mail_activity_mixin.py
  addons/mass_mailing/views/mailing_list_views.xml
  addons/payment_custom/const.py
  addons/payment_custom/models/payment_provider.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/pos_self_order/tests/test_self_order_common.py
  addons/repair/models/repair.py
  addons/repair/models/stock_picking.py
  addons/repair/tests/test_repair.py
  addons/repair/views/repair_views.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/test_mail/tests/test_mail_activity.py
  addons/web/controllers/binary.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/banner_tests.js
  odoo/addons/test_http/tests/test_static.py
  odoo/tools/config.py
Labels: 17.0

#28263 Syncing from upstream odoo/odoo (master)
  addons/base_automation/static/src/base_automation_error_dialog.xml
  addons/base_automation/static/tests/base_automation_error_dialog.test.js
  addons/bus/models/ir_websocket.py
  addons/mail/models/mail_mail.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/web_portal/message_patch.js
  addons/onboarding/static/tests/onboarding_banner_tests.js
  addons/project/models/project_project.py
  addons/project/tests/test_project_base.py
  addons/stock_account/models/analytic_account.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web/controllers/home.py
  addons/web/static/src/views/view.js
  addons/web/static/tests/_framework/view_test_helpers.js
  addons/web_tour/static/src/tour_pointer/tour_pointer.js
  addons/web_tour/static/src/tour_service/tour_compilers.js
  addons/web_tour/static/src/tour_service/tour_interactive.js
  addons/web_tour/static/src/tour_service/tour_service.js
  addons/web_tour/static/src/tour_service/tour_utils.js
  addons/web_tour/static/tests/tour_service.test.js
  addons/web_tour_recorder/static/tests/tour_recorder.test.js
  addons/website/data/website_data.xml
  addons/website/views/website_templates.xml
  addons/website_forum/controllers/website_forum.py
  addons/website_forum/static/src/js/website_forum.js
  odoo/addons/base/__manifest__.py
  odoo/addons/base/data/res_users_demo.xml
  odoo/addons/base/models/__init__.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/res_device.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/security/base_security.xml
  odoo/addons/base/security/ir.model.access.csv
  odoo/addons/base/tests/common.py
  odoo/addons/base/tests/test_ir_mail_server_smtpd.py
  odoo/addons/base/views/res_device_views.xml
  odoo/addons/base/views/res_users_views.xml
  odoo/addons/test_http/controllers.py
  odoo/addons/test_http/tests/__init__.py
  odoo/addons/test_http/tests/test_device.py
  odoo/addons/test_http/utils.py
  odoo/http.py
  odoo/service/security.py
Labels: master

#28265 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_report.py
  addons/account/views/account_account_views.xml
  addons/account/views/account_move_views.xml
  addons/hr_contract/models/hr_contract.py
  addons/hr_contract/tests/test_contract.py
  addons/hr_work_entry_holidays/models/hr_leave.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/wysiwyg.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/pos_loyalty/static/src/tours/PosLoyaltyTourMethods.js
  addons/web/controllers/binary.py
  addons/web/static/src/views/form/form_renderer.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/wysiwyg.js
  addons/website/static/tests/tours/carousel_content_removal.js
  addons/website/tests/test_ui.py
  doc/cla/corporate/samadeva.md
  odoo/addons/test_http/tests/test_static.py
Labels: tmp.16.0

#28266 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_account_tag.py
  addons/account/models/account_report.py
  addons/account/models/chart_template.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/account/views/account_account_views.xml
  addons/account/views/account_move_views.xml
  addons/account_edi/views/account_journal_views.xml
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_performance.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_ar/models/res_partner.py
  addons/l10n_be_pos_sale/models/pos_session.py
  addons/l10n_ca/data/tax_report.xml
  addons/l10n_ca/data/template/account.tax-ca_2023.csv
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/l10n_es_edi_tbai/tests/test_edi_xml.py
  addons/l10n_fr_pos_cert/static/src/js/pos.js
  addons/mail/models/mail_activity_mixin.py
  addons/mass_mailing/views/mailing_list_views.xml
  addons/payment_custom/const.py
  addons/payment_custom/models/payment_provider.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/pos_self_order/tests/test_self_order_common.py
  addons/repair/models/repair.py
  addons/repair/models/stock_picking.py
  addons/repair/tests/test_repair.py
  addons/repair/views/repair_views.xml
  addons/sale_project/models/project.py
  addons/sale_project/models/sale_order_line.py
  addons/test_mail/tests/test_mail_activity.py
  addons/web/controllers/binary.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/fields/properties/properties_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  addons/web/static/tests/views/fields/properties_field_tests.js
  addons/web/static/tests/views/list_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/tests/banner_tests.js
  odoo/addons/test_http/tests/test_static.py
  odoo/tools/config.py
Labels: tmp.17.0

#28271 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/tests/common.py
  addons/account/views/account_account_views.xml
  addons/account/views/partner_view.xml
  addons/account_update_tax_tags/__init__.py
  addons/account_update_tax_tags/__manifest__.py
  addons/account_update_tax_tags/i18n/account_update_tax_tags.pot
  addons/account_update_tax_tags/security/ir.model.access.csv
  addons/account_update_tax_tags/tests/__init__.py
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
  addons/account_update_tax_tags/views/res_config_settings_views.xml
  addons/account_update_tax_tags/wizard/__init__.py
  addons/account_update_tax_tags/wizard/account_update_tax_tags_wizard.py
  addons/account_update_tax_tags/wizard/account_update_tax_tags_wizard.xml
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/account_fiscal_position.py
  addons/mail/models/mail_activity_mixin.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/common.py
  addons/payment/tests/test_transactions.py
  addons/payment_mollie/models/payment_transaction.py
  addons/project_timesheet_holidays/__init__.py
  addons/project_timesheet_holidays/models/res_company.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/web/models/models.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/lib/odoo-editor/src/OdooEditor.js
  odoo/__init__.py
  odoo/addons/test_search_panel/models/models.py
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
  odoo/cli/server.py
Labels: tmp.15.0

#28274 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/partner_view.xml
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/account_fiscal_position.py
Labels: 16.0

#28275 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/partner_view.xml
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/account_fiscal_position.py
  addons/web/models/models.py
  doc/cla/corporate/factorlibre.md
  odoo/addons/test_search_panel/models/models.py
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
Labels: 17.0

#28278 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/partner_view.xml
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/account_fiscal_position.py
Labels: tmp.16.0

#28279 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/account.pot
  addons/account/i18n/hu.po
  addons/account/i18n/lv.po
  addons/account/models/partner.py
  addons/account/views/partner_view.xml
  addons/account_edi_ubl_cii/i18n/ar.po
  addons/account_edi_ubl_cii/i18n/ko.po
  addons/account_payment/i18n/hu.po
  addons/auth_signup/i18n/es_419.po
  addons/auth_totp/i18n/ro.po
  addons/base_setup/i18n/lv.po
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/i18n/it.po
  addons/base_vat/models/account_fiscal_position.py
  addons/delivery/i18n/de.po
  addons/delivery/i18n/es_419.po
  addons/delivery/i18n/it.po
  addons/delivery/i18n/pt_BR.po
  addons/hr_expense/i18n/hu.po
  addons/hr_expense/i18n/is.po
  addons/hr_timesheet/i18n/fr.po
  addons/hr_timesheet/i18n/it.po
  addons/loyalty/i18n/hu.po
  addons/mrp/i18n/et.po
  addons/mrp/i18n/pt_BR.po
  addons/payment/i18n/hu.po
  addons/point_of_sale/i18n/lv.po
  addons/portal/i18n/fr.po
  addons/pos_viva_wallet/i18n/pt_BR.po
  addons/project/i18n/fr.po
  addons/project/i18n/it.po
  addons/project_mail_plugin/i18n/it.po
  addons/purchase/i18n/hu.po
  addons/sale/i18n/hu.po
  addons/sale_loyalty/i18n/hu.po
  addons/sale_management/i18n/hu.po
  addons/sale_project/i18n/hu.po
  addons/sale_project/i18n/it.po
  addons/spreadsheet_dashboard_hr_timesheet/i18n/es_419.po
  addons/stock/i18n/lv.po
  addons/stock_account/i18n/is.po
  addons/survey/i18n/ro.po
  addons/web/models/models.py
  addons/website_sale/i18n/pt_BR.po
  doc/cla/corporate/factorlibre.md
  odoo/addons/base/i18n/hu.po
  odoo/addons/test_search_panel/models/models.py
  odoo/addons/test_search_panel/tests/test_search_panel_select_multi_range.py
Labels: tmp.17.0

#28280 Syncing from upstream odoo/odoo (master)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/partner_view.xml
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/account_fiscal_position.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
Labels: master

#28281 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/i18n/account.pot
  addons/account/models/partner.py
  addons/account/views/partner_view.xml
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/models/account_fiscal_position.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
Labels: tmp.master

#28284 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_fr_invoice_addr/views/report_invoice.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/web_editor/static/lib/odoo-editor/src/commands/shiftTab.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: 15.0

#28285 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_fr_invoice_addr/models/account_move.py
  addons/l10n_fr_invoice_addr/views/report_invoice.xml
  addons/l10n_pe/data/res_country_data.xml
  addons/l10n_pe/models/res_partner.py
  addons/loyalty/models/loyalty_reward.py
  addons/mail/models/mail_activity_mixin.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/web/static/src/legacy/js/widgets/colorpicker.js
  addons/web/static/src/webclient/settings_form_view/settings_form_controller.js
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/static/src/snippets/s_add_to_cart/options.js
  doc/cla/corporate/openforce.md
  odoo/__init__.py
  odoo/cli/server.py
Labels: 16.0

#28290 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_es_edi_tbai/data/template_invoice.xml
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_fr_invoice_addr/models/account_move.py
  addons/l10n_fr_invoice_addr/views/report_invoice.xml
  addons/l10n_pe/data/res_country_data.xml
  addons/l10n_pe/models/res_partner.py
  addons/loyalty/models/loyalty_reward.py
  addons/mail/models/mail_activity_mixin.py
  addons/pos_loyalty/models/pos_session.py
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/web/static/src/legacy/js/widgets/colorpicker.js
  addons/web/static/src/webclient/settings_form_view/settings_form_controller.js
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/static/src/snippets/s_add_to_cart/options.js
  doc/cla/corporate/openforce.md
  odoo/__init__.py
  odoo/cli/server.py
Labels: tmp.16.0

#28291 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/hr_skills/models/hr_resume_line.py
  addons/hr_skills_slides/models/hr_resume_line.py
  addons/hr_skills_slides/models/slide_channel.py
  addons/l10n_cl/models/account_move_line.py
  addons/l10n_fr_invoice_addr/views/report_invoice.xml
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_activity_mixin.py
  addons/mail/wizard/mail_compose_message.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/common.py
  addons/payment/tests/test_payment_transaction.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/tests/tours/helpers/ProductScreenTourMethods.js
  addons/point_of_sale/tests/test_anglo_saxon.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/sale/models/sale_order.py
  addons/sale/tests/test_payment_flow.py
  addons/sale_stock/report/stock_report_deliveryslip.xml
  addons/stock/report/report_deliveryslip.xml
  addons/stock_delivery/views/report_deliveryslip.xml
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.scss
  addons/web/static/src/views/calendar/calendar_common/calendar_common_popover.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/__init__.py
  odoo/cli/server.py
Labels: tmp.17.0

#28292 Syncing from upstream odoo/odoo (15.0)
  addons/base_vat/tests/test_validate_ruc.py
  addons/delivery/models/sale_order.py
  addons/partner_autocomplete/models/res_partner.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_sale_delivery/tests/test_controller.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/_monkeypatches.py
Labels: 15.0

#28293 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_latam_check/models/account_payment.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_reward.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/payment_mollie/models/payment_transaction.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/common.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_event/views/event_templates_page_registration.xml
Labels: 16.0

#28297 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/base_vat/tests/test_validate_ruc.py
  addons/delivery/models/sale_order.py
  addons/partner_autocomplete/models/res_partner.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_sale_delivery/tests/test_controller.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/_monkeypatches.py
Labels: tmp.15.0

#28298 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_latam_check/models/account_payment.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_reward.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/payment_mollie/models/payment_transaction.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/common.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_event/views/event_templates_page_registration.xml
Labels: tmp.16.0

#28299 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/views/account_move_views.xml
  addons/account_peppol/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/DisplayDriver_L.py
  addons/hw_drivers/views/pos_display.html
  addons/l10n_cz/models/__init__.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/__init__.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_pe/data/res_country_data.xml
  addons/l10n_pe/models/res_partner.py
  addons/l10n_ro_efactura/data/neutralize.sql
  addons/mail/static/src/core/common/message_search_hook.js
  addons/mail/static/src/core/web/messaging_menu.xml
  addons/payment/data/payment_method_data.xml
  addons/payment/data/payment_provider_data.xml
  addons/point_of_sale/models/pos_order.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/common.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/stock/models/product.py
  addons/stock/tests/test_product.py
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/src/views/fields/field.js
  addons/web/static/src/webclient/settings_form_view/settings_form_controller.js
  addons/web/static/tests/views/fields/daterange_field_tests.js
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  doc/cla/corporate/openforce.md
Labels: tmp.17.0

#28283 [bt#28056] cherry pick for logo height and width
  addons/web/models/ir_qweb.py
  addons/website/views/website_templates.xml
Labels: 15.0.project_gd_615.test

#28300 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_cl/models/account_move.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/data/account_fiscal_position_template_data.xml
  addons/l10n_fi/data/account_tax_group_data.xml
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/microsoft_calendar/tests/test_microsoft_event.py
  addons/microsoft_calendar/utils/microsoft_event.py
Labels: 15.0

#28301 Syncing from upstream odoo/odoo (16.0)
  addons/account/tests/common.py
  addons/account_update_tax_tags/__init__.py
  addons/account_update_tax_tags/__manifest__.py
  addons/account_update_tax_tags/i18n/account_update_tax_tags.pot
  addons/account_update_tax_tags/security/ir.model.access.csv
  addons/account_update_tax_tags/tests/__init__.py
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
  addons/account_update_tax_tags/views/res_config_settings_views.xml
  addons/account_update_tax_tags/wizard/__init__.py
  addons/account_update_tax_tags/wizard/account_update_tax_tags_wizard.py
  addons/account_update_tax_tags/wizard/account_update_tax_tags_wizard.xml
  addons/base_vat/tests/test_validate_ruc.py
  addons/delivery/models/sale_order.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/loyalty/report/loyalty_report_templates.xml
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/partner_autocomplete/models/res_partner.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_sale_delivery/tests/test_controller.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/_monkeypatches.py
Labels: 16.0

#28305 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_cl/models/account_move.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/data/account_fiscal_position_template_data.xml
  addons/l10n_fi/data/account_tax_group_data.xml
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/microsoft_calendar/tests/test_microsoft_event.py
  addons/microsoft_calendar/utils/microsoft_event.py
Labels: tmp.15.0

#28306 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/tests/common.py
  addons/account_update_tax_tags/__init__.py
  addons/account_update_tax_tags/__manifest__.py
  addons/account_update_tax_tags/i18n/account_update_tax_tags.pot
  addons/account_update_tax_tags/security/ir.model.access.csv
  addons/account_update_tax_tags/tests/__init__.py
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
  addons/account_update_tax_tags/views/res_config_settings_views.xml
  addons/account_update_tax_tags/wizard/__init__.py
  addons/account_update_tax_tags/wizard/account_update_tax_tags_wizard.py
  addons/account_update_tax_tags/wizard/account_update_tax_tags_wizard.xml
  addons/base_vat/tests/test_validate_ruc.py
  addons/delivery/models/sale_order.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/loyalty/report/loyalty_report_templates.xml
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/mass_mailing_sms/tests/test_mailing_internals.py
  addons/partner_autocomplete/models/res_partner.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_delivery/controllers/main.py
  addons/website_sale_delivery/i18n/website_sale_delivery.pot
  addons/website_sale_delivery/tests/test_controller.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/tools/_monkeypatches.py
Labels: tmp.16.0

#28308 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move_line.py
  addons/l10n_cz/models/__init__.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/__init__.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_it_edi/views/report_invoice.xml
  addons/l10n_ro_edi/data/neutralize.sql
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: master

#28309 Syncing from upstream odoo/odoo (saas-17.1)
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/tours/activity_date_format_tour.js
  addons/mail/tests/test_mail_activity.py
Labels: saas-17.1

#28310 Syncing from upstream odoo/odoo (saas-17.2)
  addons/l10n_it_edi/views/report_invoice.xml
  addons/mail/i18n/mail.pot
  addons/mail/wizard/mail_compose_message.py
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/legacy/views/fields/daterange_field_tests.js
Labels: saas-17.2

#28311 Syncing from upstream odoo/odoo (saas-17.4)
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: saas-17.4

#28312 Syncing from upstream odoo/odoo (staging.master)
  addons/account/models/account_move_line.py
  addons/l10n_cz/models/__init__.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/__init__.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: staging.master

#28313 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/tours/activity_date_format_tour.js
  addons/mail/tests/test_mail_activity.py
Labels: staging.saas-17.1

#28315 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: staging.saas-17.4

#28316 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_move_line.py
  addons/l10n_cz/models/__init__.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/__init__.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: tmp.master

#28317 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/tours/activity_date_format_tour.js
  addons/mail/tests/test_mail_activity.py
Labels: tmp.saas-17.1

#28318 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/tests/legacy/views/fields/daterange_field_tests.js
Labels: tmp.saas-17.2

#28319 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: tmp.saas-17.4

#28320 Syncing from upstream odoo/odoo (15.0)
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/migrations/13.0.2/post-migrate_update_taxes.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_IL.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/stock/report/report_deliveryslip.xml
  addons/survey/controllers/main.py
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: 15.0

#28321 Syncing from upstream odoo/odoo (16.0)
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/pos_discount/models/pos_session.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/models/product_attribute.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/stock/report/report_deliveryslip.xml
  addons/web/static/src/views/calendar/calendar_model.js
  addons/website_sale/controllers/main.py
Labels: 16.0

#28324 Syncing from upstream odoo/odoo (saas-17.1)
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/hw_drivers/iot_handlers/interfaces/SerialInterface.py
  addons/l10n_cy/__init__.py
  addons/l10n_cy/__manifest__.py
  addons/l10n_cy/data/account_tax_report_data.xml
  addons/l10n_cy/data/menuitem_data.xml
  addons/l10n_cy/data/template/account.account-cy.csv
  addons/l10n_cy/data/template/account.fiscal.position-cy.csv
  addons/l10n_cy/data/template/account.tax-cy.csv
  addons/l10n_cy/data/template/account.tax.group-cy.csv
  addons/l10n_cy/demo/demo_company.xml
  addons/l10n_cy/i18n/gr.po
  addons/l10n_cy/i18n/l10n_cy.pot
  addons/l10n_cy/i18n/tr.po
  addons/l10n_cy/models/__init__.py
  addons/l10n_cy/models/template_cy.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/pos_self_order/tests/test_self_order_common.py
  addons/project/static/src/views/project_task_kanban/project_task_kanban_view.scss
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/web/static/src/views/debug_items.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/banner_tests.js
  addons/website_crm_partner_assign/controllers/main.py
  odoo/__init__.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_http.py
  odoo/cli/server.py
Labels: saas-17.1

#28330 Syncing from upstream odoo/odoo (staging.15.0)
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/migrations/13.0.2/post-migrate_update_taxes.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_IL.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/stock/report/report_deliveryslip.xml
  addons/survey/controllers/main.py
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: staging.15.0

#28333 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_L.py
  addons/hw_drivers/iot_handlers/interfaces/PrinterInterface_L.py
  addons/hw_drivers/iot_handlers/interfaces/SerialInterface.py
  addons/l10n_cy/__init__.py
  addons/l10n_cy/__manifest__.py
  addons/l10n_cy/data/account_tax_report_data.xml
  addons/l10n_cy/data/menuitem_data.xml
  addons/l10n_cy/data/template/account.account-cy.csv
  addons/l10n_cy/data/template/account.fiscal.position-cy.csv
  addons/l10n_cy/data/template/account.tax-cy.csv
  addons/l10n_cy/data/template/account.tax.group-cy.csv
  addons/l10n_cy/demo/demo_company.xml
  addons/l10n_cy/i18n/gr.po
  addons/l10n_cy/i18n/l10n_cy.pot
  addons/l10n_cy/i18n/tr.po
  addons/l10n_cy/models/__init__.py
  addons/l10n_cy/models/template_cy.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/loyalty/models/loyalty_reward.py
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/pos_loyalty/static/tests/tours/PosLoyaltyTour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/pos_self_order/tests/test_self_order_common.py
  addons/project/static/src/views/project_task_kanban/project_task_kanban_view.scss
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/web/static/src/views/debug_items.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/utils.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/banner_tests.js
  addons/website_crm_partner_assign/controllers/main.py
  odoo/__init__.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_http.py
  odoo/cli/server.py
Labels: tmp.saas-17.1

#28336 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/migrations/13.0.2/post-migrate_update_taxes.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_IL.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/stock/report/report_deliveryslip.xml
  addons/survey/controllers/main.py
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: tmp.15.0

#28337 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_holidays/models/hr_leave.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/pos_discount/models/pos_session.py
  addons/pos_sale/static/src/js/OrderManagementScreen/SaleOrderManagementScreen.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/models/product_attribute.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/stock/report/report_deliveryslip.xml
  addons/web/static/src/views/calendar/calendar_model.js
  addons/website_sale/controllers/main.py
Labels: tmp.16.0

#28339 Syncing from upstream odoo/odoo (15.0)
  addons/hr_expense/models/account_move_line.py
  addons/payment_stripe/static/src/js/payment_form.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/pos_sale/static/src/js/models.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/website/i18n/website.pot
  doc/cla/corporate/manatec.md
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: 15.0

#28340 Syncing from upstream odoo/odoo (16.0)
  addons/google_calendar/wizard/reset_account.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/payment_stripe/static/src/js/stripe_options.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_IL.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/i18n/fr.po
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_location.py
  addons/survey/controllers/main.py
  addons/web/i18n/web.pot
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/legacy/xml/control_panel.xml
  addons/web_editor/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale/controllers/main.py
  odoo/tools/translate.py
Labels: 16.0

#28344 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/common.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_price_included_taxes.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/partner_autocomplete/models/res_partner.py
  addons/payment_mollie/models/payment_transaction.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_payment_flow.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/tools/_monkeypatches.py
Labels: saas-17.2

#28350 Syncing from upstream odoo/odoo (staging.15.0)
  addons/hr_expense/models/account_move_line.py
  addons/payment_stripe/static/src/js/payment_form.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/pos_sale/static/src/js/models.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/website/i18n/website.pot
  doc/cla/corporate/manatec.md
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: staging.15.0

#28351 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account/static/src/components/bills_upload/bills_upload.xml
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae_adm_centers/views/res_partner_views.xml
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_fr_invoice_addr/models/account_move.py
  addons/mail/static/src/core/common/thread.xml
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_manual_consumption.py
  addons/partner_autocomplete/models/res_partner.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_list/product_list.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/views/report_saledetails.xml
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/models/product_attribute.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/views/product_views.xml
  addons/stock/views/stock_move_line_views.xml
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_quant_views.xml
  addons/stock_account/views/stock_valuation_layer_views.xml
  addons/survey/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/tools/_monkeypatches.py
Labels: staging.17.0

#28354 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/common.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_price_included_taxes.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/partner_autocomplete/models/res_partner.py
  addons/payment_mollie/models/payment_transaction.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_payment_flow.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/color.test.js
  addons/website_crm_partner_assign/controllers/main.py
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-17.2

#28356 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/hr_expense/models/account_move_line.py
  addons/payment_stripe/static/src/js/payment_form.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/pos_sale/static/src/js/models.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/website/i18n/website.pot
  doc/cla/corporate/manatec.md
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: tmp.15.0

#28357 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/google_calendar/wizard/reset_account.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/payment_stripe/static/src/js/stripe_options.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_IL.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/i18n/fr.po
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/stock/models/stock_location.py
  addons/survey/controllers/main.py
  addons/web/i18n/web.pot
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/legacy/xml/control_panel.xml
  addons/web_editor/controllers/main.py
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale/controllers/main.py
  odoo/tools/translate.py
Labels: tmp.16.0

#28358 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account/static/src/components/bills_upload/bills_upload.xml
  addons/base_vat/tests/test_validate_ruc.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_es_edi_facturae_adm_centers/views/res_partner_views.xml
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_fr_invoice_addr/models/account_move.py
  addons/mail/static/src/core/common/thread.xml
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing/static/src/js/snippets.editor.js
  addons/mrp/models/stock_move.py
  addons/mrp/tests/test_manual_consumption.py
  addons/partner_autocomplete/models/res_partner.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_list/product_list.js
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/views/report_saledetails.xml
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/product/models/product_attribute.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/stock/report/report_deliveryslip.xml
  addons/stock/views/product_views.xml
  addons/stock/views/stock_move_line_views.xml
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_quant_views.xml
  addons/stock_account/views/stock_valuation_layer_views.xml
  addons/survey/controllers/main.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/tools/_monkeypatches.py
Labels: tmp.17.0

#28359 Syncing from upstream odoo/odoo (16.0)
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: 16.0

#28360 Syncing from upstream odoo/odoo (17.0)
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
  addons/web/static/lib/owl/owl.js
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: 17.0

#28361 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/console.js
  addons/web/static/lib/hoot/mock/network.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/expect.test.js
  addons/web/static/lib/hoot/tests/core/test.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot_utils.test.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/index.js
  addons/web/static/lib/hoot/tests/ui/hoot_technical_value.test.js
  addons/web/static/lib/hoot/ui/hoot_log_counters.js
  addons/web/static/lib/hoot/ui/hoot_presets.js
  addons/web/static/lib/hoot/ui/hoot_reporting.js
  addons/web/static/lib/hoot/ui/hoot_search.js
  addons/web/static/lib/hoot/ui/hoot_side_bar.js
  addons/web/static/lib/hoot/ui/hoot_style.css
  addons/web/static/lib/hoot/ui/hoot_technical_value.js
  addons/web/static/lib/hoot/ui/hoot_test_result.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_server/mock_server.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/core/notebook.test.js
  addons/web/static/tests/core/tags_list.test.js
  addons/web/static/tests/views/fields/color_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/views/fields/many2many_tags_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web/static/tests/views/kanban/kanban_view.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
Labels: master

#28363 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/common.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_price_included_taxes.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/console.js
  addons/web/static/lib/hoot/mock/network.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/expect.test.js
  addons/web/static/lib/hoot/tests/core/test.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot_utils.test.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/index.js
  addons/web/static/lib/hoot/tests/ui/hoot_technical_value.test.js
  addons/web/static/lib/hoot/ui/hoot_log_counters.js
  addons/web/static/lib/hoot/ui/hoot_presets.js
  addons/web/static/lib/hoot/ui/hoot_reporting.js
  addons/web/static/lib/hoot/ui/hoot_search.js
  addons/web/static/lib/hoot/ui/hoot_side_bar.js
  addons/web/static/lib/hoot/ui/hoot_style.css
  addons/web/static/lib/hoot/ui/hoot_technical_value.js
  addons/web/static/lib/hoot/ui/hoot_test_result.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_server/mock_server.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/core/notebook.test.js
  addons/web/static/tests/core/tags_list.test.js
  addons/web/static/tests/views/fields/color_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/views/fields/many2many_tags_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web/static/tests/views/kanban/kanban_view.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/views/snippets.xml
Labels: saas-17.4

#28364 Syncing from upstream odoo/odoo (staging.master)
  addons/account/models/account_move.py
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/console.js
  addons/web/static/lib/hoot/mock/network.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/expect.test.js
  addons/web/static/lib/hoot/tests/core/test.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot_utils.test.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/index.js
  addons/web/static/lib/hoot/tests/ui/hoot_technical_value.test.js
  addons/web/static/lib/hoot/ui/hoot_log_counters.js
  addons/web/static/lib/hoot/ui/hoot_presets.js
  addons/web/static/lib/hoot/ui/hoot_reporting.js
  addons/web/static/lib/hoot/ui/hoot_search.js
  addons/web/static/lib/hoot/ui/hoot_side_bar.js
  addons/web/static/lib/hoot/ui/hoot_style.css
  addons/web/static/lib/hoot/ui/hoot_technical_value.js
  addons/web/static/lib/hoot/ui/hoot_test_result.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_server/mock_server.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/core/notebook.test.js
  addons/web/static/tests/core/tags_list.test.js
  addons/web/static/tests/views/fields/color_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/views/fields/many2many_tags_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web/static/tests/views/kanban/kanban_view.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
Labels: staging.master

#28367 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/common.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_price_included_taxes.xml
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/console.js
  addons/web/static/lib/hoot/mock/network.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/expect.test.js
  addons/web/static/lib/hoot/tests/core/test.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot_utils.test.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/index.js
  addons/web/static/lib/hoot/tests/ui/hoot_technical_value.test.js
  addons/web/static/lib/hoot/ui/hoot_log_counters.js
  addons/web/static/lib/hoot/ui/hoot_presets.js
  addons/web/static/lib/hoot/ui/hoot_reporting.js
  addons/web/static/lib/hoot/ui/hoot_search.js
  addons/web/static/lib/hoot/ui/hoot_side_bar.js
  addons/web/static/lib/hoot/ui/hoot_style.css
  addons/web/static/lib/hoot/ui/hoot_technical_value.js
  addons/web/static/lib/hoot/ui/hoot_test_result.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_server/mock_server.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/core/notebook.test.js
  addons/web/static/tests/core/tags_list.test.js
  addons/web/static/tests/views/fields/color_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/views/fields/many2many_tags_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web/static/tests/views/kanban/kanban_view.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/views/snippets.xml
Labels: staging.saas-17.4

#28369 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_move.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/console.js
  addons/web/static/lib/hoot/mock/network.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/expect.test.js
  addons/web/static/lib/hoot/tests/core/test.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot_utils.test.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/index.js
  addons/web/static/lib/hoot/tests/ui/hoot_technical_value.test.js
  addons/web/static/lib/hoot/ui/hoot_log_counters.js
  addons/web/static/lib/hoot/ui/hoot_presets.js
  addons/web/static/lib/hoot/ui/hoot_reporting.js
  addons/web/static/lib/hoot/ui/hoot_search.js
  addons/web/static/lib/hoot/ui/hoot_side_bar.js
  addons/web/static/lib/hoot/ui/hoot_style.css
  addons/web/static/lib/hoot/ui/hoot_technical_value.js
  addons/web/static/lib/hoot/ui/hoot_test_result.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_server/mock_server.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/core/notebook.test.js
  addons/web/static/tests/core/tags_list.test.js
  addons/web/static/tests/views/fields/color_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/views/fields/many2many_tags_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web/static/tests/views/kanban/kanban_view.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
Labels: tmp.master

#28371 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/common.py
  addons/account/tests/test_invoice_tax_totals.py
  addons/l10n_cl/demo/partner_demo.xml
  addons/l10n_cl/demo/teksa-logo-300.png
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_price_included_taxes.xml
  addons/mrp/models/product.py
  addons/mrp/tests/test_multicompany.py
  addons/web/static/lib/hoot-dom/helpers/dom.js
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/console.js
  addons/web/static/lib/hoot/mock/network.js
  addons/web/static/lib/hoot/mock/window.js
  addons/web/static/lib/hoot/tests/core/expect.test.js
  addons/web/static/lib/hoot/tests/core/test.test.js
  addons/web/static/lib/hoot/tests/hoot-dom/dom.test.js
  addons/web/static/lib/hoot/tests/hoot_utils.test.js
  addons/web/static/lib/hoot/tests/index.html
  addons/web/static/lib/hoot/tests/index.js
  addons/web/static/lib/hoot/tests/ui/hoot_technical_value.test.js
  addons/web/static/lib/hoot/ui/hoot_log_counters.js
  addons/web/static/lib/hoot/ui/hoot_presets.js
  addons/web/static/lib/hoot/ui/hoot_reporting.js
  addons/web/static/lib/hoot/ui/hoot_search.js
  addons/web/static/lib/hoot/ui/hoot_side_bar.js
  addons/web/static/lib/hoot/ui/hoot_style.css
  addons/web/static/lib/hoot/ui/hoot_technical_value.js
  addons/web/static/lib/hoot/ui/hoot_test_result.js
  addons/web/static/tests/_framework/mock_server/mock_model.js
  addons/web/static/tests/_framework/mock_server/mock_server.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/core/notebook.test.js
  addons/web/static/tests/core/tags_list.test.js
  addons/web/static/tests/views/fields/color_field.test.js
  addons/web/static/tests/views/fields/daterange_field.test.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/views/fields/many2many_tags_field.test.js
  addons/web/static/tests/views/fields/properties_field.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web/static/tests/views/kanban/kanban_view.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/views/snippets.xml
Labels: tmp.saas-17.4

#28372 Syncing from upstream odoo/odoo (tmp.16.0)
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: tmp.16.0

#28373 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/tests/test_audit_trail.py
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
  addons/web/static/lib/owl/owl.js
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_sale/controllers/main.py
  odoo/addons/base/tests/test_base.py
  odoo/tools/safe_eval.py
Labels: tmp.17.0

#28374 Syncing from upstream odoo/odoo (15.0)
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
Labels: 15.0

#28375 Syncing from upstream odoo/odoo (17.0)
  addons/l10n_it/models/account_chart_template.py
Labels: 17.0

#28376 Syncing from upstream odoo/odoo (master)
  addons/event/report/event_event_templates.xml
Labels: master

#28377 Syncing from upstream odoo/odoo (saas-17.1)
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
Labels: saas-17.1

#28378 Syncing from upstream odoo/odoo (staging.master)
  addons/event/report/event_event_templates.xml
Labels: staging.master

#28379 Syncing from upstream odoo/odoo (staging.saas-17.1)
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
Labels: staging.saas-17.1

#28382 Syncing from upstream odoo/odoo (staging.15.0)
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
Labels: staging.15.0

#28383 Syncing from upstream odoo/odoo (staging.17.0)
  addons/l10n_it/models/account_chart_template.py
Labels: staging.17.0

#28384 Syncing from upstream odoo/odoo (tmp.master)
  addons/event/report/event_event_templates.xml
Labels: tmp.master

#28385 Syncing from upstream odoo/odoo (tmp.saas-17.1)
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
Labels: tmp.saas-17.1

#28386 Syncing from upstream odoo/odoo (tmp.15.0)
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
Labels: tmp.15.0

#28388 Syncing from upstream odoo/odoo (15.0)
  addons/purchase_stock/models/stock.py
Labels: 15.0

#28389 Syncing from upstream odoo/odoo (16.0)
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_fi/__manifest__.py
  addons/l10n_fi/data/account_fiscal_position_template_data.xml
  addons/l10n_fi/data/account_tax_group_data.xml
  addons/l10n_fi/data/account_tax_report_line.xml
  addons/l10n_fi/data/account_tax_template_data.xml
  addons/l10n_fi/data/migrations/13.0.2/post-migrate_update_taxes.py
  addons/l10n_fi/i18n/fi.po
  addons/l10n_fi/i18n/l10n_fi.pot
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/GiftCardProgramTours.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale/static/src/js/models.js
  addons/pos_sale/static/tests/tours/pos_sale_tours.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/purchase/models/purchase.py
  addons/purchase_stock/models/stock.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/web/static/src/core/action_swiper/action_swiper.js
  addons/web/static/tests/mobile/core/action_swiper_tests.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: 16.0

#28393 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_account.py
  addons/account/static/src/components/bills_upload/bills_upload.js
  addons/account/static/src/components/bills_upload/bills_upload.xml
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/google_calendar/wizard/reset_account.py
  addons/l10n_at/__manifest__.py
  addons/l10n_at/data/account_account_tag.xml
  addons/l10n_at/data/template/account.account-at.csv
  addons/l10n_at/migrations/3.2/post-migrate.py
  addons/l10n_es_edi_facturae/views/res_partner_views.xml
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_it/models/account_chart_template.py
  addons/l10n_latam_check/models/account_payment.py
  addons/mail/static/src/core/common/thread.xml
  addons/mail/static/src/core/web/messaging_menu.xml
  addons/mrp/i18n/mrp.pot
  addons/mrp/models/mrp_bom.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_backorder.py
  addons/mrp/tests/test_bom.py
  addons/payment_stripe/static/src/js/stripe_options.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_KE.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/report_sale_details.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/views/report_saledetails.xml
  addons/pos_self_order/tests/test_self_order_combo.py
  addons/pos_self_order/tests/test_self_order_common.py
  addons/product/models/product_attribute.py
  addons/sale/report/sale_report.py
  addons/sale/tests/test_sale_report.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sale_product_configurator/static/src/js/product_template_attribute_line/product_template_attribute_line.xml
  addons/stock/models/stock_move.py
  addons/stock/views/product_views.xml
  addons/stock/views/stock_move_line_views.xml
  addons/stock/views/stock_move_views.xml
  addons/stock/views/stock_quant_views.xml
  addons/stock_account/views/stock_valuation_layer_views.xml
  addons/web/static/src/views/fields/many2one/many2one_field.js
  addons/web/static/src/views/fields/many2one/many2one_field.xml
  addons/web/static/tests/legacy/views/fields/many2one_field_tests.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_facebook_page/options.js
  addons/website_profile/controllers/main.py
  odoo/__init__.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_base.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/cli/server.py
  odoo/tools/safe_eval.py
Labels: saas-17.2

#28394 Syncing from upstream odoo/odoo (saas-17.3)
  odoo/addons/base/i18n/base.pot
Labels: saas-17.3

#28400 Syncing from upstream odoo/odoo (staging.15.0)
  addons/purchase_stock/models/stock.py
Labels: staging.15.0

#28401 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/tests/common.py
  addons/account/tests/test_account_journal_dashboard.py
  addons/account_audit_trail/models/__init__.py
  addons/account_audit_trail/models/mail_message.py
  addons/account_audit_trail/models/merge_partner_automatic.py
  addons/account_update_tax_tags/tests/test_account_update_tax_tags_wizard.py
  addons/google_calendar/wizard/reset_account.py
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_latam_check/models/account_payment.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/activity.js
  addons/mail/static/src/core/web/activity.xml
  addons/mail/static/tests/activity/activity_tests.js
  addons/payment_stripe/static/src/js/stripe_options.js
  addons/phone_validation/lib/phonenumbers_patch/__init__.py
  addons/phone_validation/lib/phonenumbers_patch/region_IL.py
  addons/phone_validation/tests/test_phonenumbers_patch.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/point_of_sale/static/tests/tours/PosComboTour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/purchase/models/purchase_order_line.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/i18n/website.pot
  addons/website/static/src/components/edit_head_body_dialog/edit_head_body_dialog.xml
  odoo/tools/translate.py
Labels: staging.17.0
