Repository brain-tec/odoo, pull requests merged in 2025-09, with the labels that each got.

#35232 Syncing from upstream odoo/odoo (18.0)
  .tx/config
  addons/mass_mailing_sms/models/sms_tracker.py
  addons/mass_mailing_sms/tests/common.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/phone_validation/tools/phone_validation.py
  addons/sms/models/__init__.py
  addons/sms/models/res_company.py
  addons/sms/models/sms_sms.py
  addons/sms/models/sms_tracker.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms/wizard/sms_composer.py
  addons/sms_twilio/__init__.py
  addons/sms_twilio/__manifest__.py
  addons/sms_twilio/controllers/__init__.py
  addons/sms_twilio/controllers/controllers.py
  addons/sms_twilio/data/neutralize.sql
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/res_company.py
  addons/sms_twilio/models/res_config_settings.py
  addons/sms_twilio/models/sms_composer.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_tracker.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/security/ir.model.access.csv
  addons/sms_twilio/tests/__init__.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_sms_twilio_controller.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/__init__.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/views/res_config_settings_views.xml
  addons/sms_twilio/views/sms_sms_views.xml
  addons/sms_twilio/wizard/__init__.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/sms_twilio/wizard/sms_twilio_account_manage_views.xml
  addons/test_mail_sms/__manifest__.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/test_mail_sms/tests/test_sms_performance.py
  addons/test_mass_mailing/__manifest__.py
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
Labels: 18.0

#35234 Syncing from upstream odoo/odoo (saas-18.2)
  .tx/config
  addons/mass_mailing_sms/models/sms_tracker.py
  addons/mass_mailing_sms/tests/common.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/phone_validation/tools/phone_validation.py
  addons/sms/models/__init__.py
  addons/sms/models/res_company.py
  addons/sms/models/sms_sms.py
  addons/sms/models/sms_tracker.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms/wizard/sms_composer.py
  addons/sms_twilio/__init__.py
  addons/sms_twilio/__manifest__.py
  addons/sms_twilio/controllers/__init__.py
  addons/sms_twilio/controllers/controllers.py
  addons/sms_twilio/data/neutralize.sql
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/res_company.py
  addons/sms_twilio/models/res_config_settings.py
  addons/sms_twilio/models/sms_composer.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_tracker.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/security/ir.model.access.csv
  addons/sms_twilio/tests/__init__.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_sms_twilio_controller.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/__init__.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/views/res_config_settings_views.xml
  addons/sms_twilio/views/sms_sms_views.xml
  addons/sms_twilio/wizard/__init__.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/sms_twilio/wizard/sms_twilio_account_manage_views.xml
  addons/test_mail_sms/__manifest__.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/test_mail_sms/tests/test_sms_performance.py
  addons/test_mass_mailing/__manifest__.py
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
Labels: saas-18.2

#35235 Syncing from upstream odoo/odoo (saas-18.3)
  .tx/config
  addons/mass_mailing_sms/models/sms_tracker.py
  addons/mass_mailing_sms/tests/common.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/phone_validation/tools/phone_validation.py
  addons/sms/models/__init__.py
  addons/sms/models/res_company.py
  addons/sms/models/sms_sms.py
  addons/sms/models/sms_tracker.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms/wizard/sms_composer.py
  addons/sms_twilio/__init__.py
  addons/sms_twilio/__manifest__.py
  addons/sms_twilio/controllers/__init__.py
  addons/sms_twilio/controllers/controllers.py
  addons/sms_twilio/data/neutralize.sql
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/res_company.py
  addons/sms_twilio/models/res_config_settings.py
  addons/sms_twilio/models/sms_composer.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_tracker.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/security/ir.model.access.csv
  addons/sms_twilio/tests/__init__.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_sms_twilio_controller.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/__init__.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/views/res_config_settings_views.xml
  addons/sms_twilio/views/sms_sms_views.xml
  addons/sms_twilio/wizard/__init__.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/sms_twilio/wizard/sms_twilio_account_manage_views.xml
  addons/test_mail_sms/__manifest__.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/test_mail_sms/tests/test_sms_performance.py
  addons/test_mass_mailing/__manifest__.py
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
Labels: saas-18.3

#35244 Syncing from upstream odoo/odoo (tmp.saas-18.4)
  .tx/config
  addons/mass_mailing_sms/models/sms_tracker.py
  addons/mass_mailing_sms/tests/common.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/phone_validation/tools/phone_validation.py
  addons/sms/models/__init__.py
  addons/sms/models/res_company.py
  addons/sms/models/sms_sms.py
  addons/sms/models/sms_tracker.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms/wizard/sms_composer.py
  addons/sms_twilio/__init__.py
  addons/sms_twilio/__manifest__.py
  addons/sms_twilio/controllers/__init__.py
  addons/sms_twilio/controllers/controllers.py
  addons/sms_twilio/data/neutralize.sql
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/res_company.py
  addons/sms_twilio/models/res_config_settings.py
  addons/sms_twilio/models/sms_composer.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_tracker.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/security/ir.model.access.csv
  addons/sms_twilio/tests/__init__.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_sms_twilio_controller.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/__init__.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/views/res_config_settings_views.xml
  addons/sms_twilio/views/sms_sms_views.xml
  addons/sms_twilio/wizard/__init__.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/sms_twilio/wizard/sms_twilio_account_manage_views.xml
  addons/test_mail_sms/__manifest__.py
  addons/test_mail_sms/tests/test_sms_composer.py
  addons/test_mail_sms/tests/test_sms_performance.py
  addons/test_mass_mailing/__manifest__.py
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
Labels: tmp.saas-18.4

#35247 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/es_419.po
  addons/account/models/account_move.py
  addons/account/tests/test_account_journal.py
  addons/account/views/account_move_views.xml
  addons/hr_recruitment/i18n/es.po
  addons/mrp/i18n/fr.po
  addons/purchase/i18n/ja.po
  addons/sale/i18n/nl.po
  addons/spreadsheet_dashboard_stock_account/i18n/fr.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/ja.po
  addons/stock_account/i18n/fr.po
  addons/survey/controllers/survey_session_manage.py
  addons/survey/tests/test_survey_controller.py
  addons/web_editor/i18n/es.po
  addons/website_sale_stock/i18n/fr.po
  odoo/addons/base/i18n/zh_TW.po
Labels: 17.0

#35255 Syncing from upstream odoo/odoo (staging.saas-18.3)
  addons/account/static/src/helpers/account_tax.js
  addons/hr_holidays/report/hr_leave_report_calendar.xml
  addons/hr_holidays/static/src/leave_stats/leave_stats.xml
  addons/hr_holidays/static/src/views/calendar/calendar_controller.xml
  addons/l10n_es_edi_tbai/tests/test_edi_tbai_send_invoice.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/test_flows_mocked.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_ewaybill/i18n/l10n_in_ewaybill.pot
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_irn/models/l10n_in_ewaybill.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mrp/models/product.py
  addons/mrp/tests/test_stock.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/payment_razorpay/models/payment_provider.py
  addons/point_of_sale/models/product_attribute.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/models/utils/compute_combo_items.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/static/src/app/models/pos_order.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/services/pos_store.js
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/services/card_utils.js
  addons/pos_self_order/tests/test_self_order_attribute.py
  addons/sale_pdf_quote_builder/models/product_document.py
  addons/stock_account/models/stock_move.py
  addons/test_discuss_full/tests/test_performance_inbox.py
  addons/web/static/src/core/errors/error_dialogs.js
  addons/web/static/src/core/l10n/dates.js
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/calendar/calendar_renderer.scss
  addons/web/static/src/views/form/form_controller.js
  addons/web/static/src/views/form/form_error_dialog/form_error_dialog.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/core/components/datetime/datetime_hook.test.js
  addons/web/static/tests/core/l10n/dates.test.js
  addons/web/static/tests/mock_server/mock_server.test.js
  addons/web/static/tests/views/form/form_view.test.js
Labels: staging.saas-18.3

#35256 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_es/data/account_tax_data.xml
  addons/l10n_es/i18n/es.po
  addons/l10n_es/i18n/l10n_es.pot
  odoo/tests/test_module_operations.py
Labels: staging.16.0

#35258 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/views/account_move_views.xml
  addons/l10n_es_edi_verifactu/models/verifactu_document.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/test_flows_mocked.py
  addons/l10n_tr_nilvera_einvoice/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/data/res_partner_category_data.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/__init__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_tr_nilvera_einvoice/models/account_move_send.py
  addons/l10n_tr_nilvera_einvoice/models/res_partner_category.py
  addons/l10n_tw_edi_ecpay/__init__.py
  addons/l10n_tw_edi_ecpay/__manifest__.py
  addons/l10n_tw_edi_ecpay/controllers/__init__.py
  addons/l10n_tw_edi_ecpay/controllers/main.py
  addons/l10n_tw_edi_ecpay/i18n/l10n_tw_edi_ecpay.pot
  addons/l10n_tw_edi_ecpay/i18n/zh_TW.po
  addons/l10n_tw_edi_ecpay/models/__init__.py
  addons/l10n_tw_edi_ecpay/models/account_move.py
  addons/l10n_tw_edi_ecpay/models/account_move_line.py
  addons/l10n_tw_edi_ecpay/models/account_move_send.py
  addons/l10n_tw_edi_ecpay/models/account_tax.py
  addons/l10n_tw_edi_ecpay/models/res_company.py
  addons/l10n_tw_edi_ecpay/models/res_config_settings.py
  addons/l10n_tw_edi_ecpay/models/res_partner.py
  addons/l10n_tw_edi_ecpay/security/ir.model.access.csv
  addons/l10n_tw_edi_ecpay/tests/__init__.py
  addons/l10n_tw_edi_ecpay/tests/test_edi.py
  addons/l10n_tw_edi_ecpay/utils.py
  addons/l10n_tw_edi_ecpay/views/account_move_reversal_view.xml
  addons/l10n_tw_edi_ecpay/views/account_move_view.xml
  addons/l10n_tw_edi_ecpay/views/account_tax.xml
  addons/l10n_tw_edi_ecpay/views/l10n_tw_edi_invoice_cancel_view.xml
  addons/l10n_tw_edi_ecpay/views/l10n_tw_edi_invoice_print_view.xml
  addons/l10n_tw_edi_ecpay/views/res_config_setting_view.xml
  addons/l10n_tw_edi_ecpay/wizard/__init__.py
  addons/l10n_tw_edi_ecpay/wizard/account_move_reversal.py
  addons/l10n_tw_edi_ecpay/wizard/l10n_tw_edi_invoice_cancel.py
  addons/l10n_tw_edi_ecpay/wizard/l10n_tw_edi_invoice_print.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale_pdf_quote_builder/models/product_document.py
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/models/stock_picking.py
  doc/cla/individual/hildickethan.md
  odoo/cli/__init__.py
  odoo/cli/command.py
  odoo/cli/shell.py
  odoo/tests/common.py
  odoo/tests/shell.py
Labels: staging.18.0

#35260 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account/models/chart_template.py
  addons/account/wizard/account_move_send_wizard.py
  addons/html_editor/static/src/main/font/color_plugin.js
  addons/html_editor/static/src/main/media/icon_plugin.js
  addons/html_editor/static/tests/color.test.js
  addons/html_editor/static/tests/color_selector.test.js
  addons/html_editor/static/tests/icon.test.js
  addons/html_editor/static/tests/table/misc.test.js
  addons/l10n_es_edi_tbai/tests/test_edi_tbai_send_invoice.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/test_flows_mocked.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_ewaybill/i18n/l10n_in_ewaybill.pot
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_irn/models/l10n_in_ewaybill.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/core/web/mail_composer_template_selector.js
  addons/mail/static/tests/tours/mail_composer_test_tour.js
  addons/mail/tests/test_mail_composer.py
  addons/point_of_sale/static/src/app/screens/product_screen/control_buttons/control_buttons.js
  addons/point_of_sale/static/tests/pos/tours/product_screen_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_restaurant/models/pos_order.py
  addons/pos_restaurant/static/src/app/screens/tip_screen/tip_screen.js
  addons/pos_restaurant/static/tests/tours/tip_screen_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/models/account_invoice.py
  addons/purchase_stock/models/stock_valuation_layer.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/sale_mrp/tests/test_sale_mrp_anglo_saxon_valuation.py
  addons/sale_pdf_quote_builder/models/product_document.py
  addons/sale_stock/models/__init__.py
  addons/sale_stock/models/stock_valuation_layer.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/calendar/calendar_renderer.scss
  odoo/addons/base/models/ir_actions.py
Labels: tmp.saas-18.2

#35262 Syncing from upstream odoo/odoo (tmp.saas-18.4)
  addons/crm/tests/test_crm_lead.py
  addons/hr_holidays/report/hr_leave_report_calendar.xml
  addons/hr_holidays/static/src/leave_stats/leave_stats.xml
  addons/hr_holidays/static/src/views/calendar/calendar_controller.xml
  addons/hr_holidays/tests/test_global_leaves.py
  addons/html_editor/static/src/core/selection_plugin.js
  addons/html_editor/static/src/main/font/font_plugin.js
  addons/html_editor/static/src/main/font/font_size_selector.js
  addons/html_editor/static/tests/chatgpt_translate.test.js
  addons/html_editor/static/tests/toolbar.test.js
  addons/im_livechat/static/tests/livechat_channel_info_list.test.js
  addons/im_livechat/static/tests/sidebar_patch.test.js
  addons/iot_drivers/interface.py
  addons/iot_drivers/tools/certificate.py
  addons/l10n_es_edi_tbai/tests/test_edi_tbai_send_invoice.py
  addons/l10n_es_edi_verifactu/models/verifactu_document.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/test_flows_mocked.py
  addons/l10n_in_edi/i18n/l10n_in_edi.pot
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_ewaybill/i18n/l10n_in_ewaybill.pot
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_irn/models/l10n_in_ewaybill.py
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/discuss/core/web/discuss.test.js
  addons/mail/static/tests/mail_test_helpers.js
  addons/mail/static/tests/message/message.test.js
  addons/mrp/models/product.py
  addons/mrp/tests/test_stock.py
  addons/payment_razorpay/models/payment_provider.py
  addons/point_of_sale/static/src/app/models/pos_config.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.xml
  addons/pos_self_order/static/src/app/models/pos_config.js
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/services/card_utils.js
  addons/pos_self_order/static/src/overrides/components/receipt_header/receipt_header.xml
  addons/pos_self_order/static/tests/tours/self_order_combo_tour.js
  addons/pos_self_order/static/tests/tours/self_order_kiosk_tour.js
  addons/pos_self_order/static/tests/tours/utils/confirmation_page_util.js
  addons/pos_self_order/tests/test_self_order_attribute.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/resource/models/resource_calendar.py
  addons/sale_pdf_quote_builder/models/product_document.py
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/calendar/calendar_renderer.scss
  addons/website/static/src/builder/plugins/theme/theme_colors_option.xml
  addons/website/static/src/client_actions/website_preview/website_builder_action.xml
  addons/website/tests/test_qweb.py
  odoo/addons/test_orm/models/test_orm.py
  odoo/addons/test_orm/security/ir.model.access.csv
  odoo/addons/test_orm/tests/test_one2many.py
  odoo/orm/models.py
Labels: tmp.saas-18.4

#35265 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/views/account_move_views.xml
  addons/l10n_es_edi_verifactu/models/verifactu_document.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/test_flows_mocked.py
  addons/l10n_tr_nilvera_einvoice/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/data/res_partner_category_data.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/__init__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_tr_nilvera_einvoice/models/account_move_send.py
  addons/l10n_tr_nilvera_einvoice/models/res_partner_category.py
  addons/l10n_tw_edi_ecpay/__init__.py
  addons/l10n_tw_edi_ecpay/__manifest__.py
  addons/l10n_tw_edi_ecpay/controllers/__init__.py
  addons/l10n_tw_edi_ecpay/controllers/main.py
  addons/l10n_tw_edi_ecpay/i18n/l10n_tw_edi_ecpay.pot
  addons/l10n_tw_edi_ecpay/i18n/zh_TW.po
  addons/l10n_tw_edi_ecpay/models/__init__.py
  addons/l10n_tw_edi_ecpay/models/account_move.py
  addons/l10n_tw_edi_ecpay/models/account_move_line.py
  addons/l10n_tw_edi_ecpay/models/account_move_send.py
  addons/l10n_tw_edi_ecpay/models/account_tax.py
  addons/l10n_tw_edi_ecpay/models/res_company.py
  addons/l10n_tw_edi_ecpay/models/res_config_settings.py
  addons/l10n_tw_edi_ecpay/models/res_partner.py
  addons/l10n_tw_edi_ecpay/security/ir.model.access.csv
  addons/l10n_tw_edi_ecpay/tests/__init__.py
  addons/l10n_tw_edi_ecpay/tests/test_edi.py
  addons/l10n_tw_edi_ecpay/utils.py
  addons/l10n_tw_edi_ecpay/views/account_move_reversal_view.xml
  addons/l10n_tw_edi_ecpay/views/account_move_view.xml
  addons/l10n_tw_edi_ecpay/views/account_tax.xml
  addons/l10n_tw_edi_ecpay/views/l10n_tw_edi_invoice_cancel_view.xml
  addons/l10n_tw_edi_ecpay/views/l10n_tw_edi_invoice_print_view.xml
  addons/l10n_tw_edi_ecpay/views/res_config_setting_view.xml
  addons/l10n_tw_edi_ecpay/wizard/__init__.py
  addons/l10n_tw_edi_ecpay/wizard/account_move_reversal.py
  addons/l10n_tw_edi_ecpay/wizard/l10n_tw_edi_invoice_cancel.py
  addons/l10n_tw_edi_ecpay/wizard/l10n_tw_edi_invoice_print.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/views/purchase_views.xml
  addons/sale_pdf_quote_builder/models/product_document.py
  addons/stock_picking_batch/models/stock_move_line.py
  addons/stock_picking_batch/models/stock_picking.py
  doc/cla/individual/hildickethan.md
  odoo/cli/__init__.py
  odoo/cli/command.py
  odoo/cli/shell.py
  odoo/tests/common.py
  odoo/tests/shell.py
Labels: tmp.18.0

#35266 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_in_edi/models/account_edi_format.py
  odoo/tests/common.py
  setup/package.dfsrc
Labels: 16.0

#35274 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account/wizard/base_document_layout.py
  addons/analytic/models/analytic_plan.py
  addons/auth_signup/i18n/my.po
  addons/l10n_es/data/template/account.tax-es_canary_common.csv
  addons/l10n_es_edi_verifactu/models/verifactu_document.py
  addons/l10n_id_efaktur_coretax/models/product_code.py
  addons/l10n_tr_nilvera_einvoice/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/data/res_partner_category_data.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/__init__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_tr_nilvera_einvoice/models/account_move_send.py
  addons/l10n_tr_nilvera_einvoice/models/res_partner_category.py
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/stock_move.py
  addons/mrp_account/models/stock_valuation_layer.py
  addons/mrp_account/tests/test_mrp_account.py
  addons/point_of_sale/static/tests/pos/tours/product_screen_tour.js
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/product/i18n/my.po
  addons/purchase/i18n/it.po
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/web/static/src/public/interaction_service.js
  addons/web/static/tests/public/interaction_service.test.js
  addons/website/i18n/my.po
  doc/cla/individual/fernandoromera.md
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/i18n/my.po
  odoo/cli/__init__.py
  odoo/cli/command.py
  odoo/cli/shell.py
  odoo/tests/common.py
  odoo/tests/shell.py
Labels: staging.saas-18.2

#35276 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_in_edi/models/account_edi_format.py
  odoo/tests/common.py
  setup/package.dfsrc
Labels: staging.16.0

#35277 Syncing from upstream odoo/odoo (staging.17.0)
  .tx/config
  .weblate.json
  addons/account/i18n/es_419.po
  addons/account/models/account_move.py
  addons/account_peppol/tools/demo_bill
  addons/hr_org_chart/static/src/fields/hr_org_chart.js
  addons/hr_recruitment/i18n/es.po
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/views/l10n_in_ewaybill_views.xml
  addons/mrp/i18n/fr.po
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/purchase/i18n/ja.po
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/i18n/nl.po
  addons/spreadsheet_dashboard_stock_account/i18n/fr.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/ja.po
  addons/stock/models/stock_picking.py
  addons/stock_account/i18n/fr.po
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/test_website/tests/test_restricted_editor.py
  addons/web/static/src/webclient/settings_form_view/settings/setting_header.js
  addons/web/static/src/webclient/settings_form_view/settings/setting_header.xml
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  addons/web_editor/i18n/es.po
  addons/website/models/ir_qweb.py
  addons/website_sale_stock/i18n/fr.po
  odoo/addons/base/i18n/zh_TW.po
Labels: staging.17.0

#35284 Syncing from upstream odoo/odoo (tmp.17.0)
  .tx/config
  .weblate.json
  addons/account/i18n/es_419.po
  addons/account/models/account_move.py
  addons/account_peppol/tools/demo_bill
  addons/hr_org_chart/static/src/fields/hr_org_chart.js
  addons/hr_recruitment/i18n/es.po
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es_modelo130/data/mod130.xml
  addons/l10n_in_edi/models/account_edi_format.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/views/l10n_in_ewaybill_views.xml
  addons/mrp/i18n/fr.po
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/purchase/i18n/ja.po
  addons/purchase/tests/test_purchase_invoice.py
  addons/sale/i18n/nl.po
  addons/spreadsheet_dashboard_stock_account/i18n/fr.po
  addons/stock/i18n/fr.po
  addons/stock/i18n/ja.po
  addons/stock/models/stock_picking.py
  addons/stock_account/i18n/fr.po
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/test_website/tests/test_restricted_editor.py
  addons/web/static/src/webclient/settings_form_view/settings/setting_header.js
  addons/web/static/src/webclient/settings_form_view/settings/setting_header.xml
  addons/web/static/tests/webclient/settings_form_view/settings_form_view_tests.js
  addons/web_editor/i18n/es.po
  addons/website/models/ir_qweb.py
  addons/website_sale_stock/i18n/fr.po
  odoo/addons/base/i18n/zh_TW.po
Labels: tmp.17.0

#35295 Syncing from upstream odoo/odoo (staging.saas-18.3)
  .tx/config
  .weblate.json
  addons/account/models/account_move.py
  addons/account/models/mail_message.py
  addons/account/models/res_partner_bank.py
  addons/account/tests/test_account_journal.py
  addons/account_peppol/tools/demo_bill
  addons/analytic/models/analytic_plan.py
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_mandatory_days.py
  addons/hr_org_chart/static/src/fields/hr_org_chart.js
  addons/hr_presence/static/src/search/hr_presence_cog_menu/hr_presence_cog_menu.js
  addons/html_editor/static/src/main/font/color_plugin.js
  addons/html_editor/static/src/main/media/icon_plugin.js
  addons/html_editor/static/tests/color.test.js
  addons/html_editor/static/tests/color_selector.test.js
  addons/html_editor/static/tests/icon.test.js
  addons/html_editor/static/tests/table/misc.test.js
  addons/l10n_it_edi/data/invoice_it_template.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_2.xml
  addons/l10n_it_edi/tests/export_xmls/bill_reverse_charge_san_marino.xml
  addons/l10n_it_edi/tests/export_xmls/credit_note_export_document_type.xml
  addons/l10n_it_edi/tests/export_xmls/credit_note_negative_price.xml
  addons/l10n_it_edi/tests/export_xmls/credit_note_refund_no_reconcile.xml
  addons/l10n_it_edi/tests/export_xmls/credit_note_reverse_charge.xml
  addons/l10n_it_edi/tests/export_xmls/invoice_exclude_postdated_moves.xml
  addons/l10n_it_edi/tests/export_xmls/split_payment_cn.xml
  addons/l10n_it_edi/tests/test_edi_reverse_charge.py
  addons/mail/models/discuss/discuss_channel_member.py
  addons/mail/models/res_users.py
  addons/mail/tests/discuss/test_discuss_channel.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.js
  addons/point_of_sale/static/tests/pos/tours/product_screen_tour.js
  addons/purchase/tests/test_purchase_invoice.py
  addons/survey/controllers/survey_session_manage.py
  addons/survey/tests/test_survey_controller.py
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/test_mail_activity_mixin.py
  addons/test_website/tests/template_qweb_test.xml
  addons/test_website/tests/test_qweb.py
  addons/test_website/tests/test_restricted_editor.py
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/src/webclient/settings_form_view/settings/setting_header.js
  addons/web/static/src/webclient/settings_form_view/settings/setting_header.xml
  addons/web/static/tests/views/fields/many2many_field.test.js
  addons/web/static/tests/webclient/settings_form_view/settings_form_view.test.js
  addons/website/models/ir_qweb.py
  addons/website_event_track/models/event_track.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/test_http/tests/test_static.py
  odoo/tests/test_module_operations.py
Labels: staging.saas-18.3

#35296 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/views/account_move_views.xml
Labels: staging.16.0

#35303 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/views/account_move_views.xml
Labels: tmp.16.0

#35306 Syncing from upstream odoo/odoo (16.0)
  odoo/addons/base/tests/test_views.py
  odoo/tests/common.py
  odoo/tools/template_inheritance.py
Labels: 16.0

#35307 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/my.po
  addons/mass_mailing/i18n/my.po
  addons/payment/i18n/my.po
  addons/point_of_sale/i18n/my.po
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_restaurant/i18n/my.po
  addons/project/i18n/ja.po
  addons/stock/i18n/zh_TW.po
  addons/web/i18n/zh_TW.po
  addons/website/i18n/it.po
  addons/website/i18n/my.po
  addons/website/i18n/zh_TW.po
  addons/website_event_track/i18n/ca.po
  addons/website_event_track_quiz/i18n/da.po
  addons/website_sale_stock/i18n/pt.po
  addons/website_sale_stock_wishlist/i18n/pt.po
  addons/website_slides_survey/i18n/my.po
  odoo/addons/base/i18n/my.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/models.py
  odoo/tests/common.py
Labels: 17.0

#35316 Syncing from upstream odoo/odoo (staging.16.0)
  odoo/addons/base/tests/test_views.py
  odoo/tests/common.py
  odoo/tools/template_inheritance.py
Labels: staging.16.0

#35323 Syncing from upstream odoo/odoo (tmp.16.0)
  odoo/addons/base/tests/test_views.py
  odoo/tests/common.py
  odoo/tools/template_inheritance.py
Labels: tmp.16.0

#35334 Syncing from upstream odoo/odoo (staging.saas-18.3)
  addons/account/models/account_move.py
  addons/account_debit_note/models/account_move.py
  addons/account_debit_note/wizard/account_debit_note.py
  addons/event/static/src/client_action/event_registration_summary_dialog.js
  addons/hr_attendance/views/hr_employee_view.xml
  addons/html_editor/static/src/others/collaboration/collaboration_odoo_plugin.js
  addons/html_editor/static/src/others/collaboration/collaboration_plugin.js
  addons/hw_drivers/driver.py
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/static/tests/sidebar_patch.test.js
  addons/im_livechat/tests/test_discuss_channel.py
  addons/l10n_ar/i18n/es_419.po
  addons/l10n_ar/i18n/l10n_ar.pot
  addons/l10n_latam_base/i18n/es_419.po
  addons/l10n_latam_base/i18n/l10n_latam_base.pot
  addons/l10n_latam_base/i18n/pt_BR.po
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/static/tests/crosstab/crosstab.test.js
  addons/mail/static/tests/discuss/call/call.test.js
  addons/mail/static/tests/discuss/core/web/discuss.test.js
  addons/mail/static/tests/discuss_app/sidebar.test.js
  addons/mail/static/tests/mail_test_helpers.js
  addons/mail/static/tests/message/message.test.js
  addons/mail/wizard/mail_activity_schedule_views.xml
  addons/pos_event/models/event_registration.py
  addons/pos_event/models/pos_session.py
  addons/pos_event/static/src/app/screens/product_screen/product_screen.js
  addons/project/static/tests/tours/project_task_history.js
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/purchase_stock/models/stock_valuation_layer.py
  addons/sale_mrp/tests/test_sale_mrp_anglo_saxon_valuation.py
  addons/sale_stock/models/__init__.py
  addons/sale_stock/models/stock_valuation_layer.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  addons/stock/models/stock_picking.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_delivery/tests/test_delivery_stock_move.py
  addons/web/static/src/views/fields/many2many_checkboxes/many2many_checkboxes_field.js
  addons/web/static/tests/views/fields/many2many_checkboxes_field.test.js
  addons/web/tests/test_ir_qweb.py
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/website/i18n/website.pot
  addons/website/models/res_config_settings.py
  doc/cla/corporate/tecnativa.md
  odoo/addons/base/models/ir_qweb_fields.py
  odoo/addons/base/tests/test_res_partner.py
  odoo/addons/base/tests/test_views.py
  odoo/orm/models.py
  odoo/tools/template_inheritance.py
Labels: staging.saas-18.3

#35336 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/my.po
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/res_config_settings.py
  addons/account_peppol/tests/test_peppol_participant.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/hr_fleet/models/fleet_vehicle_assignation_log.py
  addons/hr_fleet/tests/test_hr_fleet_driver.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/mass_mailing/i18n/my.po
  addons/mass_mailing_sms/models/mailing_trace.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/mrp_account/models/stock_move.py
  addons/payment/i18n/my.po
  addons/point_of_sale/i18n/my.po
  addons/pos_restaurant/i18n/my.po
  addons/project/i18n/ja.po
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/mail_notification.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/i18n/zh_TW.po
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
  addons/web/i18n/zh_TW.po
  addons/website/i18n/it.po
  addons/website/i18n/my.po
  addons/website/i18n/zh_TW.po
  addons/website_event_track/i18n/ca.po
  addons/website_event_track_quiz/i18n/da.po
  addons/website_sale_stock/i18n/pt.po
  addons/website_sale_stock_wishlist/i18n/pt.po
  addons/website_slides_survey/i18n/my.po
  odoo/addons/base/i18n/my.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: staging.17.0

#35342 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/my.po
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/res_config_settings.py
  addons/account_peppol/tests/test_peppol_participant.py
  addons/hr_fleet/models/fleet_vehicle.py
  addons/hr_fleet/models/fleet_vehicle_assignation_log.py
  addons/hr_fleet/tests/test_hr_fleet_driver.py
  addons/l10n_cl/models/account_move.py
  addons/l10n_es_edi_tbai/models/account_move.py
  addons/mass_mailing/i18n/my.po
  addons/mass_mailing_sms/models/mailing_trace.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/mrp_account/models/stock_move.py
  addons/payment/i18n/my.po
  addons/point_of_sale/i18n/my.po
  addons/pos_restaurant/i18n/my.po
  addons/project/i18n/ja.po
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/mail_notification.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/i18n/zh_TW.po
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
  addons/web/i18n/zh_TW.po
  addons/website/i18n/it.po
  addons/website/i18n/my.po
  addons/website/i18n/zh_TW.po
  addons/website_event_track/i18n/ca.po
  addons/website_event_track_quiz/i18n/da.po
  addons/website_sale_stock/i18n/pt.po
  addons/website_sale_stock_wishlist/i18n/pt.po
  addons/website_slides_survey/i18n/my.po
  odoo/addons/base/i18n/my.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: tmp.17.0

#35362 Syncing from upstream odoo/odoo (saas-18.3)
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mass_mailing_sms/models/mailing_trace.py
  addons/mass_mailing_sms/wizard/mailing_sms_test.py
  addons/sms/tests/common.py
  addons/sms/tools/sms_api.py
  addons/sms_twilio/models/__init__.py
  addons/sms_twilio/models/mail_notification.py
  addons/sms_twilio/models/sms_sms.py
  addons/sms_twilio/models/sms_twilio_number.py
  addons/sms_twilio/tests/common.py
  addons/sms_twilio/tests/test_sms_twilio.py
  addons/sms_twilio/tests/test_twilio_account_manage.py
  addons/sms_twilio/tools/sms_api.py
  addons/sms_twilio/tools/sms_twilio.py
  addons/sms_twilio/wizard/sms_twilio_account_manage.py
  addons/test_mass_mailing/tests/test_mailing_sms.py
  addons/test_mass_mailing/tests/test_mailing_test.py
  doc/cla/individual/dimaurosalvatore.md
Labels: saas-18.3

#35375 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/es_419.po
  addons/auth_totp/i18n/zh_CN.po
  addons/auth_totp_mail/i18n/zh_CN.po
  addons/calendar/i18n/es.po
  addons/event/i18n/es.po
  addons/hr_contract/i18n/vi.po
  addons/hr_holidays/i18n/fi.po
  addons/hr_recruitment/i18n/es.po
  addons/im_livechat/i18n/es.po
  addons/loyalty/i18n/es_419.po
  addons/mail/i18n/fr.po
  addons/mass_mailing/i18n/es.po
  addons/mass_mailing/i18n/zh_TW.po
  addons/mass_mailing_sms/i18n/es.po
  addons/mass_mailing_sms/i18n/es_419.po
  addons/mrp/i18n/es.po
  addons/point_of_sale/i18n/es_419.po
  addons/portal/static/src/signature_form/signature_form.js
  addons/pos_loyalty/i18n/es_419.po
  addons/pos_razorpay/i18n/zh_TW.po
  addons/project/i18n/es.po
  addons/rating/i18n/es.po
  addons/sale/i18n/es.po
  addons/sale_loyalty/i18n/es_419.po
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sms/i18n/es_419.po
  addons/sms/i18n/it.po
  addons/sms_twilio/i18n/es_419.po
  addons/sms_twilio/i18n/it.po
  addons/snailmail/i18n/zh_TW.po
  addons/survey/i18n/es.po
  addons/web/static/src/webclient/burger_menu/burger_menu.xml
  addons/web/static/src/webclient/burger_menu/burger_user_menu/burger_user_menu.js
  addons/web/static/src/webclient/burger_menu/burger_user_menu/burger_user_menu.xml
  addons/web/static/tests/mobile/webclient/burger_menu/burger_menu_tests.js
  addons/website/i18n/es.po
  addons/website/i18n/es_419.po
  addons/website_crm_partner_assign/i18n/es.po
  addons/website_hr_recruitment/i18n/es.po
  addons/website_livechat/i18n/es.po
  addons/website_sale/i18n/es.po
  addons/website_sale/i18n/es_419.po
  addons/website_slides/i18n/es.po
  doc/cla/corporate/AdvancedSystemsPuntoBit.md
  odoo/addons/base/i18n/es.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/zh_CN.po
  odoo/addons/base/i18n/zh_TW.po
  odoo/addons/base/tests/test_ir_attachment.py
  odoo/fields.py
Labels: 17.0

#35383 Syncing from upstream odoo/odoo (staging.saas-18.3)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_analytic.py
  addons/crm_livechat/static/tests/composer.test.js
  addons/crm_livechat/static/tests/message.test.js
  addons/google_address_autocomplete/static/tests/google_address_autocomplete.test.js
  addons/hr_fleet/models/fleet_vehicle.py
  addons/hr_fleet/models/fleet_vehicle_assignation_log.py
  addons/hr_fleet/tests/test_hr_fleet_driver.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/html_editor/static/tests/embedded_components.test.js
  addons/html_editor/static/tests/link/existing.test.js
  addons/im_livechat/static/tests/composer_patch.test.js
  addons/im_livechat/static/tests/mock_server/mock_models/livechat_channel_rule.js
  addons/l10n_ar/views/portal_address_templates.xml
  addons/l10n_es_edi_verifactu/views/account_move_views.xml
  addons/l10n_tr_nilvera_einvoice/data/cron.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_journal.py
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/l10n_tr_nilvera_einvoice/views/account_move_views.xml
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/discuss/core/composer.test.js
  addons/mail/static/tests/discuss/core/web/messaging_menu.test.js
  addons/mail/static/tests/message/message.test.js
  addons/mail/static/tests/thread/thread.test.js
  addons/mail/static/tests/web/fields/avatar.test.js
  addons/point_of_sale/static/src/app/screens/product_screen/order_summary/order_summary.js
  addons/point_of_sale/static/tests/unit/components/order_summary.test.js
  addons/point_of_sale/static/tests/unit/data/res_company.data.js
  addons/point_of_sale/static/tests/unit/data/res_country.data.js
  addons/point_of_sale/static/tests/unit/data/res_currency.data.js
  addons/pos_restaurant/static/tests/unit/services/pos_service.test.js
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock_multicompany.py
  addons/spreadsheet/static/tests/helpers/model.js
  addons/web/static/src/views/view_service.js
  addons/web/static/tests/_framework/mock_server/mock_models/@types/mock_models.d.ts
  addons/web/static/tests/core/action_swiper.test.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/views/view.test.js
  addons/web/static/tests/web_test_helpers.js
  addons/web/static/tests/webclient/res_user_group_ids_field.test.js
  addons/website/static/src/scss/website.scss
  addons/website_event/static/src/snippets/options.js
  addons/website_livechat/models/website_visitor.py
  addons/website_livechat/static/src/web/persona_model_patch.js
  addons/website_livechat/static/src/web/thread_patch.xml
  addons/website_livechat/static/tests/mock_server/mock_models/discuss_channel.js
  addons/website_livechat/static/tests/mock_server/mock_models/website_visitor.js
  addons/website_livechat/static/tests/thread_patch.test.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_sale_slides/data/product_data.xml
  addons/website_sale_wishlist/tests/test_wishlist_process.py
Labels: staging.saas-18.3

#35386 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/i18n/my.po
  addons/account_edi_ubl_cii/tools/ubl_21_credit_note.py
  addons/account_fleet/i18n/my.po
  addons/crm/i18n/my.po
  addons/delivery/i18n/my.po
  addons/fleet/i18n/my.po
  addons/hr/i18n/my.po
  addons/hr_expense/i18n/my.po
  addons/hr_fleet/models/fleet_vehicle.py
  addons/hr_fleet/models/fleet_vehicle_assignation_log.py
  addons/hr_fleet/tests/test_hr_fleet_driver.py
  addons/hr_skills/i18n/my.po
  addons/l10n_es_edi_tbai/models/l10n_es_edi_tbai_document.py
  addons/mail/i18n/my.po
  addons/mail/static/src/core/common/message.xml
  addons/maintenance/i18n/my.po
  addons/mrp/i18n/my.po
  addons/mrp_subcontracting_dropshipping/tests/test_sale_dropshipping.py
  addons/point_of_sale/i18n/my.po
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.xml
  addons/point_of_sale/static/tests/tours/utils/payment_screen_util.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/pos_hr/i18n/my.po
  addons/pos_restaurant/i18n/my.po
  addons/pos_restaurant/static/src/overrides/components/payment_screen/payment_screen.xml
  addons/product/i18n/my.po
  addons/purchase/i18n/my.po
  addons/repair/i18n/my.po
  addons/sale/i18n/my.po
  addons/sale_margin/i18n/my.po
  addons/sale_timesheet/i18n/my.po
  addons/stock/i18n/my.po
  addons/stock_account/i18n/my.po
  addons/stock_landed_costs/i18n/my.po
  addons/test_mail_full/static/tests/tours/message_actions_tour.js
  addons/web/i18n/my.po
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/date_field.test.js
  addons/website/static/src/components/translator/translator.js
  addons/website_sale/i18n/my.po
  odoo/addons/base/i18n/my.po
Labels: staging.18.0

#35389 Syncing from upstream odoo/odoo (tmp.saas-18.3)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_analytic.py
  addons/crm_livechat/static/tests/composer.test.js
  addons/crm_livechat/static/tests/message.test.js
  addons/google_address_autocomplete/static/tests/google_address_autocomplete.test.js
  addons/hr_fleet/models/fleet_vehicle.py
  addons/hr_fleet/models/fleet_vehicle_assignation_log.py
  addons/hr_fleet/tests/test_hr_fleet_driver.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/html_editor/static/tests/embedded_components.test.js
  addons/html_editor/static/tests/link/existing.test.js
  addons/im_livechat/static/tests/composer_patch.test.js
  addons/im_livechat/static/tests/mock_server/mock_models/livechat_channel_rule.js
  addons/l10n_ar/views/portal_address_templates.xml
  addons/l10n_es_edi_verifactu/views/account_move_views.xml
  addons/l10n_tr_nilvera_einvoice/data/cron.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_journal.py
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/l10n_tr_nilvera_einvoice/views/account_move_views.xml
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/mail/static/tests/discuss/core/composer.test.js
  addons/mail/static/tests/discuss/core/web/messaging_menu.test.js
  addons/mail/static/tests/message/message.test.js
  addons/mail/static/tests/thread/thread.test.js
  addons/mail/static/tests/web/fields/avatar.test.js
  addons/point_of_sale/static/src/app/screens/product_screen/order_summary/order_summary.js
  addons/point_of_sale/static/tests/unit/components/order_summary.test.js
  addons/point_of_sale/static/tests/unit/data/res_company.data.js
  addons/point_of_sale/static/tests/unit/data/res_country.data.js
  addons/point_of_sale/static/tests/unit/data/res_currency.data.js
  addons/pos_restaurant/static/tests/unit/services/pos_service.test.js
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock_multicompany.py
  addons/spreadsheet/static/tests/helpers/model.js
  addons/web/static/src/views/view_service.js
  addons/web/static/tests/_framework/mock_server/mock_models/@types/mock_models.d.ts
  addons/web/static/tests/core/action_swiper.test.js
  addons/web/static/tests/core/dropdown/dropdown.test.js
  addons/web/static/tests/views/view.test.js
  addons/web/static/tests/web_test_helpers.js
  addons/web/static/tests/webclient/res_user_group_ids_field.test.js
  addons/website/static/src/scss/website.scss
  addons/website_event/static/src/snippets/options.js
  addons/website_livechat/models/website_visitor.py
  addons/website_livechat/static/src/web/persona_model_patch.js
  addons/website_livechat/static/src/web/thread_patch.xml
  addons/website_livechat/static/tests/mock_server/mock_models/discuss_channel.js
  addons/website_livechat/static/tests/mock_server/mock_models/website_visitor.js
  addons/website_livechat/static/tests/thread_patch.test.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_sale_slides/data/product_data.xml
  addons/website_sale_wishlist/tests/test_wishlist_process.py
Labels: tmp.saas-18.3

#35395 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/__init__.py
  addons/account/models/kpi_provider.py
  addons/account/tests/__init__.py
  addons/account/tests/test_kpi_provider.py
  addons/base_setup/models/__init__.py
  addons/base_setup/models/kpi_provider.py
  addons/l10n_sa_edi/models/account_move.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
Labels: 16.0

#35396 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/__init__.py
  addons/account/models/kpi_provider.py
  addons/account/tests/__init__.py
  addons/account/tests/test_kpi_provider.py
  addons/barcodes_gs1_nomenclature/i18n/ko.po
  addons/base_setup/models/__init__.py
  addons/base_setup/models/kpi_provider.py
  addons/hr/i18n/da.po
  addons/im_livechat/controllers/chatbot.py
  addons/im_livechat/static/src/embed/common/chatbot/chatbot_service.js
  addons/im_livechat/static/src/embed/common/chatbot/chatbot_step_model.js
  addons/l10n_uy/__manifest__.py
  addons/mail/i18n/nl.po
  addons/mail/static/src/core/common/thread_service.js
  addons/mail/static/tests/discuss_app/discuss_tests.js
  addons/mass_mailing_sms/i18n/ko.po
  addons/payment/controllers/portal.py
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/helpers/ProductScreenTourMethods.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/website_event/i18n/ru.po
  addons/website_hr_recruitment/i18n/da.po
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_restore_state.js
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_sale/controllers/main.py
  addons/website_sale/views/templates.xml
  addons/website_sale_stock/tests/test_website_sale_stock_delivery.py
Labels: 17.0

#35400 Syncing from upstream odoo/odoo (saas-18.3)
  addons/account/data/mail_template_data.xml
  addons/account/models/__init__.py
  addons/account/models/account_payment.py
  addons/account/models/account_tax.py
  addons/account/models/chart_template.py
  addons/account/models/kpi_provider.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/__init__.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_kpi_provider.py
  addons/account/tests/test_taxes_downpayment.py
  addons/account/views/account_move_views.xml
  addons/account_edi_ubl_cii/tools/ubl_21_credit_note.py
  addons/auth_totp_mail/i18n/zh_CN.po
  addons/base_setup/models/__init__.py
  addons/base_setup/models/kpi_provider.py
  addons/delivery/models/__init__.py
  addons/delivery/models/ir_http.py
  addons/fleet/models/fleet_vehicle.py
  addons/hr/i18n/da.po
  addons/l10n_cl/models/account_move.py
  addons/l10n_es_edi_tbai/models/l10n_es_edi_tbai_document.py
  addons/l10n_in/tests/test_l10n_in_fiscal_position.py
  addons/l10n_in_sale/tests/test_l10n_in_sale_fiscal_position.py
  addons/mail/i18n/nl.po
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/point_of_sale/models/stock_warehouse.py
  addons/point_of_sale/tests/test_pos_stock_account.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_timesheet/i18n/da.po
  addons/sms_twilio/i18n/es.po
  addons/web/static/src/core/utils/indexed_db.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/tests/core/utils/indexed_db.test.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/snippets/s_floating_blocks/floating_blocks.edit.scss
  addons/website_event/views/event_templates_list.xml
  addons/website_event_exhibitor/views/event_exhibitor_templates_list.xml
  addons/website_event_track/views/event_track_templates_list.xml
  addons/website_forum/i18n/tr.po
  addons/website_hr_recruitment/i18n/da.po
  addons/website_livechat/i18n/da.po
  addons/website_partner/i18n/da.po
  odoo/addons/base/tests/test_ir_mail_server_smtpd.py
Labels: saas-18.3

#35405 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/__init__.py
  addons/account/models/kpi_provider.py
  addons/account/tests/__init__.py
  addons/account/tests/test_kpi_provider.py
  addons/base_setup/models/__init__.py
  addons/base_setup/models/kpi_provider.py
  addons/l10n_sa_edi/models/account_move.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
Labels: staging.16.0

#35412 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/__init__.py
  addons/account/models/kpi_provider.py
  addons/account/tests/__init__.py
  addons/account/tests/test_kpi_provider.py
  addons/base_setup/models/__init__.py
  addons/base_setup/models/kpi_provider.py
  addons/l10n_sa_edi/models/account_move.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
Labels: tmp.16.0

#35456 Syncing from upstream odoo/odoo (17.0)
  addons/crm_iap_mine/models/crm_iap_lead_helpers.py
  addons/hr_timesheet/__manifest__.py
  addons/hr_timesheet/security/hr_timesheet_security.xml
  addons/hr_timesheet/upgrades/1.1/pre-migrate.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_account_move_layout.xml
  addons/l10n_hu_edi/i18n/hu.po
  addons/l10n_hu_edi/i18n/l10n_hu_edi.pot
  addons/l10n_hu_edi/models/product.py
  addons/l10n_it/models/account_tax.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_withholding/data/template/account.tax-it.csv
  addons/l10n_it_edi_withholding/i18n/it.po
  addons/l10n_it_edi_withholding/i18n/l10n_it_edi_withholding.pot
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_tax.py
  addons/l10n_it_edi_withholding/tests/export_xmls/enasarco_tax_invoice.xml
  addons/l10n_it_edi_withholding/tests/test_withholding.py
  addons/loyalty/i18n/es_419.po
  addons/payment/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/sale/i18n/de.po
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/sms/i18n/es.po
  addons/sms_twilio/i18n/es.po
  addons/web/i18n/es_419.po
  addons/website/i18n/ca.po
  addons/website/i18n/es.po
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
  addons/website_event/controllers/main.py
  addons/website_forum/i18n/es_419.po
  odoo/tests/common.py
Labels: 17.0

#35466 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/crm_iap_mine/models/crm_iap_lead_helpers.py
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
Labels: staging.16.0

#35467 Syncing from upstream odoo/odoo (staging.17.0)
  addons/crm_iap_mine/models/crm_iap_lead_helpers.py
  addons/hr_timesheet/__manifest__.py
  addons/hr_timesheet/security/hr_timesheet_security.xml
  addons/hr_timesheet/upgrades/1.1/pre-migrate.py
  addons/l10n_din5008/models/account_move.py
  addons/l10n_din5008/report/din5008_account_move_layout.xml
  addons/l10n_hu_edi/i18n/hu.po
  addons/l10n_hu_edi/i18n/l10n_hu_edi.pot
  addons/l10n_hu_edi/models/product.py
  addons/l10n_it/models/account_tax.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_withholding/data/template/account.tax-it.csv
  addons/l10n_it_edi_withholding/i18n/it.po
  addons/l10n_it_edi_withholding/i18n/l10n_it_edi_withholding.pot
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_tax.py
  addons/l10n_it_edi_withholding/tests/export_xmls/enasarco_tax_invoice.xml
  addons/l10n_it_edi_withholding/tests/test_withholding.py
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
  addons/website_event/controllers/main.py
Labels: staging.17.0

#35474 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/crm_iap_mine/models/crm_iap_lead_helpers.py
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
Labels: tmp.16.0

#35478 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/account.pot
  addons/base_setup/i18n/base_setup.pot
  addons/mass_mailing_sms/i18n/mass_mailing_sms.pot
  addons/mrp_account/i18n/mrp_account.pot
  addons/sale_loyalty/i18n/sale_loyalty.pot
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/website_sale/i18n/website_sale.pot
Labels: 17.0

#35484 Syncing from upstream odoo/odoo (saas-18.4)
  addons/auth_totp/static/tests/totp_flow.js
  addons/product/i18n/ar.po
  addons/sms_twilio/i18n/ar.po
  addons/spreadsheet_dashboard_im_livechat/i18n/ar.po
  addons/website_livechat/i18n/ar.po
Labels: saas-18.4

#35489 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/loyalty/i18n/es_419.po
  addons/payment/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/sale/i18n/de.po
  addons/web/i18n/es_419.po
  addons/website/i18n/ca.po
  addons/website/i18n/es.po
  addons/website_forum/i18n/es_419.po
Labels: tmp.saas-18.2

#35490 Syncing from upstream odoo/odoo (tmp.saas-18.3)
  addons/account/i18n/account.pot
  addons/account_payment/models/payment_transaction.py
  addons/account_peppol/i18n/account_peppol.pot
  addons/auth_totp/static/tests/totp_flow.js
  addons/base_setup/i18n/base_setup.pot
  addons/delivery/i18n/delivery.pot
  addons/l10n_it_edi/tests/export_xmls/test_export_invoice_with_two_downpayments.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi_ndd_account_dn/data/invoice_it_template.xml
  addons/l10n_it_stock_ddt/tests/expected_xmls/deferred_invoice.xml
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/loyalty/i18n/es_419.po
  addons/mass_mailing_sms/i18n/mass_mailing_sms.pot
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/payment/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/sale/i18n/de.po
  addons/sale/models/sale_order.py
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/web/i18n/es_419.po
  addons/web_editor/i18n/web_editor.pot
  addons/website/i18n/ca.po
  addons/website/i18n/es.po
  addons/website_event/i18n/website_event.pot
  addons/website_event_exhibitor/i18n/website_event_exhibitor.pot
  addons/website_event_track/i18n/website_event_track.pot
  addons/website_forum/i18n/es_419.po
Labels: tmp.saas-18.3

#35494 Syncing from upstream odoo/odoo (18.0)
  addons/account/i18n/he.po
  addons/account/i18n/lv.po
  addons/point_of_sale/i18n/hu.po
  addons/sale_timesheet/i18n/he.po
  addons/website/i18n/he.po
Labels: 18.0

#35497 Syncing from upstream odoo/odoo (saas-18.3)
  addons/hr_timesheet/__manifest__.py
  addons/hr_timesheet/security/hr_timesheet_security.xml
  addons/hr_timesheet/upgrades/1.1/pre-migrate.py
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/static/src/app/components/orderline/orderline.js
  addons/point_of_sale/static/src/app/components/orderline/orderline.xml
  addons/point_of_sale/static/src/app/components/popups/combo_configurator_popup/combo_configurator_popup.js
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.js
  addons/point_of_sale/static/src/app/components/popups/product_configurator_popup/product_configurator_popup.xml
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/models/pos_order_line.js
  addons/point_of_sale/static/src/app/models/product_attribute_custom_value.js
  addons/point_of_sale/static/src/app/models/utils/compute_combo_items.js
  addons/point_of_sale/static/src/app/screens/product_screen/order_summary/order_summary.js
  addons/point_of_sale/static/src/app/screens/product_screen/order_summary/order_summary.xml
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/src/app/utils/use_timed_press.js
  addons/point_of_sale/static/tests/pos/tours/pos_combo_tour.js
  addons/point_of_sale/static/tests/pos/tours/pos_line_configurator_tour.js
  addons/point_of_sale/static/tests/pos/tours/product_configurator_tour.js
  addons/point_of_sale/static/tests/pos/tours/receipt_screen_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/combo_popup_util.js
  addons/point_of_sale/static/tests/pos/tours/utils/product_configurator_util.js
  addons/point_of_sale/static/tests/pos/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_restaurant/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/pos_self_order/__manifest__.py
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/views/fields/datetime/datetime_field.js
  addons/web/static/tests/views/fields/date_field.test.js
Labels: saas-18.3

#35501 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/account.pot
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/base_setup/i18n/base_setup.pot
  addons/loyalty/i18n/es_419.po
  addons/mass_mailing_sms/i18n/mass_mailing_sms.pot
  addons/mrp_account/i18n/mrp_account.pot
  addons/payment/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/sale/i18n/de.po
  addons/sale_loyalty/i18n/sale_loyalty.pot
  addons/sms/i18n/es.po
  addons/sms_twilio/i18n/es.po
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/web/i18n/es_419.po
  addons/website/i18n/ca.po
  addons/website/i18n/es.po
  addons/website_forum/i18n/es_419.po
  addons/website_sale/i18n/website_sale.pot
Labels: staging.17.0

#35506 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/account.pot
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/base_setup/i18n/base_setup.pot
  addons/loyalty/i18n/es_419.po
  addons/mass_mailing_sms/i18n/mass_mailing_sms.pot
  addons/mrp_account/i18n/mrp_account.pot
  addons/payment/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/sale/i18n/de.po
  addons/sale_loyalty/i18n/sale_loyalty.pot
  addons/sms/i18n/es.po
  addons/sms_twilio/i18n/es.po
  addons/sms_twilio/i18n/sms_twilio.pot
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/web/i18n/es_419.po
  addons/website/i18n/ca.po
  addons/website/i18n/es.po
  addons/website_forum/i18n/es_419.po
  addons/website_sale/i18n/website_sale.pot
Labels: tmp.17.0

#35513 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/i18n/de.po
  addons/account/i18n/es.po
  addons/account/i18n/es_419.po
  addons/account/i18n/it.po
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/account_peppol/i18n/de.po
  addons/account_peppol/i18n/es.po
  addons/account_peppol/i18n/es_419.po
  addons/account_peppol/i18n/it.po
  addons/base_setup/i18n/de.po
  addons/base_setup/i18n/es.po
  addons/base_setup/i18n/es_419.po
  addons/base_setup/i18n/it.po
  addons/event/data/mail_template_data.xml
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_overtime.py
  addons/l10n_din5008/report/din5008_account_move_layout.xml
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_it/data/template/account.tax-it.csv
  addons/mass_mailing_sms/i18n/de.po
  addons/mass_mailing_sms/i18n/es.po
  addons/mass_mailing_sms/i18n/es_419.po
  addons/mass_mailing_sms/i18n/it.po
  addons/mass_mailing_sms/i18n/zh_TW.po
  addons/payment/i18n/es_419.po
  addons/payment_razorpay/models/payment_provider.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/i18n/da.po
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/sms/i18n/zh_TW.po
  addons/sms_twilio/i18n/de.po
  addons/sms_twilio/i18n/es.po
  addons/sms_twilio/i18n/es_419.po
  addons/sms_twilio/i18n/it.po
  addons/sms_twilio/i18n/zh_TW.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/website/i18n/ca.po
  addons/website/models/website.py
  addons/website/tests/test_sitemap.py
  addons/website_crm_partner_assign/models/crm_lead.py
  addons/website_crm_partner_assign/security/ir.model.access.csv
  addons/website_crm_partner_assign/security/ir_rule.xml
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  addons/website_event/controllers/main.py
  addons/website_forum/i18n/es_419.po
  addons/website_forum/static/src/components/website_forum_tags_wrapper.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_forum/tests/test_forum_tours.py
  addons/website_sale/models/website.py
  odoo/addons/base/models/ir_qweb_fields.py
Labels: saas-18.2

#35517 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/event/data/mail_template_data.xml
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_overtime.py
  addons/l10n_din5008/report/din5008_account_move_layout.xml
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_it/data/template/account.tax-it.csv
  addons/payment_razorpay/models/payment_provider.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/website/models/website.py
  addons/website/tests/test_sitemap.py
  addons/website_crm_partner_assign/models/crm_lead.py
  addons/website_crm_partner_assign/security/ir.model.access.csv
  addons/website_crm_partner_assign/security/ir_rule.xml
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  addons/website_event/controllers/main.py
  addons/website_forum/static/src/components/website_forum_tags_wrapper.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_forum/tests/test_forum_tours.py
  addons/website_sale/models/website.py
  odoo/addons/base/models/ir_qweb_fields.py
Labels: staging.saas-18.2

#35519 Syncing from upstream odoo/odoo (staging.16.0)
  addons/hr_work_entry_holidays/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/sale_loyalty/models/sale_order.py
  addons/website_crm_partner_assign/models/crm_lead.py
  addons/website_crm_partner_assign/security/ir.model.access.csv
  addons/website_crm_partner_assign/security/ir_rule.xml
  addons/website_crm_partner_assign/tests/test_partner_assign.py
Labels: staging.16.0

#35524 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/event/data/mail_template_data.xml
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_overtime.py
  addons/l10n_din5008/report/din5008_account_move_layout.xml
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_it/data/template/account.tax-it.csv
  addons/payment_razorpay/models/payment_provider.py
  addons/project_timesheet_holidays/models/hr_holidays.py
  addons/project_timesheet_holidays/models/resource_calendar_leaves.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_extended.dark.scss
  addons/website/models/website.py
  addons/website/tests/test_sitemap.py
  addons/website_crm_partner_assign/models/crm_lead.py
  addons/website_crm_partner_assign/security/ir.model.access.csv
  addons/website_crm_partner_assign/security/ir_rule.xml
  addons/website_crm_partner_assign/tests/test_partner_assign.py
  addons/website_event/controllers/main.py
  addons/website_forum/static/src/components/website_forum_tags_wrapper.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  addons/website_forum/tests/test_forum_tours.py
  addons/website_sale/models/website.py
  odoo/addons/base/models/ir_qweb_fields.py
Labels: tmp.saas-18.2

#35527 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_work_entry_holidays/models/hr_contract.py
  addons/hr_work_entry_holidays/tests/test_work_entry.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/sale_loyalty/models/sale_order.py
  addons/website_crm_partner_assign/models/crm_lead.py
  addons/website_crm_partner_assign/security/ir.model.access.csv
  addons/website_crm_partner_assign/security/ir_rule.xml
  addons/website_crm_partner_assign/tests/test_partner_assign.py
Labels: tmp.16.0

#35532 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  odoo/tests/common.py
Labels: 16.0

#35533 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/zh_TW.po
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/mrp/i18n/vi.po
  addons/purchase/i18n/zh_TW.po
  addons/sale/i18n/zh_TW.po
  addons/sale_mrp/i18n/zh_TW.po
  addons/sale_stock/i18n/vi.po
  addons/sale_stock/i18n/zh_TW.po
  addons/spreadsheet/i18n/zh_TW.po
  addons/spreadsheet_dashboard_stock_account/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/survey/wizard/survey_invite.py
  addons/web/i18n/ca.po
  addons/web/static/src/views/calendar/calendar_common/calendar_common_renderer.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/website_sale_stock/i18n/vi.po
  doc/cla/corporate/quartile.md
  odoo/tests/common.py
Labels: 17.0

#35534 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/ir_actions_report.py
  addons/cloud_storage/models/ir_attachment.py
  addons/cloud_storage/models/ir_http.py
  addons/cloud_storage/static/src/core/common/attachment_upload_service_patch.js
  addons/hr_attendance/__manifest__.py
  addons/hr_attendance/static/src/components/kiosk_barcode/kiosk_barcode.js
  addons/hr_attendance/static/tests/hr_attendance_kiosk_barcode_scanner.test.js
  addons/hr_expense/models/ir_actions_report.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_L.py
  addons/l10n_account_withholding_tax/__init__.py
  addons/l10n_gcc_pos/tests/test_gcc_pos.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/models/res_partner.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/static/tests/tours/utils/generic_hooks.js
  addons/l10n_sa_edi_pos/tests/test_sa_edi_pos.py
  addons/l10n_sa_pos/tests/test_sa_pos.py
  addons/portal/static/src/signature_form/signature_form.js
  addons/sale_pdf_quote_builder/models/ir_actions_report.py
  doc/cla/corporate/AdvancedSystemsPuntoBit.md
  doc/cla/corporate/ahkio-consulting.md
  doc/cla/corporate/quartile.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_performance/tests/test_timeit.py
  odoo/tests/common.py
Labels: 18.0

#35537 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/i18n/zh_TW.po
  addons/account/models/account_move.py
  addons/account/tests/test_account_journal.py
  addons/hr_contract/models/hr_employee.py
  addons/hr_contract/tests/test_contract.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_L.py
  addons/im_livechat/i18n/zh_TW.po
  addons/l10n_es_edi_tbai_pos/models/pos_order.py
  addons/l10n_eu_oss/models/__init__.py
  addons/l10n_eu_oss/models/eu_field_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/loyalty/security/loyalty_security.xml
  addons/mail/i18n/zh_TW.po
  addons/mail/models/mail_mail.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_actions.js
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/tests/discuss_app/discuss.test.js
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/mail/static/tests/translation/translation.test.js
  addons/mrp/i18n/vi.po
  addons/portal/static/src/signature_form/signature_form.js
  addons/purchase/i18n/zh_TW.po
  addons/purchase/views/purchase_views.xml
  addons/sale/i18n/zh_TW.po
  addons/sale_loyalty/tests/test_program_multi_company.py
  addons/sale_mrp/i18n/zh_TW.po
  addons/sale_stock/i18n/vi.po
  addons/sale_stock/i18n/zh_TW.po
  addons/spreadsheet/i18n/zh_TW.po
  addons/spreadsheet/static/tests/helpers/data.js
  addons/spreadsheet/static/tests/helpers/list.js
  addons/spreadsheet_dashboard_stock_account/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/web/i18n/ca.po
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/tests/test_ui.py
  addons/website_sale/models/website.py
  addons/website_sale_stock/i18n/vi.po
  doc/cla/corporate/AdvancedSystemsPuntoBit.md
  doc/cla/corporate/ahkio-consulting.md
  doc/cla/corporate/quartile.md
  doc/cla/individual/tsezgin.md
  odoo/tests/common.py
Labels: saas-18.2

#35544 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  odoo/tests/common.py
Labels: staging.16.0

#35546 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/ir_actions_report.py
  addons/cloud_storage/models/ir_attachment.py
  addons/cloud_storage/models/ir_http.py
  addons/cloud_storage/static/src/core/common/attachment_upload_service_patch.js
  addons/hr_attendance/__manifest__.py
  addons/hr_attendance/static/src/components/kiosk_barcode/kiosk_barcode.js
  addons/hr_attendance/static/tests/hr_attendance_kiosk_barcode_scanner.test.js
  addons/hr_expense/models/ir_actions_report.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_L.py
  addons/l10n_account_withholding_tax/__init__.py
  addons/l10n_gcc_pos/tests/test_gcc_pos.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/models/res_partner.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/static/tests/tours/utils/generic_hooks.js
  addons/l10n_sa_edi_pos/tests/test_sa_edi_pos.py
  addons/l10n_sa_pos/tests/test_sa_pos.py
  addons/portal/static/src/signature_form/signature_form.js
  addons/sale_pdf_quote_builder/models/ir_actions_report.py
  doc/cla/corporate/AdvancedSystemsPuntoBit.md
  doc/cla/corporate/ahkio-consulting.md
  doc/cla/corporate/quartile.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_performance/tests/test_timeit.py
  odoo/tests/common.py
Labels: staging.18.0

#35551 Syncing from upstream odoo/odoo (tmp.saas-18.4)
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
  addons/google_calendar/models/calendar.py
  addons/hr_attendance/models/hr_attendance.py
  addons/iot_drivers/iot_handlers/drivers/printer_driver_L.py
  addons/l10n_es_edi_tbai_pos/models/pos_order.py
  addons/l10n_eu_oss/models/__init__.py
  addons/l10n_eu_oss/models/eu_field_map.py
  addons/l10n_eu_oss/models/res_company.py
  addons/l10n_eu_oss/tests/test_oss.py
  addons/l10n_it/data/template/account.tax-it.csv
  addons/loyalty/security/loyalty_security.xml
  addons/mail/models/mail_activity.py
  addons/mail/models/mail_mail.py
  addons/mail/static/tests/crosstab/crosstab.test.js
  addons/mail/static/tests/mock_server/mail_mock_server.js
  addons/mrp/models/stock_move.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_manual_consumption.py
  addons/mrp/tests/test_replenish.py
  addons/payment_razorpay/models/payment_provider.py
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/tests/unit/utils.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/signature_form/signature_form.js
  addons/pos_event/__manifest__.py
  addons/pos_event/static/tests/unit/components/event_configurator_popup.test.js
  addons/pos_event/static/tests/unit/components/event_registration_popup.test.js
  addons/pos_event/static/tests/unit/components/event_slot_selection_popup.test.js
  addons/pos_event/static/tests/unit/data/event_event.data.js
  addons/pos_event/static/tests/unit/data/event_event_ticket.data.js
  addons/pos_event/static/tests/unit/data/event_question.data.js
  addons/pos_event/static/tests/unit/data/event_question_answer.data.js
  addons/pos_event/static/tests/unit/data/event_slot.data.js
  addons/pos_event/static/tests/unit/data/pos_session.data.js
  addons/pos_event/static/tests/unit/data/product_product.data.js
  addons/pos_event/static/tests/unit/data/product_template.data.js
  addons/pos_event/static/tests/unit/services/pos_store.test.js
  addons/purchase_edi_ubl_bis3/models/purchase_edi_xml_ubl_bis3.py
  addons/sale_edi_ubl/models/sale_edi_xml_ubl_bis3.py
  addons/sale_loyalty/tests/test_program_multi_company.py
  addons/sale_mrp/tests/test_sale_mrp_lead_time.py
  addons/stock/models/product.py
  addons/stock/models/stock_move.py
  addons/test_mail/tests/test_mail_activity.py
  addons/website/models/website.py
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/tests/tours/link_tools.js
  addons/website/tests/test_sitemap.py
  addons/website/tests/test_ui.py
  addons/website_sale/models/website.py
  addons/website_sale/static/src/scss/website_sale_frontend.scss
  doc/cla/corporate/AdvancedSystemsPuntoBit.md
  doc/cla/corporate/quartile.md
  doc/cla/individual/tsezgin.md
Labels: tmp.saas-18.4

#35554 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/ir_actions_report.py
  addons/cloud_storage/models/ir_attachment.py
  addons/cloud_storage/models/ir_http.py
  addons/cloud_storage/static/src/core/common/attachment_upload_service_patch.js
  addons/hr_attendance/__manifest__.py
  addons/hr_attendance/static/src/components/kiosk_barcode/kiosk_barcode.js
  addons/hr_attendance/static/tests/hr_attendance_kiosk_barcode_scanner.test.js
  addons/hr_expense/models/ir_actions_report.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_L.py
  addons/l10n_account_withholding_tax/__init__.py
  addons/l10n_gcc_pos/tests/test_gcc_pos.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/models/res_partner.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_edi_pos/static/tests/tours/utils/generic_hooks.js
  addons/l10n_sa_edi_pos/tests/test_sa_edi_pos.py
  addons/l10n_sa_pos/tests/test_sa_pos.py
  addons/portal/static/src/signature_form/signature_form.js
  addons/sale_pdf_quote_builder/models/ir_actions_report.py
  doc/cla/corporate/AdvancedSystemsPuntoBit.md
  doc/cla/corporate/ahkio-consulting.md
  doc/cla/corporate/quartile.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_performance/tests/test_timeit.py
  odoo/tests/common.py
Labels: tmp.18.0

#35557 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/ko.po
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/account_peppol/i18n/ko.po
  addons/base_setup/i18n/ko.po
  addons/hr_recruitment/i18n/ko.po
  addons/mass_mailing_sms/i18n/ko.po
  addons/mrp/i18n/ko.po
  addons/mrp_subcontracting/i18n/ko.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/ko.po
  addons/sms_twilio/i18n/ko.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/pl.po
  addons/website/i18n/ko.po
  addons/website/i18n/pl.po
  addons/website_payment/i18n/zh_TW.po
  addons/website_slides/i18n/pl.po
  addons/website_slides_forum/i18n/pl.po
  odoo/addons/base/i18n/ko.po
  odoo/addons/base/i18n/pl.po
Labels: 17.0

#35563 Syncing from upstream odoo/odoo (saas-18.4)
  addons/account/models/account_move.py
  addons/account/models/account_payment.py
  addons/account/models/ir_actions_report.py
  addons/account/tests/test_account_journal.py
  addons/account/tests/test_account_payment.py
  addons/cloud_storage/models/ir_attachment.py
  addons/cloud_storage/models/ir_http.py
  addons/cloud_storage/static/src/core/common/attachment_upload_service_patch.js
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_overtime.py
  addons/hr_expense/models/ir_actions_report.py
  addons/hr_skills/i18n/ar.po
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hr_timesheet/tests/test_timesheet.py
  addons/html_builder/i18n/de.po
  addons/html_builder/static/src/core/building_blocks/builder_number_input.js
  addons/l10n_account_withholding_tax/__init__.py
  addons/l10n_hu_edi/i18n/hu.po
  addons/l10n_hu_edi/i18n/l10n_hu_edi.pot
  addons/l10n_hu_edi/models/product.py
  addons/l10n_my_edi/models/res_company.py
  addons/l10n_my_edi/models/res_partner.py
  addons/l10n_ph/data/template/account.fiscal.position-ph.csv
  addons/l10n_ph/data/template/account.tax-ph.csv
  addons/mail/static/src/core/common/chat_hub.xml
  addons/mail/static/tests/chat_bubble/chat_bubble.test.js
  addons/project/models/project_project.py
  addons/project/tests/test_project_template.py
  addons/purchase/__manifest__.py
  addons/purchase/models/purchase_order.py
  addons/purchase/static/src/product_catalog/kanban_record.js
  addons/purchase/static/tests/tours/purchase_product_catalog.js
  addons/purchase/static/tests/tours/tour_step_utils.js
  addons/purchase/tests/test_purchase_product_catalog.py
  addons/purchase/views/purchase_views.xml
  addons/sms_twilio/i18n/pt_BR.po
  addons/web/i18n/da.po
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/fields/many2one/many2one.xml
  addons/web/static/tests/views/fields/many2one_field.test.js
  addons/website/i18n/de.po
  addons/website/static/src/builder/plugins/options/progress_bar_option.xml
  addons/website/static/tests/builder/custom_tab/builder_components/builder_number_input.test.js
  addons/website_payment/i18n/zh_TW.po
  addons/website_sale/models/website.py
  doc/cla/corporate/ahkio-consulting.md
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/tests/common.py
Labels: saas-18.4

#35576 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
Labels: tmp.16.0

#35577 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/zh_TW.po
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/mrp/i18n/vi.po
  addons/purchase/i18n/zh_TW.po
  addons/sale/i18n/zh_TW.po
  addons/sale_mrp/i18n/zh_TW.po
  addons/sale_stock/i18n/vi.po
  addons/sale_stock/i18n/zh_TW.po
  addons/spreadsheet/i18n/zh_TW.po
  addons/spreadsheet_dashboard_stock_account/i18n/vi.po
  addons/stock/i18n/vi.po
  addons/web/i18n/ca.po
  addons/website_sale_stock/i18n/vi.po
Labels: tmp.17.0

#35580 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/ja.po
  addons/hr_recruitment/i18n/es_419.po
  addons/phone_validation/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/project/i18n/es_419.po
  addons/purchase/i18n/ja.po
  addons/sale/i18n/ja.po
  addons/sale_loyalty/models/sale_order.py
  addons/sms/i18n/es_419.po
Labels: 17.0

#35584 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/project/i18n/es_419.po
  addons/sale/i18n/es_419.po
  addons/sale_loyalty/models/sale_order.py
  addons/sms/i18n/es_419.po
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  odoo/addons/base/i18n/es_419.po
Labels: saas-18.2

#35585 Syncing from upstream odoo/odoo (saas-18.3)
  addons/account/i18n/es_419.po
  addons/account/models/ir_actions_report.py
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/calendar/i18n/es_419.po
  addons/fleet/i18n/es_419.po
  addons/hr_expense/models/ir_actions_report.py
  addons/hr_recruitment/i18n/es_419.po
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/mail/i18n/es_419.po
  addons/marketing_card/i18n/es_419.po
  addons/mass_mailing/i18n/es_419.po
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/project/i18n/es_419.po
  addons/sale/i18n/es_419.po
  addons/sale_loyalty/models/sale_order.py
  addons/sms/i18n/es_419.po
  addons/survey/i18n/es_419.po
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/website_slides/i18n/es_419.po
  addons/website_slides/models/slide_channel.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_attachment.py
  odoo/addons/test_performance/tests/test_timeit.py
Labels: saas-18.3

#35586 Syncing from upstream odoo/odoo (saas-18.4)
  addons/account/i18n/ja.po
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/im_livechat/models/discuss_channel.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/point_of_sale/i18n/ja.po
  addons/project/i18n/es_419.po
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase/i18n/ja.po
  addons/sale_loyalty/models/sale_order.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/website/i18n/es_419.po
  addons/website_slides/models/slide_channel_partner.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/i18n/es_419.po
  odoo/addons/test_orm/tests/test_timeit.py
Labels: saas-18.4

#35590 Syncing from upstream odoo/odoo (staging.saas-18.4)
  addons/account/models/kpi_provider.py
  addons/account/models/product.py
  addons/account/tests/test_kpi_provider.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/im_livechat/models/discuss_channel.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale_loyalty/models/sale_order.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/copyPaste.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/htmlTables.test.js
  addons/website_slides/models/slide_channel_partner.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/test_orm/tests/test_timeit.py
Labels: staging.saas-18.4

#35591 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/ko.po
  addons/account_peppol/i18n/ko.po
  addons/base_setup/i18n/ko.po
  addons/hr_recruitment/i18n/ko.po
  addons/mass_mailing_sms/i18n/ko.po
  addons/mrp/i18n/ko.po
  addons/mrp_subcontracting/i18n/ko.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/ko.po
  addons/sale_loyalty/models/sale_order.py
  addons/sms_twilio/i18n/ko.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/pl.po
  addons/website/i18n/ko.po
  addons/website/i18n/pl.po
  addons/website_payment/i18n/zh_TW.po
  addons/website_slides/i18n/pl.po
  addons/website_slides_forum/i18n/pl.po
  odoo/addons/base/i18n/ko.po
  odoo/addons/base/i18n/pl.po
Labels: staging.17.0

#35592 Syncing from upstream odoo/odoo (staging.18.0)
  addons/sale_loyalty/models/sale_order.py
  odoo/addons/test_performance/tests/test_performance.py
  odoo/models.py
Labels: staging.18.0

#35595 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account/models/kpi_provider.py
  addons/account/tests/test_kpi_provider.py
  addons/account_edi_ubl_cii/i18n/ko.po
  addons/marketing_card/i18n/ko.po
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mass_mailing_sms/i18n/ko.po
  addons/point_of_sale/i18n/ko.po
  addons/portal_rating/i18n/ko.po
  addons/sale_loyalty/models/sale_order.py
  addons/sms/i18n/ko.po
  addons/sms_twilio/i18n/ko.po
  addons/survey/wizard/survey_invite.py
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  addons/web_editor/i18n/ar.po
  addons/web_editor/i18n/ca.po
  addons/web_editor/i18n/cs.po
  addons/web_editor/i18n/da.po
  addons/web_editor/i18n/de.po
  addons/web_editor/i18n/el.po
  addons/web_editor/i18n/es.po
  addons/web_editor/i18n/es_419.po
  addons/web_editor/i18n/fa.po
  addons/web_editor/i18n/fi.po
  addons/web_editor/i18n/fr.po
  addons/web_editor/i18n/he.po
  addons/web_editor/i18n/hi.po
  addons/web_editor/i18n/hr.po
  addons/web_editor/i18n/hu.po
  addons/web_editor/i18n/id.po
  addons/web_editor/i18n/it.po
  addons/web_editor/i18n/ja.po
  addons/web_editor/i18n/ko.po
  addons/web_editor/i18n/ku.po
  addons/web_editor/i18n/lt.po
  addons/web_editor/i18n/mn.po
  addons/web_editor/i18n/my.po
  addons/web_editor/i18n/nb.po
  addons/web_editor/i18n/nl.po
  addons/web_editor/i18n/pl.po
  addons/web_editor/i18n/pt.po
  addons/web_editor/i18n/pt_BR.po
  addons/web_editor/i18n/ro.po
  addons/web_editor/i18n/ru.po
  addons/web_editor/i18n/sl.po
  addons/web_editor/i18n/sr@latin.po
  addons/web_editor/i18n/sv.po
  addons/web_editor/i18n/th.po
  addons/web_editor/i18n/tr.po
  addons/web_editor/i18n/uk.po
  addons/web_editor/i18n/vi.po
  addons/web_editor/i18n/zh_CN.po
  addons/web_editor/i18n/zh_TW.po
  addons/website_payment/i18n/zh_TW.po
Labels: tmp.saas-18.2

#35601 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/he.po
  addons/delivery/i18n/ja.po
  addons/phone_validation/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/project/i18n/es_419.po
  addons/sms/i18n/es_419.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: 17.0

#35602 Syncing from upstream odoo/odoo (18.0)
  addons/point_of_sale/i18n/my.po
  addons/sale/i18n/ja.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: 18.0

#35604 Syncing from upstream odoo/odoo (master)
  .github/ISSUE_TEMPLATE/1_bug_form.yml
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/static/tests/embed/message_actions.test.js
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/message_reactions.js
  addons/mail/static/src/core/common/message_reactions.xml
  addons/mail/static/src/core/common/quick_reaction_menu.js
  addons/mail/static/src/core/common/quick_reaction_menu.scss
  addons/mail/static/src/core/common/quick_reaction_menu.xml
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/call/common/call.js
  addons/mail/static/src/discuss/call/common/meeting.js
  addons/mail/static/src/discuss/call/common/meeting.xml
  addons/mail/static/src/discuss/call/common/meeting_chat.xml
  addons/mail/static/src/discuss/call/common/pip_service.js
  addons/mail/static/src/utils/common/hooks.js
  addons/mail/static/tests/message/message.test.js
  addons/stock/models/product.py
  addons/stock/static/src/fields/stock_move_line_x2_many_field.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale/static/src/interactions/quick_reorder.js
  addons/website_sale/static/src/js/website_sale_utils.js
  addons/website_sale/views/product_tile_templates.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  addons/website_sale_comparison_wishlist/views/templates.xml
  addons/website_sale_stock_wishlist/static/src/xml/product_availability.xml
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  addons/website_slides/models/slide_channel_partner.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/test_orm/tests/test_timeit.py
Labels: master

#35605 Syncing from upstream odoo/odoo (saas-18.2)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  odoo/addons/base/i18n/es_419.po
  odoo/addons/test_performance/tests/test_performance.py
  odoo/orm/models.py
Labels: saas-18.2

#35606 Syncing from upstream odoo/odoo (saas-18.3)
  addons/hr_attendance/__manifest__.py
  addons/hr_attendance/static/src/components/kiosk_barcode/kiosk_barcode.js
  addons/hr_attendance/static/tests/hr_attendance_kiosk_barcode_scanner.test.js
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/tests/composer/composer.test.js
  addons/mrp_account/models/stock_move.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/resource/i18n/pl.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  odoo/addons/base/i18n/es_419.po
  odoo/addons/test_performance/tests/test_performance.py
  odoo/orm/models.py
Labels: saas-18.3

#35607 Syncing from upstream odoo/odoo (saas-18.4)
  addons/account/models/product.py
  addons/mrp_account/models/stock_move.py
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/sale/i18n/ja.po
  addons/snailmail_account/i18n/ja.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
  odoo/addons/test_orm/tests/test_performance.py
  odoo/orm/models.py
Labels: saas-18.4

#35608 Syncing from upstream odoo/odoo (staging.master)
  .github/ISSUE_TEMPLATE/1_bug_form.yml
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/static/tests/embed/message_actions.test.js
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/message_reactions.js
  addons/mail/static/src/core/common/message_reactions.xml
  addons/mail/static/src/core/common/quick_reaction_menu.js
  addons/mail/static/src/core/common/quick_reaction_menu.scss
  addons/mail/static/src/core/common/quick_reaction_menu.xml
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/call/common/call.js
  addons/mail/static/src/discuss/call/common/meeting.js
  addons/mail/static/src/discuss/call/common/meeting.xml
  addons/mail/static/src/discuss/call/common/meeting_chat.xml
  addons/mail/static/src/discuss/call/common/pip_service.js
  addons/mail/static/src/utils/common/hooks.js
  addons/mail/static/tests/message/message.test.js
  addons/stock/models/product.py
  addons/stock/static/src/fields/stock_move_line_x2_many_field.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale/static/src/interactions/quick_reorder.js
  addons/website_sale/static/src/js/website_sale_utils.js
  addons/website_sale/views/product_tile_templates.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  addons/website_sale_comparison_wishlist/views/templates.xml
  addons/website_sale_stock_wishlist/static/src/xml/product_availability.xml
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  addons/website_slides/models/slide_channel_partner.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/test_orm/tests/test_timeit.py
Labels: staging.master

#35609 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/project/i18n/es_419.po
  addons/sale/i18n/es_419.po
  addons/sms/i18n/es_419.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  odoo/addons/base/i18n/es_419.po
  odoo/addons/test_performance/tests/test_performance.py
  odoo/orm/models.py
Labels: staging.saas-18.2

#35610 Syncing from upstream odoo/odoo (staging.saas-18.3)
  addons/account/i18n/es_419.po
  addons/calendar/i18n/es_419.po
  addons/fleet/i18n/es_419.po
  addons/hr_attendance/__manifest__.py
  addons/hr_attendance/static/src/components/kiosk_barcode/kiosk_barcode.js
  addons/hr_attendance/static/tests/hr_attendance_kiosk_barcode_scanner.test.js
  addons/hr_recruitment/i18n/es_419.po
  addons/mail/i18n/es_419.po
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/tests/composer/composer.test.js
  addons/marketing_card/i18n/es_419.po
  addons/mass_mailing/i18n/es_419.po
  addons/mrp_account/models/stock_move.py
  addons/project/i18n/es_419.po
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/sale/i18n/es_419.po
  addons/sms/i18n/es_419.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  addons/survey/i18n/es_419.po
  addons/website_slides/i18n/es_419.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/test_performance/tests/test_performance.py
  odoo/orm/models.py
Labels: staging.saas-18.3

#35615 Syncing from upstream odoo/odoo (tmp.master)
  .github/ISSUE_TEMPLATE/1_bug_form.yml
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/static/tests/embed/message_actions.test.js
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/core/common/message_reactions.js
  addons/mail/static/src/core/common/message_reactions.xml
  addons/mail/static/src/core/common/quick_reaction_menu.js
  addons/mail/static/src/core/common/quick_reaction_menu.scss
  addons/mail/static/src/core/common/quick_reaction_menu.xml
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/discuss/call/common/call.js
  addons/mail/static/src/discuss/call/common/meeting.js
  addons/mail/static/src/discuss/call/common/meeting.xml
  addons/mail/static/src/discuss/call/common/meeting_chat.xml
  addons/mail/static/src/discuss/call/common/pip_service.js
  addons/mail/static/src/utils/common/hooks.js
  addons/mail/static/tests/message/message.test.js
  addons/stock/models/product.py
  addons/stock/static/src/fields/stock_move_line_x2_many_field.js
  addons/web/static/src/views/calendar/calendar_year/calendar_year_renderer.js
  addons/web/static/tests/views/calendar/calendar_year_renderer.test.js
  addons/website_sale/data/product_snippet_template_data.xml
  addons/website_sale/static/src/interactions/quick_reorder.js
  addons/website_sale/static/src/js/website_sale_utils.js
  addons/website_sale/views/product_tile_templates.xml
  addons/website_sale/views/templates.xml
  addons/website_sale_comparison/views/website_sale_comparison_template.xml
  addons/website_sale_comparison_wishlist/views/templates.xml
  addons/website_sale_stock_wishlist/static/src/xml/product_availability.xml
  addons/website_sale_wishlist/models/product_wishlist.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  addons/website_slides/models/slide_channel_partner.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/test_orm/tests/test_timeit.py
Labels: tmp.master

#35617 Syncing from upstream odoo/odoo (tmp.saas-18.3)
  addons/account/i18n/es_419.po
  addons/calendar/i18n/es_419.po
  addons/fleet/i18n/es_419.po
  addons/hr_attendance/__manifest__.py
  addons/hr_attendance/static/src/components/kiosk_barcode/kiosk_barcode.js
  addons/hr_attendance/static/tests/hr_attendance_kiosk_barcode_scanner.test.js
  addons/hr_recruitment/i18n/es_419.po
  addons/mail/i18n/es_419.po
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/tests/composer/composer.test.js
  addons/marketing_card/i18n/es_419.po
  addons/mass_mailing/i18n/es_419.po
  addons/mrp_account/models/stock_move.py
  addons/project/i18n/es_419.po
  addons/purchase_mrp/tests/test_anglo_saxon_valuation.py
  addons/sale/i18n/es_419.po
  addons/sms/i18n/es_419.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  addons/survey/i18n/es_419.po
  addons/website_slides/i18n/es_419.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/test_performance/tests/test_performance.py
  odoo/orm/models.py
Labels: tmp.saas-18.3

#35619 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/ja.po
  addons/hr_recruitment/i18n/es_419.po
  addons/phone_validation/i18n/es_419.po
  addons/pos_loyalty/i18n/es_419.po
  addons/project/i18n/es_419.po
  addons/purchase/i18n/ja.po
  addons/sale/i18n/ja.po
  addons/sms/i18n/es_419.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.17.0

#35622 Syncing from upstream odoo/odoo (17.0)
  addons/website_crm_partner_assign/i18n/ar.po
  addons/website_crm_partner_assign/i18n/az.po
  addons/website_crm_partner_assign/i18n/ca.po
  addons/website_crm_partner_assign/i18n/cs.po
  addons/website_crm_partner_assign/i18n/da.po
  addons/website_crm_partner_assign/i18n/de.po
  addons/website_crm_partner_assign/i18n/el.po
  addons/website_crm_partner_assign/i18n/es.po
  addons/website_crm_partner_assign/i18n/es_419.po
  addons/website_crm_partner_assign/i18n/fa.po
  addons/website_crm_partner_assign/i18n/fi.po
  addons/website_crm_partner_assign/i18n/fr.po
  addons/website_crm_partner_assign/i18n/he.po
  addons/website_crm_partner_assign/i18n/hi.po
  addons/website_crm_partner_assign/i18n/hr.po
  addons/website_crm_partner_assign/i18n/hu.po
  addons/website_crm_partner_assign/i18n/id.po
  addons/website_crm_partner_assign/i18n/it.po
  addons/website_crm_partner_assign/i18n/ja.po
  addons/website_crm_partner_assign/i18n/ko.po
  addons/website_crm_partner_assign/i18n/ku.po
  addons/website_crm_partner_assign/i18n/lt.po
  addons/website_crm_partner_assign/i18n/mn.po
  addons/website_crm_partner_assign/i18n/my.po
  addons/website_crm_partner_assign/i18n/nb.po
  addons/website_crm_partner_assign/i18n/nl.po
  addons/website_crm_partner_assign/i18n/pl.po
  addons/website_crm_partner_assign/i18n/pt.po
  addons/website_crm_partner_assign/i18n/pt_BR.po
  addons/website_crm_partner_assign/i18n/ro.po
  addons/website_crm_partner_assign/i18n/ru.po
  addons/website_crm_partner_assign/i18n/sl.po
  addons/website_crm_partner_assign/i18n/sr@latin.po
  addons/website_crm_partner_assign/i18n/sv.po
  addons/website_crm_partner_assign/i18n/th.po
  addons/website_crm_partner_assign/i18n/tr.po
  addons/website_crm_partner_assign/i18n/uk.po
  addons/website_crm_partner_assign/i18n/vi.po
  addons/website_crm_partner_assign/i18n/website_crm_partner_assign.pot
  addons/website_crm_partner_assign/i18n/zh_CN.po
  addons/website_crm_partner_assign/i18n/zh_TW.po
Labels: 17.0

#35624 Syncing from upstream odoo/odoo (19.0)
  addons/event/i18n/ko.po
  addons/loyalty/i18n/ko.po
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.xml
  addons/mail/static/tests/composer/composer.test.js
  addons/sale_stock/i18n/ko.po
  odoo/addons/base/i18n/ko.po
Labels: 19.0

#35625 Syncing from upstream odoo/odoo (master)
  addons/im_livechat/static/src/core/common/thread_patch.xml
  addons/l10n_it/data/template/account.tax-it.csv
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/public_web/discuss_content.js
  addons/mail/static/src/core/public_web/discuss_content.xml
  addons/mail/static/src/core/public_web/notification_item.xml
  addons/mail/static/src/discuss/core/public_web/message_patch.js
  addons/mail/static/src/discuss/core/public_web/message_patch.xml
  addons/mail/static/src/discuss/core/public_web/sub_channel_list.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_list.xml
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.scss
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.xml
  addons/mail/static/tests/composer/composer.test.js
  addons/mail/static/tests/discuss/core/public_web/sub_channels.test.js
  addons/mail/static/tests/quick_reaction_menu/quick_reaction_menu.test.js
  addons/mail/static/tests/tours/discuss_sub_channel_search_tour.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/website_livechat/static/src/web/discuss_content_patch.js
  addons/website_livechat/static/src/web/livechat_channel_info_list_patch.js
  addons/website_livechat/static/src/web/livechat_channel_info_list_patch.xml
  addons/website_livechat/static/src/web/thread_patch.js
  addons/website_livechat/static/src/web/thread_patch.scss
  addons/website_livechat/static/src/web/thread_patch.xml
  addons/website_livechat/static/tests/discuss_content_patch.test.js
  addons/website_livechat/static/tests/livechat_channel_info_list_patch.test.js
  addons/website_livechat/static/tests/thread_patch.test.js
  odoo/addons/test_orm/tests/test_performance.py
  odoo/orm/models.py
Labels: master

#35628 Syncing from upstream odoo/odoo (saas-18.4)
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/tests/composer/composer.test.js
Labels: saas-18.4

#35629 Syncing from upstream odoo/odoo (staging.master)
  addons/im_livechat/static/src/core/common/thread_patch.xml
  addons/l10n_it/data/template/account.tax-it.csv
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/public_web/discuss_content.js
  addons/mail/static/src/core/public_web/discuss_content.xml
  addons/mail/static/src/core/public_web/notification_item.xml
  addons/mail/static/src/discuss/core/public_web/message_patch.js
  addons/mail/static/src/discuss/core/public_web/message_patch.xml
  addons/mail/static/src/discuss/core/public_web/sub_channel_list.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_list.xml
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.scss
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.xml
  addons/mail/static/tests/composer/composer.test.js
  addons/mail/static/tests/discuss/core/public_web/sub_channels.test.js
  addons/mail/static/tests/quick_reaction_menu/quick_reaction_menu.test.js
  addons/mail/static/tests/tours/discuss_sub_channel_search_tour.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/website_livechat/static/src/web/discuss_content_patch.js
  addons/website_livechat/static/src/web/livechat_channel_info_list_patch.js
  addons/website_livechat/static/src/web/livechat_channel_info_list_patch.xml
  addons/website_livechat/static/src/web/thread_patch.js
  addons/website_livechat/static/src/web/thread_patch.scss
  addons/website_livechat/static/src/web/thread_patch.xml
  addons/website_livechat/static/tests/discuss_content_patch.test.js
  addons/website_livechat/static/tests/livechat_channel_info_list_patch.test.js
  addons/website_livechat/static/tests/thread_patch.test.js
  odoo/addons/test_orm/tests/test_performance.py
  odoo/orm/models.py
Labels: staging.master

#35630 Syncing from upstream odoo/odoo (staging.saas-18.3)
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_actions.js
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/tests/discuss_app/discuss.test.js
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/mail/static/tests/translation/translation.test.js
  addons/resource/i18n/pl.po
  odoo/addons/base/i18n/es_419.po
Labels: staging.saas-18.3

#35631 Syncing from upstream odoo/odoo (staging.saas-18.4)
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/tests/composer/composer.test.js
  addons/sale/i18n/ja.po
  addons/snailmail_account/i18n/ja.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: staging.saas-18.4

#35633 Syncing from upstream odoo/odoo (tmp.master)
  addons/im_livechat/static/src/core/common/thread_patch.xml
  addons/l10n_it/data/template/account.tax-it.csv
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/public_web/discuss_content.js
  addons/mail/static/src/core/public_web/discuss_content.xml
  addons/mail/static/src/core/public_web/notification_item.xml
  addons/mail/static/src/discuss/core/public_web/message_patch.js
  addons/mail/static/src/discuss/core/public_web/message_patch.xml
  addons/mail/static/src/discuss/core/public_web/sub_channel_list.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_list.xml
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.js
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.scss
  addons/mail/static/src/discuss/core/public_web/sub_channel_preview.xml
  addons/mail/static/tests/composer/composer.test.js
  addons/mail/static/tests/discuss/core/public_web/sub_channels.test.js
  addons/mail/static/tests/quick_reaction_menu/quick_reaction_menu.test.js
  addons/mail/static/tests/tours/discuss_sub_channel_search_tour.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/website_livechat/static/src/web/discuss_content_patch.js
  addons/website_livechat/static/src/web/livechat_channel_info_list_patch.js
  addons/website_livechat/static/src/web/livechat_channel_info_list_patch.xml
  addons/website_livechat/static/src/web/thread_patch.js
  addons/website_livechat/static/src/web/thread_patch.scss
  addons/website_livechat/static/src/web/thread_patch.xml
  addons/website_livechat/static/tests/discuss_content_patch.test.js
  addons/website_livechat/static/tests/livechat_channel_info_list_patch.test.js
  addons/website_livechat/static/tests/thread_patch.test.js
  odoo/addons/test_orm/tests/test_performance.py
  odoo/orm/models.py
Labels: tmp.master

#35634 Syncing from upstream odoo/odoo (tmp.saas-18.3)
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_actions.js
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/tests/discuss_app/discuss.test.js
  addons/mail/static/tests/discuss_app/inbox.test.js
  addons/mail/static/tests/translation/translation.test.js
  addons/resource/i18n/pl.po
  odoo/addons/base/i18n/es_419.po
Labels: tmp.saas-18.3

#35635 Syncing from upstream odoo/odoo (tmp.saas-18.4)
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/tests/composer/composer.test.js
  addons/sale/i18n/ja.po
  addons/snailmail_account/i18n/ja.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: tmp.saas-18.4

#35637 Syncing from upstream odoo/odoo (master)
  addons/website_payment/controllers/portal.py
  addons/website_payment/static/src/snippets/s_supported_payment_methods/supported_payment_methods.js
  addons/website_payment/static/src/website_builder/supported_payment_methods_option_plugin.js
  addons/website_payment/views/snippets/s_supported_payment_methods.xml
Labels: master

#35644 Syncing from upstream odoo/odoo (staging.19.0)
  addons/event/i18n/ko.po
  addons/loyalty/i18n/ko.po
  addons/sale_stock/i18n/ko.po
  odoo/addons/base/i18n/ko.po
Labels: staging.19.0

#35645 Syncing from upstream odoo/odoo (tmp.master)
  addons/website_payment/controllers/portal.py
  addons/website_payment/static/src/snippets/s_supported_payment_methods/supported_payment_methods.js
  addons/website_payment/static/src/website_builder/supported_payment_methods_option_plugin.js
  addons/website_payment/views/snippets/s_supported_payment_methods.xml
Labels: tmp.master

#35648 Syncing from upstream odoo/odoo (tmp.19.0)
  addons/event/i18n/ko.po
  addons/loyalty/i18n/ko.po
  addons/sale_stock/i18n/ko.po
  odoo/addons/base/i18n/ko.po
Labels: tmp.19.0

#35674 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/es_419.po
  addons/account/i18n/ja.po
  addons/account_check_printing/i18n/lt.po
  addons/account_edi_proxy_client/i18n/lt.po
  addons/base_import/i18n/es_419.po
  addons/crm/i18n/es_419.po
  addons/crm_livechat/i18n/es_419.po
  addons/digest/i18n/zh_TW.po
  addons/event/i18n/es_419.po
  addons/fleet/models/fleet_vehicle_model_brand.py
  addons/fleet/views/fleet_vehicle_model_views.xml
  addons/gamification/i18n/es_419.po
  addons/hr_gamification/i18n/es_419.po
  addons/hr_org_chart/i18n/es_419.po
  addons/hr_recruitment/i18n/es_419.po
  addons/hr_timesheet/i18n/zh_TW.po
  addons/hr_work_entry/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ja.po
  addons/hr_work_entry_holidays/i18n/ja.po
  addons/iap/i18n/es_419.po
  addons/im_livechat/i18n/es_419.po
  addons/l10n_it_edi_ndd/data/l10n_it.document.type.csv
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/l10n_it_document_type.py
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/l10n_it_edi_ndd/views/account_move_views.xml
  addons/l10n_it_edi_ndd/views/l10n_it_document_type.xml
  addons/l10n_ro_efactura_synchronize/models/account_move.py
  addons/l10n_ro_efactura_synchronize/tests/test_xml_ubl_ro.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/loyalty/i18n/es_419.po
  addons/mass_mailing_sms/i18n/es_419.po
  addons/mass_mailing_themes/i18n/es_419.po
  addons/membership/views/partner_views.xml
  addons/membership/wizard/membership_invoice.py
  addons/phone_validation/i18n/es_419.po
  addons/point_of_sale/i18n/es_419.po
  addons/portal/i18n/es_419.po
  addons/pos_self_order/i18n/es_419.po
  addons/project_timesheet_holidays/i18n/es_419.po
  addons/purchase/i18n/ja.po
  addons/sale/models/account_move.py
  addons/sale_purchase/i18n/es_419.po
  addons/sales_team/i18n/es_419.po
  addons/sms/i18n/es_419.po
  addons/snailmail/i18n/es_419.po
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/survey/i18n/lt.po
  addons/uom/i18n/es_419.po
  addons/web/models/ir_http.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/webclient/switch_company_menu/switch_company_menu.js
  addons/web/static/tests/webclient/mobile/mobile_switch_company_menu_tests.js
  addons/web/static/tests/webclient/switch_company_menu_tests.js
  addons/web/tests/test_session_info.py
  addons/website_crm_partner_assign/i18n/es_419.po
  addons/website_sale/controllers/main.py
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: 17.0

#35685 Syncing from upstream odoo/odoo (staging.16.0)
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/fleet/models/fleet_vehicle_model_brand.py
  addons/fleet/views/fleet_vehicle_model_views.xml
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/web/static/lib/owl/owl.js
Labels: staging.16.0

#35687 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/test_taxes_computation.py
  addons/account/views/account_move_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/base_automation/views/base_automation_views.xml
  addons/google_calendar/models/calendar.py
  addons/google_calendar/wizard/reset_account.py
  addons/html_editor/static/src/core/delete_plugin.js
  addons/l10n_cz/models/template_cz.py
  addons/l10n_it/models/account_tax.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_withholding/data/template/account.tax-it.csv
  addons/l10n_it_edi_withholding/i18n/it.po
  addons/l10n_it_edi_withholding/i18n/l10n_it_edi_withholding.pot
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_tax.py
  addons/l10n_it_edi_withholding/tests/export_xmls/enasarco_tax_invoice.xml
  addons/l10n_it_edi_withholding/tests/test_withholding.py
  addons/membership/views/partner_views.xml
  addons/membership/wizard/membership_invoice.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/missing_fields.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/pricelist_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/gift_card_program_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_online_payment_self_order/static/src/self_order_service.js
  addons/pos_sale/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/models/purchase_bill_line_match.py
  addons/purchase/tests/test_purchase.py
  addons/resource/models/resource_calendar.py
  addons/resource/tests/test_resource_calendar.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_loyalty/models/sale_order_line.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/test_base_automation/tests/test_tour.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/domain.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/website/static/src/components/dialog/add_page_dialog.js
  doc/cla/corporate/forgeflow.md
Labels: staging.18.0

#35690 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account/models/product.py
  addons/account/views/account_move_views.xml
  addons/auth_totp_portal/i18n/es_419.po
  addons/barcodes/models/barcode_nomenclature.py
  addons/crm_iap_mine/i18n/es_419.po
  addons/event/i18n/cs.po
  addons/event/i18n/es_419.po
  addons/event/i18n/it.po
  addons/google_calendar/models/calendar.py
  addons/google_calendar/wizard/reset_account.py
  addons/html_editor/i18n/de.po
  addons/html_editor/static/tests/list/delete_backward.test.js
  addons/l10n_ar/models/res_partner.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_it/models/account_tax.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/tests/test_account_move_document_type.py
  addons/l10n_it_edi_withholding/data/template/account.tax-it.csv
  addons/l10n_it_edi_withholding/i18n/it.po
  addons/l10n_it_edi_withholding/i18n/l10n_it_edi_withholding.pot
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_tax.py
  addons/l10n_it_edi_withholding/tests/export_xmls/enasarco_tax_invoice.xml
  addons/l10n_it_edi_withholding/tests/test_withholding.py
  addons/loyalty/i18n/es_419.po
  addons/mail/i18n/es_419.po
  addons/point_of_sale/i18n/es_419.po
  addons/point_of_sale/i18n/it.po
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_self_order_sale/i18n/es_419.po
  addons/product_margin/tests/test_product_margin.py
  addons/project/i18n/es_419.po
  addons/purchase/i18n/ko.po
  addons/purchase_stock/i18n/ko.po
  addons/sale/i18n/es_419.po
  addons/sale_stock/tests/test_sale_stock.py
  addons/sms/i18n/es_419.po
  addons/stock/i18n/ko.po
  addons/stock/models/stock_move.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/web_editor/i18n/de.po
  addons/web_editor/i18n/es_419.po
  addons/web_editor/i18n/it.po
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/website_crm_partner_assign/i18n/es_419.po
  addons/website_crm_partner_assign/i18n/it.po
  odoo/addons/base/i18n/es_419.po
Labels: tmp.saas-18.2

#35695 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/test_taxes_computation.py
  addons/account/views/account_move_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.js
  addons/analytic/static/tests/analytic_distribution_tests.js
  addons/base_automation/views/base_automation_views.xml
  addons/google_calendar/models/calendar.py
  addons/google_calendar/wizard/reset_account.py
  addons/html_editor/static/src/core/delete_plugin.js
  addons/l10n_cz/models/template_cz.py
  addons/l10n_it/models/account_tax.py
  addons/l10n_it_edi/i18n/it.po
  addons/l10n_it_edi/i18n/l10n_it_edi.pot
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi_withholding/data/template/account.tax-it.csv
  addons/l10n_it_edi_withholding/i18n/it.po
  addons/l10n_it_edi_withholding/i18n/l10n_it_edi_withholding.pot
  addons/l10n_it_edi_withholding/models/account_move.py
  addons/l10n_it_edi_withholding/models/account_tax.py
  addons/l10n_it_edi_withholding/tests/export_xmls/enasarco_tax_invoice.xml
  addons/l10n_it_edi_withholding/tests/test_withholding.py
  addons/membership/views/partner_views.xml
  addons/membership/wizard/membership_invoice.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/missing_fields.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/tests/tours/pricelist_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_loyalty/models/pos_order.py
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_loyalty/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/tests/tours/gift_card_program_tour.js
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_online_payment_self_order/static/src/self_order_service.js
  addons/pos_sale/static/src/overrides/components/control_buttons/control_buttons.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/models/purchase_bill_line_match.py
  addons/purchase/tests/test_purchase.py
  addons/resource/models/resource_calendar.py
  addons/resource/tests/test_resource_calendar.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_loyalty/models/sale_order_line.py
  addons/sale_loyalty/tests/test_loyalty.py
  addons/test_base_automation/tests/test_tour.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/domain.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/website/static/src/components/dialog/add_page_dialog.js
  doc/cla/corporate/forgeflow.md
Labels: tmp.18.0

#35697 [bt#34000] remove inappropriate error messages and their translations
  addons/account/i18n/account.pot
  addons/account/i18n/de.po
  addons/account/i18n/fr.po
  addons/account/models/account_move_line.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/i18n/de.po
  odoo/addons/base/i18n/fr.po
  odoo/addons/base/models/ir_rule.py
  odoo/addons/test_access_rights/tests/test_feedback.py
Labels: 18.0.project_sv_559

#35698 Syncing from upstream odoo/odoo (16.0)
  odoo/tools/translate.py
Labels: 16.0

#35699 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/fr.po
  addons/account/models/res_partner_bank.py
  addons/account/tests/test_account_partner.py
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/loyalty/i18n/es_419.po
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/pos_epson_printer/i18n/es_419.po
  addons/project/models/project_task.py
  addons/project/tests/test_project_flow.py
  addons/sale/i18n/es_419.po
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/sale_management/i18n/ja.po
  addons/sales_team/i18n/es_419.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move.py
  addons/web/i18n/ja.po
  addons/web_editor/i18n/ja.po
  addons/website/i18n/ca.po
  addons/website/i18n/ja.po
  addons/website_sale_mrp/__init__.py
  addons/website_sale_mrp/__manifest__.py
  addons/website_sale_mrp/controllers/__init__.py
  addons/website_sale_mrp/controllers/variant.py
  addons/website_sale_mrp/models/__init__.py
  addons/website_sale_mrp/models/sale_order.py
  addons/website_sale_mrp/static/src/js/variant_mixin.js
  addons/website_sale_mrp/static/tests/tours/test_website_sale_product_availability.js
  addons/website_sale_mrp/tests/__init__.py
  addons/website_sale_mrp/tests/test_website_sale_product_availability.py
  addons/website_sale_stock/static/src/js/variant_mixin.js
  addons/website_slides/i18n/ca.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/ja.po
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/tests/test_res_partner_bank.py
Labels: 17.0

#35700 Syncing from upstream odoo/odoo (18.0)
  addons/account/i18n/my.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/crm/i18n/my.po
  addons/event/i18n/es_419.po
  addons/fleet/models/fleet_vehicle_model_brand.py
  addons/fleet/views/fleet_vehicle_model_views.xml
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/html_editor/i18n/ja.po
  addons/l10n_dk_nemhandel/__init__.py
  addons/l10n_dk_nemhandel/__manifest__.py
  addons/marketing_card/i18n/ja.po
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/point_of_sale/static/src/utils.js
  addons/pos_epson_printer/i18n/es_419.po
  addons/project/i18n/my.po
  addons/sale/i18n/pt.po
  addons/sale/models/account_move.py
  addons/sale_management/i18n/ja.po
  addons/sale_product_matrix/i18n/ja.po
  addons/spreadsheet_account/i18n/my.po
  addons/spreadsheet_dashboard_account/i18n/my.po
  addons/spreadsheet_dashboard_event_sale/i18n/my.po
  addons/spreadsheet_dashboard_pos_hr/i18n/my.po
  addons/spreadsheet_dashboard_pos_restaurant/i18n/my.po
  addons/spreadsheet_dashboard_sale/i18n/my.po
  addons/spreadsheet_dashboard_website_sale/i18n/my.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/my.po
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/stock_delivery/wizard/choose_delivery_package.py
  addons/stock_picking_batch/models/stock_move_line.py
  addons/web/i18n/ja.po
  addons/web/models/ir_http.py
  addons/web/static/src/webclient/switch_company_menu/switch_company_menu.js
  addons/web/static/tests/_framework/mock_session.hoot.js
  addons/web/static/tests/webclient/switch_company_menu.test.js
  addons/web/tests/test_session_info.py
  addons/web_editor/i18n/ja.po
  addons/website/i18n/ca.po
  addons/website/i18n/ja.po
  addons/website_crm_partner_assign/i18n/my.po
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/es_419.po
  addons/website_slides/i18n/ca.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/ja.po
Labels: 18.0

#35703 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_analytic.py
  addons/base_automation/views/base_automation_views.xml
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/fleet/models/fleet_vehicle_model_brand.py
  addons/fleet/views/fleet_vehicle_model_views.xml
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/html_editor/i18n/ja.po
  addons/html_editor/static/src/core/delete_plugin.js
  addons/l10n_cz/models/template_cz.py
  addons/marketing_card/i18n/ja.po
  addons/membership/views/partner_views.xml
  addons/membership/wizard/membership_invoice.py
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/src/app/utils/use_idle_timer.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_epson_printer/i18n/es_419.po
  addons/pos_razorpay/i18n/ca.po
  addons/pos_restaurant/static/src/app/services/pos_store.js
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/resource/models/resource_calendar.py
  addons/resource/tests/test_resource_calendar.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_edi_ubl/i18n/es_419.po
  addons/sale_loyalty/models/sale_order_line.py
  addons/sale_management/i18n/ja.po
  addons/sale_product_matrix/i18n/ja.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/test_base_automation/tests/test_tour.py
  addons/web/i18n/ja.po
  addons/website/i18n/ca.po
  addons/website/i18n/ja.po
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/es_419.po
  addons/website_slides/i18n/ca.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/ja.po
Labels: saas-18.2

#35707 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account/i18n/ja.po
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_analytic.py
  addons/base_automation/views/base_automation_views.xml
  addons/base_import/i18n/es_419.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/crm/i18n/es_419.po
  addons/crm_livechat/i18n/es_419.po
  addons/delivery/i18n/es_419.po
  addons/digest/i18n/zh_TW.po
  addons/event/i18n/es_419.po
  addons/fleet/models/fleet_vehicle_model_brand.py
  addons/fleet/views/fleet_vehicle_model_views.xml
  addons/hr/i18n/ko.po
  addons/hr_gamification/i18n/es_419.po
  addons/hr_org_chart/i18n/es_419.po
  addons/hr_recruitment/i18n/es_419.po
  addons/hr_timesheet/i18n/zh_TW.po
  addons/html_editor/static/src/core/delete_plugin.js
  addons/iap/i18n/es_419.po
  addons/im_livechat/i18n/es_419.po
  addons/l10n_cz/models/template_cz.py
  addons/loyalty/i18n/es_419.po
  addons/mass_mailing_sms/i18n/es_419.po
  addons/membership/views/partner_views.xml
  addons/membership/wizard/membership_invoice.py
  addons/phone_validation/i18n/es_419.po
  addons/point_of_sale/controllers/main.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/src/app/utils/use_idle_timer.js
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/portal/i18n/es_419.po
  addons/pos_hr/i18n/es_419.po
  addons/pos_restaurant/static/src/app/services/pos_store.js
  addons/pos_self_order/i18n/es_419.po
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase/i18n/ja.po
  addons/resource/models/resource_calendar.py
  addons/resource/tests/test_resource_calendar.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order_line.py
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_loyalty/models/sale_order_line.py
  addons/snailmail/i18n/es_419.po
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.scss
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet_variables.scss
  addons/test_base_automation/tests/test_tour.py
  addons/website/i18n/es_419.po
  addons/website_crm_partner_assign/i18n/es_419.po
  addons/website_event_meet/i18n/es_419.po
  addons/website_sale/controllers/main.py
  addons/website_sale/i18n/es_419.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: staging.saas-18.2

#35711 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/res_partner_bank.py
  addons/account/tests/test_account_partner.py
  addons/project/models/project_task.py
  addons/project/tests/test_project_flow.py
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_order.py
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move.py
  addons/website_sale_mrp/__init__.py
  addons/website_sale_mrp/__manifest__.py
  addons/website_sale_mrp/controllers/__init__.py
  addons/website_sale_mrp/controllers/variant.py
  addons/website_sale_mrp/models/__init__.py
  addons/website_sale_mrp/models/sale_order.py
  addons/website_sale_mrp/static/src/js/variant_mixin.js
  addons/website_sale_mrp/static/tests/tours/test_website_sale_product_availability.js
  addons/website_sale_mrp/tests/__init__.py
  addons/website_sale_mrp/tests/test_website_sale_product_availability.py
  addons/website_sale_stock/static/src/js/variant_mixin.js
  odoo/addons/base/models/res_bank.py
  odoo/addons/base/tests/test_res_partner_bank.py
Labels: staging.17.0

#35718 Syncing from upstream odoo/odoo (tmp.16.0)
  odoo/tools/translate.py
Labels: tmp.16.0

#35722 Syncing from upstream odoo/odoo (16.0)
  doc/cla/corporate/adhoc.md
Labels: 16.0

#35723 Syncing from upstream odoo/odoo (17.0)
  addons/account/views/account_tax_views.xml
  addons/base_automation/i18n/es_419.po
  addons/base_install_request/i18n/es_419.po
  addons/base_vat/i18n/es_419.po
  addons/event/i18n/es_419.po
  addons/gamification/i18n/es_419.po
  addons/hr_fleet/i18n/es_419.po
  addons/l10n_mx/data/account_report_diot.xml
  addons/partner_autocomplete/i18n/es_419.po
  addons/payment/i18n/es_419.po
  addons/pos_self_order/models/pos_session.py
  addons/project/views/project_task_views.xml
  addons/purchase_stock/tests/test_purchase_order.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website_sale/i18n/es_419.po
  doc/cla/corporate/adhoc.md
  odoo/addons/base/i18n/he.po
  odoo/tools/translate.py
Labels: 17.0

#35727 Syncing from upstream odoo/odoo (saas-18.2)
  addons/base_automation/i18n/es_419.po
  addons/base_import/i18n/es_419.po
  addons/base_install_request/i18n/es_419.po
  addons/base_vat/i18n/es_419.po
  addons/crm/i18n/es_419.po
  addons/crm_livechat/i18n/es_419.po
  addons/delivery/i18n/es_419.po
  addons/event/i18n/es_419.po
  addons/hr_fleet/i18n/es_419.po
  addons/hr_gamification/i18n/es_419.po
  addons/hr_org_chart/i18n/es_419.po
  addons/iap/i18n/es_419.po
  addons/loyalty/i18n/es_419.po
  addons/partner_autocomplete/i18n/es_419.po
  addons/payment/i18n/es_419.po
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/tests/pos/tours/chrome_tour.js
  addons/point_of_sale/static/tests/pos/tours/chrome_without_cash_move_permission_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/chrome_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/portal/i18n/es_419.po
  addons/pos_epson_printer/i18n/es_419.po
  addons/pos_event/i18n/es_419.po
  addons/pos_hr/i18n/es_419.po
  addons/pos_self_order/i18n/es_419.po
  addons/sale_edi_ubl/i18n/es_419.po
  addons/snailmail/i18n/es_419.po
  addons/stock/models/stock_rule.py
  addons/website/i18n/es_419.po
  addons/website_crm_partner_assign/i18n/es_419.po
  addons/website_event_meet/i18n/es_419.po
  addons/website_sale/i18n/es_419.po
  odoo/addons/base/i18n/es_419.po
Labels: saas-18.2

#35731 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/base_automation/i18n/es_419.po
  addons/base_import/i18n/es_419.po
  addons/base_install_request/i18n/es_419.po
  addons/base_vat/i18n/es_419.po
  addons/crm/i18n/es_419.po
  addons/crm_livechat/i18n/es_419.po
  addons/delivery/i18n/es_419.po
  addons/event/i18n/es_419.po
  addons/hr_fleet/i18n/es_419.po
  addons/hr_gamification/i18n/es_419.po
  addons/hr_org_chart/i18n/es_419.po
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/html_editor/i18n/ja.po
  addons/iap/i18n/es_419.po
  addons/loyalty/i18n/es_419.po
  addons/marketing_card/i18n/ja.po
  addons/partner_autocomplete/i18n/es_419.po
  addons/payment/i18n/es_419.po
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/tests/pos/tours/chrome_tour.js
  addons/point_of_sale/static/tests/pos/tours/chrome_without_cash_move_permission_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/chrome_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/portal/i18n/es_419.po
  addons/pos_epson_printer/i18n/es_419.po
  addons/pos_event/i18n/es_419.po
  addons/pos_hr/i18n/es_419.po
  addons/pos_razorpay/i18n/ca.po
  addons/pos_self_order/i18n/es_419.po
  addons/sale_edi_ubl/i18n/es_419.po
  addons/sale_management/i18n/ja.po
  addons/sale_product_matrix/i18n/ja.po
  addons/snailmail/i18n/es_419.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move.py
  addons/web/i18n/ja.po
  addons/website/i18n/ca.po
  addons/website/i18n/es_419.po
  addons/website/i18n/ja.po
  addons/website_crm_partner_assign/i18n/es_419.po
  addons/website_event_meet/i18n/es_419.po
  addons/website_sale/i18n/es_419.po
  addons/website_slides/i18n/ca.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/es_419.po
  odoo/addons/base/i18n/ja.po
Labels: staging.saas-18.2

#35734 Syncing from upstream odoo/odoo (staging.16.0)
  doc/cla/corporate/adhoc.md
Labels: staging.16.0

#35735 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/fr.po
  addons/account/views/account_tax_views.xml
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/l10n_mx/data/account_report_diot.xml
  addons/loyalty/i18n/es_419.po
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/pos_epson_printer/i18n/es_419.po
  addons/pos_self_order/models/pos_session.py
  addons/project/views/project_task_views.xml
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/i18n/es_419.po
  addons/sale_management/i18n/ja.po
  addons/sales_team/i18n/es_419.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/web/i18n/ja.po
  addons/web_editor/i18n/ja.po
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/i18n/ca.po
  addons/website/i18n/ja.po
  addons/website_slides/i18n/ca.po
  doc/cla/corporate/adhoc.md
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/ja.po
  odoo/tools/translate.py
Labels: staging.17.0

#35743 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/fr.po
  addons/account/views/account_tax_views.xml
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/l10n_mx/data/account_report_diot.xml
  addons/loyalty/i18n/es_419.po
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/pos_epson_printer/i18n/es_419.po
  addons/pos_self_order/models/pos_session.py
  addons/project/views/project_task_views.xml
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale/i18n/es_419.po
  addons/sale_management/i18n/ja.po
  addons/sales_team/i18n/es_419.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/web/i18n/ja.po
  addons/web_editor/i18n/ja.po
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/i18n/ca.po
  addons/website/i18n/ja.po
  addons/website_slides/i18n/ca.po
  doc/cla/corporate/adhoc.md
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/ja.po
  odoo/tools/translate.py
Labels: tmp.17.0

#35744 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/i18n/my.po
  addons/crm/i18n/my.po
  addons/event/i18n/es_419.po
  addons/hr_skills/i18n/ja.po
  addons/hr_work_entry_contract/i18n/ca.po
  addons/html_editor/i18n/ja.po
  addons/marketing_card/i18n/ja.po
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/es_419.po
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/pos_epson_printer/i18n/es_419.po
  addons/project/i18n/my.po
  addons/sale/i18n/pt.po
  addons/sale/static/src/js/tours/product_configurator_tour_utils.js
  addons/sale_management/i18n/ja.po
  addons/sale_product_matrix/i18n/ja.po
  addons/spreadsheet_account/i18n/my.po
  addons/spreadsheet_dashboard_account/i18n/my.po
  addons/spreadsheet_dashboard_event_sale/i18n/my.po
  addons/spreadsheet_dashboard_pos_hr/i18n/my.po
  addons/spreadsheet_dashboard_pos_restaurant/i18n/my.po
  addons/spreadsheet_dashboard_sale/i18n/my.po
  addons/spreadsheet_dashboard_website_sale/i18n/my.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/ja.po
  addons/spreadsheet_dashboard_website_sale_slides/i18n/my.po
  addons/web/i18n/ja.po
  addons/web/static/src/core/macro.js
  addons/web_editor/i18n/ja.po
  addons/web_tour/static/tests/check_undeterminisms.test.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/website/i18n/ca.po
  addons/website/i18n/ja.po
  addons/website_crm_partner_assign/i18n/my.po
  addons/website_sale/i18n/es_419.po
  addons/website_sale_mrp/__init__.py
  addons/website_sale_mrp/__manifest__.py
  addons/website_sale_mrp/controllers/__init__.py
  addons/website_sale_mrp/controllers/variant.py
  addons/website_sale_mrp/models/__init__.py
  addons/website_sale_mrp/models/sale_order.py
  addons/website_sale_mrp/static/src/js/variant_mixin.js
  addons/website_sale_mrp/static/tests/tours/test_website_sale_product_availability.js
  addons/website_sale_mrp/tests/__init__.py
  addons/website_sale_mrp/tests/test_website_sale_product_availability.py
  addons/website_sale_stock/static/src/js/variant_mixin.js
  addons/website_slides/i18n/ca.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/ja.po
Labels: tmp.18.0

#35770 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move_line.py
  addons/project/static/src/js/tours/project.js
  addons/project/static/tests/tours/project_tour.js
  addons/project/static/tests/tours/project_update_tour_tests.js
  addons/sale_project_stock/models/stock_move.py
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
Labels: master

#35774 Syncing from upstream odoo/odoo (staging.master)
  addons/account/models/account_move_line.py
  addons/l10n_mx/data/account_report_diot.xml
  addons/project/static/src/js/tours/project.js
  addons/project/static/tests/tours/project_tour.js
  addons/project/static/tests/tours/project_update_tour_tests.js
  addons/sale_project_stock/models/stock_move.py
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
Labels: staging.master

#35778 Syncing from upstream odoo/odoo (staging.19.0)
  addons/account/models/account_move_line.py
  addons/account/models/sequence_mixin.py
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/tests/test_multi_contract.py
  addons/hr_work_entry_holidays/tests/test_performance.py
  addons/html_builder/static/src/builder.xml
  addons/html_builder/static/src/core/setup_editor_plugin.js
  addons/l10n_mx/data/account_report_diot.xml
  addons/mrp/tests/test_backorder.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_order.py
  addons/pos_discount/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/pos_discount/static/tests/tours/test_pos_global_discount_flow.js
  addons/pos_discount/tests/test_taxes_global_discount.py
  addons/pos_online_payment_self_order/static/src/overrides/services/pos_store.js
  addons/pos_self_order/static/src/app/components/attribute_selection/attribute_selection.xml
  addons/pos_self_order/static/src/app/components/attribute_selection/attribute_selection_helper.js
  addons/pos_self_order/static/src/app/components/missing_required_details/missing_required_details.scss
  addons/pos_self_order/static/src/app/components/missing_required_details/missing_required_details.xml
  addons/pos_self_order/static/src/app/pages/combo_page/combo_page.js
  addons/pos_self_order/static/src/app/pages/combo_page/combo_page.xml
  addons/pos_self_order/static/src/app/pages/product_page/product_page.js
  addons/pos_self_order/static/src/app/pages/product_page/product_page.xml
  addons/pos_self_order/static/tests/tours/self_order_attribute_tour.js
  addons/pos_self_order/static/tests/tours/utils/common.js
  addons/pos_self_order/static/tests/tours/utils/product_page_util.js
  addons/purchase/models/purchase_bill_line_match.py
  addons/purchase/tests/test_purchase.py
  addons/sale_project/views/project_views.xml
  addons/web/static/src/core/macro.js
  addons/web_tour/static/tests/check_undeterminisms.test.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/website/static/src/builder/plugins/translation_plugin.js
  addons/website/static/src/client_actions/website_preview/mobile_preview_systray.scss
  addons/website/static/src/client_actions/website_preview/mobile_preview_systray.xml
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/tests/builder/translation.test.js
  addons/website/static/tests/builder/website_helpers.js
  doc/cla/corporate/adhoc.md
Labels: staging.19.0

#35779 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_move_line.py
  addons/project/static/src/js/tours/project.js
  addons/project/static/tests/tours/project_tour.js
  addons/project/static/tests/tours/project_update_tour_tests.js
  addons/sale_project_stock/models/stock_move.py
  addons/sale_timesheet/static/tests/tours/sale_timesheet_tour.js
Labels: tmp.master

#35787 Syncing from upstream odoo/odoo (master)
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
Labels: master

#35789 Syncing from upstream odoo/odoo (saas-18.3)
  addons/mail/i18n/vi.po
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/components/popups/cash_move_popup/cash_move_list_popup/cash_move_list_popup.js
  addons/point_of_sale/static/src/app/components/popups/cash_move_popup/cash_move_list_popup/cash_move_list_popup.xml
  addons/point_of_sale/static/src/app/components/popups/cash_move_popup/cash_move_popup.js
  addons/point_of_sale/static/tests/pos/tours/utils/cash_move_list_util.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/sms/i18n/vi.po
  addons/website/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: saas-18.3

#35790 Syncing from upstream odoo/odoo (saas-18.4)
  addons/mail/i18n/vi.po
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/sms/i18n/vi.po
  addons/website/i18n/vi.po
  odoo/addons/base/i18n/vi.po
Labels: saas-18.4

#35791 Syncing from upstream odoo/odoo (staging.master)
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
Labels: staging.master

#35794 Syncing from upstream odoo/odoo (staging.saas-18.4)
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
Labels: staging.saas-18.4

#35796 Syncing from upstream odoo/odoo (tmp.master)
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
Labels: tmp.master

#35798 Syncing from upstream odoo/odoo (tmp.saas-18.4)
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
Labels: tmp.saas-18.4

#35799 Syncing from upstream odoo/odoo (tmp.19.0)
  addons/point_of_sale/i18n/ar.po
  addons/point_of_sale/i18n/az.po
  addons/point_of_sale/i18n/bg.po
  addons/point_of_sale/i18n/ca.po
  addons/point_of_sale/i18n/cs.po
  addons/point_of_sale/i18n/da.po
  addons/point_of_sale/i18n/de.po
  addons/point_of_sale/i18n/el.po
  addons/point_of_sale/i18n/es.po
  addons/point_of_sale/i18n/es_419.po
  addons/point_of_sale/i18n/fa.po
  addons/point_of_sale/i18n/fi.po
  addons/point_of_sale/i18n/fr.po
  addons/point_of_sale/i18n/he.po
  addons/point_of_sale/i18n/hi.po
  addons/point_of_sale/i18n/hr.po
  addons/point_of_sale/i18n/hu.po
  addons/point_of_sale/i18n/id.po
  addons/point_of_sale/i18n/it.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/ko.po
  addons/point_of_sale/i18n/ku.po
  addons/point_of_sale/i18n/lt.po
  addons/point_of_sale/i18n/mn.po
  addons/point_of_sale/i18n/my.po
  addons/point_of_sale/i18n/nb.po
  addons/point_of_sale/i18n/nl.po
  addons/point_of_sale/i18n/pl.po
  addons/point_of_sale/i18n/pt.po
  addons/point_of_sale/i18n/pt_BR.po
  addons/point_of_sale/i18n/ro.po
  addons/point_of_sale/i18n/ru.po
  addons/point_of_sale/i18n/sl.po
  addons/point_of_sale/i18n/sr@latin.po
  addons/point_of_sale/i18n/sv.po
  addons/point_of_sale/i18n/th.po
  addons/point_of_sale/i18n/tr.po
  addons/point_of_sale/i18n/uk.po
  addons/point_of_sale/i18n/vi.po
  addons/point_of_sale/i18n/zh_CN.po
  addons/point_of_sale/i18n/zh_TW.po
  addons/sale_project/models/sale_order.py
  addons/sale_project/tests/test_sale_project.py
Labels: tmp.19.0

#35801 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/es_419.po
  addons/base_automation/i18n/es_419.po
  addons/base_import/i18n/es_419.po
  addons/crm/data/digest_data.xml
  addons/event/i18n/es_419.po
  addons/event_sale/i18n/es_419.po
  addons/google_calendar/i18n/es_419.po
  addons/im_livechat/i18n/es_419.po
  addons/l10n_mx/i18n/es_419.po
  addons/l10n_mx/i18n/l10n_mx.pot
  addons/link_tracker/models/link_tracker.py
  addons/link_tracker/tests/test_link_tracker.py
  addons/loyalty/i18n/es_419.po
  addons/lunch/i18n/ca.po
  addons/mail/i18n/es_419.po
  addons/mrp/i18n/es_419.po
  addons/payment_stripe/const.py
  addons/payment_stripe/controllers/main.py
  addons/payment_stripe/models/payment_provider.py
  addons/payment_stripe/models/payment_transaction.py
  addons/phone_validation/i18n/es_419.po
  addons/portal/i18n/es_419.po
  addons/pos_epson_printer/i18n/es_419.po
  addons/pos_self_order/i18n/ca.po
  addons/pos_self_order/i18n/es_419.po
  addons/product/i18n/es_419.po
  addons/purchase/i18n/es_419.po
  addons/purchase_requisition/i18n/es_419.po
  addons/rating/i18n/es_419.po
  addons/repair/i18n/es_419.po
  addons/sale/i18n/es_419.po
  addons/sale_management/i18n/es_419.po
  addons/sale_timesheet/i18n/es_419.po
  addons/sms/i18n/es_419.po
  addons/snailmail/i18n/es_419.po
  addons/spreadsheet/i18n/es_419.po
  addons/stock/i18n/es_419.po
  addons/stock/i18n/fr.po
  addons/stock_account/models/product.py
  addons/stock_picking_batch/i18n/es_419.po
  addons/uom/i18n/es_419.po
  addons/web/i18n/es_419.po
  addons/web_editor/i18n/es_419.po
  addons/web_editor/i18n/ja.po
  addons/website/i18n/ja.po
  addons/website_sale_stock/i18n/ca.po
  odoo/addons/base/i18n/ca.po
  odoo/addons/base/i18n/es_419.po
Labels: 17.0

#35805 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/models/account_payment_term.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/bus/tests/test_notify.py
  addons/crm/models/res_partner.py
  addons/event/data/mail_template_data.xml
  addons/google_calendar/wizard/reset_account.py
  addons/im_livechat/static/src/core/common/message_model_patch.js
  addons/im_livechat/static/tests/translation.test.js
  addons/l10n_dk_nemhandel/__init__.py
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/mail/static/src/views/web/fields/html_mail_field/convert_inline.js
  addons/point_of_sale/static/src/css/pos_receipts.css
  addons/pos_epson_printer/models/pos_config.py
  addons/pos_epson_printer/models/pos_printer.py
  addons/pos_epson_printer/models/res_config_settings.py
  addons/pos_restaurant/static/src/app/screens/floor_screen/floor_screen.js
  addons/pos_restaurant/static/tests/tours/utils/floor_screen_util.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_self_order/__manifest__.py
  addons/pos_self_order/models/pos_session.py
  addons/pos_self_order/models/res_config_settings.py
  addons/pos_self_order/static/src/backend/qr_order_button/qr_order_button.js
  addons/pos_self_order/static/src/overrides/components/navbar/navbar.xml
  addons/pos_self_order/static/src/overrides/components/qr_order_button/qr_order_button.js
  addons/pos_self_order/static/src/overrides/components/qr_order_button/qr_order_button.xml
  addons/pos_self_order/static/src/overrides/models/pos_store.js
  addons/pos_self_order/static/src/overrides/screens/floor_screen/floor_screen.js
  addons/pos_self_order/static/src/overrides/screens/floor_screen/floor_screen.xml
  addons/pos_self_order/views/res_config_settings_views.xml
  addons/stock_delivery/tests/test_packing_delivery.py
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/fixture.js
  addons/web/static/lib/hoot/core/job.js
  addons/web/static/lib/hoot/core/logger.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/tag.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/navigator.js
  addons/web/static/tests/public/interaction.test.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/interactions/video/media_video.js
Labels: saas-18.2

#35810 Syncing from upstream odoo/odoo (staging.saas-18.3)
  addons/account/models/account_payment_term.py
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/event/data/mail_template_data.xml
  addons/google_calendar/wizard/reset_account.py
  addons/l10n_dk_nemhandel/__init__.py
  addons/l10n_it_edi/data/l10n_it.document.type.csv
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/l10n_it_document_type.py
  addons/l10n_it_edi/tests/test_account_move_document_type.py
  addons/l10n_it_edi/views/l10n_it_document_type.xml
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/mail/i18n/vi.po
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/views/web/fields/html_mail_field/convert_inline.js
  addons/payment_nuvei/models/payment_transaction.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.xml
  addons/point_of_sale/static/src/css/pos_receipts.css
  addons/pos_epson_printer/models/pos_config.py
  addons/pos_epson_printer/models/pos_printer.py
  addons/pos_epson_printer/models/res_config_settings.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/models/pos_order.js
  addons/pos_self_order/models/pos_session.py
  addons/sms/i18n/vi.po
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/fixture.js
  addons/web/static/lib/hoot/core/job.js
  addons/web/static/lib/hoot/core/logger.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/tag.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/navigator.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/i18n/vi.po
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/static/src/interactions/carousel_product.js
  addons/website_sale/tests/test_website_sale_cart.py
  odoo/addons/base/i18n/vi.po
Labels: staging.saas-18.3

#35812 Syncing from upstream odoo/odoo (staging.16.0)
  addons/payment_stripe/static/src/js/express_checkout_form.js
Labels: staging.16.0

#35818 Syncing from upstream odoo/odoo (tmp.saas-18.3)
  addons/account/models/account_payment_term.py
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/event/data/mail_template_data.xml
  addons/google_calendar/wizard/reset_account.py
  addons/l10n_dk_nemhandel/__init__.py
  addons/l10n_it_edi/data/l10n_it.document.type.csv
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_it_edi/models/l10n_it_document_type.py
  addons/l10n_it_edi/tests/test_account_move_document_type.py
  addons/l10n_it_edi/views/l10n_it_document_type.xml
  addons/l10n_it_edi/views/l10n_it_view.xml
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/mail/i18n/vi.po
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/views/web/fields/html_mail_field/convert_inline.js
  addons/payment_nuvei/models/payment_transaction.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.xml
  addons/point_of_sale/static/src/css/pos_receipts.css
  addons/pos_epson_printer/models/pos_config.py
  addons/pos_epson_printer/models/pos_printer.py
  addons/pos_epson_printer/models/res_config_settings.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/models/pos_order.js
  addons/pos_self_order/models/pos_session.py
  addons/sms/i18n/vi.po
  addons/web/static/lib/hoot/core/expect.js
  addons/web/static/lib/hoot/core/fixture.js
  addons/web/static/lib/hoot/core/job.js
  addons/web/static/lib/hoot/core/logger.js
  addons/web/static/lib/hoot/core/runner.js
  addons/web/static/lib/hoot/core/suite.js
  addons/web/static/lib/hoot/core/tag.js
  addons/web/static/lib/hoot/core/test.js
  addons/web/static/lib/hoot/hoot_utils.js
  addons/web/static/lib/hoot/mock/navigator.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/i18n/vi.po
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website_sale/models/sale_order.py
  addons/website_sale/static/src/interactions/carousel_product.js
  addons/website_sale/tests/test_website_sale_cart.py
  odoo/addons/base/i18n/vi.po
Labels: tmp.saas-18.3

#35820 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/payment_stripe/static/src/js/express_checkout_form.js
Labels: tmp.16.0
