Repository brain-tec/odoo, pull requests merged in 2025-04, with the labels that each got.

#32490 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_account_move_entry.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/l10n_pe_website_sale/static/src/js/website_sale.js
  addons/l10n_pe_website_sale/static/tests/tours/website_sale_address.js
  addons/l10n_pe_website_sale/tests/test_l10n_pe_website_sale.py
  addons/sale/static/tests/tours/sale_signature.js
  addons/sale/tests/test_controllers.py
  addons/sale_management/tests/test_sale_ui.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/link_tests.js
  addons/website/static/src/components/translator/translator.js
  addons/website_sale/models/website_snippet_filter.py
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/http.py
  odoo/service/model.py
  odoo/tools/mail.py
Labels: 17.0

#32493 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/wizard/accrued_orders.py
  addons/hr_holidays/models/resource.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/mrp_subcontracting_dropshipping/models/stock_orderpoint.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/payment_adyen/README.md
  addons/payment_adyen/const.py
  addons/payment_adyen/controllers/main.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/point_of_sale/static/tests/tours/customer_display_tour.js
  addons/pos_online_payment/__manifest__.py
  addons/pos_online_payment/static/src/overrides/customer_display_overrides/customer_display.js
  addons/pos_online_payment/static/tests/tours/customer_display_tour.js
  addons/pos_online_payment/tests/test_frontend.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/chatgpt_alternatives_dialog.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/product_template.py
  addons/website_sale/views/templates.xml
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/service/model.py
  odoo/service/server.py
Labels: saas-17.4

#32494 Syncing from upstream odoo/odoo (saas-18.1)
  README.md
  addons/account/models/account_move.py
  addons/account/models/account_tax.py
  addons/account/models/partner.py
  addons/account/models/sequence_mixin.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/test_sequence_mixin.py
  addons/account/tests/test_taxes_tax_totals_summary.py
  addons/account/views/account_journal_views.xml
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_peppol/data/cron.xml
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/account_move_send.py
  addons/account_peppol/wizard/account_move_send_wizard.py
  addons/account_peppol/wizard/peppol_registration.py
  addons/hr_holidays/i18n/hr_holidays.pot
  addons/hr_holidays/models/hr_employee.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_allocations.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/marketing_card/models/card_campaign.py
  addons/mrp/tests/test_oee.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.xml
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/tests/pos/tours/receipt_screen_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/receipt_screen_util.js
  addons/point_of_sale/tests/__init__.py
  addons/point_of_sale/tests/test_stock_product_updates.py
  addons/pos_loyalty/static/src/app/services/pos_store.js
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/src/app/services/pos_store.js
  addons/pos_restaurant/static/tests/tours/refund_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/purchase/models/purchase_order.py
  addons/purchase/tests/test_purchase.py
  addons/sale/models/payment_transaction.py
  addons/sale_stock/models/stock.py
  addons/sale_stock/tests/test_sale_stock.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/search/control_panel/control_panel.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/js/content/snippets.animation.js
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/orm/models.py
Labels: saas-18.1

#32496 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/wizard/accrued_orders.py
  addons/hr_holidays/models/resource.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/mrp_subcontracting_dropshipping/models/stock_orderpoint.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/payment_adyen/README.md
  addons/payment_adyen/const.py
  addons/payment_adyen/controllers/main.py
  addons/payment_adyen/static/src/js/payment_form.js
  addons/point_of_sale/static/tests/tours/customer_display_tour.js
  addons/pos_online_payment/__manifest__.py
  addons/pos_online_payment/static/src/overrides/customer_display_overrides/customer_display.js
  addons/pos_online_payment/static/tests/tours/customer_display_tour.js
  addons/pos_online_payment/tests/test_frontend.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/web/models/base_document_layout.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/widgets/chatgpt_alternatives_dialog.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/content/snippets.animation.js
  addons/website_sale/models/product_template.py
  addons/website_sale/views/templates.xml
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/service/model.py
  odoo/service/server.py
Labels: staging.saas-17.4

#32498 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/uom_code.xml
  addons/l10n_id_efaktur_coretax/views/uom_uom.xml
  addons/l10n_lu/data/account.account.template.csv
  addons/l10n_lu/data/account.group.template.csv
  addons/l10n_lu/data/account_tax_report_line.xml
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/loyalty/models/product_product.py
  addons/loyalty/tests/test_loyalty.py
  addons/mail/models/mail_thread.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action_test.js
  addons/survey/models/__init__.py
  addons/survey/models/ir_http.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/test_mail_models.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/web/models/base_document_layout.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/search/control_panel/control_panel.js
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/service/model.py
Labels: staging.16.0

#32499 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_account_move_entry.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/l10n_pe_website_sale/static/src/js/website_sale.js
  addons/l10n_pe_website_sale/static/tests/tours/website_sale_address.js
  addons/l10n_pe_website_sale/tests/test_l10n_pe_website_sale.py
  addons/sale/static/tests/tours/sale_signature.js
  addons/sale/tests/test_controllers.py
  addons/sale_management/tests/test_sale_ui.py
  addons/web/models/base_document_layout.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/search/control_panel/control_panel.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/link_tests.js
  addons/website/static/src/components/translator/translator.js
  addons/website_sale/models/website_snippet_filter.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/http.py
  odoo/service/model.py
  odoo/tools/mail.py
Labels: staging.17.0

#32505 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_account.py
  addons/account/tests/test_account_move_entry.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/l10n_pe_website_sale/static/src/js/website_sale.js
  addons/l10n_pe_website_sale/static/tests/tours/website_sale_address.js
  addons/l10n_pe_website_sale/tests/test_l10n_pe_website_sale.py
  addons/sale/static/tests/tours/sale_signature.js
  addons/sale/tests/test_controllers.py
  addons/sale_management/tests/test_sale_ui.py
  addons/web/models/base_document_layout.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/tests/link_tests.js
  addons/website/static/src/components/translator/translator.js
  addons/website_sale/models/website_snippet_filter.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/test_lint/tests/_odoo_checker_gettext.py
  odoo/addons/test_lint/tests/_pylint_path_setup.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/http.py
  odoo/service/model.py
  odoo/tools/mail.py
Labels: tmp.17.0

#32508 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/bus/models/bus_presence.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/tests/legacy/im_status_tests.js
  addons/bus/tests/test_ir_websocket.py
  addons/bus/tests/test_websocket_controller.py
  addons/calendar/static/src/scss/calendar.scss
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_recruitment/models/hr_candidate.py
  addons/hr_work_entry_holidays/data/hr_payroll_holidays_data.xml
  addons/html_editor/static/src/others/qweb_plugin.js
  addons/html_editor/static/tests/qweb.test.js
  addons/im_livechat/tests/test_message.py
  addons/l10n_es_edi_tbai/models/res_company.py
  addons/l10n_hu_edi/data/uom.uom.csv
  addons/l10n_hu_edi/models/uom_uom.py
  addons/l10n_mx_hr/__manifest__.py
  addons/l10n_mx_hr/data/l10n_mx_hr_demo.xml
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/loyalty/models/product_product.py
  addons/loyalty/tests/test_loyalty.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/src/discuss/core/common/discuss_notification_settings.xml
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/tests/discuss/test_bus_presence.py
  addons/mrp_subcontracting_dropshipping/models/stock_orderpoint.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/survey/models/__init__.py
  addons/survey/models/ir_http.py
  addons/web/static/src/search/control_panel/control_panel.js
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale/controllers/main.py
  addons/website_sale/models/product_template.py
  addons/website_sale/models/website_snippet_filter.py
  addons/website_sale/static/src/js/address.js
  addons/website_sale/views/templates.xml
  doc/cla/individual/corentinderuyck.md
  odoo/http.py
  odoo/tools/mail.py
Labels: 18.0

#32512 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_peppol/data/cron.xml
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/account_move_send.py
  addons/account_peppol/models/res_partner.py
  addons/account_peppol/tests/test_peppol_messages.py
  addons/account_peppol/wizard/account_move_send_wizard.py
  addons/account_peppol/wizard/peppol_registration.py
  addons/html_editor/static/src/core/history_plugin.js
  addons/iot_box_image/configuration/packages.txt
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_tbai/models/l10n_es_edi_tbai_document.py
  addons/l10n_es_edi_tbai/models/res_company.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/loyalty/models/product_product.py
  addons/loyalty/tests/test_loyalty.py
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/discuss/core/common/discuss_notification_settings.xml
  addons/mrp_subcontracting_dropshipping/models/stock_orderpoint.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.xml
  addons/point_of_sale/static/tests/pos/tours/receipt_screen_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/receipt_screen_util.js
  addons/portal/static/src/interactions/portal_security.js
  addons/pos_loyalty/static/src/app/screens/payment_screen/payment_screen.js
  addons/pos_loyalty/static/src/app/services/pos_store.js
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/src/app/services/pos_store.js
  addons/project/views/project_project_views.xml
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_crm_partner_assign/static/src/interactions/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_sale/models/website_snippet_filter.py
  addons/website_sale_collect/controllers/main.py
  odoo/http.py
  odoo/tools/mail.py
Labels: saas-18.2

#32515 Syncing from upstream odoo/odoo (staging.16.0)
  addons/hr_holidays/views/hr_leave_views.xml
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: staging.16.0

#32520 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_peppol/data/cron.xml
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/account_move_send.py
  addons/account_peppol/models/res_partner.py
  addons/account_peppol/tests/test_peppol_messages.py
  addons/account_peppol/wizard/account_move_send_wizard.py
  addons/account_peppol/wizard/peppol_registration.py
  addons/html_editor/static/src/core/history_plugin.js
  addons/iot_box_image/configuration/packages.txt
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_tbai/models/l10n_es_edi_tbai_document.py
  addons/l10n_es_edi_tbai/models/res_company.py
  addons/l10n_my_edi/models/account_move.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/loyalty/models/product_product.py
  addons/loyalty/tests/test_loyalty.py
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/discuss/core/common/discuss_notification_settings.xml
  addons/mrp_subcontracting_dropshipping/models/stock_orderpoint.py
  addons/mrp_subcontracting_dropshipping/tests/test_purchase_subcontracting.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/receipt_header/receipt_header.xml
  addons/point_of_sale/static/tests/pos/tours/receipt_screen_tour.js
  addons/point_of_sale/static/tests/pos/tours/utils/receipt_screen_util.js
  addons/portal/static/src/interactions/portal_security.js
  addons/pos_loyalty/static/src/app/screens/payment_screen/payment_screen.js
  addons/pos_loyalty/static/src/app/services/pos_store.js
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/src/app/services/pos_store.js
  addons/project/views/project_project_views.xml
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link_tools.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_crm_partner_assign/static/src/interactions/crm_partner_assign.js
  addons/website_crm_partner_assign/views/website_crm_partner_assign_templates.xml
  addons/website_sale/models/website_snippet_filter.py
  addons/website_sale_collect/controllers/main.py
  odoo/http.py
  odoo/tools/mail.py
Labels: tmp.saas-18.2

#32521 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_holidays/views/hr_leave_views.xml
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
Labels: tmp.16.0

#32524 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/chart_template.py
  addons/l10n_lu/data/tax_report/section_1.xml
  addons/l10n_lu/data/template/account.account-lu.csv
  addons/l10n_lu/data/template/account.group-lu.csv
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/survey/views/survey_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: 17.0

#32525 Syncing from upstream odoo/odoo (18.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/tests/test_ubl_cii.py
  addons/hr_holidays/views/resource_views.xml
  addons/html_editor/static/src/main/media/image_crop.js
  addons/im_livechat/static/src/embed/common/close_confirmation.scss
  addons/im_livechat/static/src/embed/common/close_confirmation.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/static/src/app/models/utils/indexed_db.js
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/tests/unit/render_service.test.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/project/static/tests/tours/project_task_history.js
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/xml/snippets.xml
  addons/web_editor/static/tests/link_tests.js
  addons/web_tour/static/src/tour_service/tour_step_automatic.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/tests/tours/html_editor.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website_payment/static/tests/tours/donation.js
  addons/website_sale_collect/static/src/tests/tours/buy_with_click_and_collect.js
  odoo/tests/_odoo_checker_markup.py
  odoo/tests/test_security.py
  odoo/tools/mail.py
Labels: 18.0

#32527 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/views/resource_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/uom_code.xml
  addons/l10n_id_efaktur_coretax/views/uom_uom.xml
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/snippets.xml
Labels: saas-17.4

#32528 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/models/account_bank_statement_line.py
  addons/bus/models/bus_presence.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/tests/im_status.test.js
  addons/bus/tests/test_ir_websocket.py
  addons/bus/tests/test_websocket_controller.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_work_entry_holidays/data/hr_payroll_holidays_data.xml
  addons/hw_posbox_homepage/static/src/app/status.js
  addons/im_livechat/tests/test_message.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_hu_edi/data/uom.uom.csv
  addons/l10n_hu_edi/models/uom_uom.py
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/tests/discuss/test_bus_presence.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/tests/pos/tours/chrome_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_event/static/src/app/models/data_service_options.js
  addons/purchase_stock/tests/test_create_picking.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/link_tests.js
Labels: saas-18.1

#32529 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/base_automation/models/base_automation.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/hr_work_entry_holidays/data/hr_payroll_holidays_data.xml
  addons/html_editor/static/src/main/font/color_plugin.js
  addons/html_editor/static/src/main/font/color_selector.xml
  addons/html_editor/static/src/main/font/gradient_picker.js
  addons/html_editor/static/src/others/embedded_components/plugins/toggle_block_plugin/toggle_block_plugin.js
  addons/html_editor/static/src/utils/color.js
  addons/html_editor/static/tests/embedded_components_plugins/toggle_block.test.js
  addons/html_editor/static/tests/utils/color.test.js
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/iot_box_image/overwrite_before_init/etc/init_image.sh
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_hu_edi/data/uom.uom.csv
  addons/l10n_hu_edi/models/uom_uom.py
  addons/mail/static/src/views/web/fields/html_mail_field/convert_inline.js
  addons/point_of_sale/static/src/app/components/numpad/numpad.xml
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/models/product_template.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.xml
  addons/point_of_sale/static/src/app/screens/product_screen/action_pad/action_pad.xml
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/tests/pos/tours/chrome_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_restaurant/static/src/app/screens/product_screen/actionpad_widget/actionpad_widget.xml
  addons/purchase/models/purchase_order.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_stock/tests/test_create_picking.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/test_base_automation/tests/test_flow.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/link_tests.js
  addons/website/controllers/form.py
  addons/website/tests/test_website_form_editor.py
  addons/website_hr_recruitment/controllers/main.py
  addons/website_hr_recruitment/data/config_data.xml
  addons/website_hr_recruitment/static/tests/tours/website_hr_recruitment.js
  addons/website_hr_recruitment/tests/test_website_hr_recruitment.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  odoo/addons/base/tests/config/non_default.conf
  odoo/addons/base/tests/config/save_posix.conf
  odoo/addons/base/tests/test_configmanager.py
  odoo/cli/server.py
  odoo/modules/loading.py
  odoo/modules/migration.py
  odoo/tools/config.py
Labels: saas-18.2

#32530 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/views/resource_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/uom_code.xml
  addons/l10n_id_efaktur_coretax/views/uom_uom.xml
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/snippets.xml
Labels: staging.saas-17.4

#32531 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_sequence_mixin.py
  addons/base_automation/models/base_automation.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_work_entry/views/hr_work_entry_views.xml
  addons/hr_work_entry_holidays/data/hr_payroll_holidays_data.xml
  addons/html_editor/static/src/main/font/color_plugin.js
  addons/html_editor/static/src/main/font/color_selector.xml
  addons/html_editor/static/src/main/font/gradient_picker.js
  addons/html_editor/static/src/others/embedded_components/plugins/toggle_block_plugin/toggle_block_plugin.js
  addons/html_editor/static/src/utils/color.js
  addons/html_editor/static/tests/embedded_components_plugins/toggle_block.test.js
  addons/html_editor/static/tests/utils/color.test.js
  addons/hw_drivers/main.py
  addons/hw_drivers/tools/helpers.py
  addons/iot_box_image/overwrite_before_init/etc/init_image.sh
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_hu_edi/data/uom.uom.csv
  addons/l10n_hu_edi/models/uom_uom.py
  addons/mail/static/src/views/web/fields/html_mail_field/convert_inline.js
  addons/point_of_sale/static/src/app/components/numpad/numpad.xml
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/models/product_template.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.xml
  addons/point_of_sale/static/src/app/screens/product_screen/action_pad/action_pad.xml
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/tests/pos/tours/chrome_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_restaurant/static/src/app/screens/product_screen/actionpad_widget/actionpad_widget.xml
  addons/purchase/models/purchase_order.py
  addons/purchase/tests/test_purchase.py
  addons/purchase_stock/tests/test_create_picking.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/test_base_automation/tests/test_flow.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/link_tests.js
  addons/website/controllers/form.py
  addons/website/tests/test_website_form_editor.py
  addons/website_hr_recruitment/controllers/main.py
  addons/website_hr_recruitment/data/config_data.xml
  addons/website_hr_recruitment/static/tests/tours/website_hr_recruitment.js
  addons/website_hr_recruitment/tests/test_website_hr_recruitment.py
  addons/website_hr_recruitment/views/website_hr_recruitment_templates.xml
  odoo/addons/base/tests/config/non_default.conf
  odoo/addons/base/tests/config/save_posix.conf
  odoo/addons/base/tests/test_configmanager.py
  odoo/cli/server.py
  odoo/modules/loading.py
  odoo/modules/migration.py
  odoo/tools/config.py
Labels: staging.saas-18.2

#32532 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_reconcile_model.py
  addons/account/models/chart_template.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
Labels: staging.16.0

#32533 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/chart_template.py
  addons/l10n_lu/data/tax_report/section_1.xml
  addons/l10n_lu/data/template/account.account-lu.csv
  addons/l10n_lu/data/template/account.group-lu.csv
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/survey/views/survey_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: staging.17.0

#32535 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/views/resource_views.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/uom_code.xml
  addons/l10n_id_efaktur_coretax/views/uom_uom.xml
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/snippets.xml
Labels: tmp.saas-17.4

#32536 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/models/account_bank_statement_line.py
  addons/bus/models/bus_presence.py
  addons/bus/static/src/im_status_service.js
  addons/bus/static/tests/im_status.test.js
  addons/bus/tests/test_ir_websocket.py
  addons/bus/tests/test_websocket_controller.py
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/tests/test_leave_requests.py
  addons/hr_holidays/views/resource_views.xml
  addons/hr_work_entry_holidays/data/hr_payroll_holidays_data.xml
  addons/hw_posbox_homepage/static/src/app/status.js
  addons/im_livechat/tests/test_message.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_hu_edi/data/uom.uom.csv
  addons/l10n_hu_edi/models/uom_uom.py
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/mail/static/src/core/common/im_status_service_patch.js
  addons/mail/static/tests/discuss_app/im_status.test.js
  addons/mail/tests/discuss/test_bus_presence.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/static/src/app/models/data_service_options.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/tests/pos/tours/chrome_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_event/static/src/app/models/data_service_options.js
  addons/purchase_stock/tests/test_create_picking.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/stock/tests/test_stock_return_picking.py
  addons/stock/wizard/stock_picking_return.py
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/link_tests.js
Labels: tmp.saas-18.1

#32538 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_reconcile_model.py
  addons/account/models/chart_template.py
  addons/account/tests/test_reconciliation_matching_rules.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
Labels: tmp.16.0

#32539 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/chart_template.py
  addons/l10n_lu/data/tax_report/section_1.xml
  addons/l10n_lu/data/template/account.account-lu.csv
  addons/l10n_lu/data/template/account.group-lu.csv
  addons/l10n_lu/i18n_extra/de.po
  addons/l10n_lu/i18n_extra/fr.po
  addons/l10n_lu/i18n_extra/l10n_lu.pot
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/survey/views/survey_templates.xml
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: tmp.17.0

#32540 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/tests/test_ubl_cii.py
  addons/hr_holidays/views/resource_views.xml
  addons/html_editor/static/src/main/media/image_crop.js
  addons/im_livechat/static/src/embed/common/close_confirmation.scss
  addons/im_livechat/static/src/embed/common/close_confirmation.xml
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_it_edi_ndd/models/account_move.py
  addons/l10n_it_edi_ndd/models/account_payment_methode_line.py
  addons/l10n_it_edi_ndd/tests/__init__.py
  addons/l10n_it_edi_ndd/tests/import_xmls/IT01234567888_FPR01.xml
  addons/l10n_it_edi_ndd/tests/test_edi_import.py
  addons/point_of_sale/__manifest__.py
  addons/point_of_sale/static/src/app/models/utils/indexed_db.js
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/tests/unit/render_service.test.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/project/static/tests/tours/project_task_history.js
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/dashboard_action.xml
  addons/spreadsheet_dashboard/static/tests/dashboard/dashboard_action.test.js
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/src/xml/snippets.xml
  addons/web_editor/static/tests/link_tests.js
  addons/web_tour/static/src/tour_service/tour_step_automatic.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/tests/tours/html_editor.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/static/tests/tours/page_manager.js
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website_payment/static/tests/tours/donation.js
  addons/website_sale_collect/static/src/tests/tours/buy_with_click_and_collect.js
  odoo/tests/_odoo_checker_markup.py
  odoo/tests/test_security.py
  odoo/tools/mail.py
Labels: tmp.18.0

#32541 Syncing from upstream odoo/odoo (17.0)
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_move.py
  addons/survey/views/survey_templates.xml
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
  addons/website_sale/views/templates.xml
Labels: 17.0

#32545 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/wizard/accrued_orders.py
  addons/html_editor/i18n/html_editor.pot
  addons/html_editor/static/src/core/sanitize_plugin.js
  addons/html_editor/static/src/fields/html_viewer.js
  addons/html_editor/static/src/html_migrations/manifest.js
  addons/html_editor/static/src/html_migrations/migration-1.2.js
  addons/html_editor/static/src/main/banner_plugin.js
  addons/html_editor/static/src/main/media/image_crop.js
  addons/html_editor/static/tests/banner.test.js
  addons/html_editor/static/tests/field.test.js
  addons/html_editor/static/tests/html_field.test.js
  addons/html_editor/static/tests/html_migrations.test.js
  addons/html_editor/static/tests/sanitize.test.js
  addons/im_livechat/static/src/core/common/close_confirmation.scss
  addons/im_livechat/static/src/core/common/close_confirmation.xml
  addons/l10n_es_edi_tbai/models/res_company.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/uom_code.xml
  addons/l10n_id_efaktur_coretax/views/uom_uom.xml
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty_delivery/tests/test_loyalty_delivery.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_lots.py
  addons/survey/views/survey_templates.xml
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/snippets.xml
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_sale/views/templates.xml
  addons/website_sale_loyalty/static/tests/tours/test_website_sale_free_shipping_discount_line.js
  odoo/tools/mail.py
Labels: saas-18.1

#32547 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/static/tests/tours/utils/pos_sale_utils.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/static/tests/tours/project_tour.js
  addons/sale_stock_margin/models/sale_order_line.py
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/survey/views/survey_templates.xml
  addons/web/static/src/core/pager/pager.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/website_sale/views/templates.xml
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: staging.saas-17.4

#32549 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/payment_flutterwave/__manifest__.py
  addons/payment_flutterwave/const.py
  addons/payment_flutterwave/controllers/main.py
  addons/payment_flutterwave/models/payment_transaction.py
  addons/payment_flutterwave/static/src/js/payment_form.js
Labels: staging.16.0

#32550 Syncing from upstream odoo/odoo (staging.17.0)
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_move.py
  addons/survey/views/survey_templates.xml
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
  addons/website_sale/views/templates.xml
Labels: staging.17.0

#32552 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/static/tests/tours/utils/pos_sale_utils.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/static/tests/tours/project_tour.js
  addons/sale_stock_margin/models/sale_order_line.py
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/sale_timesheet/__init__.py
  addons/sale_timesheet/security/sale_timesheet_security.xml
  addons/survey/views/survey_templates.xml
  addons/web/static/src/core/pager/pager.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/website_sale/views/templates.xml
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/tests/test_res_partner.py
Labels: tmp.saas-17.4

#32553 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/wizard/accrued_orders.py
  addons/html_editor/i18n/html_editor.pot
  addons/html_editor/static/src/core/sanitize_plugin.js
  addons/html_editor/static/src/fields/html_viewer.js
  addons/html_editor/static/src/html_migrations/manifest.js
  addons/html_editor/static/src/html_migrations/migration-1.2.js
  addons/html_editor/static/src/main/banner_plugin.js
  addons/html_editor/static/src/main/media/image_crop.js
  addons/html_editor/static/tests/banner.test.js
  addons/html_editor/static/tests/field.test.js
  addons/html_editor/static/tests/html_field.test.js
  addons/html_editor/static/tests/html_migrations.test.js
  addons/html_editor/static/tests/sanitize.test.js
  addons/im_livechat/static/src/core/common/close_confirmation.scss
  addons/im_livechat/static/src/core/common/close_confirmation.xml
  addons/l10n_es_edi_tbai/models/res_company.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/uom_code.xml
  addons/l10n_id_efaktur_coretax/views/uom_uom.xml
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/backend/pos_kanban_view/pos_kanban_view.js
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty_delivery/tests/test_loyalty_delivery.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_move_line.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_lots.py
  addons/survey/views/survey_templates.xml
  addons/test_website/static/tests/tours/restricted_editor.js
  addons/web_editor/models/ir_qweb_fields.py
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/image_crop.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/web_editor/static/src/xml/snippets.xml
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_sale/views/templates.xml
  addons/website_sale_loyalty/static/tests/tours/test_website_sale_free_shipping_discount_line.js
  odoo/tools/mail.py
Labels: tmp.saas-18.1

#32556 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_ch/models/account_invoice.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_edi_xml_ubl_21_zatca.py
  addons/l10n_sa_edi/models/account_move.py
  addons/survey/views/survey_templates.xml
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
  addons/website_sale/views/templates.xml
Labels: tmp.17.0

#32558 Syncing from upstream odoo/odoo (16.0)
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: 16.0

#32560 Syncing from upstream odoo/odoo (18.0)
  addons/calendar/models/calendar_event.py
  addons/html_editor/static/src/main/chatgpt/chatgpt_plugin.js
  addons/html_editor/static/src/main/media/media_plugin.js
  addons/html_editor/static/src/main/star_plugin.js
  addons/html_editor/static/src/others/embedded_components/core/file/static_file.xml
  addons/html_editor/static/src/others/embedded_components/plugins/embedded_file_plugin/file_blueprint.xml
  addons/html_editor/static/tests/_helpers/format.js
  addons/html_editor/static/tests/chatgpt.test.js
  addons/html_editor/static/tests/data-oe/protected.test.js
  addons/html_editor/static/tests/font_awesome.test.js
  addons/html_editor/static/tests/icon.test.js
  addons/html_editor/static/tests/insert/html.test.js
  addons/html_editor/static/tests/keyboard/arrow.test.js
  addons/html_editor/static/tests/link/isolated.test.js
  addons/html_editor/static/tests/rating_star.test.js
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/l10n_in/data/uom_data.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/payment_flutterwave/__manifest__.py
  addons/payment_flutterwave/const.py
  addons/payment_flutterwave/controllers/main.py
  addons/payment_flutterwave/models/payment_transaction.py
  addons/payment_flutterwave/static/src/js/payment_form.js
  addons/payment_paypal/models/payment_transaction.py
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/static/tests/tours/utils/pos_sale_utils.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/wizard/stock_orderpoint_snooze.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_lot_valuation.py
  addons/survey/views/survey_templates.xml
  addons/web/static/src/core/pager/pager.js
  addons/web/static/src/views/kanban/kanban_compiler.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/form/form_compiler.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
Labels: 18.0

#32567 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_in/data/uom_data.xml
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/corporate/moduon.md
  doc/cla/corporate/tecnativa.md
Labels: staging.16.0

#32573 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_in/data/uom_data.xml
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  doc/cla/corporate/moduon.md
  doc/cla/corporate/tecnativa.md
Labels: tmp.16.0

#32575 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/calendar/models/calendar_event.py
  addons/html_editor/static/src/main/chatgpt/chatgpt_plugin.js
  addons/html_editor/static/src/main/media/media_plugin.js
  addons/html_editor/static/src/main/star_plugin.js
  addons/html_editor/static/src/others/embedded_components/core/file/static_file.xml
  addons/html_editor/static/src/others/embedded_components/plugins/embedded_file_plugin/file_blueprint.xml
  addons/html_editor/static/tests/_helpers/format.js
  addons/html_editor/static/tests/chatgpt.test.js
  addons/html_editor/static/tests/data-oe/protected.test.js
  addons/html_editor/static/tests/font_awesome.test.js
  addons/html_editor/static/tests/icon.test.js
  addons/html_editor/static/tests/insert/html.test.js
  addons/html_editor/static/tests/keyboard/arrow.test.js
  addons/html_editor/static/tests/link/isolated.test.js
  addons/html_editor/static/tests/rating_star.test.js
  addons/l10n_eg_edi_eta/models/account_move.py
  addons/l10n_in/data/uom_data.xml
  addons/l10n_it_edi/models/account_move.py
  addons/l10n_ke_edi_tremol/views/account_move_view.xml
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/payment_flutterwave/__manifest__.py
  addons/payment_flutterwave/const.py
  addons/payment_flutterwave/controllers/main.py
  addons/payment_flutterwave/models/payment_transaction.py
  addons/payment_flutterwave/static/src/js/payment_form.js
  addons/payment_paypal/models/payment_transaction.py
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/static/tests/tours/utils/pos_sale_utils.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/wizard/stock_orderpoint_snooze.py
  addons/stock_account/models/stock_move.py
  addons/stock_account/tests/test_lot_valuation.py
  addons/survey/views/survey_templates.xml
  addons/web/static/src/core/pager/pager.js
  addons/web/static/src/views/kanban/kanban_compiler.js
  addons/web/static/src/views/view_compiler.js
  addons/web/static/tests/views/form/form_compiler.test.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/scss/website.ui.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
Labels: tmp.18.0

#32577 Syncing from upstream odoo/odoo (18.0)
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: 18.0

#32578 Syncing from upstream odoo/odoo (master)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/resource/models/resource_calendar.py
  addons/web/static/tests/tours/test_user_group_settings_tour.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: master

#32579 Syncing from upstream odoo/odoo (saas-17.4)
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: saas-17.4

#32580 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/calendar/models/calendar_event.py
  addons/html_editor/static/src/main/chatgpt/chatgpt_plugin.js
  addons/html_editor/static/src/others/embedded_components/core/file/static_file.xml
  addons/html_editor/static/src/others/embedded_components/plugins/embedded_file_plugin/file_blueprint.xml
  addons/html_editor/static/src/others/qweb_plugin.js
  addons/html_editor/static/tests/chatgpt.test.js
  addons/html_editor/static/tests/qweb.test.js
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/tests/test_sync_odoo2microsoft_mail.py
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/sale_margin/models/sale_order_line.py
  addons/sale_stock_margin/models/sale_order_line.py
  addons/sale_stock_margin/tests/test_sale_stock_margin.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/web/static/src/views/kanban/kanban_record.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.editor.js
  odoo/addons/base/i18n/he.po
Labels: saas-18.1

#32581 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/resource/models/resource_calendar.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: saas-18.2

#32582 Syncing from upstream odoo/odoo (staging.master)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/resource/models/resource_calendar.py
  addons/web/static/tests/tours/test_user_group_settings_tour.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: staging.master

#32583 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: staging.saas-17.4

#32584 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/calendar/models/calendar_event.py
  addons/html_editor/static/src/main/chatgpt/chatgpt_plugin.js
  addons/html_editor/static/src/others/embedded_components/core/file/static_file.xml
  addons/html_editor/static/src/others/embedded_components/plugins/embedded_file_plugin/file_blueprint.xml
  addons/html_editor/static/tests/chatgpt.test.js
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/microsoft_calendar/models/calendar.py
  addons/microsoft_calendar/tests/test_sync_odoo2microsoft_mail.py
  addons/pos_sale/report/sale_report.py
  addons/pos_sale/tests/test_pos_sale_report.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.editor.js
Labels: staging.saas-18.1

#32585 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/resource/models/resource_calendar.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: staging.saas-18.2

#32586 Syncing from upstream odoo/odoo (staging.18.0)
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: staging.18.0

#32587 Syncing from upstream odoo/odoo (tmp.master)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/resource/models/resource_calendar.py
  addons/web/static/tests/tours/test_user_group_settings_tour.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.master

#32588 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: tmp.saas-17.4

#32590 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/hr_holidays/models/hr_leave_type.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/uom_data.xml
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/resource/models/resource_calendar.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: tmp.saas-18.2

#32591 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/l10n_uy/i18n/es_419.po
  addons/l10n_uy/i18n/l10n_uy.pot
  addons/l10n_uy/models/l10n_latam_document_type.py
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
Labels: tmp.18.0

#32593 Syncing from upstream odoo/odoo (master)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
  addons/mail/__manifest__.py
  addons/mail/data/mail_activity_type_data.xml
  addons/mail/demo/mail_activity_demo.xml
  addons/mail/models/mail_activity.py
  addons/mail/models/res_users.py
  addons/mail/static/src/core/common/core.dark.scss
  addons/mail/static/src/core/public_web/discuss.dark.scss
  addons/mail/static/src/core/public_web/discuss.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar.dark.scss
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail/tests/test_mail_activity.py
  addons/web/static/src/core/file_viewer/file_viewer.js
Labels: master

#32594 Syncing from upstream odoo/odoo (saas-17.4)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
Labels: saas-17.4

#32595 Syncing from upstream odoo/odoo (saas-18.1)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/tests/message/message.test.js
Labels: saas-18.1

#32597 Syncing from upstream odoo/odoo (staging.master)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
  addons/mail/__manifest__.py
  addons/mail/data/mail_activity_type_data.xml
  addons/mail/demo/mail_activity_demo.xml
  addons/mail/models/mail_activity.py
  addons/mail/models/res_users.py
  addons/mail/static/src/core/common/core.dark.scss
  addons/mail/static/src/core/public_web/discuss.dark.scss
  addons/mail/static/src/core/public_web/discuss.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar.dark.scss
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail/tests/test_mail_activity.py
  addons/web/static/src/core/file_viewer/file_viewer.js
Labels: staging.master

#32599 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/tests/message/message.test.js
Labels: staging.saas-18.1

#32602 Syncing from upstream odoo/odoo (tmp.master)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
  addons/mail/__manifest__.py
  addons/mail/data/mail_activity_type_data.xml
  addons/mail/demo/mail_activity_demo.xml
  addons/mail/models/mail_activity.py
  addons/mail/models/res_users.py
  addons/mail/static/src/core/common/core.dark.scss
  addons/mail/static/src/core/public_web/discuss.dark.scss
  addons/mail/static/src/core/public_web/discuss.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar.dark.scss
  addons/survey/tests/test_survey.py
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail/tests/test_mail_activity.py
  addons/web/static/src/core/file_viewer/file_viewer.js
Labels: tmp.master

#32603 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
Labels: tmp.saas-17.4

#32604 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/analytic/models/analytic_account.py
  addons/analytic/models/analytic_plan.py
  addons/analytic/tests/test_analytic_account.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/tests/message/message.test.js
Labels: tmp.saas-18.1

#32607 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_it_edi/models/account_invoice.py
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/service/server.py
Labels: 16.0

#32611 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/i18n/cs.po
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/calendar/i18n/ru.po
  addons/crm/i18n/ru.po
  addons/event/i18n/cs.po
  addons/event/i18n/pl.po
  addons/event_sale/i18n/pl.po
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_positive_discount_price_unit.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/export_xmls/invoice_lowercase_fields.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/mail/models/mail_followers.py
  addons/payment_xendit/controllers/main.py
  addons/payment_xendit/models/payment_transaction.py
  addons/payment_xendit/tests/test_payment_transaction.py
  addons/payment_xendit/tests/test_processing_flows.py
  addons/point_of_sale/i18n/fi.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/ko.po
  addons/point_of_sale/i18n/nl.po
  addons/point_of_sale/i18n/pt_BR.po
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/product/i18n/ru.po
  addons/purchase/i18n/ja.po
  addons/purchase/report/purchase_report.py
  addons/purchase_stock/i18n/ja.po
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_website_modules/tests/__init__.py
  addons/test_website_modules/tests/test_controllers.py
  addons/web/i18n/ru.po
  addons/web_editor/controllers/main.py
  addons/website_customer/views/website_customer_templates.xml
  addons/website_event/i18n/cs.po
  addons/website_event_exhibitor/i18n/cs.po
  addons/website_event_exhibitor/i18n/pl.po
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
  addons/website_sale_loyalty/i18n/fi.po
  addons/website_sale_loyalty/i18n/ja.po
  addons/website_sale_loyalty/i18n/ko.po
  addons/website_sale_loyalty/i18n/zh_TW.po
  addons/website_sale_stock_wishlist/i18n/fi.po
  addons/website_sale_wishlist/i18n/fi.po
  odoo/http.py
Labels: saas-17.4

#32621 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/i18n/cs.po
  addons/account/report/account_invoice_report.py
  addons/account/tests/test_account_invoice_report.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/calendar/i18n/ru.po
  addons/crm/i18n/ru.po
  addons/event/i18n/cs.po
  addons/event/i18n/pl.po
  addons/event_sale/i18n/pl.po
  addons/l10n_account_edi_ubl_cii_tests/tests/test_files/from_odoo/facturx_positive_discount_price_unit.xml
  addons/l10n_account_edi_ubl_cii_tests/tests/test_xml_cii_fr.py
  addons/l10n_it_edi/models/res_partner.py
  addons/l10n_it_edi/tests/export_xmls/invoice_lowercase_fields.xml
  addons/l10n_it_edi/tests/test_edi_export.py
  addons/l10n_it_edi_website_sale/views/templates.xml
  addons/mail/models/mail_followers.py
  addons/payment_xendit/controllers/main.py
  addons/payment_xendit/models/payment_transaction.py
  addons/payment_xendit/tests/test_payment_transaction.py
  addons/payment_xendit/tests/test_processing_flows.py
  addons/point_of_sale/i18n/fi.po
  addons/point_of_sale/i18n/ja.po
  addons/point_of_sale/i18n/ko.po
  addons/point_of_sale/i18n/nl.po
  addons/point_of_sale/i18n/pt_BR.po
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/pos_combo_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/product/i18n/ru.po
  addons/purchase/i18n/ja.po
  addons/purchase/report/purchase_report.py
  addons/purchase_stock/i18n/ja.po
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/test_mail/tests/test_mail_multicompany.py
  addons/test_website_modules/tests/__init__.py
  addons/test_website_modules/tests/test_controllers.py
  addons/web/i18n/ru.po
  addons/web_editor/controllers/main.py
  addons/website_customer/views/website_customer_templates.xml
  addons/website_event/i18n/cs.po
  addons/website_event_exhibitor/i18n/cs.po
  addons/website_event_exhibitor/i18n/pl.po
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  addons/website_sale/static/src/js/notification/cart_notification/cart_notification.js
  addons/website_sale_loyalty/i18n/fi.po
  addons/website_sale_loyalty/i18n/ja.po
  addons/website_sale_loyalty/i18n/ko.po
  addons/website_sale_loyalty/i18n/zh_TW.po
  addons/website_sale_stock_wishlist/i18n/fi.po
  addons/website_sale_wishlist/i18n/fi.po
  odoo/http.py
Labels: tmp.saas-17.4

#32627 Syncing from upstream odoo/odoo (16.0)
  addons/web/static/src/core/debug/profiling/profiling_item.xml
  odoo/tools/profiler.py
Labels: 16.0

#32628 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move_line.py
  addons/account/models/uom_uom.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_distance.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/tests/test_ewaybill_stock.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/uom_uom.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/tests/common_setup_methods.py
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/repair/models/repair.py
  addons/repair/tests/test_repair.py
  addons/sms/i18n/sms.pot
  addons/sms/models/ir_actions_server.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_proc_rule.py
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
  odoo/service/server.py
Labels: 17.0

#32631 Syncing from upstream odoo/odoo (saas-17.4)
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/wizard/fleet_vehicle_send_mail.py
  addons/l10n_sa_pos/__manifest__.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_sale/models/website_snippet_filter.py
  odoo/service/server.py
Labels: saas-17.4

#32637 Syncing from upstream odoo/odoo (staging.16.0)
  addons/web/static/src/core/debug/profiling/profiling_item.xml
  odoo/tools/profiler.py
Labels: staging.16.0

#32638 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move_line.py
  addons/account/models/uom_uom.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_distance.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/tests/test_ewaybill_stock.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/uom_uom.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/tests/common_setup_methods.py
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/repair/models/repair.py
  addons/repair/tests/test_repair.py
  addons/sms/i18n/sms.pot
  addons/sms/models/ir_actions_server.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_proc_rule.py
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
  odoo/service/server.py
Labels: staging.17.0

#32641 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/fleet/models/fleet_vehicle.py
  addons/fleet/wizard/fleet_vehicle_send_mail.py
  addons/l10n_sa_pos/__manifest__.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/stock_account/tests/test_stockvaluation.py
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/website_sale/models/website_snippet_filter.py
  odoo/service/server.py
Labels: tmp.saas-17.4

#32644 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/web/static/src/core/debug/profiling/profiling_item.xml
  odoo/tools/profiler.py
Labels: tmp.16.0

#32645 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move_line.py
  addons/account/models/uom_uom.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_distance.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/tests/test_ewaybill_stock.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/uom_uom.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mass_mailing/models/mailing.py
  addons/mass_mailing/tests/test_mailing_internals.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/tests/common_setup_methods.py
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/repair/models/repair.py
  addons/repair/tests/test_repair.py
  addons/sms/i18n/sms.pot
  addons/sms/models/ir_actions_server.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock/tests/test_proc_rule.py
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager_tests.js
  addons/web_editor/static/src/components/media_dialog/media_dialog.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
  odoo/service/server.py
Labels: tmp.17.0

#32647 Syncing from upstream odoo/odoo (16.0)
  addons/hw_drivers/tools/helpers.py
  addons/l10n_ee/__manifest__.py
  addons/l10n_ee/data/account_fiscal_position_template_data.xml
  addons/l10n_ee/data/account_tax_group_data.xml
  addons/l10n_ee/data/account_tax_template_data.xml
  addons/l10n_ee/i18n/et.po
  addons/l10n_ee/i18n/l10n_ee.pot
  addons/l10n_ee/migrations/1.2/post-migrate_update_taxes.py
  addons/l10n_sa_edi/models/account_edi_format.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: 16.0

#32648 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_analytic_line.py
  addons/account/tests/test_account_analytic.py
  addons/account_debit_note/models/account_move.py
  addons/analytic/models/analytic_line.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/mail/models/ir_model_fields.py
  addons/partner_autocomplete/__manifest__.py
  addons/partner_autocomplete/i18n/partner_autocomplete.pot
  addons/partner_autocomplete/models/iap_autocomplete_api.py
  addons/partner_autocomplete/models/res_company.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/models/res_partner_autocomplete_sync.py
  addons/partner_autocomplete/static/img/crunchbase.ico
  addons/partner_autocomplete/static/img/facebook.ico
  addons/partner_autocomplete/static/img/linkedin.ico
  addons/partner_autocomplete/static/img/twitter.ico
  addons/partner_autocomplete/static/src/js/partner_autocomplete_component.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/partner_autocomplete/tests/common.py
  addons/partner_autocomplete/tests/test_res_company.py
  addons/repair/models/repair.py
  addons/repair/models/stock_lot.py
  addons/repair/tests/test_repair.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale_project/models/project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/test_mail/tests/test_message_track.py
  addons/web/static/src/views/calendar/calendar_model.js
  odoo/addons/base/models/res_company.py
  odoo/addons/test_lint/tests/test_pylint.py
Labels: 17.0

#32651 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move_line.py
  addons/account/models/uom_uom.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_distance.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/tests/test_ewaybill_stock.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/uom_uom.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/utils.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_kiosk_tour.js
  addons/pos_self_order/tests/test_self_order_kiosk.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager.test.js
  odoo/addons/test_lint/tests/test_pylint.py
Labels: saas-17.4

#32657 Syncing from upstream odoo/odoo (staging.16.0)
  addons/hw_drivers/tools/helpers.py
  addons/l10n_ee/__manifest__.py
  addons/l10n_ee/data/account_fiscal_position_template_data.xml
  addons/l10n_ee/data/account_tax_group_data.xml
  addons/l10n_ee/data/account_tax_template_data.xml
  addons/l10n_ee/i18n/et.po
  addons/l10n_ee/i18n/l10n_ee.pot
  addons/l10n_ee/migrations/1.2/post-migrate_update_taxes.py
  addons/l10n_sa_edi/models/account_edi_format.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: staging.16.0

#32658 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_analytic_line.py
  addons/account/tests/test_account_analytic.py
  addons/account_debit_note/models/account_move.py
  addons/analytic/models/analytic_line.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/mail/models/ir_model_fields.py
  addons/partner_autocomplete/__manifest__.py
  addons/partner_autocomplete/i18n/partner_autocomplete.pot
  addons/partner_autocomplete/models/iap_autocomplete_api.py
  addons/partner_autocomplete/models/res_company.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/models/res_partner_autocomplete_sync.py
  addons/partner_autocomplete/static/img/crunchbase.ico
  addons/partner_autocomplete/static/img/facebook.ico
  addons/partner_autocomplete/static/img/linkedin.ico
  addons/partner_autocomplete/static/img/twitter.ico
  addons/partner_autocomplete/static/src/js/partner_autocomplete_component.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/partner_autocomplete/tests/common.py
  addons/partner_autocomplete/tests/test_res_company.py
  addons/repair/models/repair.py
  addons/repair/models/stock_lot.py
  addons/repair/tests/test_repair.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale_project/models/project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/test_mail/tests/test_message_track.py
  addons/web/static/src/views/calendar/calendar_model.js
  odoo/addons/base/models/res_company.py
  odoo/addons/test_lint/tests/test_pylint.py
Labels: staging.17.0

#32661 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move_line.py
  addons/account/models/uom_uom.py
  addons/l10n_es_edi_facturae/data/facturae_templates.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_facturae/tests/data/expected_refund_document.xml
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_distance.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/tests/test_ewaybill_stock.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/uom_uom.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mrp/models/mrp_production.py
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/utils.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_kiosk_tour.js
  addons/pos_self_order/tests/test_self_order_kiosk.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/web/static/src/views/debug_items.js
  addons/web/static/tests/core/debug/debug_manager.test.js
  odoo/addons/test_lint/tests/test_pylint.py
Labels: tmp.saas-17.4

#32664 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hw_drivers/tools/helpers.py
  addons/l10n_ee/__manifest__.py
  addons/l10n_ee/data/account_fiscal_position_template_data.xml
  addons/l10n_ee/data/account_tax_group_data.xml
  addons/l10n_ee/data/account_tax_template_data.xml
  addons/l10n_ee/i18n/et.po
  addons/l10n_ee/i18n/l10n_ee.pot
  addons/l10n_ee/migrations/1.2/post-migrate_update_taxes.py
  addons/l10n_sa_edi/models/account_edi_format.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/test_lint/tests/test_pylint.py
  odoo/modules/registry.py
  odoo/sql_db.py
  odoo/tests/common.py
Labels: tmp.16.0

#32665 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_analytic_line.py
  addons/account/tests/test_account_analytic.py
  addons/account_debit_note/models/account_move.py
  addons/analytic/models/analytic_line.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/mail/models/ir_model_fields.py
  addons/partner_autocomplete/__manifest__.py
  addons/partner_autocomplete/i18n/partner_autocomplete.pot
  addons/partner_autocomplete/models/iap_autocomplete_api.py
  addons/partner_autocomplete/models/res_company.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/models/res_partner_autocomplete_sync.py
  addons/partner_autocomplete/static/img/crunchbase.ico
  addons/partner_autocomplete/static/img/facebook.ico
  addons/partner_autocomplete/static/img/linkedin.ico
  addons/partner_autocomplete/static/img/twitter.ico
  addons/partner_autocomplete/static/src/js/partner_autocomplete_component.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/partner_autocomplete/tests/common.py
  addons/partner_autocomplete/tests/test_res_company.py
  addons/repair/models/repair.py
  addons/repair/models/stock_lot.py
  addons/repair/tests/test_repair.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale_project/models/project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/test_mail/tests/test_message_track.py
  addons/web/static/src/views/calendar/calendar_model.js
  odoo/addons/base/models/res_company.py
  odoo/addons/test_lint/tests/test_pylint.py
Labels: tmp.17.0

#32687 Syncing from upstream odoo/odoo (16.0)
  addons/payment_adyen/controllers/main.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: 16.0

#32688 Syncing from upstream odoo/odoo (17.0)
  addons/l10n_de/models/res_company.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_ro_efactura/models/account_move.py
  addons/l10n_ro_efactura/models/ciusro_document.py
  addons/loyalty/models/loyalty_card.py
  addons/payment_adyen/controllers/main.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/stock/models/stock_quant.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: 17.0

#32689 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_move_send.py
  addons/account/models/ir_attachment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_analytic.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/analytic/models/analytic_line.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/l10n_in/models/res_partner.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/loyalty/models/loyalty_card.py
  addons/payment/models/payment_method.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/web/views/report_templates.xml
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  doc/cla/individual/etobella.md
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
  odoo/tools/mail.py
Labels: 18.0

#32691 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/ir_attachment.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_edi_ubl_cii/tests/test_files/bis3_bill_without_tax.xml
  addons/account_edi_ubl_cii/tests/test_ubl_cii.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/composer.xml
  addons/mrp/models/stock_rule.py
  addons/partner_autocomplete/__manifest__.py
  addons/partner_autocomplete/i18n/partner_autocomplete.pot
  addons/partner_autocomplete/models/iap_autocomplete_api.py
  addons/partner_autocomplete/models/res_company.py
  addons/partner_autocomplete/models/res_partner.py
  addons/partner_autocomplete/models/res_partner_autocomplete_sync.py
  addons/partner_autocomplete/static/img/crunchbase.ico
  addons/partner_autocomplete/static/img/facebook.ico
  addons/partner_autocomplete/static/img/linkedin.ico
  addons/partner_autocomplete/static/img/twitter.ico
  addons/partner_autocomplete/static/src/js/partner_autocomplete_component.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_core.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/partner_autocomplete/static/src/js/partner_autocomplete_many2one.js
  addons/partner_autocomplete/static/src/scss/partner_autocomplete.scss
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/partner_autocomplete/tests/common.py
  addons/partner_autocomplete/tests/test_res_company.py
  addons/payment/models/payment_method.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/sale_project/models/project_project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_tabs/options.js
  doc/cla/individual/etobella.md
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
Labels: saas-17.4

#32692 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_move_send.py
  addons/account/models/ir_attachment.py
  addons/account/models/sequence_mixin.py
  addons/account/static/src/components/product_catalog/kanban_controller.js
  addons/account/tests/test_account_analytic.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/analytic/models/analytic_line.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/core/line_break_plugin.js
  addons/html_editor/static/src/core/split_plugin.js
  addons/html_editor/static/src/main/feff_plugin.js
  addons/html_editor/static/src/main/font/font_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/tests/color.test.js
  addons/html_editor/static/tests/format/underline.test.js
  addons/html_editor/static/tests/insert/line_break.test.js
  addons/html_editor/static/tests/insert/paragraph_break.test.js
  addons/html_editor/static/tests/list/paragraph_break.test.js
  addons/hw_drivers/tools/helpers.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/im_livechat/tests/test_chatbot_internals.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/loyalty/models/loyalty_card.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/rtc_session_model.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/payment/models/payment_method.py
  addons/product/models/product_catalog_mixin.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_order_product_catalog.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_pdf_quote_builder/views/sale_order_template_views.xml
  addons/spreadsheet/models/spreadsheet_mixin.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/core/select_menu/select_menu.js
  addons/web/static/src/views/fields/many2one/many2one_field.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/views/report_templates.xml
  addons/website/static/src/components/translator/translator.js
  addons/website_customer/views/website_customer_templates.xml
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  odoo/tools/mail.py
Labels: saas-18.1

#32695 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_move_send.py
  addons/account/models/ir_attachment.py
  addons/account/models/sequence_mixin.py
  addons/account/static/src/components/product_catalog/kanban_controller.js
  addons/account/tests/test_account_analytic.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/analytic/models/analytic_line.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/core/line_break_plugin.js
  addons/html_editor/static/src/core/split_plugin.js
  addons/html_editor/static/src/main/feff_plugin.js
  addons/html_editor/static/src/main/font/font_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/tests/color.test.js
  addons/html_editor/static/tests/format/underline.test.js
  addons/html_editor/static/tests/insert/line_break.test.js
  addons/html_editor/static/tests/insert/paragraph_break.test.js
  addons/html_editor/static/tests/list/paragraph_break.test.js
  addons/hw_drivers/tools/helpers.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/im_livechat/tests/test_chatbot_internals.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/loyalty/models/loyalty_card.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/rtc_session_model.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/payment/models/payment_method.py
  addons/product/models/product_catalog_mixin.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_order_product_catalog.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_pdf_quote_builder/views/sale_order_template_views.xml
  addons/spreadsheet/models/spreadsheet_mixin.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/core/select_menu/select_menu.js
  addons/web/static/src/views/fields/many2one/many2one_field.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/views/report_templates.xml
  addons/website/static/src/components/translator/translator.js
  addons/website_customer/views/website_customer_templates.xml
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  odoo/tools/mail.py
Labels: staging.saas-18.1

#32697 Syncing from upstream odoo/odoo (staging.16.0)
  addons/payment_adyen/controllers/main.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: staging.16.0

#32698 Syncing from upstream odoo/odoo (staging.17.0)
  addons/l10n_de/models/res_company.py
  addons/l10n_ro_efactura/models/account_move.py
  addons/l10n_ro_efactura/models/ciusro_document.py
  addons/loyalty/models/loyalty_card.py
  addons/payment_adyen/controllers/main.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/stock/models/stock_quant.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: staging.17.0

#32699 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_move_send.py
  addons/account/models/ir_attachment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_analytic.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/analytic/models/analytic_line.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/l10n_in/models/res_partner.py
  addons/loyalty/models/loyalty_card.py
  addons/payment/models/payment_method.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/web/views/report_templates.xml
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  doc/cla/individual/etobella.md
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
  odoo/tools/mail.py
Labels: staging.18.0

#32702 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_move_send.py
  addons/account/models/ir_attachment.py
  addons/account/models/sequence_mixin.py
  addons/account/static/src/components/product_catalog/kanban_controller.js
  addons/account/tests/test_account_analytic.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/analytic/models/analytic_line.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/core/line_break_plugin.js
  addons/html_editor/static/src/core/split_plugin.js
  addons/html_editor/static/src/main/feff_plugin.js
  addons/html_editor/static/src/main/font/font_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/tests/color.test.js
  addons/html_editor/static/tests/format/underline.test.js
  addons/html_editor/static/tests/insert/line_break.test.js
  addons/html_editor/static/tests/insert/paragraph_break.test.js
  addons/html_editor/static/tests/list/paragraph_break.test.js
  addons/hw_drivers/tools/helpers.py
  addons/im_livechat/models/chatbot_script_step.py
  addons/im_livechat/tests/test_chatbot_internals.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_it_stock_ddt/report/l10n_it_ddt_report.xml
  addons/loyalty/models/loyalty_card.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/rtc_session_model.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/payment/models/payment_method.py
  addons/product/models/product_catalog_mixin.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale/tests/__init__.py
  addons/sale/tests/test_sale_order_product_catalog.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_pdf_quote_builder/views/sale_order_template_views.xml
  addons/spreadsheet/models/spreadsheet_mixin.py
  addons/stock/models/stock_move_line.py
  addons/stock/tests/test_move.py
  addons/stock_account/models/stock_move.py
  addons/web/static/src/core/select_menu/select_menu.js
  addons/web/static/src/views/fields/many2one/many2one_field.xml
  addons/web/static/src/views/form/form_controller.scss
  addons/web/views/report_templates.xml
  addons/website/static/src/components/translator/translator.js
  addons/website_customer/views/website_customer_templates.xml
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  odoo/tools/mail.py
Labels: tmp.saas-18.1

#32704 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/payment_adyen/controllers/main.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
Labels: tmp.16.0

#32705 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/l10n_de/models/res_company.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_ro_efactura/models/account_move.py
  addons/l10n_ro_efactura/models/ciusro_document.py
  addons/loyalty/models/loyalty_card.py
  addons/payment_adyen/controllers/main.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/stock/models/stock_quant.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: tmp.17.0

#32706 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_analytic_line.py
  addons/account/models/account_move_send.py
  addons/account/models/ir_attachment.py
  addons/account/models/sequence_mixin.py
  addons/account/tests/test_account_analytic.py
  addons/account/tests/test_account_incoming_supplier_invoice.py
  addons/analytic/models/analytic_line.py
  addons/hr_timesheet/models/hr_timesheet.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/l10n_in/models/res_partner.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/loyalty/models/loyalty_card.py
  addons/payment/models/payment_method.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_proc_rule.py
  addons/web/views/report_templates.xml
  addons/website/static/src/components/translator/translator.js
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website_mass_mailing/static/src/js/website_mass_mailing.js
  doc/cla/individual/etobella.md
  odoo/addons/test_read_group/tests/test_m2m_grouping.py
  odoo/models.py
  odoo/tools/mail.py
Labels: tmp.18.0

#32709 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_move_send.py
  addons/l10n_in/models/res_partner.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_adyen/controllers/main.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: master

#32710 Syncing from upstream odoo/odoo (saas-17.4)
  addons/payment_adyen/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: saas-17.4

#32711 Syncing from upstream odoo/odoo (saas-18.1)
  addons/l10n_in/models/res_partner.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_adyen/controllers/main.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: saas-18.1

#32713 Syncing from upstream odoo/odoo (staging.master)
  addons/account/models/account_move_send.py
  addons/l10n_in/models/res_partner.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_adyen/controllers/main.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: staging.master

#32714 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/l10n_in/models/res_partner.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_adyen/controllers/main.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: staging.saas-18.1

#32718 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_move_send.py
  addons/l10n_in/models/res_partner.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_adyen/controllers/main.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: tmp.master

#32719 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/payment_adyen/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: tmp.saas-17.4

#32720 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/l10n_in/models/res_partner.py
  addons/payment/models/payment_transaction.py
  addons/payment/tests/test_flows.py
  addons/payment_adyen/controllers/main.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/tabs.test.js
Labels: tmp.saas-18.1

#32724 Syncing from upstream odoo/odoo (18.0)
  addons/mrp/models/stock_rule.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
Labels: 18.0

#32725 Syncing from upstream odoo/odoo (master)
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/account_journal.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_quant.py
Labels: master

#32728 Syncing from upstream odoo/odoo (saas-18.2)
  addons/mail/static/src/core/common/chat_window.scss
  addons/mail/static/src/core/common/chat_window.xml
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/core/common/core.scss
  addons/mail/static/src/core/common/message.dark.scss
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/public_web/discuss.dark.scss
  addons/mail/static/src/core/public_web/discuss.scss
  addons/mail/static/src/core/public_web/discuss.xml
  addons/mail/static/src/core/public_web/discuss_sidebar.scss
  addons/mail/static/src/core/public_web/messaging_menu.dark.scss
  addons/mail/static/src/core/public_web/messaging_menu.xml
  addons/mail/static/src/core/public_web/notification_item.dark.scss
  addons/mail/static/src/core/public_web/notification_item.scss
  addons/mail/static/src/core/public_web/notification_item.xml
  addons/mail/static/src/core/web/discuss_sidebar_mailboxes.xml
  addons/mail/static/src/core/web/discuss_sidebar_patch.xml
  addons/mail/static/src/discuss/core/common/channel_invitation.xml
  addons/mail/static/src/discuss/core/common/channel_member_list.xml
  addons/mail/static/src/discuss/core/public_web/discuss_command_palette.scss
  addons/mail/static/src/discuss/core/public_web/discuss_command_palette.xml
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.dark.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.js
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.xml
  addons/mail/static/src/discuss/message_pin/common/thread_model_patch.js
  addons/mail/static/src/model/record_internal.js
  addons/mail/static/src/model/store.js
  addons/mail/static/src/model/store_internal.js
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock/models/stock_quant.py
Labels: saas-18.2

#32729 Syncing from upstream odoo/odoo (staging.master)
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/account_journal.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_quant.py
Labels: staging.master

#32731 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/mail/static/src/core/common/chat_window.scss
  addons/mail/static/src/core/common/chat_window.xml
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/core/common/core.scss
  addons/mail/static/src/core/common/message.dark.scss
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/public_web/discuss.dark.scss
  addons/mail/static/src/core/public_web/discuss.scss
  addons/mail/static/src/core/public_web/discuss.xml
  addons/mail/static/src/core/public_web/discuss_sidebar.scss
  addons/mail/static/src/core/public_web/messaging_menu.dark.scss
  addons/mail/static/src/core/public_web/messaging_menu.xml
  addons/mail/static/src/core/public_web/notification_item.dark.scss
  addons/mail/static/src/core/public_web/notification_item.scss
  addons/mail/static/src/core/public_web/notification_item.xml
  addons/mail/static/src/core/web/discuss_sidebar_mailboxes.xml
  addons/mail/static/src/core/web/discuss_sidebar_patch.xml
  addons/mail/static/src/discuss/core/common/channel_invitation.xml
  addons/mail/static/src/discuss/core/common/channel_member_list.xml
  addons/mail/static/src/discuss/core/public_web/discuss_command_palette.scss
  addons/mail/static/src/discuss/core/public_web/discuss_command_palette.xml
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.dark.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.js
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.xml
  addons/mail/static/src/discuss/message_pin/common/thread_model_patch.js
  addons/mail/static/src/model/record_internal.js
  addons/mail/static/src/model/store.js
  addons/mail/static/src/model/store_internal.js
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock/models/stock_quant.py
Labels: staging.saas-18.2

#32732 Syncing from upstream odoo/odoo (staging.18.0)
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/mrp/models/stock_rule.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
Labels: staging.18.0

#32733 Syncing from upstream odoo/odoo (tmp.master)
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/models/account_journal.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_quant.py
Labels: tmp.master

#32736 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/mail/static/src/core/common/chat_window.scss
  addons/mail/static/src/core/common/chat_window.xml
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/core/common/composer.xml
  addons/mail/static/src/core/common/core.scss
  addons/mail/static/src/core/common/message.dark.scss
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message.scss
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_in_reply.xml
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/core/public_web/discuss.dark.scss
  addons/mail/static/src/core/public_web/discuss.scss
  addons/mail/static/src/core/public_web/discuss.xml
  addons/mail/static/src/core/public_web/discuss_sidebar.scss
  addons/mail/static/src/core/public_web/messaging_menu.dark.scss
  addons/mail/static/src/core/public_web/messaging_menu.xml
  addons/mail/static/src/core/public_web/notification_item.dark.scss
  addons/mail/static/src/core/public_web/notification_item.scss
  addons/mail/static/src/core/public_web/notification_item.xml
  addons/mail/static/src/core/web/discuss_sidebar_mailboxes.xml
  addons/mail/static/src/core/web/discuss_sidebar_patch.xml
  addons/mail/static/src/discuss/core/common/channel_invitation.xml
  addons/mail/static/src/discuss/core/common/channel_member_list.xml
  addons/mail/static/src/discuss/core/public_web/discuss_command_palette.scss
  addons/mail/static/src/discuss/core/public_web/discuss_command_palette.xml
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.dark.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.js
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.scss
  addons/mail/static/src/discuss/core/public_web/discuss_sidebar_categories.xml
  addons/mail/static/src/discuss/message_pin/common/thread_model_patch.js
  addons/mail/static/src/model/record_internal.js
  addons/mail/static/src/model/store.js
  addons/mail/static/src/model/store_internal.js
  addons/mrp/models/stock_rule.py
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/__init__.py
  addons/point_of_sale/models/account_cash_rounding.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/stock/models/stock_quant.py
Labels: tmp.saas-18.2

#32737 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/mrp/models/stock_rule.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
Labels: tmp.18.0

#32739 Syncing from upstream odoo/odoo (16.0)
  addons/hw_drivers/main.py
  addons/point_of_sale/tools/posbox/configuration/migrate_config.sh
  addons/pos_loyalty/tests/test_frontend.py
  addons/pos_sale_loyalty/tests/test_pos_sale_loyalty.py
  addons/web_editor/controllers/main.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/tests/tours/popup_visibility_option.js
  addons/website/tests/test_ui.py
  odoo/tools/image.py
Labels: 16.0

#32740 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/sequence_mixin.py
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/hr_contract/views/hr_contract_views.xml
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_hu_edi/views/report_invoice.xml
  addons/l10n_jo_edi/data/ubl_jo_templates.xml
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/website_cf_turnstile/static/src/js/turnstile.js
  addons/website_cf_turnstile/static/src/xml/turnstile.xml
Labels: 17.0

#32741 Syncing from upstream odoo/odoo (18.0)
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_de/models/res_company.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/l10n_sa/models/account_move.py
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/ir_attachment.py
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/marketing_card/__manifest__.py
  addons/marketing_card/i18n/marketing_card.pot
  addons/marketing_card/models/card_campaign.py
  addons/marketing_card/static/src/scss/mass_mailing.scss
  addons/marketing_card/views/card_campaign_views.xml
  addons/marketing_card/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_self_order/controllers/orders.py
  addons/product/report/product_pricelist_report.py
  addons/project_mrp/views/mrp_production_views.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_project/models/project_project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_quant.py
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale/views/variant_templates.xml
  odoo/addons/base/tests/test_res_partner.py
Labels: 18.0

#32745 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/tests/test_mail_tracking_value.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/base_automation/models/base_automation.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_de/models/res_company.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/loyalty/models/loyalty_card.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_followers_edit.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/tests/test_stock.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/pos_restaurant/static/src/app/screens/floor_screen/floor_screen.scss
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_pdf_quote_builder/views/sale_order_template_views.xml
  addons/stock/data/stock_demo.xml
  addons/test_import_export/tests/test_load.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/views/snippets/snippets.xml
  odoo/orm/models.py
  odoo/service/server.py
Labels: saas-18.2

#32747 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_br_website_sale/static/tests/tours/brazilian_address.js
  addons/l10n_de/models/res_company.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/mail/models/mail_thread.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/tests/pos/tours/product_screen_tour.js
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_orderpoint.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/test_website/static/tests/tours/systray.js
  addons/web/static/src/core/macro.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_tour/static/src/tour_service/tour_helpers.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/static/tests/tours/client_action_redirect.js
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/snippets.xml
  addons/website_livechat/static/tests/tours/lazy_frontend_bus_tour.js
  addons/website_livechat/static/tests/tours/website_livechat_common.js
  addons/website_livechat/static/tests/tours/website_livechat_no_new_session_with_hide_rule.js
  odoo/orm/models.py
  odoo/service/server.py
Labels: staging.saas-18.1

#32748 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account/tests/test_mail_tracking_value.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/base_automation/models/base_automation.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_de/models/res_company.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/loyalty/models/loyalty_card.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_followers_edit.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/tests/test_stock.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/pos_restaurant/static/src/app/screens/floor_screen/floor_screen.scss
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_pdf_quote_builder/views/sale_order_template_views.xml
  addons/stock/data/stock_demo.xml
  addons/test_import_export/tests/test_load.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/views/snippets/snippets.xml
  odoo/orm/models.py
  odoo/service/server.py
Labels: staging.saas-18.2

#32751 Syncing from upstream odoo/odoo (staging.18.0)
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_de/models/res_company.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/l10n_sa/models/account_move.py
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/ir_attachment.py
  addons/marketing_card/__manifest__.py
  addons/marketing_card/i18n/marketing_card.pot
  addons/marketing_card/models/card_campaign.py
  addons/marketing_card/static/src/scss/mass_mailing.scss
  addons/marketing_card/views/card_campaign_views.xml
  addons/marketing_card/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_self_order/controllers/orders.py
  addons/product/report/product_pricelist_report.py
  addons/project_mrp/views/mrp_production_views.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_project/models/project_project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_quant.py
  addons/web/static/src/core/autocomplete/autocomplete.xml
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web_tour/static/src/tour_service/tour_interactive.js
  addons/web_tour/static/src/tour_service/tour_step.js
  addons/web_tour/static/tests/tour_interactive.test.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale/views/variant_templates.xml
  odoo/addons/base/tests/test_res_partner.py
Labels: staging.18.0

#32753 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_de/models/res_company.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/mrp/data/mrp_demo.xml
  addons/stock/data/stock_demo.xml
Labels: tmp.saas-17.4

#32754 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_br_website_sale/static/tests/tours/brazilian_address.js
  addons/l10n_de/models/res_company.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/mail/models/mail_thread.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/tests/test_stock.py
  addons/point_of_sale/static/tests/pos/tours/product_screen_tour.js
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_orderpoint.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/test_website/static/tests/tours/systray.js
  addons/web/static/src/core/macro.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_tour/static/src/tour_service/tour_helpers.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/static/tests/tours/client_action_redirect.js
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/snippets.xml
  addons/website_livechat/static/tests/tours/lazy_frontend_bus_tour.js
  addons/website_livechat/static/tests/tours/website_livechat_common.js
  addons/website_livechat/static/tests/tours/website_livechat_no_new_session_with_hide_rule.js
  odoo/orm/models.py
  odoo/service/server.py
Labels: tmp.saas-18.1

#32755 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account/tests/test_mail_tracking_value.py
  addons/barcodes_gs1_nomenclature/models/barcode_nomenclature.py
  addons/barcodes_gs1_nomenclature/tests/test_barcodes_gs1_nomenclature.py
  addons/base_automation/models/base_automation.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_de/models/res_company.py
  addons/l10n_id/models/res_bank.py
  addons/l10n_id_pos/tests/test_qris_pos.py
  addons/loyalty/models/loyalty_card.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_thread.py
  addons/mail/wizard/mail_followers_edit.py
  addons/mrp/data/mrp_demo.xml
  addons/mrp/tests/test_stock.py
  addons/pos_mrp/__manifest__.py
  addons/pos_mrp/security/ir.model.access.csv
  addons/pos_mrp/static/tests/tours/pos_mrp_tour.js
  addons/pos_mrp/tests/__init__.py
  addons/pos_mrp/tests/test_frontend.py
  addons/pos_restaurant/static/src/app/screens/floor_screen/floor_screen.scss
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/sale_loyalty/models/loyalty_card.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_pdf_quote_builder/views/sale_order_template_views.xml
  addons/stock/data/stock_demo.xml
  addons/test_import_export/tests/test_load.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mass_mailing/tests/test_performance.py
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_tabs/options.js
  addons/website/views/snippets/snippets.xml
  odoo/orm/models.py
  odoo/service/server.py
Labels: tmp.saas-18.2

#32758 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_de/models/res_company.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/l10n_sa/models/account_move.py
  addons/l10n_sa_edi/models/__init__.py
  addons/l10n_sa_edi/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_journal.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/models/ir_attachment.py
  addons/mail/static/src/discuss/call/common/call_participant_video.js
  addons/marketing_card/__manifest__.py
  addons/marketing_card/i18n/marketing_card.pot
  addons/marketing_card/models/card_campaign.py
  addons/marketing_card/static/src/scss/mass_mailing.scss
  addons/marketing_card/views/card_campaign_views.xml
  addons/marketing_card/views/mailing_mailing_views.xml
  addons/mass_mailing_sms/views/mailing_mailing_views.xml
  addons/mrp/data/mrp_demo.xml
  addons/point_of_sale/models/pos_session.py
  addons/pos_self_order/controllers/orders.py
  addons/product/report/product_pricelist_report.py
  addons/project_mrp/views/mrp_production_views.xml
  addons/sale/views/sale_order_views.xml
  addons/sale_project/models/project_project.py
  addons/sale_project_stock/tests/__init__.py
  addons/sale_project_stock/tests/test_sale_project_stock_profitability.py
  addons/sale_timesheet/models/account_move.py
  addons/stock/data/stock_demo.xml
  addons/stock/models/stock_quant.py
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website_sale/views/variant_templates.xml
  odoo/addons/base/tests/test_res_partner.py
Labels: tmp.18.0

#32738 [t158878][MIG][18.0] odoo core updates based on our changes in v15
  addons/account/controllers/portal.py
  addons/account/models/account_account.py
  addons/account/models/account_analytic_account.py
  addons/account/models/account_bank_statement.py
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_journal_dashboard.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_move_send.py
  addons/account/models/company.py
  addons/account/models/digest.py
  addons/account/models/partner.py
  addons/account/models/product.py
  addons/account/views/account_move_views.xml
  addons/account/views/account_portal_templates.xml
  addons/account/views/report_invoice.xml
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/account/wizard/account_move_reversal.py
  addons/account/wizard/account_payment_register.py
  addons/account/wizard/account_secure_entries_wizard.py
  addons/l10n_ch/models/res_bank.py
  addons/l10n_ch/report/swissqr_report.xml
  addons/mrp/models/mrp_bom.py
  addons/point_of_sale/models/pos_category.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_payment_method.py
  addons/point_of_sale/models/pos_session.py
  addons/product/models/product_product.py
  addons/stock/models/product.py
  addons/web/controllers/report.py
Labels: 18.0.project_sv_559

#32779 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_json.py
  addons/mail/models/mail_thread.py
  addons/project/models/project.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/web/static/tests/core/scroller_service_tests.js
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  doc/cla/corporate/moduon.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: 16.0

#32781 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_payment_term.py
  addons/account_peppol/tools/demo_utils.py
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_constraints.py
  addons/mail/controllers/google_translate.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/tests/test_mail_message_translate.py
  addons/payment/tests/test_payment_transaction.py
  addons/payment_asiapay/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_worldline/tests/common.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/tests/tours/pos_cash_rounding_tour.js
  addons/point_of_sale/tests/test_pos_cash_rounding.py
  addons/pos_self_order/static/src/app/pages/product_list_page/product_list_page.scss
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/website/static/src/snippets/s_image_gallery/options.js
Labels: 18.0

#32785 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/html_editor/controllers/main.py
  addons/im_livechat/tests/test_user_livechat_username.py
  addons/l10n_es/models/account_move.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/controllers/google_translate.py
  addons/mail/models/discuss/discuss_channel_member.py
  addons/mail/static/src/discuss/call/common/call.xml
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/tests/test_mail_message_translate.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/address.js
  addons/portal/tests/test_addresses.py
  addons/portal_rating/static/src/chatter/frontend/composer_patch.js
  addons/portal_rating/static/src/chatter/frontend/message_patch.js
  addons/pos_self_order/static/src/app/components/combo_selection/combo_selection.js
  addons/pos_self_order/static/src/app/components/combo_selection/combo_selection.xml
  addons/pos_self_order/static/src/app/components/product_info_popup/product_info_popup.js
  addons/pos_self_order/static/src/app/components/product_info_popup/product_info_popup.xml
  addons/pos_self_order/static/src/app/pages/product_list_page/product_list_page.scss
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/interactions/dropdown/hoverable_dropdown.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/static/src/snippets/s_website_form/form.js
  addons/website_sale/controllers/main.py
Labels: saas-18.2

#32788 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/html_editor/controllers/main.py
  addons/im_livechat/tests/test_user_livechat_username.py
  addons/l10n_es/models/account_move.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/controllers/google_translate.py
  addons/mail/models/discuss/discuss_channel_member.py
  addons/mail/static/src/discuss/call/common/call.xml
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/tests/test_mail_message_translate.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/address.js
  addons/portal/tests/test_addresses.py
  addons/portal_rating/static/src/chatter/frontend/composer_patch.js
  addons/portal_rating/static/src/chatter/frontend/message_patch.js
  addons/pos_self_order/static/src/app/components/combo_selection/combo_selection.js
  addons/pos_self_order/static/src/app/components/combo_selection/combo_selection.xml
  addons/pos_self_order/static/src/app/components/product_info_popup/product_info_popup.js
  addons/pos_self_order/static/src/app/components/product_info_popup/product_info_popup.xml
  addons/pos_self_order/static/src/app/pages/product_list_page/product_list_page.scss
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/interactions/dropdown/hoverable_dropdown.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/static/src/snippets/s_website_form/form.js
  addons/website_sale/controllers/main.py
Labels: staging.saas-18.2

#32791 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/account_payment_term.py
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_peppol/tools/demo_utils.py
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_constraints.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/controllers/google_translate.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/tests/test_mail_message_translate.py
  addons/payment/tests/test_payment_transaction.py
  addons/payment_asiapay/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_worldline/tests/common.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/tests/tours/pos_cash_rounding_tour.js
  addons/point_of_sale/tests/test_pos_cash_rounding.py
  addons/pos_self_order/static/src/app/pages/product_list_page/product_list_page.scss
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/website/static/src/snippets/s_image_gallery/options.js
Labels: staging.18.0

#32795 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/html_editor/controllers/main.py
  addons/im_livechat/tests/test_user_livechat_username.py
  addons/l10n_es/models/account_move.py
  addons/l10n_ro_edi/models/account_edi_xml_ubl_ciusro.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_ro_edi/tests/test_files/from_odoo/ciusro_out_invoice_no_prefix_vat.xml
  addons/l10n_ro_edi/tests/test_xml_ubl_ro.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/controllers/google_translate.py
  addons/mail/models/discuss/discuss_channel_member.py
  addons/mail/static/src/discuss/call/common/call.xml
  addons/mail/static/src/views/web/activity/activity_controller.js
  addons/mail/tests/test_mail_message_translate.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/portal/controllers/portal.py
  addons/portal/static/src/js/address.js
  addons/portal/tests/test_addresses.py
  addons/portal_rating/static/src/chatter/frontend/composer_patch.js
  addons/portal_rating/static/src/chatter/frontend/message_patch.js
  addons/pos_self_order/static/src/app/components/combo_selection/combo_selection.js
  addons/pos_self_order/static/src/app/components/combo_selection/combo_selection.xml
  addons/pos_self_order/static/src/app/components/product_info_popup/product_info_popup.js
  addons/pos_self_order/static/src/app/components/product_info_popup/product_info_popup.xml
  addons/pos_self_order/static/src/app/pages/product_list_page/product_list_page.scss
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/sale_mrp/tests/test_multistep_manufacturing.py
  addons/sale_mrp/tests/test_sale_mrp_procurement.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/interactions/dropdown/hoverable_dropdown.js
  addons/website/static/src/snippets/s_image_gallery/options.js
  addons/website/static/src/snippets/s_website_form/form.js
  addons/website_sale/controllers/main.py
Labels: tmp.saas-18.2

#32796 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_json.py
  addons/mail/models/mail_thread.py
  addons/project/models/project.py
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/web/static/tests/core/scroller_service_tests.js
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  doc/cla/corporate/moduon.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
Labels: tmp.16.0

#32798 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_payment_term.py
  addons/account_peppol/tools/demo_utils.py
  addons/hr_attendance/models/hr_attendance.py
  addons/hr_attendance/tests/test_hr_attendance_constraints.py
  addons/mail/controllers/google_translate.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mail/tests/test_mail_message_translate.py
  addons/payment/tests/test_payment_transaction.py
  addons/payment_asiapay/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_worldline/tests/common.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/tests/tours/pos_cash_rounding_tour.js
  addons/point_of_sale/tests/test_pos_cash_rounding.py
  addons/pos_self_order/static/src/app/pages/product_list_page/product_list_page.scss
  addons/project/views/project_sharing_project_task_views.xml
  addons/sale_loyalty/tests/test_buy_gift_card.py
  addons/website/static/src/snippets/s_image_gallery/options.js
Labels: tmp.18.0

#32799 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_bank_statement_line.py
  addons/analytic/models/analytic_distribution_model.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/mass_mailing/models/mailing.py
  addons/web/models/base_document_layout.py
  odoo/addons/base/models/assetsbundle.py
  odoo/http.py
  odoo/netsvc.py
  odoo/tools/config.py
Labels: 16.0

#32800 Syncing from upstream odoo/odoo (17.0)
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/bus/tests/common.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/l10n_cl/models/account_move.py
  addons/l10n_nz/__manifest__.py
  addons/l10n_nz/data/account_tax_report_data.xml
  addons/l10n_nz/data/template/account.tax-nz.csv
  addons/l10n_nz/migrations/1.2/post-migrate.py
  addons/l10n_nz/migrations/1.2/pre-migrate.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_tools.py
  addons/mail/tools/parser.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/sale/models/sale_order.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale/tests/test_sale_order_product_catalog.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/test_base_automation/tests/test_flow.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/views/kanban/kanban_header.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/model_page.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/popup_visibility_option.js
  addons/website/tests/test_ui.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/test_http/tests/test_static.py
  odoo/service/server.py
  odoo/tests/common.py
Labels: 17.0

#32803 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move_line.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_json.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/report/ewaybill_report.xml
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_nz/__manifest__.py
  addons/l10n_nz/data/account_tax_report_data.xml
  addons/l10n_nz/data/template/account.tax-nz.csv
  addons/l10n_nz/migrations/1.2/post-migrate.py
  addons/l10n_nz/migrations/1.2/pre-migrate.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_kiosk_tour.js
  addons/pos_self_order/tests/test_self_order_kiosk.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/repair/models/repair.py
  addons/repair/tests/test_repair.py
  addons/sale_project/tests/test_sale_project.py
  addons/stock_account/models/account_move.py
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/web/static/tests/legacy/core/utils/sortable_tests.js
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  odoo/addons/base/models/assetsbundle.py
Labels: saas-17.4

#32804 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/models/account_payment_term.py
  addons/calendar/static/src/scss/calendar.scss
  addons/hw_drivers/connection_manager.py
  addons/l10n_ch/views/qr_invoice_wizard_view.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill/report/ewaybill_report.xml
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_jo_edi/models/account_move.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/payment/tests/test_payment_transaction.py
  addons/payment_asiapay/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/payment_worldline/tests/common.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/sms/i18n/sms.pot
  addons/sms/models/ir_actions_server.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  doc/cla/individual/corentinderuyck.md
  odoo/addons/base/models/assetsbundle.py
Labels: saas-18.1

#32805 Syncing from upstream odoo/odoo (saas-18.2)
  addons/account/models/account_payment_term.py
  addons/account_peppol/tools/demo_utils.py
  addons/calendar/static/src/scss/calendar.scss
  addons/l10n_ch/views/qr_invoice_wizard_view.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_in/data/uom_data.xml
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill/report/ewaybill_report.xml
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mrp/data/mail_templates.xml
  addons/payment/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/services/pos_printer_service.js
  addons/pos_epson_printer/static/src/app/utils/payment/epson_printer.js
  addons/pos_event/static/src/app/models/pos_order_line.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  doc/cla/individual/corentinderuyck.md
  odoo/addons/base/models/assetsbundle.py
Labels: saas-18.2

#32806 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/account/models/account_payment_term.py
  addons/calendar/static/src/scss/calendar.scss
  addons/hw_drivers/connection_manager.py
  addons/l10n_ch/views/qr_invoice_wizard_view.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill/report/ewaybill_report.xml
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_jo_edi/models/account_move.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/payment/tests/test_payment_transaction.py
  addons/payment_asiapay/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/payment_worldline/tests/common.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/sms/i18n/sms.pot
  addons/sms/models/ir_actions_server.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  doc/cla/individual/corentinderuyck.md
  odoo/addons/base/models/assetsbundle.py
Labels: staging.saas-18.1

#32807 Syncing from upstream odoo/odoo (staging.saas-18.2)
  addons/account/models/account_payment_term.py
  addons/account_peppol/tools/demo_utils.py
  addons/calendar/static/src/scss/calendar.scss
  addons/hr_holidays/static/tests/tours/time_off_graph_view_tour.js
  addons/l10n_ch/views/qr_invoice_wizard_view.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_in/data/uom_data.xml
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill/report/ewaybill_report.xml
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/src/js/tours/discuss_channel_tour.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mrp/data/mail_templates.xml
  addons/payment/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/services/pos_printer_service.js
  addons/point_of_sale/static/tests/pos/tours/product_screen_tour.js
  addons/pos_epson_printer/static/src/app/utils/payment/epson_printer.js
  addons/pos_event/static/src/app/models/pos_order_line.js
  addons/pos_restaurant/static/tests/tours/control_buttons_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_self_order/tests/test_self_order_mobile.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/test_mail/tests/test_mail_activity.py
  addons/test_website/static/tests/tours/systray.js
  addons/web/models/base_document_layout.py
  addons/web/static/src/core/macro.js
  addons/web_tour/static/src/tour_service/tour_helpers.js
  addons/website/static/tests/tours/client_action_redirect.js
  addons/website/static/tests/tours/edit_menus.js
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  addons/website_livechat/static/tests/tours/lazy_frontend_bus_tour.js
  addons/website_livechat/static/tests/tours/website_livechat_common.js
  addons/website_livechat/static/tests/tours/website_livechat_no_new_session_with_hide_rule.js
  addons/website_slides/static/tests/tours/slides_course_member.js
  doc/cla/individual/corentinderuyck.md
  odoo/addons/base/models/assetsbundle.py
Labels: staging.saas-18.2

#32808 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_bank_statement_line.py
  addons/analytic/models/analytic_distribution_model.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/mass_mailing/models/mailing.py
  addons/web/models/base_document_layout.py
  odoo/addons/base/models/assetsbundle.py
  odoo/http.py
  odoo/netsvc.py
  odoo/tools/config.py
Labels: staging.16.0

#32809 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/bus/tests/common.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/l10n_cl/models/account_move.py
  addons/l10n_nz/__manifest__.py
  addons/l10n_nz/data/account_tax_report_data.xml
  addons/l10n_nz/data/template/account.tax-nz.csv
  addons/l10n_nz/migrations/1.2/post-migrate.py
  addons/l10n_nz/migrations/1.2/pre-migrate.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_tools.py
  addons/mail/tools/parser.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/sale/models/sale_order.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale/tests/test_sale_order_product_catalog.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/test_base_automation/tests/test_flow.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/views/kanban/kanban_header.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/model_page.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/popup_visibility_option.js
  addons/website/tests/test_ui.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/test_http/tests/test_static.py
  odoo/service/server.py
  odoo/tests/common.py
Labels: staging.17.0

#32812 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move_line.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/l10n_in_edi_ewaybill/models/account_edi_format.py
  addons/l10n_in_edi_ewaybill/tests/test_edi_ewaybill_json.py
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill_stock/report/ewaybill_report.xml
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_nz/__manifest__.py
  addons/l10n_nz/data/account_tax_report_data.xml
  addons/l10n_nz/data/template/account.tax-nz.csv
  addons/l10n_nz/migrations/1.2/post-migrate.py
  addons/l10n_nz/migrations/1.2/pre-migrate.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/partner_autocomplete/static/src/xml/partner_autocomplete.xml
  addons/partner_autocomplete/static/tests/partner_autocomplete_tests.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_kiosk_tour.js
  addons/pos_self_order/tests/test_self_order_kiosk.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/repair/models/repair.py
  addons/repair/tests/test_repair.py
  addons/sale_project/tests/test_sale_project.py
  addons/stock_account/models/account_move.py
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/web/static/tests/legacy/core/utils/sortable_tests.js
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  odoo/addons/base/models/assetsbundle.py
Labels: tmp.saas-17.4

#32813 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/models/account_payment_term.py
  addons/calendar/static/src/scss/calendar.scss
  addons/hw_drivers/connection_manager.py
  addons/l10n_ch/views/qr_invoice_wizard_view.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill/report/ewaybill_report.xml
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_jo_edi/models/account_move.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/payment/tests/test_payment_transaction.py
  addons/payment_asiapay/tests/common.py
  addons/payment_asiapay/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/payment_worldline/tests/common.py
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/sms/i18n/sms.pot
  addons/sms/models/ir_actions_server.py
  addons/stock/report/report_stockpicking_operations.xml
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  doc/cla/individual/corentinderuyck.md
  odoo/addons/base/models/assetsbundle.py
Labels: tmp.saas-18.1

#32814 Syncing from upstream odoo/odoo (tmp.saas-18.2)
  addons/account/models/account_payment_term.py
  addons/account_peppol/tools/demo_utils.py
  addons/calendar/static/src/scss/calendar.scss
  addons/l10n_ch/views/qr_invoice_wizard_view.xml
  addons/l10n_ch/views/res_bank_view.xml
  addons/l10n_ch/views/setup_wizard_views.xml
  addons/l10n_eg_edi_eta/models/account_edi_format.py
  addons/l10n_in/data/uom_data.xml
  addons/l10n_in_edi/models/account_move.py
  addons/l10n_in_ewaybill/models/l10n_in_ewaybill.py
  addons/l10n_in_ewaybill/report/ewaybill_report.xml
  addons/l10n_in_ewaybill_stock/models/l10n_in_ewaybill.py
  addons/l10n_in_purchase_stock/models/stock_move.py
  addons/l10n_in_sale_stock/models/stock_move.py
  addons/l10n_ke_edi_tremol/models/account_move.py
  addons/mail/models/mail_activity_mixin.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/thread.js
  addons/mail/static/tests/chat_window/chat_window.test.js
  addons/mrp/data/mail_templates.xml
  addons/payment/tests/test_payment_transaction.py
  addons/payment_custom/tests/test_payment_transaction.py
  addons/payment_stripe/tests/test_stripe.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/res_partner.py
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/services/pos_printer_service.js
  addons/pos_epson_printer/static/src/app/utils/payment/epson_printer.js
  addons/pos_event/static/src/app/models/pos_order_line.js
  addons/project/views/project_sharing_project_task_views.xml
  addons/purchase_mrp/tests/test_purchase_mrp_flow.py
  addons/test_mail/tests/test_mail_activity.py
  addons/web/models/base_document_layout.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  addons/website_event/models/event_event.py
  doc/cla/individual/corentinderuyck.md
  odoo/addons/base/models/assetsbundle.py
Labels: tmp.saas-18.2

#32815 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_bank_statement_line.py
  addons/analytic/models/analytic_distribution_model.py
  addons/l10n_ch/models/account_bank_statement.py
  addons/mass_mailing/models/mailing.py
  addons/web/models/base_document_layout.py
  odoo/addons/base/models/assetsbundle.py
  odoo/http.py
  odoo/netsvc.py
  odoo/tools/config.py
Labels: tmp.16.0

#32816 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_edi_ubl_cii/models/ir_actions_report.py
  addons/bus/tests/common.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/l10n_cl/models/account_move.py
  addons/l10n_nz/__manifest__.py
  addons/l10n_nz/data/account_tax_report_data.xml
  addons/l10n_nz/data/template/account.tax-nz.csv
  addons/l10n_nz/migrations/1.2/post-migrate.py
  addons/l10n_nz/migrations/1.2/pre-migrate.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/test_mail_tools.py
  addons/mail/tools/parser.py
  addons/mrp_subcontracting/tests/test_subcontracting.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/sale/models/sale_order.py
  addons/sale/static/tests/tours/sale_catalog.js
  addons/sale/tests/test_sale_order_product_catalog.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_product_configurator/static/src/js/sale_product_field.js
  addons/test_base_automation/tests/test_flow.py
  addons/web/models/base_document_layout.py
  addons/web/static/src/views/kanban/kanban_header.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/controllers/model_page.py
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/popup_visibility_option.js
  addons/website/tests/test_ui.py
  addons/website_blog/tests/__init__.py
  addons/website_blog/tests/test_sitemap.py
  odoo/addons/base/models/assetsbundle.py
  odoo/addons/base/tests/test_http_case.py
  odoo/addons/test_http/tests/test_static.py
  odoo/service/server.py
  odoo/tests/common.py
Labels: tmp.17.0

#32818 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_account.py
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_id/data/account.account.template.csv
  addons/l10n_ke/data/account.account.template.csv
  addons/l10n_lu/data/account.account.template.csv
  addons/l10n_ro/data/account.account.template.csv
  addons/l10n_se/data/account.account.template-K2.csv
  addons/l10n_se/data/account.account.template.csv
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/stock_account/models/stock_valuation_layer.py
  doc/cla/individual/paimonchan2.md
Labels: 16.0

#32819 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_account.py
  addons/analytic/models/analytic_distribution_model.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_drivers/websocket_client.py
  addons/l10n_fr/data/template/account.account-fr.csv
  addons/l10n_id/data/template/account.account-id.csv
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/l10n_ke/data/template/account.account-ke.csv
  addons/l10n_kz/data/template/account.account-kz.csv
  addons/l10n_lu/data/template/account.account-lu.csv
  addons/l10n_ro/data/template/account.account-ro.csv
  addons/l10n_se/data/template/account.account-se.csv
  addons/l10n_se/data/template/account.account-se_K2.csv
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/product.py
  addons/mrp_account/models/stock_valuation_layer.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project_task.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_delivery/models/stock_move.py
  addons/web/static/src/core/browser/cookie.js
  addons/web_editor/static/src/js/common/utils.js
  doc/cla/corporate/moduon.md
  doc/cla/corporate/tecnativa.md
  odoo/http.py
  odoo/netsvc.py
Labels: 17.0

#32822 Syncing from upstream odoo/odoo (saas-17.4)
  addons/analytic/models/analytic_distribution_model.py
  addons/bus/tests/common.py
  addons/hr/models/resource.py
  addons/hr/static/tests/legacy/m2x_avatar_employee_tests.js
  addons/hr_skills/static/tests/many2one_avatar_employee.test.js
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/im_livechat/static/tests/embed/chat_window.test.js
  addons/l10n_cl/models/account_move.py
  addons/l10n_ee/data/template/account.fiscal.position-ee.csv
  addons/l10n_ee/data/template/account.tax-ee.csv
  addons/l10n_ee/data/template/account.tax.group-ee.csv
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/mail/static/src/core/common/chat_hub.js
  addons/mail/static/src/core/common/chat_hub.scss
  addons/mail/static/src/core/common/chat_hub.xml
  addons/mail/static/src/core/common/chat_window.js
  addons/mail/static/src/core/common/thread_actions.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/discuss/core/common/composer_patch.js
  addons/mail/tests/test_mail_tools.py
  addons/mail/tools/parser.py
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/product.py
  addons/mrp_account/models/stock_valuation_layer.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/resource_mail/models/resource_resource.py
  addons/resource_mail/static/src/components/avatar_card_resource/avatar_card_resource_popover.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_delivery/models/stock_move.py
  addons/test_base_automation/tests/test_flow.py
  addons/web/static/src/views/fields/phone/phone_field.xml
  addons/web/static/tests/views/fields/phone_field.test.js
  addons/website/controllers/model_page.py
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/tests/test_http_case.py
  odoo/http.py
  odoo/netsvc.py
  odoo/tests/common.py
Labels: saas-17.4

#32827 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_account.py
  addons/hr_timesheet_attendance/report/hr_timesheet_attendance_report.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_fr/data/account.account.template.csv
  addons/l10n_id/data/account.account.template.csv
  addons/l10n_ke/data/account.account.template.csv
  addons/l10n_lu/data/account.account.template.csv
  addons/l10n_ro/data/account.account.template.csv
  addons/l10n_se/data/account.account.template-K2.csv
  addons/l10n_se/data/account.account.template.csv
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/stock_account/models/stock_valuation_layer.py
  doc/cla/individual/paimonchan2.md
Labels: staging.16.0

#32828 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_account.py
  addons/analytic/models/analytic_distribution_model.py
  addons/hw_drivers/tools/helpers.py
  addons/hw_drivers/websocket_client.py
  addons/l10n_fr/data/template/account.account-fr.csv
  addons/l10n_id/data/template/account.account-id.csv
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/l10n_ke/data/template/account.account-ke.csv
  addons/l10n_kz/data/template/account.account-kz.csv
  addons/l10n_lu/data/template/account.account-lu.csv
  addons/l10n_ro/data/template/account.account-ro.csv
  addons/l10n_se/data/template/account.account-se.csv
  addons/l10n_se/data/template/account.account-se_K2.csv
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/product.py
  addons/mrp_account/models/stock_valuation_layer.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/partner_autocomplete/static/src/js/partner_autocomplete_fieldchar.js
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/project/models/project_task.py
  addons/purchase_stock/tests/test_purchase_order.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/sale_timesheet/models/product.py
  addons/sale_timesheet/tests/test_sale_service.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_delivery/models/stock_move.py
  addons/web/static/src/core/browser/cookie.js
  addons/web_editor/static/src/js/common/utils.js
  doc/cla/corporate/moduon.md
  doc/cla/corporate/tecnativa.md
  odoo/http.py
  odoo/netsvc.py
Labels: staging.17.0

#32831 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/analytic/models/analytic_distribution_model.py
  addons/bus/tests/common.py
  addons/hr/models/resource.py
  addons/hr/static/tests/legacy/m2x_avatar_employee_tests.js
  addons/hr_skills/static/tests/many2one_avatar_employee.test.js
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/im_livechat/static/tests/embed/chat_window.test.js
  addons/l10n_cl/models/account_move.py
  addons/l10n_ee/data/template/account.fiscal.position-ee.csv
  addons/l10n_ee/data/template/account.tax-ee.csv
  addons/l10n_ee/data/template/account.tax.group-ee.csv
  addons/l10n_it_stock_ddt/tests/test_edi.py
  addons/mail/static/src/core/common/chat_hub.js
  addons/mail/static/src/core/common/chat_hub.scss
  addons/mail/static/src/core/common/chat_hub.xml
  addons/mail/static/src/core/common/chat_window.js
  addons/mail/static/src/core/common/thread_actions.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/src/discuss/core/common/composer_patch.js
  addons/mail/tests/test_mail_tools.py
  addons/mail/tools/parser.py
  addons/mrp_account/models/__init__.py
  addons/mrp_account/models/product.py
  addons/mrp_account/models/stock_valuation_layer.py
  addons/mrp_account/tests/test_valuation_layers.py
  addons/payment_paypal/models/payment_transaction.py
  addons/payment_paypal/tests/test_paypal.py
  addons/payment_paypal/views/payment_paypal_templates.xml
  addons/pos_mrp/tests/test_pos_mrp_flow.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase_stock/tests/test_replenish_wizard.py
  addons/resource_mail/models/resource_resource.py
  addons/resource_mail/static/src/components/avatar_card_resource/avatar_card_resource_popover.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_to_invoice.py
  addons/sale_mrp/tests/test_sale_mrp_kit_bom.py
  addons/stock_account/models/product.py
  addons/stock_account/models/stock_valuation_layer.py
  addons/stock_delivery/models/stock_move.py
  addons/test_base_automation/tests/test_flow.py
  addons/web/static/src/views/fields/phone/phone_field.xml
  addons/web/static/tests/views/fields/phone_field.test.js
  addons/website/controllers/model_page.py
  addons/website/static/src/js/editor/snippets.options.js
  odoo/addons/base/tests/test_http_case.py
  odoo/http.py
  odoo/netsvc.py
  odoo/tests/common.py
Labels: tmp.saas-17.4
