Repository brain-tec/odoo, pull requests merged in 2025-02, with the labels that each got.

#31500 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi/tests/common.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/product_template.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/common.py
  addons/l10n_es_edi_tbai/tests/test_edi_web_services.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/web/static/src/legacy/js/views/kanban/kanban_record.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/models/website.py
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/addons/base/i18n/base.pot
Labels: 16.0

#31501 Syncing from upstream odoo/odoo (17.0)
  addons/account_check_printing/models/account_payment.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/mrp/tests/test_order.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/i18n/nl.po
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_embed_code/000.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/s_searchbar.xml
  addons/website/views/snippets/s_website_form.xml
  addons/website/views/website_templates.xml
  addons/website_event/views/event_snippets.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale_product_configurator/data/demo.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/corporate/rooteam.md
  doc/cla/individual/burkhaltery.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/tools/template_inheritance.py
Labels: 17.0

#31504 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account_check_printing/models/account_payment.py
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.xml
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/test_self_order_mobile.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/survey/static/src/js/survey_session_leaderboard.js
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/tests/core/model_field_selector.test.js
  addons/web/static/tests/legacy/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/views/website_templates.xml
  addons/website_sale_product_configurator/data/demo.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/corporate/rooteam.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: saas-17.2

#31505 Syncing from upstream odoo/odoo (saas-17.4)
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/app/debug/debug_widget.js
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_mobile_tour.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_fleet/models/stock_picking_batch.py
  addons/survey/static/src/js/survey_session_leaderboard.js
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/tests/core/model_field_selector.test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/views/website_templates.xml
  addons/website_sale/data/demo.xml
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_slides/models/product_product.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: saas-17.4

#31508 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account_check_printing/models/account_payment.py
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.xml
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/test_self_order_mobile.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/survey/static/src/js/survey_session_leaderboard.js
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/tests/core/model_field_selector.test.js
  addons/web/static/tests/legacy/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/views/website_templates.xml
  addons/website_sale_product_configurator/data/demo.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/corporate/rooteam.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: staging.saas-17.2

#31509 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/app/debug/debug_widget.js
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_mobile_tour.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_fleet/models/stock_picking_batch.py
  addons/survey/static/src/js/survey_session_leaderboard.js
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/tests/core/model_field_selector.test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/views/website_templates.xml
  addons/website_sale/data/demo.xml
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_slides/models/product_product.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: staging.saas-17.4

#31511 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi/tests/common.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/product_template.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/common.py
  addons/l10n_es_edi_tbai/tests/test_edi_web_services.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/web/static/src/legacy/js/views/kanban/kanban_record.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/models/website.py
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/addons/base/i18n/base.pot
Labels: staging.16.0

#31515 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account_check_printing/models/account_payment.py
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.xml
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/test_self_order_mobile.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/survey/static/src/js/survey_session_leaderboard.js
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/tests/core/model_field_selector.test.js
  addons/web/static/tests/legacy/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/views/website_templates.xml
  addons/website_sale_product_configurator/data/demo.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/corporate/rooteam.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: tmp.saas-17.2

#31516 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/mass_mailing/controllers/main.py
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mass_mailing/models/mailing.py
  addons/point_of_sale/static/src/app/debug/debug_widget.js
  addons/pos_self_order/static/src/app/pages/cart_page/cart_page.js
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/pos_self_order/static/tests/tours/self_order_mobile_tour.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock_fleet/models/stock_picking_batch.py
  addons/survey/static/src/js/survey_session_leaderboard.js
  addons/survey/static/src/js/survey_session_manage.js
  addons/survey/static/tests/tours/survey_tour_session_manage.js
  addons/survey/views/survey_templates_user_input_session.xml
  addons/test_mail_full/tests/test_mass_mailing.py
  addons/web/static/src/core/model_field_selector/model_field_selector_popover.js
  addons/web/static/tests/core/model_field_selector.test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_image_gallery/000.js
  addons/website/static/src/snippets/s_website_form/000.js
  addons/website/static/tests/tours/website_form_editor.js
  addons/website/views/website_templates.xml
  addons/website_sale/data/demo.xml
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_slides/models/product_product.py
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/tools/template_inheritance.py
Labels: tmp.saas-17.4

#31518 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi/tests/common.py
  addons/delivery/i18n/delivery.pot
  addons/delivery/models/product_template.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai/tests/common.py
  addons/l10n_es_edi_tbai/tests/test_edi_web_services.py
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/web/static/src/legacy/js/views/kanban/kanban_record.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website/models/website.py
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/addons/base/i18n/base.pot
Labels: tmp.16.0

#31519 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account_check_printing/models/account_payment.py
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/mrp/tests/test_order.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/views/stock_picking_views.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/i18n/nl.po
  addons/website/i18n/website.pot
  addons/website/static/src/components/dialog/seo.js
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_embed_code/000.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/s_searchbar.xml
  addons/website/views/snippets/s_website_form.xml
  addons/website/views/website_templates.xml
  addons/website_event/views/event_snippets.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_sale_product_configurator/data/demo.xml
  addons/website_slides/views/website_slides_templates_lesson_embed.xml
  doc/cla/corporate/rooteam.md
  doc/cla/individual/burkhaltery.md
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/tests/test_views.py
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/tools/template_inheritance.py
Labels: tmp.17.0

#31524 Syncing from upstream odoo/odoo (saas-17.2)
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
Labels: saas-17.2

#31527 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
Labels: staging.saas-17.2

#31528 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/website/i18n/website.pot
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: staging.saas-17.4

#31530 Syncing from upstream odoo/odoo (staging.17.0)
  addons/website/i18n/website.pot
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: staging.17.0

#31531 Syncing from upstream odoo/odoo (staging.18.0)
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/tests/message/message.test.js
Labels: staging.18.0

#31532 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
Labels: tmp.saas-17.2

#31533 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_es/__manifest__.py
  addons/l10n_es/data/account.account.tag.csv
  addons/l10n_es/data/mod390/mod390_section1.xml
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/website/i18n/website.pot
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: tmp.saas-17.4

#31534 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/website/i18n/website.pot
  addons/website/static/src/scss/website.scss
  addons/website/static/src/snippets/s_facebook_page/options.js
Labels: tmp.17.0

#31535 Syncing from upstream odoo/odoo (16.0)
  odoo/tools/_monkeypatches.py
Labels: 16.0

#31536 Syncing from upstream odoo/odoo (17.0)
  odoo/tools/_monkeypatches.py
Labels: 17.0

#31537 Syncing from upstream odoo/odoo (18.0)
  odoo/_monkeypatches/__init__.py
  odoo/_monkeypatches/email.py
  odoo/_monkeypatches/urllib3.py
Labels: 18.0

#31538 Syncing from upstream odoo/odoo (master)
  odoo/_monkeypatches/__init__.py
  odoo/_monkeypatches/email.py
  odoo/_monkeypatches/urllib3.py
Labels: master

#31539 Syncing from upstream odoo/odoo (saas-17.2)
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/website/models/website.py
  odoo/tools/_monkeypatches.py
Labels: saas-17.2

#31540 Syncing from upstream odoo/odoo (saas-17.4)
  addons/website/models/website.py
  odoo/tools/_monkeypatches.py
Labels: saas-17.4

#31542 Syncing from upstream odoo/odoo (staging.master)
  addons/pos_restaurant/static/src/app/screens/floor_screen/floor_screen.xml
  odoo/_monkeypatches/__init__.py
  odoo/_monkeypatches/email.py
  odoo/_monkeypatches/urllib3.py
Labels: staging.master

#31543 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/website/models/website.py
Labels: staging.saas-17.2

#31548 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/website/models/website.py
Labels: tmp.saas-17.2

#31551 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_bank_statement.py
  addons/account/models/partner.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/views/res_config_settings_views.xml
  addons/crm/views/crm_lead_views.xml
  addons/gamification/models/gamification_karma_rank.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_ar/demo/account_customer_invoice_demo.xml
  addons/l10n_ar/models/account_move_line.py
  addons/l10n_ar/tests/common.py
  addons/l10n_ar/tests/test_manual.py
  addons/l10n_ar/views/report_invoice.xml
  addons/mass_mailing/controllers/main.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/color_palette.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
  odoo/sql_db.py
Labels: 16.0

#31552 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/mass_mailing/controllers/main.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/pos_loyalty/static/src/overrides/models/loyalty.js
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/models/account_move.py
  addons/stock_account/models/account_move.py
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website/models/website.py
  odoo/sql_db.py
Labels: 17.0

#31555 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_simple_discount.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_tax_price_include.xml
  addons/l10n_hu_edi/tests/test_invoice_xml.py
  addons/payment/controllers/portal.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/i18n/nl.po
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_embed_code/000.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/s_searchbar.xml
  addons/website/views/snippets/s_website_form.xml
  addons/website_event/views/event_snippets.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_payment/controllers/portal.py
  addons/website_payment/static/src/js/payment_form.js
  doc/cla/individual/burkhaltery.md
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/sql_db.py
Labels: saas-17.2

#31559 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_simple_discount.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_tax_price_include.xml
  addons/l10n_hu_edi/tests/test_invoice_xml.py
  addons/payment/controllers/portal.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/i18n/nl.po
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_embed_code/000.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/s_searchbar.xml
  addons/website/views/snippets/s_website_form.xml
  addons/website_event/views/event_snippets.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_payment/controllers/portal.py
  addons/website_payment/static/src/js/payment_form.js
  doc/cla/individual/burkhaltery.md
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/sql_db.py
  odoo/tools/_monkeypatches.py
Labels: staging.saas-17.2

#31566 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_simple_discount.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_tax_price_include.xml
  addons/l10n_hu_edi/tests/test_invoice_xml.py
  addons/payment/controllers/portal.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/sale/wizard/sale_order_discount.py
  addons/sale_project/models/project.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_quant.py
  addons/stock/views/stock_picking_views.xml
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/wysiwyg_snippets.scss
  addons/website/i18n/nl.po
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_embed_code/000.scss
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  addons/website/static/tests/tours/snippets_all_drag_and_drop.js
  addons/website/views/snippets/s_searchbar.xml
  addons/website/views/snippets/s_website_form.xml
  addons/website_event/views/event_snippets.xml
  addons/website_mass_mailing/views/snippets_templates.xml
  addons/website_payment/controllers/portal.py
  addons/website_payment/static/src/js/payment_form.js
  doc/cla/individual/burkhaltery.md
  odoo/addons/base/wizard/base_partner_merge.py
  odoo/sql_db.py
  odoo/tools/_monkeypatches.py
Labels: tmp.saas-17.2

#31572 Syncing from upstream odoo/odoo (16.0)
  addons/l10n_ae/__manifest__.py
  addons/l10n_ae_pos/__manifest__.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/static/description/icon.png
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/l10n_pk/__manifest__.py
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/base.pot
Labels: 16.0

#31573 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/base_import_module/models/ir_module.py
  addons/gamification/models/gamification_karma_rank.py
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mail/views/mail_activity_plan_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/tests/unit/render_service_tests.js
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/product_template.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: 17.0

#31576 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/gamification/models/gamification_karma_rank.py
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/views/mrp_production_views.xml
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/resource/static/tests/resource_test_helpers.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/resource_mail/static/tests/resource_mail_test_helpers.js
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: saas-17.2

#31577 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/event_sale/data/event_sale_data.xml
  addons/gamification/models/gamification_karma_rank.py
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_simple_discount.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_tax_price_include.xml
  addons/l10n_hu_edi/tests/test_invoice_xml.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.xml
  addons/pos_restaurant/static/tests/tours/split_bill_screen_tour.js
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: saas-17.4

#31580 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/gamification/models/gamification_karma_rank.py
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/views/mrp_production_views.xml
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/resource/static/tests/resource_test_helpers.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/resource_mail/static/tests/resource_mail_test_helpers.js
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: staging.saas-17.2

#31581 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/event_sale/data/event_sale_data.xml
  addons/gamification/models/gamification_karma_rank.py
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_simple_discount.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_tax_price_include.xml
  addons/l10n_hu_edi/tests/test_invoice_xml.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.xml
  addons/pos_restaurant/static/tests/tours/split_bill_screen_tour.js
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: staging.saas-17.4

#31583 Syncing from upstream odoo/odoo (staging.16.0)
  addons/l10n_ae/__manifest__.py
  addons/l10n_ae_pos/__manifest__.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/static/description/icon.png
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/l10n_pk/__manifest__.py
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/base.pot
Labels: staging.16.0

#31584 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/base_import_module/models/ir_module.py
  addons/gamification/models/gamification_karma_rank.py
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/tests/unit/render_service_tests.js
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/product_template.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: staging.17.0

#31587 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/gamification/models/gamification_karma_rank.py
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/views/mrp_production_views.xml
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/resource/static/tests/resource_test_helpers.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/resource_mail/static/tests/resource_mail_test_helpers.js
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: tmp.saas-17.2

#31588 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_bank_statement.py
  addons/event_sale/data/event_sale_data.xml
  addons/gamification/models/gamification_karma_rank.py
  addons/hr_recruitment/data/hr_recruitment_demo.xml
  addons/hr_recruitment/static/applicant_cvs/Meldona_Thang_CV.pdf
  addons/hr_recruitment/static/applicant_cvs/Ohen_Rizome_CV.pdf
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_hu_edi/tests/common.py
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_complex_eur.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_simple_discount.xml
  addons/l10n_hu_edi/tests/invoice_xmls/invoice_tax_price_include.xml
  addons/l10n_hu_edi/tests/test_invoice_xml.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/product_screen/product_info_popup/product_info_popup.xml
  addons/pos_restaurant/static/tests/tours/split_bill_screen_tour.js
  addons/product_margin/models/product_product.py
  addons/product_margin/tests/test_product_margin.py
  addons/purchase_stock/tests/test_anglo_saxon_valuation_reconciliation.py
  addons/stock_account/models/account_move.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/scss/bootstrap_overridden.scss
  addons/web_editor/static/src/scss/secondary_variables.scss
  addons/web_editor/static/src/scss/web_editor.common.scss
  addons/web_editor/static/src/xml/editor.xml
  addons/website/i18n/website.pot
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: tmp.saas-17.4

#31590 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_ae/__manifest__.py
  addons/l10n_ae_pos/__manifest__.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/static/description/icon.png
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/l10n_pk/__manifest__.py
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  odoo/addons/base/i18n/ar.po
  odoo/addons/base/i18n/base.pot
Labels: tmp.16.0

#31591 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/base_import_module/models/ir_module.py
  addons/gamification/models/gamification_karma_rank.py
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mail/views/mail_activity_plan_views.xml
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/static/src/app/printer/render_service.js
  addons/point_of_sale/static/tests/unit/render_service_tests.js
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/product_template.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/tests/test_static.py
  odoo/http.py
Labels: tmp.17.0

#31550 [bt#28772][FIX] auth_oauth: missing user in signin endpoint
  addons/auth_oauth/controllers/main.py
  addons/web/controllers/utils.py
  odoo/http.py
Labels: 16.0.project_sc_465

#31593 Syncing from upstream odoo/odoo (16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  odoo/fields.py
  odoo/models.py
Labels: 16.0

#31594 Syncing from upstream odoo/odoo (17.0)
  addons/crm/views/crm_lead_views.xml
  addons/hr/models/hr_employee.py
  addons/l10n_de/models/ir_attachment.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.jpg
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_lot.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  odoo/fields.py
  odoo/models.py
  odoo/tools/xml_utils.py
Labels: 17.0

#31595 Syncing from upstream odoo/odoo (18.0)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/static/src/views/account_dashboard_kanban/account_dashboard_kanban_renderer.js
  addons/account/static/src/views/file_upload_kanban/file_upload_kanban_renderer.js
  addons/account/static/src/views/file_upload_kanban/file_upload_kanban_renderer.xml
  addons/account/static/src/views/file_upload_list/file_upload_list_renderer.js
  addons/account/static/src/views/file_upload_list/file_upload_list_renderer.xml
  addons/account/views/res_config_settings_views.xml
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/event_sale/data/event_sale_data.xml
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/im_livechat/tests/chatbot_common.py
  addons/im_livechat/tests/test_message.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/i18n/mail.pot
  addons/mail/models/mail_scheduled_message.py
  addons/mail/models/mail_thread.py
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/views/mrp_production_views.xml
  addons/point_of_sale/static/src/app/models/data_service.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/utils.js
  addons/point_of_sale/static/tests/tours/utils/chrome_util.js
  addons/portal/static/src/js/portal_security.js
  addons/portal/static/src/xml/portal_security.xml
  addons/portal/views/portal_templates.xml
  addons/pos_self_order/static/src/app/data_service.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/test_mail/tests/test_mail_scheduled_message.py
  addons/web/static/src/webclient/clickbot/clickbot.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/i18n/website.pot
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_website_form/options.js
  addons/website/static/src/xml/website_form_editor.xml
  addons/website_sale/static/src/scss/website_sale.scss
  odoo/fields.py
  odoo/models.py
Labels: 18.0

#31597 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock/models/stock_move.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/product_template.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/addons/base/i18n/base.pot
  odoo/fields.py
  odoo/models.py
Labels: saas-17.2

#31598 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/resource/static/tests/resource_test_helpers.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/resource_mail/static/tests/resource_mail_test_helpers.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/fields.py
  odoo/models.py
Labels: saas-17.4

#31601 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock/models/stock_move.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/product_template.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/addons/base/i18n/base.pot
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-17.2

#31602 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/resource/static/tests/resource_test_helpers.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/resource_mail/static/tests/resource_mail_test_helpers.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/fields.py
  odoo/models.py
Labels: staging.saas-17.4

#31604 Syncing from upstream odoo/odoo (staging.16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  odoo/fields.py
  odoo/models.py
Labels: staging.16.0

#31605 Syncing from upstream odoo/odoo (staging.17.0)
  addons/crm/views/crm_lead_views.xml
  addons/hr/models/hr_employee.py
  addons/l10n_de/models/ir_attachment.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.jpg
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_lot.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  odoo/fields.py
  odoo/models.py
  odoo/tools/xml_utils.py
Labels: staging.17.0

#31608 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/stock/models/stock_move.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/product_template.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/addons/base/i18n/base.pot
  odoo/fields.py
  odoo/models.py
Labels: tmp.saas-17.2

#31609 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/i18n/account.pot
  addons/account/models/chart_template.py
  addons/account/models/partner.py
  addons/account/views/res_config_settings_views.xml
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_import_module/models/ir_module.py
  addons/crm/views/crm_lead_views.xml
  addons/hr/models/hr_department.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/l10n_es_edi_facturae/models/account_chart_template.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mail/views/mail_activity_plan_views.xml
  addons/mass_mailing/controllers/main.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/resource/static/tests/resource_test_helpers.js
  addons/resource_mail/static/tests/many2many_avatar_resource.test.js
  addons/resource_mail/static/tests/many2one_avatar_resource.test.js
  addons/resource_mail/static/tests/resource_mail_test_helpers.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.js
  addons/spreadsheet_dashboard/static/src/bundle/dashboard_action/mobile_figure_container/mobile_figure_container.xml
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/tests/convert_inline_tests.js
  addons/website_blog/static/src/scss/website_blog.scss
  odoo/fields.py
  odoo/models.py
Labels: tmp.saas-17.4

#31611 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  odoo/fields.py
  odoo/models.py
Labels: tmp.16.0

#31612 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/crm/views/crm_lead_views.xml
  addons/hr/models/hr_employee.py
  addons/l10n_de/models/ir_attachment.py
  addons/mail/static/src/core/common/failure_model.js
  addons/mail/static/src/img/smiley/mailfailure.jpg
  addons/mail/static/src/img/smiley/mailfailure.svg
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_lot.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_lot.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/lib/pdfjs/web/viewer.js
  addons/web_editor/static/src/js/backend/convert_inline.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  odoo/fields.py
  odoo/models.py
  odoo/tools/xml_utils.py
Labels: tmp.17.0

#31614 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/decimal_precision.py
  addons/l10n_ar/views/report_invoice.xml
  addons/mail/models/res_users_settings.py
  addons/mail/tests/common.py
  addons/mail/views/res_users_settings_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_express_checkout_flows.py
  addons/website_sale_delivery/tests/test_express_checkout_flows.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: 16.0

#31618 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/tests/test_structured_reference.py
  addons/account/tools/structured_reference.py
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/iap/tools/iap_tools.py
  addons/l10n_ch/data/template/account.account-ch.csv
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/point_of_sale/static/src/app/screens/product_screen/control_buttons/control_buttons.js
  addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: saas-17.2

#31619 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/tests/test_structured_reference.py
  addons/account/tools/structured_reference.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/iap/tools/iap_tools.py
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mrp/tests/test_order.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/point_of_sale/models/report_sale_details.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: saas-17.4

#31623 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/tests/test_structured_reference.py
  addons/account/tools/structured_reference.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/iap/tools/iap_tools.py
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mrp/tests/test_order.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/point_of_sale/models/report_sale_details.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: staging.saas-17.4

#31625 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/decimal_precision.py
  addons/l10n_ar/views/report_invoice.xml
  addons/mail/models/res_users_settings.py
  addons/mail/tests/common.py
  addons/mail/views/res_users_settings_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_express_checkout_flows.py
  addons/website_sale_delivery/tests/test_express_checkout_flows.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: staging.16.0

#31629 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/tests/test_structured_reference.py
  addons/account/tools/structured_reference.py
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/iap/tools/iap_tools.py
  addons/l10n_ch/data/template/account.account-ch.csv
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting/models/mrp_production.py
  addons/mrp_subcontracting/models/stock_move.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/point_of_sale/static/src/app/screens/product_screen/control_buttons/control_buttons.js
  addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_picking.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: tmp.saas-17.2

#31630 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/tests/test_structured_reference.py
  addons/account/tools/structured_reference.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/iap/tools/iap_tools.py
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_eu_oss/i18n/cs.po
  addons/l10n_eu_oss/i18n/de.po
  addons/l10n_eu_oss/i18n/es.po
  addons/l10n_eu_oss/i18n/fr.po
  addons/l10n_eu_oss/i18n/it.po
  addons/l10n_eu_oss/i18n/l10n_eu_oss.pot
  addons/l10n_eu_oss/i18n/nl.po
  addons/l10n_eu_oss/i18n/pl.po
  addons/mrp/tests/test_order.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/payment_adyen/models/payment_transaction.py
  addons/point_of_sale/models/report_sale_details.py
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/project_timesheet_holidays/tests/test_timesheet_global_time_off.py
  addons/sale/models/account_move.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_packing.py
  addons/stock_picking_batch/i18n/stock_picking_batch.pot
  addons/stock_picking_batch/models/stock_picking.py
  addons/stock_picking_batch/models/stock_picking_batch.py
  addons/stock_picking_batch/tests/test_batch_picking.py
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_color_blocks_2/000.scss
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: tmp.saas-17.4

#31632 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/decimal_precision.py
  addons/l10n_ar/views/report_invoice.xml
  addons/mail/models/res_users_settings.py
  addons/mail/tests/common.py
  addons/mail/views/res_users_settings_views.xml
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_express_checkout_flows.py
  addons/website_sale_delivery/tests/test_express_checkout_flows.py
  odoo/addons/base/models/ir_qweb.py
  odoo/tools/safe_eval.py
Labels: tmp.16.0

#31635 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr_skills/static/tests/tours/skills_tour.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_sa/data/l10n_sa_chart_data.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sk/__manifest__.py
  addons/l10n_sk/data/account_fiscal_position_data.xml
  addons/l10n_sk/data/account_tax_data.xml
  addons/l10n_sk/data/account_tax_group_data.xml
  addons/l10n_sk/migrations/1.1/post-migrate_update_taxes.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_robustness.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/website_sale_stock/views/website_sale_stock_templates.xml
Labels: 16.0

#31636 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_account.py
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/decimal_precision.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/bill_preview_template.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/hr_attendance/controllers/main.py
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/l10n_ae/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_dk/i18n/da_DK.po
  addons/l10n_dk/i18n/l10n_dk.pot
  addons/l10n_dk/models/__init__.py
  addons/l10n_dk/models/account_account.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/static/description/icon.png
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_pk/__manifest__.py
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/payment_razorpay/controllers/main.py
  addons/payment_razorpay/models/payment_provider.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_project/models/sale_order_line.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/views/report_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  addons/website_sale_stock/views/website_sale_stock_templates.xml
  odoo/addons/base/i18n/base.pot
Labels: 17.0

#31637 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_account.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_cash_rounding_view.xml
  addons/account/wizard/account_secure_entries_wizard.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/tests/_helpers/user_actions.js
  addons/html_editor/static/tests/format/font_size.test.js
  addons/html_editor/static/tests/link/popover.test.js
  addons/html_editor/static/tests/link/transform.test.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.js
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/store/select_lot_popup/edit_list_input/edit_list_input.scss
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_self_order/models/res_config_settings.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/letzdoo.md
  odoo/tools/xml_utils.py
Labels: 18.0

#31639 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_recruitment/__manifest__.py
  addons/hr_recruitment/static/src/applicant_char/applicant_char.js
  addons/hr_recruitment/static/tests/ir_attachments.test.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_br_website_sale/__init__.py
  addons/l10n_br_website_sale/controllers/main.py
  addons/l10n_br_website_sale/models/website.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  odoo/tools/xml_utils.py
Labels: saas-17.2

#31640 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_br_website_sale/__init__.py
  addons/l10n_br_website_sale/controllers/main.py
  addons/l10n_br_website_sale/models/website.py
  addons/l10n_ch/data/template/account.account-ch.csv
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/views/product_view.xml
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/models/ir_http.py
  odoo/tools/xml_utils.py
Labels: saas-17.4

#31643 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_recruitment/__manifest__.py
  addons/hr_recruitment/static/src/applicant_char/applicant_char.js
  addons/hr_recruitment/static/tests/ir_attachments.test.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_br_website_sale/__init__.py
  addons/l10n_br_website_sale/controllers/main.py
  addons/l10n_br_website_sale/models/website.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  odoo/tools/xml_utils.py
Labels: staging.saas-17.2

#31644 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_br_website_sale/__init__.py
  addons/l10n_br_website_sale/controllers/main.py
  addons/l10n_br_website_sale/models/website.py
  addons/l10n_ch/data/template/account.account-ch.csv
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/views/product_view.xml
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/models/ir_http.py
  odoo/tools/xml_utils.py
Labels: staging.saas-17.4

#31646 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr_skills/static/tests/tours/skills_tour.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_sa/data/l10n_sa_chart_data.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sk/__manifest__.py
  addons/l10n_sk/data/account_fiscal_position_data.xml
  addons/l10n_sk/data/account_tax_data.xml
  addons/l10n_sk/data/account_tax_group_data.xml
  addons/l10n_sk/migrations/1.1/post-migrate_update_taxes.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_robustness.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/website_sale_stock/views/website_sale_stock_templates.xml
Labels: staging.16.0

#31647 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/decimal_precision.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/bill_preview_template.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/hr_attendance/controllers/main.py
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/l10n_ae/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_dk/i18n/da_DK.po
  addons/l10n_dk/i18n/l10n_dk.pot
  addons/l10n_dk/models/__init__.py
  addons/l10n_dk/models/account_account.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/static/description/icon.png
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_pk/__manifest__.py
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/payment_razorpay/controllers/main.py
  addons/payment_razorpay/models/payment_provider.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_project/models/sale_order_line.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/views/report_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  addons/website_sale_stock/views/website_sale_stock_templates.xml
  odoo/addons/base/i18n/base.pot
Labels: staging.17.0

#31649 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/calendar/models/calendar_event.py
  addons/calendar/tests/test_calendar.py
  addons/google_calendar/tests/test_sync_common.py
  addons/google_calendar/tests/test_sync_odoo2google.py
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_recruitment/__manifest__.py
  addons/hr_recruitment/static/src/applicant_char/applicant_char.js
  addons/hr_recruitment/static/tests/ir_attachments.test.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_br_website_sale/__init__.py
  addons/l10n_br_website_sale/controllers/main.py
  addons/l10n_br_website_sale/models/website.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/microsoft_calendar/tests/test_create_events.py
  addons/mrp/models/mrp_workorder.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/stock/models/stock_move.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/tests/test_packing.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  odoo/tools/xml_utils.py
Labels: tmp.saas-17.2

#31650 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/auth_signup/controllers/main.py
  addons/auth_signup/i18n/auth_signup.pot
  addons/auth_signup/static/src/js/reset_password.js
  addons/auth_signup/static/src/js/signup.js
  addons/google_recaptcha/__manifest__.py
  addons/google_recaptcha/static/src/js/signup.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_br_website_sale/__init__.py
  addons/l10n_br_website_sale/controllers/main.py
  addons/l10n_br_website_sale/models/website.py
  addons/l10n_ch/data/template/account.account-ch.csv
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/views/product_view.xml
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/src/app/bill_screen/bill_screen.js
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/website_cf_turnstile/static/src/js/turnstile.js
  odoo/addons/base/models/ir_http.py
  odoo/tools/xml_utils.py
Labels: tmp.saas-17.4

#31652 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/models/product.py
  addons/account/tests/test_sequence_mixin.py
  addons/hr_skills/static/tests/tours/skills_tour.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_sa/data/l10n_sa_chart_data.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sk/__manifest__.py
  addons/l10n_sk/data/account_fiscal_position_data.xml
  addons/l10n_sk/data/account_tax_data.xml
  addons/l10n_sk/data/account_tax_group_data.xml
  addons/l10n_sk/migrations/1.1/post-migrate_update_taxes.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/stock_move.py
  addons/stock/tests/test_robustness.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/website_sale_stock/views/website_sale_stock_templates.xml
Labels: tmp.16.0

#31653 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_account.py
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/decimal_precision.py
  addons/account/tests/test_account_bank_statement.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/bill_preview_template.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/hr_attendance/controllers/main.py
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/l10n_ae/__manifest__.py
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_dk/i18n/da_DK.po
  addons/l10n_dk/i18n/l10n_dk.pot
  addons/l10n_dk/models/__init__.py
  addons/l10n_dk/models/account_account.py
  addons/l10n_eg/__manifest__.py
  addons/l10n_eg/static/description/icon.png
  addons/l10n_eg_edi_eta/__manifest__.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es/data/template/account.tax-es_common.csv
  addons/l10n_es_edi_facturae/data/template/account.tax-es_common.csv
  addons/l10n_pk/__manifest__.py
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa_edi/__manifest__.py
  addons/l10n_sa_edi_pos/__manifest__.py
  addons/l10n_sa_pos/__manifest__.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/payment_razorpay/controllers/main.py
  addons/payment_razorpay/models/payment_provider.py
  addons/point_of_sale/models/pos_session.py
  addons/sale_project/models/sale_order_line.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/views/survey_templates_statistics.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/views/report_templates.xml
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  addons/website_sale_stock/views/website_sale_stock_templates.xml
  odoo/addons/base/i18n/base.pot
Labels: tmp.17.0

#31654 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_account.py
  addons/account/models/account_cash_rounding.py
  addons/account/models/account_journal.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_cash_rounding_view.xml
  addons/account/wizard/account_secure_entries_wizard.py
  addons/hr_holidays/tests/test_expiring_leaves.py
  addons/hr_holidays/views/hr_leave_allocation_views.xml
  addons/hr_holidays_attendance/i18n/hr_holidays_attendance.pot
  addons/hr_holidays_attendance/models/hr_leave_allocation.py
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/tests/_helpers/user_actions.js
  addons/html_editor/static/tests/format/font_size.test.js
  addons/html_editor/static/tests/link/popover.test.js
  addons/html_editor/static/tests/link/transform.test.js
  addons/l10n_ar/views/report_invoice.xml
  addons/l10n_latam_invoice_document/wizards/account_move_reversal.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_manual_consumption.py
  addons/payment/data/payment_cron.xml
  addons/payment/models/payment_provider.py
  addons/payment/tests/test_payment_provider.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.js
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/store/select_lot_popup/edit_list_input/edit_list_input.scss
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_self_order/models/res_config_settings.py
  addons/sale_stock/models/account_move.py
  addons/sale_stock/tests/test_anglo_saxon_valuation.py
  addons/stock/i18n/stock.pot
  addons/stock/models/stock_move.py
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  addons/website_sale/static/src/js/website_sale.js
  doc/cla/corporate/letzdoo.md
  odoo/tools/xml_utils.py
Labels: tmp.18.0

#31658 Syncing from upstream odoo/odoo (master)
  addons/html_editor/static/src/fields/html_field.js
  addons/html_editor/static/src/fields/html_viewer.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/src/utils/html.js
  addons/html_editor/static/src/utils/sanitize.js
  addons/html_editor/static/tests/html_field.test.js
  addons/html_editor/static/tests/html_viewer.test.js
  addons/repair/data/repair_demo.xml
  addons/repair/models/product.py
  addons/repair/models/sale_order.py
  addons/repair/tests/test_repair.py
  addons/repair/views/product_views.xml
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/ir_actions.py
Labels: master

#31660 Syncing from upstream odoo/odoo (saas-18.1)
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/tests/_helpers/user_actions.js
  addons/html_editor/static/tests/format/font_size.test.js
  addons/html_editor/static/tests/link/popover.test.js
  addons/html_editor/static/tests/link/transform.test.js
  addons/point_of_sale/static/src/app/components/popups/select_lot_popup/edit_list_input/edit_list_input.scss
Labels: saas-18.1

#31661 Syncing from upstream odoo/odoo (staging.master)
  addons/html_editor/static/src/fields/html_field.js
  addons/html_editor/static/src/fields/html_viewer.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/src/utils/html.js
  addons/html_editor/static/src/utils/sanitize.js
  addons/html_editor/static/tests/html_field.test.js
  addons/html_editor/static/tests/html_viewer.test.js
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/ir_actions.py
Labels: staging.master

#31664 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/html_editor/static/src/core/format_plugin.js
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/tests/_helpers/user_actions.js
  addons/html_editor/static/tests/format/font_size.test.js
  addons/html_editor/static/tests/link/popover.test.js
  addons/html_editor/static/tests/link/transform.test.js
  addons/point_of_sale/static/src/app/components/popups/select_lot_popup/edit_list_input/edit_list_input.scss
Labels: staging.saas-18.1

#31665 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_sequence_mixin.py
Labels: tmp.17.0

#31666 Syncing from upstream odoo/odoo (tmp.18.0)
  odoo/addons/base/models/ir_actions.py
Labels: tmp.18.0

#31667 Syncing from upstream odoo/odoo (18.0)
  addons/account/views/bill_preview_template.xml
  addons/account_payment/wizards/payment_refund_wizard.py
Labels: 18.0

#31668 Syncing from upstream odoo/odoo (master)
  addons/account/views/bill_preview_template.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_in_pos/static/src/app/components/popups/cash_move_popup/cash_move_popup.js
  addons/l10n_in_pos/static/src/app/components/popups/closing_popup/closing_popup.js
  addons/l10n_in_pos/static/src/app/models/invoice_button.js
  addons/l10n_in_pos/static/src/app/models/payment_screen.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  odoo/service/server.py
Labels: master

#31669 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/account/models/decimal_precision.py
  addons/account/views/bill_preview_template.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/web/views/report_templates.xml
Labels: saas-17.2

#31670 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/views/bill_preview_template.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/web/views/report_templates.xml
Labels: saas-17.4

#31672 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_sequence_mixin.py
Labels: staging.17.0

#31673 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/views/bill_preview_template.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/html_editor/static/src/fields/html_field.js
  addons/html_editor/static/src/fields/html_viewer.js
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.scss
  addons/html_editor/static/src/main/media/media_dialog/upload_progress_toast/upload_progress_toast.xml
  addons/html_editor/static/src/utils/html.js
  addons/html_editor/static/src/utils/sanitize.js
  addons/html_editor/static/tests/html_field.test.js
  addons/html_editor/static/tests/html_viewer.test.js
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_in_pos/static/src/app/components/popups/cash_move_popup/cash_move_popup.js
  addons/l10n_in_pos/static/src/app/components/popups/closing_popup/closing_popup.js
  addons/l10n_in_pos/static/src/app/models/invoice_button.js
  addons/l10n_in_pos/static/src/app/models/payment_screen.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/repair/data/repair_demo.xml
  addons/repair/models/product.py
  addons/repair/models/sale_order.py
  addons/repair/tests/test_repair.py
  addons/repair/views/product_views.xml
  addons/website_sale/static/src/js/website_sale.js
  odoo/addons/base/models/ir_actions.py
  odoo/service/server.py
Labels: tmp.master

#31674 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/account/models/decimal_precision.py
  addons/account/views/bill_preview_template.xml
  addons/account/views/report_invoice.xml
  addons/account_payment/wizards/payment_refund_wizard.py
  addons/web/views/report_templates.xml
Labels: tmp.saas-17.2

#31679 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/account.pot
  addons/account_edi_ubl_cii/i18n/account_edi_ubl_cii.pot
  addons/account_peppol/i18n/account_peppol.pot
  addons/barcodes/i18n/barcodes.pot
  addons/base_import/i18n/base_import.pot
  addons/base_vat/i18n/base_vat.pot
  addons/bus/i18n/bus.pot
  addons/crm/i18n/crm.pot
  addons/delivery/i18n/delivery.pot
  addons/event/i18n/event.pot
  addons/hr/i18n/hr.pot
  addons/hr_expense/i18n/hr_expense.pot
  addons/hr_recruitment/i18n/hr_recruitment.pot
  addons/hr_recruitment/models/hr_applicant.py
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/http_routing/models/ir_http.py
  addons/l10n_dk_oioubl/models/account_edi_xml_oioubl_201.py
  addons/l10n_dk_oioubl/tests/test_files/from_odoo/oioubl_out_invoice_foreign_partner_be.xml
  addons/mail/i18n/mail.pot
  addons/mass_mailing/i18n/mass_mailing.pot
  addons/mrp/i18n/mrp.pot
  addons/point_of_sale/i18n/point_of_sale.pot
  addons/point_of_sale/models/pos_session.py
  addons/pos_loyalty/i18n/pos_loyalty.pot
  addons/pos_mercado_pago/i18n/pos_mercado_pago.pot
  addons/pos_restaurant/i18n/pos_restaurant.pot
  addons/pos_self_order/i18n/pos_self_order.pot
  addons/pos_stripe/i18n/pos_stripe.pot
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/product/models/product_product.py
  addons/product_expiry/i18n/product_expiry.pot
  addons/project/i18n/project.pot
  addons/project/models/project_task.py
  addons/project/tests/test_project_flow.py
  addons/project_hr_expense/i18n/project_hr_expense.pot
  addons/project_mrp/i18n/project_mrp.pot
  addons/project_timesheet_holidays/i18n/project_timesheet_holidays.pot
  addons/purchase/i18n/purchase.pot
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/rating/i18n/rating.pot
  addons/sale/i18n/sale.pot
  addons/sale_pdf_quote_builder/i18n/sale_pdf_quote_builder.pot
  addons/sale_timesheet/i18n/sale_timesheet.pot
  addons/spreadsheet/i18n/spreadsheet.pot
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/product_strategy.py
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/web/i18n/web.pot
  addons/web_editor/i18n/web_editor.pot
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/i18n/website.pot
  addons/website_event_exhibitor/i18n/website_event_exhibitor.pot
  addons/website_mail/i18n/website_mail.pot
  addons/website_mass_mailing/i18n/website_mass_mailing.pot
  addons/website_sale/i18n/website_sale.pot
  addons/website_slides/i18n/website_slides.pot
  odoo/addons/base/i18n/base.pot
Labels: 17.0

#31696 Syncing from upstream odoo/odoo (16.0)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/payment_stripe/models/payment_provider.py
  addons/sms/models/sms_api.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/models/product_template.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  odoo/addons/base/models/ir_actions_report.py
Labels: 16.0

#31697 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/product.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/L10nKeEDISerialDriver.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_id/data/template/account.tax-id.csv
  addons/l10n_id/data/template/account.tax.group-id.csv
  addons/l10n_id/demo/demo_company.xml
  addons/l10n_id_efaktur/i18n/efaktur.pot
  addons/l10n_id_efaktur/i18n/id.po
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__init__.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/controllers/__init__.py
  addons/l10n_id_efaktur_coretax/controllers/download_efaktur.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/data/ir_action.xml
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.product.code.csv
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.uom.code.csv
  addons/l10n_id_efaktur_coretax/data/uom.uom.csv
  addons/l10n_id_efaktur_coretax/i18n/coretax.pot
  addons/l10n_id_efaktur_coretax/i18n/id.po
  addons/l10n_id_efaktur_coretax/models/__init__.py
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/efaktur_document.py
  addons/l10n_id_efaktur_coretax/models/product_code.py
  addons/l10n_id_efaktur_coretax/models/product_template.py
  addons/l10n_id_efaktur_coretax/models/res_partner.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/models/uom_uom.py
  addons/l10n_id_efaktur_coretax/security/ir.model.access.csv
  addons/l10n_id_efaktur_coretax/tests/__init__.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/account_move.xml
  addons/l10n_id_efaktur_coretax/views/efaktur_document.xml
  addons/l10n_id_efaktur_coretax/views/product_code.xml
  addons/l10n_id_efaktur_coretax/views/product_template.xml
  addons/l10n_id_efaktur_coretax/views/res_partner.xml
  addons/payment_stripe/models/payment_provider.py
  addons/point_of_sale/static/src/app/utils/contextual_utils_service.js
  addons/pos_restaurant/static/src/app/floor_screen/table.xml
  addons/pos_restaurant/static/src/overrides/components/product_screen/actionpad_widget/actionpad_widget.xml
  addons/product/static/src/product_catalog/search/search_panel.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website_sale/models/product_template.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_company_checks.py
  odoo/models.py
Labels: 17.0

#31698 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/base_document_layout_views.xml
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_attendance/static/src/scss/kiosk/hr_attendance.scss
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/src/main/link/link_popover.js
  addons/html_editor/static/src/main/link/utils.js
  addons/html_editor/static/tests/insert/paragraph_break.test.js
  addons/html_editor/static/tests/link/isolated.test.js
  addons/html_editor/static/tests/link/popover.test.js
  addons/html_editor/static/tests/list/delete_backward.test.js
  addons/html_editor/static/tests/list/delete_forward.test.js
  addons/html_editor/static/tests/list/outdent.test.js
  addons/http_routing/models/ir_http.py
  addons/hw_drivers/iot_handlers/drivers/L10nKeEDISerialDriver.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_dk_oioubl/models/account_edi_xml_oioubl_201.py
  addons/l10n_dk_oioubl/tests/test_files/from_odoo/oioubl_out_invoice_foreign_partner_be.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/pos_printer_service.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/views/product_view.xml
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/product/models/product_product.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale/models/account_move.py
  addons/sale/report/ir_actions_report_templates.xml
  addons/sale_project/models/sale_order_line.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/translation.js
  addons/web/static/tests/core/l10n/translation.test.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  odoo/addons/base/models/ir_actions_report.py
Labels: 18.0

#31703 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hr_timesheet/views/project_task_sharing_views.xml
  addons/http_routing/models/ir_http.py
  addons/hw_drivers/iot_handlers/drivers/L10nKeEDISerialDriver.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_dk_oioubl/models/account_edi_xml_oioubl_201.py
  addons/l10n_dk_oioubl/tests/test_files/from_odoo/oioubl_out_invoice_foreign_partner_be.xml
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_lot.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/utils/contextual_utils_service.js
  addons/pos_restaurant/static/src/app/floor_screen/floor_screen.xml
  addons/pos_restaurant/static/src/overrides/components/product_screen/actionpad_widget/actionpad_widget.xml
  addons/product/models/product_product.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_lot.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_facebook_page/000.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_company_checks.py
  odoo/models.py
Labels: staging.saas-17.4

#31705 Syncing from upstream odoo/odoo (staging.16.0)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/payment_stripe/models/payment_provider.py
  addons/sms/models/sms_api.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/models/product_template.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  odoo/addons/base/models/ir_actions_report.py
Labels: staging.16.0

#31708 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/views/hr_timesheet_views.xml
  addons/hr_timesheet/views/project_task_sharing_views.xml
  addons/http_routing/models/ir_http.py
  addons/hw_drivers/iot_handlers/drivers/L10nKeEDISerialDriver.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_dk_oioubl/models/account_edi_xml_oioubl_201.py
  addons/l10n_dk_oioubl/tests/test_files/from_odoo/oioubl_out_invoice_foreign_partner_be.xml
  addons/mrp/models/mrp_workorder.py
  addons/mrp/models/stock_lot.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/utils/contextual_utils_service.js
  addons/pos_restaurant/static/src/app/floor_screen/floor_screen.xml
  addons/pos_restaurant/static/src/overrides/components/product_screen/actionpad_widget/actionpad_widget.xml
  addons/product/models/product_product.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_lot.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/format.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/scss/website.edit_mode.scss
  addons/website/static/src/snippets/s_facebook_page/000.js
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_company_checks.py
  odoo/models.py
Labels: tmp.saas-17.4

#31710 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp/views/mrp_production_views.xml
  addons/payment_stripe/models/payment_provider.py
  addons/sms/models/sms_api.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website_sale/models/product_template.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.16.0

#31711 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/product.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/L10nKeEDISerialDriver.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_id/data/template/account.tax-id.csv
  addons/l10n_id/data/template/account.tax.group-id.csv
  addons/l10n_id/demo/demo_company.xml
  addons/l10n_id_efaktur/i18n/efaktur.pot
  addons/l10n_id_efaktur/i18n/id.po
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__init__.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/controllers/__init__.py
  addons/l10n_id_efaktur_coretax/controllers/download_efaktur.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/data/ir_action.xml
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.product.code.csv
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.uom.code.csv
  addons/l10n_id_efaktur_coretax/data/uom.uom.csv
  addons/l10n_id_efaktur_coretax/i18n/coretax.pot
  addons/l10n_id_efaktur_coretax/i18n/id.po
  addons/l10n_id_efaktur_coretax/models/__init__.py
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/efaktur_document.py
  addons/l10n_id_efaktur_coretax/models/product_code.py
  addons/l10n_id_efaktur_coretax/models/product_template.py
  addons/l10n_id_efaktur_coretax/models/res_partner.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/models/uom_uom.py
  addons/l10n_id_efaktur_coretax/security/ir.model.access.csv
  addons/l10n_id_efaktur_coretax/tests/__init__.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/account_move.xml
  addons/l10n_id_efaktur_coretax/views/efaktur_document.xml
  addons/l10n_id_efaktur_coretax/views/product_code.xml
  addons/l10n_id_efaktur_coretax/views/product_template.xml
  addons/l10n_id_efaktur_coretax/views/res_partner.xml
  addons/payment_stripe/models/payment_provider.py
  addons/point_of_sale/static/src/app/utils/contextual_utils_service.js
  addons/pos_restaurant/static/src/app/floor_screen/table.xml
  addons/pos_restaurant/static/src/overrides/components/product_screen/actionpad_widget/actionpad_widget.xml
  addons/product/static/src/product_catalog/search/search_panel.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website_sale/models/product_template.py
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/tests/test_company_checks.py
  odoo/models.py
Labels: tmp.17.0

#31712 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/tests/test_account_payment.py
  addons/account/tests/test_sequence_mixin.py
  addons/account/views/base_document_layout_views.xml
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/hr_attendance/static/src/scss/kiosk/hr_attendance.scss
  addons/hr_holidays/models/hr_leave.py
  addons/hr_holidays/tests/test_leave_requests.py
  addons/html_editor/static/src/main/link/link_plugin.js
  addons/html_editor/static/src/main/link/link_popover.js
  addons/html_editor/static/src/main/link/utils.js
  addons/html_editor/static/tests/insert/paragraph_break.test.js
  addons/html_editor/static/tests/link/isolated.test.js
  addons/html_editor/static/tests/link/popover.test.js
  addons/html_editor/static/tests/list/delete_backward.test.js
  addons/html_editor/static/tests/list/delete_forward.test.js
  addons/html_editor/static/tests/list/outdent.test.js
  addons/http_routing/models/ir_http.py
  addons/hw_drivers/iot_handlers/drivers/L10nKeEDISerialDriver.py
  addons/l10n_din5008/report/din5008_report.xml
  addons/l10n_dk_oioubl/models/account_edi_xml_oioubl_201.py
  addons/l10n_dk_oioubl/tests/test_files/from_odoo/oioubl_out_invoice_foreign_partner_be.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/mail/tests/common.py
  addons/mail/wizard/mail_compose_message.py
  addons/mass_mailing/models/mail_mail.py
  addons/mass_mailing/wizard/mail_compose_message.py
  addons/point_of_sale/models/account_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/printer/pos_printer_service.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/views/product_view.xml
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/product/models/product_product.py
  addons/purchase_stock/models/stock_rule.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/sale/models/account_move.py
  addons/sale/report/ir_actions_report_templates.xml
  addons/sale_project/models/sale_order_line.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_mail/tests/test_mail_composer.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/core/l10n/translation.js
  addons/web/static/tests/core/l10n/translation.test.js
  addons/web/views/report_templates.xml
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/list.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/src/snippets/s_facebook_page/000.js
  addons/website_sale/controllers/main.py
  addons/website_sale/tests/test_delivery_express_checkout_flows.py
  addons/website_sale/tests/test_express_checkout_flows.py
  odoo/addons/base/models/ir_actions_report.py
Labels: tmp.18.0

#31713 Syncing from upstream odoo/odoo (16.0)
  addons/point_of_sale/models/pos_session.py
Labels: 16.0

#31714 Syncing from upstream odoo/odoo (17.0)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hr_expense/wizard/hr_expense_split_wizard_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/portal/controllers/portal.py
  addons/sms/tools/sms_api.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
Labels: 17.0

#31717 Syncing from upstream odoo/odoo (saas-17.4)
  addons/base_vat/models/res_partner.py
  addons/l10n_id/data/template/account.tax-id.csv
  addons/l10n_id/data/template/account.tax.group-id.csv
  addons/l10n_id/demo/demo_company.xml
  addons/l10n_id_efaktur/i18n/efaktur.pot
  addons/l10n_id_efaktur/i18n/id.po
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__init__.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/controllers/__init__.py
  addons/l10n_id_efaktur_coretax/controllers/download_efaktur.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/data/ir_action.xml
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.product.code.csv
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.uom.code.csv
  addons/l10n_id_efaktur_coretax/data/uom.uom.csv
  addons/l10n_id_efaktur_coretax/i18n/coretax.pot
  addons/l10n_id_efaktur_coretax/i18n/id.po
  addons/l10n_id_efaktur_coretax/models/__init__.py
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/efaktur_document.py
  addons/l10n_id_efaktur_coretax/models/product_code.py
  addons/l10n_id_efaktur_coretax/models/product_template.py
  addons/l10n_id_efaktur_coretax/models/res_partner.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/models/uom_uom.py
  addons/l10n_id_efaktur_coretax/security/ir.model.access.csv
  addons/l10n_id_efaktur_coretax/tests/__init__.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/account_move.xml
  addons/l10n_id_efaktur_coretax/views/efaktur_document.xml
  addons/l10n_id_efaktur_coretax/views/product_code.xml
  addons/l10n_id_efaktur_coretax/views/product_template.xml
  addons/l10n_id_efaktur_coretax/views/res_partner.xml
  addons/payment_razorpay/controllers/main.py
  addons/payment_razorpay/models/payment_provider.py
  addons/payment_stripe/models/payment_provider.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/product/static/src/product_catalog/search/search_panel.js
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/sms/tools/sms_api.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
Labels: saas-17.4

#31722 Syncing from upstream odoo/odoo (staging.16.0)
  addons/point_of_sale/models/pos_session.py
Labels: staging.16.0

#31723 Syncing from upstream odoo/odoo (staging.17.0)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hr_expense/wizard/hr_expense_split_wizard_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/portal/controllers/portal.py
  addons/sms/tools/sms_api.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
Labels: staging.17.0

#31725 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/base_vat/models/res_partner.py
  addons/l10n_id/data/template/account.tax-id.csv
  addons/l10n_id/data/template/account.tax.group-id.csv
  addons/l10n_id/demo/demo_company.xml
  addons/l10n_id_efaktur/i18n/efaktur.pot
  addons/l10n_id_efaktur/i18n/id.po
  addons/l10n_id_efaktur/models/account_move.py
  addons/l10n_id_efaktur/models/res_partner.py
  addons/l10n_id_efaktur/tests/test_l10n_id_efaktur.py
  addons/l10n_id_efaktur_coretax/__init__.py
  addons/l10n_id_efaktur_coretax/__manifest__.py
  addons/l10n_id_efaktur_coretax/controllers/__init__.py
  addons/l10n_id_efaktur_coretax/controllers/download_efaktur.py
  addons/l10n_id_efaktur_coretax/data/efaktur_templates.xml
  addons/l10n_id_efaktur_coretax/data/ir_action.xml
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.product.code.csv
  addons/l10n_id_efaktur_coretax/data/l10n_id_efaktur_coretax.uom.code.csv
  addons/l10n_id_efaktur_coretax/data/uom.uom.csv
  addons/l10n_id_efaktur_coretax/i18n/coretax.pot
  addons/l10n_id_efaktur_coretax/i18n/id.po
  addons/l10n_id_efaktur_coretax/models/__init__.py
  addons/l10n_id_efaktur_coretax/models/account_move.py
  addons/l10n_id_efaktur_coretax/models/account_move_line.py
  addons/l10n_id_efaktur_coretax/models/efaktur_document.py
  addons/l10n_id_efaktur_coretax/models/product_code.py
  addons/l10n_id_efaktur_coretax/models/product_template.py
  addons/l10n_id_efaktur_coretax/models/res_partner.py
  addons/l10n_id_efaktur_coretax/models/uom_code.py
  addons/l10n_id_efaktur_coretax/models/uom_uom.py
  addons/l10n_id_efaktur_coretax/security/ir.model.access.csv
  addons/l10n_id_efaktur_coretax/tests/__init__.py
  addons/l10n_id_efaktur_coretax/tests/results/sample.xml
  addons/l10n_id_efaktur_coretax/tests/test_l10n_id_efaktur_coretax.py
  addons/l10n_id_efaktur_coretax/views/account_move.xml
  addons/l10n_id_efaktur_coretax/views/efaktur_document.xml
  addons/l10n_id_efaktur_coretax/views/product_code.xml
  addons/l10n_id_efaktur_coretax/views/product_template.xml
  addons/l10n_id_efaktur_coretax/views/res_partner.xml
  addons/payment_razorpay/controllers/main.py
  addons/payment_razorpay/models/payment_provider.py
  addons/payment_stripe/models/payment_provider.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/product/static/src/product_catalog/search/search_panel.js
  addons/sale_purchase_stock/tests/test_lead_time.py
  addons/sms/tools/sms_api.py
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/tests/views/fields/image_field.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_sale_loyalty/models/sale_order.py
  addons/website_sale_loyalty/tests/test_shop_sale_coupon.py
  addons/website_sale_wishlist/views/website_sale_wishlist_template.xml
Labels: tmp.saas-17.4

#31727 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/point_of_sale/models/pos_session.py
Labels: tmp.16.0

#31728 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hr_expense/wizard/hr_expense_split_wizard_views.xml
  addons/hr_holidays/models/hr_leave_allocation.py
  addons/hr_holidays/tests/test_accrual_allocations.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/portal/controllers/portal.py
  addons/sms/tools/sms_api.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
Labels: tmp.17.0

#31730 Syncing from upstream odoo/odoo (16.0)
  doc/cla/corporate/moduon.md
  odoo/tests/common.py
Labels: 16.0

#31731 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/suggestion_service.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/tests/common.py
  addons/payment/__manifest__.py
  addons/payment/static/src/js/payment_wizard_copy_clipboard_field.js
  addons/payment/static/tests/payment_wizard_copy_clipboard_field_tests.js
  addons/payment/wizards/payment_link_wizard_views.xml
  addons/project/static/src/js/tours/project.js
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/static/src/search/search_bar/search_bar.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/tests/search/search_bar_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/tests/tours/edit_link_popover.js
  doc/cla/corporate/labiso.md
  doc/cla/corporate/moduon.md
Labels: 17.0

#31734 Syncing from upstream odoo/odoo (saas-17.4)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hr_expense/wizard/hr_expense_split_wizard_views.xml
  addons/mail/static/src/core/common/suggestion_service.js
  addons/mail/static/tests/suggestion/suggestion.test.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/portal/controllers/portal.py
  addons/project/static/src/js/tours/project.js
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/tests/views/list/list_view.test.js
  doc/cla/corporate/moduon.md
Labels: saas-17.4

#31735 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/views/base_document_layout_views.xml
  addons/hr_recruitment_survey/models/survey_survey.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/chatbot_script_step.py
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/models/discuss_channel_member.py
  addons/im_livechat/static/src/core/common/thread_patch.js
  addons/im_livechat/static/src/core/common/thread_patch.xml
  addons/im_livechat/static/tests/visitor_disconnection.test.js
  addons/im_livechat/tests/test_chatbot_internals.py
  addons/im_livechat/tests/test_get_discuss_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderSummary.xml
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/models/product_template.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/src/app/utils/devices_synchronisation.js
  addons/point_of_sale/static/tests/pos/tours/ticket_screen_tour.js
  addons/portal/controllers/portal.py
  addons/portal/models/mail_message.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/models/pos_restaurant.py
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/__init__.py
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_restaurant/tests/test_pos_restaurant_flow.py
  addons/pos_self_order/static/src/app/models/pos_order.js
  addons/sms/tools/sms_api.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_mail_full/__manifest__.py
  addons/test_mail_full/controllers/portal.py
  addons/test_mail_full/static/tests/tours/message_actions_tour.js
  addons/test_mail_full/tests/__init__.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mail_full/tests/test_ui.py
  addons/test_mail_full/views/test_portal_template.xml
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_sale/data/demo.xml
  addons/website_sale_collect/tests/__init__.py
  doc/cla/corporate/moduon.md
Labels: saas-18.1

#31738 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/account/views/base_document_layout_views.xml
  addons/hr_recruitment_survey/models/survey_survey.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/chatbot_script_step.py
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/models/discuss_channel_member.py
  addons/im_livechat/static/src/core/common/thread_patch.js
  addons/im_livechat/static/src/core/common/thread_patch.xml
  addons/im_livechat/static/tests/visitor_disconnection.test.js
  addons/im_livechat/tests/test_chatbot_internals.py
  addons/im_livechat/tests/test_get_discuss_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderSummary.xml
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/models/product_template.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/src/app/utils/devices_synchronisation.js
  addons/point_of_sale/static/tests/pos/tours/ticket_screen_tour.js
  addons/portal/controllers/portal.py
  addons/portal/models/mail_message.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/models/pos_restaurant.py
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/__init__.py
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_restaurant/tests/test_pos_restaurant_flow.py
  addons/pos_self_order/static/src/app/models/pos_order.js
  addons/sms/tools/sms_api.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_mail_full/__manifest__.py
  addons/test_mail_full/controllers/portal.py
  addons/test_mail_full/static/tests/tours/message_actions_tour.js
  addons/test_mail_full/tests/__init__.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mail_full/tests/test_ui.py
  addons/test_mail_full/views/test_portal_template.xml
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_sale/data/demo.xml
  addons/website_sale_collect/tests/__init__.py
  doc/cla/corporate/moduon.md
Labels: staging.saas-18.1

#31739 Syncing from upstream odoo/odoo (staging.16.0)
  doc/cla/corporate/moduon.md
  odoo/tests/common.py
Labels: staging.16.0

#31740 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/suggestion_service.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/tests/common.py
  addons/payment/__manifest__.py
  addons/payment/static/src/js/payment_wizard_copy_clipboard_field.js
  addons/payment/static/tests/payment_wizard_copy_clipboard_field_tests.js
  addons/payment/wizards/payment_link_wizard_views.xml
  addons/project/static/src/js/tours/project.js
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/static/src/search/search_bar/search_bar.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/tests/search/search_bar_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/tests/tours/edit_link_popover.js
  doc/cla/corporate/labiso.md
  doc/cla/corporate/moduon.md
Labels: staging.17.0

#31742 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/hr_expense/wizard/hr_expense_split.py
  addons/hr_expense/wizard/hr_expense_split_wizard_views.xml
  addons/mail/static/src/core/common/suggestion_service.js
  addons/mail/static/tests/suggestion/suggestion.test.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/payment_xendit/static/src/js/payment_form.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/portal/controllers/portal.py
  addons/project/static/src/js/tours/project.js
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/test_mail/data/test_mail_data.py
  addons/test_mail/tests/test_mail_gateway.py
  addons/web/static/src/model/relational_model/dynamic_list.js
  addons/web/static/tests/views/list/list_view.test.js
  doc/cla/corporate/moduon.md
Labels: tmp.saas-17.4

#31743 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/views/base_document_layout_views.xml
  addons/hr_recruitment_survey/models/survey_survey.py
  addons/html_editor/static/src/core/clipboard_plugin.js
  addons/html_editor/static/tests/paste.test.js
  addons/im_livechat/i18n/im_livechat.pot
  addons/im_livechat/models/chatbot_script_step.py
  addons/im_livechat/models/discuss_channel.py
  addons/im_livechat/models/discuss_channel_member.py
  addons/im_livechat/static/src/core/common/thread_patch.js
  addons/im_livechat/static/src/core/common/thread_patch.xml
  addons/im_livechat/static/tests/visitor_disconnection.test.js
  addons/im_livechat/tests/test_chatbot_internals.py
  addons/im_livechat/tests/test_get_discuss_channel.py
  addons/l10n_fr_pos_cert/static/src/xml/OrderSummary.xml
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/mail_message.py
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/mail_message.js
  addons/mass_mailing/static/src/js/mass_mailing_html_field.js
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/product_product.py
  addons/point_of_sale/models/product_template.py
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/services/data_service.js
  addons/point_of_sale/static/src/app/services/pos_store.js
  addons/point_of_sale/static/src/app/utils/devices_synchronisation.js
  addons/point_of_sale/static/tests/pos/tours/ticket_screen_tour.js
  addons/portal/controllers/portal.py
  addons/portal/models/mail_message.py
  addons/pos_online_payment/static/src/overrides/pos_overrides/components/payment_screen/payment_screen.js
  addons/pos_restaurant/models/pos_restaurant.py
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/tests/__init__.py
  addons/pos_restaurant/tests/test_frontend.py
  addons/pos_restaurant/tests/test_pos_restaurant_flow.py
  addons/pos_self_order/static/src/app/models/pos_order.js
  addons/sms/tools/sms_api.py
  addons/stock_account/models/product.py
  addons/stock_account/tests/test_stockvaluationlayer.py
  addons/test_discuss_full/tests/test_performance.py
  addons/test_mail_full/__manifest__.py
  addons/test_mail_full/controllers/portal.py
  addons/test_mail_full/static/tests/tours/message_actions_tour.js
  addons/test_mail_full/tests/__init__.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/test_mail_full/tests/test_ui.py
  addons/test_mail_full/views/test_portal_template.xml
  addons/website_livechat/tests/test_chatbot_ui.py
  addons/website_sale/data/demo.xml
  addons/website_sale_collect/tests/__init__.py
  doc/cla/corporate/moduon.md
Labels: tmp.saas-18.1

#31744 Syncing from upstream odoo/odoo (tmp.16.0)
  doc/cla/corporate/moduon.md
  odoo/tests/common.py
Labels: tmp.16.0

#31745 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/mail/models/mail_thread.py
  addons/mail/static/src/core/common/suggestion_service.js
  addons/mail/static/tests/suggestion/suggestion_tests.js
  addons/mail/tests/common.py
  addons/payment/__manifest__.py
  addons/payment/static/src/js/payment_wizard_copy_clipboard_field.js
  addons/payment/static/tests/payment_wizard_copy_clipboard_field_tests.js
  addons/payment/wizards/payment_link_wizard_views.xml
  addons/project/static/src/js/tours/project.js
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/web/static/src/search/search_bar/search_bar.js
  addons/web/static/src/views/kanban/kanban_controller.scss
  addons/web/static/tests/search/search_bar_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/website/static/tests/tours/edit_link_popover.js
  doc/cla/corporate/labiso.md
  doc/cla/corporate/moduon.md
Labels: tmp.17.0

#31747 Syncing from upstream odoo/odoo (16.0)
  addons/calendar/models/calendar_event.py
  addons/calendar/models/mail_activity.py
  addons/calendar/tests/test_calendar.py
  addons/mail/models/mail_ice_server.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: 16.0

#31751 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_mt/data/template/account.tax-mt.csv
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sk/data/template/account.fiscal.position-sk.csv
  addons/l10n_sk/data/template/account.tax-sk.csv
  addons/l10n_sk/data/template/account.tax.group-sk.csv
  addons/l10n_sk/models/template_sk.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/wizard/mrp_batch_produce.py
  addons/payment/__manifest__.py
  addons/payment/static/src/js/payment_wizard_copy_clipboard_field.js
  addons/payment/static/tests/payment_wizard_copy_clipboard_field_tests.js
  addons/payment/wizards/payment_link_wizard_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/website_sale/static/src/js/checkout.js
  addons/website_sale/views/templates.xml
  doc/cla/corporate/labiso.md
Labels: saas-17.4

#31754 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_mt/data/template/account.tax-mt.csv
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sk/data/template/account.fiscal.position-sk.csv
  addons/l10n_sk/data/template/account.tax-sk.csv
  addons/l10n_sk/data/template/account.tax.group-sk.csv
  addons/l10n_sk/models/template_sk.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/wizard/mrp_batch_produce.py
  addons/payment/__manifest__.py
  addons/payment/static/src/js/payment_wizard_copy_clipboard_field.js
  addons/payment/static/tests/payment_wizard_copy_clipboard_field_tests.js
  addons/payment/wizards/payment_link_wizard_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/website_sale/static/src/js/checkout.js
  addons/website_sale/views/templates.xml
  doc/cla/corporate/labiso.md
Labels: staging.saas-17.4

#31756 Syncing from upstream odoo/odoo (staging.16.0)
  addons/calendar/models/calendar_event.py
  addons/calendar/models/mail_activity.py
  addons/calendar/tests/test_calendar.py
  addons/mail/models/mail_ice_server.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: staging.16.0

#31759 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/views/account_tax_views.xml
  addons/account/views/res_config_settings_views.xml
  addons/analytic/static/src/components/analytic_distribution/analytic_distribution.scss
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_mt/data/template/account.tax-mt.csv
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sk/data/template/account.fiscal.position-sk.csv
  addons/l10n_sk/data/template/account.tax-sk.csv
  addons/l10n_sk/data/template/account.tax.group-sk.csv
  addons/l10n_sk/models/template_sk.py
  addons/mail/models/mail_ice_server.py
  addons/mail/models/mail_thread.py
  addons/mail/tests/common.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/stock_rule.py
  addons/mrp/wizard/mrp_batch_produce.py
  addons/payment/__manifest__.py
  addons/payment/static/src/js/payment_wizard_copy_clipboard_field.js
  addons/payment/static/tests/payment_wizard_copy_clipboard_field_tests.js
  addons/payment/wizards/payment_link_wizard_views.xml
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/models/stock_move_line.py
  addons/stock/models/stock_rule.py
  addons/stock/tests/test_move2.py
  addons/stock_picking_batch/report/report_picking_batch.xml
  addons/test_mail/tests/test_mail_gateway.py
  addons/test_mail/tests/test_mail_message_security.py
  addons/test_mail/tests/test_message_post.py
  addons/test_mail/tests/test_performance.py
  addons/test_mail_full/tests/test_mail_performance.py
  addons/website_sale/static/src/js/checkout.js
  addons/website_sale/views/templates.xml
  doc/cla/corporate/labiso.md
Labels: tmp.saas-17.4

#31761 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/calendar/models/calendar_event.py
  addons/calendar/models/mail_activity.py
  addons/calendar/tests/test_calendar.py
  addons/mail/models/mail_ice_server.py
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
Labels: tmp.16.0

#31769 Syncing from upstream odoo/odoo (saas-18.1)
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/mail/i18n/mail.pot
  addons/mail/static/src/discuss/call/common/call_context_menu.js
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/call_settings.xml
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/thread_model_patch.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/sale/models/sale_order.py
  addons/website_sale/models/sale_order.py
Labels: saas-18.1

#31771 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/mail/i18n/mail.pot
  addons/mail/static/src/discuss/call/common/call_context_menu.js
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/call_settings.xml
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/thread_model_patch.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/sale/models/sale_order.py
  addons/website_sale/models/sale_order.py
Labels: staging.saas-18.1

#31774 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/mail/i18n/mail.pot
  addons/mail/static/src/discuss/call/common/call_context_menu.js
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/call_settings.xml
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/thread_model_patch.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/sale/models/sale_order.py
  addons/website_sale/models/sale_order.py
Labels: tmp.saas-18.1

#31775 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/hr_attendance/static/src/components/card_layout/card_layout.js
  addons/hr_attendance/static/src/components/manual_selection/manual_selection.js
  addons/hr_attendance/static/src/public_kiosk/public_kiosk_app.js
  addons/mail/i18n/mail.pot
  addons/mail/static/src/discuss/call/common/call_context_menu.js
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/call_settings.xml
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/thread_model_patch.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
Labels: tmp.18.0

#31778 Syncing from upstream odoo/odoo (18.0)
  addons/auth_ldap/models/res_company_ldap.py
  addons/google_calendar/utils/google_event.py
  addons/mail/models/mail_scheduled_message.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/test_mail/tests/test_mail_scheduled_message.py
  addons/web/controllers/pivot.py
  addons/web/static/src/views/pivot/pivot_renderer.js
  addons/web/static/tests/views/pivot_view.test.js
  odoo/http.py
Labels: 18.0

#31779 Syncing from upstream odoo/odoo (master)
  addons/auth_ldap/models/res_company_ldap.py
  addons/google_calendar/utils/google_event.py
  addons/mail/static/src/discuss/call/common/call_context_menu.js
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/call_settings.xml
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/thread_model_patch.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/web/controllers/pivot.py
  addons/web/static/src/views/pivot/pivot_renderer.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/website_event/views/event_templates_page.xml
  addons/website_event_track/models/event_track.py
  odoo/http.py
Labels: master

#31780 Syncing from upstream odoo/odoo (saas-17.4)
  addons/auth_ldap/models/res_company_ldap.py
  addons/google_calendar/utils/google_event.py
  addons/microsoft_calendar/utils/microsoft_event.py
  addons/spreadsheet/static/src/actions/spreadsheet_download_action.js
  addons/web/controllers/pivot.py
  addons/web/static/src/views/pivot/pivot_renderer.js
  addons/web/static/tests/views/pivot_view.test.js
  odoo/http.py
Labels: saas-17.4

#31782 Syncing from upstream odoo/odoo (tmp.master)
  addons/mail/static/src/discuss/call/common/call_context_menu.js
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.js
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/call/common/call_settings.js
  addons/mail/static/src/discuss/call/common/call_settings.xml
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mail/static/src/discuss/call/common/thread_model_patch.js
  addons/mail/static/tests/discuss/call/peer_to_peer.test.js
  addons/website_event/views/event_templates_page.xml
  addons/website_event_track/models/event_track.py
Labels: tmp.master

#31784 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/models/account_payment_term.py
  addons/l10n_es_edi_tbai_multi_refund/i18n/es.po
  addons/l10n_es_edi_tbai_multi_refund/i18n/l10n_es_edi_tbai_multi_refund.pot
  addons/l10n_es_edi_tbai_multi_refund/models/account_move.py
  addons/l10n_es_edi_tbai_multi_refund/views/account_move_view.xml
  addons/web_editor/static/src/js/editor/snippets.editor.js
Labels: 16.0

#31788 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_payment.py
  addons/l10n_es_edi_facturae/views/account_move_views.xml
  addons/l10n_id/models/res_bank.py
  addons/l10n_jo_edi/models/account_edi_xml_ubl_21_jo.py
  addons/l10n_jo_edi/tests/test_jo_edi_precision.py
  addons/point_of_sale/static/src/app/models/pos_payment.js
  addons/stock/models/stock_quant.py
  addons/stock/tests/test_packing.py
  odoo/addons/base/models/ir_embedded_actions.py
  odoo/addons/base/views/ir_ui_view_views.xml
  odoo/tests/common.py
  odoo/tools/view_validation.py
Labels: saas-17.4

#31804 Syncing from upstream odoo/odoo (saas-17.4)
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_de/models/res_company.py
  addons/l10n_dk/i18n/da_DK.po
  addons/l10n_dk/i18n/l10n_dk.pot
  addons/l10n_dk/models/__init__.py
  addons/l10n_dk/models/account_account.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/__manifest__.py
  addons/l10n_es_edi_tbai_multi_refund/data/template_LROE_bizkaia.xml
  addons/l10n_es_edi_tbai_multi_refund/i18n/es.po
  addons/l10n_es_edi_tbai_multi_refund/i18n/l10n_es_edi_tbai_multi_refund.pot
  addons/l10n_es_edi_tbai_multi_refund/models/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_move.py
  addons/l10n_es_edi_tbai_multi_refund/views/account_move_view.xml
  addons/l10n_hu_edi/__init__.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/l10n_tr_nilvera/models/res_partner.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/src/core/common/message_search_hook.js
  addons/mail/static/src/discuss/core/common/message_patch.js
  addons/mail/static/src/utils/common/format.js
  addons/mail/static/src/utils/common/html.js
  addons/mail/static/src/views/web/activity/activity_record.js
  addons/mail/static/tests/core/search_highlight.test.js
  addons/mail/static/tests/discuss/search_discuss.test.js
  addons/mail/static/tests/mail_utils.test.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/utils/html.test.js
  addons/point_of_sale/models/pos_note.py
  addons/point_of_sale/static/src/app/screens/product_screen/control_buttons/control_buttons.js
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/product_strategy.py
  addons/web/static/src/core/utils/html.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/core/utils/html.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/chatgpt_alternatives_dialog.xml
Labels: saas-17.4

#31807 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_de/models/res_company.py
  addons/l10n_dk/i18n/da_DK.po
  addons/l10n_dk/i18n/l10n_dk.pot
  addons/l10n_dk/models/__init__.py
  addons/l10n_dk/models/account_account.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/__manifest__.py
  addons/l10n_es_edi_tbai_multi_refund/data/template_LROE_bizkaia.xml
  addons/l10n_es_edi_tbai_multi_refund/i18n/es.po
  addons/l10n_es_edi_tbai_multi_refund/i18n/l10n_es_edi_tbai_multi_refund.pot
  addons/l10n_es_edi_tbai_multi_refund/models/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_move.py
  addons/l10n_es_edi_tbai_multi_refund/views/account_move_view.xml
  addons/l10n_hu_edi/__init__.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/l10n_tr_nilvera/models/res_partner.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/src/core/common/message_search_hook.js
  addons/mail/static/src/discuss/core/common/message_patch.js
  addons/mail/static/src/utils/common/format.js
  addons/mail/static/src/utils/common/html.js
  addons/mail/static/src/views/web/activity/activity_record.js
  addons/mail/static/tests/core/search_highlight.test.js
  addons/mail/static/tests/discuss/search_discuss.test.js
  addons/mail/static/tests/mail_utils.test.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/utils/html.test.js
  addons/point_of_sale/models/pos_note.py
  addons/point_of_sale/static/src/app/screens/product_screen/control_buttons/control_buttons.js
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/product_strategy.py
  addons/web/static/src/core/utils/html.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/core/utils/html.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/chatgpt_alternatives_dialog.xml
Labels: staging.saas-17.4

#31812 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/l10n_de/i18n/de.po
  addons/l10n_de/i18n/l10n_de.pot
  addons/l10n_de/models/ir_attachment.py
  addons/l10n_de/models/res_company.py
  addons/l10n_dk/i18n/da_DK.po
  addons/l10n_dk/i18n/l10n_dk.pot
  addons/l10n_dk/models/__init__.py
  addons/l10n_dk/models/account_account.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/__manifest__.py
  addons/l10n_es_edi_tbai_multi_refund/data/template_LROE_bizkaia.xml
  addons/l10n_es_edi_tbai_multi_refund/i18n/es.po
  addons/l10n_es_edi_tbai_multi_refund/i18n/l10n_es_edi_tbai_multi_refund.pot
  addons/l10n_es_edi_tbai_multi_refund/models/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_move.py
  addons/l10n_es_edi_tbai_multi_refund/views/account_move_view.xml
  addons/l10n_hu_edi/__init__.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/l10n_tr_nilvera/models/res_partner.py
  addons/mail/static/src/core/common/message.js
  addons/mail/static/src/core/common/message_model.js
  addons/mail/static/src/core/common/message_search_hook.js
  addons/mail/static/src/discuss/core/common/message_patch.js
  addons/mail/static/src/utils/common/format.js
  addons/mail/static/src/utils/common/html.js
  addons/mail/static/src/views/web/activity/activity_record.js
  addons/mail/static/tests/core/search_highlight.test.js
  addons/mail/static/tests/discuss/search_discuss.test.js
  addons/mail/static/tests/mail_utils.test.js
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  addons/mail/static/tests/utils/html.test.js
  addons/point_of_sale/models/pos_note.py
  addons/point_of_sale/static/src/app/screens/product_screen/control_buttons/control_buttons.js
  addons/purchase_stock/models/account_move_line.py
  addons/purchase_stock/tests/test_stockvaluation.py
  addons/stock/models/product_strategy.py
  addons/web/static/src/core/utils/html.js
  addons/web/static/src/views/kanban/kanban_record.js
  addons/web/static/src/webclient/actions/action_service.js
  addons/web/static/tests/core/utils/html.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/commands.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/insert.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/chatgpt_alternatives_dialog.xml
Labels: tmp.saas-17.4

#31817 Syncing from upstream odoo/odoo (16.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/event_crm/models/event_registration.py
  addons/event_crm/tests/test_crm_lead_merge.py
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/spreadsheet/static/src/global_filters/components/filter_value/filter_value.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  odoo/tools/config.py
Labels: 16.0

#31818 Syncing from upstream odoo/odoo (17.0)
  addons/l10n_my_edi_extended/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/l10n_sa_edi/views/res_partner_views.xml
  addons/mail/static/src/discuss/call/common/call.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mrp_account/models/product.py
  addons/mrp_account/models/stock_move.py
  addons/mrp_account/tests/test_mrp_account.py
  debian/control
  odoo/addons/test_performance/tests/test_performance.py
  odoo/fields.py
Labels: 17.0

#31821 Syncing from upstream odoo/odoo (saas-17.4)
  CONTRIBUTING.md
  addons/hr/models/hr_department.py
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_tr_nilvera/__init__.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/static/src/core/common/composer.xml
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/tests/test_survey_results.py
  addons/survey/views/survey_templates_statistics.xml
  addons/web/static/src/core/file_viewer/file_model.js
  addons/web/static/src/search/search_bar/search_bar.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/src/webclient/webclient.js
  addons/web/static/tests/core/file_viewer/file_model.test.js
  addons/web/static/tests/search/search_bar.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website/controllers/main.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/user_custom_javascript.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/website_seo_notification.js
  addons/website/tests/test_assets.py
  addons/website/tests/test_ui.py
  addons/website_sale/models/product_template.py
  doc/cla/individual/alvaro-osvaldo-tm.md
Labels: saas-17.4

#31824 Syncing from upstream odoo/odoo (staging.saas-17.4)
  CONTRIBUTING.md
  addons/hr/models/hr_department.py
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_tr_nilvera/__init__.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/static/src/core/common/composer.xml
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/tests/test_survey_results.py
  addons/survey/views/survey_templates_statistics.xml
  addons/web/static/src/core/file_viewer/file_model.js
  addons/web/static/src/search/search_bar/search_bar.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/src/webclient/webclient.js
  addons/web/static/tests/core/file_viewer/file_model.test.js
  addons/web/static/tests/search/search_bar.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website/controllers/main.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/user_custom_javascript.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/website_seo_notification.js
  addons/website/tests/test_assets.py
  addons/website/tests/test_ui.py
  addons/website_sale/models/product_template.py
  doc/cla/individual/alvaro-osvaldo-tm.md
Labels: staging.saas-17.4

#31827 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/event_crm/models/event_registration.py
  addons/event_crm/tests/test_crm_lead_merge.py
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/spreadsheet/static/src/global_filters/components/filter_value/filter_value.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  odoo/tools/config.py
Labels: staging.16.0

#31828 Syncing from upstream odoo/odoo (staging.17.0)
  addons/l10n_my_edi_extended/models/account_move.py
  addons/l10n_my_edi_extended/tests/test_new_submissions_flow.py
  addons/l10n_sa_edi/views/res_partner_views.xml
  addons/mail/static/src/discuss/call/common/call.xml
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mrp_account/models/product.py
  addons/mrp_account/models/stock_move.py
  addons/mrp_account/tests/test_mrp_account.py
  debian/control
  odoo/addons/test_performance/tests/test_performance.py
  odoo/fields.py
Labels: staging.17.0

#31830 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  CONTRIBUTING.md
  addons/hr/models/hr_department.py
  addons/l10n_es/data/mod390/mod390_section2.xml
  addons/l10n_tr_nilvera/__init__.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/mail/static/src/core/common/composer.xml
  addons/purchase_stock/models/purchase_order_line.py
  addons/purchase_stock/tests/test_reordering_rule.py
  addons/stock/models/stock_orderpoint.py
  addons/stock/models/stock_rule.py
  addons/survey/i18n/survey.pot
  addons/survey/models/survey_question.py
  addons/survey/tests/test_survey_results.py
  addons/survey/views/survey_templates_statistics.xml
  addons/web/static/src/core/file_viewer/file_model.js
  addons/web/static/src/search/search_bar/search_bar.js
  addons/web/static/src/webclient/menus/menu_service.js
  addons/web/static/src/webclient/webclient.js
  addons/web/static/tests/core/file_viewer/file_model.test.js
  addons/web/static/tests/search/search_bar.test.js
  addons/web/static/tests/views/pivot_view.test.js
  addons/web/static/tests/webclient/actions/load_state.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/sanitize.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  addons/web_editor/static/src/js/wysiwyg/widgets/link.js
  addons/web_editor/static/tests/test_wysiwyg_collaboration.js
  addons/website/controllers/main.py
  addons/website/static/src/components/wysiwyg_adapter/wysiwyg_adapter.js
  addons/website/static/src/js/user_custom_javascript.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/website_seo_notification.js
  addons/website/tests/test_assets.py
  addons/website/tests/test_ui.py
  addons/website_sale/models/product_template.py
  doc/cla/individual/alvaro-osvaldo-tm.md
Labels: tmp.saas-17.4

#31833 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/wizard/account_automatic_entry_wizard.py
  addons/event_crm/models/event_registration.py
  addons/event_crm/tests/test_crm_lead_merge.py
  addons/l10n_es_edi_sii/data/account_tax_data.xml
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/l10n_es_edi_sii/tests/test_edi_xml.py
  addons/spreadsheet/static/src/global_filters/components/filter_value/filter_value.js
  addons/web/static/tests/views/fields/image_field_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/deleteBackward.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/link.test.js
  odoo/tools/config.py
Labels: tmp.16.0
