Repository brain-tec/odoo, pull requests merged in 2025-01, with the labels that each got.

#30944 Syncing from upstream odoo/odoo (16.0)
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: 16.0

#30945 Syncing from upstream odoo/odoo (17.0)
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: 17.0

#30946 Syncing from upstream odoo/odoo (18.0)
  addons/delivery/i18n/delivery.pot
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/mrp/models/stock_move.py
  addons/sale_project/models/sale_order.py
  addons/stock/views/stock_orderpoint_views.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_carrier_propagation.py
  addons/test_event_full/static/src/js/tours/wevent_register_tour.js
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_tour/static/src/tour_service/tour_automatic.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/tests/tours/parallax.js
  addons/website_event_sale/static/tests/tours/website_event_sale.js
  addons/website_event_sale/static/tests/tours/website_event_sale_pricelists.js
  addons/website_forum/static/src/js/tours/website_forum.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  odoo/cli/shell.py
Labels: 18.0

#30947 Syncing from upstream odoo/odoo (saas-17.4)
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/i18n/es.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/stock/views/stock_orderpoint_views.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/widget_link.js
Labels: saas-17.4

#30948 Syncing from upstream odoo/odoo (saas-18.1)
  addons/delivery/i18n/delivery.pot
  addons/l10n_in/data/neutralize.sql
  addons/l10n_in_edi/data/neutralize.sql
  addons/pos_loyalty/static/src/app/models/data_service_options.js
  addons/pos_loyalty/static/src/app/screens/partner_list_screen/partner_list_screen.js
  addons/stock/views/stock_orderpoint_views.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_carrier_propagation.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/widget_link.js
Labels: saas-18.1

#30951 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/i18n/es.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/stock/views/stock_orderpoint_views.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/widget_link.js
Labels: staging.saas-17.4

#30952 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/delivery/i18n/delivery.pot
  addons/l10n_in/data/neutralize.sql
  addons/l10n_in_edi/data/neutralize.sql
  addons/pos_loyalty/static/src/app/models/data_service_options.js
  addons/pos_loyalty/static/src/app/screens/partner_list_screen/partner_list_screen.js
  addons/stock/views/stock_orderpoint_views.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_carrier_propagation.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/widget_link.js
Labels: staging.saas-18.1

#30953 Syncing from upstream odoo/odoo (staging.17.0)
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: staging.17.0

#30954 Syncing from upstream odoo/odoo (staging.18.0)
  addons/delivery/i18n/delivery.pot
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/mrp/models/stock_move.py
  addons/sale_project/models/sale_order.py
  addons/stock/views/stock_orderpoint_views.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_carrier_propagation.py
  addons/test_event_full/static/src/js/tours/wevent_register_tour.js
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_tour/static/src/tour_service/tour_automatic.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/tests/tours/parallax.js
  addons/website_event_sale/static/tests/tours/website_event_sale.js
  addons/website_event_sale/static/tests/tours/website_event_sale_pricelists.js
  addons/website_forum/static/src/js/tours/website_forum.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  odoo/cli/shell.py
Labels: staging.18.0

#30955 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/i18n/es.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/stock/views/stock_orderpoint_views.xml
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/widget_link.js
Labels: tmp.saas-17.4

#30956 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/delivery/i18n/delivery.pot
  addons/l10n_in/data/neutralize.sql
  addons/l10n_in_edi/data/neutralize.sql
  addons/pos_loyalty/static/src/app/models/data_service_options.js
  addons/pos_loyalty/static/src/app/screens/partner_list_screen/partner_list_screen.js
  addons/stock/views/stock_orderpoint_views.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_carrier_propagation.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/editor/widget_link.js
Labels: tmp.saas-18.1

#30957 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: tmp.16.0

#30958 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/web_editor/static/src/js/editor/snippets.options.js
Labels: tmp.17.0

#30959 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/delivery/i18n/delivery.pot
  addons/hr_recruitment/views/hr_applicant_views.xml
  addons/mrp/models/stock_move.py
  addons/sale_project/models/sale_order.py
  addons/stock/views/stock_orderpoint_views.xml
  addons/stock_delivery/i18n/stock_delivery.pot
  addons/stock_delivery/models/stock_picking.py
  addons/stock_delivery/tests/test_carrier_propagation.py
  addons/test_event_full/static/src/js/tours/wevent_register_tour.js
  addons/test_website_modules/static/tests/tours/configurator_flow.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/web_tour/static/src/tour_service/tour_automatic.js
  addons/website/static/src/js/editor/widget_link.js
  addons/website/static/tests/tours/parallax.js
  addons/website_event_sale/static/tests/tours/website_event_sale.js
  addons/website_event_sale/static/tests/tours/website_event_sale_pricelists.js
  addons/website_forum/static/src/js/tours/website_forum.js
  addons/website_forum/static/tests/tours/website_forum_question.js
  odoo/cli/shell.py
Labels: tmp.18.0

#30960 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/hr_holidays/views/hr_leave_type_views.xml
Labels: staging.saas-17.2

#30963 Syncing from upstream odoo/odoo (staging.16.0)
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
Labels: staging.16.0

#30964 Syncing from upstream odoo/odoo (staging.18.0)
  addons/hr_holidays/views/hr_leave_type_views.xml
Labels: staging.18.0

#30965 Syncing from upstream odoo/odoo (tmp.master)
  addons/stock/views/stock_orderpoint_views.xml
Labels: tmp.master

#30966 Syncing from upstream odoo/odoo (16.0)
  addons/hr/views/hr_plan_views.xml
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/privacy_lookup/wizard/privacy_lookup_wizard_views.xml
  addons/web/static/src/legacy/js/core/menu.js
  addons/web/static/src/views/fields/daterange/daterange_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: 16.0

#30967 Syncing from upstream odoo/odoo (17.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_fr/data/template/account.account-fr.csv
  addons/l10n_sa/views/report_invoice.xml
  addons/payment_authorize/models/authorize_request.py
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
Labels: 17.0

#30968 Syncing from upstream odoo/odoo (18.0)
  SECURITY.md
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/i18n/es.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/hr/tests/test_mail_activity_plan.py
  addons/hr/wizard/mail_activity_schedule.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_fleet/tests/test_mail_activity_plan.py
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/html_editor/static/src/main/link/link_selection.scss
  addons/l10n_ar/data/template/account.tax-ar_base.csv
  addons/l10n_ar/data/template/account.tax-ar_ex.csv
  addons/l10n_ar/data/template/account.tax-ar_ri.csv
  addons/l10n_ar_withholding/data/template/account.tax-ar_base.csv
  addons/l10n_ar_withholding/data/template/account.tax-ar_ex.csv
  addons/l10n_ar_withholding/data/template/account.tax-ar_ri.csv
  addons/l10n_ar_withholding/data/template/account.tax.group-ar_base.csv
  addons/l10n_ar_withholding/demo/account_demo.py
  addons/l10n_ar_withholding/tests/test_withholding_ar_ri.py
  addons/l10n_ar_withholding/views/account_tax_views.xml
  addons/l10n_fr/views/res_company_views.xml
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_in_withholding/views/account_payment_views.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/core/common/chat_window.xml
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_combo_configurator.py
  addons/sale_expense/models/hr_expense.py
  addons/spreadsheet/models/spreadsheet_mixin.py
  addons/web/static/src/views/fields/priority/priority_field.xml
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.xml
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  doc/cla/individual/jhemono.md
Labels: 18.0

#30971 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_proxy_client/data/neutralize.sql
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_mx/__init__.py
  addons/l10n_mx/controllers/__init__.py
  addons/l10n_mx/controllers/portal.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/payment_authorize/models/authorize_request.py
  addons/portal/controllers/portal.py
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  doc/cla/corporate/phytocontrol-group.md
  odoo/cli/shell.py
Labels: staging.saas-17.2

#30972 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_proxy_client/data/neutralize.sql
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/views/res_partner_views.xml
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sg_ubl_pint/models/account_edi_xml_pint_sg.py
  addons/l10n_tr_nilvera/__init__.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/neutralize.sql
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/account_journal.py
  addons/l10n_tr_nilvera/models/l10n_tr_nilvera_alias.py
  addons/l10n_tr_nilvera/models/res_company.py
  addons/l10n_tr_nilvera/models/res_config_settings.py
  addons/l10n_tr_nilvera/models/res_partner.py
  addons/l10n_tr_nilvera/security/ir.model.access.csv
  addons/l10n_tr_nilvera/views/res_config_settings_views.xml
  addons/l10n_tr_nilvera/views/res_partner_views.xml
  addons/l10n_tr_nilvera_einvoice/__init__.py
  addons/l10n_tr_nilvera_einvoice/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/data/cron.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/__init__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_tr_nilvera_einvoice/models/account_journal.py
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/l10n_tr_nilvera_einvoice/views/account_journal_dashboard_views.xml
  addons/l10n_tr_nilvera_einvoice/views/account_move_views.xml
  addons/l10n_tr_nilvera_einvoice/wizard/__init__.py
  addons/l10n_tr_nilvera_einvoice/wizard/account_move_send.py
  addons/l10n_tr_nilvera_einvoice/wizard/account_move_send_views.xml
  addons/payment_authorize/models/authorize_request.py
  addons/project_todo/views/project_task_views.xml
  addons/web/static/src/views/fields/priority/priority_field.xml
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.xml
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  doc/cla/corporate/phytocontrol-group.md
  odoo/addons/base/i18n/base.pot
  odoo/cli/shell.py
Labels: staging.saas-17.4

#30974 Syncing from upstream odoo/odoo (staging.16.0)
  addons/hr/views/hr_plan_views.xml
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/privacy_lookup/wizard/privacy_lookup_wizard_views.xml
  addons/web/static/src/legacy/js/core/menu.js
  addons/web/static/src/views/fields/daterange/daterange_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: staging.16.0

#30975 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_fr/data/template/account.account-fr.csv
  addons/l10n_sa/views/report_invoice.xml
  addons/payment_authorize/models/authorize_request.py
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
Labels: staging.17.0

#30976 Syncing from upstream odoo/odoo (staging.18.0)
  SECURITY.md
  addons/base_vat/i18n/base_vat.pot
  addons/base_vat/i18n/es.po
  addons/base_vat/models/res_partner.py
  addons/base_vat/tests/test_validate_ruc.py
  addons/hr/tests/test_mail_activity_plan.py
  addons/hr/wizard/mail_activity_schedule.py
  addons/hr_expense/models/hr_expense.py
  addons/hr_fleet/tests/test_mail_activity_plan.py
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/html_editor/static/src/main/link/link_selection.scss
  addons/l10n_ar/data/template/account.tax-ar_base.csv
  addons/l10n_ar/data/template/account.tax-ar_ex.csv
  addons/l10n_ar/data/template/account.tax-ar_ri.csv
  addons/l10n_ar_withholding/data/template/account.tax-ar_base.csv
  addons/l10n_ar_withholding/data/template/account.tax-ar_ex.csv
  addons/l10n_ar_withholding/data/template/account.tax-ar_ri.csv
  addons/l10n_ar_withholding/data/template/account.tax.group-ar_base.csv
  addons/l10n_ar_withholding/demo/account_demo.py
  addons/l10n_ar_withholding/tests/test_withholding_ar_ri.py
  addons/l10n_ar_withholding/views/account_tax_views.xml
  addons/l10n_fr/views/res_company_views.xml
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_in_withholding/views/account_payment_views.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/mail/static/src/core/common/chat_window.xml
  addons/payment_authorize/models/authorize_request.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/sale_order.py
  addons/sale/tests/test_sale_combo_configurator.py
  addons/sale_expense/models/hr_expense.py
  addons/spreadsheet/models/spreadsheet_mixin.py
  addons/web/static/src/views/fields/priority/priority_field.xml
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.xml
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  doc/cla/individual/jhemono.md
Labels: staging.18.0

#30978 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_proxy_client/data/neutralize.sql
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_mx/__init__.py
  addons/l10n_mx/controllers/__init__.py
  addons/l10n_mx/controllers/portal.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/payment_authorize/models/authorize_request.py
  addons/portal/controllers/portal.py
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/account_move.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  doc/cla/corporate/phytocontrol-group.md
  odoo/cli/shell.py
Labels: tmp.saas-17.2

#30979 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_proxy_client/data/neutralize.sql
  addons/account_edi_ubl_cii/data/ubl_20_templates.xml
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_edi_ubl_cii/models/res_partner.py
  addons/account_edi_ubl_cii/views/res_partner_views.xml
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sg_ubl_pint/models/account_edi_xml_pint_sg.py
  addons/l10n_tr_nilvera/__init__.py
  addons/l10n_tr_nilvera/__manifest__.py
  addons/l10n_tr_nilvera/data/neutralize.sql
  addons/l10n_tr_nilvera/i18n/l10n_tr_nilvera.pot
  addons/l10n_tr_nilvera/i18n/tr.po
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/l10n_tr_nilvera/models/__init__.py
  addons/l10n_tr_nilvera/models/account_journal.py
  addons/l10n_tr_nilvera/models/l10n_tr_nilvera_alias.py
  addons/l10n_tr_nilvera/models/res_company.py
  addons/l10n_tr_nilvera/models/res_config_settings.py
  addons/l10n_tr_nilvera/models/res_partner.py
  addons/l10n_tr_nilvera/security/ir.model.access.csv
  addons/l10n_tr_nilvera/views/res_config_settings_views.xml
  addons/l10n_tr_nilvera/views/res_partner_views.xml
  addons/l10n_tr_nilvera_einvoice/__init__.py
  addons/l10n_tr_nilvera_einvoice/__manifest__.py
  addons/l10n_tr_nilvera_einvoice/data/cron.xml
  addons/l10n_tr_nilvera_einvoice/i18n/l10n_tr_nilvera_einvoice.pot
  addons/l10n_tr_nilvera_einvoice/i18n/tr.po
  addons/l10n_tr_nilvera_einvoice/models/__init__.py
  addons/l10n_tr_nilvera_einvoice/models/account_edi_xml_ubl_tr.py
  addons/l10n_tr_nilvera_einvoice/models/account_journal.py
  addons/l10n_tr_nilvera_einvoice/models/account_move.py
  addons/l10n_tr_nilvera_einvoice/views/account_journal_dashboard_views.xml
  addons/l10n_tr_nilvera_einvoice/views/account_move_views.xml
  addons/l10n_tr_nilvera_einvoice/wizard/__init__.py
  addons/l10n_tr_nilvera_einvoice/wizard/account_move_send.py
  addons/l10n_tr_nilvera_einvoice/wizard/account_move_send_views.xml
  addons/payment_authorize/models/authorize_request.py
  addons/project_todo/views/project_task_views.xml
  addons/web/static/src/views/fields/priority/priority_field.xml
  addons/web/static/src/views/fields/statusbar/statusbar_field.js
  addons/web/static/src/views/fields/statusbar/statusbar_field.xml
  addons/web/static/tests/views/fields/statusbar_field.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  doc/cla/corporate/phytocontrol-group.md
  odoo/addons/base/i18n/base.pot
  odoo/cli/shell.py
Labels: tmp.saas-17.4

#30981 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr/views/hr_plan_views.xml
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/privacy_lookup/wizard/privacy_lookup_wizard_views.xml
  addons/web/static/src/legacy/js/core/menu.js
  addons/web/static/src/views/fields/daterange/daterange_field.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/list_view_tests.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: tmp.16.0

#30982 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_fr/data/template/account.account-fr.csv
  addons/l10n_sa/views/report_invoice.xml
  addons/payment_authorize/models/authorize_request.py
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
Labels: tmp.17.0

#30984 Syncing from upstream odoo/odoo (16.0)
  addons/hr_contract/models/resource.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/sale/models/sale_order_line.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
Labels: 16.0

#30985 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/auto_hide_menu.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/link_tools.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: 17.0

#30986 Syncing from upstream odoo/odoo (18.0)
  addons/event_crm/models/crm_lead.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/iap_crm/models/crm_lead.py
  addons/l10n_fr_account/migrations/2.2/pre-migrate-add-bank-xmlid.py
  addons/l10n_in/data/template/account.fiscal.position-in.csv
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/models/template_in.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/product/models/product_template.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/web_tour/static/tests/tour_interactive.test.js
  addons/web_tour/static/tests/tour_service.test.js
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: 18.0

#30988 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_bank_statement_line.py
  addons/account_edi_proxy_client/data/neutralize.sql
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hr_gamification/wizard/gamification_badge_user_wizard.py
  addons/hr_holidays_attendance/models/hr_leave.py
  addons/hr_holidays_attendance/tests/test_holidays_overtime.py
  addons/hr_timesheet/views/hr_timesheet_portal_templates.xml
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/l10n_fr_account/data/template/account.account-fr.csv
  addons/l10n_mx/__init__.py
  addons/l10n_mx/controllers/__init__.py
  addons/l10n_mx/controllers/portal.py
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/tests/test_submissions.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/payment_authorize/models/authorize_request.py
  addons/portal/controllers/portal.py
  addons/project_todo/views/project_task_views.xml
  addons/sale/models/account_move.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/spreadsheet/static/src/list/plugins/list_core_plugin.js
  addons/spreadsheet/static/tests/lists/list_plugin_test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  doc/cla/corporate/phytocontrol-group.md
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
  odoo/cli/shell.py
Labels: saas-17.2

#30992 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/spreadsheet/static/src/list/plugins/list_core_plugin.js
  addons/spreadsheet/static/tests/lists/list_plugin_test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: staging.saas-17.2

#30993 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/models/data_service.js
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.js
  addons/point_of_sale/static/src/app/navbar/navbar.xml
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_restaurant/models/pos_order.py
  addons/pos_restaurant/models/pos_restaurant.py
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/spreadsheet/static/src/list/plugins/list_core_plugin.js
  addons/spreadsheet/static/tests/lists/list_plugin.test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/website_sale/models/website_snippet_filter.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/common.py
  addons/website_sale/tests/test_website_sale_product_filters.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: staging.saas-17.4

#30995 Syncing from upstream odoo/odoo (staging.16.0)
  addons/hr_contract/models/resource.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/sale/models/sale_order_line.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
Labels: staging.16.0

#30996 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/auto_hide_menu.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/link_tools.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: staging.17.0

#30997 Syncing from upstream odoo/odoo (staging.18.0)
  addons/event_crm/models/crm_lead.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/iap_crm/models/crm_lead.py
  addons/l10n_fr_account/migrations/2.2/pre-migrate-add-bank-xmlid.py
  addons/l10n_in/data/template/account.fiscal.position-in.csv
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/models/template_in.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/product/models/product_template.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/web_tour/static/tests/tour_interactive.test.js
  addons/web_tour/static/tests/tour_service.test.js
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: staging.18.0

#30999 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/spreadsheet/static/src/list/plugins/list_core_plugin.js
  addons/spreadsheet/static/tests/lists/list_plugin_test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: tmp.saas-17.2

#31000 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/mass_mailing/static/src/scss/mass_mailing.wysiwyg.scss
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/app/models/data_service.js
  addons/point_of_sale/static/src/app/models/pos_order.js
  addons/point_of_sale/static/src/app/models/related_models.js
  addons/point_of_sale/static/src/app/navbar/closing_popup/closing_popup.js
  addons/point_of_sale/static/src/app/navbar/navbar.xml
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.js
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt/order_receipt.xml
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_loyalty/static/src/overrides/models/pos_order.js
  addons/pos_restaurant/models/pos_order.py
  addons/pos_restaurant/models/pos_restaurant.py
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_sale/models/sale_order.py
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/sale/models/account_move.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/spreadsheet/static/src/list/plugins/list_core_plugin.js
  addons/spreadsheet/static/tests/lists/list_plugin.test.js
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/wysiwyg/wysiwyg_iframe.js
  addons/website_sale/models/website_snippet_filter.py
  addons/website_sale/tests/__init__.py
  addons/website_sale/tests/common.py
  addons/website_sale/tests/test_website_sale_product_filters.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: tmp.saas-17.4

#31002 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/hr_contract/models/resource.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/sale/models/sale_order_line.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
Labels: tmp.16.0

#31003 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/models/account_report.py
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/js/content/auto_hide_menu.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/link_tools.js
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: tmp.17.0

#31004 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/event_crm/models/crm_lead.py
  addons/hr_expense/static/src/views/expense_line_widget.js
  addons/hw_posbox_homepage/controllers/homepage.py
  addons/hw_posbox_homepage/static/src/app/Homepage.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/HandlerDialog.js
  addons/hw_posbox_homepage/static/src/app/components/dialog/UpdateDialog.js
  addons/iap_crm/models/crm_lead.py
  addons/l10n_fr_account/migrations/2.2/pre-migrate-add-bank-xmlid.py
  addons/l10n_in/data/template/account.fiscal.position-in.csv
  addons/l10n_in/i18n/l10n_in.pot
  addons/l10n_in/models/template_in.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/views/pos_order_view.xml
  addons/product/models/product_template.py
  addons/sale/models/sale_order.py
  addons/sale_management/tests/test_sale_order.py
  addons/web_editor/static/src/js/backend/html_field.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/web_tour/static/tests/tour_interactive.test.js
  addons/web_tour/static/tests/tour_service.test.js
  addons/website_crm_iap_reveal/models/crm_reveal_rule.py
  odoo/addons/base/data/res_lang_data.xml
  odoo/addons/base/static/img/lang_flags/lang_ar.png
  odoo/addons/base/static/img/lang_flags/lang_ca.png
Labels: tmp.18.0

#31013 [bt#30676]
  addons/auth_oauth/controllers/main.py
  addons/auth_oauth/models/res_users.py
  addons/web_editor/models/assets.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_config_parameter.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/models/ir_ui_menu.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_api.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/api.py
  odoo/fields.py
  odoo/models.py
Labels: 13.0.project_mi_582_test

#31016 Fix conflict from cherry-picking
  odoo/addons/test_new_api/tests/test_new_fields.py
Labels: 13.0.project_mi_582_test

#31017 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/sale_purchase/models/sale_order_line.py
  addons/sale_purchase/tests/test_sale_purchase.py
  addons/web/controllers/home.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: 16.0

#31018 Syncing from upstream odoo/odoo (17.0)
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_cl/models/l10n_latam_document_type.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/sale/models/sale_order_line.py
  addons/website_livechat/views/website_livechat.xml
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/views/res_partner_views.xml
  odoo/tools/pdf/__init__.py
Labels: 17.0

#31021 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_report.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/event/static/src/client_action/event_barcode.js
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_pos_tbai/__manifest__.py
  addons/l10n_es_pos_tbai/models/__init__.py
  addons/l10n_es_pos_tbai/models/account_move.py
  addons/l10n_es_pos_tbai/models/pos_order.py
  addons/l10n_es_pos_tbai/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/l10n_es_pos_tbai/static/src/overrides/models/order.js
  addons/l10n_es_pos_tbai/static/tests/tours/spanish_tbai_pos_tour.js
  addons/l10n_es_pos_tbai/tests/__init__.py
  addons/l10n_es_pos_tbai/tests/test_frontend.py
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/pos_self_order/models/ir_http.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/web/tooling/_eslintignore
  addons/website/static/src/js/content/auto_hide_menu.js
  addons/website_payment/static/src/snippets/s_donation/000.js
Labels: saas-17.2

#31025 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_report.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/event/static/src/client_action/event_barcode.js
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_pos_tbai/__manifest__.py
  addons/l10n_es_pos_tbai/models/__init__.py
  addons/l10n_es_pos_tbai/models/account_move.py
  addons/l10n_es_pos_tbai/models/pos_order.py
  addons/l10n_es_pos_tbai/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/l10n_es_pos_tbai/static/src/overrides/models/order.js
  addons/l10n_es_pos_tbai/static/tests/tours/spanish_tbai_pos_tour.js
  addons/l10n_es_pos_tbai/tests/__init__.py
  addons/l10n_es_pos_tbai/tests/test_frontend.py
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/pos_self_order/models/ir_http.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/web/tooling/_eslintignore
  addons/website/static/src/js/content/auto_hide_menu.js
  addons/website_payment/static/src/snippets/s_donation/000.js
Labels: staging.saas-17.2

#31032 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_report.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/event/static/src/client_action/event_barcode.js
  addons/hr_holidays/models/resource.py
  addons/hr_holidays/tests/test_global_leaves.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_ch/tests/test_ch_qr_code.py
  addons/l10n_es_pos_tbai/__manifest__.py
  addons/l10n_es_pos_tbai/models/__init__.py
  addons/l10n_es_pos_tbai/models/account_move.py
  addons/l10n_es_pos_tbai/models/pos_order.py
  addons/l10n_es_pos_tbai/static/src/overrides/components/ticket_screen/ticket_screen.js
  addons/l10n_es_pos_tbai/static/src/overrides/models/order.js
  addons/l10n_es_pos_tbai/static/tests/tours/spanish_tbai_pos_tour.js
  addons/l10n_es_pos_tbai/tests/__init__.py
  addons/l10n_es_pos_tbai/tests/test_frontend.py
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/pos_self_order/models/ir_http.py
  addons/product/models/product_product.py
  addons/product/models/product_template.py
  addons/product/tests/test_variants.py
  addons/web/tooling/_eslintignore
  addons/website/static/src/js/content/auto_hide_menu.js
  addons/website_payment/static/src/snippets/s_donation/000.js
Labels: tmp.saas-17.2

#31015 [bt#30676]
  addons/auth_oauth/controllers/main.py
  addons/auth_oauth/models/res_users.py
  addons/web_editor/models/assets.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_config_parameter.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/models/ir_ui_menu.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_api.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/api.py
  odoo/fields.py
  odoo/models.py
Labels: 13.0.project_ms_592

#31038 Fix missing import from cherry-picking
  odoo/addons/base/models/assetsbundle.py
Labels: 13.0.project_ms_592

#31039 Fix conflicts from cherry-picking
  odoo/fields.py
Labels: 13.0.project_mi_582_test

#31014 [bt#30676]
  addons/auth_oauth/controllers/main.py
  addons/auth_oauth/models/res_users.py
  addons/web_editor/models/assets.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/ir_actions_report.py
  odoo/addons/base/models/ir_config_parameter.py
  odoo/addons/base/models/ir_cron.py
  odoo/addons/base/models/ir_default.py
  odoo/addons/base/models/ir_logging.py
  odoo/addons/base/models/ir_mail_server.py
  odoo/addons/base/models/ir_model.py
  odoo/addons/base/models/ir_module.py
  odoo/addons/base/models/ir_property.py
  odoo/addons/base/models/ir_rule.py
  odoo/addons/base/models/ir_sequence.py
  odoo/addons/base/models/ir_ui_menu.py
  odoo/addons/base/models/ir_ui_view.py
  odoo/addons/base/models/res_partner.py
  odoo/addons/base/models/res_users.py
  odoo/addons/base/tests/test_api.py
  odoo/addons/test_new_api/models/test_new_api.py
  odoo/addons/test_new_api/security/ir.model.access.csv
  odoo/addons/test_new_api/tests/test_new_fields.py
  odoo/api.py
  odoo/fields.py
  odoo/models.py
Labels: 13.0.project_mi_582

#31040 Syncing from upstream odoo/odoo (16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/models/mail_mail.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_average_price.py
  addons/stock/models/stock_orderpoint.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: 16.0

#31041 Syncing from upstream odoo/odoo (17.0)
  addons/account/tests/test_product.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/purchase_stock/views/purchase_views.xml
  addons/stock/models/stock_orderpoint.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_payment/static/src/snippets/s_donation/000.js
Labels: 17.0

#31044 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/im_livechat/static/src/core/common/message_patch.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/stock/models/stock_orderpoint.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_livechat/views/website_livechat.xml
  odoo/tools/pdf/__init__.py
Labels: saas-17.2

#31045 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/i18n/es_PA.po
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/im_livechat/static/src/core/common/message_patch.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/settings_model_patch.js
  addons/mail/static/tests/discuss/call/call.test.js
  addons/mail/static/tests/mock_server/mock_models/res_users_settings_volumes.js
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/utils/input_popups/number_popup.xml
  addons/pos_hr/static/src/app/select_cashier_mixin.js
  addons/pos_loyalty/static/src/overrides/components/payment_screen/payment_screen.js
  addons/pos_self_order/models/ir_http.py
  addons/pos_self_order/models/product_product.py
  addons/sale/i18n/es_PA.po
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/core/popover/popover.js
  addons/web/static/tests/core/popover/popover_service.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_livechat/views/website_livechat.xml
  odoo/addons/base/data/res_country_data.xml
  odoo/tools/pdf/__init__.py
Labels: saas-17.4

#31048 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/im_livechat/static/src/core/common/message_patch.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/stock/models/stock_orderpoint.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_livechat/views/website_livechat.xml
  odoo/tools/pdf/__init__.py
Labels: staging.saas-17.2

#31049 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/i18n/es_PA.po
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/im_livechat/static/src/core/common/message_patch.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/settings_model_patch.js
  addons/mail/static/tests/discuss/call/call.test.js
  addons/mail/static/tests/mock_server/mock_models/res_users_settings_volumes.js
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/utils/input_popups/number_popup.xml
  addons/pos_hr/static/src/app/select_cashier_mixin.js
  addons/pos_loyalty/static/src/overrides/components/payment_screen/payment_screen.js
  addons/pos_self_order/models/ir_http.py
  addons/pos_self_order/models/product_product.py
  addons/sale/i18n/es_PA.po
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/core/popover/popover.js
  addons/web/static/tests/core/popover/popover_service.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_livechat/views/website_livechat.xml
  odoo/addons/base/data/res_country_data.xml
  odoo/tools/pdf/__init__.py
Labels: staging.saas-17.4

#31051 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/models/mail_mail.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_average_price.py
  addons/stock/models/stock_orderpoint.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: staging.16.0

#31055 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/im_livechat/static/src/core/common/message_patch.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/stock/models/stock_orderpoint.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_livechat/views/website_livechat.xml
  odoo/tools/pdf/__init__.py
Labels: tmp.saas-17.2

#31056 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/i18n/es_PA.po
  addons/account/models/account_move.py
  addons/base_vat/models/res_partner.py
  addons/hw_drivers/iot_handlers/drivers/PrinterDriver_W.py
  addons/im_livechat/static/src/core/common/message_patch.js
  addons/l10n_eu_oss/models/eu_tax_map.py
  addons/mail/static/src/discuss/call/common/call_context_menu.xml
  addons/mail/static/src/discuss/call/common/settings_model_patch.js
  addons/mail/static/tests/discuss/call/call.test.js
  addons/mail/static/tests/mock_server/mock_models/res_users_settings_volumes.js
  addons/mrp_subcontracting_dropshipping/tests/test_anglo_saxon_valuation.py
  addons/point_of_sale/models/pos_config.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/models/product.py
  addons/point_of_sale/static/src/app/screens/payment_screen/payment_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/utils/input_popups/number_popup.xml
  addons/pos_hr/static/src/app/select_cashier_mixin.js
  addons/pos_loyalty/static/src/overrides/components/payment_screen/payment_screen.js
  addons/pos_self_order/models/ir_http.py
  addons/pos_self_order/models/product_product.py
  addons/sale/i18n/es_PA.po
  addons/stock/models/stock_orderpoint.py
  addons/web/static/src/core/datetime/datetimepicker_service.js
  addons/web/static/src/core/popover/popover.js
  addons/web/static/tests/core/popover/popover_service.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_livechat/tests/test_livechat_basic_flow.py
  addons/website_livechat/views/website_livechat.xml
  odoo/addons/base/data/res_country_data.xml
  odoo/tools/pdf/__init__.py
Labels: tmp.saas-17.4

#31058 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/mail/models/mail_mail.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/static/src/js/Screens/TicketScreen/TicketScreen.js
  addons/purchase_stock/models/stock_move.py
  addons/purchase_stock/tests/test_average_price.py
  addons/stock/models/stock_orderpoint.py
  odoo/addons/base/tests/test_mail.py
  odoo/tools/mail.py
Labels: tmp.16.0

#31062 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_product.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/hr_contract/models/resource.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_self_order/models/res_config_settings.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/purchase_stock/views/purchase_views.xml
  addons/sale/models/sale_order_line.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/legacy/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/models/res_currency.py
  odoo/http.py
Labels: saas-17.2

#31063 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_account.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/hr_contract/models/resource.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/l10n_be/i18n/de.po
  addons/l10n_be/i18n/fr.po
  addons/l10n_be/i18n/l10n_be.pot
  addons/l10n_be/i18n/nl.po
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/purchase_stock/views/purchase_views.xml
  addons/sale/models/sale_order_line.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/http.py
Labels: saas-17.4

#31066 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_product.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/hr_contract/models/resource.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_self_order/models/res_config_settings.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/purchase_stock/views/purchase_views.xml
  addons/sale/models/sale_order_line.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/legacy/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/models/res_currency.py
  odoo/http.py
Labels: staging.saas-17.2

#31067 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_account.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/hr_contract/models/resource.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/l10n_be/i18n/de.po
  addons/l10n_be/i18n/fr.po
  addons/l10n_be/i18n/l10n_be.pot
  addons/l10n_be/i18n/nl.po
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/purchase_stock/views/purchase_views.xml
  addons/sale/models/sale_order_line.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/models/res_currency.py
  odoo/http.py
Labels: staging.saas-17.4

#31069 Syncing from upstream odoo/odoo (staging.16.0)
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/project/models/project.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_dynamic_group_list.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/sale/models/account_move_line.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
Labels: staging.16.0

#31070 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/hr_contract/models/resource.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/helpers/mock_server/models/res_partner.js
  addons/hr_holidays/static/tests/helpers/model_definitions_setup.js
  addons/hr_holidays/static/tests/im_status_tests.js
  addons/hr_holidays_attendance/models/hr_leave_type.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/helpers/mock_server/models/res_partner.js
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/product/models/product_product.py
  addons/product/models/product_supplierinfo.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/purchase/models/product.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/addons/base/models/res_currency.py
  odoo/http.py
Labels: staging.17.0

#31073 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_account.py
  addons/account/models/account_move.py
  addons/account/tests/test_product.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/hr_contract/models/resource.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_self_order/models/res_config_settings.py
  addons/pos_stripe/models/pos_payment_method.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/purchase_stock/views/purchase_views.xml
  addons/sale/models/sale_order_line.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/legacy/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/addons/base/models/res_currency.py
  odoo/http.py
Labels: tmp.saas-17.2

#31074 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_account.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/auth_signup/static/src/js/reset_password.js
  addons/hr_contract/models/resource.py
  addons/hr_expense/models/res_config_settings.py
  addons/hr_expense/views/res_config_settings_views.xml
  addons/l10n_be/i18n/de.po
  addons/l10n_be/i18n/fr.po
  addons/l10n_be/i18n/l10n_be.pot
  addons/l10n_be/i18n/nl.po
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/point_of_sale/views/pos_ticket_view.xml
  addons/pos_restaurant_stripe/static/src/overrides/models/payment_stripe.js
  addons/pos_stripe/models/pos_payment_method.py
  addons/purchase_stock/views/purchase_views.xml
  addons/sale/models/sale_order_line.py
  addons/web_editor/static/src/js/editor/odoo-editor/src/OdooEditor.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/link_tools.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
  odoo/http.py
Labels: tmp.saas-17.4

#31076 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_es/data/account_fiscal_position_template_data.xml
  addons/project/models/project.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_dynamic_group_list.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
Labels: tmp.16.0

#31077 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py
  addons/hr_contract/models/resource.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/helpers/mock_server/models/res_partner.js
  addons/hr_holidays/static/tests/helpers/model_definitions_setup.js
  addons/hr_holidays/static/tests/im_status_tests.js
  addons/hr_holidays_attendance/models/hr_leave_type.py
  addons/hw_drivers/controllers/driver.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/helpers/mock_server/models/res_partner.js
  addons/point_of_sale/static/src/app/generic_components/product_card/product_card.scss
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/product/models/product_product.py
  addons/product/models/product_supplierinfo.py
  addons/project/models/project_project.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/purchase/models/product.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/views/form/form_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/addons/base/models/res_currency.py
  odoo/http.py
Labels: tmp.17.0

#31083 Syncing from upstream odoo/odoo (saas-17.2)
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/hw_drivers/tools/helpers.py
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.scss
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.xml
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.scss
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/legacy/views/calendar/calendar_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: saas-17.2

#31084 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/ir_module.py
  addons/event/static/src/client_action/event_barcode.js
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project_task.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_hu_edi/models/account_move.py
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/pos_loyalty/static/src/overrides/models/data_service_options.js
  addons/project/controllers/portal.py
  addons/project/models/project_project.py
  addons/project/tests/test_portal.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/project_timesheet_holidays/i18n/project_timesheet_holidays.pot
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/views/form/auto_save.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/tools/translate.py
Labels: saas-17.4

#31087 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/hw_drivers/tools/helpers.py
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.scss
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.xml
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.scss
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/legacy/views/calendar/calendar_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: staging.saas-17.2

#31091 Syncing from upstream odoo/odoo (staging.17.0)
  addons/calendar/models/calendar_alarm_manager.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_procurement.py
  addons/mrp/tests/test_replenish.py
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  odoo/tools/pdf/__init__.py
  odoo/tools/pdf/_pypdf.py
Labels: staging.17.0

#31094 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/hw_drivers/tools/helpers.py
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.scss
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.xml
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.scss
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/legacy/views/calendar/calendar_view_tests.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
Labels: tmp.saas-17.2

#31095 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/ir_module.py
  addons/event/static/src/client_action/event_barcode.js
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project_task.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/pos_loyalty/static/src/overrides/models/data_service_options.js
  addons/project/controllers/portal.py
  addons/project/models/project_project.py
  addons/project/tests/test_portal.py
  addons/project/tests/test_project_stage_multicompany.py
  addons/project_timesheet_holidays/i18n/project_timesheet_holidays.pot
  addons/project_timesheet_holidays/models/account_analytic.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/views/form/auto_save.test.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/utils/utils.js
  addons/web_editor/static/src/scss/web_editor.common.scss
  odoo/tools/translate.py
Labels: tmp.saas-17.4

#31097 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/point_of_sale/static/src/js/models.js
  addons/pos_loyalty/static/src/js/Loyalty.js
  addons/pos_loyalty/static/src/tours/PosLoyaltyTour.js
  addons/sale/models/account_move_line.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/http.py
Labels: tmp.16.0

#31098 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/calendar/models/calendar_alarm_manager.py
  addons/hw_drivers/tools/helpers.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_in_pos/static/src/overrides/models/order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_procurement.py
  addons/mrp/tests/test_replenish.py
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view_tests.js
  odoo/tools/pdf/__init__.py
  odoo/tools/pdf/_pypdf.py
Labels: tmp.17.0

#31099 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_bank_statement.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/security/ir.model.access.csv
  addons/account/tests/test_product.py
  addons/bus/static/src/components/bus_connection_alert.js
  addons/bus/static/src/components/bus_connection_alert.scss
  addons/bus/static/src/components/bus_connection_alert.xml
  addons/bus/static/src/services/bus_monitoring_service.js
  addons/bus/static/tests/bus_connection_alert.test.js
  addons/bus/static/tests/bus_monitoring_service.test.js
  addons/event/static/src/client_action/event_barcode.js
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/hw_drivers/tools/helpers.py
  addons/im_livechat/models/discuss_channel.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_jo_edi/tests/jo_edi_common.py
  addons/l10n_vn/migrations/17.0.2.0.2/post-migration.py
  addons/mail/static/src/discuss/call/common/peer_to_peer.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_smp.py
  addons/mrp/wizard/mrp_batch_produce.py
  addons/point_of_sale/static/src/app/generic_components/list_container/list_container.js
  addons/point_of_sale/static/src/app/screens/product_screen/product_screen.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/static/tests/tours/utils/product_screen_util.js
  addons/point_of_sale/tests/test_frontend.py
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/systemd/system/odoo.service
  addons/pos_self_order/static/src/app/self_order_service.js
  addons/project/controllers/portal.py
  addons/project/tests/test_portal.py
  addons/sale/models/sale_order_line.py
  addons/stock_account/models/stock_lot.py
  addons/website/static/tests/tours/snippet_translation.js
  addons/website_sale/models/sale_order_line.py
  addons/website_sale/tests/test_website_sale_pricelist.py
Labels: tmp.18.0

#31100 Syncing from upstream odoo/odoo (16.0)
  addons/crm/models/crm_lead.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/web/static/lib/owl/owl.js
Labels: 16.0

#31101 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move_line.py
  addons/account/views/account_move_views.xml
  addons/crm/models/crm_lead.py
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/views/stock_move_line_views.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/test_new_api/tests/test_properties.py
Labels: 17.0

#31104 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_bank_statement_line.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_replenish.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/website_project/controllers/main.py
  odoo/addons/base/models/ir_actions.py
  odoo/tools/pdf/_pypdf.py
Labels: saas-17.2

#31105 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/l10n_be_pos_sale/__init__.py
  addons/l10n_be_pos_sale/i18n/l10n_be_pos_sale.pot
  addons/l10n_be_pos_sale/models/__init__.py
  addons/l10n_be_pos_sale/models/pos_session.py
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in_pos/static/src/overrides/models/pos_order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_replenish.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mercado_pago/static/src/app/pos_store.js
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_sale/models/sale_order_line.py
  odoo/addons/base/models/ir_actions.py
  odoo/tools/pdf/_pypdf.py
Labels: saas-17.4

#31106 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_code_mapping.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/ir_module.py
  addons/bus/static/src/components/bus_connection_alert.js
  addons/bus/static/src/components/bus_connection_alert.scss
  addons/bus/static/src/components/bus_connection_alert.xml
  addons/bus/static/src/services/bus_monitoring_service.js
  addons/bus/static/tests/bus_connection_alert.test.js
  addons/bus/static/tests/bus_monitoring_service.test.js
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/l10n_ar_pos/models/pos_config.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_es_pos/models/pos_config.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/l10n_pe_pos/models/pos_config.py
  addons/mail/static/src/core/common/attachment_model.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_smp.py
  addons/mrp/wizard/mrp_batch_produce.py
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.scss
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.xml
  addons/point_of_sale/static/src/app/components/navbar/navbar.scss
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/project_todo/static/tests/tours/project_task_activities_split.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_stock/views/purchase_views.xml
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_lot.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  odoo/tools/pdf/_pypdf.py
Labels: saas-18.1

#31108 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_bank_statement_line.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_replenish.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/website_project/controllers/main.py
  odoo/addons/base/models/ir_actions.py
  odoo/tools/pdf/_pypdf.py
Labels: staging.saas-17.2

#31109 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/l10n_be_pos_sale/__init__.py
  addons/l10n_be_pos_sale/i18n/l10n_be_pos_sale.pot
  addons/l10n_be_pos_sale/models/__init__.py
  addons/l10n_be_pos_sale/models/pos_session.py
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in_pos/static/src/overrides/models/pos_order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_replenish.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mercado_pago/static/src/app/pos_store.js
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_sale/models/sale_order_line.py
  odoo/addons/base/models/ir_actions.py
  odoo/tools/pdf/_pypdf.py
Labels: staging.saas-17.4

#31111 Syncing from upstream odoo/odoo (staging.16.0)
  addons/crm/models/crm_lead.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/web/static/lib/owl/owl.js
Labels: staging.16.0

#31112 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move_line.py
  addons/account/views/account_move_views.xml
  addons/crm/models/crm_lead.py
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/views/stock_move_line_views.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/test_new_api/tests/test_properties.py
Labels: staging.17.0

#31115 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_bank_statement_line.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_replenish.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/website_project/controllers/main.py
  odoo/addons/base/models/ir_actions.py
  odoo/tools/pdf/_pypdf.py
Labels: tmp.saas-17.2

#31116 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_move.py
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon.patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/l10n_be_pos_sale/__init__.py
  addons/l10n_be_pos_sale/i18n/l10n_be_pos_sale.pot
  addons/l10n_be_pos_sale/models/__init__.py
  addons/l10n_be_pos_sale/models/pos_session.py
  addons/l10n_be_pos_sale/static/src/js/PaymentScreen.js
  addons/l10n_be_pos_sale/static/tests/tours/l10n_be_pos_sale_tour.js
  addons/l10n_be_pos_sale/tests/test_l10n_be_pos_sale.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_in_pos/static/src/overrides/models/pos_order.js
  addons/l10n_in_pos/static/src/overrides/store/pos_store.js
  addons/l10n_sa_edi/models/account_move.py
  addons/l10n_sa_edi/tests/test_edi_zatca.py
  addons/l10n_sa_edi/tests/test_files/downpayment_invoice.xml
  addons/l10n_sa_edi/tests/test_files/final_invoice.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/mrp/models/stock_rule.py
  addons/mrp/tests/test_replenish.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_mercado_pago/static/src/app/pos_store.js
  addons/pos_viva_wallet/i18n/pos_viva_wallet.pot
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock_account/models/account_move.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/commands/shiftEnter.js
  addons/web_editor/static/src/js/editor/odoo-editor/test/spec/editor.test.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/tests/tours/edit_link_popover.js
  addons/website_sale/models/sale_order_line.py
  odoo/addons/base/models/ir_actions.py
  odoo/tools/pdf/_pypdf.py
Labels: tmp.saas-17.4

#31117 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/models/account_bank_statement_line.py
  addons/account/models/account_code_mapping.py
  addons/account/models/account_move.py
  addons/account/models/account_move_line.py
  addons/account/models/ir_module.py
  addons/bus/static/src/components/bus_connection_alert.js
  addons/bus/static/src/components/bus_connection_alert.scss
  addons/bus/static/src/components/bus_connection_alert.xml
  addons/bus/static/src/services/bus_monitoring_service.js
  addons/bus/static/tests/bus_connection_alert.test.js
  addons/bus/static/tests/bus_monitoring_service.test.js
  addons/calendar/models/calendar_alarm_manager.py
  addons/crm/models/crm_lead.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/gamification/tests/test_karma_tracking.py
  addons/google_address_autocomplete/static/src/address_autocomplete/google_address_autocomplete.js
  addons/google_address_autocomplete/static/src/address_autocomplete/google_address_autocomplete.xml
  addons/google_address_autocomplete/static/tests/google_address_autocomplete.test.js
  addons/l10n_ar_pos/models/pos_config.py
  addons/l10n_cz/models/account_move.py
  addons/l10n_cz/models/account_move_line.py
  addons/l10n_cz/tests/test_moves.py
  addons/l10n_cz/views/account_move_views.xml
  addons/l10n_es_pos/models/pos_config.py
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/l10n_hu_edi/models/account_move.py
  addons/l10n_my_edi/data/my_ubl_templates.xml
  addons/l10n_my_edi/models/account_edi_xml_ubl_my.py
  addons/l10n_my_edi/tests/test_file_generation.py
  addons/l10n_my_edi/views/res_partner_view.xml
  addons/l10n_my_ubl_pint/views/res_partner_view.xml
  addons/l10n_pe_pos/models/pos_config.py
  addons/mail/static/src/core/common/attachment_model.js
  addons/mail/static/src/discuss/call/common/rtc_service.js
  addons/mrp/tests/test_order.py
  addons/mrp/tests/test_smp.py
  addons/mrp/wizard/mrp_batch_produce.py
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.scss
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.xml
  addons/point_of_sale/static/src/app/components/navbar/navbar.scss
  addons/point_of_sale/static/src/app/screens/partner_list/partner_list.js
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/project_todo/static/tests/tours/project_task_activities_split.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/purchase_stock/views/purchase_views.xml
  addons/stock_account/models/account_move.py
  addons/stock_account/models/stock_lot.py
  addons/stock_account/tests/test_account_move.py
  addons/web/static/lib/owl/owl.js
  addons/website/tests/test_performance.py
  odoo/addons/base/security/base_security.xml
  odoo/tools/pdf/_pypdf.py
Labels: tmp.saas-18.1

#31118 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/crm/models/crm_lead.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/mass_mailing_crm/data/mass_mailing_demo.xml
  addons/web/static/lib/owl/owl.js
Labels: tmp.16.0

#31119 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move_line.py
  addons/account/views/account_move_views.xml
  addons/crm/models/crm_lead.py
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_gcc_invoice/views/report_invoice.xml
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase_requisition/tests/test_purchase_requisition.py
  addons/stock/views/stock_move_line_views.xml
  odoo/addons/base/models/ir_actions.py
  odoo/addons/test_new_api/tests/test_properties.py
Labels: tmp.17.0

#31123 Syncing from upstream odoo/odoo (master)
  addons/account/models/account_bank_statement_line.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/gamification/tests/test_karma_tracking.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon_patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/pos_mercado_pago/static/src/app/services/pos_store.js
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/test_sale_purchase_edi_ubl/__init__.py
  addons/test_sale_purchase_edi_ubl/__manifest__.py
  addons/test_sale_purchase_edi_ubl/tests/__init__.py
  addons/test_sale_purchase_edi_ubl/tests/test_order_ubl_bis3.py
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/website/tests/test_performance.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/security/base_security.xml
Labels: master

#31126 Syncing from upstream odoo/odoo (staging.master)
  addons/account/models/account_bank_statement_line.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/gamification/tests/test_karma_tracking.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon_patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/pos_mercado_pago/static/src/app/services/pos_store.js
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/test_sale_purchase_edi_ubl/__init__.py
  addons/test_sale_purchase_edi_ubl/__manifest__.py
  addons/test_sale_purchase_edi_ubl/tests/__init__.py
  addons/test_sale_purchase_edi_ubl/tests/test_order_ubl_bis3.py
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/website/tests/test_performance.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/security/base_security.xml
Labels: staging.master

#31129 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/account/models/account_bank_statement_line.py
  addons/pos_mercado_pago/static/src/app/services/pos_store.js
  addons/test_sale_purchase_edi_ubl/__init__.py
  addons/test_sale_purchase_edi_ubl/__manifest__.py
  addons/test_sale_purchase_edi_ubl/tests/__init__.py
  addons/test_sale_purchase_edi_ubl/tests/test_order_ubl_bis3.py
  addons/web/static/tests/_framework/module_set.hoot.js
Labels: staging.saas-18.1

#31130 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/account_bank_statement_line.py
  addons/pos_mercado_pago/static/src/app/pos_store.js
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/views/form/auto_save.test.js
  odoo/addons/base/models/ir_actions.py
Labels: staging.18.0

#31131 Syncing from upstream odoo/odoo (tmp.master)
  addons/account/models/account_bank_statement_line.py
  addons/crm/tests/test_crm_lead_convert_mass.py
  addons/gamification/tests/test_karma_tracking.py
  addons/hr_holidays/static/src/persona_model_patch.js
  addons/hr_holidays/static/src/thread_icon_patch.xml
  addons/hr_holidays/static/tests/im_status.test.js
  addons/hr_holidays/static/tests/mock_server/mock_models/res_partner.js
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/pos_mercado_pago/static/src/app/services/pos_store.js
  addons/project/models/project_task.py
  addons/project/tests/test_project_subtasks.py
  addons/test_sale_purchase_edi_ubl/__init__.py
  addons/test_sale_purchase_edi_ubl/__manifest__.py
  addons/test_sale_purchase_edi_ubl/tests/__init__.py
  addons/test_sale_purchase_edi_ubl/tests/test_order_ubl_bis3.py
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/website/tests/test_performance.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/security/base_security.xml
Labels: tmp.master

#31133 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_bank_statement_line.py
  addons/mail/models/discuss/discuss_channel.py
  addons/mail/models/discuss/res_partner.py
  addons/mail/models/discuss/res_users.py
  addons/mail/models/res_partner.py
  addons/mail/static/src/core/common/@types/models.d.ts
  addons/mail/static/src/core/common/message.xml
  addons/mail/static/src/core/common/persona_model.js
  addons/mail/static/src/core/common/res_groups_model.js
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/common/suggestion_service.js
  addons/mail/static/src/core/common/thread_model.js
  addons/mail/static/tests/mock_server/mock_models/discuss_channel.js
  addons/mail/static/tests/mock_server/mock_models/res_partner.js
  addons/mail/static/tests/suggestion/suggestion.test.js
  addons/pos_mercado_pago/static/src/app/pos_store.js
  addons/test_discuss_full/tests/test_performance.py
  addons/test_import_export/tests/test_export.py
  addons/web/controllers/export.py
  addons/web/static/src/model/relational_model/record.js
  addons/web/static/tests/_framework/module_set.hoot.js
  addons/web/static/tests/views/form/auto_save.test.js
  odoo/addons/base/models/ir_actions.py
Labels: tmp.18.0

#31134 Syncing from upstream odoo/odoo (18.0)
  odoo/addons/base/models/res_lang.py
  odoo/tools/misc.py
Labels: 18.0

#31136 Syncing from upstream odoo/odoo (saas-17.2)
  odoo/addons/base/models/res_lang.py
  odoo/tools/misc.py
Labels: saas-17.2

#31137 Syncing from upstream odoo/odoo (saas-17.4)
  odoo/addons/base/models/res_lang.py
  odoo/tools/misc.py
Labels: saas-17.4

#31138 Syncing from upstream odoo/odoo (saas-18.1)
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/messaging_menu_patch.js
  addons/mail/static/src/core/web/messaging_menu_patch.xml
  addons/mail/static/tests/messaging_menu/messaging_menu.test.js
  odoo/addons/base/models/res_lang.py
  odoo/tools/misc.py
Labels: saas-18.1

#31148 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move_line.py
  addons/l10n_es_edi_tbai/views/account_move_view.xml
  addons/l10n_es_edi_tbai_multi_refund/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/__manifest__.py
  addons/l10n_es_edi_tbai_multi_refund/data/template_LROE_bizkaia.xml
  addons/l10n_es_edi_tbai_multi_refund/i18n/es.po
  addons/l10n_es_edi_tbai_multi_refund/i18n/l10n_es_edi_tbai_multi_refund.pot
  addons/l10n_es_edi_tbai_multi_refund/models/__init__.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_edi_format.py
  addons/l10n_es_edi_tbai_multi_refund/models/account_move.py
  addons/l10n_es_edi_tbai_multi_refund/views/account_move_view.xml
  addons/l10n_sa/__manifest__.py
  addons/l10n_sa/data/report_paperformat_data.xml
  addons/l10n_sa/demo/demo_company.xml
  addons/l10n_sa/views/report_invoice.xml
  addons/l10n_sa_edi/views/report_invoice.xml
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/point_of_sale/models/pos_session.py
  addons/product/models/product_template.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/tools.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
Labels: 16.0

#31149 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet_account/i18n/spreadsheet_account.pot
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: 17.0

#31152 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move_line.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/models/models.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/product/models/product_product.py
  addons/product/models/product_supplierinfo.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase/models/product.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/stock/views/stock_move_line_views.xml
  addons/website_sale_loyalty/controllers/__init__.py
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/test_new_api/tests/test_properties.py
Labels: saas-17.2

#31153 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_tax.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/crm/static/src/js/tours/crm.js
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/models/models.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/product/models/product_product.py
  addons/product/models/product_supplierinfo.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase/models/product.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.scss
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.xml
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.scss
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/stock/views/stock_move_line_views.xml
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/test_new_api/tests/test_properties.py
Labels: saas-17.4

#31160 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/product/models/product_template.py
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet_account/i18n/spreadsheet_account.pot
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: staging.17.0

#31163 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move_line.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/hr_holidays/views/hr_leave_type_views.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/models/models.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/product/models/product_product.py
  addons/product/models/product_supplierinfo.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase/models/product.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/stock/views/stock_move_line_views.xml
  addons/website_sale_loyalty/controllers/__init__.py
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/tools/misc.py
Labels: tmp.saas-17.2

#31164 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_tax.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/crm/static/src/js/tours/crm.js
  addons/data_recycle/views/data_recycle_model_views.xml
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/models/models.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/product/models/product_product.py
  addons/product/models/product_supplierinfo.py
  addons/project_todo/static/src/views/todo_form/todo_form_renderer.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_button.js
  addons/project_todo/static/src/views/todo_form/todo_form_status_bar_buttons.xml
  addons/project_todo/static/src/views/todo_form/todo_form_view.js
  addons/purchase/models/product.py
  addons/purchase/models/purchase_order_line.py
  addons/purchase/tests/test_purchase.py
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.scss
  addons/resource_mail/static/src/views/fields/many2many_avatar_resource/many2many_avatar_resource_field.xml
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.js
  addons/resource_mail/static/src/views/fields/many2one_avatar_resource/many2one_avatar_resource_field.scss
  addons/sale/tests/test_sale_order_discount.py
  addons/sale/wizard/sale_order_discount.py
  addons/stock/views/stock_move_line_views.xml
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/models/res_lang.py
  odoo/addons/test_new_api/tests/test_properties.py
  odoo/tools/misc.py
Labels: tmp.saas-17.4

#31167 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account_peppol/models/account_edi_proxy_user.py
  addons/account_peppol/tools/demo_utils.py
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/mail/static/src/core/common/notification_permission_service.js
  addons/mail/static/src/core/web/messaging_menu.js
  addons/mass_mailing_crm/demo/mailing_mailing.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/screens/ticket_screen/ticket_screen.js
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet_account/i18n/spreadsheet_account.pot
  addons/spreadsheet_account/static/src/accounting_functions.js
  addons/website_sale_loyalty/controllers/main.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: tmp.17.0

#31169 Syncing from upstream odoo/odoo (16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/auth_totp/tests/test_totp.py
  addons/event/i18n/event.pot
  addons/event/models/event_event.py
  addons/hr_holidays/models/res_users.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/purchase/static/src/js/tours/purchase.js
  addons/repair/models/account_move.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/product_templates.xml
  addons/stock_account/models/account_move.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/systray_items/website_switcher.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/controllers/rpc.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/fields.py
  odoo/http.py
Labels: 16.0

#31170 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account/static/src/components/document_state/document_state_field.scss
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_jp/models/template_jp.py
  addons/l10n_ro_efactura/models/account_move.py
  addons/l10n_ro_efactura/models/ciusro_document.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product/models/product_template.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_base_automation/tests/test_flow.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tools.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
Labels: 17.0

#31171 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/views/account_payment_view.xml
  addons/hr_expense/static/tests/tours/expense_form_in_sheet_tours.js
  addons/html_editor/static/src/main/table/table_selection.scss
  addons/html_editor/static/tests/table/selection.test.js
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/store_service_patch.js
  addons/mail/static/src/discuss/call/common/call_participant_card.scss
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.xml
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/utils/use_idle_timer.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_hr/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/src/overrides/models/data_service_options.js
  addons/pos_restaurant/static/src/overrides/components/navbar/navbar.js
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/project/models/project_task.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_line_views.xml
  addons/web/static/src/core/macro.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_tour/__manifest__.py
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/skip_website_configurator.js
  addons/website/tools.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: 18.0

#31173 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/views/mail_activity_plan_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/product/models/product_template.py
  addons/website/tools.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
  odoo/tools/pdf/__init__.py
Labels: saas-17.2

#31174 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/account_move_views.xml
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/report/project_report.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/utils/order_change.js
  addons/point_of_sale/static/src/app/navbar/navbar.js
  addons/point_of_sale/static/src/app/navbar/navbar.xml
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_restaurant/static/src/app/product_screen/order_summary/order_summary.js
  addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/tests/tours/floor_screen_tour.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/static/tests/tours/refund_tour.js
  addons/pos_restaurant/static/tests/tours/split_bill_screen_tour.js
  addons/pos_restaurant/static/tests/tours/tip_screen_tour.js
  addons/product/models/product_template.py
  addons/project/models/project_task.py
  addons/website/tools.py
  addons/website_sale_loyalty/controllers/__init__.py
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: saas-17.4

#31175 Syncing from upstream odoo/odoo (saas-18.1)
  addons/account/models/account_payment.py
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/test_taxes_tax_totals_summary.py
  addons/account/views/account_payment_view.xml
  addons/hr_expense/static/tests/tours/expense_form_in_sheet_tours.js
  addons/html_editor/static/src/main/table/table_selection.scss
  addons/html_editor/static/tests/table/selection.test.js
  addons/im_livechat/models/im_livechat_channel.py
  addons/im_livechat/static/src/embed/common/chatbot/chatbot_model.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/discuss/call/common/call_participant_card.scss
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/tests/common.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.xml
  addons/project/models/project_task.py
  addons/project/tests/__init__.py
  addons/project/tests/test_project_base.py
  addons/project/tests/test_project_flow.py
  addons/project/tests/test_project_mail_features.py
  addons/purchase/models/purchase_order_line.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_flow.py
  addons/test_mail/tests/test_mail_push.py
  addons/web/static/src/core/macro.js
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/xml/add_snippet_dialog.xml
  addons/web_tour/__manifest__.py
  addons/web_tour/static/src/tour_service/tour_automatic.js
  addons/web_tour/static/src/tour_service/tour_step_automatic.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/skip_website_configurator.js
  addons/website/tools.py
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_flow.js
  addons/website_slides/static/tests/tours/slides_course_reviews.js
Labels: saas-18.1

#31177 Syncing from upstream odoo/odoo (staging.saas-17.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/views/mail_activity_plan_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/product/models/product_template.py
  addons/website/tools.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
  odoo/tools/pdf/__init__.py
Labels: staging.saas-17.2

#31178 Syncing from upstream odoo/odoo (staging.saas-17.4)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/account_move_views.xml
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/report/project_report.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/utils/order_change.js
  addons/point_of_sale/static/src/app/navbar/navbar.js
  addons/point_of_sale/static/src/app/navbar/navbar.xml
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_restaurant/static/src/app/product_screen/order_summary/order_summary.js
  addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/tests/tours/floor_screen_tour.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/static/tests/tours/refund_tour.js
  addons/pos_restaurant/static/tests/tours/split_bill_screen_tour.js
  addons/pos_restaurant/static/tests/tours/tip_screen_tour.js
  addons/product/models/product_template.py
  addons/project/models/project_task.py
  addons/website/tools.py
  addons/website_sale_loyalty/controllers/__init__.py
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: staging.saas-17.4

#31179 Syncing from upstream odoo/odoo (staging.saas-18.1)
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/test_taxes_tax_totals_summary.py
  addons/account/views/account_payment_view.xml
  addons/hr_expense/static/tests/tours/expense_form_in_sheet_tours.js
  addons/html_editor/static/src/main/table/table_selection.scss
  addons/html_editor/static/tests/table/selection.test.js
  addons/im_livechat/models/im_livechat_channel.py
  addons/im_livechat/static/src/embed/common/chatbot/chatbot_model.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/discuss/call/common/call_participant_card.scss
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/tests/common.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.xml
  addons/project/models/project_task.py
  addons/project/tests/__init__.py
  addons/project/tests/test_project_base.py
  addons/project/tests/test_project_flow.py
  addons/project/tests/test_project_mail_features.py
  addons/purchase/models/purchase_order_line.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_flow.py
  addons/test_mail/tests/test_mail_push.py
  addons/web/static/src/core/macro.js
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/xml/add_snippet_dialog.xml
  addons/web_tour/__manifest__.py
  addons/web_tour/static/src/tour_service/tour_automatic.js
  addons/web_tour/static/src/tour_service/tour_step_automatic.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/skip_website_configurator.js
  addons/website/tools.py
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_flow.js
  addons/website_slides/static/tests/tours/slides_course_reviews.js
Labels: staging.saas-18.1

#31180 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/auth_totp/tests/test_totp.py
  addons/event/i18n/event.pot
  addons/event/models/event_event.py
  addons/hr_holidays/models/res_users.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/purchase/static/src/js/tours/purchase.js
  addons/repair/models/account_move.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/product_templates.xml
  addons/stock_account/models/account_move.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/systray_items/website_switcher.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/controllers/rpc.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/fields.py
  odoo/http.py
Labels: staging.16.0

#31182 Syncing from upstream odoo/odoo (staging.18.0)
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/views/account_payment_view.xml
  addons/hr_expense/static/tests/tours/expense_form_in_sheet_tours.js
  addons/html_editor/static/src/main/table/table_selection.scss
  addons/html_editor/static/tests/table/selection.test.js
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/store_service_patch.js
  addons/mail/static/src/discuss/call/common/call_participant_card.scss
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.xml
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/utils/use_idle_timer.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_hr/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/src/overrides/models/data_service_options.js
  addons/pos_restaurant/static/src/overrides/components/navbar/navbar.js
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/project/models/project_task.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_line_views.xml
  addons/web/static/src/core/macro.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_tour/__manifest__.py
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/skip_website_configurator.js
  addons/website/tools.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: staging.18.0

#31184 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/views/mail_activity_plan_views.xml
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/store/models.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/product/models/product_template.py
  addons/website/tools.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
  odoo/tools/pdf/__init__.py
Labels: tmp.saas-17.2

#31185 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_move_line.py
  addons/account/tests/test_account_move_in_invoice.py
  addons/account/views/account_move_views.xml
  addons/hr_timesheet/i18n/hr_timesheet.pot
  addons/hr_timesheet/models/project_task.py
  addons/hr_timesheet/report/project_report.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/utils/order_change.js
  addons/point_of_sale/static/src/app/navbar/navbar.js
  addons/point_of_sale/static/src/app/navbar/navbar.xml
  addons/point_of_sale/static/src/app/screens/receipt_screen/receipt_screen.js
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/pos_restaurant/static/src/app/product_screen/order_summary/order_summary.js
  addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/pos_restaurant/static/tests/tours/floor_screen_tour.js
  addons/pos_restaurant/static/tests/tours/pos_restaurant_tour.js
  addons/pos_restaurant/static/tests/tours/refund_tour.js
  addons/pos_restaurant/static/tests/tours/split_bill_screen_tour.js
  addons/pos_restaurant/static/tests/tours/tip_screen_tour.js
  addons/product/models/product_template.py
  addons/project/models/project_task.py
  addons/website/tools.py
  addons/website_sale_loyalty/controllers/__init__.py
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: tmp.saas-17.4

#31186 Syncing from upstream odoo/odoo (tmp.saas-18.1)
  addons/account/models/account_payment.py
  addons/account/models/account_tax.py
  addons/account/static/src/helpers/account_tax.js
  addons/account/tests/test_taxes_tax_totals_summary.py
  addons/account/views/account_payment_view.xml
  addons/hr_expense/static/tests/tours/expense_form_in_sheet_tours.js
  addons/html_editor/static/src/main/table/table_selection.scss
  addons/html_editor/static/tests/table/selection.test.js
  addons/im_livechat/models/im_livechat_channel.py
  addons/im_livechat/static/src/embed/common/chatbot/chatbot_model.js
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_es_edi_facturae/models/account_move.py
  addons/l10n_es_edi_sii/models/account_edi_format.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/discuss/call/common/call_participant_card.scss
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/tests/common.py
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/static/src/app/components/category_selector/category_selector.xml
  addons/project/models/project_task.py
  addons/project/tests/__init__.py
  addons/project/tests/test_project_base.py
  addons/project/tests/test_project_flow.py
  addons/project/tests/test_project_mail_features.py
  addons/purchase/models/purchase_order_line.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/test_mail/data/subtype_data.xml
  addons/test_mail/models/mail_test_ticket.py
  addons/test_mail/security/ir.model.access.csv
  addons/test_mail/security/test_mail_security.xml
  addons/test_mail/tests/test_mail_flow.py
  addons/test_mail/tests/test_mail_push.py
  addons/web/static/src/core/macro.js
  addons/web/static/src/views/calendar/calendar_model.js
  addons/web/static/tests/views/calendar/calendar_view.test.js
  addons/web_editor/static/src/js/editor/add_snippet_dialog.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_editor/static/src/js/editor/snippets.editor.js
  addons/web_editor/static/src/xml/add_snippet_dialog.xml
  addons/web_tour/__manifest__.py
  addons/web_tour/static/src/tour_service/tour_automatic.js
  addons/web_tour/static/src/tour_service/tour_step_automatic.js
  addons/web_tour/static/tests/tour_automatic.test.js
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/skip_website_configurator.js
  addons/website/tools.py
  addons/website_livechat/static/tests/tours/website_livechat_chatbot_flow.js
  addons/website_slides/static/tests/tours/slides_course_reviews.js
Labels: tmp.saas-18.1

#31187 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/auth_totp/tests/test_totp.py
  addons/event/i18n/event.pot
  addons/event/models/event_event.py
  addons/hr_holidays/models/res_users.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_es_edi_tbai/models/account_edi_format.py
  addons/purchase/static/src/js/tours/purchase.js
  addons/repair/models/account_move.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/sale_stock/models/account_move.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/stock/report/product_templates.xml
  addons/stock_account/models/account_move.py
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/systray_items/website_switcher.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/controllers/rpc.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_rpc/tests/test_error.py
  odoo/fields.py
  odoo/http.py
Labels: tmp.16.0

#31188 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account/static/src/components/document_state/document_state_field.scss
  addons/l10n_ch/models/ir_actions_report.py
  addons/l10n_jp/models/template_jp.py
  addons/l10n_ro_efactura/models/account_move.py
  addons/l10n_ro_efactura/models/ciusro_document.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/product/models/product_template.py
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/test_base_automation/tests/test_flow.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/tests/tours/media_dialog.js
  addons/website/tools.py
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
Labels: tmp.17.0

#31189 Syncing from upstream odoo/odoo (tmp.18.0)
  addons/account/models/account_move_line.py
  addons/account/models/account_payment.py
  addons/account/views/account_payment_view.xml
  addons/hr_expense/static/tests/tours/expense_form_in_sheet_tours.js
  addons/html_editor/static/src/main/table/table_selection.scss
  addons/html_editor/static/tests/table/selection.test.js
  addons/im_livechat/models/im_livechat_channel.py
  addons/l10n_ch/models/ir_actions_report.py
  addons/loyalty/i18n/loyalty.pot
  addons/loyalty/models/loyalty_card.py
  addons/mail/static/src/core/common/store_service.js
  addons/mail/static/src/core/web/store_service_patch.js
  addons/mail/static/src/discuss/call/common/call_participant_card.scss
  addons/mail/static/src/discuss/call/common/call_participant_card.xml
  addons/mail/static/src/discuss/core/common/store_service_patch.js
  addons/point_of_sale/models/pos_order.py
  addons/point_of_sale/models/pos_payment.py
  addons/point_of_sale/models/pos_session.py
  addons/point_of_sale/static/src/app/models/product_product.js
  addons/point_of_sale/static/src/app/pos_app.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.js
  addons/point_of_sale/static/src/app/screens/saver_screen/saver_screen.xml
  addons/point_of_sale/static/src/app/store/pos_store.js
  addons/point_of_sale/static/src/app/utils/use_idle_timer.js
  addons/point_of_sale/static/tests/tours/product_screen_tour.js
  addons/point_of_sale/tests/test_frontend.py
  addons/pos_hr/static/src/overrides/models/pos_store.js
  addons/pos_loyalty/static/src/overrides/models/data_service_options.js
  addons/pos_restaurant/static/src/overrides/components/navbar/navbar.js
  addons/pos_restaurant/static/src/overrides/models/pos_store.js
  addons/project/models/project_task.py
  addons/sale_loyalty/models/sale_order.py
  addons/sale_loyalty/tests/test_program_numbers.py
  addons/stock/models/stock_picking.py
  addons/stock/tests/test_move.py
  addons/stock/views/stock_move_line_views.xml
  addons/web/static/src/core/macro.js
  addons/web_editor/static/src/js/editor/odoo-editor/src/style.scss
  addons/web_tour/__manifest__.py
  addons/website/static/tests/tours/editable_root_as_custom_snippet.js
  addons/website/static/tests/tours/skip_website_configurator.js
  addons/website/tools.py
  addons/website_slides/static/tests/tours/slides_course_reviews.js
  odoo/addons/base/models/res_currency.py
  odoo/addons/base/tests/test_qweb_field.py
  odoo/addons/base/views/ir_qweb_widget_templates.xml
Labels: tmp.18.0

#31190 Syncing from upstream odoo/odoo (16.0)
  addons/auth_ldap/models/res_company_ldap.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/graph/graph_controller.js
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph_view_tests.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/controllers.py
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_static.py
  odoo/addons/test_http/tests/test_web_server.py
  odoo/http.py
  odoo/tests/common.py
Labels: 16.0

#31191 Syncing from upstream odoo/odoo (17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/hr_holidays/models/res_users.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/l10n_be/data/template/account.tax-be.csv
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/sale/models/account_move_line.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/report/report_stockinventory.xml
  addons/stock/tests/test_multicompany.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/systray_items/website_switcher.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_http/controllers.py
  odoo/fields.py
  odoo/http.py
  odoo/tests/common.py
Labels: 17.0

#31192 Syncing from upstream odoo/odoo (18.0)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account/static/src/components/document_state/document_state_field.scss
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/hr/static/src/components/avatar_card_resource/avatar_card_resource_popover.xml
  addons/hr/static/src/components/background_image/background_image.scss
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_holidays/models/res_users.py
  addons/l10n_it/__manifest__.py
  addons/l10n_it/data/account_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_annual_tax_report_data.xml
  addons/l10n_it/data/tax_report/account_monthly_tax_report_data.xml
  addons/l10n_it/data/tax_report/annual_report_sections/va.xml
  addons/l10n_it/data/tax_report/annual_report_sections/ve.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vf.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vh.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vj.xml
  addons/l10n_it/data/tax_report/annual_report_sections/vl.xml
  addons/l10n_it/i18n/it.po
  addons/l10n_it/i18n/l10n_it.pot
  addons/l10n_it/migrations/0.7/post-map_carryover_to_new_report.py
  addons/l10n_it/models/account_report.py
  addons/l10n_ro_edi/models/account_move.py
  addons/l10n_ro_edi/models/ciusro_document.py
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/mail/static/src/core/common/composer.js
  addons/mail/static/src/discuss/web/avatar_card/avatar_card_popover.dark.scss
  addons/mail/static/src/discuss/web/avatar_card/avatar_card_popover.scss
  addons/mail/static/src/discuss/web/avatar_card/avatar_card_popover.xml
  addons/mail/static/tests/tours/mail_composer_test_tour.js
  addons/mail/views/mail_activity_plan_views.xml
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/project/controllers/portal.py
  addons/purchase_stock/report/purchase_report_templates.xml
  addons/resource_mail/static/src/components/avatar_card_resource/avatar_card_resource_popover.xml
  addons/stock/tests/test_move2.py
  addons/stock/wizard/stock_picking_return.py
  addons/stock/wizard/stock_picking_return_views.xml
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/core/dropzone/dropzone_hook.js
  addons/web_editor/static/src/js/editor/snippets.options.js
  addons/website/static/src/snippets/s_image_gallery/002.scss
  addons/website/static/tests/tours/media_dialog.js
  addons/website_sale/static/src/js/checkout.js
  addons/website_sale/views/templates.xml
  addons/website_sale_collect/static/src/js/checkout.js
  addons/website_sale_loyalty/controllers/__init__.py
  addons/website_sale_loyalty/controllers/payment.py
  addons/website_sale_loyalty/i18n/website_sale_loyalty.pot
  addons/website_sale_loyalty/tests/__init__.py
  addons/website_sale_loyalty/tests/test_shop_loyalty_payment.py
  addons/website_sale_mondialrelay/static/src/js/checkout.js
  doc/cla/corporate/initos.md
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
Labels: 18.0

#31194 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/hr_holidays/models/res_users.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/test_base_automation/tests/test_flow.py
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
  odoo/tests/common.py
Labels: saas-17.2

#31195 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_holidays/models/res_users.py
  addons/html_builder/static/src/builder/options/image_gallery_option.js
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/mail/views/mail_activity_plan_views.xml
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/website/controllers/form.py
  addons/website/i18n/website.pot
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_crm/tests/test_website_crm.py
  addons/website_hr_recruitment/controllers/main.py
  addons/website_project/controllers/main.py
  addons/website_project/i18n/website_project.pot
  addons/website_project/tests/__init__.py
  addons/website_project/tests/test_website_project.py
  doc/cla/corporate/initos.md
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
Labels: saas-17.4

#31197 Syncing from upstream odoo/odoo (staging.16.0)
  addons/auth_ldap/models/res_company_ldap.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/graph/graph_controller.js
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph_view_tests.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/controllers.py
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_static.py
  odoo/addons/test_http/tests/test_web_server.py
  odoo/http.py
  odoo/tests/common.py
Labels: staging.16.0

#31198 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/hr_holidays/models/res_users.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/l10n_be/data/template/account.tax-be.csv
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/sale/models/account_move_line.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/report/report_stockinventory.xml
  addons/stock/tests/test_multicompany.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/systray_items/website_switcher.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_http/controllers.py
  odoo/fields.py
  odoo/http.py
  odoo/tests/common.py
Labels: staging.17.0

#31201 Syncing from upstream odoo/odoo (tmp.saas-17.2)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/hr_holidays/models/res_users.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_sale/static/src/app/order_management_screen/sale_order_management_screen/sale_order_management_screen.js
  addons/pos_sale/static/tests/tours/PosSaleTour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/test_base_automation/tests/test_flow.py
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
  odoo/tests/common.py
Labels: tmp.saas-17.2

#31202 Syncing from upstream odoo/odoo (tmp.saas-17.4)
  addons/account/models/account_account_tag.py
  addons/account/models/ir_module.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/base_import_module/models/ir_module.py
  addons/base_import_module/tests/test_cloc.py
  addons/hr/views/mail_activity_plan_views.xml
  addons/hr_holidays/models/res_users.py
  addons/html_builder/static/src/builder/options/image_gallery_option.js
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/l10n_es/data/template/account.fiscal.position-es_common.csv
  addons/l10n_tr_nilvera/lib/nilvera_client.py
  addons/mail/views/mail_activity_plan_views.xml
  addons/point_of_sale/models/stock_picking.py
  addons/point_of_sale/tests/test_point_of_sale_flow.py
  addons/pos_restaurant/static/src/app/split_bill_screen/split_bill_screen.js
  addons/pos_viva_wallet/static/src/app/payment_viva_wallet.js
  addons/project/models/project_task.py
  addons/project/static/src/project_sharing/views/kanban/kanban_view.js
  addons/project/static/src/views/project_task_kanban/project_task_kanban_model.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.js
  addons/spreadsheet/static/src/o_spreadsheet/o_spreadsheet.xml
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/list/list_renderer.js
  addons/web/static/tests/views/form/form_view.test.js
  addons/website/controllers/form.py
  addons/website/i18n/website.pot
  addons/website_blog/static/src/scss/website_blog.scss
  addons/website_crm/tests/test_website_crm.py
  addons/website_hr_recruitment/controllers/main.py
  addons/website_project/controllers/main.py
  addons/website_project/i18n/website_project.pot
  addons/website_project/tests/__init__.py
  addons/website_project/tests/test_website_project.py
  doc/cla/corporate/initos.md
  odoo/addons/base/tests/test_translate.py
  odoo/fields.py
Labels: tmp.saas-17.4

#31204 Syncing from upstream odoo/odoo (tmp.16.0)
  addons/auth_ldap/models/res_company_ldap.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_order.py
  addons/point_of_sale/tools/posbox/configuration/posbox_update.sh
  addons/point_of_sale/tools/posbox/overwrite_after_init/usr/local/lib/python3.11/dist-packages/v4l2.py.iotpatch
  addons/point_of_sale/tools/posbox/overwrite_before_init/etc/init_posbox_image.sh
  addons/web/static/lib/owl/owl.js
  addons/web/static/src/views/graph/graph_controller.js
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph_view_tests.js
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/controllers.py
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_static.py
  odoo/addons/test_http/tests/test_web_server.py
  odoo/http.py
  odoo/tests/common.py
Labels: tmp.16.0

#31205 Syncing from upstream odoo/odoo (tmp.17.0)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/data/cii_22_templates.xml
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/hr_holidays/models/res_users.py
  addons/hw_drivers/driver.py
  addons/hw_drivers/interface.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/l10n_be/data/template/account.tax-be.csv
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workorder.py
  addons/mrp/tests/test_order.py
  addons/mrp_subcontracting_purchase/tests/test_mrp_subcontracting_purchase.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/sale/models/account_move_line.py
  addons/sale_expense/tests/test_reinvoice.py
  addons/spreadsheet_dashboard_purchase/data/files/vendors_dashboard.json
  addons/spreadsheet_dashboard_purchase_stock/data/files/purchase_dashboard.json
  addons/stock/models/stock_move.py
  addons/stock/models/stock_rule.py
  addons/stock/report/report_stockinventory.xml
  addons/stock/tests/test_multicompany.py
  addons/stock_landed_costs/models/stock_landed_cost.py
  addons/stock_landed_costs/tests/test_stock_landed_costs_rounding.py
  addons/web/controllers/home.py
  addons/web/static/lib/owl/owl.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website/static/src/client_actions/website_preview/website_preview.js
  addons/website/static/src/systray_items/website_switcher.js
  addons/website_blog/static/src/scss/website_blog.scss
  doc/cla/corporate/initos.md
  odoo/addons/base/models/ir_http.py
  odoo/addons/base/tests/test_translate.py
  odoo/addons/test_http/controllers.py
  odoo/fields.py
  odoo/http.py
  odoo/tests/common.py
Labels: tmp.17.0

#31207 Syncing from upstream odoo/odoo (16.0)
  addons/account/i18n/account.pot
  addons/account/wizard/accrued_orders.py
  addons/account_test/report/report_account_test.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/static/tests/tours/snippet_popup_add_remove.js
  addons/website_event_track/views/event_track_templates_agenda.xml
  addons/website_sale/models/product_product.py
  odoo/addons/base/tests/test_qweb_field.py
Labels: 16.0

#31208 Syncing from upstream odoo/odoo (17.0)
  addons/account/i18n/account.pot
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_peppol/i18n/account_peppol.pot
  addons/account_peppol/models/res_config_settings.py
  addons/account_peppol/static/src/components/res_config_settings_buttons/res_config_settings_buttons.js
  addons/account_peppol/static/src/components/res_config_settings_buttons/res_config_settings_buttons.xml
  addons/account_peppol/tests/test_peppol_participant.py
  addons/account_test/report/report_account_test.py
  addons/hr_attendance/models/res_company.py
  addons/hw_drivers/tools/helpers.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/web/static/src/views/graph/graph_controller.js
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/website_event_track/views/event_track_templates_agenda.xml
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_web_server.py
Labels: 17.0

#31211 Syncing from upstream odoo/odoo (saas-17.2)
  addons/account/i18n/account.pot
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_test/report/report_account_test.py
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/l10n_jp/models/template_jp.py
  addons/mrp/models/mrp_production.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/tests/test_order.py
  addons/project/controllers/portal.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/stock/report/report_stockinventory.xml
  addons/web/static/tests/legacy/core/dropdown_tests.js
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_event_track/views/event_track_templates_agenda.xml
  addons/website_slides/models/slide_slide.py
  addons/website_slides/tests/test_slide_channel.py
  odoo/addons/base/models/ir_http.py
  odoo/addons/test_http/controllers.py
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_web_server.py
  odoo/http.py
Labels: saas-17.2

#31212 Syncing from upstream odoo/odoo (saas-17.4)
  addons/account/models/account_move.py
  addons/account/tests/test_account_move_out_invoice.py
  addons/account_edi_ubl_cii/models/account_edi_common.py
  addons/account_test/report/report_account_test.py
  addons/base_import/static/src/import_model.js
  addons/base_import/static/tests/import_action_tests.js
  addons/html_builder/static/src/builder/options/image_gallery_option.js
  addons/hw_drivers/controllers/driver.py
  addons/hw_drivers/iot_handlers/drivers/KeyboardUSBDriver_L.py
  addons/l10n_jp/models/template_jp.py
  addons/mrp/models/mrp_unbuild.py
  addons/mrp/models/mrp_workcenter.py
  addons/mrp/tests/test_order.py
  addons/pos_mercado_pago/static/src/app/pos_store.js
  addons/pos_sale/static/src/overrides/models/pos_store.js
  addons/pos_sale/static/tests/tours/pos_sale_tour.js
  addons/pos_sale/tests/test_pos_sale_flow.py
  addons/project/controllers/portal.py
  addons/repair/tests/__init__.py
  addons/repair/tests/test_anglo_saxon_valuation.py
  addons/stock/report/report_stockinventory.xml
  addons/test_base_automation/tests/test_flow.py
  addons/web_editor/static/src/js/wysiwyg/wysiwyg.js
  addons/website_event_track/views/event_track_templates_agenda.xml
  odoo/addons/base/i18n/base.pot
  odoo/addons/base/models/ir_actions.py
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_web_server.py
  odoo/tests/common.py
Labels: saas-17.4

#31218 Syncing from upstream odoo/odoo (staging.16.0)
  addons/account/i18n/account.pot
  addons/account/wizard/accrued_orders.py
  addons/account_test/report/report_account_test.py
  addons/point_of_sale/tools/posbox/posbox_create_image.sh
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/web/static/src/views/fields/image/image_field.js
  addons/web/static/src/views/fields/image_url/image_url_field.js
  addons/website/static/src/snippets/s_popup/options.js
  addons/website/static/tests/tours/snippet_popup_add_remove.js
  addons/website_event_track/views/event_track_templates_agenda.xml
  addons/website_sale/models/product_product.py
  odoo/addons/base/tests/test_qweb_field.py
Labels: staging.16.0

#31219 Syncing from upstream odoo/odoo (staging.17.0)
  addons/account/i18n/account.pot
  addons/account/wizard/accrued_orders.py
  addons/account_edi_ubl_cii/models/account_edi_xml_ubl_20.py
  addons/account_peppol/i18n/account_peppol.pot
  addons/account_peppol/models/res_config_settings.py
  addons/account_peppol/static/src/components/res_config_settings_buttons/res_config_settings_buttons.js
  addons/account_peppol/static/src/components/res_config_settings_buttons/res_config_settings_buttons.xml
  addons/account_peppol/tests/test_peppol_participant.py
  addons/account_test/report/report_account_test.py
  addons/hr_attendance/models/res_company.py
  addons/hw_drivers/tools/helpers.py
  addons/mrp/models/mrp_production.py
  addons/mrp/tests/test_order.py
  addons/purchase/tests/test_accrued_purchase_orders.py
  addons/web/static/src/views/graph/graph_controller.js
  addons/web/static/src/views/graph/graph_controller.xml
  addons/web/static/src/views/graph/graph_model.js
  addons/web/static/tests/views/graph_view_tests.js
  addons/website_event_track/views/event_track_templates_agenda.xml
  odoo/addons/test_http/tests/test_echo_reply.py
  odoo/addons/test_http/tests/test_error.py
  odoo/addons/test_http/tests/test_greeting.py
  odoo/addons/test_http/tests/test_models.py
  odoo/addons/test_http/tests/test_session.py
  odoo/addons/test_http/tests/test_web_server.py
Labels: staging.17.0
